LLVM: llvm::UnreachableInst Class Reference
llvm::UnreachableInst Class Reference
UnreachableInst - This function has undefined behavior.
#include <Instructions.h>
Public Member Functions
void * operator new (size_t s)
Allocate a User with an operand pointer co-allocated.
UnreachableInst (LLVMContext &C, Instruction *InsertBefore=nullptr)
UnreachableInst (LLVMContext &C, BasicBlock *InsertAtEnd)
unsigned getNumSuccessors () const
Return the number of successors that this terminator has.
Static Public Member Functions
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
UnreachableInst * clone_impl () const override
Detailed Description
UnreachableInst - This function has undefined behavior.
In particular, the presence of this instruction indicates some higher level knowledge that the end of the block cannot be reached.
Definition at line 3473 of file Instructions.h.
Constructor & Destructor Documentation
UnreachableInst::UnreachableInst (LLVMContext & C, Instruction * InsertBefore = nullptr) [explicit]
Definition at line 679 of file Instructions.cpp.
Referenced by clone_impl().
UnreachableInst::UnreachableInst (LLVMContext & C, BasicBlock * InsertAtEnd) [explicit]
Definition at line 684 of file Instructions.cpp.
Member Function Documentation
static bool llvm::UnreachableInst::classof (const Instruction * I) [inline, static]
Reimplemented from llvm::TerminatorInst.
Definition at line 3489 of file Instructions.h.
References llvm::Instruction::getOpcode().
static bool llvm::UnreachableInst::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::TerminatorInst.
Definition at line 3492 of file Instructions.h.
UnreachableInst * UnreachableInst::clone_impl () const [override, protected, virtual]
Implements llvm::Instruction.
Definition at line 3630 of file Instructions.cpp.
References llvm::Value::getContext(), and UnreachableInst().
unsigned llvm::UnreachableInst::getNumSuccessors () const [inline]
Return the number of successors that this terminator has.
Reimplemented from llvm::TerminatorInst.
Definition at line 3486 of file Instructions.h.
void* llvm::UnreachableInst::operator new (size_t Size) [inline]
Allocate a User with an operand pointer co-allocated.
This is used for subclasses which need to allocate a variable number of operands, ie, 'hung off uses'.
Reimplemented from llvm::User.
Definition at line 3480 of file Instructions.h.
References llvm::User::operator new().
The documentation for this class was generated from the following files:
Instructions.h
Instructions.cpp