LLVM: llvm::cl::generic_parser_base Class Reference
llvm::cl::generic_parser_base Class Reference
#include <CommandLine.h>
Classes
class GenericOptionInfo
Public Member Functions
generic_parser_base (Option &O)
virtual ~generic_parser_base ()
virtual unsigned getNumOptions () const =0
virtual const char * getOption (unsigned N) const =0
virtual const char * getDescription (unsigned N) const =0
virtual size_t getOptionWidth (const Option &O) const
virtual const GenericOptionValue & getOptionValue (unsigned N) const =0
virtual void printOptionInfo (const Option &O, size_t GlobalWidth) const
void printGenericOptionDiff (const Option &O, const GenericOptionValue &V, const GenericOptionValue &Default, size_t GlobalWidth) const
template<class AnyOptionValue >
void printOptionDiff (const Option &O, const AnyOptionValue &V, const AnyOptionValue &Default, size_t GlobalWidth) const
void initialize ()
void getExtraOptionNames (SmallVectorImpl< const char * > &OptionNames)
enum ValueExpected getValueExpectedFlagDefault () const
unsigned findOption (const char *Name)
Protected Attributes
Option & Owner
Detailed Description
Definition at line 556 of file CommandLine.h.
Constructor & Destructor Documentation
llvm::cl::generic_parser_base::generic_parser_base (Option & O) [inline]
Definition at line 567 of file CommandLine.h.
virtual llvm::cl::generic_parser_base::~generic_parser_base () [inline, virtual]
Definition at line 569 of file CommandLine.h.
Member Function Documentation
unsigned generic_parser_base::findOption (const char * Name)
Definition at line 1309 of file CommandLine.cpp.
References getNumOptions(), and getOption().
Referenced by llvm::cl::parser< const PassInfo * >::addLiteralOption(), llvm::PassNameParser::passRegistered(), and llvm::cl::parser< const PassInfo * >::removeLiteralOption().
virtual const char* llvm::cl::generic_parser_base::getDescription (unsigned N) const [pure virtual]
Implemented in llvm::cl::parser< DataType >, llvm::cl::parser< RegistryClass::FunctionPassCtor >, llvm::cl::parser< const U::entry * >, and llvm::cl::parser< const PassInfo * >.
Referenced by printOptionInfo().
void llvm::cl::generic_parser_base::getExtraOptionNames (SmallVectorImpl< const char * > & OptionNames) [inline]
Definition at line 609 of file CommandLine.h.
References getNumOptions(), getOption(), llvm::cl::Option::hasArgStr(), Owner, and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
virtual unsigned llvm::cl::generic_parser_base::getNumOptions () const [pure virtual]
Implemented in llvm::cl::parser< DataType >, llvm::cl::parser< RegistryClass::FunctionPassCtor >, llvm::cl::parser< const U::entry * >, and llvm::cl::parser< const PassInfo * >.
Referenced by findOption(), getExtraOptionNames(), getOptionWidth(), printGenericOptionDiff(), and printOptionInfo().
virtual const char* llvm::cl::generic_parser_base::getOption (unsigned N) const [pure virtual]
Implemented in llvm::cl::parser< DataType >, llvm::cl::parser< RegistryClass::FunctionPassCtor >, llvm::cl::parser< const U::entry * >, and llvm::cl::parser< const PassInfo * >.
Referenced by findOption(), getExtraOptionNames(), getOptionWidth(), printGenericOptionDiff(), and printOptionInfo().
virtual const GenericOptionValue& llvm::cl::generic_parser_base::getOptionValue (unsigned N) const [pure virtual]
Implemented in llvm::cl::parser< DataType >, llvm::cl::parser< RegistryClass::FunctionPassCtor >, llvm::cl::parser< const U::entry * >, and llvm::cl::parser< const PassInfo * >.
Referenced by printGenericOptionDiff().
size_t generic_parser_base::getOptionWidth (const Option & O) const [virtual]
Definition at line 1320 of file CommandLine.cpp.
References llvm::cl::Option::ArgStr, getNumOptions(), getOption(), and llvm::cl::Option::hasArgStr().
enum ValueExpected llvm::cl::generic_parser_base::getValueExpectedFlagDefault () const [inline]
Definition at line 618 of file CommandLine.h.
References llvm::cl::Option::hasArgStr(), Owner, llvm::cl::ValueDisallowed, and llvm::cl::ValueRequired.
void llvm::cl::generic_parser_base::initialize () [inline]
Reimplemented in llvm::RegisterPassParser< RegistryClass >, and llvm::PassNameParser.
Definition at line 607 of file CommandLine.h.
Referenced by llvm::RegistryParser< T, U >::initialize().
void generic_parser_base::printGenericOptionDiff (const Option & O, const GenericOptionValue & V, const GenericOptionValue & Default, size_t GlobalWidth) const
Definition at line 1364 of file CommandLine.cpp.
References llvm::cl::Option::ArgStr, llvm::cl::GenericOptionValue::compare(), getNumOptions(), getOption(), getOptionValue(), llvm::raw_ostream::indent(), MaxOptWidth, and llvm::outs().
Referenced by printOptionDiff().
template<class AnyOptionValue > void llvm::cl::generic_parser_base::printOptionDiff (const Option & O, const AnyOptionValue & V, const AnyOptionValue & Default, size_t GlobalWidth) const [inline]
Definition at line 601 of file CommandLine.h.
References printGenericOptionDiff().
Referenced by llvm::cl::printOptionDiff().
void generic_parser_base::printOptionInfo (const Option & O, size_t GlobalWidth) const [virtual]
Reimplemented in llvm::PassNameParser.
Definition at line 1337 of file CommandLine.cpp.
References llvm::cl::Option::ArgStr, getDescription(), getNumOptions(), getOption(), llvm::cl::Option::hasArgStr(), llvm::cl::Option::HelpStr, llvm::raw_ostream::indent(), llvm::outs(), and printHelpStr().
Member Data Documentation
Option& llvm::cl::generic_parser_base::Owner [protected]
Definition at line 642 of file CommandLine.h.
Referenced by llvm::cl::parser< const PassInfo * >::addLiteralOption(), getExtraOptionNames(), getValueExpectedFlagDefault(), and llvm::cl::parser< const PassInfo * >::parse().
The documentation for this class was generated from the following files:
CommandLine.h
CommandLine.cpp