LLVM: llvm::ARMElfTargetObjectFile Class Reference
llvm::ARMElfTargetObjectFile Class Reference
#include <ARMTargetObjectFile.h>
Public Member Functions
ARMElfTargetObjectFile ()
void Initialize (MCContext &Ctx, const TargetMachine &TM) override
This method must be called before any actual lowering is done.
const MCExpr * getTTypeGlobalReference (const GlobalValue *GV, unsigned Encoding, Mangler &Mang, const TargetMachine &TM, MachineModuleInfo *MMI, MCStreamer &Streamer) const override
Return an MCExpr to use for a reference to the specified type info global variable from exception handling information.
const MCExpr * getDebugThreadLocalSymbol (const MCSymbol *Sym) const override
Describe a TLS variable address within debug info.
Protected Attributes
const MCSection * AttributesSection
Detailed Description
Definition at line 20 of file ARMTargetObjectFile.h.
Constructor & Destructor Documentation
llvm::ARMElfTargetObjectFile::ARMElfTargetObjectFile () [inline]
Definition at line 24 of file ARMTargetObjectFile.h.
Member Function Documentation
const MCExpr * ARMElfTargetObjectFile::getDebugThreadLocalSymbol (const MCSymbol * Sym) const [override, virtual]
Describe a TLS variable address within debug info.
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 58 of file ARMTargetObjectFile.cpp.
References llvm::MCSymbolRefExpr::create(), and llvm::MCSymbolRefExpr::VK_ARM_TLSLDO.
const MCExpr * ARMElfTargetObjectFile::getTTypeGlobalReference (const GlobalValue * GV, unsigned Encoding, Mangler & Mang, const TargetMachine & TM, MachineModuleInfo * MMI, MCStreamer & Streamer) const [override, virtual]
Return an MCExpr to use for a reference to the specified type info global variable from exception handling information.
Reimplemented from llvm::TargetLoweringObjectFileELF.
Definition at line 43 of file ARMTargetObjectFile.cpp.
References llvm::ARM, llvm::MCSymbolRefExpr::create(), llvm::dwarf::DW_EH_PE_absptr, llvm::MCAsmInfo::getExceptionHandlingType(), llvm::TargetMachine::getMCAsmInfo(), llvm::TargetMachine::getSymbol(), llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference(), and llvm::MCSymbolRefExpr::VK_ARM_TARGET2.
void ARMElfTargetObjectFile::Initialize (MCContext & ctx, const TargetMachine & TM) [override, virtual]
This method must be called before any actual lowering is done.
Initialize - this method must be called before any actual lowering is done.
This specifies the current context for codegen, and gives the lowering implementations a chance to set up their default sections.
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 28 of file ARMTargetObjectFile.cpp.
References llvm::TargetLoweringObjectFile::Initialize(), llvm::ELF::SHT_ARM_ATTRIBUTES, and llvm::SystemZISD::TM.
Member Data Documentation
const MCSection* llvm::ARMElfTargetObjectFile::AttributesSection [protected]
Definition at line 22 of file ARMTargetObjectFile.h.
The documentation for this class was generated from the following files:
ARMTargetObjectFile.h
ARMTargetObjectFile.cpp