LLVM: llvm::DIExpression::ExprOperand Class Reference
llvm::DIExpression::ExprOperand Class Reference
A lightweight wrapper around an expression operand.
#include <DebugInfoMetadata.h>
Public Member Functions
ExprOperand (const uint64_t *Op)
const uint64_t * get () const
uint64_t getOp () const
Get the operand code.
uint64_t getArg (unsigned I) const
Get an argument to the operand.
unsigned getNumArgs () const
unsigned getSize () const
Return the size of the operand.
Detailed Description
A lightweight wrapper around an expression operand.
TODO: Store arguments directly and change DIExpression to store a range of these.
Definition at line 1991 of file DebugInfoMetadata.h.
Constructor & Destructor Documentation
llvm::DIExpression::ExprOperand::ExprOperand (const uint64_t * Op) [inline, explicit]
Definition at line 1995 of file DebugInfoMetadata.h.
Member Function Documentation
const uint64_t* llvm::DIExpression::ExprOperand::get () const [inline]
Definition at line 1997 of file DebugInfoMetadata.h.
Referenced by llvm::DIExpression::expr_op_iterator::getBase().
uint64_t llvm::DIExpression::ExprOperand::getArg (unsigned I) const [inline]
Get an argument to the operand.
Never returns the operand itself.
Definition at line 2005 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfExpression::AddExpression().
unsigned llvm::DIExpression::ExprOperand::getNumArgs () const [inline]
Definition at line 2007 of file DebugInfoMetadata.h.
References getSize().
uint64_t llvm::DIExpression::ExprOperand::getOp () const [inline]
Get the operand code.
Definition at line 2000 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfExpression::AddExpression(), and getSize().
unsigned DIExpression::ExprOperand::getSize () const
Return the size of the operand.
Return the number of elements in the operand (1 + args).
Definition at line 477 of file DebugInfoMetadata.cpp.
References getOp().
Referenced by getNumArgs().
The documentation for this class was generated from the following files:
DebugInfoMetadata.h
DebugInfoMetadata.cpp