LLVM: llvm::NonLocalDepResult Class Reference
llvm::NonLocalDepResult Class Reference
NonLocalDepResult - This is a result from a NonLocal dependence query.
#include <MemoryDependenceAnalysis.h>
Public Member Functions
NonLocalDepResult (BasicBlock *bb, MemDepResult result, Value *address)
BasicBlock * getBB () const
void setResult (const MemDepResult &R, Value *Addr)
const MemDepResult & getResult () const
Value * getAddress () const
getAddress - Return the address of this pointer in this block.
Detailed Description
NonLocalDepResult - This is a result from a NonLocal dependence query.
For each BasicBlock (the BB entry) it keeps a MemDepResult and the (potentially phi translated) address that was live in the block.
Definition at line 215 of file MemoryDependenceAnalysis.h.
Constructor & Destructor Documentation
llvm::NonLocalDepResult::NonLocalDepResult (BasicBlock * bb, MemDepResult result, Value * address) [inline]
Definition at line 219 of file MemoryDependenceAnalysis.h.
Member Function Documentation
Value* llvm::NonLocalDepResult::getAddress () const [inline]
getAddress - Return the address of this pointer in this block.
This can be different than the address queried for the non-local result because of phi translation. This returns null if the address was not available in a block (i.e. because phi translation failed) or if this is a cached result and that address was deleted.
The address is always null for a non-local 'call' dependence.
Definition at line 239 of file MemoryDependenceAnalysis.h.
BasicBlock* llvm::NonLocalDepResult::getBB () const [inline]
Definition at line 223 of file MemoryDependenceAnalysis.h.
References llvm::NonLocalDepEntry::getBB().
const MemDepResult& llvm::NonLocalDepResult::getResult () const [inline]
Definition at line 230 of file MemoryDependenceAnalysis.h.
References llvm::NonLocalDepEntry::getResult().
void llvm::NonLocalDepResult::setResult (const MemDepResult & R, Value * Addr) [inline]
Definition at line 225 of file MemoryDependenceAnalysis.h.
References llvm::NonLocalDepEntry::setResult().
The documentation for this class was generated from the following file:
MemoryDependenceAnalysis.h