LLVM: llvm::NVPTXTargetMachine Class Reference
llvm::NVPTXTargetMachine Class Reference
NVPTXTargetMachine.
#include <NVPTXTargetMachine.h>
Public Member Functions
NVPTXTargetMachine (const Target &T, const Triple &TT, StringRef CPU, StringRef FS, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OP, bool is64bit)
~NVPTXTargetMachine () override
const NVPTXSubtarget * getSubtargetImpl (const Function &) const override
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
const NVPTXSubtarget * getSubtargetImpl () const
bool is64Bit () const
NVPTX::DrvInterface getDrvInterface () const
ManagedStringPool * getManagedStrPool () const
TargetPassConfig * createPassConfig (PassManagerBase &PM) override
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
bool addPassesToEmitMC (PassManagerBase &, MCContext *&, raw_pwrite_stream &, bool=true) override
Add passes to the specified pass manager to get machine code emitted with the MCJIT.
TargetLoweringObjectFile * getObjFileLowering () const override
TargetIRAnalysis getTargetIRAnalysis () override
Get a TargetIRAnalysis implementation for the target.
Detailed Description
NVPTXTargetMachine.
Definition at line 27 of file NVPTXTargetMachine.h.
Constructor & Destructor Documentation
NVPTXTargetMachine::NVPTXTargetMachine (const Target & T, const Triple & TT, StringRef CPU, StringRef FS, const TargetOptions & Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OP, bool is64bit)
Definition at line 88 of file NVPTXTargetMachine.cpp.
References llvm::NVPTX::CUDA, llvm::Triple::getOS(), llvm::LLVMTargetMachine::initAsmInfo(), and llvm::NVPTX::NVCL.
NVPTXTargetMachine::~NVPTXTargetMachine () [override]
Definition at line 104 of file NVPTXTargetMachine.cpp.
Member Function Documentation
bool llvm::NVPTXTargetMachine::addPassesToEmitMC (PassManagerBase & PM, MCContext *& Ctx, raw_pwrite_stream & Out, bool DisableVerify = true) [inline, override, virtual]
Add passes to the specified pass manager to get machine code emitted with the MCJIT.
addPassesToEmitMC - Add passes to the specified pass manager to get machine code emitted with the MCJIT.
This method returns true if machine code is not supported. It fills the MCContext Ctx pointer which can be used to build custom MCStreamer.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 56 of file NVPTXTargetMachine.h.
TargetPassConfig * NVPTXTargetMachine::createPassConfig (PassManagerBase & PM) [override, virtual]
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
createPassConfig - Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
Targets may override this to extend TargetPassConfig.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 145 of file NVPTXTargetMachine.cpp.
NVPTX::DrvInterface llvm::NVPTXTargetMachine::getDrvInterface () const [inline]
Definition at line 48 of file NVPTXTargetMachine.h.
Referenced by llvm::NVPTXSubtarget::hasImageHandles().
ManagedStringPool* llvm::NVPTXTargetMachine::getManagedStrPool () const [inline]
Definition at line 49 of file NVPTXTargetMachine.h.
Referenced by llvm::NVPTXTargetLowering::LowerCall().
TargetLoweringObjectFile* llvm::NVPTXTargetMachine::getObjFileLowering () const [inline, override, virtual]
Reimplemented from llvm::TargetMachine.
Definition at line 60 of file NVPTXTargetMachine.h.
const NVPTXSubtarget* llvm::NVPTXTargetMachine::getSubtargetImpl (const Function &) const [inline, override, virtual]
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
Reimplemented from llvm::TargetMachine.
Definition at line 43 of file NVPTXTargetMachine.h.
const NVPTXSubtarget* llvm::NVPTXTargetMachine::getSubtargetImpl () const [inline]
Definition at line 46 of file NVPTXTargetMachine.h.
TargetIRAnalysis NVPTXTargetMachine::getTargetIRAnalysis () [override, virtual]
Get a TargetIRAnalysis implementation for the target.
This analysis will produce a TTI result which uses the common code generator to answer queries about the IR.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 150 of file NVPTXTargetMachine.cpp.
bool llvm::NVPTXTargetMachine::is64Bit () const [inline]
Definition at line 47 of file NVPTXTargetMachine.h.
The documentation for this class was generated from the following files:
NVPTXTargetMachine.h
NVPTXTargetMachine.cpp