LLVM: llvm::DISubroutineType Class Reference
llvm::DISubroutineType Class Reference
Type array for a subprogram.
#include <DebugInfoMetadata.h>
Public Member Functions
DEFINE_MDNODE_GET (DISubroutineType,(unsigned Flags, DITypeRefArray TypeArray),(Flags, TypeArray)) DEFINE_MDNODE_GET(DISubroutineType
unsigned Metadata TypeArray
TempDISubroutineType clone () const
Create a (temporary) clone of this.
DITypeRefArray getTypeArray () const
Metadata * getRawTypeArray () const
Static Public Member Functions
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
Public Attributes
unsigned Flags
unsigned Metadata * TypeArray
unsigned Metadata Flags
Friends
class LLVMContextImpl
class MDNode
Detailed Description
Type array for a subprogram.
TODO: Detach from CompositeType, and fold the array of types in directly as operands.
Definition at line 921 of file DebugInfoMetadata.h.
Member Function Documentation
static bool llvm::DISubroutineType::classof (const Metadata * MD) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::DICompositeTypeBase.
Definition at line 960 of file DebugInfoMetadata.h.
References llvm::Metadata::DISubroutineTypeKind, and llvm::Metadata::getMetadataID().
unsigned Metadata TypeArray TempDISubroutineType llvm::DISubroutineType::clone () const [inline]
Create a (temporary) clone of this.
Reimplemented from llvm::DIType.
Definition at line 953 of file DebugInfoMetadata.h.
llvm::DISubroutineType::DEFINE_MDNODE_GET (DISubroutineType , (unsigned Flags, DITypeRefArray TypeArray) , (Flags, TypeArray))
Metadata* llvm::DISubroutineType::getRawTypeArray () const [inline]
Definition at line 958 of file DebugInfoMetadata.h.
References llvm::DICompositeTypeBase::getRawElements().
Referenced by getTypeArray(), and llvm::MDNodeKeyImpl< DISubroutineType >::isKeyOf().
DITypeRefArray llvm::DISubroutineType::getTypeArray () const [inline]
Definition at line 955 of file DebugInfoMetadata.h.
References getRawTypeArray().
Referenced by llvm::DwarfUnit::applySubprogramAttributes(), and WriteDISubroutineType().
Friends And Related Function Documentation
friend class LLVMContextImpl [friend]
Reimplemented from llvm::DINode.
Definition at line 922 of file DebugInfoMetadata.h.
friend class MDNode [friend]
Reimplemented from llvm::DINode.
Definition at line 923 of file DebugInfoMetadata.h.
Member Data Documentation
unsigned llvm::DISubroutineType::Flags
Reimplemented from llvm::DIType.
Definition at line 950 of file DebugInfoMetadata.h.
unsigned Metadata llvm::DISubroutineType::Flags
Reimplemented from llvm::DIType.
Definition at line 950 of file DebugInfoMetadata.h.
unsigned Metadata* llvm::DISubroutineType::TypeArray
Definition at line 950 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
DebugInfoMetadata.h
DebugInfoMetadata.cpp