LLVM: llvm::AArch64TargetMachine Class Reference
llvm::AArch64TargetMachine Class Reference
#include <AArch64TargetMachine.h>
Public Member Functions
AArch64TargetMachine (const Target &T, const Triple &TT, StringRef CPU, StringRef FS, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL, bool IsLittleEndian)
TargetMachine ctor - Create an AArch64 architecture model.
~AArch64TargetMachine () override
const AArch64Subtarget * getSubtargetImpl (const Function &F) const override
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
TargetPassConfig * createPassConfig (PassManagerBase &PM) override
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
TargetIRAnalysis getTargetIRAnalysis () override
Get the TargetIRAnalysis for this target.
TargetLoweringObjectFile * getObjFileLowering () const override
Protected Attributes
std::unique_ptr
< TargetLoweringObjectFile > TLOF
StringMap< std::unique_ptr
< AArch64Subtarget > > SubtargetMap
Detailed Description
Definition at line 24 of file AArch64TargetMachine.h.
Constructor & Destructor Documentation
AArch64TargetMachine::AArch64TargetMachine (const Target & T, const Triple & TT, StringRef CPU, StringRef FS, const TargetOptions & Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL, bool IsLittleEndian)
TargetMachine ctor - Create an AArch64 architecture model.
Definition at line 123 of file AArch64TargetMachine.cpp.
References llvm::LLVMTargetMachine::initAsmInfo().
AArch64TargetMachine::~AArch64TargetMachine () [override]
Definition at line 138 of file AArch64TargetMachine.cpp.
Member Function Documentation
TargetPassConfig * AArch64TargetMachine::createPassConfig (PassManagerBase & PM) [override, virtual]
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
createPassConfig - Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
Targets may override this to extend TargetPassConfig.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 211 of file AArch64TargetMachine.cpp.
TargetLoweringObjectFile* llvm::AArch64TargetMachine::getObjFileLowering () const [inline, override, virtual]
Reimplemented from llvm::TargetMachine.
Definition at line 44 of file AArch64TargetMachine.h.
References TLOF.
const AArch64Subtarget * AArch64TargetMachine::getSubtargetImpl (const Function &) const [override, virtual]
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
Reimplemented from llvm::TargetMachine.
Definition at line 141 of file AArch64TargetMachine.cpp.
References llvm::FS, llvm::Function::getFnAttribute(), llvm::Attribute::getValueAsString(), llvm::Attribute::hasAttribute(), I, llvm::Attribute::None, llvm::TargetMachine::resetTargetOptions(), llvm::StringRef::str(), SubtargetMap, llvm::TargetMachine::TargetCPU, llvm::TargetMachine::TargetFS, and llvm::TargetMachine::TargetTriple.
TargetIRAnalysis AArch64TargetMachine::getTargetIRAnalysis () [override, virtual]
Get the TargetIRAnalysis for this target.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 205 of file AArch64TargetMachine.cpp.
References F().
Member Data Documentation
StringMap<std::unique_ptr<AArch64Subtarget> > llvm::AArch64TargetMachine::SubtargetMap [mutable, protected]
Definition at line 27 of file AArch64TargetMachine.h.
Referenced by getSubtargetImpl().
std::unique_ptr<TargetLoweringObjectFile> llvm::AArch64TargetMachine::TLOF [protected]
Definition at line 26 of file AArch64TargetMachine.h.
Referenced by getObjFileLowering().
The documentation for this class was generated from the following files:
AArch64TargetMachine.h
AArch64TargetMachine.cpp