LLVM: llvm::MCSymbolELF Class Reference
llvm::MCSymbolELF Class Reference
#include <MCSymbolELF.h>
Public Member Functions
MCSymbolELF (const StringMapEntry< bool > *Name, bool isTemporary)
void setSize (const MCExpr *SS)
const MCExpr * getSize () const
void setVisibility (unsigned Visibility)
unsigned getVisibility () const
void setOther (unsigned Other)
unsigned getOther () const
void setType (unsigned Type) const
unsigned getType () const
void setBinding (unsigned Binding) const
unsigned getBinding () const
bool isBindingSet () const
void setIsWeakrefUsedInReloc () const
bool isWeakrefUsedInReloc () const
void setIsSignature () const
bool isSignature () const
Static Public Member Functions
static bool classof (const MCSymbol *S)
Detailed Description
Definition at line 15 of file MCSymbolELF.h.
Constructor & Destructor Documentation
llvm::MCSymbolELF::MCSymbolELF (const StringMapEntry< bool > * Name, bool isTemporary) [inline]
Definition at line 21 of file MCSymbolELF.h.
Member Function Documentation
static bool llvm::MCSymbolELF::classof (const MCSymbol * S) [inline, static]
Definition at line 47 of file MCSymbolELF.h.
References llvm::MCSymbol::isELF().
unsigned llvm::MCSymbolELF::getBinding () const
Definition at line 66 of file MCSymbolELF.cpp.
References llvm::MCSymbol::getFlags(), isBindingSet(), llvm::MCSymbol::isDefined(), isSignature(), llvm::MCSymbol::isUsedInReloc(), isWeakrefUsedInReloc(), llvm_unreachable, llvm::ELF::STB_GLOBAL, llvm::ELF::STB_GNU_UNIQUE, llvm::ELF::STB_LOCAL, and llvm::ELF::STB_WEAK.
Referenced by getMatchingLoType(), and isWeak().
unsigned llvm::MCSymbolELF::getOther () const
Definition at line 170 of file MCSymbolELF.cpp.
References llvm::MCSymbol::getFlags(), and Other.
const MCExpr* llvm::MCSymbolELF::getSize () const [inline]
Definition at line 25 of file MCSymbolELF.h.
unsigned llvm::MCSymbolELF::getType () const
Definition at line 125 of file MCSymbolELF.cpp.
References llvm::MCSymbol::getFlags(), llvm_unreachable, llvm::ELF::STT_COMMON, llvm::ELF::STT_FUNC, llvm::ELF::STT_GNU_IFUNC, llvm::ELF::STT_NOTYPE, llvm::ELF::STT_OBJECT, llvm::ELF::STT_SECTION, and llvm::ELF::STT_TLS.
Referenced by isWeak().
unsigned llvm::MCSymbolELF::getVisibility () const
Definition at line 155 of file MCSymbolELF.cpp.
References llvm::MCSymbol::getFlags(), llvm::ELF::STV_DEFAULT, llvm::ELF::STV_HIDDEN, llvm::ELF::STV_INTERNAL, llvm::ELF::STV_PROTECTED, and Visibility.
bool llvm::MCSymbolELF::isBindingSet () const
Definition at line 198 of file MCSymbolELF.cpp.
References llvm::MCSymbol::getFlags().
Referenced by getBinding().
bool llvm::MCSymbolELF::isSignature () const
Definition at line 189 of file MCSymbolELF.cpp.
References llvm::MCSymbol::getFlags().
Referenced by getBinding().
bool llvm::MCSymbolELF::isWeakrefUsedInReloc () const
Definition at line 180 of file MCSymbolELF.cpp.
References llvm::MCSymbol::getFlags().
Referenced by getBinding().
void llvm::MCSymbolELF::setBinding (unsigned Binding) const
Definition at line 43 of file MCSymbolELF.cpp.
References llvm::MCSymbol::getFlags(), llvm_unreachable, llvm::MCSymbol::setFlags(), llvm::ELF::STB_GLOBAL, llvm::ELF::STB_GNU_UNIQUE, llvm::ELF::STB_LOCAL, and llvm::ELF::STB_WEAK.
void llvm::MCSymbolELF::setIsSignature () const
Definition at line 184 of file MCSymbolELF.cpp.
References llvm::MCSymbol::getFlags(), and llvm::MCSymbol::setFlags().
void llvm::MCSymbolELF::setIsWeakrefUsedInReloc () const
Definition at line 175 of file MCSymbolELF.cpp.
References llvm::MCSymbol::getFlags(), and llvm::MCSymbol::setFlags().
void llvm::MCSymbolELF::setOther (unsigned Other)
Definition at line 162 of file MCSymbolELF.cpp.
References llvm::MCSymbol::getFlags(), and llvm::MCSymbol::setFlags().
void llvm::MCSymbolELF::setSize (const MCExpr * SS) [inline]
Definition at line 23 of file MCSymbolELF.h.
References llvm::SS.
Referenced by llvm::MCELFStreamer::emitELFSize().
void llvm::MCSymbolELF::setType (unsigned Type) const
Definition at line 94 of file MCSymbolELF.cpp.
References llvm::MCSymbol::getFlags(), llvm_unreachable, llvm::MCSymbol::setFlags(), llvm::ELF::STT_COMMON, llvm::ELF::STT_FUNC, llvm::ELF::STT_GNU_IFUNC, llvm::ELF::STT_NOTYPE, llvm::ELF::STT_OBJECT, llvm::ELF::STT_SECTION, and llvm::ELF::STT_TLS.
void llvm::MCSymbolELF::setVisibility (unsigned Visibility)
Definition at line 147 of file MCSymbolELF.cpp.
References llvm::MCSymbol::getFlags(), llvm::MCSymbol::setFlags(), llvm::ELF::STV_DEFAULT, llvm::ELF::STV_HIDDEN, llvm::ELF::STV_INTERNAL, and llvm::ELF::STV_PROTECTED.
The documentation for this class was generated from the following files:
MCSymbolELF.h
MCSymbolELF.cpp