LLVM: llvm::WinEH::UnwindEmitter Class Reference
llvm::WinEH::UnwindEmitter Class Reference
#include <MCWinEH.h>
Public Member Functions
virtual ~UnwindEmitter ()
virtual void Emit (MCStreamer &Streamer) const =0
virtual void EmitUnwindInfo (MCStreamer &Streamer, FrameInfo *FI) const =0
Static Public Member Functions
static MCSection * getPDataSection (const MCSymbol *Function, MCContext &Context)
static MCSection * getXDataSection (const MCSymbol *Function, MCContext &Context)
Detailed Description
Definition at line 66 of file MCWinEH.h.
Constructor & Destructor Documentation
virtual llvm::WinEH::UnwindEmitter::~UnwindEmitter () [inline, virtual]
Definition at line 73 of file MCWinEH.h.
Member Function Documentation
virtual void llvm::WinEH::UnwindEmitter::Emit (MCStreamer & Streamer) const [pure virtual]
Implemented in llvm::Win64EH::UnwindEmitter.
virtual void llvm::WinEH::UnwindEmitter::EmitUnwindInfo (MCStreamer & Streamer, FrameInfo * FI) const [pure virtual]
Implemented in llvm::Win64EH::UnwindEmitter.
MCSection * llvm::WinEH::UnwindEmitter::getPDataSection (const MCSymbol * Function, MCContext & Context) [static]
Definition at line 63 of file MCWinEH.cpp.
References llvm::MCContext::getObjectFileInfo(), llvm::MCObjectFileInfo::getPDataSection(), and llvm::WinEH::getUnwindInfoSection().
Referenced by llvm::Win64EH::UnwindEmitter::Emit().
MCSection * llvm::WinEH::UnwindEmitter::getXDataSection (const MCSymbol * Function, MCContext & Context) [static]
Definition at line 70 of file MCWinEH.cpp.
References llvm::MCContext::getObjectFileInfo(), llvm::WinEH::getUnwindInfoSection(), and llvm::MCObjectFileInfo::getXDataSection().
Referenced by llvm::Win64EH::UnwindEmitter::Emit(), llvm::Win64EH::UnwindEmitter::EmitUnwindInfo(), and llvm::WinException::endFunction().
The documentation for this class was generated from the following files:
MCWinEH.h
MCWinEH.cpp