LLVM: llvm::SystemZTargetLowering Class Reference
llvm::SystemZTargetLowering Class Reference
#include <SystemZISelLowering.h>
Public Member Functions
SystemZTargetLowering (const TargetMachine &TM, const SystemZSubtarget &STI)
MVT getScalarShiftAmountTy (EVT LHSTy) const override
MVT getVectorIdxTy () const override
Returns the type to be used for the index operand of: ISD::INSERT_VECTOR_ELT, ISD::EXTRACT_VECTOR_ELT, ISD::INSERT_SUBVECTOR, and ISD::EXTRACT_SUBVECTOR.
TargetLoweringBase::LegalizeTypeAction getPreferredVectorAction (EVT VT) const override
Return the preferred vector type legalization action.
EVT getSetCCResultType (LLVMContext &, EVT) const override
Return the ValueType of the result of SETCC operations.
bool isFMAFasterThanFMulAndFAdd (EVT VT) const override
Return true if an FMA operation is faster than a pair of fmul and fadd instructions.
bool isFPImmLegal (const APFloat &Imm, EVT VT) const override
Returns true if the target can instruction select the specified FP immediate natively.
bool isLegalICmpImmediate (int64_t Imm) const override
Return true if the specified immediate is legal icmp immediate, that is the target has icmp instructions which can compare a register against the immediate without having to materialize the immediate into a register.
bool isLegalAddImmediate (int64_t Imm) const override
Return true if the specified immediate is legal add immediate, that is the target has add instructions which can add a register with the immediate without having to materialize the immediate into a register.
bool isLegalAddressingMode (const AddrMode &AM, Type *Ty, unsigned AS) const override
Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
bool allowsMisalignedMemoryAccesses (EVT VT, unsigned AS, unsigned Align, bool *Fast) const override
Determine if the target supports unaligned memory accesses.
bool isTruncateFree (Type *, Type *) const override
Return true if it's free to truncate a value of type Ty1 to type Ty2.
bool isTruncateFree (EVT, EVT) const override
const char * getTargetNodeName (unsigned Opcode) const override
This method returns the name of a target specific DAG node.
std::pair< unsigned, const
TargetRegisterClass * > getRegForInlineAsmConstraint (const TargetRegisterInfo *TRI, const std::string &Constraint, MVT VT) const override
Given a physical register constraint (e.g.
TargetLowering::ConstraintType getConstraintType (const std::string &Constraint) const override
Given a constraint, return the type of constraint it is for this target.
TargetLowering::ConstraintWeight getSingleConstraintMatchWeight (AsmOperandInfo &info, const char *constraint) const override
Examine constraint string and operand type and determine a weight value.
void LowerAsmOperandForConstraint (SDValue Op, std::string &Constraint, std::vector< SDValue > &Ops, SelectionDAG &DAG) const override
Lower the specified operand into the Ops vector.
unsigned getInlineAsmMemConstraint (const std::string &ConstraintCode) const override
MachineBasicBlock * EmitInstrWithCustomInserter (MachineInstr *MI, MachineBasicBlock *BB) const override
This method should be implemented by targets that mark instructions with the 'usesCustomInserter' flag.
SDValue LowerOperation (SDValue Op, SelectionDAG &DAG) const override
This callback is invoked for operations that are unsupported by the target, which are registered to use 'custom' lowering, and whose defined values are all legal.
bool allowTruncateForTailCall (Type *, Type *) const override
Return true if a truncation from Ty1 to Ty2 is permitted when deciding whether a call is in tail position.
bool mayBeEmittedAsTailCall (CallInst *CI) const override
Return true if the target may be able emit the call instruction as a tail call.
SDValue LowerFormalArguments (SDValue Chain, CallingConv::ID CallConv, bool isVarArg, const SmallVectorImpl< ISD::InputArg > &Ins, SDLoc DL, SelectionDAG &DAG, SmallVectorImpl< SDValue > &InVals) const override
This hook must be implemented to lower the incoming (formal) arguments, described by the Ins array, into the specified DAG.
SDValue LowerCall (CallLoweringInfo &CLI, SmallVectorImpl< SDValue > &InVals) const override
This hook must be implemented to lower calls into the specified DAG.
SDValue LowerReturn (SDValue Chain, CallingConv::ID CallConv, bool IsVarArg, const SmallVectorImpl< ISD::OutputArg > &Outs, const SmallVectorImpl< SDValue > &OutVals, SDLoc DL, SelectionDAG &DAG) const override
This hook must be implemented to lower outgoing return values, described by the Outs array, into the specified DAG.
SDValue prepareVolatileOrAtomicLoad (SDValue Chain, SDLoc DL, SelectionDAG &DAG) const override
This callback is used to prepare for a volatile or atomic load.
SDValue PerformDAGCombine (SDNode *N, DAGCombinerInfo &DCI) const override
This method will be invoked for all target nodes and for any target-independent nodes that the target has registered with invoke it for.
Detailed Description
Definition at line 336 of file SystemZISelLowering.h.
Constructor & Destructor Documentation
SystemZTargetLowering::SystemZTargetLowering (const TargetMachine & TM, const SystemZSubtarget & STI) [explicit]
Definition at line 84 of file SystemZISelLowering.cpp.
References llvm::ISD::ADD, llvm::TargetLoweringBase::addRegisterClass(), llvm::ISD::AND, llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_LOAD, llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_MAX, llvm::ISD::ATOMIC_LOAD_MIN, llvm::ISD::ATOMIC_LOAD_NAND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, llvm::ISD::ATOMIC_LOAD_UMAX, llvm::ISD::ATOMIC_LOAD_UMIN, llvm::ISD::ATOMIC_LOAD_XOR, llvm::ISD::ATOMIC_STORE, llvm::ISD::ATOMIC_SWAP, llvm::ISD::BITCAST, llvm::ISD::BlockAddress, llvm::ISD::BR_CC, llvm::ISD::BR_JT, llvm::ISD::BRCOND, llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, llvm::TargetLoweringBase::computeRegisterProperties(), llvm::ISD::ConstantPool, llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::TargetLoweringBase::Custom, llvm::ISD::DYNAMIC_STACKALLOC, llvm::TargetLoweringBase::Expand, llvm::ISD::EXTLOAD, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, llvm::ISD::FABS, llvm::ISD::FADD, llvm::ISD::FCEIL, llvm::ISD::FCOS, llvm::ISD::FDIV, llvm::ISD::FFLOOR, llvm::MVT::FIRST_FP_VALUETYPE, llvm::MVT::FIRST_INTEGER_VALUETYPE, llvm::ISD::FMA, llvm::ISD::FMUL, llvm::ISD::FNEARBYINT, llvm::ISD::FNEG, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::MVT::fp_valuetypes(), llvm::ISD::FREM, llvm::ISD::FRINT, llvm::ISD::FROUND, llvm::ISD::FSIN, llvm::ISD::FSQRT, llvm::ISD::FSUB, llvm::ISD::FTRUNC, llvm::TargetLoweringBase::getOperationAction(), llvm::TargetLoweringBase::getPointerTy(), llvm::SystemZSubtarget::getRegisterInfo(), llvm::ISD::GlobalAddress, llvm::ISD::GlobalTLSAddress, llvm::SystemZSubtarget::hasFPExtension(), llvm::SystemZSubtarget::hasHighWord(), llvm::SystemZSubtarget::hasPopulationCount(), llvm::SystemZSubtarget::hasVector(), I, llvm::MVT::i1, llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::INSERT_VECTOR_ELT, llvm::MVT::integer_valuetypes(), llvm::MVT::integer_vector_valuetypes(), llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::TargetLoweringBase::isTypeLegal(), llvm::ISD::JumpTable, llvm::MVT::LAST_FP_VALUETYPE, llvm::MVT::LAST_INTEGER_VALUETYPE, llvm::TargetLoweringBase::Legal, llvm::ISD::LOAD, llvm::TargetLoweringBase::MaxStoresPerMemcpy, llvm::TargetLoweringBase::MaxStoresPerMemcpyOptSize, llvm::TargetLoweringBase::MaxStoresPerMemset, llvm::TargetLoweringBase::MaxStoresPerMemsetOptSize, llvm::ISD::MUL, llvm::ISD::MULHS, llvm::ISD::MULHU, llvm::ISD::OR, llvm::MVT::Other, llvm::ISD::PREFETCH, llvm::TargetLoweringBase::Promote, llvm::Sched::RegPressure, llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SDIV, llvm::ISD::SDIVREM, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::TargetLoweringBase::setBooleanContents(), llvm::TargetLoweringBase::setBooleanVectorContents(), llvm::ISD::SETCC, llvm::TargetLoweringBase::setExceptionPointerRegister(), llvm::TargetLoweringBase::setExceptionSelectorRegister(), llvm::TargetLoweringBase::setLoadExtAction(), llvm::TargetLoweringBase::setMinFunctionAlignment(), llvm::TargetLoweringBase::setOperationAction(), llvm::TargetLoweringBase::setSchedulingPreference(), llvm::TargetLoweringBase::setStackPointerRegisterToSaveRestore(), llvm::TargetLoweringBase::setTargetDAGCombine(), llvm::TargetLoweringBase::setTruncStoreAction(), llvm::ISD::SEXTLOAD, llvm::ISD::SHL, llvm::ISD::SHL_PARTS, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::ISD::SINT_TO_FP, llvm::ISD::SMUL_LOHI, llvm::ISD::SRA, llvm::ISD::SRA_PARTS, llvm::ISD::SREM, llvm::ISD::SRL, llvm::ISD::SRL_PARTS, llvm::ISD::STACKRESTORE, llvm::ISD::STACKSAVE, llvm::ISD::STORE, llvm::ISD::SUB, llvm::ISD::UDIV, llvm::ISD::UDIVREM, llvm::ISD::UINT_TO_FP, llvm::ISD::UMUL_LOHI, llvm::ISD::UNDEF, llvm::ISD::UREM, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v4i32, llvm::MVT::v8i16, llvm::ISD::VACOPY, llvm::ISD::VAEND, llvm::ISD::VASTART, llvm::ISD::VECTOR_SHUFFLE, llvm::MVT::vector_valuetypes(), llvm::ISD::VSELECT, llvm::ISD::XOR, llvm::ISD::ZERO_EXTEND_VECTOR_INREG, llvm::TargetLoweringBase::ZeroOrNegativeOneBooleanContent, llvm::TargetLoweringBase::ZeroOrOneBooleanContent, and llvm::ISD::ZEXTLOAD.
Member Function Documentation
bool SystemZTargetLowering::allowsMisalignedMemoryAccesses (EVT , unsigned AddrSpace, unsigned Align, bool *) const [override, virtual]
Determine if the target supports unaligned memory accesses.
This function returns true if the target allows unaligned memory accesses of the specified type in the given address space. If true, it also returns whether the unaligned memory access is "fast" in the last argument by reference. This is used, for example, in situations where an array copy/move/set is converted to a sequence of store operations. Its use helps to ensure that such replacements don't generate code that causes an alignment error (trap) on the target machine.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 498 of file SystemZISelLowering.cpp.
bool SystemZTargetLowering::allowTruncateForTailCall (Type * , Type *) const [override, virtual]
Return true if a truncation from Ty1 to Ty2 is permitted when deciding whether a call is in tail position.
Typically this means that both results would be assigned to the same register or stack slot, but it could mean the target performs adequate checks of its own before proceeding with the tail call.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 771 of file SystemZISelLowering.cpp.
References isTruncateFree().
MachineBasicBlock * SystemZTargetLowering::EmitInstrWithCustomInserter (MachineInstr * MI, MachineBasicBlock * MBB) const [override, virtual]
This method should be implemented by targets that mark instructions with the 'usesCustomInserter' flag.
These instructions are special in various ways, which require special support to insert. The specified MachineInstr is created but not inserted into any basic blocks, and this method is called to expand it into a sequence of instructions, potentially also creating new basic blocks and control flow. As long as the returned basic block is different (i.e., we created a new one), the custom inserter is free to modify the rest of MBB.
Reimplemented from llvm::TargetLowering.
Definition at line 5599 of file SystemZISelLowering.cpp.
References llvm::SystemZISD::ATOMIC_CMP_SWAPW, llvm::ISD::ATOMIC_LOAD_OR, llvm::SystemZISD::ATOMIC_LOADW_MAX, llvm::SystemZISD::ATOMIC_LOADW_MIN, llvm::SystemZISD::ATOMIC_LOADW_OR, llvm::SystemZISD::ATOMIC_LOADW_UMAX, llvm::SystemZISD::ATOMIC_LOADW_UMIN, llvm::SystemZISD::ATOMIC_SWAPW, llvm::SystemZ::CCMASK_CMP_GE, llvm::SystemZ::CCMASK_CMP_LE, llvm::SystemZISD::CLC, llvm::MachineInstr::getOpcode(), llvm_unreachable, llvm::SystemZISD::MVC, NC, llvm::SystemZISD::OC, OR, llvm::AArch64DB::ST, llvm::SystemZISD::TBEGIN, and llvm::SystemZISD::XC.
TargetLowering::ConstraintType SystemZTargetLowering::getConstraintType (const std::string & Constraint) const [override, virtual]
Given a constraint, return the type of constraint it is for this target.
Reimplemented from llvm::TargetLowering.
Definition at line 547 of file SystemZISelLowering.cpp.
References llvm::TargetLowering::C_Memory, llvm::TargetLowering::C_Other, and llvm::TargetLowering::C_RegisterClass.
unsigned llvm::SystemZTargetLowering::getInlineAsmMemConstraint (const std::string & ConstraintCode) const [inline, override, virtual]
Reimplemented from llvm::TargetLowering.
Definition at line 394 of file SystemZISelLowering.h.
References llvm::InlineAsm::Constraint_Q, llvm::InlineAsm::Constraint_R, llvm::InlineAsm::Constraint_S, and llvm::InlineAsm::Constraint_T.
TargetLoweringBase::LegalizeTypeAction llvm::SystemZTargetLowering::getPreferredVectorAction (EVT VT) const [inline, override, virtual]
Return the preferred vector type legalization action.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 350 of file SystemZISelLowering.h.
References llvm::EVT::getSizeInBits(), llvm::EVT::getVectorElementType(), and llvm::TargetLoweringBase::TypeWidenVector.
std::pair< unsigned, const TargetRegisterClass * > SystemZTargetLowering::getRegForInlineAsmConstraint (const TargetRegisterInfo * TRI, const std::string & Constraint, MVT VT) const [override, virtual]
Given a physical register constraint (e.g.
{edx}), return the register number and the register class for the register.
Given a register class constraint, like 'r', if this corresponds directly to an LLVM register class, return a register of 0 and the register class pointer.
This should only be used for C_Register constraints. On error, this returns a register number of 0 and a null register class pointer.
Reimplemented from llvm::TargetLowering.
Definition at line 657 of file SystemZISelLowering.cpp.
References llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::SystemZMC::FP128Regs, llvm::SystemZMC::FP32Regs, llvm::SystemZMC::FP64Regs, llvm::SystemZMC::GR128Regs, llvm::SystemZMC::GR32Regs, llvm::SystemZMC::GR64Regs, llvm::MVT::i128, llvm::MVT::i32, llvm::MVT::i64, and parseRegisterNumber().
MVT llvm::SystemZTargetLowering::getScalarShiftAmountTy (EVT LHSTy) const [inline, override, virtual]
Reimplemented from llvm::TargetLoweringBase.
Definition at line 342 of file SystemZISelLowering.h.
References llvm::MVT::i32.
EVT SystemZTargetLowering::getSetCCResultType (LLVMContext & Context, EVT VT) const [override, virtual]
Return the ValueType of the result of SETCC operations.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 458 of file SystemZISelLowering.cpp.
References llvm::EVT::changeVectorElementTypeToInteger(), llvm::MVT::i32, and llvm::EVT::isVector().
TargetLowering::ConstraintWeight SystemZTargetLowering::getSingleConstraintMatchWeight (AsmOperandInfo & info, const char * constraint) const [override, virtual]
Examine constraint string and operand type and determine a weight value.
Examine constraint type and operand type and determine a weight value.
The operand object must already have been set up with the operand type.
This object must already have been set up with the operand type and the current alternative constraint selected.
Reimplemented from llvm::TargetLowering.
Definition at line 579 of file SystemZISelLowering.cpp.
References llvm::C, llvm::TargetLowering::AsmOperandInfo::CallOperandVal, llvm::TargetLowering::CW_Constant, llvm::TargetLowering::CW_Default, llvm::TargetLowering::CW_Invalid, llvm::TargetLowering::CW_Register, llvm::Value::getType(), llvm::Type::isFloatingPointTy(), llvm::isInt< 16 >(), llvm::Type::isIntegerTy(), and llvm::isUInt< 8 >().
const char * SystemZTargetLowering::getTargetNodeName (unsigned Opcode) const [override, virtual]
This method returns the name of a target specific DAG node.
Reimplemented from llvm::TargetLowering.
Definition at line 4371 of file SystemZISelLowering.cpp.
References llvm::SystemZISD::ADJDYNALLOC, llvm::SystemZISD::ATOMIC_CMP_SWAPW, llvm::SystemZISD::ATOMIC_LOADW_ADD, llvm::SystemZISD::ATOMIC_LOADW_AND, llvm::SystemZISD::ATOMIC_LOADW_MAX, llvm::SystemZISD::ATOMIC_LOADW_MIN, llvm::SystemZISD::ATOMIC_LOADW_NAND, llvm::SystemZISD::ATOMIC_LOADW_OR, llvm::SystemZISD::ATOMIC_LOADW_SUB, llvm::SystemZISD::ATOMIC_LOADW_UMAX, llvm::SystemZISD::ATOMIC_LOADW_UMIN, llvm::SystemZISD::ATOMIC_LOADW_XOR, llvm::SystemZISD::ATOMIC_SWAPW, llvm::SystemZISD::BR_CCMASK, llvm::SystemZISD::BYTE_MASK, llvm::AArch64ISD::CALL, llvm::SystemZISD::CLC, llvm::SystemZISD::CLC_LOOP, llvm::SystemZISD::EXTRACT_ACCESS, llvm::AArch64ISD::FCMP, llvm::SystemZISD::FIRST_NUMBER, llvm::SystemZISD::IABS, llvm::SystemZISD::ICMP, llvm::SystemZISD::IPM, llvm::SystemZISD::JOIN_DWORDS, llvm::SystemZISD::MERGE_HIGH, llvm::SystemZISD::MERGE_LOW, llvm::SystemZISD::MVC, llvm::SystemZISD::MVC_LOOP, NC, llvm::SystemZISD::NC_LOOP, llvm::SystemZISD::OC, llvm::SystemZISD::OC_LOOP, OPCODE, llvm::SystemZISD::PACK, llvm::SystemZISD::PACKLS_CC, llvm::SystemZISD::PACKS_CC, llvm::SystemZISD::PCREL_OFFSET, llvm::SystemZISD::PCREL_WRAPPER, llvm::SystemZISD::PERMUTE, llvm::SystemZISD::PERMUTE_DWORDS, llvm::SystemZISD::POPCNT, llvm::PREFETCH, llvm::SystemZISD::REPLICATE, llvm::AArch64ISD::RET_FLAG, llvm::SystemZISD::ROTATE_MASK, llvm::SystemZISD::SDIVREM32, llvm::SystemZISD::SDIVREM64, llvm::SystemZISD::SEARCH_STRING, llvm::SystemZISD::SELECT_CCMASK, llvm::SystemZISD::SERIALIZE, llvm::SystemZISD::SHL_DOUBLE, llvm::SystemZISD::SIBCALL, llvm::SystemZISD::SPLAT, llvm::SystemZISD::STPCPY, llvm::SystemZISD::STRCMP, llvm::SystemZISD::TBEGIN, llvm::SystemZISD::TBEGIN_NOFLOAT, llvm::SystemZISD::TEND, llvm::SystemZISD::TLS_GDCALL, llvm::SystemZISD::TLS_LDCALL, llvm::SystemZISD::UDIVREM32, llvm::SystemZISD::UDIVREM64, llvm::SystemZISD::UMUL_LOHI64, llvm::SystemZISD::UNPACK_HIGH, llvm::SystemZISD::UNPACK_LOW, llvm::SystemZISD::UNPACKL_HIGH, llvm::SystemZISD::UNPACKL_LOW, llvm::SystemZISD::VEXTEND, llvm::SystemZISD::VFAE_CC, llvm::SystemZISD::VFAEZ_CC, llvm::SystemZISD::VFCMPE, llvm::SystemZISD::VFCMPES, llvm::SystemZISD::VFCMPH, llvm::SystemZISD::VFCMPHE, llvm::SystemZISD::VFCMPHES, llvm::SystemZISD::VFCMPHS, llvm::SystemZISD::VFEE_CC, llvm::SystemZISD::VFEEZ_CC, llvm::SystemZISD::VFENE_CC, llvm::SystemZISD::VFENEZ_CC, llvm::SystemZISD::VFTCI, llvm::SystemZISD::VICMPE, llvm::SystemZISD::VICMPES, llvm::SystemZISD::VICMPH, llvm::SystemZISD::VICMPHL, llvm::SystemZISD::VICMPHLS, llvm::SystemZISD::VICMPHS, llvm::SystemZISD::VISTR_CC, llvm::SystemZISD::VROUND, llvm::SystemZISD::VSHL_BY_SCALAR, llvm::SystemZISD::VSRA_BY_SCALAR, llvm::SystemZISD::VSRL_BY_SCALAR, llvm::SystemZISD::VSTRC_CC, llvm::SystemZISD::VSTRCZ_CC, llvm::SystemZISD::VSUM, llvm::SystemZISD::VTM, llvm::SystemZISD::XC, and llvm::SystemZISD::XC_LOOP.
MVT llvm::SystemZTargetLowering::getVectorIdxTy () const [inline, override, virtual]
Returns the type to be used for the index operand of: ISD::INSERT_VECTOR_ELT, ISD::EXTRACT_VECTOR_ELT, ISD::INSERT_SUBVECTOR, and ISD::EXTRACT_SUBVECTOR.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 345 of file SystemZISelLowering.h.
References llvm::MVT::i32.
bool SystemZTargetLowering::isFMAFasterThanFMulAndFAdd (EVT) const [override, virtual]
Return true if an FMA operation is faster than a pair of fmul and fadd instructions.
fmuladd intrinsics will be expanded to FMAs when this method returns true, otherwise fmuladd is expanded to fmul + fadd.
NOTE: This may be called before legalization on types for which FMAs are not legal, but should return true if those types will eventually legalize to types that support FMAs. After legalization, it will only be called on types that support FMAs (via Legal or Custom actions)
Reimplemented from llvm::TargetLoweringBase.
Definition at line 464 of file SystemZISelLowering.cpp.
References llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::EVT::getScalarType(), llvm::EVT::getSimpleVT(), llvm::EVT::isSimple(), and llvm::MVT::SimpleTy.
bool SystemZTargetLowering::isFPImmLegal (const APFloat & , EVT) const [override, virtual]
Returns true if the target can instruction select the specified FP immediate natively.
If false, the legalizer will materialize the FP immediate as a load from a constant pool.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 483 of file SystemZISelLowering.cpp.
References llvm::APFloat::isNegZero(), and llvm::APFloat::isZero().
bool SystemZTargetLowering::isLegalAddImmediate (int64_t) const [override, virtual]
Return true if the specified immediate is legal add immediate, that is the target has add instructions which can add a register with the immediate without having to materialize the immediate into a register.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 493 of file SystemZISelLowering.cpp.
References llvm::isUInt< 32 >().
bool SystemZTargetLowering::isLegalAddressingMode (const AddrMode & AM, Type * Ty, unsigned AS) const [override, virtual]
Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
isLegalAddressingMode - Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
The type may be VoidTy, in which case only return true if the addressing mode is legal for a load/store of any legal type. TODO: Handle pre/postinc as well.
If the address space cannot be determined, it will be -1.
TODO: Remove default argument
Reimplemented from llvm::TargetLoweringBase.
Definition at line 510 of file SystemZISelLowering.cpp.
References llvm::TargetLoweringBase::AddrMode::BaseGV, llvm::TargetLoweringBase::AddrMode::BaseOffs, and llvm::TargetLoweringBase::AddrMode::Scale.
bool SystemZTargetLowering::isLegalICmpImmediate (int64_t) const [override, virtual]
Return true if the specified immediate is legal icmp immediate, that is the target has icmp instructions which can compare a register against the immediate without having to materialize the immediate into a register.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 488 of file SystemZISelLowering.cpp.
References llvm::isInt< 32 >(), and llvm::isUInt< 32 >().
bool SystemZTargetLowering::isTruncateFree (Type * , Type *) const [override, virtual]
Return true if it's free to truncate a value of type Ty1 to type Ty2.
e.g. On x86 it's free to truncate a i32 value in register EAX to i16 by referencing its sub-register AX.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 526 of file SystemZISelLowering.cpp.
References llvm::Type::getPrimitiveSizeInBits(), and llvm::Type::isIntegerTy().
Referenced by allowTruncateForTailCall().
bool SystemZTargetLowering::isTruncateFree (EVT FromVT, EVT ToVT) const [override, virtual]
Reimplemented from llvm::TargetLoweringBase.
Definition at line 534 of file SystemZISelLowering.cpp.
References llvm::EVT::getSizeInBits(), and llvm::EVT::isInteger().
void SystemZTargetLowering::LowerAsmOperandForConstraint (SDValue Op, std::string & Constraint, std::vector< SDValue > & Ops, SelectionDAG & DAG) const [override, virtual]
Lower the specified operand into the Ops vector.
LowerAsmOperandForConstraint - Lower the specified operand into the Ops vector.
If it is invalid, don't add anything to Ops.
Reimplemented from llvm::TargetLowering.
Definition at line 720 of file SystemZISelLowering.cpp.
References llvm::C, llvm::SelectionDAG::getTargetConstant(), llvm::SDValue::getValueType(), llvm::isInt< 16 >(), and llvm::isUInt< 8 >().
SDValue SystemZTargetLowering::LowerCall (CallLoweringInfo & , SmallVectorImpl< SDValue > &) const [override, virtual]
This hook must be implemented to lower calls into the specified DAG.
The outgoing arguments to the call are described by the Outs array, and the values to be returned by the call are described by the Ins array. The implementation should fill in the InVals array with legal-type return values from the call, and return the resulting token chain value.
Reimplemented from llvm::TargetLowering.
Definition at line 1009 of file SystemZISelLowering.cpp.
References llvm::ISD::ADD, llvm::dwarf::syntax::Address, llvm::SystemZCCState::AnalyzeCallOperands(), llvm::CCState::AnalyzeCallResult(), llvm::SystemZISD::CALL, llvm::TargetLowering::CallLoweringInfo::CallConv, llvm::TargetLowering::CallLoweringInfo::Callee, llvm::SystemZMC::CallFrameSize, canUseSiblingCall(), llvm::TargetLowering::CallLoweringInfo::Chain, convertLocVTToValVT(), convertValVTToLocVT(), llvm::SelectionDAG::CreateStackTemporary(), llvm::TargetLowering::CallLoweringInfo::DAG, llvm::DL, llvm::TargetLowering::CallLoweringInfo::DL, llvm::SmallVectorBase::empty(), llvm::MVT::f32, G, llvm::TargetRegisterInfo::getCallPreservedMask(), llvm::SelectionDAG::getCALLSEQ_END(), llvm::SelectionDAG::getCALLSEQ_START(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::MachinePointerInfo::getFixedStack(), llvm::SelectionDAG::getIntPtrConstant(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::SystemZSubtarget::getRegisterInfo(), llvm::SelectionDAG::getRegisterMask(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTargetExternalSymbol(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::CCValAssign::getValVT(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, llvm::SystemZSubtarget::hasVector(), I, llvm::MVT::i32, llvm::CCValAssign::Indirect, llvm::MipsISD::Ins, llvm::TargetLowering::CallLoweringInfo::Ins, llvm::CCValAssign::isMemLoc(), llvm::CCValAssign::isRegLoc(), llvm::TargetLowering::CallLoweringInfo::IsTailCall, llvm::TargetLowering::CallLoweringInfo::IsVarArg, llvm::MVT::Other, llvm::TargetLowering::CallLoweringInfo::Outs, llvm::TargetLowering::CallLoweringInfo::OutVals, llvm::SystemZISD::PCREL_WRAPPER, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SystemZISD::SIBCALL, llvm::SmallVectorTemplateCommon< T >::size(), llvm::ISD::TokenFactor, and VerifyVectorTypes().
SDValue SystemZTargetLowering::LowerFormalArguments (SDValue , CallingConv::ID , bool , const SmallVectorImpl< ISD::InputArg > & , SDLoc , SelectionDAG & , SmallVectorImpl< SDValue > &) const [override, virtual]
This hook must be implemented to lower the incoming (formal) arguments, described by the Ins array, into the specified DAG.
The implementation should fill in the InVals array with legal-type argument values, and return the resulting token chain value.
Reimplemented from llvm::TargetLowering.
Definition at line 861 of file SystemZISelLowering.cpp.
References llvm::ISD::ADD, llvm::MachineFunction::addLiveIn(), llvm::MachineRegisterInfo::addLiveIn(), llvm::SystemZCCState::AnalyzeFormalArguments(), llvm::SystemZ::ArgFPRs, convertLocVTToValVT(), llvm::MachineFrameInfo::CreateFixedObject(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::DL, llvm::MVT::f32, llvm::MVT::f64, llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::MachinePointerInfo::getFixedStack(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::SystemZSubtarget::getFrameLowering(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::MachineFunction::getRegInfo(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getStore(), llvm::SDValue::getValue(), llvm::SystemZSubtarget::hasVector(), I, llvm::MVT::i32, llvm::MVT::i64, llvm::CCValAssign::isMemLoc(), llvm::CCValAssign::isRegLoc(), llvm_unreachable, llvm::makeArrayRef(), llvm::SystemZ::NumArgFPRs, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SystemZMachineFunctionInfo::setRegSaveFrameIndex(), llvm::SystemZMachineFunctionInfo::setVarArgsFirstFPR(), llvm::SystemZMachineFunctionInfo::setVarArgsFirstGPR(), llvm::SystemZMachineFunctionInfo::setVarArgsFrameIndex(), llvm::MVT::SimpleTy, llvm::SmallVectorTemplateCommon< T >::size(), llvm::ISD::TokenFactor, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v4i32, llvm::MVT::v8i16, and VerifyVectorTypes().
SDValue SystemZTargetLowering::LowerOperation (SDValue Op, SelectionDAG & DAG) const [override, virtual]
This callback is invoked for operations that are unsupported by the target, which are registered to use 'custom' lowering, and whose defined values are all legal.
If the target has no operations that require custom lowering, it need not implement this. The default implementation of this aborts.
Reimplemented from llvm::TargetLowering.
Definition at line 4263 of file SystemZISelLowering.cpp.
References llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_LOAD, llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_MAX, llvm::ISD::ATOMIC_LOAD_MIN, llvm::ISD::ATOMIC_LOAD_NAND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, llvm::ISD::ATOMIC_LOAD_UMAX, llvm::ISD::ATOMIC_LOAD_UMIN, llvm::ISD::ATOMIC_LOAD_XOR, llvm::SystemZISD::ATOMIC_LOADW_ADD, llvm::SystemZISD::ATOMIC_LOADW_AND, llvm::SystemZISD::ATOMIC_LOADW_MAX, llvm::SystemZISD::ATOMIC_LOADW_MIN, llvm::SystemZISD::ATOMIC_LOADW_NAND, llvm::SystemZISD::ATOMIC_LOADW_OR, llvm::SystemZISD::ATOMIC_LOADW_UMAX, llvm::SystemZISD::ATOMIC_LOADW_UMIN, llvm::SystemZISD::ATOMIC_LOADW_XOR, llvm::ISD::ATOMIC_STORE, llvm::ISD::ATOMIC_SWAP, llvm::SystemZISD::ATOMIC_SWAPW, llvm::ISD::BITCAST, llvm::ISD::BlockAddress, llvm::ISD::BR_CC, llvm::ISD::BUILD_VECTOR, llvm::ISD::ConstantPool, llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::ISD::DYNAMIC_STACKALLOC, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::ISD::GlobalAddress, llvm::ISD::GlobalTLSAddress, llvm::ISD::INSERT_VECTOR_ELT, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::ISD::JumpTable, llvm_unreachable, llvm::ISD::OR, llvm::ISD::PREFETCH, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SDIVREM, llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::ISD::SMUL_LOHI, llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::STACKRESTORE, llvm::ISD::STACKSAVE, llvm::ISD::UDIVREM, llvm::ISD::UMUL_LOHI, llvm::SystemZISD::UNPACK_HIGH, llvm::SystemZISD::UNPACKL_HIGH, llvm::ISD::VACOPY, llvm::ISD::VASTART, llvm::ISD::VECTOR_SHUFFLE, llvm::SystemZISD::VSHL_BY_SCALAR, llvm::SystemZISD::VSRA_BY_SCALAR, llvm::SystemZISD::VSRL_BY_SCALAR, and llvm::ISD::ZERO_EXTEND_VECTOR_INREG.
SDValue SystemZTargetLowering::LowerReturn (SDValue , CallingConv::ID , bool , const SmallVectorImpl< ISD::OutputArg > & , const SmallVectorImpl< SDValue > & , SDLoc , SelectionDAG &) const [override, virtual]
This hook must be implemented to lower outgoing return values, described by the Outs array, into the specified DAG.
The implementation should return the resulting token chain value.
Reimplemented from llvm::TargetLowering.
Definition at line 1177 of file SystemZISelLowering.cpp.
References llvm::CCState::AnalyzeReturn(), convertValVTToLocVT(), llvm::SmallVectorBase::empty(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyToReg(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getRegister(), llvm::SDValue::getValue(), llvm::SystemZSubtarget::hasVector(), I, llvm::CCValAssign::isRegLoc(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SystemZISD::RET_FLAG, llvm::SmallVectorTemplateCommon< T >::size(), and VerifyVectorTypes().
bool SystemZTargetLowering::mayBeEmittedAsTailCall (CallInst *) const [override, virtual]
Return true if the target may be able emit the call instruction as a tail call.
This is used by optimization passes to determine if it's profitable to duplicate return instructions to enable tailcall optimization.
Reimplemented from llvm::TargetLowering.
Definition at line 776 of file SystemZISelLowering.cpp.
References llvm::CallInst::isTailCall().
SDValue SystemZTargetLowering::PerformDAGCombine (SDNode * N, DAGCombinerInfo & DCI) const [override, virtual]
This method will be invoked for all target nodes and for any target-independent nodes that the target has registered with invoke it for.
The semantics are as follows: Return Value: SDValue.Val == 0 - No change was made SDValue.Val == N - N was replaced, is dead, and is already handled. otherwise - N should be replaced by the returned Operand.
In addition, methods provided by DAGCombinerInfo may be used to perform more complex transformations.
Reimplemented from llvm::TargetLowering.
Definition at line 4629 of file SystemZISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::AddToWorklist(), llvm::ISD::ANY_EXTEND, llvm::ISD::BITCAST, llvm::SystemZISD::BYTE_MASK, llvm::EVT::changeVectorElementTypeToInteger(), llvm::ISD::Constant, llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::dyn_cast(), llvm::MipsISD::Ext, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f32, llvm::ISD::FP_ROUND, llvm::SelectionDAG::getConstant(), llvm::MVT::getIntegerVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::EVT::getStoreSize(), llvm::SelectionDAG::getTruncStore(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::MVT::getVectorVT(), llvm::SDValue::hasOneUse(), llvm::SDNode::hasOneUse(), llvm::MVT::i32, llvm::SystemZISD::JOIN_DWORDS, llvm::SystemZISD::MERGE_HIGH, llvm::SystemZISD::MERGE_LOW, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::SystemZISD::REPLICATE, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::ISD::SRA, llvm::ISD::STORE, llvm::SystemZISD::UNPACKL_HIGH, llvm::SystemZISD::UNPACKL_LOW, llvm::SDNode::uses(), llvm::MVT::v2f64, llvm::MVT::v4f32, and llvm::SystemZISD::VROUND.
SDValue SystemZTargetLowering::prepareVolatileOrAtomicLoad (SDValue Chain, SDLoc DL, SelectionDAG & DAG) const [override, virtual]
This callback is used to prepare for a volatile or atomic load.
It takes a chain node as input and returns the chain for the load itself.
Having a callback like this is necessary for targets like SystemZ, which allows a CPU to reuse the result of a previous load indefinitely, even if a cache-coherent store is performed by another CPU. The default implementation does nothing.
Reimplemented from llvm::TargetLowering.
Definition at line 1227 of file SystemZISelLowering.cpp.
References llvm::SelectionDAG::getNode(), llvm::MVT::Other, and llvm::SystemZISD::SERIALIZE.
The documentation for this class was generated from the following files:
SystemZISelLowering.h
SystemZISelLowering.cpp