LLVM: llvm::ARMMCExpr Class Reference
llvm::ARMMCExpr Class Reference
#include <ARMMCExpr.h>
Public Types
enum VariantKind { VK_ARM_None, VK_ARM_HI16, VK_ARM_LO16 }
Public Member Functions
VariantKind getKind () const
getOpcode - Get the kind of this expression.
const MCExpr * getSubExpr () const
getSubExpr - Get the child of this expression.
void printImpl (raw_ostream &OS, const MCAsmInfo *MAI) const override
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const override
void visitUsedExpr (MCStreamer &Streamer) const override
MCSection * findAssociatedSection () const override
Find the "associated section" for this expression, which is currently defined as the absolute section for constants, or otherwise the section associated with the first defined symbol in the expression.
void fixELFSymbolsInTLSFixups (MCAssembler &Asm) const override
Static Public Member Functions
static bool classof (const MCExpr *E)
Construction
static const ARMMCExpr * create (VariantKind Kind, const MCExpr *Expr, MCContext &Ctx)
static const ARMMCExpr * createUpper16 (const MCExpr *Expr, MCContext &Ctx)
static const ARMMCExpr * createLower16 (const MCExpr *Expr, MCContext &Ctx)
Detailed Description
Definition at line 17 of file ARMMCExpr.h.
Member Enumeration Documentation
enum llvm::ARMMCExpr::VariantKind
Enumerator:
VK_ARM_None
VK_ARM_HI16
VK_ARM_LO16
Definition at line 19 of file ARMMCExpr.h.
Member Function Documentation
static bool llvm::ARMMCExpr::classof (const MCExpr * E) [inline, static]
Reimplemented from llvm::MCTargetExpr.
Definition at line 71 of file ARMMCExpr.h.
const ARMMCExpr * ARMMCExpr::create (VariantKind Kind, const MCExpr * Expr, MCContext & Ctx) [static]
Definition at line 19 of file ARMMCExpr.cpp.
Referenced by createLower16(), and createUpper16().
static const ARMMCExpr* llvm::ARMMCExpr::createLower16 (const MCExpr * Expr, MCContext & Ctx) [inline, static]
Definition at line 43 of file ARMMCExpr.h.
References create(), and VK_ARM_LO16.
Referenced by llvm::ARMAsmPrinter::EmitInstruction().
static const ARMMCExpr* llvm::ARMMCExpr::createUpper16 (const MCExpr * Expr, MCContext & Ctx) [inline, static]
Definition at line 39 of file ARMMCExpr.h.
References create(), and VK_ARM_HI16.
Referenced by llvm::ARMAsmPrinter::EmitInstruction().
bool llvm::ARMMCExpr::evaluateAsRelocatableImpl (MCValue & Res, const MCAsmLayout * Layout, const MCFixup * Fixup) const [inline, override, virtual]
Implements llvm::MCTargetExpr.
Definition at line 58 of file ARMMCExpr.h.
MCSection* llvm::ARMMCExpr::findAssociatedSection () const [inline, override, virtual]
Find the "associated section" for this expression, which is currently defined as the absolute section for constants, or otherwise the section associated with the first defined symbol in the expression.
Implements llvm::MCTargetExpr.
Definition at line 64 of file ARMMCExpr.h.
void llvm::ARMMCExpr::fixELFSymbolsInTLSFixups (MCAssembler & Asm) const [inline, override, virtual]
Implements llvm::MCTargetExpr.
Definition at line 69 of file ARMMCExpr.h.
VariantKind llvm::ARMMCExpr::getKind () const [inline]
getOpcode - Get the kind of this expression.
Reimplemented from llvm::MCExpr.
Definition at line 50 of file ARMMCExpr.h.
const MCExpr* llvm::ARMMCExpr::getSubExpr () const [inline]
getSubExpr - Get the child of this expression.
Definition at line 53 of file ARMMCExpr.h.
Referenced by printImpl(), and visitUsedExpr().
void ARMMCExpr::printImpl (raw_ostream & OS, const MCAsmInfo * MAI) const [override, virtual]
Implements llvm::MCTargetExpr.
Definition at line 24 of file ARMMCExpr.cpp.
References llvm::MCExpr::getKind(), getSubExpr(), llvm_unreachable, llvm::MCExpr::print(), llvm::MCExpr::SymbolRef, VK_ARM_HI16, and VK_ARM_LO16.
void ARMMCExpr::visitUsedExpr (MCStreamer & Streamer) const [override, virtual]
Implements llvm::MCTargetExpr.
Definition at line 39 of file ARMMCExpr.cpp.
References getSubExpr(), and llvm::MCStreamer::visitUsedExpr().
The documentation for this class was generated from the following files:
ARMMCExpr.h
ARMMCExpr.cpp