LLVM: llvm::ExtractElementInst Class Reference
llvm::ExtractElementInst Class Reference
ExtractElementInst - This instruction extracts a single (scalar) element from a VectorType value.
#include <Instructions.h>
Public Member Functions
Value * getVectorOperand ()
Value * getIndexOperand ()
const Value * getVectorOperand () const
const Value * getIndexOperand () const
VectorType * getVectorOperandType () const
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
Static Public Member Functions
static ExtractElementInst * Create (Value *Vec, Value *Idx, const Twine &NameStr="", Instruction *InsertBefore=nullptr)
static ExtractElementInst * Create (Value *Vec, Value *Idx, const Twine &NameStr, BasicBlock *InsertAtEnd)
static bool isValidOperands (const Value *Vec, const Value *Idx)
isValidOperands - Return true if an extractelement instruction can be formed with the specified operands.
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
ExtractElementInst * clone_impl () const override
Detailed Description
ExtractElementInst - This instruction extracts a single (scalar) element from a VectorType value.
Definition at line 1779 of file Instructions.h.
Member Function Documentation
static bool llvm::ExtractElementInst::classof (const Instruction * I) [inline, static]
Definition at line 1817 of file Instructions.h.
References ExtractElement(), and llvm::Instruction::getOpcode().
Referenced by classof().
static bool llvm::ExtractElementInst::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::Instruction.
Definition at line 1820 of file Instructions.h.
References classof().
ExtractElementInst * ExtractElementInst::clone_impl () const [override, protected, virtual]
Implements llvm::Instruction.
Definition at line 3585 of file Instructions.cpp.
References Create(), and llvm::User::getOperand().
static ExtractElementInst* llvm::ExtractElementInst::Create (Value * Vec, Value * Idx, const Twine & NameStr = "", Instruction * InsertBefore = nullptr) [inline, static]
Definition at line 1788 of file Instructions.h.
Referenced by clone_impl(), llvm::NoFolder::CreateExtractElement(), llvm::IRBuilder< true, TargetFolder >::CreateExtractElement(), llvm::ConstantExpr::getAsInstruction(), OptimizeIntToFloatBitCast(), and llvm::InstCombiner::visitExtractElementInst().
static ExtractElementInst* llvm::ExtractElementInst::Create (Value * Vec, Value * Idx, const Twine & NameStr, BasicBlock * InsertAtEnd) [inline, static]
Definition at line 1793 of file Instructions.h.
llvm::ExtractElementInst::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
Value* llvm::ExtractElementInst::getIndexOperand () [inline]
Definition at line 1804 of file Instructions.h.
Referenced by llvm::InstCombiner::visitExtractElementInst().
const Value* llvm::ExtractElementInst::getIndexOperand () const [inline]
Definition at line 1806 of file Instructions.h.
Value* llvm::ExtractElementInst::getVectorOperand () [inline]
Definition at line 1803 of file Instructions.h.
Referenced by getVectorOperandType().
const Value* llvm::ExtractElementInst::getVectorOperand () const [inline]
Definition at line 1805 of file Instructions.h.
VectorType* llvm::ExtractElementInst::getVectorOperandType () const [inline]
Definition at line 1808 of file Instructions.h.
References llvm::Value::getType(), and getVectorOperand().
Referenced by llvm::InstCombiner::visitExtractElementInst().
bool ExtractElementInst::isValidOperands (const Value * Vec, const Value * Idx) [static]
isValidOperands - Return true if an extractelement instruction can be formed with the specified operands.
Definition at line 1335 of file Instructions.cpp.
References llvm::Value::getType(), llvm::Type::isIntegerTy(), and llvm::Type::isVectorTy().
The documentation for this class was generated from the following files:
Instructions.h
Instructions.cpp