LLVM: llvm::DIARawSymbol Class Reference
llvm::DIARawSymbol Class Reference
#include <DIARawSymbol.h>
Public Member Functions
DIARawSymbol (const DIASession &PDBSession, CComPtr< IDiaSymbol > DiaSymbol)
void dump (raw_ostream &OS, int Indent) const override
CComPtr< IDiaSymbol > getDiaSymbol () const
std::unique_ptr< IPDBEnumSymbols > findChildren (PDB_SymType Type) const override
std::unique_ptr< IPDBEnumSymbols > findChildren (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags) const override
std::unique_ptr< IPDBEnumSymbols > findChildrenByRVA (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint32_t RVA) const override
std::unique_ptr< IPDBEnumSymbols > findInlineFramesByRVA (uint32_t RVA) const override
void getDataBytes (llvm::SmallVector< uint8_t, 32 > &bytes) const override
void getFrontEndVersion (VersionInfo &Version) const override
void getBackEndVersion (VersionInfo &Version) const override
PDB_MemberAccess getAccess () const override
uint32_t getAddressOffset () const override
uint32_t getAddressSection () const override
uint32_t getAge () const override
uint32_t getArrayIndexTypeId () const override
uint32_t getBaseDataOffset () const override
uint32_t getBaseDataSlot () const override
uint32_t getBaseSymbolId () const override
PDB_BuiltinType getBuiltinType () const override
uint32_t getBitPosition () const override
PDB_CallingConv getCallingConvention () const override
uint32_t getClassParentId () const override
std::string getCompilerName () const override
uint32_t getCount () const override
uint32_t getCountLiveRanges () const override
PDB_Lang getLanguage () const override
uint32_t getLexicalParentId () const override
std::string getLibraryName () const override
uint32_t getLiveRangeStartAddressOffset () const override
uint32_t getLiveRangeStartAddressSection () const override
uint32_t getLiveRangeStartRelativeVirtualAddress () const override
PDB_RegisterId getLocalBasePointerRegisterId () const override
uint32_t getLowerBoundId () const override
uint32_t getMemorySpaceKind () const override
std::string getName () const override
uint32_t getNumberOfAcceleratorPointerTags () const override
uint32_t getNumberOfColumns () const override
uint32_t getNumberOfModifiers () const override
uint32_t getNumberOfRegisterIndices () const override
uint32_t getNumberOfRows () const override
std::string getObjectFileName () const override
uint32_t getOemId () const override
uint32_t getOemSymbolId () const override
uint32_t getOffsetInUdt () const override
PDB_Cpu getPlatform () const override
uint32_t getRank () const override
PDB_RegisterId getRegisterId () const override
uint32_t getRegisterType () const override
uint32_t getRelativeVirtualAddress () const override
uint32_t getSamplerSlot () const override
uint32_t getSignature () const override
uint32_t getSizeInUdt () const override
uint32_t getSlot () const override
std::string getSourceFileName () const override
uint32_t getStride () const override
uint32_t getSubTypeId () const override
std::string getSymbolsFileName () const override
uint32_t getSymIndexId () const override
uint32_t getTargetOffset () const override
uint32_t getTargetRelativeVirtualAddress () const override
uint64_t getTargetVirtualAddress () const override
uint32_t getTargetSection () const override
uint32_t getTextureSlot () const override
uint32_t getTimeStamp () const override
uint32_t getToken () const override
uint32_t getTypeId () const override
uint32_t getUavSlot () const override
std::string getUndecoratedName () const override
uint32_t getUnmodifiedTypeId () const override
uint32_t getUpperBoundId () const override
Variant getValue () const override
uint32_t getVirtualBaseDispIndex () const override
uint32_t getVirtualBaseOffset () const override
uint32_t getVirtualTableShapeId () const override
PDB_DataKind getDataKind () const override
PDB_SymType getSymTag () const override
PDB_UniqueId getGuid () const override
int32_t getOffset () const override
int32_t getThisAdjust () const override
int32_t getVirtualBasePointerOffset () const override
PDB_LocType getLocationType () const override
PDB_Machine getMachineType () const override
PDB_ThunkOrdinal getThunkOrdinal () const override
uint64_t getLength () const override
uint64_t getLiveRangeLength () const override
uint64_t getVirtualAddress () const override
PDB_UdtType getUdtKind () const override
bool hasConstructor () const override
bool hasCustomCallingConvention () const override
bool hasFarReturn () const override
bool isCode () const override
bool isCompilerGenerated () const override
bool isConstType () const override
bool isEditAndContinueEnabled () const override
bool isFunction () const override
bool getAddressTaken () const override
bool getNoStackOrdering () const override
bool hasAlloca () const override
bool hasAssignmentOperator () const override
bool hasCTypes () const override
bool hasCastOperator () const override
bool hasDebugInfo () const override
bool hasEH () const override
bool hasEHa () const override
bool hasInlAsm () const override
bool hasInlineAttribute () const override
bool hasInterruptReturn () const override
bool hasFramePointer () const override
bool hasLongJump () const override
bool hasManagedCode () const override
bool hasNestedTypes () const override
bool hasNoInlineAttribute () const override
bool hasNoReturnAttribute () const override
bool hasOptimizedCodeDebugInfo () const override
bool hasOverloadedOperator () const override
bool hasSEH () const override
bool hasSecurityChecks () const override
bool hasSetJump () const override
bool hasStrictGSCheck () const override
bool isAcceleratorGroupSharedLocal () const override
bool isAcceleratorPointerTagLiveRange () const override
bool isAcceleratorStubFunction () const override
bool isAggregated () const override
bool isIntroVirtualFunction () const override
bool isCVTCIL () const override
bool isConstructorVirtualBase () const override
bool isCxxReturnUdt () const override
bool isDataAligned () const override
bool isHLSLData () const override
bool isHotpatchable () const override
bool isIndirectVirtualBaseClass () const override
bool isInterfaceUdt () const override
bool isIntrinsic () const override
bool isLTCG () const override
bool isLocationControlFlowDependent () const override
bool isMSILNetmodule () const override
bool isMatrixRowMajor () const override
bool isManagedCode () const override
bool isMSILCode () const override
bool isMultipleInheritance () const override
bool isNaked () const override
bool isNested () const override
bool isOptimizedAway () const override
bool isPacked () const override
bool isPointerBasedOnSymbolValue () const override
bool isPointerToDataMember () const override
bool isPointerToMemberFunction () const override
bool isPureVirtual () const override
bool isRValueReference () const override
bool isRefUdt () const override
bool isReference () const override
bool isRestrictedType () const override
bool isReturnValue () const override
bool isSafeBuffers () const override
bool isScoped () const override
bool isSdl () const override
bool isSingleInheritance () const override
bool isSplitted () const override
bool isStatic () const override
bool hasPrivateSymbols () const override
bool isUnalignedType () const override
bool isUnreached () const override
bool isValueUdt () const override
bool isVirtual () const override
bool isVirtualBaseClass () const override
bool isVirtualInheritance () const override
bool isVolatileType () const override
bool wasInlined () const override
std::string getUnused () const override
Detailed Description
Definition at line 18 of file DIARawSymbol.h.
Constructor & Destructor Documentation
DIARawSymbol::DIARawSymbol (const DIASession & PDBSession, CComPtr< IDiaSymbol > DiaSymbol)
Definition at line 175 of file DIARawSymbol.cpp.
Member Function Documentation
void DIARawSymbol::dump (raw_ostream & OS, int Indent) const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 182 of file DIARawSymbol.cpp.
References RAW_METHOD_DUMP.
std::unique_ptr< IPDBEnumSymbols > DIARawSymbol::findChildren (PDB_SymType Type) const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 352 of file DIARawSymbol.cpp.
std::unique_ptr< IPDBEnumSymbols > DIARawSymbol::findChildren (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags) const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 363 of file DIARawSymbol.cpp.
References llvm::convertUTF8ToUTF16String(), and llvm::SmallVectorTemplateCommon< T >::data().
std::unique_ptr< IPDBEnumSymbols > DIARawSymbol::findChildrenByRVA (PDB_SymType Type, StringRef Name, PDB_NameSearchFlags Flags, uint32_t RVA) const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 381 of file DIARawSymbol.cpp.
References llvm::convertUTF8ToUTF16String(), and llvm::SmallVectorTemplateCommon< T >::data().
std::unique_ptr< IPDBEnumSymbols > DIARawSymbol::findInlineFramesByRVA (uint32_t RVA) const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 400 of file DIARawSymbol.cpp.
PDB_MemberAccess DIARawSymbol::getAccess () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 420 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getAddressOffset () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 425 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getAddressSection () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 429 of file DIARawSymbol.cpp.
bool DIARawSymbol::getAddressTaken () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 795 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getAge () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 433 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getArrayIndexTypeId () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 437 of file DIARawSymbol.cpp.
void DIARawSymbol::getBackEndVersion (VersionInfo & Version) const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 441 of file DIARawSymbol.cpp.
References llvm::VersionInfo::Build, llvm::VersionInfo::Major, llvm::VersionInfo::Minor, and llvm::VersionInfo::QFE.
uint32_t DIARawSymbol::getBaseDataOffset () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 448 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getBaseDataSlot () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 452 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getBaseSymbolId () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 456 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getBitPosition () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 465 of file DIARawSymbol.cpp.
PDB_BuiltinType DIARawSymbol::getBuiltinType () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 460 of file DIARawSymbol.cpp.
PDB_CallingConv DIARawSymbol::getCallingConvention () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 469 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getClassParentId () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 474 of file DIARawSymbol.cpp.
std::string DIARawSymbol::getCompilerName () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 478 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getCount () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 482 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getCountLiveRanges () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 486 of file DIARawSymbol.cpp.
void DIARawSymbol::getDataBytes (llvm::SmallVector< uint8_t, 32 > & bytes) const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 408 of file DIARawSymbol.cpp.
References llvm::SmallVectorImpl< T >::clear(), llvm::SmallVectorTemplateCommon< T, typename >::data(), and llvm::SmallVectorImpl< T >::resize().
PDB_DataKind DIARawSymbol::getDataKind () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 705 of file DIARawSymbol.cpp.
CComPtr<IDiaSymbol> llvm::DIARawSymbol::getDiaSymbol () const [inline]
Definition at line 24 of file DIARawSymbol.h.
Referenced by llvm::DIASession::getSourceFilesForCompiland().
void DIARawSymbol::getFrontEndVersion (VersionInfo & Version) const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 490 of file DIARawSymbol.cpp.
References llvm::VersionInfo::Build, llvm::VersionInfo::Major, llvm::VersionInfo::Minor, and llvm::VersionInfo::QFE.
PDB_UniqueId DIARawSymbol::getGuid () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 715 of file DIARawSymbol.cpp.
PDB_Lang DIARawSymbol::getLanguage () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 497 of file DIARawSymbol.cpp.
uint64_t DIARawSymbol::getLength () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 746 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getLexicalParentId () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 501 of file DIARawSymbol.cpp.
std::string DIARawSymbol::getLibraryName () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 505 of file DIARawSymbol.cpp.
uint64_t DIARawSymbol::getLiveRangeLength () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 750 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getLiveRangeStartAddressOffset () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 509 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getLiveRangeStartAddressSection () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 514 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getLiveRangeStartRelativeVirtualAddress () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 519 of file DIARawSymbol.cpp.
PDB_RegisterId DIARawSymbol::getLocalBasePointerRegisterId () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 524 of file DIARawSymbol.cpp.
PDB_LocType DIARawSymbol::getLocationType () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 731 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getLowerBoundId () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 529 of file DIARawSymbol.cpp.
PDB_Machine DIARawSymbol::getMachineType () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 736 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getMemorySpaceKind () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 533 of file DIARawSymbol.cpp.
std::string DIARawSymbol::getName () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 537 of file DIARawSymbol.cpp.
bool DIARawSymbol::getNoStackOrdering () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 799 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getNumberOfAcceleratorPointerTags () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 541 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getNumberOfColumns () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 546 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getNumberOfModifiers () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 550 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getNumberOfRegisterIndices () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 554 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getNumberOfRows () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 558 of file DIARawSymbol.cpp.
std::string DIARawSymbol::getObjectFileName () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 562 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getOemId () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 566 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getOemSymbolId () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 570 of file DIARawSymbol.cpp.
int32_t DIARawSymbol::getOffset () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 719 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getOffsetInUdt () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 574 of file DIARawSymbol.cpp.
PDB_Cpu DIARawSymbol::getPlatform () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 578 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getRank () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 582 of file DIARawSymbol.cpp.
PDB_RegisterId DIARawSymbol::getRegisterId () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 586 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getRegisterType () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 591 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getRelativeVirtualAddress () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 595 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getSamplerSlot () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 599 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getSignature () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 603 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getSizeInUdt () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 607 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getSlot () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 611 of file DIARawSymbol.cpp.
std::string DIARawSymbol::getSourceFileName () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 615 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getStride () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 619 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getSubTypeId () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 623 of file DIARawSymbol.cpp.
std::string DIARawSymbol::getSymbolsFileName () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 627 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getSymIndexId () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 631 of file DIARawSymbol.cpp.
PDB_SymType DIARawSymbol::getSymTag () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 710 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getTargetOffset () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 635 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getTargetRelativeVirtualAddress () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 639 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getTargetSection () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 648 of file DIARawSymbol.cpp.
uint64_t DIARawSymbol::getTargetVirtualAddress () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 644 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getTextureSlot () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 652 of file DIARawSymbol.cpp.
int32_t DIARawSymbol::getThisAdjust () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 723 of file DIARawSymbol.cpp.
PDB_ThunkOrdinal DIARawSymbol::getThunkOrdinal () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 741 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getTimeStamp () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 656 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getToken () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 660 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getTypeId () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 664 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getUavSlot () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 668 of file DIARawSymbol.cpp.
PDB_UdtType DIARawSymbol::getUdtKind () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 758 of file DIARawSymbol.cpp.
std::string DIARawSymbol::getUndecoratedName () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 672 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getUnmodifiedTypeId () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 676 of file DIARawSymbol.cpp.
std::string DIARawSymbol::getUnused () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 1093 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getUpperBoundId () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 680 of file DIARawSymbol.cpp.
Variant DIARawSymbol::getValue () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 684 of file DIARawSymbol.cpp.
References llvm::Variant.
uint64_t DIARawSymbol::getVirtualAddress () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 754 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getVirtualBaseDispIndex () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 693 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getVirtualBaseOffset () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 697 of file DIARawSymbol.cpp.
int32_t DIARawSymbol::getVirtualBasePointerOffset () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 727 of file DIARawSymbol.cpp.
uint32_t DIARawSymbol::getVirtualTableShapeId () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 701 of file DIARawSymbol.cpp.
bool DIARawSymbol::hasAlloca () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 803 of file DIARawSymbol.cpp.
bool DIARawSymbol::hasAssignmentOperator () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 807 of file DIARawSymbol.cpp.
bool DIARawSymbol::hasCastOperator () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 815 of file DIARawSymbol.cpp.
bool DIARawSymbol::hasConstructor () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 763 of file DIARawSymbol.cpp.
bool DIARawSymbol::hasCTypes () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 811 of file DIARawSymbol.cpp.
bool DIARawSymbol::hasCustomCallingConvention () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 767 of file DIARawSymbol.cpp.
bool DIARawSymbol::hasDebugInfo () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 819 of file DIARawSymbol.cpp.
bool DIARawSymbol::hasEH () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 823 of file DIARawSymbol.cpp.
bool DIARawSymbol::hasEHa () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 827 of file DIARawSymbol.cpp.
bool DIARawSymbol::hasFarReturn () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 771 of file DIARawSymbol.cpp.
bool DIARawSymbol::hasFramePointer () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 843 of file DIARawSymbol.cpp.
bool DIARawSymbol::hasInlAsm () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 831 of file DIARawSymbol.cpp.
bool DIARawSymbol::hasInlineAttribute () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 835 of file DIARawSymbol.cpp.
bool DIARawSymbol::hasInterruptReturn () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 839 of file DIARawSymbol.cpp.
bool DIARawSymbol::hasLongJump () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 847 of file DIARawSymbol.cpp.
bool DIARawSymbol::hasManagedCode () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 851 of file DIARawSymbol.cpp.
bool DIARawSymbol::hasNestedTypes () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 855 of file DIARawSymbol.cpp.
bool DIARawSymbol::hasNoInlineAttribute () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 859 of file DIARawSymbol.cpp.
bool DIARawSymbol::hasNoReturnAttribute () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 863 of file DIARawSymbol.cpp.
bool DIARawSymbol::hasOptimizedCodeDebugInfo () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 867 of file DIARawSymbol.cpp.
bool DIARawSymbol::hasOverloadedOperator () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 871 of file DIARawSymbol.cpp.
bool DIARawSymbol::hasPrivateSymbols () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 1055 of file DIARawSymbol.cpp.
bool DIARawSymbol::hasSecurityChecks () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 879 of file DIARawSymbol.cpp.
bool DIARawSymbol::hasSEH () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 875 of file DIARawSymbol.cpp.
bool DIARawSymbol::hasSetJump () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 883 of file DIARawSymbol.cpp.
bool DIARawSymbol::hasStrictGSCheck () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 887 of file DIARawSymbol.cpp.
bool DIARawSymbol::isAcceleratorGroupSharedLocal () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 891 of file DIARawSymbol.cpp.
bool DIARawSymbol::isAcceleratorPointerTagLiveRange () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 896 of file DIARawSymbol.cpp.
bool DIARawSymbol::isAcceleratorStubFunction () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 901 of file DIARawSymbol.cpp.
bool DIARawSymbol::isAggregated () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 905 of file DIARawSymbol.cpp.
bool DIARawSymbol::isCode () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 775 of file DIARawSymbol.cpp.
bool DIARawSymbol::isCompilerGenerated () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 779 of file DIARawSymbol.cpp.
bool DIARawSymbol::isConstructorVirtualBase () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 917 of file DIARawSymbol.cpp.
bool DIARawSymbol::isConstType () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 783 of file DIARawSymbol.cpp.
bool DIARawSymbol::isCVTCIL () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 913 of file DIARawSymbol.cpp.
bool DIARawSymbol::isCxxReturnUdt () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 921 of file DIARawSymbol.cpp.
bool DIARawSymbol::isDataAligned () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 925 of file DIARawSymbol.cpp.
bool DIARawSymbol::isEditAndContinueEnabled () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 787 of file DIARawSymbol.cpp.
bool DIARawSymbol::isFunction () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 791 of file DIARawSymbol.cpp.
bool DIARawSymbol::isHLSLData () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 929 of file DIARawSymbol.cpp.
bool DIARawSymbol::isHotpatchable () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 933 of file DIARawSymbol.cpp.
bool DIARawSymbol::isIndirectVirtualBaseClass () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 937 of file DIARawSymbol.cpp.
bool DIARawSymbol::isInterfaceUdt () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 941 of file DIARawSymbol.cpp.
bool DIARawSymbol::isIntrinsic () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 945 of file DIARawSymbol.cpp.
bool DIARawSymbol::isIntroVirtualFunction () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 909 of file DIARawSymbol.cpp.
bool DIARawSymbol::isLocationControlFlowDependent () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 953 of file DIARawSymbol.cpp.
bool DIARawSymbol::isLTCG () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 949 of file DIARawSymbol.cpp.
bool DIARawSymbol::isManagedCode () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 966 of file DIARawSymbol.cpp.
bool DIARawSymbol::isMatrixRowMajor () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 962 of file DIARawSymbol.cpp.
bool DIARawSymbol::isMSILCode () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 970 of file DIARawSymbol.cpp.
bool DIARawSymbol::isMSILNetmodule () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 958 of file DIARawSymbol.cpp.
bool DIARawSymbol::isMultipleInheritance () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 974 of file DIARawSymbol.cpp.
bool DIARawSymbol::isNaked () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 978 of file DIARawSymbol.cpp.
bool DIARawSymbol::isNested () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 982 of file DIARawSymbol.cpp.
bool DIARawSymbol::isOptimizedAway () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 986 of file DIARawSymbol.cpp.
bool DIARawSymbol::isPacked () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 990 of file DIARawSymbol.cpp.
bool DIARawSymbol::isPointerBasedOnSymbolValue () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 994 of file DIARawSymbol.cpp.
bool DIARawSymbol::isPointerToDataMember () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 999 of file DIARawSymbol.cpp.
bool DIARawSymbol::isPointerToMemberFunction () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 1003 of file DIARawSymbol.cpp.
bool DIARawSymbol::isPureVirtual () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 1007 of file DIARawSymbol.cpp.
bool DIARawSymbol::isReference () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 1019 of file DIARawSymbol.cpp.
bool DIARawSymbol::isRefUdt () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 1015 of file DIARawSymbol.cpp.
bool DIARawSymbol::isRestrictedType () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 1023 of file DIARawSymbol.cpp.
bool DIARawSymbol::isReturnValue () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 1027 of file DIARawSymbol.cpp.
bool DIARawSymbol::isRValueReference () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 1011 of file DIARawSymbol.cpp.
bool DIARawSymbol::isSafeBuffers () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 1031 of file DIARawSymbol.cpp.
bool DIARawSymbol::isScoped () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 1035 of file DIARawSymbol.cpp.
bool DIARawSymbol::isSdl () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 1039 of file DIARawSymbol.cpp.
bool DIARawSymbol::isSingleInheritance () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 1043 of file DIARawSymbol.cpp.
bool DIARawSymbol::isSplitted () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 1047 of file DIARawSymbol.cpp.
bool DIARawSymbol::isStatic () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 1051 of file DIARawSymbol.cpp.
bool DIARawSymbol::isUnalignedType () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 1061 of file DIARawSymbol.cpp.
bool DIARawSymbol::isUnreached () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 1065 of file DIARawSymbol.cpp.
bool DIARawSymbol::isValueUdt () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 1069 of file DIARawSymbol.cpp.
bool DIARawSymbol::isVirtual () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 1073 of file DIARawSymbol.cpp.
bool DIARawSymbol::isVirtualBaseClass () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 1077 of file DIARawSymbol.cpp.
bool DIARawSymbol::isVirtualInheritance () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 1081 of file DIARawSymbol.cpp.
bool DIARawSymbol::isVolatileType () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 1085 of file DIARawSymbol.cpp.
bool DIARawSymbol::wasInlined () const [override, virtual]
Implements llvm::IPDBRawSymbol.
Definition at line 1089 of file DIARawSymbol.cpp.
The documentation for this class was generated from the following files:
DIARawSymbol.h
DIARawSymbol.cpp