LLVM: llvm::MCRegUnitMaskIterator Class Reference
llvm::MCRegUnitMaskIterator Class Reference
MCRegUnitIterator enumerates a list of register units and their associated lane masks for Reg.
#include <MCRegisterInfo.h>
Public Member Functions
MCRegUnitMaskIterator ()
MCRegUnitMaskIterator (unsigned Reg, const MCRegisterInfo *MCRI)
Constructs an iterator that traverses the register units and their associated LaneMasks in Reg.
std::pair< unsigned, unsigned > operator* () const
Returns a (RegUnit, LaneMask) pair.
bool isValid () const
Returns true if this iterator is not yet at the end.
void operator++ ()
Moves to the next position.
Detailed Description
MCRegUnitIterator enumerates a list of register units and their associated lane masks for Reg.
The register units are in ascending numerical order.
Definition at line 560 of file MCRegisterInfo.h.
Constructor & Destructor Documentation
llvm::MCRegUnitMaskIterator::MCRegUnitMaskIterator () [inline]
Definition at line 564 of file MCRegisterInfo.h.
llvm::MCRegUnitMaskIterator::MCRegUnitMaskIterator (unsigned Reg, const MCRegisterInfo * MCRI) [inline]
Constructs an iterator that traverses the register units and their associated LaneMasks in Reg.
Definition at line 567 of file MCRegisterInfo.h.
References llvm::MCRegisterInfo::get(), and llvm::MCRegisterDesc::RegUnitLaneMasks.
Member Function Documentation
bool llvm::MCRegUnitMaskIterator::isValid () const [inline]
Returns true if this iterator is not yet at the end.
Definition at line 579 of file MCRegisterInfo.h.
References llvm::MCRegisterInfo::DiffListIterator::isValid().
Referenced by foreachUnit().
std::pair<unsigned,unsigned> llvm::MCRegUnitMaskIterator::operator* () const [inline]
Returns a (RegUnit, LaneMask) pair.
Definition at line 574 of file MCRegisterInfo.h.
void llvm::MCRegUnitMaskIterator::operator++ () [inline]
Moves to the next position.
Definition at line 582 of file MCRegisterInfo.h.
The documentation for this class was generated from the following file:
MCRegisterInfo.h