LLVM: llvm::RuntimeDyldMachOX86_64 Class Reference
llvm::RuntimeDyldMachOX86_64 Class Reference
#include <RuntimeDyldMachOX86_64.h>
Public Types
typedef uint64_t TargetPtrT
Public Member Functions
RuntimeDyldMachOX86_64 (RuntimeDyld::MemoryManager &MM, RuntimeDyld::SymbolResolver &Resolver)
unsigned getMaxStubSize () override
unsigned getStubAlignment () override
relocation_iterator processRelocationRef (unsigned SectionID, relocation_iterator RelI, const ObjectFile &BaseObjT, ObjSectionToIDMap &ObjSectionToID, StubMap &Stubs) override
Parses one or more object file relocations (some object files use relocation pairs) and stores it to Relocations or SymbolRelocations (this depends on the object file type).
void resolveRelocation (const RelocationEntry &RE, uint64_t Value) override
A object file specific relocation resolver.
void finalizeSection (const ObjectFile &Obj, unsigned SectionID, const SectionRef &Section)
Detailed Description
Definition at line 19 of file RuntimeDyldMachOX86_64.h.
Member Typedef Documentation
typedef uint64_t llvm::RuntimeDyldMachOX86_64::TargetPtrT
Definition at line 23 of file RuntimeDyldMachOX86_64.h.
Constructor & Destructor Documentation
llvm::RuntimeDyldMachOX86_64::RuntimeDyldMachOX86_64 (RuntimeDyld::MemoryManager & MM, RuntimeDyld::SymbolResolver & Resolver) [inline]
Definition at line 25 of file RuntimeDyldMachOX86_64.h.
Member Function Documentation
void llvm::RuntimeDyldMachOX86_64::finalizeSection (const ObjectFile & Obj, unsigned SectionID, const SectionRef & Section) [inline]
Definition at line 102 of file RuntimeDyldMachOX86_64.h.
unsigned llvm::RuntimeDyldMachOX86_64::getMaxStubSize () [inline, override, virtual]
Implements llvm::RuntimeDyldImpl.
Definition at line 29 of file RuntimeDyldMachOX86_64.h.
unsigned llvm::RuntimeDyldMachOX86_64::getStubAlignment () [inline, override, virtual]
Implements llvm::RuntimeDyldImpl.
Definition at line 31 of file RuntimeDyldMachOX86_64.h.
relocation_iterator llvm::RuntimeDyldMachOX86_64::processRelocationRef (unsigned SectionID, relocation_iterator RelI, const ObjectFile & Obj, ObjSectionToIDMap & ObjSectionToID, StubMap & Stubs) [inline, override, virtual]
Parses one or more object file relocations (some object files use relocation pairs) and stores it to Relocations or SymbolRelocations (this depends on the object file type).
Returns:
Iterator to the next relocation that needs to be parsed.
Implements llvm::RuntimeDyldImpl.
Definition at line 34 of file RuntimeDyldMachOX86_64.h.
References llvm::RuntimeDyldImpl::addRelocationForSection(), llvm::RuntimeDyldImpl::addRelocationForSymbol(), llvm::object::MachOObjectFile::getPlainRelocationExternal(), llvm::object::MachOObjectFile::getRelocation(), llvm::RuntimeDyldMachO::getRelocationEntry(), llvm::RuntimeDyldMachO::getRelocationValueRef(), llvm::object::MachOObjectFile::isRelocationScattered(), llvm::RuntimeDyldMachO::makeValueAddendPCRel(), llvm::RuntimeDyldMachO::memcpyAddend(), llvm::RelocationValueRef::Offset, llvm::RelocationValueRef::SectionID, llvm::RelocationValueRef::SymbolName, llvm::MachO::X86_64_RELOC_GOT, and llvm::MachO::X86_64_RELOC_GOT_LOAD.
void llvm::RuntimeDyldMachOX86_64::resolveRelocation (const RelocationEntry & RE, uint64_t Value) [inline, override, virtual]
A object file specific relocation resolver.
Parameters:
RE The relocation to be resolved
Value Target symbol address to apply the relocation action
Implements llvm::RuntimeDyldImpl.
Definition at line 69 of file RuntimeDyldMachOX86_64.h.
References llvm::RelocationEntry::Addend, llvm::SectionEntry::Address, DEBUG, llvm::RuntimeDyldMachO::dumpRelocationToResolve(), llvm::RuntimeDyldImpl::Error(), llvm::RelocationEntry::IsPCRel, llvm_unreachable, llvm::SectionEntry::LoadAddress, llvm::RelocationEntry::Offset, llvm::RelocationEntry::RelType, llvm::ARMBuildAttrs::Section, llvm::RelocationEntry::SectionID, llvm::RuntimeDyldImpl::Sections, llvm::RelocationEntry::Size, llvm::RuntimeDyldImpl::writeBytesUnaligned(), llvm::MachO::X86_64_RELOC_BRANCH, llvm::MachO::X86_64_RELOC_GOT, llvm::MachO::X86_64_RELOC_GOT_LOAD, llvm::MachO::X86_64_RELOC_SIGNED, llvm::MachO::X86_64_RELOC_SIGNED_1, llvm::MachO::X86_64_RELOC_SIGNED_2, llvm::MachO::X86_64_RELOC_SIGNED_4, llvm::MachO::X86_64_RELOC_SUBTRACTOR, llvm::MachO::X86_64_RELOC_TLV, and llvm::MachO::X86_64_RELOC_UNSIGNED.
The documentation for this class was generated from the following file:
RuntimeDyldMachOX86_64.h