LLVM: llvm::StringInit Class Reference
llvm::StringInit Class Reference
StringInit - "foo" - Represent an initialization by a string value.
#include <Record.h>
Public Member Functions
const std::string & getValue () const
Init * convertInitializerTo (RecTy *Ty) const override
convertInitializerTo - This virtual function converts to the appropriate Init based on the passed in type.
std::string getAsString () const override
getAsString - Convert this value to a string form.
std::string getAsUnquotedString () const override
getAsUnquotedString - Convert this value to a string form, without adding quote markers.
Init * resolveListElementReference (Record &R, const RecordVal *RV, unsigned Elt) const override
resolveListElementReference - This method is used to implement VarListElementInit::resolveReferences.
Init * getBit (unsigned Bit) const override
getBit - This method is used to return the initializer for the specified bit.
Static Public Member Functions
static bool classof (const Init *I)
static StringInit * get (StringRef)
Detailed Description
StringInit - "foo" - Represent an initialization by a string value.
Definition at line 547 of file Record.h.
Member Function Documentation
static bool llvm::StringInit::classof (const Init * I) [inline, static]
Reimplemented from llvm::TypedInit.
Definition at line 557 of file Record.h.
References llvm::Init::getKind(), and llvm::Init::IK_StringInit.
Init * StringInit::convertInitializerTo (RecTy * Ty) const [override, virtual]
convertInitializerTo - This virtual function converts to the appropriate Init based on the passed in type.
Reimplemented from llvm::TypedInit.
Definition at line 461 of file Record.cpp.
StringInit * StringInit::get (StringRef V) [static]
Definition at line 453 of file Record.cpp.
References I.
Referenced by llvm::Record::addTemplateArg(), llvm::UnOpInit::Fold(), llvm::Record::getValue(), llvm::Record::isTemplateArg(), llvm::QualifyName(), llvm::Record::removeValue(), and llvm::Record::setName().
std::string llvm::StringInit::getAsString () const [inline, override, virtual]
getAsString - Convert this value to a string form.
Implements llvm::Init.
Definition at line 566 of file Record.h.
std::string llvm::StringInit::getAsUnquotedString () const [inline, override, virtual]
getAsUnquotedString - Convert this value to a string form, without adding quote markers.
This primaruly affects StringInits where we will not surround the string value with quotes.
Reimplemented from llvm::Init.
Definition at line 567 of file Record.h.
Init* llvm::StringInit::getBit (unsigned Bit) const [inline, override, virtual]
getBit - This method is used to return the initializer for the specified bit.
Implements llvm::Init.
Definition at line 577 of file Record.h.
References llvm_unreachable.
const std::string& llvm::StringInit::getValue () const [inline]
Definition at line 562 of file Record.h.
Referenced by llvm::BinOpInit::Fold(), and llvm::VarInit::getName().
Init* llvm::StringInit::resolveListElementReference (Record & R, const RecordVal * RV, unsigned Elt) const [inline, override, virtual]
resolveListElementReference - This method is used to implement VarListElementInit::resolveReferences.
If the list element is resolvable now, we return the resolved value, otherwise we return null.
Implements llvm::TypedInit.
Definition at line 572 of file Record.h.
References llvm_unreachable.
The documentation for this class was generated from the following files:
Record.h
Record.cpp