LLVM: llvm::FoldingSetNodeIDRef Class Reference
llvm::FoldingSetNodeIDRef Class Reference
FoldingSetNodeIDRef - This class describes a reference to an interned FoldingSetNodeID, which can be a useful to store node id data rather than using plain FoldingSetNodeIDs, since the 32-element SmallVector is often much larger than necessary, and the possibility of heap allocation means it requires a non-trivial destructor call.
#include <FoldingSet.h>
Public Member Functions
FoldingSetNodeIDRef ()
FoldingSetNodeIDRef (const unsigned *D, size_t S)
unsigned ComputeHash () const
ComputeHash - Compute a strong hash value for this FoldingSetNodeIDRef, used to lookup the node in the FoldingSetImpl.
bool operator== (FoldingSetNodeIDRef) const
bool operator!= (FoldingSetNodeIDRef RHS) const
bool operator< (FoldingSetNodeIDRef) const
Used to compare the "ordering" of two nodes as defined by the profiled bits and their ordering defined by memcmp().
const unsigned * getData () const
size_t getSize () const
Detailed Description
FoldingSetNodeIDRef - This class describes a reference to an interned FoldingSetNodeID, which can be a useful to store node id data rather than using plain FoldingSetNodeIDs, since the 32-element SmallVector is often much larger than necessary, and the possibility of heap allocation means it requires a non-trivial destructor call.
Definition at line 269 of file FoldingSet.h.
Constructor & Destructor Documentation
llvm::FoldingSetNodeIDRef::FoldingSetNodeIDRef () [inline]
Definition at line 273 of file FoldingSet.h.
llvm::FoldingSetNodeIDRef::FoldingSetNodeIDRef (const unsigned * D, size_t S) [inline]
Definition at line 274 of file FoldingSet.h.
Member Function Documentation
unsigned FoldingSetNodeIDRef::ComputeHash () const
ComputeHash - Compute a strong hash value for this FoldingSetNodeIDRef, used to lookup the node in the FoldingSetImpl.
Definition at line 30 of file FoldingSet.cpp.
References llvm::hash_combine_range().
Referenced by llvm::FoldingSetTrait< SCEV >::ComputeHash(), and llvm::SDVTListNode::SDVTListNode().
const unsigned* llvm::FoldingSetNodeIDRef::getData () const [inline]
Definition at line 288 of file FoldingSet.h.
size_t llvm::FoldingSetNodeIDRef::getSize () const [inline]
Definition at line 289 of file FoldingSet.h.
bool llvm::FoldingSetNodeIDRef::operator!= (FoldingSetNodeIDRef RHS) const [inline]
Definition at line 282 of file FoldingSet.h.
bool FoldingSetNodeIDRef::operator< (FoldingSetNodeIDRef RHS) const
Used to compare the "ordering" of two nodes as defined by the profiled bits and their ordering defined by memcmp().
Definition at line 41 of file FoldingSet.cpp.
bool FoldingSetNodeIDRef::operator== (FoldingSetNodeIDRef RHS) const
Definition at line 34 of file FoldingSet.cpp.
The documentation for this class was generated from the following files:
FoldingSet.h
FoldingSet.cpp