LLVM: llvm::GCOVBuffer Class Reference
llvm::GCOVBuffer Class Reference
GCOVBuffer - A wrapper around MemoryBuffer to provide GCOV specific read operations.
#include <GCOV.h>
Public Member Functions
GCOVBuffer (MemoryBuffer *B)
bool readGCNOFormat ()
readGCNOFormat - Check GCNO signature is valid at the beginning of buffer.
bool readGCDAFormat ()
readGCDAFormat - Check GCDA signature is valid at the beginning of buffer.
bool readGCOVVersion (GCOV::GCOVVersion &Version)
readGCOVVersion - Read GCOV version.
bool readFunctionTag ()
readFunctionTag - If cursor points to a function tag then increment the cursor and return true otherwise return false.
bool readBlockTag ()
readBlockTag - If cursor points to a block tag then increment the cursor and return true otherwise return false.
bool readEdgeTag ()
readEdgeTag - If cursor points to an edge tag then increment the cursor and return true otherwise return false.
bool readLineTag ()
readLineTag - If cursor points to a line tag then increment the cursor and return true otherwise return false.
bool readArcTag ()
readArcTag - If cursor points to an gcda arc tag then increment the cursor and return true otherwise return false.
bool readObjectTag ()
readObjectTag - If cursor points to an object summary tag then increment the cursor and return true otherwise return false.
bool readProgramTag ()
readProgramTag - If cursor points to a program summary tag then increment the cursor and return true otherwise return false.
bool readInt (uint32_t &Val)
bool readInt64 (uint64_t &Val)
bool readString (StringRef &Str)
uint64_t getCursor () const
void advanceCursor (uint32_t n)
Detailed Description
GCOVBuffer - A wrapper around MemoryBuffer to provide GCOV specific read operations.
Definition at line 54 of file GCOV.h.
Constructor & Destructor Documentation
llvm::GCOVBuffer::GCOVBuffer (MemoryBuffer * B) [inline]
Definition at line 56 of file GCOV.h.
Member Function Documentation
void llvm::GCOVBuffer::advanceCursor (uint32_t n) [inline]
Definition at line 218 of file GCOV.h.
Referenced by llvm::GCOVFile::readGCDA().
uint64_t llvm::GCOVBuffer::getCursor () const [inline]
Definition at line 217 of file GCOV.h.
Referenced by llvm::GCOVFunction::readGCNO().
bool llvm::GCOVBuffer::readArcTag () [inline]
readArcTag - If cursor points to an gcda arc tag then increment the cursor and return true otherwise return false.
Definition at line 147 of file GCOV.h.
References llvm::StringRef::empty(), llvm::MemoryBuffer::getBuffer(), and llvm::StringRef::slice().
Referenced by llvm::GCOVFunction::readGCDA().
bool llvm::GCOVBuffer::readBlockTag () [inline]
readBlockTag - If cursor points to a block tag then increment the cursor and return true otherwise return false.
Definition at line 111 of file GCOV.h.
References llvm::StringRef::empty(), llvm::MemoryBuffer::getBuffer(), and llvm::StringRef::slice().
Referenced by llvm::GCOVFunction::readGCNO().
bool llvm::GCOVBuffer::readEdgeTag () [inline]
readEdgeTag - If cursor points to an edge tag then increment the cursor and return true otherwise return false.
Definition at line 123 of file GCOV.h.
References llvm::StringRef::empty(), llvm::MemoryBuffer::getBuffer(), and llvm::StringRef::slice().
Referenced by llvm::GCOVFunction::readGCNO().
bool llvm::GCOVBuffer::readFunctionTag () [inline]
readFunctionTag - If cursor points to a function tag then increment the cursor and return true otherwise return false.
Definition at line 99 of file GCOV.h.
References llvm::StringRef::empty(), llvm::MemoryBuffer::getBuffer(), and llvm::StringRef::slice().
Referenced by llvm::GCOVFile::readGCDA(), and llvm::GCOVFile::readGCNO().
bool llvm::GCOVBuffer::readGCDAFormat () [inline]
readGCDAFormat - Check GCDA signature is valid at the beginning of buffer.
Definition at line 70 of file GCOV.h.
References llvm::errs(), llvm::ARMBuildAttrs::File, llvm::MemoryBuffer::getBuffer(), and llvm::StringRef::slice().
Referenced by llvm::GCOVFile::readGCDA().
bool llvm::GCOVBuffer::readGCNOFormat () [inline]
readGCNOFormat - Check GCNO signature is valid at the beginning of buffer.
Definition at line 59 of file GCOV.h.
References llvm::errs(), llvm::ARMBuildAttrs::File, llvm::MemoryBuffer::getBuffer(), and llvm::StringRef::slice().
Referenced by llvm::GCOVFile::readGCNO().
bool llvm::GCOVBuffer::readGCOVVersion (GCOV::GCOVVersion & Version) [inline]
readGCOVVersion - Read GCOV version.
Definition at line 81 of file GCOV.h.
References llvm::errs(), llvm::MemoryBuffer::getBuffer(), llvm::StringRef::slice(), llvm::GCOV::V402, and llvm::GCOV::V404.
Referenced by llvm::GCOVFile::readGCDA(), and llvm::GCOVFile::readGCNO().
bool llvm::GCOVBuffer::readInt (uint32_t & Val) [inline]
Definition at line 181 of file GCOV.h.
References llvm::StringRef::data(), llvm::errs(), llvm::MemoryBuffer::getBuffer(), llvm::StringRef::size(), and llvm::StringRef::slice().
Referenced by llvm::GCOVFile::readGCDA(), llvm::GCOVFunction::readGCDA(), llvm::GCOVFile::readGCNO(), llvm::GCOVFunction::readGCNO(), readInt64(), and readString().
bool llvm::GCOVBuffer::readInt64 (uint64_t & Val) [inline]
Definition at line 192 of file GCOV.h.
References llvm::MipsISD::Hi, llvm::MipsISD::Lo, and readInt().
Referenced by llvm::GCOVFunction::readGCDA().
bool llvm::GCOVBuffer::readLineTag () [inline]
readLineTag - If cursor points to a line tag then increment the cursor and return true otherwise return false.
Definition at line 135 of file GCOV.h.
References llvm::StringRef::empty(), llvm::MemoryBuffer::getBuffer(), and llvm::StringRef::slice().
Referenced by llvm::GCOVFunction::readGCNO().
bool llvm::GCOVBuffer::readObjectTag () [inline]
readObjectTag - If cursor points to an object summary tag then increment the cursor and return true otherwise return false.
Definition at line 159 of file GCOV.h.
References llvm::StringRef::empty(), llvm::MemoryBuffer::getBuffer(), and llvm::StringRef::slice().
Referenced by llvm::GCOVFile::readGCDA().
bool llvm::GCOVBuffer::readProgramTag () [inline]
readProgramTag - If cursor points to a program summary tag then increment the cursor and return true otherwise return false.
Definition at line 171 of file GCOV.h.
References llvm::StringRef::empty(), llvm::MemoryBuffer::getBuffer(), and llvm::StringRef::slice().
Referenced by llvm::GCOVFile::readGCDA().
bool llvm::GCOVBuffer::readString (StringRef & Str) [inline]
Definition at line 200 of file GCOV.h.
References llvm::errs(), llvm::MemoryBuffer::getBuffer(), readInt(), llvm::StringRef::size(), llvm::StringRef::slice(), and llvm::StringRef::split().
Referenced by llvm::GCOVFunction::readGCDA(), and llvm::GCOVFunction::readGCNO().
The documentation for this class was generated from the following file:
GCOV.h