LLVM: llvm::DebugLocEntry Class Reference
llvm::DebugLocEntry Class Reference
This struct describes location entries emitted in the .debug_loc section.
#include <DebugLocEntry.h>
Classes
struct Value
A single location or constant.
Public Member Functions
DebugLocEntry (const MCSymbol *B, const MCSymbol *E, Value Val)
bool MergeValues (const DebugLocEntry &Next)
If this and Next are describing different pieces of the same variable, merge them by appending Next's values to the current list of values.
bool MergeRanges (const DebugLocEntry &Next)
Attempt to merge this DebugLocEntry with Next and return true if the merge was successful.
const MCSymbol * getBeginSym () const
const MCSymbol * getEndSym () const
ArrayRef< Value > getValues () const
void addValues (ArrayRef< DebugLocEntry::Value > Vals)
void sortUniqueValues ()
void finalize (const AsmPrinter &AP, DebugLocStream::ListBuilder &List, const DIBasicType *BT)
Lower this entry into a DWARF expression.
Detailed Description
This struct describes location entries emitted in the .debug_loc section.
Definition at line 24 of file DebugLocEntry.h.
Constructor & Destructor Documentation
llvm::DebugLocEntry::DebugLocEntry (const MCSymbol * B, const MCSymbol * E, Value Val) [inline]
Definition at line 86 of file DebugLocEntry.h.
References llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Member Function Documentation
void llvm::DebugLocEntry::addValues (ArrayRef< DebugLocEntry::Value > Vals) [inline]
Definition at line 124 of file DebugLocEntry.h.
References llvm::all_of(), llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::ArrayRef< T >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::ArrayRef< T >::end(), and sortUniqueValues().
Referenced by MergeValues().
void DebugLocEntry::finalize (const AsmPrinter & AP, DebugLocStream::ListBuilder & List, const DIBasicType * BT)
Lower this entry into a DWARF expression.
Definition at line 1507 of file DwarfDebug.cpp.
References llvm::all_of(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), emitDebugLocValue(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::DIExpression::getBitPieceOffset(), llvm::DIExpression::getBitPieceSize(), llvm::AsmPrinter::getDwarfDebug(), llvm::DwarfDebug::getDwarfVersion(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::DebugLocStream::EntryBuilder::getStreamer(), llvm::MachineFunction::getSubtarget(), llvm::DebugLocEntry::Value::isBitPiece(), llvm::AsmPrinter::MF, P, and llvm::SmallVectorTemplateCommon< T, typename >::size().
const MCSymbol* llvm::DebugLocEntry::getBeginSym () const [inline]
Definition at line 121 of file DebugLocEntry.h.
const MCSymbol* llvm::DebugLocEntry::getEndSym () const [inline]
Definition at line 122 of file DebugLocEntry.h.
ArrayRef<Value> llvm::DebugLocEntry::getValues () const [inline]
Definition at line 123 of file DebugLocEntry.h.
bool llvm::DebugLocEntry::MergeRanges (const DebugLocEntry & Next) [inline]
Attempt to merge this DebugLocEntry with Next and return true if the merge was successful.
Entries can be merged if they share the same Loc/Constant and if Next immediately follows this Entry.
Definition at line 112 of file DebugLocEntry.h.
bool llvm::DebugLocEntry::MergeValues (const DebugLocEntry & Next) [inline]
If this and Next are describing different pieces of the same variable, merge them by appending Next's values to the current list of values.
Return true if the merge was successful.
Definition at line 95 of file DebugLocEntry.h.
References addValues().
void llvm::DebugLocEntry::sortUniqueValues () [inline]
Definition at line 134 of file DebugLocEntry.h.
References llvm::ARM_PROC::A, llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorImpl< T >::erase(), and llvm::DebugLocEntry::Value::getExpression().
Referenced by addValues().
The documentation for this class was generated from the following files:
DebugLocEntry.h
DwarfDebug.cpp