LLVM: llvm::GlobalObject Class Reference
llvm::GlobalObject Class Reference
#include <GlobalObject.h>
Public Member Functions
unsigned getAlignment () const
void setAlignment (unsigned Align)
unsigned getGlobalObjectSubClassData () const
void setGlobalObjectSubClassData (unsigned Val)
bool hasSection () const
const char * getSection () const
void setSection (StringRef S)
bool hasComdat () const
const Comdat * getComdat () const
Comdat * getComdat ()
void setComdat (Comdat *C)
void copyAttributesFrom (const GlobalValue *Src) override
Copy all additional attributes (those not needed to create a GlobalValue) from the GlobalValue Src to this one.
Static Public Member Functions
static bool classof (const Value *V)
Protected Member Functions
GlobalObject (PointerType *Ty, ValueTy VTy, Use *Ops, unsigned NumOps, LinkageTypes Linkage, const Twine &Name)
Protected Attributes
std::string Section
Comdat * ObjComdat
Static Protected Attributes
static const unsigned AlignmentBits = 5
static const unsigned GlobalObjectSubClassDataBits
Detailed Description
Definition at line 26 of file GlobalObject.h.
Constructor & Destructor Documentation
llvm::GlobalObject::GlobalObject (PointerType * Ty, ValueTy VTy, Use * Ops, unsigned NumOps, LinkageTypes Linkage, const Twine & Name) [inline, protected]
Definition at line 30 of file GlobalObject.h.
References llvm::GlobalValue::setGlobalValueSubClassData().
Member Function Documentation
static bool llvm::GlobalObject::classof (const Value * V) [inline, static]
Reimplemented from llvm::GlobalValue.
Reimplemented in llvm::Function, and llvm::GlobalVariable.
Definition at line 68 of file GlobalObject.h.
References llvm::Value::getValueID().
void GlobalObject::copyAttributesFrom (const GlobalValue * Src) [override, virtual]
Copy all additional attributes (those not needed to create a GlobalValue) from the GlobalValue Src to this one.
copyAttributesFrom - copy all additional attributes (those not needed to create a GlobalValue) from the GlobalValue Src to this one.
Reimplemented from llvm::GlobalValue.
Reimplemented in llvm::Function, and llvm::GlobalVariable.
Definition at line 99 of file Globals.cpp.
References setAlignment(), and setSection().
unsigned llvm::GlobalObject::getAlignment () const [inline]
Reimplemented from llvm::GlobalValue.
Definition at line 46 of file GlobalObject.h.
References llvm::Data, and llvm::GlobalValue::getGlobalValueSubClassData().
Referenced by llvm::DataLayout::getPreferredAlignment(), setAlignment(), SRAGlobal(), and llvm::ObjectSizeOffsetVisitor::visitGlobalVariable().
const Comdat* llvm::GlobalObject::getComdat () const [inline]
Reimplemented from llvm::GlobalValue.
Definition at line 61 of file GlobalObject.h.
References ObjComdat.
Referenced by llvm::TargetLoweringObjectFileELF::getSectionForJumpTable(), llvm::TargetLoweringObjectFileCOFF::getSectionForJumpTable(), hasComdat(), maybePrintComdat(), llvm::Inliner::removeDeadFunctions(), and rewriteComdat().
Comdat* llvm::GlobalObject::getComdat () [inline]
Reimplemented from llvm::GlobalValue.
Definition at line 62 of file GlobalObject.h.
References ObjComdat.
unsigned GlobalObject::getGlobalObjectSubClassData () const
Definition at line 87 of file Globals.cpp.
References AlignmentBits, and llvm::GlobalValue::getGlobalValueSubClassData().
Referenced by llvm::Function::isMaterializable(), and setGlobalObjectSubClassData().
const char* llvm::GlobalObject::getSection () const [inline]
Reimplemented from llvm::GlobalValue.
Definition at line 57 of file GlobalObject.h.
References Section.
Referenced by llvm::AsmPrinter::EmitSpecialLLVMGlobal(), and hasSection().
bool llvm::GlobalObject::hasComdat () const [inline]
Reimplemented from llvm::GlobalValue.
Definition at line 60 of file GlobalObject.h.
References getComdat().
bool llvm::GlobalObject::hasSection () const [inline]
Reimplemented from llvm::GlobalValue.
Definition at line 56 of file GlobalObject.h.
References llvm::StringRef::empty(), and getSection().
Referenced by isSuitableForBSS().
void GlobalObject::setAlignment (unsigned Align)
Definition at line 77 of file Globals.cpp.
References getAlignment(), llvm::GlobalValue::getGlobalValueSubClassData(), llvm::Log2_32(), llvm::Value::MaximumAlignment, and llvm::GlobalValue::setGlobalValueSubClassData().
Referenced by copyAttributesFrom(), and SRAGlobal().
void llvm::GlobalObject::setComdat (Comdat * C) [inline]
Definition at line 63 of file GlobalObject.h.
References llvm::C, and ObjComdat.
Referenced by rewriteComdat().
void GlobalObject::setGlobalObjectSubClassData (unsigned Val)
Definition at line 92 of file Globals.cpp.
References AlignmentBits, getGlobalObjectSubClassData(), llvm::GlobalValue::getGlobalValueSubClassData(), and llvm::GlobalValue::setGlobalValueSubClassData().
void GlobalObject::setSection (StringRef S)
Definition at line 126 of file Globals.cpp.
References Section.
Referenced by assureFPCallStub(), copyAttributesFrom(), createFPFnStub(), and setUsedInitializer().
Member Data Documentation
const unsigned llvm::GlobalObject::AlignmentBits = 5 [static, protected]
Definition at line 38 of file GlobalObject.h.
Referenced by getGlobalObjectSubClassData(), and setGlobalObjectSubClassData().
const unsigned llvm::GlobalObject::GlobalObjectSubClassDataBits [static, protected]
Initial value:
      GlobalValueSubClassDataBits - AlignmentBits
Definition at line 39 of file GlobalObject.h.
Comdat* llvm::GlobalObject::ObjComdat [protected]
Definition at line 37 of file GlobalObject.h.
Referenced by getComdat(), and setComdat().
std::string llvm::GlobalObject::Section [protected]
Definition at line 36 of file GlobalObject.h.
Referenced by getSection(), and setSection().
The documentation for this class was generated from the following files:
GlobalObject.h
Globals.cpp