LLVM: llvm::orc::SimpleCompiler Class Reference
llvm::orc::SimpleCompiler Class Reference
Simple compile functor: Takes a single IR module and returns an ObjectFile.
#include <CompileUtils.h>
Public Member Functions
SimpleCompiler (TargetMachine &TM)
Construct a simple compile functor with the given target.
object::OwningBinary
< object::ObjectFile > operator() (Module &M) const
Compile a Module to an ObjectFile.
Detailed Description
Simple compile functor: Takes a single IR module and returns an ObjectFile.
Definition at line 28 of file CompileUtils.h.
Constructor & Destructor Documentation
llvm::orc::SimpleCompiler::SimpleCompiler (TargetMachine & TM) [inline]
Construct a simple compile functor with the given target.
Definition at line 31 of file CompileUtils.h.
Member Function Documentation
object::OwningBinary<object::ObjectFile> llvm::orc::SimpleCompiler::operator() (Module & M) const [inline]
Compile a Module to an ObjectFile.
Definition at line 34 of file CompileUtils.h.
References llvm::TargetMachine::addPassesToEmitMC(), llvm::object::ObjectFile::createObjectFile(), llvm::raw_ostream::flush(), llvm_unreachable, and llvm::legacy::PassManager::run().
The documentation for this class was generated from the following file:
CompileUtils.h