LLVM: llvm::ConstantPointerNull Class Reference
llvm::ConstantPointerNull Class Reference
ConstantPointerNull - a constant pointer value that points to null.
#include <Constants.h>
Public Member Functions
PointerType * getType () const
getType - Specialize the getType() method to always return an PointerType, which reduces the amount of casting needed in parts of the compiler.
Static Public Member Functions
static ConstantPointerNull * get (PointerType *T)
get() - Static factory methods - Return objects of the specified value
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
ConstantPointerNull (PointerType *T)
void * operator new (size_t s)
Allocate a User with an operand pointer co-allocated.
Friends
class Constant
Detailed Description
ConstantPointerNull - a constant pointer value that points to null.
Definition at line 513 of file Constants.h.
Constructor & Destructor Documentation
llvm::ConstantPointerNull::ConstantPointerNull (PointerType * T) [inline, explicit, protected]
Definition at line 521 of file Constants.h.
Member Function Documentation
static bool llvm::ConstantPointerNull::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::Constant.
Definition at line 542 of file Constants.h.
References llvm::Value::getValueID().
ConstantPointerNull * ConstantPointerNull::get (PointerType * T) [static]
get() - Static factory methods - Return objects of the specified value
Definition at line 1455 of file Constants.cpp.
References llvm::LLVMContextImpl::CPNConstants, llvm::Type::getContext(), and llvm::LLVMContext::pImpl.
Referenced by combineLoadToNewType(), llvm::ConstantFoldCastInstruction(), ConstantFoldGetElementPtrImpl(), FoldBitCast(), llvm::Constant::getNullValue(), LLVMConstPointerNull(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::MapValue(), relocationViaAlloca(), ReplaceWithStatepoint(), and llvm::InstCombiner::visitCallInst().
PointerType* llvm::ConstantPointerNull::getType () const [inline]
getType - Specialize the getType() method to always return an PointerType, which reduces the amount of casting needed in parts of the compiler.
Reimplemented from llvm::Value.
Definition at line 537 of file Constants.h.
References llvm::Value::getType().
void* llvm::ConstantPointerNull::operator new (size_t Size) [inline, protected]
Allocate a User with an operand pointer co-allocated.
This is used for subclasses which need to allocate a variable number of operands, ie, 'hung off uses'.
Reimplemented from llvm::User.
Definition at line 527 of file Constants.h.
References llvm::User::operator new().
Friends And Related Function Documentation
friend class Constant [friend]
Definition at line 517 of file Constants.h.
The documentation for this class was generated from the following files:
Constants.h
Constants.cpp