LLVM: llvm::TargetTransformInfoWrapperPass Class Reference
llvm::TargetTransformInfoWrapperPass Class Reference
Wrapper pass for TargetTransformInfo.
#include <TargetTransformInfo.h>
Public Member Functions
TargetTransformInfoWrapperPass ()
We must provide a default constructor for the pass but it should never be used.
TargetTransformInfoWrapperPass (TargetIRAnalysis TIRA)
TargetTransformInfo & getTTI (Function &F)
Static Public Attributes
static char ID
Detailed Description
Wrapper pass for TargetTransformInfo.
This pass can be constructed from a TTI object which it stores internally and is queried by passes.
Definition at line 885 of file TargetTransformInfo.h.
Constructor & Destructor Documentation
TargetTransformInfoWrapperPass::TargetTransformInfoWrapperPass ()
We must provide a default constructor for the pass but it should never be used.
Use the constructor below or call one of the creation routines.
Definition at line 312 of file TargetTransformInfo.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeTargetTransformInfoWrapperPassPass().
TargetTransformInfoWrapperPass::TargetTransformInfoWrapperPass (TargetIRAnalysis TIRA) [explicit]
Definition at line 318 of file TargetTransformInfo.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeTargetTransformInfoWrapperPassPass().
Member Function Documentation
TargetTransformInfo & TargetTransformInfoWrapperPass::getTTI (Function & F)
Definition at line 325 of file TargetTransformInfo.cpp.
References llvm::TargetIRAnalysis::run().
Referenced by llvm::InlineCostAnalysis::getInlineCost().
Member Data Documentation
char llvm::TargetTransformInfoWrapperPass::ID [static]
Definition at line 892 of file TargetTransformInfo.h.
The documentation for this class was generated from the following files:
TargetTransformInfo.h
TargetTransformInfo.cpp