LLVM: llvm::DebugLocDwarfExpression Class Reference
llvm::DebugLocDwarfExpression Class Reference
DwarfExpression implementation for .debug_loc entries.
#include <DwarfExpression.h>
Public Member Functions
DebugLocDwarfExpression (const TargetRegisterInfo &TRI, unsigned DwarfVersion, ByteStreamer &BS)
void EmitOp (uint8_t Op, const char *Comment=nullptr) override
Output a dwarf operand and an optional assembler comment.
void EmitSigned (int64_t Value) override
Emit a raw signed value.
void EmitUnsigned (uint64_t Value) override
Emit a raw unsigned value.
bool isFrameRegister (unsigned MachineReg) override
Return whether the given machine register is the frame register in the current function.
Detailed Description
DwarfExpression implementation for .debug_loc entries.
Definition at line 107 of file DwarfExpression.h.
Constructor & Destructor Documentation
llvm::DebugLocDwarfExpression::DebugLocDwarfExpression (const TargetRegisterInfo & TRI, unsigned DwarfVersion, ByteStreamer & BS) [inline]
Definition at line 111 of file DwarfExpression.h.
Member Function Documentation
void DebugLocDwarfExpression::EmitOp (uint8_t Op, const char * Comment = nullptr) [override, virtual]
Output a dwarf operand and an optional assembler comment.
Implements llvm::DwarfExpression.
Definition at line 110 of file DwarfDebug.cpp.
References llvm::ByteStreamer::EmitInt8(), and llvm::dwarf::OperationEncodingString().
void DebugLocDwarfExpression::EmitSigned (int64_t Value) [override, virtual]
Emit a raw signed value.
Implements llvm::DwarfExpression.
Definition at line 116 of file DwarfDebug.cpp.
References llvm::ByteStreamer::EmitSLEB128().
void DebugLocDwarfExpression::EmitUnsigned (uint64_t Value) [override, virtual]
Emit a raw unsigned value.
Implements llvm::DwarfExpression.
Definition at line 120 of file DwarfDebug.cpp.
References llvm::ByteStreamer::EmitULEB128().
bool DebugLocDwarfExpression::isFrameRegister (unsigned MachineReg) [override, virtual]
Return whether the given machine register is the frame register in the current function.
Implements llvm::DwarfExpression.
Definition at line 124 of file DwarfDebug.cpp.
The documentation for this class was generated from the following files:
DwarfExpression.h
DwarfDebug.cpp