LLVM: llvm::dwarf::syntax::WithColor Class Reference
llvm::dwarf::syntax::WithColor Class Reference
An RAII object that temporarily switches an output stream to a specific color.
#include <SyntaxHighlighting.h>
Public Member Functions
WithColor (llvm::raw_ostream &OS, enum HighlightColor Type)
To be used like this: WithColor(OS, syntax::String) << "text";.
~WithColor ()
llvm::raw_ostream & get ()
operator llvm::raw_ostream & ()
Detailed Description
An RAII object that temporarily switches an output stream to a specific color.
Definition at line 24 of file SyntaxHighlighting.h.
Constructor & Destructor Documentation
WithColor::WithColor (llvm::raw_ostream & OS, enum HighlightColor Type)
To be used like this: WithColor(OS, syntax::String) << "text";.
Definition at line 21 of file SyntaxHighlighting.cpp.
References llvm::dwarf::syntax::Address, llvm::raw_ostream::BLUE, llvm::cl::BOU_TRUE, llvm::cl::BOU_UNSET, llvm::raw_ostream::changeColor(), llvm::raw_ostream::CYAN, llvm::dwarf::syntax::Enumerator, llvm::raw_ostream::GREEN, llvm::raw_ostream::has_colors(), llvm::raw_ostream::MAGENTA, llvm::dwarf::syntax::String, UseColor, and llvm::raw_ostream::YELLOW.
WithColor::~WithColor ()
Definition at line 34 of file SyntaxHighlighting.cpp.
References llvm::cl::BOU_TRUE, llvm::cl::BOU_UNSET, llvm::raw_ostream::has_colors(), llvm::raw_ostream::resetColor(), and UseColor.
Member Function Documentation
llvm::raw_ostream& llvm::dwarf::syntax::WithColor::get () [inline]
Definition at line 32 of file SyntaxHighlighting.h.
Referenced by llvm::DWARFDebugInfoEntryMinimal::dump(), llvm::DWARFFormValue::dump(), and llvm::DWARFDebugInfoEntryMinimal::dumpAttribute().
llvm::dwarf::syntax::WithColor::operator llvm::raw_ostream & () [inline]
Definition at line 33 of file SyntaxHighlighting.h.
The documentation for this class was generated from the following files:
SyntaxHighlighting.h
SyntaxHighlighting.cpp