LLVM: llvm::MCDwarfLineTable Class Reference
llvm::MCDwarfLineTable Class Reference
#include <MCDwarf.h>
Public Member Functions
void EmitCU (MCObjectStreamer *MCOS) const
unsigned getFile (StringRef &Directory, StringRef &FileName, unsigned FileNumber=0)
MCSymbol * getLabel () const
void setLabel (MCSymbol *Label)
void setCompilationDir (StringRef CompilationDir)
const SmallVectorImpl
< std::string > & getMCDwarfDirs () const
SmallVectorImpl< std::string > & getMCDwarfDirs ()
const SmallVectorImpl
< MCDwarfFile > & getMCDwarfFiles () const
SmallVectorImpl< MCDwarfFile > & getMCDwarfFiles ()
const MCLineSection & getMCLineSections () const
MCLineSection & getMCLineSections ()
Static Public Member Functions
static void Emit (MCObjectStreamer *MCOS)
Detailed Description
Definition at line 203 of file MCDwarf.h.
Member Function Documentation
void MCDwarfLineTable::Emit (MCObjectStreamer * MCOS) [static]
Definition at line 200 of file MCDwarf.cpp.
References llvm::MCStreamer::getContext(), llvm::MCObjectFileInfo::getDwarfLineSection(), llvm::MCContext::getMCDwarfLineTables(), llvm::MCContext::getObjectFileInfo(), and llvm::MCStreamer::SwitchSection().
Referenced by llvm::MCObjectStreamer::FinishImpl().
void MCDwarfLineTable::EmitCU (MCObjectStreamer * MCOS) const
Definition at line 332 of file MCDwarf.cpp.
References llvm::MCDwarfLineTableHeader::Emit(), EmitDwarfLineTable(), llvm::MCObjectStreamer::EmitLabel(), and llvm::MCLineSection::getMCLineEntries().
unsigned MCDwarfLineTable::getFile (StringRef & Directory, StringRef & FileName, unsigned FileNumber = 0)
Definition at line 344 of file MCDwarf.cpp.
References llvm::MCDwarfLineTableHeader::getFile().
Referenced by llvm::MCContext::getDwarfFile().
MCSymbol* llvm::MCDwarfLineTable::getLabel () const [inline]
Definition at line 217 of file MCDwarf.h.
References llvm::MCDwarfLineTableHeader::Label.
Referenced by llvm::MCStreamer::getDwarfLineTableSymbol().
const SmallVectorImpl<std::string>& llvm::MCDwarfLineTable::getMCDwarfDirs () const [inline]
Definition at line 229 of file MCDwarf.h.
References llvm::MCDwarfLineTableHeader::MCDwarfDirs.
Referenced by llvm::MCContext::getMCDwarfDirs().
SmallVectorImpl<std::string>& llvm::MCDwarfLineTable::getMCDwarfDirs () [inline]
Definition at line 233 of file MCDwarf.h.
References llvm::MCDwarfLineTableHeader::MCDwarfDirs.
const SmallVectorImpl<MCDwarfFile>& llvm::MCDwarfLineTable::getMCDwarfFiles () const [inline]
Definition at line 237 of file MCDwarf.h.
References llvm::MCDwarfLineTableHeader::MCDwarfFiles.
Referenced by llvm::MCContext::getMCDwarfFiles().
SmallVectorImpl<MCDwarfFile>& llvm::MCDwarfLineTable::getMCDwarfFiles () [inline]
Definition at line 241 of file MCDwarf.h.
References llvm::MCDwarfLineTableHeader::MCDwarfFiles.
const MCLineSection& llvm::MCDwarfLineTable::getMCLineSections () const [inline]
Definition at line 245 of file MCDwarf.h.
MCLineSection& llvm::MCDwarfLineTable::getMCLineSections () [inline]
Definition at line 248 of file MCDwarf.h.
void llvm::MCDwarfLineTable::setCompilationDir (StringRef CompilationDir) [inline]
Definition at line 225 of file MCDwarf.h.
References llvm::MCDwarfLineTableHeader::CompilationDir.
Referenced by llvm::MCContext::setMCLineTableCompilationDir().
void llvm::MCDwarfLineTable::setLabel (MCSymbol * Label) [inline]
Definition at line 221 of file MCDwarf.h.
References llvm::MCDwarfLineTableHeader::Label, and llvm::Label.
Referenced by llvm::MCStreamer::getDwarfLineTableSymbol().
The documentation for this class was generated from the following files:
MCDwarf.h
MCDwarf.cpp