LLVM: llvm::DbgVariable Class Reference
llvm::DbgVariable Class Reference
This class is used to track local variable information.
#include <DwarfDebug.h>
Public Member Functions
DbgVariable (const DILocalVariable *V, const DILocation *IA, DwarfDebug *DD)
Construct a DbgVariable.
void initializeMMI (const DIExpression *E, int FI)
Initialize from the MMI table.
void initializeDbgValue (const MachineInstr *DbgValue)
Initialize from a DBG_VALUE instruction.
const DILocalVariable * getVariable () const
const DILocation * getInlinedAt () const
const ArrayRef< const
DIExpression * > getExpression () const
void setDIE (DIE &D)
DIE * getDIE () const
void setDebugLocListIndex (unsigned O)
unsigned getDebugLocListIndex () const
StringRef getName () const
const MachineInstr * getMInsn () const
const ArrayRef< int > getFrameIndex () const
void addMMIEntry (const DbgVariable &V)
dwarf::Tag getTag () const
bool isArtificial () const
Return true if DbgVariable is artificial.
bool isObjectPointer () const
bool hasComplexAddress () const
bool isBlockByrefVariable () const
const DIType * getType () const
Detailed Description
This class is used to track local variable information.
Variables can be created from allocas, in which case they're generated from the MMI table. Such variables can have multiple expressions and frame indices. The Expr and FrameIndices array must match.
Variables can be created from DBG_VALUE instructions. Those whose location changes over time use DebugLocListIndex, while those with a single instruction use MInsn and (optionally) a single entry of Expr.
Variables that have been optimized out use none of these fields.
Definition at line 81 of file DwarfDebug.h.
Constructor & Destructor Documentation
llvm::DbgVariable::DbgVariable (const DILocalVariable * V, const DILocation * IA, DwarfDebug * DD) [inline]
Construct a DbgVariable.
Creates a variable without any DW_AT_location. Call initializeMMI() for MMI entries, or initializeDbgValue() for DBG_VALUE instructions.
Definition at line 96 of file DwarfDebug.h.
Member Function Documentation
void llvm::DbgVariable::addMMIEntry (const DbgVariable & V) [inline]
Definition at line 139 of file DwarfDebug.h.
References llvm::all_of(), llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::DIExpression::isBitPiece(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
unsigned llvm::DbgVariable::getDebugLocListIndex () const [inline]
Definition at line 134 of file DwarfDebug.h.
DIE* llvm::DbgVariable::getDIE () const [inline]
Definition at line 132 of file DwarfDebug.h.
const ArrayRef<const DIExpression *> llvm::DbgVariable::getExpression () const [inline]
Definition at line 130 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::addComplexAddress().
const ArrayRef<int> llvm::DbgVariable::getFrameIndex () const [inline]
Definition at line 137 of file DwarfDebug.h.
const DILocation* llvm::DbgVariable::getInlinedAt () const [inline]
Definition at line 129 of file DwarfDebug.h.
const MachineInstr* llvm::DbgVariable::getMInsn () const [inline]
Definition at line 136 of file DwarfDebug.h.
StringRef llvm::DbgVariable::getName () const [inline]
Definition at line 135 of file DwarfDebug.h.
References llvm::DIVariable::getName().
Referenced by llvm::DwarfUnit::addBlockByrefAddress(), llvm::DwarfCompileUnit::applyVariableAttributes(), and getType().
dwarf::Tag llvm::DbgVariable::getTag () const [inline]
Definition at line 158 of file DwarfDebug.h.
References llvm::DINode::getTag().
const DIType * DbgVariable::getType () const
Definition at line 144 of file DwarfDebug.cpp.
References getName(), llvm::DINode::getTag(), llvm::DIVariable::getType(), llvm::DwarfDebug::getTypeIdentifierMap(), llvm::DIType::isBlockByrefStruct(), N, and llvm::TypedDINodeRef< T >::resolve().
Referenced by llvm::DwarfUnit::addBlockByrefAddress(), llvm::DwarfCompileUnit::applyVariableAttributes(), isArtificial(), and isObjectPointer().
const DILocalVariable* llvm::DbgVariable::getVariable () const [inline]
Definition at line 128 of file DwarfDebug.h.
Referenced by llvm::DwarfFile::addScopeVariable(), and llvm::DwarfCompileUnit::applyVariableAttributes().
bool llvm::DbgVariable::hasComplexAddress () const [inline]
Definition at line 181 of file DwarfDebug.h.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorBase::empty(), llvm::DIExpression::getNumElements(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::DwarfCompileUnit::addVariableAddress().
void llvm::DbgVariable::initializeDbgValue (const MachineInstr * DbgValue) [inline]
Initialize from a DBG_VALUE instruction.
Definition at line 113 of file DwarfDebug.h.
References llvm::SmallVectorBase::empty(), llvm::MachineInstr::getDebugExpression(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getDebugVariable(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by llvm::DebugLocStream::ListBuilder::~ListBuilder().
void llvm::DbgVariable::initializeMMI (const DIExpression * E, int FI) [inline]
Initialize from the MMI table.
Definition at line 100 of file DwarfDebug.h.
References llvm::SmallVectorBase::empty(), llvm::DIExpression::isValid(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
bool llvm::DbgVariable::isArtificial () const [inline]
Return true if DbgVariable is artificial.
Definition at line 165 of file DwarfDebug.h.
References getType(), llvm::DIType::isArtificial(), and llvm::DILocalVariable::isArtificial().
Referenced by llvm::DwarfCompileUnit::applyVariableAttributes().
bool DbgVariable::isBlockByrefVariable () const
Definition at line 137 of file DwarfDebug.cpp.
References llvm::DIVariable::getType(), llvm::DwarfDebug::getTypeIdentifierMap(), and llvm::TypedDINodeRef< T >::resolve().
Referenced by llvm::DwarfCompileUnit::addVariableAddress().
bool llvm::DbgVariable::isObjectPointer () const [inline]
Definition at line 173 of file DwarfDebug.h.
References getType(), llvm::DIType::isObjectPointer(), and llvm::DILocalVariable::isObjectPointer().
Referenced by llvm::DwarfCompileUnit::constructVariableDIE().
void llvm::DbgVariable::setDebugLocListIndex (unsigned O) [inline]
Definition at line 133 of file DwarfDebug.h.
Referenced by llvm::DebugLocStream::ListBuilder::~ListBuilder().
void llvm::DbgVariable::setDIE (DIE & D) [inline]
Definition at line 131 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::constructVariableDIE().
The documentation for this class was generated from the following files:
DwarfDebug.h
DwarfDebug.cpp