LLVM: llvm::InstCombinePass Class Reference
llvm::InstCombinePass Class Reference
#include <InstCombine.h>
Public Member Functions
InstCombinePass ()
InstCombinePass (InstCombinePass &&Arg)
InstCombinePass & operator= (InstCombinePass &&RHS)
PreservedAnalyses run (Function &F, AnalysisManager< Function > *AM)
Static Public Member Functions
static StringRef name ()
Detailed Description
Definition at line 27 of file InstCombine.h.
Constructor & Destructor Documentation
llvm::InstCombinePass::InstCombinePass () [inline]
Definition at line 34 of file InstCombine.h.
llvm::InstCombinePass::InstCombinePass (InstCombinePass && Arg) [inline]
Definition at line 35 of file InstCombine.h.
Member Function Documentation
static StringRef llvm::InstCombinePass::name () [inline, static]
Definition at line 31 of file InstCombine.h.
InstCombinePass& llvm::InstCombinePass::operator= (InstCombinePass && RHS) [inline]
Definition at line 36 of file InstCombine.h.
PreservedAnalyses InstCombinePass::run (Function & F, AnalysisManager< Function > * AM)
Definition at line 3012 of file InstructionCombining.cpp.
References llvm::PreservedAnalyses::all(), combineInstructionsOverFunction(), F(), llvm::detail::AnalysisManagerBase< AnalysisManager< IRUnitT >, IRUnitT >::getCachedResult(), llvm::detail::AnalysisManagerBase< AnalysisManager< IRUnitT >, IRUnitT >::getResult(), and llvm::PreservedAnalyses::preserve().
The documentation for this class was generated from the following files:
InstCombine.h
InstructionCombining.cpp