LLVM: llvm::RegPressureTracker Class Reference
llvm::RegPressureTracker Class Reference
Track the current register pressure at some position in the instruction stream, and remember the high water mark within the region traversed.
#include <RegisterPressure.h>
Public Member Functions
RegPressureTracker (IntervalPressure &rp)
RegPressureTracker (RegionPressure &rp)
void reset ()
void init (const MachineFunction *mf, const RegisterClassInfo *rci, const LiveIntervals *lis, const MachineBasicBlock *mbb, MachineBasicBlock::const_iterator pos, bool ShouldTrackUntiedDefs=false)
Setup the RegPressureTracker.
void addLiveRegs (ArrayRef< unsigned > Regs)
Force liveness of virtual registers or physical register units.
MachineBasicBlock::const_iterator getPos () const
Get the MI position corresponding to this register pressure.
void setPos (MachineBasicBlock::const_iterator Pos)
SlotIndex getCurrSlot () const
Get the SlotIndex for the first nondebug instruction including or after the current position.
bool recede (SmallVectorImpl< unsigned > *LiveUses=nullptr, PressureDiff *PDiff=nullptr)
Recede across the previous instruction.
bool advance ()
Advance across the current instruction.
void closeRegion ()
Finalize the region boundaries and recored live ins and live outs.
void initLiveThru (const RegPressureTracker &RPTracker)
Initialize the LiveThru pressure set based on the untied defs found in RPTracker.
void initLiveThru (ArrayRef< unsigned > PressureSet)
Copy an existing live thru pressure result.
ArrayRef< unsigned > getLiveThru () const
RegisterPressure & getPressure ()
Get the resulting register pressure over the traversed region.
const RegisterPressure & getPressure () const
std::vector< unsigned > & getRegSetPressureAtPos ()
Get the register set pressure at the current position, which may be less than the pressure across the traversed region.
void discoverLiveOut (unsigned Reg)
Add Reg to the live out set and increase max pressure.
void discoverLiveIn (unsigned Reg)
Add Reg to the live in set and increase max pressure.
bool isTopClosed () const
Does this pressure result have a valid top position and live ins.
bool isBottomClosed () const
Does this pressure result have a valid bottom position and live outs.
void closeTop ()
Set the boundary for the top of the region and summarize live ins.
void closeBottom ()
Set the boundary for the bottom of the region and summarize live outs.
void getMaxUpwardPressureDelta (const MachineInstr *MI, PressureDiff *PDiff, RegPressureDelta &Delta, ArrayRef< PressureChange > CriticalPSets, ArrayRef< unsigned > MaxPressureLimit)
Consider the pressure increase caused by traversing this instruction bottom-up.
void getUpwardPressureDelta (const MachineInstr *MI, PressureDiff &PDiff, RegPressureDelta &Delta, ArrayRef< PressureChange > CriticalPSets, ArrayRef< unsigned > MaxPressureLimit) const
This is the fast version of querying register pressure that does not directly depend on current liveness.
void getMaxDownwardPressureDelta (const MachineInstr *MI, RegPressureDelta &Delta, ArrayRef< PressureChange > CriticalPSets, ArrayRef< unsigned > MaxPressureLimit)
Consider the pressure increase caused by traversing this instruction top-down.
void getMaxPressureDelta (const MachineInstr *MI, RegPressureDelta &Delta, ArrayRef< PressureChange > CriticalPSets, ArrayRef< unsigned > MaxPressureLimit)
Find the pressure set with the most change beyond its pressure limit after traversing this instruction either upward or downward depending on the closed end of the current region.
void getUpwardPressure (const MachineInstr *MI, std::vector< unsigned > &PressureResult, std::vector< unsigned > &MaxPressureResult)
Get the pressure of each PSet after traversing this instruction bottom-up.
void getDownwardPressure (const MachineInstr *MI, std::vector< unsigned > &PressureResult, std::vector< unsigned > &MaxPressureResult)
Get the pressure of each PSet after traversing this instruction top-down.
void getPressureAfterInst (const MachineInstr *MI, std::vector< unsigned > &PressureResult, std::vector< unsigned > &MaxPressureResult)
bool hasUntiedDef (unsigned VirtReg) const
void dump () const
Protected Member Functions
const LiveRange * getLiveRange (unsigned Reg) const
void increaseRegPressure (ArrayRef< unsigned > Regs)
Increase the current pressure as impacted by these registers and bump the high water mark if needed.
void decreaseRegPressure (ArrayRef< unsigned > Regs)
Simply decrease the current pressure as impacted by these registers.
void bumpUpwardPressure (const MachineInstr *MI)
Record the upward impact of a single instruction on current register pressure.
void bumpDownwardPressure (const MachineInstr *MI)
Record the downward impact of a single instruction on current register pressure.
Detailed Description
Track the current register pressure at some position in the instruction stream, and remember the high water mark within the region traversed.
This does not automatically consider live-through ranges. The client may independently adjust for global liveness.
Each RegPressureTracker only works within a MachineBasicBlock. Pressure can be tracked across a larger region by storing a RegisterPressure result at each block boundary and explicitly adjusting pressure to account for block live-in and live-out register sets.
RegPressureTracker holds a reference to a RegisterPressure result that it computes incrementally. During downward tracking, P.BottomIdx or P.BottomPos is invalid until it reaches the end of the block or closeRegion() is explicitly called. Similarly, P.TopIdx is invalid during upward tracking. Changing direction has the side effect of closing region, and traversing past TopIdx or BottomIdx reopens it.
Definition at line 235 of file RegisterPressure.h.
Constructor & Destructor Documentation
llvm::RegPressureTracker::RegPressureTracker (IntervalPressure & rp) [inline]
Definition at line 272 of file RegisterPressure.h.
llvm::RegPressureTracker::RegPressureTracker (RegionPressure & rp) [inline]
Definition at line 276 of file RegisterPressure.h.
Member Function Documentation
void RegPressureTracker::addLiveRegs (ArrayRef< unsigned > Regs)
Force liveness of virtual registers or physical register units.
Force liveness of registers.
Particularly useful to initialize the livein/out state of the tracker before the first call to advance/recede.
Definition at line 424 of file RegisterPressure.cpp.
References increaseRegPressure(), llvm::LiveRegSet::insert(), and llvm::ArrayRef< T >::size().
Referenced by llvm::ScheduleDAGMILive::initRegPressure().
bool RegPressureTracker::advance ()
Advance across the current instruction.
Definition at line 555 of file RegisterPressure.cpp.
References closeRegion(), closeTop(), collectOperands(), llvm::LiveRegSet::contains(), decreaseRegPressure(), discoverLiveIn(), llvm::MachineBasicBlock::end(), llvm::LiveRegSet::erase(), getCurrSlot(), getLiveRange(), increaseRegPressure(), llvm::LiveRegSet::insert(), isBottomClosed(), llvm::LiveQueryResult::isKill(), isTopClosed(), llvm::TargetRegisterInfo::isVirtualRegister(), and llvm::LiveRange::Query().
Referenced by llvm::ScheduleDAGMILive::scheduleMI().
void RegPressureTracker::bumpDownwardPressure (const MachineInstr * MI) [protected]
Record the downward impact of a single instruction on current register pressure.
Unlike the advance/recede pressure tracking interface, this does not discover live in/outs.
This is intended for speculative queries. It leaves pressure inconsistent with the current position, so must be restored by the caller.
Definition at line 906 of file RegisterPressure.cpp.
References collectOperands(), decreaseRegPressure(), findUseBetween(), getCurrSlot(), llvm::LiveIntervals::getInstructionIndex(), getLiveRange(), llvm::SlotIndex::getRegSlot(), increaseRegPressure(), llvm::MachineInstr::isDebugValue(), llvm::LiveQueryResult::isKill(), llvm::TargetRegisterInfo::isVirtualRegister(), and llvm::LiveRange::Query().
Referenced by getDownwardPressure(), and getMaxDownwardPressureDelta().
void RegPressureTracker::bumpUpwardPressure (const MachineInstr * MI) [protected]
Record the upward impact of a single instruction on current register pressure.
Unlike the advance/recede pressure tracking interface, this does not discover live in/outs.
This is intended for speculative queries. It leaves pressure inconsistent with the current position, so must be restored by the caller.
Definition at line 708 of file RegisterPressure.cpp.
References collectOperands(), llvm::LiveRegSet::contains(), containsReg(), decreaseRegPressure(), llvm::LiveIntervals::getInstructionIndex(), getLiveRange(), increaseRegPressure(), llvm::LiveQueryResult::isDeadDef(), llvm::MachineInstr::isDebugValue(), and llvm::LiveRange::Query().
Referenced by getMaxUpwardPressureDelta(), and getUpwardPressure().
void RegPressureTracker::closeBottom ()
Set the boundary for the bottom of the region and summarize live outs.
Definition at line 254 of file RegisterPressure.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::begin(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::end(), llvm::SmallVectorImpl< T >::erase(), getCurrSlot(), I, llvm::RegisterPressure::LiveOutRegs, llvm::LiveRegSet::PhysRegs, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorImpl< T >::reserve(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::size(), and llvm::LiveRegSet::VirtRegs.
Referenced by closeRegion(), llvm::ScheduleDAGMILive::initRegPressure(), and recede().
void RegPressureTracker::closeRegion ()
Finalize the region boundaries and recored live ins and live outs.
Finalize the region boundaries and record live ins and live outs.
Definition at line 272 of file RegisterPressure.cpp.
References closeBottom(), closeTop(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::empty(), isBottomClosed(), isTopClosed(), llvm::LiveRegSet::PhysRegs, and llvm::LiveRegSet::VirtRegs.
Referenced by advance(), llvm::ScheduleDAGMILive::initRegPressure(), and recede().
void RegPressureTracker::closeTop ()
Set the boundary for the top of the region and summarize live ins.
Definition at line 236 of file RegisterPressure.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::begin(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::end(), llvm::SmallVectorImpl< T >::erase(), getCurrSlot(), I, llvm::RegisterPressure::LiveInRegs, llvm::LiveRegSet::PhysRegs, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorImpl< T >::reserve(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::size(), and llvm::LiveRegSet::VirtRegs.
Referenced by advance(), closeRegion(), and llvm::ScheduleDAGMILive::initRegPressure().
void RegPressureTracker::decreaseRegPressure (ArrayRef< unsigned > Regs) [protected]
Simply decrease the current pressure as impacted by these registers.
Definition at line 96 of file RegisterPressure.cpp.
References decreaseSetPressure(), llvm::MachineRegisterInfo::getPressureSets(), I, and llvm::ArrayRef< T >::size().
Referenced by advance(), bumpDownwardPressure(), bumpUpwardPressure(), and recede().
void RegPressureTracker::discoverLiveIn (unsigned Reg)
Add Reg to the live in set and increase max pressure.
Definition at line 432 of file RegisterPressure.cpp.
References llvm::LiveRegSet::contains(), containsReg(), llvm::MachineRegisterInfo::getPressureSets(), increaseSetPressure(), llvm::RegisterPressure::LiveInRegs, llvm::RegisterPressure::MaxSetPressure, and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by advance().
void RegPressureTracker::discoverLiveOut (unsigned Reg)
Add Reg to the live out set and increase max pressure.
Definition at line 443 of file RegisterPressure.cpp.
References llvm::LiveRegSet::contains(), containsReg(), llvm::MachineRegisterInfo::getPressureSets(), increaseSetPressure(), llvm::RegisterPressure::LiveOutRegs, llvm::RegisterPressure::MaxSetPressure, and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by recede().
LLVM_DUMP_METHOD void RegPressureTracker::dump () const
Definition at line 72 of file RegisterPressure.cpp.
References llvm::dbgs(), llvm::RegisterPressure::dump(), llvm::dumpRegSetPressure(), isBottomClosed(), and isTopClosed().
Referenced by llvm::ScheduleDAGMILive::initRegPressure().
SlotIndex RegPressureTracker::getCurrSlot () const
Get the SlotIndex for the first nondebug instruction including or after the current position.
Definition at line 226 of file RegisterPressure.cpp.
References llvm::MachineBasicBlock::end(), llvm::LiveIntervals::getInstructionIndex(), llvm::LiveIntervals::getMBBEndIdx(), and llvm::SlotIndex::getRegSlot().
Referenced by advance(), bumpDownwardPressure(), closeBottom(), and closeTop().
void RegPressureTracker::getDownwardPressure (const MachineInstr * MI, std::vector< unsigned > & PressureResult, std::vector< unsigned > & MaxPressureResult)
Get the pressure of each PSet after traversing this instruction top-down.
Definition at line 998 of file RegisterPressure.cpp.
References bumpDownwardPressure(), and llvm::RegisterPressure::MaxSetPressure.
Referenced by getPressureAfterInst().
const LiveRange * RegPressureTracker::getLiveRange (unsigned Reg) const [protected]
Definition at line 150 of file RegisterPressure.cpp.
References llvm::LiveIntervals::getCachedRegUnit(), llvm::LiveIntervals::getInterval(), and llvm::TargetRegisterInfo::isVirtualRegister().
Referenced by advance(), bumpDownwardPressure(), bumpUpwardPressure(), and recede().
ArrayRef<unsigned> llvm::RegPressureTracker::getLiveThru () const [inline]
Definition at line 324 of file RegisterPressure.h.
Referenced by llvm::ScheduleDAGMILive::initRegPressure(), and llvm::ScheduleDAGMILive::updateScheduledPressure().
void RegPressureTracker::getMaxDownwardPressureDelta (const MachineInstr * MI, RegPressureDelta & Delta, ArrayRef< PressureChange > CriticalPSets, ArrayRef< unsigned > MaxPressureLimit)
Consider the pressure increase caused by traversing this instruction top-down.
Find the pressure set with the most change beyond its pressure limit based on the tracker's current pressure, and record the number of excess register units of that pressure set introduced by this instruction.
Find the register class with the most change in its pressure limit based on the tracker's current pressure, and return the number of excess register units of that pressure set introduced by this instruction.
This assumes that the current LiveIn set is sufficient.
This is expensive for an on-the-fly query because it calls bumpDownwardPressure to recompute the pressure sets based on current liveness. We don't yet have a fast version of downward pressure tracking analagous to getUpwardPressureDelta.
Definition at line 959 of file RegisterPressure.cpp.
References bumpDownwardPressure(), computeExcessPressureDelta(), computeMaxPressureDelta(), llvm::RegPressureDelta::CriticalMax, llvm::RegPressureDelta::CurrentMax, llvm::PressureChange::getUnitInc(), and llvm::RegisterPressure::MaxSetPressure.
Referenced by getMaxPressureDelta(), and llvm::GenericScheduler::tryCandidate().
void llvm::RegPressureTracker::getMaxPressureDelta (const MachineInstr * MI, RegPressureDelta & Delta, ArrayRef< PressureChange > CriticalPSets, ArrayRef< unsigned > MaxPressureLimit) [inline]
Find the pressure set with the most change beyond its pressure limit after traversing this instruction either upward or downward depending on the closed end of the current region.
Definition at line 373 of file RegisterPressure.h.
References getMaxDownwardPressureDelta(), getMaxUpwardPressureDelta(), isBottomClosed(), and isTopClosed().
void RegPressureTracker::getMaxUpwardPressureDelta (const MachineInstr * MI, PressureDiff * PDiff, RegPressureDelta & Delta, ArrayRef< PressureChange > CriticalPSets, ArrayRef< unsigned > MaxPressureLimit)
Consider the pressure increase caused by traversing this instruction bottom-up.
Find the pressure set with the most change beyond its pressure limit based on the tracker's current pressure, and record the number of excess register units of that pressure set introduced by this instruction.
Find the pressure set with the most change beyond its pressure limit based on the tracker's current pressure, and return the change in number of register units of that pressure set introduced by this instruction.
This assumes that the current LiveOut set is sufficient.
This is expensive for an on-the-fly query because it calls bumpUpwardPressure to recompute the pressure sets based on current liveness. This mainly exists to verify correctness, e.g. with -verify-misched. getUpwardPressureDelta is the fast version of this query that uses the per-SUnit cache of the PressureDiff.
Definition at line 759 of file RegisterPressure.cpp.
References bumpUpwardPressure(), computeExcessPressureDelta(), computeMaxPressureDelta(), llvm::RegPressureDelta::CriticalMax, llvm::RegPressureDelta::CurrentMax, llvm::dbgs(), llvm::RegPressureDelta::Excess, llvm::PressureChange::getPSet(), llvm::TargetRegisterInfo::getRegPressureSetName(), llvm::PressureChange::getUnitInc(), getUpwardPressureDelta(), llvm::PressureChange::isValid(), llvm_unreachable, llvm::RegisterPressure::MaxSetPressure, and llvm::AArch64CC::MI.
Referenced by getMaxPressureDelta(), and llvm::GenericScheduler::tryCandidate().
MachineBasicBlock::const_iterator llvm::RegPressureTracker::getPos () const [inline]
Get the MI position corresponding to this register pressure.
Definition at line 293 of file RegisterPressure.h.
Referenced by llvm::ScheduleDAGInstrs::buildSchedGraph(), llvm::ScheduleDAGMILive::initRegPressure(), llvm::ScheduleDAGMILive::schedule(), llvm::ScheduleDAGMILive::scheduleMI(), and llvm::ScheduleDAGMILive::updatePressureDiffs().
RegisterPressure& llvm::RegPressureTracker::getPressure () [inline]
Get the resulting register pressure over the traversed region.
This result is complete if either advance() or recede() has returned true, or if closeRegion() was explicitly invoked.
Definition at line 329 of file RegisterPressure.h.
Referenced by llvm::ScheduleDAGMILive::computeCyclicCriticalPath(), llvm::ScheduleDAGMILive::initRegPressure(), and llvm::ScheduleDAGMILive::scheduleMI().
const RegisterPressure& llvm::RegPressureTracker::getPressure () const [inline]
Definition at line 330 of file RegisterPressure.h.
void llvm::RegPressureTracker::getPressureAfterInst (const MachineInstr * MI, std::vector< unsigned > & PressureResult, std::vector< unsigned > & MaxPressureResult) [inline]
Definition at line 396 of file RegisterPressure.h.
References getDownwardPressure(), getUpwardPressure(), isBottomClosed(), and isTopClosed().
std::vector<unsigned>& llvm::RegPressureTracker::getRegSetPressureAtPos () [inline]
Get the register set pressure at the current position, which may be less than the pressure across the traversed region.
Definition at line 334 of file RegisterPressure.h.
void RegPressureTracker::getUpwardPressure (const MachineInstr * MI, std::vector< unsigned > & PressureResult, std::vector< unsigned > & MaxPressureResult)
Get the pressure of each PSet after traversing this instruction bottom-up.
Definition at line 982 of file RegisterPressure.cpp.
References bumpUpwardPressure(), and llvm::RegisterPressure::MaxSetPressure.
Referenced by getPressureAfterInst().
void RegPressureTracker::getUpwardPressureDelta (const MachineInstr * MI, PressureDiff & PDiff, RegPressureDelta & Delta, ArrayRef< PressureChange > CriticalPSets, ArrayRef< unsigned > MaxPressureLimit) const
This is the fast version of querying register pressure that does not directly depend on current liveness.
Parameters:
Delta captures information needed for heuristics.
CriticalPSets Are the pressure sets that are known to exceed some limit within the region, not necessarily at the current position.
MaxPressureLimit Is the max pressure within the region, not necessarily at the current position.
Definition at line 825 of file RegisterPressure.cpp.
References llvm::PressureDiff::begin(), llvm::RegPressureDelta::CriticalMax, llvm::RegPressureDelta::CurrentMax, llvm::PressureDiff::end(), llvm::RegPressureDelta::Excess, llvm::RegisterClassInfo::getRegPressureSetLimit(), llvm::PressureChange::isValid(), llvm::RegisterPressure::MaxSetPressure, llvm::PressureChange::setUnitInc(), and llvm::ArrayRef< T >::size().
Referenced by getMaxUpwardPressureDelta(), and llvm::GenericScheduler::tryCandidate().
bool llvm::RegPressureTracker::hasUntiedDef (unsigned VirtReg) const [inline]
Definition at line 406 of file RegisterPressure.h.
References llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::count().
Referenced by initLiveThru().
void RegPressureTracker::increaseRegPressure (ArrayRef< unsigned > RegUnits) [protected]
Increase the current pressure as impacted by these registers and bump the high water mark if needed.
Definition at line 82 of file RegisterPressure.cpp.
References llvm::MachineRegisterInfo::getPressureSets(), llvm::PSetIterator::getWeight(), llvm::PSetIterator::isValid(), llvm::RegisterPressure::MaxSetPressure, and llvm::ArrayRef< T >::size().
Referenced by addLiveRegs(), advance(), bumpDownwardPressure(), bumpUpwardPressure(), and recede().
void RegPressureTracker::init (const MachineFunction * mf, const RegisterClassInfo * rci, const LiveIntervals * lis, const MachineBasicBlock * mbb, MachineBasicBlock::const_iterator pos, bool ShouldTrackUntiedDefs = false)
Setup the RegPressureTracker.
TODO: Add support for pressure without LiveIntervals.
Definition at line 177 of file RegisterPressure.cpp.
References llvm::TargetRegisterInfo::getNumRegPressureSets(), llvm::MCRegisterInfo::getNumRegs(), llvm::MachineRegisterInfo::getNumVirtRegs(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::RegisterPressure::MaxSetPressure, llvm::LiveRegSet::PhysRegs, reset(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::setUniverse(), and llvm::LiveRegSet::VirtRegs.
Referenced by llvm::ScheduleDAGMILive::buildDAGWithRegPressure(), and llvm::ScheduleDAGMILive::initRegPressure().
void RegPressureTracker::initLiveThru (const RegPressureTracker & RPTracker)
Initialize the LiveThru pressure set based on the untied defs found in RPTracker.
The register tracker is unaware of global liveness so ignores normal live-thru ranges.
However, two-address or coalesced chains can also lead to live ranges with no holes. Count these to inform heuristics that we can never drop below this pressure.
Definition at line 289 of file RegisterPressure.cpp.
References llvm::TargetRegisterInfo::getNumRegPressureSets(), llvm::MachineRegisterInfo::getPressureSets(), hasUntiedDef(), increaseSetPressure(), isBottomClosed(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::RegisterPressure::LiveOutRegs, and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::ScheduleDAGMILive::initRegPressure().
void llvm::RegPressureTracker::initLiveThru (ArrayRef< unsigned > PressureSet) [inline]
Copy an existing live thru pressure result.
Definition at line 320 of file RegisterPressure.h.
References llvm::ArrayRef< T >::begin(), and llvm::ArrayRef< T >::end().
bool RegPressureTracker::isBottomClosed () const
Does this pressure result have a valid bottom position and live outs.
Definition at line 218 of file RegisterPressure.cpp.
Referenced by advance(), closeRegion(), dump(), getMaxPressureDelta(), getPressureAfterInst(), initLiveThru(), and recede().
bool RegPressureTracker::isTopClosed () const
Does this pressure result have a valid top position and live ins.
Definition at line 210 of file RegisterPressure.cpp.
Referenced by advance(), closeRegion(), dump(), getMaxPressureDelta(), getPressureAfterInst(), and recede().
bool RegPressureTracker::recede (SmallVectorImpl< unsigned > * LiveUses = nullptr, PressureDiff * PDiff = nullptr)
Recede across the previous instruction.
If LiveUses is provided, record any RegUnits that are made live by the current instruction's uses. This includes registers that are both defined and used by the instruction. If a pressure difference pointer is provided record the changes is pressure caused by this instruction independent of liveness.
Definition at line 458 of file RegisterPressure.cpp.
References llvm::PressureDiff::addPressureChange(), llvm::MachineBasicBlock::begin(), closeBottom(), closeRegion(), collectOperands(), collectPDiff(), llvm::LiveRegSet::contains(), containsReg(), decreaseRegPressure(), discoverLiveOut(), llvm::LiveRegSet::erase(), llvm::LiveIntervals::getInstructionIndex(), getLiveRange(), llvm::SlotIndex::getRegSlot(), increaseRegPressure(), llvm::LiveRegSet::insert(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::insert(), isBottomClosed(), llvm::LiveQueryResult::isDeadDef(), llvm::LiveQueryResult::isKill(), isTopClosed(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::LiveRange::Query(), and llvm::LiveQueryResult::valueDefined().
Referenced by llvm::ScheduleDAGMILive::buildDAGWithRegPressure(), llvm::ScheduleDAGInstrs::buildSchedGraph(), llvm::ScheduleDAGMILive::initRegPressure(), and llvm::ScheduleDAGMILive::scheduleMI().
void RegPressureTracker::reset ()
Definition at line 156 of file RegisterPressure.cpp.
References llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::clear(), llvm::RegisterPressure::MaxSetPressure, llvm::LiveRegSet::PhysRegs, and llvm::LiveRegSet::VirtRegs.
Referenced by llvm::ScheduleDAGMILive::buildDAGWithRegPressure(), and init().
void llvm::RegPressureTracker::setPos (MachineBasicBlock::const_iterator Pos) [inline]
Definition at line 299 of file RegisterPressure.h.
Referenced by llvm::ScheduleDAGMILive::schedule(), and llvm::ScheduleDAGMILive::scheduleMI().
The documentation for this class was generated from the following files:
RegisterPressure.h
RegisterPressure.cpp