LLVM: llvm::BitCastInst Class Reference
llvm::BitCastInst Class Reference
This class represents a no-op cast from one type to another.
#include <Instructions.h>
Public Member Functions
BitCastInst (Value *S, Type *Ty, const Twine &NameStr="", Instruction *InsertBefore=nullptr)
Constructor with insert-before-instruction semantics.
BitCastInst (Value *S, Type *Ty, const Twine &NameStr, BasicBlock *InsertAtEnd)
Constructor with insert-at-end-of-block semantics.
Static Public Member Functions
static bool classof (const Instruction *I)
Methods for support type inquiry through isa, cast, and dyn_cast:
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
BitCastInst * clone_impl () const override
Clone an identical BitCastInst.
Detailed Description
This class represents a no-op cast from one type to another.
Definition at line 3918 of file Instructions.h.
Constructor & Destructor Documentation
BitCastInst::BitCastInst (Value * S, Type * Ty, const Twine & NameStr = "", Instruction * InsertBefore = nullptr)
Constructor with insert-before-instruction semantics.
Parameters:
S The value to be casted
Ty The type to casted to
NameStr A name for the new instruction
InsertBefore Where to insert the new instruction
Definition at line 2941 of file Instructions.cpp.
References llvm::CastInst::castIsValid(), and llvm::CastInst::getOpcode().
Referenced by clone_impl().
BitCastInst::BitCastInst (Value * S, Type * Ty, const Twine & NameStr, BasicBlock * InsertAtEnd)
Constructor with insert-at-end-of-block semantics.
Parameters:
S The value to be casted
Ty The type to casted to
NameStr A name for the new instruction
InsertAtEnd The block to insert the instruction into
Definition at line 2947 of file Instructions.cpp.
References llvm::CastInst::castIsValid(), and llvm::CastInst::getOpcode().
Member Function Documentation
static bool llvm::BitCastInst::classof (const Instruction * I) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::CastInst.
Definition at line 3941 of file Instructions.h.
References llvm::Instruction::getOpcode().
Referenced by classof().
static bool llvm::BitCastInst::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::CastInst.
Definition at line 3944 of file Instructions.h.
References classof().
BitCastInst * BitCastInst::clone_impl () const [override, protected, virtual]
Clone an identical BitCastInst.
Implements llvm::Instruction.
Definition at line 3565 of file Instructions.cpp.
References BitCastInst(), llvm::User::getOperand(), and llvm::Value::getType().
The documentation for this class was generated from the following files:
Instructions.h
Instructions.cpp