LLVM: llvm::MemIntrinsicSDNode Class Reference
llvm::MemIntrinsicSDNode Class Reference
This SDNode is used for target intrinsics that touch memory and need an associated MachineMemOperand.
#include <SelectionDAGNodes.h>
Public Member Functions
MemIntrinsicSDNode (unsigned Opc, unsigned Order, DebugLoc dl, SDVTList VTs, ArrayRef< SDValue > Ops, EVT MemoryVT, MachineMemOperand *MMO)
Static Public Member Functions
static bool classof (const SDNode *N)
Detailed Description
This SDNode is used for target intrinsics that touch memory and need an associated MachineMemOperand.
Its opcode may be INTRINSIC_VOID, INTRINSIC_W_CHAIN, PREFETCH, or a target-specific opcode with a value not less than FIRST_TARGET_MEMORY_OPCODE.
Definition at line 1323 of file SelectionDAGNodes.h.
Constructor & Destructor Documentation
llvm::MemIntrinsicSDNode::MemIntrinsicSDNode (unsigned Opc, unsigned Order, DebugLoc dl, SDVTList VTs, ArrayRef< SDValue > Ops, EVT MemoryVT, MachineMemOperand * MMO) [inline]
Definition at line 1325 of file SelectionDAGNodes.h.
References llvm::SDNode::SubclassData.
Member Function Documentation
static bool llvm::MemIntrinsicSDNode::classof (const SDNode * N) [inline, static]
Reimplemented from llvm::MemSDNode.
Definition at line 1333 of file SelectionDAGNodes.h.
References llvm::SDNode::getOpcode(), llvm::SDNode::isMemIntrinsic(), llvm::SDNode::isTargetMemoryOpcode(), and llvm::ISD::PREFETCH.
The documentation for this class was generated from the following file:
SelectionDAGNodes.h