LLVM: llvm::DbgInfoIntrinsic Class Reference
llvm::DbgInfoIntrinsic Class Reference
DbgInfoIntrinsic - This is the common base class for debug info intrinsics.
#include <IntrinsicInst.h>
Static Public Member Functions
static bool classof (const IntrinsicInst *I)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
static Value * StripCast (Value *C)
Detailed Description
DbgInfoIntrinsic - This is the common base class for debug info intrinsics.
Definition at line 61 of file IntrinsicInst.h.
Member Function Documentation
static bool llvm::DbgInfoIntrinsic::classof (const IntrinsicInst * I) [inline, static]
Reimplemented in llvm::DbgValueInst, and llvm::DbgDeclareInst.
Definition at line 65 of file IntrinsicInst.h.
References llvm::IntrinsicInst::getIntrinsicID().
Referenced by classof().
static bool llvm::DbgInfoIntrinsic::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::IntrinsicInst.
Reimplemented in llvm::DbgValueInst, and llvm::DbgDeclareInst.
Definition at line 73 of file IntrinsicInst.h.
References classof().
Value * DbgInfoIntrinsic::StripCast (Value * C) [static]
Definition at line 41 of file IntrinsicInst.cpp.
References llvm::C, CastOperand(), and llvm::dyn_cast().
The documentation for this class was generated from the following files:
IntrinsicInst.h
IntrinsicInst.cpp