LLVM: llvm::MipsSubtarget Class Reference
llvm::MipsSubtarget Class Reference
#include <MipsSubtarget.h>
Public Member Functions
bool enablePostRAScheduler () const override
This overrides the PostRAScheduler bit in the SchedModel for each CPU.
void getCriticalPathRCs (RegClassVector &CriticalPathRCs) const override
CodeGenOpt::Level getOptLevelToEnablePostRAScheduler () const override
bool isABI_EABI () const
Only O32 and EABI supported right now.
bool isABI_N64 () const
bool isABI_N32 () const
bool isABI_O32 () const
const MipsABIInfo & getABI () const
bool isABI_FPXX () const
MipsSubtarget (const Triple &TT, const std::string &CPU, const std::string &FS, bool little, const MipsTargetMachine &TM)
This constructor initializes the data members to match that of the specified triple.
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
bool hasMips1 () const
bool hasMips2 () const
bool hasMips3 () const
bool hasMips4 () const
bool hasMips5 () const
bool hasMips4_32 () const
bool hasMips4_32r2 () const
bool hasMips32 () const
bool hasMips32r2 () const
bool hasMips32r3 () const
bool hasMips32r5 () const
bool hasMips32r6 () const
bool hasMips64 () const
bool hasMips64r2 () const
bool hasMips64r3 () const
bool hasMips64r5 () const
bool hasMips64r6 () const
bool hasCnMips () const
bool isLittle () const
bool isABICalls () const
bool isFPXX () const
bool isFP64bit () const
bool useOddSPReg () const
bool noOddSPReg () const
bool isNaN2008 () const
bool isGP64bit () const
bool isGP32bit () const
unsigned getGPRSizeInBytes () const
bool isSingleFloat () const
bool hasVFPU () const
bool inMips16Mode () const
bool inMips16ModeDefault () const
bool inMips16HardFloat () const
bool inMicroMipsMode () const
bool inMicroMips32r6Mode () const
bool hasDSP () const
bool hasDSPR2 () const
bool hasMSA () const
bool useSmallSection () const
bool hasStandardEncoding () const
bool useSoftFloat () const
bool enableLongBranchPass () const
bool hasExtractInsert () const
Features related to the presence of specific instructions.
bool hasMTHC1 () const
bool allowMixed16_32 () const
bool os16 () const
bool isTargetNaCl () const
unsigned stackAlignment () const
Reloc::Model getRelocationModel () const
MipsSubtarget & initializeSubtargetDependencies (StringRef CPU, StringRef FS, const TargetMachine &TM)
bool systemSupportsUnalignedAccess () const
Does the system support unaligned memory access.
void setHelperClassesMips16 ()
void setHelperClassesMipsSE ()
const MipsSelectionDAGInfo * getSelectionDAGInfo () const override
const MipsInstrInfo * getInstrInfo () const override
const TargetFrameLowering * getFrameLowering () const override
const MipsRegisterInfo * getRegisterInfo () const override
const MipsTargetLowering * getTargetLowering () const override
const InstrItineraryData * getInstrItineraryData () const override
Static Public Member Functions
static bool useConstantIslands ()
Detailed Description
Definition at line 36 of file MipsSubtarget.h.
Constructor & Destructor Documentation
MipsSubtarget::MipsSubtarget (const Triple & TT, const std::string & CPU, const std::string & FS, bool little, const MipsTargetMachine & TM)
This constructor initializes the data members to match that of the specified triple.
Definition at line 62 of file MipsSubtarget.cpp.
References llvm::errs(), llvm::TargetMachine::getRelocationModel(), GPOpt, hasDSP(), hasMips32r6(), hasMips64r6(), hasMSA(), isABI_EABI(), isABI_N32(), isABI_N64(), isABI_O32(), isFP64bit(), isGP64bit(), isNaN2008(), llvm::Reloc::PIC_, llvm::report_fatal_error(), and useOddSPReg().
Member Function Documentation
bool llvm::MipsSubtarget::allowMixed16_32 () const [inline]
Definition at line 248 of file MipsSubtarget.h.
References inMips16ModeDefault().
Referenced by enableLongBranchPass(), and llvm::MipsTargetMachine::getTargetIRAnalysis().
bool llvm::MipsSubtarget::enableLongBranchPass () const [inline]
Definition at line 240 of file MipsSubtarget.h.
References allowMixed16_32(), and hasStandardEncoding().
bool MipsSubtarget::enablePostRAScheduler () const [override]
This overrides the PostRAScheduler bit in the SchedModel for each CPU.
This overrides the PostRAScheduler bit in the SchedModel for any CPU.
Definition at line 129 of file MipsSubtarget.cpp.
const MipsABIInfo & MipsSubtarget::getABI () const
Definition at line 170 of file MipsSubtarget.cpp.
References llvm::MipsTargetMachine::getABI().
Referenced by llvm::MipsSEInstrInfo::adjustStackPtr(), llvm::MipsFrameLowering::eliminateCallFramePseudoInstr(), llvm::MipsSEFrameLowering::emitEpilogue(), llvm::MipsSEFrameLowering::emitPrologue(), isABI_EABI(), isABI_N32(), isABI_N64(), isABI_O32(), and llvm::MipsSEFrameLowering::processFunctionBeforeCalleeSavedScan().
void MipsSubtarget::getCriticalPathRCs (RegClassVector & CriticalPathRCs) const [override]
Definition at line 131 of file MipsSubtarget.cpp.
References isGP64bit().
const TargetFrameLowering* llvm::MipsSubtarget::getFrameLowering () const [inline, override]
Definition at line 282 of file MipsSubtarget.h.
Referenced by llvm::MipsRegisterInfo::canRealignStack(), llvm::MipsRegisterInfo::getFrameRegister(), llvm::MipsRegisterInfo::getReservedRegs(), llvm::MipsTargetLowering::HandleByVal(), and llvm::MipsRegisterInfo::needsStackRealignment().
unsigned llvm::MipsSubtarget::getGPRSizeInBytes () const [inline]
Definition at line 215 of file MipsSubtarget.h.
References isGP64bit().
Referenced by llvm::MipsTargetLowering::HandleByVal().
const MipsInstrInfo* llvm::MipsSubtarget::getInstrInfo () const [inline, override]
Definition at line 281 of file MipsSubtarget.h.
Referenced by llvm::MipsFrameLowering::eliminateCallFramePseudoInstr(), llvm::Mips16FrameLowering::emitEpilogue(), llvm::MipsSEFrameLowering::emitEpilogue(), llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::Mips16FrameLowering::processFunctionBeforeCalleeSavedScan(), and llvm::MipsSEFrameLowering::spillCalleeSavedRegisters().
const InstrItineraryData* llvm::MipsSubtarget::getInstrItineraryData () const [inline, override]
Definition at line 291 of file MipsSubtarget.h.
CodeGenOpt::Level MipsSubtarget::getOptLevelToEnablePostRAScheduler () const [override]
Definition at line 137 of file MipsSubtarget.cpp.
References Aggressive.
const MipsRegisterInfo* llvm::MipsSubtarget::getRegisterInfo () const [inline, override]
Definition at line 285 of file MipsSubtarget.h.
Referenced by llvm::MipsSEFrameLowering::emitEpilogue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::MipsFrameLowering::estimateStackSize(), llvm::MipsTargetLowering::getOpndList(), llvm::MipsFrameLowering::hasBP(), llvm::MipsFrameLowering::hasFP(), llvm::Mips16TargetLowering::Mips16TargetLowering(), and llvm::MipsSETargetLowering::MipsSETargetLowering().
Reloc::Model MipsSubtarget::getRelocationModel () const
Definition at line 162 of file MipsSubtarget.cpp.
References llvm::TargetMachine::getRelocationModel().
const MipsSelectionDAGInfo* llvm::MipsSubtarget::getSelectionDAGInfo () const [inline, override]
Definition at line 278 of file MipsSubtarget.h.
const MipsTargetLowering* llvm::MipsSubtarget::getTargetLowering () const [inline, override]
Definition at line 288 of file MipsSubtarget.h.
bool llvm::MipsSubtarget::hasCnMips () const [inline]
Definition at line 204 of file MipsSubtarget.h.
Referenced by llvm::MipsSETargetLowering::MipsSETargetLowering(), and llvm::MipsTargetLowering::MipsTargetLowering().
bool llvm::MipsSubtarget::hasDSP () const [inline]
Definition at line 231 of file MipsSubtarget.h.
Referenced by llvm::MipsSETargetLowering::getRepRegClassFor(), llvm::MipsSETargetLowering::MipsSETargetLowering(), MipsSubtarget(), and performDSPShiftCombine().
bool llvm::MipsSubtarget::hasDSPR2 () const [inline]
Definition at line 232 of file MipsSubtarget.h.
Referenced by llvm::MipsSETargetLowering::MipsSETargetLowering(), performSRACombine(), and performSRLCombine().
bool llvm::MipsSubtarget::hasExtractInsert () const [inline]
Features related to the presence of specific instructions.
Definition at line 245 of file MipsSubtarget.h.
References hasMips32r2(), and inMips16Mode().
Referenced by performANDCombine(), and performORCombine().
bool llvm::MipsSubtarget::hasMips1 () const [inline]
Definition at line 171 of file MipsSubtarget.h.
bool llvm::MipsSubtarget::hasMips2 () const [inline]
Definition at line 172 of file MipsSubtarget.h.
bool llvm::MipsSubtarget::hasMips3 () const [inline]
Definition at line 173 of file MipsSubtarget.h.
bool llvm::MipsSubtarget::hasMips32 () const [inline]
Definition at line 178 of file MipsSubtarget.h.
References hasMips64().
Referenced by llvm::MipsTargetLowering::MipsTargetLowering(), performADDECombine(), and performSUBECombine().
bool llvm::MipsSubtarget::hasMips32r2 () const [inline]
Definition at line 182 of file MipsSubtarget.h.
References hasMips64r2().
Referenced by hasExtractInsert(), hasMTHC1(), and llvm::MipsTargetLowering::MipsTargetLowering().
bool llvm::MipsSubtarget::hasMips32r3 () const [inline]
Definition at line 186 of file MipsSubtarget.h.
References hasMips64r2().
bool llvm::MipsSubtarget::hasMips32r5 () const [inline]
Definition at line 190 of file MipsSubtarget.h.
References hasMips64r2().
bool llvm::MipsSubtarget::hasMips32r6 () const [inline]
Definition at line 194 of file MipsSubtarget.h.
References hasMips64r6().
Referenced by inMicroMips32r6Mode(), llvm::MipsSETargetLowering::MipsSETargetLowering(), MipsSubtarget(), llvm::MipsTargetLowering::MipsTargetLowering(), performADDECombine(), and systemSupportsUnalignedAccess().
bool llvm::MipsSubtarget::hasMips4 () const [inline]
Definition at line 174 of file MipsSubtarget.h.
bool llvm::MipsSubtarget::hasMips4_32 () const [inline]
Definition at line 176 of file MipsSubtarget.h.
bool llvm::MipsSubtarget::hasMips4_32r2 () const [inline]
Definition at line 177 of file MipsSubtarget.h.
bool llvm::MipsSubtarget::hasMips5 () const [inline]
Definition at line 175 of file MipsSubtarget.h.
bool llvm::MipsSubtarget::hasMips64 () const [inline]
Definition at line 198 of file MipsSubtarget.h.
Referenced by hasMips32(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::MipsSEFrameLowering::processFunctionBeforeCalleeSavedScan(), and stackAlignment().
bool llvm::MipsSubtarget::hasMips64r2 () const [inline]
Definition at line 199 of file MipsSubtarget.h.
Referenced by hasMips32r2(), hasMips32r3(), hasMips32r5(), and llvm::MipsTargetLowering::MipsTargetLowering().
bool llvm::MipsSubtarget::hasMips64r3 () const [inline]
Definition at line 200 of file MipsSubtarget.h.
bool llvm::MipsSubtarget::hasMips64r5 () const [inline]
Definition at line 201 of file MipsSubtarget.h.
bool llvm::MipsSubtarget::hasMips64r6 () const [inline]
Definition at line 202 of file MipsSubtarget.h.
Referenced by hasMips32r6(), llvm::MipsSETargetLowering::MipsSETargetLowering(), and MipsSubtarget().
bool llvm::MipsSubtarget::hasMSA () const [inline]
Definition at line 233 of file MipsSubtarget.h.
Referenced by llvm::MipsSETargetLowering::MipsSETargetLowering(), MipsSubtarget(), performANDCombine(), performORCombine(), performSRACombine(), and performXORCombine().
bool llvm::MipsSubtarget::hasMTHC1 () const [inline]
Definition at line 246 of file MipsSubtarget.h.
References hasMips32r2().
bool llvm::MipsSubtarget::hasStandardEncoding () const [inline]
Definition at line 236 of file MipsSubtarget.h.
References inMips16Mode().
Referenced by llvm::MipsRegisterInfo::canRealignStack(), and enableLongBranchPass().
bool llvm::MipsSubtarget::hasVFPU () const [inline]
Definition at line 217 of file MipsSubtarget.h.
MipsSubtarget & MipsSubtarget::initializeSubtargetDependencies (StringRef CPU, StringRef FS, const TargetMachine & TM)
Definition at line 142 of file MipsSubtarget.cpp.
References llvm::TargetMachine::getTargetTriple(), ParseSubtargetFeatures(), and llvm::MIPS_MC::selectMipsCPU().
bool llvm::MipsSubtarget::inMicroMips32r6Mode () const [inline]
Definition at line 230 of file MipsSubtarget.h.
References hasMips32r6().
bool llvm::MipsSubtarget::inMicroMipsMode () const [inline]
Definition at line 229 of file MipsSubtarget.h.
Referenced by llvm::MipsSEInstrInfo::copyPhysReg(), llvm::MipsAsmPrinter::EmitFunctionEntryLabel(), llvm::MipsSEInstrInfo::expandPostRAPseudo(), llvm::MipsFunctionInfo::getGlobalBaseReg(), and llvm::MipsTargetLowering::MipsTargetLowering().
bool llvm::MipsSubtarget::inMips16HardFloat () const [inline]
Definition at line 226 of file MipsSubtarget.h.
References inMips16Mode().
Referenced by llvm::MipsTargetLowering::getOpndList(), and llvm::MipsCCState::getSpecialCallingConvForCallee().
bool llvm::MipsSubtarget::inMips16Mode () const [inline]
Definition at line 218 of file MipsSubtarget.h.
Referenced by llvm::MipsFrameLowering::create(), llvm::MipsInstrInfo::create(), llvm::MipsTargetLowering::create(), llvm::MipsAsmPrinter::EmitFunctionBodyEnd(), llvm::MipsAsmPrinter::EmitFunctionBodyStart(), llvm::MipsAsmPrinter::EmitFunctionEntryLabel(), llvm::MipsAsmPrinter::EmitInstruction(), llvm::MipsRegisterInfo::getFrameRegister(), llvm::MipsFunctionInfo::getGlobalBaseReg(), llvm::MipsRegisterInfo::getReservedRegs(), hasExtractInsert(), hasStandardEncoding(), inMips16HardFloat(), llvm::MipsTargetLowering::MipsTargetLowering(), and llvm::MipsAsmPrinter::runOnMachineFunction().
bool llvm::MipsSubtarget::inMips16ModeDefault () const [inline]
Definition at line 219 of file MipsSubtarget.h.
Referenced by allowMixed16_32().
bool MipsSubtarget::isABI_EABI () const
Only O32 and EABI supported right now.
Definition at line 166 of file MipsSubtarget.cpp.
References getABI(), and llvm::MipsABIInfo::IsEABI().
Referenced by MipsSubtarget().
bool llvm::MipsSubtarget::isABI_FPXX () const [inline]
Definition at line 160 of file MipsSubtarget.h.
References isABI_O32().
bool MipsSubtarget::isABI_N32 () const
Definition at line 168 of file MipsSubtarget.cpp.
References getABI(), and llvm::MipsABIInfo::IsN32().
Referenced by llvm::MipsRegisterInfo::getCalleeSavedRegs(), llvm::MipsRegisterInfo::getCallPreservedMask(), and MipsSubtarget().
bool MipsSubtarget::isABI_N64 () const
Definition at line 167 of file MipsSubtarget.cpp.
References getABI(), and llvm::MipsABIInfo::IsN64().
Referenced by llvm::MipsSEFrameLowering::emitPrologue(), llvm::MipsRegisterInfo::getCalleeSavedRegs(), llvm::MipsRegisterInfo::getCallPreservedMask(), llvm::MipsSEInstrInfo::loadImmediate(), and MipsSubtarget().
bool MipsSubtarget::isABI_O32 () const
Definition at line 169 of file MipsSubtarget.cpp.
References getABI(), and llvm::MipsABIInfo::IsO32().
Referenced by llvm::MipsRegisterInfo::getReservedRegs(), isABI_FPXX(), and MipsSubtarget().
bool llvm::MipsSubtarget::isABICalls () const [inline]
Definition at line 207 of file MipsSubtarget.h.
Referenced by llvm::MipsAsmPrinter::EmitStartOfAsmFile(), and llvm::MipsRegisterInfo::getReservedRegs().
bool llvm::MipsSubtarget::isFP64bit () const [inline]
Definition at line 209 of file MipsSubtarget.h.
Referenced by llvm::MipsRegisterInfo::getCalleeSavedRegs(), llvm::MipsRegisterInfo::getCallPreservedMask(), llvm::MipsRegisterInfo::getReservedRegs(), llvm::MipsSETargetLowering::MipsSETargetLowering(), and MipsSubtarget().
bool llvm::MipsSubtarget::isFPXX () const [inline]
Definition at line 208 of file MipsSubtarget.h.
Referenced by llvm::MipsRegisterInfo::getCalleeSavedRegs(), and llvm::MipsRegisterInfo::getCallPreservedMask().
bool llvm::MipsSubtarget::isGP32bit () const [inline]
Definition at line 214 of file MipsSubtarget.h.
Referenced by llvm::MipsRegisterInfo::canRealignStack().
bool llvm::MipsSubtarget::isGP64bit () const [inline]
Definition at line 213 of file MipsSubtarget.h.
Referenced by getCriticalPathRCs(), getGPRSizeInBytes(), llvm::MipsTargetLowering::getRegisterByName(), llvm::MipsSETargetLowering::MipsSETargetLowering(), MipsSubtarget(), llvm::MipsTargetLowering::MipsTargetLowering(), and llvm::MipsAsmPrinter::PrintAsmOperand().
bool llvm::MipsSubtarget::isLittle () const [inline]
Definition at line 206 of file MipsSubtarget.h.
Referenced by CC_MipsO32(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::MipsTargetLowering::lowerLOAD(), llvm::MipsTargetLowering::lowerSTORE(), performDSPShiftCombine(), performORCombine(), and llvm::MipsAsmPrinter::PrintAsmOperand().
bool llvm::MipsSubtarget::isNaN2008 () const [inline]
Definition at line 212 of file MipsSubtarget.h.
Referenced by MipsSubtarget().
bool llvm::MipsSubtarget::isSingleFloat () const [inline]
Definition at line 216 of file MipsSubtarget.h.
Referenced by llvm::MipsRegisterInfo::getCalleeSavedRegs(), llvm::MipsRegisterInfo::getCallPreservedMask(), and llvm::MipsSETargetLowering::MipsSETargetLowering().
bool llvm::MipsSubtarget::isTargetNaCl () const [inline]
Definition at line 253 of file MipsSubtarget.h.
References llvm::Triple::isOSNaCl().
Referenced by llvm::MipsAsmPrinter::EmitFunctionEntryLabel(), llvm::MipsRegisterInfo::getReservedRegs(), and llvm::MipsAsmPrinter::runOnMachineFunction().
bool llvm::MipsSubtarget::noOddSPReg () const [inline]
Definition at line 211 of file MipsSubtarget.h.
bool llvm::MipsSubtarget::os16 () const [inline]
Definition at line 251 of file MipsSubtarget.h.
void llvm::MipsSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
Definition of function is auto generated by tblgen.
Referenced by initializeSubtargetDependencies().
void llvm::MipsSubtarget::setHelperClassesMips16 ()
void llvm::MipsSubtarget::setHelperClassesMipsSE ()
unsigned llvm::MipsSubtarget::stackAlignment () const [inline]
Definition at line 259 of file MipsSubtarget.h.
References hasMips64().
bool llvm::MipsSubtarget::systemSupportsUnalignedAccess () const [inline]
Does the system support unaligned memory access.
MIPS32r6/MIPS64r6 require full unaligned access support but does not specify which component of the system provides it. Hardware, software, and hybrid implementations are all valid.
Definition at line 272 of file MipsSubtarget.h.
References hasMips32r6().
Referenced by llvm::MipsSETargetLowering::allowsMisalignedMemoryAccesses(), llvm::MipsTargetLowering::lowerLOAD(), and llvm::MipsTargetLowering::lowerSTORE().
bool MipsSubtarget::useConstantIslands () [static]
Definition at line 157 of file MipsSubtarget.cpp.
References llvm::dbgs(), DEBUG, and Mips16ConstantIslands.
bool llvm::MipsSubtarget::useOddSPReg () const [inline]
Definition at line 210 of file MipsSubtarget.h.
Referenced by llvm::MipsRegisterInfo::getReservedRegs(), and MipsSubtarget().
bool llvm::MipsSubtarget::useSmallSection () const [inline]
Definition at line 234 of file MipsSubtarget.h.
Referenced by llvm::MipsRegisterInfo::getReservedRegs(), and llvm::MipsTargetObjectFile::IsGlobalInSmallSectionImpl().
bool llvm::MipsSubtarget::useSoftFloat () const [inline]
Definition at line 238 of file MipsSubtarget.h.
Referenced by llvm::Mips16TargetLowering::Mips16TargetLowering(), and llvm::MipsSETargetLowering::MipsSETargetLowering().
The documentation for this class was generated from the following files:
MipsSubtarget.h
MipsSubtarget.cpp