LLVM: llvm::TargetLoweringObjectFile Class Reference
llvm::TargetLoweringObjectFile Class Reference
#include <TargetLoweringObjectFile.h>
Public Member Functions
MCContext & getContext () const
TargetLoweringObjectFile ()
virtual ~TargetLoweringObjectFile ()
virtual void Initialize (MCContext &ctx, const TargetMachine &TM)
This method must be called before any actual lowering is done.
virtual void emitPersonalityValue (MCStreamer &Streamer, const TargetMachine &TM, const MCSymbol *Sym) const
virtual StringRef getDepLibFromLinkerOpt (StringRef LinkerOption) const
Extract the dependent library name from a linker option string.
virtual void emitModuleFlags (MCStreamer &Streamer, ArrayRef< Module::ModuleFlagEntry > Flags, Mangler &Mang, const TargetMachine &TM) const
Emit the module flags that the platform cares about.
virtual MCSection * getSectionForConstant (SectionKind Kind, const Constant *C) const
Given a constant with the SectionKind, return a section that it should be placed in.
MCSection * SectionForGlobal (const GlobalValue *GV, SectionKind Kind, Mangler &Mang, const TargetMachine &TM) const
This method computes the appropriate section to emit the specified global variable or function definition.
MCSection * SectionForGlobal (const GlobalValue *GV, Mangler &Mang, const TargetMachine &TM) const
This method computes the appropriate section to emit the specified global variable or function definition.
virtual void getNameWithPrefix (SmallVectorImpl< char > &OutName, const GlobalValue *GV, bool CannotUsePrivateLabel, Mangler &Mang, const TargetMachine &TM) const
virtual MCSection * getSectionForJumpTable (const Function &F, Mangler &Mang, const TargetMachine &TM) const
virtual bool shouldPutJumpTableInFunctionSection (bool UsesLabelDifference, const Function &F) const
virtual MCSection * getExplicitSectionGlobal (const GlobalValue *GV, SectionKind Kind, Mangler &Mang, const TargetMachine &TM) const =0
Targets should implement this method to assign a section to globals with an explicit section specfied.
virtual const MCSection * getSpecialCasedSectionGlobals (const GlobalValue *GV, SectionKind Kind, Mangler &Mang) const
Allow the target to completely override section assignment of a global.
virtual const MCExpr * getTTypeGlobalReference (const GlobalValue *GV, unsigned Encoding, Mangler &Mang, const TargetMachine &TM, MachineModuleInfo *MMI, MCStreamer &Streamer) const
Return an MCExpr to use for a reference to the specified global variable from exception handling information.
MCSymbol * getSymbolWithGlobalValueBase (const GlobalValue *GV, StringRef Suffix, Mangler &Mang, const TargetMachine &TM) const
Return the MCSymbol for a private symbol with global value name as its base, with the specified suffix.
virtual MCSymbol * getCFIPersonalitySymbol (const GlobalValue *GV, Mangler &Mang, const TargetMachine &TM, MachineModuleInfo *MMI) const
const MCExpr * getTTypeReference (const MCSymbolRefExpr *Sym, unsigned Encoding, MCStreamer &Streamer) const
virtual MCSection * getStaticCtorSection (unsigned Priority, const MCSymbol *KeySym) const
virtual MCSection * getStaticDtorSection (unsigned Priority, const MCSymbol *KeySym) const
virtual const MCExpr * getDebugThreadLocalSymbol (const MCSymbol *Sym) const
Create a symbol reference to describe the given TLS variable when emitting the address in debug info.
virtual const MCExpr * getExecutableRelativeSymbol (const ConstantExpr *CE, Mangler &Mang, const TargetMachine &TM) const
bool supportIndirectSymViaGOTPCRel () const
Target supports replacing a data "PC"-relative access to a symbol through another symbol, by accessing the later via a GOT entry instead?
bool supportGOTPCRelWithOffset () const
Target GOT "PC"-relative relocation supports encoding an additional binary expression with an offset?
virtual const MCExpr * getIndirectSymViaGOTPCRel (const MCSymbol *Sym, const MCValue &MV, int64_t Offset, MachineModuleInfo *MMI, MCStreamer &Streamer) const
Get the target specific PC relative GOT entry relocation.
Static Public Member Functions
static SectionKind getKindForGlobal (const GlobalValue *GV, const TargetMachine &TM)
Classify the specified global variable into a set of target independent categories embodied in SectionKind.
Protected Member Functions
virtual MCSection * SelectSectionForGlobal (const GlobalValue *GV, SectionKind Kind, Mangler &Mang, const TargetMachine &TM) const =0
Protected Attributes
const DataLayout * DL
bool SupportIndirectSymViaGOTPCRel
bool SupportGOTPCRelWithOffset
Detailed Description
Definition at line 37 of file TargetLoweringObjectFile.h.
Constructor & Destructor Documentation
llvm::TargetLoweringObjectFile::TargetLoweringObjectFile () [inline]
Definition at line 52 of file TargetLoweringObjectFile.h.
TargetLoweringObjectFile::~TargetLoweringObjectFile () [virtual]
Definition at line 51 of file TargetLoweringObjectFile.cpp.
Member Function Documentation
virtual void llvm::TargetLoweringObjectFile::emitModuleFlags (MCStreamer & Streamer, ArrayRef< Module::ModuleFlagEntry > Flags, Mangler & Mang, const TargetMachine & TM) const [inline, virtual]
Emit the module flags that the platform cares about.
Reimplemented in llvm::TargetLoweringObjectFileCOFF, and llvm::TargetLoweringObjectFileMachO.
Definition at line 74 of file TargetLoweringObjectFile.h.
Referenced by llvm::AsmPrinter::doFinalization().
void TargetLoweringObjectFile::emitPersonalityValue (MCStreamer & Streamer, const TargetMachine & TM, const MCSymbol * Sym) const [virtual]
Reimplemented in llvm::TargetLoweringObjectFileELF.
Definition at line 122 of file TargetLoweringObjectFile.cpp.
Referenced by llvm::DwarfCFIException::endModule().
MCSymbol * TargetLoweringObjectFile::getCFIPersonalitySymbol (const GlobalValue * GV, Mangler & Mang, const TargetMachine & TM, MachineModuleInfo * MMI) const [virtual]
Reimplemented in llvm::TargetLoweringObjectFileMachO, llvm::TargetLoweringObjectFileELF, llvm::AArch64_MachoTargetObjectFile, and llvm::X86_64MachoTargetObjectFile.
Definition at line 116 of file TargetLoweringObjectFile.cpp.
References llvm::TargetMachine::getSymbol().
Referenced by llvm::DwarfCFIException::beginFunction(), and llvm::WinException::beginFunction().
MCContext& llvm::TargetLoweringObjectFile::getContext () const [inline]
Definition at line 50 of file TargetLoweringObjectFile.h.
Referenced by llvm::TargetLoweringObjectFileMachO::emitModuleFlags(), llvm::XCoreTargetObjectFile::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileMachO::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), llvm::AArch64_MachoTargetObjectFile::getIndirectSymViaGOTPCRel(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), llvm::TargetLoweringObjectFileCOFF::getSectionForJumpTable(), llvm::TargetLoweringObjectFileCOFF::getStaticCtorSection(), llvm::TargetLoweringObjectFileCOFF::getStaticDtorSection(), llvm::TargetMachine::getSymbol(), llvm::SparcELFTargetObjectFile::getTTypeGlobalReference(), llvm::AArch64_MachoTargetObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference(), getTTypeGlobalReference(), getTTypeReference(), llvm::HexagonTargetObjectFile::Initialize(), llvm::MipsTargetObjectFile::Initialize(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), and llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal().
const MCExpr * TargetLoweringObjectFile::getDebugThreadLocalSymbol (const MCSymbol * Sym) const [virtual]
Create a symbol reference to describe the given TLS variable when emitting the address in debug info.
Reimplemented in llvm::ARMElfTargetObjectFile.
Definition at line 341 of file TargetLoweringObjectFile.cpp.
References llvm::MCSymbolRefExpr::create().
Referenced by llvm::AddressPool::emit(), and llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
virtual StringRef llvm::TargetLoweringObjectFile::getDepLibFromLinkerOpt (StringRef LinkerOption) const [inline, virtual]
Extract the dependent library name from a linker option string.
Returns StringRef() if the option does not specify a library.
Reimplemented in llvm::TargetLoweringObjectFileCOFF, and llvm::TargetLoweringObjectFileMachO.
Definition at line 69 of file TargetLoweringObjectFile.h.
virtual const MCExpr* llvm::TargetLoweringObjectFile::getExecutableRelativeSymbol (const ConstantExpr * CE, Mangler & Mang, const TargetMachine & TM) const [inline, virtual]
Definition at line 165 of file TargetLoweringObjectFile.h.
virtual MCSection* llvm::TargetLoweringObjectFile::getExplicitSectionGlobal (const GlobalValue * GV, SectionKind Kind, Mangler & Mang, const TargetMachine & TM) const [pure virtual]
Targets should implement this method to assign a section to globals with an explicit section specfied.
The implementation of this method can assume that GV->hasSection() is true.
Implemented in llvm::TargetLoweringObjectFileCOFF, llvm::TargetLoweringObjectFileMachO, llvm::NVPTXTargetObjectFile, llvm::TargetLoweringObjectFileELF, and llvm::XCoreTargetObjectFile.
Referenced by SectionForGlobal().
virtual const MCExpr* llvm::TargetLoweringObjectFile::getIndirectSymViaGOTPCRel (const MCSymbol * Sym, const MCValue & MV, int64_t Offset, MachineModuleInfo * MMI, MCStreamer & Streamer) const [inline, virtual]
Get the target specific PC relative GOT entry relocation.
Reimplemented in llvm::TargetLoweringObjectFileMachO, llvm::AArch64_MachoTargetObjectFile, and llvm::X86_64MachoTargetObjectFile.
Definition at line 183 of file TargetLoweringObjectFile.h.
Referenced by handleIndirectSymViaGOTPCRel().
SectionKind TargetLoweringObjectFile::getKindForGlobal (const GlobalValue * GV, const TargetMachine & TM) [static]
Classify the specified global variable into a set of target independent categories embodied in SectionKind.
getKindForGlobal - This is a top-level target-independent classifier for a global variable.
Given an global variable and information from TM, it classifies the global in a variety of ways that make various target implementations simpler. The target implementation is free to ignore this extra info of course.
Definition at line 133 of file TargetLoweringObjectFile.cpp.
References llvm::C, llvm::dyn_cast(), llvm::SectionKind::getBSS(), llvm::SectionKind::getBSSExtern(), llvm::SectionKind::getBSSLocal(), llvm::SectionKind::getCommon(), llvm::TargetMachine::getDataLayout(), llvm::SectionKind::getDataNoRel(), llvm::SectionKind::getDataRel(), llvm::SectionKind::getDataRelLocal(), llvm::GlobalVariable::getInitializer(), llvm::SectionKind::getMergeable1ByteCString(), llvm::SectionKind::getMergeable2ByteCString(), llvm::SectionKind::getMergeable4ByteCString(), llvm::SectionKind::getMergeableConst16(), llvm::SectionKind::getMergeableConst4(), llvm::SectionKind::getMergeableConst8(), llvm::SectionKind::getReadOnly(), llvm::SectionKind::getReadOnlyWithRel(), llvm::SectionKind::getReadOnlyWithRelLocal(), llvm::Constant::getRelocationInfo(), llvm::TargetMachine::getRelocationModel(), llvm::SectionKind::getText(), llvm::SectionKind::getThreadBSS(), llvm::SectionKind::getThreadData(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::Constant::GlobalRelocations, llvm::GlobalValue::hasAvailableExternallyLinkage(), llvm::GlobalValue::hasCommonLinkage(), llvm::GlobalValue::hasExternalLinkage(), llvm::GlobalValue::hasLocalLinkage(), llvm::GlobalValue::hasUnnamedAddr(), llvm::GlobalVariable::isConstant(), llvm::GlobalValue::isDeclaration(), IsNullTerminatedString(), isSuitableForBSS(), llvm::GlobalValue::isThreadLocal(), llvm_unreachable, llvm::Constant::LocalRelocation, llvm::Constant::NoRelocation, llvm::TargetOptions::NoZerosInBSS, llvm::TargetMachine::Options, and llvm::Reloc::Static.
Referenced by llvm::AsmPrinter::EmitGlobalVariable(), llvm::TargetMachine::getNameWithPrefix(), llvm::MipsTargetObjectFile::IsGlobalInSmallSection(), llvm::HexagonTargetObjectFile::IsGlobalInSmallSection(), and SectionForGlobal().
void TargetLoweringObjectFile::getNameWithPrefix (SmallVectorImpl< char > & OutName, const GlobalValue * GV, bool CannotUsePrivateLabel, Mangler & Mang, const TargetMachine & TM) const [virtual]
Reimplemented in llvm::TargetLoweringObjectFileCOFF.
Definition at line 347 of file TargetLoweringObjectFile.cpp.
References llvm::Mangler::getNameWithPrefix().
Referenced by llvm::TargetMachine::getNameWithPrefix().
MCSection * TargetLoweringObjectFile::getSectionForConstant (SectionKind Kind, const Constant * C) const [virtual]
Given a constant with the SectionKind, return a section that it should be placed in.
Given a mergable constant with the specified size and relocation information, return a section that it should be placed in.
Reimplemented in llvm::TargetLoweringObjectFileMachO, llvm::NVPTXTargetObjectFile, llvm::TargetLoweringObjectFileELF, llvm::MipsTargetObjectFile, and llvm::XCoreTargetObjectFile.
Definition at line 300 of file TargetLoweringObjectFile.cpp.
References llvm::MCObjectFileInfo::DataSection, llvm::SectionKind::isReadOnly(), and llvm::MCObjectFileInfo::ReadOnlySection.
Referenced by llvm::AsmPrinter::doFinalization(), llvm::AsmPrinter::EmitConstantPool(), and getSectionForJumpTable().
MCSection * TargetLoweringObjectFile::getSectionForJumpTable (const Function & F, Mangler & Mang, const TargetMachine & TM) const [virtual]
Reimplemented in llvm::TargetLoweringObjectFileCOFF, and llvm::TargetLoweringObjectFileELF.
Definition at line 274 of file TargetLoweringObjectFile.cpp.
References llvm::SectionKind::getReadOnly(), and getSectionForConstant().
Referenced by llvm::AsmPrinter::EmitJumpTableInfo().
virtual const MCSection* llvm::TargetLoweringObjectFile::getSpecialCasedSectionGlobals (const GlobalValue * GV, SectionKind Kind, Mangler & Mang) const [inline, virtual]
Allow the target to completely override section assignment of a global.
Definition at line 121 of file TargetLoweringObjectFile.h.
virtual MCSection* llvm::TargetLoweringObjectFile::getStaticCtorSection (unsigned Priority, const MCSymbol * KeySym) const [inline, virtual]
Reimplemented in llvm::TargetLoweringObjectFileCOFF, and llvm::TargetLoweringObjectFileELF.
Definition at line 150 of file TargetLoweringObjectFile.h.
References llvm::MCObjectFileInfo::StaticCtorSection.
virtual MCSection* llvm::TargetLoweringObjectFile::getStaticDtorSection (unsigned Priority, const MCSymbol * KeySym) const [inline, virtual]
Reimplemented in llvm::TargetLoweringObjectFileCOFF, and llvm::TargetLoweringObjectFileELF.
Definition at line 155 of file TargetLoweringObjectFile.h.
References llvm::MCObjectFileInfo::StaticDtorSection.
MCSymbol * TargetLoweringObjectFile::getSymbolWithGlobalValueBase (const GlobalValue * GV, StringRef Suffix, Mangler & Mang, const TargetMachine & TM) const
Return the MCSymbol for a private symbol with global value name as its base, with the specified suffix.
Definition at line 104 of file TargetLoweringObjectFile.cpp.
References llvm::StringRef::begin(), DL, llvm::StringRef::empty(), llvm::StringRef::end(), llvm::TargetMachine::getNameWithPrefix(), llvm::MCContext::getOrCreateSymbol(), and llvm::DataLayout::getPrivateGlobalPrefix().
Referenced by llvm::TargetLoweringObjectFileMachO::getCFIPersonalitySymbol(), llvm::AsmPrinter::getSymbolWithGlobalValueBase(), llvm::SparcELFTargetObjectFile::getTTypeGlobalReference(), and llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference().
const MCExpr * TargetLoweringObjectFile::getTTypeGlobalReference (const GlobalValue * GV, unsigned Encoding, Mangler & Mang, const TargetMachine & TM, MachineModuleInfo * MMI, MCStreamer & Streamer) const [virtual]
Return an MCExpr to use for a reference to the specified global variable from exception handling information.
getTTypeGlobalReference - Return an MCExpr to use for a reference to the specified global variable from exception handling information.
Reimplemented in llvm::TargetLoweringObjectFileMachO, llvm::TargetLoweringObjectFileELF, llvm::ARMElfTargetObjectFile, llvm::AArch64_MachoTargetObjectFile, llvm::SparcELFTargetObjectFile, and llvm::X86_64MachoTargetObjectFile.
Definition at line 311 of file TargetLoweringObjectFile.cpp.
References llvm::MCSymbolRefExpr::create(), getContext(), llvm::TargetMachine::getSymbol(), and getTTypeReference().
Referenced by llvm::AsmPrinter::EmitTTypeReference(), and llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference().
const MCExpr * TargetLoweringObjectFile::getTTypeReference (const MCSymbolRefExpr * Sym, unsigned Encoding, MCStreamer & Streamer) const
Definition at line 322 of file TargetLoweringObjectFile.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), llvm::MCContext::createTempSymbol(), llvm::dwarf::DW_EH_PE_absptr, llvm::dwarf::DW_EH_PE_pcrel, llvm::MCStreamer::EmitLabel(), getContext(), and llvm::report_fatal_error().
Referenced by llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference(), and getTTypeGlobalReference().
void TargetLoweringObjectFile::Initialize (MCContext & ctx, const TargetMachine & TM) [virtual]
This method must be called before any actual lowering is done.
Initialize - this method must be called before any actual lowering is done.
This specifies the current context for codegen, and gives the lowering implementations a chance to set up their default sections.
Reimplemented in llvm::NVPTXTargetObjectFile, llvm::ARMElfTargetObjectFile, llvm::XCoreTargetObjectFile, llvm::HexagonTargetObjectFile, and llvm::MipsTargetObjectFile.
Definition at line 43 of file TargetLoweringObjectFile.cpp.
References DL, llvm::TargetMachine::getCodeModel(), llvm::TargetMachine::getDataLayout(), llvm::TargetMachine::getRelocationModel(), llvm::TargetMachine::getTargetTriple(), and llvm::MCObjectFileInfo::InitMCObjectFileInfo().
Referenced by llvm::ARMElfTargetObjectFile::Initialize().
MCSection * TargetLoweringObjectFile::SectionForGlobal (const GlobalValue * GV, SectionKind Kind, Mangler & Mang, const TargetMachine & TM) const
This method computes the appropriate section to emit the specified global variable or function definition.
This should not be passed external (or available externally) globals.
Definition at line 262 of file TargetLoweringObjectFile.cpp.
References getExplicitSectionGlobal(), llvm::GlobalValue::hasSection(), and SelectSectionForGlobal().
Referenced by llvm::AsmPrinter::EmitGlobalVariable(), llvm::TargetMachine::getNameWithPrefix(), and SectionForGlobal().
MCSection* llvm::TargetLoweringObjectFile::SectionForGlobal (const GlobalValue * GV, Mangler & Mang, const TargetMachine & TM) const [inline]
This method computes the appropriate section to emit the specified global variable or function definition.
This should not be passed external (or available externally) globals.
Definition at line 97 of file TargetLoweringObjectFile.h.
References getKindForGlobal(), and SectionForGlobal().
virtual MCSection* llvm::TargetLoweringObjectFile::SelectSectionForGlobal (const GlobalValue * GV, SectionKind Kind, Mangler & Mang, const TargetMachine & TM) const [protected, pure virtual]
Implemented in llvm::TargetLoweringObjectFileCOFF, llvm::TargetLoweringObjectFileMachO, llvm::NVPTXTargetObjectFile, llvm::TargetLoweringObjectFileELF, llvm::HexagonTargetObjectFile, llvm::MipsTargetObjectFile, and llvm::XCoreTargetObjectFile.
Referenced by SectionForGlobal().
bool TargetLoweringObjectFile::shouldPutJumpTableInFunctionSection (bool UsesLabelDifference, const Function & F) const [virtual]
Reimplemented in llvm::TargetLoweringObjectFileELF.
Definition at line 279 of file TargetLoweringObjectFile.cpp.
References llvm::GlobalValue::isWeakForLinker().
Referenced by llvm::AsmPrinter::EmitJumpTableInfo().
bool llvm::TargetLoweringObjectFile::supportGOTPCRelWithOffset () const [inline]
Target GOT "PC"-relative relocation supports encoding an additional binary expression with an offset?
Definition at line 178 of file TargetLoweringObjectFile.h.
References SupportGOTPCRelWithOffset.
Referenced by handleIndirectSymViaGOTPCRel().
bool llvm::TargetLoweringObjectFile::supportIndirectSymViaGOTPCRel () const [inline]
Target supports replacing a data "PC"-relative access to a symbol through another symbol, by accessing the later via a GOT entry instead?
Definition at line 172 of file TargetLoweringObjectFile.h.
References SupportIndirectSymViaGOTPCRel.
Referenced by emitGlobalConstantImpl().
Member Data Documentation
const DataLayout* llvm::TargetLoweringObjectFile::DL [protected]
Definition at line 45 of file TargetLoweringObjectFile.h.
Referenced by llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), getSymbolWithGlobalValueBase(), and Initialize().
bool llvm::TargetLoweringObjectFile::SupportGOTPCRelWithOffset [protected]
Definition at line 47 of file TargetLoweringObjectFile.h.
Referenced by llvm::AArch64_MachoTargetObjectFile::AArch64_MachoTargetObjectFile(), and supportGOTPCRelWithOffset().
bool llvm::TargetLoweringObjectFile::SupportIndirectSymViaGOTPCRel [protected]
Definition at line 46 of file TargetLoweringObjectFile.h.
Referenced by supportIndirectSymViaGOTPCRel(), and llvm::TargetLoweringObjectFileMachO::TargetLoweringObjectFileMachO().
The documentation for this class was generated from the following files:
TargetLoweringObjectFile.h
TargetLoweringObjectFile.cpp