LLVM: llvm::RegisterPassParser< RegistryClass > Class Template Reference
llvm::RegisterPassParser< RegistryClass > Class Template Reference
RegisterPassParser class - Handle the addition of new machine passes.
#include <MachinePassRegistry.h>
Public Member Functions
RegisterPassParser (cl::Option &O)
~RegisterPassParser () override
void initialize ()
void NotifyAdd (const char *N, MachinePassCtor C, const char *D) override
void NotifyRemove (const char *N) override
Detailed Description
template<class RegistryClass>
class llvm::RegisterPassParser< RegistryClass >
RegisterPassParser class - Handle the addition of new machine passes.
Definition at line 122 of file MachinePassRegistry.h.
Constructor & Destructor Documentation
template<class RegistryClass > llvm::RegisterPassParser< RegistryClass >::RegisterPassParser (cl::Option & O) [inline]
Definition at line 125 of file MachinePassRegistry.h.
template<class RegistryClass > llvm::RegisterPassParser< RegistryClass >::~RegisterPassParser () [inline, override]
Definition at line 127 of file MachinePassRegistry.h.
Member Function Documentation
template<class RegistryClass > void llvm::RegisterPassParser< RegistryClass >::initialize () [inline]
Reimplemented from llvm::cl::generic_parser_base.
Definition at line 129 of file MachinePassRegistry.h.
References llvm::cl::parser< RegistryClass::FunctionPassCtor >::addLiteralOption().
template<class RegistryClass > void llvm::RegisterPassParser< RegistryClass >::NotifyAdd (const char * N, MachinePassCtor C, const char * D) [inline, override, virtual]
Implements llvm::MachinePassRegistryListener.
Definition at line 146 of file MachinePassRegistry.h.
References llvm::cl::parser< RegistryClass::FunctionPassCtor >::addLiteralOption().
template<class RegistryClass > void llvm::RegisterPassParser< RegistryClass >::NotifyRemove (const char * N) [inline, override, virtual]
Implements llvm::MachinePassRegistryListener.
Definition at line 149 of file MachinePassRegistry.h.
References llvm::cl::parser< RegistryClass::FunctionPassCtor >::removeLiteralOption().
The documentation for this class was generated from the following file:
MachinePassRegistry.h