LLVM: llvm::CCValAssign Class Reference
llvm::CCValAssign Class Reference
CCValAssign - Represent assignment of one arg/retval to a location.
#include <CallingConvLower.h>
Public Types
enum LocInfo {
Full, SExt, ZExt, AExt,
SExtUpper, ZExtUpper, AExtUpper, BCvt,
VExt, FPExt, Indirect
}
Public Member Functions
void convertToReg (unsigned RegNo)
void convertToMem (unsigned Offset)
unsigned getValNo () const
MVT getValVT () const
bool isRegLoc () const
bool isMemLoc () const
bool needsCustom () const
unsigned getLocReg () const
unsigned getLocMemOffset () const
unsigned getExtraInfo () const
MVT getLocVT () const
LocInfo getLocInfo () const
bool isExtInLoc () const
bool isUpperBitsInLoc () const
Static Public Member Functions
static CCValAssign getReg (unsigned ValNo, MVT ValVT, unsigned RegNo, MVT LocVT, LocInfo HTP)
static CCValAssign getCustomReg (unsigned ValNo, MVT ValVT, unsigned RegNo, MVT LocVT, LocInfo HTP)
static CCValAssign getMem (unsigned ValNo, MVT ValVT, unsigned Offset, MVT LocVT, LocInfo HTP)
static CCValAssign getCustomMem (unsigned ValNo, MVT ValVT, unsigned Offset, MVT LocVT, LocInfo HTP)
static CCValAssign getPending (unsigned ValNo, MVT ValVT, MVT LocVT, LocInfo HTP, unsigned ExtraInfo=0)
Detailed Description
CCValAssign - Represent assignment of one arg/retval to a location.
Definition at line 32 of file CallingConvLower.h.
Member Enumeration Documentation
enum llvm::CCValAssign::LocInfo
Enumerator:
Full
SExt
ZExt
AExt
SExtUpper
ZExtUpper
AExtUpper
BCvt
VExt
FPExt
Indirect
Definition at line 34 of file CallingConvLower.h.
Member Function Documentation
void llvm::CCValAssign::convertToMem (unsigned Offset) [inline]
Definition at line 135 of file CallingConvLower.h.
void llvm::CCValAssign::convertToReg (unsigned RegNo) [inline]
Definition at line 130 of file CallingConvLower.h.
static CCValAssign llvm::CCValAssign::getCustomMem (unsigned ValNo, MVT ValVT, unsigned Offset, MVT LocVT, LocInfo HTP) [inline, static]
Definition at line 114 of file CallingConvLower.h.
References getMem(), and llvm::MipsISD::Ret.
Referenced by CC_Sparc_Assign_f64(), CC_Sparc_Assign_SRet(), llvm::f64AssignAAPCS(), and llvm::f64AssignAPCS().
static CCValAssign llvm::CCValAssign::getCustomReg (unsigned ValNo, MVT ValVT, unsigned RegNo, MVT LocVT, LocInfo HTP) [inline, static]
Definition at line 91 of file CallingConvLower.h.
References getReg(), and llvm::MipsISD::Ret.
Referenced by CC_Sparc64_Half(), CC_Sparc_Assign_f64(), llvm::f64AssignAAPCS(), llvm::f64AssignAPCS(), llvm::f64RetAssign(), and fixupVariableFloatArgs().
unsigned llvm::CCValAssign::getExtraInfo () const [inline]
Definition at line 150 of file CallingConvLower.h.
LocInfo llvm::CCValAssign::getLocInfo () const [inline]
Definition at line 153 of file CallingConvLower.h.
Referenced by canUseSiblingCall(), convertLocVTToValVT(), convertValVTToLocVT(), fixupVariableFloatArgs(), llvm::HexagonTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::SparcTargetLowering::LowerReturn_64(), and UnpackFromArgumentSlot().
unsigned llvm::CCValAssign::getLocMemOffset () const [inline]
Definition at line 149 of file CallingConvLower.h.
References isMemLoc().
Referenced by llvm::HexagonTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), LowerCallResult(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), and llvm::SparcTargetLowering::LowerFormalArguments_64().
unsigned llvm::CCValAssign::getLocReg () const [inline]
Definition at line 148 of file CallingConvLower.h.
References isRegLoc().
Referenced by canUseSiblingCall(), fixupVariableFloatArgs(), llvm::HexagonTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), LowerCallResult(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::HexagonTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), and llvm::SparcTargetLowering::LowerReturn_64().
MVT llvm::CCValAssign::getLocVT () const [inline]
Definition at line 151 of file CallingConvLower.h.
Referenced by convertLocVTToValVT(), convertValVTToLocVT(), fixupVariableFloatArgs(), llvm::HexagonTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::HexagonTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), and UnpackFromArgumentSlot().
static CCValAssign llvm::CCValAssign::getMem (unsigned ValNo, MVT ValVT, unsigned Offset, MVT LocVT, LocInfo HTP) [inline, static]
Definition at line 100 of file CallingConvLower.h.
References llvm::MipsISD::Ret.
Referenced by allocateStack(), CC_Hexagon(), CC_Hexagon32(), CC_Hexagon64(), CC_Hexagon_VarArg(), CC_MipsO32(), CC_Sparc64_Full(), CC_Sparc64_Half(), fixupVariableFloatArgs(), getCustomMem(), llvm::CCState::HandleByVal(), RetCC_Hexagon32(), and RetCC_Hexagon64().
static CCValAssign llvm::CCValAssign::getPending (unsigned ValNo, MVT ValVT, MVT LocVT, LocInfo HTP, unsigned ExtraInfo = 0) [inline, static]
Definition at line 125 of file CallingConvLower.h.
References getReg().
Referenced by llvm::CC_ARM_AAPCS_Custom_Aggregate().
static CCValAssign llvm::CCValAssign::getReg (unsigned ValNo, MVT ValVT, unsigned RegNo, MVT LocVT, LocInfo HTP) [inline, static]
Definition at line 77 of file CallingConvLower.h.
References llvm::MipsISD::Ret.
Referenced by AnalyzeArguments(), CC_Hexagon32(), CC_Hexagon64(), CC_MipsO32(), CC_Sparc64_Full(), CC_Sparc64_Half(), fixupVariableFloatArgs(), getCustomReg(), getPending(), RetCC_Hexagon32(), and RetCC_Hexagon64().
unsigned llvm::CCValAssign::getValNo () const [inline]
Definition at line 140 of file CallingConvLower.h.
Referenced by fixupVariableFloatArgs().
MVT llvm::CCValAssign::getValVT () const [inline]
Definition at line 141 of file CallingConvLower.h.
Referenced by convertLocVTToValVT(), convertValVTToLocVT(), fixupVariableFloatArgs(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_64(), LowerCallResult(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::SparcTargetLowering::LowerReturn_64(), and UnpackFromArgumentSlot().
bool llvm::CCValAssign::isExtInLoc () const [inline]
Definition at line 154 of file CallingConvLower.h.
References AExt, SExt, and ZExt.
Referenced by convertLocVTToValVT(), llvm::SparcTargetLowering::LowerCall_64(), and llvm::SparcTargetLowering::LowerFormalArguments_64().
bool llvm::CCValAssign::isMemLoc () const [inline]
Definition at line 144 of file CallingConvLower.h.
Referenced by getLocMemOffset(), llvm::HexagonTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), LowerCallResult(), llvm::SITargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), and llvm::SparcTargetLowering::LowerFormalArguments_64().
bool llvm::CCValAssign::isRegLoc () const [inline]
Definition at line 143 of file CallingConvLower.h.
Referenced by canUseSiblingCall(), fixupVariableFloatArgs(), getLocReg(), llvm::CCState::getRemainingRegParmsForType(), llvm::HexagonTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), LowerCallResult(), llvm::SITargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::SystemZTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), and llvm::SparcTargetLowering::LowerReturn_64().
bool llvm::CCValAssign::isUpperBitsInLoc () const [inline]
Definition at line 158 of file CallingConvLower.h.
References AExtUpper, SExtUpper, and ZExtUpper.
bool llvm::CCValAssign::needsCustom () const [inline]
Definition at line 146 of file CallingConvLower.h.
Referenced by llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), and llvm::SparcTargetLowering::LowerReturn_64().
The documentation for this class was generated from the following file:
CallingConvLower.h