LLVM: llvm::TargetLoweringObjectFileELF Class Reference
llvm::TargetLoweringObjectFileELF Class Reference
#include <TargetLoweringObjectFileImpl.h>
Public Member Functions
TargetLoweringObjectFileELF ()
~TargetLoweringObjectFileELF () override
void emitPersonalityValue (MCStreamer &Streamer, const TargetMachine &TM, const MCSymbol *Sym) const override
MCSection * getSectionForConstant (SectionKind Kind, const Constant *C) const override
Given a constant with the SectionKind, return a section that it should be placed in.
MCSection * getExplicitSectionGlobal (const GlobalValue *GV, SectionKind Kind, Mangler &Mang, const TargetMachine &TM) const override
Targets should implement this method to assign a section to globals with an explicit section specfied.
MCSection * SelectSectionForGlobal (const GlobalValue *GV, SectionKind Kind, Mangler &Mang, const TargetMachine &TM) const override
MCSection * getSectionForJumpTable (const Function &F, Mangler &Mang, const TargetMachine &TM) const override
bool shouldPutJumpTableInFunctionSection (bool UsesLabelDifference, const Function &F) const override
const MCExpr * getTTypeGlobalReference (const GlobalValue *GV, unsigned Encoding, Mangler &Mang, const TargetMachine &TM, MachineModuleInfo *MMI, MCStreamer &Streamer) const override
Return an MCExpr to use for a reference to the specified type info global variable from exception handling information.
MCSymbol * getCFIPersonalitySymbol (const GlobalValue *GV, Mangler &Mang, const TargetMachine &TM, MachineModuleInfo *MMI) const override
void InitializeELF (bool UseInitArray_)
MCSection * getStaticCtorSection (unsigned Priority, const MCSymbol *KeySym) const override
MCSection * getStaticDtorSection (unsigned Priority, const MCSymbol *KeySym) const override
Detailed Description
Definition at line 35 of file TargetLoweringObjectFileImpl.h.
Constructor & Destructor Documentation
llvm::TargetLoweringObjectFileELF::TargetLoweringObjectFileELF () [inline]
Definition at line 40 of file TargetLoweringObjectFileImpl.h.
llvm::TargetLoweringObjectFileELF::~TargetLoweringObjectFileELF () [inline, override]
Definition at line 42 of file TargetLoweringObjectFileImpl.h.
Member Function Documentation
void TargetLoweringObjectFileELF::emitPersonalityValue (MCStreamer & Streamer, const TargetMachine & TM, const MCSymbol * Sym) const [override, virtual]
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 61 of file TargetLoweringObjectFileImpl.cpp.
References llvm::StringRef::begin(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::MCConstantExpr::create(), llvm::MCStreamer::emitELFSize(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitSymbolAttribute(), llvm::MCStreamer::EmitSymbolValue(), llvm::MCStreamer::EmitValueToAlignment(), llvm::StringRef::end(), llvm::TargetMachine::getDataLayout(), llvm::MCSymbol::getName(), llvm::DataLayout::getPointerABIAlignment(), llvm::DataLayout::getPointerSize(), llvm::SmallVectorImpl< T >::insert(), llvm::Label, llvm::MCSA_ELF_TypeObject, llvm::MCSA_Hidden, llvm::MCSA_Weak, llvm::cl::Prefix, llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_GROUP, llvm::ELF::SHF_WRITE, llvm::ELF::SHT_PROGBITS, and llvm::MCStreamer::SwitchSection().
MCSymbol * TargetLoweringObjectFileELF::getCFIPersonalitySymbol (const GlobalValue * GV, Mangler & Mang, const TargetMachine & TM, MachineModuleInfo * MMI) const [override, virtual]
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 49 of file TargetLoweringObjectFileImpl.cpp.
References llvm::dwarf::DW_EH_PE_absptr, llvm::dwarf::DW_EH_PE_indirect, llvm::MCSymbol::getName(), llvm::TargetMachine::getSymbol(), and llvm::report_fatal_error().
MCSection * TargetLoweringObjectFileELF::getExplicitSectionGlobal (const GlobalValue * GV, SectionKind Kind, Mangler & Mang, const TargetMachine & TM) const [override, virtual]
Targets should implement this method to assign a section to globals with an explicit section specfied.
The implementation of this method can assume that GV->hasSection() is true.
Implements llvm::TargetLoweringObjectFile.
Reimplemented in llvm::XCoreTargetObjectFile.
Definition at line 203 of file TargetLoweringObjectFileImpl.cpp.
References llvm::C, getELFComdat(), getELFKindForNamedSection(), getELFSectionFlags(), getELFSectionType(), llvm::GlobalValue::getSection(), and llvm::ELF::SHF_GROUP.
MCSection * TargetLoweringObjectFileELF::getSectionForConstant (SectionKind Kind, const Constant * C) const [override, virtual]
Given a constant with the SectionKind, return a section that it should be placed in.
Given a mergeable constant with the specified size and relocation information, return a section that it should be placed in.
Reimplemented from llvm::TargetLoweringObjectFile.
Reimplemented in llvm::MipsTargetObjectFile, and llvm::XCoreTargetObjectFile.
Definition at line 354 of file TargetLoweringObjectFileImpl.cpp.
References llvm::SectionKind::isMergeableConst16(), llvm::SectionKind::isMergeableConst4(), llvm::SectionKind::isMergeableConst8(), llvm::SectionKind::isReadOnly(), llvm::SectionKind::isReadOnlyWithRel(), and llvm::SectionKind::isReadOnlyWithRelLocal().
MCSection * TargetLoweringObjectFileELF::getSectionForJumpTable (const Function & F, Mangler & Mang, const TargetMachine & TM) const [override, virtual]
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 330 of file TargetLoweringObjectFileImpl.cpp.
References llvm::C, llvm::GlobalObject::getComdat(), llvm::TargetMachine::getFunctionSections(), llvm::SectionKind::getReadOnly(), selectELFSectionForGlobal(), and llvm::ELF::SHF_ALLOC.
MCSection * TargetLoweringObjectFileELF::getStaticCtorSection (unsigned Priority, const MCSymbol * KeySym) const [override, virtual]
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 410 of file TargetLoweringObjectFileImpl.cpp.
References getStaticStructorSection().
MCSection * TargetLoweringObjectFileELF::getStaticDtorSection (unsigned Priority, const MCSymbol * KeySym) const [override, virtual]
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 416 of file TargetLoweringObjectFileImpl.cpp.
References getStaticStructorSection().
const MCExpr * TargetLoweringObjectFileELF::getTTypeGlobalReference (const GlobalValue * GV, unsigned Encoding, Mangler & Mang, const TargetMachine & TM, MachineModuleInfo * MMI, MCStreamer & Streamer) const [override, virtual]
Return an MCExpr to use for a reference to the specified type info global variable from exception handling information.
Reimplemented from llvm::TargetLoweringObjectFile.
Reimplemented in llvm::ARMElfTargetObjectFile, and llvm::SparcELFTargetObjectFile.
Definition at line 86 of file TargetLoweringObjectFileImpl.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::dwarf::DW_EH_PE_indirect, llvm::MachineModuleInfoELF::getGVStubEntry(), llvm::MachineModuleInfo::getObjFileInfo(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer(), llvm::TargetMachine::getSymbol(), llvm::TargetLoweringObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFile::getTTypeReference(), and llvm::GlobalValue::hasLocalLinkage().
Referenced by llvm::ARMElfTargetObjectFile::getTTypeGlobalReference().
void TargetLoweringObjectFileELF::InitializeELF (bool UseInitArray_)
Definition at line 423 of file TargetLoweringObjectFileImpl.cpp.
References llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_WRITE, llvm::ELF::SHT_FINI_ARRAY, and llvm::ELF::SHT_INIT_ARRAY.
Referenced by llvm::MipsTargetObjectFile::Initialize(), and llvm::HexagonTargetObjectFile::Initialize().
MCSection * TargetLoweringObjectFileELF::SelectSectionForGlobal (const GlobalValue * GV, SectionKind Kind, Mangler & Mang, const TargetMachine & TM) const [override, virtual]
Implements llvm::TargetLoweringObjectFile.
Reimplemented in llvm::HexagonTargetObjectFile, llvm::MipsTargetObjectFile, and llvm::XCoreTargetObjectFile.
Definition at line 310 of file TargetLoweringObjectFileImpl.cpp.
References llvm::TargetMachine::getDataSections(), getELFSectionFlags(), llvm::TargetMachine::getFunctionSections(), llvm::GlobalValue::hasComdat(), llvm::SectionKind::isCommon(), llvm::SectionKind::isText(), selectELFSectionForGlobal(), and llvm::ELF::SHF_MERGE.
bool TargetLoweringObjectFileELF::shouldPutJumpTableInFunctionSection (bool UsesLabelDifference, const Function & F) const [override, virtual]
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 344 of file TargetLoweringObjectFileImpl.cpp.
The documentation for this class was generated from the following files:
TargetLoweringObjectFileImpl.h
TargetLoweringObjectFileImpl.cpp