LLVM: llvm::object::ExportEntry Class Reference
llvm::object::ExportEntry Class Reference
ExportEntry encapsulates the current-state-of-the-walk used when doing a non-recursive walk of the trie data structure.
#include <MachO.h>
Classes
struct NodeState
Public Member Functions
ExportEntry (ArrayRef< uint8_t > Trie)
StringRef name () const
uint64_t flags () const
uint64_t address () const
uint64_t other () const
StringRef otherName () const
uint32_t nodeOffset () const
bool operator== (const ExportEntry &) const
void moveNext ()
Friends
class MachOObjectFile
Detailed Description
ExportEntry encapsulates the current-state-of-the-walk used when doing a non-recursive walk of the trie data structure.
This allows you to iterate across all exported symbols using: for (const llvm::object::ExportEntry &AnExport : Obj->exports()) { }
Definition at line 57 of file Object/MachO.h.
Constructor & Destructor Documentation
ExportEntry::ExportEntry (ArrayRef< uint8_t > Trie)
Definition at line 1289 of file MachOObjectFile.cpp.
Member Function Documentation
uint64_t ExportEntry::address () const
Definition at line 1339 of file MachOObjectFile.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back().
uint64_t ExportEntry::flags () const
Definition at line 1335 of file MachOObjectFile.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back().
void ExportEntry::moveNext ()
Definition at line 1423 of file MachOObjectFile.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateBase< T, isPodLike >::pop_back(), and llvm::SmallVectorImpl< T >::resize().
StringRef ExportEntry::name () const
Definition at line 1331 of file MachOObjectFile.cpp.
uint32_t ExportEntry::nodeOffset () const
Definition at line 1354 of file MachOObjectFile.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), and llvm::ArrayRef< T >::begin().
bool ExportEntry::operator== (const ExportEntry & Other) const
Definition at line 1302 of file MachOObjectFile.cpp.
References llvm::SmallString< InternalLen >::equals(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
uint64_t ExportEntry::other () const
Definition at line 1343 of file MachOObjectFile.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back().
StringRef ExportEntry::otherName () const
Definition at line 1347 of file MachOObjectFile.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back().
Friends And Related Function Documentation
friend class MachOObjectFile [friend]
Definition at line 73 of file Object/MachO.h.
The documentation for this class was generated from the following files:
Object/MachO.h
MachOObjectFile.cpp