LLVM: llvm::IntRecTy Class Reference
llvm::IntRecTy Class Reference
IntRecTy - 'int' - Represent an integer value of no particular size.
#include <Record.h>
Public Member Functions
std::string getAsString () const override
bool typeIsConvertibleTo (const RecTy *RHS) const override
typeIsConvertibleTo - Return true if all values of 'this' type can be converted to the specified type.
Static Public Member Functions
static bool classof (const RecTy *RT)
static IntRecTy * get ()
Detailed Description
IntRecTy - 'int' - Represent an integer value of no particular size.
Definition at line 120 of file Record.h.
Member Function Documentation
static bool llvm::IntRecTy::classof (const RecTy * RT) [inline, static]
Definition at line 125 of file Record.h.
References llvm::RecTy::getRecTyKind(), and llvm::RecTy::IntRecTyKind.
static IntRecTy* llvm::IntRecTy::get () [inline, static]
Definition at line 129 of file Record.h.
Referenced by llvm::BinOpInit::Fold(), llvm::TernOpInit::Fold(), and llvm::TernOpInit::resolveReferences().
std::string llvm::IntRecTy::getAsString () const [inline, override, virtual]
Implements llvm::RecTy.
Definition at line 131 of file Record.h.
bool IntRecTy::typeIsConvertibleTo (const RecTy * RHS) const [override, virtual]
typeIsConvertibleTo - Return true if all values of 'this' type can be converted to the specified type.
Reimplemented from llvm::RecTy.
Definition at line 131 of file Record.cpp.
References llvm::RecTy::BitRecTyKind, llvm::RecTy::BitsRecTyKind, llvm::RecTy::getRecTyKind(), and llvm::RecTy::IntRecTyKind.
The documentation for this class was generated from the following files:
Record.h
Record.cpp