LLVM: llvm::BasicTTIImplBase< T > Class Template Reference
llvm::BasicTTIImplBase< T > Class Template Reference
Base class which can be used to help build a TTI implementation.
#include <BasicTTIImpl.h>
Public Member Functions
BasicTTIImplBase (const BasicTTIImplBase &Arg)
BasicTTIImplBase (BasicTTIImplBase &&Arg)
BasicTTIImplBase & operator= (const BasicTTIImplBase &RHS)
BasicTTIImplBase & operator= (BasicTTIImplBase &&RHS)
Scalar TTI Implementations
bool hasBranchDivergence ()
bool isSourceOfDivergence (const Value *V)
bool isLegalAddImmediate (int64_t imm)
bool isLegalICmpImmediate (int64_t imm)
bool isLegalAddressingMode (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace)
int getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace)
bool isTruncateFree (Type *Ty1, Type *Ty2)
bool isProfitableToHoist (Instruction *I)
bool isTypeLegal (Type *Ty)
unsigned getIntrinsicCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< const Value * > Arguments)
unsigned getIntrinsicCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< Type * > ParamTys)
unsigned getJumpBufAlignment ()
unsigned getJumpBufSize ()
bool shouldBuildLookupTables ()
bool haveFastSqrt (Type *Ty)
unsigned getFPOpCost (Type *Ty)
unsigned getOperationCost (unsigned Opcode, Type *Ty, Type *OpTy)
void getUnrollingPreferences (Loop *L, TTI::UnrollingPreferences &UP)
Vector TTI Implementations
unsigned getNumberOfRegisters (bool Vector)
unsigned getRegisterBitWidth (bool Vector)
unsigned getMaxInterleaveFactor (unsigned VF)
unsigned getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::OperandValueKind Opd1Info=TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info=TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo=TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo=TTI::OP_None)
unsigned getShuffleCost (TTI::ShuffleKind Kind, Type *Tp, int Index, Type *SubTp)
unsigned getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src)
unsigned getCFInstrCost (unsigned Opcode)
unsigned getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy)
unsigned getVectorInstrCost (unsigned Opcode, Type *Val, unsigned Index)
unsigned getMemoryOpCost (unsigned Opcode, Type *Src, unsigned Alignment, unsigned AddressSpace)
unsigned getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace)
unsigned getIntrinsicInstrCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< Type * > Tys)
unsigned getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type * > Tys)
Compute a cost of the given call instruction.
unsigned getNumberOfParts (Type *Tp)
unsigned getAddressComputationCost (Type *Ty, bool IsComplex)
unsigned getReductionCost (unsigned Opcode, Type *Ty, bool IsPairwise)
Protected Member Functions
BasicTTIImplBase (const TargetMachine *TM)
Detailed Description
template<typename T>
class llvm::BasicTTIImplBase< T >
Base class which can be used to help build a TTI implementation.
This class provides as much implementation of the TTI interface as is possible using the target independent parts of the code generator.
In order to subclass it, your class must implement a getST() method to return the subtarget, and a getTLI() method to return the target lowering. We need these methods implemented in the derived class so that this class doesn't have to duplicate storage for them.
Definition at line 40 of file BasicTTIImpl.h.
Constructor & Destructor Documentation
template<typename T> llvm::BasicTTIImplBase< T >::BasicTTIImplBase (const TargetMachine * TM) [inline, explicit, protected]
Definition at line 94 of file BasicTTIImpl.h.
template<typename T> llvm::BasicTTIImplBase< T >::BasicTTIImplBase (const BasicTTIImplBase< T > & Arg) [inline]
Definition at line 99 of file BasicTTIImpl.h.
template<typename T> llvm::BasicTTIImplBase< T >::BasicTTIImplBase (BasicTTIImplBase< T > && Arg) [inline]
Definition at line 101 of file BasicTTIImpl.h.
Member Function Documentation
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getAddressComputationCost (Type * Ty, bool IsComplex) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, and llvm::X86TTIImpl.
Definition at line 778 of file BasicTTIImpl.h.
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getArithmeticInstrCost (unsigned Opcode, Type * Ty, TTI::OperandValueKind Opd1Info = TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info = TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo = TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo = TTI::OP_None) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::PPCTTIImpl, llvm::X86TTIImpl, and llvm::NVPTXTTIImpl.
Definition at line 291 of file BasicTTIImpl.h.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getArithmeticInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicInstrCost(), and llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getReductionCost().
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getCallInstrCost (Function * F, Type * RetTy, ArrayRef< Type * > Tys) [inline]
Compute a cost of the given call instruction.
Compute the cost of calling function F with return type RetTy and argument types Tys. F might be nullptr, in this case the cost of an arbitrary call with the specified signature will be returned. This is used, for instance, when we estimate call of a vector counterpart of the given function.
Parameters:
F Called function, might be nullptr.
RetTy Return value types.
Tys Argument types.
Returns:
The cost of Call instruction.
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 769 of file BasicTTIImpl.h.
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getCastInstrCost (unsigned Opcode, Type * Dst, Type * Src) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::PPCTTIImpl, and llvm::X86TTIImpl.
Definition at line 348 of file BasicTTIImpl.h.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getCastInstrCost().
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getCFInstrCost (unsigned Opcode) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 442 of file BasicTTIImpl.h.
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getCmpSelInstrCost (unsigned Opcode, Type * ValTy, Type * CondTy) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::PPCTTIImpl, and llvm::X86TTIImpl.
Definition at line 447 of file BasicTTIImpl.h.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getCmpSelInstrCost().
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getFPOpCost (Type * Ty) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::ARMTTIImpl.
Definition at line 200 of file BasicTTIImpl.h.
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getInterleavedMemoryOpCost (unsigned Opcode, Type * VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 526 of file BasicTTIImpl.h.
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getIntrinsicCost (Intrinsic::ID IID, Type * RetTy, ArrayRef< const Value * > Arguments) [inline]
Reimplemented from llvm::TargetTransformInfoImplCRTPBase< T >.
Definition at line 161 of file BasicTTIImpl.h.
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getIntrinsicCost (Intrinsic::ID IID, Type * RetTy, ArrayRef< Type * > ParamTys) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 166 of file BasicTTIImpl.h.
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost (Intrinsic::ID IID, Type * RetTy, ArrayRef< Type * > Tys) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 593 of file BasicTTIImpl.h.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicInstrCost().
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getJumpBufAlignment () [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 183 of file BasicTTIImpl.h.
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getJumpBufSize () [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 185 of file BasicTTIImpl.h.
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getMaxInterleaveFactor (unsigned VF) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::PPCTTIImpl, llvm::X86TTIImpl, and llvm::AMDGPUTTIImpl.
Definition at line 289 of file BasicTTIImpl.h.
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getMemoryOpCost (unsigned Opcode, Type * Src, unsigned Alignment, unsigned AddressSpace) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::PPCTTIImpl, and llvm::X86TTIImpl.
Definition at line 493 of file BasicTTIImpl.h.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getInterleavedMemoryOpCost().
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getNumberOfParts (Type * Tp) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 773 of file BasicTTIImpl.h.
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getNumberOfRegisters (bool Vector) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::AArch64TTIImpl, llvm::PPCTTIImpl, llvm::ARMTTIImpl, llvm::X86TTIImpl, llvm::AMDGPUTTIImpl, llvm::SystemZTTIImpl, and llvm::XCoreTTIImpl.
Definition at line 285 of file BasicTTIImpl.h.
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getOperationCost (unsigned Opcode, Type * Ty, Type * OpTy) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 206 of file BasicTTIImpl.h.
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getReductionCost (unsigned Opcode, Type * Ty, bool IsPairwise) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::X86TTIImpl.
Definition at line 780 of file BasicTTIImpl.h.
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getRegisterBitWidth (bool Vector) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::PPCTTIImpl, llvm::X86TTIImpl, llvm::AMDGPUTTIImpl, and llvm::SystemZTTIImpl.
Definition at line 287 of file BasicTTIImpl.h.
template<typename T> int llvm::BasicTTIImplBase< T >::getScalingFactorCost (Type * Ty, GlobalValue * BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 138 of file BasicTTIImpl.h.
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getShuffleCost (TTI::ShuffleKind Kind, Type * Tp, int Index, Type * SubTp) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::ARMTTIImpl, llvm::PPCTTIImpl, and llvm::X86TTIImpl.
Definition at line 340 of file BasicTTIImpl.h.
template<typename T> void llvm::BasicTTIImplBase< T >::getUnrollingPreferences (Loop * L, TTI::UnrollingPreferences & UP) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::AArch64TTIImpl, llvm::PPCTTIImpl, and llvm::AMDGPUTTIImpl.
Definition at line 225 of file BasicTTIImpl.h.
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getVectorInstrCost (unsigned Opcode, Type * Val, unsigned Index) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::PPCTTIImpl, and llvm::X86TTIImpl.
Definition at line 486 of file BasicTTIImpl.h.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getInterleavedMemoryOpCost().
template<typename T> bool llvm::BasicTTIImplBase< T >::hasBranchDivergence () [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::AMDGPUTTIImpl, and llvm::NVPTXTTIImpl.
Definition at line 115 of file BasicTTIImpl.h.
template<typename T> bool llvm::BasicTTIImplBase< T >::haveFastSqrt (Type * Ty) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 193 of file BasicTTIImpl.h.
template<typename T> bool llvm::BasicTTIImplBase< T >::isLegalAddImmediate (int64_t imm) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 119 of file BasicTTIImpl.h.
template<typename T> bool llvm::BasicTTIImplBase< T >::isLegalAddressingMode (Type * Ty, GlobalValue * BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 127 of file BasicTTIImpl.h.
template<typename T> bool llvm::BasicTTIImplBase< T >::isLegalICmpImmediate (int64_t imm) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 123 of file BasicTTIImpl.h.
template<typename T> bool llvm::BasicTTIImplBase< T >::isProfitableToHoist (Instruction * I) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 152 of file BasicTTIImpl.h.
template<typename T> bool llvm::BasicTTIImplBase< T >::isSourceOfDivergence (const Value * V) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::NVPTXTTIImpl.
Definition at line 117 of file BasicTTIImpl.h.
template<typename T> bool llvm::BasicTTIImplBase< T >::isTruncateFree (Type * Ty1, Type * Ty2) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 148 of file BasicTTIImpl.h.
template<typename T> bool llvm::BasicTTIImplBase< T >::isTypeLegal (Type * Ty) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 156 of file BasicTTIImpl.h.
template<typename T> BasicTTIImplBase& llvm::BasicTTIImplBase< T >::operator= (const BasicTTIImplBase< T > & RHS) [inline]
Definition at line 103 of file BasicTTIImpl.h.
template<typename T> BasicTTIImplBase& llvm::BasicTTIImplBase< T >::operator= (BasicTTIImplBase< T > && RHS) [inline]
Definition at line 107 of file BasicTTIImpl.h.
template<typename T> bool llvm::BasicTTIImplBase< T >::shouldBuildLookupTables () [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 187 of file BasicTTIImpl.h.
The documentation for this class was generated from the following file:
BasicTTIImpl.h