LLVM: llvm::cl::basic_parser_impl Class Reference
llvm::cl::basic_parser_impl Class Reference
#include <CommandLine.h>
Public Member Functions
basic_parser_impl (Option &O)
enum ValueExpected getValueExpectedFlagDefault () const
void getExtraOptionNames (SmallVectorImpl< const char * > &)
void initialize ()
size_t getOptionWidth (const Option &O) const
void printOptionInfo (const Option &O, size_t GlobalWidth) const
void printOptionNoValue (const Option &O, size_t GlobalWidth) const
virtual const char * getValueName () const
virtual void anchor ()
Protected Member Functions
~basic_parser_impl ()
void printOptionName (const Option &O, size_t GlobalWidth) const
Detailed Description
Definition at line 716 of file CommandLine.h.
Constructor & Destructor Documentation
llvm::cl::basic_parser_impl::basic_parser_impl (Option & O) [inline]
Definition at line 718 of file CommandLine.h.
llvm::cl::basic_parser_impl::~basic_parser_impl () [protected]
Member Function Documentation
void basic_parser_impl::anchor () [virtual]
Reimplemented in llvm::cl::final< DataType >, llvm::cl::final< DataType >, llvm::cl::final< DataType >, llvm::cl::final< DataType >, llvm::cl::final< DataType >, llvm::cl::final< DataType >, llvm::cl::final< DataType >, llvm::cl::final< DataType >, and llvm::cl::final< DataType >.
Definition at line 72 of file CommandLine.cpp.
void llvm::cl::basic_parser_impl::getExtraOptionNames (SmallVectorImpl< const char * > &) [inline]
Definition at line 725 of file CommandLine.h.
size_t basic_parser_impl::getOptionWidth (const Option & O) const
Definition at line 1184 of file CommandLine.cpp.
References llvm::cl::Option::ArgStr, getValueName(), and getValueStr().
Referenced by printOptionInfo().
enum ValueExpected llvm::cl::basic_parser_impl::getValueExpectedFlagDefault () const [inline]
Reimplemented in llvm::cl::final< DataType >, and llvm::cl::final< DataType >.
Definition at line 721 of file CommandLine.h.
References llvm::cl::ValueRequired.
virtual const char* llvm::cl::basic_parser_impl::getValueName () const [inline, virtual]
Reimplemented in llvm::cl::final< DataType >, llvm::cl::final< DataType >, llvm::cl::final< DataType >, llvm::cl::final< DataType >, llvm::cl::final< DataType >, llvm::cl::final< DataType >, llvm::cl::final< DataType >, llvm::cl::final< DataType >, and llvm::cl::final< DataType >.
Definition at line 742 of file CommandLine.h.
Referenced by getOptionWidth(), and printOptionInfo().
void llvm::cl::basic_parser_impl::initialize () [inline]
Reimplemented in llvm::cl::final< DataType >.
Definition at line 727 of file CommandLine.h.
void basic_parser_impl::printOptionInfo (const Option & O, size_t GlobalWidth) const
Definition at line 1195 of file CommandLine.cpp.
References llvm::cl::Option::ArgStr, getOptionWidth(), getValueName(), getValueStr(), llvm::cl::Option::HelpStr, llvm::outs(), and printHelpStr().
void basic_parser_impl::printOptionName (const Option & O, size_t GlobalWidth) const [protected]
Definition at line 1205 of file CommandLine.cpp.
References llvm::cl::Option::ArgStr, llvm::raw_ostream::indent(), and llvm::outs().
Referenced by printOptionNoValue().
void basic_parser_impl::printOptionNoValue (const Option & O, size_t GlobalWidth) const
Definition at line 1437 of file CommandLine.cpp.
References llvm::outs(), and printOptionName().
The documentation for this class was generated from the following files:
CommandLine.h
CommandLine.cpp