LLVM: llvm::DwarfCompileUnit Class Reference
llvm::DwarfCompileUnit Class Reference
#include <DwarfCompileUnit.h>
Public Member Functions
DwarfCompileUnit (unsigned UID, const DICompileUnit *Node, AsmPrinter *A, DwarfDebug *DW, DwarfFile *DWU)
DwarfCompileUnit * getSkeleton () const
void initStmtList ()
void applyStmtList (DIE &D)
Apply the DW_AT_stmt_list from this compile unit to the specified DIE.
DIE * getOrCreateGlobalVariableDIE (const DIGlobalVariable *GV)
getOrCreateGlobalVariableDIE - get or create global variable DIE.
void addLabelAddress (DIE &Die, dwarf::Attribute Attribute, const MCSymbol *Label)
addLabelAddress - Add a dwarf label attribute data and value using either DW_FORM_addr or DW_FORM_GNU_addr_index.
void addLocalLabelAddress (DIE &Die, dwarf::Attribute Attribute, const MCSymbol *Label)
addLocalLabelAddress - Add a dwarf label attribute data and value using DW_FORM_addr only.
void addSectionDelta (DIE &Die, dwarf::Attribute Attribute, const MCSymbol *Hi, const MCSymbol *Lo)
addSectionDelta - Add a label delta attribute data and value.
DwarfCompileUnit & getCU () override
unsigned getOrCreateSourceID (StringRef FileName, StringRef DirName) override
Look up the source ID with the given directory and source file names.
void addRange (RangeSpan Range)
addRange - Add an address range to the list of ranges for this unit.
void attachLowHighPC (DIE &D, const MCSymbol *Begin, const MCSymbol *End)
void addSectionLabel (DIE &Die, dwarf::Attribute Attribute, const MCSymbol *Label, const MCSymbol *Sec)
addSectionLabel - Add a Dwarf section label attribute data and value.
DIE & updateSubprogramScopeDIE (const DISubprogram *SP)
Find DIE for the given subprogram and attach appropriate DW_AT_low_pc and DW_AT_high_pc attributes.
void constructScopeDIE (LexicalScope *Scope, SmallVectorImpl< std::unique_ptr< DIE >> &FinalChildren)
void addScopeRangeList (DIE &ScopeDIE, SmallVector< RangeSpan, 2 > Range)
A helper function to construct a RangeSpanList for a given lexical scope.
void attachRangesOrLowHighPC (DIE &D, SmallVector< RangeSpan, 2 > Ranges)
void attachRangesOrLowHighPC (DIE &D, const SmallVectorImpl< InsnRange > &Ranges)
std::unique_ptr< DIE > constructInlinedScopeDIE (LexicalScope *Scope)
This scope represents inlined body of a function.
std::unique_ptr< DIE > constructLexicalScopeDIE (LexicalScope *Scope)
Construct new DW_TAG_lexical_block for this scope and attach DW_AT_low_pc/DW_AT_high_pc labels.
std::unique_ptr< DIE > constructVariableDIE (DbgVariable &DV, bool Abstract=false)
constructVariableDIE - Construct a DIE for the given DbgVariable.
std::unique_ptr< DIE > constructVariableDIE (DbgVariable &DV, const LexicalScope &Scope, DIE *&ObjectPointer)
DIE * createScopeChildrenDIE (LexicalScope *Scope, SmallVectorImpl< std::unique_ptr< DIE >> &Children, unsigned *ChildScopeCount=nullptr)
A helper function to create children of a Scope DIE.
void constructSubprogramScopeDIE (LexicalScope *Scope)
Construct a DIE for this subprogram scope.
DIE * createAndAddScopeChildren (LexicalScope *Scope, DIE &ScopeDIE)
void constructAbstractSubprogramScopeDIE (LexicalScope *Scope)
std::unique_ptr< DIE > constructImportedEntityDIE (const DIImportedEntity *Module)
Construct import_module DIE.
void finishSubprogramDefinition (const DISubprogram *SP)
void collectDeadVariables (const DISubprogram *SP)
void setSkeleton (DwarfCompileUnit &Skel)
Set the skeleton unit associated with this unit.
const MCSymbol * getSectionSym () const
unsigned getLength ()
void emitHeader (bool UseOffsets) override
Emit the header for this unit, not including the initial length field.
MCSymbol * getLabelBegin () const
void addGlobalName (StringRef Name, DIE &Die, const DIScope *Context) override
Add a new global name to the compile unit.
void addGlobalType (const DIType *Ty, const DIE &Die, const DIScope *Context) override
Add a new global type to the compile unit.
const StringMap< const DIE * > & getGlobalNames () const
const StringMap< const DIE * > & getGlobalTypes () const
void addVariableAddress (const DbgVariable &DV, DIE &Die, MachineLocation Location)
Add DW_AT_location attribute for a DbgVariable based on provided MachineLocation.
void addAddress (DIE &Die, dwarf::Attribute Attribute, const MachineLocation &Location)
Add an address attribute to a die based on the location provided.
void addComplexAddress (const DbgVariable &DV, DIE &Die, dwarf::Attribute Attribute, const MachineLocation &Location)
Start with the address based on the location provided, and generate the DWARF information necessary to find the actual variable (navigating the extra location information encoded in the type) based on the starting location.
void addLocationList (DIE &Die, dwarf::Attribute Attribute, unsigned Index)
Add a Dwarf loclistptr attribute data and value.
void applyVariableAttributes (const DbgVariable &Var, DIE &VariableDie)
void addExpr (DIELoc &Die, dwarf::Form Form, const MCExpr *Expr)
Add a Dwarf expression attribute data and value.
void applySubprogramAttributesToDefinition (const DISubprogram *SP, DIE &SPDie)
const SmallVectorImpl
< RangeSpanList > & getRangeLists () const
getRangeLists - Get the vector of range lists.
const SmallVectorImpl
< RangeSpan > & getRanges () const
getRanges - Get the list of ranges for this unit.
SmallVector< RangeSpan, 2 > takeRanges ()
void setBaseAddress (const MCSymbol *Base)
const MCSymbol * getBaseAddress () const
Detailed Description
Definition at line 31 of file DwarfCompileUnit.h.
Constructor & Destructor Documentation
llvm::DwarfCompileUnit::DwarfCompileUnit (unsigned UID, const DICompileUnit * Node, AsmPrinter * A, DwarfDebug * DW, DwarfFile * DWU)
Definition at line 19 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::getUnitDie(), and llvm::DwarfUnit::insertDIE().
Member Function Documentation
void llvm::DwarfCompileUnit::addAddress (DIE & Die, dwarf::Attribute Attribute, const MachineLocation & Location)
Add an address attribute to a die based on the location provided.
Definition at line 737 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addBlock(), llvm::DwarfUnit::addRegisterOffset(), llvm::DwarfUnit::addRegisterOpPiece(), llvm::DwarfUnit::DIEValueAllocator, llvm::MachineLocation::getOffset(), llvm::MachineLocation::getReg(), and llvm::MachineLocation::isReg().
Referenced by addVariableAddress(), and updateSubprogramScopeDIE().
void llvm::DwarfCompileUnit::addComplexAddress (const DbgVariable & DV, DIE & Die, dwarf::Attribute Attribute, const MachineLocation & Location)
Start with the address based on the location provided, and generate the DWARF information necessary to find the actual variable (navigating the extra location information encoded in the type) based on the starting location.
Start with the address based on the location provided, and generate the DWARF information necessary to find the actual variable given the extra address information encoded in the DbgVariable, starting from the starting location.
Add the DWARF information to the die.
Definition at line 758 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addBlock(), llvm::DwarfExpression::AddExpression(), llvm::DwarfExpression::AddMachineRegExpression(), llvm::DwarfExpression::AddMachineRegIndirect(), llvm::DwarfUnit::Asm, llvm::DwarfUnit::DIEValueAllocator, llvm::DbgVariable::getExpression(), llvm::MachineLocation::getOffset(), and llvm::MachineLocation::getReg().
Referenced by addVariableAddress().
void llvm::DwarfCompileUnit::addExpr (DIELoc & Die, dwarf::Form Form, const MCExpr * Expr)
Add a Dwarf expression attribute data and value.
Definition at line 799 of file DwarfCompileUnit.cpp.
Referenced by getOrCreateGlobalVariableDIE().
void llvm::DwarfCompileUnit::addGlobalName (StringRef Name, DIE & Die, const DIScope * Context) [override, virtual]
Add a new global name to the compile unit.
addGlobalName - Add a new global name to the compile unit.
Reimplemented from llvm::DwarfUnit.
Definition at line 707 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::getParentContextString(), and llvm::StringRef::str().
Referenced by applySubprogramAttributesToDefinition(), and getOrCreateGlobalVariableDIE().
void llvm::DwarfCompileUnit::addGlobalType (const DIType * Ty, const DIE & Die, const DIScope * Context) [override, virtual]
Add a new global type to the compile unit.
Add a new global type to the unit.
Reimplemented from llvm::DwarfUnit.
Definition at line 716 of file DwarfCompileUnit.cpp.
References llvm::DIType::getName(), llvm::DwarfUnit::getParentContextString(), and llvm::StringRef::str().
void llvm::DwarfCompileUnit::addLabelAddress (DIE & Die, dwarf::Attribute Attribute, const MCSymbol * Label)
addLabelAddress - Add a dwarf label attribute data and value using either DW_FORM_addr or DW_FORM_GNU_addr_index.
addLabelAddress - Add a dwarf label attribute data and value using DW_FORM_addr or DW_FORM_GNU_addr_index.
Definition at line 30 of file DwarfCompileUnit.cpp.
References llvm::DwarfDebug::addArangeLabel(), addLocalLabelAddress(), llvm::DwarfUnit::DD, llvm::dwarf::DW_FORM_GNU_addr_index, llvm::DwarfDebug::getAddressPool(), llvm::AddressPool::getIndex(), and llvm::DwarfDebug::useSplitDwarf().
Referenced by attachLowHighPC().
void llvm::DwarfCompileUnit::addLocalLabelAddress (DIE & Die, dwarf::Attribute Attribute, const MCSymbol * Label)
addLocalLabelAddress - Add a dwarf label attribute data and value using DW_FORM_addr only.
Definition at line 48 of file DwarfCompileUnit.cpp.
References llvm::DwarfDebug::addArangeLabel(), llvm::DwarfUnit::DD, and llvm::dwarf::DW_FORM_addr.
Referenced by addLabelAddress().
void llvm::DwarfCompileUnit::addLocationList (DIE & Die, dwarf::Attribute Attribute, unsigned Index)
Add a Dwarf loclistptr attribute data and value.
Definition at line 780 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::DD, llvm::dwarf::DW_FORM_data4, llvm::dwarf::DW_FORM_sec_offset, and llvm::DwarfDebug::getDwarfVersion().
void llvm::DwarfCompileUnit::addRange (RangeSpan Range)
addRange - Add an address range to the list of ranges for this unit.
Definition at line 211 of file DwarfCompileUnit.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::DwarfUnit::DD, llvm::SmallVectorBase::empty(), llvm::RangeSpan::getEnd(), llvm::DwarfDebug::getPrevCU(), llvm::MCSymbol::getSection(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::RangeSpan::setEnd(), and llvm::DwarfDebug::setPrevCU().
void llvm::DwarfCompileUnit::addScopeRangeList (DIE & ScopeDIE, SmallVector< RangeSpan, 2 > Range)
A helper function to construct a RangeSpanList for a given lexical scope.
Definition at line 371 of file DwarfCompileUnit.cpp.
References addSectionDelta(), addSectionLabel(), llvm::DwarfUnit::Asm, llvm::AsmPrinter::createTempSymbol(), llvm::dwarf::DW_AT_ranges, llvm::MCSection::getBeginSymbol(), llvm::MCObjectFileInfo::getDwarfRangesSection(), llvm::AsmPrinter::getObjFileLowering(), llvm::tgtok::List, and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by attachRangesOrLowHighPC().
void llvm::DwarfCompileUnit::addSectionDelta (DIE & Die, dwarf::Attribute Attribute, const MCSymbol * Hi, const MCSymbol * Lo)
addSectionDelta - Add a label delta attribute data and value.
Definition at line 364 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::DD, llvm::DwarfUnit::DIEValueAllocator, llvm::dwarf::DW_FORM_data4, llvm::dwarf::DW_FORM_sec_offset, and llvm::DwarfDebug::getDwarfVersion().
Referenced by addScopeRangeList(), and addSectionLabel().
void llvm::DwarfCompileUnit::addSectionLabel (DIE & Die, dwarf::Attribute Attribute, const MCSymbol * Label, const MCSymbol * Sec)
addSectionLabel - Add a Dwarf section label attribute data and value.
Definition at line 228 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addLabel(), addSectionDelta(), llvm::DwarfUnit::Asm, llvm::DwarfUnit::DD, llvm::MCAsmInfo::doesDwarfUseRelocationsAcrossSections(), llvm::dwarf::DW_FORM_data4, llvm::dwarf::DW_FORM_sec_offset, llvm::DwarfDebug::getDwarfVersion(), llvm::Label, and llvm::AsmPrinter::MAI.
Referenced by addScopeRangeList(), and initStmtList().
void llvm::DwarfCompileUnit::addVariableAddress (const DbgVariable & DV, DIE & Die, MachineLocation Location)
Add DW_AT_location attribute for a DbgVariable based on provided MachineLocation.
addVariableAddress - Add DW_AT_location attribute for a DbgVariable based on provided MachineLocation.
Definition at line 726 of file DwarfCompileUnit.cpp.
References addAddress(), llvm::DwarfUnit::addBlockByrefAddress(), addComplexAddress(), llvm::dwarf::DW_AT_location, llvm::DbgVariable::hasComplexAddress(), and llvm::DbgVariable::isBlockByrefVariable().
void llvm::DwarfCompileUnit::applyStmtList (DIE & D)
Apply the DW_AT_stmt_list from this compile unit to the specified DIE.
Definition at line 257 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::UnitDie.
Referenced by llvm::DwarfDebug::addDwarfTypeUnitType().
void llvm::DwarfCompileUnit::applySubprogramAttributesToDefinition (const DISubprogram * SP, DIE & SPDie)
Definition at line 804 of file DwarfCompileUnit.cpp.
References addGlobalName(), llvm::DwarfUnit::applySubprogramAttributes(), llvm::DIScope::getName(), llvm::DIScope::getScope(), and llvm::DwarfUnit::resolve().
Referenced by constructAbstractSubprogramScopeDIE(), and finishSubprogramDefinition().
void llvm::DwarfCompileUnit::applyVariableAttributes (const DbgVariable & Var, DIE & VariableDie)
Definition at line 787 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addFlag(), llvm::DwarfUnit::addSourceLine(), llvm::DwarfUnit::addString(), llvm::DwarfUnit::addType(), llvm::dwarf::DW_AT_artificial, llvm::dwarf::DW_AT_name, llvm::StringRef::empty(), llvm::DbgVariable::getName(), llvm::DbgVariable::getType(), llvm::DbgVariable::getVariable(), and llvm::DbgVariable::isArtificial().
Referenced by collectDeadVariables().
void llvm::DwarfCompileUnit::attachLowHighPC (DIE & D, const MCSymbol * Begin, const MCSymbol * End)
Definition at line 261 of file DwarfCompileUnit.cpp.
References addLabelAddress(), llvm::DwarfUnit::addLabelDelta(), llvm::DwarfUnit::DD, llvm::dwarf::DW_AT_high_pc, llvm::dwarf::DW_AT_low_pc, llvm::DwarfDebug::getDwarfVersion(), and llvm::MCSymbol::isDefined().
Referenced by attachRangesOrLowHighPC(), and updateSubprogramScopeDIE().
void llvm::DwarfCompileUnit::attachRangesOrLowHighPC (DIE & D, SmallVector< RangeSpan, 2 > Ranges)
Definition at line 395 of file DwarfCompileUnit.cpp.
References addScopeRangeList(), attachLowHighPC(), llvm::SmallVectorTemplateCommon< T, typename >::front(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by attachRangesOrLowHighPC(), constructInlinedScopeDIE(), and constructLexicalScopeDIE().
void llvm::DwarfCompileUnit::attachRangesOrLowHighPC (DIE & D, const SmallVectorImpl< InsnRange > & Ranges)
Definition at line 404 of file DwarfCompileUnit.cpp.
References attachRangesOrLowHighPC(), llvm::DwarfUnit::DD, llvm::DwarfDebug::getLabelAfterInsn(), llvm::DwarfDebug::getLabelBeforeInsn(), llvm::tgtok::List, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorImpl< T >::reserve(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
void llvm::DwarfCompileUnit::collectDeadVariables (const DISubprogram * SP)
Definition at line 676 of file DwarfCompileUnit.cpp.
References applyVariableAttributes(), constructVariableDIE(), llvm::DwarfUnit::DD, llvm::DwarfUnit::DU, llvm::DwarfFile::getAbstractSPDies(), llvm::DwarfUnit::getDIE(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup().
void llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE (LexicalScope * Scope)
Definition at line 600 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addDIEEntry(), llvm::DwarfUnit::addUInt(), applySubprogramAttributesToDefinition(), llvm::DwarfUnit::createAndAddDIE(), createAndAddScopeChildren(), llvm::DwarfUnit::DU, llvm::dwarf::DW_AT_inline, llvm::dwarf::DW_AT_object_pointer, llvm::dwarf::DW_INL_inlined, llvm::DwarfFile::getAbstractSPDies(), llvm::DwarfUnit::getOrCreateContextDIE(), llvm::DwarfUnit::getOrCreateSubprogramDIE(), llvm::LexicalScope::getScopeNode(), llvm::DwarfUnit::getUnitDie(), llvm::None, llvm::DwarfUnit::resolve(), and llvm::SP.
std::unique_ptr< DIE > llvm::DwarfCompileUnit::constructImportedEntityDIE (const DIImportedEntity * Module)
Construct import_module DIE.
Definition at line 633 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addDIEEntry(), llvm::DwarfUnit::addSourceLine(), llvm::DwarfUnit::addString(), llvm::dwarf::DW_AT_import, llvm::dwarf::DW_AT_name, llvm::StringRef::empty(), llvm::MDNode::get(), llvm::DwarfUnit::getDIE(), llvm::DIScope::getDirectory(), llvm::DIImportedEntity::getEntity(), llvm::DIScope::getFilename(), llvm::DIImportedEntity::getLine(), llvm::DIImportedEntity::getName(), getOrCreateGlobalVariableDIE(), llvm::DwarfUnit::getOrCreateNameSpace(), llvm::DwarfUnit::getOrCreateSubprogramDIE(), llvm::DwarfUnit::getOrCreateTypeDIE(), llvm::DIImportedEntity::getScope(), llvm::DINode::getTag(), llvm::DwarfUnit::insertDIE(), llvm::DwarfUnit::resolve(), and llvm::SP.
Referenced by constructScopeDIE().
std::unique_ptr< DIE > llvm::DwarfCompileUnit::constructInlinedScopeDIE (LexicalScope * Scope)
This scope represents inlined body of a function.
Construct DIE to represent this concrete inlined copy of the function.
Definition at line 417 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addDIEEntry(), llvm::DwarfDebug::addSubprogramNames(), llvm::DwarfUnit::addUInt(), attachRangesOrLowHighPC(), llvm::DwarfUnit::DD, llvm::DS, llvm::DwarfUnit::DU, llvm::dwarf::DW_AT_abstract_origin, llvm::dwarf::DW_AT_call_file, llvm::dwarf::DW_AT_call_line, llvm::DwarfFile::getAbstractSPDies(), llvm::getDISubprogram(), llvm::LexicalScope::getInlinedAt(), getOrCreateSourceID(), llvm::LexicalScope::getRanges(), llvm::LexicalScope::getScopeNode(), and llvm::None.
Referenced by constructScopeDIE().
std::unique_ptr< DIE > llvm::DwarfCompileUnit::constructLexicalScopeDIE (LexicalScope * Scope)
Construct new DW_TAG_lexical_block for this scope and attach DW_AT_low_pc/DW_AT_high_pc labels.
Definition at line 447 of file DwarfCompileUnit.cpp.
References attachRangesOrLowHighPC(), llvm::DwarfUnit::DD, llvm::LexicalScope::getRanges(), llvm::LexicalScope::isAbstractScope(), and llvm::DwarfDebug::isLexicalScopeDIENull().
Referenced by constructScopeDIE().
void llvm::DwarfCompileUnit::constructScopeDIE (LexicalScope * Scope, SmallVectorImpl< std::unique_ptr< DIE >> & FinalChildren)
Definition at line 302 of file DwarfCompileUnit.cpp.
References constructImportedEntityDIE(), constructInlinedScopeDIE(), constructLexicalScopeDIE(), createScopeChildrenDIE(), llvm::DwarfUnit::DD, llvm::DS, llvm::DwarfDebug::findImportedEntitiesForScope(), llvm::LexicalScope::getInlinedAt(), llvm::LexicalScope::getParent(), llvm::LexicalScope::getScopeNode(), I, and llvm::DwarfDebug::isLexicalScopeDIENull().
Referenced by createScopeChildrenDIE().
void llvm::DwarfCompileUnit::constructSubprogramScopeDIE (LexicalScope * Scope)
Construct a DIE for this subprogram scope.
Definition at line 559 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addDIEEntry(), createAndAddScopeChildren(), llvm::DwarfUnit::DD, llvm::dwarf::DW_AT_object_pointer, llvm::LexicalScope::getInlinedAt(), llvm::DwarfDebug::getProcessedSPNodes(), llvm::LexicalScope::getScopeNode(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::LexicalScope::isAbstractScope(), llvm::DITypeRefArray::size(), and updateSubprogramScopeDIE().
std::unique_ptr< DIE > llvm::DwarfCompileUnit::constructVariableDIE (DbgVariable & DV, bool Abstract = false)
constructVariableDIE - Construct a DIE for the given DbgVariable.
Definition at line 461 of file DwarfCompileUnit.cpp.
References llvm::DbgVariable::setDIE().
Referenced by collectDeadVariables(), constructVariableDIE(), and createScopeChildrenDIE().
std::unique_ptr< DIE > llvm::DwarfCompileUnit::constructVariableDIE (DbgVariable & DV, const LexicalScope & Scope, DIE *& ObjectPointer)
Definition at line 532 of file DwarfCompileUnit.cpp.
References constructVariableDIE(), llvm::LexicalScope::isAbstractScope(), and llvm::DbgVariable::isObjectPointer().
DIE * llvm::DwarfCompileUnit::createAndAddScopeChildren (LexicalScope * Scope, DIE & ScopeDIE)
Definition at line 586 of file DwarfCompileUnit.cpp.
References createScopeChildrenDIE(), and I.
Referenced by constructAbstractSubprogramScopeDIE(), and constructSubprogramScopeDIE().
DIE * llvm::DwarfCompileUnit::createScopeChildrenDIE (LexicalScope * Scope, SmallVectorImpl< std::unique_ptr< DIE >> & Children, unsigned * ChildScopeCount = nullptr)
A helper function to create children of a Scope DIE.
Definition at line 540 of file DwarfCompileUnit.cpp.
References constructScopeDIE(), constructVariableDIE(), llvm::DwarfUnit::DU, llvm::LexicalScope::getChildren(), llvm::DwarfFile::getScopeVariables(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), and llvm::AArch64CC::LS.
Referenced by constructScopeDIE(), and createAndAddScopeChildren().
void llvm::DwarfCompileUnit::emitHeader (bool UseOffsets) [override, virtual]
Emit the header for this unit, not including the initial length field.
Reimplemented from llvm::DwarfUnit.
Definition at line 696 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::Asm, llvm::AsmPrinter::createTempSymbol(), and llvm::AsmPrinter::OutStreamer.
void llvm::DwarfCompileUnit::finishSubprogramDefinition (const DISubprogram * SP)
Definition at line 659 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addDIEEntry(), applySubprogramAttributesToDefinition(), llvm::DwarfUnit::DU, llvm::dwarf::DW_AT_abstract_origin, llvm::DwarfFile::getAbstractSPDies(), llvm::DwarfUnit::getDIE(), llvm::DwarfUnit::getOrCreateSubprogramDIE(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup().
const MCSymbol* llvm::DwarfCompileUnit::getBaseAddress () const [inline]
Definition at line 231 of file DwarfCompileUnit.h.
DwarfCompileUnit& llvm::DwarfCompileUnit::getCU () [inline, override, virtual]
Implements llvm::DwarfUnit.
Definition at line 98 of file DwarfCompileUnit.h.
const StringMap<const DIE *>& llvm::DwarfCompileUnit::getGlobalNames () const [inline]
Definition at line 192 of file DwarfCompileUnit.h.
const StringMap<const DIE *>& llvm::DwarfCompileUnit::getGlobalTypes () const [inline]
Definition at line 193 of file DwarfCompileUnit.h.
MCSymbol* llvm::DwarfCompileUnit::getLabelBegin () const [inline]
Definition at line 180 of file DwarfCompileUnit.h.
References llvm::DwarfUnit::Section.
unsigned llvm::DwarfCompileUnit::getLength () [inline]
Definition at line 173 of file DwarfCompileUnit.h.
References llvm::DwarfUnit::getHeaderSize(), and llvm::DwarfUnit::UnitDie.
DIE * llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE (const DIGlobalVariable * GV)
getOrCreateGlobalVariableDIE - get or create global variable DIE.
Definition at line 100 of file DwarfCompileUnit.cpp.
References llvm::DwarfDebug::addAccelName(), llvm::DwarfDebug::addArangeLabel(), llvm::DwarfUnit::addBlock(), llvm::DwarfUnit::addConstantValue(), llvm::DwarfUnit::addDIEEntry(), addExpr(), llvm::DwarfUnit::addFlag(), addGlobalName(), llvm::DwarfUnit::addLinkageName(), llvm::DwarfUnit::addOpAddress(), llvm::DwarfUnit::addSourceLine(), llvm::DwarfUnit::addString(), llvm::DwarfUnit::addType(), llvm::DwarfUnit::addUInt(), llvm::DwarfUnit::Asm, llvm::WinEH::CE, llvm::DwarfUnit::createAndAddDIE(), llvm::DwarfUnit::DD, llvm::DwarfUnit::DIEValueAllocator, llvm::dwarf::DW_AT_declaration, llvm::dwarf::DW_AT_external, llvm::dwarf::DW_AT_location, llvm::dwarf::DW_AT_name, llvm::dwarf::DW_AT_specification, llvm::dwarf::DW_FORM_data1, llvm::dwarf::DW_FORM_udata, llvm::DwarfDebug::getAddressPool(), llvm::AsmPrinter::getDataLayout(), llvm::TargetLoweringObjectFile::getDebugThreadLocalSymbol(), llvm::DwarfUnit::getDIE(), llvm::DIGlobalVariable::getDisplayName(), llvm::AddressPool::getIndex(), llvm::DataLayout::getIndexedOffset(), llvm::DIGlobalVariable::getLinkageName(), llvm::getMergedGlobalExpr(), llvm::DIVariable::getName(), llvm::AsmPrinter::getObjFileLowering(), llvm::DwarfUnit::getOrCreateContextDIE(), llvm::DwarfUnit::getOrCreateStaticMemberDIE(), llvm::DataLayout::getPointerSize(), llvm::DIVariable::getScope(), llvm::DIGlobalVariable::getStaticDataMemberDeclaration(), llvm::AsmPrinter::getSymbol(), llvm::DINode::getTag(), llvm::Value::getType(), llvm::DIVariable::getType(), llvm::DIGlobalVariable::getVariable(), llvm::Global, llvm::DIGlobalVariable::isDefinition(), llvm::DIGlobalVariable::isLocalToUnit(), llvm::DwarfUnit::resolve(), llvm::DwarfDebug::resolve(), llvm::DwarfDebug::useGNUTLSOpcode(), and llvm::DwarfDebug::useSplitDwarf().
Referenced by constructImportedEntityDIE().
unsigned llvm::DwarfCompileUnit::getOrCreateSourceID (StringRef File, StringRef Directory) [override, virtual]
Look up the source ID with the given directory and source file names.
If none currently exists, create a new ID and insert it in the line table.
Implements llvm::DwarfUnit.
Definition at line 60 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::Asm, llvm::DwarfUnit::getUniqueID(), and llvm::AsmPrinter::OutStreamer.
Referenced by constructInlinedScopeDIE().
const SmallVectorImpl<RangeSpanList>& llvm::DwarfCompileUnit::getRangeLists () const [inline]
getRangeLists - Get the vector of range lists.
Definition at line 222 of file DwarfCompileUnit.h.
const SmallVectorImpl<RangeSpan>& llvm::DwarfCompileUnit::getRanges () const [inline]
getRanges - Get the list of ranges for this unit.
Definition at line 227 of file DwarfCompileUnit.h.
const MCSymbol* llvm::DwarfCompileUnit::getSectionSym () const [inline]
Definition at line 168 of file DwarfCompileUnit.h.
References llvm::MCSection::getBeginSymbol(), and llvm::DwarfUnit::Section.
DwarfCompileUnit* llvm::DwarfCompileUnit::getSkeleton () const [inline]
Definition at line 72 of file DwarfCompileUnit.h.
Referenced by forBothCUs().
void llvm::DwarfCompileUnit::initStmtList ()
Definition at line 240 of file DwarfCompileUnit.cpp.
References addSectionLabel(), llvm::DwarfUnit::Asm, llvm::dwarf::DW_AT_stmt_list, llvm::AsmPrinter::getObjFileLowering(), llvm::DwarfUnit::getUniqueID(), llvm::AsmPrinter::OutStreamer, and llvm::DwarfUnit::UnitDie.
void llvm::DwarfCompileUnit::setBaseAddress (const MCSymbol * Base) [inline]
Definition at line 230 of file DwarfCompileUnit.h.
void llvm::DwarfCompileUnit::setSkeleton (DwarfCompileUnit & Skel) [inline]
Set the skeleton unit associated with this unit.
Definition at line 166 of file DwarfCompileUnit.h.
SmallVector<RangeSpan, 2> llvm::DwarfCompileUnit::takeRanges () [inline]
Definition at line 228 of file DwarfCompileUnit.h.
DIE & llvm::DwarfCompileUnit::updateSubprogramScopeDIE (const DISubprogram * SP)
Find DIE for the given subprogram and attach appropriate DW_AT_low_pc and DW_AT_high_pc attributes.
If there are global variables in this scope then create and insert DIEs for these variables.
Definition at line 278 of file DwarfCompileUnit.cpp.
References addAddress(), llvm::DwarfUnit::addFlag(), llvm::DwarfDebug::addSubprogramNames(), llvm::DwarfUnit::Asm, attachLowHighPC(), llvm::DwarfUnit::DD, llvm::TargetOptions::DisableFramePointerElim(), llvm::dwarf::DW_AT_APPLE_omit_frame_ptr, llvm::dwarf::DW_AT_frame_base, llvm::DwarfDebug::getCurrentFunction(), llvm::TargetRegisterInfo::getFrameRegister(), llvm::AsmPrinter::getFunctionBegin(), llvm::AsmPrinter::getFunctionEnd(), llvm::DwarfUnit::getOrCreateSubprogramDIE(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::AsmPrinter::MF, and llvm::TargetMachine::Options.
Referenced by constructSubprogramScopeDIE().
The documentation for this class was generated from the following files:
DwarfCompileUnit.h
DwarfCompileUnit.cpp