LLVM: llvm::PressureDiff Class Reference
llvm::PressureDiff Class Reference
List of PressureChanges in order of increasing, unique PSetID.
#include <RegisterPressure.h>
Public Types
typedef PressureChange * iterator
typedef const PressureChange * const_iterator
Public Member Functions
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
void addPressureChange (unsigned RegUnit, bool IsDec, const MachineRegisterInfo *MRI)
Add a change in pressure to the pressure diff of a given instruction.
Detailed Description
List of PressureChanges in order of increasing, unique PSetID.
Use a small fixed number, because we can fit more PressureChanges in an empty SmallVector than ever need to be tracked per register class. If more PSets are affected, then we only track the most constrained.
Definition at line 121 of file RegisterPressure.h.
Member Typedef Documentation
typedef const PressureChange* llvm::PressureDiff::const_iterator
Definition at line 130 of file RegisterPressure.h.
typedef PressureChange* llvm::PressureDiff::iterator
Definition at line 129 of file RegisterPressure.h.
Member Function Documentation
void PressureDiff::addPressureChange (unsigned RegUnit, bool IsDec, const MachineRegisterInfo * MRI)
Add a change in pressure to the pressure diff of a given instruction.
Definition at line 386 of file RegisterPressure.cpp.
References begin(), end(), llvm::MachineRegisterInfo::getPressureSets(), llvm::PressureChange::getPSet(), llvm::PressureChange::getUnitInc(), llvm::PSetIterator::getWeight(), I, llvm::PressureChange::isValid(), llvm::PSetIterator::isValid(), llvm::PressureChange::setUnitInc(), and std::swap().
Referenced by collectPDiff(), llvm::RegPressureTracker::recede(), and llvm::ScheduleDAGMILive::updatePressureDiffs().
iterator llvm::PressureDiff::begin () [inline]
Definition at line 131 of file RegisterPressure.h.
Referenced by addPressureChange(), collectPDiff(), llvm::RegPressureTracker::getUpwardPressureDelta(), and llvm::ScheduleDAGMILive::updateScheduledPressure().
const_iterator llvm::PressureDiff::begin () const [inline]
Definition at line 133 of file RegisterPressure.h.
iterator llvm::PressureDiff::end () [inline]
Definition at line 132 of file RegisterPressure.h.
Referenced by addPressureChange(), llvm::RegPressureTracker::getUpwardPressureDelta(), and llvm::ScheduleDAGMILive::updateScheduledPressure().
const_iterator llvm::PressureDiff::end () const [inline]
Definition at line 134 of file RegisterPressure.h.
The documentation for this class was generated from the following files:
RegisterPressure.h
RegisterPressure.cpp