LLVM: llvm::ARMBaseTargetMachine Class Reference
llvm::ARMBaseTargetMachine Class Reference
#include <ARMTargetMachine.h>
Public Types
enum ARMABI { ARM_ABI_UNKNOWN, ARM_ABI_APCS, ARM_ABI_AAPCS }
Public Member Functions
ARMBaseTargetMachine (const Target &T, const Triple &TT, StringRef CPU, StringRef FS, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL, bool isLittle)
TargetMachine ctor - Create an ARM architecture model.
~ARMBaseTargetMachine () override
const ARMSubtarget * getSubtargetImpl () const
const ARMSubtarget * getSubtargetImpl (const Function &F) const override
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
bool isLittleEndian () const
TargetIRAnalysis getTargetIRAnalysis () override
Get the TargetIRAnalysis for this target.
TargetPassConfig * createPassConfig (PassManagerBase &PM) override
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
TargetLoweringObjectFile * getObjFileLowering () const override
Public Attributes
enum
llvm::ARMBaseTargetMachine::ARMABI TargetABI
Protected Attributes
std::unique_ptr
< TargetLoweringObjectFile > TLOF
ARMSubtarget Subtarget
bool isLittle
StringMap< std::unique_ptr
< ARMSubtarget > > SubtargetMap
Detailed Description
Definition at line 24 of file ARMTargetMachine.h.
Member Enumeration Documentation
enum llvm::ARMBaseTargetMachine::ARMABI
Enumerator:
ARM_ABI_UNKNOWN
ARM_ABI_APCS
ARM_ABI_AAPCS
Definition at line 26 of file ARMTargetMachine.h.
Constructor & Destructor Documentation
ARMBaseTargetMachine::ARMBaseTargetMachine (const Target & T, const Triple & TT, StringRef CPU, StringRef FS, const TargetOptions & Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL, bool isLittle)
TargetMachine ctor - Create an ARM architecture model.
Definition at line 173 of file ARMTargetMachine.cpp.
References llvm::FloatABI::Default, llvm::TargetOptions::FloatABIType, llvm::FloatABI::Hard, llvm::ARMSubtarget::isTargetHardFloat(), llvm::FloatABI::Soft, and Subtarget.
ARMBaseTargetMachine::~ARMBaseTargetMachine () [override]
Definition at line 190 of file ARMTargetMachine.cpp.
Member Function Documentation
TargetPassConfig * ARMBaseTargetMachine::createPassConfig (PassManagerBase & PM) [override, virtual]
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
createPassConfig - Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
Targets may override this to extend TargetPassConfig.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 315 of file ARMTargetMachine.cpp.
TargetLoweringObjectFile* llvm::ARMBaseTargetMachine::getObjFileLowering () const [inline, override, virtual]
Reimplemented from llvm::TargetMachine.
Definition at line 55 of file ARMTargetMachine.h.
References TLOF.
const ARMSubtarget* llvm::ARMBaseTargetMachine::getSubtargetImpl () const [inline]
Definition at line 45 of file ARMTargetMachine.h.
References Subtarget.
const ARMSubtarget * ARMBaseTargetMachine::getSubtargetImpl (const Function &) const [override, virtual]
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
Reimplemented from llvm::TargetMachine.
Definition at line 193 of file ARMTargetMachine.cpp.
References llvm::StringRef::empty(), llvm::FS, llvm::Function::getFnAttribute(), llvm::Attribute::getValueAsString(), llvm::Attribute::hasAttribute(), llvm::Function::hasFnAttribute(), I, isLittle, llvm::Attribute::None, llvm::TargetMachine::resetTargetOptions(), llvm::StringRef::str(), SubtargetMap, llvm::TargetMachine::TargetCPU, llvm::TargetMachine::TargetFS, and llvm::TargetMachine::TargetTriple.
TargetIRAnalysis ARMBaseTargetMachine::getTargetIRAnalysis () [override, virtual]
Get the TargetIRAnalysis for this target.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 228 of file ARMTargetMachine.cpp.
References F().
bool llvm::ARMBaseTargetMachine::isLittleEndian () const [inline]
Definition at line 47 of file ARMTargetMachine.h.
References isLittle.
Member Data Documentation
bool llvm::ARMBaseTargetMachine::isLittle [protected]
Definition at line 35 of file ARMTargetMachine.h.
Referenced by getSubtargetImpl(), and isLittleEndian().
ARMSubtarget llvm::ARMBaseTargetMachine::Subtarget [protected]
Definition at line 34 of file ARMTargetMachine.h.
Referenced by ARMBaseTargetMachine(), llvm::ARMTargetMachine::ARMTargetMachine(), and getSubtargetImpl().
StringMap<std::unique_ptr<ARMSubtarget> > llvm::ARMBaseTargetMachine::SubtargetMap [mutable, protected]
Definition at line 36 of file ARMTargetMachine.h.
Referenced by getSubtargetImpl().
enum llvm::ARMBaseTargetMachine::ARMABI llvm::ARMBaseTargetMachine::TargetABI
Referenced by llvm::ARMSubtarget::isAAPCS_ABI(), and llvm::ARMSubtarget::isAPCS_ABI().
std::unique_ptr<TargetLoweringObjectFile> llvm::ARMBaseTargetMachine::TLOF [protected]
Definition at line 33 of file ARMTargetMachine.h.
Referenced by getObjFileLowering().
The documentation for this class was generated from the following files:
ARMTargetMachine.h
ARMTargetMachine.cpp