LLVM: llvm::GraphWriter< GraphType > Class Template Reference
llvm::GraphWriter< GraphType > Class Template Reference
#include <GraphWriter.h>
Public Member Functions
GraphWriter (raw_ostream &o, const GraphType &g, bool SN)
void writeGraph (const std::string &Title="")
void writeHeader (const std::string &Title)
void writeFooter ()
void writeNodes ()
bool isNodeHidden (NodeType &Node)
bool isNodeHidden (NodeType *const *Node)
bool isNodeHidden (NodeType *Node)
void writeNode (NodeType &Node)
void writeNode (NodeType *const *Node)
void writeNode (NodeType *Node)
void writeEdge (NodeType *Node, unsigned edgeidx, child_iterator EI)
void emitSimpleNode (const void *ID, const std::string &Attr, const std::string &Label, unsigned NumEdgeSources=0, const std::vector< std::string > *EdgeSourceLabels=nullptr)
emitSimpleNode - Outputs a simple (non-record) node
void emitEdge (const void *SrcNodeID, int SrcNodePort, const void *DestNodeID, int DestNodePort, const std::string &Attrs)
emitEdge - Output an edge from a simple node into the graph...
raw_ostream & getOStream ()
getOStream - Get the raw output stream into the graph file.
Detailed Description
template<typename GraphType>
class llvm::GraphWriter< GraphType >
Definition at line 56 of file GraphWriter.h.
Constructor & Destructor Documentation
template<typename GraphType> llvm::GraphWriter< GraphType >::GraphWriter (raw_ostream & o, const GraphType & g, bool SN) [inline]
Definition at line 95 of file GraphWriter.h.
Member Function Documentation
template<typename GraphType> void llvm::GraphWriter< GraphType >::emitEdge (const void * SrcNodeID, int SrcNodePort, const void * DestNodeID, int DestNodePort, const std::string & Attrs) [inline]
emitEdge - Output an edge from a simple node into the graph...
Definition at line 283 of file GraphWriter.h.
References llvm::DefaultDOTGraphTraits::hasEdgeDestLabels().
Referenced by llvm::DOTGraphTraits< SelectionDAG * >::addCustomGraphFeatures(), llvm::ScheduleDAGSDNodes::getCustomGraphFeatures(), and llvm::GraphWriter< GraphType >::writeEdge().
template<typename GraphType> void llvm::GraphWriter< GraphType >::emitSimpleNode (const void * ID, const std::string & Attr, const std::string & Label, unsigned NumEdgeSources = 0, const std::vector< std::string > * EdgeSourceLabels = nullptr) [inline]
emitSimpleNode - Outputs a simple (non-record) node
Definition at line 260 of file GraphWriter.h.
References llvm::DOT::EscapeString().
Referenced by llvm::DOTGraphTraits< SelectionDAG * >::addCustomGraphFeatures(), and llvm::ScheduleDAGSDNodes::getCustomGraphFeatures().
template<typename GraphType> raw_ostream& llvm::GraphWriter< GraphType >::getOStream () [inline]
getOStream - Get the raw output stream into the graph file.
Useful to write fancy things using addCustomGraphFeatures().
Definition at line 303 of file GraphWriter.h.
Referenced by llvm::DOTGraphTraits< RegionInfoPass * >::addCustomGraphFeatures(), and llvm::DOTGraphTraits< RegionInfoPass * >::printRegionCluster().
template<typename GraphType> bool llvm::GraphWriter< GraphType >::isNodeHidden (NodeType & Node) [inline]
Definition at line 147 of file GraphWriter.h.
Referenced by llvm::GraphWriter< GraphType >::isNodeHidden(), and llvm::GraphWriter< GraphType >::writeNodes().
template<typename GraphType> bool llvm::GraphWriter< GraphType >::isNodeHidden (NodeType *const * Node) [inline]
Definition at line 151 of file GraphWriter.h.
References llvm::GraphWriter< GraphType >::isNodeHidden().
template<typename GraphType> bool llvm::GraphWriter< GraphType >::isNodeHidden (NodeType * Node) [inline]
Definition at line 155 of file GraphWriter.h.
References llvm::DefaultDOTGraphTraits::isNodeHidden().
template<typename GraphType> void llvm::GraphWriter< GraphType >::writeEdge (NodeType * Node, unsigned edgeidx, child_iterator EI) [inline]
Definition at line 238 of file GraphWriter.h.
References llvm::DefaultDOTGraphTraits::edgeTargetsEdgeSource(), llvm::GraphWriter< GraphType >::emitEdge(), llvm::DefaultDOTGraphTraits::getEdgeAttributes(), llvm::DefaultDOTGraphTraits::getEdgeSourceLabel(), and llvm::DefaultDOTGraphTraits::getEdgeTarget().
Referenced by llvm::GraphWriter< GraphType >::writeNode().
template<typename GraphType> void llvm::GraphWriter< GraphType >::writeFooter () [inline]
Definition at line 134 of file GraphWriter.h.
Referenced by llvm::GraphWriter< GraphType >::writeGraph().
template<typename GraphType> void llvm::GraphWriter< GraphType >::writeGraph (const std::string & Title = "") [inline]
Definition at line 99 of file GraphWriter.h.
References llvm::GraphWriter< GraphType >::writeFooter(), llvm::GraphWriter< GraphType >::writeHeader(), and llvm::GraphWriter< GraphType >::writeNodes().
Referenced by llvm::WriteGraph().
template<typename GraphType> void llvm::GraphWriter< GraphType >::writeHeader (const std::string & Title) [inline]
Definition at line 113 of file GraphWriter.h.
References llvm::DOT::EscapeString(), llvm::DefaultDOTGraphTraits::getGraphName(), llvm::DefaultDOTGraphTraits::getGraphProperties(), and llvm::DefaultDOTGraphTraits::renderGraphFromBottomUp().
Referenced by llvm::GraphWriter< GraphType >::writeGraph().
template<typename GraphType> void llvm::GraphWriter< GraphType >::writeNode (NodeType & Node) [inline]
Definition at line 159 of file GraphWriter.h.
Referenced by llvm::GraphWriter< GraphType >::writeNode(), and llvm::GraphWriter< GraphType >::writeNodes().
template<typename GraphType> void llvm::GraphWriter< GraphType >::writeNode (NodeType *const * Node) [inline]
Definition at line 163 of file GraphWriter.h.
References llvm::GraphWriter< GraphType >::writeNode().
template<typename GraphType> void llvm::GraphWriter< GraphType >::writeNode (NodeType * Node) [inline]
Definition at line 167 of file GraphWriter.h.
References llvm::DOT::EscapeString(), llvm::DefaultDOTGraphTraits::getEdgeDestLabel(), llvm::DefaultDOTGraphTraits::getNodeAttributes(), llvm::DefaultDOTGraphTraits::getNodeDescription(), llvm::DefaultDOTGraphTraits::getNodeLabel(), llvm::DefaultDOTGraphTraits::hasEdgeDestLabels(), llvm::DefaultDOTGraphTraits::hasNodeAddressLabel(), llvm::DefaultDOTGraphTraits::isNodeHidden(), llvm::DefaultDOTGraphTraits::numEdgeDestLabels(), llvm::DefaultDOTGraphTraits::renderGraphFromBottomUp(), llvm::raw_string_ostream::str(), and llvm::GraphWriter< GraphType >::writeEdge().
template<typename GraphType> void llvm::GraphWriter< GraphType >::writeNodes () [inline]
Definition at line 139 of file GraphWriter.h.
References I, llvm::GraphWriter< GraphType >::isNodeHidden(), and llvm::GraphWriter< GraphType >::writeNode().
Referenced by llvm::GraphWriter< GraphType >::writeGraph().
The documentation for this class was generated from the following file:
GraphWriter.h