LLVM: llvm::object::Archive::Child Class Reference
llvm::object::Archive::Child Class Reference
#include <Archive.h>
Public Member Functions
Child (const Archive *Parent, const char *Start)
bool operator== (const Child &other) const
bool operator< (const Child &other) const
Child getNext () const
ErrorOr< StringRef > getName () const
StringRef getRawName () const
sys::TimeValue getLastModified () const
StringRef getRawLastModified () const
unsigned getUID () const
unsigned getGID () const
sys::fs::perms getAccessMode () const
uint64_t getSize () const
uint64_t getRawSize () const
StringRef getBuffer () const
uint64_t getChildOffset () const
ErrorOr< MemoryBufferRef > getMemoryBufferRef () const
ErrorOr< std::unique_ptr
< Binary > > getAsBinary (LLVMContext *Context=nullptr) const
Detailed Description
Definition at line 54 of file Archive.h.
Constructor & Destructor Documentation
Archive::Child::Child (const Archive * Parent, const char * Start)
Definition at line 84 of file Archive.cpp.
References llvm::StringRef::getAsInteger(), llvm::object::ArchiveMemberHeader::getName(), llvm::object::ArchiveMemberHeader::getSize(), llvm_unreachable, llvm::COFF::NameSize, llvm::StringRef::rtrim(), llvm::StringRef::startswith(), and llvm::StringRef::substr().
Member Function Documentation
sys::fs::perms llvm::object::Archive::Child::getAccessMode () const [inline]
Definition at line 89 of file Archive.h.
References llvm::object::ArchiveMemberHeader::getAccessMode().
Referenced by llvm::writeArchive().
ErrorOr< std::unique_ptr< Binary > > Archive::Child::getAsBinary (LLVMContext * Context = nullptr) const
Definition at line 193 of file Archive.cpp.
References llvm::object::createBinary(), llvm::ErrorOr< T >::get(), llvm::ErrorOr< T >::getError(), and llvm::object::Binary::getMemoryBufferRef().
Referenced by llvm::MCJIT::findSymbol().
StringRef llvm::object::Archive::Child::getBuffer () const [inline]
Definition at line 97 of file Archive.h.
References llvm::StringRef::data(), and getSize().
Referenced by llvm::object::Archive::Symbol::getName(), llvm::object::Archive::getNumberOfSymbols(), and llvm::object::Archive::symbol_begin().
uint64_t Archive::Child::getChildOffset () const
Definition at line 133 of file Archive.cpp.
References llvm::object::Binary::Data.
unsigned llvm::object::Archive::Child::getGID () const [inline]
Definition at line 88 of file Archive.h.
References llvm::object::ArchiveMemberHeader::getGID().
Referenced by llvm::writeArchive().
sys::TimeValue llvm::object::Archive::Child::getLastModified () const [inline]
Definition at line 81 of file Archive.h.
References llvm::object::ArchiveMemberHeader::getLastModified().
Referenced by llvm::writeArchive().
ErrorOr< MemoryBufferRef > Archive::Child::getMemoryBufferRef () const
Definition at line 184 of file Archive.cpp.
References llvm::ErrorOr< T >::get(), llvm::ErrorOr< T >::getError(), and getName().
Referenced by llvm::writeArchive().
ErrorOr< StringRef > Archive::Child::getName () const
Definition at line 140 of file Archive.cpp.
References addr, llvm::object::Binary::Data, llvm::StringRef::find(), llvm::StringRef::getAsInteger(), llvm::object::Archive::K_GNU, llvm::object::Archive::K_MIPS64, llvm_unreachable, name, llvm::object::parse_failed, llvm::StringRef::rtrim(), llvm::StringRef::size(), llvm::StringRef::startswith(), and llvm::StringRef::substr().
Referenced by llvm::object::Archive::Archive().
Archive::Child Archive::Child::getNext () const
Definition at line 118 of file Archive.cpp.
References llvm::object::Binary::Data.
Referenced by llvm::object::Archive::child_iterator::operator++().
StringRef llvm::object::Archive::Child::getRawLastModified () const [inline]
Definition at line 84 of file Archive.h.
References llvm::object::ArchiveMemberHeader::getRawLastModified().
StringRef llvm::object::Archive::Child::getRawName () const [inline]
Definition at line 80 of file Archive.h.
References llvm::object::ArchiveMemberHeader::getName().
Referenced by llvm::object::Archive::Archive().
uint64_t Archive::Child::getRawSize () const
Returns:
the size in the archive header for this member.
Definition at line 114 of file Archive.cpp.
uint64_t Archive::Child::getSize () const
Returns:
the size of the archive member without the header or padding.
Definition at line 108 of file Archive.cpp.
References llvm::object::Binary::Data.
Referenced by getBuffer(), and llvm::writeArchive().
unsigned llvm::object::Archive::Child::getUID () const [inline]
Definition at line 87 of file Archive.h.
References llvm::object::ArchiveMemberHeader::getUID().
Referenced by llvm::writeArchive().
bool llvm::object::Archive::Child::operator< (const Child & other) const [inline]
Definition at line 73 of file Archive.h.
References llvm::StringRef::begin().
bool llvm::object::Archive::Child::operator== (const Child & other) const [inline]
Definition at line 68 of file Archive.h.
References llvm::StringRef::begin().
The documentation for this class was generated from the following files:
Archive.h
Archive.cpp