LLVM: llvm::SelectionDAGBuilder Class Reference
llvm::SelectionDAGBuilder Class Reference
SelectionDAGBuilder - This is the common target-independent lowering implementation that is parameterized by a TargetLowering object.
#include <SelectionDAGBuilder.h>
Classes
struct BitTestBlock
struct BitTestCase
struct CaseBits
struct CaseBlock
CaseBlock - This structure is used to communicate between SelectionDAGBuilder and SDISel for the code generation of additional basic blocks needed by multi-case switch statements.
struct CaseCluster
A cluster of case labels.
class DanglingDebugInfo
DanglingDebugInfo - Helper type for DanglingDebugInfoMap.
struct JumpTable
struct JumpTableHeader
class StackProtectorDescriptor
A class which encapsulates all of the information needed to generate a stack protector check and signals to isel via its state being initialized that a stack protector needs to be generated.
struct SwitchWorkListItem
Public Member Functions
SelectionDAGBuilder (SelectionDAG &dag, FunctionLoweringInfo &funcinfo, CodeGenOpt::Level ol)
void init (GCFunctionInfo *gfi, AliasAnalysis &aa, const TargetLibraryInfo *li)
void clear ()
clear - Clear out the current SelectionDAG and the associated state and prepare this SelectionDAGBuilder object to be used for a new block.
void clearDanglingDebugInfo ()
clearDanglingDebugInfo - Clear the dangling debug information map.
SDValue getRoot ()
getRoot - Return the current virtual root of the Selection DAG, flushing any PendingLoad items.
SDValue getControlRoot ()
getControlRoot - Similar to getRoot, but instead of flushing all the PendingLoad items, flush all the PendingExports items.
SDLoc getCurSDLoc () const
DebugLoc getCurDebugLoc () const
unsigned getSDNodeOrder () const
void CopyValueToVirtualRegister (const Value *V, unsigned Reg)
void visit (const Instruction &I)
void visit (unsigned Opcode, const User &I)
SDValue getCopyFromRegs (const Value *V, Type *Ty)
getCopyFromRegs - If there was virtual register allocated for the value V emit CopyFromReg of the specified type Ty.
void resolveDanglingDebugInfo (const Value *V, SDValue Val)
SDValue getValue (const Value *V)
getValue - Return an SDValue for the given Value.
bool findValue (const Value *V) const
SDValue getNonRegisterValue (const Value *V)
getNonRegisterValue - Return an SDValue for the given Value, but don't look in FuncInfo.ValueMap for a virtual register.
SDValue getValueImpl (const Value *V)
getValueImpl - Helper function for getValue and getNonRegisterValue.
void setValue (const Value *V, SDValue NewN)
void setUnusedArgValue (const Value *V, SDValue NewN)
void FindMergedConditions (const Value *Cond, MachineBasicBlock *TBB, MachineBasicBlock *FBB, MachineBasicBlock *CurBB, MachineBasicBlock *SwitchBB, unsigned Opc, uint32_t TW, uint32_t FW)
FindMergedConditions - If Cond is an expression like.
void EmitBranchForMergedCondition (const Value *Cond, MachineBasicBlock *TBB, MachineBasicBlock *FBB, MachineBasicBlock *CurBB, MachineBasicBlock *SwitchBB, uint32_t TW, uint32_t FW)
EmitBranchForMergedCondition - Helper method for FindMergedConditions.
bool ShouldEmitAsBranches (const std::vector< CaseBlock > &Cases)
If the set of cases should be emitted as a series of branches, return true.
bool isExportableFromCurrentBlock (const Value *V, const BasicBlock *FromBB)
void CopyToExportRegsIfNeeded (const Value *V)
CopyToExportRegsIfNeeded - If the given value has virtual registers created for it, emit nodes to copy the value into the virtual registers.
void ExportFromCurrentBlock (const Value *V)
ExportFromCurrentBlock - If this condition isn't known to be exported from the current basic block, add it to ValueMap now so that we'll get a CopyTo/FromReg.
void LowerCallTo (ImmutableCallSite CS, SDValue Callee, bool IsTailCall, MachineBasicBlock *LandingPad=nullptr)
std::pair< SDValue, SDValue > lowerCallOperands (ImmutableCallSite CS, unsigned ArgIdx, unsigned NumArgs, SDValue Callee, Type *ReturnTy, MachineBasicBlock *LandingPad=nullptr, bool IsPatchPoint=false)
Lower an argument list according to the target calling convention.
void UpdateSplitBlock (MachineBasicBlock *First, MachineBasicBlock *Last)
UpdateSplitBlock - When an MBB was split during scheduling, update the references that need to refer to the last resulting block.
void LowerStatepoint (ImmutableStatepoint Statepoint, MachineBasicBlock *LandingPad=nullptr)
void visitSwitchCase (CaseBlock &CB, MachineBasicBlock *SwitchBB)
visitSwitchCase - Emits the necessary code to represent a single node in the binary search tree resulting from lowering a switch instruction.
void visitSPDescriptorParent (StackProtectorDescriptor &SPD, MachineBasicBlock *ParentBB)
Codegen a new tail for a stack protector check ParentMBB which has had its tail spliced into a stack protector check success bb.
void visitSPDescriptorFailure (StackProtectorDescriptor &SPD)
Codegen the failure basic block for a stack protector check.
void visitBitTestHeader (BitTestBlock &B, MachineBasicBlock *SwitchBB)
visitBitTestHeader - This function emits necessary code to produce value suitable for "bit tests"
void visitBitTestCase (BitTestBlock &BB, MachineBasicBlock *NextMBB, uint32_t BranchWeightToNext, unsigned Reg, BitTestCase &B, MachineBasicBlock *SwitchBB)
visitBitTestCase - this function produces one "bit test"
void visitJumpTable (JumpTable &JT)
visitJumpTable - Emit JumpTable node in the current MBB
void visitJumpTableHeader (JumpTable &JT, JumpTableHeader &JTH, MachineBasicBlock *SwitchBB)
visitJumpTableHeader - This function emits necessary code to produce index in the JumpTable from switch case.
unsigned visitLandingPadClauseBB (GlobalValue *ClauseGV, MachineBasicBlock *LPadMBB)
Public Attributes
SmallVector< SDValue, 8 > PendingLoads
PendingLoads - Loads are not emitted to the program immediately.
StatepointLoweringState StatepointLowering
State used while lowering a statepoint sequence (gc_statepoint, gc_relocate, and gc_result).
SelectionDAG & DAG
const DataLayout * DL
AliasAnalysis * AA
const TargetLibraryInfo * LibInfo
std::vector< CaseBlock > SwitchCases
SwitchCases - Vector of CaseBlock structures used to communicate SwitchInst code generation information.
std::vector< JumpTableBlock > JTCases
JTCases - Vector of JumpTable structures used to communicate SwitchInst code generation information.
std::vector< BitTestBlock > BitTestCases
BitTestCases - Vector of BitTestBlock structures used to communicate SwitchInst code generation information.
StackProtectorDescriptor SPDescriptor
A StackProtectorDescriptor structure used to communicate stack protector information in between SelectBasicBlock and FinishBasicBlock.
DenseMap< const Constant
*, unsigned > ConstantsOut
FunctionLoweringInfo & FuncInfo
FuncInfo - Information about the function as a whole.
CodeGenOpt::Level OptLevel
OptLevel - What optimization level we're generating code for.
GCFunctionInfo * GFI
GFI - Garbage collection metadata for the function.
DenseMap< MachineBasicBlock
*, SmallVector< unsigned, 4 > > LPadToCallSiteMap
LPadToCallSiteMap - Map a landing pad to the call site indexes.
bool HasTailCall
HasTailCall - This is set to true if a call in the current block has been translated as a tail call.
LLVMContext * Context
Static Public Attributes
static const unsigned LowestSDNodeOrder = 1
Lowest valid SDNodeOrder.
Detailed Description
SelectionDAGBuilder - This is the common target-independent lowering implementation that is parameterized by a TargetLowering object.
Definition at line 87 of file SelectionDAGBuilder.h.
Constructor & Destructor Documentation
llvm::SelectionDAGBuilder::SelectionDAGBuilder (SelectionDAG & dag, FunctionLoweringInfo & funcinfo, CodeGenOpt::Level ol) [inline]
Definition at line 613 of file SelectionDAGBuilder.h.
Member Function Documentation
void SelectionDAGBuilder::clear ()
clear - Clear out the current SelectionDAG and the associated state and prepare this SelectionDAGBuilder object to be used for a new block.
This doesn't clear out information about additional blocks that are needed to complete switch lowering or PHI node updating; that information is cleared out as it is consumed.
Definition at line 820 of file SelectionDAGBuilder.cpp.
References llvm::StatepointLoweringState::clear(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::SmallVectorImpl< T >::clear(), HasTailCall, LowestSDNodeOrder, PendingLoads, and StatepointLowering.
void SelectionDAGBuilder::clearDanglingDebugInfo ()
clearDanglingDebugInfo - Clear the dangling debug information map.
This function is separated from the clear so that debug information that is dangling in a basic block can be properly resolved in a different basic block. This allows the SelectionDAG to resolve dangling debug information attached to PHI nodes.
Definition at line 837 of file SelectionDAGBuilder.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear().
void SelectionDAGBuilder::CopyToExportRegsIfNeeded (const Value * V)
CopyToExportRegsIfNeeded - If the given value has virtual registers created for it, emit nodes to copy the value into the virtual registers.
Definition at line 1274 of file SelectionDAGBuilder.cpp.
References CopyValueToVirtualRegister(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), FuncInfo, llvm::Value::getType(), llvm::Type::isEmptyTy(), llvm::Value::use_empty(), and llvm::FunctionLoweringInfo::ValueMap.
Referenced by visit().
void SelectionDAGBuilder::CopyValueToVirtualRegister (const Value * V, unsigned Reg)
Definition at line 6994 of file SelectionDAGBuilder.cpp.
References llvm::ISD::ANY_EXTEND, llvm::ISD::CopyFromReg, DAG, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), FuncInfo, llvm::Value::getContext(), getCurSDLoc(), llvm::SelectionDAG::getEntryNode(), getNonRegisterValue(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), getReg(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::Value::getType(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::FunctionLoweringInfo::PreferredExtendType, and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by CopyToExportRegsIfNeeded(), and ExportFromCurrentBlock().
void SelectionDAGBuilder::EmitBranchForMergedCondition (const Value * Cond, MachineBasicBlock * TBB, MachineBasicBlock * FBB, MachineBasicBlock * CurBB, MachineBasicBlock * SwitchBB, uint32_t TWeight, uint32_t FWeight)
EmitBranchForMergedCondition - Helper method for FindMergedConditions.
This function emits a branch and is used at the leaves of an OR or an AND operator tree.
Definition at line 1358 of file SelectionDAGBuilder.cpp.
References DAG, R600_InstFlag::FC, llvm::MachineBasicBlock::getBasicBlock(), llvm::SelectionDAG::getContext(), llvm::getFCmpCodeWithoutNaN(), llvm::getFCmpCondCode(), llvm::getICmpCondCode(), llvm::ConstantInt::getTrue(), isExportableFromCurrentBlock(), llvm_unreachable, llvm::ISD::SETEQ, SwitchCases, and llvm::SystemZISD::TM.
Referenced by FindMergedConditions().
void SelectionDAGBuilder::ExportFromCurrentBlock (const Value * V)
ExportFromCurrentBlock - If this condition isn't known to be exported from the current basic block, add it to ValueMap now so that we'll get a CopyTo/FromReg.
Definition at line 1289 of file SelectionDAGBuilder.cpp.
References CopyValueToVirtualRegister(), FuncInfo, llvm::FunctionLoweringInfo::InitializeRegForValue(), and llvm::FunctionLoweringInfo::isExportedInst().
Referenced by lowerStatepointMetaArgs().
void SelectionDAGBuilder::FindMergedConditions (const Value * Cond, MachineBasicBlock * TBB, MachineBasicBlock * FBB, MachineBasicBlock * CurBB, MachineBasicBlock * SwitchBB, unsigned Opc, uint32_t TW, uint32_t FW)
FindMergedConditions - If Cond is an expression like.
Definition at line 1410 of file SelectionDAGBuilder.cpp.
References llvm::APIntOps::And(), llvm::MachineFunction::CreateMachineBasicBlock(), DAG, llvm::dyn_cast(), EmitBranchForMergedCondition(), llvm::MachineBasicBlock::getBasicBlock(), llvm::SelectionDAG::getMachineFunction(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::MachineBasicBlock::getParent(), llvm::Value::hasOneUse(), InBlock(), llvm::MachineFunction::insert(), llvm::APIntOps::Or(), and ScaleWeights().
bool SelectionDAGBuilder::findValue (const Value * V) const
Definition at line 999 of file SelectionDAGBuilder.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), FuncInfo, and llvm::FunctionLoweringInfo::ValueMap.
Referenced by getUniformBase().
SDValue SelectionDAGBuilder::getControlRoot ()
getControlRoot - Similar to getRoot, but instead of flushing all the PendingLoad items, flush all the PendingExports items.
It is necessary to do this before emitting a terminator instruction.
Definition at line 869 of file SelectionDAGBuilder.cpp.
References llvm::SmallVectorImpl< T >::clear(), DAG, llvm::SmallVectorBase::empty(), llvm::ISD::EntryToken, getCurSDLoc(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SelectionDAG::getRoot(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SelectionDAG::setRoot(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::ISD::TokenFactor.
Referenced by visitBitTestCase(), visitBitTestHeader(), visitJumpTable(), visitJumpTableHeader(), visitLandingPadClauseBB(), and visitSwitchCase().
SDValue SelectionDAGBuilder::getCopyFromRegs (const Value * V, Type * Ty)
getCopyFromRegs - If there was virtual register allocated for the value V emit CopyFromReg of the specified type Ty.
Return empty SDValue() otherwise.
Definition at line 960 of file SelectionDAGBuilder.cpp.
References DAG, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), FuncInfo, llvm::SelectionDAG::getContext(), getCurSDLoc(), llvm::SelectionDAG::getEntryNode(), llvm::SelectionDAG::getTargetLoweringInfo(), resolveDanglingDebugInfo(), and llvm::FunctionLoweringInfo::ValueMap.
Referenced by getValue().
DebugLoc llvm::SelectionDAGBuilder::getCurDebugLoc () const [inline]
Definition at line 656 of file SelectionDAGBuilder.h.
References llvm::Instruction::getDebugLoc().
SDLoc llvm::SelectionDAGBuilder::getCurSDLoc () const [inline]
Definition at line 652 of file SelectionDAGBuilder.h.
Referenced by CopyValueToVirtualRegister(), getControlRoot(), getCopyFromRegs(), getMemCmpLoad(), getRoot(), getValueImpl(), lowerCallFromStatepoint(), lowerCallOperands(), LowerCallTo(), LowerStatepoint(), pushStackMapConstant(), spillIncomingStatepointValue(), visitBitTestCase(), visitBitTestHeader(), visitJumpTable(), visitJumpTableHeader(), visitLandingPadClauseBB(), visitSPDescriptorFailure(), visitSPDescriptorParent(), and visitSwitchCase().
SDValue SelectionDAGBuilder::getNonRegisterValue (const Value * V)
getNonRegisterValue - Return an SDValue for the given Value, but don't look in FuncInfo.ValueMap for a virtual register.
Definition at line 1006 of file SelectionDAGBuilder.cpp.
References llvm::SDValue::getNode(), getValueImpl(), N, resolveDanglingDebugInfo(), and llvm::SDNode::setDebugLoc().
Referenced by CopyValueToVirtualRegister().
SDValue SelectionDAGBuilder::getRoot ()
getRoot - Return the current virtual root of the Selection DAG, flushing any PendingLoad items.
This must be done before emitting a store or any other node that may need to be ordered after any prior load instructions.
Definition at line 846 of file SelectionDAGBuilder.cpp.
References llvm::SmallVectorImpl< T >::clear(), DAG, llvm::SmallVectorBase::empty(), getCurSDLoc(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getRoot(), llvm::MVT::Other, PendingLoads, llvm::SelectionDAG::setRoot(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::ISD::TokenFactor.
Referenced by lowerCallOperands(), LowerCallTo(), and lowerIncomingStatepointValue().
unsigned llvm::SelectionDAGBuilder::getSDNodeOrder () const [inline]
Definition at line 660 of file SelectionDAGBuilder.h.
SDValue SelectionDAGBuilder::getValue (const Value * V)
getValue - Return an SDValue for the given Value.
Definition at line 977 of file SelectionDAGBuilder.cpp.
References getCopyFromRegs(), llvm::SDValue::getNode(), llvm::Value::getType(), getValueImpl(), N, and resolveDanglingDebugInfo().
Referenced by addStackMapLiveVars(), getMemCmpLoad(), getUniformBase(), getValueImpl(), lowerCallFromStatepoint(), lowerCallOperands(), LowerCallTo(), LowerStatepoint(), lowerStatepointMetaArgs(), removeDuplicatesGCPtrs(), reservePreviousStackSlotForValue(), visitBitTestHeader(), visitJumpTableHeader(), visitSPDescriptorParent(), and visitSwitchCase().
SDValue SelectionDAGBuilder::getValueImpl (const Value * V)
getValueImpl - Helper function for getValue and getNonRegisterValue.
Create an SDValue for the given value.
Definition at line 1029 of file SelectionDAGBuilder.cpp.
References llvm::SmallVectorImpl< T >::assign(), llvm::ISD::BUILD_VECTOR, llvm::C, llvm::WinEH::CE, llvm::ComputeValueVTs(), DAG, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), FuncInfo, llvm::SelectionDAG::getBlockAddress(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getContext(), getCurSDLoc(), llvm::SequentialType::getElementType(), llvm::SelectionDAG::getEntryNode(), llvm::SelectionDAG::getFrameIndex(), llvm::SelectionDAG::getGlobalAddress(), llvm::SelectionDAG::getMergeValues(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::VectorType::getNumElements(), llvm::SDNode::getNumValues(), llvm::Type::getPointerAddressSpace(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::Value::getType(), llvm::SelectionDAG::getUNDEF(), getValue(), llvm::TargetLoweringBase::getValueType(), llvm::FunctionLoweringInfo::InitializeRegForValue(), llvm::Type::isAggregateType(), llvm::EVT::isFloatingPoint(), llvm_unreachable, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SI, llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::FunctionLoweringInfo::StaticAllocaMap, and visit().
Referenced by getNonRegisterValue(), and getValue().
void SelectionDAGBuilder::init (GCFunctionInfo * gfi, AliasAnalysis & aa, const TargetLibraryInfo * li)
Definition at line 804 of file SelectionDAGBuilder.cpp.
References aa, AA, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), Context, DAG, DL, llvm::SelectionDAG::getContext(), llvm::TargetMachine::getDataLayout(), llvm::SelectionDAG::getTarget(), GFI, LibInfo, and LPadToCallSiteMap.
Referenced by llvm::SelectionDAGISel::runOnMachineFunction().
bool SelectionDAGBuilder::isExportableFromCurrentBlock (const Value * V, const BasicBlock * FromBB)
Definition at line 1300 of file SelectionDAGBuilder.cpp.
References FuncInfo, llvm::Function::getEntryBlock(), llvm::BasicBlock::getParent(), llvm::FunctionLoweringInfo::isExportedInst(), and VI.
Referenced by EmitBranchForMergedCondition().
std::pair< SDValue, SDValue > SelectionDAGBuilder::lowerCallOperands (ImmutableCallSite CS, unsigned ArgIdx, unsigned NumArgs, SDValue Callee, Type * ReturnTy, MachineBasicBlock * LandingPad = nullptr, bool IsPatchPoint = false)
Lower an argument list according to the target calling convention.
Returns:
A tuple of <return-value, token-chain>
This is a helper for lowering intrinsics that follow a target calling convention or require stack pointer adjustment. Only a subset of the intrinsic's operands need to participate in the calling convention.
Definition at line 6418 of file SelectionDAGBuilder.cpp.
References DAG, llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCallingConv(), getCurSDLoc(), getRoot(), llvm::Value::getType(), getValue(), llvm::Type::isEmptyTy(), llvm::TargetLowering::ArgListEntry::Node, llvm::TargetLowering::CallLoweringInfo::setCallee(), llvm::TargetLowering::CallLoweringInfo::setChain(), and llvm::TargetLowering::CallLoweringInfo::setDebugLoc().
Referenced by lowerCallFromStatepoint().
void SelectionDAGBuilder::LowerCallTo (ImmutableCallSite CS, SDValue Callee, bool IsTailCall, MachineBasicBlock * LandingPad = nullptr)
Definition at line 5074 of file SelectionDAGBuilder.cpp.
References llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_begin(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_end(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_size(), DAG, llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCalledValue(), getCurSDLoc(), llvm::SequentialType::getElementType(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getInstruction(), getRoot(), llvm::SelectionDAG::getTarget(), llvm::Value::getType(), getValue(), llvm::Type::isEmptyTy(), llvm::isInTailCallPosition(), llvm::TargetLowering::ArgListEntry::isSRet, llvm::TargetLowering::ArgListEntry::Node, llvm::TargetLowering::ArgListEntry::setAttributes(), llvm::TargetLowering::CallLoweringInfo::setCallee(), llvm::TargetLowering::CallLoweringInfo::setChain(), llvm::TargetLowering::CallLoweringInfo::setDebugLoc(), llvm::TargetLowering::CallLoweringInfo::setTailCall(), setValue(), and llvm::TargetLowering::ArgListEntry::Ty.
void SelectionDAGBuilder::LowerStatepoint (ImmutableStatepoint Statepoint, MachineBasicBlock * LandingPad = nullptr)
Definition at line 610 of file StatepointLowering.cpp.
References llvm::Call, llvm::CS, DAG, llvm::SelectionDAG::DeleteNode(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::gc_transition_args(), llvm::ISD::GC_TRANSITION_END, llvm::ISD::GC_TRANSITION_START, llvm::GCTransition, llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::getCallSite(), getCurSDLoc(), llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::getFlags(), llvm::SDNode::getGluedNode(), llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::getID(), llvm::SelectionDAG::getMachineNode(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::getNumPatchBytes(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getSrcValue(), llvm::GCFunctionInfo::getStrategy(), llvm::SelectionDAG::getTargetConstant(), llvm::SDValue::getValue(), getValue(), llvm::SelectionDAG::getVTList(), GFI, llvm::MVT::Glue, llvm::MVT::i32, llvm::MVT::i64, llvm::SmallVectorImpl< T >::insert(), llvm::isGCRelocate(), lowerCallFromStatepoint(), lowerStatepointMetaArgs(), llvm::MaskAll, llvm::SDNode::op_begin(), llvm::SDNode::op_end(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), pushStackMapConstant(), llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::StatepointLoweringState::scheduleRelocCall(), llvm::StatepointLoweringState::startNewStatepoint(), llvm::TargetOpcode::STATEPOINT, StatepointLowering, llvm::GCStrategy::useStatepoints(), and llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::verify().
void SelectionDAGBuilder::resolveDanglingDebugInfo (const Value * V, SDValue Val)
Definition at line 930 of file SelectionDAGBuilder.cpp.
References llvm::SelectionDAG::AddDbgValue(), DAG, llvm::dbgs(), DEBUG, llvm::DI, llvm::SelectionDAG::getDbgValue(), llvm::DbgValueInst::getExpression(), llvm::SDValue::getNode(), llvm::DbgValueInst::getOffset(), llvm::SDValue::getResNo(), llvm::DbgValueInst::getVariable(), and llvm::DILocalVariable::isValidLocationForIntrinsic().
Referenced by getCopyFromRegs(), getNonRegisterValue(), and getValue().
void llvm::SelectionDAGBuilder::setUnusedArgValue (const Value * V, SDValue NewN) [inline]
Definition at line 687 of file SelectionDAGBuilder.h.
References llvm::SDValue::getNode(), and N.
void llvm::SelectionDAGBuilder::setValue (const Value * V, SDValue NewN) [inline]
Definition at line 681 of file SelectionDAGBuilder.h.
References llvm::SDValue::getNode(), and N.
Referenced by getUniformBase(), lowerCallFromStatepoint(), and LowerCallTo().
bool SelectionDAGBuilder::ShouldEmitAsBranches (const std::vector< CaseBlock > & Cases)
If the set of cases should be emitted as a series of branches, return true.
If we should emit this as a bunch of and/or'd together conditions, return false.
Definition at line 1510 of file SelectionDAGBuilder.cpp.
References llvm::ISD::SETEQ, and llvm::ISD::SETNE.
void SelectionDAGBuilder::UpdateSplitBlock (MachineBasicBlock * First, MachineBasicBlock * Last)
UpdateSplitBlock - When an MBB was split during scheduling, update the references that need to refer to the last resulting block.
Definition at line 2096 of file SelectionDAGBuilder.cpp.
References BitTestCases, JTCases, and llvm::IndexedInstrProf::Last.
void SelectionDAGBuilder::visit (const Instruction & I)
Definition at line 895 of file SelectionDAGBuilder.cpp.
References CopyToExportRegsIfNeeded(), llvm::Instruction::getOpcode(), llvm::Instruction::getParent(), HasTailCall, and I.
Referenced by getValueImpl().
void SelectionDAGBuilder::visit (unsigned Opcode, const User & I)
Definition at line 916 of file SelectionDAGBuilder.cpp.
References llvm_unreachable.
void SelectionDAGBuilder::visitBitTestCase (BitTestBlock & BB, MachineBasicBlock * NextMBB, uint32_t BranchWeightToNext, unsigned Reg, BitTestCase & B, MachineBasicBlock * SwitchBB)
visitBitTestCase - this function produces one "bit test"
Definition at line 1895 of file SelectionDAGBuilder.cpp.
References llvm::ISD::AND, llvm::ISD::BR, llvm::ISD::BRCOND, llvm::countPopulation(), llvm::countTrailingOnes(), llvm::countTrailingZeros(), DAG, llvm::SelectionDAG::getBasicBlock(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), getControlRoot(), llvm::SelectionDAG::getCopyFromReg(), getCurSDLoc(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getSetCC(), llvm::TargetLoweringBase::getSetCCResultType(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::MVT::Other, llvm::ISD::SETEQ, llvm::ISD::SETNE, llvm::SelectionDAG::setRoot(), and llvm::ISD::SHL.
void SelectionDAGBuilder::visitBitTestHeader (BitTestBlock & B, MachineBasicBlock * SwitchBB)
visitBitTestHeader - This function emits necessary code to produce value suitable for "bit tests"
Definition at line 1838 of file SelectionDAGBuilder.cpp.
References llvm::ISD::BR, llvm::ISD::BRCOND, llvm::FunctionLoweringInfo::CreateReg(), DAG, FuncInfo, llvm::SelectionDAG::getBasicBlock(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), getControlRoot(), llvm::SelectionDAG::getCopyToReg(), getCurSDLoc(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getSetCC(), llvm::TargetLoweringBase::getSetCCResultType(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::TargetLoweringBase::isTypeLegal(), llvm::isUIntN(), llvm::MVT::Other, llvm::SelectionDAG::setRoot(), llvm::ISD::SETUGT, and llvm::ISD::SUB.
void SelectionDAGBuilder::visitJumpTable (JumpTable & JT)
visitJumpTable - Emit JumpTable node in the current MBB
Definition at line 1691 of file SelectionDAGBuilder.cpp.
References llvm::ISD::BR_JT, DAG, getControlRoot(), llvm::SelectionDAG::getCopyFromReg(), getCurSDLoc(), llvm::SelectionDAG::getJumpTable(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValue(), llvm::MVT::Other, and llvm::SelectionDAG::setRoot().
void SelectionDAGBuilder::visitJumpTableHeader (JumpTable & JT, JumpTableHeader & JTH, MachineBasicBlock * SwitchBB)
visitJumpTableHeader - This function emits necessary code to produce index in the JumpTable from switch case.
Definition at line 1706 of file SelectionDAGBuilder.cpp.
References llvm::ISD::BR, llvm::ISD::BRCOND, llvm::ARMISD::CMP, llvm::FunctionLoweringInfo::CreateReg(), DAG, FuncInfo, llvm::SelectionDAG::getBasicBlock(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), getControlRoot(), llvm::SelectionDAG::getCopyToReg(), getCurSDLoc(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getSetCC(), llvm::TargetLoweringBase::getSetCCResultType(), llvm::SelectionDAG::getTargetLoweringInfo(), getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::MVT::Other, llvm::SelectionDAG::setRoot(), llvm::ISD::SETUGT, and llvm::ISD::SUB.
unsigned SelectionDAGBuilder::visitLandingPadClauseBB (GlobalValue * ClauseGV, MachineBasicBlock * LPadMBB)
Definition at line 2041 of file SelectionDAGBuilder.cpp.
References llvm::MachineBasicBlock::addSuccessor(), llvm::ISD::BR, llvm::MachineRegisterInfo::createVirtualRegister(), DAG, FuncInfo, llvm::SelectionDAG::getBasicBlock(), llvm::SelectionDAG::getConstant(), getControlRoot(), llvm::SelectionDAG::getCopyToReg(), getCurSDLoc(), llvm::SelectionDAG::getMachineFunction(), llvm::MachineFunction::getMMI(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::TargetLoweringBase::getRegClassFor(), llvm::MachineFunction::getRegInfo(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::MachineModuleInfo::getTypeIDFor(), llvm::FunctionLoweringInfo::MBB, llvm::FunctionLoweringInfo::MF, llvm::MVT::Other, and llvm::SelectionDAG::setRoot().
void SelectionDAGBuilder::visitSPDescriptorFailure (StackProtectorDescriptor & SPD)
Codegen the failure basic block for a stack protector check.
A failure stack protector machine basic block consists simply of a call to __stack_chk_fail().
For a high level explanation of how this fits into the stack protector generation see the comment on the declaration of class StackProtectorDescriptor.
Definition at line 1828 of file SelectionDAGBuilder.cpp.
References DAG, getCurSDLoc(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::MVT::isVoid, llvm::TargetLowering::makeLibCall(), llvm::SelectionDAG::setRoot(), and llvm::RTLIB::STACKPROTECTOR_CHECK_FAIL.
void SelectionDAGBuilder::visitSPDescriptorParent (StackProtectorDescriptor & SPD, MachineBasicBlock * ParentBB)
Codegen a new tail for a stack protector check ParentMBB which has had its tail spliced into a stack protector check success bb.
For a high level explanation of how this fits into the stack protector generation see the comment on the declaration of class StackProtectorDescriptor.
Definition at line 1759 of file SelectionDAGBuilder.cpp.
References Align(), llvm::ISD::BR, llvm::ISD::BRCOND, DAG, llvm::SelectionDAG::getBasicBlock(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), getCurSDLoc(), llvm::TargetLoweringBase::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::MachinePointerInfo::getFixedStack(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::TargetLoweringBase::getPointerTy(), llvm::DataLayout::getPrefTypeAlignment(), llvm::SelectionDAG::getSetCC(), llvm::TargetLoweringBase::getSetCCResultType(), llvm::MachineFrameInfo::getStackProtectorIndex(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::Value::getType(), getValue(), llvm::SDValue::getValueType(), llvm::MVT::Other, llvm::ISD::SETNE, llvm::SelectionDAG::setRoot(), llvm::ISD::SUB, and llvm::TargetLowering::useLoadStackGuardNode().
void SelectionDAGBuilder::visitSwitchCase (CaseBlock & CB, MachineBasicBlock * SwitchBB)
visitSwitchCase - Emits the necessary code to represent a single node in the binary search tree resulting from lowering a switch instruction.
Definition at line 1623 of file SelectionDAGBuilder.cpp.
References llvm::ISD::BR, llvm::ISD::BRCOND, DAG, llvm::SelectionDAG::getBasicBlock(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), getControlRoot(), getCurSDLoc(), llvm::ConstantInt::getFalse(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getSetCC(), llvm::ConstantInt::getTrue(), getValue(), llvm::SDValue::getValueType(), llvm::MVT::i1, llvm::MVT::Other, llvm::ISD::SETEQ, llvm::ISD::SETLE, llvm::SelectionDAG::setRoot(), llvm::ISD::SETULE, llvm::ISD::SUB, SUB, std::swap(), and llvm::ISD::XOR.
Member Data Documentation
AliasAnalysis* llvm::SelectionDAGBuilder::AA
Definition at line 571 of file SelectionDAGBuilder.h.
Referenced by getMemCmpLoad(), and init().
std::vector<BitTestBlock> llvm::SelectionDAGBuilder::BitTestCases
BitTestCases - Vector of BitTestBlock structures used to communicate SwitchInst code generation information.
Definition at line 582 of file SelectionDAGBuilder.h.
Referenced by UpdateSplitBlock().
DenseMap<const Constant *, unsigned> llvm::SelectionDAGBuilder::ConstantsOut
Definition at line 589 of file SelectionDAGBuilder.h.
LLVMContext* llvm::SelectionDAGBuilder::Context
Definition at line 611 of file SelectionDAGBuilder.h.
Referenced by init().
SelectionDAG& llvm::SelectionDAGBuilder::DAG
Definition at line 569 of file SelectionDAGBuilder.h.
Referenced by addStackMapLiveVars(), llvm::StatepointLoweringState::allocateStackSlot(), CopyValueToVirtualRegister(), EmitBranchForMergedCondition(), FindMergedConditions(), getControlRoot(), getCopyFromRegs(), getMemCmpLoad(), getRoot(), getUniformBase(), getValueImpl(), init(), lowerCallFromStatepoint(), lowerCallOperands(), LowerCallTo(), lowerIncomingStatepointValue(), LowerStatepoint(), lowerStatepointMetaArgs(), pushStackMapConstant(), reservePreviousStackSlotForValue(), resolveDanglingDebugInfo(), spillIncomingStatepointValue(), visitBitTestCase(), visitBitTestHeader(), visitJumpTable(), visitJumpTableHeader(), visitLandingPadClauseBB(), visitSPDescriptorFailure(), visitSPDescriptorParent(), and visitSwitchCase().
const DataLayout* llvm::SelectionDAGBuilder::DL
Definition at line 570 of file SelectionDAGBuilder.h.
Referenced by getMemCmpLoad(), and init().
FunctionLoweringInfo& llvm::SelectionDAGBuilder::FuncInfo
FuncInfo - Information about the function as a whole.
Definition at line 593 of file SelectionDAGBuilder.h.
Referenced by llvm::StatepointLoweringState::allocateStackSlot(), CopyToExportRegsIfNeeded(), CopyValueToVirtualRegister(), ExportFromCurrentBlock(), findPreviousSpillSlot(), findValue(), getCopyFromRegs(), getValueImpl(), isExportableFromCurrentBlock(), lowerCallFromStatepoint(), lowerStatepointMetaArgs(), reservePreviousStackSlotForValue(), llvm::StatepointLoweringState::startNewStatepoint(), visitBitTestHeader(), visitJumpTableHeader(), and visitLandingPadClauseBB().
GCFunctionInfo* llvm::SelectionDAGBuilder::GFI
GFI - Garbage collection metadata for the function.
Definition at line 600 of file SelectionDAGBuilder.h.
Referenced by init(), LowerStatepoint(), and lowerStatepointMetaArgs().
bool llvm::SelectionDAGBuilder::HasTailCall
HasTailCall - This is set to true if a call in the current block has been translated as a tail call.
In this case, no subsequent DAG nodes should be created.
Definition at line 609 of file SelectionDAGBuilder.h.
Referenced by clear(), and visit().
std::vector<JumpTableBlock> llvm::SelectionDAGBuilder::JTCases
JTCases - Vector of JumpTable structures used to communicate SwitchInst code generation information.
Definition at line 579 of file SelectionDAGBuilder.h.
Referenced by UpdateSplitBlock().
const TargetLibraryInfo* llvm::SelectionDAGBuilder::LibInfo
Definition at line 572 of file SelectionDAGBuilder.h.
Referenced by init().
const unsigned llvm::SelectionDAGBuilder::LowestSDNodeOrder = 1 [static]
Lowest valid SDNodeOrder.
The special case 0 is reserved for scheduling nodes without a corresponding SDNode.
Definition at line 567 of file SelectionDAGBuilder.h.
Referenced by clear().
DenseMap<MachineBasicBlock*, SmallVector<unsigned, 4> > llvm::SelectionDAGBuilder::LPadToCallSiteMap
LPadToCallSiteMap - Map a landing pad to the call site indexes.
Definition at line 603 of file SelectionDAGBuilder.h.
Referenced by init().
CodeGenOpt::Level llvm::SelectionDAGBuilder::OptLevel
OptLevel - What optimization level we're generating code for.
Definition at line 597 of file SelectionDAGBuilder.h.
SmallVector<SDValue, 8> llvm::SelectionDAGBuilder::PendingLoads
PendingLoads - Loads are not emitted to the program immediately.
We bunch them up and then emit token factor nodes when possible. This allows us to get simple disambiguation between loads without worrying about alias analysis.
Definition at line 120 of file SelectionDAGBuilder.h.
Referenced by clear(), getMemCmpLoad(), and getRoot().
StackProtectorDescriptor llvm::SelectionDAGBuilder::SPDescriptor
A StackProtectorDescriptor structure used to communicate stack protector information in between SelectBasicBlock and FinishBasicBlock.
Definition at line 585 of file SelectionDAGBuilder.h.
StatepointLoweringState llvm::SelectionDAGBuilder::StatepointLowering
State used while lowering a statepoint sequence (gc_statepoint, gc_relocate, and gc_result).
See StatepointLowering.hpp/cpp for details.
Definition at line 124 of file SelectionDAGBuilder.h.
Referenced by clear(), LowerStatepoint(), lowerStatepointMetaArgs(), reservePreviousStackSlotForValue(), and spillIncomingStatepointValue().
std::vector<CaseBlock> llvm::SelectionDAGBuilder::SwitchCases
SwitchCases - Vector of CaseBlock structures used to communicate SwitchInst code generation information.
Definition at line 576 of file SelectionDAGBuilder.h.
Referenced by EmitBranchForMergedCondition().
The documentation for this class was generated from the following files:
SelectionDAGBuilder.h
SelectionDAGBuilder.cpp
StatepointLowering.cpp