LLVM: llvm::PrintRegUnit Class Reference
llvm::PrintRegUnit Class Reference
PrintRegUnit - Helper class for printing register units on a raw_ostream.
#include <TargetRegisterInfo.h>
Public Member Functions
PrintRegUnit (unsigned unit, const TargetRegisterInfo *tri)
void print (raw_ostream &) const
Protected Attributes
const TargetRegisterInfo * TRI
unsigned Unit
Detailed Description
PrintRegUnit - Helper class for printing register units on a raw_ostream.
Register units are named after their root registers:
AL - Single root. FP0~ST7 - Dual roots.
Usage: OS << PrintRegUnit(Unit, TRI) << '
';
Definition at line 971 of file TargetRegisterInfo.h.
Constructor & Destructor Documentation
llvm::PrintRegUnit::PrintRegUnit (unsigned unit, const TargetRegisterInfo * tri) [inline]
Definition at line 976 of file TargetRegisterInfo.h.
Member Function Documentation
void PrintRegUnit::print (raw_ostream & OS) const
Reimplemented in llvm::PrintVRegOrUnit.
Definition at line 56 of file TargetRegisterInfo.cpp.
References llvm::MCRegisterInfo::getName(), llvm::MCRegisterInfo::getNumRegUnits(), llvm::MCRegUnitRootIterator::isValid(), TRI, and Unit.
Referenced by llvm::operator<<().
Member Data Documentation
const TargetRegisterInfo* llvm::PrintRegUnit::TRI [protected]
Definition at line 973 of file TargetRegisterInfo.h.
Referenced by print(), and llvm::PrintVRegOrUnit::print().
unsigned llvm::PrintRegUnit::Unit [protected]
Definition at line 974 of file TargetRegisterInfo.h.
Referenced by print(), and llvm::PrintVRegOrUnit::print().
The documentation for this class was generated from the following files:
TargetRegisterInfo.h
TargetRegisterInfo.cpp