LLVM: llvm::DWARFDebugAranges Class Reference
llvm::DWARFDebugAranges Class Reference
#include <DWARFDebugAranges.h>
Classes
struct Range
struct RangeEndpoint
Public Member Functions
void generate (DWARFContext *CTX)
uint32_t findAddress (uint64_t Address) const
Detailed Description
Definition at line 21 of file DWARFDebugAranges.h.
Member Function Documentation
uint32_t DWARFDebugAranges::findAddress (uint64_t Address) const
Definition at line 112 of file DWARFDebugAranges.cpp.
References llvm::sys::path::begin(), and llvm::sys::path::end().
void DWARFDebugAranges::generate (DWARFContext * CTX)
Definition at line 38 of file DWARFDebugAranges.cpp.
References llvm::DWARFContext::compile_units(), llvm::DWARFContext::getARangeSection(), llvm::DenseSet< ValueT, ValueInfoT >::insert(), and llvm::DWARFContext::isLittleEndian().
Referenced by llvm::DWARFContext::getDebugAranges().
The documentation for this class was generated from the following files:
DWARFDebugAranges.h
DWARFDebugAranges.cpp