LLVM: llvm::UnaryInstruction Class Reference
llvm::UnaryInstruction Class Reference
#include <InstrTypes.h>
Public Member Functions
void * operator new (size_t s)
Allocate a User with an operand pointer co-allocated.
~UnaryInstruction () override
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
Static Public Member Functions
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
UnaryInstruction (Type *Ty, unsigned iType, Value *V, Instruction *IB=nullptr)
UnaryInstruction (Type *Ty, unsigned iType, Value *V, BasicBlock *IAE)
Detailed Description
Definition at line 85 of file InstrTypes.h.
Constructor & Destructor Documentation
llvm::UnaryInstruction::UnaryInstruction (Type * Ty, unsigned iType, Value * V, Instruction * IB = nullptr) [inline, protected]
Definition at line 89 of file InstrTypes.h.
llvm::UnaryInstruction::UnaryInstruction (Type * Ty, unsigned iType, Value * V, BasicBlock * IAE) [inline, protected]
Definition at line 94 of file InstrTypes.h.
UnaryInstruction::~UnaryInstruction () [override]
Definition at line 53 of file Instructions.cpp.
Member Function Documentation
static bool llvm::UnaryInstruction::classof (const Instruction * I) [inline, static]
Reimplemented in llvm::AddrSpaceCastInst, llvm::BitCastInst, llvm::PtrToIntInst, llvm::IntToPtrInst, llvm::FPToSIInst, llvm::FPToUIInst, llvm::SIToFPInst, llvm::UIToFPInst, llvm::FPExtInst, llvm::FPTruncInst, llvm::SExtInst, llvm::ZExtInst, llvm::TruncInst, llvm::ExtractValueInst, llvm::VAArgInst, llvm::CastInst, llvm::LoadInst, and llvm::AllocaInst.
Definition at line 111 of file InstrTypes.h.
References llvm::Alloca, llvm::ExtractValue, llvm::Instruction::getOpcode(), llvm::SPII::Load, and llvm::VAArg.
Referenced by classof().
static bool llvm::UnaryInstruction::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::Instruction.
Reimplemented in llvm::AddrSpaceCastInst, llvm::BitCastInst, llvm::PtrToIntInst, llvm::IntToPtrInst, llvm::FPToSIInst, llvm::FPToUIInst, llvm::SIToFPInst, llvm::UIToFPInst, llvm::FPExtInst, llvm::FPTruncInst, llvm::SExtInst, llvm::ZExtInst, llvm::TruncInst, llvm::ExtractValueInst, llvm::VAArgInst, llvm::CastInst, llvm::LoadInst, and llvm::AllocaInst.
Definition at line 118 of file InstrTypes.h.
References classof().
llvm::UnaryInstruction::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
void* llvm::UnaryInstruction::operator new (size_t Size) [inline]
Allocate a User with an operand pointer co-allocated.
This is used for subclasses which need to allocate a variable number of operands, ie, 'hung off uses'.
Reimplemented from llvm::User.
Definition at line 100 of file InstrTypes.h.
References llvm::User::operator new().
The documentation for this class was generated from the following files:
InstrTypes.h
Instructions.cpp