LLVM: llvm::object::BasicSymbolRef Class Reference
llvm::object::BasicSymbolRef Class Reference
This is a value type class that represents a single symbol in the list of symbols in the object file.
#include <SymbolicFile.h>
Public Types
enum Flags {
SF_None = 0, SF_Undefined = 1U << 0, SF_Global = 1U << 1, SF_Weak = 1U << 2,
SF_Absolute = 1U << 3, SF_Common = 1U << 4, SF_Indirect = 1U << 5, SF_Exported = 1U << 6,
SF_FormatSpecific = 1U << 7, SF_Thumb = 1U << 8, SF_Hidden = 1U << 9
}
Public Member Functions
BasicSymbolRef ()
BasicSymbolRef (DataRefImpl SymbolP, const SymbolicFile *Owner)
bool operator== (const BasicSymbolRef &Other) const
bool operator< (const BasicSymbolRef &Other) const
void moveNext ()
std::error_code printName (raw_ostream &OS) const
uint32_t getFlags () const
Get symbol flags (bitwise OR of SymbolRef::Flags)
DataRefImpl getRawDataRefImpl () const
const SymbolicFile * getObject () const
Detailed Description
This is a value type class that represents a single symbol in the list of symbols in the object file.
Definition at line 78 of file SymbolicFile.h.
Member Enumeration Documentation
enum llvm::object::BasicSymbolRef::Flags
Enumerator:
SF_None
SF_Undefined
SF_Global
SF_Weak
SF_Absolute
SF_Common
SF_Indirect
SF_Exported
SF_FormatSpecific
SF_Thumb
SF_Hidden
Definition at line 84 of file SymbolicFile.h.
Constructor & Destructor Documentation
llvm::object::BasicSymbolRef::BasicSymbolRef () [inline]
Definition at line 99 of file SymbolicFile.h.
llvm::object::BasicSymbolRef::BasicSymbolRef (DataRefImpl SymbolP, const SymbolicFile * Owner) [inline]
Definition at line 166 of file SymbolicFile.h.
Member Function Documentation
uint32_t llvm::object::BasicSymbolRef::getFlags () const [inline]
Get symbol flags (bitwise OR of SymbolRef::Flags)
Definition at line 186 of file SymbolicFile.h.
References llvm::object::SymbolicFile::getSymbolFlags().
const SymbolicFile * llvm::object::BasicSymbolRef::getObject () const [inline]
Reimplemented in llvm::object::SymbolRef.
Definition at line 194 of file SymbolicFile.h.
DataRefImpl llvm::object::BasicSymbolRef::getRawDataRefImpl () const [inline]
Definition at line 190 of file SymbolicFile.h.
Referenced by llvm::object::SectionRef::containsSymbol(), llvm::object::SymbolRef::getAddress(), llvm::object::SymbolRef::getAlignment(), llvm::object::SymbolRef::getName(), llvm::object::SymbolRef::getOther(), llvm::object::SymbolRef::getSection(), llvm::object::SymbolRef::getSize(), and llvm::object::SymbolRef::getType().
void llvm::object::BasicSymbolRef::moveNext () [inline]
Definition at line 178 of file SymbolicFile.h.
References llvm::object::SymbolicFile::moveSymbolNext().
bool llvm::object::BasicSymbolRef::operator< (const BasicSymbolRef & Other) const [inline]
Definition at line 174 of file SymbolicFile.h.
bool llvm::object::BasicSymbolRef::operator== (const BasicSymbolRef & Other) const [inline]
Definition at line 170 of file SymbolicFile.h.
std::error_code llvm::object::BasicSymbolRef::printName (raw_ostream & OS) const [inline]
Definition at line 182 of file SymbolicFile.h.
References llvm::object::SymbolicFile::printSymbolName().
The documentation for this class was generated from the following file:
SymbolicFile.h