LLVM: llvm::DITemplateValueParameter Class Reference
llvm::DITemplateValueParameter Class Reference
#include <DebugInfoMetadata.h>
Public Member Functions
DEFINE_MDNODE_GET (DITemplateValueParameter,(unsigned Tag, StringRef Name, DITypeRef Type, Metadata *Value),(Tag, Name, Type, Value)) DEFINE_MDNODE_GET(DITemplateValueParameter
unsigned MDString Metadata
Metadata Value
TempDITemplateValueParameter clone () const
Create a (temporary) clone of this.
Metadata * getValue () const
Static Public Member Functions
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
Public Attributes
unsigned Tag
unsigned MDString * Name
unsigned MDString Metadata * Type
unsigned MDString Metadata
Metadata * Value
unsigned MDString Metadata Metadata Tag
unsigned MDString Metadata Metadata Name
unsigned MDString Metadata Metadata Type
Friends
class LLVMContextImpl
class MDNode
Detailed Description
Definition at line 1684 of file DebugInfoMetadata.h.
Member Function Documentation
static bool llvm::DITemplateValueParameter::classof (const Metadata * MD) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::DITemplateParameter.
Definition at line 1723 of file DebugInfoMetadata.h.
References llvm::Metadata::DITemplateValueParameterKind, and llvm::Metadata::getMetadataID().
unsigned MDString Metadata Metadata Value TempDITemplateValueParameter llvm::DITemplateValueParameter::clone () const [inline]
Create a (temporary) clone of this.
Reimplemented from llvm::MDNode.
Definition at line 1719 of file DebugInfoMetadata.h.
llvm::DITemplateValueParameter::DEFINE_MDNODE_GET (DITemplateValueParameter , (unsigned Tag, StringRef Name,DITypeRef Type, Metadata *Value) , (Tag, Name, Type, Value))
Metadata* llvm::DITemplateValueParameter::getValue () const [inline]
Definition at line 1721 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by llvm::MDNodeKeyImpl< DITemplateValueParameter >::isKeyOf(), and WriteDITemplateValueParameter().
Friends And Related Function Documentation
friend class LLVMContextImpl [friend]
Reimplemented from llvm::DINode.
Definition at line 1685 of file DebugInfoMetadata.h.
friend class MDNode [friend]
Reimplemented from llvm::DINode.
Definition at line 1686 of file DebugInfoMetadata.h.
Member Data Documentation
unsigned MDString* llvm::DITemplateValueParameter::Name
Definition at line 1715 of file DebugInfoMetadata.h.
unsigned MDString Metadata Metadata llvm::DITemplateValueParameter::Name
Definition at line 1715 of file DebugInfoMetadata.h.
unsigned llvm::DITemplateValueParameter::Tag
Definition at line 1715 of file DebugInfoMetadata.h.
unsigned MDString Metadata Metadata llvm::DITemplateValueParameter::Tag
Definition at line 1715 of file DebugInfoMetadata.h.
unsigned MDString Metadata* llvm::DITemplateValueParameter::Type
Definition at line 1715 of file DebugInfoMetadata.h.
unsigned MDString Metadata Metadata llvm::DITemplateValueParameter::Type
Definition at line 1715 of file DebugInfoMetadata.h.
unsigned MDString Metadata Metadata* llvm::DITemplateValueParameter::Value
Definition at line 1715 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
DebugInfoMetadata.h
DebugInfoMetadata.cpp