LLVM: llvm::MCAsmParserExtension Class Reference
llvm::MCAsmParserExtension Class Reference
Generic interface for extending the MCAsmParser, which is implemented by target and object file assembly parser implementations.
#include <MCAsmParserExtension.h>
Public Member Functions
virtual ~MCAsmParserExtension ()
virtual void Initialize (MCAsmParser &Parser)
Initialize the extension for parsing using the given Parser.
MCAsmParser Proxy Interfaces
MCContext & getContext ()
MCAsmLexer & getLexer ()
const MCAsmLexer & getLexer () const
MCAsmParser & getParser ()
const MCAsmParser & getParser () const
SourceMgr & getSourceManager ()
MCStreamer & getStreamer ()
bool Warning (SMLoc L, const Twine &Msg)
bool Error (SMLoc L, const Twine &Msg)
bool TokError (const Twine &Msg)
const AsmToken & Lex ()
const AsmToken & getTok ()
bool HasBracketExpressions () const
Protected Member Functions
MCAsmParserExtension ()
Static Protected Member Functions
template<typename T , bool(T::*)(StringRef, SMLoc) Handler>
static bool HandleDirective (MCAsmParserExtension *Target, StringRef Directive, SMLoc DirectiveLoc)
Protected Attributes
bool BracketExpressionsSupported
Detailed Description
Generic interface for extending the MCAsmParser, which is implemented by target and object file assembly parser implementations.
Definition at line 23 of file MCAsmParserExtension.h.
Constructor & Destructor Documentation
MCAsmParserExtension::MCAsmParserExtension () [protected]
Definition at line 13 of file MCAsmParserExtension.cpp.
MCAsmParserExtension::~MCAsmParserExtension () [virtual]
Definition at line 17 of file MCAsmParserExtension.cpp.
Member Function Documentation
bool llvm::MCAsmParserExtension::Error (SMLoc L, const Twine & Msg) [inline]
Definition at line 71 of file MCAsmParserExtension.h.
References llvm::MCAsmParser::Error(), and getParser().
MCContext& llvm::MCAsmParserExtension::getContext () [inline]
Definition at line 54 of file MCAsmParserExtension.h.
References llvm::MCAsmParser::getContext(), and getParser().
MCAsmLexer& llvm::MCAsmParserExtension::getLexer () [inline]
Definition at line 56 of file MCAsmParserExtension.h.
References llvm::MCAsmParser::getLexer(), and getParser().
Referenced by getLexer().
const MCAsmLexer& llvm::MCAsmParserExtension::getLexer () const [inline]
Definition at line 57 of file MCAsmParserExtension.h.
References getLexer().
MCAsmParser& llvm::MCAsmParserExtension::getParser () [inline]
Definition at line 61 of file MCAsmParserExtension.h.
Referenced by Error(), getContext(), getLexer(), getParser(), getSourceManager(), getStreamer(), getTok(), Lex(), TokError(), and Warning().
const MCAsmParser& llvm::MCAsmParserExtension::getParser () const [inline]
Definition at line 62 of file MCAsmParserExtension.h.
References getParser().
SourceMgr& llvm::MCAsmParserExtension::getSourceManager () [inline]
Definition at line 66 of file MCAsmParserExtension.h.
References getParser(), and llvm::MCAsmParser::getSourceManager().
MCStreamer& llvm::MCAsmParserExtension::getStreamer () [inline]
Definition at line 67 of file MCAsmParserExtension.h.
References getParser(), and llvm::MCAsmParser::getStreamer().
const AsmToken& llvm::MCAsmParserExtension::getTok () [inline]
Definition at line 80 of file MCAsmParserExtension.h.
References getParser(), and llvm::MCAsmParser::getTok().
template<typename T , bool(T::*)(StringRef, SMLoc) Handler> static bool llvm::MCAsmParserExtension::HandleDirective (MCAsmParserExtension * Target, StringRef Directive, SMLoc DirectiveLoc) [inline, static, protected]
Definition at line 34 of file MCAsmParserExtension.h.
bool llvm::MCAsmParserExtension::HasBracketExpressions () const [inline]
Definition at line 82 of file MCAsmParserExtension.h.
References BracketExpressionsSupported.
void MCAsmParserExtension::Initialize (MCAsmParser & Parser) [virtual]
Initialize the extension for parsing using the given Parser.
The extension should use the AsmParser interfaces to register its parsing routines.
Definition at line 20 of file MCAsmParserExtension.cpp.
Referenced by llvm::MCAsmParser::setTargetParser().
const AsmToken& llvm::MCAsmParserExtension::Lex () [inline]
Definition at line 78 of file MCAsmParserExtension.h.
References getParser(), and llvm::MCAsmParser::Lex().
bool llvm::MCAsmParserExtension::TokError (const Twine & Msg) [inline]
Definition at line 74 of file MCAsmParserExtension.h.
References getParser(), and llvm::MCAsmParser::TokError().
bool llvm::MCAsmParserExtension::Warning (SMLoc L, const Twine & Msg) [inline]
Definition at line 68 of file MCAsmParserExtension.h.
References getParser(), and llvm::MCAsmParser::Warning().
Member Data Documentation
bool llvm::MCAsmParserExtension::BracketExpressionsSupported [protected]
Definition at line 41 of file MCAsmParserExtension.h.
Referenced by HasBracketExpressions().
The documentation for this class was generated from the following files:
MCAsmParserExtension.h
MCAsmParserExtension.cpp