LLVM: llvm::DIVariable Class Reference
llvm::DIVariable Class Reference
Base class for variables.
#include <DebugInfoMetadata.h>
Public Member Functions
unsigned getLine () const
DIScope * getScope () const
StringRef getName () const
DIFile * getFile () const
DITypeRef getType () const
StringRef getFilename () const
StringRef getDirectory () const
Metadata * getRawScope () const
MDString * getRawName () const
Metadata * getRawFile () const
Metadata * getRawType () const
Static Public Member Functions
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
DIVariable (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, unsigned Line, ArrayRef< Metadata * > Ops)
~DIVariable ()
Detailed Description
Base class for variables.
TODO: Hardcode to DW_TAG_variable.
Definition at line 1731 of file DebugInfoMetadata.h.
Constructor & Destructor Documentation
llvm::DIVariable::DIVariable (LLVMContext & C, unsigned ID, StorageType Storage, unsigned Tag, unsigned Line, ArrayRef< Metadata * > Ops) [inline, protected]
Definition at line 1735 of file DebugInfoMetadata.h.
llvm::DIVariable::~DIVariable () [protected]
Member Function Documentation
static bool llvm::DIVariable::classof (const Metadata * MD) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::DINode.
Reimplemented in llvm::DILocalVariable, and llvm::DIGlobalVariable.
Definition at line 1763 of file DebugInfoMetadata.h.
References llvm::Metadata::DIGlobalVariableKind, llvm::Metadata::DILocalVariableKind, and llvm::Metadata::getMetadataID().
StringRef llvm::DIVariable::getDirectory () const [inline]
Definition at line 1752 of file DebugInfoMetadata.h.
References F(), and getFile().
Referenced by llvm::DwarfUnit::addSourceLine().
DIFile* llvm::DIVariable::getFile () const [inline]
Definition at line 1744 of file DebugInfoMetadata.h.
References getRawFile().
Referenced by getDirectory(), getFilename(), WriteDIGlobalVariable(), and WriteDILocalVariable().
StringRef llvm::DIVariable::getFilename () const [inline]
Definition at line 1747 of file DebugInfoMetadata.h.
References F(), and getFile().
Referenced by llvm::DwarfUnit::addSourceLine().
unsigned llvm::DIVariable::getLine () const [inline]
Definition at line 1741 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfUnit::addSourceLine(), llvm::MDNodeKeyImpl< DIGlobalVariable >::isKeyOf(), llvm::MDNodeKeyImpl< DILocalVariable >::isKeyOf(), printExtendedName(), WriteDIGlobalVariable(), and WriteDILocalVariable().
StringRef llvm::DIVariable::getName () const [inline]
Definition at line 1743 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
Referenced by emitDebugValueComment(), llvm::DbgVariable::getName(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), llvm::MDNodeKeyImpl< DIGlobalVariable >::isKeyOf(), llvm::MDNodeKeyImpl< DILocalVariable >::isKeyOf(), and printExtendedName().
Metadata* llvm::DIVariable::getRawFile () const [inline]
Definition at line 1760 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getFile(), llvm::MDNodeKeyImpl< DIGlobalVariable >::isKeyOf(), and llvm::MDNodeKeyImpl< DILocalVariable >::isKeyOf().
MDString* llvm::DIVariable::getRawName () const [inline]
Definition at line 1759 of file DebugInfoMetadata.h.
Referenced by WriteDIGlobalVariable(), and WriteDILocalVariable().
Metadata* llvm::DIVariable::getRawScope () const [inline]
Definition at line 1758 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getScope(), llvm::MDNodeKeyImpl< DIGlobalVariable >::isKeyOf(), and llvm::MDNodeKeyImpl< DILocalVariable >::isKeyOf().
Metadata* llvm::DIVariable::getRawType () const [inline]
Definition at line 1761 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getType(), getVariableSize(), llvm::MDNodeKeyImpl< DIGlobalVariable >::isKeyOf(), and llvm::MDNodeKeyImpl< DILocalVariable >::isKeyOf().
DIScope* llvm::DIVariable::getScope () const [inline]
Reimplemented in llvm::DILocalVariable.
Definition at line 1742 of file DebugInfoMetadata.h.
References getRawScope().
Referenced by llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), and WriteDIGlobalVariable().
DITypeRef llvm::DIVariable::getType () const [inline]
Definition at line 1745 of file DebugInfoMetadata.h.
References getRawType().
Referenced by llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), llvm::DbgVariable::getType(), llvm::DbgVariable::isBlockByrefVariable(), WriteDIGlobalVariable(), and WriteDILocalVariable().
The documentation for this class was generated from the following file:
DebugInfoMetadata.h