LLVM: llvm::GCOVFile Class Reference
llvm::GCOVFile Class Reference
GCOVFile - Collects coverage information for one pair of coverage file (.gcno and .gcda).
#include <GCOV.h>
Public Member Functions
GCOVFile ()
bool readGCNO (GCOVBuffer &Buffer)
readGCNO - Read GCNO buffer.
bool readGCDA (GCOVBuffer &Buffer)
readGCDA - Read GCDA buffer.
uint32_t getChecksum () const
void dump () const
dump - Dump GCOVFile content to dbgs() for debugging purposes.
void collectLineCounts (FileInfo &FI)
collectLineCounts - Collect line counts.
Detailed Description
GCOVFile - Collects coverage information for one pair of coverage file (.gcno and .gcda).
Definition at line 227 of file GCOV.h.
Constructor & Destructor Documentation
llvm::GCOVFile::GCOVFile () [inline]
Definition at line 229 of file GCOV.h.
Member Function Documentation
void GCOVFile::collectLineCounts (FileInfo & FI)
collectLineCounts - Collect line counts.
This must be used after reading .gcno and .gcda files.
Definition at line 114 of file GCOV.cpp.
References llvm::FileInfo::setProgramCount(), and llvm::FileInfo::setRunCount().
void GCOVFile::dump () const
dump - Dump GCOVFile content to dbgs() for debugging purposes.
Definition at line 107 of file GCOV.cpp.
uint32_t llvm::GCOVFile::getChecksum () const [inline]
Definition at line 234 of file GCOV.h.
Referenced by llvm::GCOVFunction::readGCDA(), and llvm::GCOVFunction::readGCNO().
bool GCOVFile::readGCDA (GCOVBuffer & Buffer)
readGCDA - Read GCDA buffer.
It is required that readGCDA() can only be called after readGCNO().
Definition at line 54 of file GCOV.cpp.
References llvm::GCOVBuffer::advanceCursor(), llvm::NVPTXISD::Dummy, llvm::errs(), llvm::GCOVBuffer::readFunctionTag(), llvm::GCOVBuffer::readGCDAFormat(), llvm::GCOVBuffer::readGCOVVersion(), llvm::GCOVBuffer::readInt(), llvm::GCOVBuffer::readObjectTag(), llvm::GCOVBuffer::readProgramTag(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::IndexedInstrProf::Version.
bool GCOVFile::readGCNO (GCOVBuffer & Buffer)
readGCNO - Read GCNO buffer.
Definition at line 31 of file GCOV.cpp.
References llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::GCOVBuffer::readFunctionTag(), llvm::GCOVBuffer::readGCNOFormat(), llvm::GCOVBuffer::readGCOVVersion(), llvm::GCOVBuffer::readInt(), and llvm::IndexedInstrProf::Version.
The documentation for this class was generated from the following files:
GCOV.h
GCOV.cpp