LLVM: llvm::ilist_node< NodeTy > Class Template Reference
llvm::ilist_node< NodeTy > Class Template Reference
ilist_node - Base class that provides next/prev services for nodes that use ilist_nextprev_traits or ilist_default_traits.
#include <ilist_node.h>
Public Member Functions
Adjacent Node Accessors
NodeTy * getPrevNode ()
Get the previous node, or 0 for the list head.
const NodeTy * getPrevNode () const
Get the previous node, or 0 for the list head.
NodeTy * getNextNode ()
Get the next node, or 0 for the list tail.
const NodeTy * getNextNode () const
Get the next node, or 0 for the list tail.
Protected Member Functions
ilist_node ()
Friends
struct ilist_nextprev_traits< NodeTy >
struct ilist_traits< NodeTy >
Detailed Description
template<typename NodeTy>
class llvm::ilist_node< NodeTy >
ilist_node - Base class that provides next/prev services for nodes that use ilist_nextprev_traits or ilist_default_traits.
Definition at line 43 of file ilist_node.h.
Constructor & Destructor Documentation
template<typename NodeTy> llvm::ilist_node< NodeTy >::ilist_node () [inline, protected]
Definition at line 51 of file ilist_node.h.
Member Function Documentation
template<typename NodeTy> NodeTy* llvm::ilist_node< NodeTy >::getNextNode () [inline]
Get the next node, or 0 for the list tail.
Definition at line 80 of file ilist_node.h.
Referenced by insertRelocationStores(), matchOutlinedFinallyCall(), rematerializeLiveValues(), llvm::SCEVExpander::replaceCongruentIVs(), ReplaceWithStatepoint(), and simplifyRelocatesOffABase().
template<typename NodeTy> const NodeTy* llvm::ilist_node< NodeTy >::getNextNode () const [inline]
Get the next node, or 0 for the list tail.
Definition at line 91 of file ilist_node.h.
template<typename NodeTy> NodeTy* llvm::ilist_node< NodeTy >::getPrevNode () [inline]
Get the previous node, or 0 for the list head.
Definition at line 58 of file ilist_node.h.
Referenced by findBeginCatchSplitPoint(), llvm::BasicBlock::getTerminatingMustTailCall(), llvm::MCAsmLayout::invalidateFragmentsFrom(), llvm::MCAsmLayout::layoutFragment(), and PrevCrossBBInst().
template<typename NodeTy> const NodeTy* llvm::ilist_node< NodeTy >::getPrevNode () const [inline]
Get the previous node, or 0 for the list head.
Definition at line 69 of file ilist_node.h.
Friends And Related Function Documentation
template<typename NodeTy> friend struct ilist_nextprev_traits< NodeTy > [friend]
Definition at line 44 of file ilist_node.h.
template<typename NodeTy> friend struct ilist_traits< NodeTy > [friend]
Reimplemented from llvm::ilist_half_node< NodeTy >.
Definition at line 45 of file ilist_node.h.
The documentation for this class was generated from the following file:
ilist_node.h