LLVM: llvm::NVPTXTTIImpl Class Reference
llvm::NVPTXTTIImpl Class Reference
#include <NVPTXTargetTransformInfo.h>
Public Member Functions
NVPTXTTIImpl (const NVPTXTargetMachine *TM)
NVPTXTTIImpl (const NVPTXTTIImpl &Arg)
NVPTXTTIImpl (NVPTXTTIImpl &&Arg)
NVPTXTTIImpl & operator= (const NVPTXTTIImpl &RHS)
NVPTXTTIImpl & operator= (NVPTXTTIImpl &&RHS)
bool hasBranchDivergence ()
bool isSourceOfDivergence (const Value *V)
unsigned getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::OperandValueKind Opd1Info=TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info=TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo=TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo=TTI::OP_None)
Detailed Description
Definition at line 28 of file NVPTXTargetTransformInfo.h.
Constructor & Destructor Documentation
llvm::NVPTXTTIImpl::NVPTXTTIImpl (const NVPTXTargetMachine * TM) [inline, explicit]
Definition at line 40 of file NVPTXTargetTransformInfo.h.
llvm::NVPTXTTIImpl::NVPTXTTIImpl (const NVPTXTTIImpl & Arg) [inline]
Definition at line 44 of file NVPTXTargetTransformInfo.h.
llvm::NVPTXTTIImpl::NVPTXTTIImpl (NVPTXTTIImpl && Arg) [inline]
Definition at line 46 of file NVPTXTargetTransformInfo.h.
Member Function Documentation
unsigned NVPTXTTIImpl::getArithmeticInstrCost (unsigned Opcode, Type * Ty, TTI::OperandValueKind Opd1Info = TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info = TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo = TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo = TTI::OP_None)
Reimplemented from llvm::BasicTTIImplBase< NVPTXTTIImpl >.
Definition at line 92 of file NVPTXTargetTransformInfo.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::BasicTTIImplBase< NVPTXTTIImpl >::getArithmeticInstrCost(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::MVT::i64, llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::AArch64CC::LT, llvm::ISD::MUL, llvm::ISD::OR, and llvm::ISD::XOR.
bool llvm::NVPTXTTIImpl::hasBranchDivergence () [inline]
Reimplemented from llvm::BasicTTIImplBase< NVPTXTTIImpl >.
Definition at line 62 of file NVPTXTargetTransformInfo.h.
bool NVPTXTTIImpl::isSourceOfDivergence (const Value * V)
Reimplemented from llvm::BasicTTIImplBase< NVPTXTTIImpl >.
Definition at line 49 of file NVPTXTargetTransformInfo.cpp.
References llvm::ADDRESS_SPACE_GENERIC, llvm::ADDRESS_SPACE_LOCAL, I, llvm::isKernelFunction(), isNVVMAtomic(), readsLaneId(), and readsThreadIndex().
NVPTXTTIImpl& llvm::NVPTXTTIImpl::operator= (const NVPTXTTIImpl & RHS) [inline]
Definition at line 49 of file NVPTXTargetTransformInfo.h.
References llvm::BasicTTIImplBase< NVPTXTTIImpl >::operator=().
NVPTXTTIImpl& llvm::NVPTXTTIImpl::operator= (NVPTXTTIImpl && RHS) [inline]
Definition at line 55 of file NVPTXTargetTransformInfo.h.
References llvm::BasicTTIImplBase< NVPTXTTIImpl >::operator=().
The documentation for this class was generated from the following files:
NVPTXTargetTransformInfo.h
NVPTXTargetTransformInfo.cpp