LLVM: llvm::MCObjectWriter Class Reference
llvm::MCObjectWriter Class Reference
Defines the object file and target independent interfaces used by the assembler backend to write native file format object files.
#include <MCObjectWriter.h>
Public Member Functions
virtual ~MCObjectWriter ()
virtual void reset ()
lifetime management
bool isLittleEndian () const
raw_ostream & getStream ()
void write8 (uint8_t Value)
void writeLE16 (uint16_t Value)
void writeLE32 (uint32_t Value)
void writeLE64 (uint64_t Value)
void writeBE16 (uint16_t Value)
void writeBE32 (uint32_t Value)
void writeBE64 (uint64_t Value)
void write16 (uint16_t Value)
void write32 (uint32_t Value)
void write64 (uint64_t Value)
void WriteZeros (unsigned N)
void writeBytes (const SmallVectorImpl< char > &ByteVec, unsigned ZeroFillSize=0)
void writeBytes (StringRef Str, unsigned ZeroFillSize=0)
High-Level API
virtual void executePostLayoutBinding (MCAssembler &Asm, const MCAsmLayout &Layout)=0
Perform any late binding of symbols (for example, to assign symbol indices for use when generating relocations).
virtual void recordRelocation (MCAssembler &Asm, const MCAsmLayout &Layout, const MCFragment *Fragment, const MCFixup &Fixup, MCValue Target, bool &IsPCRel, uint64_t &FixedValue)=0
Record a relocation entry.
bool isSymbolRefDifferenceFullyResolved (const MCAssembler &Asm, const MCSymbolRefExpr *A, const MCSymbolRefExpr *B, bool InSet) const
Check whether the difference (A - B) between two symbol references is fully resolved.
virtual bool isSymbolRefDifferenceFullyResolvedImpl (const MCAssembler &Asm, const MCSymbol &SymA, const MCFragment &FB, bool InSet, bool IsPCRel) const
virtual bool isWeak (const MCSymbol &Sym) const
True if this symbol (which is a variable) is weak.
virtual void writeObject (MCAssembler &Asm, const MCAsmLayout &Layout)=0
Write the object file.
Protected Member Functions
MCObjectWriter (raw_pwrite_stream &OS, bool IsLittleEndian)
Protected Attributes
raw_pwrite_stream & OS
unsigned IsLittleEndian: 1
Detailed Description
Defines the object file and target independent interfaces used by the assembler backend to write native file format object files.
The object writer contains a few callbacks used by the assembler to allow the object writer to modify the assembler data structures at appropriate points. Once assembly is complete, the object writer is given the MCAssembler instance, which contains all the symbol and section data which should be emitted as part of writeObject().
The object writer also contains a number of helper methods for writing binary data to the output stream.
Definition at line 39 of file MCObjectWriter.h.
Constructor & Destructor Documentation
llvm::MCObjectWriter::MCObjectWriter (raw_pwrite_stream & OS, bool IsLittleEndian) [inline, protected]
Definition at line 49 of file MCObjectWriter.h.
MCObjectWriter::~MCObjectWriter () [virtual]
Definition at line 17 of file MCObjectWriter.cpp.
Member Function Documentation
virtual void llvm::MCObjectWriter::executePostLayoutBinding (MCAssembler & Asm, const MCAsmLayout & Layout) [pure virtual]
Perform any late binding of symbols (for example, to assign symbol indices for use when generating relocations).
This routine is called by the assembler after layout and relaxation is complete.
Implemented in llvm::MachObjectWriter.
Referenced by llvm::MCAssembler::Finish().
raw_ostream& llvm::MCObjectWriter::getStream () [inline]
Definition at line 60 of file MCObjectWriter.h.
References OS.
Referenced by llvm::MCLOHDirective::emit(), writeFragment(), and llvm::MCAssembler::writeSectionData().
bool llvm::MCObjectWriter::isLittleEndian () const [inline]
Definition at line 58 of file MCObjectWriter.h.
References IsLittleEndian.
bool MCObjectWriter::isSymbolRefDifferenceFullyResolved (const MCAssembler & Asm, const MCSymbolRefExpr * A, const MCSymbolRefExpr * B, bool InSet) const
Check whether the difference (A - B) between two symbol references is fully resolved.
Clients are not required to answer precisely and may conservatively return false, even when a difference is fully resolved.
Definition at line 20 of file MCObjectWriter.cpp.
References llvm::MCSymbol::getFragment(), llvm::MCSymbolRefExpr::getKind(), llvm::MCSymbolRefExpr::getSymbol(), isSymbolRefDifferenceFullyResolvedImpl(), llvm::MCSymbol::isUndefined(), and llvm::MCSymbolRefExpr::VK_None.
bool MCObjectWriter::isSymbolRefDifferenceFullyResolvedImpl (const MCAssembler & Asm, const MCSymbol & SymA, const MCFragment & FB, bool InSet, bool IsPCRel) const [virtual]
Reimplemented in llvm::MachObjectWriter.
Definition at line 40 of file MCObjectWriter.cpp.
References llvm::MCFragment::getParent(), and llvm::MCSymbol::getSection().
Referenced by isSymbolRefDifferenceFullyResolved().
bool MCObjectWriter::isWeak (const MCSymbol & Sym) const [virtual]
True if this symbol (which is a variable) is weak.
This is not just STB_WEAK, but more generally whether or not we can evaluate past it.
Definition at line 49 of file MCObjectWriter.cpp.
Referenced by canExpand().
virtual void llvm::MCObjectWriter::recordRelocation (MCAssembler & Asm, const MCAsmLayout & Layout, const MCFragment * Fragment, const MCFixup & Fixup, MCValue Target, bool & IsPCRel, uint64_t & FixedValue) [pure virtual]
Record a relocation entry.
This routine is called by the assembler after layout and relaxation, and post layout binding. The implementation is responsible for storing information about the relocation so that it can be emitted during writeObject().
Implemented in llvm::MachObjectWriter.
virtual void llvm::MCObjectWriter::reset () [inline, virtual]
lifetime management
Reimplemented in llvm::MachObjectWriter.
Definition at line 56 of file MCObjectWriter.h.
Referenced by llvm::MCAssembler::reset().
void llvm::MCObjectWriter::write16 (uint16_t Value) [inline]
Definition at line 140 of file MCObjectWriter.h.
Referenced by writeFragment(), llvm::MachObjectWriter::writeNlist(), and llvm::MachObjectWriter::writeObject().
void llvm::MCObjectWriter::write32 (uint32_t Value) [inline]
Definition at line 147 of file MCObjectWriter.h.
Referenced by llvm::MachObjectWriter::writeDysymtabLoadCommand(), writeFragment(), llvm::MachObjectWriter::writeHeader(), llvm::MachObjectWriter::writeLinkeditLoadCommand(), llvm::MachObjectWriter::writeLinkerOptionsLoadCommand(), llvm::MachObjectWriter::writeNlist(), llvm::MachObjectWriter::writeObject(), llvm::MachObjectWriter::writeSection(), llvm::MachObjectWriter::writeSegmentLoadCommand(), and llvm::MachObjectWriter::writeSymtabLoadCommand().
void llvm::MCObjectWriter::write64 (uint64_t Value) [inline]
Definition at line 154 of file MCObjectWriter.h.
Referenced by writeFragment(), llvm::MachObjectWriter::writeNlist(), llvm::MachObjectWriter::writeSection(), and llvm::MachObjectWriter::writeSegmentLoadCommand().
void llvm::MCObjectWriter::write8 (uint8_t Value) [inline]
Definition at line 114 of file MCObjectWriter.h.
Referenced by writeFragment(), and llvm::MachObjectWriter::writeNlist().
void llvm::MCObjectWriter::writeBE16 (uint16_t Value) [inline]
Definition at line 128 of file MCObjectWriter.h.
void llvm::MCObjectWriter::writeBE32 (uint32_t Value) [inline]
Definition at line 132 of file MCObjectWriter.h.
void llvm::MCObjectWriter::writeBE64 (uint64_t Value) [inline]
Definition at line 136 of file MCObjectWriter.h.
void llvm::MCObjectWriter::writeBytes (const SmallVectorImpl< char > & ByteVec, unsigned ZeroFillSize = 0) [inline]
Definition at line 170 of file MCObjectWriter.h.
Referenced by writeFragment(), llvm::MachObjectWriter::writeLinkerOptionsLoadCommand(), llvm::MachObjectWriter::writeObject(), llvm::MachObjectWriter::writeSection(), and llvm::MachObjectWriter::writeSegmentLoadCommand().
void llvm::MCObjectWriter::writeBytes (StringRef Str, unsigned ZeroFillSize = 0) [inline]
Definition at line 175 of file MCObjectWriter.h.
void llvm::MCObjectWriter::writeLE16 (uint16_t Value) [inline]
Definition at line 116 of file MCObjectWriter.h.
References OS.
void llvm::MCObjectWriter::writeLE32 (uint32_t Value) [inline]
Definition at line 120 of file MCObjectWriter.h.
void llvm::MCObjectWriter::writeLE64 (uint64_t Value) [inline]
Definition at line 124 of file MCObjectWriter.h.
virtual void llvm::MCObjectWriter::writeObject (MCAssembler & Asm, const MCAsmLayout & Layout) [pure virtual]
Write the object file.
This routine is called by the assembler after layout and relaxation is complete, fixups have been evaluated and applied, and relocations generated.
Implemented in llvm::MachObjectWriter.
Referenced by llvm::MCAssembler::Finish().
void llvm::MCObjectWriter::WriteZeros (unsigned N) [inline]
Definition at line 161 of file MCObjectWriter.h.
Referenced by llvm::MipsAsmBackend::writeNopData(), and llvm::MachObjectWriter::writeObject().
Member Data Documentation
unsigned llvm::MCObjectWriter::IsLittleEndian [protected]
Definition at line 46 of file MCObjectWriter.h.
Referenced by llvm::MachObjectWriter::computeSymbolTable(), and isLittleEndian().
raw_pwrite_stream& llvm::MCObjectWriter::OS [protected]
Definition at line 44 of file MCObjectWriter.h.
Referenced by getStream(), llvm::MachObjectWriter::writeDysymtabLoadCommand(), llvm::MachObjectWriter::writeHeader(), writeLE16(), llvm::MachObjectWriter::writeLinkeditLoadCommand(), llvm::MachObjectWriter::writeLinkerOptionsLoadCommand(), llvm::MachObjectWriter::writeObject(), llvm::MachObjectWriter::writeSection(), llvm::MachObjectWriter::writeSegmentLoadCommand(), and llvm::MachObjectWriter::writeSymtabLoadCommand().
The documentation for this class was generated from the following files:
MCObjectWriter.h
MCObjectWriter.cpp