LLVM: llvm::IntToPtrInst Class Reference
llvm::IntToPtrInst Class Reference
This class represents a cast from an integer to a pointer.
#include <Instructions.h>
Public Member Functions
IntToPtrInst (Value *S, Type *Ty, const Twine &NameStr="", Instruction *InsertBefore=nullptr)
Constructor with insert-before-instruction semantics.
IntToPtrInst (Value *S, Type *Ty, const Twine &NameStr, BasicBlock *InsertAtEnd)
Constructor with insert-at-end-of-block semantics.
IntToPtrInst * clone_impl () const override
Clone an identical IntToPtrInst.
unsigned getAddressSpace () const
Returns the address space of this instruction's pointer type.
Static Public Member Functions
static bool classof (const Instruction *I)
Methods for support type inquiry through isa, cast, and dyn_cast:
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Detailed Description
This class represents a cast from an integer to a pointer.
Definition at line 3830 of file Instructions.h.
Constructor & Destructor Documentation
IntToPtrInst::IntToPtrInst (Value * S, Type * Ty, const Twine & NameStr = "", Instruction * InsertBefore = nullptr)
Constructor with insert-before-instruction semantics.
Parameters:
S The value to be converted
Ty The type to convert to
NameStr A name for the new instruction
InsertBefore Where to insert the new instruction
Definition at line 2929 of file Instructions.cpp.
References llvm::CastInst::castIsValid(), and llvm::CastInst::getOpcode().
Referenced by clone_impl().
IntToPtrInst::IntToPtrInst (Value * S, Type * Ty, const Twine & NameStr, BasicBlock * InsertAtEnd)
Constructor with insert-at-end-of-block semantics.
Parameters:
S The value to be converted
Ty The type to convert to
NameStr A name for the new instruction
InsertAtEnd The block to insert the instruction into
Definition at line 2935 of file Instructions.cpp.
References llvm::CastInst::castIsValid(), and llvm::CastInst::getOpcode().
Member Function Documentation
static bool llvm::IntToPtrInst::classof (const Instruction * I) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::CastInst.
Definition at line 3857 of file Instructions.h.
References llvm::Instruction::getOpcode(), and llvm::IntToPtr.
Referenced by classof().
static bool llvm::IntToPtrInst::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::CastInst.
Definition at line 3860 of file Instructions.h.
References classof().
IntToPtrInst * IntToPtrInst::clone_impl () const [override, virtual]
Clone an identical IntToPtrInst.
Implements llvm::Instruction.
Definition at line 3561 of file Instructions.cpp.
References llvm::User::getOperand(), llvm::Value::getType(), and IntToPtrInst().
unsigned llvm::IntToPtrInst::getAddressSpace () const [inline]
Returns the address space of this instruction's pointer type.
Definition at line 3852 of file Instructions.h.
References llvm::Type::getPointerAddressSpace(), and llvm::Value::getType().
Referenced by llvm::InstCombiner::visitIntToPtr().
The documentation for this class was generated from the following files:
Instructions.h
Instructions.cpp