LLVM: llvm::X86FrameLowering Class Reference
llvm::X86FrameLowering Class Reference
#include <X86FrameLowering.h>
Public Member Functions
X86FrameLowering (const X86Subtarget &STI, unsigned StackAlignOverride)
void emitStackProbeCall (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, DebugLoc DL) const
Emit a call to the target's stack probe function.
void emitCalleeSavedFrameMoves (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, DebugLoc DL) const
void emitPrologue (MachineFunction &MF, MachineBasicBlock &MBB) const override
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const override
void adjustForSegmentedStacks (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const override
Adjust the prologue to have the function use segmented stacks.
void adjustForHiPEPrologue (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const override
Erlang programs may need a special prologue to handle the stack size they might need at runtime.
void processFunctionBeforeCalleeSavedScan (MachineFunction &MF, RegScavenger *RS=nullptr) const override
processFunctionBeforeCalleeSavedScan - This method is called immediately before PrologEpilogInserter scans the physical registers used to determine what callee saved registers should be spilled.
bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI) const override
assignCalleeSavedSpillSlots - Allows target to override spill slot assignment logic.
bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const override
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const override
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
bool hasFP (const MachineFunction &MF) const override
hasFP - Return true if the specified function should have a dedicated frame pointer register.
bool hasReservedCallFrame (const MachineFunction &MF) const override
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
bool canSimplifyCallFramePseudos (const MachineFunction &MF) const override
canSimplifyCallFramePseudos - If there is a reserved call frame, the call frame pseudos can be simplified.
bool needsFrameIndexResolution (const MachineFunction &MF) const override
int getFrameIndexOffset (const MachineFunction &MF, int FI) const override
getFrameIndexOffset - Returns the displacement from the frame register to the stack frame of the specified index.
int getFrameIndexReference (const MachineFunction &MF, int FI, unsigned &FrameReg) const override
getFrameIndexReference - This method should return the base register and offset used to reference a frame index location.
int getFrameIndexOffsetFromSP (const MachineFunction &MF, int FI) const
int getFrameIndexReferenceFromSP (const MachineFunction &MF, int FI, unsigned &FrameReg) const override
Same as above, except that the 'base register' will always be RSP, not RBP on x86.
void eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MI) const override
eliminateCallFramePseudoInstr - This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
int mergeSPUpdates (MachineBasicBlock &MBB, MachineBasicBlock::iterator &MBBI, bool doMergeWithPrevious) const
Check the instruction before/after the passed instruction.
void emitSPUpdate (MachineBasicBlock &MBB, MachineBasicBlock::iterator &MBBI, int64_t NumBytes, bool InEpilogue) const
Emit a series of instructions to increment / decrement the stack pointer by a constant value.
bool canUseLEAForSPInEpilogue (const MachineFunction &MF) const
Check that LEA can be used on SP in an epilogue sequence for MF.
bool canUseAsEpilogue (const MachineBasicBlock &MBB) const override
Check whether or not the given MBB can be used as a epilogue for the target.
Public Attributes
const X86Subtarget & STI
const TargetInstrInfo & TII
const X86RegisterInfo * TRI
unsigned SlotSize
bool Is64Bit
Is64Bit implies that x86_64 instructions are available.
bool IsLP64
bool Uses64BitFramePtr
True if the 64-bit frame or stack pointer should be used.
unsigned StackPtr
Detailed Description
Definition at line 26 of file X86FrameLowering.h.
Constructor & Destructor Documentation
X86FrameLowering::X86FrameLowering (const X86Subtarget & STI, unsigned StackAlignOverride)
Definition at line 40 of file X86FrameLowering.cpp.
References Is64Bit, IsLP64, SlotSize, StackPtr, TRI, and Uses64BitFramePtr.
Member Function Documentation
void X86FrameLowering::adjustForHiPEPrologue (MachineFunction & MF, MachineBasicBlock & PrologueMBB) const [override, virtual]
Erlang programs may need a special prologue to handle the stack size they might need at runtime.
That is because Erlang/OTP does not implement a C stack but uses a custom implementation of hybrid stack/heap architecture. (for more information see Eric Stenman's Ph.D. thesis: http://publications.uu.se/uu/fulltext/nbn_se_uu_diva-2688.pdf)
CheckStack: temp0 = sp - MaxStack if(temp0 < SP_LIMIT(P)) goto IncStack else goto OldStart OldStart: ... IncStack: call inc_stack # doubles the stack space temp0 = sp - MaxStack if(temp0 < SP_LIMIT(P)) goto IncStack else goto OldStart
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1741 of file X86FrameLowering.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::addRegOffset(), llvm::MachineBasicBlock::addSuccessor(), llvm::Function::arg_size(), llvm::MachineFunction::begin(), llvm::BuildMI(), llvm::MachineFunction::CreateMachineBasicBlock(), llvm::DL, llvm::dyn_cast(), llvm::EBP, llvm::MachineFunction::end(), llvm::ESP, F(), llvm::StringRef::find(), llvm::StringRef::find_first_of(), llvm::MCInstrInfo::get(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getGlobal(), llvm::Value::getName(), llvm::MachineInstr::getOperand(), llvm::MachineFunction::getRegInfo(), GetScratchRegister(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFrameInfo::hasCalls(), I, Is64Bit, llvm::MachineInstr::isCall(), llvm::MachineOperand::isGlobal(), llvm::MachineRegisterInfo::isLiveIn(), IsLP64, llvm::MachineBasicBlock::livein_begin(), llvm::MachineBasicBlock::livein_end(), llvm::AArch64CC::MI, llvm::StringRef::npos, llvm::MachineFunction::push_front(), llvm::RBP, llvm::RSP, SlotSize, STI, TII, and llvm::MachineFunction::verify().
void X86FrameLowering::adjustForSegmentedStacks (MachineFunction & MF, MachineBasicBlock & PrologueMBB) const [override, virtual]
Adjust the prologue to have the function use segmented stacks.
This works by adding a check even before the "normal" function prologue.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1494 of file X86FrameLowering.cpp.
References llvm::MachineInstrBuilder::addExternalSymbol(), llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), llvm::BuildMI(), llvm::MachineFunction::CreateMachineBasicBlock(), llvm::DL, llvm::EAX, llvm::ESP, llvm::FS, llvm::MCInstrInfo::get(), llvm::X86MachineFunctionInfo::getArgumentStackSize(), llvm::TargetMachine::getCodeModel(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getMMI(), llvm::MachineFunction::getRegInfo(), GetScratchRegister(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getTarget(), llvm::GS, HasNestArgument(), Is64Bit, llvm::MachineRegisterInfo::isLiveIn(), IsLP64, llvm::Function::isVarArg(), llvm::RegState::Kill, kSplitStackAvailable, llvm::CodeModel::Large, llvm::MachineBasicBlock::livein_begin(), llvm::MachineBasicBlock::livein_end(), llvm::MachineFunction::push_front(), llvm::R10, llvm::R11, llvm::RAX, llvm::report_fatal_error(), llvm::RSP, llvm::MachineRegisterInfo::setPhysRegUsed(), llvm::MachineModuleInfo::setUsesMorestackAddr(), STI, TII, and llvm::MachineFunction::verify().
bool X86FrameLowering::assignCalleeSavedSpillSlots (MachineFunction & MF, const TargetRegisterInfo * TRI, std::vector< CalleeSavedInfo > & CSI) const [override, virtual]
assignCalleeSavedSpillSlots - Allows target to override spill slot assignment logic.
If implemented, assignCalleeSavedSpillSlots() should assign frame slots to all CSI entries and return true. If this method returns false, spill slots will be assigned using generic implementation. assignCalleeSavedSpillSlots() may add, delete or rearrange elements of CSI.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1280 of file X86FrameLowering.cpp.
References llvm::abs(), contains(), llvm::MachineFrameInfo::CreateFixedSpillStackObject(), llvm::MachineFrameInfo::ensureMaxAlignment(), llvm::TargetRegisterClass::getAlignment(), llvm::MachineFunction::getFrameInfo(), llvm::TargetRegisterInfo::getFrameRegister(), llvm::MachineFunction::getInfo(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::TargetFrameLowering::getOffsetOfLocalArea(), llvm::TargetRegisterClass::getSize(), llvm::X86MachineFunctionInfo::getTCReturnAddrDelta(), hasFP(), llvm::TargetRegisterInfo::regsOverlap(), llvm::X86MachineFunctionInfo::setCalleeSavedFrameSize(), and SlotSize.
bool X86FrameLowering::canSimplifyCallFramePseudos (const MachineFunction & MF) const [override, virtual]
canSimplifyCallFramePseudos - If there is a reserved call frame, the call frame pseudos can be simplified.
Having a FP, as in the default implementation, is not sufficient here since we can't always use it. Use a more nuanced condition.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 64 of file X86FrameLowering.cpp.
References hasFP(), hasReservedCallFrame(), and TRI.
bool X86FrameLowering::canUseAsEpilogue (const MachineBasicBlock & MBB) const [override, virtual]
Check whether or not the given MBB can be used as a epilogue for the target.
The epilogue will be inserted before the first terminator of that block. This method is used by the shrink-wrapping pass to decide if MBB will be correctly handled by the target.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1918 of file X86FrameLowering.cpp.
References canUseLEAForSPInEpilogue(), llvm::MachineBasicBlock::getParent(), and terminatorsNeedFlagsAsInput().
bool X86FrameLowering::canUseLEAForSPInEpilogue (const MachineFunction & MF) const
Check that LEA can be used on SP in an epilogue sequence for MF.
Definition at line 994 of file X86FrameLowering.cpp.
References llvm::TargetMachine::getMCAsmInfo(), llvm::MachineFunction::getTarget(), hasFP(), and llvm::MCAsmInfo::usesWindowsCFI().
Referenced by canUseAsEpilogue().
void X86FrameLowering::eliminateCallFramePseudoInstr (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const [override, virtual]
eliminateCallFramePseudoInstr - This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
It is responsible for eliminating these instructions, replacing them with concrete instructions. This method need only be implemented if using call frame setup/destroy pseudo instructions.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1869 of file X86FrameLowering.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::erase(), llvm::TargetInstrInfo::getCallFrameDestroyOpcode(), llvm::TargetFrameLowering::getStackAlignment(), hasReservedCallFrame(), I, llvm::RoundUpToAlignment(), and TII.
void X86FrameLowering::emitCalleeSavedFrameMoves (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, DebugLoc DL) const
Definition at line 415 of file X86FrameLowering.cpp.
References llvm::MCCFIInstruction::createOffset(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineModuleInfo::getContext(), llvm::MCRegisterInfo::getDwarfRegNum(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getMMI(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineBasicBlock::getParent(), llvm::MCContext::getRegisterInfo(), and I.
Referenced by emitPrologue().
void X86FrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const [override, virtual]
Implements llvm::TargetFrameLowering.
Definition at line 1005 of file X86FrameLowering.cpp.
References llvm::addRegOffset(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), calculateSetFPREG(), llvm::TargetOpcode::DBG_VALUE, llvm::DL, emitSPUpdate(), llvm::MachineBasicBlock::end(), FramePtr, llvm::MCInstrInfo::get(), llvm::X86MachineFunctionInfo::getCalleeSavedFrameSize(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), getLEArOpcode(), llvm::TargetMachine::getMCAsmInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getTarget(), llvm::X86MachineFunctionInfo::getTCReturnAddrDelta(), llvm::getX86SubSuperRegister(), hasFP(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::MVT::i64, Is64Bit, mergeSPUpdates(), mergeSPUpdatesUp(), llvm::Function::needsUnwindTableEntry(), llvm::RoundUpToAlignment(), SlotSize, StackPtr, STI, TII, TRI, Uses64BitFramePtr, and llvm::MCAsmInfo::usesWindowsCFI().
void X86FrameLowering::emitPrologue (MachineFunction & MF, MachineBasicBlock & MBB) const [override, virtual]
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
emitPrologue - Push callee-saved registers onto the stack, which automatically adjust the stack pointer.
Adjust the stack pointer to allocate space for local variables. Also emit labels used by the exception handler to generate the exception handling frames.
Implements llvm::TargetFrameLowering.
Definition at line 638 of file X86FrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::addRegOffset(), llvm::MachineFrameInfo::adjustsStack(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::BuildMI(), calculateSetFPREG(), contains(), llvm::MCCFIInstruction::createDefCfaOffset(), llvm::MCCFIInstruction::createDefCfaRegister(), llvm::MCCFIInstruction::createOffset(), llvm::DL, llvm::EAX, emitCalleeSavedFrameMoves(), emitSPUpdate(), emitStackProbeCall(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), FramePtr, llvm::MachineInstr::FrameSetup, llvm::MCInstrInfo::get(), llvm::StringRef::getAsInteger(), llvm::X86MachineFunctionInfo::getCalleeSavedFrameSize(), llvm::Function::getCallingConv(), llvm::Function::getFnAttribute(), getFrameIndexOffset(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::TargetMachine::getMCAsmInfo(), llvm::MachineFunction::getMMI(), llvm::X86MachineFunctionInfo::getRestoreBasePointer(), llvm::X86MachineFunctionInfo::getRestoreBasePointerOffset(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::X86MachineFunctionInfo::getTCReturnAddrDelta(), llvm::Attribute::getValueAsString(), llvm::getX86SubSuperRegister(), llvm::MachineModuleInfo::hasDebugInfo(), llvm::Function::hasFnAttribute(), hasFP(), llvm::MachineFrameInfo::hasVarSizedObjects(), I, llvm::MVT::i64, llvm::MachineBasicBlock::insert(), Is64Bit, isEAXLiveIn(), llvm::isInt< 32 >(), llvm::TargetInstrInfo::isStoreToStackSlot(), llvm::isUInt< 32 >(), llvm::RegState::Kill, mergeSPUpdates(), llvm::Function::needsUnwindTableEntry(), llvm::Attribute::NoRedZone, llvm::RAX, llvm::report_fatal_error(), llvm::RoundUpToAlignment(), llvm::X86MachineFunctionInfo::setCalleeSavedFrameSize(), llvm::MachineInstr::setFlag(), llvm::MachineInstrBuilder::setMIFlag(), llvm::MachineFrameInfo::setOffsetAdjustment(), llvm::MachineFrameInfo::setStackSize(), llvm::MachineFunction::shouldSplitStack(), SlotSize, StackPtr, STI, TII, TRI, Uses64BitFramePtr, usesTheStack(), and llvm::MCAsmInfo::usesWindowsCFI().
void X86FrameLowering::emitSPUpdate (MachineBasicBlock & MBB, MachineBasicBlock::iterator & MBBI, int64_t NumBytes, bool InEpilogue) const
Emit a series of instructions to increment / decrement the stack pointer by a constant value.
emitSPUpdate - Emit a series of instructions to increment / decrement the stack pointer by a constant value.
Definition at line 242 of file X86FrameLowering.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::DL, llvm::EAX, findDeadCallerSavedReg(), llvm::MachineBasicBlock::findDebugLoc(), llvm::MachineInstr::FrameSetup, llvm::MCInstrInfo::get(), getADDrrOpcode(), llvm::getDefRegState(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), getSUBrrOpcode(), llvm::getUndefRegState(), Is64Bit, isEAXLiveIn(), llvm::AArch64CC::MI, fuzzer::min(), llvm::RAX, llvm::MachineInstr::setFlag(), llvm::MachineOperand::setIsDead(), llvm::MachineInstrBuilder::setMIFlag(), StackPtr, TII, and TRI.
Referenced by emitEpilogue(), and emitPrologue().
void X86FrameLowering::emitStackProbeCall (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, DebugLoc DL) const
Emit a call to the target's stack probe function.
This is required for all large stack allocations on Windows. The caller is required to materialize the number of bytes to probe in RAX/EAX.
Definition at line 456 of file X86FrameLowering.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::AX, llvm::BuildMI(), llvm::RegState::Define, llvm::EAX, llvm::ESP, llvm::MCInstrInfo::get(), llvm::TargetMachine::getCodeModel(), llvm::MachineFunction::getTarget(), llvm::RegState::Implicit, Is64Bit, llvm::CodeModel::Large, llvm::R11, llvm::RAX, llvm::RSP, llvm::SP, STI, llvm::ARMBuildAttrs::Symbol, and TII.
Referenced by emitPrologue().
int X86FrameLowering::getFrameIndexOffset (const MachineFunction & MF, int FI) const [override, virtual]
getFrameIndexOffset - Returns the displacement from the frame register to the stack frame of the specified index.
This is the default implementation which is overridden for some targets.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1124 of file X86FrameLowering.cpp.
References calculateSetFPREG(), llvm::X86MachineFunctionInfo::getCalleeSavedFrameSize(), llvm::X86MachineFunctionInfo::getFAIndex(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::TargetMachine::getMCAsmInfo(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectOffset(), llvm::TargetFrameLowering::getOffsetOfLocalArea(), llvm::X86MachineFunctionInfo::getRestoreBasePointer(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getTarget(), llvm::X86MachineFunctionInfo::getTCReturnAddrDelta(), llvm::MachineFrameInfo::hasCalls(), hasFP(), SlotSize, TRI, and llvm::MCAsmInfo::usesWindowsCFI().
Referenced by emitPrologue(), and getFrameIndexReference().
int X86FrameLowering::getFrameIndexOffsetFromSP (const MachineFunction & MF, int FI) const
Definition at line 1212 of file X86FrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFrameInfo::getObjectOffset(), llvm::TargetFrameLowering::getOffsetOfLocalArea(), llvm::MachineFrameInfo::getStackSize(), and TRI.
Referenced by getFrameIndexReferenceFromSP().
int X86FrameLowering::getFrameIndexReference (const MachineFunction & MF, int FI, unsigned & FrameReg) const [override, virtual]
getFrameIndexReference - This method should return the base register and offset used to reference a frame index location.
The offset is returned directly, and the base register is returned via FrameReg.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1197 of file X86FrameLowering.cpp.
References getFrameIndexOffset(), and TRI.
int X86FrameLowering::getFrameIndexReferenceFromSP (const MachineFunction & MF, int FI, unsigned & FrameReg) const [override, virtual]
Same as above, except that the 'base register' will always be RSP, not RBP on x86.
This is used exclusively for lowering STATEPOINT nodes. TODO: This should really be a parameterizable choice.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1271 of file X86FrameLowering.cpp.
References getFrameIndexOffsetFromSP(), and TRI.
bool X86FrameLowering::hasFP (const MachineFunction & MF) const [override, virtual]
hasFP - Return true if the specified function should have a dedicated frame pointer register.
This is true if the function has variable sized allocas or if frame pointer elimination is disabled.
Implements llvm::TargetFrameLowering.
Definition at line 86 of file X86FrameLowering.cpp.
References llvm::MachineModuleInfo::callsEHReturn(), llvm::MachineModuleInfo::callsUnwindInit(), llvm::TargetOptions::DisableFramePointerElim(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getMMI(), llvm::MachineFunction::getTarget(), llvm::MachineFrameInfo::hasInlineAsmWithSPAdjust(), llvm::MachineFrameInfo::hasPatchPoint(), llvm::MachineFrameInfo::hasStackMap(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::MachineFrameInfo::isFrameAddressTaken(), llvm::TargetMachine::Options, and TRI.
Referenced by assignCalleeSavedSpillSlots(), canSimplifyCallFramePseudos(), canUseLEAForSPInEpilogue(), emitEpilogue(), emitPrologue(), and getFrameIndexOffset().
bool X86FrameLowering::hasReservedCallFrame (const MachineFunction & MF) const [override, virtual]
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
This eliminates the need for add/sub sp brackets around call sites. Returns true if the call frame is included as part of the stack frame.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 54 of file X86FrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), and llvm::MachineFrameInfo::hasVarSizedObjects().
Referenced by canSimplifyCallFramePseudos(), and eliminateCallFramePseudoInstr().
int X86FrameLowering::mergeSPUpdates (MachineBasicBlock & MBB, MachineBasicBlock::iterator & MBBI, bool doMergeWithPrevious) const
Check the instruction before/after the passed instruction.
If it is an ADD/SUB/LEA instruction it is deleted argument and the stack adjustment is returned as a positive value for ADD/LEA and a negative for SUB.
Definition at line 374 of file X86FrameLowering.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::erase(), and StackPtr.
Referenced by emitEpilogue(), and emitPrologue().
bool X86FrameLowering::needsFrameIndexResolution (const MachineFunction & MF) const [override, virtual]
Reimplemented from llvm::TargetFrameLowering.
Definition at line 78 of file X86FrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), and llvm::MachineFrameInfo::hasStackObjects().
void X86FrameLowering::processFunctionBeforeCalleeSavedScan (MachineFunction & MF, RegScavenger * RS = nullptr) const [override, virtual]
processFunctionBeforeCalleeSavedScan - This method is called immediately before PrologEpilogInserter scans the physical registers used to determine what callee saved registers should be spilled.
This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1416 of file X86FrameLowering.cpp.
References llvm::MachineFrameInfo::CreateFixedObject(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getRegInfo(), llvm::X86MachineFunctionInfo::getTCReturnAddrDelta(), llvm::MachineRegisterInfo::setPhysRegUsed(), SlotSize, and TRI.
bool X86FrameLowering::restoreCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const [override, virtual]
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1382 of file X86FrameLowering.cpp.
References llvm::BuildMI(), contains(), llvm::MachineBasicBlock::findDebugLoc(), llvm::MCInstrInfo::get(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::TargetInstrInfo::loadRegFromStackSlot(), STI, and TII.
bool X86FrameLowering::spillCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const [override, virtual]
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1342 of file X86FrameLowering.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::BuildMI(), contains(), llvm::MachineBasicBlock::findDebugLoc(), llvm::MachineInstr::FrameSetup, llvm::MCInstrInfo::get(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::RegState::Kill, llvm::AArch64CC::MI, llvm::MachineInstrBuilder::setMIFlag(), STI, llvm::TargetInstrInfo::storeRegToStackSlot(), and TII.
Member Data Documentation
bool llvm::X86FrameLowering::Is64Bit
Is64Bit implies that x86_64 instructions are available.
Definition at line 39 of file X86FrameLowering.h.
Referenced by adjustForHiPEPrologue(), adjustForSegmentedStacks(), emitEpilogue(), emitPrologue(), emitSPUpdate(), emitStackProbeCall(), and X86FrameLowering().
bool llvm::X86FrameLowering::IsLP64
Definition at line 41 of file X86FrameLowering.h.
Referenced by adjustForHiPEPrologue(), adjustForSegmentedStacks(), and X86FrameLowering().
unsigned llvm::X86FrameLowering::SlotSize
Definition at line 36 of file X86FrameLowering.h.
Referenced by adjustForHiPEPrologue(), assignCalleeSavedSpillSlots(), emitEpilogue(), emitPrologue(), getFrameIndexOffset(), processFunctionBeforeCalleeSavedScan(), and X86FrameLowering().
unsigned llvm::X86FrameLowering::StackPtr
Definition at line 48 of file X86FrameLowering.h.
Referenced by emitEpilogue(), emitPrologue(), emitSPUpdate(), mergeSPUpdates(), and X86FrameLowering().
const X86Subtarget& llvm::X86FrameLowering::STI
Definition at line 32 of file X86FrameLowering.h.
Referenced by adjustForHiPEPrologue(), adjustForSegmentedStacks(), emitEpilogue(), emitPrologue(), emitStackProbeCall(), restoreCalleeSavedRegisters(), and spillCalleeSavedRegisters().
const TargetInstrInfo& llvm::X86FrameLowering::TII
Definition at line 33 of file X86FrameLowering.h.
Referenced by adjustForHiPEPrologue(), adjustForSegmentedStacks(), eliminateCallFramePseudoInstr(), emitEpilogue(), emitPrologue(), emitSPUpdate(), emitStackProbeCall(), restoreCalleeSavedRegisters(), and spillCalleeSavedRegisters().
const X86RegisterInfo* llvm::X86FrameLowering::TRI
Definition at line 34 of file X86FrameLowering.h.
Referenced by canSimplifyCallFramePseudos(), emitEpilogue(), emitPrologue(), emitSPUpdate(), getFrameIndexOffset(), getFrameIndexOffsetFromSP(), getFrameIndexReference(), getFrameIndexReferenceFromSP(), hasFP(), processFunctionBeforeCalleeSavedScan(), and X86FrameLowering().
bool llvm::X86FrameLowering::Uses64BitFramePtr
True if the 64-bit frame or stack pointer should be used.
True for most 64-bit targets with the exception of x32. If this is false, 32-bit instruction operands should be used to manipulate StackPtr and FramePtr.
Definition at line 46 of file X86FrameLowering.h.
Referenced by emitEpilogue(), emitPrologue(), and X86FrameLowering().
The documentation for this class was generated from the following files:
X86FrameLowering.h
X86FrameLowering.cpp