LLVM: llvm::PDBSymbolFunc Class Reference
llvm::PDBSymbolFunc Class Reference
#include <PDBSymbolFunc.h>
Public Member Functions
PDBSymbolFunc (const IPDBSession &PDBSession, std::unique_ptr< IPDBRawSymbol > FuncSymbol)
void dump (PDBSymDumper &Dumper) const override
Dumps the contents of a symbol a raw_ostream.
std::unique_ptr
< PDBSymbolTypeFunctionSig > getSignature () const
std::unique_ptr< PDBSymbolTypeUDT > getClassParent () const
std::unique_ptr
< IPDBEnumChildren
< PDBSymbolData > > getArguments () const
Detailed Description
Definition at line 20 of file PDBSymbolFunc.h.
Constructor & Destructor Documentation
PDBSymbolFunc::PDBSymbolFunc (const IPDBSession & PDBSession, std::unique_ptr< IPDBRawSymbol > FuncSymbol)
Definition at line 85 of file PDBSymbolFunc.cpp.
Member Function Documentation
void PDBSymbolFunc::dump (PDBSymDumper & Dumper) const [override, virtual]
Dumps the contents of a symbol a raw_ostream.
By default this will just call dump() on the underlying RawSymbol, which allows us to discover unknown properties, but individual implementations of PDBSymbol may override the behavior to only dump known fields.
Implements llvm::PDBSymbol.
Definition at line 102 of file PDBSymbolFunc.cpp.
References llvm::PDBSymDumper::dump().
std::unique_ptr< IPDBEnumChildren< PDBSymbolData > > PDBSymbolFunc::getArguments () const
Definition at line 94 of file PDBSymbolFunc.cpp.
References llvm::PDBSymbol::Session.
std::unique_ptr< PDBSymbolTypeUDT > PDBSymbolFunc::getClassParent () const
Definition at line 98 of file PDBSymbolFunc.cpp.
References llvm::IPDBSession::getConcreteSymbolById(), and llvm::PDBSymbol::Session.
std::unique_ptr< PDBSymbolTypeFunctionSig > PDBSymbolFunc::getSignature () const
Definition at line 89 of file PDBSymbolFunc.cpp.
References llvm::IPDBSession::getConcreteSymbolById(), and llvm::PDBSymbol::Session.
The documentation for this class was generated from the following files:
PDBSymbolFunc.h
PDBSymbolFunc.cpp