LLVM: llvm::PDBContext Class Reference
llvm::PDBContext Class Reference
PDBContext This data structure is the top level entity that deals with PDB debug information parsing.
#include <PDBContext.h>
Public Member Functions
PDBContext (const object::COFFObjectFile &Object, std::unique_ptr< IPDBSession > PDBSession, bool RelativeAddress)
void dump (raw_ostream &OS, DIDumpType DumpType=DIDT_All) override
DILineInfo getLineInfoForAddress (uint64_t Address, DILineInfoSpecifier Specifier=DILineInfoSpecifier()) override
DILineInfoTable getLineInfoForAddressRange (uint64_t Address, uint64_t Size, DILineInfoSpecifier Specifier=DILineInfoSpecifier()) override
DIInliningInfo getInliningInfoForAddress (uint64_t Address, DILineInfoSpecifier Specifier=DILineInfoSpecifier()) override
Static Public Member Functions
static bool classof (const DIContext *DICtx)
Detailed Description
PDBContext This data structure is the top level entity that deals with PDB debug information parsing.
This data structure exists only when there is a need for a transparent interface to different debug information formats (e.g. PDB and DWARF). More control and power over the debug information access can be had by using the PDB interfaces directly.
Definition at line 28 of file PDBContext.h.
Constructor & Destructor Documentation
PDBContext::PDBContext (const object::COFFObjectFile & Object, std::unique_ptr< IPDBSession > PDBSession, bool RelativeAddress)
Definition at line 23 of file PDBContext.cpp.
References llvm::object::COFFObjectFile::getPE32Header(), llvm::object::COFFObjectFile::getPE32PlusHeader(), llvm::object::pe32_header::ImageBase, llvm::object::pe32plus_header::ImageBase, and llvm::object::COFFObjectFile::is64().
Member Function Documentation
static bool llvm::PDBContext::classof (const DIContext * DICtx) [inline, static]
Definition at line 38 of file PDBContext.h.
References llvm::DIContext::CK_PDB, and llvm::DIContext::getKind().
void PDBContext::dump (raw_ostream & OS, DIDumpType DumpType = DIDT_All) [override, virtual]
Implements llvm::DIContext.
Definition at line 44 of file PDBContext.cpp.
DIInliningInfo PDBContext::getInliningInfoForAddress (uint64_t Address, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) [override, virtual]
Implements llvm::DIContext.
Definition at line 98 of file PDBContext.cpp.
References llvm::DIInliningInfo::addFrame(), and getLineInfoForAddress().
DILineInfo PDBContext::getLineInfoForAddress (uint64_t Address, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) [override, virtual]
Implements llvm::DIContext.
Definition at line 46 of file PDBContext.cpp.
References llvm::DILineInfo::Column, llvm::Data, llvm::DILineInfo::FileName, llvm::DILineInfoSpecifier::FLIKind, llvm::DILineInfoSpecifier::FNKind, llvm::DILineInfo::FunctionName, getFunctionName(), llvm::DILineInfo::Line, llvm::LineNumbers, llvm::None, and llvm::ARMBuildAttrs::Symbol.
Referenced by getInliningInfoForAddress(), and getLineInfoForAddressRange().
DILineInfoTable PDBContext::getLineInfoForAddressRange (uint64_t Address, uint64_t Size, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) [override, virtual]
Implements llvm::DIContext.
Definition at line 79 of file PDBContext.cpp.
References getLineInfoForAddress(), llvm::LineNumbers, and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
The documentation for this class was generated from the following files:
PDBContext.h
PDBContext.cpp