LLVM: llvm::RuntimeDyldCOFFX86_64 Class Reference
llvm::RuntimeDyldCOFFX86_64 Class Reference
#include <RuntimeDyldCOFFX86_64.h>
Public Member Functions
RuntimeDyldCOFFX86_64 (RuntimeDyld::MemoryManager &MM, RuntimeDyld::SymbolResolver &Resolver)
unsigned getMaxStubSize () override
void resolveRelocation (const RelocationEntry &RE, uint64_t Value) override
A object file specific relocation resolver.
relocation_iterator processRelocationRef (unsigned SectionID, relocation_iterator RelI, const ObjectFile &Obj, ObjSectionToIDMap &ObjSectionToID, StubMap &Stubs) override
Parses one or more object file relocations (some object files use relocation pairs) and stores it to Relocations or SymbolRelocations (this depends on the object file type).
unsigned getStubAlignment () override
void registerEHFrames () override
void deregisterEHFrames () override
void finalizeLoad (const ObjectFile &Obj, ObjSectionToIDMap &SectionMap) override
Detailed Description
Definition at line 25 of file RuntimeDyldCOFFX86_64.h.
Constructor & Destructor Documentation
llvm::RuntimeDyldCOFFX86_64::RuntimeDyldCOFFX86_64 (RuntimeDyld::MemoryManager & MM, RuntimeDyld::SymbolResolver & Resolver) [inline]
Definition at line 35 of file RuntimeDyldCOFFX86_64.h.
Member Function Documentation
void llvm::RuntimeDyldCOFFX86_64::deregisterEHFrames () [inline, override, virtual]
Reimplemented from llvm::RuntimeDyldImpl.
Definition at line 193 of file RuntimeDyldCOFFX86_64.h.
void llvm::RuntimeDyldCOFFX86_64::finalizeLoad (const ObjectFile & Obj, ObjSectionToIDMap & SectionMap) [inline, override, virtual]
Reimplemented from llvm::RuntimeDyldImpl.
Definition at line 196 of file RuntimeDyldCOFFX86_64.h.
References llvm::Check(), llvm::object::SectionRef::getName(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::ARMBuildAttrs::Section.
unsigned llvm::RuntimeDyldCOFFX86_64::getMaxStubSize () [inline, override, virtual]
Implements llvm::RuntimeDyldImpl.
Definition at line 39 of file RuntimeDyldCOFFX86_64.h.
unsigned llvm::RuntimeDyldCOFFX86_64::getStubAlignment () [inline, override, virtual]
Implements llvm::RuntimeDyldImpl.
Definition at line 182 of file RuntimeDyldCOFFX86_64.h.
relocation_iterator llvm::RuntimeDyldCOFFX86_64::processRelocationRef (unsigned SectionID, relocation_iterator RelI, const ObjectFile & Obj, ObjSectionToIDMap & ObjSectionToID, StubMap & Stubs) [inline, override, virtual]
Parses one or more object file relocations (some object files use relocation pairs) and stores it to Relocations or SymbolRelocations (this depends on the object file type).
Returns:
Iterator to the next relocation that needs to be parsed.
Implements llvm::RuntimeDyldImpl.
Definition at line 112 of file RuntimeDyldCOFFX86_64.h.
References llvm::RuntimeDyldImpl::addRelocationForSection(), llvm::RuntimeDyldImpl::addRelocationForSymbol(), llvm::Check(), llvm::dbgs(), DEBUG, llvm::RuntimeDyldImpl::findOrEmitSection(), llvm::object::SymbolRef::getName(), llvm::object::SymbolRef::getSection(), llvm::RuntimeDyldCOFF::getSymbolOffset(), llvm::COFF::IMAGE_REL_AMD64_ADDR32NB, llvm::COFF::IMAGE_REL_AMD64_ADDR64, llvm::COFF::IMAGE_REL_AMD64_REL32, llvm::COFF::IMAGE_REL_AMD64_REL32_1, llvm::COFF::IMAGE_REL_AMD64_REL32_2, llvm::COFF::IMAGE_REL_AMD64_REL32_3, llvm::COFF::IMAGE_REL_AMD64_REL32_4, llvm::COFF::IMAGE_REL_AMD64_REL32_5, llvm::SectionEntry::ObjAddress, llvm::report_fatal_error(), llvm::ARMBuildAttrs::Section, llvm::object::ObjectFile::section_end(), llvm::RuntimeDyldImpl::Sections, llvm::ARMBuildAttrs::Symbol, and llvm::object::SymbolicFile::symbol_end().
void llvm::RuntimeDyldCOFFX86_64::registerEHFrames () [inline, override, virtual]
Reimplemented from llvm::RuntimeDyldImpl.
Definition at line 183 of file RuntimeDyldCOFFX86_64.h.
References llvm::RuntimeDyldImpl::MemMgr, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::RuntimeDyld::MemoryManager::registerEHFrames(), and llvm::RuntimeDyldImpl::Sections.
void llvm::RuntimeDyldCOFFX86_64::resolveRelocation (const RelocationEntry & RE, uint64_t Value) [inline, override, virtual]
A object file specific relocation resolver.
Parameters:
RE The relocation to be resolved
Value Target symbol address to apply the relocation action
Implements llvm::RuntimeDyldImpl.
Definition at line 63 of file RuntimeDyldCOFFX86_64.h.
References llvm::RelocationEntry::Addend, llvm::SectionEntry::Address, llvm::COFF::IMAGE_REL_AMD64_ADDR32NB, llvm::COFF::IMAGE_REL_AMD64_ADDR64, llvm::COFF::IMAGE_REL_AMD64_REL32, llvm::COFF::IMAGE_REL_AMD64_REL32_1, llvm::COFF::IMAGE_REL_AMD64_REL32_2, llvm::COFF::IMAGE_REL_AMD64_REL32_3, llvm::COFF::IMAGE_REL_AMD64_REL32_4, llvm::COFF::IMAGE_REL_AMD64_REL32_5, llvm_unreachable, llvm::SectionEntry::LoadAddress, llvm::RelocationEntry::Offset, llvm::RelocationEntry::RelType, llvm::ARMBuildAttrs::Section, llvm::RelocationEntry::SectionID, and llvm::RuntimeDyldImpl::Sections.
The documentation for this class was generated from the following file:
RuntimeDyldCOFFX86_64.h