LLVM: llvm::DIFile Class Reference
llvm::DIFile Class Reference
File.
#include <DebugInfoMetadata.h>
Public Member Functions
DEFINE_MDNODE_GET (DIFile,(StringRef Filename, StringRef Directory),(Filename, Directory)) DEFINE_MDNODE_GET(DIFile
MDString MDString Directory
TempDIFile clone () const
Create a (temporary) clone of this.
StringRef getFilename () const
StringRef getDirectory () const
MDString * getRawFilename () const
MDString * getRawDirectory () const
Static Public Member Functions
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
Public Attributes
MDString * Filename
MDString MDString * Directory
MDString MDString Filename
Friends
class LLVMContextImpl
class MDNode
Detailed Description
File.
TODO: Merge with directory/file node (including users). TODO: Canonicalize paths on creation.
Definition at line 455 of file DebugInfoMetadata.h.
Member Function Documentation
static bool llvm::DIFile::classof (const Metadata * MD) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::DIScope.
Definition at line 492 of file DebugInfoMetadata.h.
References llvm::Metadata::DIFileKind, and llvm::Metadata::getMetadataID().
MDString MDString Directory TempDIFile llvm::DIFile::clone () const [inline]
Create a (temporary) clone of this.
Reimplemented from llvm::MDNode.
Definition at line 484 of file DebugInfoMetadata.h.
llvm::DIFile::DEFINE_MDNODE_GET (DIFile , (StringRef Filename, StringRef Directory) , (Filename, Directory))
StringRef llvm::DIFile::getDirectory () const [inline]
Reimplemented from llvm::DIScope.
Definition at line 487 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
Referenced by llvm::MDNodeKeyImpl< DIFile >::isKeyOf().
StringRef llvm::DIFile::getFilename () const [inline]
Reimplemented from llvm::DIScope.
Definition at line 486 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
Referenced by llvm::MDNodeKeyImpl< DIFile >::isKeyOf().
MDString* llvm::DIFile::getRawDirectory () const [inline]
Definition at line 490 of file DebugInfoMetadata.h.
Referenced by WriteDIFile().
MDString* llvm::DIFile::getRawFilename () const [inline]
Definition at line 489 of file DebugInfoMetadata.h.
Referenced by WriteDIFile().
Friends And Related Function Documentation
friend class LLVMContextImpl [friend]
Reimplemented from llvm::DINode.
Definition at line 456 of file DebugInfoMetadata.h.
friend class MDNode [friend]
Reimplemented from llvm::DINode.
Definition at line 457 of file DebugInfoMetadata.h.
Member Data Documentation
MDString MDString* llvm::DIFile::Directory
Definition at line 481 of file DebugInfoMetadata.h.
MDString* llvm::DIFile::Filename
Definition at line 481 of file DebugInfoMetadata.h.
MDString MDString llvm::DIFile::Filename
Definition at line 481 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
DebugInfoMetadata.h
DebugInfoMetadata.cpp