LLVM: llvm::StringRef Class Reference
llvm::StringRef Class Reference
StringRef - Represent a constant reference to a string, i.e.
#include <StringRef.h>
Public Types
typedef const char * iterator
typedef const char * const_iterator
typedef size_t size_type
Public Member Functions
iterator begin () const
iterator end () const
const unsigned char * bytes_begin () const
const unsigned char * bytes_end () const
const char * data () const
data - Get a pointer to the start of the string (which may not be null terminated).
bool empty () const
empty - Check if the string is empty.
size_t size () const
size - Get the string size.
char front () const
front - Get the first character in the string.
char back () const
back - Get the last character in the string.
template<typename Allocator >
StringRef copy (Allocator &A) const
bool equals (StringRef RHS) const
equals - Check for string equality, this is more efficient than compare() when the relative ordering of inequal strings isn't needed.
bool equals_lower (StringRef RHS) const
equals_lower - Check for string equality, ignoring case.
int compare (StringRef RHS) const
compare - Compare two strings; the result is -1, 0, or 1 if this string is lexicographically less than, equal to, or greater than the RHS.
int compare_lower (StringRef RHS) const
compare_lower - Compare two strings, ignoring case.
int compare_numeric (StringRef RHS) const
compare_numeric - Compare two strings, treating sequences of digits as numbers.
unsigned edit_distance (StringRef Other, bool AllowReplacements=true, unsigned MaxEditDistance=0) const
Determine the edit distance between this string and another string.
std::string str () const
str - Get the contents as an std::string.
char operator[] (size_t Index) const
operator std::string () const
bool startswith (StringRef Prefix) const
Check if this string starts with the given Prefix.
bool startswith_lower (StringRef Prefix) const
Check if this string starts with the given Prefix, ignoring case.
bool endswith (StringRef Suffix) const
Check if this string ends with the given Suffix.
bool endswith_lower (StringRef Suffix) const
Check if this string ends with the given Suffix, ignoring case.
size_t find (char C, size_t From=0) const
Search for the first character C in the string.
size_t find (StringRef Str, size_t From=0) const
Search for the first string Str in the string.
size_t rfind (char C, size_t From=npos) const
Search for the last character C in the string.
size_t rfind (StringRef Str) const
Search for the last string Str in the string.
size_t find_first_of (char C, size_t From=0) const
Find the first character in the string that is C, or npos if not found.
size_t find_first_of (StringRef Chars, size_t From=0) const
Find the first character in the string that is in Chars, or npos if not found.
size_t find_first_not_of (char C, size_t From=0) const
Find the first character in the string that is not C or npos if not found.
size_t find_first_not_of (StringRef Chars, size_t From=0) const
Find the first character in the string that is not in the string Chars, or npos if not found.
size_t find_last_of (char C, size_t From=npos) const
Find the last character in the string that is C, or npos if not found.
size_t find_last_of (StringRef Chars, size_t From=npos) const
Find the last character in the string that is in C, or npos if not found.
size_t find_last_not_of (char C, size_t From=npos) const
Find the last character in the string that is not C, or npos if not found.
size_t find_last_not_of (StringRef Chars, size_t From=npos) const
Find the last character in the string that is not in Chars, or npos if not found.
size_t count (char C) const
Return the number of occurrences of C in the string.
size_t count (StringRef Str) const
Return the number of non-overlapped occurrences of Str in the string.
template<typename T >
std::enable_if
< std::numeric_limits< T >
::is_signed, bool >::type getAsInteger (unsigned Radix, T &Result) const
Parse the current string as an integer of the specified radix.
template<typename T >
std::enable_if
<!std::numeric_limits< T >
::is_signed, bool >::type getAsInteger (unsigned Radix, T &Result) const
bool getAsInteger (unsigned Radix, APInt &Result) const
Parse the current string as an integer of the specified Radix, or of an autosensed radix if the Radix given is 0.
std::string lower () const
std::string upper () const
Convert the given ASCII string to uppercase.
StringRef substr (size_t Start, size_t N=npos) const
Return a reference to the substring from [Start, Start + N).
StringRef drop_front (size_t N=1) const
Return a StringRef equal to 'this' but with the first N elements dropped.
StringRef drop_back (size_t N=1) const
Return a StringRef equal to 'this' but with the last N elements dropped.
StringRef slice (size_t Start, size_t End) const
Return a reference to the substring from [Start, End).
std::pair< StringRef, StringRef > split (char Separator) const
Split into two substrings around the first occurrence of a separator character.
std::pair< StringRef, StringRef > split (StringRef Separator) const
Split into two substrings around the first occurrence of a separator string.
void split (SmallVectorImpl< StringRef > &A, StringRef Separator, int MaxSplit=-1, bool KeepEmpty=true) const
Split into substrings around the occurrences of a separator string.
std::pair< StringRef, StringRef > rsplit (char Separator) const
Split into two substrings around the last occurrence of a separator character.
StringRef ltrim (StringRef Chars=" \t\n\v\f\r") const
Return string with consecutive characters in Chars starting from the left removed.
StringRef rtrim (StringRef Chars=" \t\n\v\f\r") const
Return string with consecutive characters in Chars starting from the right removed.
StringRef trim (StringRef Chars=" \t\n\v\f\r") const
Return string with consecutive characters in Chars starting from the left and right removed.
Constructors
StringRef ()
Construct an empty string ref.
StringRef (const char *Str)
Construct a string ref from a cstring.
StringRef (const char *data, size_t length)
Construct a string ref from a pointer and length.
StringRef (const std::string &Str)
Construct a string ref from an std::string.
Static Public Attributes
static const size_t npos = ~size_t(0)
Detailed Description
StringRef - Represent a constant reference to a string, i.e.
a character array and a length, which need not be null terminated.
This class does not own the string data, it is expected to be used in situations where the character data resides in some other buffer, whose lifetime extends past that of the StringRef. For this reason, it is not in general safe to store a StringRef.
Definition at line 40 of file StringRef.h.
Member Typedef Documentation
typedef const char* llvm::StringRef::const_iterator
Definition at line 43 of file StringRef.h.
typedef const char* llvm::StringRef::iterator
Definition at line 42 of file StringRef.h.
typedef size_t llvm::StringRef::size_type
Definition at line 45 of file StringRef.h.
Constructor & Destructor Documentation
llvm::StringRef::StringRef () [inline]
Construct an empty string ref.
Definition at line 66 of file StringRef.h.
Referenced by drop_back(), and split().
llvm::StringRef::StringRef (const char * Str) [inline]
Construct a string ref from a cstring.
Definition at line 69 of file StringRef.h.
llvm::StringRef::StringRef (const char * data, size_t length) [inline]
Construct a string ref from a pointer and length.
Definition at line 76 of file StringRef.h.
llvm::StringRef::StringRef (const std::string & Str) [inline]
Construct a string ref from an std::string.
Definition at line 83 of file StringRef.h.
Member Function Documentation
char llvm::StringRef::back () const [inline]
back - Get the last character in the string.
Definition at line 118 of file StringRef.h.
Referenced by llvm::ConstantDataSequential::isCString(), llvm::yaml::needsQuotes(), and parsePhysicalReg().
iterator llvm::StringRef::begin () const [inline]
Definition at line 88 of file StringRef.h.
Referenced by llvm::sys::path::append(), llvm::SmallString< 256 >::assign(), llvm::MDString::begin(), llvm::yaml::final::BlockScalarNode(), llvm::APFloat::convertFromString(), llvm::convertUTF8ToUTF16String(), llvm::ConvertUTF8toWide(), llvm::sys::fs::createTemporaryFile(), decodeUTF8(), llvm::MCObjectStreamer::EmitBytes(), llvm::TargetLoweringObjectFileELF::emitPersonalityValue(), llvm::yaml::escape(), llvm::APInt::getBitsNeeded(), llvm::MemoryBufferRef::getBufferStart(), llvm::object::Archive::Symbol::getName(), llvm::object::Archive::getNumberOfSymbols(), llvm::StringToOffsetTable::GetOrAddStringOffset(), llvm::object::MachOObjectFile::getRelocationTypeName(), llvm::object::ELFFile< ELFT >::getRelocationTypeName(), llvm::object::COFFObjectFile::getRelocationTypeName(), llvm::ConstantDataArray::getString(), llvm::TargetLoweringObjectFile::getSymbolWithGlobalValueBase(), llvm::hash_value(), llvm::Timer::init(), isAllZeros(), llvm::LLLexer::LLLexer(), llvm::MIToken::location(), llvm::object::MachOUniversalBinary::MachOUniversalBinary(), llvm::sys::fs::make_absolute(), mangleCoveragePath(), llvm::object::MachOUniversalBinary::ObjectForArch::ObjectForArch(), llvm::object::Archive::Child::operator<(), llvm::sys::path::const_iterator::operator==(), llvm::object::Archive::Child::operator==(), llvm::sys::path::reverse_iterator::operator==(), llvm::opt::OptTable::OptTable(), llvm::DWARFDebugLoc::parse(), llvm::DWARFDebugLocDWO::parse(), llvm::InlineAsm::ConstraintInfo::Parse(), llvm::InlineAsm::ParseConstraints(), parseDouble(), parsePhysicalReg(), prependCompressionHeader(), printName(), llvm::sys::path::replace_extension(), llvm::yaml::final::ScalarNode(), llvm::AsmLexer::setBuffer(), llvm::EngineBuilder::setMArch(), llvm::EngineBuilder::setMCPU(), llvm::TimerGroup::setName(), SimplifyCondBranchToCondBranch(), llvm::Regex::sub(), llvm::object::Archive::symbol_begin(), llvm::TGLexer::TGLexer(), WriteAttributeGroupTable(), and WriteModuleMetadataStore().
const unsigned char* llvm::StringRef::bytes_begin () const [inline]
Definition at line 92 of file StringRef.h.
Referenced by llvm::MDString::bytes_begin(), and WriteModuleMetadata().
const unsigned char* llvm::StringRef::bytes_end () const [inline]
Definition at line 95 of file StringRef.h.
Referenced by llvm::MDString::bytes_end(), and WriteModuleMetadata().
int llvm::StringRef::compare (StringRef RHS) const [inline]
compare - Compare two strings; the result is -1, 0, or 1 if this string is lexicographically less than, equal to, or greater than the RHS.
Definition at line 144 of file StringRef.h.
Referenced by llvm::SmallString< 256 >::compare_lower(), llvm::operator<(), llvm::operator<=(), llvm::operator>(), llvm::operator>=(), order_by_name(), and SortSymbolPair().
int StringRef::compare_lower (StringRef RHS) const
compare_lower - Compare two strings, ignoring case.
compare_lower - Compare strings, ignoring case.
Definition at line 52 of file StringRef.cpp.
References ascii_strncasecmp(), and fuzzer::min().
Referenced by llvm::SmallString< 256 >::compare_numeric().
int StringRef::compare_numeric (StringRef RHS) const
compare_numeric - Compare two strings, treating sequences of digits as numbers.
compare_numeric - Compare strings, handle embedded numbers.
Definition at line 73 of file StringRef.cpp.
References ascii_isdigit(), I, and fuzzer::min().
template<typename Allocator > StringRef llvm::StringRef::copy (Allocator & A) const [inline]
Definition at line 124 of file StringRef.h.
Referenced by llvm::yaml::Document::parseBlockNode().
size_t llvm::StringRef::count (char C) const [inline]
Return the number of occurrences of C in the string.
Definition at line 312 of file StringRef.h.
Referenced by llvm::SmallString< 256 >::count(), and llvm::InlineAsm::ConstraintInfo::Parse().
size_t StringRef::count (StringRef Str) const
Return the number of non-overlapped occurrences of Str in the string.
count - Return the number of non-overlapped occurrences of
Str in the string.
Definition at line 303 of file StringRef.cpp.
References equals(), N, size(), and substr().
const char* llvm::StringRef::data () const [inline]
data - Get a pointer to the start of the string (which may not be null terminated).
Definition at line 103 of file StringRef.h.
Referenced by llvm::SourceMgr::AddIncludeFile(), llvm::FoldingSetNodeID::AddString(), llvm::StringSwitch< T, R >::Case(), llvm::sys::unicode::columnWidthUTF8(), compareWithScalarFnName(), compareWithVectorFnName(), llvm::ConvertUTF8toWide(), CopyStringRef(), llvm::StringMapEntry< MDString >::Create(), llvm::X86Operand::CreateToken(), llvm::dumpBlock(), edit_distance(), llvm::RuntimeDyldImpl::emitSection(), llvm::StringSwitch< T, R >::EndsWith(), llvm::cl::Option::error(), ExecGraphViewer(), llvm::DWARFFormValue::extractValue(), llvm::object::Archive::Child::getBuffer(), llvm::DataExtractor::getCStr(), llvm::AsmToken::getEndLoc(), llvm::object::MachOObjectFile::getIndirectName(), llvm::getInst(), llvm::TargetLibraryInfoImpl::getLibFunc(), llvm::AsmToken::getLoc(), llvm::MemoryBuffer::getMemBufferCopy(), llvm::opt::ArgList::GetOrMakeJoinedArgString(), llvm::RuntimeDyldMachO::getRelocationValueRef(), llvm::ConstantDataVector::getSplatValue(), llvm::ConstantDataArray::getString(), llvm::object::MachOObjectFile::getSymbolName(), llvm::DataExtractor::getU16(), llvm::DataExtractor::getU32(), llvm::DataExtractor::getU64(), llvm::DataExtractor::getU8(), llvm::sys::fs::identify_magic(), llvm::ExecutionEngine::InitializeMemory(), LLVMGetAsString(), LLVMGetSectionContents(), LLVMGetSectionName(), LLVMGetStructName(), LLVMGetSymbolName(), LLVMTargetMachineEmitToMemoryBuffer(), loadTestingFormat(), llvm::Regex::match(), llvm::sys::path::native(), llvm::raw_ostream::operator<<(), llvm::opt::OptTable::ParseOneArg(), llvm::RuntimeDyldELF::processRelocationRef(), ProvideOption(), readCoverageMappingData(), llvm::GCOVBuffer::readInt(), llvm::RawInstrProfReader< IntPtrT >::readNextRecord(), llvm::LessRecordRegister::RecordParts::RecordParts(), llvm::Regex::Regex(), replaceSubString(), llvm::report_fatal_error(), llvm::RuntimeDyldImpl::resolveExternalSymbols(), RewriteIntelBracExpression(), llvm::StringSaver::saveImpl(), llvm::yaml::Output::scalarString(), llvm::X86Operand::setTokenValue(), sortOpts(), split(), llvm::StringSwitch< T, R >::StartsWith(), and llvm::MD5::update().
StringRef llvm::StringRef::drop_back (size_t N = 1) const [inline]
Return a StringRef equal to 'this' but with the last N elements dropped.
Definition at line 401 of file StringRef.h.
References fuzzer::min(), N, and StringRef().
Referenced by llvm::ConstantDataSequential::isCString(), and llvm::yaml::Document::parseBlockNode().
StringRef llvm::StringRef::drop_front (size_t N = 1) const [inline]
Return a StringRef equal to 'this' but with the first N elements dropped.
Definition at line 394 of file StringRef.h.
Referenced by getFuncNameWithoutPrefix(), llvm::yaml::isNumber(), llvm::yaml::isNumeric(), and MatchCoprocessorOperandName().
unsigned StringRef::edit_distance (llvm::StringRef Other, bool AllowReplacements = true, unsigned MaxEditDistance = 0) const
Determine the edit distance between this string and another string.
Parameters:
Other the string to compare this string against.
AllowReplacements whether to allow character replacements (change one character into another) as a single operation, rather than as two operations (an insertion and a removal).
MaxEditDistance If non-zero, the maximum edit distance that this routine is allowed to compute. If the edit distance will exceed that maximum, returns MaxEditDistance+1.
Returns:
the minimum number of character insertions, removals, or (if AllowReplacements is true) replacements needed to transform one of the given strings into the other. If zero, the strings are identical.
Definition at line 104 of file StringRef.cpp.
References llvm::ComputeEditDistance(), data(), llvm::makeArrayRef(), and size().
Referenced by LookupNearestOption().
bool llvm::StringRef::empty () const [inline]
empty - Check if the string is empty.
Definition at line 106 of file StringRef.h.
Referenced by llvm::SubtargetFeatures::AddFeature(), llvm::ExecutionEngine::addGlobalMapping(), llvm::DwarfUnit::addLinkageName(), llvm::DwarfUnit::applySubprogramAttributes(), llvm::DwarfUnit::applySubprogramDefinitionAttributes(), llvm::DwarfCompileUnit::applyVariableAttributes(), llvm::APSInt::APSInt(), CloneInstructionInExitBlock(), llvm::MipsABIInfo::computeTargetABI(), computeTargetABI(), llvm::ConstantFoldLoadFromConstPtr(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), llvm::DwarfUnit::constructTypeDIE(), llvm::APFloat::convertFromString(), llvm::convertUTF8ToUTF16String(), llvm::StructType::create(), llvm::sys::fs::create_directories(), createAArch64MCSubtargetInfo(), llvm::MDBuilder::createAnonymousAARoot(), llvm::ARM_MC::createARMMCSubtargetInfo(), llvm::DIBuilder::createBasicType(), llvm::DIBuilder::createClassType(), llvm::DIBuilder::createCompileUnit(), llvm::DIBuilder::createEnumerationType(), llvm::DIBuilder::createEnumerator(), llvm::DIBuilder::createForwardDecl(), llvm::DIBuilder::createReplaceableCompositeType(), llvm::createSanitizerCtorAndInitFunctions(), createSparcMCSubtargetInfo(), llvm::DIBuilder::createStructType(), llvm::sys::fs::createTemporaryFile(), llvm::DIBuilder::createUnionType(), llvm::DIBuilder::createUnspecifiedType(), llvm::X86_MC::createX86MCSubtargetInfo(), decodeBase64StringEntry(), llvm::DISubprogram::describes(), EatNumber(), emitComments(), emitDebugValueComment(), EmitGenDwarfAbbrev(), EmitGenDwarfInfo(), llvm::TargetLoweringObjectFileMachO::emitModuleFlags(), llvm::cl::Option::error(), llvm::DWARFFormValue::extractValue(), FoldBlockIntoPredecessor(), llvm::Attribute::get(), getARClassRegisterMask(), llvm::Triple::getARMCPUForArch(), getAsInteger(), llvm::getAsSignedInteger(), llvm::Attribute::getAsString(), llvm::getAsUnsignedInteger(), llvm::APInt::getBitsNeeded(), llvm::ARMTargetParser::getCanonicalArchName(), llvm::DINode::getCanonicalMDString(), getChompedLineBreaks(), llvm::MCContext::getCOFFSection(), llvm::DOTGraphTraits< const Function * >::getCompleteNodeLabel(), getELFKindForNamedSection(), llvm::MCContext::getELFSection(), llvm::SubtargetFeatures::getFeatureBits(), llvm::MCDwarfLineTableHeader::getFile(), getItineraryLatency(), llvm::TargetLibraryInfoImpl::getLibFunc(), llvm::object::MachOObjectFile::getLibraryShortNameByIndex(), getMClassFlagsMask(), getMClassRegisterMask(), getMemcpyLoadsAndStores(), getMemsetStringVal(), getNameWithPrefixImpl(), llvm::DwarfUnit::getOrCreateNameSpace(), llvm::MCContext::getOrCreateSymbol(), llvm::DwarfUnit::getParentContextString(), llvm::GlobalValue::getRealLinkageName(), llvm::TargetLibraryInfoImpl::getScalarizedFunction(), getSearchPaths(), llvm::DOTGraphTraits< const Function * >::getSimpleNodeLabel(), llvm::DataExtractor::getSLEB128(), llvm::ARMBaseTargetMachine::getSubtargetImpl(), llvm::MipsTargetMachine::getSubtargetImpl(), GetSymbolFromOperand(), llvm::TargetLoweringObjectFile::getSymbolWithGlobalValueBase(), llvm::DataExtractor::getULEB128(), llvm::TargetLibraryInfoImpl::getVectorizedFunction(), llvm::yaml::Node::getVerbatimTag(), llvm::MachineModuleInfo::getWinEHParent(), llvm::sys::path::has_extension(), llvm::sys::path::has_filename(), llvm::sys::path::has_parent_path(), llvm::sys::path::has_relative_path(), llvm::sys::path::has_root_directory(), llvm::sys::path::has_root_name(), llvm::sys::path::has_root_path(), llvm::sys::path::has_stem(), hasFlag(), llvm::GlobalObject::hasSection(), llvm::GlobalValue::hasSection(), llvm::MCSubtargetInfo::InitCPUSchedModel(), llvm::NVPTXSubtarget::initializeSubtargetDependencies(), llvm::StringSet< AllocatorTy >::insert(), isCanonical(), isEnabled(), llvm::TargetLibraryInfoImpl::isFunctionScalarizable(), llvm::TargetLibraryInfoImpl::isFunctionVectorizable(), isRepeatedByteSequence(), llvm::MCAsmInfo::isValidUnquotedName(), llvm::LoadAndStorePromoter::LoadAndStorePromoter(), loadBinaryFormat(), LookupNearestOption(), matchAsm(), llvm::yaml::needsQuotes(), llvm::Triple::normalize(), parseARMArch(), llvm::ARM_MC::ParseARMTriple(), llvm::PassBuilder::parsePassPipeline(), llvm::MCSectionMachO::ParseSectionSpecifier(), parseSubArch(), parseVersionFromName(), llvm::MCInstPrinter::printAnnotation(), printExtendedName(), printFile(), PrintLLVMName(), printMetadataIdentifier(), llvm::AttributeImpl::Profile(), llvm::GCOVBuffer::readArcTag(), llvm::GCOVBuffer::readBlockTag(), llvm::GCOVBuffer::readEdgeTag(), llvm::GCOVBuffer::readFunctionTag(), llvm::GCOVBuffer::readLineTag(), llvm::TextInstrProfReader::readNextRecord(), llvm::GCOVBuffer::readObjectTag(), llvm::GCOVBuffer::readProgramTag(), llvm::LessRecordRegister::RecordParts::RecordParts(), sanitizeFunctionName(), llvm::yaml::Output::scalarString(), llvm::FastISel::selectInstruction(), llvm::MIPS_MC::selectMipsCPU(), llvm::EngineBuilder::selectTarget(), setFunctionAttributes(), llvm::StructType::setName(), split(), StripTypeNames(), llvm::Regex::sub(), llvm::ExecutionEngine::updateGlobalMapping(), UsesVectorABI(), llvm::InlineAsm::Verify(), WriteAttributeGroupTable(), and WriteTypeTable().
iterator llvm::StringRef::end () const [inline]
Definition at line 90 of file StringRef.h.
Referenced by llvm::sys::path::append(), llvm::SmallString< 256 >::assign(), llvm::yaml::final::BlockScalarNode(), llvm::convertUTF8ToUTF16String(), llvm::ConvertUTF8toWide(), decodeUTF8(), llvm::MCObjectStreamer::EmitBytes(), llvm::TargetLoweringObjectFileELF::emitPersonalityValue(), llvm::MDString::end(), endswith_lower(), llvm::yaml::escape(), llvm::MemoryBufferRef::getBufferEnd(), llvm::StringToOffsetTable::GetOrAddStringOffset(), llvm::object::MachOObjectFile::getRelocationTypeName(), llvm::object::ELFFile< ELFT >::getRelocationTypeName(), llvm::object::COFFObjectFile::getRelocationTypeName(), llvm::ConstantDataArray::getString(), llvm::TargetLoweringObjectFile::getSymbolWithGlobalValueBase(), llvm::hash_value(), llvm::Timer::init(), isAllZeros(), llvm::AsmLexer::LexUntilEndOfLine(), llvm::AsmLexer::LexUntilEndOfStatement(), llvm::sys::fs::make_absolute(), mangleCoveragePath(), llvm::opt::OptTable::OptTable(), llvm::DWARFDebugLoc::parse(), llvm::DWARFDebugLocDWO::parse(), llvm::InlineAsm::ConstraintInfo::Parse(), llvm::InlineAsm::ParseConstraints(), parseDouble(), parsePhysicalReg(), prependCompressionHeader(), printName(), llvm::Regex::Regex(), llvm::sys::path::replace_extension(), llvm::yaml::final::ScalarNode(), llvm::EngineBuilder::setMArch(), llvm::EngineBuilder::setMCPU(), llvm::TimerGroup::setName(), llvm::Regex::sub(), WriteAttributeGroupTable(), and WriteModuleMetadataStore().
bool llvm::StringRef::endswith (StringRef Suffix) const [inline]
Check if this string ends with the given Suffix.
Definition at line 214 of file StringRef.h.
Referenced by llvm::StringTableBuilder::finalize(), llvm::ARMTargetParser::getCanonicalArchName(), llvm::opt::ArgList::GetOrMakeJoinedArgString(), llvm::ARMTargetParser::parseArch(), llvm::ARMTargetParser::parseArchEndian(), and llvm::UpgradeIntrinsicCall().
bool StringRef::endswith_lower (StringRef Suffix) const
Check if this string ends with the given Suffix, ignoring case.
Definition at line 67 of file StringRef.cpp.
References ascii_strncasecmp(), and end().
bool llvm::StringRef::equals (StringRef RHS) const [inline]
equals - Check for string equality, this is more efficient than compare() when the relative ordering of inequal strings isn't needed.
Definition at line 132 of file StringRef.h.
Referenced by count(), llvm::SmallString< 256 >::equals_lower(), find(), llvm::GetUnrollMetadata(), llvm::yaml::isBool(), isGCLeafFunction(), isGCSafepointPoll(), llvm::yaml::isNull(), llvm::yaml::isNumber(), llvm::yaml::isNumeric(), llvm::operator==(), parseBPFArch(), parseSegmentLoadCommand(), and rfind().
bool llvm::StringRef::equals_lower (StringRef RHS) const [inline]
equals_lower - Check for string equality, ignoring case.
Definition at line 138 of file StringRef.h.
Referenced by llvm::SmallString< 256 >::compare(), llvm::PPCTargetLowering::getRegForInlineAsmConstraint(), and llvm::StrInStrNoCase().
size_t llvm::StringRef::find (char C, size_t From = 0) const [inline]
Search for the first character C in the string.
Returns:
The index of the first occurrence of C, or npos if not found.
Definition at line 228 of file StringRef.h.
References P.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), CommaSeparateAndAddOccurrence(), emitComments(), llvm::RuntimeDyldCheckerExprEval::evaluate(), llvm::SmallString< 256 >::find(), llvm::ARMTargetParser::getCanonicalArchName(), llvm::getConstantStringInfo(), llvm::DataExtractor::getCStr(), llvm::object::ArchiveMemberHeader::getName(), llvm::object::Archive::Child::getName(), getObjCClassCategory(), getObjCMethodName(), llvm::object::ELFFile< ELFT >::getSymbolVersion(), GlobalWasGeneratedByAsan(), llvm::object::MachOObjectFile::guessLibraryShortName(), hasObjCCategory(), llvm::ConstantDataSequential::isCString(), llvm::objcarc::IsObjCIdentifiedObject(), parseRefinementStep(), llvm::SmallString< 256 >::rfind(), sanitizeFunctionName(), and split().
size_t StringRef::find (StringRef Str, size_t From = 0) const
Search for the first string Str in the string.
find - Search for the first string
Returns:
The index of the first occurrence of Str, or npos if not found.
Str in the string.
Returns:
- The index of the first occurrence of
Str, or npos if not found.
Definition at line 142 of file StringRef.cpp.
References equals(), fuzzer::min(), N, npos, size(), and substr().
StringRef::size_type StringRef::find_first_not_of (char C, size_t From = 0) const
Find the first character in the string that is not C or npos if not found.
find_first_not_of - Find the first character in the string that is not
C or npos if not found.
Definition at line 212 of file StringRef.cpp.
References fuzzer::min(), and npos.
Referenced by llvm::DWARFContextInMemory::DWARFContextInMemory(), llvm::SmallString< 256 >::find_first_not_of(), llvm::SmallString< 256 >::find_last_of(), llvm::getToken(), llvm::yaml::isNumber(), matchAsm(), llvm::yaml::needsQuotes(), printName(), and llvm::Regex::sub().
StringRef::size_type StringRef::find_first_not_of (StringRef Chars, size_t From = 0) const
Find the first character in the string that is not in the string Chars, or npos if not found.
find_first_not_of - Find the first character in the string that is not in the string
Complexity: O(size() + Chars.size())
Chars, or npos if not found.
Note: O(size() + Chars.size())
Definition at line 223 of file StringRef.cpp.
References fuzzer::min(), npos, and size().
size_t llvm::StringRef::find_first_of (char C, size_t From = 0) const [inline]
Find the first character in the string that is C, or npos if not found.
Same as find.
Definition at line 267 of file StringRef.h.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::sys::fs::createTemporaryFile(), llvm::SmallString< 256 >::find_first_not_of(), llvm::SmallString< 256 >::find_first_of(), llvm::getToken(), llvm::Regex::isLiteralERE(), and llvm::PassBuilder::parsePassPipeline().
StringRef::size_type StringRef::find_first_of (StringRef Chars, size_t From = 0) const
Find the first character in the string that is in Chars, or npos if not found.
find_first_of - Find the first character in the string that is in
Complexity: O(size() + Chars.size())
Chars, or npos if not found.
Note: O(size() + Chars.size())
Definition at line 198 of file StringRef.cpp.
References fuzzer::min(), npos, and size().
StringRef::size_type StringRef::find_last_not_of (char C, size_t From = npos) const
Find the last character in the string that is not C, or npos if not found.
find_last_not_of - Find the last character in the string that is not
C, or npos if not found.
Definition at line 253 of file StringRef.cpp.
References fuzzer::min(), and npos.
StringRef::size_type StringRef::find_last_not_of (StringRef Chars, size_t From = npos) const
Find the last character in the string that is not in Chars, or npos if not found.
find_last_not_of - Find the last character in the string that is not in
Complexity: O(size() + Chars.size())
Chars, or npos if not found.
Note: O(size() + Chars.size())
Definition at line 264 of file StringRef.cpp.
References fuzzer::min(), npos, and size().
size_t llvm::StringRef::find_last_of (char C, size_t From = npos) const [inline]
Find the last character in the string that is C, or npos if not found.
Definition at line 289 of file StringRef.h.
Referenced by llvm::SmallString< 256 >::count(), llvm::sys::path::extension(), llvm::SmallString< 256 >::find_last_of(), llvm::SourceMgr::getLineAndColumn(), llvm::yaml::Node::getVerbatimTag(), llvm::sys::path::replace_extension(), and llvm::sys::path::stem().
StringRef::size_type StringRef::find_last_of (StringRef Chars, size_t From = npos) const
Find the last character in the string that is in C, or npos if not found.
find_last_of - Find the last character in the string that is in
Complexity: O(size() + Chars.size())
C, or npos if not found.
Note: O(size() + Chars.size())
Definition at line 239 of file StringRef.cpp.
References fuzzer::min(), npos, and size().
char llvm::StringRef::front () const [inline]
front - Get the first character in the string.
Definition at line 112 of file StringRef.h.
Referenced by getAsInteger(), llvm::getAsSignedInteger(), llvm::yaml::isNumeric(), llvm::yaml::needsQuotes(), and parsePhysicalReg().
template<typename T > std::enable_if<std::numeric_limits<T>::is_signed, bool>::type llvm::StringRef::getAsInteger (unsigned Radix, T & Result) const [inline]
Parse the current string as an integer of the specified radix.
If Radix is specified as zero, this does radix autosensing using extended C rules: 0 is octal, 0x is hex, 0b is binary.
If the string is invalid or if only a subset of the string is valid, this returns true to signify the error. The string is considered erroneous if empty or if it overflows T.
Definition at line 333 of file StringRef.h.
Referenced by llvm::AMDGPUMachineFunction::AMDGPUMachineFunction(), llvm::object::Archive::Child::Child(), EmitGCCInlineAsmStr(), llvm::X86FrameLowering::emitPrologue(), getInt(), llvm::object::Archive::Child::getName(), llvm::SITargetLowering::getRegForInlineAsmConstraint(), llvm::MCSectionMachO::ParseSectionSpecifier(), ReplaceWithStatepoint(), llvm::StackProtector::runOnFunction(), llvm::Regex::sub(), WindowsRequiresStackProbe(), and llvm::yaml::BinaryRef::writeAsBinary().
template<typename T > std::enable_if<!std::numeric_limits<T>::is_signed, bool>::type llvm::StringRef::getAsInteger (unsigned Radix, T & Result) const [inline]
Definition at line 344 of file StringRef.h.
References llvm::getAsSignedInteger().
bool StringRef::getAsInteger (unsigned Radix, APInt & Result) const
Parse the current string as an integer of the specified Radix, or of an autosensed radix if the Radix given is 0.
The current value in Result is discarded, and the storage is changed to be wide enough to store the parsed integer.
Returns:
true if the string does not solely consist of a valid non-empty number in the appropriate base.
APInt::fromString is superficially similar but assumes the string is well-formed in the given radix.
Definition at line 406 of file StringRef.cpp.
References empty(), front(), GetAutoSenseRadix(), llvm::APInt::getBitWidth(), size(), substr(), and llvm::APInt::zext().
std::string StringRef::lower () const
Definition at line 117 of file StringRef.cpp.
References ascii_tolower(), and size().
Referenced by llvm::SubtargetFeatures::AddFeature(), llvm::MipsTargetAsmStreamer::emitDirectiveCpLoad(), llvm::MipsTargetAsmStreamer::emitDirectiveCpsetup(), llvm::MipsTargetAsmStreamer::emitFrame(), llvm::SparcTargetAsmStreamer::emitSparcRegisterIgnore(), llvm::SparcTargetAsmStreamer::emitSparcRegisterScratch(), llvm::AArch64NamedImmMapper::fromString(), llvm::AArch64SysReg::SysRegMapper::fromString(), getBankedRegisterMask(), getMClassRegisterSYSmValueMask(), llvm::MipsAsmPrinter::printOperand(), llvm::SparcInstPrinter::printRegName(), llvm::XCoreInstPrinter::printRegName(), and llvm::MipsInstPrinter::printRegName().
StringRef llvm::StringRef::ltrim (StringRef Chars = " \t\n\v\f\r") const [inline]
Return string with consecutive characters in Chars starting from the left removed.
Definition at line 493 of file StringRef.h.
Referenced by llvm::RuntimeDyldCheckerExprEval::evaluate(), and llvm::opt::OptTable::ParseOneArg().
llvm::StringRef::operator std::string () const [inline]
Definition at line 198 of file StringRef.h.
char llvm::StringRef::operator[] (size_t Index) const [inline]
Definition at line 191 of file StringRef.h.
size_t llvm::StringRef::rfind (char C, size_t From = npos) const [inline]
Search for the last character C in the string.
Returns:
The index of the last occurrence of C, or npos if not found.
Definition at line 248 of file StringRef.h.
Referenced by llvm::SmallString< 256 >::find_first_of(), llvm::object::MachOObjectFile::guessLibraryShortName(), llvm::SmallString< 256 >::rfind(), and rtrim().
size_t StringRef::rfind (StringRef Str) const
Search for the last string Str in the string.
rfind - Search for the last string
Returns:
The index of the last occurrence of Str, or npos if not found.
Str in the string.
Returns:
- The index of the last occurrence of
Str, or npos if not found.
Definition at line 182 of file StringRef.cpp.
References equals(), N, npos, size(), and substr().
std::pair<StringRef, StringRef> llvm::StringRef::rsplit (char Separator) const [inline]
Split into two substrings around the last occurrence of a separator character.
If Separator is in the string, then the result is a pair (LHS, RHS) such that (*this == LHS + Separator + RHS) is true and RHS is minimal. If Separator is not in the string, then the result is a pair (LHS, RHS) where (*this == LHS) and (RHS == "").
Parameters:
Separator - The character to split on.
Returns:
- The split substrings.
Definition at line 484 of file StringRef.h.
Referenced by llvm::HexagonAsmInstPrinter::printInst().
StringRef llvm::StringRef::rtrim (StringRef Chars = " \t\n\v\f\r") const [inline]
Return string with consecutive characters in Chars starting from the right removed.
Definition at line 499 of file StringRef.h.
References npos, and rfind().
Referenced by llvm::object::Archive::Child::Child(), llvm::RuntimeDyldCheckerExprEval::evaluate(), llvm::object::Archive::Child::getName(), and llvm::object::ArchiveMemberHeader::getRawLastModified().
size_t llvm::StringRef::size () const [inline]
size - Get the string size.
Definition at line 109 of file StringRef.h.
Referenced by llvm::FoldingSetNodeID::AddString(), llvm::APSInt::APSInt(), llvm::StringSwitch< T, R >::Case(), llvm::RuntimeDyldCheckerImpl::checkAllRulesInBuffer(), llvm::sys::locale::columnWidth(), llvm::sys::unicode::columnWidthUTF8(), compareBySuffix(), compareWithScalarFnName(), compareWithVectorFnName(), llvm::ConstantFoldLoadFromConstPtr(), llvm::APFloat::convertFromString(), llvm::convertUTF8ToUTF16String(), llvm::ConvertUTF8toWide(), CopyStringRef(), count(), llvm::StringMapEntry< MDString >::Create(), llvm::X86Operand::CreateToken(), decodeBase64StringEntry(), dumpPubSection(), edit_distance(), llvm::object::elf_hash(), llvm::object::ELFFile< ELFT >::ELFFile(), llvm::emitSourceFileHeader(), llvm::sys::path::end(), llvm::StringSwitch< T, R >::EndsWith(), llvm::Regex::escape(), llvm::sys::path::extension(), find(), find_first_not_of(), find_first_of(), find_last_not_of(), find_last_of(), llvm::DWARFUnit::getAddrOffsetSectionItem(), llvm::ConstantDataSequential::getAsCString(), getAsInteger(), llvm::APInt::getBitsNeeded(), llvm::MemoryBufferRef::getBufferSize(), llvm::ARMTargetParser::getCanonicalArchName(), llvm::object::getElfArchType(), llvm::AsmToken::getEndLoc(), llvm::DwarfStringPool::getEntry(), llvm::Triple::getEnvironmentVersion(), getFuncNameWithoutPrefix(), llvm::object::MachOObjectFile::getIndirectName(), GetLazyPtr(), llvm::MDString::getLength(), llvm::TargetLibraryInfoImpl::getLibFunc(), llvm::object::MachOObjectFile::getLibraryShortNameByIndex(), llvm::MemoryBuffer::getMemBufferCopy(), getMemsetStringVal(), llvm::object::Archive::Child::getName(), llvm::MemoryBuffer::getNewUninitMemBuffer(), getOptionPred(), llvm::opt::ArgList::GetOrMakeJoinedArgString(), llvm::Triple::getOSVersion(), llvm::SITargetLowering::getRegForInlineAsmConstraint(), llvm::ConstantDataArray::getString(), llvm::AsmToken::getStringContents(), GetStringLengthH(), llvm::DWARFUnit::getStringOffsetSectionItem(), llvm::object::ELFFile< ELFT >::getSymbolVersion(), getUnicodeEncoding(), llvm::object::MachOObjectFile::guessLibraryShortName(), HandlePrefixedOrGroupedOption(), llvm::HashString(), llvm::sys::fs::identify_magic(), llvm::ExecutionEngine::InitializeMemory(), llvm::NVPTXSubtarget::initializeSubtargetDependencies(), isRepeatedByteSequence(), llvm::DataExtractor::isValidOffset(), llvm::join_impl(), LLVMGetAsString(), LLVMTargetMachineEmitToMemoryBuffer(), loadTestingFormat(), lower(), llvm::object::MachOUniversalBinary::MachOUniversalBinary(), llvm::MCGenDwarfLabelEntry::Make(), llvm::Regex::match(), MatchCoprocessorOperandName(), matchOption(), llvm::object::MachOUniversalBinary::ObjectForArch::ObjectForArch(), operator new(), llvm::raw_ostream::operator<<(), llvm::DWARFDebugLocDWO::parse(), parseBackslash(), parseRefinementStep(), parseSectionFlags(), llvm::MCSectionMachO::ParseSectionSpecifier(), prependCompressionHeader(), PrintEscapedString(), PrintHelpOptionList(), printLine(), PrintLLVMName(), printMetadataIdentifier(), PrintQuotedString(), printSourceLine(), llvm::sys::path::rbegin(), readCoverageMappingData(), llvm::GCOVBuffer::readInt(), llvm::RawInstrProfReader< IntPtrT >::readNextRecord(), llvm::sampleprof::SampleProfileReaderBinary::readString(), llvm::GCOVBuffer::readString(), llvm::LessRecordRegister::RecordParts::RecordParts(), llvm::sys::path::relative_path(), llvm::sys::path::replace_extension(), replaceSubString(), llvm::report_fatal_error(), RequiresVFPRegListValidation(), llvm::RuntimeDyldImpl::resolveExternalSymbols(), RewriteIntelBracExpression(), rfind(), llvm::StringSaver::saveImpl(), llvm::yaml::Output::scalarString(), llvm::StructType::setName(), llvm::X86Operand::setTokenValue(), slice(), split(), llvm::StringSwitch< T, R >::StartsWith(), llvm::sys::path::stem(), llvm::StrInStrNoCase(), llvm::Regex::sub(), llvm::cl::TokenizeGNUCommandLine(), llvm::cl::TokenizeWindowsCommandLine(), llvm::MD5::update(), UpgradeIntrinsicFunction1(), upper(), llvm::raw_ostream::write_escaped(), llvm::writeArchive(), llvm::MachObjectWriter::writeObject(), WriteStringRecord(), and writeStringTable().
StringRef llvm::StringRef::slice (size_t Start, size_t End) const [inline]
Return a reference to the substring from [Start, End).
Parameters:
Start The index of the starting character in the substring; if the index is npos or greater than the length of the string then the empty substring will be returned.
End The index following the last character to include in the substring. If this is npos, or less than Start, or exceeds the number of characters remaining in the string, the string suffix (starting with Start) will be returned.
Definition at line 416 of file StringRef.h.
References N, size(), and substr().
Referenced by llvm::SmallString< 256 >::c_str(), llvm::object::ObjectFile::createMachOObjectFile(), getObjCClassCategory(), getObjCMethodName(), llvm::AsmToken::getStringContents(), llvm::getToken(), llvm::object::MachOObjectFile::guessLibraryShortName(), llvm::GCOVBuffer::readArcTag(), llvm::GCOVBuffer::readBlockTag(), llvm::GCOVBuffer::readEdgeTag(), llvm::GCOVBuffer::readFunctionTag(), llvm::GCOVBuffer::readGCDAFormat(), llvm::GCOVBuffer::readGCNOFormat(), llvm::GCOVBuffer::readGCOVVersion(), llvm::GCOVBuffer::readInt(), llvm::GCOVBuffer::readLineTag(), llvm::GCOVBuffer::readObjectTag(), llvm::GCOVBuffer::readProgramTag(), llvm::GCOVBuffer::readString(), split(), and llvm::Regex::sub().
std::pair<StringRef, StringRef> llvm::StringRef::split (char Separator) const [inline]
Split into two substrings around the first occurrence of a separator character.
If Separator is in the string, then the result is a pair (LHS, RHS) such that (*this == LHS + Separator + RHS) is true and RHS is maximal. If Separator is not in the string, then the result is a pair (LHS, RHS) where (*this == LHS) and (RHS == "").
Parameters:
Separator The character to split on.
Returns:
The split substrings.
Definition at line 432 of file StringRef.h.
References fuzzer::min(), and StringRef().
Referenced by llvm::Triple::getArchName(), llvm::Triple::getEnvironmentName(), getIntOperandFromRegisterString(), getIntOperandsFromRegisterString(), llvm::Triple::getOSAndEnvironmentName(), llvm::Triple::getOSName(), getSearchPaths(), llvm::Triple::getVendorName(), LookupNearestOption(), llvm::Triple::normalize(), llvm::MCSectionMachO::ParseSectionSpecifier(), printHelpStr(), llvm::HexagonAsmInstPrinter::printInst(), llvm::GCOVBuffer::readString(), Split(), split(), split(), llvm::Regex::sub(), and UsesVectorABI().
std::pair<StringRef, StringRef> llvm::StringRef::split (StringRef Separator) const [inline]
Split into two substrings around the first occurrence of a separator string.
If Separator is in the string, then the result is a pair (LHS, RHS) such that (*this == LHS + Separator + RHS) is true and RHS is maximal. If Separator is not in the string, then the result is a pair (LHS, RHS) where (*this == LHS) and (RHS == "").
Parameters:
Separator - The string to split on.
Returns:
- The split substrings.
Definition at line 449 of file StringRef.h.
References find(), npos, slice(), and StringRef().
void StringRef::split (SmallVectorImpl< StringRef > & A, StringRef Separator, int MaxSplit = -1, bool KeepEmpty = true) const
Split into substrings around the occurrences of a separator string.
Each substring is stored in A. If MaxSplit is >= 0, at most MaxSplit splits are done and consequently <= MaxSplit elements are added to A. If KeepEmpty is false, empty strings are not added to A. They still count when considering MaxSplit An useful invariant is that Separator.join(A) == *this if MaxSplit == -1 and KeepEmpty == true
Parameters:
A - Where to put the substrings.
Separator - The string to split on.
MaxSplit - The maximum number of times the string is split.
KeepEmpty - True if empty substring should be added.
Definition at line 276 of file StringRef.cpp.
References data(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), size(), and split().
bool llvm::StringRef::startswith (StringRef Prefix) const [inline]
Check if this string starts with the given Prefix.
Definition at line 205 of file StringRef.h.
References str().
Referenced by llvm::object::Archive::Archive(), llvm::ARMBuildAttrs::AttrTypeFromString(), llvm::RuntimeDyldCheckerImpl::checkAllRulesInBuffer(), llvm::object::Archive::Child::Child(), CloneLoopBlocks(), llvm::MipsABIInfo::computeTargetABI(), computeTargetABI(), consumeCompressedDebugSectionHeader(), doesIgnoreDataTypeSuffix(), llvm::DWARFContextInMemory::DWARFContextInMemory(), llvm::SmallString< 256 >::endswith(), GetAutoSenseRadix(), llvm::ARMTargetParser::getCanonicalArchName(), llvm::TargetLoweringObjectFileMachO::getDepLibFromLinkerOpt(), llvm::TargetLoweringObjectFileCOFF::getDepLibFromLinkerOpt(), getELFKindForNamedSection(), llvm::Triple::getEnvironmentVersion(), llvm::XCoreTargetObjectFile::getExplicitSectionGlobal(), getFuncNameWithoutPrefix(), getName(), llvm::object::Archive::Child::getName(), llvm::Mangler::getNameWithPrefix(), llvm::opt::ArgList::GetOrMakeJoinedArgString(), llvm::Triple::getOSVersion(), llvm::object::IRObjectFile::getSymbolFlags(), llvm::WinEH::getUnwindInfoSection(), llvm::yaml::Node::getVerbatimTag(), llvm::object::MachOObjectFile::guessLibraryShortName(), INITIALIZE_PASS(), llvm::LTOModule::isBitcodeForTarget(), isInput(), llvm::Function::isIntrinsic(), llvm::yaml::isNumber(), isObjCClass(), llvm::objcarc::IsObjCIdentifiedObject(), llvm::MCGenDwarfLabelEntry::Make(), matchAsm(), matchOption(), llvm::orc::GlobalRenamer::needsRenaming(), llvm::Triple::normalize(), llvm::ARMTargetParser::parseArchEndian(), parseARMArch(), parseVersionFromName(), llvm::TextInstrProfReader::readNextRecord(), RequiresVFPRegListValidation(), SetLoopAlreadyUnrolled(), llvm::StripDebugInfo(), StripSymtab(), StripTypeNames(), llvm::UpgradeIntrinsicCall(), and UpgradeIntrinsicFunction1().
bool StringRef::startswith_lower (StringRef Prefix) const
Check if this string starts with the given Prefix, ignoring case.
Definition at line 61 of file StringRef.cpp.
References ascii_strncasecmp().
Referenced by matchOption().
std::string llvm::StringRef::str () const [inline]
str - Get the contents as an std::string.
Definition at line 184 of file StringRef.h.
Referenced by llvm::DwarfCompileUnit::addGlobalName(), llvm::DwarfCompileUnit::addGlobalType(), cacheAnnotationFromMD(), findInputFile(), llvm::bfi_detail::getBlockName(), llvm::DOTGraphTraits< const Function * >::getGraphName(), llvm::DOTGraphTraits< MachineBlockFrequencyInfo * >::getNodeLabel(), llvm::DOTGraphTraits< const Function * >::getSimpleNodeLabel(), llvm::AArch64TargetMachine::getSubtargetImpl(), llvm::PPCTargetMachine::getSubtargetImpl(), llvm::ARMBaseTargetMachine::getSubtargetImpl(), llvm::MipsTargetMachine::getSubtargetImpl(), llvm::Record::getValueAsBitOrUnset(), llvm::yaml::ScalarTraits< StringValue >::input(), mangleCoveragePath(), llvm::cl::final< DataType >::parse(), llvm::sys::fs::directory_entry::replace_filename(), llvm::DOTGraphTraitsViewer< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::runOnFunction(), llvm::DOTGraphTraitsPrinter< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::runOnFunction(), llvm::MCContext::setCompilationDir(), llvm::MCParsedAsmOperand::setConstraint(), startswith(), and llvm::Twine::str().
StringRef llvm::StringRef::substr (size_t Start, size_t N = npos) const [inline]
Return a reference to the substring from [Start, Start + N).
Parameters:
Start The index of the starting character in the substring; if the index is npos or greater than the length of the string then the empty substring will be returned.
N The number of characters to included in the substring. If N exceeds the number of characters remaining in the string, the string suffix (starting with Start) will be returned.
Definition at line 387 of file StringRef.h.
Referenced by llvm::RuntimeDyldCheckerImpl::checkAllRulesInBuffer(), llvm::object::Archive::Child::Child(), CommaSeparateAndAddOccurrence(), consumeCompressedDebugSectionHeader(), count(), decodeBase64StringEntry(), llvm::DWARFContextInMemory::DWARFContextInMemory(), EatNumber(), emitComments(), llvm::emitSourceFileHeader(), llvm::RuntimeDyldCheckerExprEval::evaluate(), llvm::sys::path::extension(), llvm::DWARFFormValue::extractValue(), find(), llvm::object::MachOUniversalBinary::ObjectForArch::getAsArchive(), llvm::ConstantDataSequential::getAsCString(), getAsInteger(), llvm::object::MachOUniversalBinary::ObjectForArch::getAsObjectFile(), llvm::getAsSignedInteger(), llvm::getAsUnsignedInteger(), GetAutoSenseRadix(), llvm::ARMTargetParser::getCanonicalArchName(), llvm::getConstantStringInfo(), llvm::TargetLoweringObjectFileMachO::getDepLibFromLinkerOpt(), llvm::TargetLoweringObjectFileCOFF::getDepLibFromLinkerOpt(), llvm::Triple::getEnvironmentVersion(), GetLazyPtr(), getMemcpyLoadsAndStores(), getName(), llvm::object::Archive::Child::getName(), getNameWithPrefixImpl(), getOptionPred(), llvm::Triple::getOSVersion(), llvm::GlobalValue::getRealLinkageName(), llvm::SITargetLowering::getRegForInlineAsmConstraint(), llvm::object::MachOObjectFile::getSectionContents(), llvm::object::MachOObjectFile::getStringTableData(), GetSymbolFromOperand(), llvm::object::ELFFile< ELFT >::getSymbolVersion(), llvm::getToken(), llvm::WinEH::getUnwindInfoSection(), llvm::yaml::Node::getVerbatimTag(), HandlePrefixedOrGroupedOption(), loadTestingFormat(), llvm::MCGenDwarfLabelEntry::Make(), matchAsm(), matchOption(), llvm::sys::path::parent_path(), llvm::DWARFDebugLoc::parse(), llvm::DWARFDebugLocDWO::parse(), llvm::yaml::Document::parseBlockNode(), llvm::PassBuilder::parsePassPipeline(), parseRefinementStep(), parseVersionFromName(), llvm::sys::path::relative_path(), llvm::sys::path::rend(), RequiresVFPRegListValidation(), rfind(), llvm::sys::path::root_path(), llvm::SmallString< 256 >::slice(), slice(), llvm::sys::path::stem(), llvm::StrInStrNoCase(), StripFlag(), llvm::Regex::sub(), llvm::UpgradeIntrinsicCall(), and UpgradeIntrinsicFunction1().
StringRef llvm::StringRef::trim (StringRef Chars = " \t\n\v\f\r") const [inline]
Return string with consecutive characters in Chars starting from the left and right removed.
Definition at line 505 of file StringRef.h.
Referenced by llvm::RuntimeDyldCheckerImpl::check(), and llvm::RuntimeDyldCheckerExprEval::evaluate().
std::string StringRef::upper () const
Convert the given ASCII string to uppercase.
Definition at line 125 of file StringRef.cpp.
References ascii_toupper(), and size().
Referenced by llvm::AArch64InstPrinter::printMRSSystemRegister(), llvm::AArch64InstPrinter::printMSRSystemRegister(), and llvm::AArch64InstPrinter::printSystemPStateField().
Member Data Documentation
const size_t StringRef::npos = ~size_t(0) [static]
Definition at line 44 of file StringRef.h.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), buildFixItLine(), CommaSeparateAndAddOccurrence(), llvm::sys::fs::createTemporaryFile(), llvm::sys::path::extension(), find(), find_first_not_of(), find_first_of(), find_last_not_of(), find_last_of(), llvm::ARMTargetParser::getCanonicalArchName(), llvm::DataExtractor::getCStr(), llvm::SourceMgr::getLineAndColumn(), llvm::object::ArchiveMemberHeader::getName(), llvm::object::ELFFile< ELFT >::getSymbolVersion(), llvm::object::MachOObjectFile::guessLibraryShortName(), hasObjCCategory(), llvm::ConstantDataSequential::isCString(), llvm::Regex::isLiteralERE(), llvm::yaml::isNumber(), llvm::objcarc::IsObjCIdentifiedObject(), llvm::yaml::needsQuotes(), llvm::sys::path::parent_path(), parseRefinementStep(), printName(), llvm::AArch64InstPrinter::printSysAlias(), llvm::sys::path::remove_filename(), llvm::sys::path::replace_extension(), rfind(), rtrim(), sanitizeFunctionName(), split(), llvm::sys::path::stem(), and llvm::StrInStrNoCase().
The documentation for this class was generated from the following files:
StringRef.h
StringRef.cpp