LLVM: llvm::MCDwarfLineAddrFragment Class Reference
llvm::MCDwarfLineAddrFragment Class Reference
#include <MCAssembler.h>
Public Member Functions
MCDwarfLineAddrFragment (int64_t LineDelta, const MCExpr &AddrDelta, MCSection *Sec=nullptr)
Accessors
int64_t getLineDelta () const
const MCExpr & getAddrDelta () const
SmallString< 8 > & getContents ()
const SmallString< 8 > & getContents () const
Static Public Member Functions
static bool classof (const MCFragment *F)
Detailed Description
Definition at line 429 of file MCAssembler.h.
Constructor & Destructor Documentation
llvm::MCDwarfLineAddrFragment::MCDwarfLineAddrFragment (int64_t LineDelta, const MCExpr & AddrDelta, MCSection * Sec = nullptr) [inline]
Definition at line 442 of file MCAssembler.h.
References llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Member Function Documentation
static bool llvm::MCDwarfLineAddrFragment::classof (const MCFragment * F) [inline, static]
Definition at line 461 of file MCAssembler.h.
References llvm::MCFragment::FT_Dwarf, and llvm::MCFragment::getKind().
const MCExpr& llvm::MCDwarfLineAddrFragment::getAddrDelta () const [inline]
Definition at line 454 of file MCAssembler.h.
Referenced by llvm::MCFragment::dump().
SmallString<8>& llvm::MCDwarfLineAddrFragment::getContents () [inline]
Definition at line 456 of file MCAssembler.h.
Referenced by writeFragment().
const SmallString<8>& llvm::MCDwarfLineAddrFragment::getContents () const [inline]
Definition at line 457 of file MCAssembler.h.
int64_t llvm::MCDwarfLineAddrFragment::getLineDelta () const [inline]
Definition at line 452 of file MCAssembler.h.
Referenced by llvm::MCFragment::dump().
The documentation for this class was generated from the following file:
MCAssembler.h