LLVM: llvm::LoopAccessAnalysis Class Reference
llvm::LoopAccessAnalysis Class Reference
This analysis provides dependence information for the memory accesses of a loop.
#include <LoopAccessAnalysis.h>
Public Member Functions
LoopAccessAnalysis ()
bool runOnFunction (Function &F) override
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
const LoopAccessInfo & getInfo (Loop *L, const ValueToValueMap &Strides)
Query the result of the loop access information for the loop L.
void releaseMemory () override
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
void print (raw_ostream &OS, const Module *M=nullptr) const override
Print the result of the analysis when invoked with -analyze.
Static Public Attributes
static char ID = 0
Detailed Description
This analysis provides dependence information for the memory accesses of a loop.
It runs the analysis for a loop on demand. This can be initiated by querying the loop access info via LAA::getInfo. getInfo return a LoopAccessInfo object. See this class for the specifics of what information is provided.
Definition at line 519 of file LoopAccessAnalysis.h.
Constructor & Destructor Documentation
llvm::LoopAccessAnalysis::LoopAccessAnalysis () [inline]
Definition at line 523 of file LoopAccessAnalysis.h.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeLoopAccessAnalysisPass().
Member Function Documentation
void LoopAccessAnalysis::getAnalysisUsage (AnalysisUsage &) const [override, virtual]
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 1483 of file LoopAccessAnalysis.cpp.
References llvm::AnalysisUsage::addRequired(), and llvm::AnalysisUsage::setPreservesAll().
const LoopAccessInfo & LoopAccessAnalysis::getInfo (Loop * L, const ValueToValueMap & Strides)
Query the result of the loop access information for the loop L.
If the client speculates (and then issues run-time checks) for the values of symbolic strides, Strides provides the mapping (see replaceSymbolicStrideSCEV). If there is no cached result available run the analysis.
Definition at line 1440 of file LoopAccessAnalysis.cpp.
References llvm::DL, llvm::Module::getDataLayout(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::BasicBlock::getModule(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size().
Referenced by print().
void LoopAccessAnalysis::print (raw_ostream & OS, const Module * M = nullptr) const [override, virtual]
Print the result of the analysis when invoked with -analyze.
Reimplemented from llvm::Pass.
Definition at line 1459 of file LoopAccessAnalysis.cpp.
References llvm::depth_first(), getInfo(), llvm::raw_ostream::indent(), and llvm::LoopAccessInfo::print().
void llvm::LoopAccessAnalysis::releaseMemory () [inline, override, virtual]
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 539 of file LoopAccessAnalysis.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear().
bool LoopAccessAnalysis::runOnFunction (Function & F) [override, virtual]
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
Implements llvm::FunctionPass.
Definition at line 1472 of file LoopAccessAnalysis.cpp.
Member Data Documentation
char LoopAccessAnalysis::ID = 0 [static]
Definition at line 521 of file LoopAccessAnalysis.h.
The documentation for this class was generated from the following files:
LoopAccessAnalysis.h
LoopAccessAnalysis.cpp