LLVM: llvm::object::COFFSymbolRef Class Reference
llvm::object::COFFSymbolRef Class Reference
#include <COFF.h>
Public Member Functions
COFFSymbolRef (const coff_symbol16 *CS)
COFFSymbolRef (const coff_symbol32 *CS)
COFFSymbolRef ()
const void * getRawPtr () const
bool isBigObj () const
const char * getShortName () const
const StringTableOffset & getStringTableOffset () const
uint32_t getValue () const
int32_t getSectionNumber () const
uint16_t getType () const
uint8_t getStorageClass () const
uint8_t getNumberOfAuxSymbols () const
uint8_t getBaseType () const
uint8_t getComplexType () const
bool isAbsolute () const
bool isExternal () const
bool isCommon () const
bool isUndefined () const
bool isWeakExternal () const
bool isFunctionDefinition () const
bool isFunctionLineInfo () const
bool isAnyUndefined () const
bool isFileRecord () const
bool isSection () const
bool isSectionDefinition () const
bool isCLRToken () const
Friends
bool operator< (COFFSymbolRef A, COFFSymbolRef B)
Detailed Description
Definition at line 252 of file Object/COFF.h.
Constructor & Destructor Documentation
llvm::object::COFFSymbolRef::COFFSymbolRef (const coff_symbol16 * CS) [inline]
Definition at line 254 of file Object/COFF.h.
llvm::object::COFFSymbolRef::COFFSymbolRef (const coff_symbol32 * CS) [inline]
Definition at line 255 of file Object/COFF.h.
llvm::object::COFFSymbolRef::COFFSymbolRef () [inline]
Definition at line 256 of file Object/COFF.h.
Member Function Documentation
uint8_t llvm::object::COFFSymbolRef::getBaseType () const [inline]
Definition at line 311 of file Object/COFF.h.
References getType().
Referenced by isFunctionDefinition().
uint8_t llvm::object::COFFSymbolRef::getComplexType () const [inline]
Definition at line 313 of file Object/COFF.h.
References getType(), and llvm::COFF::SCT_COMPLEX_TYPE_SHIFT.
Referenced by isFunctionDefinition().
uint8_t llvm::object::COFFSymbolRef::getNumberOfAuxSymbols () const [inline]
Definition at line 306 of file Object/COFF.h.
References llvm::object::coff_symbol< SectionNumberType >::NumberOfAuxSymbols.
Referenced by llvm::object::COFFObjectFile::getSymbolAuxData(), and isSectionDefinition().
const void* llvm::object::COFFSymbolRef::getRawPtr () const [inline]
Definition at line 258 of file Object/COFF.h.
Referenced by llvm::object::COFFObjectFile::getSymbolAuxData().
int32_t llvm::object::COFFSymbolRef::getSectionNumber () const [inline]
Definition at line 285 of file Object/COFF.h.
References llvm::COFF::MaxNumberOfSections16, and llvm::object::coff_symbol< SectionNumberType >::SectionNumber.
Referenced by llvm::object::COFFObjectFile::getSymbolAddress(), llvm::object::COFFObjectFile::getSymbolFlags(), llvm::object::COFFObjectFile::getSymbolSection(), llvm::object::COFFObjectFile::getSymbolType(), isAbsolute(), isCommon(), isFunctionDefinition(), isSectionDefinition(), isUndefined(), and llvm::object::COFFObjectFile::sectionContainsSymbol().
const char* llvm::object::COFFSymbolRef::getShortName () const [inline]
Definition at line 274 of file Object/COFF.h.
References llvm::object::coff_symbol< SectionNumberType >::Name, and llvm::object::coff_symbol< SectionNumberType >::ShortName.
uint8_t llvm::object::COFFSymbolRef::getStorageClass () const [inline]
Definition at line 301 of file Object/COFF.h.
References llvm::object::coff_symbol< SectionNumberType >::StorageClass.
Referenced by isCLRToken(), isExternal(), isFileRecord(), isFunctionLineInfo(), isSection(), isSectionDefinition(), and isWeakExternal().
const StringTableOffset& llvm::object::COFFSymbolRef::getStringTableOffset () const [inline]
Definition at line 278 of file Object/COFF.h.
References llvm::object::coff_symbol< SectionNumberType >::Name, and llvm::object::coff_symbol< SectionNumberType >::Offset.
uint16_t llvm::object::COFFSymbolRef::getType () const [inline]
Definition at line 296 of file Object/COFF.h.
References llvm::object::coff_symbol< SectionNumberType >::Type.
Referenced by getBaseType(), and getComplexType().
uint32_t llvm::object::COFFSymbolRef::getValue () const [inline]
Definition at line 283 of file Object/COFF.h.
References llvm::object::coff_symbol< SectionNumberType >::Value.
Referenced by llvm::object::COFFObjectFile::getSymbolAddress(), llvm::object::COFFObjectFile::getSymbolSize(), isCommon(), and isUndefined().
bool llvm::object::COFFSymbolRef::isAbsolute () const [inline]
Definition at line 317 of file Object/COFF.h.
References getSectionNumber().
bool llvm::object::COFFSymbolRef::isAnyUndefined () const [inline]
Definition at line 349 of file Object/COFF.h.
References isUndefined(), and isWeakExternal().
Referenced by llvm::object::COFFObjectFile::getSymbolAddress(), llvm::object::COFFObjectFile::getSymbolFlags(), and llvm::object::COFFObjectFile::getSymbolType().
bool llvm::object::COFFSymbolRef::isBigObj () const [inline]
Definition at line 266 of file Object/COFF.h.
References llvm_unreachable.
bool llvm::object::COFFSymbolRef::isCLRToken () const [inline]
Definition at line 373 of file Object/COFF.h.
References getStorageClass(), and llvm::COFF::IMAGE_SYM_CLASS_CLR_TOKEN.
bool llvm::object::COFFSymbolRef::isCommon () const [inline]
Definition at line 325 of file Object/COFF.h.
References getSectionNumber(), getValue(), llvm::COFF::IMAGE_SYM_UNDEFINED, and isExternal().
Referenced by llvm::object::COFFObjectFile::getSymbolAddress(), llvm::object::COFFObjectFile::getSymbolFlags(), llvm::object::COFFObjectFile::getSymbolSize(), and llvm::object::COFFObjectFile::getSymbolType().
bool llvm::object::COFFSymbolRef::isExternal () const [inline]
Definition at line 321 of file Object/COFF.h.
References getStorageClass(), and llvm::COFF::IMAGE_SYM_CLASS_EXTERNAL.
Referenced by llvm::object::COFFObjectFile::getSymbolFlags(), isCommon(), isFunctionDefinition(), and isUndefined().
bool llvm::object::COFFSymbolRef::isFileRecord () const [inline]
Definition at line 353 of file Object/COFF.h.
References getStorageClass(), and llvm::COFF::IMAGE_SYM_CLASS_FILE.
Referenced by llvm::object::COFFObjectFile::getSymbolFlags(), and llvm::object::COFFObjectFile::getSymbolType().
bool llvm::object::COFFSymbolRef::isFunctionDefinition () const [inline]
Definition at line 339 of file Object/COFF.h.
References getBaseType(), getComplexType(), getSectionNumber(), llvm::COFF::IMAGE_SYM_DTYPE_FUNCTION, llvm::COFF::IMAGE_SYM_TYPE_NULL, isExternal(), and llvm::COFF::isReservedSectionNumber().
Referenced by llvm::object::COFFObjectFile::getSymbolType().
bool llvm::object::COFFSymbolRef::isFunctionLineInfo () const [inline]
Definition at line 345 of file Object/COFF.h.
References getStorageClass(), and llvm::COFF::IMAGE_SYM_CLASS_FUNCTION.
bool llvm::object::COFFSymbolRef::isSection () const [inline]
Definition at line 357 of file Object/COFF.h.
References getStorageClass(), and llvm::COFF::IMAGE_SYM_CLASS_SECTION.
bool llvm::object::COFFSymbolRef::isSectionDefinition () const [inline]
Definition at line 361 of file Object/COFF.h.
References getNumberOfAuxSymbols(), getSectionNumber(), getStorageClass(), llvm::COFF::IMAGE_SYM_ABSOLUTE, llvm::COFF::IMAGE_SYM_CLASS_EXTERNAL, and llvm::COFF::IMAGE_SYM_CLASS_STATIC.
Referenced by llvm::object::COFFObjectFile::getSymbolFlags(), and llvm::object::COFFObjectFile::getSymbolType().
bool llvm::object::COFFSymbolRef::isUndefined () const [inline]
Definition at line 330 of file Object/COFF.h.
References getSectionNumber(), getValue(), llvm::COFF::IMAGE_SYM_UNDEFINED, and isExternal().
Referenced by isAnyUndefined().
bool llvm::object::COFFSymbolRef::isWeakExternal () const [inline]
Definition at line 335 of file Object/COFF.h.
References getStorageClass(), and llvm::COFF::IMAGE_SYM_CLASS_WEAK_EXTERNAL.
Referenced by llvm::object::COFFObjectFile::getSymbolFlags(), and isAnyUndefined().
Friends And Related Function Documentation
bool operator< (COFFSymbolRef A, COFFSymbolRef B) [friend]
Definition at line 262 of file Object/COFF.h.
The documentation for this class was generated from the following file:
Object/COFF.h