LLVM: llvm::DwarfCFIException Class Reference
llvm::DwarfCFIException Class Reference
#include <DwarfException.h>
Public Member Functions
DwarfCFIException (AsmPrinter *A)
~DwarfCFIException () override
void endModule () override
Emit all exception information that should come after the content.
void beginFunction (const MachineFunction *MF) override
Gather pre-function exception information.
void endFunction (const MachineFunction *) override
Gather and emit post-function exception information.
Detailed Description
Definition at line 34 of file DwarfException.h.
Constructor & Destructor Documentation
DwarfCFIException::DwarfCFIException (AsmPrinter * A)
Definition at line 56 of file DwarfCFIException.cpp.
DwarfCFIException::~DwarfCFIException () [override]
Definition at line 61 of file DwarfCFIException.cpp.
Member Function Documentation
void DwarfCFIException::beginFunction (const MachineFunction * MF) [override, virtual]
Gather pre-function exception information.
Assumes being emitted immediately after the function entry point.
Implements llvm::AsmPrinterHandler.
Definition at line 90 of file DwarfCFIException.cpp.
References llvm::EHStreamer::Asm, llvm::AsmPrinter::CFI_M_Debug, llvm::AsmPrinter::CFI_M_EH, llvm::AsmPrinter::CFI_M_None, llvm::dwarf::DW_EH_PE_omit, llvm::TargetLoweringObjectFile::getCFIPersonalitySymbol(), llvm::AsmPrinter::getCurExceptionSym(), llvm::MachineModuleInfo::getLandingPads(), llvm::MCObjectFileInfo::getLSDAEncoding(), llvm::AsmPrinter::getObjFileLowering(), llvm::MachineModuleInfo::getPersonality(), llvm::MCObjectFileInfo::getPersonalityEncoding(), llvm::AsmPrinter::Mang, llvm::EHStreamer::MMI, llvm::AsmPrinter::needsCFIMoves(), llvm::AsmPrinter::OutStreamer, llvm::DwarfCFIExceptionBase::shouldEmitCFI, and llvm::AsmPrinter::TM.
void DwarfCFIException::endFunction (const MachineFunction *) [override, virtual]
Gather and emit post-function exception information.
endFunction - Gather and emit post-function exception information.
Implements llvm::AsmPrinterHandler.
Definition at line 139 of file DwarfCFIException.cpp.
References llvm::EHStreamer::emitExceptionTable().
void DwarfCFIException::endModule () [override, virtual]
Emit all exception information that should come after the content.
endModule - Emit all exception information that should come after the content.
Implements llvm::AsmPrinterHandler.
Definition at line 65 of file DwarfCFIException.cpp.
References llvm::EHStreamer::Asm, llvm::AsmPrinter::CFI_M_Debug, llvm::dwarf::DW_EH_PE_indirect, llvm::TargetLoweringObjectFile::emitPersonalityValue(), llvm::AsmPrinter::getObjFileLowering(), llvm::MachineModuleInfo::getPersonalities(), llvm::MCObjectFileInfo::getPersonalityEncoding(), llvm::AsmPrinter::getSymbol(), llvm::AsmPrinter::MAI, llvm::EHStreamer::MMI, llvm::AsmPrinter::OutStreamer, llvm::AsmPrinter::TM, and llvm::MCAsmInfo::usesCFIForEH().
The documentation for this class was generated from the following files:
DwarfException.h
DwarfCFIException.cpp