LLVM: llvm::HexagonInstr Class Reference
llvm::HexagonInstr Class Reference
#include <HexagonShuffler.h>
Public Member Functions
HexagonInstr (MCInst const *id, MCInst const *Extender, unsigned s, bool x=false)
MCInst const * getDesc () const
MCInst const * getExtender () const
unsigned isSoloException () const
bool operator< (const HexagonInstr &B) const
Static Public Member Functions
static bool lessCore (const HexagonInstr &A, const HexagonInstr &B)
Friends
class HexagonShuffler
Detailed Description
Definition at line 55 of file HexagonShuffler.h.
Constructor & Destructor Documentation
llvm::HexagonInstr::HexagonInstr (MCInst const * id, MCInst const * Extender, unsigned s, bool x = false) [inline]
Definition at line 64 of file HexagonShuffler.h.
Member Function Documentation
MCInst const* llvm::HexagonInstr::getDesc () const [inline]
Definition at line 68 of file HexagonShuffler.h.
MCInst const* llvm::HexagonInstr::getExtender () const [inline]
Definition at line 70 of file HexagonShuffler.h.
unsigned llvm::HexagonInstr::isSoloException () const [inline]
Definition at line 72 of file HexagonShuffler.h.
static bool llvm::HexagonInstr::lessCore (const HexagonInstr & A, const HexagonInstr & B) [inline, static]
Definition at line 79 of file HexagonShuffler.h.
References llvm::HexagonResource::lessUnits().
Referenced by llvm::HexagonShuffler::check().
bool llvm::HexagonInstr::operator< (const HexagonInstr & B) const [inline]
Definition at line 75 of file HexagonShuffler.h.
References llvm::HexagonResource::lessWeight().
Friends And Related Function Documentation
friend class HexagonShuffler [friend]
Definition at line 56 of file HexagonShuffler.h.
The documentation for this class was generated from the following file:
HexagonShuffler.h