LLVM: llvm::DILocalScope Class Reference
llvm::DILocalScope Class Reference
A scope for locals.
#include <DebugInfoMetadata.h>
Public Member Functions
DISubprogram * getSubprogram () const
Get the subprogram for this scope.
Static Public Member Functions
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
DILocalScope (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops)
~DILocalScope ()
Detailed Description
A scope for locals.
A legal scope for lexical blocks, local variables, and debug info locations. Subclasses are DISubprogram, DILexicalBlock, and DILexicalBlockFile.
Definition at line 1104 of file DebugInfoMetadata.h.
Constructor & Destructor Documentation
llvm::DILocalScope::DILocalScope (LLVMContext & C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops) [inline, protected]
Definition at line 1106 of file DebugInfoMetadata.h.
llvm::DILocalScope::~DILocalScope () [protected]
Member Function Documentation
static bool llvm::DILocalScope::classof (const Metadata * MD) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::DIScope.
Reimplemented in llvm::DILexicalBlockFile, llvm::DILexicalBlock, llvm::DILexicalBlockBase, and llvm::DISubprogram.
Definition at line 1118 of file DebugInfoMetadata.h.
References llvm::Metadata::DILexicalBlockFileKind, llvm::Metadata::DILexicalBlockKind, llvm::Metadata::DISubprogramKind, and llvm::Metadata::getMetadataID().
DISubprogram * DILocalScope::getSubprogram () const
Get the subprogram for this scope.
Return this if it's an DISubprogram; otherwise, look up the scope chain.
Definition at line 332 of file DebugInfoMetadata.cpp.
References llvm::Block.
Referenced by llvm::DwarfDebug::beginFunction(), llvm::getDISubprogram(), llvm::DIBuilder::insertDbgValueIntrinsic(), llvm::DIBuilder::insertDeclare(), and llvm::DILocalVariable::isValidLocationForIntrinsic().
The documentation for this class was generated from the following files:
DebugInfoMetadata.h
DebugInfoMetadata.cpp