LLVM: llvm::MachineFunction Class Reference
llvm::MachineFunction Class Reference
#include <MachineFunction.h>
Public Types
typedef
BasicBlockListType::iterator iterator
typedef
BasicBlockListType::const_iterator const_iterator
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
typedef std::reverse_iterator
< iterator > reverse_iterator
typedef ArrayRecycler
< MachineOperand >::Capacity OperandCapacity
Public Member Functions
MachineFunction (const Function *Fn, const TargetMachine &TM, unsigned FunctionNum, MachineModuleInfo &MMI)
~MachineFunction ()
MachineModuleInfo & getMMI () const
MCContext & getContext () const
const Function * getFunction () const
getFunction - Return the LLVM function that this machine code represents
StringRef getName () const
getName - Return the name of the corresponding LLVM function.
unsigned getFunctionNumber () const
getFunctionNumber - Return a unique ID for the current function.
const TargetMachine & getTarget () const
getTarget - Return the target machine this machine code is compiled with
const TargetSubtargetInfo & getSubtarget () const
getSubtarget - Return the subtarget for which this machine code is being compiled.
void setSubtarget (const TargetSubtargetInfo *ST)
template<typename STC >
const STC & getSubtarget () const
getSubtarget - This method returns a pointer to the specified type of TargetSubtargetInfo.
MachineRegisterInfo & getRegInfo ()
getRegInfo - Return information about the registers currently in use.
const MachineRegisterInfo & getRegInfo () const
MachineFrameInfo * getFrameInfo ()
getFrameInfo - Return the frame info object for the current function.
const MachineFrameInfo * getFrameInfo () const
const MachineJumpTableInfo * getJumpTableInfo () const
getJumpTableInfo - Return the jump table info object for the current function.
MachineJumpTableInfo * getJumpTableInfo ()
MachineJumpTableInfo * getOrCreateJumpTableInfo (unsigned JTEntryKind)
getOrCreateJumpTableInfo - Get the JumpTableInfo for this function, if it does already exist, allocate one.
MachineConstantPool * getConstantPool ()
getConstantPool - Return the constant pool object for the current function.
const MachineConstantPool * getConstantPool () const
unsigned getAlignment () const
getAlignment - Return the alignment (log2, not bytes) of the function.
void setAlignment (unsigned A)
setAlignment - Set the alignment (log2, not bytes) of the function.
void ensureAlignment (unsigned A)
ensureAlignment - Make sure the function is at least 1 << A bytes aligned.
bool exposesReturnsTwice () const
exposesReturnsTwice - Returns true if the function calls setjmp or any other similar functions with attribute "returns twice" without having the attribute itself.
void setExposesReturnsTwice (bool B)
setCallsSetJmp - Set a flag that indicates if there's a call to a "returns twice" function.
bool hasInlineAsm () const
Returns true if the function contains any inline assembly.
void setHasInlineAsm (bool B)
Set a flag that indicates that the function contains inline assembly.
template<typename Ty >
Ty * getInfo ()
getInfo - Keep track of various per-function pieces of information for backends that would like to do so.
template<typename Ty >
const Ty * getInfo () const
MachineBasicBlock * getBlockNumbered (unsigned N) const
getBlockNumbered - MachineBasicBlocks are automatically numbered when they are inserted into the machine function.
bool shouldSplitStack ()
Should we be emitting segmented stack stuff for the function.
unsigned getNumBlockIDs () const
getNumBlockIDs - Return the number of MBB ID's allocated.
void RenumberBlocks (MachineBasicBlock *MBBFrom=nullptr)
RenumberBlocks - This discards all of the MachineBasicBlock numbers and recomputes them.
void print (raw_ostream &OS, SlotIndexes *=nullptr) const
print - Print out the MachineFunction in a format suitable for debugging to the specified stream.
void viewCFG () const
viewCFG - This function is meant for use from the debugger.
void viewCFGOnly () const
viewCFGOnly - This function is meant for use from the debugger.
void dump () const
dump - Print the current MachineFunction to cerr, useful for debugger use.
void verify (Pass *p=nullptr, const char *Banner=nullptr) const
verify - Run the current MachineFunction through the machine code verifier, useful for debugger use.
unsigned addLiveIn (unsigned PReg, const TargetRegisterClass *RC)
addLiveIn - Add the specified physical register as a live-in value and create a corresponding virtual register for it.
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
unsigned size () const
bool empty () const
const MachineBasicBlock & front () const
MachineBasicBlock & front ()
const MachineBasicBlock & back () const
MachineBasicBlock & back ()
void push_back (MachineBasicBlock *MBB)
void push_front (MachineBasicBlock *MBB)
void insert (iterator MBBI, MachineBasicBlock *MBB)
void splice (iterator InsertPt, iterator MBBI)
void splice (iterator InsertPt, iterator MBBI, iterator MBBE)
void remove (iterator MBBI)
void erase (iterator MBBI)
unsigned addToMBBNumbering (MachineBasicBlock *MBB)
Adds the MBB to the internal numbering.
void removeFromMBBNumbering (unsigned N)
removeFromMBBNumbering - Remove the specific machine basic block from our tracker, this is only really to be used by the MachineBasicBlock implementation.
MachineInstr * CreateMachineInstr (const MCInstrDesc &MCID, DebugLoc DL, bool NoImp=false)
CreateMachineInstr - Allocate a new MachineInstr.
MachineInstr * CloneMachineInstr (const MachineInstr *Orig)
CloneMachineInstr - Create a new MachineInstr which is a copy of the 'Orig' instruction, identical in all ways except the instruction has no parent, prev, or next.
void DeleteMachineInstr (MachineInstr *MI)
DeleteMachineInstr - Delete the given MachineInstr.
MachineBasicBlock * CreateMachineBasicBlock (const BasicBlock *bb=nullptr)
CreateMachineBasicBlock - Allocate a new MachineBasicBlock.
void DeleteMachineBasicBlock (MachineBasicBlock *MBB)
DeleteMachineBasicBlock - Delete the given MachineBasicBlock.
MachineMemOperand * getMachineMemOperand (MachinePointerInfo PtrInfo, unsigned f, uint64_t s, unsigned base_alignment, const AAMDNodes &AAInfo=AAMDNodes(), const MDNode *Ranges=nullptr)
getMachineMemOperand - Allocate a new MachineMemOperand.
MachineMemOperand * getMachineMemOperand (const MachineMemOperand *MMO, int64_t Offset, uint64_t Size)
getMachineMemOperand - Allocate a new MachineMemOperand by copying an existing one, adjusting by an offset and using the given size.
MachineOperand * allocateOperandArray (OperandCapacity Cap)
Allocate an array of MachineOperands.
void deallocateOperandArray (OperandCapacity Cap, MachineOperand *Array)
Dellocate an array of MachineOperands and recycle the memory.
uint32_t * allocateRegisterMask (unsigned NumRegister)
Allocate and initialize a register mask with NumRegister bits.
MachineInstr::mmo_iterator allocateMemRefsArray (unsigned long Num)
allocateMemRefsArray - Allocate an array to hold MachineMemOperand pointers.
std::pair
< MachineInstr::mmo_iterator,
MachineInstr::mmo_iterator > extractLoadMemRefs (MachineInstr::mmo_iterator Begin, MachineInstr::mmo_iterator End)
extractLoadMemRefs - Allocate an array and populate it with just the load information from the given MachineMemOperand sequence.
std::pair
< MachineInstr::mmo_iterator,
MachineInstr::mmo_iterator > extractStoreMemRefs (MachineInstr::mmo_iterator Begin, MachineInstr::mmo_iterator End)
extractStoreMemRefs - Allocate an array and populate it with just the store information from the given MachineMemOperand sequence.
MCSymbol * getJTISymbol (unsigned JTI, MCContext &Ctx, bool isLinkerPrivate=false) const
getJTISymbol - Return the MCSymbol for the specified non-empty jump table.
MCSymbol * getPICBaseSymbol () const
getPICBaseSymbol - Return a function-local symbol to represent the PIC base.
Detailed Description
Definition at line 86 of file MachineFunction.h.
Member Typedef Documentation
typedef BasicBlockListType::const_iterator llvm::MachineFunction::const_iterator
Definition at line 322 of file MachineFunction.h.
typedef std::reverse_iterator<const_iterator> llvm::MachineFunction::const_reverse_iterator
Definition at line 323 of file MachineFunction.h.
typedef BasicBlockListType::iterator llvm::MachineFunction::iterator
Definition at line 321 of file MachineFunction.h.
typedef ArrayRecycler<MachineOperand>::Capacity llvm::MachineFunction::OperandCapacity
Definition at line 433 of file MachineFunction.h.
typedef std::reverse_iterator<iterator> llvm::MachineFunction::reverse_iterator
Definition at line 324 of file MachineFunction.h.
Constructor & Destructor Documentation
MachineFunction::MachineFunction (const Function * Fn, const TargetMachine & TM, unsigned FunctionNum, MachineModuleInfo & MMI)
Definition at line 58 of file MachineFunction.cpp.
References llvm::MachineFrameInfo::ensureMaxAlignment(), llvm::Function::getFnStackAlignment(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::TargetLoweringBase::getMinFunctionAlignment(), llvm::TargetLoweringBase::getPrefFunctionAlignment(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::TargetFrameLowering::getStackAlignment(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::Function::hasFnAttribute(), llvm::TargetFrameLowering::isStackRealignable(), llvm::Attribute::OptimizeForSize, and llvm::Attribute::StackAlignment.
MachineFunction::~MachineFunction ()
Definition at line 88 of file MachineFunction.cpp.
References begin(), llvm::Recycler< T, Size, Align >::clear(), llvm::ArrayRecycler< T, Align >::clear(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Deallocate(), end(), llvm::iplist< NodeTy, Traits >::erase(), I, and llvm::MachineFunctionInfo::~MachineFunctionInfo().
Member Function Documentation
unsigned MachineFunction::addLiveIn (unsigned PReg, const TargetRegisterClass * RC)
addLiveIn - Add the specified physical register as a live-in value and create a corresponding virtual register for it.
Add the specified physical register as a live-in value and create a corresponding virtual register for it.
Definition at line 431 of file MachineFunction.cpp.
References llvm::MachineRegisterInfo::addLiveIn(), llvm::TargetRegisterClass::contains(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineRegisterInfo::getLiveInVirtReg(), llvm::MachineRegisterInfo::getRegClass(), getRegInfo(), and llvm::TargetRegisterClass::hasSubClassEq().
Referenced by llvm::CCState::analyzeMustTailForwardedRegisters(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::HexagonTargetLowering::LowerRETURNADDR(), and LowerRETURNADDR().
unsigned llvm::MachineFunction::addToMBBNumbering (MachineBasicBlock * MBB) [inline]
Adds the MBB to the internal numbering.
Returns the unique number assigned to the MBB.
Definition at line 376 of file MachineFunction.h.
MachineInstr::mmo_iterator MachineFunction::allocateMemRefsArray (unsigned long Num)
allocateMemRefsArray - Allocate an array to hold MachineMemOperand pointers.
This array is owned by the MachineFunction.
Definition at line 251 of file MachineFunction.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate().
Referenced by llvm::MachineInstr::addMemOperand(), concatenateMemOperands(), extractLoadMemRefs(), extractStoreMemRefs(), and llvm::SelectionDAGISel::SelectCodeCommon().
MachineOperand* llvm::MachineFunction::allocateOperandArray (OperandCapacity Cap) [inline]
Allocate an array of MachineOperands.
This is only intended for use by internal MachineInstr functions.
Definition at line 437 of file MachineFunction.h.
References llvm::ArrayRecycler< T, Align >::allocate().
uint32_t* llvm::MachineFunction::allocateRegisterMask (unsigned NumRegister) [inline]
Allocate and initialize a register mask with NumRegister bits.
Definition at line 449 of file MachineFunction.h.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate().
const MachineBasicBlock& llvm::MachineFunction::back () const [inline]
Definition at line 347 of file MachineFunction.h.
References llvm::iplist< NodeTy, Traits >::back().
MachineBasicBlock& llvm::MachineFunction::back () [inline]
Definition at line 348 of file MachineFunction.h.
References llvm::iplist< NodeTy, Traits >::back().
iterator llvm::MachineFunction::begin () [inline]
Definition at line 333 of file MachineFunction.h.
References llvm::iplist< NodeTy, Traits >::begin().
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::ScheduleDAGSDNodes::EmitSchedule(), llvm::finalizeBundles(), getBBFallenThrough(), llvm::GraphTraits< MachineBlockFrequencyInfo * >::getEntryNode(), llvm::SIMachineFunctionInfo::getSpilledReg(), llvm::MachineLoop::getTopBlock(), HandleVRSaveUpdate(), llvm::GraphTraits< MachineBlockFrequencyInfo * >::nodes_begin(), llvm::GraphTraits< MachineFunction * >::nodes_begin(), llvm::GraphTraits< const MachineFunction * >::nodes_begin(), llvm::BranchFolder::OptimizeFunction(), PrevCrossBBInst(), RemoveVRSaveCode(), RenumberBlocks(), llvm::PPCFrameLowering::replaceFPWithRealFP(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::LiveVariables::runOnMachineFunction(), llvm::SlotIndexes::runOnMachineFunction(), llvm::Mips16FrameLowering::spillCalleeSavedRegisters(), llvm::MipsSEFrameLowering::spillCalleeSavedRegisters(), verifyCTRBranch(), VerifyPHIs(), and ~MachineFunction().
const_iterator llvm::MachineFunction::begin () const [inline]
Definition at line 334 of file MachineFunction.h.
References llvm::iplist< NodeTy, Traits >::begin().
MachineInstr * MachineFunction::CloneMachineInstr (const MachineInstr * Orig)
CloneMachineInstr - Create a new MachineInstr which is a copy of the 'Orig' instruction, identical in all ways except the instruction has no parent, prev, or next.
Create a new MachineInstr which is a copy of the 'Orig' instruction, identical in all ways except the instruction has no parent, prev, or next.
See also TargetInstrInfo::duplicate() for target-specific fixes to cloned instructions.
Definition at line 188 of file MachineFunction.cpp.
References llvm::Recycler< T, Size, Align >::Allocate().
Referenced by llvm::TargetInstrInfo::commuteInstruction(), llvm::TargetInstrInfo::duplicate(), insertDelayFiller(), llvm::ARMBaseInstrInfo::reMaterialize(), and llvm::TargetInstrInfo::reMaterialize().
MachineBasicBlock * MachineFunction::CreateMachineBasicBlock (const BasicBlock * bb = nullptr)
CreateMachineBasicBlock - Allocate a new MachineBasicBlock.
Allocate a new MachineBasicBlock.
Use this instead of `new MachineBasicBlock'.
Definition at line 212 of file MachineFunction.cpp.
References llvm::Recycler< T, Size, Align >::Allocate().
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::PPCTargetLowering::EmitAtomicBinary(), emitBlockAfter(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::AArch64TargetLowering::EmitF128CSEL(), llvm::BPFTargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::MSP430TargetLowering::EmitShiftInstr(), EmitXBegin(), llvm::SparcTargetLowering::expandAtomicRMW(), llvm::SparcTargetLowering::expandSelectCC(), llvm::SelectionDAGBuilder::FindMergedConditions(), llvm::MIRParserImpl::initializeMachineFunction(), llvm::FunctionLoweringInfo::set(), and llvm::MachineBasicBlock::SplitCriticalEdge().
MachineInstr * MachineFunction::CreateMachineInstr (const MCInstrDesc & MCID, DebugLoc DL, bool NoImp = false)
CreateMachineInstr - Allocate a new MachineInstr.
Allocate a new MachineInstr. Use this instead of `new MachineInstr'.
Use this instead of `new MachineInstr'.
Definition at line 179 of file MachineFunction.cpp.
References llvm::Recycler< T, Size, Align >::Allocate().
Referenced by llvm::BuildMI(), foldPatchpoint(), FuseInst(), and FuseTwoAddrInst().
void llvm::MachineFunction::deallocateOperandArray (OperandCapacity Cap, MachineOperand * Array) [inline]
Dellocate an array of MachineOperands and recycle the memory.
This is only intended for use by internal MachineInstr functions. Cap must be the same capacity that was used to allocate the array.
Definition at line 444 of file MachineFunction.h.
References llvm::ArrayRecycler< T, Align >::deallocate().
Referenced by DeleteMachineInstr().
void MachineFunction::DeleteMachineBasicBlock (MachineBasicBlock * MBB)
DeleteMachineBasicBlock - Delete the given MachineBasicBlock.
Delete the given MachineBasicBlock.
Definition at line 219 of file MachineFunction.cpp.
References llvm::Recycler< T, Size, Align >::Deallocate(), and llvm::MachineBasicBlock::getParent().
void MachineFunction::DeleteMachineInstr (MachineInstr * MI)
DeleteMachineInstr - Delete the given MachineInstr.
Delete the given MachineInstr.
This function also serves as the MachineInstr destructor - the real ~MachineInstr() destructor must be empty.
Definition at line 198 of file MachineFunction.cpp.
References llvm::Recycler< T, Size, Align >::Deallocate(), and deallocateOperandArray().
Referenced by llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters().
void MachineFunction::dump () const
dump - Print the current MachineFunction to cerr, useful for debugger use.
Definition at line 320 of file MachineFunction.cpp.
References llvm::dbgs(), and print().
Referenced by llvm::A57ChainingConstraint::apply().
bool llvm::MachineFunction::empty () const [inline]
Definition at line 344 of file MachineFunction.h.
References llvm::iplist< NodeTy, Traits >::empty().
Referenced by RenumberBlocks().
iterator llvm::MachineFunction::end () [inline]
Definition at line 335 of file MachineFunction.h.
References llvm::iplist< NodeTy, Traits >::end().
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), BBHasFallthrough(), canFallThroughTo(), llvm::MSP430FrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::finalizeBundles(), FixTail(), llvm::MachineLoop::getBottomBlock(), getNextBlock(), llvm::SIMachineFunctionInfo::getSpilledReg(), HandleVRSaveUpdate(), llvm::MIRParserImpl::initializeMachineFunction(), llvm::SlotIndexes::insertMBBInMaps(), jumpTableFollowsTB(), llvm::GraphTraits< MachineBlockFrequencyInfo * >::nodes_end(), llvm::GraphTraits< MachineFunction * >::nodes_end(), llvm::GraphTraits< const MachineFunction * >::nodes_end(), llvm::BranchFolder::OptimizeFunction(), RemoveVRSaveCode(), RenumberBlocks(), llvm::PPCFrameLowering::replaceFPWithRealFP(), llvm::LiveVariables::runOnMachineFunction(), llvm::SlotIndexes::runOnMachineFunction(), llvm::MachineBasicBlock::SplitCriticalEdge(), VerifyPHIs(), and ~MachineFunction().
const_iterator llvm::MachineFunction::end () const [inline]
Definition at line 336 of file MachineFunction.h.
References llvm::iplist< NodeTy, Traits >::end().
void llvm::MachineFunction::ensureAlignment (unsigned A) [inline]
ensureAlignment - Make sure the function is at least 1 << A bytes aligned.
Definition at line 225 of file MachineFunction.h.
References llvm::ARM_PROC::A.
void llvm::MachineFunction::erase (iterator MBBI) [inline]
Definition at line 365 of file MachineFunction.h.
References llvm::iplist< NodeTy, Traits >::erase().
Referenced by llvm::MachineBasicBlock::eraseFromParent().
bool llvm::MachineFunction::exposesReturnsTwice () const [inline]
exposesReturnsTwice - Returns true if the function calls setjmp or any other similar functions with attribute "returns twice" without having the attribute itself.
Definition at line 232 of file MachineFunction.h.
std::pair< MachineInstr::mmo_iterator, MachineInstr::mmo_iterator > MachineFunction::extractLoadMemRefs (MachineInstr::mmo_iterator Begin, MachineInstr::mmo_iterator End)
extractLoadMemRefs - Allocate an array and populate it with just the load information from the given MachineMemOperand sequence.
Definition at line 256 of file MachineFunction.cpp.
References allocateMemRefsArray(), getMachineMemOperand(), llvm::MachineMemOperand::getSize(), and I.
std::pair< MachineInstr::mmo_iterator, MachineInstr::mmo_iterator > MachineFunction::extractStoreMemRefs (MachineInstr::mmo_iterator Begin, MachineInstr::mmo_iterator End)
extractStoreMemRefs - Allocate an array and populate it with just the store information from the given MachineMemOperand sequence.
Definition at line 288 of file MachineFunction.cpp.
References allocateMemRefsArray(), getMachineMemOperand(), llvm::MachineMemOperand::getSize(), and I.
const MachineBasicBlock& llvm::MachineFunction::front () const [inline]
Definition at line 345 of file MachineFunction.h.
References llvm::iplist< NodeTy, Traits >::front().
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::SIInstrInfo::calculateLDSSpillAddress(), emitGPDisp(), llvm::Mips16FrameLowering::emitPrologue(), llvm::NVPTXFrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::HexagonFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::DominatorTreeBase< MachineBasicBlock >::findNearestCommonDominator(), llvm::GraphTraits< MachineFunction * >::getEntryNode(), llvm::GraphTraits< const MachineFunction * >::getEntryNode(), llvm::GraphTraits< Inverse< MachineFunction * > >::getEntryNode(), llvm::GraphTraits< Inverse< const MachineFunction * > >::getEntryNode(), llvm::SparcInstrInfo::getGlobalBaseReg(), llvm::LiveVariables::MarkVirtRegAliveInBlock(), and updateLiveness().
MachineBasicBlock& llvm::MachineFunction::front () [inline]
Definition at line 346 of file MachineFunction.h.
References llvm::iplist< NodeTy, Traits >::front().
unsigned llvm::MachineFunction::getAlignment () const [inline]
getAlignment - Return the alignment (log2, not bytes) of the function.
Definition at line 218 of file MachineFunction.h.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::MipsAsmPrinter::EmitFunctionEntryLabel(), and llvm::AMDGPUAsmPrinter::runOnMachineFunction().
MachineBasicBlock* llvm::MachineFunction::getBlockNumbered (unsigned N) const [inline]
getBlockNumbered - MachineBasicBlocks are automatically numbered when they are inserted into the machine function.
The block number for a machine basic block can be found by using the MBB::getBlockNumber method, this method provides the inverse mapping.
Definition at line 272 of file MachineFunction.h.
Referenced by llvm::SplitEditor::splitLiveThroughBlock().
MachineConstantPool* llvm::MachineFunction::getConstantPool () [inline]
getConstantPool - Return the constant pool object for the current function.
Definition at line 213 of file MachineFunction.h.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), duplicateCPV(), llvm::AsmPrinter::EmitConstantPool(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), emitThumb1LoadConstPool(), emitThumb2LoadConstPool(), getConstantFromPool(), llvm::X86AsmPrinter::GetCPISymbol(), llvm::XCoreInstrInfo::loadImmediate(), llvm::ARMBaseInstrInfo::produceSameValue(), llvm::ARMAsmPrinter::runOnMachineFunction(), and llvm::MipsAsmPrinter::runOnMachineFunction().
const MachineConstantPool* llvm::MachineFunction::getConstantPool () const [inline]
Definition at line 214 of file MachineFunction.h.
MCContext& llvm::MachineFunction::getContext () const [inline]
Definition at line 156 of file MachineFunction.h.
Referenced by llvm::MipsAsmPrinter::EmitFunctionBodyStart(), llvm::SystemZAsmPrinter::EmitInstruction(), llvm::DwarfDebug::endFunction(), llvm::PPCFunctionInfo::getPICOffsetSymbol(), llvm::MachineBasicBlock::getSymbol(), llvm::FastISel::lowerCallTo(), and llvm::SystemZAsmPrinter::PrintAsmOperand().
MachineFrameInfo* llvm::MachineFunction::getFrameInfo () [inline]
getFrameInfo - Return the frame info object for the current function.
This object contains information about objects allocated on the stack frame of the current function in an abstract way.
Definition at line 195 of file MachineFunction.h.
Referenced by llvm::addFrameReference(), llvm::RegsForValue::AddInlineAsmOperands(), llvm::PPCFrameLowering::addScavengingSpillSlot(), llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::CCState::AllocateStack(), llvm::HexagonFrameLowering::assignCalleeSavedSpillSlots(), llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), llvm::VirtRegMap::assignVirt2StackSlot(), CalculateTailCallArgDest(), llvm::AArch64RegisterInfo::cannotEliminateFrame(), llvm::ARMBaseRegisterInfo::cannotEliminateFrame(), llvm::ARMFrameLowering::canSimplifyCallFramePseudos(), llvm::AArch64FrameLowering::canUseRedZone(), llvm::MipsFunctionInfo::createEhDataRegsFI(), llvm::XCoreFunctionInfo::createEHSpillSlot(), llvm::XCoreFunctionInfo::createFPSpillSlot(), llvm::XCoreFunctionInfo::createLRSpillSlot(), llvm::SelectionDAG::CreateStackTemporary(), llvm::PPCFrameLowering::determineFrameLayout(), llvm::TargetOptions::DisableFramePointerElim(), llvm::BPFRegisterInfo::eliminateFrameIndex(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::NVPTXRegisterInfo::eliminateFrameIndex(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::MipsRegisterInfo::eliminateFrameIndex(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Spills(), llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), emitComments(), llvm::Mips16FrameLowering::emitEpilogue(), llvm::MipsSEFrameLowering::emitEpilogue(), llvm::SparcFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::MipsAsmPrinter::emitFrameDirective(), llvm::TargetLoweringBase::emitPatchPoint(), llvm::NVPTXFrameLowering::emitPrologue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::HexagonFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), EmitTailCallStoreFPAndRetAddr(), EmitTailCallStoreRetAddr(), llvm::MipsFrameLowering::estimateStackSize(), fixupFuncForFI(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::SystemZFrameLowering::getAllocatedStackSize(), getFRAMEADDR(), getFrameIndexMMO(), llvm::AMDGPUFrameLowering::getFrameIndexOffset(), llvm::SystemZFrameLowering::getFrameIndexOffset(), llvm::HexagonFrameLowering::getFrameIndexOffset(), llvm::X86FrameLowering::getFrameIndexOffset(), llvm::TargetFrameLowering::getFrameIndexOffset(), llvm::X86FrameLowering::getFrameIndexOffsetFromSP(), llvm::AMDGPUInstrInfo::getIndirectIndexBegin(), llvm::AMDGPUInstrInfo::getIndirectIndexEnd(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), llvm::MipsInstrInfo::GetMemOperand(), getMemsetStores(), llvm::MipsFunctionInfo::getMoveF64ViaSpillFI(), getPrologueDeath(), llvm::MipsRegisterInfo::getReservedRegs(), llvm::MSP430TargetLowering::getReturnAddressFrameIndex(), llvm::SIMachineFunctionInfo::getSpilledReg(), GetTLSADDR(), llvm::CCState::HandleByVal(), llvm::AArch64RegisterInfo::hasBasePointer(), llvm::ARMBaseRegisterInfo::hasBasePointer(), llvm::MipsFrameLowering::hasBP(), llvm::MipsFrameLowering::hasFP(), llvm::SparcFrameLowering::hasFP(), llvm::PPCFrameLowering::hasFP(), llvm::SystemZFrameLowering::hasFP(), llvm::MSP430FrameLowering::hasFP(), llvm::ARMFrameLowering::hasFP(), llvm::XCoreFrameLowering::hasFP(), llvm::HexagonFrameLowering::hasFP(), llvm::AArch64FrameLowering::hasFP(), llvm::X86FrameLowering::hasFP(), llvm::MipsSEFrameLowering::hasReservedCallFrame(), llvm::SparcFrameLowering::hasReservedCallFrame(), llvm::Mips16FrameLowering::hasReservedCallFrame(), llvm::Thumb1FrameLowering::hasReservedCallFrame(), llvm::MSP430FrameLowering::hasReservedCallFrame(), llvm::ARMFrameLowering::hasReservedCallFrame(), llvm::AArch64FrameLowering::hasReservedCallFrame(), llvm::X86FrameLowering::hasReservedCallFrame(), llvm::SelectionDAG::InferPtrAlignment(), llvm::RegScavenger::initRegState(), llvm::SelectionDAG::isConsecutiveLoad(), isConsecutiveLSLoc(), llvm::XCoreFunctionInfo::isLargeFrame(), llvm::SystemZInstrInfo::isStackSlotCopy(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::PPCInstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), LowerAsSplatVectorLoad(), llvm::HexagonTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::TargetLowering::LowerCallTo(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::SparcTargetLowering::LowerF128_LibCallArg(), llvm::SparcTargetLowering::LowerF128Op(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::MSP430TargetLowering::LowerFRAMEADDR(), llvm::HexagonTargetLowering::LowerFRAMEADDR(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), LowerINTRINSIC_W_CHAIN(), llvm::MSP430TargetLowering::LowerRETURNADDR(), llvm::HexagonTargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), LowerVASTART(), llvm::SparcTargetLowering::makeAddress(), llvm::Mips16InstrInfo::makeFrame(), llvm::HexagonFrameLowering::needsAligna(), llvm::PPCFrameLowering::needsFP(), llvm::AArch64RegisterInfo::needsFrameBaseReg(), llvm::ARMBaseRegisterInfo::needsFrameBaseReg(), llvm::X86FrameLowering::needsFrameIndexResolution(), llvm::TargetFrameLowering::needsFrameIndexResolution(), llvm::HexagonRegisterInfo::needsStackRealignment(), llvm::MipsRegisterInfo::needsStackRealignment(), llvm::AArch64RegisterInfo::needsStackRealignment(), llvm::ARMBaseRegisterInfo::needsStackRealignment(), llvm::PPCRegisterInfo::needsStackRealignment(), llvm::MipsAsmPrinter::printSavedRegsBitmask(), llvm::SystemZFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::MipsSEFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::HexagonFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::XCoreFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::X86FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::SystemZFrameLowering::processFunctionBeforeFrameFinalized(), llvm::HexagonFrameLowering::processFunctionBeforeFrameFinalized(), llvm::MSP430FrameLowering::processFunctionBeforeFrameFinalized(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::XCoreFrameLowering::processFunctionBeforeFrameFinalized(), llvm::SIRegisterInfo::requiresRegisterScavenging(), llvm::AArch64FrameLowering::resolveFrameIndexReference(), llvm::ARMFrameLowering::ResolveFrameIndexReference(), llvm::Mips16InstrInfo::restoreFrame(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::FastISel::selectPatchpoint(), llvm::FastISel::selectStackmap(), llvm::FunctionLoweringInfo::set(), llvm::Mips16FrameLowering::spillCalleeSavedRegisters(), llvm::MipsSEFrameLowering::spillCalleeSavedRegisters(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), llvm::CriticalAntiDepBreaker::StartBlock(), llvm::AggressiveAntiDepBreaker::StartBlock(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::XCoreInstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::SIInstrInfo::storeRegToStackSlot(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::PPCInstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), updateLiveness(), llvm::AArch64RegisterInfo::useFPForScavengingIndex(), llvm::SelectionDAGBuilder::visitSPDescriptorParent(), and WindowsRequiresStackProbe().
const MachineFrameInfo* llvm::MachineFunction::getFrameInfo () const [inline]
Definition at line 196 of file MachineFunction.h.
const Function* llvm::MachineFunction::getFunction () const [inline]
getFunction - Return the LLVM function that this machine code represents
Definition at line 160 of file MachineFunction.h.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::NVPTXTargetLowering::allowFMA(), llvm::AMDGPUMachineFunction::AMDGPUMachineFunction(), llvm::HexagonFrameLowering::assignCalleeSavedSpillSlots(), llvm::WinException::beginFunction(), llvm::WinCodeViewLineTables::beginFunction(), llvm::DwarfDebug::beginFunction(), llvm::AArch64RegisterInfo::canRealignStack(), llvm::ARMBaseRegisterInfo::canRealignStack(), llvm::PPCRegisterInfo::canRealignStack(), llvm::AArch64FrameLowering::canUseRedZone(), checkNumAlignedDPRCS2Regs(), llvm::XCoreFunctionInfo::createLRSpillSlot(), llvm::PPCFrameLowering::determineFrameLayout(), llvm::TargetOptions::DisableFramePointerElim(), duplicateCPV(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::ARMFrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::MipsAsmPrinter::EmitFunctionBodyStart(), llvm::AsmPrinter::EmitJumpTableInfo(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::XCoreFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), emitThumb1LoadConstPool(), emitThumb2LoadConstPool(), llvm::ARMException::endFunction(), llvm::WinCodeViewLineTables::endFunction(), llvm::DwarfDebug::endFunction(), ExpandPowI(), findDeadCallerSavedReg(), get64BitArgumentXMMs(), llvm::MSP430RegisterInfo::getCalleeSavedRegs(), llvm::AArch64RegisterInfo::getCalleeSavedRegs(), llvm::PPCRegisterInfo::getCalleeSavedRegs(), llvm::ARMBaseRegisterInfo::getCalleeSavedRegs(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), getName(), llvm::ARMBaseInstrInfo::getOperandLatency(), llvm::ARMTargetLowering::getOptimalMemOpType(), llvm::AArch64TargetLowering::getOptimalMemOpType(), llvm::PPCTargetLowering::getOptimalMemOpType(), llvm::MipsRegisterInfo::getReservedRegs(), GetScratchRegister(), llvm::SparcTargetLowering::getSRetArgSize(), HasNestArgument(), hasReturnsTwiceAttr(), llvm::SelectionDAG::init(), llvm::MIRParserImpl::initializeMachineFunction(), llvm::HexagonTargetLowering::IsEligibleForTailCallOptimization(), llvm::TargetLowering::isInTailCallPosition(), isMinSize(), isOptSize(), llvm::ARMBaseInstrInfo::isProfitableToIfCvt(), llvm::XCoreInstrInfo::loadImmediate(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::AMDGPUMCInstLower::lower(), llvm::HexagonTargetLowering::LowerCall(), llvm::AMDGPUTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::AsmPrinter::lowerConstant(), llvm::SITargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), LowerInterruptReturn(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), LowerVectorBroadcast(), llvm::AsmPrinter::needsCFIMoves(), llvm::PPCFrameLowering::needsFP(), llvm::XCoreRegisterInfo::needsFrameMoves(), llvm::AsmPrinter::needsSEHMoves(), llvm::MipsRegisterInfo::needsStackRealignment(), llvm::AArch64RegisterInfo::needsStackRealignment(), llvm::ARMBaseRegisterInfo::needsStackRealignment(), llvm::PPCRegisterInfo::needsStackRealignment(), llvm::TargetFrameLowering::noFramePointerElim(), PerformOrCombine(), performSTORECombine(), PerformSTORECombine(), llvm::AMDGPUAsmPrinter::PrintAsmOperand(), llvm::SystemZFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::XCoreFrameLowering::processFunctionBeforeCalleeSavedScan(), ProfitableToMerge(), llvm::MipsTargetMachine::resetSubtarget(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::X86AsmPrinter::runOnMachineFunction(), llvm::VLIWMachineScheduler::schedule(), llvm::AsmPrinter::SetupMachineFunction(), shouldSplitStack(), llvm::SystemZFrameLowering::spillCalleeSavedRegisters(), llvm::SIInstrInfo::storeRegToStackSlot(), llvm::tryFoldSPUpdateIntoPushPop(), llvm::ARMSubtarget::useMovt(), and WindowsRequiresStackProbe().
unsigned llvm::MachineFunction::getFunctionNumber () const [inline]
getFunctionNumber - Return a unique ID for the current function.
Definition at line 168 of file MachineFunction.h.
Referenced by llvm::NVPTXFrameLowering::emitPrologue(), llvm::AsmPrinter::getFunctionNumber(), getJTISymbol(), getPICBaseSymbol(), llvm::PPCFunctionInfo::getPICOffsetSymbol(), and llvm::MachineBasicBlock::getSymbol().
template<typename Ty > Ty* llvm::MachineFunction::getInfo () [inline]
getInfo - Keep track of various per-function pieces of information for backends that would like to do so.
Definition at line 256 of file MachineFunction.h.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), llvm::SIInstrInfo::calculateLDSSpillAddress(), CalculateTailCallSPDiff(), llvm::ARMBaseRegisterInfo::canRealignStack(), llvm::AArch64FrameLowering::canUseRedZone(), checkNumAlignedDPRCS2Regs(), duplicateCPV(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), llvm::MipsSEFrameLowering::emitEpilogue(), llvm::SparcFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::SystemZFrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::HexagonTargetLowering::EmitInstrWithCustomInserter(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), estimateRSStackSizeLimit(), fixupFuncForFI(), llvm::X86FrameLowering::getFrameIndexOffset(), llvm::X86FrameLowering::getFrameIndexOffsetFromSP(), llvm::MipsDAGToDAGISel::getGlobalBaseReg(), llvm::SparcInstrInfo::getGlobalBaseReg(), llvm::MipsTargetLowering::getGlobalReg(), llvm::SIRegisterInfo::getPreloadedValue(), llvm::MipsRegisterInfo::getReservedRegs(), llvm::PPCRegisterInfo::getReservedRegs(), llvm::MSP430TargetLowering::getReturnAddressFrameIndex(), llvm::ARMBaseRegisterInfo::hasBasePointer(), llvm::SystemZFrameLowering::hasFP(), llvm::HexagonFrameLowering::hasFP(), llvm::X86FrameLowering::hasFP(), hasNonRISpills(), llvm::X86FrameLowering::hasReservedCallFrame(), llvm::PPCRegisterInfo::hasReservedSpillSlot(), hasSpills(), llvm::ARMBaseInstrInfo::InsertBranch(), llvm::ARMBaseInstrInfo::isPredicable(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::PPCInstrInfo::loadRegFromStackSlot(), llvm::HexagonTargetLowering::LowerEH_RETURN(), llvm::SITargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::HexagonTargetLowering::LowerINLINEASM(), LowerINTRINSIC_W_CHAIN(), llvm::R600TargetLowering::LowerOperation(), llvm::SITargetLowering::LowerOperation(), llvm::SparcTargetLowering::LowerReturn_32(), LowerToTLSLocalDynamicModel(), llvm::MSP430TargetLowering::LowerVASTART(), llvm::HexagonTargetLowering::LowerVASTART(), LowerVASTART(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), MustSaveLR(), llvm::PPCFrameLowering::needsFP(), llvm::ARMBaseRegisterInfo::needsFrameBaseReg(), llvm::X86FrameLowering::needsFrameIndexResolution(), llvm::SystemZFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::MipsSEFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::SparcFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::HexagonFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::XCoreFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::X86FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::XCoreFrameLowering::processFunctionBeforeFrameFinalized(), llvm::Thumb2InstrInfo::ReplaceTailWithBranchTo(), llvm::ARMBaseRegisterInfo::resolveFrameIndex(), llvm::AArch64FrameLowering::resolveFrameIndexReference(), llvm::ARMFrameLowering::ResolveFrameIndexReference(), llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZFrameLowering::restoreCalleeSavedRegisters(), llvm::ARMFrameLowering::restoreCalleeSavedRegisters(), llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::MipsAsmPrinter::runOnMachineFunction(), setUsesTOCBasePtr(), llvm::SystemZFrameLowering::spillCalleeSavedRegisters(), llvm::XCoreFrameLowering::spillCalleeSavedRegisters(), llvm::ARMFrameLowering::spillCalleeSavedRegisters(), llvm::MSP430FrameLowering::spillCalleeSavedRegisters(), llvm::PPCFrameLowering::spillCalleeSavedRegisters(), spillsCR(), spillsVRSAVE(), llvm::SIInstrInfo::storeRegToStackSlot(), llvm::PPCInstrInfo::storeRegToStackSlot(), llvm::R600InstrInfo::usesTextureCache(), and llvm::R600InstrInfo::usesVertexCache().
template<typename Ty > const Ty* llvm::MachineFunction::getInfo () const [inline]
Definition at line 263 of file MachineFunction.h.
MCSymbol * MachineFunction::getJTISymbol (unsigned JTI, MCContext & Ctx, bool isLinkerPrivate = false) const
getJTISymbol - Return the MCSymbol for the specified non-empty jump table.
Return the MCSymbol for the specified non-empty jump table.
If isLinkerPrivate is specified, an 'l' label is returned, otherwise a normal 'L' label is returned.
Definition at line 456 of file MachineFunction.cpp.
References llvm::DL, llvm::TargetMachine::getDataLayout(), getFunctionNumber(), llvm::DataLayout::getLinkerPrivateGlobalPrefix(), llvm::MCContext::getOrCreateSymbol(), llvm::DataLayout::getPrivateGlobalPrefix(), getTarget(), llvm::cl::Prefix, and size().
Referenced by llvm::AsmPrinter::GetJTISymbol(), and llvm::TargetLowering::getPICJumpTableRelocBaseExpr().
const MachineJumpTableInfo* llvm::MachineFunction::getJumpTableInfo () const [inline]
getJumpTableInfo - Return the jump table info object for the current function.
This object contains information about jump tables in the current function. If the current function has no jump tables, this will return null.
Definition at line 202 of file MachineFunction.h.
Referenced by llvm::ARMAsmPrinter::EmitJumpTableAddrs(), llvm::AsmPrinter::EmitJumpTableInfo(), llvm::ARMAsmPrinter::EmitJumpTableInsts(), llvm::ARMAsmPrinter::EmitJumpTableTBInst(), llvm::HexagonTargetLowering::LowerBR_JT(), and llvm::BranchFolder::OptimizeFunction().
MachineJumpTableInfo* llvm::MachineFunction::getJumpTableInfo () [inline]
Definition at line 203 of file MachineFunction.h.
MachineMemOperand * MachineFunction::getMachineMemOperand (MachinePointerInfo PtrInfo, unsigned f, uint64_t s, unsigned base_alignment, const AAMDNodes & AAInfo = AAMDNodes(), const MDNode * Ranges = nullptr)
getMachineMemOperand - Allocate a new MachineMemOperand.
MachineMemOperands are owned by the MachineFunction and need not be explicitly deallocated.
Definition at line 226 of file MachineFunction.cpp.
Referenced by llvm::addFrameReference(), llvm::FastISel::createMachineMemOperandFor(), llvm::TargetLoweringBase::emitPatchPoint(), extractLoadMemRefs(), extractStoreMemRefs(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::SelectionDAG::getAtomic(), llvm::SelectionDAG::getAtomicCmpSwap(), getFrameIndexMMO(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::MipsInstrInfo::GetMemOperand(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTruncStore(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::PPCInstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), NarrowVectorLoadToElement(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::XCoreInstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::PPCInstrInfo::storeRegToStackSlot(), and llvm::ARMBaseInstrInfo::storeRegToStackSlot().
MachineMemOperand * MachineFunction::getMachineMemOperand (const MachineMemOperand * MMO, int64_t Offset, uint64_t Size)
getMachineMemOperand - Allocate a new MachineMemOperand by copying an existing one, adjusting by an offset and using the given size.
MachineMemOperands are owned by the MachineFunction and need not be explicitly deallocated.
Definition at line 235 of file MachineFunction.cpp.
References llvm::MachineMemOperand::getBaseAlignment(), llvm::MachineMemOperand::getFlags(), llvm::MachineMemOperand::getOffset(), llvm::MachineMemOperand::getPseudoValue(), and llvm::MachineMemOperand::getValue().
MachineModuleInfo& llvm::MachineFunction::getMMI () const [inline]
Definition at line 155 of file MachineFunction.h.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), llvm::AsmPrinter::emitCFIInstruction(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), findDeadCallerSavedReg(), llvm::X86FrameLowering::hasFP(), LowerEXCEPTIONINFO(), LowerINTRINSIC_WO_CHAIN(), llvm::XCoreRegisterInfo::needsFrameMoves(), llvm::XCoreFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::FastISel::selectCall(), llvm::FastISel::selectIntrinsicCall(), llvm::FunctionLoweringInfo::set(), and llvm::SelectionDAGBuilder::visitLandingPadClauseBB().
StringRef MachineFunction::getName () const
getName - Return the name of the corresponding LLVM function.
Definition at line 325 of file MachineFunction.cpp.
References getFunction(), and llvm::Value::getName().
Referenced by llvm::calculateSpillWeightsAndHints(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), llvm::MipsRegisterInfo::eliminateFrameIndex(), llvm::MachineBasicBlock::getFullName(), llvm::DOTGraphTraits< ScheduleDAG * >::getGraphName(), llvm::DOTGraphTraits< SelectionDAG * >::getGraphName(), llvm::DOTGraphTraits< MachineBlockFrequencyInfo * >::getGraphName(), llvm::DOTGraphTraits< const MachineFunction * >::getGraphName(), llvm::DOTGraphTraits< ScheduleDAGMI * >::getGraphName(), llvm::MIRParserImpl::initializeMachineFunction(), print(), viewCFG(), and viewCFGOnly().
unsigned llvm::MachineFunction::getNumBlockIDs () const [inline]
getNumBlockIDs - Return the number of MBB ID's allocated.
Definition at line 283 of file MachineFunction.h.
Referenced by llvm::MachineTraceMetrics::runOnMachineFunction(), llvm::LiveVariables::runOnMachineFunction(), llvm::SlotIndexes::runOnMachineFunction(), and llvm::MachineTraceMetrics::verifyAnalysis().
MachineJumpTableInfo * MachineFunction::getOrCreateJumpTableInfo (unsigned EntryKind)
getOrCreateJumpTableInfo - Get the JumpTableInfo for this function, if it does already exist, allocate one.
Get the JumpTableInfo for this function.
If it does not already exist, allocate one.
Definition at line 123 of file MachineFunction.cpp.
MCSymbol * MachineFunction::getPICBaseSymbol () const
getPICBaseSymbol - Return a function-local symbol to represent the PIC base.
Return a function-local symbol to represent the PIC base.
Definition at line 471 of file MachineFunction.cpp.
References llvm::DL, llvm::TargetMachine::getDataLayout(), getFunctionNumber(), llvm::MCContext::getOrCreateSymbol(), llvm::DataLayout::getPrivateGlobalPrefix(), and getTarget().
Referenced by llvm::X86AsmPrinter::EmitInstruction(), GetSymbolRef(), and printSymbolOperand().
MachineRegisterInfo& llvm::MachineFunction::getRegInfo () [inline]
getRegInfo - Return information about the registers currently in use.
Definition at line 188 of file MachineFunction.h.
Referenced by llvm::RegsForValue::AddInlineAsmOperands(), addLiveIn(), llvm::MachineBasicBlock::addLiveIn(), addLiveIn(), llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::SITargetLowering::AdjustInstrPostInstrSelection(), llvm::AllocationOrder::AllocationOrder(), llvm::VirtRegMap::assignVirt2StackSlot(), llvm::SIInstrInfo::calculateLDSSpillAddress(), llvm::VirtRegAuxInfo::calculateSpillWeightAndHint(), llvm::calculateSpillWeightsAndHints(), canCombineWithMUL(), canCompareBeNewValueJump(), canFoldCopy(), llvm::AArch64InstrInfo::canInsertSelect(), llvm::PPCInstrInfo::canInsertSelect(), llvm::MipsRegisterInfo::canRealignStack(), llvm::ARMBaseRegisterInfo::canRealignStack(), checkNumAlignedDPRCS2Regs(), llvm::SystemZInstrInfo::convertToThreeAddress(), llvm::NVPTXInstrInfo::copyPhysReg(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), llvm::HexagonInstrInfo::createVR(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), llvm::PPCTargetLowering::EmitAtomicBinary(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::NVPTXFrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::MSP430TargetLowering::EmitShiftInstr(), emitThumbRegPlusImmInReg(), llvm::RegScavenger::enterBasicBlock(), llvm::MachineInstr::eraseFromParentAndMarkDBGValuesForRemoval(), llvm::SparcTargetLowering::expandAtomicRMW(), llvm::findPHICopyInsertPoint(), llvm::AArch64InstrInfo::foldMemoryOperandImpl(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), foldPatchpoint(), forceReg(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), llvm::PPCRegisterInfo::getCalleeSavedRegs(), GetCostForDef(), llvm::MipsFunctionInfo::getGlobalBaseReg(), llvm::SparcInstrInfo::getGlobalBaseReg(), llvm::AMDGPUInstrInfo::getIndirectIndexBegin(), llvm::MipsFunctionInfo::getMips16SPAliasReg(), llvm::PPCInstrInfo::getOperandLatency(), llvm::SIInstrInfo::getOpRegClass(), getPrologueDeath(), llvm::ARMBaseRegisterInfo::getRegAllocationHints(), llvm::TargetRegisterInfo::getRegAllocationHints(), GetRegistersForValue(), getRegTy(), llvm::SIMachineFunctionInfo::getSpilledReg(), llvm::VirtRegMap::grow(), HandleVRSaveUpdate(), hasReassocSibling(), hasVGPROperands(), hasVirtualRegDefsInBasicBlock(), llvm::RegPressureTracker::init(), llvm::AArch64InstrInfo::insertSelect(), llvm::PPCInstrInfo::insertSelect(), isEAXLiveIn(), isNonFoldablePartialRegisterLoad(), llvm::SIInstrInfo::isOperandLegal(), llvm::SIInstrInfo::legalizeOperands(), llvm::SIInstrInfo::legalizeOpWithMove(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::R600TargetLowering::LowerOperation(), llvm::PPCRegisterInfo::lowerVRSAVERestore(), llvm::PPCRegisterInfo::lowerVRSAVESpilling(), llvm::MachineSSAUpdater::MachineSSAUpdater(), llvm::AArch64RegisterInfo::materializeFrameBaseRegister(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), llvm::SIInstrInfo::moveToVALU(), MustSaveLR(), needToReserveScavengingSpillSlots(), llvm::AArch64InstrInfo::optimizeCondBranch(), llvm::BranchFolder::OptimizeFunction(), llvm::ARMBaseInstrInfo::optimizeSelect(), llvm::HexagonInstrInfo::PredicateInstruction(), llvm::MachineInstr::print(), llvm::SystemZFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::BPFFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::MipsSEFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::Mips16FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::HexagonFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::XCoreFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::X86FrameLowering::processFunctionBeforeCalleeSavedScan(), reassociateOps(), llvm::LiveRangeCalc::reset(), llvm::PPCRegisterInfo::resolveFrameIndex(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::MachineTraceMetrics::runOnMachineFunction(), llvm::RegisterClassInfo::runOnMachineFunction(), llvm::LiveVariables::runOnMachineFunction(), llvm::LiveIntervals::runOnMachineFunction(), llvm::FunctionLoweringInfo::set(), llvm::CoalescerPair::setRegisters(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), llvm::MachineBasicBlock::SplitCriticalEdge(), llvm::SIInstrInfo::splitSMRD(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::tryFoldSPUpdateIntoPushPop(), UpdateOperandRegClass(), llvm::ARMBaseRegisterInfo::updateRegAllocHint(), usesTheStack(), llvm::SIInstrInfo::verifyInstruction(), and llvm::SelectionDAGBuilder::visitLandingPadClauseBB().
const MachineRegisterInfo& llvm::MachineFunction::getRegInfo () const [inline]
Definition at line 189 of file MachineFunction.h.
const TargetSubtargetInfo& llvm::MachineFunction::getSubtarget () const [inline]
getSubtarget - Return the subtarget for which this machine code is being compiled.
Definition at line 176 of file MachineFunction.h.
Referenced by llvm::MachineBasicBlock::addLiveIn(), addLiveInRegs(), llvm::ScheduleDAGInstrs::addPhysRegDataDeps(), addSavedGPR(), llvm::ScheduleDAGInstrs::addVRegUseDeps(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::CCState::analyzeMustTailForwardedRegisters(), llvm::A57ChainingConstraint::apply(), llvm::DwarfDebug::beginFunction(), llvm::ScheduleDAGInstrs::buildSchedGraph(), llvm::SIInstrInfo::calculateLDSSpillAddress(), llvm::LiveRangeEdit::calculateRegClassAndHint(), llvm::VirtRegAuxInfo::calculateSpillWeightAndHint(), llvm::MachineBasicBlock::canFallThrough(), llvm::MipsRegisterInfo::canRealignStack(), llvm::ARMBaseRegisterInfo::canRealignStack(), CC_MipsO32(), checkNumAlignedDPRCS2Regs(), llvm::TargetSchedModel::computeOutputLatency(), llvm::Thumb1InstrInfo::copyPhysReg(), llvm::createBURRListDAGScheduler(), llvm::createDefaultScheduler(), llvm::ARM::createFastISel(), llvm::PPC::createFastISel(), llvm::createHybridListDAGScheduler(), llvm::createILPListDAGScheduler(), llvm::FunctionLoweringInfo::CreateReg(), llvm::FunctionLoweringInfo::CreateRegs(), llvm::createSourceListDAGScheduler(), llvm::PPCInstrInfo::CreateTargetPostRAHazardRecognizer(), llvm::TargetOptions::DisableFramePointerElim(), llvm::AArch64FrameLowering::eliminateCallFramePseudoInstr(), llvm::MSP430FrameLowering::eliminateCallFramePseudoInstr(), llvm::XCoreFrameLowering::eliminateCallFramePseudoInstr(), llvm::BPFRegisterInfo::eliminateFrameIndex(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), emitAligningInstructions(), llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), emitComments(), emitDebugLocValue(), emitDebugValueComment(), llvm::AsmPrinter::EmitDwarfRegOp(), llvm::SparcFrameLowering::emitEpilogue(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::SystemZFrameLowering::emitEpilogue(), llvm::MipsAsmPrinter::emitFrameDirective(), llvm::SystemZAsmPrinter::EmitInstruction(), llvm::AMDGPUAsmPrinter::EmitInstruction(), llvm::X86AsmPrinter::EmitInstruction(), llvm::BPFTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::AsmPrinter::EmitJumpTableInfo(), llvm::ThumbRegisterInfo::emitLoadConstPool(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::PPCDispatchGroupSBHazardRecognizer::EmitNoop(), llvm::NVPTXFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::HexagonFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::MSP430TargetLowering::EmitShiftInstr(), llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), EmitTailCallStoreFPAndRetAddr(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), emitThumb1LoadConstPool(), emitThumb2LoadConstPool(), llvm::RegScavenger::enterBasicBlock(), llvm::MachineFrameInfo::estimateStackSize(), llvm::DebugLocEntry::finalize(), llvm::finalizeBundle(), llvm::ARMFrameLowering::fixTCReturn(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), llvm::PPCRegisterInfo::getBaseRegister(), llvm::MSP430RegisterInfo::getCalleeSavedRegs(), llvm::XCoreRegisterInfo::getCalleeSavedRegs(), llvm::MipsRegisterInfo::getCalleeSavedRegs(), llvm::HexagonRegisterInfo::getCalleeSavedRegs(), llvm::PPCRegisterInfo::getCalleeSavedRegs(), llvm::ARMBaseRegisterInfo::getCalleeSavedRegs(), llvm::HexagonRegisterInfo::getCallerSavedRegs(), llvm::MipsRegisterInfo::getCallPreservedMask(), llvm::PPCRegisterInfo::getCallPreservedMask(), llvm::ARMBaseRegisterInfo::getCallPreservedMask(), getFPMode(), llvm::TargetFrameLowering::getFrameIndexReference(), llvm::MSP430RegisterInfo::getFrameRegister(), llvm::XCoreRegisterInfo::getFrameRegister(), llvm::SystemZRegisterInfo::getFrameRegister(), llvm::MipsRegisterInfo::getFrameRegister(), llvm::HexagonRegisterInfo::getFrameRegister(), llvm::AArch64RegisterInfo::getFrameRegister(), llvm::PPCRegisterInfo::getFrameRegister(), llvm::ARMBaseRegisterInfo::getFrameRegister(), llvm::MipsFunctionInfo::getGlobalBaseReg(), llvm::ARMHazardRecognizer::getHazardType(), llvm::AMDGPUInstrInfo::getIndirectIndexEnd(), llvm::MSP430InstrInfo::GetInstSizeInBytes(), llvm::ThumbRegisterInfo::getLargestLegalSuperClass(), llvm::PPCRegisterInfo::getLargestLegalSuperClass(), llvm::SIMachineFunctionInfo::getMaximumWorkGroupSize(), getMemcpyLoadsAndStores(), llvm::SparcRegisterInfo::getPointerRegClass(), llvm::ThumbRegisterInfo::getPointerRegClass(), llvm::MipsRegisterInfo::getPointerRegClass(), llvm::MachineFrameInfo::getPristineRegs(), GetRegistersForValue(), llvm::MipsRegisterInfo::getRegPressureLimit(), llvm::PPCRegisterInfo::getRegPressureLimit(), llvm::AArch64RegisterInfo::getRegPressureLimit(), llvm::ARMBaseRegisterInfo::getRegPressureLimit(), llvm::SIRegisterInfo::getRegPressureSetLimit(), llvm::R600RegisterInfo::getReservedRegs(), llvm::SIRegisterInfo::getReservedRegs(), llvm::MSP430RegisterInfo::getReservedRegs(), llvm::SparcRegisterInfo::getReservedRegs(), llvm::XCoreRegisterInfo::getReservedRegs(), llvm::SystemZRegisterInfo::getReservedRegs(), llvm::MipsRegisterInfo::getReservedRegs(), llvm::AArch64RegisterInfo::getReservedRegs(), llvm::PPCRegisterInfo::getReservedRegs(), llvm::ARMBaseRegisterInfo::getReservedRegs(), llvm::TargetInstrInfo::getSPAdjust(), llvm::SIMachineFunctionInfo::getSpilledReg(), llvm::TargetInstrInfo::getStackSlotRange(), llvm::SelectionDAG::getSubtarget(), llvm::AsmPrinter::getSubtargetInfo(), llvm::MachineRegisterInfo::getTargetRegisterInfo(), llvm::ARMBaseRegisterInfo::getThisReturnPreservedMask(), llvm::CCState::HandleByVal(), HandleVRSaveUpdate(), llvm::ARMBaseRegisterInfo::hasBasePointer(), llvm::ARMFrameLowering::hasFP(), llvm::AArch64FrameLowering::hasFP(), llvm::PPCRegisterInfo::hasReservedSpillSlot(), llvm::RegPressureTracker::init(), llvm::ConvergingVLIWScheduler::initialize(), llvm::PostGenericScheduler::initialize(), llvm::GenericScheduler::initPolicy(), initReachingDef(), llvm::AArch64RegisterInfo::isReservedReg(), llvm::TargetInstrInfo::isSchedulingBoundary(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::PPCRegisterInfo::lowerVRSAVERestore(), llvm::PPCRegisterInfo::lowerVRSAVESpilling(), llvm::MachineSSAUpdater::MachineSSAUpdater(), llvm::AArch64RegisterInfo::materializeFrameBaseRegister(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), MIsNeedChainEdge(), llvm::SIInstrInfo::moveSMRDToVALU(), llvm::AArch64RegisterInfo::needsFrameBaseReg(), llvm::PPCRegisterInfo::needsFrameBaseReg(), llvm::ARMBaseRegisterInfo::needsFrameBaseReg(), llvm::MipsRegisterInfo::needsStackRealignment(), llvm::ARMBaseRegisterInfo::needsStackRealignment(), llvm::PPCRegisterInfo::needsStackRealignment(), llvm::ARMFrameLowering::noFramePointerElim(), llvm::PPCDispatchGroupSBHazardRecognizer::PreEmitNoops(), print(), llvm::MachineFrameInfo::print(), llvm::MachineBasicBlock::print(), llvm::MachineInstr::print(), llvm::ARMAsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::printOperand(), llvm::MipsAsmPrinter::printSavedRegsBitmask(), llvm::SystemZFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::HexagonFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), reassociateOps(), llvm::MachineRegisterInfo::recomputeRegClass(), replaceFI(), llvm::R600InstrInfo::reserveIndirectRegisters(), llvm::ThumbRegisterInfo::resolveFrameIndex(), llvm::AArch64RegisterInfo::resolveFrameIndex(), llvm::PPCRegisterInfo::resolveFrameIndex(), llvm::ARMBaseRegisterInfo::resolveFrameIndex(), llvm::AArch64FrameLowering::resolveFrameIndexReference(), llvm::ARMFrameLowering::ResolveFrameIndexReference(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), llvm::SystemZFrameLowering::restoreCalleeSavedRegisters(), llvm::XCoreFrameLowering::restoreCalleeSavedRegisters(), llvm::MSP430FrameLowering::restoreCalleeSavedRegisters(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), restoreCRs(), llvm::ThumbRegisterInfo::rewriteFrameIndex(), llvm::HexagonAsmPrinter::runOnMachineFunction(), llvm::MipsDAGToDAGISel::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::MachineTraceMetrics::runOnMachineFunction(), llvm::RegisterClassInfo::runOnMachineFunction(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::LiveStacks::runOnMachineFunction(), llvm::MipsAsmPrinter::runOnMachineFunction(), llvm::X86AsmPrinter::runOnMachineFunction(), llvm::LiveVariables::runOnMachineFunction(), llvm::LiveIntervals::runOnMachineFunction(), llvm::NVPTXAsmPrinter::runOnMachineFunction(), llvm::Mips16RegisterInfo::saveScavengerRegister(), llvm::ThumbRegisterInfo::saveScavengerRegister(), llvm::ScheduleDAGInstrs::ScheduleDAGInstrs(), llvm::FunctionLoweringInfo::set(), setCallTargetReg(), llvm::X86MachineFunctionInfo::setRestoreBasePointer(), llvm::SystemZFrameLowering::spillCalleeSavedRegisters(), llvm::XCoreFrameLowering::spillCalleeSavedRegisters(), llvm::MSP430FrameLowering::spillCalleeSavedRegisters(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), llvm::MachineBasicBlock::SplitCriticalEdge(), llvm::SIInstrInfo::splitSMRD(), UpdateOperandRegClass(), llvm::DwarfCompileUnit::updateSubprogramScopeDIE(), llvm::MachineBasicBlock::updateTerminator(), llvm::HexagonRegisterInfo::useFPForScavengingIndex(), and llvm::VLIWPacketizerList::VLIWPacketizerList().
template<typename STC > const STC& llvm::MachineFunction::getSubtarget () const [inline]
getSubtarget - This method returns a pointer to the specified type of TargetSubtargetInfo.
In debug builds, it verifies that the object being returned is of the correct type.
Definition at line 182 of file MachineFunction.h.
const TargetMachine& llvm::MachineFunction::getTarget () const [inline]
getTarget - Return the target machine this machine code is compiled with
Definition at line 172 of file MachineFunction.h.
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::NVPTXTargetLowering::allowFMA(), llvm::AArch64RegisterInfo::cannotEliminateFrame(), llvm::ARMBaseRegisterInfo::cannotEliminateFrame(), llvm::X86FrameLowering::canUseLEAForSPInEpilogue(), llvm::MipsFunctionInfo::createEhDataRegsFI(), llvm::PPCFrameLowering::eliminateCallFramePseudoInstr(), llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCFrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::AsmPrinter::EmitJumpTableInfo(), llvm::NVPTXFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitStackProbeCall(), llvm::ARMBaseInstrInfo::expandPostRAPseudo(), llvm::AArch64InstrInfo::expandPostRAPseudo(), llvm::X86FrameLowering::getFrameIndexOffset(), llvm::MipsRegisterInfo::getFrameRegister(), llvm::MipsFunctionInfo::getGlobalBaseReg(), llvm::AArch64InstrInfo::GetInstSizeInBytes(), llvm::MSP430InstrInfo::GetInstSizeInBytes(), llvm::MipsInstrInfo::GetInstSizeInBytes(), llvm::ARMBaseInstrInfo::GetInstSizeInBytes(), llvm::SystemZInstrInfo::getInstSizeInBytes(), llvm::PPCInstrInfo::GetInstSizeInBytes(), getJTISymbol(), getPICBaseSymbol(), llvm::PPCFunctionInfo::getPICOffsetSymbol(), llvm::TargetInstrInfo::getStackSlotRange(), llvm::MipsFrameLowering::hasFP(), llvm::SparcFrameLowering::hasFP(), llvm::SystemZFrameLowering::hasFP(), llvm::MSP430FrameLowering::hasFP(), llvm::ARMFrameLowering::hasFP(), llvm::XCoreFrameLowering::hasFP(), llvm::X86FrameLowering::hasFP(), LowerINTRINSIC_W_CHAIN(), llvm::PPCFrameLowering::needsFP(), llvm::AArch64RegisterInfo::needsStackRealignment(), llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::MachineBasicBlock::SplitCriticalEdge(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
bool llvm::MachineFunction::hasInlineAsm () const [inline]
Returns true if the function contains any inline assembly.
Definition at line 243 of file MachineFunction.h.
Referenced by llvm::PPCRegisterInfo::getReservedRegs().
void llvm::MachineFunction::insert (iterator MBBI, MachineBasicBlock * MBB) [inline]
Definition at line 352 of file MachineFunction.h.
References llvm::ilist< NodeTy >::insert().
Referenced by llvm::PPCTargetLowering::EmitAtomicBinary(), emitBlockAfter(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::AArch64TargetLowering::EmitF128CSEL(), llvm::BPFTargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::MSP430TargetLowering::EmitShiftInstr(), EmitXBegin(), llvm::SparcTargetLowering::expandAtomicRMW(), llvm::SparcTargetLowering::expandSelectCC(), llvm::SelectionDAGBuilder::FindMergedConditions(), llvm::MIRParserImpl::initializeMachineFunction(), and llvm::MachineBasicBlock::SplitCriticalEdge().
void MachineFunction::print (raw_ostream & OS, SlotIndexes * Indexes = nullptr) const
print - Print out the MachineFunction in a format suitable for debugging to the specified stream.
Definition at line 330 of file MachineFunction.cpp.
References getName(), llvm::TargetSubtargetInfo::getRegisterInfo(), getSubtarget(), I, llvm::MachineRegisterInfo::isSSA(), llvm::MachineRegisterInfo::livein_begin(), llvm::MachineRegisterInfo::livein_empty(), llvm::MachineRegisterInfo::livein_end(), llvm::MachineJumpTableInfo::print(), llvm::MachineFrameInfo::print(), and llvm::MachineRegisterInfo::tracksLiveness().
Referenced by dump(), and llvm::SlotIndexes::runOnMachineFunction().
void llvm::MachineFunction::push_back (MachineBasicBlock * MBB) [inline]
Definition at line 350 of file MachineFunction.h.
References llvm::ilist< NodeTy >::push_back().
Referenced by llvm::FunctionLoweringInfo::set().
void llvm::MachineFunction::push_front (MachineBasicBlock * MBB) [inline]
Definition at line 351 of file MachineFunction.h.
References llvm::ilist< NodeTy >::push_front().
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), and llvm::X86FrameLowering::adjustForSegmentedStacks().
reverse_iterator llvm::MachineFunction::rbegin () [inline]
Definition at line 338 of file MachineFunction.h.
References llvm::iplist< NodeTy, Traits >::rbegin().
const_reverse_iterator llvm::MachineFunction::rbegin () const [inline]
Definition at line 339 of file MachineFunction.h.
References llvm::iplist< NodeTy, Traits >::rbegin().
void llvm::MachineFunction::remove (iterator MBBI) [inline]
Definition at line 362 of file MachineFunction.h.
References llvm::iplist< NodeTy, Traits >::remove().
Referenced by llvm::MachineBasicBlock::removeFromParent().
void llvm::MachineFunction::removeFromMBBNumbering (unsigned N) [inline]
removeFromMBBNumbering - Remove the specific machine basic block from our tracker, this is only really to be used by the MachineBasicBlock implementation.
Definition at line 384 of file MachineFunction.h.
reverse_iterator llvm::MachineFunction::rend () [inline]
Definition at line 340 of file MachineFunction.h.
References llvm::iplist< NodeTy, Traits >::rend().
const_reverse_iterator llvm::MachineFunction::rend () const [inline]
Definition at line 341 of file MachineFunction.h.
References llvm::iplist< NodeTy, Traits >::rend().
void MachineFunction::RenumberBlocks (MachineBasicBlock * MBB = nullptr)
RenumberBlocks - This discards all of the MachineBasicBlock numbers and recomputes them.
This discards all of the MachineBasicBlock numbers and recomputes them.
This guarantees that the MBB numbers are sequential, dense, and match the ordering of the blocks within the function. If a specific MachineBasicBlock is specified, only that block and those after it are renumbered.
Definition at line 140 of file MachineFunction.cpp.
References begin(), empty(), and end().
void llvm::MachineFunction::setAlignment (unsigned A) [inline]
setAlignment - Set the alignment (log2, not bytes) of the function.
Definition at line 222 of file MachineFunction.h.
References llvm::ARM_PROC::A.
Referenced by llvm::MIRParserImpl::initializeMachineFunction(), and llvm::AMDGPUAsmPrinter::runOnMachineFunction().
void llvm::MachineFunction::setExposesReturnsTwice (bool B) [inline]
setCallsSetJmp - Set a flag that indicates if there's a call to a "returns twice" function.
Definition at line 238 of file MachineFunction.h.
Referenced by llvm::MIRParserImpl::initializeMachineFunction().
void llvm::MachineFunction::setHasInlineAsm (bool B) [inline]
Set a flag that indicates that the function contains inline assembly.
Definition at line 248 of file MachineFunction.h.
Referenced by llvm::MIRParserImpl::initializeMachineFunction(), and llvm::SelectionDAGISel::runOnMachineFunction().
void llvm::MachineFunction::setSubtarget (const TargetSubtargetInfo * ST) [inline]
Definition at line 177 of file MachineFunction.h.
References llvm::AArch64DB::ST.
Referenced by llvm::MipsTargetMachine::resetSubtarget().
bool MachineFunction::shouldSplitStack ()
Should we be emitting segmented stack stuff for the function.
Definition at line 132 of file MachineFunction.cpp.
References getFunction(), and llvm::Function::hasFnAttribute().
Referenced by llvm::X86FrameLowering::emitPrologue().
unsigned llvm::MachineFunction::size () const [inline]
Definition at line 343 of file MachineFunction.h.
References llvm::iplist< NodeTy, Traits >::size().
Referenced by getJTISymbol(), reachingDef(), llvm::SlotIndexes::runOnMachineFunction(), llvm::GraphTraits< MachineFunction * >::size(), and llvm::GraphTraits< const MachineFunction * >::size().
void llvm::MachineFunction::splice (iterator InsertPt, iterator MBBI) [inline]
Definition at line 355 of file MachineFunction.h.
References llvm::iplist< NodeTy, Traits >::splice().
Referenced by llvm::MachineBasicBlock::moveAfter(), and llvm::MachineBasicBlock::moveBefore().
void llvm::MachineFunction::splice (iterator InsertPt, iterator MBBI, iterator MBBE) [inline]
Definition at line 358 of file MachineFunction.h.
References llvm::iplist< NodeTy, Traits >::splice().
void MachineFunction::verify (Pass * p = nullptr, const char * Banner = nullptr) const
verify - Run the current MachineFunction through the machine code verifier, useful for debugger use.
Definition at line 271 of file MachineVerifier.cpp.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), and llvm::RegScavenger::forward().
void MachineFunction::viewCFG () const
viewCFG - This function is meant for use from the debugger.
You can just say 'call F->viewCFG()' and a ghostview window should pop up from the program, displaying the CFG of the current function with the code for each basic block inside. This depends on there being a 'dot' and 'gv' program in your path.
Definition at line 409 of file MachineFunction.cpp.
References llvm::errs(), getName(), and llvm::ViewGraph().
void MachineFunction::viewCFGOnly () const
viewCFGOnly - This function is meant for use from the debugger.
It works just like viewCFG, but it does not include the contents of basic blocks into the nodes, just the label. If you are only interested in the CFG this can make the graph smaller.
Definition at line 419 of file MachineFunction.cpp.
References llvm::errs(), getName(), and llvm::ViewGraph().
The documentation for this class was generated from the following files:
MachineFunction.h
MachineFunction.cpp
MachineVerifier.cpp