LLVM: llvm::PSetIterator Class Reference
llvm::PSetIterator Class Reference
Iterate over the pressure sets affected by the given physical or virtual register.
#include <MachineRegisterInfo.h>
Public Member Functions
PSetIterator ()
PSetIterator (unsigned RegUnit, const MachineRegisterInfo *MRI)
bool isValid () const
unsigned getWeight () const
unsigned operator* () const
void operator++ ()
Detailed Description
Iterate over the pressure sets affected by the given physical or virtual register.
If Reg is physical, it must be a register unit (from MCRegUnitIterator).
Definition at line 1001 of file MachineRegisterInfo.h.
Constructor & Destructor Documentation
llvm::PSetIterator::PSetIterator () [inline]
Definition at line 1005 of file MachineRegisterInfo.h.
llvm::PSetIterator::PSetIterator (unsigned RegUnit, const MachineRegisterInfo * MRI) [inline]
Definition at line 1006 of file MachineRegisterInfo.h.
References llvm::MachineRegisterInfo::getRegClass(), llvm::TargetRegisterInfo::getRegClassPressureSets(), llvm::TargetRegisterInfo::getRegClassWeight(), llvm::TargetRegisterInfo::getRegUnitPressureSets(), llvm::TargetRegisterInfo::getRegUnitWeight(), llvm::MachineRegisterInfo::getTargetRegisterInfo(), llvm::TargetRegisterInfo::isVirtualRegister(), and llvm::RegClassWeight::RegWeight.
Member Function Documentation
unsigned llvm::PSetIterator::getWeight () const [inline]
Definition at line 1022 of file MachineRegisterInfo.h.
Referenced by llvm::PressureDiff::addPressureChange(), decreaseSetPressure(), llvm::RegPressureTracker::increaseRegPressure(), and increaseSetPressure().
bool llvm::PSetIterator::isValid () const [inline]
Definition at line 1020 of file MachineRegisterInfo.h.
Referenced by llvm::PressureDiff::addPressureChange(), decreaseSetPressure(), llvm::RegPressureTracker::increaseRegPressure(), increaseSetPressure(), and operator++().
unsigned llvm::PSetIterator::operator* () const [inline]
Definition at line 1024 of file MachineRegisterInfo.h.
void llvm::PSetIterator::operator++ () [inline]
Definition at line 1026 of file MachineRegisterInfo.h.
References isValid().
The documentation for this class was generated from the following file:
MachineRegisterInfo.h