LLVM: llvm::HexagonFrameLowering Class Reference
llvm::HexagonFrameLowering Class Reference
#include <HexagonFrameLowering.h>
Public Member Functions
HexagonFrameLowering ()
void emitPrologue (MachineFunction &MF, MachineBasicBlock &MBB) const override
Perform most of the PEI work here:
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const override
bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const override
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const override
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
void eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator I) const override
eliminateCallFramePseudoInstr - This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS=nullptr) const override
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
void processFunctionBeforeCalleeSavedScan (MachineFunction &MF, RegScavenger *RS) const override
processFunctionBeforeCalleeSavedScan - This method is called immediately before PrologEpilogInserter scans the physical registers used to determine what callee saved registers should be spilled.
bool targetHandlesStackFrameRounding () const override
targetHandlesStackFrameRounding - Returns true if the target is responsible for rounding up the stack frame (probably at emitPrologue time).
int getFrameIndexOffset (const MachineFunction &MF, int FI) const override
getFrameIndexOffset - Returns the displacement from the frame register to the stack frame of the specified index.
bool hasFP (const MachineFunction &MF) const override
hasFP - Return true if the specified function should have a dedicated frame pointer register.
const SpillSlot * getCalleeSavedSpillSlots (unsigned &NumEntries) const override
getCalleeSavedSpillSlots - This method returns a pointer to an array of pairs, that contains an entry for each callee saved register that must be spilled to a particular stack location if it is spilled.
bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI) const override
assignCalleeSavedSpillSlots - Allows target to override spill slot assignment logic.
bool needsAligna (const MachineFunction &MF) const
MachineInstr * getAlignaInstr (MachineFunction &MF) const
Detailed Description
Definition at line 21 of file HexagonFrameLowering.h.
Constructor & Destructor Documentation
llvm::HexagonFrameLowering::HexagonFrameLowering () [inline, explicit]
Definition at line 23 of file HexagonFrameLowering.h.
Member Function Documentation
bool HexagonFrameLowering::assignCalleeSavedSpillSlots (MachineFunction & MF, const TargetRegisterInfo * TRI, std::vector< CalleeSavedInfo > & CSI) const [override, virtual]
assignCalleeSavedSpillSlots - Allows target to override spill slot assignment logic.
If implemented, assignCalleeSavedSpillSlots() should assign frame slots to all CSI entries and return true. If this method returns false, spill slots will be assigned using generic implementation. assignCalleeSavedSpillSlots() may add, delete or rearrange elements of CSI.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1007 of file HexagonFrameLowering.cpp.
References Align(), llvm::dbgs(), DEBUG, dump_registers(), llvm::BitVector::find_first(), llvm::BitVector::find_next(), llvm::TargetRegisterClass::getAlignment(), getCalleeSavedSpillSlots(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::Value::getName(), getReg(), llvm::TargetRegisterInfo::getReservedRegs(), llvm::TargetRegisterClass::getSize(), llvm::TargetFrameLowering::getStackAlignment(), llvm::isPowerOf2_32(), llvm::MCRegisterInfo::DiffListIterator::isValid(), LLVM_FUNCTION_NAME, llvm_unreachable, fuzzer::min(), and llvm::Reserved.
void HexagonFrameLowering::eliminateCallFramePseudoInstr (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const [override, virtual]
eliminateCallFramePseudoInstr - This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
It is responsible for eliminating these instructions, replacing them with concrete instructions. This method need only be implemented if using call frame setup/destroy pseudo instructions.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 816 of file HexagonFrameLowering.cpp.
References llvm::MachineBasicBlock::erase(), llvm::MachineInstr::getOpcode(), and I.
void llvm::HexagonFrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const [inline, override, virtual]
Implements llvm::TargetFrameLowering.
Definition at line 31 of file HexagonFrameLowering.h.
void HexagonFrameLowering::emitPrologue (MachineFunction & MF, MachineBasicBlock & MBB) const [override, virtual]
Perform most of the PEI work here:
saving/restoring of the callee-saved registers,
stack frame creation and destruction. Normally, this work is distributed among various functions, but doing it in one place allows shrink-wrapping of the stack frame.
Implements llvm::TargetFrameLowering.
Definition at line 352 of file HexagonFrameLowering.cpp.
References EnableShrinkWrapping, llvm::MachineFunction::front(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFunction::getFrameInfo(), llvm::HexagonSubtarget::getRegisterInfo(), and llvm::MachineFunction::getSubtarget().
MachineInstr * HexagonFrameLowering::getAlignaInstr (MachineFunction & MF) const
Definition at line 1212 of file HexagonFrameLowering.cpp.
const SpillSlot* llvm::HexagonFrameLowering::getCalleeSavedSpillSlots (unsigned & NumEntries) const [inline, override, virtual]
getCalleeSavedSpillSlots - This method returns a pointer to an array of pairs, that contains an entry for each callee saved register that must be spilled to a particular stack location if it is spilled.
Each entry in this array contains a <register,offset> pair, indicating the fixed offset from the incoming stack pointer that each register should be spilled at. If a register is not listed here, the code generator is allowed to spill it anywhere it chooses.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 57 of file HexagonFrameLowering.h.
References llvm::array_lengthof().
Referenced by assignCalleeSavedSpillSlots().
int HexagonFrameLowering::getFrameIndexOffset (const MachineFunction & MF, int FI) const [override, virtual]
getFrameIndexOffset - Returns the displacement from the frame register to the stack frame of the specified index.
This is the default implementation which is overridden for some targets.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 721 of file HexagonFrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), and llvm::MachineFrameInfo::getObjectOffset().
bool HexagonFrameLowering::hasFP (const MachineFunction & MF) const [override, virtual]
hasFP - Return true if the specified function should have a dedicated frame pointer register.
For most targets this is true only if the function has variable sized allocas or if frame pointer elimination is disabled.
Implements llvm::TargetFrameLowering.
Definition at line 633 of file HexagonFrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFrameInfo::hasCalls(), and llvm::HexagonMachineFunctionInfo::hasClobberLR().
bool HexagonFrameLowering::needsAligna (const MachineFunction & MF) const
Definition at line 1201 of file HexagonFrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getMaxAlignment(), llvm::TargetFrameLowering::getStackAlignment(), and llvm::MachineFrameInfo::hasVarSizedObjects().
void HexagonFrameLowering::processFunctionBeforeCalleeSavedScan (MachineFunction & MF, RegScavenger * RS) const [override, virtual]
processFunctionBeforeCalleeSavedScan - This method is called immediately before PrologEpilogInserter scans the physical registers used to determine what callee saved registers should be spilled.
This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 962 of file HexagonFrameLowering.cpp.
References llvm::RegScavenger::addScavengingFrameIndex(), llvm::MachineFrameInfo::CreateSpillStackObject(), llvm::TargetRegisterClass::getAlignment(), llvm::HexagonRegisterInfo::getCalleeSavedRegs(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getRegInfo(), llvm::TargetRegisterClass::getSize(), llvm::MachineFunction::getSubtarget(), llvm::MachineRegisterInfo::isPhysRegUsed(), needToReserveScavengingSpillSlots(), NumberScavengerSlots, and llvm::MachineRegisterInfo::setPhysRegUsed().
void HexagonFrameLowering::processFunctionBeforeFrameFinalized (MachineFunction & MF, RegScavenger * RS = nullptr) const [override, virtual]
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
Once the frame is finalized, MO_FrameIndex operands are replaced with direct constants. This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 827 of file HexagonFrameLowering.cpp.
References llvm::ARM_PROC::A, llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getLocalFrameMaxAlign(), llvm::MachineFrameInfo::getLocalFrameSize(), llvm::MachineFrameInfo::getMaxAlignment(), llvm::MachineFrameInfo::getObjectIndexEnd(), llvm::MachineFrameInfo::getObjectSize(), llvm::TargetFrameLowering::getStackAlignment(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::MachineFrameInfo::isDeadObjectIndex(), llvm::MachineFrameInfo::isSpillSlotObjectIndex(), llvm::MachineFrameInfo::mapLocalFrameObject(), llvm::MachineFrameInfo::setLocalFrameMaxAlign(), llvm::MachineFrameInfo::setLocalFrameSize(), and llvm::MachineFrameInfo::setUseLocalStackAllocationBlock().
bool llvm::HexagonFrameLowering::restoreCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const [inline, override, virtual]
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 38 of file HexagonFrameLowering.h.
bool llvm::HexagonFrameLowering::spillCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const [inline, override, virtual]
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 33 of file HexagonFrameLowering.h.
bool llvm::HexagonFrameLowering::targetHandlesStackFrameRounding () const [inline, override, virtual]
targetHandlesStackFrameRounding - Returns true if the target is responsible for rounding up the stack frame (probably at emitPrologue time).
Reimplemented from llvm::TargetFrameLowering.
Definition at line 51 of file HexagonFrameLowering.h.
The documentation for this class was generated from the following files:
HexagonFrameLowering.h
HexagonFrameLowering.cpp