LLVM: llvm::cl::opt< DataType, ExternalStorage, ParserClass > Class Template Reference
llvm::cl::opt< DataType, ExternalStorage, ParserClass > Class Template Reference
#include <CommandLine.h>
Public Member Functions
void setInitialValue (const DataType &V)
ParserClass & getParser ()
template<class T >
DataType & operator= (const T &Val)
template<class... Mods>
opt (const Mods &...Ms)
Detailed Description
template<class DataType, bool ExternalStorage = false, class ParserClass = parser<DataType>>
class llvm::cl::opt< DataType, ExternalStorage, ParserClass >
Definition at line 1190 of file CommandLine.h.
Constructor & Destructor Documentation
template<class DataType, bool ExternalStorage = false, class ParserClass = parser<DataType>> template<class... Mods> llvm::cl::opt< DataType, ExternalStorage, ParserClass >::opt (const Mods &... Ms) [inline, explicit]
Definition at line 1250 of file CommandLine.h.
References llvm::cl::apply().
Member Function Documentation
template<class DataType, bool ExternalStorage = false, class ParserClass = parser<DataType>> ParserClass& llvm::cl::opt< DataType, ExternalStorage, ParserClass >::getParser () [inline]
Definition at line 1242 of file CommandLine.h.
template<class DataType, bool ExternalStorage = false, class ParserClass = parser<DataType>> template<class T > DataType& llvm::cl::opt< DataType, ExternalStorage, ParserClass >::operator= (const T & Val) [inline]
Definition at line 1244 of file CommandLine.h.
References llvm::cl::opt_storage< DataType, ExternalStorage, std::is_class< DataType >::value >::getValue(), and llvm::cl::opt_storage< DataType, ExternalStorage, std::is_class< DataType >::value >::setValue().
template<class DataType, bool ExternalStorage = false, class ParserClass = parser<DataType>> void llvm::cl::opt< DataType, ExternalStorage, ParserClass >::setInitialValue (const DataType & V) [inline]
Definition at line 1240 of file CommandLine.h.
References llvm::cl::opt_storage< DataType, ExternalStorage, std::is_class< DataType >::value >::setValue().
The documentation for this class was generated from the following file:
CommandLine.h