LLVM: llvm::HexagonMCShuffler Class Reference
llvm::HexagonMCShuffler Class Reference
#include <HexagonMCShuffler.h>
Public Member Functions
HexagonMCShuffler (MCInstrInfo const &MCII, MCSubtargetInfo const &STI, MCInst &MCB)
HexagonMCShuffler (MCInstrInfo const &MCII, MCSubtargetInfo const &STI, MCInst &MCB, const MCInst *AddMI, bool bInsertAtFront=false)
void copyTo (MCInst &MCB)
bool reshuffleTo (MCInst &MCB)
bool immextPresent () const
bool duplexPresent () const
Detailed Description
Definition at line 25 of file HexagonMCShuffler.h.
Constructor & Destructor Documentation
llvm::HexagonMCShuffler::HexagonMCShuffler (MCInstrInfo const & MCII, MCSubtargetInfo const & STI, MCInst & MCB) [inline]
Definition at line 30 of file HexagonMCShuffler.h.
llvm::HexagonMCShuffler::HexagonMCShuffler (MCInstrInfo const & MCII, MCSubtargetInfo const & STI, MCInst & MCB, const MCInst * AddMI, bool bInsertAtFront = false) [inline]
Definition at line 35 of file HexagonMCShuffler.h.
Member Function Documentation
void HexagonMCShuffler::copyTo (MCInst & MCB)
Definition at line 77 of file HexagonMCShuffler.cpp.
References llvm::MCInst::addOperand(), llvm::HexagonShuffler::begin(), llvm::HexagonShuffler::BundleFlags, llvm::MCInst::clear(), llvm::MCOperand::createImm(), llvm::MCOperand::createInst(), llvm::HexagonShuffler::end(), and I.
Referenced by llvm::HexagonMCShuffle(), and reshuffleTo().
bool llvm::HexagonMCShuffler::duplexPresent () const [inline]
Definition at line 48 of file HexagonMCShuffler.h.
bool llvm::HexagonMCShuffler::immextPresent () const [inline]
Definition at line 47 of file HexagonMCShuffler.h.
bool HexagonMCShuffler::reshuffleTo (MCInst & MCB)
Definition at line 91 of file HexagonMCShuffler.cpp.
References copyTo(), DEBUG, llvm::MCInst::dump(), llvm::HexagonShuffler::getError(), and llvm::HexagonShuffler::shuffle().
Referenced by llvm::HexagonMCShuffle().
The documentation for this class was generated from the following files:
HexagonMCShuffler.h
HexagonMCShuffler.cpp