LLVM: llvm::MachineModuleInfoMachO Class Reference
llvm::MachineModuleInfoMachO Class Reference
MachineModuleInfoMachO - This is a MachineModuleInfoImpl implementation for MachO targets.
#include <MachineModuleInfoImpls.h>
Public Member Functions
MachineModuleInfoMachO (const MachineModuleInfo &)
StubValueTy & getFnStubEntry (MCSymbol *Sym)
StubValueTy & getGVStubEntry (MCSymbol *Sym)
StubValueTy & getHiddenGVStubEntry (MCSymbol *Sym)
SymbolListTy GetFnStubList ()
Accessor methods to return the set of stubs in sorted order.
SymbolListTy GetGVStubList ()
SymbolListTy GetHiddenGVStubList ()
Detailed Description
MachineModuleInfoMachO - This is a MachineModuleInfoImpl implementation for MachO targets.
Definition at line 25 of file MachineModuleInfoImpls.h.
Constructor & Destructor Documentation
llvm::MachineModuleInfoMachO::MachineModuleInfoMachO (const MachineModuleInfo &) [inline]
Definition at line 43 of file MachineModuleInfoImpls.h.
Member Function Documentation
StubValueTy& llvm::MachineModuleInfoMachO::getFnStubEntry (MCSymbol * Sym) [inline]
Definition at line 45 of file MachineModuleInfoImpls.h.
Referenced by GetSymbolFromOperand().
SymbolListTy llvm::MachineModuleInfoMachO::GetFnStubList () [inline]
Accessor methods to return the set of stubs in sorted order.
Definition at line 61 of file MachineModuleInfoImpls.h.
References llvm::MachineModuleInfoImpl::getSortedStubs().
Referenced by llvm::X86AsmPrinter::EmitEndOfAsmFile().
StubValueTy& llvm::MachineModuleInfoMachO::getGVStubEntry (MCSymbol * Sym) [inline]
Definition at line 50 of file MachineModuleInfoImpls.h.
Referenced by llvm::TargetLoweringObjectFileMachO::getCFIPersonalitySymbol(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), GetSymbolFromOperand(), and llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference().
SymbolListTy llvm::MachineModuleInfoMachO::GetGVStubList () [inline]
Definition at line 64 of file MachineModuleInfoImpls.h.
References llvm::MachineModuleInfoImpl::getSortedStubs().
Referenced by llvm::ARMAsmPrinter::EmitEndOfAsmFile(), and llvm::X86AsmPrinter::EmitEndOfAsmFile().
StubValueTy& llvm::MachineModuleInfoMachO::getHiddenGVStubEntry (MCSymbol * Sym) [inline]
Definition at line 55 of file MachineModuleInfoImpls.h.
Referenced by GetSymbolFromOperand(), and llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference().
SymbolListTy llvm::MachineModuleInfoMachO::GetHiddenGVStubList () [inline]
Definition at line 67 of file MachineModuleInfoImpls.h.
References llvm::MachineModuleInfoImpl::getSortedStubs().
Referenced by llvm::ARMAsmPrinter::EmitEndOfAsmFile(), and llvm::X86AsmPrinter::EmitEndOfAsmFile().
The documentation for this class was generated from the following files:
MachineModuleInfoImpls.h
MachineModuleInfoImpls.cpp