LLVM: llvm::MipsRegisterInfo Class Reference
llvm::MipsRegisterInfo Class Reference
#include <MipsRegisterInfo.h>
Public Member Functions
MipsRegisterInfo ()
void adjustMipsStackFrame (MachineFunction &MF) const
Adjust the Mips stack frame.
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind) const override
Code Generation virtual methods...
unsigned getRegPressureLimit (const TargetRegisterClass *RC, MachineFunction &MF) const override
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
Mips Callee Saved Registers.
const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID) const override
BitVector getReservedRegs (const MachineFunction &MF) const override
bool requiresRegisterScavenging (const MachineFunction &MF) const override
bool trackLivenessAfterRegAlloc (const MachineFunction &MF) const override
void eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
Stack Frame Processing Methods.
void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS=nullptr) const
bool canRealignStack (const MachineFunction &MF) const
bool needsStackRealignment (const MachineFunction &MF) const override
unsigned getFrameRegister (const MachineFunction &MF) const override
Debug information queries.
virtual const TargetRegisterClass * intRegClass (unsigned Size) const =0
Return GPR register class.
Static Public Member Functions
static unsigned getRegisterNumbering (unsigned RegEnum)
getRegisterNumbering - Given the enum value for some register, e.g.
static unsigned getPICCallReg ()
Get PIC indirect call register.
static const uint32_t * getMips16RetHelperMask ()
Detailed Description
Definition at line 24 of file MipsRegisterInfo.h.
Constructor & Destructor Documentation
MipsRegisterInfo::MipsRegisterInfo ()
Definition at line 47 of file MipsRegisterInfo.cpp.
Member Function Documentation
void llvm::MipsRegisterInfo::adjustMipsStackFrame (MachineFunction & MF) const
Adjust the Mips stack frame.
bool MipsRegisterInfo::canRealignStack (const MachineFunction & MF) const
Definition at line 286 of file MipsRegisterInfo.cpp.
References llvm::BP, llvm::MachineRegisterInfo::canReserveReg(), llvm::MipsSubtarget::getFrameLowering(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::TargetFrameLowering::hasReservedCallFrame(), llvm::MipsSubtarget::hasStandardEncoding(), and llvm::MipsSubtarget::isGP32bit().
Referenced by needsStackRealignment().
void MipsRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const [override]
Stack Frame Processing Methods.
Definition at line 253 of file MipsRegisterInfo.cpp.
References DEBUG, llvm::errs(), llvm::ISD::FrameIndex, llvm::MachineFunction::getFrameInfo(), llvm::MachineOperand::getIndex(), llvm::MachineFunction::getName(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineFrameInfo::getStackSize(), and llvm::AArch64CC::MI.
const MCPhysReg * MipsRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const [override]
Mips Callee Saved Registers.
Definition at line 85 of file MipsRegisterInfo.cpp.
References llvm::MachineFunction::getSubtarget(), llvm::MipsSubtarget::isABI_N32(), llvm::MipsSubtarget::isABI_N64(), llvm::MipsSubtarget::isFP64bit(), llvm::MipsSubtarget::isFPXX(), and llvm::MipsSubtarget::isSingleFloat().
const uint32_t * MipsRegisterInfo::getCallPreservedMask (const MachineFunction & MF, CallingConv::ID) const [override]
Definition at line 106 of file MipsRegisterInfo.cpp.
References llvm::MachineFunction::getSubtarget(), llvm::MipsSubtarget::isABI_N32(), llvm::MipsSubtarget::isABI_N64(), llvm::MipsSubtarget::isFP64bit(), llvm::MipsSubtarget::isFPXX(), and llvm::MipsSubtarget::isSingleFloat().
unsigned MipsRegisterInfo::getFrameRegister (const MachineFunction & MF) const [override]
Debug information queries.
Definition at line 273 of file MipsRegisterInfo.cpp.
References llvm::MipsSubtarget::getFrameLowering(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::MipsSubtarget::inMips16Mode(), and llvm::SP.
const uint32_t * MipsRegisterInfo::getMips16RetHelperMask () [static]
Definition at line 127 of file MipsRegisterInfo.cpp.
Referenced by llvm::MipsTargetLowering::getOpndList().
unsigned MipsRegisterInfo::getPICCallReg () [static]
Get PIC indirect call register.
Definition at line 49 of file MipsRegisterInfo.cpp.
const TargetRegisterClass * MipsRegisterInfo::getPointerRegClass (const MachineFunction & MF, unsigned Kind) const [override]
Code Generation virtual methods...
Definition at line 52 of file MipsRegisterInfo.cpp.
References llvm::MipsABIInfo::ArePtrs64bit(), and llvm::MachineFunction::getSubtarget().
static unsigned llvm::MipsRegisterInfo::getRegisterNumbering (unsigned RegEnum) [static]
getRegisterNumbering - Given the enum value for some register, e.g.
Mips::RA, return the number that it corresponds to (e.g. 31).
unsigned MipsRegisterInfo::getRegPressureLimit (const TargetRegisterClass * RC, MachineFunction & MF) const [override]
Definition at line 59 of file MipsRegisterInfo.cpp.
References llvm::TargetSubtargetInfo::getFrameLowering(), llvm::TargetRegisterClass::getID(), llvm::MachineFunction::getSubtarget(), and llvm::TargetFrameLowering::hasFP().
BitVector MipsRegisterInfo::getReservedRegs (const MachineFunction & MF) const [override]
Definition at line 132 of file MipsRegisterInfo.cpp.
References llvm::array_lengthof(), llvm::sys::path::begin(), llvm::sys::path::const_iterator::end, llvm::sys::path::end(), llvm::MachineFunction::getFrameInfo(), llvm::MipsSubtarget::getFrameLowering(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getSubtarget(), llvm::Function::hasFnAttribute(), llvm::TargetFrameLowering::hasFP(), llvm::MipsFunctionInfo::hasSaveS2(), llvm::MachineFrameInfo::hasVarSizedObjects(), I, llvm::MipsSubtarget::inMips16Mode(), llvm::MipsSubtarget::isABI_O32(), llvm::MipsSubtarget::isABICalls(), llvm::MipsSubtarget::isFP64bit(), llvm::MipsSubtarget::isTargetNaCl(), needsStackRealignment(), llvm::Reserved, llvm::BitVector::set(), llvm::SP, T1, llvm::X86II::T8, llvm::MipsSubtarget::useOddSPReg(), and llvm::MipsSubtarget::useSmallSection().
Referenced by llvm::Mips16InstrInfo::makeFrame(), llvm::Mips16FrameLowering::processFunctionBeforeCalleeSavedScan(), and llvm::Mips16InstrInfo::restoreFrame().
virtual const TargetRegisterClass* llvm::MipsRegisterInfo::intRegClass (unsigned Size) const [pure virtual]
Return GPR register class.
Implemented in llvm::Mips16RegisterInfo, and llvm::MipsSERegisterInfo.
bool MipsRegisterInfo::needsStackRealignment (const MachineFunction & MF) const [override]
Definition at line 310 of file MipsRegisterInfo.cpp.
References canRealignStack(), llvm::dbgs(), DEBUG, F(), llvm::MachineFunction::getFrameInfo(), llvm::MipsSubtarget::getFrameLowering(), llvm::MachineFunction::getFunction(), llvm::Value::getName(), llvm::TargetFrameLowering::getStackAlignment(), llvm::MachineFunction::getSubtarget(), llvm::Function::hasFnAttribute(), and llvm::Attribute::StackAlignment.
Referenced by llvm::MipsSEFrameLowering::emitPrologue(), and getReservedRegs().
void llvm::MipsRegisterInfo::processFunctionBeforeFrameFinalized (MachineFunction & MF, RegScavenger * RS = nullptr) const
bool MipsRegisterInfo::requiresRegisterScavenging (const MachineFunction & MF) const [override]
Reimplemented in llvm::MipsSERegisterInfo, and llvm::Mips16RegisterInfo.
Definition at line 240 of file MipsRegisterInfo.cpp.
bool MipsRegisterInfo::trackLivenessAfterRegAlloc (const MachineFunction & MF) const [override]
Definition at line 245 of file MipsRegisterInfo.cpp.
The documentation for this class was generated from the following files:
MipsRegisterInfo.h
MipsRegisterInfo.cpp