LLVM: llvm::AMDGPUTTIImpl Class Reference
llvm::AMDGPUTTIImpl Class Reference
#include <AMDGPUTargetTransformInfo.h>
Public Member Functions
AMDGPUTTIImpl (const AMDGPUTargetMachine *TM)
AMDGPUTTIImpl (const AMDGPUTTIImpl &Arg)
AMDGPUTTIImpl (AMDGPUTTIImpl &&Arg)
AMDGPUTTIImpl & operator= (const AMDGPUTTIImpl &RHS)
AMDGPUTTIImpl & operator= (AMDGPUTTIImpl &&RHS)
bool hasBranchDivergence ()
void getUnrollingPreferences (Loop *L, TTI::UnrollingPreferences &UP)
TTI::PopcntSupportKind getPopcntSupport (unsigned TyWidth)
unsigned getNumberOfRegisters (bool Vector)
unsigned getRegisterBitWidth (bool Vector)
unsigned getMaxInterleaveFactor (unsigned VF)
Detailed Description
Definition at line 28 of file AMDGPUTargetTransformInfo.h.
Constructor & Destructor Documentation
llvm::AMDGPUTTIImpl::AMDGPUTTIImpl (const AMDGPUTargetMachine * TM) [inline, explicit]
Definition at line 40 of file AMDGPUTargetTransformInfo.h.
llvm::AMDGPUTTIImpl::AMDGPUTTIImpl (const AMDGPUTTIImpl & Arg) [inline]
Definition at line 44 of file AMDGPUTargetTransformInfo.h.
llvm::AMDGPUTTIImpl::AMDGPUTTIImpl (AMDGPUTTIImpl && Arg) [inline]
Definition at line 46 of file AMDGPUTargetTransformInfo.h.
Member Function Documentation
unsigned AMDGPUTTIImpl::getMaxInterleaveFactor (unsigned VF)
Reimplemented from llvm::BasicTTIImplBase< AMDGPUTTIImpl >.
Definition at line 79 of file AMDGPUTargetTransformInfo.cpp.
unsigned AMDGPUTTIImpl::getNumberOfRegisters (bool Vector)
Reimplemented from llvm::BasicTTIImplBase< AMDGPUTTIImpl >.
Definition at line 66 of file AMDGPUTargetTransformInfo.cpp.
References llvm::AMDGPUSubtarget::getGeneration(), and llvm::AMDGPUSubtarget::SOUTHERN_ISLANDS.
TTI::PopcntSupportKind llvm::AMDGPUTTIImpl::getPopcntSupport (unsigned TyWidth) [inline]
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 66 of file AMDGPUTargetTransformInfo.h.
References llvm::AMDGPUSubtarget::hasBCNT(), llvm::isPowerOf2_32(), llvm::TargetTransformInfo::PSK_FastHardware, and llvm::TargetTransformInfo::PSK_Software.
unsigned AMDGPUTTIImpl::getRegisterBitWidth (bool Vector)
Reimplemented from llvm::BasicTTIImplBase< AMDGPUTTIImpl >.
Definition at line 77 of file AMDGPUTargetTransformInfo.cpp.
void AMDGPUTTIImpl::getUnrollingPreferences (Loop * L, TTI::UnrollingPreferences & UP)
Reimplemented from llvm::BasicTTIImplBase< AMDGPUTTIImpl >.
Definition at line 31 of file AMDGPUTargetTransformInfo.cpp.
References llvm::Alloca, llvm::TargetTransformInfoImplBase::DL, llvm::dyn_cast(), llvm::GetElementPtrInst::getAddressSpace(), llvm::LoopBase< BlockT, LoopT >::getBlocks(), llvm::GetElementPtrInst::getPointerOperand(), llvm::GetUnderlyingObject(), I, llvm::TargetTransformInfo::UnrollingPreferences::MaxCount, llvm::TargetTransformInfo::UnrollingPreferences::Partial, AMDGPUAS::PRIVATE_ADDRESS, and llvm::TargetTransformInfo::UnrollingPreferences::Threshold.
bool llvm::AMDGPUTTIImpl::hasBranchDivergence () [inline]
Reimplemented from llvm::BasicTTIImplBase< AMDGPUTTIImpl >.
Definition at line 62 of file AMDGPUTargetTransformInfo.h.
AMDGPUTTIImpl& llvm::AMDGPUTTIImpl::operator= (const AMDGPUTTIImpl & RHS) [inline]
Definition at line 49 of file AMDGPUTargetTransformInfo.h.
References llvm::BasicTTIImplBase< AMDGPUTTIImpl >::operator=().
AMDGPUTTIImpl& llvm::AMDGPUTTIImpl::operator= (AMDGPUTTIImpl && RHS) [inline]
Definition at line 55 of file AMDGPUTargetTransformInfo.h.
References llvm::BasicTTIImplBase< AMDGPUTTIImpl >::operator=().
The documentation for this class was generated from the following files:
AMDGPUTargetTransformInfo.h
AMDGPUTargetTransformInfo.cpp