LLVM: llvm::MCOrgFragment Class Reference
llvm::MCOrgFragment Class Reference
#include <MCAssembler.h>
Public Member Functions
MCOrgFragment (const MCExpr &Offset, int8_t Value, MCSection *Sec=nullptr)
Accessors
const MCExpr & getOffset () const
uint8_t getValue () const
Static Public Member Functions
static bool classof (const MCFragment *F)
Detailed Description
Definition at line 370 of file MCAssembler.h.
Constructor & Destructor Documentation
llvm::MCOrgFragment::MCOrgFragment (const MCExpr & Offset, int8_t Value, MCSection * Sec = nullptr) [inline]
Definition at line 379 of file MCAssembler.h.
Member Function Documentation
static bool llvm::MCOrgFragment::classof (const MCFragment * F) [inline, static]
Definition at line 391 of file MCAssembler.h.
References llvm::MCFragment::FT_Org, and llvm::MCFragment::getKind().
const MCExpr& llvm::MCOrgFragment::getOffset () const [inline]
Definition at line 385 of file MCAssembler.h.
Referenced by llvm::MCAssembler::computeFragmentSize(), and llvm::MCFragment::dump().
uint8_t llvm::MCOrgFragment::getValue () const [inline]
Definition at line 387 of file MCAssembler.h.
Referenced by llvm::MCFragment::dump(), and writeFragment().
The documentation for this class was generated from the following file:
MCAssembler.h