LLVM: llvm::DWARFAbbreviationDeclaration Class Reference
llvm::DWARFAbbreviationDeclaration Class Reference
#include <DWARFAbbreviationDeclaration.h>
Classes
struct AttributeSpec
Public Types
typedef SmallVector
< AttributeSpec, 8 > AttributeSpecVector
typedef iterator_range
< AttributeSpecVector::const_iterator > attr_iterator_range
Public Member Functions
DWARFAbbreviationDeclaration ()
uint32_t getCode () const
uint32_t getTag () const
bool hasChildren () const
attr_iterator_range attributes () const
uint16_t getFormByIndex (uint32_t idx) const
uint32_t findAttributeIndex (uint16_t attr) const
bool extract (DataExtractor Data, uint32_t *OffsetPtr)
void dump (raw_ostream &OS) const
Detailed Description
Definition at line 20 of file DWARFAbbreviationDeclaration.h.
Member Typedef Documentation
typedef iterator_range<AttributeSpecVector::const_iterator> llvm::DWARFAbbreviationDeclaration::attr_iterator_range
Definition at line 36 of file DWARFAbbreviationDeclaration.h.
typedef SmallVector<AttributeSpec, 8> llvm::DWARFAbbreviationDeclaration::AttributeSpecVector
Definition at line 27 of file DWARFAbbreviationDeclaration.h.
Constructor & Destructor Documentation
DWARFAbbreviationDeclaration::DWARFAbbreviationDeclaration ()
Definition at line 24 of file DWARFAbbreviationDeclaration.cpp.
Member Function Documentation
attr_iterator_range llvm::DWARFAbbreviationDeclaration::attributes () const [inline]
Definition at line 38 of file DWARFAbbreviationDeclaration.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorTemplateCommon< T, typename >::end().
void DWARFAbbreviationDeclaration::dump (raw_ostream & OS) const
Definition at line 64 of file DWARFAbbreviationDeclaration.cpp.
References llvm::dwarf::AttributeString(), llvm::format(), llvm::dwarf::FormEncodingString(), llvm::dwarf::getTag(), and llvm::dwarf::TagString().
bool DWARFAbbreviationDeclaration::extract (DataExtractor Data, uint32_t * OffsetPtr)
Definition at line 29 of file DWARFAbbreviationDeclaration.cpp.
References llvm::Code, llvm::dwarf::DW_CHILDREN_yes, llvm::DataExtractor::getU8(), and llvm::DataExtractor::getULEB128().
Referenced by llvm::DWARFAbbreviationDeclarationSet::extract().
uint32_t DWARFAbbreviationDeclaration::findAttributeIndex (uint16_t attr) const
Definition at line 91 of file DWARFAbbreviationDeclaration.cpp.
uint32_t llvm::DWARFAbbreviationDeclaration::getCode () const [inline]
Definition at line 31 of file DWARFAbbreviationDeclaration.h.
Referenced by llvm::DWARFAbbreviationDeclarationSet::extract().
uint16_t llvm::DWARFAbbreviationDeclaration::getFormByIndex (uint32_t idx) const [inline]
Definition at line 42 of file DWARFAbbreviationDeclaration.h.
References llvm::SmallVectorTemplateCommon< T, typename >::size().
uint32_t llvm::DWARFAbbreviationDeclaration::getTag () const [inline]
Definition at line 32 of file DWARFAbbreviationDeclaration.h.
Referenced by llvm::DWARFDebugInfoEntryMinimal::getTag().
bool llvm::DWARFAbbreviationDeclaration::hasChildren () const [inline]
Definition at line 33 of file DWARFAbbreviationDeclaration.h.
Referenced by llvm::DWARFDebugInfoEntryMinimal::hasChildren().
The documentation for this class was generated from the following files:
DWARFAbbreviationDeclaration.h
DWARFAbbreviationDeclaration.cpp