LLVM: llvm::TargetLibraryAnalysis Class Reference
llvm::TargetLibraryAnalysis Class Reference
Analysis pass providing the TargetLibraryInfo.
#include <TargetLibraryInfo.h>
Public Types
typedef TargetLibraryInfo Result
Public Member Functions
TargetLibraryAnalysis ()
Default construct the library analysis.
TargetLibraryAnalysis (TargetLibraryInfoImpl PresetInfoImpl)
Construct a library analysis with preset info.
TargetLibraryAnalysis (TargetLibraryAnalysis &&Arg)
TargetLibraryAnalysis & operator= (TargetLibraryAnalysis &&RHS)
TargetLibraryInfo run (Module &M)
TargetLibraryInfo run (Function &F)
Static Public Member Functions
static void * ID ()
Opaque, unique identifier for this analysis pass.
static StringRef name ()
Provide access to a name for this pass for debugging purposes.
Detailed Description
Analysis pass providing the TargetLibraryInfo.
Note that this pass's result cannot be invalidated, it is immutable for the life of the module.
Definition at line 265 of file TargetLibraryInfo.h.
Member Typedef Documentation
typedef TargetLibraryInfo llvm::TargetLibraryAnalysis::Result
Definition at line 267 of file TargetLibraryInfo.h.
Constructor & Destructor Documentation
llvm::TargetLibraryAnalysis::TargetLibraryAnalysis () [inline]
Default construct the library analysis.
This will use the module's triple to construct the library info for that module.
Definition at line 276 of file TargetLibraryInfo.h.
llvm::TargetLibraryAnalysis::TargetLibraryAnalysis (TargetLibraryInfoImpl PresetInfoImpl) [inline]
Construct a library analysis with preset info.
This will directly copy the preset info into the result without consulting the module's triple.
Definition at line 282 of file TargetLibraryInfo.h.
llvm::TargetLibraryAnalysis::TargetLibraryAnalysis (TargetLibraryAnalysis && Arg) [inline]
Definition at line 286 of file TargetLibraryInfo.h.
Member Function Documentation
static void* llvm::TargetLibraryAnalysis::ID () [inline, static]
Opaque, unique identifier for this analysis pass.
Definition at line 270 of file TargetLibraryInfo.h.
static StringRef llvm::TargetLibraryAnalysis::name () [inline, static]
Provide access to a name for this pass for debugging purposes.
Definition at line 298 of file TargetLibraryInfo.h.
TargetLibraryAnalysis& llvm::TargetLibraryAnalysis::operator= (TargetLibraryAnalysis && RHS) [inline]
Definition at line 288 of file TargetLibraryInfo.h.
TargetLibraryInfo TargetLibraryAnalysis::run (Module & M)
Definition at line 555 of file TargetLibraryInfo.cpp.
References llvm::Module::getTargetTriple().
TargetLibraryInfo TargetLibraryAnalysis::run (Function & F)
Definition at line 562 of file TargetLibraryInfo.cpp.
References llvm::GlobalValue::getParent(), and llvm::Module::getTargetTriple().
The documentation for this class was generated from the following files:
TargetLibraryInfo.h
TargetLibraryInfo.cpp