LLVM: llvm::DILexicalBlockBase Class Reference
llvm::DILexicalBlockBase Class Reference
#include <DebugInfoMetadata.h>
Public Member Functions
DILocalScope * getScope () const
Metadata * getRawScope () const
unsigned getLine () const
Forwarding accessors to LexicalBlock.
unsigned getColumn () const
Static Public Member Functions
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
DILexicalBlockBase (LLVMContext &C, unsigned ID, StorageType Storage, ArrayRef< Metadata * > Ops)
~DILexicalBlockBase ()
Detailed Description
Definition at line 1432 of file DebugInfoMetadata.h.
Constructor & Destructor Documentation
llvm::DILexicalBlockBase::DILexicalBlockBase (LLVMContext & C, unsigned ID, StorageType Storage, ArrayRef< Metadata * > Ops) [inline, protected]
Definition at line 1434 of file DebugInfoMetadata.h.
llvm::DILexicalBlockBase::~DILexicalBlockBase () [protected]
Member Function Documentation
static bool llvm::DILexicalBlockBase::classof (const Metadata * MD) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::DILocalScope.
Reimplemented in llvm::DILexicalBlockFile, and llvm::DILexicalBlock.
Definition at line 1451 of file DebugInfoMetadata.h.
References llvm::Metadata::DILexicalBlockFileKind, llvm::Metadata::DILexicalBlockKind, and llvm::Metadata::getMetadataID().
unsigned llvm::DILexicalBlockBase::getColumn () const [inline]
Reimplemented in llvm::DILexicalBlockFile, and llvm::DILexicalBlock.
Definition at line 1512 of file DebugInfoMetadata.h.
References N.
unsigned llvm::DILexicalBlockBase::getLine () const [inline]
Forwarding accessors to LexicalBlock.
TODO: Remove these and update code to use DILexicalBlock directly.
Reimplemented in llvm::DILexicalBlockFile, and llvm::DILexicalBlock.
Definition at line 1506 of file DebugInfoMetadata.h.
References N.
Metadata* llvm::DILexicalBlockBase::getRawScope () const [inline]
Definition at line 1442 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getScope(), llvm::MDNodeKeyImpl< DILexicalBlock >::isKeyOf(), and llvm::MDNodeKeyImpl< DILexicalBlockFile >::isKeyOf().
DILocalScope* llvm::DILexicalBlockBase::getScope () const [inline]
Reimplemented from llvm::DIScope.
Definition at line 1440 of file DebugInfoMetadata.h.
References getRawScope().
Referenced by WriteDILexicalBlock(), and WriteDILexicalBlockFile().
The documentation for this class was generated from the following file:
DebugInfoMetadata.h