LLVM: llvm::MCSafeSEHFragment Class Reference
llvm::MCSafeSEHFragment Class Reference
#include <MCAssembler.h>
Public Member Functions
MCSafeSEHFragment (const MCSymbol *Sym, MCSection *Sec=nullptr)
Accessors
const MCSymbol * getSymbol ()
const MCSymbol * getSymbol () const
Static Public Member Functions
static bool classof (const MCFragment *F)
Detailed Description
Definition at line 495 of file MCAssembler.h.
Constructor & Destructor Documentation
llvm::MCSafeSEHFragment::MCSafeSEHFragment (const MCSymbol * Sym, MCSection * Sec = nullptr) [inline]
Definition at line 499 of file MCAssembler.h.
Member Function Documentation
static bool llvm::MCSafeSEHFragment::classof (const MCFragment * F) [inline, static]
Definition at line 510 of file MCAssembler.h.
References llvm::MCFragment::FT_SafeSEH, and llvm::MCFragment::getKind().
const MCSymbol* llvm::MCSafeSEHFragment::getSymbol () [inline]
Definition at line 505 of file MCAssembler.h.
Referenced by llvm::MCFragment::dump(), and writeFragment().
const MCSymbol* llvm::MCSafeSEHFragment::getSymbol () const [inline]
Definition at line 506 of file MCAssembler.h.
The documentation for this class was generated from the following file:
MCAssembler.h