LLVM: llvm::DIExpression Class Reference
llvm::DIExpression Class Reference
DWARF expression.
#include <DebugInfoMetadata.h>
Classes
class expr_op_iterator
An iterator for expression operands.
class ExprOperand
A lightweight wrapper around an expression operand.
Public Types
typedef ArrayRef< uint64_t >
::iterator element_iterator
Public Member Functions
DEFINE_MDNODE_GET (DIExpression,(ArrayRef< uint64_t > Elements),(Elements)) TempDIExpression clone() const
ArrayRef< uint64_t > getElements () const
unsigned getNumElements () const
uint64_t getElement (unsigned I) const
bool isBitPiece () const
Return whether this is a piece of an aggregate variable.
uint64_t getBitPieceOffset () const
Return the offset of this piece in bits.
uint64_t getBitPieceSize () const
Return the size of this piece in bits.
element_iterator elements_begin () const
element_iterator elements_end () const
bool isValid () const
expr_op_iterator expr_op_begin () const
Visit the elements via ExprOperand wrappers.
expr_op_iterator expr_op_end () const
Static Public Member Functions
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
Friends
class LLVMContextImpl
class MDNode
Detailed Description
DWARF expression.
This is (almost) a DWARF expression that modifies the location of a variable or (or the location of a single piece of a variable).
FIXME: Instead of DW_OP_plus taking an argument, this should use DW_OP_const and have DW_OP_plus consume the topmost elements on the stack.
TODO: Co-allocate the expression elements. TODO: Separate from MDNode, or otherwise drop Distinct and Temporary storage types.
Definition at line 1942 of file DebugInfoMetadata.h.
Member Typedef Documentation
typedef ArrayRef<uint64_t>::iterator llvm::DIExpression::element_iterator
Definition at line 1983 of file DebugInfoMetadata.h.
Member Function Documentation
static bool llvm::DIExpression::classof (const Metadata * MD) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::MDNode.
Definition at line 2073 of file DebugInfoMetadata.h.
References llvm::Metadata::DIExpressionKind, and llvm::Metadata::getMetadataID().
llvm::DIExpression::DEFINE_MDNODE_GET (DIExpression , (ArrayRef< uint64_t > Elements) , (Elements)) const [inline]
Definition at line 1962 of file DebugInfoMetadata.h.
element_iterator llvm::DIExpression::elements_begin () const [inline]
Definition at line 1984 of file DebugInfoMetadata.h.
References llvm::ArrayRef< T >::begin(), and getElements().
Referenced by expr_op_begin(), and WriteDIExpression().
element_iterator llvm::DIExpression::elements_end () const [inline]
Definition at line 1985 of file DebugInfoMetadata.h.
References llvm::ArrayRef< T >::end(), and getElements().
Referenced by expr_op_end(), and WriteDIExpression().
expr_op_iterator llvm::DIExpression::expr_op_begin () const [inline]
Visit the elements via ExprOperand wrappers.
These range iterators visit elements through ExprOperand wrappers. This is not guaranteed to be a valid range unless isValid() gives true.
Precondition:
isValid() gives true.
Definition at line 2063 of file DebugInfoMetadata.h.
References elements_begin().
Referenced by llvm::DwarfExpression::AddMachineRegExpression(), emitDebugLocValue(), and isValid().
expr_op_iterator llvm::DIExpression::expr_op_end () const [inline]
Definition at line 2066 of file DebugInfoMetadata.h.
References elements_end().
Referenced by llvm::DwarfExpression::AddMachineRegExpression(), emitDebugLocValue(), and isValid().
uint64_t DIExpression::getBitPieceOffset () const
Return the offset of this piece in bits.
Definition at line 517 of file DebugInfoMetadata.cpp.
References getElement(), getNumElements(), and isBitPiece().
Referenced by emitDebugValueComment(), llvm::DebugLocEntry::finalize(), llvm::operator<(), and piecesOverlap().
uint64_t DIExpression::getBitPieceSize () const
Return the size of this piece in bits.
Definition at line 522 of file DebugInfoMetadata.cpp.
References getElement(), getNumElements(), and isBitPiece().
Referenced by emitDebugValueComment(), llvm::DebugLocEntry::finalize(), and piecesOverlap().
uint64_t llvm::DIExpression::getElement (unsigned I) const [inline]
Definition at line 1969 of file DebugInfoMetadata.h.
References I, and llvm::ArrayRef< T >::size().
Referenced by getBitPieceOffset(), getBitPieceSize(), and isBitPiece().
ArrayRef<uint64_t> llvm::DIExpression::getElements () const [inline]
Definition at line 1966 of file DebugInfoMetadata.h.
Referenced by elements_begin(), elements_end(), llvm::MDNodeKeyImpl< DIExpression >::isKeyOf(), and WriteDIExpression().
unsigned llvm::DIExpression::getNumElements () const [inline]
Definition at line 1968 of file DebugInfoMetadata.h.
References llvm::ArrayRef< T >::size().
Referenced by emitDebugLocValue(), getBitPieceOffset(), getBitPieceSize(), llvm::DbgVariable::hasComplexAddress(), and isBitPiece().
bool DIExpression::isBitPiece () const
Return whether this is a piece of an aggregate variable.
Definition at line 509 of file DebugInfoMetadata.cpp.
References getElement(), getNumElements(), isValid(), and N.
Referenced by llvm::DbgVariable::addMMIEntry(), emitDebugValueComment(), getBitPieceOffset(), getBitPieceSize(), llvm::DebugLocEntry::Value::isBitPiece(), and piecesOverlap().
bool DIExpression::isValid () const
Definition at line 488 of file DebugInfoMetadata.cpp.
References expr_op_begin(), expr_op_end(), and I.
Referenced by llvm::DbgVariable::initializeMMI(), and isBitPiece().
Friends And Related Function Documentation
friend class LLVMContextImpl [friend]
Reimplemented from llvm::MDNode.
Definition at line 1943 of file DebugInfoMetadata.h.
friend class MDNode [friend]
Definition at line 1944 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
DebugInfoMetadata.h
DebugInfoMetadata.cpp