LLVM: llvm::DIDerivedTypeBase Class Reference
llvm::DIDerivedTypeBase Class Reference
Base class for DIDerivedType and DICompositeType.
#include <DebugInfoMetadata.h>
Public Member Functions
DITypeRef getBaseType () const
Metadata * getRawBaseType () const
Static Public Member Functions
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
DIDerivedTypeBase (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, unsigned Line, uint64_t SizeInBits, uint64_t AlignInBits, uint64_t OffsetInBits, unsigned Flags, ArrayRef< Metadata * > Ops)
~DIDerivedTypeBase ()
Detailed Description
Base class for DIDerivedType and DICompositeType.
TODO: Delete; they're not really related.
Definition at line 650 of file DebugInfoMetadata.h.
Constructor & Destructor Documentation
llvm::DIDerivedTypeBase::DIDerivedTypeBase (LLVMContext & C, unsigned ID, StorageType Storage, unsigned Tag, unsigned Line, uint64_t SizeInBits, uint64_t AlignInBits, uint64_t OffsetInBits, unsigned Flags, ArrayRef< Metadata * > Ops) [inline, protected]
Definition at line 652 of file DebugInfoMetadata.h.
llvm::DIDerivedTypeBase::~DIDerivedTypeBase () [protected]
Member Function Documentation
static bool llvm::DIDerivedTypeBase::classof (const Metadata * MD) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::DIType.
Reimplemented in llvm::DISubroutineType, and llvm::DICompositeTypeBase.
Definition at line 664 of file DebugInfoMetadata.h.
References llvm::Metadata::DICompositeTypeKind, llvm::Metadata::DIDerivedTypeKind, llvm::Metadata::DISubroutineTypeKind, and llvm::Metadata::getMetadataID().
DITypeRef llvm::DIDerivedTypeBase::getBaseType () const [inline]
Definition at line 661 of file DebugInfoMetadata.h.
References getRawBaseType().
Referenced by getBaseTypeSize(), llvm::DwarfUnit::getOrCreateStaticMemberDIE(), WriteDICompositeType(), and WriteDIDerivedType().
Metadata* llvm::DIDerivedTypeBase::getRawBaseType () const [inline]
Definition at line 662 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getBaseType(), llvm::MDNodeKeyImpl< DIDerivedType >::isKeyOf(), and llvm::MDNodeKeyImpl< DICompositeType >::isKeyOf().
The documentation for this class was generated from the following file:
DebugInfoMetadata.h