LLVM: llvm::opt::ArgList Class Reference
llvm::opt::ArgList Class Reference
ArgList - Ordered collection of driver arguments.
#include <ArgList.h>
Public Types
typedef SmallVector< Arg *, 16 > arglist_type
typedef arglist_type::iterator iterator
typedef
arglist_type::const_iterator const_iterator
typedef
arglist_type::reverse_iterator reverse_iterator
typedef
arglist_type::const_reverse_iterator const_reverse_iterator
Public Member Functions
iterator begin ()
iterator end ()
reverse_iterator rbegin ()
reverse_iterator rend ()
const_iterator begin () const
const_iterator end () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
arg_iterator filtered_begin (OptSpecifier Id0=0U, OptSpecifier Id1=0U, OptSpecifier Id2=0U) const
arg_iterator filtered_end () const
iterator_range< arg_iterator > filtered (OptSpecifier Id0=0U, OptSpecifier Id1=0U, OptSpecifier Id2=0U) const
void eraseArg (OptSpecifier Id)
eraseArg - Remove any option matching Id.
bool hasArgNoClaim (OptSpecifier Id) const
hasArg - Does the arg list contain any option matching Id.
bool hasArg (OptSpecifier Id) const
bool hasArg (OptSpecifier Id0, OptSpecifier Id1) const
bool hasArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2) const
Arg * getLastArgNoClaim (OptSpecifier Id) const
getLastArg - Return the last argument matching Id, or null.
Arg * getLastArgNoClaim (OptSpecifier Id0, OptSpecifier Id1) const
Arg * getLastArgNoClaim (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2) const
Arg * getLastArgNoClaim (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3) const
Arg * getLastArg (OptSpecifier Id) const
Arg * getLastArg (OptSpecifier Id0, OptSpecifier Id1) const
Arg * getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2) const
Arg * getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3) const
Arg * getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3, OptSpecifier Id4) const
Arg * getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3, OptSpecifier Id4, OptSpecifier Id5) const
Arg * getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3, OptSpecifier Id4, OptSpecifier Id5, OptSpecifier Id6) const
Arg * getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3, OptSpecifier Id4, OptSpecifier Id5, OptSpecifier Id6, OptSpecifier Id7) const
virtual const char * getArgString (unsigned Index) const =0
getArgString - Return the input argument string at Index.
virtual unsigned getNumInputArgStrings () const =0
getNumInputArgStrings - Return the number of original argument strings, which are guaranteed to be the first strings in the argument string list.
StringRef getLastArgValue (OptSpecifier Id, StringRef Default="") const
getLastArgValue - Return the value of the last argument, or a default.
std::vector< std::string > getAllArgValues (OptSpecifier Id) const
getAllArgValues - Get the values of all instances of the given argument as strings.
bool hasFlag (OptSpecifier Pos, OptSpecifier Neg, bool Default=true) const
hasFlag - Given an option Pos and its negative form Neg, return true if the option is present, false if the negation is present, and Default if neither option is given.
bool hasFlag (OptSpecifier Pos, OptSpecifier PosAlias, OptSpecifier Neg, bool Default=true) const
hasFlag - Given an option Pos, an alias PosAlias and its negative form Neg, return true if the option or its alias is present, false if the negation is present, and Default if none of the options are given.
void AddLastArg (ArgStringList &Output, OptSpecifier Id0) const
AddLastArg - Render only the last argument match Id0, if present.
void AddLastArg (ArgStringList &Output, OptSpecifier Id0, OptSpecifier Id1) const
void AddAllArgs (ArgStringList &Output, OptSpecifier Id0, OptSpecifier Id1=0U, OptSpecifier Id2=0U) const
AddAllArgs - Render all arguments matching the given ids.
void AddAllArgValues (ArgStringList &Output, OptSpecifier Id0, OptSpecifier Id1=0U, OptSpecifier Id2=0U) const
AddAllArgValues - Render the argument values of all arguments matching the given ids.
void AddAllArgsTranslated (ArgStringList &Output, OptSpecifier Id0, const char *Translation, bool Joined=false) const
AddAllArgsTranslated - Render all the arguments matching the given ids, but forced to separate args and using the provided name instead of the first option value.
void ClaimAllArgs (OptSpecifier Id0) const
ClaimAllArgs - Claim all arguments which match the given option id.
void ClaimAllArgs () const
ClaimAllArgs - Claim all arguments.
virtual const char * MakeArgStringRef (StringRef Str) const =0
Construct a constant string pointer whose lifetime will match that of the ArgList.
const char * MakeArgString (const Twine &Str) const
const char * GetOrMakeJoinedArgString (unsigned Index, StringRef LHS, StringRef RHS) const
Create an arg string for (LHS + RHS), reusing the string at Index if possible.
Arg Access
void append (Arg *A)
append - Append A to the arg list.
arglist_type & getArgs ()
const arglist_type & getArgs () const
unsigned size () const
Protected Member Functions
ArgList ()
ArgList (ArgList &&RHS)
ArgList & operator= (ArgList &&RHS)
~ArgList ()
Detailed Description
ArgList - Ordered collection of driver arguments.
The ArgList class manages a list of Arg instances as well as auxiliary data and convenience methods to allow Tools to quickly check for the presence of Arg instances for a particular Option and to iterate over groups of arguments.
Definition at line 94 of file ArgList.h.
Member Typedef Documentation
typedef SmallVector<Arg*, 16> llvm::opt::ArgList::arglist_type
Definition at line 96 of file ArgList.h.
typedef arglist_type::const_iterator llvm::opt::ArgList::const_iterator
Definition at line 98 of file ArgList.h.
typedef arglist_type::const_reverse_iterator llvm::opt::ArgList::const_reverse_iterator
Definition at line 100 of file ArgList.h.
typedef arglist_type::iterator llvm::opt::ArgList::iterator
Definition at line 97 of file ArgList.h.
typedef arglist_type::reverse_iterator llvm::opt::ArgList::reverse_iterator
Definition at line 99 of file ArgList.h.
Constructor & Destructor Documentation
llvm::opt::ArgList::ArgList () [protected]
llvm::opt::ArgList::ArgList (ArgList && RHS) [inline, protected]
Definition at line 116 of file ArgList.h.
llvm::opt::ArgList::~ArgList () [protected]
Member Function Documentation
void ArgList::AddAllArgs (ArgStringList & Output, OptSpecifier Id0, OptSpecifier Id1 = 0U, OptSpecifier Id2 = 0U) const
AddAllArgs - Render all arguments matching the given ids.
Definition at line 261 of file ArgList.cpp.
References llvm::opt::Arg::claim(), and llvm::opt::Arg::render().
void ArgList::AddAllArgsTranslated (ArgStringList & Output, OptSpecifier Id0, const char * Translation, bool Joined = false) const
AddAllArgsTranslated - Render all the arguments matching the given ids, but forced to separate args and using the provided name instead of the first option value.
Parameters:
Joined - If true, render the argument as joined with the option specifier.
Definition at line 278 of file ArgList.cpp.
References llvm::opt::Arg::claim(), llvm::opt::Arg::getValue(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
void ArgList::AddAllArgValues (ArgStringList & Output, OptSpecifier Id0, OptSpecifier Id1 = 0U, OptSpecifier Id2 = 0U) const
AddAllArgValues - Render the argument values of all arguments matching the given ids.
Definition at line 269 of file ArgList.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::opt::Arg::claim(), and llvm::opt::Arg::getValues().
void ArgList::AddLastArg (ArgStringList & Output, OptSpecifier Id0) const
AddLastArg - Render only the last argument match Id0, if present.
Definition at line 246 of file ArgList.cpp.
References llvm::ARM_PROC::A.
void ArgList::AddLastArg (ArgStringList & Output, OptSpecifier Id0, OptSpecifier Id1) const
Definition at line 253 of file ArgList.cpp.
References llvm::ARM_PROC::A.
void ArgList::append (Arg * A)
append - Append A to the arg list.
Definition at line 36 of file ArgList.cpp.
iterator llvm::opt::ArgList::begin () [inline]
Definition at line 140 of file ArgList.h.
const_iterator llvm::opt::ArgList::begin () const [inline]
Definition at line 146 of file ArgList.h.
References llvm::SmallVectorTemplateCommon< T, typename >::rend().
void ArgList::ClaimAllArgs (OptSpecifier Id0) const
ClaimAllArgs - Claim all arguments which match the given option id.
Definition at line 294 of file ArgList.cpp.
References llvm::opt::Arg::claim().
void ArgList::ClaimAllArgs () const
ClaimAllArgs - Claim all arguments.
Definition at line 299 of file ArgList.cpp.
References llvm::sys::path::begin(), and llvm::sys::path::end().
iterator llvm::opt::ArgList::end () [inline]
Definition at line 141 of file ArgList.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
const_iterator llvm::opt::ArgList::end () const [inline]
Definition at line 147 of file ArgList.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
void ArgList::eraseArg (OptSpecifier Id)
eraseArg - Remove any option matching Id.
Definition at line 40 of file ArgList.cpp.
References llvm::ARM_PROC::A, llvm::sys::path::begin(), llvm::sys::path::end(), llvm::opt::Arg::getOption(), and llvm::opt::Option::matches().
iterator_range<arg_iterator> llvm::opt::ArgList::filtered (OptSpecifier Id0 = 0U, OptSpecifier Id1 = 0U, OptSpecifier Id2 = 0U) const [inline]
Definition at line 160 of file ArgList.h.
arg_iterator llvm::opt::ArgList::filtered_begin (OptSpecifier Id0 = 0U, OptSpecifier Id1 = 0U, OptSpecifier Id2 = 0U) const [inline]
Definition at line 152 of file ArgList.h.
References llvm::SmallVectorTemplateCommon< T, typename >::rend().
arg_iterator llvm::opt::ArgList::filtered_end () const [inline]
Definition at line 156 of file ArgList.h.
std::vector< std::string > ArgList::getAllArgValues (OptSpecifier Id) const
getAllArgValues - Get the values of all instances of the given argument as strings.
Definition at line 240 of file ArgList.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorTemplateCommon< T, typename >::end().
arglist_type& llvm::opt::ArgList::getArgs () [inline]
Definition at line 133 of file ArgList.h.
const arglist_type& llvm::opt::ArgList::getArgs () const [inline]
Definition at line 134 of file ArgList.h.
virtual const char* llvm::opt::ArgList::getArgString (unsigned Index) const [pure virtual]
getArgString - Return the input argument string at Index.
Implemented in llvm::opt::final, and llvm::opt::final.
Referenced by llvm::opt::Option::accept(), and llvm::opt::OptTable::ParseOneArg().
Arg * ArgList::getLastArg (OptSpecifier Id) const
Definition at line 83 of file ArgList.cpp.
References llvm::sys::path::begin(), llvm::opt::Arg::claim(), and llvm::sys::path::end().
Referenced by hasArg().
Arg * ArgList::getLastArg (OptSpecifier Id0, OptSpecifier Id1) const
Definition at line 95 of file ArgList.cpp.
References llvm::sys::path::begin(), llvm::opt::Arg::claim(), and llvm::sys::path::end().
Arg * ArgList::getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2) const
Definition at line 109 of file ArgList.cpp.
References llvm::sys::path::begin(), llvm::opt::Arg::claim(), and llvm::sys::path::end().
Arg * ArgList::getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3) const
Definition at line 124 of file ArgList.cpp.
References llvm::sys::path::begin(), llvm::opt::Arg::claim(), and llvm::sys::path::end().
Arg * ArgList::getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3, OptSpecifier Id4) const
Definition at line 140 of file ArgList.cpp.
References llvm::sys::path::begin(), llvm::opt::Arg::claim(), and llvm::sys::path::end().
Arg * ArgList::getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3, OptSpecifier Id4, OptSpecifier Id5) const
Definition at line 158 of file ArgList.cpp.
References llvm::sys::path::begin(), llvm::opt::Arg::claim(), and llvm::sys::path::end().
Arg * ArgList::getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3, OptSpecifier Id4, OptSpecifier Id5, OptSpecifier Id6) const
Definition at line 177 of file ArgList.cpp.
References llvm::sys::path::begin(), llvm::opt::Arg::claim(), and llvm::sys::path::end().
Arg * ArgList::getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3, OptSpecifier Id4, OptSpecifier Id5, OptSpecifier Id6, OptSpecifier Id7) const
Definition at line 198 of file ArgList.cpp.
References llvm::sys::path::begin(), llvm::opt::Arg::claim(), and llvm::sys::path::end().
Arg * ArgList::getLastArgNoClaim (OptSpecifier Id) const
getLastArg - Return the last argument matching Id, or null.
Claim Whether the argument should be claimed, if it exists.
Definition at line 46 of file ArgList.cpp.
References llvm::sys::path::rbegin(), and llvm::sys::path::rend().
Referenced by hasArg().
Arg * ArgList::getLastArgNoClaim (OptSpecifier Id0, OptSpecifier Id1) const
Definition at line 54 of file ArgList.cpp.
References llvm::sys::path::rbegin(), and llvm::sys::path::rend().
Arg * ArgList::getLastArgNoClaim (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2) const
Definition at line 63 of file ArgList.cpp.
References llvm::sys::path::rbegin(), and llvm::sys::path::rend().
Arg * ArgList::getLastArgNoClaim (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3) const
Definition at line 73 of file ArgList.cpp.
References llvm::sys::path::rbegin(), and llvm::sys::path::rend().
StringRef ArgList::getLastArgValue (OptSpecifier Id, StringRef Default = "") const
getLastArgValue - Return the value of the last argument, or a default.
Definition at line 233 of file ArgList.cpp.
References llvm::ARM_PROC::A, and Default.
virtual unsigned llvm::opt::ArgList::getNumInputArgStrings () const [pure virtual]
getNumInputArgStrings - Return the number of original argument strings, which are guaranteed to be the first strings in the argument string list.
Implemented in llvm::opt::final, and llvm::opt::final.
Referenced by llvm::opt::Option::accept().
const char * ArgList::GetOrMakeJoinedArgString (unsigned Index, StringRef LHS, StringRef RHS) const
Create an arg string for (LHS + RHS), reusing the string at Index if possible.
Definition at line 305 of file ArgList.cpp.
References llvm::StringRef::data(), llvm::StringRef::endswith(), llvm::StringRef::size(), and llvm::StringRef::startswith().
Referenced by llvm::opt::Arg::render().
bool llvm::opt::ArgList::hasArg (OptSpecifier Id) const [inline]
Definition at line 179 of file ArgList.h.
bool llvm::opt::ArgList::hasArg (OptSpecifier Id0, OptSpecifier Id1) const [inline]
Definition at line 182 of file ArgList.h.
References getLastArgNoClaim().
bool llvm::opt::ArgList::hasArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2) const [inline]
Definition at line 185 of file ArgList.h.
References getLastArg().
bool llvm::opt::ArgList::hasArgNoClaim (OptSpecifier Id) const [inline]
hasArg - Does the arg list contain any option matching Id.
Claim Whether the argument should be claimed, if it exists.
Definition at line 176 of file ArgList.h.
bool ArgList::hasFlag (OptSpecifier Pos, OptSpecifier Neg, bool Default = true) const
hasFlag - Given an option Pos and its negative form Neg, return true if the option is present, false if the negation is present, and Default if neither option is given.
If both the option and its negation are present, the last one wins.
Definition at line 220 of file ArgList.cpp.
References llvm::ARM_PROC::A, and Default.
bool ArgList::hasFlag (OptSpecifier Pos, OptSpecifier PosAlias, OptSpecifier Neg, bool Default = true) const
hasFlag - Given an option Pos, an alias PosAlias and its negative form Neg, return true if the option or its alias is present, false if the negation is present, and Default if none of the options are given.
If multiple options are present, the last one wins.
Definition at line 226 of file ArgList.cpp.
References llvm::ARM_PROC::A, and Default.
const char* llvm::opt::ArgList::MakeArgString (const Twine & Str) const [inline]
Definition at line 284 of file ArgList.h.
Referenced by llvm::opt::Option::accept(), and llvm::opt::Arg::render().
virtual const char* llvm::opt::ArgList::MakeArgStringRef (StringRef Str) const [pure virtual]
Construct a constant string pointer whose lifetime will match that of the ArgList.
Implemented in llvm::opt::final, and llvm::opt::final.
ArgList& llvm::opt::ArgList::operator= (ArgList && RHS) [inline, protected]
Definition at line 117 of file ArgList.h.
Referenced by llvm::opt::final::operator=().
reverse_iterator llvm::opt::ArgList::rbegin () [inline]
Definition at line 143 of file ArgList.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
const_reverse_iterator llvm::opt::ArgList::rbegin () const [inline]
Definition at line 149 of file ArgList.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
reverse_iterator llvm::opt::ArgList::rend () [inline]
Definition at line 144 of file ArgList.h.
References llvm::SmallVectorTemplateCommon< T, typename >::rbegin().
const_reverse_iterator llvm::opt::ArgList::rend () const [inline]
Definition at line 150 of file ArgList.h.
References llvm::SmallVectorTemplateCommon< T, typename >::rbegin().
unsigned llvm::opt::ArgList::size () const [inline]
Definition at line 136 of file ArgList.h.
References llvm::SmallVectorTemplateCommon< T, typename >::size().
The documentation for this class was generated from the following files:
ArgList.h
ArgList.cpp