LLVM: llvm::coverage::RawCoverageMappingReader Class Reference
llvm::coverage::RawCoverageMappingReader Class Reference
Reader for the raw coverage mapping data.
#include <CoverageMappingReader.h>
Public Member Functions
RawCoverageMappingReader (StringRef MappingData, ArrayRef< StringRef > TranslationUnitFilenames, std::vector< StringRef > &Filenames, std::vector< CounterExpression > &Expressions, std::vector< CounterMappingRegion > &MappingRegions)
std::error_code read ()
Detailed Description
Reader for the raw coverage mapping data.
Definition at line 107 of file CoverageMappingReader.h.
Constructor & Destructor Documentation
llvm::coverage::RawCoverageMappingReader::RawCoverageMappingReader (StringRef MappingData, ArrayRef< StringRef > TranslationUnitFilenames, std::vector< StringRef > & Filenames, std::vector< CounterExpression > & Expressions, std::vector< CounterMappingRegion > & MappingRegions) [inline]
Definition at line 118 of file CoverageMappingReader.h.
Member Function Documentation
std::error_code RawCoverageMappingReader::read ()
Definition at line 224 of file CoverageMappingReader.cpp.
References llvm::coverage::CounterMappingRegion::ExpansionRegion, I, Pass, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorImpl< T >::resize(), and llvm::coverage::CounterExpression::Subtract.
Referenced by llvm::coverage::BinaryCoverageReader::readNextRecord().
The documentation for this class was generated from the following files:
CoverageMappingReader.h
CoverageMappingReader.cpp