LLVM: llvm::FaultMapParser Class Reference
llvm::FaultMapParser Class Reference
A parser for the __llvm_faultmaps section generated by the FaultMaps class above.
#include <FaultMaps.h>
Classes
class FunctionFaultInfoAccessor
class FunctionInfoAccessor
Public Member Functions
FaultMapParser (const uint8_t *Begin, const uint8_t *End)
FaultMapVersionType getFaultMapVersion () const
NumFunctionsType getNumFunctions () const
FunctionInfoAccessor getFirstFunctionInfo () const
Detailed Description
A parser for the __llvm_faultmaps section generated by the FaultMaps class above.
This parser is version locked with with the __llvm_faultmaps section generated by the version of LLVM that includes it. No guarantees are made with respect to forward or backward compatibility.
Definition at line 78 of file FaultMaps.h.
Constructor & Destructor Documentation
llvm::FaultMapParser::FaultMapParser (const uint8_t * Begin, const uint8_t * End) [inline, explicit]
Definition at line 191 of file FaultMaps.h.
Member Function Documentation
FaultMapVersionType llvm::FaultMapParser::getFaultMapVersion () const [inline]
Definition at line 194 of file FaultMaps.h.
References llvm::IndexedInstrProf::Version.
Referenced by llvm::operator<<().
FunctionInfoAccessor llvm::FaultMapParser::getFirstFunctionInfo () const [inline]
Definition at line 204 of file FaultMaps.h.
Referenced by llvm::operator<<().
NumFunctionsType llvm::FaultMapParser::getNumFunctions () const [inline]
Definition at line 200 of file FaultMaps.h.
Referenced by llvm::operator<<().
The documentation for this class was generated from the following file:
FaultMaps.h