LLVM: llvm::RuntimeDyld::SymbolInfo Class Reference
llvm::RuntimeDyld::SymbolInfo Class Reference
Information about a named symbol.
#include <RuntimeDyld.h>
Public Member Functions
SymbolInfo (std::nullptr_t)
SymbolInfo (uint64_t Address, JITSymbolFlags Flags)
operator bool () const
uint64_t getAddress () const
Detailed Description
Information about a named symbol.
Definition at line 47 of file RuntimeDyld.h.
Constructor & Destructor Documentation
llvm::RuntimeDyld::SymbolInfo::SymbolInfo (std::nullptr_t) [inline]
Definition at line 49 of file RuntimeDyld.h.
llvm::RuntimeDyld::SymbolInfo::SymbolInfo (uint64_t Address, JITSymbolFlags Flags) [inline]
Definition at line 50 of file RuntimeDyld.h.
Member Function Documentation
uint64_t llvm::RuntimeDyld::SymbolInfo::getAddress () const [inline]
Definition at line 53 of file RuntimeDyld.h.
Referenced by llvm::MCJIT::getPointerToFunction(), llvm::orc::OrcMCJITReplacement::getSymbolAddress(), and llvm::MCJIT::getSymbolAddress().
llvm::RuntimeDyld::SymbolInfo::operator bool () const [inline, explicit]
Definition at line 52 of file RuntimeDyld.h.
The documentation for this class was generated from the following file:
RuntimeDyld.h