LLVM: llvm::MCEncodedFragmentWithContents< ContentsSize > Class Template Reference
llvm::MCEncodedFragmentWithContents< ContentsSize > Class Template Reference
Interface implemented by fragments that contain encoded instructions and/or data.
#include <MCAssembler.h>
Public Member Functions
SmallVectorImpl< char > & getContents ()
const SmallVectorImpl< char > & getContents () const
Protected Member Functions
MCEncodedFragmentWithContents (MCFragment::FragmentType FType, bool HasInstructions, MCSection *Sec)
Detailed Description
template<unsigned ContentsSize>
class llvm::MCEncodedFragmentWithContents< ContentsSize >
Interface implemented by fragments that contain encoded instructions and/or data.
Definition at line 176 of file MCAssembler.h.
Constructor & Destructor Documentation
template<unsigned ContentsSize> llvm::MCEncodedFragmentWithContents< ContentsSize >::MCEncodedFragmentWithContents (MCFragment::FragmentType FType, bool HasInstructions, MCSection * Sec) [inline, protected]
Definition at line 180 of file MCAssembler.h.
Member Function Documentation
template<unsigned ContentsSize> SmallVectorImpl<char>& llvm::MCEncodedFragmentWithContents< ContentsSize >::getContents () [inline]
Definition at line 186 of file MCAssembler.h.
Referenced by llvm::MCFragment::dump(), llvm::MCObjectStreamer::EmitBytes(), llvm::MCWinCOFFStreamer::EmitCOFFSecRel32(), llvm::MCWinCOFFStreamer::EmitCOFFSectionIndex(), llvm::MCObjectStreamer::EmitFill(), llvm::MCObjectStreamer::EmitGPRel32Value(), llvm::MCObjectStreamer::EmitGPRel64Value(), llvm::MCWinCOFFStreamer::EmitInstToData(), llvm::MCObjectStreamer::EmitInstToFragment(), llvm::MCObjectStreamer::EmitValueImpl(), and llvm::MCAssembler::writeSectionData().
template<unsigned ContentsSize> const SmallVectorImpl<char>& llvm::MCEncodedFragmentWithContents< ContentsSize >::getContents () const [inline]
Definition at line 187 of file MCAssembler.h.
The documentation for this class was generated from the following file:
MCAssembler.h