LLVM: llvm::UnOpInit Class Reference
llvm::UnOpInit Class Reference
UnOpInit - !op (X) - Transform an init.
#include <Record.h>
Public Types
enum UnaryOp { CAST, HEAD, TAIL, EMPTY }
Public Member Functions
OpInit * clone (std::vector< Init * > &Operands) const override
unsigned getNumOperands () const override
Init * getOperand (unsigned i) const override
UnaryOp getOpcode () const
Init * getOperand () const
Init * Fold (Record *CurRec, MultiClass *CurMultiClass) const override
Init * resolveReferences (Record &R, const RecordVal *RV) const override
resolveReferences - This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
std::string getAsString () const override
getAsString - Convert this value to a string form.
Static Public Member Functions
static bool classof (const Init *I)
static UnOpInit * get (UnaryOp opc, Init *lhs, RecTy *Type)
Detailed Description
UnOpInit - !op (X) - Transform an init.
Definition at line 678 of file Record.h.
Member Enumeration Documentation
enum llvm::UnOpInit::UnaryOp
Enumerator:
CAST
HEAD
TAIL
EMPTY
Definition at line 680 of file Record.h.
Member Function Documentation
static bool llvm::UnOpInit::classof (const Init * I) [inline, static]
Reimplemented from llvm::OpInit.
Definition at line 693 of file Record.h.
References llvm::Init::getKind(), and llvm::Init::IK_UnOpInit.
OpInit* llvm::UnOpInit::clone (std::vector< Init * > & Operands) const [inline, override, virtual]
Implements llvm::OpInit.
Definition at line 699 of file Record.h.
References get(), getOpcode(), and llvm::TypedInit::getType().
Init * UnOpInit::Fold (Record * CurRec, MultiClass * CurMultiClass) const [override, virtual]
Implements llvm::OpInit.
Definition at line 617 of file Record.cpp.
References CAST, EMPTY, llvm::IntInit::get(), llvm::StringInit::get(), get(), llvm::DefInit::get(), getDef(), llvm::Record::getLoc(), getOpcode(), llvm::Record::getRecords(), llvm::TypedInit::getType(), llvm::RecordVal::getType(), llvm::Record::getValue(), HEAD, llvm::Record::isTemplateArg(), llvm::PrintFatalError(), llvm::QualifyName(), llvm::MultiClass::Rec, and TAIL.
Referenced by resolveReferences().
UnOpInit * UnOpInit::get (UnaryOp opc, Init * lhs, RecTy * Type) [static]
Definition at line 606 of file Record.cpp.
References I.
Referenced by clone(), Fold(), and resolveReferences().
std::string UnOpInit::getAsString () const [override, virtual]
getAsString - Convert this value to a string form.
Implements llvm::Init.
Definition at line 715 of file Record.cpp.
References CAST, EMPTY, llvm::RecTy::getAsString(), llvm::Init::getAsString(), llvm::TypedInit::getType(), HEAD, and TAIL.
unsigned llvm::UnOpInit::getNumOperands () const [inline, override, virtual]
Implements llvm::OpInit.
Definition at line 705 of file Record.h.
UnaryOp llvm::UnOpInit::getOpcode () const [inline]
Definition at line 711 of file Record.h.
Referenced by clone(), Fold(), and resolveReferences().
Init* llvm::UnOpInit::getOperand (unsigned i) const [inline, override, virtual]
Implements llvm::OpInit.
Definition at line 706 of file Record.h.
References getOperand().
Init* llvm::UnOpInit::getOperand () const [inline]
Definition at line 712 of file Record.h.
Referenced by getOperand().
Init * UnOpInit::resolveReferences (Record & R, const RecordVal * RV) const [override, virtual]
resolveReferences - This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 707 of file Record.cpp.
References Fold(), get(), getOpcode(), llvm::TypedInit::getType(), and llvm::Init::resolveReferences().
The documentation for this class was generated from the following files:
Record.h
Record.cpp