LLVM: llvm::PointerType Class Reference
llvm::PointerType Class Reference
PointerType - Class to represent pointers.
#include <DerivedTypes.h>
Public Member Functions
unsigned getAddressSpace () const
Return the address space of the Pointer type.
Static Public Member Functions
static PointerType * get (Type *ElementType, unsigned AddressSpace)
PointerType::get - This constructs a pointer to an object of the specified type in a numbered address space.
static PointerType * getUnqual (Type *ElementType)
PointerType::getUnqual - This constructs a pointer to an object of the specified type in the generic address space (address space zero).
static bool isValidElementType (Type *ElemTy)
isValidElementType - Return true if the specified type is valid as a element type.
static bool isLoadableOrStorableType (Type *ElemTy)
Return true if we can load or store from a pointer to this type.
static bool classof (const Type *T)
Implement support type inquiry through isa, cast, and dyn_cast.
Detailed Description
PointerType - Class to represent pointers.
Definition at line 449 of file DerivedTypes.h.
Member Function Documentation
static bool llvm::PointerType::classof (const Type * T) [inline, static]
Implement support type inquiry through isa, cast, and dyn_cast.
Reimplemented from llvm::SequentialType.
Definition at line 475 of file DerivedTypes.h.
References llvm::Type::getTypeID(), and llvm::Type::PointerTyID.
PointerType * PointerType::get (Type * ElementType, unsigned AddressSpace) [static]
PointerType::get - This constructs a pointer to an object of the specified type in a numbered address space.
Definition at line 735 of file Type.cpp.
References llvm::LLVMContextImpl::ASPointerTypes, llvm::Type::getContext(), isValidElementType(), llvm::LLVMContext::pImpl, llvm::LLVMContextImpl::PointerTypes, and llvm::LLVMContextImpl::TypeAllocator.
Referenced by AnalyzeLoadFromClobberingMemInst(), ConstantFoldGetElementPtrImpl(), convertMemSetToLoop(), llvm::orc::createIRTypedAddress(), CreatePrologue(), DecodeFixedType(), getAccessType(), llvm::SelectionDAG::getEVTAlignment(), getFoldedAlignOf(), getFoldedSizeOf(), llvm::GetElementPtrInst::getGEPReturnType(), GetHeapSROAValue(), GetLoadValueForLoad(), GetMemInstValueForLoad(), llvm::Module::getOrInsertGlobal(), llvm::Type::getPointerTo(), INITIALIZE_PASS(), LLVMPointerType(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), PerformHeapAllocSRoA(), SimplifyGEPInst(), and llvm::InstCombiner::visitAddrSpaceCast().
unsigned llvm::PointerType::getAddressSpace () const [inline]
Return the address space of the Pointer type.
Definition at line 472 of file DerivedTypes.h.
References llvm::Type::getSubclassData().
Referenced by canDemoteGlobalVar(), llvm::CastInst::castIsValid(), llvm::orc::cloneGlobalVariableDecl(), ConstantFoldGetElementPtrImpl(), copyGlobalVariableProto(), llvm::IRBuilder< true, TargetFolder >::CreateAlignmentAssumption(), FoldReinterpretLoadFromConstPtr(), llvm::GlobalAddressSDNode::getAddressSpace(), llvm::ConstantExpr::getAddrSpaceCast(), llvm::SelectionDAG::getGlobalAddress(), getNaturalGEPWithOffset(), INITIALIZE_PASS(), llvm::isAllocaPromotable(), isTypeCongruent(), SRAGlobal(), StripPtrCastKeepAS(), TryToShrinkGlobalToBoolean(), llvm::InstCombiner::visitAddrSpaceCast(), llvm::InstCombiner::visitGetElementPtrInst(), and WriteTypeTable().
static PointerType* llvm::PointerType::getUnqual (Type * ElementType) [inline, static]
PointerType::getUnqual - This constructs a pointer to an object of the specified type in the generic address space (address space zero).
Definition at line 460 of file DerivedTypes.h.
References llvm::IntegerType::get().
Referenced by appendToGlobalArray(), createMalloc(), DecodeFixedType(), llvm::InlineAsm::get(), llvm::TypeBuilder< T *, cross >::get(), llvm::ScalarEvolution::getElementSize(), llvm::ScalarEvolution::getGEPExpr(), getMemCmpLoad(), llvm::ConstantExpr::getOffsetOf(), llvm::Module::getOrInsertFunction(), llvm::ConstantExpr::getSizeOf(), llvm::TargetLowering::LowerCallTo(), llvm::SparcTargetLowering::LowerF128_LibCallArg(), llvm::SparcTargetLowering::LowerF128Op(), llvm::UpgradeIntrinsicCall(), and llvm::InstCombiner::visitCallInst().
bool PointerType::isLoadableOrStorableType (Type * ElemTy) [static]
Return true if we can load or store from a pointer to this type.
Definition at line 770 of file Type.cpp.
References llvm::Type::isFunctionTy(), and isValidElementType().
bool PointerType::isValidElementType (Type * ElemTy) [static]
isValidElementType - Return true if the specified type is valid as a element type.
Definition at line 765 of file Type.cpp.
References llvm::Type::isLabelTy(), llvm::Type::isMetadataTy(), and llvm::Type::isVoidTy().
Referenced by get(), and isLoadableOrStorableType().
The documentation for this class was generated from the following files:
DerivedTypes.h
Type.cpp