LLVM: llvm::DIEValue Class Reference
llvm::DIEValue Class Reference
#include <DIE.h>
Public Types
enum Type { isNone }
Public Member Functions
DIEValue ()
DIEValue (const DIEValue &X)
DIEValue & operator= (const DIEValue &X)
~DIEValue ()
Type getType () const
dwarf::Attribute getAttribute () const
dwarf::Form getForm () const
operator bool () const
void EmitValue (const AsmPrinter *AP, dwarf::Form Form) const
EmitValue - Emit value via the Dwarf writer.
unsigned SizeOf (const AsmPrinter *AP, dwarf::Form Form) const
SizeOf - Return the size of a value in bytes.
void print (raw_ostream &O) const
void dump () const
Detailed Description
Definition at line 307 of file DIE.h.
Member Enumeration Documentation
enum llvm::DIEValue::Type
Enumerator:
isNone
Definition at line 309 of file DIE.h.
Constructor & Destructor Documentation
llvm::DIEValue::DIEValue ()
llvm::DIEValue::DIEValue (const DIEValue & X) [inline]
Definition at line 393 of file DIE.h.
llvm::DIEValue::~DIEValue () [inline]
Definition at line 404 of file DIE.h.
Member Function Documentation
void DIEValue::dump () const
Definition at line 233 of file DIE.cpp.
References llvm::dbgs(), and print().
void DIEValue::EmitValue (const AsmPrinter * AP, dwarf::Form Form) const
EmitValue - Emit value via the Dwarf writer.
Definition at line 196 of file DIE.cpp.
References isNone, and llvm_unreachable.
dwarf::Attribute llvm::DIEValue::getAttribute () const [inline]
Definition at line 421 of file DIE.h.
dwarf::Form llvm::DIEValue::getForm () const [inline]
Definition at line 422 of file DIE.h.
Type llvm::DIEValue::getType () const [inline]
Definition at line 420 of file DIE.h.
llvm::DIEValue::operator bool () const [inline, explicit]
Definition at line 423 of file DIE.h.
DIEValue& llvm::DIEValue::operator= (const DIEValue & X) [inline]
Definition at line 396 of file DIE.h.
void DIEValue::print (raw_ostream & O) const
Definition at line 221 of file DIE.cpp.
References isNone, and llvm_unreachable.
Referenced by dump().
unsigned DIEValue::SizeOf (const AsmPrinter * AP, dwarf::Form Form) const
SizeOf - Return the size of a value in bytes.
Definition at line 208 of file DIE.cpp.
References isNone, and llvm_unreachable.
The documentation for this class was generated from the following files:
DIE.h
DIE.cpp