LLVM: llvm::InsertValueInst Class Reference
llvm::InsertValueInst Class Reference
InsertValueInst - This instruction inserts a struct field of array element value into an aggregate value.
#include <Instructions.h>
Public Types
typedef const unsigned * idx_iterator
Public Member Functions
void * operator new (size_t s)
Allocate a User with an operand pointer co-allocated.
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
idx_iterator idx_begin () const
idx_iterator idx_end () const
iterator_range< idx_iterator > indices () const
Value * getAggregateOperand ()
const Value * getAggregateOperand () const
Value * getInsertedValueOperand ()
const Value * getInsertedValueOperand () const
ArrayRef< unsigned > getIndices () const
unsigned getNumIndices () const
bool hasIndices () const
Static Public Member Functions
static InsertValueInst * Create (Value *Agg, Value *Val, ArrayRef< unsigned > Idxs, const Twine &NameStr="", Instruction *InsertBefore=nullptr)
static InsertValueInst * Create (Value *Agg, Value *Val, ArrayRef< unsigned > Idxs, const Twine &NameStr, BasicBlock *InsertAtEnd)
static unsigned getAggregateOperandIndex ()
static unsigned getInsertedValueOperandIndex ()
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
InsertValueInst * clone_impl () const override
Detailed Description
InsertValueInst - This instruction inserts a struct field of array element value into an aggregate value.
Definition at line 2086 of file Instructions.h.
Member Typedef Documentation
typedef const unsigned* llvm::InsertValueInst::idx_iterator
Definition at line 2137 of file Instructions.h.
Member Function Documentation
static bool llvm::InsertValueInst::classof (const Instruction * I) [inline, static]
Definition at line 2177 of file Instructions.h.
References llvm::Instruction::getOpcode().
Referenced by classof().
static bool llvm::InsertValueInst::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::Instruction.
Definition at line 2180 of file Instructions.h.
References classof().
InsertValueInst * InsertValueInst::clone_impl () const [override, protected, virtual]
Implements llvm::Instruction.
Definition at line 3477 of file Instructions.cpp.
static InsertValueInst* llvm::InsertValueInst::Create (Value * Agg, Value * Val, ArrayRef< unsigned > Idxs, const Twine & NameStr = "", Instruction * InsertBefore = nullptr) [inline, static]
Definition at line 2121 of file Instructions.h.
Referenced by BuildSubAggregate(), llvm::NoFolder::CreateInsertValue(), llvm::IRBuilder< true, TargetFolder >::CreateInsertValue(), llvm::InstCombiner::CreateOverflowTuple(), llvm::ConstantExpr::getAsInstruction(), and llvm::InstCombiner::visitExtractValueInst().
static InsertValueInst* llvm::InsertValueInst::Create (Value * Agg, Value * Val, ArrayRef< unsigned > Idxs, const Twine & NameStr, BasicBlock * InsertAtEnd) [inline, static]
Definition at line 2127 of file Instructions.h.
llvm::InsertValueInst::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
Value* llvm::InsertValueInst::getAggregateOperand () [inline]
Definition at line 2144 of file Instructions.h.
References llvm::User::getOperand().
Referenced by BuildSubAggregate(), llvm::SimplifyInstruction(), and llvm::Interpreter::visitInsertValueInst().
const Value* llvm::InsertValueInst::getAggregateOperand () const [inline]
Definition at line 2147 of file Instructions.h.
References llvm::User::getOperand().
static unsigned llvm::InsertValueInst::getAggregateOperandIndex () [inline, static]
Definition at line 2150 of file Instructions.h.
ArrayRef<unsigned> llvm::InsertValueInst::getIndices () const [inline]
Definition at line 2164 of file Instructions.h.
Referenced by llvm::SimplifyInstruction(), llvm::Interpreter::visitInsertValueInst(), and llvm::InstCombiner::visitInsertValueInst().
Value* llvm::InsertValueInst::getInsertedValueOperand () [inline]
Definition at line 2154 of file Instructions.h.
References llvm::User::getOperand().
Referenced by llvm::SimplifyInstruction().
const Value* llvm::InsertValueInst::getInsertedValueOperand () const [inline]
Definition at line 2157 of file Instructions.h.
References llvm::User::getOperand().
static unsigned llvm::InsertValueInst::getInsertedValueOperandIndex () [inline, static]
Definition at line 2160 of file Instructions.h.
unsigned llvm::InsertValueInst::getNumIndices () const [inline]
Definition at line 2168 of file Instructions.h.
References llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::Interpreter::visitInsertValueInst().
bool llvm::InsertValueInst::hasIndices () const [inline]
Definition at line 2172 of file Instructions.h.
idx_iterator llvm::InsertValueInst::idx_begin () const [inline]
Definition at line 2138 of file Instructions.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
Referenced by indices(), and llvm::Interpreter::visitInsertValueInst().
idx_iterator llvm::InsertValueInst::idx_end () const [inline]
Definition at line 2139 of file Instructions.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by indices().
iterator_range<idx_iterator> llvm::InsertValueInst::indices () const [inline]
Definition at line 2140 of file Instructions.h.
References idx_begin(), and idx_end().
void* llvm::InsertValueInst::operator new (size_t Size) [inline]
Allocate a User with an operand pointer co-allocated.
This is used for subclasses which need to allocate a variable number of operands, ie, 'hung off uses'.
Reimplemented from llvm::User.
Definition at line 2117 of file Instructions.h.
References llvm::User::operator new().
The documentation for this class was generated from the following files:
Instructions.h
Instructions.cpp