LLVM: llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst > Class Template Reference
llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst > Class Template Reference
#include <DenseMap.h>
Public Types
typedef ptrdiff_t difference_type
typedef std::conditional
< IsConst, const Bucket,
Bucket >::type value_type
typedef value_type * pointer
typedef value_type & reference
typedef std::forward_iterator_tag iterator_category
Public Member Functions
DenseMapIterator ()
DenseMapIterator (pointer Pos, pointer E, const DebugEpochBase &Epoch, bool NoAdvance=false)
template<bool IsConstSrc, typename = typename std::enable_if<!IsConstSrc && IsConst>::type>
DenseMapIterator (const DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConstSrc > &I)
reference operator* () const
pointer operator-> () const
bool operator== (const ConstIterator &RHS) const
bool operator!= (const ConstIterator &RHS) const
DenseMapIterator & operator++ ()
DenseMapIterator operator++ (int)
Friends
class DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, true >
class DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, false >
Detailed Description
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst>
class llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >
Definition at line 987 of file DenseMap.h.
Member Typedef Documentation
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> typedef ptrdiff_t llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::difference_type
Definition at line 993 of file DenseMap.h.
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> typedef std::forward_iterator_tag llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::iterator_category
Definition at line 998 of file DenseMap.h.
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> typedef value_type* llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::pointer
Definition at line 996 of file DenseMap.h.
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> typedef value_type& llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::reference
Definition at line 997 of file DenseMap.h.
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> typedef std::conditional<IsConst, const Bucket, Bucket>::type llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::value_type
Definition at line 995 of file DenseMap.h.
Constructor & Destructor Documentation
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::DenseMapIterator () [inline]
Definition at line 1002 of file DenseMap.h.
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::DenseMapIterator (pointer Pos, pointer E, const DebugEpochBase & Epoch, bool NoAdvance = false) [inline]
Definition at line 1004 of file DenseMap.h.
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> template<bool IsConstSrc, typename = typename std::enable_if<!IsConstSrc && IsConst>::type> llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::DenseMapIterator (const DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConstSrc > & I) [inline]
Definition at line 1016 of file DenseMap.h.
Member Function Documentation
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> bool llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::operator!= (const ConstIterator & RHS) const [inline]
Definition at line 1036 of file DenseMap.h.
References llvm::DebugEpochBase::HandleBase::getEpochAddress(), and llvm::DebugEpochBase::HandleBase::isHandleInSync().
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> reference llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::operator* () const [inline]
Definition at line 1020 of file DenseMap.h.
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> DenseMapIterator& llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::operator++ () [inline]
Definition at line 1044 of file DenseMap.h.
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> DenseMapIterator llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::operator++ (int) [inline]
Definition at line 1050 of file DenseMap.h.
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> pointer llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::operator-> () const [inline]
Definition at line 1024 of file DenseMap.h.
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> bool llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::operator== (const ConstIterator & RHS) const [inline]
Definition at line 1029 of file DenseMap.h.
References llvm::DebugEpochBase::HandleBase::getEpochAddress(), and llvm::DebugEpochBase::HandleBase::isHandleInSync().
Friends And Related Function Documentation
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> friend class DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, false > [friend]
Definition at line 990 of file DenseMap.h.
template<typename KeyT, typename ValueT, typename KeyInfoT, typename Bucket, bool IsConst> friend class DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, true > [friend]
Definition at line 989 of file DenseMap.h.
The documentation for this class was generated from the following file:
DenseMap.h