LLVM: llvm::AArch64AppleInstPrinter Class Reference
llvm::AArch64AppleInstPrinter Class Reference
#include <AArch64InstPrinter.h>
Public Member Functions
AArch64AppleInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printInst (const MCInst *MI, raw_ostream &O, StringRef Annot, const MCSubtargetInfo &STI) override
Print the specified MCInst to the specified raw_ostream.
void printInstruction (const MCInst *MI, const MCSubtargetInfo &STI, raw_ostream &O) override
bool printAliasInstr (const MCInst *MI, const MCSubtargetInfo &STI, raw_ostream &O) override
void printCustomAliasOperand (const MCInst *MI, unsigned OpIdx, unsigned PrintMethodIdx, const MCSubtargetInfo &STI, raw_ostream &O) override
StringRef getRegName (unsigned RegNo) const override
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo, unsigned AltIdx=AArch64::NoRegAltName)
Detailed Description
Definition at line 162 of file AArch64InstPrinter.h.
Constructor & Destructor Documentation
AArch64AppleInstPrinter::AArch64AppleInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI)
Definition at line 40 of file AArch64InstPrinter.cpp.
Member Function Documentation
static const char* llvm::AArch64AppleInstPrinter::getRegisterName (unsigned RegNo, unsigned AltIdx = AArch64::NoRegAltName) [static]
Reimplemented from llvm::AArch64InstPrinter.
Referenced by getRegName(), and printInst().
StringRef llvm::AArch64AppleInstPrinter::getRegName (unsigned RegNo) const [inline, override, virtual]
Reimplemented from llvm::AArch64InstPrinter.
Definition at line 178 of file AArch64InstPrinter.h.
References getRegisterName().
bool llvm::AArch64AppleInstPrinter::printAliasInstr (const MCInst * MI, const MCSubtargetInfo & STI, raw_ostream & O) [override, virtual]
Reimplemented from llvm::AArch64InstPrinter.
void llvm::AArch64AppleInstPrinter::printCustomAliasOperand (const MCInst * MI, unsigned OpIdx, unsigned PrintMethodIdx, const MCSubtargetInfo & STI, raw_ostream & O) [override, virtual]
Reimplemented from llvm::AArch64InstPrinter.
void AArch64AppleInstPrinter::printInst (const MCInst * MI, raw_ostream & OS, StringRef Annot, const MCSubtargetInfo & STI) [override, virtual]
Print the specified MCInst to the specified raw_ostream.
Reimplemented from llvm::AArch64InstPrinter.
Definition at line 624 of file AArch64InstPrinter.cpp.
References llvm::MCOperand::getImm(), getLdStNInstrDesc(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), isTblTbxInstruction(), llvm::MCInstPrinter::printAnnotation(), and llvm::AArch64InstPrinter::printVectorList().
void llvm::AArch64AppleInstPrinter::printInstruction (const MCInst * MI, const MCSubtargetInfo & STI, raw_ostream & O) [override, virtual]
Reimplemented from llvm::AArch64InstPrinter.
The documentation for this class was generated from the following files:
AArch64InstPrinter.h
AArch64InstPrinter.cpp