LLVM: llvm::CallInst Class Reference
llvm::CallInst Class Reference
CallInst - This class represents a function call, abstracting a target machine's calling convention.
#include <Instructions.h>
Public Types
enum TailCallKind { TCK_None = 0, TCK_Tail = 1, TCK_MustTail = 2 }
Public Member Functions
~CallInst () override
FunctionType * getFunctionType () const
void mutateFunctionType (FunctionType *FTy)
TailCallKind getTailCallKind () const
bool isTailCall () const
bool isMustTailCall () const
void setTailCall (bool isTC=true)
void setTailCallKind (TailCallKind TCK)
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Provide fast operand accessors.
unsigned getNumArgOperands () const
getNumArgOperands - Return the number of call arguments.
Value * getArgOperand (unsigned i) const
getArgOperand/setArgOperand - Return/set the i-th call argument.
void setArgOperand (unsigned i, Value *v)
iterator_range< op_iterator > arg_operands ()
arg_operands - iteration adapter for range-for loops.
iterator_range< const_op_iterator > arg_operands () const
arg_operands - iteration adapter for range-for loops.
const Use & getArgOperandUse (unsigned i) const
Wrappers for getting the Use of a call argument.
Use & getArgOperandUse (unsigned i)
CallingConv::ID getCallingConv () const
getCallingConv/setCallingConv - Get or set the calling convention of this function call.
void setCallingConv (CallingConv::ID CC)
const AttributeSet & getAttributes () const
getAttributes - Return the parameter attributes for this call.
void setAttributes (const AttributeSet &Attrs)
setAttributes - Set the parameter attributes for this call.
void addAttribute (unsigned i, Attribute::AttrKind attr)
addAttribute - adds the attribute to the list of attributes.
void removeAttribute (unsigned i, Attribute attr)
removeAttribute - removes the attribute from the list of attributes.
void addDereferenceableAttr (unsigned i, uint64_t Bytes)
adds the dereferenceable attribute to the list of attributes.
void addDereferenceableOrNullAttr (unsigned i, uint64_t Bytes)
adds the dereferenceable_or_null attribute to the list of attributes.
bool hasFnAttr (Attribute::AttrKind A) const
Determine whether this call has the given attribute.
bool paramHasAttr (unsigned i, Attribute::AttrKind A) const
Determine whether the call or the callee has the given attributes.
unsigned getParamAlignment (unsigned i) const
Extract the alignment for a call or parameter (0=unknown).
uint64_t getDereferenceableBytes (unsigned i) const
Extract the number of dereferenceable bytes for a call or parameter (0=unknown).
uint64_t getDereferenceableOrNullBytes (unsigned i) const
Extract the number of dereferenceable_or_null bytes for a call or parameter (0=unknown).
bool isNoBuiltin () const
Return true if the call should not be treated as a call to a builtin.
bool isNoInline () const
Return true if the call should not be inlined.
void setIsNoInline ()
bool canReturnTwice () const
Return true if the call can return twice.
void setCanReturnTwice ()
bool doesNotAccessMemory () const
Determine if the call does not access memory.
void setDoesNotAccessMemory ()
bool onlyReadsMemory () const
Determine if the call does not access or only reads memory.
void setOnlyReadsMemory ()
bool doesNotReturn () const
Determine if the call cannot return.
void setDoesNotReturn ()
bool doesNotThrow () const
Determine if the call cannot unwind.
void setDoesNotThrow ()
bool cannotDuplicate () const
Determine if the call cannot be duplicated.
void setCannotDuplicate ()
bool hasStructRetAttr () const
Determine if the call returns a structure through first pointer argument.
bool hasByValArgument () const
Determine if any call argument is an aggregate passed by value.
Function * getCalledFunction () const
getCalledFunction - Return the function called, or null if this is an indirect function invocation.
const Value * getCalledValue () const
getCalledValue - Get a pointer to the function that is invoked by this instruction.
Value * getCalledValue ()
void setCalledFunction (Value *Fn)
setCalledFunction - Set the function called.
void setCalledFunction (FunctionType *FTy, Value *Fn)
bool isInlineAsm () const
isInlineAsm - Check if this call is an inline asm statement.
Static Public Member Functions
static CallInst * Create (Value *Func, ArrayRef< Value * > Args, const Twine &NameStr="", Instruction *InsertBefore=nullptr)
static CallInst * Create (FunctionType *Ty, Value *Func, ArrayRef< Value * > Args, const Twine &NameStr="", Instruction *InsertBefore=nullptr)
static CallInst * Create (Value *Func, ArrayRef< Value * > Args, const Twine &NameStr, BasicBlock *InsertAtEnd)
static CallInst * Create (Value *F, const Twine &NameStr="", Instruction *InsertBefore=nullptr)
static CallInst * Create (Value *F, const Twine &NameStr, BasicBlock *InsertAtEnd)
static Instruction * CreateMalloc (Instruction *InsertBefore, Type *IntPtrTy, Type *AllocTy, Value *AllocSize, Value *ArraySize=nullptr, Function *MallocF=nullptr, const Twine &Name="")
CreateMalloc - Generate the IR for a call to malloc: 1.
static Instruction * CreateMalloc (BasicBlock *InsertAtEnd, Type *IntPtrTy, Type *AllocTy, Value *AllocSize, Value *ArraySize=nullptr, Function *MallocF=nullptr, const Twine &Name="")
CreateMalloc - Generate the IR for a call to malloc: 1.
static Instruction * CreateFree (Value *Source, Instruction *InsertBefore)
CreateFree - Generate the IR for a call to the builtin free function.
static Instruction * CreateFree (Value *Source, BasicBlock *InsertAtEnd)
CreateFree - Generate the IR for a call to the builtin free function.
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
CallInst * clone_impl () const override
Detailed Description
CallInst - This class represents a function call, abstracting a target machine's calling convention.
This class uses low bit of the SubClassData field to indicate whether or not this is a tail call. The rest of the bits hold the calling convention of the call.
Definition at line 1321 of file Instructions.h.
Member Enumeration Documentation
enum llvm::CallInst::TailCallKind
Enumerator:
TCK_None
TCK_Tail
TCK_MustTail
Definition at line 1413 of file Instructions.h.
Constructor & Destructor Documentation
CallInst::~CallInst () [override]
Definition at line 222 of file Instructions.cpp.
Member Function Documentation
void CallInst::addAttribute (unsigned i, Attribute::AttrKind attr)
addAttribute - adds the attribute to the list of attributes.
Definition at line 289 of file Instructions.cpp.
References llvm::AttributeSet::addAttribute(), getAttributes(), llvm::Value::getContext(), and setAttributes().
Referenced by setCannotDuplicate(), setCanReturnTwice(), setDoesNotAccessMemory(), setDoesNotReturn(), setDoesNotThrow(), setIsNoInline(), and setOnlyReadsMemory().
void CallInst::addDereferenceableAttr (unsigned i, uint64_t Bytes)
adds the dereferenceable attribute to the list of attributes.
Definition at line 304 of file Instructions.cpp.
References llvm::AttributeSet::addDereferenceableAttr(), getAttributes(), llvm::Value::getContext(), and setAttributes().
void CallInst::addDereferenceableOrNullAttr (unsigned i, uint64_t Bytes)
adds the dereferenceable_or_null attribute to the list of attributes.
Definition at line 310 of file Instructions.cpp.
References llvm::AttributeSet::addDereferenceableOrNullAttr(), getAttributes(), llvm::Value::getContext(), and setAttributes().
iterator_range<op_iterator> llvm::CallInst::arg_operands () [inline]
arg_operands - iteration adapter for range-for loops.
Definition at line 1445 of file Instructions.h.
References llvm::User::op_begin(), and llvm::User::op_end().
Referenced by getVectorCallCost(), and llvm::InstCombiner::visitCallInst().
iterator_range<const_op_iterator> llvm::CallInst::arg_operands () const [inline]
arg_operands - iteration adapter for range-for loops.
Definition at line 1452 of file Instructions.h.
References llvm::User::op_begin(), and llvm::User::op_end().
bool llvm::CallInst::cannotDuplicate () const [inline]
Determine if the call cannot be duplicated.
Definition at line 1568 of file Instructions.h.
References hasFnAttr(), and llvm::Attribute::NoDuplicate.
Referenced by HasNoDuplicateCall().
bool llvm::CallInst::canReturnTwice () const [inline]
Return true if the call can return twice.
Definition at line 1532 of file Instructions.h.
References hasFnAttr(), and llvm::Attribute::ReturnsTwice.
static bool llvm::CallInst::classof (const Instruction * I) [inline, static]
Definition at line 1616 of file Instructions.h.
References llvm::Call, and llvm::Instruction::getOpcode().
Referenced by classof().
static bool llvm::CallInst::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::Instruction.
Reimplemented in llvm::InstrProfIncrementInst, llvm::VACopyInst, llvm::VAEndInst, llvm::VAStartInst, llvm::MemMoveInst, llvm::MemCpyInst, llvm::MemTransferInst, llvm::MemSetInst, llvm::MemIntrinsic, llvm::DbgValueInst, llvm::DbgDeclareInst, llvm::DbgInfoIntrinsic, and llvm::IntrinsicInst.
Definition at line 1619 of file Instructions.h.
References classof().
CallInst * CallInst::clone_impl () const [override, protected, virtual]
Implements llvm::Instruction.
Definition at line 3573 of file Instructions.cpp.
References llvm::User::getNumOperands().
static CallInst* llvm::CallInst::Create (Value * Func, ArrayRef< Value * > Args, const Twine & NameStr = "", Instruction * InsertBefore = nullptr) [inline, static]
Definition at line 1355 of file Instructions.h.
References llvm::Value::getType().
Referenced by changeToCall(), changeToUnreachable(), CombineUAddWithOverflow(), llvm::IRBuilder< true, TargetFolder >::CreateCall(), createCallHelper(), createFree(), createMalloc(), fixupFPReturnAndCall(), llvm::DIBuilder::insertDbgValueIntrinsic(), llvm::DIBuilder::insertDeclare(), InsertSafepointPoll(), insertUseHolderAfter(), llvm::IntrinsicLowering::LowerToByteSwap(), and llvm::InstCombiner::visitFPTrunc().
static CallInst* llvm::CallInst::Create (FunctionType * Ty, Value * Func, ArrayRef< Value * > Args, const Twine & NameStr = "", Instruction * InsertBefore = nullptr) [inline, static]
Definition at line 1363 of file Instructions.h.
References llvm::ArrayRef< T >::size().
static CallInst* llvm::CallInst::Create (Value * Func, ArrayRef< Value * > Args, const Twine & NameStr, BasicBlock * InsertAtEnd) [inline, static]
Definition at line 1369 of file Instructions.h.
References llvm::ArrayRef< T >::size().
static CallInst* llvm::CallInst::Create (Value * F, const Twine & NameStr = "", Instruction * InsertBefore = nullptr) [inline, static]
Definition at line 1375 of file Instructions.h.
static CallInst* llvm::CallInst::Create (Value * F, const Twine & NameStr, BasicBlock * InsertAtEnd) [inline, static]
Definition at line 1379 of file Instructions.h.
Instruction * CallInst::CreateFree (Value * Source, Instruction * InsertBefore) [static]
CreateFree - Generate the IR for a call to the builtin free function.
Definition at line 482 of file Instructions.cpp.
References createFree().
Referenced by LLVMBuildFree(), and PerformHeapAllocSRoA().
Instruction * CallInst::CreateFree (Value * Source, BasicBlock * InsertAtEnd) [static]
CreateFree - Generate the IR for a call to the builtin free function.
Note: This function does not add the call to the basic block, that is the responsibility of the caller.
Definition at line 489 of file Instructions.cpp.
References createFree().
Instruction * CallInst::CreateMalloc (Instruction * InsertBefore, Type * IntPtrTy, Type * AllocTy, Value * AllocSize, Value * ArraySize = nullptr, Function * MallocF = nullptr, const Twine & Name = "") [static]
CreateMalloc - Generate the IR for a call to malloc: 1.
Compute the malloc call's argument as the specified type's size, possibly multiplied by the array size if the array size is not constant 1. 2. Call malloc with that argument. 3. Bitcast the result of the malloc call to the specified type.
Definition at line 424 of file Instructions.cpp.
References createMalloc().
Referenced by LLVMBuildArrayMalloc(), LLVMBuildMalloc(), PerformHeapAllocSRoA(), and TryToOptimizeStoreOfMallocToGlobal().
Instruction * CallInst::CreateMalloc (BasicBlock * InsertAtEnd, Type * IntPtrTy, Type * AllocTy, Value * AllocSize, Value * ArraySize = nullptr, Function * MallocF = nullptr, const Twine & Name = "") [static]
CreateMalloc - Generate the IR for a call to malloc: 1.
Compute the malloc call's argument as the specified type's size, possibly multiplied by the array size if the array size is not constant 1. 2. Call malloc with that argument. 3. Bitcast the result of the malloc call to the specified type. Note: This function does not add the bitcast to the basic block, that is the responsibility of the caller.
Definition at line 441 of file Instructions.cpp.
References createMalloc().
llvm::CallInst::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Provide fast operand accessors.
bool llvm::CallInst::doesNotAccessMemory () const [inline]
Determine if the call does not access memory.
Definition at line 1540 of file Instructions.h.
References hasFnAttr(), and llvm::Attribute::ReadNone.
Referenced by onlyReadsMemory().
bool llvm::CallInst::doesNotReturn () const [inline]
Determine if the call cannot return.
Definition at line 1556 of file Instructions.h.
References hasFnAttr(), and llvm::Attribute::NoReturn.
bool llvm::CallInst::doesNotThrow () const [inline]
Determine if the call cannot unwind.
Definition at line 1562 of file Instructions.h.
References hasFnAttr(), and llvm::Attribute::NoUnwind.
Referenced by HandleCallsInBlockInlinedThroughInvoke(), and llvm::InstCombiner::visitCallInst().
Value* llvm::CallInst::getArgOperand (unsigned i) const [inline]
getArgOperand/setArgOperand - Return/set the i-th call argument.
Definition at line 1441 of file Instructions.h.
References llvm::User::getOperand().
Referenced by llvm::checkBinaryFloatSignature(), llvm::checkUnaryFloatSignature(), computeArraySize(), computeKnownBitsFromAssume(), llvm::ComputeUsesVAFloatArgument(), detectLog2OfHalf(), llvm::DbgDeclareInst::getAddress(), llvm::MemIntrinsic::getAlignmentCst(), llvm::MemIntrinsic::getAlignmentType(), llvm::VAStartInst::getArgList(), llvm::VAEndInst::getArgList(), llvm::VACopyInst::getDest(), llvm::InstrProfIncrementInst::getHash(), llvm::InstrProfIncrementInst::getIndex(), llvm::MemIntrinsic::getLength(), getLocForWrite(), llvm::InstrProfIncrementInst::getName(), llvm::InstrProfIncrementInst::getNumCounters(), llvm::DbgValueInst::getOffset(), llvm::AArch64TTIImpl::getOrCreateResultFromMemIntrinsic(), llvm::MemIntrinsic::getRawDest(), llvm::DbgDeclareInst::getRawExpression(), llvm::DbgValueInst::getRawExpression(), llvm::MemTransferInst::getRawSource(), llvm::DbgDeclareInst::getRawVariable(), llvm::DbgValueInst::getRawVariable(), llvm::VACopyInst::getSrc(), llvm::AArch64TTIImpl::getTgtMemIntrinsic(), llvm::AArch64TargetLowering::getTgtMemIntrinsic(), llvm::ARMTargetLowering::getTgtMemIntrinsic(), llvm::NVPTXTargetLowering::getTgtMemIntrinsic(), llvm::PPCTargetLowering::getTgtMemIntrinsic(), llvm::DbgValueInst::getValue(), llvm::MemSetInst::getValue(), getVectorIntrinsicCost(), llvm::MemIntrinsic::getVolatileCst(), handleBranchExpect(), handleSwitchExpect(), isDynamicConstant(), isReportingError(), lowerExpectIntrinsic(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::IntrinsicLowering::LowerToByteSwap(), llvm::parseEHActions(), PerformHeapAllocSRoA(), ReplaceFPIntrinsicWithCall(), ScalarizeMaskedLoad(), ScalarizeMaskedStore(), llvm::FastISel::selectIntrinsicCall(), llvm::FastISel::selectPatchpoint(), SimplifyX86insertps(), SimplifyX86vperm2(), tryToMoveFreeBeforeNullTest(), TryToOptimizeStoreOfMallocToGlobal(), llvm::UpgradeIntrinsicCall(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitFPTrunc(), llvm::InstCombiner::visitFree(), and WriteInstruction().
const Use& llvm::CallInst::getArgOperandUse (unsigned i) const [inline]
Wrappers for getting the Use of a call argument.
Definition at line 1457 of file Instructions.h.
References llvm::User::getOperandUse().
Referenced by llvm::MemIntrinsic::getLengthUse(), llvm::MemIntrinsic::getRawDestUse(), llvm::MemTransferInst::getRawSourceUse(), and llvm::MemSetInst::getValueUse().
Use& llvm::CallInst::getArgOperandUse (unsigned i) [inline]
Definition at line 1458 of file Instructions.h.
References llvm::User::getOperandUse().
const AttributeSet& llvm::CallInst::getAttributes () const [inline]
getAttributes - Return the parameter attributes for this call.
Definition at line 1472 of file Instructions.h.
Referenced by addAttribute(), addDereferenceableAttr(), addDereferenceableOrNullAttr(), HandleCallsInBlockInlinedThroughInvoke(), makeStatepointExplicitImpl(), removeAttribute(), and WriteInstruction().
Function* llvm::CallInst::getCalledFunction () const [inline]
getCalledFunction - Return the function called, or null if this is an indirect function invocation.
Definition at line 1588 of file Instructions.h.
References llvm::dyn_cast(), and llvm::User::Op().
Referenced by llvm::IntrinsicInst::classof(), computeKnownBitsFromAssume(), llvm::objcarc::GetARCInstKind(), llvm::IntrinsicInst::getIntrinsicID(), llvm::getIntrinsicIDForCall(), getVectorCallCost(), handleBranchExpect(), handleSwitchExpect(), llvm::isFreeCall(), isTrigLibCall(), lowerExpectIntrinsic(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::FortifiedLibCallSimplifier::optimizeCall(), llvm::LibCallSimplifier::optimizeCall(), paramHasAttr(), llvm::FastISel::selectStackmap(), llvm::UpgradeIntrinsicCall(), and llvm::InstCombiner::visitFCmpInst().
const Value* llvm::CallInst::getCalledValue () const [inline]
getCalledValue - Get a pointer to the function that is invoked by this instruction.
Definition at line 1594 of file Instructions.h.
References llvm::User::Op().
Referenced by llvm::ComputeUsesVAFloatArgument(), llvm::ARMTargetLowering::ExpandInlineAsm(), HandleCallsInBlockInlinedThroughInvoke(), llvm::FastISel::lowerCall(), llvm::FastISel::selectCall(), shouldConvertUse(), llvm::InstCombiner::visitCallInst(), and WriteInstruction().
Value* llvm::CallInst::getCalledValue () [inline]
Definition at line 1595 of file Instructions.h.
References llvm::User::Op().
CallingConv::ID llvm::CallInst::getCallingConv () const [inline]
getCallingConv/setCallingConv - Get or set the calling convention of this function call.
Definition at line 1462 of file Instructions.h.
References llvm::Instruction::getSubclassDataFromInstruction().
Referenced by HandleCallsInBlockInlinedThroughInvoke(), makeStatepointExplicitImpl(), llvm::FortifiedLibCallSimplifier::optimizeCall(), llvm::LibCallSimplifier::optimizeCall(), ReplaceWithStatepoint(), llvm::FastISel::selectPatchpoint(), llvm::FastISel::selectStackmap(), and WriteInstruction().
uint64_t llvm::CallInst::getDereferenceableBytes (unsigned i) const [inline]
Extract the number of dereferenceable bytes for a call or parameter (0=unknown).
Definition at line 1508 of file Instructions.h.
References llvm::AttributeSet::getDereferenceableBytes().
uint64_t llvm::CallInst::getDereferenceableOrNullBytes (unsigned i) const [inline]
Extract the number of dereferenceable_or_null bytes for a call or parameter (0=unknown).
Definition at line 1514 of file Instructions.h.
References llvm::AttributeSet::getDereferenceableOrNullBytes().
FunctionType* llvm::CallInst::getFunctionType () const [inline]
Definition at line 1405 of file Instructions.h.
Referenced by WriteInstruction().
unsigned llvm::CallInst::getNumArgOperands () const [inline]
getNumArgOperands - Return the number of call arguments.
Definition at line 1437 of file Instructions.h.
References llvm::User::getNumOperands().
Referenced by llvm::checkBinaryFloatSignature(), llvm::checkUnaryFloatSignature(), llvm::ComputeUsesVAFloatArgument(), llvm::AArch64TTIImpl::getOrCreateResultFromMemIntrinsic(), llvm::AArch64TTIImpl::getTgtMemIntrinsic(), llvm::AArch64TargetLowering::getTgtMemIntrinsic(), llvm::ARMTargetLowering::getTgtMemIntrinsic(), getVectorIntrinsicCost(), isReportingError(), llvm::IntrinsicLowering::LowerToByteSwap(), llvm::parseEHActions(), llvm::FastISel::selectPatchpoint(), llvm::UpgradeIntrinsicCall(), and WriteInstruction().
unsigned llvm::CallInst::getParamAlignment (unsigned i) const [inline]
Extract the alignment for a call or parameter (0=unknown).
Definition at line 1502 of file Instructions.h.
References llvm::AttributeSet::getParamAlignment().
TailCallKind llvm::CallInst::getTailCallKind () const [inline]
Definition at line 1414 of file Instructions.h.
References llvm::Instruction::getSubclassDataFromInstruction().
Referenced by llvm::InlineFunction().
bool llvm::CallInst::hasByValArgument () const [inline]
Determine if any call argument is an aggregate passed by value.
Definition at line 1581 of file Instructions.h.
References llvm::Attribute::ByVal, and llvm::AttributeSet::hasAttrSomewhere().
bool llvm::CallInst::hasFnAttr (Attribute::AttrKind A) const [inline]
Determine whether this call has the given attribute.
Definition at line 1492 of file Instructions.h.
References llvm::Attribute::NoBuiltin.
Referenced by cannotDuplicate(), canReturnTwice(), doesNotAccessMemory(), doesNotReturn(), doesNotThrow(), isNoInline(), isTrigLibCall(), and onlyReadsMemory().
bool llvm::CallInst::hasStructRetAttr () const [inline]
Determine if the call returns a structure through first pointer argument.
Definition at line 1575 of file Instructions.h.
References paramHasAttr(), and llvm::Attribute::StructRet.
bool llvm::CallInst::isInlineAsm () const [inline]
isInlineAsm - Check if this call is an inline asm statement.
Definition at line 1611 of file Instructions.h.
References llvm::User::Op().
Referenced by needsStatepoint().
bool llvm::CallInst::isMustTailCall () const [inline]
Definition at line 1420 of file Instructions.h.
References llvm::Instruction::getSubclassDataFromInstruction(), and TCK_MustTail.
Referenced by llvm::InlineFunction(), and WriteInstruction().
bool llvm::CallInst::isNoBuiltin () const [inline]
Return true if the call should not be treated as a call to a builtin.
Definition at line 1520 of file Instructions.h.
References llvm::Attribute::Builtin, and llvm::Attribute::NoBuiltin.
Referenced by getVectorCallCost(), and llvm::LibCallSimplifier::optimizeCall().
bool llvm::CallInst::isNoInline () const [inline]
Return true if the call should not be inlined.
Definition at line 1526 of file Instructions.h.
References hasFnAttr(), and llvm::Attribute::NoInline.
bool llvm::CallInst::isTailCall () const [inline]
Definition at line 1417 of file Instructions.h.
References llvm::Instruction::getSubclassDataFromInstruction(), and TCK_None.
Referenced by llvm::FastISel::lowerCall(), makeStatepointExplicitImpl(), llvm::HexagonTargetLowering::mayBeEmittedAsTailCall(), llvm::SystemZTargetLowering::mayBeEmittedAsTailCall(), ReplaceWithStatepoint(), and WriteInstruction().
void llvm::CallInst::mutateFunctionType (FunctionType * FTy) [inline]
Definition at line 1407 of file Instructions.h.
References llvm::FunctionType::getReturnType(), and llvm::Value::mutateType().
bool llvm::CallInst::onlyReadsMemory () const [inline]
Determine if the call does not access or only reads memory.
Definition at line 1548 of file Instructions.h.
References doesNotAccessMemory(), hasFnAttr(), and llvm::Attribute::ReadOnly.
Referenced by llvm::checkBinaryFloatSignature(), and llvm::checkUnaryFloatSignature().
bool CallInst::paramHasAttr (unsigned i, Attribute::AttrKind A) const
Determine whether the call or the callee has the given attributes.
Definition at line 324 of file Instructions.cpp.
References F(), getCalledFunction(), and llvm::AttributeSet::hasAttribute().
Referenced by hasStructRetAttr().
void CallInst::removeAttribute (unsigned i, Attribute attr)
removeAttribute - removes the attribute from the list of attributes.
Definition at line 295 of file Instructions.cpp.
References getAttributes(), llvm::Value::getContext(), llvm::AttributeSet::removeAttributes(), and setAttributes().
void llvm::CallInst::setArgOperand (unsigned i, Value * v) [inline]
Definition at line 1442 of file Instructions.h.
References llvm::User::setOperand().
Referenced by llvm::MemIntrinsic::setAlignment(), llvm::MemIntrinsic::setDest(), llvm::MemIntrinsic::setLength(), llvm::MemTransferInst::setSource(), llvm::MemSetInst::setValue(), llvm::MemIntrinsic::setVolatile(), llvm::InstCombiner::visitCallInst(), and llvm::InstCombiner::visitFMul().
void llvm::CallInst::setAttributes (const AttributeSet & Attrs) [inline]
setAttributes - Set the parameter attributes for this call.
Definition at line 1476 of file Instructions.h.
Referenced by addAttribute(), addDereferenceableAttr(), addDereferenceableOrNullAttr(), llvm::EmitBinaryFloatFnCall(), llvm::EmitUnaryFloatFnCall(), llvm::orc::makeStub(), removeAttribute(), and ReplaceWithStatepoint().
void llvm::CallInst::setCalledFunction (Value * Fn) [inline]
setCalledFunction - Set the function called.
Definition at line 1598 of file Instructions.h.
References llvm::Value::getType().
Referenced by llvm::InstCombiner::visitCallInst().
void llvm::CallInst::setCalledFunction (FunctionType * FTy, Value * Fn) [inline]
Definition at line 1603 of file Instructions.h.
References llvm::Value::getType(), and llvm::User::Op().
void llvm::CallInst::setCallingConv (CallingConv::ID CC) [inline]
Definition at line 1465 of file Instructions.h.
References llvm::Instruction::getSubclassDataFromInstruction().
Referenced by createFree(), createMalloc(), llvm::EmitBinaryFloatFnCall(), llvm::EmitFPutC(), llvm::EmitFPutS(), llvm::EmitFWrite(), llvm::EmitMemChr(), llvm::EmitMemCmp(), llvm::EmitMemCpyChk(), llvm::EmitPutChar(), llvm::EmitPutS(), llvm::EmitStrChr(), llvm::EmitStrCpy(), llvm::EmitStrLen(), llvm::EmitStrNCmp(), llvm::EmitStrNCpy(), llvm::EmitStrNLen(), and llvm::EmitUnaryFloatFnCall().
void llvm::CallInst::setCannotDuplicate () [inline]
Definition at line 1569 of file Instructions.h.
References addAttribute(), llvm::AttributeSet::FunctionIndex, and llvm::Attribute::NoDuplicate.
void llvm::CallInst::setCanReturnTwice () [inline]
Definition at line 1535 of file Instructions.h.
References addAttribute(), llvm::AttributeSet::FunctionIndex, and llvm::Attribute::ReturnsTwice.
void llvm::CallInst::setDoesNotAccessMemory () [inline]
Definition at line 1543 of file Instructions.h.
References addAttribute(), llvm::AttributeSet::FunctionIndex, and llvm::Attribute::ReadNone.
void llvm::CallInst::setDoesNotReturn () [inline]
Definition at line 1557 of file Instructions.h.
References addAttribute(), llvm::AttributeSet::FunctionIndex, and llvm::Attribute::NoReturn.
Referenced by INITIALIZE_PASS().
void llvm::CallInst::setDoesNotThrow () [inline]
Definition at line 1563 of file Instructions.h.
References addAttribute(), llvm::AttributeSet::FunctionIndex, and llvm::Attribute::NoUnwind.
Referenced by llvm::InlineFunction(), and llvm::InstCombiner::visitCallInst().
void llvm::CallInst::setIsNoInline () [inline]
Definition at line 1527 of file Instructions.h.
References addAttribute(), llvm::AttributeSet::FunctionIndex, and llvm::Attribute::NoInline.
void llvm::CallInst::setOnlyReadsMemory () [inline]
Definition at line 1551 of file Instructions.h.
References addAttribute(), llvm::AttributeSet::FunctionIndex, and llvm::Attribute::ReadOnly.
void llvm::CallInst::setTailCall (bool isTC = true) [inline]
Definition at line 1423 of file Instructions.h.
References llvm::Instruction::getSubclassDataFromInstruction(), TCK_None, and TCK_Tail.
Referenced by createFree(), createMalloc(), makeStatepointExplicitImpl(), and llvm::orc::makeStub().
void llvm::CallInst::setTailCallKind (TailCallKind TCK) [inline]
Definition at line 1427 of file Instructions.h.
References llvm::Instruction::getSubclassDataFromInstruction().
Referenced by llvm::InlineFunction().
The documentation for this class was generated from the following files:
Instructions.h
Instructions.cpp