LLVM: llvm::Comdat Class Reference
llvm::Comdat Class Reference
#include <Comdat.h>
Public Types
enum SelectionKind {
Any, ExactMatch, Largest, NoDuplicates,
SameSize
}
Public Member Functions
Comdat (Comdat &&C)
SelectionKind getSelectionKind () const
void setSelectionKind (SelectionKind Val)
StringRef getName () const
void print (raw_ostream &OS) const
void dump () const
Friends
class Module
Detailed Description
Definition at line 31 of file Comdat.h.
Member Enumeration Documentation
enum llvm::Comdat::SelectionKind
Enumerator:
Any
The linker may choose any COMDAT.
ExactMatch
The data referenced by the COMDAT must be the same.
Largest
The linker will choose the largest COMDAT.
NoDuplicates
No other Module may specify this COMDAT.
SameSize
The data referenced by the COMDAT must be the same size.
Definition at line 33 of file Comdat.h.
Constructor & Destructor Documentation
Comdat::Comdat (Comdat && C)
Definition at line 21 of file Comdat.cpp.
Member Function Documentation
LLVM_DUMP_METHOD void Comdat::dump () const
Definition at line 3269 of file AsmWriter.cpp.
References llvm::dbgs(), and print().
StringRef Comdat::getName () const
Definition at line 25 of file Comdat.cpp.
References llvm::StringMapEntry< ValueTy >::first().
Referenced by checkMachOComdat(), getComdatGVForCOFF(), getELFComdat(), maybePrintComdat(), and print().
SelectionKind llvm::Comdat::getSelectionKind () const [inline]
Definition at line 42 of file Comdat.h.
Referenced by getELFComdat(), getEncodedComdatSelectionKind(), and print().
void Comdat::print (raw_ostream & OS) const
Definition at line 3118 of file AsmWriter.cpp.
References Any, ComdatPrefix, ExactMatch, getName(), getSelectionKind(), Largest, NoDuplicates, PrintLLVMName(), and SameSize.
Referenced by dump(), and llvm::operator<<().
void llvm::Comdat::setSelectionKind (SelectionKind Val) [inline]
Definition at line 43 of file Comdat.h.
Referenced by rewriteComdat().
Friends And Related Function Documentation
friend class Module [friend]
Definition at line 49 of file Comdat.h.
The documentation for this class was generated from the following files:
Comdat.h
AsmWriter.cpp
Comdat.cpp