LLVM: llvm::SmallVectorTemplateBase< T, isPodLike > Class Template Reference
llvm::SmallVectorTemplateBase< T, isPodLike > Class Template Reference
SmallVectorTemplateBase<isPodLike = false> - This is where we put method implementations that are designed to work with non-POD-like T's.
#include <SmallVector.h>
Inherits llvm::SmallVectorTemplateCommon< T >.
Public Member Functions
void push_back (const T &Elt)
void push_back (T &&Elt)
void pop_back ()
Protected Member Functions
SmallVectorTemplateBase (size_t Size)
void grow (size_t MinSize=0)
Grow the allocated memory (without initializing new elements), doubling the size of the allocated memory.
Static Protected Member Functions
static void destroy_range (T *S, T *E)
template<typename It1 , typename It2 >
static It2 move (It1 I, It1 E, It2 Dest)
Use move-assignment to move the range [I, E) onto the objects starting with "Dest".
template<typename It1 , typename It2 >
static It2 move_backward (It1 I, It1 E, It2 Dest)
Use move-assignment to move the range [I, E) onto the objects ending at "Dest", moving objects in reverse order.
template<typename It1 , typename It2 >
static void uninitialized_move (It1 I, It1 E, It2 Dest)
Move the range [I, E) into the uninitialized memory starting with "Dest", constructing elements as needed.
template<typename It1 , typename It2 >
static void uninitialized_copy (It1 I, It1 E, It2 Dest)
Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements as needed.
Detailed Description
template<typename T, bool isPodLike>
class llvm::SmallVectorTemplateBase< T, isPodLike >
SmallVectorTemplateBase<isPodLike = false> - This is where we put method implementations that are designed to work with non-POD-like T's.
Definition at line 169 of file SmallVector.h.
Constructor & Destructor Documentation
template<typename T, bool isPodLike> llvm::SmallVectorTemplateBase< T, isPodLike >::SmallVectorTemplateBase (size_t Size) [inline, protected]
Definition at line 171 of file SmallVector.h.
Member Function Documentation
template<typename T, bool isPodLike> static void llvm::SmallVectorTemplateBase< T, isPodLike >::destroy_range (T * S, T * E) [inline, static, protected]
Definition at line 173 of file SmallVector.h.
template<typename T , bool isPodLike> void llvm::SmallVectorTemplateBase< T, isPodLike >::grow (size_t MinSize = 0) [protected]
Grow the allocated memory (without initializing new elements), doubling the size of the allocated memory.
Guarantees space for at least one more element, or MinSize more elements if specified.
Definition at line 244 of file SmallVector.h.
References llvm::sys::path::begin(), llvm::sys::path::end(), llvm::NextPowerOf2(), and size.
Referenced by llvm::SmallVectorTemplateBase< LiveOutInfo, isPodLike< LiveOutInfo >::value >::push_back(), and llvm::SmallVectorTemplateBase< T, true >::push_back().
template<typename T, bool isPodLike> template<typename It1 , typename It2 > static It2 llvm::SmallVectorTemplateBase< T, isPodLike >::move (It1 I, It1 E, It2 Dest) [inline, static, protected]
Use move-assignment to move the range [I, E) onto the objects starting with "Dest".
This is just <memory>'s std::move, but not all stdlibs actually provide that.
Definition at line 184 of file SmallVector.h.
Referenced by llvm::SmallVectorTemplateBase< LiveOutInfo, isPodLike< LiveOutInfo >::value >::move_backward().
template<typename T, bool isPodLike> template<typename It1 , typename It2 > static It2 llvm::SmallVectorTemplateBase< T, isPodLike >::move_backward (It1 I, It1 E, It2 Dest) [inline, static, protected]
Use move-assignment to move the range [I, E) onto the objects ending at "Dest", moving objects in reverse order.
This is just <algorithm>'s std::move_backward, but not all stdlibs actually provide that.
Definition at line 195 of file SmallVector.h.
template<typename T, bool isPodLike> void llvm::SmallVectorTemplateBase< T, isPodLike >::pop_back () [inline]
Definition at line 236 of file SmallVector.h.
Referenced by llvm::MachineInstr::addRegisterDead(), llvm::MachineInstr::addRegisterKilled(), advanceToNextLeafType(), llvm::MipsInstrInfo::AnalyzeBranch(), llvm::A57ChainingConstraint::apply(), BuildSubAggregate(), llvm::ArrayRecycler< MachineOperand >::clear(), createUniqueEntity(), llvm::DWARFContextInMemory::DWARFContextInMemory(), EmitAddTreeOfValues(), llvm::MCELFStreamer::EmitBundleUnlock(), llvm::yaml::Output::endFlowMapping(), llvm::yaml::Output::endFlowSequence(), llvm::WinCodeViewLineTables::endFunction(), llvm::yaml::Output::endMapping(), llvm::yaml::Output::endSequence(), llvm::SparseSet< RootData >::erase(), llvm::MDAttachmentMap::erase(), extendSegmentsToUses(), llvm::ScalarEvolution::getAddRecExpr(), llvm::MemoryDependenceAnalysis::getNonLocalCallDependency(), llvm::object::ExportEntry::moveNext(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator--(), llvm::MCStreamer::PopSection(), llvm::yaml::Output::postflightKey(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::DAGTypeLegalizer::run(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::skipToParent(), and llvm::Twine::toNullTerminatedStringRef().
template<typename T, bool isPodLike> void llvm::SmallVectorTemplateBase< T, isPodLike >::push_back (const T & Elt) [inline]
Definition at line 222 of file SmallVector.h.
Referenced by llvm::opt::Option::accept(), llvm::InstCombineWorklist::Add(), llvm::SDDbgInfo::add(), llvm::BitCodeAbbrev::Add(), llvm::PMDataManager::add(), llvm::MemoryDepChecker::addAccess(), AddAliasScopeMetadata(), llvm::opt::ArgList::AddAllArgsTranslated(), llvm::MCJIT::addArchive(), llvm::DIEAbbrev::AddAttribute(), llvm::LexicalScope::addChild(), AddCombineTo64bitMLAL(), AddCombineToVPADDL(), llvm::MCLOHContainer::addDirective(), llvm::GCOVBlock::addDstEdge(), llvm::DwarfDebug::addDwarfTypeUnitType(), llvm::ConstantPool::addEntry(), llvm::SMDiagnostic::addFixIt(), llvm::DIInliningInfo::addFrame(), llvm::PMTopLevelManager::addImmutablePass(), llvm::PMTopLevelManager::addIndirectPassManager(), llvm::InstCombineWorklist::AddInitialGroup(), llvm::RegsForValue::AddInlineAsmOperands(), llvm::CCState::addInRegsParamInfo(), addInstructionToGraph(), llvm::FoldingSetNodeID::AddInteger(), llvm::MachineModuleInfo::addInvoke(), llvm::AddLandingPadInfo(), llvm::GCOVBlock::addLine(), llvm::SpillPlacement::Node::addLink(), llvm::SpillPlacement::addLinks(), llvm::cl::parser< const PassInfo * >::addLiteralOption(), llvm::LiveRangeCalc::addLiveInBlock(), llvm::CCState::addLoc(), llvm::AArch64FunctionInfo::addLOHDirective(), llvm::orc::OrcMCJITReplacement::addModule(), llvm::ExecutionEngine::addModule(), llvm::PPCFunctionInfo::addMustSaveCR(), llvm::MCJIT::addObjectFile(), llvm::BitSetBuilder::addOffset(), llvm::MCInst::addOperand(), llvm::PMTopLevelManager::addPassManager(), llvm::SUnit::addPred(), llvm::AnalysisUsage::addPreserved(), llvm::AnalysisUsage::addPreservedID(), llvm::RangeSpanList::addRange(), llvm::DwarfCompileUnit::addRange(), llvm::MachineInstr::addRegisterDead(), llvm::MachineInstr::addRegisterKilled(), llvm::AnalysisUsage::addRequiredID(), llvm::AnalysisUsage::addRequiredTransitiveID(), llvm::RegScavenger::addScavengingFrameIndex(), llvm::DwarfCompileUnit::addScopeRangeList(), llvm::MachineModuleInfo::addSEHCatchHandler(), llvm::MachineModuleInfo::addSEHCleanupHandler(), llvm::GCOVBlock::addSrcEdge(), addStackMapLiveVars(), llvm::FoldingSetNodeID::AddString(), llvm::DwarfFile::addUnit(), advanceToNextLeafType(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate(), llvm::StatepointLoweringState::allocateStackSlot(), llvm::MipsInstrInfo::AnalyzeBranch(), llvm::SystemZCCState::AnalyzeCallOperands(), llvm::SystemZCCState::AnalyzeFormalArguments(), llvm::CCState::analyzeMustTailForwardedRegisters(), llvm::HexagonShuffler::append(), llvm::sys::path::append(), llvm::LiveRange::append(), llvm::A57ChainingConstraint::apply(), AreAnyUnderlyingObjectsAnAlloca(), llvm::opt::Arg::Arg(), llvm::DwarfCompileUnit::attachRangesOrLowHighPC(), llvm::yaml::Output::beginFlowMapping(), llvm::yaml::Output::beginFlowSequence(), llvm::WinCodeViewLineTables::beginFunction(), llvm::yaml::Output::beginMapping(), llvm::DwarfDebug::beginModule(), llvm::yaml::Output::beginSequence(), llvm::CriticalAntiDepBreaker::BreakAntiDependencies(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), buildFromShuffleMostly(), BuildSubAggregate(), canWidenShuffleElements(), llvm::CC_ARM_AAPCS_Custom_Aggregate(), ChangeVSETULTtoVSETULE(), CheckForLiveRegDef(), CheckForLiveRegDefMasked(), CloneAliasScopeMetadata(), CloneLoopBlocks(), cloneLoopWithPreheader(), CloneNodeWithValues(), llvm::RegPressureTracker::closeBottom(), llvm::LexicalScope::closeInsnRange(), llvm::RegPressureTracker::closeTop(), CollectAddOperandsWithScales(), collectDebugValues(), llvm::PMTopLevelManager::collectLastUses(), llvm::PMDataManager::collectRequiredAnalysis(), CollectSubexprs(), CombineBaseUpdate(), combineConcatVectorOfScalars(), combineRedundantDWordShuffle(), llvm::SCEVAddRecExpr::computeAccessFunctions(), llvm::EHStreamer::computeActionsTable(), computeOthers(), ComputePTXValueVTs(), llvm::ComputeValueVTs(), ConstantFoldGetElementPtrImpl(), llvm::SelectionDAGBuilder::CopyValueToVirtualRegister(), llvm::MDBuilder::createAnonymousAARoot(), llvm::DIBuilder::createEnumerationType(), llvm::DIBuilder::createFunction(), CreateGCRelocates(), llvm::DIBuilder::createGlobalVariable(), llvm::DIBuilder::createMethod(), createUniqueEntity(), llvm::LiveRange::createValueCopy(), llvm::DebugLocEntry::DebugLocEntry(), llvm::DecodeBLENDMask(), llvm::DecodeINSERTPSMask(), llvm::DecodeMOVDDUPMask(), llvm::DecodeMOVHLPSMask(), llvm::DecodeMOVLHPSMask(), llvm::DecodeMOVSHDUPMask(), llvm::DecodeMOVSLDUPMask(), llvm::DecodePALIGNRMask(), llvm::DecodePSHUFBMask(), llvm::DecodePSHUFHWMask(), llvm::DecodePSHUFLWMask(), llvm::DecodePSHUFMask(), llvm::DecodePSLLDQMask(), llvm::DecodePSRLDQMask(), llvm::DecodeScalarMoveMask(), llvm::DecodeSHUFPMask(), llvm::DecodeUNPCKHMask(), llvm::DecodeUNPCKLMask(), llvm::DecodeVPERM2X128Mask(), llvm::DecodeVPERMILPMask(), llvm::DecodeVPERMMask(), llvm::DecodeZeroExtendMask(), llvm::DecodeZeroMoveLowMask(), llvm::DeleteDeadPHIs(), llvm::RegPressureTracker::discoverLiveIn(), llvm::RegPressureTracker::discoverLiveOut(), llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::BlockFrequencyInfoImplBase::distributeMass(), llvm::AsmPrinter::doInitialization(), DoInitialMatch(), llvm::MCELFStreamer::EmitBundleLock(), llvm::MCWinCOFFStreamer::EmitCOFFSecRel32(), llvm::MCWinCOFFStreamer::EmitCOFFSectionIndex(), EmitDarwinBCHeaderAndTrailer(), llvm::ExecutionEngine::emitGlobals(), llvm::MCObjectStreamer::EmitGPRel32Value(), llvm::MCObjectStreamer::EmitGPRel64Value(), llvm::PPCDispatchGroupSBHazardRecognizer::EmitInstruction(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::MCWinCOFFStreamer::EmitInstToData(), llvm::BufferByteStreamer::EmitInt8(), llvm::MipsELFStreamer::EmitLabel(), llvm::MCObjectStreamer::EmitLabel(), llvm::PPCDispatchGroupSBHazardRecognizer::EmitNoop(), llvm::SystemZFrameLowering::emitPrologue(), llvm::UnwindOpcodeAssembler::EmitRaw(), llvm::ScheduleDAGSDNodes::EmitSchedule(), emitSignedInt64(), llvm::BufferByteStreamer::EmitSLEB128(), llvm::BufferByteStreamer::EmitULEB128(), llvm::MCObjectStreamer::EmitValueImpl(), encodeUTF8(), llvm::detail::PtrUseVisitorBase::enqueueUsers(), enqueueUsersInWorklist(), llvm::BitstreamCursor::EnterSubBlock(), llvm::ExecutionEngine::ExecutionEngine(), ExpandREAD_REGISTER(), ExpandUnalignedLoad(), ExpandUnalignedStore(), extendSegmentsToUses(), ExtendUsesToFormExtLoad(), llvm::SelectionDAG::ExtractVectorElements(), llvm::finalizeBundle(), llvm::RuntimeDyldELF::finalizeLoad(), llvm::RuntimeDyldCOFFX86_64::finalizeLoad(), llvm::ScalarEvolution::findArrayDimensions(), findArrayDimensionsRec(), llvm::SSAUpdaterImpl< UpdaterT >::FindAvailableVals(), findBasePointer(), llvm::SlotIndexes::findLiveInMBBs(), llvm::SSAUpdaterTraits< SSAUpdater >::FindPredecessorBlocks(), llvm::SSAUpdaterTraits< MachineSSAUpdater >::FindPredecessorBlocks(), findRematerializableChainToBasePointer(), llvm::ScheduleDAGMI::findRootsAndBiasEdges(), FindSingleUseMultiplyFactors(), llvm::MachineInstr::findTiedOperandIdx(), FindUnconditionalPreds(), llvm::SplitEditor::finish(), firstRealType(), fixPhis(), llvm::InstCombiner::FoldCmpLoadFromIndexedGlobal(), llvm::ScalarEvolution::forgetValue(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), llvm::MCJIT::generateCodeForModule(), GenerateTBL(), genMadd(), genMaddR(), llvm::ScalarEvolution::getAddExpr(), getBranchTargetOpValue(), GetBranchWeights(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAGBuilder::getControlRoot(), getExactSDiv(), llvm::cl::generic_parser_base::getExtraOptionNames(), llvm::MCDwarfLineTableHeader::getFile(), llvm::GCModuleInfo::getGCStrategy(), getGEPSmallConstantIntOffsetV(), llvm::NVPTXMachineFunctionInfo::getImageHandleSymbolIndex(), getIncomingStatepointGCValues(), llvm::DWARFDebugInfoEntryMinimal::getInlinedChainForAddress(), llvm::Intrinsic::getIntrinsicInfoTableEntries(), llvm::object::MachOObjectFile::getLibraryShortNameByIndex(), llvm::PDBContext::getLineInfoForAddressRange(), llvm::DWARFContext::getLineInfoForAddressRange(), llvm::MCContext::getMachOSection(), llvm::ManagedStringPool::getManagedString(), getMemCmpLoad(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), llvm::SelectionDAG::getMergeValues(), llvm::MDNode::getMostGenericRange(), llvm::ScalarEvolution::getMulExpr(), getNaturalGEPRecursively(), getNaturalGEPWithOffset(), getNaturalGEPWithType(), llvm::LiveRange::getNextValue(), llvm::SelectionDAG::getNode(), llvm::MemoryDependenceAnalysis::getNonLocalCallDependency(), llvm::MipsTargetLowering::getOpndList(), llvm::LexicalScopes::getOrCreateAbstractScope(), llvm::AMDGPUTargetLowering::getOriginalFunctionArgs(), getPossibleTargets(), getReadPerformanceCounter(), getReadTimeStampCounter(), llvm::ARMBaseRegisterInfo::getRegAllocationHints(), llvm::TargetRegisterInfo::getRegAllocationHints(), GetRegistersForValue(), llvm::CCState::getRemainingRegParmsForType(), llvm::GetReturnInfo(), llvm::RegScavenger::getScavengingFrameIndices(), llvm::ShuffleVectorInst::getShuffleMask(), llvm::ScalarEvolution::getSMaxExpr(), llvm::SelectionDAG::getStackArgumentTokenFactor(), llvm::ConstantDataArray::getString(), getTargetVShiftByConstNode(), llvm::ScalarEvolution::getUDivExactExpr(), llvm::ScalarEvolution::getUMaxExpr(), getUnderlyingObjects(), llvm::GetUnderlyingObjects(), getUnderlyingObjectsForInstr(), llvm::Loop::getUniqueExitBlocks(), llvm::MachineSSAUpdater::GetValueInMiddleOfBlock(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), getVectorIntrinsicCost(), llvm::IntEqClasses::grow(), HandleByValArgument(), llvm::SCEVExpander::hoistIVInc(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::ImutAVLTreeGenericIterator(), llvm::DbgVariable::initializeDbgValue(), llvm::DbgVariable::initializeMMI(), InlineCallIfPossible(), llvm::InlineFunction(), llvm::SparseSet< RootData >::insert(), llvm::LoopAccessInfo::RuntimePointerCheck::insert(), llvm::LiveIntervals::insertMBBInMaps(), llvm::SlotIndexes::insertMBBInMaps(), llvm::TargetPassConfig::insertPass(), llvm::MDNode::intersect(), isAllocSiteRemovable(), isOnlyCopiedFromConstantGlobal(), llvm::isPotentiallyReachable(), isProfitableToFoldUnconditional(), IsValueFullyAvailableInBlock(), llvm::SpillPlacement::iterate(), llvm::LiveRange::join(), llvm::LazyCallGraph::LazyCallGraph(), llvm::SITargetLowering::legalizeTargetIndependentNode(), LinearizeExprTree(), llvm::LiveRange::LiveRange(), LookupNearestOption(), llvm::HexagonTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallFromStatepoint(), llvm::HexagonTargetLowering::LowerCallResult(), LowerCallResult(), llvm::FastISel::lowerCallTo(), llvm::TargetLowering::LowerCallTo(), LowerCONCAT_VECTORSvXi1(), llvm::LowerDbgDeclare(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), lowerIncomingStatepointValue(), LowerMemOpCallTo(), llvm::R600TargetLowering::LowerOperation(), llvm::MipsTargetLowering::LowerOperationWrapper(), llvm::TargetLowering::LowerOperationWrapper(), llvm::NVPTXTargetLowering::LowerReturn(), LowerShift(), llvm::SelectionDAGBuilder::LowerStatepoint(), lowerStatepointMetaArgs(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLEv8i8(), LowerVectorAllZeroTest(), lowerVectorShuffleAsBlend(), llvm::object::MachOObjectFile::MachOObjectFile(), mangleCoveragePath(), llvm::MachineFrameInfo::mapLocalFrameObject(), llvm::Regex::match(), llvm::MCAsmLayout::MCAsmLayout(), llvm::MCDwarfCallFrameFragment::MCDwarfCallFrameFragment(), llvm::MCDwarfLineAddrFragment::MCDwarfLineAddrFragment(), llvm::MCLEBFragment::MCLEBFragment(), llvm::MCStreamer::MCStreamer(), llvm::MipsELFStreamer::MipsELFStreamer(), MoveBelowOrigChain(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator++(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator--(), OptimizeVectorResize(), parseBackslash(), ParseFunctionArgs(), parseSegmentLoadCommand(), PerformBUILD_VECTORCombine(), performNEONPostLDSTCombine(), performPostLD1Combine(), PerformShuffleCombine(), PerformSTORECombine(), llvm::PHITransAddr::PHITransAddr(), llvm::yaml::Output::postflightKey(), PrepareCall(), llvm::FileInfo::print(), llvm::MachineInstr::print(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::promoteLoopAccessesToScalars(), promoteSingleBlockAlloca(), llvm::LiveIntervals::pruneValue(), PushDefUseChildren(), PushLoopPHIs(), llvm::MCStreamer::PushSection(), pushStackMapConstant(), pushValue(), PushValueAndType(), llvm::coverage::RawCoverageMappingReader::read(), llvm::GCOVFile::readGCNO(), llvm::GCOVFunction::readGCNO(), llvm::BitstreamCursor::readRecord(), llvm::MachineInstr::readsWritesVirtualRegister(), llvm::object::MachOObjectFile::ReadULEB128s(), reassociateOps(), llvm::RegPressureTracker::recede(), llvm::LessRecordRegister::RecordParts::RecordParts(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), llvm::RuntimeDyldELF::registerEHFrames(), llvm::RuntimeDyldCOFFX86_64::registerEHFrames(), llvm::RegsForValue::RegsForValue(), llvm::PostGenericScheduler::releaseBottomNode(), removeConstantFactors(), llvm::SelectionDAG::RemoveDeadNodes(), llvm::LazyCallGraph::SCC::removeInterSCCEdge(), llvm::opt::Arg::render(), llvm::LiveRange::RenumberValues(), llvm::sys::path::replace_extension(), ReplaceBITCASTResults(), replaceInChain(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::R600TargetLowering::ReplaceNodeResults(), llvm::XCoreTargetLowering::ReplaceNodeResults(), llvm::AMDGPUTargetLowering::ReplaceNodeResults(), llvm::SparcTargetLowering::ReplaceNodeResults(), llvm::ARMTargetLowering::ReplaceNodeResults(), llvm::PPCTargetLowering::ReplaceNodeResults(), ReplaceREADCYCLECOUNTER(), llvm::UnwindOpcodeAssembler::Reset(), llvm::MCStreamer::reset(), RewriteHeapSROALoadUser(), RewriteIntelBracExpression(), rewriteNonInstructionUses(), llvm::DAGTypeLegalizer::run(), llvm::SlotIndexes::runOnMachineFunction(), llvm::AMDGPUTargetLowering::ScalarizeVectorLoad(), llvm::AMDGPUTargetLowering::ScalarizeVectorStore(), llvm::SpillPlacement::scanActiveBundles(), llvm::RegScavenger::scavengeRegister(), llvm::StatepointLoweringState::scheduleRelocCall(), llvm::SelectionDAGISel::SelectCodeCommon(), selectELFSectionForGlobal(), llvm::SUnit::setDepthDirty(), llvm::SUnit::setHeightDirty(), SetLoopAlreadyUnrolled(), llvm::StructType::setName(), llvm::LiveIntervals::shrinkToUses(), SimplifyAddOperands(), skipExtensionForVectorMULL(), SkipExtensionForVMULL(), llvm::StringRef::split(), SplitAddRecs(), llvm::MachineBasicBlock::SplitCriticalEdge(), llvm::DINode::splitFlags(), llvm::SplitLandingPadPredecessors(), llvm::SplitString(), splitVectorValues(), SRAGlobal(), stablize_order(), StoreTailCallArgumentsToStackSlot(), llvm::cl::TokenizeGNUCommandLine(), llvm::cl::TokenizeWindowsCommandLine(), llvm::Twine::toNullTerminatedStringRef(), llvm::APFloat::toString(), llvm::APInt::toString(), TrackDefUses(), tryToFoldExtendOfConstant(), llvm::IntEqClasses::uncompress(), llvm::SelectionDAG::UnrollVectorOp(), llvm::UnwindOpcodeAssembler::UnwindOpcodeAssembler(), UpdateCallGraphAfterInlining(), updatePhysDepsDownwards(), updatePhysDepsUpwards(), llvm::UpgradeIntrinsicCall(), llvm::cl::ValuesClass< DataType >::ValuesClass(), llvm::SCEVParameterRewriter::visitAddExpr(), llvm::SCEVApplyRewriter::visitAddExpr(), llvm::SCEVParameterRewriter::visitAddRecExpr(), llvm::SCEVApplyRewriter::visitAddRecExpr(), llvm::SCEVParameterRewriter::visitMulExpr(), llvm::SCEVApplyRewriter::visitMulExpr(), llvm::SCEVParameterRewriter::visitSMaxExpr(), llvm::SCEVApplyRewriter::visitSMaxExpr(), llvm::SCEVParameterRewriter::visitUMaxExpr(), llvm::SCEVApplyRewriter::visitUMaxExpr(), WalkChainUsers(), WriteDIBasicType(), WriteDICompileUnit(), WriteDICompositeType(), WriteDIDerivedType(), WriteDIEnumerator(), WriteDIExpression(), WriteDIFile(), WriteDIGlobalVariable(), WriteDIImportedEntity(), WriteDILexicalBlock(), WriteDILexicalBlockFile(), WriteDILocalVariable(), WriteDILocation(), WriteDINamespace(), WriteDIObjCProperty(), WriteDISubprogram(), WriteDISubrange(), WriteDISubroutineType(), WriteDITemplateTypeParameter(), WriteDITemplateValueParameter(), WriteGenericDINode(), WriteInstruction(), WriteMDTuple(), and WriteValueAsMetadata().
template<typename T, bool isPodLike> void llvm::SmallVectorTemplateBase< T, isPodLike >::push_back (T && Elt) [inline]
Definition at line 229 of file SmallVector.h.
template<typename T, bool isPodLike> template<typename It1 , typename It2 > static void llvm::SmallVectorTemplateBase< T, isPodLike >::uninitialized_copy (It1 I, It1 E, It2 Dest) [inline, static, protected]
Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements as needed.
Definition at line 212 of file SmallVector.h.
Referenced by llvm::SmallVectorTemplateBase< LiveOutInfo, isPodLike< LiveOutInfo >::value >::uninitialized_copy(), llvm::SmallVectorTemplateBase< T, true >::uninitialized_copy(), and llvm::SmallVectorTemplateBase< T, true >::uninitialized_move().
template<typename T, bool isPodLike> template<typename It1 , typename It2 > static void llvm::SmallVectorTemplateBase< T, isPodLike >::uninitialized_move (It1 I, It1 E, It2 Dest) [inline, static, protected]
Move the range [I, E) into the uninitialized memory starting with "Dest", constructing elements as needed.
Definition at line 204 of file SmallVector.h.
The documentation for this class was generated from the following file:
SmallVector.h