LLVM: llvm::sys::fs::directory_iterator Class Reference
llvm::sys::fs::directory_iterator Class Reference
directory_iterator - Iterates through the entries in path.
#include <FileSystem.h>
Public Member Functions
directory_iterator (const Twine &path, std::error_code &ec)
directory_iterator (const directory_entry &de, std::error_code &ec)
directory_iterator ()
Construct end iterator.
directory_iterator & increment (std::error_code &ec)
const directory_entry & operator* () const
const directory_entry * operator-> () const
bool operator== (const directory_iterator &RHS) const
bool operator!= (const directory_iterator &RHS) const
Detailed Description
directory_iterator - Iterates through the entries in path.
There is no operator++ because we need an error_code. If it's really needed we can make it call report_fatal_error on error.
Definition at line 726 of file FileSystem.h.
Constructor & Destructor Documentation
llvm::sys::fs::directory_iterator::directory_iterator (const Twine & path, std::error_code & ec) [inline, explicit]
Definition at line 730 of file FileSystem.h.
References directory_iterator().
llvm::sys::fs::directory_iterator::directory_iterator (const directory_entry & de, std::error_code & ec) [inline, explicit]
Definition at line 737 of file FileSystem.h.
llvm::sys::fs::directory_iterator::directory_iterator () [inline]
Construct end iterator.
Definition at line 743 of file FileSystem.h.
References llvm::sys::fs::detail::directory_iterator_construct(), and llvm::sys::fs::directory_entry::path().
Referenced by directory_iterator().
Member Function Documentation
directory_iterator& llvm::sys::fs::directory_iterator::increment (std::error_code & ec) [inline]
Definition at line 746 of file FileSystem.h.
bool llvm::sys::fs::directory_iterator::operator!= (const directory_iterator & RHS) const [inline]
Definition at line 764 of file FileSystem.h.
const directory_entry& llvm::sys::fs::directory_iterator::operator* () const [inline]
Definition at line 751 of file FileSystem.h.
const directory_entry* llvm::sys::fs::directory_iterator::operator-> () const [inline]
Definition at line 752 of file FileSystem.h.
References llvm::sys::fs::detail::directory_iterator_increment().
bool llvm::sys::fs::directory_iterator::operator== (const directory_iterator & RHS) const [inline]
Definition at line 754 of file FileSystem.h.
The documentation for this class was generated from the following file:
FileSystem.h