LLVM: llvm::EarlyCSEPass Class Reference
llvm::EarlyCSEPass Class Reference
A simple and fast domtree-based CSE pass.
#include <EarlyCSE.h>
Public Member Functions
PreservedAnalyses run (Function &F, AnalysisManager< Function > *AM)
Run the pass over the function.
Static Public Member Functions
static StringRef name ()
Detailed Description
A simple and fast domtree-based CSE pass.
This pass does a simple depth-first walk over the dominator tree, eliminating trivially redundant instructions and using instsimplify to canonicalize things as it goes. It is intended to be fast and catch obvious cases so that instcombine and other passes are more effective. It is expected that a later pass of GVN will catch the interesting/hard cases.
Definition at line 29 of file EarlyCSE.h.
Member Function Documentation
static StringRef llvm::EarlyCSEPass::name () [inline, static]
Definition at line 31 of file EarlyCSE.h.
PreservedAnalyses EarlyCSEPass::run (Function & F, AnalysisManager< Function > * AM)
Run the pass over the function.
Definition at line 710 of file EarlyCSE.cpp.
References llvm::PreservedAnalyses::all(), CSE, F(), llvm::detail::AnalysisManagerBase< AnalysisManager< IRUnitT >, IRUnitT >::getResult(), and llvm::PreservedAnalyses::preserve().
The documentation for this class was generated from the following files:
EarlyCSE.h
EarlyCSE.cpp