LLVM: llvm::SmallVectorImpl< T > Class Template Reference
llvm::SmallVectorImpl< T > Class Template Reference
This class consists of common code factored out of the SmallVector class to reduce code duplication based on the SmallVector 'N' template parameter.
#include <SmallVector.h>
Inherits llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >.
Inherited by llvm::SmallVector< T, N >, and llvm::SmallVector< T, 0 >.
Public Types
typedef SuperClass::iterator iterator
typedef SuperClass::size_type size_type
Public Member Functions
~SmallVectorImpl ()
void clear ()
void resize (size_type N)
void resize (size_type N, const T &NV)
void reserve (size_type N)
T LLVM_ATTRIBUTE_UNUSED_RESULT pop_back_val ()
void swap (SmallVectorImpl &RHS)
template<typename in_iter >
void append (in_iter in_start, in_iter in_end)
Add the specified range to the end of the SmallVector.
void append (size_type NumInputs, const T &Elt)
Add the specified range to the end of the SmallVector.
void append (std::initializer_list< T > IL)
void assign (size_type NumElts, const T &Elt)
void assign (std::initializer_list< T > IL)
iterator erase (iterator I)
iterator erase (iterator S, iterator E)
iterator insert (iterator I, T &&Elt)
iterator insert (iterator I, const T &Elt)
iterator insert (iterator I, size_type NumToInsert, const T &Elt)
template<typename ItTy >
iterator insert (iterator I, ItTy From, ItTy To)
void insert (iterator I, std::initializer_list< T > IL)
template<typename... ArgTypes>
void emplace_back (ArgTypes &&...Args)
SmallVectorImpl & operator= (const SmallVectorImpl &RHS)
SmallVectorImpl & operator= (SmallVectorImpl &&RHS)
bool operator== (const SmallVectorImpl &RHS) const
bool operator!= (const SmallVectorImpl &RHS) const
bool operator< (const SmallVectorImpl &RHS) const
void set_size (size_type N)
Set the array size to N, which the current array must have enough capacity for.
Protected Member Functions
SmallVectorImpl (unsigned N)
Detailed Description
template<typename T>
class llvm::SmallVectorImpl< T >
This class consists of common code factored out of the SmallVector class to reduce code duplication based on the SmallVector 'N' template parameter.
Definition at line 344 of file SmallVector.h.
Member Typedef Documentation
template<typename T> typedef SuperClass::iterator llvm::SmallVectorImpl< T >::iterator
Reimplemented from llvm::SmallVectorTemplateCommon< T >.
Reimplemented in llvm::final< T >, llvm::final< T >, and llvm::final< T >.
Definition at line 349 of file SmallVector.h.
template<typename T> typedef SuperClass::size_type llvm::SmallVectorImpl< T >::size_type
Reimplemented from llvm::SmallVectorTemplateCommon< T >.
Definition at line 350 of file SmallVector.h.
Constructor & Destructor Documentation
template<typename T> llvm::SmallVectorImpl< T >::SmallVectorImpl (unsigned N) [inline, explicit, protected]
Definition at line 354 of file SmallVector.h.
template<typename T> llvm::SmallVectorImpl< T >::~SmallVectorImpl () [inline]
Definition at line 359 of file SmallVector.h.
Member Function Documentation
template<typename T> template<typename in_iter > void llvm::SmallVectorImpl< T >::append (in_iter in_start, in_iter in_end) [inline]
Add the specified range to the end of the SmallVector.
Reimplemented in llvm::SmallString< InternalLen >, llvm::SmallString< 64 >, llvm::SmallString< 128 >, llvm::SmallString< 8 >, and llvm::SmallString< 256 >.
Definition at line 414 of file SmallVector.h.
Referenced by llvm::opt::ArgList::AddAllArgValues(), llvm::DbgVariable::addMMIEntry(), llvm::FoldingSetNodeID::AddNodeID(), llvm::FoldingSetNodeID::AddPointer(), llvm::RecurrenceDescriptor::AddReductionVar(), llvm::FoldingSetNodeID::AddString(), llvm::DebugLocEntry::addValues(), llvm::sys::path::append(), llvm::SmallVectorImpl< MachineInstr * >::append(), llvm::RegsForValue::append(), llvm::SmallVectorImpl< MachineInstr * >::assign(), llvm::RegPressureTracker::closeBottom(), llvm::RegPressureTracker::closeTop(), llvm::MDNode::concatenate(), ConcatenateVectors(), ConstantFoldGetElementPtrImpl(), constexprToEdges(), containsConstantSomewhere(), llvm::MCObjectStreamer::EmitBytes(), llvm::MCObjectStreamer::EmitFill(), llvm::MCWinCOFFStreamer::EmitInstToData(), llvm::MCObjectStreamer::EmitInstToFragment(), llvm::FindInsertedValue(), llvm::SSAUpdaterTraits< SSAUpdater >::FindPredecessorBlocks(), llvm::LiveRange::flushSegmentSet(), llvm::AttributeSet::get(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), llvm::DominatorTreeBase< MachineBasicBlock >::getDescendants(), llvm::ScalarEvolution::getMulExpr(), llvm::SelectionDAG::getNode(), getNoopInput(), llvm::object::MachOObjectFile::getRelocationTypeName(), llvm::object::ELFFile< ELFT >::getRelocationTypeName(), llvm::object::COFFObjectFile::getRelocationTypeName(), llvm::ScalarEvolution::getSMaxExpr(), llvm::ConstantDataArray::getString(), llvm::ScalarEvolution::getUDivExactExpr(), llvm::ScalarEvolution::getUMaxExpr(), getUncompressedData(), llvm::SmallVectorImpl< MachineInstr * >::insert(), isPotentiallyReachableInner(), IsValueFullyAvailableInBlock(), LowerBITCAST(), llvm::SITargetLowering::LowerFormalArguments(), MoveBelowOrigChain(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::BitstreamCursor::readRecord(), llvm::opt::Arg::render(), llvm::opt::Arg::renderAsInput(), llvm::sys::path::replace_extension(), llvm::replaceDbgDeclareForAlloca(), ReplaceINTRINSIC_W_CHAIN(), llvm::EngineBuilder::setMAttrs(), SimplifyAddOperands(), llvm::simplifyLoop(), llvm::SmallVector< unsigned, 0 >::SmallVector(), SplitAddRecs(), llvm::APInt::toString(), llvm::InstCombiner::visitGetElementPtrInst(), WriteAttributeGroupTable(), WriteConstants(), WriteDIExpression(), WriteModuleMetadata(), and WriteModuleMetadataStore().
template<typename T> void llvm::SmallVectorImpl< T >::append (size_type NumInputs, const T & Elt) [inline]
Add the specified range to the end of the SmallVector.
Definition at line 426 of file SmallVector.h.
template<typename T> void llvm::SmallVectorImpl< T >::append (std::initializer_list< T > IL) [inline]
Definition at line 436 of file SmallVector.h.
template<typename T> void llvm::SmallVectorImpl< T >::assign (size_type NumElts, const T & Elt) [inline]
Definition at line 440 of file SmallVector.h.
Referenced by BuildSplatI(), CollectShuffleElements(), CollectSingleShuffleElements(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAGBuilder::getValueImpl(), lowerVectorShuffleAsUnpack(), llvm::SmallVector< unsigned, 0 >::operator=(), and llvm::SmallVector< unsigned, 0 >::SmallVector().
template<typename T> void llvm::SmallVectorImpl< T >::assign (std::initializer_list< T > IL) [inline]
Definition at line 448 of file SmallVector.h.
template<typename T> void llvm::SmallVectorImpl< T >::clear () [inline]
Definition at line 369 of file SmallVector.h.
Referenced by llvm::PMDataManager::add(), llvm::DwarfDebug::addDwarfTypeUnitType(), llvm::LiveIntervals::addKillFlags(), llvm::BPFInstrInfo::AnalyzeBranch(), llvm::HexagonInstrInfo::AnalyzeBranch(), llvm::SparcInstrInfo::AnalyzeBranch(), llvm::MSP430InstrInfo::AnalyzeBranch(), llvm::ARMBaseInstrInfo::AnalyzeBranch(), llvm::SystemZInstrInfo::AnalyzeBranch(), llvm::SystemZCCState::AnalyzeCallOperands(), llvm::MipsCCState::AnalyzeCallOperands(), llvm::MipsCCState::AnalyzeCallResult(), llvm::SystemZCCState::AnalyzeFormalArguments(), llvm::MipsCCState::AnalyzeFormalArguments(), llvm::MipsCCState::AnalyzeReturn(), llvm::SmallVectorImpl< MachineInstr * >::assign(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), buildSetsFrom(), llvm::IDFCalculator::calculate(), llvm::CC_ARM_AAPCS_Custom_Aggregate(), llvm::MipsCCState::CheckReturn(), CleanupPointerRootUsers(), llvm::StatepointLoweringState::clear(), llvm::IntEqClasses::clear(), llvm::StringTableBuilder::clear(), llvm::IndexedMap< unsigned >::clear(), llvm::AssumptionCache::clear(), llvm::SpillPlacement::Node::clear(), llvm::ArrayRecycler< MachineOperand >::clear(), llvm::SchedDFSResult::clear(), llvm::LiveIntervalUnion::Query::clear(), llvm::SplitAnalysis::clear(), llvm::SDDbgInfo::clear(), llvm::FunctionLoweringInfo::clear(), llvm::MCInst::clear(), llvm::GCModuleInfo::clear(), llvm::SparseSet< RootData >::clear(), llvm::LiveRange::clear(), llvm::FoldingSetNodeID::clear(), llvm::SparseMultiSet< VReg2SUnit, VirtReg2IndexFunctor >::clear(), llvm::SelectionDAGBuilder::clear(), llvm::CCState::clearByValRegsInfo(), llvm::FastISel::CallLoweringInfo::clearIns(), llvm::MemoryDepChecker::clearInterestingDependences(), llvm::FastISel::CallLoweringInfo::clearOuts(), collectDebugValues(), combineX86ShufflesRecursively(), llvm::SCEVAddRecExpr::computeAccessFunctions(), llvm::ComputeASanStackFrameLayout(), constexprToEdges(), llvm::convertUTF8ToUTF16String(), llvm::MipsELFStreamer::createPendingLabelRelocs(), llvm::DecodePSHUFBMask(), llvm::RuntimeDyldELF::deregisterEHFrames(), emitComments(), llvm::ConstantPool::emitEntries(), llvm::PPCDispatchGroupSBHazardRecognizer::EmitInstruction(), llvm::PPCDispatchGroupSBHazardRecognizer::EmitNoop(), llvm::MipsELFStreamer::EmitValueImpl(), llvm::MachineModuleInfo::EndFunction(), ExpandBVWithShuffles(), llvm::ARMTargetLowering::ExpandInlineAsm(), llvm::finalizeBundle(), llvm::ScalarEvolution::findArrayDimensions(), findConsecutiveLoad(), FindMostPopularDest(), llvm::SplitEditor::finish(), llvm::BitstreamCursor::freeState(), llvm::ScalarEvolution::getAddExpr(), getAdjustedPtr(), llvm::SelectionDAGBuilder::getControlRoot(), llvm::RegsForValue::getCopyFromRegs(), llvm::TargetSubtargetInfo::getCriticalPathRCs(), llvm::DIARawSymbol::getDataBytes(), llvm::DominatorTreeBase< MachineBasicBlock >::getDescendants(), getMemmoveLoadsAndStores(), llvm::DIADataStream::getNext(), llvm::MemoryDependenceAnalysis::getNonLocalPointerDependency(), llvm::SelectionDAGBuilder::getRoot(), llvm::ScalarEvolution::getUDivExpr(), getUnderlyingObjectsForInstr(), llvm::Loop::getUniqueExitBlocks(), insertParsePoints(), insertVector(), llvm::TargetLowering::LowerCallTo(), llvm::Regex::match(), llvm::MCContext::MCContext(), MoveBelowOrigChain(), llvm::sys::path::native(), llvm::IntervalPressure::openBottom(), llvm::RegionPressure::openBottom(), llvm::IntervalPressure::openTop(), llvm::RegionPressure::openTop(), llvm::BlockFrequencyInfoImplBase::packageLoop(), llvm::SpillPlacement::prepare(), llvm::ValueEnumerator::purgeFunction(), llvm::BitstreamCursor::ReadBlockInfoBlock(), llvm::RuntimeDyldELF::registerEHFrames(), llvm::BranchProbabilityInfo::releaseMemory(), llvm::MachineTraceMetrics::releaseMemory(), llvm::LiveIntervals::releaseMemory(), llvm::SlotIndexes::releaseMemory(), llvm::LiveRange::RenumberValues(), llvm::MCELFStreamer::reset(), llvm::UnwindOpcodeAssembler::Reset(), llvm::PPCDispatchGroupSBHazardRecognizer::Reset(), llvm::MCObjectStreamer::reset(), llvm::IntervalPressure::reset(), llvm::RegionPressure::reset(), llvm::HexagonShuffler::reset(), llvm::LexicalScopes::reset(), llvm::LiveRangeCalc::reset(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Reset(), llvm::MCLOHContainer::reset(), llvm::MCStreamer::reset(), llvm::InlineFunctionInfo::reset(), llvm::MCContext::reset(), llvm::LoopAccessInfo::RuntimePointerCheck::reset(), llvm::SchedRemainder::reset(), llvm::SchedBoundary::reset(), llvm::TypeFinder::run(), llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::RegisterClassInfo::runOnMachineFunction(), llvm::MachineDominatorTree::runOnMachineFunction(), llvm::SpillPlacement::scanActiveBundles(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::FileRemover::setFile(), llvm::EngineBuilder::setMAttrs(), SimplifyAddOperands(), llvm::SplitCriticalEdge(), llvm::MachineBasicBlock::SplitCriticalEdge(), llvm::MipsELFStreamer::SwitchSection(), llvm::cl::TokenizeGNUCommandLine(), llvm::cl::TokenizeWindowsCommandLine(), llvm::BlockFrequencyInfoImplBase::updateLoopWithIrreducible(), llvm::MachineBasicBlock::updateTerminator(), WriteAttributeGroupTable(), WriteAttributeTable(), writeComdats(), WriteConstants(), WriteDIBasicType(), WriteDICompileUnit(), WriteDICompositeType(), WriteDIDerivedType(), WriteDIEnumerator(), WriteDIExpression(), WriteDIFile(), WriteDIGlobalVariable(), WriteDIImportedEntity(), WriteDILexicalBlock(), WriteDILexicalBlockFile(), WriteDILocalVariable(), WriteDILocation(), WriteDINamespace(), WriteDIObjCProperty(), WriteDISubprogram(), WriteDISubrange(), WriteDISubroutineType(), WriteDITemplateTypeParameter(), WriteDITemplateValueParameter(), WriteFunction(), WriteGenericDINode(), WriteInstruction(), WriteMetadataAttachment(), WriteModuleInfo(), WriteModuleMetadata(), WriteModuleMetadataStore(), WriteTypeTable(), WriteValueAsMetadata(), WriteValueSymbolTable(), llvm::GCOVBlock::~GCOVBlock(), and llvm::MCJIT::~MCJIT().
template<typename T> template<typename... ArgTypes> void llvm::SmallVectorImpl< T >::emplace_back (ArgTypes &&... Args) [inline]
Definition at line 650 of file SmallVector.h.
Referenced by llvm::IDFCalculator::calculate(), createImportedModule(), DeleteTriviallyDeadInstructions(), isAllocSiteRemovable(), LinearizeExprTree(), llvm::SCEVExpander::replaceCongruentIVs(), llvm::DIBuilder::retainType(), and llvm::MachineModuleInfo::setVariableDbgInfo().
template<typename T> iterator llvm::SmallVectorImpl< T >::erase (iterator I) [inline]
Definition at line 453 of file SmallVector.h.
Referenced by llvm::RegPressureTracker::closeBottom(), llvm::RegPressureTracker::closeTop(), completeEphemeralValues(), DecomposeGEPExpression(), determineMissingVNIs(), llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::MCInst::erase(), llvm::cl::ExpandResponseFiles(), llvm::ScalarEvolution::findArrayDimensions(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getMulExpr(), getNaturalGEPWithType(), llvm::ScalarEvolution::getSMaxExpr(), llvm::ScalarEvolution::getUMaxExpr(), isVectorPromotionViable(), llvm::LiveRange::join(), lowerV16I8VectorShuffle(), lowerV8I16GeneralSingleInputVectorShuffle(), llvm::LiveRange::MergeValueNumberInto(), OptimizeAndOrXor(), llvm::MachineInstr::print(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), relocationViaAlloca(), llvm::StatepointLoweringState::relocCallVisited(), llvm::MDAttachmentMap::remove_if(), llvm::Inliner::removeDeadFunctions(), RemoveInstInputs(), llvm::LazyCallGraph::SCC::removeIntraSCCEdge(), llvm::cl::parser< const PassInfo * >::removeLiteralOption(), llvm::ExecutionEngine::removeModule(), llvm::SUnit::removePred(), llvm::LiveRange::removeSegment(), llvm::LiveRange::removeValNo(), replaceConstantExprOp(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Reset(), llvm::Inliner::runOnSCC(), SimplifyBranchOnICmpChain(), llvm::DebugLocEntry::sortUniqueValues(), llvm::MachineModuleInfo::TidyLandingPads(), unique_unsorted(), llvm::BlockFrequencyInfoImplBase::updateLoopWithIrreducible(), VerifySubExpr(), and llvm::InstCombiner::visitLandingPadInst().
template<typename T> iterator llvm::SmallVectorImpl< T >::erase (iterator S, iterator E) [inline]
Definition at line 465 of file SmallVector.h.
template<typename T> iterator llvm::SmallVectorImpl< T >::insert (iterator I, T && Elt) [inline]
Definition at line 479 of file SmallVector.h.
Referenced by llvm::DwarfFile::addScopeVariable(), llvm::MipsInstrInfo::AnalyzeBranch(), analyzeParsePointLiveness(), llvm::ComputeASanStackFrameLayout(), llvm::TargetLoweringObjectFileELF::emitPersonalityValue(), llvm::UnwindOpcodeAssembler::EmitRaw(), llvm::BitstreamWriter::EmitRecord(), llvm::cl::ExpandResponseFiles(), findBasePointers(), findConsecutiveLoad(), llvm::AttributeSet::get(), llvm::SelectionDAG::getConstant(), llvm::MCSection::getSubsectionInsertionPoint(), llvm::MCInst::insert(), llvm::SmallVectorImpl< MachineInstr * >::insert(), insertParsePoints(), llvm::BlockFrequencyInfoImplBase::LoopData::LoopData(), LowerInterruptReturn(), llvm::SelectionDAGBuilder::LowerStatepoint(), makeStatepointExplicitImpl(), prependCompressionHeader(), llvm::AArch64TargetLowering::ReconstructShuffle(), llvm::LiveRange::removeSegment(), llvm::IntervalMapImpl::Path::replaceRoot(), and llvm::WriteBitcodeToFile().
template<typename T> iterator llvm::SmallVectorImpl< T >::insert (iterator I, const T & Elt) [inline]
Definition at line 509 of file SmallVector.h.
template<typename T> iterator llvm::SmallVectorImpl< T >::insert (iterator I, size_type NumToInsert, const T & Elt) [inline]
Definition at line 538 of file SmallVector.h.
template<typename T> template<typename ItTy > iterator llvm::SmallVectorImpl< T >::insert (iterator I, ItTy From, ItTy To) [inline]
Definition at line 590 of file SmallVector.h.
template<typename T> void llvm::SmallVectorImpl< T >::insert (iterator I, std::initializer_list< T > IL) [inline]
Definition at line 646 of file SmallVector.h.
template<typename T> bool llvm::SmallVectorImpl< T >::operator!= (const SmallVectorImpl< T > & RHS) const [inline]
Definition at line 665 of file SmallVector.h.
template<typename T> bool llvm::SmallVectorImpl< T >::operator< (const SmallVectorImpl< T > & RHS) const [inline]
Definition at line 669 of file SmallVector.h.
template<typename T > SmallVectorImpl< T > & llvm::SmallVectorImpl< T >::operator= (const SmallVectorImpl< T > & RHS)
Definition at line 730 of file SmallVector.h.
References llvm::sys::path::begin(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::sys::path::end(), llvm::SmallVectorTemplateCommon< T >::end(), size, and llvm::SmallVectorTemplateCommon< T >::size().
template<typename T > SmallVectorImpl< T > & llvm::SmallVectorImpl< T >::operator= (SmallVectorImpl< T > && RHS)
Reimplemented in llvm::SmallVector< T, N >, and llvm::SmallVector< T, 0 >.
Definition at line 778 of file SmallVector.h.
References llvm::sys::path::begin(), llvm::sys::path::end(), and size.
template<typename T> bool llvm::SmallVectorImpl< T >::operator== (const SmallVectorImpl< T > & RHS) const [inline]
Definition at line 661 of file SmallVector.h.
template<typename T> T LLVM_ATTRIBUTE_UNUSED_RESULT llvm::SmallVectorImpl< T >::pop_back_val () [inline]
Definition at line 404 of file SmallVector.h.
Referenced by addBlockAndPredsToSet(), AddReachableCodeToWorklist(), AreAnyUnderlyingObjectsAnAlloca(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), buildMultiplyTree(), buildSetsFrom(), llvm::IDFCalculator::calculate(), llvm::SSAUpdaterImpl< UpdaterT >::CheckIfPHIMatches(), combineRedundantDWordShuffle(), constexprToEdges(), ConstHasGlobalValuePredicate(), containsConstantSomewhere(), DeleteDeadInstruction(), DeleteTriviallyDeadInstructions(), determinePointerReadAttrs(), llvm::LiveRangeEdit::eliminateDeadDefs(), findCallees(), llvm::objcarc::FindDependencies(), llvm::FindFunctionBackedges(), llvm::ScalarEvolution::forgetLoop(), llvm::ScalarEvolution::forgetValue(), llvm::DominatorTreeBase< MachineBasicBlock >::getDescendants(), getUnderlyingObjects(), llvm::GetUnderlyingObjects(), llvm::SDNode::hasPredecessorHelper(), llvm::HexagonMCShuffle(), llvm::LazyCallGraph::SCC::insertIncomingEdge(), llvm::MachineTraceMetrics::Ensemble::invalidate(), isAllocSiteRemovable(), llvm::LazyCallGraph::SCC::isDescendantOf(), isEphemeralValueOf(), isLeakCheckerRoot(), isObjectSizeLessThanOrEq(), isOnlyCopiedFromConstantGlobal(), isPotentiallyReachableInner(), IsStoredObjCPointer(), IsValueFullyAvailableInBlock(), llvm::SpillPlacement::iterate(), markAliveBlocks(), llvm::SIInstrInfo::moveToVALU(), llvm::PHITransAddr::PHITranslateWithInsertion(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), llvm::SelectionDAG::RemoveDeadNodes(), llvm::InstCombineWorklist::RemoveOne(), rewriteNonInstructionUses(), llvm::SUnit::setDepthDirty(), llvm::SUnit::setHeightDirty(), llvm::simplifyLoop(), llvm::UnrollLoop(), updateLiveness(), verifyCTRBranch(), llvm::SCEVTraversal< SV >::visitAll(), and llvm::PtrUseVisitor< SliceBuilder >::visitPtr().
template<typename T> void llvm::SmallVectorImpl< T >::reserve (size_type N) [inline]
Definition at line 399 of file SmallVector.h.
Referenced by llvm::InstCombineWorklist::AddInitialGroup(), AddOperand(), llvm::DwarfCompileUnit::attachRangesOrLowHighPC(), llvm::RegPressureTracker::closeBottom(), llvm::RegPressureTracker::closeTop(), combineX86ShufflesRecursively(), llvm::EHStreamer::computeActionsTable(), llvm::MDNode::concatenate(), ConstantFoldGetElementPtrImpl(), llvm::ConstantFoldInsertElementInstruction(), CreateGCRelocates(), llvm::DecodePSHUFBMask(), llvm::DecodeVPERMILPMask(), llvm::EHStreamer::emitExceptionTable(), emitIntrinsicWithChainAndGlue(), emitIntrinsicWithGlue(), ExpandBVWithShuffles(), extractVector(), llvm::StringTableBuilder::finalize(), findBasePointer(), findBasePointers(), llvm::FindInsertedValue(), llvm::MachineInstrExpressionTrait::getHashValue(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getIntrinsicCost(), llvm::SelectionDAG::getMergeValues(), llvm::MDNode::getMostGenericRange(), llvm::ScalarEvolution::getMulExpr(), llvm::IntEqClasses::grow(), llvm::raw_svector_ostream::init(), llvm::ScheduleDAGTopologicalSort::InitDAGTopologicalSorting(), llvm::SmallVectorImpl< MachineInstr * >::insert(), insertParsePoints(), insertVector(), makeStatepointExplicit(), llvm::MapValue(), OptimizeAwayTrappingUsesOfValue(), llvm::CallGraph::print(), relocationViaAlloca(), llvm::RemapInstruction(), llvm::ConstantArray::replaceUsesOfWithOnConstant(), llvm::ConstantStruct::replaceUsesOfWithOnConstant(), llvm::ConstantVector::replaceUsesOfWithOnConstant(), llvm::IndexedMap< unsigned >::reserve(), llvm::raw_svector_ostream::resync(), llvm::SlotIndexes::runOnMachineFunction(), SimplifyCall(), simplifyShuffleOperandRecursively(), llvm::InstCombiner::visitLandingPadInst(), llvm::WriteBitcodeToFile(), WriteDIExpression(), and llvm::LLVMContextImpl::~LLVMContextImpl().
template<typename T> void llvm::SmallVectorImpl< T >::resize (size_type N) [inline]
Definition at line 374 of file SmallVector.h.
Referenced by llvm::Calculate(), llvm::CCState::CCState(), llvm::EHStreamer::computeCallSiteTable(), ConstantFoldGetElementPtrImpl(), llvm::convertUTF8ToUTF16String(), llvm::DependenceAnalysis::depends(), llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::DWARFContextInMemory::DWARFContextInMemory(), llvm::MCWinCOFFStreamer::EmitCOFFSecRel32(), llvm::MCWinCOFFStreamer::EmitCOFFSectionIndex(), llvm::MCObjectStreamer::EmitGPRel32Value(), llvm::MCObjectStreamer::EmitGPRel64Value(), llvm::MCObjectStreamer::EmitValueImpl(), llvm::MachineTraceMetrics::Ensemble::Ensemble(), llvm::UnwindOpcodeAssembler::Finalize(), llvm::SplitEditor::finish(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::RegsForValue::getCopyFromRegs(), llvm::DIARawSymbol::getDataBytes(), llvm::MCDwarfLineTableHeader::getFile(), llvm::DIADataStream::getItemAtIndex(), llvm::LLVMContext::getMDKindNames(), llvm::MDNode::getMostGenericRange(), llvm::DIADataStream::getNext(), getNoopInput(), llvm::CCState::getRemainingRegParmsForType(), llvm::DependenceAnalysis::getSplitIteration(), getVPermMask(), llvm::TargetSchedModel::init(), llvm::SchedRemainder::init(), llvm::SchedBoundary::init(), is128BitLaneRepeatedShuffleMask(), llvm::LiveRange::join(), llvm::BlockFrequencyInfoImplBase::LoopData::LoopData(), lowerVectorShuffleByMerging128BitLanes(), llvm::Regex::match(), llvm::IntervalMapImpl::Path::moveLeft(), llvm::object::ExportEntry::moveNext(), llvm::Triple::normalize(), llvm::raw_ostream::operator<<(), llvm::DWARFDebugLoc::parse(), llvm::DWARFDebugLocDWO::parse(), llvm::promoteLoopAccessesToScalars(), llvm::coverage::RawCoverageMappingReader::read(), llvm::SchedBoundary::reset(), llvm::IndexedMap< unsigned >::resize(), llvm::MachineTraceMetrics::runOnMachineFunction(), llvm::RegisterClassInfo::runOnMachineFunction(), llvm::SlotIndexes::runOnMachineFunction(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::StructType::setName(), and llvm::StatepointLoweringState::startNewStatepoint().
template<typename T> void llvm::SmallVectorImpl< T >::resize (size_type N, const T & NV) [inline]
Definition at line 387 of file SmallVector.h.
template<typename T> void llvm::SmallVectorImpl< T >::set_size (size_type N) [inline]
Set the array size to N, which the current array must have enough capacity for.
This does not construct or destroy any elements in the vector.
Clients can use this in conjunction with capacity() to write past the end of the buffer when they know that more elements are available, and only update the size later. This avoids the cost of value initializing elements which will only be overwritten.
Definition at line 683 of file SmallVector.h.
Referenced by llvm::sys::path::remove_filename(), and llvm::sys::path::replace_extension().
template<typename T > void llvm::SmallVectorImpl< T >::swap (SmallVectorImpl< T > & RHS)
Definition at line 691 of file SmallVector.h.
References llvm::sys::path::begin(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::SmallVectorBase::BeginX, llvm::SmallVectorTemplateCommon< T >::capacity(), llvm::SmallVectorBase::CapacityX, llvm::sys::path::end(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::SmallVectorBase::EndX, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::grow(), llvm::SmallVectorTemplateCommon< T >::isSmall(), llvm::SmallVectorTemplateCommon< T >::setEnd(), size, llvm::SmallVectorTemplateCommon< T >::size(), and std::swap().
Referenced by createUniqueEntity(), ExpandBVWithShuffles(), llvm::sys::fs::make_absolute(), llvm::LazyCallGraph::SCC::removeIntraSCCEdge(), llvm::LiveIntervals::shrinkToUses(), and std::swap().
The documentation for this class was generated from the following file:
SmallVector.h