LLVM: llvm::VACopyInst Class Reference
llvm::VACopyInst Class Reference
VACopyInst - This represents the llvm.va_copy intrinsic.
#include <IntrinsicInst.h>
Public Member Functions
Value * getDest () const
Value * getSrc () const
Static Public Member Functions
static bool classof (const IntrinsicInst *I)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Detailed Description
VACopyInst - This represents the llvm.va_copy intrinsic.
Definition at line 335 of file IntrinsicInst.h.
Member Function Documentation
static bool llvm::VACopyInst::classof (const IntrinsicInst * I) [inline, static]
Definition at line 337 of file IntrinsicInst.h.
References llvm::IntrinsicInst::getIntrinsicID().
Referenced by classof().
static bool llvm::VACopyInst::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::IntrinsicInst.
Definition at line 340 of file IntrinsicInst.h.
References classof().
Value* llvm::VACopyInst::getDest () const [inline]
Definition at line 344 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperand().
Value* llvm::VACopyInst::getSrc () const [inline]
Definition at line 345 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperand().
The documentation for this class was generated from the following file:
IntrinsicInst.h