LLVM: llvm::SCEVNAryExpr Class Reference
llvm::SCEVNAryExpr Class Reference
SCEVNAryExpr - This node is a base class providing common functionality for n'ary operators.
#include <ScalarEvolutionExpressions.h>
Public Types
typedef const SCEV *const * op_iterator
typedef iterator_range
< op_iterator > op_range
Public Member Functions
size_t getNumOperands () const
const SCEV * getOperand (unsigned i) const
op_iterator op_begin () const
op_iterator op_end () const
op_range operands () const
Type * getType () const
getType - Return the LLVM type of this SCEV expression.
NoWrapFlags getNoWrapFlags (NoWrapFlags Mask=NoWrapMask) const
Static Public Member Functions
static bool classof (const SCEV *S)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
SCEVNAryExpr (const FoldingSetNodeIDRef ID, enum SCEVTypes T, const SCEV *const *O, size_t N)
Protected Attributes
const SCEV *const * Operands
size_t NumOperands
Detailed Description
SCEVNAryExpr - This node is a base class providing common functionality for n'ary operators.
Definition at line 134 of file ScalarEvolutionExpressions.h.
Member Typedef Documentation
typedef const SCEV* const* llvm::SCEVNAryExpr::op_iterator
Definition at line 154 of file ScalarEvolutionExpressions.h.
typedef iterator_range<op_iterator> llvm::SCEVNAryExpr::op_range
Definition at line 155 of file ScalarEvolutionExpressions.h.
Constructor & Destructor Documentation
llvm::SCEVNAryExpr::SCEVNAryExpr (const FoldingSetNodeIDRef ID, enum SCEVTypes T, const SCEV *const * O, size_t N) [inline, protected]
Definition at line 143 of file ScalarEvolutionExpressions.h.
Member Function Documentation
static bool llvm::SCEVNAryExpr::classof (const SCEV * S) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented in llvm::SCEVUMaxExpr, llvm::SCEVSMaxExpr, llvm::SCEVAddRecExpr, llvm::SCEVMulExpr, llvm::SCEVAddExpr, and llvm::SCEVCommutativeExpr.
Definition at line 169 of file ScalarEvolutionExpressions.h.
References llvm::SCEV::getSCEVType(), llvm::scAddExpr, llvm::scAddRecExpr, llvm::scMulExpr, llvm::scSMaxExpr, and llvm::scUMaxExpr.
NoWrapFlags llvm::SCEVNAryExpr::getNoWrapFlags (NoWrapFlags Mask = NoWrapMask) const [inline]
Definition at line 164 of file ScalarEvolutionExpressions.h.
References llvm::SCEV::SubclassData.
Referenced by llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getMulExpr(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), getPreStartForExtend(), llvm::isStridedPtr(), llvm::SCEV::print(), llvm::SCEVParameterRewriter::visitAddRecExpr(), and llvm::SCEVApplyRewriter::visitAddRecExpr().
size_t llvm::SCEVNAryExpr::getNumOperands () const [inline]
Definition at line 148 of file ScalarEvolutionExpressions.h.
References NumOperands.
Referenced by BuildConstantFromSCEV(), CollectAddOperandsWithScales(), llvm::SCEVAddRecExpr::evaluateAtIteration(), llvm::ScalarEvolution::getAddExpr(), getConstantPart(), llvm::ScalarEvolution::getMulExpr(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), getPreStartForExtend(), llvm::SCEVAddExpr::getType(), llvm::ScalarEvolution::getUDivExactExpr(), llvm::SCEVAddRecExpr::isAffine(), isMulSExtable(), llvm::SCEVAddRecExpr::isQuadratic(), MatchNotExpr(), llvm::SCEV::print(), SolveQuadraticEquation(), llvm::SCEVParameterRewriter::visitAddExpr(), llvm::SCEVApplyRewriter::visitAddExpr(), llvm::SCEVParameterRewriter::visitAddRecExpr(), llvm::SCEVApplyRewriter::visitAddRecExpr(), llvm::SCEVParameterRewriter::visitMulExpr(), llvm::SCEVApplyRewriter::visitMulExpr(), llvm::SCEVParameterRewriter::visitSMaxExpr(), llvm::SCEVApplyRewriter::visitSMaxExpr(), llvm::SCEVParameterRewriter::visitUMaxExpr(), and llvm::SCEVApplyRewriter::visitUMaxExpr().
const SCEV* llvm::SCEVNAryExpr::getOperand (unsigned i) const [inline]
Definition at line 149 of file ScalarEvolutionExpressions.h.
References NumOperands, and Operands.
Referenced by BuildConstantFromSCEV(), CollectAddOperandsWithScales(), llvm::SCEVAddRecExpr::evaluateAtIteration(), llvm::ScalarEvolution::getAddExpr(), getConstantPart(), llvm::ScalarEvolution::getMulExpr(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), llvm::SCEVAddRecExpr::getStepRecurrence(), getType(), llvm::SCEVAddExpr::getType(), llvm::ScalarEvolution::getUDivExactExpr(), llvm::SCEV::isNonConstantNegative(), MatchNotExpr(), llvm::SCEV::print(), SolveQuadraticEquation(), llvm::SCEVParameterRewriter::visitAddExpr(), llvm::SCEVApplyRewriter::visitAddExpr(), llvm::SCEVParameterRewriter::visitAddRecExpr(), llvm::SCEVApplyRewriter::visitAddRecExpr(), llvm::SCEVParameterRewriter::visitMulExpr(), llvm::SCEVApplyRewriter::visitMulExpr(), llvm::SCEVParameterRewriter::visitSMaxExpr(), llvm::SCEVApplyRewriter::visitSMaxExpr(), llvm::SCEVParameterRewriter::visitUMaxExpr(), and llvm::SCEVApplyRewriter::visitUMaxExpr().
Type* llvm::SCEVNAryExpr::getType () const [inline]
getType - Return the LLVM type of this SCEV expression.
Reimplemented from llvm::SCEV.
Reimplemented in llvm::SCEVAddExpr.
Definition at line 162 of file ScalarEvolutionExpressions.h.
References getOperand(), and llvm::SCEV::getType().
Referenced by canBeCheaplyTransformed(), CollectSubexprs(), llvm::SCEVAddRecExpr::evaluateAtIteration(), FindLoopCounter(), llvm::ScalarEvolution::getMulExpr(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), getPreStartForExtend(), isAddRecSExtable(), isExistingPhi(), IsIncrementNSW(), IsIncrementNUW(), and isMulSExtable().
op_iterator llvm::SCEVNAryExpr::op_begin () const [inline]
Definition at line 156 of file ScalarEvolutionExpressions.h.
References Operands.
Referenced by CollectAddOperandsWithScales(), llvm::ScalarEvolution::getAddExpr(), getExprBase(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::ScalarEvolution::getUDivExactExpr(), operands(), llvm::SCEV::print(), and llvm::SCEVTraversal< SV >::visitAll().
op_iterator llvm::SCEVNAryExpr::op_end () const [inline]
Definition at line 157 of file ScalarEvolutionExpressions.h.
References NumOperands, and Operands.
Referenced by CollectAddOperandsWithScales(), llvm::ScalarEvolution::getAddExpr(), getExprBase(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::ScalarEvolution::getUDivExactExpr(), operands(), llvm::SCEV::print(), and llvm::SCEVTraversal< SV >::visitAll().
op_range llvm::SCEVNAryExpr::operands () const [inline]
Definition at line 158 of file ScalarEvolutionExpressions.h.
References llvm::make_range(), op_begin(), and op_end().
Referenced by getPreStartForExtend().
Member Data Documentation
size_t llvm::SCEVNAryExpr::NumOperands [protected]
Definition at line 141 of file ScalarEvolutionExpressions.h.
Referenced by getNumOperands(), getOperand(), and op_end().
const SCEV* const* llvm::SCEVNAryExpr::Operands [protected]
Definition at line 140 of file ScalarEvolutionExpressions.h.
Referenced by llvm::SCEVAddRecExpr::getNumIterationsInRange(), getOperand(), llvm::SCEVAddRecExpr::getStart(), op_begin(), and op_end().
The documentation for this class was generated from the following file:
ScalarEvolutionExpressions.h