LLVM: llvm::ConstantDataVector Class Reference
llvm::ConstantDataVector Class Reference
ConstantDataVector - A vector constant whose element type is a simple 1/2/4/8-byte integer or float/double, and whose elements are just simple data values (i.e.
#include <Constants.h>
Public Member Functions
Constant * getSplatValue () const
getSplatValue - If this is a splat constant, meaning that all of the elements have the same value, return that value.
VectorType * getType () const
getType - Specialize the getType() method to always return a VectorType, which reduces the amount of casting needed in parts of the compiler.
Static Public Member Functions
static Constant * get (LLVMContext &Context, ArrayRef< uint8_t > Elts)
get() constructors - Return a constant with vector type with an element count and element type matching the ArrayRef passed in.
static Constant * get (LLVMContext &Context, ArrayRef< uint16_t > Elts)
static Constant * get (LLVMContext &Context, ArrayRef< uint32_t > Elts)
static Constant * get (LLVMContext &Context, ArrayRef< uint64_t > Elts)
static Constant * get (LLVMContext &Context, ArrayRef< float > Elts)
static Constant * get (LLVMContext &Context, ArrayRef< double > Elts)
static Constant * getFP (LLVMContext &Context, ArrayRef< uint16_t > Elts)
getFP() constructors - Return a constant with vector type with an element count and element type of float with the precision matching the number of bits in the ArrayRef passed in.
static Constant * getFP (LLVMContext &Context, ArrayRef< uint32_t > Elts)
static Constant * getFP (LLVMContext &Context, ArrayRef< uint64_t > Elts)
static Constant * getSplat (unsigned NumElts, Constant *Elt)
getSplat - Return a ConstantVector with the specified constant in each element.
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
void * operator new (size_t s)
Allocate a User with an operand pointer co-allocated.
Friends
class ConstantDataSequential
Detailed Description
ConstantDataVector - A vector constant whose element type is a simple 1/2/4/8-byte integer or float/double, and whose elements are just simple data values (i.e.
ConstantInt/ConstantFP). This Constant node has no operands because it stores all of the elements of the constant as densely packed data, instead of as Value*'s.
Definition at line 740 of file Constants.h.
Member Function Documentation
static bool llvm::ConstantDataVector::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::ConstantDataSequential.
Definition at line 791 of file Constants.h.
References llvm::Value::getValueID().
Constant * ConstantDataVector::get (LLVMContext & Context, ArrayRef< uint8_t > Elts) [static]
get() constructors - Return a constant with vector type with an element count and element type matching the ArrayRef passed in.
Note that this can return a ConstantAggregateZero object.
Definition at line 2627 of file Constants.cpp.
References llvm::ArrayRef< T >::data(), llvm::Data, llvm::ConstantDataSequential::getImpl(), llvm::Type::getInt8Ty(), and llvm::ArrayRef< T >::size().
Referenced by get(), getFP(), OptimizeVectorResize(), and llvm::InstCombiner::visitCallInst().
Constant * ConstantDataVector::get (LLVMContext & Context, ArrayRef< uint16_t > Elts) [static]
Definition at line 2632 of file Constants.cpp.
References llvm::ArrayRef< T >::data(), llvm::Data, get(), llvm::ConstantDataSequential::getImpl(), llvm::Type::getInt16Ty(), and llvm::ArrayRef< T >::size().
Constant * ConstantDataVector::get (LLVMContext & Context, ArrayRef< uint32_t > Elts) [static]
Definition at line 2637 of file Constants.cpp.
References llvm::ArrayRef< T >::data(), llvm::Data, get(), llvm::ConstantDataSequential::getImpl(), llvm::Type::getInt32Ty(), and llvm::ArrayRef< T >::size().
Constant * ConstantDataVector::get (LLVMContext & Context, ArrayRef< uint64_t > Elts) [static]
Definition at line 2642 of file Constants.cpp.
References llvm::ArrayRef< T >::data(), llvm::Data, get(), llvm::ConstantDataSequential::getImpl(), llvm::Type::getInt64Ty(), and llvm::ArrayRef< T >::size().
Constant * ConstantDataVector::get (LLVMContext & Context, ArrayRef< float > Elts) [static]
Definition at line 2647 of file Constants.cpp.
References llvm::ArrayRef< T >::data(), llvm::Data, get(), llvm::Type::getFloatTy(), llvm::ConstantDataSequential::getImpl(), and llvm::ArrayRef< T >::size().
Constant * ConstantDataVector::get (LLVMContext & Context, ArrayRef< double > Elts) [static]
Definition at line 2652 of file Constants.cpp.
References llvm::ArrayRef< T >::data(), llvm::Data, get(), llvm::Type::getDoubleTy(), llvm::ConstantDataSequential::getImpl(), and llvm::ArrayRef< T >::size().
Constant * ConstantDataVector::getFP (LLVMContext & Context, ArrayRef< uint16_t > Elts) [static]
getFP() constructors - Return a constant with vector type with an element count and element type of float with the precision matching the number of bits in the ArrayRef passed in.
(i.e. half for 16bits, float for 32bits, double for 64bits) Note that this can return a ConstantAggregateZero object.
Definition at line 2663 of file Constants.cpp.
References llvm::ArrayRef< T >::data(), llvm::Data, get(), llvm::Type::getHalfTy(), llvm::ConstantDataSequential::getImpl(), and llvm::ArrayRef< T >::size().
Referenced by getSplat().
Constant * ConstantDataVector::getFP (LLVMContext & Context, ArrayRef< uint32_t > Elts) [static]
Definition at line 2669 of file Constants.cpp.
References llvm::ArrayRef< T >::data(), llvm::Data, get(), llvm::Type::getFloatTy(), llvm::ConstantDataSequential::getImpl(), and llvm::ArrayRef< T >::size().
Constant * ConstantDataVector::getFP (LLVMContext & Context, ArrayRef< uint64_t > Elts) [static]
Definition at line 2675 of file Constants.cpp.
References llvm::ArrayRef< T >::data(), llvm::Data, get(), llvm::Type::getDoubleTy(), llvm::ConstantDataSequential::getImpl(), and llvm::ArrayRef< T >::size().
Constant * ConstantDataVector::getSplat (unsigned NumElts, Constant * Elt) [static]
getSplat - Return a ConstantVector with the specified constant in each element.
The specified constant has to be a of a compatible type (i8/i16/ i32/i64/float/double) and must be a ConstantFP or ConstantInt.
Definition at line 2682 of file Constants.cpp.
References llvm::Value::getContext(), getFP(), llvm::Value::getType(), and llvm::ConstantDataSequential::isElementTypeCompatible().
Constant * ConstantDataVector::getSplatValue () const
getSplatValue - If this is a splat constant, meaning that all of the elements have the same value, return that value.
Otherwise return NULL.
Otherwise return nullptr.
Reimplemented from llvm::Constant.
Definition at line 2811 of file Constants.cpp.
References llvm::StringRef::data(), llvm::ConstantDataSequential::getElementAsConstant(), llvm::ConstantDataSequential::getElementByteSize(), llvm::ConstantDataSequential::getNumElements(), and llvm::ConstantDataSequential::getRawDataValues().
VectorType* llvm::ConstantDataVector::getType () const [inline]
getType - Specialize the getType() method to always return a VectorType, which reduces the amount of casting needed in parts of the compiler.
Reimplemented from llvm::ConstantDataSequential.
Definition at line 785 of file Constants.h.
void* llvm::ConstantDataVector::operator new (size_t Size) [inline, protected]
Allocate a User with an operand pointer co-allocated.
This is used for subclasses which need to allocate a variable number of operands, ie, 'hung off uses'.
Reimplemented from llvm::ConstantDataSequential.
Definition at line 749 of file Constants.h.
References operator new().
Friends And Related Function Documentation
friend class ConstantDataSequential [friend]
Definition at line 744 of file Constants.h.
The documentation for this class was generated from the following files:
Constants.h
Constants.cpp