LLVM: llvm::object::MachOUniversalBinary::ObjectForArch Class Reference
llvm::object::MachOUniversalBinary::ObjectForArch Class Reference
#include <MachOUniversal.h>
Public Member Functions
ObjectForArch (const MachOUniversalBinary *Parent, uint32_t Index)
void clear ()
bool operator== (const ObjectForArch &Other) const
ObjectForArch getNext () const
uint32_t getCPUType () const
uint32_t getCPUSubType () const
uint32_t getOffset () const
uint32_t getSize () const
uint32_t getAlign () const
std::string getArchTypeName () const
ErrorOr< std::unique_ptr
< MachOObjectFile > > getAsObjectFile () const
ErrorOr< std::unique_ptr
< Archive > > getAsArchive () const
Detailed Description
Definition at line 34 of file MachOUniversal.h.
Constructor & Destructor Documentation
MachOUniversalBinary::ObjectForArch::ObjectForArch (const MachOUniversalBinary * Parent, uint32_t Index)
Definition at line 53 of file MachOUniversal.cpp.
References llvm::StringRef::begin(), clear(), llvm::object::Binary::getData(), llvm::object::MachOUniversalBinary::getNumberOfObjects(), llvm::MachO::fat_arch::offset, llvm::StringRef::size(), and llvm::MachO::fat_arch::size.
Referenced by getNext().
Member Function Documentation
void llvm::object::MachOUniversalBinary::ObjectForArch::clear () [inline]
Definition at line 44 of file MachOUniversal.h.
Referenced by ObjectForArch().
uint32_t llvm::object::MachOUniversalBinary::ObjectForArch::getAlign () const [inline]
Definition at line 58 of file MachOUniversal.h.
References llvm::MachO::fat_arch::align.
std::string llvm::object::MachOUniversalBinary::ObjectForArch::getArchTypeName () const [inline]
Definition at line 59 of file MachOUniversal.h.
References llvm::MachO::fat_arch::cpusubtype, llvm::MachO::fat_arch::cputype, llvm::object::MachOObjectFile::getArch(), and llvm::Triple::getArchName().
ErrorOr< std::unique_ptr< Archive > > MachOUniversalBinary::ObjectForArch::getAsArchive () const
Definition at line 83 of file MachOUniversal.cpp.
References llvm::object::MachOUniversalBinary::create(), llvm::object::parse_failed, and llvm::StringRef::substr().
ErrorOr< std::unique_ptr< MachOObjectFile > > MachOUniversalBinary::ObjectForArch::getAsObjectFile () const
Definition at line 71 of file MachOUniversal.cpp.
References llvm::object::ObjectFile::createMachOObjectFile(), llvm::object::parse_failed, and llvm::StringRef::substr().
uint32_t llvm::object::MachOUniversalBinary::ObjectForArch::getCPUSubType () const [inline]
Definition at line 55 of file MachOUniversal.h.
References llvm::MachO::fat_arch::cpusubtype.
uint32_t llvm::object::MachOUniversalBinary::ObjectForArch::getCPUType () const [inline]
Definition at line 54 of file MachOUniversal.h.
References llvm::MachO::fat_arch::cputype.
ObjectForArch llvm::object::MachOUniversalBinary::ObjectForArch::getNext () const [inline]
Definition at line 53 of file MachOUniversal.h.
References ObjectForArch().
Referenced by llvm::object::MachOUniversalBinary::object_iterator::operator++().
uint32_t llvm::object::MachOUniversalBinary::ObjectForArch::getOffset () const [inline]
Definition at line 56 of file MachOUniversal.h.
References llvm::MachO::fat_arch::offset.
uint32_t llvm::object::MachOUniversalBinary::ObjectForArch::getSize () const [inline]
Definition at line 57 of file MachOUniversal.h.
References llvm::MachO::fat_arch::size.
bool llvm::object::MachOUniversalBinary::ObjectForArch::operator== (const ObjectForArch & Other) const [inline]
Definition at line 49 of file MachOUniversal.h.
The documentation for this class was generated from the following files:
MachOUniversal.h
MachOUniversal.cpp