LLVM: llvm::DITypeRefArray Class Reference
llvm::DITypeRefArray Class Reference
#include <DebugInfoMetadata.h>
Classes
class iterator
Public Member Functions
DITypeRefArray (const MDTuple *N)
operator bool () const
operator MDTuple * () const
MDTuple * get () const
MDTuple * operator-> () const
MDTuple & operator* () const
unsigned size () const
DITypeRef operator[] (unsigned I) const
iterator begin () const
iterator end () const
Detailed Description
Definition at line 96 of file DebugInfoMetadata.h.
Constructor & Destructor Documentation
llvm::DITypeRefArray::DITypeRefArray (const MDTuple * N) [inline]
Definition at line 100 of file DebugInfoMetadata.h.
Member Function Documentation
iterator llvm::DITypeRefArray::begin () const [inline]
Definition at line 135 of file DebugInfoMetadata.h.
References llvm::MDNode::op_begin().
iterator llvm::DITypeRefArray::end () const [inline]
Definition at line 136 of file DebugInfoMetadata.h.
References llvm::MDNode::op_end().
MDTuple* llvm::DITypeRefArray::get () const [inline]
Definition at line 105 of file DebugInfoMetadata.h.
Referenced by WriteDISubroutineType().
llvm::DITypeRefArray::operator bool () const [inline, explicit]
Definition at line 102 of file DebugInfoMetadata.h.
llvm::DITypeRefArray::operator MDTuple * () const [inline, explicit]
Definition at line 103 of file DebugInfoMetadata.h.
MDTuple& llvm::DITypeRefArray::operator* () const [inline]
Definition at line 107 of file DebugInfoMetadata.h.
MDTuple* llvm::DITypeRefArray::operator-> () const [inline]
Definition at line 106 of file DebugInfoMetadata.h.
DITypeRef llvm::DITypeRefArray::operator[] (unsigned I) const [inline]
Definition at line 111 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
unsigned llvm::DITypeRefArray::size () const [inline]
Definition at line 110 of file DebugInfoMetadata.h.
References llvm::MDNode::getNumOperands().
Referenced by llvm::DwarfUnit::constructSubprogramArguments(), and llvm::DwarfCompileUnit::constructSubprogramScopeDIE().
The documentation for this class was generated from the following file:
DebugInfoMetadata.h