LLVM: llvm::HexagonTargetLowering Class Reference
llvm::HexagonTargetLowering Class Reference
#include <HexagonISelLowering.h>
Public Member Functions
HexagonTargetLowering (const TargetMachine &TM, const HexagonSubtarget &ST)
bool IsEligibleForTailCallOptimization (SDValue Callee, CallingConv::ID CalleeCC, bool isVarArg, bool isCalleeStructRet, bool isCallerStructRet, const SmallVectorImpl< ISD::OutputArg > &Outs, const SmallVectorImpl< SDValue > &OutVals, const SmallVectorImpl< ISD::InputArg > &Ins, SelectionDAG &DAG) const
IsEligibleForTailCallOptimization - Check whether the call is eligible for tail call optimization.
bool isTruncateFree (Type *Ty1, Type *Ty2) const override
Return true if it's free to truncate a value of type Ty1 to type Ty2.
bool isTruncateFree (EVT VT1, EVT VT2) const override
bool allowTruncateForTailCall (Type *Ty1, Type *Ty2) const override
Return true if a truncation from Ty1 to Ty2 is permitted when deciding whether a call is in tail position.
bool shouldExpandBuildVectorWithShuffles (EVT VT, unsigned DefinedValues) const override
SDValue LowerOperation (SDValue Op, SelectionDAG &DAG) const override
This callback is invoked for operations that are unsupported by the target, which are registered to use 'custom' lowering, and whose defined values are all legal.
const char * getTargetNodeName (unsigned Opcode) const override
This method returns the name of a target specific DAG node.
SDValue LowerCONCAT_VECTORS (SDValue Op, SelectionDAG &DAG) const
SDValue LowerEXTRACT_VECTOR (SDValue Op, SelectionDAG &DAG) const
SDValue LowerINSERT_VECTOR (SDValue Op, SelectionDAG &DAG) const
SDValue LowerBUILD_VECTOR (SDValue Op, SelectionDAG &DAG) const
SDValue LowerBR_JT (SDValue Op, SelectionDAG &DAG) const
SDValue LowerDYNAMIC_STACKALLOC (SDValue Op, SelectionDAG &DAG) const
SDValue LowerINLINEASM (SDValue Op, SelectionDAG &DAG) const
SDValue LowerEH_LABEL (SDValue Op, SelectionDAG &DAG) const
SDValue LowerEH_RETURN (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFormalArguments (SDValue Chain, CallingConv::ID CallConv, bool isVarArg, const SmallVectorImpl< ISD::InputArg > &Ins, SDLoc dl, SelectionDAG &DAG, SmallVectorImpl< SDValue > &InVals) const override
This hook must be implemented to lower the incoming (formal) arguments, described by the Ins array, into the specified DAG.
SDValue LowerGLOBALADDRESS (SDValue Op, SelectionDAG &DAG) const
SDValue LowerBlockAddress (SDValue Op, SelectionDAG &DAG) const
SDValue LowerCall (TargetLowering::CallLoweringInfo &CLI, SmallVectorImpl< SDValue > &InVals) const override
LowerCall - Functions arguments are copied from virtual regs to (physical regs)/(stack frame), CALLSEQ_START and CALLSEQ_END are emitted.
SDValue LowerCallResult (SDValue Chain, SDValue InFlag, CallingConv::ID CallConv, bool isVarArg, const SmallVectorImpl< ISD::InputArg > &Ins, SDLoc dl, SelectionDAG &DAG, SmallVectorImpl< SDValue > &InVals, const SmallVectorImpl< SDValue > &OutVals, SDValue Callee) const
LowerCallResult - Lower the result values of an ISD::CALL into the appropriate copies out of appropriate physical registers.
SDValue LowerSETCC (SDValue Op, SelectionDAG &DAG) const
SDValue LowerVSELECT (SDValue Op, SelectionDAG &DAG) const
SDValue LowerCTPOP (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFRAMEADDR (SDValue Op, SelectionDAG &DAG) const
SDValue LowerATOMIC_FENCE (SDValue Op, SelectionDAG &DAG) const
SDValue LowerRETURNADDR (SDValue Op, SelectionDAG &DAG) const
SDValue LowerLOAD (SDValue Op, SelectionDAG &DAG) const
SDValue LowerReturn (SDValue Chain, CallingConv::ID CallConv, bool isVarArg, const SmallVectorImpl< ISD::OutputArg > &Outs, const SmallVectorImpl< SDValue > &OutVals, SDLoc dl, SelectionDAG &DAG) const override
This hook must be implemented to lower outgoing return values, described by the Outs array, into the specified DAG.
bool mayBeEmittedAsTailCall (CallInst *CI) const override
Return true if the target may be able emit the call instruction as a tail call.
MachineBasicBlock * EmitInstrWithCustomInserter (MachineInstr *MI, MachineBasicBlock *BB) const override
This method should be implemented by targets that mark instructions with the 'usesCustomInserter' flag.
SDValue LowerVASTART (SDValue Op, SelectionDAG &DAG) const
SDValue LowerConstantPool (SDValue Op, SelectionDAG &DAG) const
EVT getSetCCResultType (LLVMContext &C, EVT VT) const override
Return the ValueType of the result of SETCC operations.
bool getPostIndexedAddressParts (SDNode *N, SDNode *Op, SDValue &Base, SDValue &Offset, ISD::MemIndexedMode &AM, SelectionDAG &DAG) const override
getPostIndexedAddressParts - returns true by value, base pointer and offset pointer and addressing mode by reference if this node can be combined with a load / store to form a post-indexed load / store.
std::pair< unsigned, const
TargetRegisterClass * > getRegForInlineAsmConstraint (const TargetRegisterInfo *TRI, const std::string &Constraint, MVT VT) const override
Given a physical register constraint (e.g.
unsigned getInlineAsmMemConstraint (const std::string &ConstraintCode) const override
SDValue LowerINTRINSIC_WO_CHAIN (SDValue Op, SelectionDAG &DAG) const
bool isLegalAddressingMode (const AddrMode &AM, Type *Ty, unsigned AS) const override
isLegalAddressingMode - Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
bool isFPImmLegal (const APFloat &Imm, EVT VT) const override
isFPImmLegal - Returns true if the target can instruction select the specified FP immediate natively.
bool isLegalICmpImmediate (int64_t Imm) const override
isLegalICmpImmediate - Return true if the specified immediate is legal icmp immediate, that is the target has icmp instructions which can compare a register against the immediate without having to materialize the immediate into a register.
Detailed Description
Definition at line 93 of file HexagonISelLowering.h.
Constructor & Destructor Documentation
HexagonTargetLowering::HexagonTargetLowering (const TargetMachine & TM, const HexagonSubtarget & ST) [explicit]
Definition at line 1271 of file HexagonISelLowering.cpp.
References llvm::ISD::ADD, ADD, llvm::RTLIB::ADD_F32, llvm::RTLIB::ADD_F64, llvm::ISD::ADDC, llvm::ISD::ADDE, llvm::TargetLoweringBase::AddPromotedToType(), llvm::TargetLoweringBase::addRegisterClass(), llvm::ISD::AND, AND, llvm::ISD::ATOMIC_FENCE, llvm::ISD::BlockAddress, llvm::ISD::BR_CC, llvm::ISD::BR_JT, llvm::ISD::BSWAP, llvm::ISD::BUILD_PAIR, llvm::ISD::BUILD_VECTOR, llvm::TargetLoweringBase::computeRegisterProperties(), llvm::ISD::CONCAT_VECTORS, llvm::ISD::ConstantFP, llvm::ISD::ConstantPool, llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::TargetLoweringBase::Custom, llvm::RTLIB::DIV_F32, llvm::RTLIB::DIV_F64, llvm::ISD::DYNAMIC_STACKALLOC, llvm::ISD::EH_RETURN, EmitJumpTables, EnableFastMath, EnableHexSDNodeSched, llvm::TargetLoweringBase::Expand, llvm::ISD::EXTLOAD, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FABS, llvm::ISD::FADD, llvm::ISD::FCEIL, llvm::ISD::FCOPYSIGN, llvm::ISD::FCOS, llvm::ISD::FDIV, llvm::ISD::FEXP, llvm::ISD::FEXP2, llvm::ISD::FFLOOR, llvm::ISD::FLOG, llvm::ISD::FLOG10, llvm::ISD::FLOG2, llvm::ISD::FMA, llvm::ISD::FMAXNUM, llvm::ISD::FMINNUM, llvm::ISD::FMUL, llvm::ISD::FNEARBYINT, llvm::ISD::FNEG, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::MVT::fp_valuetypes(), llvm::RTLIB::FPEXT_F32_F64, llvm::ISD::FPOW, llvm::ISD::FPOWI, llvm::RTLIB::FPROUND_F64_F32, llvm::RTLIB::FPTOSINT_F32_I128, llvm::RTLIB::FPTOSINT_F32_I32, llvm::RTLIB::FPTOSINT_F32_I64, llvm::RTLIB::FPTOSINT_F64_I128, llvm::RTLIB::FPTOSINT_F64_I32, llvm::RTLIB::FPTOSINT_F64_I64, llvm::RTLIB::FPTOUINT_F32_I128, llvm::RTLIB::FPTOUINT_F32_I32, llvm::RTLIB::FPTOUINT_F32_I64, llvm::RTLIB::FPTOUINT_F64_I128, llvm::RTLIB::FPTOUINT_F64_I32, llvm::RTLIB::FPTOUINT_F64_I64, llvm::ISD::FREM, llvm::ISD::FRINT, llvm::ISD::FROUND, llvm::ISD::FSIN, llvm::ISD::FSINCOS, llvm::ISD::FSQRT, llvm::ISD::FSUB, llvm::ISD::FTRUNC, llvm::HexagonSubtarget::getRegisterInfo(), llvm::ISD::GlobalAddress, llvm::HexagonSubtarget::hasV5TOps(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::ISD::INLINEASM, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::MVT::integer_valuetypes(), llvm::TargetLoweringBase::Legal, llvm::ISD::LOAD, llvm::TargetLoweringBase::MaxStoresPerMemcpy, MaxStoresPerMemcpyCL, llvm::TargetLoweringBase::MaxStoresPerMemcpyOptSize, MaxStoresPerMemcpyOptSizeCL, llvm::TargetLoweringBase::MaxStoresPerMemmove, MaxStoresPerMemmoveCL, llvm::TargetLoweringBase::MaxStoresPerMemmoveOptSize, MaxStoresPerMemmoveOptSizeCL, llvm::TargetLoweringBase::MaxStoresPerMemset, MaxStoresPerMemsetCL, llvm::TargetLoweringBase::MaxStoresPerMemsetOptSize, MaxStoresPerMemsetOptSizeCL, MinimumJumpTables, llvm::ISD::MUL, llvm::RTLIB::MUL_F32, llvm::RTLIB::MUL_F64, llvm::ISD::MULHS, llvm::RTLIB::O_F32, llvm::RTLIB::O_F64, llvm::RTLIB::OEQ_F32, llvm::RTLIB::OEQ_F64, llvm::RTLIB::OGE_F32, llvm::RTLIB::OGE_F64, llvm::RTLIB::OGT_F32, llvm::RTLIB::OGT_F64, llvm::RTLIB::OLE_F32, llvm::RTLIB::OLE_F64, llvm::RTLIB::OLT_F32, llvm::RTLIB::OLT_F64, llvm::ISD::OR, OR, llvm::MVT::Other, llvm::ISD::POST_INC, llvm::TargetLoweringBase::Promote, llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SADDO, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SDIV, llvm::RTLIB::SDIV_I32, llvm::RTLIB::SDIV_I64, llvm::ISD::SDIVREM, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::TargetLoweringBase::setCondCodeAction(), llvm::TargetLoweringBase::setExceptionPointerRegister(), llvm::TargetLoweringBase::setExceptionSelectorRegister(), llvm::TargetLoweringBase::setIndexedLoadAction(), llvm::TargetLoweringBase::setIndexedStoreAction(), llvm::TargetLoweringBase::setInsertFencesForAtomic(), llvm::TargetLoweringBase::setLibcallName(), llvm::TargetLoweringBase::setLoadExtAction(), llvm::TargetLoweringBase::setMinFunctionAlignment(), llvm::TargetLoweringBase::setMinimumJumpTableEntries(), llvm::ISD::SETO, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::TargetLoweringBase::setOperationAction(), llvm::TargetLoweringBase::setPrefFunctionAlignment(), llvm::TargetLoweringBase::setPrefLoopAlignment(), llvm::TargetLoweringBase::setSchedulingPreference(), llvm::TargetLoweringBase::setStackPointerRegisterToSaveRestore(), llvm::TargetLoweringBase::setTruncStoreAction(), llvm::ISD::SETUNE, llvm::ISD::SETUO, llvm::ISD::SEXTLOAD, llvm::ISD::SHL, llvm::RTLIB::SHL_I128, llvm::ISD::SHL_PARTS, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SINT_TO_FP, llvm::RTLIB::SINTTOFP_I128_F32, llvm::RTLIB::SINTTOFP_I128_F64, llvm::RTLIB::SINTTOFP_I32_F32, llvm::RTLIB::SINTTOFP_I32_F64, llvm::RTLIB::SINTTOFP_I64_F32, llvm::RTLIB::SINTTOFP_I64_F64, llvm::ISD::SMUL_LOHI, llvm::Sched::Source, llvm::RTLIB::SQRT_F32, llvm::RTLIB::SQRT_F64, llvm::ISD::SRA, llvm::RTLIB::SRA_I128, llvm::ISD::SRA_PARTS, llvm::ISD::SREM, llvm::RTLIB::SREM_I32, llvm::RTLIB::SREM_I64, llvm::ISD::SRL, llvm::RTLIB::SRL_I128, llvm::ISD::SRL_PARTS, llvm::ISD::SSUBO, llvm::ISD::STACKRESTORE, llvm::ISD::STACKSAVE, llvm::ISD::STORE, llvm::ISD::SUB, SUB, llvm::RTLIB::SUB_F32, llvm::RTLIB::SUB_F64, llvm::ISD::SUBC, llvm::ISD::SUBE, llvm::ISD::UADDO, llvm::ISD::UDIV, llvm::RTLIB::UDIV_I32, llvm::RTLIB::UDIV_I64, llvm::ISD::UDIVREM, llvm::ISD::UINT_TO_FP, llvm::RTLIB::UINTTOFP_I32_F32, llvm::RTLIB::UINTTOFP_I32_F64, llvm::RTLIB::UINTTOFP_I64_F32, llvm::RTLIB::UINTTOFP_I64_F64, llvm::ISD::UMUL_LOHI, llvm::RTLIB::UNE_F32, llvm::RTLIB::UNE_F64, llvm::RTLIB::UO_F32, llvm::RTLIB::UO_F64, llvm::ISD::UREM, llvm::RTLIB::UREM_I32, llvm::RTLIB::UREM_I64, llvm::ISD::USUBO, llvm::MVT::v1i32, llvm::MVT::v1i64, llvm::MVT::v2i1, llvm::MVT::v2i16, llvm::MVT::v2i32, llvm::MVT::v32i1, llvm::MVT::v4i1, llvm::MVT::v4i16, llvm::MVT::v4i8, llvm::MVT::v64i1, llvm::MVT::v8i1, llvm::MVT::v8i8, llvm::ISD::VAARG, llvm::ISD::VAEND, llvm::ISD::VASTART, llvm::ISD::VECTOR_SHUFFLE, llvm::MVT::vector_valuetypes(), llvm::Sched::VLIW, llvm::ISD::VSELECT, llvm::ISD::XOR, XOR, and llvm::ISD::ZEXTLOAD.
Member Function Documentation
bool HexagonTargetLowering::allowTruncateForTailCall (Type * , Type *) const [override, virtual]
Return true if a truncation from Ty1 to Ty2 is permitted when deciding whether a call is in tail position.
Typically this means that both results would be assigned to the same register or stack slot, but it could mean the target performs adequate checks of its own before proceeding with the tail call.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 2239 of file HexagonISelLowering.cpp.
References llvm::Type::getPrimitiveSizeInBits(), and llvm::Type::isIntegerTy().
MachineBasicBlock * HexagonTargetLowering::EmitInstrWithCustomInserter (MachineInstr * MI, MachineBasicBlock * MBB) const [override, virtual]
This method should be implemented by targets that mark instructions with the 'usesCustomInserter' flag.
These instructions are special in various ways, which require special support to insert. The specified MachineInstr is created but not inserted into any basic blocks, and this method is called to expand it into a sequence of instructions, potentially also creating new basic blocks and control flow. As long as the returned basic block is different (i.e., we created a new one), the custom inserter is free to modify the rest of MBB.
Reimplemented from llvm::TargetLowering.
Definition at line 2321 of file HexagonISelLowering.cpp.
References llvm::HexagonMachineFunctionInfo::addAllocaAdjustInst(), llvm::HexagonISD::ALLOCA, llvm::MachineFunction::getInfo(), llvm::MachineInstr::getOpcode(), llvm::MachineBasicBlock::getParent(), and llvm_unreachable.
unsigned llvm::HexagonTargetLowering::getInlineAsmMemConstraint (const std::string & ConstraintCode) const [inline, override, virtual]
Reimplemented from llvm::TargetLowering.
Definition at line 185 of file HexagonISelLowering.h.
References llvm::InlineAsm::Constraint_o, and llvm::InlineAsm::Constraint_v.
bool HexagonTargetLowering::getPostIndexedAddressParts (SDNode * N, SDNode * Op, SDValue & Base, SDValue & Offset, ISD::MemIndexedMode & AM, SelectionDAG & DAG) const [override, virtual]
getPostIndexedAddressParts - returns true by value, base pointer and offset pointer and addressing mode by reference if this node can be combined with a load / store to form a post-indexed load / store.
Reimplemented from llvm::TargetLowering.
Definition at line 701 of file HexagonISelLowering.cpp.
References getIndexedAddressParts(), llvm::SDValue::getNode(), llvm::EVT::getSizeInBits(), llvm::MVT::i64, Is_PostInc_S4_Offset(), llvm::ISD::isSEXTLoad(), llvm::AArch64DB::LD, llvm::ISD::POST_DEC, llvm::ISD::POST_INC, llvm::ISD::SEXTLOAD, and llvm::AArch64DB::ST.
std::pair< unsigned, const TargetRegisterClass * > HexagonTargetLowering::getRegForInlineAsmConstraint (const TargetRegisterInfo * TRI, const std::string & Constraint, MVT VT) const [override, virtual]
Given a physical register constraint (e.g.
{edx}), return the register number and the register class for the register.
Given a register class constraint, like 'r', if this corresponds directly to an LLVM register class, return a register of 0 and the register class pointer.
This should only be used for C_Register constraints. On error, this returns a register number of 0 and a null register class pointer.
Reimplemented from llvm::TargetLowering.
Definition at line 2340 of file HexagonISelLowering.cpp.
References llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm_unreachable, and llvm::MVT::SimpleTy.
EVT llvm::HexagonTargetLowering::getSetCCResultType (LLVMContext & Context, EVT VT) const [inline, override, virtual]
Return the ValueType of the result of SETCC operations.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 168 of file HexagonISelLowering.h.
References llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::MVT::i1, and llvm::EVT::isVector().
const char * HexagonTargetLowering::getTargetNodeName (unsigned Opcode) const [override, virtual]
This method returns the name of a target specific DAG node.
Reimplemented from llvm::TargetLowering.
Definition at line 1713 of file HexagonISelLowering.cpp.
References llvm::HexagonISD::ALLOCA, llvm::HexagonISD::ARGEXTEND, llvm::HexagonISD::AT_GOT, llvm::HexagonISD::AT_PCREL, llvm::HexagonISD::BARRIER, llvm::HexagonISD::BR_JT, llvm::HexagonISD::CALLR, llvm::HexagonISD::CALLv3, llvm::HexagonISD::CALLv3nr, llvm::HexagonISD::COMBINE, llvm::HexagonISD::CONST32, llvm::HexagonISD::CONST32_GP, llvm::HexagonISD::CP, llvm::HexagonISD::DCFETCH, llvm::HexagonISD::EH_RETURN, llvm::HexagonISD::EXTRACTU, llvm::HexagonISD::EXTRACTURP, llvm::HexagonISD::FCONST32, llvm::HexagonISD::INSERT, llvm::HexagonISD::INSERTRP, llvm::HexagonISD::JT, llvm::HexagonISD::OP_END, llvm::HexagonISD::PACKHL, llvm::HexagonISD::PIC_ADD, llvm::HexagonISD::POPCOUNT, llvm::HexagonISD::RET_FLAG, llvm::HexagonISD::SHUFFEB, llvm::HexagonISD::SHUFFEH, llvm::HexagonISD::SHUFFOB, llvm::HexagonISD::SHUFFOH, llvm::HexagonISD::TC_RETURN, llvm::HexagonISD::VCMPBEQ, llvm::HexagonISD::VCMPBGT, llvm::HexagonISD::VCMPBGTU, llvm::HexagonISD::VCMPHEQ, llvm::HexagonISD::VCMPHGT, llvm::HexagonISD::VCMPHGTU, llvm::HexagonISD::VCMPWEQ, llvm::HexagonISD::VCMPWGT, llvm::HexagonISD::VCMPWGTU, llvm::HexagonISD::VSHLH, llvm::HexagonISD::VSHLW, llvm::HexagonISD::VSPLATB, llvm::HexagonISD::VSPLATH, llvm::HexagonISD::VSRAH, llvm::HexagonISD::VSRAW, llvm::HexagonISD::VSRLH, llvm::HexagonISD::VSRLW, llvm::HexagonISD::VSXTBH, and llvm::HexagonISD::VSXTBW.
bool HexagonTargetLowering::IsEligibleForTailCallOptimization (SDValue Callee, CallingConv::ID CalleeCC, bool isVarArg, bool isCalleeStructRet, bool isCallerStructRet, const SmallVectorImpl< ISD::OutputArg > & Outs, const SmallVectorImpl< SDValue > & OutVals, const SmallVectorImpl< ISD::InputArg > & Ins, SelectionDAG & DAG) const
IsEligibleForTailCallOptimization - Check whether the call is eligible for tail call optimization.
Targets which want to do tail call optimization should implement this function.
Definition at line 2408 of file HexagonISelLowering.cpp.
References llvm::Function::getCallingConv(), llvm::MachineFunction::getFunction(), and llvm::SelectionDAG::getMachineFunction().
Referenced by LowerCall().
bool HexagonTargetLowering::isFPImmLegal (const APFloat & Imm, EVT VT) const [override, virtual]
isFPImmLegal - Returns true if the target can instruction select the specified FP immediate natively.
If false, the legalizer will materialize the FP immediate as a load from a constant pool.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 2369 of file HexagonISelLowering.cpp.
References llvm::HexagonSubtarget::hasV5TOps().
bool HexagonTargetLowering::isLegalAddressingMode (const AddrMode & AM, Type * Ty, unsigned AS) const [override, virtual]
isLegalAddressingMode - Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
The type may be VoidTy, in which case only return true if the addressing mode is legal for a load/store of any legal type. TODO: Handle pre/postinc as well.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 2375 of file HexagonISelLowering.cpp.
References llvm::TargetLoweringBase::AddrMode::BaseGV, llvm::TargetLoweringBase::AddrMode::BaseOffs, and llvm::TargetLoweringBase::AddrMode::Scale.
bool HexagonTargetLowering::isLegalICmpImmediate (int64_t Imm) const [override, virtual]
isLegalICmpImmediate - Return true if the specified immediate is legal icmp immediate, that is the target has icmp instructions which can compare a register against the immediate without having to materialize the immediate into a register.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 2401 of file HexagonISelLowering.cpp.
bool HexagonTargetLowering::isTruncateFree (Type * , Type *) const [override, virtual]
Return true if it's free to truncate a value of type Ty1 to type Ty2.
e.g. On x86 it's free to truncate a i32 value in register EAX to i16 by referencing its sub-register AX.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1769 of file HexagonISelLowering.cpp.
References llvm::EVT::getEVT(), llvm::EVT::getSimpleVT(), llvm::MVT::i32, llvm::MVT::i64, and llvm::EVT::isSimple().
bool HexagonTargetLowering::isTruncateFree (EVT VT1, EVT VT2) const [override, virtual]
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1777 of file HexagonISelLowering.cpp.
References llvm::EVT::getSimpleVT(), llvm::MVT::i32, llvm::MVT::i64, and llvm::EVT::isSimple().
SDValue HexagonTargetLowering::LowerATOMIC_FENCE (SDValue Op, SelectionDAG & DAG) const
Definition at line 1221 of file HexagonISelLowering.cpp.
References llvm::HexagonISD::BARRIER, llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), and llvm::MVT::Other.
Referenced by LowerOperation().
SDValue HexagonTargetLowering::LowerBlockAddress (SDValue Op, SelectionDAG & DAG) const
Definition at line 1260 of file HexagonISelLowering.cpp.
References llvm::HexagonISD::CONST32_GP, llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getTargetBlockAddress(), and llvm::MVT::i32.
Referenced by LowerOperation().
SDValue HexagonTargetLowering::LowerBR_JT (SDValue Op, SelectionDAG & DAG) const
Definition at line 791 of file HexagonISelLowering.cpp.
References llvm::ISD::ADD, llvm::HexagonISD::BR_JT, llvm::BlockAddress::get(), llvm::MachineBasicBlock::getBasicBlock(), llvm::SelectionDAG::getConstant(), llvm::JumpTableSDNode::getIndex(), llvm::MachineFunction::getJumpTableInfo(), llvm::MachineJumpTableInfo::getJumpTables(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getTargetJumpTable(), llvm::MVT::i32, llvm::HexagonISD::JT, llvm::MVT::Other, llvm::MachineBasicBlock::setHasAddressTaken(), and llvm::ISD::SHL.
Referenced by LowerOperation().
SDValue HexagonTargetLowering::LowerBUILD_VECTOR (SDValue Op, SelectionDAG & DAG) const
Definition at line 1916 of file HexagonISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::C, llvm::HexagonISD::COMBINE, createSplat(), llvm::dyn_cast(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::ConstantSDNode::getSExtValue(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetExtractSubreg(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::APInt::getZExtValue(), llvm::MVT::i32, llvm::MVT::i64, llvm::HexagonISD::INSERTRP, llvm::BuildVectorSDNode::isConstantSplat(), llvm::isInt< 8 >(), llvm::ISD::MUL, llvm::ISD::OR, llvm::HexagonISD::PACKHL, llvm::ISD::SHL, llvm::ISD::UNDEF, llvm::MVT::v2i16, llvm::MVT::v2i32, llvm::MVT::v4i16, and llvm::MVT::v4i8.
Referenced by LowerOperation().
SDValue HexagonTargetLowering::LowerCall (TargetLowering::CallLoweringInfo & CLI, SmallVectorImpl< SDValue > & InVals) const [override, virtual]
LowerCall - Functions arguments are copied from virtual regs to (physical regs)/(stack frame), CALLSEQ_START and CALLSEQ_END are emitted.
Reimplemented from llvm::TargetLowering.
Definition at line 446 of file HexagonISelLowering.cpp.
References llvm::ISD::ADD, llvm::CCValAssign::AExt, llvm::ISD::ANY_EXTEND, llvm::CCValAssign::BCvt, llvm::C, llvm::TargetLowering::CallLoweringInfo::CallConv, llvm::TargetLowering::CallLoweringInfo::Callee, llvm::HexagonISD::CALLv3, llvm::HexagonISD::CALLv3nr, CC_Hexagon(), CC_Hexagon_VarArg(), llvm::TargetLowering::CallLoweringInfo::Chain, CreateCopyOfByValArgument(), llvm::TargetLowering::CallLoweringInfo::DAG, llvm::dbgs(), DEBUG, llvm::TargetLowering::CallLoweringInfo::DL, llvm::TargetLowering::CallLoweringInfo::DoesNotReturn, llvm::SmallVectorBase::empty(), llvm::flag_aligned_memcpy, llvm::CCValAssign::Full, G, llvm::SelectionDAG::getCALLSEQ_END(), llvm::SelectionDAG::getCALLSEQ_START(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::Function::getFnAttribute(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::Function::getFunctionType(), llvm::SelectionDAG::getIntPtrConstant(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::FunctionType::getNumParams(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::HexagonSubtarget::getRegisterInfo(), llvm::MachinePointerInfo::getStack(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTargetExternalSymbol(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, llvm::Function::hasStructRetAttr(), llvm::MVT::i32, llvm::MipsISD::Ins, llvm::TargetLowering::CallLoweringInfo::Ins, llvm::ISD::ArgFlagsTy::isByVal(), IsEligibleForTailCallOptimization(), llvm::CCValAssign::isMemLoc(), llvm::CCValAssign::isRegLoc(), llvm::TargetLowering::CallLoweringInfo::IsTailCall, llvm::Function::isVarArg(), llvm::TargetLowering::CallLoweringInfo::IsVarArg, llvm_unreachable, LowerCallResult(), llvm::MVT::Other, llvm::TargetLowering::CallLoweringInfo::Outs, llvm::TargetLowering::CallLoweringInfo::OutVals, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::MachineFrameInfo::setHasTailCall(), llvm::CCValAssign::SExt, llvm::ISD::SIGN_EXTEND, llvm::SmallVectorTemplateCommon< T >::size(), llvm::HexagonISD::TC_RETURN, llvm::ISD::TokenFactor, llvm::ISD::ZERO_EXTEND, and llvm::CCValAssign::ZExt.
SDValue HexagonTargetLowering::LowerCallResult (SDValue Chain, SDValue InFlag, CallingConv::ID CallConv, bool isVarArg, const SmallVectorImpl< ISD::InputArg > & Ins, SDLoc dl, SelectionDAG & DAG, SmallVectorImpl< SDValue > & InVals, const SmallVectorImpl< SDValue > & OutVals, SDValue Callee) const
LowerCallResult - Lower the result values of an ISD::CALL into the appropriate copies out of appropriate physical registers.
This assumes that Chain/InFlag are the input chain/flag to use, and that TheCall is the call being lowered. Returns a SDNode with the same number of values as the ISD::CALL.
Definition at line 414 of file HexagonISelLowering.cpp.
References llvm::CCState::AnalyzeCallResult(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getValue(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), RetCC_Hexagon(), and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by LowerCall().
SDValue HexagonTargetLowering::LowerCONCAT_VECTORS (SDValue Op, SelectionDAG & DAG) const
Definition at line 2055 of file HexagonISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::C, llvm::HexagonISD::COMBINE, llvm::dyn_cast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOperand(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::ConstantSDNode::getZExtValue(), llvm::MVT::i32, llvm::MVT::i64, llvm::HexagonISD::INSERTRP, llvm::ISD::MUL, llvm::ISD::OR, llvm::ISD::SHL, llvm::MVT::v2i16, and llvm::MVT::v4i8.
Referenced by LowerOperation().
SDValue HexagonTargetLowering::LowerConstantPool (SDValue Op, SelectionDAG & DAG) const
Definition at line 1163 of file HexagonISelLowering.cpp.
References llvm::HexagonISD::CP, llvm::ConstantPoolSDNode::getAlignment(), llvm::ConstantPoolSDNode::getConstVal(), llvm::ConstantPoolSDNode::getMachineCPVal(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetConstantPool(), llvm::SDValue::getValueType(), and llvm::ConstantPoolSDNode::isMachineConstantPoolEntry().
Referenced by LowerOperation().
SDValue HexagonTargetLowering::LowerCTPOP (SDValue Op, SelectionDAG & DAG) const
Definition at line 998 of file HexagonISelLowering.cpp.
References llvm::countPopulation(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getTargetConstant(), llvm::MVT::i32, llvm::MVT::i64, llvm::HexagonISD::POPCOUNT, and llvm::ISD::ZERO_EXTEND.
Referenced by LowerOperation().
SDValue HexagonTargetLowering::LowerDYNAMIC_STACKALLOC (SDValue Op, SelectionDAG & DAG) const
Definition at line 828 of file HexagonISelLowering.cpp.
References llvm::ARM_PROC::A, Align(), llvm::HexagonISD::ALLOCA, llvm::dbgs(), DEBUG, llvm::SDNode::dump(), llvm::dyn_cast(), llvm::SelectionDAG::getConstant(), llvm::HexagonSubtarget::getFrameLowering(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::ConstantSDNode::getSExtValue(), llvm::SelectionDAG::getVTList(), llvm::MVT::i32, LLVM_FUNCTION_NAME, and llvm::MVT::Other.
Referenced by LowerOperation().
SDValue llvm::HexagonTargetLowering::LowerEH_LABEL (SDValue Op, SelectionDAG & DAG) const
SDValue HexagonTargetLowering::LowerEH_RETURN (SDValue Op, SelectionDAG & DAG) const
Definition at line 2252 of file HexagonISelLowering.cpp.
References llvm::ISD::ADD, llvm::HexagonISD::EH_RETURN, llvm::SelectionDAG::getCopyToReg(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::SelectionDAG::getStore(), llvm::MVT::Other, and llvm::HexagonMachineFunctionInfo::setHasEHReturn().
Referenced by LowerOperation().
SDValue HexagonTargetLowering::LowerEXTRACT_VECTOR (SDValue Op, SelectionDAG & DAG) const
Definition at line 2113 of file HexagonISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::dyn_cast(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::HexagonISD::EXTRACTU, llvm::HexagonISD::EXTRACTURP, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetExtractSubreg(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::ConstantSDNode::getZExtValue(), llvm::MVT::i32, llvm::MVT::i64, llvm::EVT::isVector(), llvm_unreachable, llvm::ISD::MUL, N, llvm::ISD::OR, llvm::ISD::SHL, llvm::MVT::v2i32, llvm::MVT::v4i16, llvm::MVT::v8i8, and X.
Referenced by LowerOperation().
SDValue HexagonTargetLowering::LowerFormalArguments (SDValue , CallingConv::ID , bool , const SmallVectorImpl< ISD::InputArg > & , SDLoc , SelectionDAG & , SmallVectorImpl< SDValue > &) const [override, virtual]
This hook must be implemented to lower the incoming (formal) arguments, described by the Ins array, into the specified DAG.
The implementation should fill in the InVals array with legal-type argument values, and return the resulting token chain value.
Reimplemented from llvm::TargetLowering.
Definition at line 856 of file HexagonISelLowering.cpp.
References llvm::MachineRegisterInfo::addLiveIn(), llvm::CCState::AnalyzeFormalArguments(), CC_Hexagon(), llvm::MachineFrameInfo::CreateFixedObject(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::SmallVectorBase::empty(), llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FrameIndex, llvm::ISD::ArgFlagsTy::getByValSize(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getLoad(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::MachineFunction::getRegInfo(), llvm::MVT::getStoreSizeInBits(), HEXAGON_LRFP_SIZE, Hexagon_PointerSize, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::ISD::ArgFlagsTy::isByVal(), llvm::CCValAssign::isMemLoc(), llvm::CCValAssign::isRegLoc(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::ISD::TokenFactor.
SDValue HexagonTargetLowering::LowerFRAMEADDR (SDValue Op, SelectionDAG & DAG) const
Definition at line 1204 of file HexagonISelLowering.cpp.
References llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getEntryNode(), llvm::MachineFunction::getFrameInfo(), llvm::HexagonRegisterInfo::getFrameRegister(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getOperand(), llvm::HexagonSubtarget::getRegisterInfo(), llvm::SDValue::getValueType(), and llvm::MachineFrameInfo::setFrameAddressIsTaken().
Referenced by LowerOperation(), and LowerRETURNADDR().
SDValue HexagonTargetLowering::LowerGLOBALADDRESS (SDValue Op, SelectionDAG & DAG) const
Definition at line 1228 of file HexagonISelLowering.cpp.
References llvm::HexagonISD::CONST32, llvm::HexagonISD::CONST32_GP, llvm::SelectionDAG::getNode(), llvm::TargetMachine::getObjFileLowering(), llvm::getOffset(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::TargetLoweringBase::getTargetMachine(), and llvm::HexagonTargetObjectFile::IsGlobalInSmallSection().
Referenced by LowerOperation().
SDValue HexagonTargetLowering::LowerINLINEASM (SDValue Op, SelectionDAG & DAG) const
Definition at line 736 of file HexagonISelLowering.cpp.
References llvm::MachineFunction::getInfo(), llvm::InlineAsm::getKind(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::InlineAsm::getNumOperandRegisters(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::HexagonRegisterInfo::getRARegister(), getReg(), llvm::HexagonSubtarget::getRegisterInfo(), llvm::SDValue::getValueType(), llvm::MVT::Glue, llvm::ISD::INLINEASM, llvm::InlineAsm::Kind_Clobber, llvm::InlineAsm::Kind_Imm, llvm::InlineAsm::Kind_Mem, llvm::InlineAsm::Kind_RegDef, llvm::InlineAsm::Kind_RegDefEarlyClobber, llvm::InlineAsm::Kind_RegUse, llvm_unreachable, and llvm::InlineAsm::Op_FirstOperand.
Referenced by LowerOperation().
SDValue HexagonTargetLowering::LowerINSERT_VECTOR (SDValue Op, SelectionDAG & DAG) const
Definition at line 2187 of file HexagonISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::C, llvm::HexagonISD::COMBINE, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::MVT::i32, llvm::MVT::i64, llvm::HexagonISD::INSERT, llvm::ISD::INSERT_VECTOR_ELT, llvm::HexagonISD::INSERTRP, llvm::EVT::isVector(), llvm::ISD::MUL, N, llvm::ISD::OR, and llvm::ISD::SHL.
Referenced by LowerOperation().
SDValue HexagonTargetLowering::LowerINTRINSIC_WO_CHAIN (SDValue Op, SelectionDAG & DAG) const
Definition at line 332 of file HexagonISelLowering.cpp.
Referenced by LowerOperation().
SDValue HexagonTargetLowering::LowerLOAD (SDValue Op, SelectionDAG & DAG) const
Definition at line 1077 of file HexagonISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::BITCAST, llvm::HexagonISD::COMBINE, llvm::DL, llvm::MipsISD::Ext, llvm::MemSDNode::getAlignment(), llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::LoadSDNode::getExtensionType(), llvm::SelectionDAG::getExtLoad(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::MemSDNode::getPointerInfo(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MemSDNode::isInvariant(), llvm::MemSDNode::isNonTemporal(), llvm::MemSDNode::isVolatile(), llvm_unreachable, Loads, llvm::ISD::NON_EXTLOAD, llvm::ISD::OR, llvm::MVT::Other, llvm::ISD::SHL, llvm::ISD::TokenFactor, llvm::MVT::v4i16, and llvm::ISD::ZEXTLOAD.
Referenced by LowerOperation().
SDValue HexagonTargetLowering::LowerOperation (SDValue Op, SelectionDAG & DAG) const [override, virtual]
This callback is invoked for operations that are unsupported by the target, which are registered to use 'custom' lowering, and whose defined values are all legal.
If the target has no operations that require custom lowering, it need not implement this. The default implementation of this aborts.
Reimplemented from llvm::TargetLowering.
Definition at line 2279 of file HexagonISelLowering.cpp.
References llvm::ISD::ATOMIC_FENCE, llvm::ISD::BlockAddress, llvm::ISD::BR_JT, llvm::ISD::BUILD_VECTOR, llvm::ISD::CONCAT_VECTORS, llvm::ISD::ConstantPool, llvm::ISD::CTPOP, llvm::SDNode::dumpr(), llvm::ISD::DYNAMIC_STACKALLOC, llvm::ISD::EH_RETURN, llvm::errs(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FRAMEADDR, llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::ISD::GlobalAddress, llvm::ISD::INLINEASM, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::ISD::INTRINSIC_WO_CHAIN, llvm_unreachable, llvm::ISD::LOAD, LowerATOMIC_FENCE(), LowerBlockAddress(), LowerBR_JT(), LowerBUILD_VECTOR(), LowerCONCAT_VECTORS(), LowerConstantPool(), LowerCTPOP(), LowerDYNAMIC_STACKALLOC(), LowerEH_RETURN(), LowerEXTRACT_VECTOR(), LowerFRAMEADDR(), LowerGLOBALADDRESS(), LowerINLINEASM(), LowerINSERT_VECTOR(), LowerINTRINSIC_WO_CHAIN(), LowerLOAD(), LowerRETURNADDR(), LowerSETCC(), LowerVASTART(), LowerVECTOR_SHIFT(), LowerVECTOR_SHUFFLE(), LowerVSELECT(), llvm::HexagonISD::OP_BEGIN, llvm::HexagonISD::OP_END, llvm::ISD::RETURNADDR, llvm::ISD::SETCC, llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::VASTART, llvm::ISD::VECTOR_SHUFFLE, and llvm::ISD::VSELECT.
SDValue HexagonTargetLowering::LowerReturn (SDValue , CallingConv::ID , bool , const SmallVectorImpl< ISD::OutputArg > & , const SmallVectorImpl< SDValue > & , SDLoc , SelectionDAG &) const [override, virtual]
This hook must be implemented to lower outgoing return values, described by the Outs array, into the specified DAG.
The implementation should return the resulting token chain value.
Reimplemented from llvm::TargetLowering.
Definition at line 359 of file HexagonISelLowering.cpp.
References llvm::CCState::AnalyzeReturn(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyToReg(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getRegister(), llvm::SDValue::getValue(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::HexagonISD::RET_FLAG, RetCC_Hexagon(), and llvm::SmallVectorTemplateCommon< T >::size().
SDValue HexagonTargetLowering::LowerRETURNADDR (SDValue Op, SelectionDAG & DAG) const
Definition at line 1178 of file HexagonISelLowering.cpp.
References llvm::ISD::ADD, llvm::MachineFunction::addLiveIn(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getEntryNode(), llvm::MachineFunction::getFrameInfo(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::HexagonRegisterInfo::getRARegister(), llvm::TargetLoweringBase::getRegClassFor(), llvm::HexagonSubtarget::getRegisterInfo(), llvm::SDValue::getValueType(), llvm::MVT::i32, LowerFRAMEADDR(), llvm::MachineFrameInfo::setReturnAddressIsTaken(), and llvm::TargetLowering::verifyReturnAddressArgumentIsConstant().
Referenced by LowerOperation().
SDValue HexagonTargetLowering::LowerSETCC (SDValue Op, SelectionDAG & DAG) const
Definition at line 1009 of file HexagonISelLowering.cpp.
References llvm::C, llvm::dyn_cast(), llvm::ConstantSDNode::getAPIntValue(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::APInt::isNegative(), isSExtFree(), llvm::ISD::isSignedIntSetCC(), llvm::ISD::isUnsignedIntSetCC(), llvm::EVT::isVector(), llvm::PPCISD::SC, llvm::ISD::SETCC, llvm::ISD::SETEQ, llvm::ISD::SETNE, llvm::ISD::SIGN_EXTEND, llvm::MVT::v2i1, llvm::MVT::v2i16, llvm::MVT::v2i32, and llvm::ISD::ZERO_EXTEND.
Referenced by LowerOperation().
SDValue HexagonTargetLowering::LowerVASTART (SDValue Op, SelectionDAG & DAG) const
Definition at line 964 of file HexagonISelLowering.cpp.
References llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getStore(), llvm::HexagonMachineFunctionInfo::getVarArgsFrameIndex(), and llvm::MVT::i32.
Referenced by LowerOperation().
SDValue HexagonTargetLowering::LowerVSELECT (SDValue Op, SelectionDAG & DAG) const
Definition at line 1058 of file HexagonISelLowering.cpp.
References llvm::DL, llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::ISD::TRUNCATE, llvm::MVT::v2i16, llvm::MVT::v2i32, llvm::ISD::VSELECT, and llvm::ISD::ZERO_EXTEND.
Referenced by LowerOperation().
bool HexagonTargetLowering::mayBeEmittedAsTailCall (CallInst *) const [override, virtual]
Return true if the target may be able emit the call instruction as a tail call.
This is used by optimization passes to determine if it's profitable to duplicate return instructions to enable tailcall optimization.
Reimplemented from llvm::TargetLowering.
Definition at line 398 of file HexagonISelLowering.cpp.
References llvm::Function::getFnAttribute(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), and llvm::CallInst::isTailCall().
bool HexagonTargetLowering::shouldExpandBuildVectorWithShuffles (EVT VT, unsigned DefinedValues) const [override, virtual]
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1786 of file HexagonISelLowering.cpp.
References llvm::EVT::getSizeInBits(), and llvm::EVT::getVectorElementType().
The documentation for this class was generated from the following files:
HexagonISelLowering.h
HexagonISelLowering.cpp