LLVM: llvm::DebugLocStream Class Reference
llvm::DebugLocStream Class Reference
Byte stream of .debug_loc entries.
#include <DebugLocStream.h>
Classes
struct Entry
class EntryBuilder
Builder for DebugLocStream entries.
struct List
class ListBuilder
Builder for DebugLocStream lists.
Public Member Functions
DebugLocStream (bool GenerateComments)
size_t getNumLists () const
const List & getList (size_t LI) const
ArrayRef< List > getLists () const
BufferByteStreamer getStreamer ()
ArrayRef< Entry > getEntries (const List &L) const
ArrayRef< char > getBytes (const Entry &E) const
ArrayRef< std::string > getComments (const Entry &E) const
Detailed Description
Byte stream of .debug_loc entries.
Stores a unified stream of .debug_loc entries. There's List for each variable/inlined-at pair, and an Entry for each DebugLocEntry.
FIXME: Do we need all these temp symbols? FIXME: Why not output directly to the output stream?
Definition at line 32 of file DebugLocStream.h.
Constructor & Destructor Documentation
llvm::DebugLocStream::DebugLocStream (bool GenerateComments) [inline]
Definition at line 63 of file DebugLocStream.h.
Member Function Documentation
ArrayRef<char> llvm::DebugLocStream::getBytes (const Entry & E) const [inline]
Definition at line 114 of file DebugLocStream.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), and llvm::makeArrayRef().
Referenced by llvm::DwarfDebug::emitDebugLocEntry(), and llvm::DwarfDebug::emitDebugLocEntryLocation().
ArrayRef<std::string> llvm::DebugLocStream::getComments (const Entry & E) const [inline]
Definition at line 119 of file DebugLocStream.h.
References llvm::makeArrayRef().
Referenced by llvm::DwarfDebug::emitDebugLocEntry().
ArrayRef<Entry> llvm::DebugLocStream::getEntries (const List & L) const [inline]
Definition at line 108 of file DebugLocStream.h.
References llvm::makeArrayRef().
const List& llvm::DebugLocStream::getList (size_t LI) const [inline]
Definition at line 65 of file DebugLocStream.h.
Referenced by llvm::DIELocList::EmitValue().
ArrayRef<List> llvm::DebugLocStream::getLists () const [inline]
Definition at line 66 of file DebugLocStream.h.
size_t llvm::DebugLocStream::getNumLists () const [inline]
Definition at line 64 of file DebugLocStream.h.
References llvm::SmallVectorTemplateCommon< T, typename >::size().
BufferByteStreamer llvm::DebugLocStream::getStreamer () [inline]
Definition at line 104 of file DebugLocStream.h.
Referenced by llvm::DebugLocStream::EntryBuilder::getStreamer().
The documentation for this class was generated from the following files:
DebugLocStream.h
DebugLocStream.cpp