LLVM: llvm::DICompileUnit Class Reference
llvm::DICompileUnit Class Reference
Compile unit.
#include <DebugInfoMetadata.h>
Public Member Functions
DEFINE_MDNODE_GET (DICompileUnit,(unsigned SourceLanguage, DIFile *File, StringRef Producer, bool IsOptimized, StringRef Flags, unsigned RuntimeVersion, StringRef SplitDebugFilename, unsigned EmissionKind, DICompositeTypeArray EnumTypes, DITypeArray RetainedTypes, DISubprogramArray Subprograms, DIGlobalVariableArray GlobalVariables, DIImportedEntityArray ImportedEntities, uint64_t DWOId),(SourceLanguage, File, Producer, IsOptimized, Flags, RuntimeVersion, SplitDebugFilename, EmissionKind, EnumTypes, RetainedTypes, Subprograms, GlobalVariables, ImportedEntities, DWOId)) DEFINE_MDNODE_GET(DICompileUnit
unsigned Metadata MDString
bool MDString unsigned
MDString unsigned Metadata
Metadata Metadata Metadata
Metadata uint64_t DWOId
TempDICompileUnit clone () const
Create a (temporary) clone of this.
unsigned getSourceLanguage () const
bool isOptimized () const
unsigned getRuntimeVersion () const
unsigned getEmissionKind () const
StringRef getProducer () const
StringRef getFlags () const
StringRef getSplitDebugFilename () const
DICompositeTypeArray getEnumTypes () const
DITypeArray getRetainedTypes () const
DISubprogramArray getSubprograms () const
DIGlobalVariableArray getGlobalVariables () const
DIImportedEntityArray getImportedEntities () const
unsigned getDWOId () const
MDString * getRawProducer () const
MDString * getRawFlags () const
MDString * getRawSplitDebugFilename () const
Metadata * getRawEnumTypes () const
Metadata * getRawRetainedTypes () const
Metadata * getRawSubprograms () const
Metadata * getRawGlobalVariables () const
Metadata * getRawImportedEntities () const
void replaceSubprograms (DISubprogramArray N)
Replace arrays.
void replaceGlobalVariables (DIGlobalVariableArray N)
Static Public Member Functions
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
Public Attributes
unsigned Metadata * File
unsigned Metadata MDString * Producer
unsigned Metadata MDString bool IsOptimized
unsigned Metadata MDString
bool MDString * Flags
unsigned Metadata MDString
bool MDString unsigned RuntimeVersion
unsigned Metadata MDString
bool MDString unsigned
MDString * SplitDebugFilename
unsigned Metadata MDString
bool MDString unsigned
MDString unsigned EmissionKind
unsigned Metadata MDString
bool MDString unsigned
MDString unsigned Metadata * EnumTypes
unsigned Metadata MDString
bool MDString unsigned
MDString unsigned Metadata
Metadata * RetainedTypes
unsigned Metadata MDString
bool MDString unsigned
MDString unsigned Metadata
Metadata Metadata * Subprograms
unsigned Metadata MDString
bool MDString unsigned
MDString unsigned Metadata
Metadata Metadata Metadata * GlobalVariables
unsigned Metadata MDString
bool MDString unsigned
MDString unsigned Metadata
Metadata Metadata Metadata
Metadata * ImportedEntities
unsigned Metadata MDString
bool MDString unsigned
MDString unsigned Metadata
Metadata Metadata Metadata
Metadata uint64_t DWOId
unsigned Metadata MDString
bool MDString unsigned
MDString unsigned Metadata
Metadata Metadata Metadata
Metadata uint64_t SourceLanguage
unsigned Metadata MDString
bool MDString unsigned
MDString unsigned Metadata
Metadata Metadata Metadata
Metadata uint64_t File
unsigned Metadata MDString
bool MDString unsigned
MDString unsigned Metadata
Metadata Metadata Metadata
Metadata uint64_t Producer
unsigned Metadata MDString
bool MDString unsigned
MDString unsigned Metadata
Metadata Metadata Metadata
Metadata uint64_t IsOptimized
unsigned Metadata MDString
bool MDString unsigned
MDString unsigned Metadata
Metadata Metadata Metadata
Metadata uint64_t Flags
unsigned Metadata MDString
bool MDString unsigned
MDString unsigned Metadata
Metadata Metadata Metadata
Metadata uint64_t RuntimeVersion
unsigned Metadata MDString
bool MDString unsigned
MDString unsigned Metadata
Metadata Metadata Metadata
Metadata uint64_t SplitDebugFilename
unsigned Metadata MDString
bool MDString unsigned
MDString unsigned Metadata
Metadata Metadata Metadata
Metadata uint64_t EmissionKind
unsigned Metadata MDString
bool MDString unsigned
MDString unsigned Metadata
Metadata Metadata Metadata
Metadata uint64_t EnumTypes
unsigned Metadata MDString
bool MDString unsigned
MDString unsigned Metadata
Metadata Metadata Metadata
Metadata uint64_t RetainedTypes
unsigned Metadata MDString
bool MDString unsigned
MDString unsigned Metadata
Metadata Metadata Metadata
Metadata uint64_t Subprograms
unsigned Metadata MDString
bool MDString unsigned
MDString unsigned Metadata
Metadata Metadata Metadata
Metadata uint64_t GlobalVariables
unsigned Metadata MDString
bool MDString unsigned
MDString unsigned Metadata
Metadata Metadata Metadata
Metadata uint64_t ImportedEntities
Friends
class LLVMContextImpl
class MDNode
Detailed Description
Compile unit.
Definition at line 966 of file DebugInfoMetadata.h.
Member Function Documentation
static bool llvm::DICompileUnit::classof (const Metadata * MD) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::DIScope.
Definition at line 1094 of file DebugInfoMetadata.h.
References llvm::Metadata::DICompileUnitKind, and llvm::Metadata::getMetadataID().
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t DWOId TempDICompileUnit llvm::DICompileUnit::clone () const [inline]
Create a (temporary) clone of this.
Reimplemented from llvm::MDNode.
Definition at line 1043 of file DebugInfoMetadata.h.
llvm::DICompileUnit::DEFINE_MDNODE_GET (DICompileUnit , (unsigned SourceLanguage, DIFile *File, StringRef Producer,bool IsOptimized, StringRef Flags, unsigned RuntimeVersion,StringRef SplitDebugFilename, unsigned EmissionKind,DICompositeTypeArray EnumTypes, DITypeArray RetainedTypes,DISubprogramArray Subprograms,DIGlobalVariableArray GlobalVariables,DIImportedEntityArray ImportedEntities, uint64_t DWOId) , (SourceLanguage, File, Producer, IsOptimized, Flags,RuntimeVersion, SplitDebugFilename, EmissionKind,EnumTypes, RetainedTypes, Subprograms, GlobalVariables,ImportedEntities, DWOId))
unsigned llvm::DICompileUnit::getDWOId () const [inline]
Definition at line 1067 of file DebugInfoMetadata.h.
Referenced by llvm::MDNodeKeyImpl< DICompileUnit >::isKeyOf(), and WriteDICompileUnit().
unsigned llvm::DICompileUnit::getEmissionKind () const [inline]
Definition at line 1048 of file DebugInfoMetadata.h.
Referenced by llvm::MDNodeKeyImpl< DICompileUnit >::isKeyOf(), and WriteDICompileUnit().
DICompositeTypeArray llvm::DICompileUnit::getEnumTypes () const [inline]
Definition at line 1052 of file DebugInfoMetadata.h.
References getRawEnumTypes().
Referenced by WriteDICompileUnit().
StringRef llvm::DICompileUnit::getFlags () const [inline]
Definition at line 1050 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
Referenced by llvm::MDNodeKeyImpl< DICompileUnit >::isKeyOf().
DIGlobalVariableArray llvm::DICompileUnit::getGlobalVariables () const [inline]
Definition at line 1061 of file DebugInfoMetadata.h.
References getRawGlobalVariables().
Referenced by WriteDICompileUnit().
DIImportedEntityArray llvm::DICompileUnit::getImportedEntities () const [inline]
Definition at line 1064 of file DebugInfoMetadata.h.
References getRawImportedEntities().
Referenced by WriteDICompileUnit().
StringRef llvm::DICompileUnit::getProducer () const [inline]
Definition at line 1049 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
Referenced by llvm::MDNodeKeyImpl< DICompileUnit >::isKeyOf().
Metadata* llvm::DICompileUnit::getRawEnumTypes () const [inline]
Definition at line 1074 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getEnumTypes(), and llvm::MDNodeKeyImpl< DICompileUnit >::isKeyOf().
MDString* llvm::DICompileUnit::getRawFlags () const [inline]
Definition at line 1070 of file DebugInfoMetadata.h.
Referenced by WriteDICompileUnit().
Metadata* llvm::DICompileUnit::getRawGlobalVariables () const [inline]
Definition at line 1077 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getGlobalVariables(), and llvm::MDNodeKeyImpl< DICompileUnit >::isKeyOf().
Metadata* llvm::DICompileUnit::getRawImportedEntities () const [inline]
Definition at line 1078 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getImportedEntities(), and llvm::MDNodeKeyImpl< DICompileUnit >::isKeyOf().
MDString* llvm::DICompileUnit::getRawProducer () const [inline]
Definition at line 1069 of file DebugInfoMetadata.h.
Referenced by WriteDICompileUnit().
Metadata* llvm::DICompileUnit::getRawRetainedTypes () const [inline]
Definition at line 1075 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getRetainedTypes(), and llvm::MDNodeKeyImpl< DICompileUnit >::isKeyOf().
MDString* llvm::DICompileUnit::getRawSplitDebugFilename () const [inline]
Definition at line 1071 of file DebugInfoMetadata.h.
Referenced by WriteDICompileUnit().
Metadata* llvm::DICompileUnit::getRawSubprograms () const [inline]
Definition at line 1076 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getSubprograms(), and llvm::MDNodeKeyImpl< DICompileUnit >::isKeyOf().
DITypeArray llvm::DICompileUnit::getRetainedTypes () const [inline]
Definition at line 1055 of file DebugInfoMetadata.h.
References getRawRetainedTypes().
Referenced by WriteDICompileUnit().
unsigned llvm::DICompileUnit::getRuntimeVersion () const [inline]
Definition at line 1047 of file DebugInfoMetadata.h.
Referenced by llvm::MDNodeKeyImpl< DICompileUnit >::isKeyOf(), and WriteDICompileUnit().
unsigned llvm::DICompileUnit::getSourceLanguage () const [inline]
Definition at line 1045 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfUnit::getLanguage(), llvm::MDNodeKeyImpl< DICompileUnit >::isKeyOf(), and WriteDICompileUnit().
StringRef llvm::DICompileUnit::getSplitDebugFilename () const [inline]
Definition at line 1051 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
Referenced by llvm::MDNodeKeyImpl< DICompileUnit >::isKeyOf().
DISubprogramArray llvm::DICompileUnit::getSubprograms () const [inline]
Definition at line 1058 of file DebugInfoMetadata.h.
References getRawSubprograms().
Referenced by WriteDICompileUnit().
bool llvm::DICompileUnit::isOptimized () const [inline]
Definition at line 1046 of file DebugInfoMetadata.h.
Referenced by llvm::MDNodeKeyImpl< DICompileUnit >::isKeyOf(), and WriteDICompileUnit().
void llvm::DICompileUnit::replaceGlobalVariables (DIGlobalVariableArray N) [inline]
Definition at line 1089 of file DebugInfoMetadata.h.
References llvm::MDNode::replaceOperandWith().
void llvm::DICompileUnit::replaceSubprograms (DISubprogramArray N) [inline]
Replace arrays.
If this isUniqued() and not isResolved(), it will be RAUW'ed and deleted on a uniquing collision. In practice, uniquing collisions on DICompileUnit should be fairly rare.
Definition at line 1086 of file DebugInfoMetadata.h.
References llvm::MDNode::replaceOperandWith().
Referenced by AddOperand().
Friends And Related Function Documentation
friend class LLVMContextImpl [friend]
Reimplemented from llvm::DINode.
Definition at line 967 of file DebugInfoMetadata.h.
friend class MDNode [friend]
Reimplemented from llvm::DINode.
Definition at line 968 of file DebugInfoMetadata.h.
Member Data Documentation
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t llvm::DICompileUnit::DWOId
Definition at line 1034 of file DebugInfoMetadata.h.
unsigned Metadata MDString bool MDString unsigned MDString unsigned llvm::DICompileUnit::EmissionKind
Definition at line 1034 of file DebugInfoMetadata.h.
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t llvm::DICompileUnit::EmissionKind
Definition at line 1034 of file DebugInfoMetadata.h.
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata* llvm::DICompileUnit::EnumTypes
Definition at line 1034 of file DebugInfoMetadata.h.
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t llvm::DICompileUnit::EnumTypes
Definition at line 1034 of file DebugInfoMetadata.h.
unsigned Metadata* llvm::DICompileUnit::File
Definition at line 1034 of file DebugInfoMetadata.h.
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t llvm::DICompileUnit::File
Definition at line 1034 of file DebugInfoMetadata.h.
unsigned Metadata MDString bool MDString* llvm::DICompileUnit::Flags
Definition at line 1034 of file DebugInfoMetadata.h.
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t llvm::DICompileUnit::Flags
Definition at line 1034 of file DebugInfoMetadata.h.
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata* llvm::DICompileUnit::GlobalVariables
Definition at line 1034 of file DebugInfoMetadata.h.
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t llvm::DICompileUnit::GlobalVariables
Definition at line 1034 of file DebugInfoMetadata.h.
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata* llvm::DICompileUnit::ImportedEntities
Definition at line 1034 of file DebugInfoMetadata.h.
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t llvm::DICompileUnit::ImportedEntities
Definition at line 1034 of file DebugInfoMetadata.h.
unsigned Metadata MDString bool llvm::DICompileUnit::IsOptimized
Definition at line 1034 of file DebugInfoMetadata.h.
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t llvm::DICompileUnit::IsOptimized
Definition at line 1034 of file DebugInfoMetadata.h.
unsigned Metadata MDString* llvm::DICompileUnit::Producer
Definition at line 1034 of file DebugInfoMetadata.h.
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t llvm::DICompileUnit::Producer
Definition at line 1034 of file DebugInfoMetadata.h.
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata* llvm::DICompileUnit::RetainedTypes
Definition at line 1034 of file DebugInfoMetadata.h.
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t llvm::DICompileUnit::RetainedTypes
Definition at line 1034 of file DebugInfoMetadata.h.
unsigned Metadata MDString bool MDString unsigned llvm::DICompileUnit::RuntimeVersion
Definition at line 1034 of file DebugInfoMetadata.h.
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t llvm::DICompileUnit::RuntimeVersion
Definition at line 1034 of file DebugInfoMetadata.h.
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t llvm::DICompileUnit::SourceLanguage
Definition at line 1034 of file DebugInfoMetadata.h.
unsigned Metadata MDString bool MDString unsigned MDString* llvm::DICompileUnit::SplitDebugFilename
Definition at line 1034 of file DebugInfoMetadata.h.
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t llvm::DICompileUnit::SplitDebugFilename
Definition at line 1034 of file DebugInfoMetadata.h.
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata* llvm::DICompileUnit::Subprograms
Definition at line 1034 of file DebugInfoMetadata.h.
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t llvm::DICompileUnit::Subprograms
Definition at line 1034 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
DebugInfoMetadata.h
DebugInfoMetadata.cpp