LLVM: llvm::IPDBSourceFile Class Reference
llvm::IPDBSourceFile Class Reference
IPDBSourceFile defines an interface used to represent source files whose information are stored in the PDB.
#include <IPDBSourceFile.h>
Public Member Functions
virtual ~IPDBSourceFile ()
void dump (raw_ostream &OS, int Indent) const
virtual std::string getFileName () const =0
virtual uint32_t getUniqueId () const =0
virtual std::string getChecksum () const =0
virtual PDB_Checksum getChecksumType () const =0
virtual std::unique_ptr
< IPDBEnumSymbols > getCompilands () const =0
Detailed Description
IPDBSourceFile defines an interface used to represent source files whose information are stored in the PDB.
Definition at line 23 of file IPDBSourceFile.h.
Constructor & Destructor Documentation
IPDBSourceFile::~IPDBSourceFile () [virtual]
Definition at line 18 of file IPDBSourceFile.cpp.
Member Function Documentation
void IPDBSourceFile::dump (raw_ostream & OS, int Indent) const
Definition at line 20 of file IPDBSourceFile.cpp.
References llvm::format_hex_no_prefix(), getChecksum(), getChecksumType(), getFileName(), llvm::raw_ostream::indent(), and llvm::None.
virtual std::string llvm::IPDBSourceFile::getChecksum () const [pure virtual]
Implemented in llvm::DIASourceFile.
Referenced by dump().
virtual PDB_Checksum llvm::IPDBSourceFile::getChecksumType () const [pure virtual]
Implemented in llvm::DIASourceFile.
Referenced by dump().
virtual std::unique_ptr<IPDBEnumSymbols> llvm::IPDBSourceFile::getCompilands () const [pure virtual]
Implemented in llvm::DIASourceFile.
virtual std::string llvm::IPDBSourceFile::getFileName () const [pure virtual]
Implemented in llvm::DIASourceFile.
Referenced by dump().
virtual uint32_t llvm::IPDBSourceFile::getUniqueId () const [pure virtual]
Implemented in llvm::DIASourceFile.
The documentation for this class was generated from the following files:
IPDBSourceFile.h
IPDBSourceFile.cpp