LLVM: llvm::raw_string_ostream Class Reference
llvm::raw_string_ostream Class Reference
A raw_ostream that writes to an std::string.
#include <raw_ostream.h>
Public Member Functions
raw_string_ostream (std::string &O)
~raw_string_ostream () override
std::string & str ()
Flushes the stream contents to the target string and returns the string's reference.
Detailed Description
A raw_ostream that writes to an std::string.
This is a simple adaptor class. This class does not encounter output errors.
Definition at line 463 of file raw_ostream.h.
Constructor & Destructor Documentation
llvm::raw_string_ostream::raw_string_ostream (std::string & O) [inline, explicit]
Definition at line 473 of file raw_ostream.h.
raw_string_ostream::~raw_string_ostream () [override]
Definition at line 746 of file raw_ostream.cpp.
References llvm::raw_ostream::flush().
Member Function Documentation
std::string& llvm::raw_string_ostream::str () [inline]
Flushes the stream contents to the target string and returns the string's reference.
Definition at line 478 of file raw_ostream.h.
References llvm::raw_ostream::flush().
Referenced by llvm::TargetSchedModel::computeOperandLatency(), EmitGCCInlineAsmStr(), llvm::X86AsmPrinter::EmitInstruction(), EmitMSInlineAsmStr(), llvm::DOTGraphTraits< const Function * >::getCompleteNodeLabel(), llvm::DOTGraphTraits< const Function * >::getEdgeSourceLabel(), llvm::ScheduleDAGSDNodes::getGraphNodeLabel(), llvm::ScheduleDAGInstrs::getGraphNodeLabel(), getLoopBackedgeTakenCounts(), llvm::DOTGraphTraits< ScheduleDAGMI * >::getNodeLabel(), llvm::DOTGraphTraits< const Function * >::getSimpleNodeLabel(), getTypeString(), LLVMVerifyModule(), LLVMWriteBitcodeToMemoryBuffer(), llvm::AsmPrinter::lowerConstant(), llvm::AsmPrinter::PrintSpecial(), false::Chain::str(), llvm::GraphWriter< GraphType >::writeNode(), and writeSymbolTable().
The documentation for this class was generated from the following files:
raw_ostream.h
raw_ostream.cpp