LLVM: llvm::BufferByteStreamer Class Reference
llvm::BufferByteStreamer Class Reference
#include <ByteStreamer.h>
Public Member Functions
BufferByteStreamer (SmallVectorImpl< char > &Buffer, SmallVectorImpl< std::string > &Comments, bool GenerateComments)
void EmitInt8 (uint8_t Byte, const Twine &Comment) override
void EmitSLEB128 (uint64_t DWord, const Twine &Comment) override
void EmitULEB128 (uint64_t DWord, const Twine &Comment) override
Detailed Description
Definition at line 72 of file ByteStreamer.h.
Constructor & Destructor Documentation
llvm::BufferByteStreamer::BufferByteStreamer (SmallVectorImpl< char > & Buffer, SmallVectorImpl< std::string > & Comments, bool GenerateComments) [inline]
Definition at line 83 of file ByteStreamer.h.
Member Function Documentation
void llvm::BufferByteStreamer::EmitInt8 (uint8_t Byte, const Twine & Comment) [inline, override, virtual]
Implements llvm::ByteStreamer.
Definition at line 87 of file ByteStreamer.h.
References llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::Twine::str().
void llvm::BufferByteStreamer::EmitSLEB128 (uint64_t DWord, const Twine & Comment) [inline, override, virtual]
Implements llvm::ByteStreamer.
Definition at line 92 of file ByteStreamer.h.
References llvm::encodeSLEB128(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::Twine::str().
void llvm::BufferByteStreamer::EmitULEB128 (uint64_t DWord, const Twine & Comment) [inline, override, virtual]
Implements llvm::ByteStreamer.
Definition at line 98 of file ByteStreamer.h.
References llvm::encodeULEB128(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::Twine::str().
The documentation for this class was generated from the following file:
ByteStreamer.h