LLVM: llvm::ObjectCache Class Reference
llvm::ObjectCache Class Reference
This is the base ObjectCache type which can be provided to an ExecutionEngine for the purpose of avoiding compilation for Modules that have already been compiled and an object file is available.
#include <ObjectCache.h>
Public Member Functions
ObjectCache ()
virtual ~ObjectCache ()
virtual void notifyObjectCompiled (const Module *M, MemoryBufferRef Obj)=0
notifyObjectCompiled - Provides a pointer to compiled code for Module M.
virtual std::unique_ptr
< MemoryBuffer > getObject (const Module *M)=0
Returns a pointer to a newly allocated MemoryBuffer that contains the object which corresponds with Module M, or 0 if an object is not available.
Detailed Description
This is the base ObjectCache type which can be provided to an ExecutionEngine for the purpose of avoiding compilation for Modules that have already been compiled and an object file is available.
Definition at line 22 of file ObjectCache.h.
Constructor & Destructor Documentation
llvm::ObjectCache::ObjectCache () [inline]
Definition at line 25 of file ObjectCache.h.
virtual llvm::ObjectCache::~ObjectCache () [inline, virtual]
Definition at line 27 of file ObjectCache.h.
Member Function Documentation
virtual std::unique_ptr<MemoryBuffer> llvm::ObjectCache::getObject (const Module * M) [pure virtual]
Returns a pointer to a newly allocated MemoryBuffer that contains the object which corresponds with Module M, or 0 if an object is not available.
Referenced by llvm::MCJIT::generateCodeForModule().
virtual void llvm::ObjectCache::notifyObjectCompiled (const Module * M, MemoryBufferRef Obj) [pure virtual]
notifyObjectCompiled - Provides a pointer to compiled code for Module M.
Referenced by llvm::orc::IRCompileLayer< ObjectLayerT >::addModuleSet(), and llvm::MCJIT::emitObject().
The documentation for this class was generated from the following files:
ObjectCache.h
MCJIT.cpp