LLVM: llvm::PBQP::RegAlloc::GraphMetadata Class Reference
llvm::PBQP::RegAlloc::GraphMetadata Class Reference
Holds graph-level metadata relevent to PBQP RA problems.
#include <RegAllocPBQP.h>
Public Types
typedef AllowedRegVecPool::PoolRef AllowedRegVecRef
Public Member Functions
GraphMetadata (MachineFunction &MF, LiveIntervals &LIS, MachineBlockFrequencyInfo &MBFI)
void setNodeIdForVReg (unsigned VReg, GraphBase::NodeId NId)
GraphBase::NodeId getNodeIdForVReg (unsigned VReg) const
void eraseNodeIdForVReg (unsigned VReg)
AllowedRegVecRef getAllowedRegs (AllowedRegVector Allowed)
Public Attributes
MachineFunction & MF
LiveIntervals & LIS
MachineBlockFrequencyInfo & MBFI
Detailed Description
Holds graph-level metadata relevent to PBQP RA problems.
Definition at line 138 of file RegAllocPBQP.h.
Member Typedef Documentation
typedef AllowedRegVecPool::PoolRef llvm::PBQP::RegAlloc::GraphMetadata::AllowedRegVecRef
Definition at line 143 of file RegAllocPBQP.h.
Constructor & Destructor Documentation
llvm::PBQP::RegAlloc::GraphMetadata::GraphMetadata (MachineFunction & MF, LiveIntervals & LIS, MachineBlockFrequencyInfo & MBFI) [inline]
Definition at line 145 of file RegAllocPBQP.h.
Member Function Documentation
void llvm::PBQP::RegAlloc::GraphMetadata::eraseNodeIdForVReg (unsigned VReg) [inline]
Definition at line 165 of file RegAllocPBQP.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase().
AllowedRegVecRef llvm::PBQP::RegAlloc::GraphMetadata::getAllowedRegs (AllowedRegVector Allowed) [inline]
Definition at line 169 of file RegAllocPBQP.h.
References llvm::PBQP::ValuePool< ValueT >::getValue().
GraphBase::NodeId llvm::PBQP::RegAlloc::GraphMetadata::getNodeIdForVReg (unsigned VReg) const [inline]
Definition at line 158 of file RegAllocPBQP.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and llvm::PBQP::GraphBase::invalidNodeId().
void llvm::PBQP::RegAlloc::GraphMetadata::setNodeIdForVReg (unsigned VReg, GraphBase::NodeId NId) [inline]
Definition at line 154 of file RegAllocPBQP.h.
Member Data Documentation
LiveIntervals& llvm::PBQP::RegAlloc::GraphMetadata::LIS
Definition at line 151 of file RegAllocPBQP.h.
MachineBlockFrequencyInfo& llvm::PBQP::RegAlloc::GraphMetadata::MBFI
Definition at line 152 of file RegAllocPBQP.h.
MachineFunction& llvm::PBQP::RegAlloc::GraphMetadata::MF
Definition at line 150 of file RegAllocPBQP.h.
The documentation for this class was generated from the following file:
RegAllocPBQP.h