LLVM: llvm::StringToOffsetTable Class Reference
llvm::StringToOffsetTable Class Reference
StringToOffsetTable - This class uniques a bunch of nul-terminated strings and keeps track of their offset in a massive contiguous string allocation.
#include <StringToOffsetTable.h>
Public Member Functions
unsigned GetOrAddStringOffset (StringRef Str, bool appendZero=true)
void EmitString (raw_ostream &O)
Detailed Description
StringToOffsetTable - This class uniques a bunch of nul-terminated strings and keeps track of their offset in a massive contiguous string allocation.
It can then output this string blob and use indexes into the string to reference each piece.
Definition at line 25 of file StringToOffsetTable.h.
Member Function Documentation
void llvm::StringToOffsetTable::EmitString (raw_ostream & O) [inline]
Definition at line 43 of file StringToOffsetTable.h.
References llvm::SmallString< InternalLen >::str(), and llvm::raw_ostream::write_escaped().
unsigned llvm::StringToOffsetTable::GetOrAddStringOffset (StringRef Str, bool appendZero = true) [inline]
Definition at line 30 of file StringToOffsetTable.h.
References llvm::StringRef::begin(), llvm::StringRef::end(), and llvm::StringMap< ValueTy, AllocatorTy >::insert().
The documentation for this class was generated from the following file:
StringToOffsetTable.h