LLVM: llvm::BPFFrameLowering Class Reference
llvm::BPFFrameLowering Class Reference
#include <BPFFrameLowering.h>
Public Member Functions
BPFFrameLowering (const BPFSubtarget &sti)
void emitPrologue (MachineFunction &MF, MachineBasicBlock &MBB) const override
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const override
bool hasFP (const MachineFunction &MF) const override
hasFP - Return true if the specified function should have a dedicated frame pointer register.
void processFunctionBeforeCalleeSavedScan (MachineFunction &MF, RegScavenger *RS) const override
processFunctionBeforeCalleeSavedScan - This method is called immediately before PrologEpilogInserter scans the physical registers used to determine what callee saved registers should be spilled.
void eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MI) const override
eliminateCallFramePseudoInstr - This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
Detailed Description
Definition at line 22 of file BPFFrameLowering.h.
Constructor & Destructor Documentation
llvm::BPFFrameLowering::BPFFrameLowering (const BPFSubtarget & sti) [inline, explicit]
Definition at line 24 of file BPFFrameLowering.h.
Member Function Documentation
void llvm::BPFFrameLowering::eliminateCallFramePseudoInstr (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const [inline, override, virtual]
eliminateCallFramePseudoInstr - This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
It is responsible for eliminating these instructions, replacing them with concrete instructions. This method need only be implemented if using call frame setup/destroy pseudo instructions.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 35 of file BPFFrameLowering.h.
References llvm::MachineBasicBlock::erase().
void BPFFrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const [override, virtual]
Implements llvm::TargetFrameLowering.
Definition at line 29 of file BPFFrameLowering.cpp.
void BPFFrameLowering::emitPrologue (MachineFunction & MF, MachineBasicBlock & MBB) const [override, virtual]
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
Implements llvm::TargetFrameLowering.
Definition at line 26 of file BPFFrameLowering.cpp.
bool BPFFrameLowering::hasFP (const MachineFunction & MF) const [override, virtual]
hasFP - Return true if the specified function should have a dedicated frame pointer register.
For most targets this is true only if the function has variable sized allocas or if frame pointer elimination is disabled.
Implements llvm::TargetFrameLowering.
Definition at line 24 of file BPFFrameLowering.cpp.
void BPFFrameLowering::processFunctionBeforeCalleeSavedScan (MachineFunction & MF, RegScavenger * RS) const [override, virtual]
processFunctionBeforeCalleeSavedScan - This method is called immediately before PrologEpilogInserter scans the physical registers used to determine what callee saved registers should be spilled.
This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 32 of file BPFFrameLowering.cpp.
References llvm::MachineFunction::getRegInfo(), llvm::R8, llvm::R9, and llvm::MachineRegisterInfo::setPhysRegUnused().
The documentation for this class was generated from the following files:
BPFFrameLowering.h
BPFFrameLowering.cpp