LLVM: llvm::DwarfUnit Class Reference
llvm::DwarfUnit Class Reference
This dwarf writer support class manages information associated with a source file.
#include <DwarfUnit.h>
Public Member Functions
virtual ~DwarfUnit ()
void initSection (MCSection *Section)
MCSection * getSection () const
AsmPrinter * getAsmPrinter () const
unsigned getUniqueID () const
uint16_t getLanguage () const
const DICompileUnit * getCUNode () const
DIE & getUnitDie ()
unsigned getDebugInfoOffset () const
void setDebugInfoOffset (unsigned DbgInfoOff)
bool hasContent () const
Return true if this compile unit has something to write out.
std::string getParentContextString (const DIScope *Context) const
Get string containing language specific context for a global name.
virtual void addGlobalName (StringRef Name, DIE &Die, const DIScope *Context)
Add a new global name to the compile unit.
virtual void addGlobalType (const DIType *Ty, const DIE &Die, const DIScope *Context)
Add a new global type to the compile unit.
void addAccelNamespace (StringRef Name, const DIE &Die)
Add a new name to the namespace accelerator table.
DIE * getDIE (const DINode *D) const
Returns the DIE map slot for the specified debug variable.
DIELoc * getDIELoc ()
Returns a fresh newly allocated DIELoc.
void insertDIE (const DINode *Desc, DIE *D)
Insert DIE into the map.
void addFlag (DIE &Die, dwarf::Attribute Attribute)
Add a flag that is true to the DIE.
void addUInt (DIE &Die, dwarf::Attribute Attribute, Optional< dwarf::Form > Form, uint64_t Integer)
Add an unsigned integer attribute data and value.
void addUInt (DIE &Block, dwarf::Form Form, uint64_t Integer)
void addSInt (DIE &Die, dwarf::Attribute Attribute, Optional< dwarf::Form > Form, int64_t Integer)
Add an signed integer attribute data and value.
void addSInt (DIELoc &Die, Optional< dwarf::Form > Form, int64_t Integer)
void addString (DIE &Die, dwarf::Attribute Attribute, StringRef Str)
Add a string attribute data and value.
void addLabel (DIE &Die, dwarf::Attribute Attribute, dwarf::Form Form, const MCSymbol *Label)
Add a Dwarf label attribute data and value.
void addLabel (DIELoc &Die, dwarf::Form Form, const MCSymbol *Label)
void addSectionOffset (DIE &Die, dwarf::Attribute Attribute, uint64_t Integer)
Add an offset into a section attribute data and value.
void addOpAddress (DIELoc &Die, const MCSymbol *Label)
Add a dwarf op address data and value using the form given and an op of either DW_FORM_addr or DW_FORM_GNU_addr_index.
void addLabelDelta (DIE &Die, dwarf::Attribute Attribute, const MCSymbol *Hi, const MCSymbol *Lo)
Add a label delta attribute data and value.
void addDIEEntry (DIE &Die, dwarf::Attribute Attribute, DIE &Entry)
Add a DIE attribute data and value.
void addDIEEntry (DIE &Die, dwarf::Attribute Attribute, DIEEntry Entry)
Add a DIE attribute data and value.
void addDIETypeSignature (DIE &Die, const DwarfTypeUnit &Type)
void addBlock (DIE &Die, dwarf::Attribute Attribute, DIELoc *Block)
Add block data.
void addBlock (DIE &Die, dwarf::Attribute Attribute, DIEBlock *Block)
Add block data.
void addSourceLine (DIE &Die, unsigned Line, StringRef File, StringRef Directory)
Add location information to specified debug information entry.
void addSourceLine (DIE &Die, const DILocalVariable *V)
void addSourceLine (DIE &Die, const DIGlobalVariable *G)
void addSourceLine (DIE &Die, const DISubprogram *SP)
void addSourceLine (DIE &Die, const DIType *Ty)
void addSourceLine (DIE &Die, const DINamespace *NS)
void addSourceLine (DIE &Die, const DIObjCProperty *Ty)
void addConstantValue (DIE &Die, const MachineOperand &MO, const DIType *Ty)
Add constant value entry in variable DIE.
void addConstantValue (DIE &Die, const ConstantInt *CI, const DIType *Ty)
void addConstantValue (DIE &Die, const APInt &Val, const DIType *Ty)
void addConstantValue (DIE &Die, const APInt &Val, bool Unsigned)
void addConstantValue (DIE &Die, bool Unsigned, uint64_t Val)
void addConstantFPValue (DIE &Die, const MachineOperand &MO)
Add constant value entry in variable DIE.
void addConstantFPValue (DIE &Die, const ConstantFP *CFP)
void addLinkageName (DIE &Die, StringRef LinkageName)
Add a linkage name, if it isn't empty.
void addTemplateParams (DIE &Buffer, DINodeArray TParams)
Add template parameters in buffer.
bool addRegisterOpPiece (DIELoc &TheDie, unsigned Reg, unsigned SizeInBits=0, unsigned OffsetInBits=0)
Add register operand.
bool addRegisterOffset (DIELoc &TheDie, unsigned Reg, int64_t Offset)
Add register offset.
void addBlockByrefAddress (const DbgVariable &DV, DIE &Die, dwarf::Attribute Attribute, const MachineLocation &Location)
Start with the address based on the location provided, and generate the DWARF information necessary to find the actual Block variable (navigating the Block struct) based on the starting location.
void addType (DIE &Entity, const DIType *Ty, dwarf::Attribute Attribute=dwarf::DW_AT_type)
Add a new type attribute to the specified entity.
DIE * getOrCreateNameSpace (const DINamespace *NS)
DIE * getOrCreateSubprogramDIE (const DISubprogram *SP, bool Minimal=false)
void applySubprogramAttributes (const DISubprogram *SP, DIE &SPDie, bool Minimal=false)
DIE * getOrCreateTypeDIE (const MDNode *N)
Find existing DIE or create new DIE for the given type.
DIE * createTypeDIE (const DICompositeType *Ty)
Get context owner's DIE.
DIE * getOrCreateContextDIE (const DIScope *Context)
Get context owner's DIE.
void constructContainingTypeDIEs ()
Construct DIEs for types that contain vtables.
void constructSubprogramArguments (DIE &Buffer, DITypeRefArray Args)
Construct function argument DIEs.
DIE & createAndAddDIE (unsigned Tag, DIE &Parent, const DINode *N=nullptr)
Create a DIE with the given Tag, add the DIE to its parent, and call insertDIE if MD is not null.
virtual unsigned getHeaderSize () const
Compute the size of a header for this unit, not including the initial length field.
virtual void emitHeader (bool UseOffsets)
Emit the header for this unit, not including the initial length field.
virtual DwarfCompileUnit & getCU ()=0
void constructTypeDIE (DIE &Buffer, const DICompositeType *CTy)
Protected Member Functions
DwarfUnit (unsigned UID, dwarf::Tag, const DICompileUnit *CU, AsmPrinter *A, DwarfDebug *DW, DwarfFile *DWU)
void addLocalString (DIE &Die, dwarf::Attribute Attribute, StringRef Str)
Add a string attribute data and value.
void addIndexedString (DIE &Die, dwarf::Attribute Attribute, StringRef Str)
bool applySubprogramDefinitionAttributes (const DISubprogram *SP, DIE &SPDie)
DIE * getOrCreateStaticMemberDIE (const DIDerivedType *DT)
Create new static data member DIE.
virtual unsigned getOrCreateSourceID (StringRef File, StringRef Directory)=0
Look up the source ID with the given directory and source file names.
template<typename T >
T * resolve (TypedDINodeRef< T > Ref) const
Look in the DwarfDebug map for the MDNode that corresponds to the reference.
Protected Attributes
unsigned UniqueID
A numeric ID unique among all CUs in the module.
const DICompileUnit * CUNode
MDNode for the compile unit.
DIE UnitDie
Unit debug information entry.
unsigned DebugInfoOffset
Offset of the UnitDie from beginning of debug info section.
AsmPrinter * Asm
Target of Dwarf emission.
DwarfDebug * DD
DwarfFile * DU
DIE * IndexTyDie
An anonymous type for index type. Owned by UnitDie.
DenseMap< const MDNode *, DIE * > MDNodeToDieMap
Tracks the mapping of unit level debug information variables to debug information entries.
std::vector< DIEBlock * > DIEBlocks
A list of all the DIEBlocks in use.
std::vector< DIELoc * > DIELocs
A list of all the DIELocs in use.
DenseMap< DIE *, const DINode * > ContainingTypeMap
This map is used to keep track of subprogram DIEs that need DW_AT_containing_type attribute.
BumpPtrAllocator DIEValueAllocator
MCSection * Section
The section this unit will be emitted in.
Detailed Description
This dwarf writer support class manages information associated with a source file.
Definition at line 68 of file DwarfUnit.h.
Constructor & Destructor Documentation
DwarfUnit::DwarfUnit (unsigned UID, dwarf::Tag UnitTag, const DICompileUnit * CU, AsmPrinter * A, DwarfDebug * DW, DwarfFile * DWU) [protected]
Definition at line 66 of file DwarfUnit.cpp.
DwarfUnit::~DwarfUnit () [virtual]
Definition at line 84 of file DwarfUnit.cpp.
References DIEBlocks, and DIELocs.
Member Function Documentation
void llvm::DwarfUnit::addAccelNamespace (StringRef Name, const DIE & Die)
Add a new name to the namespace accelerator table.
void DwarfUnit::addBlock (DIE & Die, dwarf::Attribute Attribute, DIELoc * Block)
Add block data.
Definition at line 299 of file DwarfUnit.cpp.
References Asm, llvm::DIELoc::BestForm(), llvm::DIELoc::ComputeSize(), DD, DIELocs, and llvm::DwarfDebug::getDwarfVersion().
Referenced by llvm::DwarfCompileUnit::addAddress(), addBlockByrefAddress(), llvm::DwarfCompileUnit::addComplexAddress(), addConstantFPValue(), addConstantValue(), applySubprogramAttributes(), and llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
void DwarfUnit::addBlock (DIE & Die, dwarf::Attribute Attribute, DIEBlock * Block)
Add block data.
Definition at line 305 of file DwarfUnit.cpp.
References Asm, llvm::DIEBlock::BestForm(), llvm::Block, llvm::DIEBlock::ComputeSize(), and DIEBlocks.
void DwarfUnit::addBlockByrefAddress (const DbgVariable & DV, DIE & Die, dwarf::Attribute Attribute, const MachineLocation & Location)
Start with the address based on the location provided, and generate the DWARF information necessary to find the actual Block variable (navigating the Block struct) based on the starting location.
Add the DWARF information to the die. Obsolete, please use addComplexAddress instead.
Definition at line 425 of file DwarfUnit.cpp.
References addBlock(), addRegisterOffset(), addRegisterOpPiece(), addUInt(), DIEValueAllocator, llvm::dwarf::DW_FORM_data1, llvm::dwarf::DW_FORM_udata, llvm::DbgVariable::getName(), llvm::MachineLocation::getOffset(), llvm::DIType::getOffsetInBits(), llvm::MachineLocation::getReg(), llvm::DINode::getTag(), llvm::DbgVariable::getType(), llvm::MachineLocation::isReg(), N, and resolve().
Referenced by llvm::DwarfCompileUnit::addVariableAddress().
void DwarfUnit::addConstantFPValue (DIE & Die, const MachineOperand & MO)
Add constant value entry in variable DIE.
Definition at line 577 of file DwarfUnit.cpp.
References addBlock(), addUInt(), Asm, llvm::APFloat::bitcastToAPInt(), llvm::Block, DIEValueAllocator, llvm::dwarf::DW_AT_const_value, llvm::dwarf::DW_FORM_data1, llvm::APInt::getBitWidth(), llvm::AsmPrinter::getDataLayout(), llvm::MachineOperand::getFPImm(), llvm::APInt::getRawData(), llvm::ConstantFP::getValueAPF(), llvm::MachineOperand::isFPImm(), and llvm::DataLayout::isLittleEndian().
Referenced by getOrCreateStaticMemberDIE().
void DwarfUnit::addConstantFPValue (DIE & Die, const ConstantFP * CFP)
Definition at line 599 of file DwarfUnit.cpp.
References addConstantValue(), llvm::APFloat::bitcastToAPInt(), and llvm::ConstantFP::getValueAPF().
void DwarfUnit::addConstantValue (DIE & Die, const MachineOperand & MO, const DIType * Ty)
Add constant value entry in variable DIE.
Definition at line 609 of file DwarfUnit.cpp.
References DD, llvm::MachineOperand::getImm(), llvm::MachineOperand::isImm(), and isUnsignedDIType().
Referenced by addConstantFPValue(), addConstantValue(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), and getOrCreateStaticMemberDIE().
void DwarfUnit::addConstantValue (DIE & Die, const ConstantInt * CI, const DIType * Ty)
Definition at line 604 of file DwarfUnit.cpp.
References addConstantValue(), and llvm::ConstantInt::getValue().
void DwarfUnit::addConstantValue (DIE & Die, const APInt & Val, const DIType * Ty)
Definition at line 623 of file DwarfUnit.cpp.
References addConstantValue(), DD, and isUnsignedDIType().
void DwarfUnit::addConstantValue (DIE & Die, const APInt & Val, bool Unsigned)
Definition at line 627 of file DwarfUnit.cpp.
References addBlock(), addConstantValue(), addUInt(), Asm, llvm::Block, DIEValueAllocator, llvm::dwarf::DW_AT_const_value, llvm::dwarf::DW_FORM_data1, llvm::APInt::getBitWidth(), llvm::AsmPrinter::getDataLayout(), llvm::APInt::getRawData(), llvm::APInt::getSExtValue(), llvm::APInt::getZExtValue(), and llvm::DataLayout::isLittleEndian().
void DwarfUnit::addConstantValue (DIE & Die, bool Unsigned, uint64_t Val)
Definition at line 616 of file DwarfUnit.cpp.
References addUInt(), llvm::dwarf::DW_AT_const_value, llvm::dwarf::DW_FORM_sdata, and llvm::dwarf::DW_FORM_udata.
void DwarfUnit::addDIEEntry (DIE & Die, dwarf::Attribute Attribute, DIE & Entry)
Add a DIE attribute data and value.
Definition at line 261 of file DwarfUnit.cpp.
Referenced by addType(), applySubprogramDefinitionAttributes(), llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), constructContainingTypeDIEs(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), llvm::DwarfCompileUnit::constructInlinedScopeDIE(), llvm::DwarfCompileUnit::constructSubprogramScopeDIE(), constructTypeDIE(), llvm::DwarfCompileUnit::finishSubprogramDefinition(), and llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
void DwarfUnit::addDIEEntry (DIE & Die, dwarf::Attribute Attribute, DIEEntry Entry)
Add a DIE attribute data and value.
Definition at line 276 of file DwarfUnit.cpp.
References llvm::dwarf::DW_FORM_ref4, llvm::dwarf::DW_FORM_ref_addr, llvm::DIEEntry::getEntry(), and getUnitDie().
void DwarfUnit::addDIETypeSignature (DIE & Die, const DwarfTypeUnit & Type)
Definition at line 265 of file DwarfUnit.cpp.
References addFlag(), llvm::dwarf::DW_AT_declaration, llvm::dwarf::DW_AT_signature, and llvm::dwarf::DW_FORM_ref_sig8.
Referenced by llvm::DwarfDebug::addDwarfTypeUnitType().
void DwarfUnit::addFlag (DIE & Die, dwarf::Attribute Attribute)
Add a flag that is true to the DIE.
Definition at line 185 of file DwarfUnit.cpp.
References DD, llvm::dwarf::DW_FORM_flag, llvm::dwarf::DW_FORM_flag_present, and llvm::DwarfDebug::getDwarfVersion().
Referenced by addDIETypeSignature(), applySubprogramAttributes(), llvm::DwarfCompileUnit::applyVariableAttributes(), constructSubprogramArguments(), constructTypeDIE(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), getOrCreateStaticMemberDIE(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
virtual void llvm::DwarfUnit::addGlobalName (StringRef Name, DIE & Die, const DIScope * Context) [inline, virtual]
Add a new global name to the compile unit.
Reimplemented in llvm::DwarfCompileUnit.
Definition at line 158 of file DwarfUnit.h.
Referenced by getOrCreateNameSpace().
virtual void llvm::DwarfUnit::addGlobalType (const DIType * Ty, const DIE & Die, const DIScope * Context) [inline, virtual]
Add a new global type to the compile unit.
Reimplemented in llvm::DwarfCompileUnit.
Definition at line 162 of file DwarfUnit.h.
void llvm::DwarfUnit::addIndexedString (DIE & Die, dwarf::Attribute Attribute, StringRef Str) [protected]
void DwarfUnit::addLabel (DIE & Die, dwarf::Attribute Attribute, dwarf::Form Form, const MCSymbol * Label)
Add a Dwarf label attribute data and value.
Definition at line 222 of file DwarfUnit.cpp.
Referenced by addLabel(), addOpAddress(), and llvm::DwarfCompileUnit::addSectionLabel().
void DwarfUnit::addLabel (DIELoc & Die, dwarf::Form Form, const MCSymbol * Label)
Definition at line 227 of file DwarfUnit.cpp.
References addLabel().
void DwarfUnit::addLabelDelta (DIE & Die, dwarf::Attribute Attribute, const MCSymbol * Hi, const MCSymbol * Lo)
Add a label delta attribute data and value.
Definition at line 255 of file DwarfUnit.cpp.
References DIEValueAllocator, and llvm::dwarf::DW_FORM_data4.
Referenced by llvm::DwarfCompileUnit::attachLowHighPC().
void DwarfUnit::addLinkageName (DIE & Die, StringRef LinkageName)
Add a linkage name, if it isn't empty.
Definition at line 656 of file DwarfUnit.cpp.
References addString(), DD, llvm::dwarf::DW_AT_linkage_name, llvm::dwarf::DW_AT_MIPS_linkage_name, llvm::StringRef::empty(), llvm::DwarfDebug::getDwarfVersion(), and llvm::GlobalValue::getRealLinkageName().
Referenced by applySubprogramDefinitionAttributes(), and llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
void llvm::DwarfUnit::addLocalString (DIE & Die, dwarf::Attribute Attribute, StringRef Str) [protected]
Add a string attribute data and value.
This is guaranteed to be in the local string pool instead of indirected.
void DwarfUnit::addOpAddress (DIELoc & Die, const MCSymbol * Label)
Add a dwarf op address data and value using the form given and an op of either DW_FORM_addr or DW_FORM_GNU_addr_index.
Definition at line 244 of file DwarfUnit.cpp.
References addLabel(), addUInt(), DD, llvm::dwarf::DW_FORM_data1, llvm::dwarf::DW_FORM_GNU_addr_index, llvm::dwarf::DW_FORM_udata, llvm::DwarfDebug::getAddressPool(), llvm::AddressPool::getIndex(), and llvm::DwarfDebug::useSplitDwarf().
Referenced by llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
bool DwarfUnit::addRegisterOffset (DIELoc & TheDie, unsigned Reg, int64_t Offset)
Add register offset.
Returns:
false if the register does not exist, e.g., because it was never materialized.
Definition at line 365 of file DwarfUnit.cpp.
References llvm::DwarfExpression::AddMachineRegIndirect(), and Asm.
Referenced by llvm::DwarfCompileUnit::addAddress(), and addBlockByrefAddress().
bool DwarfUnit::addRegisterOpPiece (DIELoc & TheDie, unsigned Reg, unsigned SizeInBits = 0, unsigned OffsetInBits = 0)
Add register operand.
Returns:
false if the register does not exist, e.g., because it was never materialized.
Definition at line 358 of file DwarfUnit.cpp.
References llvm::DwarfExpression::AddMachineRegPiece(), and Asm.
Referenced by llvm::DwarfCompileUnit::addAddress(), and addBlockByrefAddress().
void DwarfUnit::addSectionOffset (DIE & Die, dwarf::Attribute Attribute, uint64_t Integer)
Add an offset into a section attribute data and value.
Definition at line 231 of file DwarfUnit.cpp.
References addUInt(), DD, llvm::dwarf::DW_FORM_data4, llvm::dwarf::DW_FORM_sec_offset, and llvm::DwarfDebug::getDwarfVersion().
Referenced by llvm::DwarfTypeUnit::DwarfTypeUnit().
void DwarfUnit::addSInt (DIE & Die, dwarf::Attribute Attribute, Optional< dwarf::Form > Form, int64_t Integer)
Add an signed integer attribute data and value.
Definition at line 203 of file DwarfUnit.cpp.
References llvm::DIEInteger::BestForm().
Referenced by addSInt(), and llvm::DIEDwarfExpression::EmitSigned().
void DwarfUnit::addSInt (DIELoc & Die, Optional< dwarf::Form > Form, int64_t Integer)
Definition at line 210 of file DwarfUnit.cpp.
References addSInt().
void DwarfUnit::addSourceLine (DIE & Die, unsigned Line, StringRef File, StringRef Directory)
Add location information to specified debug information entry.
Definition at line 312 of file DwarfUnit.cpp.
References addUInt(), llvm::dwarf::DW_AT_decl_file, llvm::dwarf::DW_AT_decl_line, getOrCreateSourceID(), and llvm::None.
Referenced by addSourceLine(), applySubprogramAttributes(), llvm::DwarfCompileUnit::applyVariableAttributes(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), constructTypeDIE(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), getOrCreateNameSpace(), and getOrCreateStaticMemberDIE().
void DwarfUnit::addSourceLine (DIE & Die, const DILocalVariable * V)
Definition at line 323 of file DwarfUnit.cpp.
References addSourceLine(), llvm::DIScope::getDirectory(), llvm::DIScope::getFilename(), llvm::DIVariable::getLine(), and llvm::DILocalVariable::getScope().
void DwarfUnit::addSourceLine (DIE & Die, const DIGlobalVariable * G)
Definition at line 330 of file DwarfUnit.cpp.
References addSourceLine(), llvm::DIVariable::getDirectory(), llvm::DIVariable::getFilename(), and llvm::DIVariable::getLine().
void DwarfUnit::addSourceLine (DIE & Die, const DISubprogram * SP)
Definition at line 336 of file DwarfUnit.cpp.
References addSourceLine(), llvm::DIScope::getDirectory(), and llvm::DIScope::getFilename().
void DwarfUnit::addSourceLine (DIE & Die, const DIType * Ty)
Definition at line 342 of file DwarfUnit.cpp.
References addSourceLine(), llvm::DIScope::getDirectory(), llvm::DIScope::getFilename(), and llvm::DIType::getLine().
void DwarfUnit::addSourceLine (DIE & Die, const DINamespace * NS)
Definition at line 354 of file DwarfUnit.cpp.
References addSourceLine(), llvm::DIScope::getDirectory(), llvm::DIScope::getFilename(), and llvm::DINamespace::getLine().
void DwarfUnit::addSourceLine (DIE & Die, const DIObjCProperty * Ty)
Definition at line 348 of file DwarfUnit.cpp.
References addSourceLine(), llvm::DIObjCProperty::getDirectory(), llvm::DIObjCProperty::getFilename(), and llvm::DIObjCProperty::getLine().
void DwarfUnit::addString (DIE & Die, dwarf::Attribute Attribute, StringRef Str)
Add a string attribute data and value.
We always emit a reference to the string pool instead of immediate strings so that DIEs have more predictable sizes. In the case of split dwarf we emit an index into another table which gets us the static offset into the string table.
Definition at line 215 of file DwarfUnit.cpp.
References Asm, DU, llvm::dwarf::DW_FORM_GNU_str_index, llvm::dwarf::DW_FORM_strp, llvm::DwarfStringPool::getEntry(), and llvm::DwarfFile::getStringPool().
Referenced by addLinkageName(), applySubprogramAttributes(), llvm::DwarfCompileUnit::applyVariableAttributes(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), constructTypeDIE(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), getOrCreateNameSpace(), and getOrCreateStaticMemberDIE().
void DwarfUnit::addTemplateParams (DIE & Buffer, DINodeArray TParams)
Add template parameters in buffer.
Definition at line 664 of file DwarfUnit.cpp.
Referenced by applySubprogramDefinitionAttributes(), and constructTypeDIE().
void DwarfUnit::addType (DIE & Entity, const DIType * Ty, dwarf::Attribute Attribute = dwarf::DW_AT_type)
Add a new type attribute to the specified entity.
This takes and attribute parameter because DW_AT_friend attributes are also type references.
Definition at line 765 of file DwarfUnit.cpp.
References addDIEEntry(), and getOrCreateTypeDIE().
Referenced by applySubprogramAttributes(), llvm::DwarfCompileUnit::applyVariableAttributes(), constructSubprogramArguments(), constructTypeDIE(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), and getOrCreateStaticMemberDIE().
void DwarfUnit::addUInt (DIE & Die, dwarf::Attribute Attribute, Optional< dwarf::Form > Form, uint64_t Integer)
Add an unsigned integer attribute data and value.
Definition at line 192 of file DwarfUnit.cpp.
References llvm::DIEInteger::BestForm().
Referenced by addBlockByrefAddress(), addConstantFPValue(), addConstantValue(), addOpAddress(), addSectionOffset(), addSourceLine(), addUInt(), applySubprogramAttributes(), llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), llvm::DwarfCompileUnit::constructInlinedScopeDIE(), constructTypeDIE(), llvm::DIEDwarfExpression::EmitOp(), llvm::DIEDwarfExpression::EmitUnsigned(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), and getOrCreateStaticMemberDIE().
void DwarfUnit::addUInt (DIE & Block, dwarf::Form Form, uint64_t Integer)
Definition at line 199 of file DwarfUnit.cpp.
References addUInt().
void DwarfUnit::applySubprogramAttributes (const DISubprogram * SP, DIE & SPDie, bool Minimal = false)
Definition at line 1130 of file DwarfUnit.cpp.
References addBlock(), addFlag(), addSourceLine(), addString(), addType(), addUInt(), applySubprogramDefinitionAttributes(), Asm, llvm::Block, constructSubprogramArguments(), ContainingTypeMap, llvm::dwarf::DW_ACCESS_private, llvm::dwarf::DW_ACCESS_protected, llvm::dwarf::DW_ACCESS_public, llvm::dwarf::DW_AT_accessibility, llvm::dwarf::DW_AT_APPLE_isa, llvm::dwarf::DW_AT_APPLE_optimized, llvm::dwarf::DW_AT_artificial, llvm::dwarf::DW_AT_declaration, llvm::dwarf::DW_AT_explicit, llvm::dwarf::DW_AT_external, llvm::dwarf::DW_AT_name, llvm::dwarf::DW_AT_prototyped, llvm::dwarf::DW_AT_reference, llvm::dwarf::DW_AT_rvalue_reference, llvm::dwarf::DW_AT_virtuality, llvm::dwarf::DW_AT_vtable_elem_location, llvm::dwarf::DW_FORM_data1, llvm::dwarf::DW_FORM_flag, llvm::dwarf::DW_FORM_udata, llvm::StringRef::empty(), getDIELoc(), llvm::AsmPrinter::getISAEncoding(), getLanguage(), llvm::DIScope::getName(), llvm::DINode::getTag(), llvm::DISubroutineType::getTypeArray(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::isa(), and resolve().
Referenced by llvm::DwarfCompileUnit::applySubprogramAttributesToDefinition(), and getOrCreateSubprogramDIE().
bool DwarfUnit::applySubprogramDefinitionAttributes (const DISubprogram * SP, DIE & SPDie) [protected]
Definition at line 1098 of file DwarfUnit.cpp.
References addDIEEntry(), addLinkageName(), addTemplateParams(), llvm::dwarf::DW_AT_specification, llvm::StringRef::empty(), getDIE(), and llvm::LinkageName.
Referenced by applySubprogramAttributes().
void DwarfUnit::constructContainingTypeDIEs ()
Construct DIEs for types that contain vtables.
Definition at line 1294 of file DwarfUnit.cpp.
References addDIEEntry(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin(), llvm::WinEH::CE, ContainingTypeMap, llvm::dwarf::DW_AT_containing_type, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), and getDIE().
void DwarfUnit::constructSubprogramArguments (DIE & Buffer, DITypeRefArray Args)
Construct function argument DIEs.
Definition at line 853 of file DwarfUnit.cpp.
References addFlag(), addType(), createAndAddDIE(), llvm::dwarf::DW_AT_artificial, llvm::DIType::isArtificial(), N, resolve(), and llvm::DITypeRefArray::size().
Referenced by applySubprogramAttributes().
void DwarfUnit::constructTypeDIE (DIE & Buffer, const DICompositeType * CTy)
Definition at line 896 of file DwarfUnit.cpp.
References addDIEEntry(), addFlag(), addSourceLine(), addString(), addTemplateParams(), addType(), addUInt(), createAndAddDIE(), llvm::dwarf::DW_AT_APPLE_block, llvm::dwarf::DW_AT_APPLE_objc_complete_type, llvm::dwarf::DW_AT_APPLE_property_attribute, llvm::dwarf::DW_AT_APPLE_property_getter, llvm::dwarf::DW_AT_APPLE_property_name, llvm::dwarf::DW_AT_APPLE_property_setter, llvm::dwarf::DW_AT_APPLE_runtime_class, llvm::dwarf::DW_AT_byte_size, llvm::dwarf::DW_AT_containing_type, llvm::dwarf::DW_AT_declaration, llvm::dwarf::DW_AT_friend, llvm::dwarf::DW_AT_name, llvm::dwarf::DW_FORM_data1, llvm::StringRef::empty(), llvm::DICompositeTypeBase::getElements(), llvm::DIType::getName(), getOrCreateStaticMemberDIE(), getOrCreateSubprogramDIE(), getOrCreateTypeDIE(), llvm::DICompositeTypeBase::getRuntimeLang(), llvm::DIType::getSizeInBits(), llvm::DICompositeTypeBase::getTemplateParams(), llvm::DICompositeTypeBase::getVTableHolder(), llvm::DIType::isAppleBlockExtension(), llvm::DIType::isForwardDecl(), llvm::DIType::isObjcClassComplete(), llvm::None, resolve(), and llvm::SP.
Referenced by llvm::DwarfDebug::addDwarfTypeUnitType(), createTypeDIE(), and getOrCreateTypeDIE().
DIE & DwarfUnit::createAndAddDIE (unsigned Tag, DIE & Parent, const DINode * N = nullptr)
Create a DIE with the given Tag, add the DIE to its parent, and call insertDIE if MD is not null.
Definition at line 290 of file DwarfUnit.cpp.
References insertDIE().
Referenced by llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), constructSubprogramArguments(), constructTypeDIE(), createTypeDIE(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), getOrCreateNameSpace(), getOrCreateStaticMemberDIE(), getOrCreateSubprogramDIE(), and getOrCreateTypeDIE().
DIE * DwarfUnit::createTypeDIE (const DICompositeType * Ty)
Get context owner's DIE.
Definition at line 686 of file DwarfUnit.cpp.
References constructTypeDIE(), createAndAddDIE(), getDIE(), getOrCreateContextDIE(), llvm::DIType::getScope(), llvm::DINode::getTag(), and resolve().
void DwarfUnit::emitHeader (bool UseOffsets) [virtual]
Emit the header for this unit, not including the initial length field.
Reimplemented in llvm::DwarfTypeUnit, and llvm::DwarfCompileUnit.
Definition at line 1439 of file DwarfUnit.cpp.
References Asm, DD, llvm::AsmPrinter::emitDwarfSymbolReference(), llvm::AsmPrinter::EmitInt16(), llvm::AsmPrinter::EmitInt32(), llvm::AsmPrinter::EmitInt8(), llvm::MCSection::getBeginSymbol(), llvm::AsmPrinter::getDataLayout(), llvm::MCObjectFileInfo::getDwarfAbbrevSection(), llvm::DwarfDebug::getDwarfVersion(), getHeaderSize(), llvm::AsmPrinter::getObjFileLowering(), llvm::DataLayout::getPointerSize(), llvm::AsmPrinter::OutStreamer, and UnitDie.
AsmPrinter* llvm::DwarfUnit::getAsmPrinter () const [inline]
Definition at line 136 of file DwarfUnit.h.
References Asm.
virtual DwarfCompileUnit& llvm::DwarfUnit::getCU () [pure virtual]
Implemented in llvm::DwarfTypeUnit, and llvm::DwarfCompileUnit.
Referenced by getOrCreateTypeDIE().
const DICompileUnit* llvm::DwarfUnit::getCUNode () const [inline]
Definition at line 139 of file DwarfUnit.h.
References CUNode.
unsigned llvm::DwarfUnit::getDebugInfoOffset () const [inline]
Definition at line 142 of file DwarfUnit.h.
References DebugInfoOffset.
DIE * DwarfUnit::getDIE (const DINode * D) const
Returns the DIE map slot for the specified debug variable.
We delegate the request to DwarfDebug when the MDNode can be part of the type system, since DIEs for the type system can be shared across CUs and the mappings are kept in DwarfDebug.
Definition at line 171 of file DwarfUnit.cpp.
References DU, llvm::DwarfFile::getDIE(), isShareableAcrossCUs(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), and MDNodeToDieMap.
Referenced by applySubprogramDefinitionAttributes(), llvm::DwarfCompileUnit::collectDeadVariables(), constructContainingTypeDIEs(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), createTypeDIE(), llvm::DwarfCompileUnit::finishSubprogramDefinition(), getOrCreateContextDIE(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), getOrCreateNameSpace(), getOrCreateStaticMemberDIE(), getOrCreateSubprogramDIE(), and getOrCreateTypeDIE().
DIELoc* llvm::DwarfUnit::getDIELoc () [inline]
Returns a fresh newly allocated DIELoc.
Definition at line 176 of file DwarfUnit.h.
References DIEValueAllocator.
Referenced by applySubprogramAttributes().
virtual unsigned llvm::DwarfUnit::getHeaderSize () const [inline, virtual]
Compute the size of a header for this unit, not including the initial length field.
Reimplemented in llvm::DwarfTypeUnit.
Definition at line 320 of file DwarfUnit.h.
Referenced by emitHeader(), and llvm::DwarfCompileUnit::getLength().
uint16_t llvm::DwarfUnit::getLanguage () const [inline]
Definition at line 138 of file DwarfUnit.h.
References CUNode, and llvm::DICompileUnit::getSourceLanguage().
Referenced by llvm::DwarfDebug::addDwarfTypeUnitType(), applySubprogramAttributes(), computeIndexValue(), and getParentContextString().
DIE * DwarfUnit::getOrCreateContextDIE (const DIScope * Context)
Get context owner's DIE.
Definition at line 674 of file DwarfUnit.cpp.
References getDIE(), getOrCreateNameSpace(), getOrCreateSubprogramDIE(), getOrCreateTypeDIE(), getUnitDie(), and llvm::SP.
Referenced by llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), createTypeDIE(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), getOrCreateNameSpace(), getOrCreateStaticMemberDIE(), getOrCreateSubprogramDIE(), and getOrCreateTypeDIE().
DIE * DwarfUnit::getOrCreateNameSpace (const DINamespace * NS)
Definition at line 1047 of file DwarfUnit.cpp.
References llvm::DwarfDebug::addAccelNamespace(), addGlobalName(), addSourceLine(), addString(), createAndAddDIE(), DD, llvm::dwarf::DW_AT_name, llvm::StringRef::empty(), getDIE(), llvm::DINamespace::getName(), getOrCreateContextDIE(), and llvm::DINamespace::getScope().
Referenced by llvm::DwarfCompileUnit::constructImportedEntityDIE(), and getOrCreateContextDIE().
virtual unsigned llvm::DwarfUnit::getOrCreateSourceID (StringRef File, StringRef Directory) [protected, pure virtual]
Look up the source ID with the given directory and source file names.
If none currently exists, create a new ID and insert it in the line table.
Implemented in llvm::DwarfCompileUnit.
Referenced by addSourceLine().
DIE * DwarfUnit::getOrCreateStaticMemberDIE (const DIDerivedType * DT) [protected]
Create new static data member DIE.
Definition at line 1396 of file DwarfUnit.cpp.
References addConstantFPValue(), addConstantValue(), addFlag(), addSourceLine(), addString(), addType(), addUInt(), createAndAddDIE(), llvm::dwarf::DW_ACCESS_private, llvm::dwarf::DW_ACCESS_protected, llvm::dwarf::DW_ACCESS_public, llvm::dwarf::DW_AT_accessibility, llvm::dwarf::DW_AT_declaration, llvm::dwarf::DW_AT_external, llvm::dwarf::DW_AT_name, llvm::dwarf::DW_FORM_data1, llvm::DIDerivedTypeBase::getBaseType(), getDIE(), llvm::DIType::getName(), getOrCreateContextDIE(), llvm::DIType::getScope(), llvm::DINode::getTag(), llvm::DIType::isPrivate(), llvm::DIType::isProtected(), llvm::DIType::isPublic(), llvm::dwarf::isType(), and resolve().
Referenced by constructTypeDIE(), and llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
DIE * DwarfUnit::getOrCreateSubprogramDIE (const DISubprogram * SP, bool Minimal = false)
Definition at line 1067 of file DwarfUnit.cpp.
References applySubprogramAttributes(), createAndAddDIE(), getDIE(), getOrCreateContextDIE(), llvm::DIScope::getScope(), getUnitDie(), and resolve().
Referenced by llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), constructTypeDIE(), llvm::DwarfCompileUnit::finishSubprogramDefinition(), getOrCreateContextDIE(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
DIE * DwarfUnit::getOrCreateTypeDIE (const MDNode * N)
Find existing DIE or create new DIE for the given type.
Definition at line 702 of file DwarfUnit.cpp.
References llvm::DwarfDebug::addDwarfTypeUnitType(), llvm::X86ISD::BT, constructTypeDIE(), createAndAddDIE(), DD, GenerateDwarfTypeUnits, getCU(), getDIE(), llvm::DwarfDebug::getDwarfVersion(), getOrCreateContextDIE(), and resolve().
Referenced by addType(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), constructTypeDIE(), and getOrCreateContextDIE().
std::string DwarfUnit::getParentContextString (const DIScope * Context) const
Get string containing language specific context for a global name.
Walks the metadata parent chain in a language specific manner (using the compile unit language) and returns it as a string. This is done at the metadata level because DIEs may not currently have been added to the parent context and walking the DIEs looking for names is more expensive than walking the metadata.
Definition at line 771 of file DwarfUnit.cpp.
References llvm::CS, llvm::StringRef::empty(), getLanguage(), llvm::DIScope::getName(), llvm::DIScope::getScope(), I, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateCommon< T >::rbegin(), llvm::SmallVectorTemplateCommon< T >::rend(), and resolve().
Referenced by llvm::DwarfCompileUnit::addGlobalName(), and llvm::DwarfCompileUnit::addGlobalType().
MCSection* llvm::DwarfUnit::getSection () const [inline]
Definition at line 130 of file DwarfUnit.h.
References Section.
unsigned llvm::DwarfUnit::getUniqueID () const [inline]
Definition at line 137 of file DwarfUnit.h.
References UniqueID.
Referenced by llvm::DwarfDebug::beginFunction(), llvm::DwarfCompileUnit::getOrCreateSourceID(), and llvm::DwarfCompileUnit::initStmtList().
DIE& llvm::DwarfUnit::getUnitDie () [inline]
Definition at line 140 of file DwarfUnit.h.
References UnitDie.
Referenced by addDIEEntry(), llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), llvm::DwarfCompileUnit::DwarfCompileUnit(), getOrCreateContextDIE(), and getOrCreateSubprogramDIE().
bool llvm::DwarfUnit::hasContent () const [inline]
Return true if this compile unit has something to write out.
Definition at line 146 of file DwarfUnit.h.
References UnitDie.
void DwarfUnit::initSection (MCSection * Section)
Definition at line 1459 of file DwarfUnit.cpp.
References Section.
void DwarfUnit::insertDIE (const DINode * Desc, DIE * D)
Insert DIE into the map.
We delegate the request to DwarfDebug when the MDNode can be part of the type system, since DIEs for the type system can be shared across CUs and the mappings are kept in DwarfDebug.
Definition at line 177 of file DwarfUnit.cpp.
References DU, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::DwarfFile::insertDIE(), isShareableAcrossCUs(), and MDNodeToDieMap.
Referenced by llvm::DwarfCompileUnit::constructImportedEntityDIE(), createAndAddDIE(), and llvm::DwarfCompileUnit::DwarfCompileUnit().
template<typename T > T* llvm::DwarfUnit::resolve (TypedDINodeRef< T > Ref) const [inline, protected]
Look in the DwarfDebug map for the MDNode that corresponds to the reference.
Definition at line 343 of file DwarfUnit.h.
References DD, and llvm::DwarfDebug::resolve().
Referenced by addBlockByrefAddress(), applySubprogramAttributes(), llvm::DwarfCompileUnit::applySubprogramAttributesToDefinition(), llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), constructSubprogramArguments(), constructTypeDIE(), createTypeDIE(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), getOrCreateStaticMemberDIE(), getOrCreateSubprogramDIE(), getOrCreateTypeDIE(), and getParentContextString().
void llvm::DwarfUnit::setDebugInfoOffset (unsigned DbgInfoOff) [inline]
Definition at line 143 of file DwarfUnit.h.
References DebugInfoOffset.
Member Data Documentation
AsmPrinter* llvm::DwarfUnit::Asm [protected]
Target of Dwarf emission.
Definition at line 83 of file DwarfUnit.h.
Referenced by addBlock(), llvm::DwarfCompileUnit::addComplexAddress(), addConstantFPValue(), addConstantValue(), addRegisterOffset(), addRegisterOpPiece(), llvm::DwarfCompileUnit::addScopeRangeList(), llvm::DwarfCompileUnit::addSectionLabel(), addString(), applySubprogramAttributes(), llvm::DwarfCompileUnit::emitHeader(), emitHeader(), llvm::DwarfTypeUnit::emitHeader(), getAsmPrinter(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), llvm::DwarfCompileUnit::getOrCreateSourceID(), llvm::DwarfCompileUnit::initStmtList(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
DenseMap<DIE *, const DINode *> llvm::DwarfUnit::ContainingTypeMap [protected]
This map is used to keep track of subprogram DIEs that need DW_AT_containing_type attribute.
This attribute points to a DIE that corresponds to the MDNode mapped with the subprogram DIE.
Definition at line 105 of file DwarfUnit.h.
Referenced by applySubprogramAttributes(), and constructContainingTypeDIEs().
const DICompileUnit* llvm::DwarfUnit::CUNode [protected]
MDNode for the compile unit.
Definition at line 74 of file DwarfUnit.h.
Referenced by getCUNode(), and getLanguage().
DwarfDebug* llvm::DwarfUnit::DD [protected]
Definition at line 86 of file DwarfUnit.h.
Referenced by addBlock(), addConstantValue(), addFlag(), llvm::DwarfCompileUnit::addLabelAddress(), addLinkageName(), llvm::DwarfCompileUnit::addLocalLabelAddress(), llvm::DwarfCompileUnit::addLocationList(), addOpAddress(), llvm::DwarfCompileUnit::addRange(), llvm::DwarfCompileUnit::addSectionDelta(), llvm::DwarfCompileUnit::addSectionLabel(), addSectionOffset(), llvm::DwarfCompileUnit::attachLowHighPC(), llvm::DwarfCompileUnit::attachRangesOrLowHighPC(), llvm::DwarfCompileUnit::collectDeadVariables(), llvm::DwarfCompileUnit::constructInlinedScopeDIE(), llvm::DwarfCompileUnit::constructLexicalScopeDIE(), llvm::DwarfCompileUnit::constructScopeDIE(), llvm::DwarfCompileUnit::constructSubprogramScopeDIE(), emitHeader(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), getOrCreateNameSpace(), getOrCreateTypeDIE(), resolve(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
unsigned llvm::DwarfUnit::DebugInfoOffset [protected]
Offset of the UnitDie from beginning of debug info section.
Definition at line 80 of file DwarfUnit.h.
Referenced by getDebugInfoOffset(), and setDebugInfoOffset().
std::vector<DIEBlock *> llvm::DwarfUnit::DIEBlocks [protected]
A list of all the DIEBlocks in use.
Definition at line 97 of file DwarfUnit.h.
Referenced by addBlock(), and ~DwarfUnit().
std::vector<DIELoc *> llvm::DwarfUnit::DIELocs [protected]
A list of all the DIELocs in use.
Definition at line 100 of file DwarfUnit.h.
Referenced by addBlock(), and ~DwarfUnit().
BumpPtrAllocator llvm::DwarfUnit::DIEValueAllocator [protected]
Definition at line 108 of file DwarfUnit.h.
Referenced by llvm::DwarfCompileUnit::addAddress(), addBlockByrefAddress(), llvm::DwarfCompileUnit::addComplexAddress(), addConstantFPValue(), addConstantValue(), addLabelDelta(), llvm::DwarfCompileUnit::addSectionDelta(), getDIELoc(), and llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
DwarfFile* llvm::DwarfUnit::DU [protected]
Definition at line 87 of file DwarfUnit.h.
Referenced by addString(), llvm::DwarfCompileUnit::collectDeadVariables(), llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), llvm::DwarfCompileUnit::constructInlinedScopeDIE(), llvm::DwarfCompileUnit::createScopeChildrenDIE(), llvm::DwarfCompileUnit::finishSubprogramDefinition(), getDIE(), and insertDIE().
DIE* llvm::DwarfUnit::IndexTyDie [protected]
An anonymous type for index type. Owned by UnitDie.
Definition at line 90 of file DwarfUnit.h.
DenseMap<const MDNode *, DIE *> llvm::DwarfUnit::MDNodeToDieMap [protected]
Tracks the mapping of unit level debug information variables to debug information entries.
Definition at line 94 of file DwarfUnit.h.
Referenced by getDIE(), and insertDIE().
MCSection* llvm::DwarfUnit::Section [protected]
The section this unit will be emitted in.
Definition at line 111 of file DwarfUnit.h.
Referenced by llvm::DwarfCompileUnit::getLabelBegin(), getSection(), llvm::DwarfCompileUnit::getSectionSym(), and initSection().
unsigned llvm::DwarfUnit::UniqueID [protected]
A numeric ID unique among all CUs in the module.
Definition at line 71 of file DwarfUnit.h.
Referenced by getUniqueID().
DIE llvm::DwarfUnit::UnitDie [protected]
Unit debug information entry.
Definition at line 77 of file DwarfUnit.h.
Referenced by llvm::DwarfCompileUnit::applyStmtList(), llvm::DwarfTypeUnit::DwarfTypeUnit(), emitHeader(), llvm::DwarfCompileUnit::getLength(), getUnitDie(), hasContent(), and llvm::DwarfCompileUnit::initStmtList().
The documentation for this class was generated from the following files:
DwarfUnit.h
DwarfUnit.cpp