LLVM: llvm::SwitchInst::CaseIteratorT< SwitchInstTy, ConstantIntTy, BasicBlockTy > Class Template Reference
llvm::SwitchInst::CaseIteratorT< SwitchInstTy, ConstantIntTy, BasicBlockTy > Class Template Reference
#include <Instructions.h>
Public Types
typedef CaseIteratorT
< SwitchInstTy, ConstantIntTy,
BasicBlockTy > Self
Public Member Functions
CaseIteratorT (SwitchInstTy *SI, unsigned CaseNum)
Initializes case iterator for given SwitchInst and for given case number.
ConstantIntTy * getCaseValue ()
Resolves case value for current case.
BasicBlockTy * getCaseSuccessor ()
Resolves successor for current case.
unsigned getCaseIndex () const
Returns number of current case.
unsigned getSuccessorIndex () const
Returns TerminatorInst's successor index for current case successor.
Self operator++ ()
Self operator++ (int)
Self operator-- ()
Self operator-- (int)
bool operator== (const Self &RHS) const
bool operator!= (const Self &RHS) const
Self & operator* ()
Static Public Member Functions
static Self fromSuccessorIndex (SwitchInstTy *SI, unsigned SuccessorIndex)
Initializes case iterator for given SwitchInst and for given TerminatorInst's successor index.
Protected Attributes
SwitchInstTy * SI
unsigned Index
Detailed Description
template<class SwitchInstTy, class ConstantIntTy, class BasicBlockTy>
class llvm::SwitchInst::CaseIteratorT< SwitchInstTy, ConstantIntTy, BasicBlockTy >
Definition at line 2727 of file Instructions.h.
Member Typedef Documentation
template<class SwitchInstTy, class ConstantIntTy, class BasicBlockTy> typedef CaseIteratorT<SwitchInstTy, ConstantIntTy, BasicBlockTy> llvm::SwitchInst::CaseIteratorT< SwitchInstTy, ConstantIntTy, BasicBlockTy >::Self
Definition at line 2735 of file Instructions.h.
Constructor & Destructor Documentation
template<class SwitchInstTy, class ConstantIntTy, class BasicBlockTy> llvm::SwitchInst::CaseIteratorT< SwitchInstTy, ConstantIntTy, BasicBlockTy >::CaseIteratorT (SwitchInstTy * SI, unsigned CaseNum) [inline]
Initializes case iterator for given SwitchInst and for given case number.
Definition at line 2739 of file Instructions.h.
Member Function Documentation
template<class SwitchInstTy, class ConstantIntTy, class BasicBlockTy> static Self llvm::SwitchInst::CaseIteratorT< SwitchInstTy, ConstantIntTy, BasicBlockTy >::fromSuccessorIndex (SwitchInstTy * SI, unsigned SuccessorIndex) [inline, static]
Initializes case iterator for given SwitchInst and for given TerminatorInst's successor index.
Definition at line 2746 of file Instructions.h.
Referenced by llvm::DOTGraphTraits< const Function * >::getEdgeSourceLabel().
template<class SwitchInstTy, class ConstantIntTy, class BasicBlockTy> unsigned llvm::SwitchInst::CaseIteratorT< SwitchInstTy, ConstantIntTy, BasicBlockTy >::getCaseIndex () const [inline]
Returns number of current case.
Definition at line 2769 of file Instructions.h.
Referenced by EliminateDeadSwitchCases(), handleSwitchExpect(), and llvm::SwitchInst::removeCase().
template<class SwitchInstTy, class ConstantIntTy, class BasicBlockTy> BasicBlockTy* llvm::SwitchInst::CaseIteratorT< SwitchInstTy, ConstantIntTy, BasicBlockTy >::getCaseSuccessor () [inline]
Resolves successor for current case.
Definition at line 2761 of file Instructions.h.
Referenced by llvm::ConstantFoldTerminator(), EliminateDeadSwitchCases(), and SimplifySwitchOnSelect().
template<class SwitchInstTy, class ConstantIntTy, class BasicBlockTy> ConstantIntTy* llvm::SwitchInst::CaseIteratorT< SwitchInstTy, ConstantIntTy, BasicBlockTy >::getCaseValue () [inline]
Resolves case value for current case.
Definition at line 2755 of file Instructions.h.
Referenced by llvm::ConstantFoldTerminator(), and llvm::DOTGraphTraits< const Function * >::getEdgeSourceLabel().
template<class SwitchInstTy, class ConstantIntTy, class BasicBlockTy> unsigned llvm::SwitchInst::CaseIteratorT< SwitchInstTy, ConstantIntTy, BasicBlockTy >::getSuccessorIndex () const [inline]
Returns TerminatorInst's successor index for current case successor.
Definition at line 2772 of file Instructions.h.
template<class SwitchInstTy, class ConstantIntTy, class BasicBlockTy> bool llvm::SwitchInst::CaseIteratorT< SwitchInstTy, ConstantIntTy, BasicBlockTy >::operator!= (const Self & RHS) const [inline]
Definition at line 2808 of file Instructions.h.
template<class SwitchInstTy, class ConstantIntTy, class BasicBlockTy> Self& llvm::SwitchInst::CaseIteratorT< SwitchInstTy, ConstantIntTy, BasicBlockTy >::operator* () [inline]
Definition at line 2812 of file Instructions.h.
template<class SwitchInstTy, class ConstantIntTy, class BasicBlockTy> Self llvm::SwitchInst::CaseIteratorT< SwitchInstTy, ConstantIntTy, BasicBlockTy >::operator++ () [inline]
Definition at line 2778 of file Instructions.h.
template<class SwitchInstTy, class ConstantIntTy, class BasicBlockTy> Self llvm::SwitchInst::CaseIteratorT< SwitchInstTy, ConstantIntTy, BasicBlockTy >::operator++ (int) [inline]
Definition at line 2785 of file Instructions.h.
template<class SwitchInstTy, class ConstantIntTy, class BasicBlockTy> Self llvm::SwitchInst::CaseIteratorT< SwitchInstTy, ConstantIntTy, BasicBlockTy >::operator-- () [inline]
Definition at line 2790 of file Instructions.h.
template<class SwitchInstTy, class ConstantIntTy, class BasicBlockTy> Self llvm::SwitchInst::CaseIteratorT< SwitchInstTy, ConstantIntTy, BasicBlockTy >::operator-- (int) [inline]
Definition at line 2799 of file Instructions.h.
template<class SwitchInstTy, class ConstantIntTy, class BasicBlockTy> bool llvm::SwitchInst::CaseIteratorT< SwitchInstTy, ConstantIntTy, BasicBlockTy >::operator== (const Self & RHS) const [inline]
Definition at line 2804 of file Instructions.h.
Member Data Documentation
template<class SwitchInstTy, class ConstantIntTy, class BasicBlockTy> unsigned llvm::SwitchInst::CaseIteratorT< SwitchInstTy, ConstantIntTy, BasicBlockTy >::Index [protected]
Definition at line 2731 of file Instructions.h.
Referenced by llvm::SwitchInst::CaseIteratorT< SwitchInst, ConstantInt, BasicBlock >::operator!=(), and llvm::SwitchInst::CaseIteratorT< SwitchInst, ConstantInt, BasicBlock >::operator==().
template<class SwitchInstTy, class ConstantIntTy, class BasicBlockTy> SwitchInstTy* llvm::SwitchInst::CaseIteratorT< SwitchInstTy, ConstantIntTy, BasicBlockTy >::SI [protected]
Definition at line 2730 of file Instructions.h.
Referenced by llvm::SwitchInst::CaseIteratorT< SwitchInst, ConstantInt, BasicBlock >::operator!=(), and llvm::SwitchInst::CaseIteratorT< SwitchInst, ConstantInt, BasicBlock >::operator==().
The documentation for this class was generated from the following file:
Instructions.h