LLVM: llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t > Class Template Reference
llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t > Class Template Reference
#include <InstIterator.h>
Public Types
typedef
std::bidirectional_iterator_tag iterator_category
typedef IIty value_type
typedef signed difference_type
typedef IIty * pointer
typedef IIty & reference
Public Member Functions
InstIterator ()
template<typename A , typename B , typename C , typename D >
InstIterator (const InstIterator< A, B, C, D > &II)
template<typename A , typename B , typename C , typename D >
InstIterator (InstIterator< A, B, C, D > &II)
template<class M >
InstIterator (M &m)
template<class M >
InstIterator (M &m, bool)
BBIty & getBasicBlockIterator ()
BIty & getInstructionIterator ()
reference operator* () const
pointer operator-> () const
bool operator== (const InstIterator &y) const
bool operator!= (const InstIterator &y) const
InstIterator & operator++ ()
InstIterator operator++ (int)
InstIterator & operator-- ()
InstIterator operator-- (int)
bool atEnd () const
Detailed Description
template<class BB_t, class BB_i_t, class BI_t, class II_t>
class llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >
Definition at line 30 of file InstIterator.h.
Member Typedef Documentation
template<class BB_t, class BB_i_t, class BI_t, class II_t> typedef signed llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::difference_type
Definition at line 41 of file InstIterator.h.
template<class BB_t, class BB_i_t, class BI_t, class II_t> typedef std::bidirectional_iterator_tag llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::iterator_category
Definition at line 39 of file InstIterator.h.
template<class BB_t, class BB_i_t, class BI_t, class II_t> typedef IIty* llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::pointer
Definition at line 42 of file InstIterator.h.
template<class BB_t, class BB_i_t, class BI_t, class II_t> typedef IIty& llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::reference
Definition at line 43 of file InstIterator.h.
template<class BB_t, class BB_i_t, class BI_t, class II_t> typedef IIty llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::value_type
Definition at line 40 of file InstIterator.h.
Constructor & Destructor Documentation
template<class BB_t, class BB_i_t, class BI_t, class II_t> llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::InstIterator () [inline]
Definition at line 46 of file InstIterator.h.
template<class BB_t, class BB_i_t, class BI_t, class II_t> template<typename A , typename B , typename C , typename D > llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::InstIterator (const InstIterator< A, B, C, D > & II) [inline]
Definition at line 50 of file InstIterator.h.
template<class BB_t, class BB_i_t, class BI_t, class II_t> template<typename A , typename B , typename C , typename D > llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::InstIterator (InstIterator< A, B, C, D > & II) [inline]
Definition at line 54 of file InstIterator.h.
template<class BB_t, class BB_i_t, class BI_t, class II_t> template<class M > llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::InstIterator (M & m) [inline]
Definition at line 57 of file InstIterator.h.
template<class BB_t, class BB_i_t, class BI_t, class II_t> template<class M > llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::InstIterator (M & m, bool) [inline]
Definition at line 65 of file InstIterator.h.
Member Function Documentation
template<class BB_t, class BB_i_t, class BI_t, class II_t> bool llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::atEnd () const [inline]
Definition at line 104 of file InstIterator.h.
template<class BB_t, class BB_i_t, class BI_t, class II_t> BBIty& llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::getBasicBlockIterator () [inline]
Definition at line 70 of file InstIterator.h.
template<class BB_t, class BB_i_t, class BI_t, class II_t> BIty& llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::getInstructionIterator () [inline]
Definition at line 71 of file InstIterator.h.
template<class BB_t, class BB_i_t, class BI_t, class II_t> bool llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::operator!= (const InstIterator< BB_t, BB_i_t, BI_t, II_t > & y) const [inline]
Definition at line 79 of file InstIterator.h.
References llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::operator==().
template<class BB_t, class BB_i_t, class BI_t, class II_t> reference llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::operator* () const [inline]
Definition at line 73 of file InstIterator.h.
Referenced by llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::operator->().
template<class BB_t, class BB_i_t, class BI_t, class II_t> InstIterator& llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::operator++ () [inline]
Definition at line 83 of file InstIterator.h.
template<class BB_t, class BB_i_t, class BI_t, class II_t> InstIterator llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::operator++ (int) [inline]
Definition at line 88 of file InstIterator.h.
template<class BB_t, class BB_i_t, class BI_t, class II_t> InstIterator& llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::operator-- () [inline]
Definition at line 92 of file InstIterator.h.
template<class BB_t, class BB_i_t, class BI_t, class II_t> InstIterator llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::operator-- (int) [inline]
Definition at line 100 of file InstIterator.h.
template<class BB_t, class BB_i_t, class BI_t, class II_t> pointer llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::operator-> () const [inline]
Definition at line 74 of file InstIterator.h.
References llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::operator*().
template<class BB_t, class BB_i_t, class BI_t, class II_t> bool llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::operator== (const InstIterator< BB_t, BB_i_t, BI_t, II_t > & y) const [inline]
Definition at line 76 of file InstIterator.h.
Referenced by llvm::InstIterator< BB_t, BB_i_t, BI_t, II_t >::operator!=().
The documentation for this class was generated from the following file:
InstIterator.h