LLVM: llvm::SmallPtrSetIteratorImpl Class Reference
llvm::SmallPtrSetIteratorImpl Class Reference
SmallPtrSetIteratorImpl - This is the common base class shared between all instances of SmallPtrSetIterator.
#include <SmallPtrSet.h>
Public Member Functions
SmallPtrSetIteratorImpl (const void *const *BP, const void *const *E)
bool operator== (const SmallPtrSetIteratorImpl &RHS) const
bool operator!= (const SmallPtrSetIteratorImpl &RHS) const
Protected Member Functions
void AdvanceIfNotValid ()
AdvanceIfNotValid - If the current bucket isn't valid, advance to a bucket that is.
Protected Attributes
const void *const * Bucket
const void *const * End
Detailed Description
SmallPtrSetIteratorImpl - This is the common base class shared between all instances of SmallPtrSetIterator.
Definition at line 147 of file SmallPtrSet.h.
Constructor & Destructor Documentation
llvm::SmallPtrSetIteratorImpl::SmallPtrSetIteratorImpl (const void *const * BP, const void *const * E) [inline, explicit]
Definition at line 152 of file SmallPtrSet.h.
References AdvanceIfNotValid().
Member Function Documentation
void llvm::SmallPtrSetIteratorImpl::AdvanceIfNotValid () [inline, protected]
AdvanceIfNotValid - If the current bucket isn't valid, advance to a bucket that is.
This is guaranteed to stop because the end() bucket is marked valid.
Definition at line 168 of file SmallPtrSet.h.
References Bucket, End, llvm::SmallPtrSetImplBase::getEmptyMarker(), and llvm::SmallPtrSetImplBase::getTombstoneMarker().
Referenced by llvm::SmallPtrSetIterator< PtrTy >::operator++(), and SmallPtrSetIteratorImpl().
bool llvm::SmallPtrSetIteratorImpl::operator!= (const SmallPtrSetIteratorImpl & RHS) const [inline]
Definition at line 160 of file SmallPtrSet.h.
References Bucket.
bool llvm::SmallPtrSetIteratorImpl::operator== (const SmallPtrSetIteratorImpl & RHS) const [inline]
Definition at line 157 of file SmallPtrSet.h.
References Bucket.
Member Data Documentation
const void* const* llvm::SmallPtrSetIteratorImpl::Bucket [protected]
Definition at line 149 of file SmallPtrSet.h.
Referenced by AdvanceIfNotValid(), operator!=(), llvm::SmallPtrSetIterator< PtrTy >::operator*(), llvm::SmallPtrSetIterator< PtrTy >::operator++(), and operator==().
const void* const* llvm::SmallPtrSetIteratorImpl::End [protected]
Definition at line 150 of file SmallPtrSet.h.
Referenced by AdvanceIfNotValid(), and llvm::SmallPtrSetIterator< PtrTy >::operator*().
The documentation for this class was generated from the following file:
SmallPtrSet.h