LLVM: llvm::DIELabel Class Reference
llvm::DIELabel Class Reference
DIELabel - A label DIE.
#include <DIE.h>
Public Member Functions
DIELabel (const MCSymbol *L)
const MCSymbol * getValue () const
getValue - Get MCSymbol.
void EmitValue (const AsmPrinter *AP, dwarf::Form Form) const
EmitValue - Emit label value.
unsigned SizeOf (const AsmPrinter *AP, dwarf::Form Form) const
SizeOf - Determine size of label value in bytes.
void print (raw_ostream &O) const
Detailed Description
DIELabel - A label DIE.
Definition at line 173 of file DIE.h.
Constructor & Destructor Documentation
llvm::DIELabel::DIELabel (const MCSymbol * L) [inline, explicit]
Definition at line 177 of file DIE.h.
Member Function Documentation
void DIELabel::EmitValue (const AsmPrinter * AP, dwarf::Form Form) const
EmitValue - Emit label value.
Definition at line 344 of file DIE.cpp.
References llvm::dwarf::DW_FORM_ref_addr, llvm::dwarf::DW_FORM_sec_offset, llvm::dwarf::DW_FORM_strp, llvm::AsmPrinter::EmitLabelReference(), and SizeOf().
const MCSymbol* llvm::DIELabel::getValue () const [inline]
getValue - Get MCSymbol.
Definition at line 181 of file DIE.h.
void DIELabel::print (raw_ostream & O) const
Definition at line 361 of file DIE.cpp.
References llvm::MCSymbol::getName().
unsigned DIELabel::SizeOf (const AsmPrinter * AP, dwarf::Form Form) const
SizeOf - Determine size of label value in bytes.
Definition at line 353 of file DIE.cpp.
References llvm::dwarf::DW_FORM_data4, llvm::dwarf::DW_FORM_sec_offset, llvm::dwarf::DW_FORM_strp, llvm::AsmPrinter::getDataLayout(), and llvm::DataLayout::getPointerSize().
Referenced by EmitValue().
The documentation for this class was generated from the following files:
DIE.h
DIE.cpp