LLVM: llvm::SmallVectorTemplateCommon< T, typename > Class Template Reference
llvm::SmallVectorTemplateCommon< T, typename > Class Template Reference
This is the part of SmallVectorTemplateBase which does not depend on whether the type T is a POD.
#include <SmallVector.h>
Inherits llvm::SmallVectorBase.
Public Types
typedef size_t size_type
typedef ptrdiff_t difference_type
typedef T value_type
typedef T * iterator
typedef const T * const_iterator
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
typedef std::reverse_iterator
< iterator > reverse_iterator
typedef T & reference
typedef const T & const_reference
typedef T * pointer
typedef const T * const_pointer
Public Member Functions
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type size () const
size_type max_size () const
size_t capacity () const
Return the total number of elements in the currently allocated buffer.
pointer data ()
Return a pointer to the vector's buffer, even if empty().
const_pointer data () const
Return a pointer to the vector's buffer, even if empty().
reference operator[] (size_type idx)
const_reference operator[] (size_type idx) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
Protected Member Functions
SmallVectorTemplateCommon (size_t Size)
void grow_pod (size_t MinSizeInBytes, size_t TSize)
bool isSmall () const
Return true if this is a smallvector which has not had dynamic memory allocated for it.
void resetToSmall ()
Put this vector in a state of being small.
void setEnd (T *P)
iterator capacity_ptr ()
const_iterator capacity_ptr () const
Friends
struct SmallVectorStorage
Detailed Description
template<typename T, typename = void>
class llvm::SmallVectorTemplateCommon< T, typename >
This is the part of SmallVectorTemplateBase which does not depend on whether the type T is a POD.
The extra dummy template argument is used by ArrayRef to avoid unnecessarily requiring T to be complete.
Definition at line 66 of file SmallVector.h.
Member Typedef Documentation
template<typename T, typename = void> typedef const T* llvm::SmallVectorTemplateCommon< T, typename >::const_iterator
Reimplemented in llvm::final< T >, and llvm::final< T >.
Definition at line 101 of file SmallVector.h.
template<typename T, typename = void> typedef const T* llvm::SmallVectorTemplateCommon< T, typename >::const_pointer
Definition at line 109 of file SmallVector.h.
template<typename T, typename = void> typedef const T& llvm::SmallVectorTemplateCommon< T, typename >::const_reference
Definition at line 107 of file SmallVector.h.
template<typename T, typename = void> typedef std::reverse_iterator<const_iterator> llvm::SmallVectorTemplateCommon< T, typename >::const_reverse_iterator
Definition at line 103 of file SmallVector.h.
template<typename T, typename = void> typedef ptrdiff_t llvm::SmallVectorTemplateCommon< T, typename >::difference_type
Definition at line 98 of file SmallVector.h.
template<typename T, typename = void> typedef T* llvm::SmallVectorTemplateCommon< T, typename >::iterator
Reimplemented in llvm::final< T >, llvm::final< T >, llvm::SmallVectorImpl< T >, llvm::SmallVectorImpl< DILineInfo >, llvm::SmallVectorImpl< CriticalEdge >, llvm::SmallVectorImpl< SMFixIt >, llvm::SmallVectorImpl< const CallInst * >, llvm::SmallVectorImpl< WeakVH >, llvm::SmallVectorImpl< std::pair< SlotIndex, SlotIndex > >, llvm::SmallVectorImpl< Value * >, llvm::SmallVectorImpl< Arg * >, llvm::SmallVectorImpl< LayoutAlignElem >, llvm::SmallVectorImpl< DWARFDebugInfoEntryMinimal >, llvm::SmallVectorImpl< ImmutablePass * >, llvm::SmallVectorImpl< uint32_t >, llvm::SmallVectorImpl< LiveRange * >, llvm::SmallVectorImpl< TreeData >, llvm::SmallVectorImpl< ISD::ArgFlagsTy >, llvm::SmallVectorImpl< const MachineInstr * >, llvm::SmallVectorImpl< MCDataFragment * >, llvm::SmallVectorImpl< std::pair< std::string, GCOVCoverage > >, llvm::SmallVectorImpl< std::unique_ptr< DwarfUnit > >, llvm::SmallVectorImpl< PointerAlignElem >, llvm::SmallVectorImpl< AsmRewrite >, llvm::SmallVectorImpl< CCValAssign >, llvm::SmallVectorImpl< std::unique_ptr< UnitType > >, llvm::SmallVectorImpl< MVT >, llvm::SmallVectorImpl< std::pair< MCSectionSubPair, MCSectionSubPair > >, llvm::SmallVectorImpl< MachineBasicBlock * >, llvm::SmallVectorImpl< Location >, llvm::SmallVectorImpl< IdxMBBPair >, llvm::SmallVectorImpl< std::pair< unsigned, unsigned > >, llvm::SmallVectorImpl< StringRef >, llvm::SmallVectorImpl< DIScope * >, llvm::SmallVectorImpl< std::pair< const MDNode *, const MDNode * > >, llvm::SmallVectorImpl< Entry >, llvm::SmallVectorImpl< std::string >, llvm::SmallVectorImpl< NodeState >, llvm::SmallVectorImpl< std::pair< const char *, std::pair< int, const char * > > >, llvm::SmallVectorImpl< Function * >, llvm::SmallVectorImpl< Node * >, llvm::SmallVectorImpl< LiveOutPair >, llvm::SmallVectorImpl< SlotIndex >, llvm::SmallVectorImpl< const DIExpression * >, llvm::SmallVectorImpl< std::pair< std::unique_ptr< DwarfTypeUnit >, const DICompositeType * > >, llvm::SmallVectorImpl< std::unique_ptr< DbgVariable > >, llvm::SmallVectorImpl< OptionInfo >, llvm::SmallVectorImpl< ConstantPoolEntry >, llvm::SmallVectorImpl< MCPhysReg >, llvm::SmallVectorImpl< ScavengedInfo >, llvm::SmallVectorImpl< SimpleKey >, llvm::SmallVectorImpl< SMLoc >, llvm::SmallVectorImpl< LiveOutReg >, llvm::SmallVectorImpl< std::unique_ptr< GCOVFunction > >, llvm::SmallVectorImpl< std::unique_ptr< Module > >, llvm::SmallVectorImpl< TrackingVH< Value > >, llvm::SmallVectorImpl< ISD::InputArg >, llvm::SmallVectorImpl< ForwardedRegister >, llvm::SmallVectorImpl< SDDbgValue * >, llvm::SmallVectorImpl< int >, llvm::SmallVectorImpl< std::pair< void *, size_t > >, llvm::SmallVectorImpl< LiveInReg >, llvm::SmallVectorImpl< InsnRange >, llvm::SmallVectorImpl< VariableDbgInfo >, llvm::SmallVectorImpl< SUnit * >, llvm::SmallVectorImpl< LiveInBlock >, llvm::SmallVectorImpl< UseToVisit >, llvm::SmallVectorImpl< DIType * >, llvm::SmallVectorImpl< DISubprogram * >, llvm::SmallVectorImpl< Inst >, llvm::SmallVectorImpl< SID >, llvm::SmallVectorImpl< EHFrameRelatedSections >, llvm::SmallVectorImpl< std::unique_ptr< Arg > >, llvm::SmallVectorImpl< LexicalScope * >, llvm::SmallVectorImpl< const Value * >, llvm::SmallVectorImpl< Dependence >, llvm::SmallVectorImpl< BlockInterference >, llvm::SmallVectorImpl< std::pair< const TargetRegisterClass *, MachineOperand * > >, llvm::SmallVectorImpl< std::pair< unsigned, MCFragment * > >, llvm::SmallVectorImpl< DIGlobalVariable * >, llvm::SmallVectorImpl< Segment >, llvm::SmallVectorImpl< const char * >, llvm::SmallVectorImpl< SMSNode >, llvm::SmallVectorImpl< PHINode * >, llvm::SmallVectorImpl< FixedBlockInfo >, llvm::SmallVectorImpl< AllocaInst * >, llvm::SmallVectorImpl< const LocalAsMetadata * >, llvm::SmallVectorImpl< std::unique_ptr< GCOVEdge > >, llvm::SmallVectorImpl< uint8_t >, llvm::SmallVectorImpl< std::pair< bool, StringRef > >, llvm::SmallVectorImpl< std::pair< BlockNode, BlockMass > >, llvm::SmallVectorImpl< VNInfo * >, llvm::SmallVectorImpl< LiveOutInfo >, llvm::SmallVectorImpl< std::pair< KeyT, ValueT > >, llvm::SmallVectorImpl< HandlerInfo >, llvm::SmallVectorImpl< std::pair< MCSymbol *, int > >, llvm::SmallVectorImpl< WinEHUnwindMapEntry >, llvm::SmallVectorImpl< LiveRange::Segment >, llvm::SmallVectorImpl< ISD::OutputArg >, llvm::SmallVectorImpl< std::unique_ptr< MemoryBuffer > >, llvm::SmallVectorImpl< BitCodeAbbrevOp >, llvm::SmallVectorImpl< Metadata * >, llvm::SmallVectorImpl< MCOperand >, llvm::SmallVectorImpl< std::unique_ptr< MipsOptionRecord > >, llvm::SmallVectorImpl< unsigned char >, llvm::SmallVectorImpl< std::pair< BlockFrequency, unsigned > >, llvm::SmallVectorImpl< RangeSpan >, llvm::SmallVectorImpl< VarInfo >, llvm::SmallVectorImpl< BlockMass >, llvm::SmallVectorImpl< DICompileUnit * >, llvm::SmallVectorImpl< std::pair< unsigned, TrackingMDNodeRef > >, llvm::SmallVectorImpl< const SCEV * >, llvm::SmallVectorImpl< MCSymbol * >, llvm::SmallVectorImpl< FreeList * >, llvm::SmallVectorImpl< uintptr_t >, llvm::SmallVectorImpl< SectionEntry >, llvm::SmallVectorImpl< Pass * >, llvm::SmallVectorImpl< SDValue >, llvm::SmallVectorImpl< std::pair< unsigned, MCSymbol * > >, llvm::SmallVectorImpl< MILOHDirective >, llvm::SmallVectorImpl< sys::MemoryBlock >, llvm::SmallVectorImpl< MCSection * >, llvm::SmallVectorImpl< BasicBlock * >, llvm::SmallVectorImpl< MCDwarfFile >, llvm::SmallVectorImpl< PhiT * >, llvm::SmallVectorImpl< ValueT >, llvm::SmallVectorImpl< void * >, llvm::SmallVectorImpl< Block >, llvm::SmallVectorImpl< std::unique_ptr< object::ObjectFile > >, llvm::SmallVectorImpl< DIEAbbrevData >, llvm::SmallVectorImpl< PMDataManager * >, llvm::SmallVectorImpl< BlockNode >, llvm::SmallVectorImpl< unsigned >, llvm::SmallVectorImpl< char >, llvm::SmallVectorImpl< EVT >, llvm::SmallVectorImpl< std::unique_ptr< GCStrategy > >, llvm::SmallVectorImpl< SDNode * >, llvm::SmallVectorImpl< TraceBlockInfo >, llvm::SmallVectorImpl< TrackingMDNodeRef >, llvm::SmallVectorImpl< SmallString< 32 > >, llvm::SmallVectorImpl< BlockInfo >, llvm::SmallVectorImpl< AnalysisID >, llvm::SmallVectorImpl< Instruction * >, llvm::SmallVectorImpl< LiveInterval * >, llvm::SmallVectorImpl< bool >, llvm::SmallVectorImpl< SEHHandler >, llvm::SmallVectorImpl< Weight >, llvm::SmallVectorImpl< std::pair< AtomType, Form > >, llvm::SmallVectorImpl< InState >, llvm::SmallVectorImpl< RangeSpanList >, llvm::SmallVectorImpl< BlockFrequency >, llvm::SmallVectorImpl< GCOVEdge * >, llvm::SmallVectorImpl< const uint32_t * >, llvm::SmallVectorImpl< AttributeSpec >, llvm::SmallVectorImpl< std::unique_ptr< GCOVBlock > >, llvm::SmallVectorImpl< SCC * >, llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >, llvm::SmallVectorImpl< RootData >, llvm::SmallVectorImpl< HexagonInstr >, llvm::SmallVectorImpl< List >, llvm::SmallVectorImpl< WinEHTryBlockMapEntry >, llvm::SmallVectorImpl< object::OwningBinary< object::Archive > >, llvm::SmallVectorImpl< SDep >, llvm::SmallVectorImpl< WinEHHandlerType >, llvm::SmallVectorImpl< LoadCommandInfo >, llvm::SmallVectorImpl< std::string * >, llvm::SmallVectorImpl< RegUnitInfo >, llvm::SmallVectorImpl< SmallVector< unsigned, 8 > >, llvm::SmallVectorImpl< Atom >, llvm::SmallVectorImpl< VersionMapEntry >, llvm::SmallVectorImpl< MCFixup >, llvm::SmallVectorImpl< BitTestCase >, llvm::SmallVectorImpl< uint64_t >, llvm::SmallVectorImpl< MCLOHDirective >, llvm::SmallVectorImpl< std::pair< AnalysisID, IdentifyingPassPtr > >, llvm::SmallVectorImpl< const Function * >, llvm::SmallVectorImpl< Value >, llvm::SmallVectorImpl< std::pair< Node *, iterator > >, llvm::SmallVectorImpl< ByValInfo >, llvm::SmallVectorImpl< LocationList >, llvm::SmallVectorImpl< VReg2SUnit >, llvm::SmallVectorImpl< std::pair< int, int64_t > >, llvm::SmallVectorImpl< MachineInstr * >, and llvm::final< T >.
Definition at line 100 of file SmallVector.h.
template<typename T, typename = void> typedef T* llvm::SmallVectorTemplateCommon< T, typename >::pointer
Definition at line 108 of file SmallVector.h.
template<typename T, typename = void> typedef T& llvm::SmallVectorTemplateCommon< T, typename >::reference
Definition at line 106 of file SmallVector.h.
template<typename T, typename = void> typedef std::reverse_iterator<iterator> llvm::SmallVectorTemplateCommon< T, typename >::reverse_iterator
Definition at line 104 of file SmallVector.h.
template<typename T, typename = void> typedef size_t llvm::SmallVectorTemplateCommon< T, typename >::size_type
Reimplemented in llvm::SmallVectorImpl< T >, llvm::SmallVectorImpl< DILineInfo >, llvm::SmallVectorImpl< CriticalEdge >, llvm::SmallVectorImpl< SMFixIt >, llvm::SmallVectorImpl< const CallInst * >, llvm::SmallVectorImpl< WeakVH >, llvm::SmallVectorImpl< std::pair< SlotIndex, SlotIndex > >, llvm::SmallVectorImpl< Value * >, llvm::SmallVectorImpl< Arg * >, llvm::SmallVectorImpl< LayoutAlignElem >, llvm::SmallVectorImpl< DWARFDebugInfoEntryMinimal >, llvm::SmallVectorImpl< ImmutablePass * >, llvm::SmallVectorImpl< uint32_t >, llvm::SmallVectorImpl< LiveRange * >, llvm::SmallVectorImpl< TreeData >, llvm::SmallVectorImpl< ISD::ArgFlagsTy >, llvm::SmallVectorImpl< const MachineInstr * >, llvm::SmallVectorImpl< MCDataFragment * >, llvm::SmallVectorImpl< std::pair< std::string, GCOVCoverage > >, llvm::SmallVectorImpl< std::unique_ptr< DwarfUnit > >, llvm::SmallVectorImpl< PointerAlignElem >, llvm::SmallVectorImpl< AsmRewrite >, llvm::SmallVectorImpl< CCValAssign >, llvm::SmallVectorImpl< std::unique_ptr< UnitType > >, llvm::SmallVectorImpl< MVT >, llvm::SmallVectorImpl< std::pair< MCSectionSubPair, MCSectionSubPair > >, llvm::SmallVectorImpl< MachineBasicBlock * >, llvm::SmallVectorImpl< Location >, llvm::SmallVectorImpl< IdxMBBPair >, llvm::SmallVectorImpl< std::pair< unsigned, unsigned > >, llvm::SmallVectorImpl< StringRef >, llvm::SmallVectorImpl< DIScope * >, llvm::SmallVectorImpl< std::pair< const MDNode *, const MDNode * > >, llvm::SmallVectorImpl< Entry >, llvm::SmallVectorImpl< std::string >, llvm::SmallVectorImpl< NodeState >, llvm::SmallVectorImpl< std::pair< const char *, std::pair< int, const char * > > >, llvm::SmallVectorImpl< Function * >, llvm::SmallVectorImpl< Node * >, llvm::SmallVectorImpl< LiveOutPair >, llvm::SmallVectorImpl< SlotIndex >, llvm::SmallVectorImpl< const DIExpression * >, llvm::SmallVectorImpl< std::pair< std::unique_ptr< DwarfTypeUnit >, const DICompositeType * > >, llvm::SmallVectorImpl< std::unique_ptr< DbgVariable > >, llvm::SmallVectorImpl< OptionInfo >, llvm::SmallVectorImpl< ConstantPoolEntry >, llvm::SmallVectorImpl< MCPhysReg >, llvm::SmallVectorImpl< ScavengedInfo >, llvm::SmallVectorImpl< SimpleKey >, llvm::SmallVectorImpl< SMLoc >, llvm::SmallVectorImpl< LiveOutReg >, llvm::SmallVectorImpl< std::unique_ptr< GCOVFunction > >, llvm::SmallVectorImpl< std::unique_ptr< Module > >, llvm::SmallVectorImpl< TrackingVH< Value > >, llvm::SmallVectorImpl< ISD::InputArg >, llvm::SmallVectorImpl< ForwardedRegister >, llvm::SmallVectorImpl< SDDbgValue * >, llvm::SmallVectorImpl< int >, llvm::SmallVectorImpl< std::pair< void *, size_t > >, llvm::SmallVectorImpl< LiveInReg >, llvm::SmallVectorImpl< InsnRange >, llvm::SmallVectorImpl< VariableDbgInfo >, llvm::SmallVectorImpl< SUnit * >, llvm::SmallVectorImpl< LiveInBlock >, llvm::SmallVectorImpl< UseToVisit >, llvm::SmallVectorImpl< DIType * >, llvm::SmallVectorImpl< DISubprogram * >, llvm::SmallVectorImpl< Inst >, llvm::SmallVectorImpl< SID >, llvm::SmallVectorImpl< EHFrameRelatedSections >, llvm::SmallVectorImpl< std::unique_ptr< Arg > >, llvm::SmallVectorImpl< LexicalScope * >, llvm::SmallVectorImpl< const Value * >, llvm::SmallVectorImpl< Dependence >, llvm::SmallVectorImpl< BlockInterference >, llvm::SmallVectorImpl< std::pair< const TargetRegisterClass *, MachineOperand * > >, llvm::SmallVectorImpl< std::pair< unsigned, MCFragment * > >, llvm::SmallVectorImpl< DIGlobalVariable * >, llvm::SmallVectorImpl< Segment >, llvm::SmallVectorImpl< const char * >, llvm::SmallVectorImpl< SMSNode >, llvm::SmallVectorImpl< PHINode * >, llvm::SmallVectorImpl< FixedBlockInfo >, llvm::SmallVectorImpl< AllocaInst * >, llvm::SmallVectorImpl< const LocalAsMetadata * >, llvm::SmallVectorImpl< std::unique_ptr< GCOVEdge > >, llvm::SmallVectorImpl< uint8_t >, llvm::SmallVectorImpl< std::pair< bool, StringRef > >, llvm::SmallVectorImpl< std::pair< BlockNode, BlockMass > >, llvm::SmallVectorImpl< VNInfo * >, llvm::SmallVectorImpl< LiveOutInfo >, llvm::SmallVectorImpl< std::pair< KeyT, ValueT > >, llvm::SmallVectorImpl< HandlerInfo >, llvm::SmallVectorImpl< std::pair< MCSymbol *, int > >, llvm::SmallVectorImpl< WinEHUnwindMapEntry >, llvm::SmallVectorImpl< LiveRange::Segment >, llvm::SmallVectorImpl< ISD::OutputArg >, llvm::SmallVectorImpl< std::unique_ptr< MemoryBuffer > >, llvm::SmallVectorImpl< BitCodeAbbrevOp >, llvm::SmallVectorImpl< Metadata * >, llvm::SmallVectorImpl< MCOperand >, llvm::SmallVectorImpl< std::unique_ptr< MipsOptionRecord > >, llvm::SmallVectorImpl< unsigned char >, llvm::SmallVectorImpl< std::pair< BlockFrequency, unsigned > >, llvm::SmallVectorImpl< RangeSpan >, llvm::SmallVectorImpl< VarInfo >, llvm::SmallVectorImpl< BlockMass >, llvm::SmallVectorImpl< DICompileUnit * >, llvm::SmallVectorImpl< std::pair< unsigned, TrackingMDNodeRef > >, llvm::SmallVectorImpl< const SCEV * >, llvm::SmallVectorImpl< MCSymbol * >, llvm::SmallVectorImpl< FreeList * >, llvm::SmallVectorImpl< uintptr_t >, llvm::SmallVectorImpl< SectionEntry >, llvm::SmallVectorImpl< Pass * >, llvm::SmallVectorImpl< SDValue >, llvm::SmallVectorImpl< std::pair< unsigned, MCSymbol * > >, llvm::SmallVectorImpl< MILOHDirective >, llvm::SmallVectorImpl< sys::MemoryBlock >, llvm::SmallVectorImpl< MCSection * >, llvm::SmallVectorImpl< BasicBlock * >, llvm::SmallVectorImpl< MCDwarfFile >, llvm::SmallVectorImpl< PhiT * >, llvm::SmallVectorImpl< ValueT >, llvm::SmallVectorImpl< void * >, llvm::SmallVectorImpl< Block >, llvm::SmallVectorImpl< std::unique_ptr< object::ObjectFile > >, llvm::SmallVectorImpl< DIEAbbrevData >, llvm::SmallVectorImpl< PMDataManager * >, llvm::SmallVectorImpl< BlockNode >, llvm::SmallVectorImpl< unsigned >, llvm::SmallVectorImpl< char >, llvm::SmallVectorImpl< EVT >, llvm::SmallVectorImpl< std::unique_ptr< GCStrategy > >, llvm::SmallVectorImpl< SDNode * >, llvm::SmallVectorImpl< TraceBlockInfo >, llvm::SmallVectorImpl< TrackingMDNodeRef >, llvm::SmallVectorImpl< SmallString< 32 > >, llvm::SmallVectorImpl< BlockInfo >, llvm::SmallVectorImpl< AnalysisID >, llvm::SmallVectorImpl< Instruction * >, llvm::SmallVectorImpl< LiveInterval * >, llvm::SmallVectorImpl< bool >, llvm::SmallVectorImpl< SEHHandler >, llvm::SmallVectorImpl< Weight >, llvm::SmallVectorImpl< std::pair< AtomType, Form > >, llvm::SmallVectorImpl< InState >, llvm::SmallVectorImpl< RangeSpanList >, llvm::SmallVectorImpl< BlockFrequency >, llvm::SmallVectorImpl< GCOVEdge * >, llvm::SmallVectorImpl< const uint32_t * >, llvm::SmallVectorImpl< AttributeSpec >, llvm::SmallVectorImpl< std::unique_ptr< GCOVBlock > >, llvm::SmallVectorImpl< SCC * >, llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >, llvm::SmallVectorImpl< RootData >, llvm::SmallVectorImpl< HexagonInstr >, llvm::SmallVectorImpl< List >, llvm::SmallVectorImpl< WinEHTryBlockMapEntry >, llvm::SmallVectorImpl< object::OwningBinary< object::Archive > >, llvm::SmallVectorImpl< SDep >, llvm::SmallVectorImpl< WinEHHandlerType >, llvm::SmallVectorImpl< LoadCommandInfo >, llvm::SmallVectorImpl< std::string * >, llvm::SmallVectorImpl< RegUnitInfo >, llvm::SmallVectorImpl< SmallVector< unsigned, 8 > >, llvm::SmallVectorImpl< Atom >, llvm::SmallVectorImpl< VersionMapEntry >, llvm::SmallVectorImpl< MCFixup >, llvm::SmallVectorImpl< BitTestCase >, llvm::SmallVectorImpl< uint64_t >, llvm::SmallVectorImpl< MCLOHDirective >, llvm::SmallVectorImpl< std::pair< AnalysisID, IdentifyingPassPtr > >, llvm::SmallVectorImpl< const Function * >, llvm::SmallVectorImpl< Value >, llvm::SmallVectorImpl< std::pair< Node *, iterator > >, llvm::SmallVectorImpl< ByValInfo >, llvm::SmallVectorImpl< LocationList >, llvm::SmallVectorImpl< VReg2SUnit >, llvm::SmallVectorImpl< std::pair< int, int64_t > >, and llvm::SmallVectorImpl< MachineInstr * >.
Definition at line 97 of file SmallVector.h.
template<typename T, typename = void> typedef T llvm::SmallVectorTemplateCommon< T, typename >::value_type
Definition at line 99 of file SmallVector.h.
Constructor & Destructor Documentation
template<typename T, typename = void> llvm::SmallVectorTemplateCommon< T, typename >::SmallVectorTemplateCommon (size_t Size) [inline, protected]
Definition at line 78 of file SmallVector.h.
Member Function Documentation
template<typename T, typename = void> reference llvm::SmallVectorTemplateCommon< T, typename >::back () [inline]
Definition at line 156 of file SmallVector.h.
Referenced by llvm::GCOVBlock::addDstEdge(), llvm::orc::OrcMCJITReplacement::addModule(), llvm::DwarfCompileUnit::addRange(), llvm::MachineInstr::addRegisterDead(), llvm::MachineInstr::addRegisterKilled(), llvm::object::ExportEntry::address(), advanceToNextLeafType(), llvm::LiveRange::append(), llvm::A57ChainingConstraint::apply(), buildGEP(), buildMultiplyTree(), llvm::yaml::Output::canElideEmptySequence(), combineConcatVectorOfScalars(), llvm::LiveInterval::constructMainRangeFromSubranges(), llvm::SpecificBumpPtrAllocator< SCC >::DestroyAll(), llvm::DWARFContextInMemory::DWARFContextInMemory(), EmitAddTreeOfValues(), llvm::MCELFStreamer::EmitBundleUnlock(), llvm::UnwindOpcodeAssembler::EmitRaw(), llvm::LiveRange::endIndex(), llvm::BitstreamCursor::EnterSubBlock(), llvm::SparseSet< RootData >::erase(), llvm::MDAttachmentMap::erase(), ExposePointerBase(), extendSegmentsToUses(), firstRealType(), llvm::object::ExportEntry::flags(), llvm::ScalarEvolution::getAddRecExpr(), GetBranchWeights(), llvm::MCStreamer::getCurrentSection(), llvm::GCOVFunction::getExitCount(), llvm::GCModuleInfo::getGCStrategy(), llvm::GCOVBlock::getLastLine(), llvm::MemoryDependenceAnalysis::getNonLocalCallDependency(), llvm::MCStreamer::getPreviousSection(), llvm::CCState::getRemainingRegParmsForType(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::getVisitState(), llvm::DbgVariable::hasComplexAddress(), LowerVectorAllZeroTest(), llvm::object::ExportEntry::moveNext(), nextRealType(), llvm::object::ExportEntry::nodeOffset(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator*(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator++(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator--(), llvm::object::ExportEntry::other(), llvm::object::ExportEntry::otherName(), llvm::DWARFDebugLoc::parse(), llvm::DWARFDebugLocDWO::parse(), ParseFunctionArgs(), llvm::yaml::Output::postflightKey(), llvm::yaml::Output::preflightKey(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::GCOVFunction::readGCNO(), llvm::StackMaps::recordPatchPoint(), llvm::returnTypeIsEligibleForTailCall(), llvm::DAGTypeLegalizer::run(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::skipToParent(), llvm::MCStreamer::SubSection(), llvm::MCStreamer::SwitchSection(), and llvm::MCStreamer::SwitchSectionNoChange().
template<typename T, typename = void> const_reference llvm::SmallVectorTemplateCommon< T, typename >::back () const [inline]
Definition at line 160 of file SmallVector.h.
template<typename T, typename = void> iterator llvm::SmallVectorTemplateCommon< T, typename >::begin () [inline]
Reimplemented in llvm::final< T >, and llvm::final< T >.
Definition at line 112 of file SmallVector.h.
Referenced by llvm::SpillPlacement::Node::addLink(), llvm::AArch64FunctionInfo::addLOHDirective(), llvm::DbgVariable::addMMIEntry(), llvm::FoldingSetNodeID::AddNodeID(), llvm::TargetPassConfig::addPass(), llvm::SUnit::addPred(), llvm::DebugLocEntry::addValues(), AnalyzeArguments(), llvm::MipsInstrInfo::AnalyzeBranch(), AnalyzeReturnValues(), AntiDepEdges(), llvm::RegsForValue::append(), llvm::SmallString< 256 >::assign(), llvm::DWARFAbbreviationDeclaration::attributes(), llvm::LiveRangeEdit::begin(), llvm::SparseSet< RootData >::begin(), llvm::MCInst::begin(), llvm::LazyCallGraph::Node::begin(), llvm::GCModuleInfo::begin(), llvm::LiveRange::begin(), llvm::LazyCallGraph::SCC::begin(), llvm::LazyCallGraph::begin(), llvm::object::MachOObjectFile::begin_load_commands(), llvm::DwarfDebug::beginFunction(), llvm::DwarfDebug::beginModule(), llvm::SUnit::biasCriticalPath(), llvm::GCOVFunction::block_begin(), llvm::CriticalAntiDepBreaker::BreakAntiDependencies(), llvm::AggressiveAntiDepBreaker::BreakAntiDependencies(), llvm::ScheduleDAGInstrs::buildSchedGraph(), llvm::SDDbgInfo::ByvalParmDbgBegin(), calcMaxScratches(), CalcNodeSethiUllmanNumber(), canClobberReachingPhysRegUse(), llvm::SmallVectorTemplateCommon< MachineInstr * >::capacity(), llvm::CC_ARM_AAPCS_Custom_Aggregate(), llvm::RegPressureTracker::closeBottom(), closestSucc(), llvm::RegPressureTracker::closeTop(), llvm::PMDataManager::collectRequiredAnalysis(), llvm::DebugInfoFinder::compile_units(), llvm::SCEVAddRecExpr::computeAccessFunctions(), createUniqueEntity(), CriticalPathStep(), llvm::SmallVectorTemplateCommon< MachineInstr * >::data(), llvm::SDDbgInfo::DbgBegin(), llvm::SpecificBumpPtrAllocator< SCC >::DestroyAll(), llvm::GCOVBlock::dst_begin(), llvm::SUnit::dumpAll(), llvm::PMTopLevelManager::dumpArguments(), llvm::PMDataManager::dumpPassArguments(), llvm::ConstantPool::emitEntries(), llvm::MCWinCOFFStreamer::EmitInstToData(), llvm::MCObjectStreamer::EmitInstToFragment(), llvm::TargetLoweringObjectFileELF::emitPersonalityValue(), llvm::UnwindOpcodeAssembler::EmitRaw(), llvm::ScheduleDAGSDNodes::EmitSchedule(), llvm::opt::ArgList::end(), llvm::MDAttachmentMap::erase(), llvm::cl::ExpandResponseFiles(), llvm::DIBuilder::finalize(), llvm::DebugLocEntry::finalize(), llvm::ScalarEvolution::findArrayDimensions(), llvm::SSAUpdaterImpl< UpdaterT >::FindAvailableVals(), findBasePointer(), llvm::SSAUpdaterImpl< UpdaterT >::FindExistingPHI(), llvm::DwarfDebug::findImportedEntitiesForScope(), llvm::SlotIndexes::findLiveInMBBs(), llvm::MCEncodedFragmentWithFixups< 8, 1 >::fixup_begin(), llvm::RegScavenger::forward(), llvm::SmallVectorTemplateCommon< MachineInstr * >::front(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), llvm::MDAttachmentMap::getAll(), llvm::opt::ArgList::getAllArgValues(), llvm::opt::Arg::getAsString(), llvm::DebugLocStream::getBytes(), llvm::BlockFrequencyInfoImplBase::LoopData::getHeaderIndex(), llvm::DWARFDebugInfoEntryMinimal::getInlinedChainForAddress(), llvm::DataLayout::getLargestLegalIntTypeSize(), llvm::LexicalScopes::getMachineBasicBlocks(), llvm::SlotIndexes::getMBBCoveringRange(), llvm::SlotIndexes::getMBBFromIndex(), llvm::ScalarEvolution::getMulExpr(), llvm::RegScavenger::getScavengingFrameIndices(), getSingleUnscheduledPred(), getSingleUnscheduledSucc(), llvm::ScalarEvolution::getSMaxExpr(), llvm::MCSection::getSubsectionInsertionPoint(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::getTotalMemory(), llvm::ScalarEvolution::getUMaxExpr(), getUncompressedData(), llvm::Loop::getUniqueExitBlocks(), llvm::DebugInfoFinder::global_variables(), GroupByComplexity(), HandleMergeInputChains(), hasDataSucc(), hasOnlyLiveInOpers(), hasOnlyLiveOutUses(), hasVRegCycleUse(), llvm::ExtractValueInst::idx_begin(), llvm::InsertValueInst::idx_begin(), llvm::ScheduleDAGTopologicalSort::InitDAGTopologicalSorting(), llvm::PMTopLevelManager::initializeAllAnalysisInfo(), llvm::PMDataManager::initializeAnalysisImpl(), llvm::RegScavenger::initRegState(), initVRegCycle(), llvm::SlotIndexes::insertMBBInMaps(), llvm::FoldingSetNodeID::Intern(), llvm::BlockFrequencyInfoImplBase::LoopData::isHeader(), llvm::AllocationOrder::isHint(), llvm::LoadAndStorePromoter::isInstInList(), llvm::RegScavenger::isScavengingFrameIndex(), llvm::LiveIntervalUnion::Query::isSeenInterference(), llvm::SpillPlacement::iterate(), iterateChainSucc(), LLVMGetRelocationTypeName(), llvm::MipsSEInstrInfo::loadImmediate(), LowerInterruptReturn(), lowerV16I8VectorShuffle(), lowerV8I16GeneralSingleInputVectorShuffle(), LowerVectorAllZeroTest(), llvm::BlockFrequencyInfoImplBase::LoopData::members_begin(), llvm::sys::path::native(), numberCtrlDepsInSU(), numberCtrlPredInSU(), llvm::ObjectMemoryBuffer::ObjectMemoryBuffer(), llvm::SmallVectorImpl< MachineInstr * >::operator<(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::operator=(), llvm::SmallVectorImpl< MachineInstr * >::operator==(), llvm::SmallVectorTemplateCommon< MachineInstr * >::operator[](), llvm::yaml::Scanner::peekNext(), prependCompressionHeader(), llvm::PMDataManager::preserveHigherLevelAnalysis(), llvm::MachineInstr::print(), llvm::PassNameParser::printOptionInfo(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), processInstruction(), llvm::LatencyPriorityQueue::push(), llvm::ResourcePriorityQueue::push(), llvm::SSAUpdaterImpl< UpdaterT >::RecordMatchingPHIs(), llvm::PostGenericScheduler::registerRoots(), llvm::ConvergingVLIWScheduler::releaseBottomNode(), llvm::ScheduleDAGMI::releasePredecessors(), llvm::ScheduleDAGMI::releaseSuccessors(), llvm::ConvergingVLIWScheduler::releaseTopNode(), llvm::StatepointLoweringState::relocCallVisited(), llvm::sys::path::remove_filename(), llvm::MDAttachmentMap::remove_if(), RemoveInstInputs(), llvm::LazyCallGraph::SCC::removeInterSCCEdge(), llvm::LazyCallGraph::SCC::removeIntraSCCEdge(), llvm::cl::parser< const PassInfo * >::removeLiteralOption(), llvm::ExecutionEngine::removeModule(), llvm::PMDataManager::removeNotPreservedAnalysis(), llvm::SUnit::removePred(), llvm::SmallVectorTemplateCommon< MachineInstr * >::rend(), llvm::opt::Arg::render(), llvm::opt::Arg::renderAsInput(), llvm::sys::path::replace_extension(), llvm::IntervalMapImpl::Path::replaceRoot(), llvm::GenericScheduler::reschedulePhysRegCopies(), reservePreviousStackSlotForValue(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Reset(), resetVRegCycle(), RewriteIntelBracExpression(), llvm::SlotIndexes::runOnMachineFunction(), llvm::LatencyPriorityQueue::scheduledNode(), llvm::ResourcePriorityQueue::scheduledNode(), llvm::PMTopLevelManager::schedulePass(), llvm::ConvergingVLIWScheduler::SchedulingCost(), llvm::DebugInfoFinder::scopes(), llvm::SUnit::setDepthDirty(), llvm::SUnit::setHeightDirty(), llvm::PMTopLevelManager::setLastUser(), llvm::HexagonShuffler::shuffle(), SimplifyAddOperands(), llvm::SmallVectorTemplateCommon< MachineInstr * >::size(), llvm::SMDiagnostic::SMDiagnostic(), llvm::GCOVBlock::sortDstEdges(), llvm::DebugLocEntry::sortUniqueValues(), SplitAddRecs(), llvm::MachineBasicBlock::SplitCriticalEdge(), splitVectorValues(), llvm::GCOVBlock::src_begin(), llvm::raw_svector_ostream::str(), StrengthenNoWrapFlags(), llvm::DebugInfoFinder::subprograms(), llvm::MachineModuleInfo::TidyLandingPads(), llvm::APInt::toString(), llvm::DebugInfoFinder::types(), llvm::SpillPlacement::Node::update(), llvm::BlockFrequencyInfoImplBase::updateLoopWithIrreducible(), llvm::PHITransAddr::Verify(), llvm::PMDataManager::verifyPreservedAnalysis(), VerifySubExpr(), llvm::SchedDFSImpl::visitPostorderNode(), llvm::LiveRange::vni_begin(), WalkChainUsers(), llvm::ScheduleDAGTopologicalSort::WillCreateCycle(), llvm::WriteBitcodeToFile(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::~BumpPtrAllocatorImpl(), llvm::ManagedStringPool::~ManagedStringPool(), llvm::PMDataManager::~PMDataManager(), and llvm::PMTopLevelManager::~PMTopLevelManager().
template<typename T, typename = void> const_iterator llvm::SmallVectorTemplateCommon< T, typename >::begin () const [inline]
Reimplemented in llvm::final< T >, and llvm::final< T >.
Definition at line 113 of file SmallVector.h.
template<typename T, typename = void> size_t llvm::SmallVectorTemplateCommon< T, typename >::capacity () const [inline]
Return the total number of elements in the currently allocated buffer.
Definition at line 131 of file SmallVector.h.
Referenced by llvm::raw_svector_ostream::init(), and llvm::raw_svector_ostream::resync().
template<typename T, typename = void> iterator llvm::SmallVectorTemplateCommon< T, typename >::capacity_ptr () [inline, protected]
Definition at line 117 of file SmallVector.h.
Referenced by llvm::SmallVectorTemplateCommon< MachineInstr * >::capacity().
template<typename T, typename = void> const_iterator llvm::SmallVectorTemplateCommon< T, typename >::capacity_ptr () const [inline, protected]
Definition at line 118 of file SmallVector.h.
template<typename T, typename = void> pointer llvm::SmallVectorTemplateCommon< T, typename >::data () [inline]
Return a pointer to the vector's buffer, even if empty().
Definition at line 134 of file SmallVector.h.
Referenced by llvm::FoldingSetNodeID::ComputeHash(), llvm::StringTableBuilder::finalize(), GenerateTBL(), llvm::ScalarEvolution::getAddExpr(), llvm::DIARawSymbol::getDataBytes(), llvm::MachineTraceMetrics::getProcResourceCycles(), lowerV8I16GeneralSingleInputVectorShuffle(), llvm::sys::fs::make_absolute(), llvm::sys::path::native(), llvm::FoldingSetNodeID::operator<(), llvm::FoldingSetNodeID::operator==(), and llvm::Twine::toNullTerminatedStringRef().
template<typename T, typename = void> const_pointer llvm::SmallVectorTemplateCommon< T, typename >::data () const [inline]
Return a pointer to the vector's buffer, even if empty().
Definition at line 136 of file SmallVector.h.
template<typename T, typename = void> iterator llvm::SmallVectorTemplateCommon< T, typename >::end () [inline]
Reimplemented in llvm::final< T >, and llvm::final< T >.
Definition at line 114 of file SmallVector.h.
Referenced by llvm::SpillPlacement::Node::addLink(), llvm::AArch64FunctionInfo::addLOHDirective(), llvm::DbgVariable::addMMIEntry(), llvm::FoldingSetNodeID::AddNodeID(), llvm::TargetPassConfig::addPass(), llvm::SUnit::addPred(), llvm::DebugLocEntry::addValues(), AnalyzeReturnValues(), AntiDepEdges(), llvm::RegsForValue::append(), llvm::SmallString< 256 >::assign(), llvm::DWARFAbbreviationDeclaration::attributes(), llvm::SmallVectorTemplateCommon< MachineInstr * >::back(), llvm::LazyCallGraph::Node::begin(), llvm::LazyCallGraph::begin(), llvm::DwarfDebug::beginFunction(), llvm::DwarfDebug::beginModule(), llvm::SUnit::biasCriticalPath(), llvm::GCOVFunction::block_end(), llvm::CriticalAntiDepBreaker::BreakAntiDependencies(), llvm::AggressiveAntiDepBreaker::BreakAntiDependencies(), llvm::ScheduleDAGInstrs::buildSchedGraph(), llvm::SDDbgInfo::ByvalParmDbgEnd(), calcMaxScratches(), CalcNodeSethiUllmanNumber(), canClobberReachingPhysRegUse(), llvm::CC_ARM_AAPCS_Custom_Aggregate(), llvm::RegPressureTracker::closeBottom(), closestSucc(), llvm::RegPressureTracker::closeTop(), llvm::PMDataManager::collectRequiredAnalysis(), llvm::DebugInfoFinder::compile_units(), llvm::SCEVAddRecExpr::computeAccessFunctions(), llvm::ComputeASanStackFrameLayout(), CriticalPathStep(), llvm::SDDbgInfo::DbgEnd(), llvm::SpecificBumpPtrAllocator< SCC >::DestroyAll(), llvm::GCOVBlock::dst_end(), llvm::SUnit::dumpAll(), llvm::PMTopLevelManager::dumpArguments(), llvm::PMDataManager::dumpPassArguments(), llvm::ConstantPool::emitEntries(), llvm::MCWinCOFFStreamer::EmitInstToData(), llvm::MCObjectStreamer::EmitInstToFragment(), llvm::UnwindOpcodeAssembler::EmitRaw(), llvm::ScheduleDAGSDNodes::EmitSchedule(), llvm::LiveRangeEdit::end(), llvm::SparseSet< RootData >::end(), llvm::MCInst::end(), llvm::GCModuleInfo::end(), llvm::LazyCallGraph::Node::end(), llvm::LiveRange::end(), llvm::LazyCallGraph::SCC::end(), llvm::LazyCallGraph::end(), llvm::object::MachOObjectFile::end_load_commands(), llvm::MDAttachmentMap::erase(), llvm::DIBuilder::finalize(), llvm::DebugLocEntry::finalize(), llvm::ScalarEvolution::findArrayDimensions(), llvm::SSAUpdaterImpl< UpdaterT >::FindAvailableVals(), findBasePointer(), llvm::SSAUpdaterImpl< UpdaterT >::FindExistingPHI(), llvm::DwarfDebug::findImportedEntitiesForScope(), llvm::SlotIndexes::findLiveInMBBs(), llvm::MCEncodedFragmentWithFixups< 8, 1 >::fixup_end(), llvm::RegScavenger::forward(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), llvm::MDAttachmentMap::getAll(), llvm::opt::ArgList::getAllArgValues(), llvm::opt::Arg::getAsString(), llvm::DebugLocStream::getBytes(), llvm::SelectionDAG::getConstant(), llvm::DWARFDebugInfoEntryMinimal::getInlinedChainForAddress(), llvm::DataLayout::getLargestLegalIntTypeSize(), llvm::LexicalScopes::getMachineBasicBlocks(), llvm::SlotIndexes::getMBBCoveringRange(), llvm::SlotIndexes::getMBBFromIndex(), llvm::ScalarEvolution::getMulExpr(), getNaturalGEPWithType(), llvm::DataLayout::getPointerABIAlignment(), llvm::DataLayout::getPointerPrefAlignment(), llvm::DataLayout::getPointerSize(), llvm::RegScavenger::getScavengingFrameIndices(), getSingleUnscheduledPred(), getSingleUnscheduledSucc(), llvm::ScalarEvolution::getSMaxExpr(), llvm::MCSection::getSubsectionInsertionPoint(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::getTotalMemory(), llvm::ScalarEvolution::getUMaxExpr(), getUncompressedData(), llvm::Loop::getUniqueExitBlocks(), llvm::DebugInfoFinder::global_variables(), GroupByComplexity(), HandleMergeInputChains(), hasDataSucc(), hasOnlyLiveInOpers(), hasOnlyLiveOutUses(), hasVRegCycleUse(), llvm::ExtractValueInst::idx_end(), llvm::InsertValueInst::idx_end(), llvm::raw_svector_ostream::init(), llvm::ScheduleDAGTopologicalSort::InitDAGTopologicalSorting(), llvm::PMTopLevelManager::initializeAllAnalysisInfo(), llvm::PMDataManager::initializeAnalysisImpl(), llvm::RegScavenger::initRegState(), initVRegCycle(), llvm::SlotIndexes::insertMBBInMaps(), llvm::FoldingSetNodeID::Intern(), llvm::AllocationOrder::isHint(), llvm::LoadAndStorePromoter::isInstInList(), llvm::RegScavenger::isScavengingFrameIndex(), llvm::LiveIntervalUnion::Query::isSeenInterference(), llvm::SpillPlacement::iterate(), iterateChainSucc(), LLVMGetRelocationTypeName(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::BlockFrequencyInfoImplBase::LoopData::LoopData(), lowerV16I8VectorShuffle(), lowerV8I16GeneralSingleInputVectorShuffle(), llvm::BlockFrequencyInfoImplBase::LoopData::members_end(), llvm::sys::path::native(), llvm::AllocationOrder::next(), llvm::AllocationOrder::nextWithDups(), numberCtrlDepsInSU(), numberCtrlPredInSU(), llvm::ObjectMemoryBuffer::ObjectMemoryBuffer(), llvm::SmallVectorImpl< MachineInstr * >::operator<(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::operator=(), llvm::yaml::Scanner::peekNext(), llvm::MCStreamer::PopSection(), llvm::PMDataManager::preserveHigherLevelAnalysis(), llvm::PassNameParser::printOptionInfo(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), processInstruction(), llvm::LatencyPriorityQueue::push(), llvm::ResourcePriorityQueue::push(), llvm::SmallVectorTemplateCommon< MachineInstr * >::rbegin(), llvm::opt::ArgList::rbegin(), llvm::SSAUpdaterImpl< UpdaterT >::RecordMatchingPHIs(), llvm::ConvergingVLIWScheduler::releaseBottomNode(), llvm::ScheduleDAGMI::releasePredecessors(), llvm::ScheduleDAGMI::releaseSuccessors(), llvm::ConvergingVLIWScheduler::releaseTopNode(), llvm::StatepointLoweringState::relocCallVisited(), llvm::MDAttachmentMap::remove_if(), RemoveInstInputs(), llvm::LazyCallGraph::SCC::removeInterSCCEdge(), llvm::LazyCallGraph::SCC::removeIntraSCCEdge(), llvm::ExecutionEngine::removeModule(), llvm::PMDataManager::removeNotPreservedAnalysis(), llvm::SUnit::removePred(), llvm::opt::Arg::render(), llvm::opt::Arg::renderAsInput(), llvm::GenericScheduler::reschedulePhysRegCopies(), reservePreviousStackSlotForValue(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Reset(), resetVRegCycle(), llvm::raw_svector_ostream::resync(), RewriteIntelBracExpression(), llvm::SlotIndexes::runOnMachineFunction(), llvm::LatencyPriorityQueue::scheduledNode(), llvm::ResourcePriorityQueue::scheduledNode(), llvm::PMTopLevelManager::schedulePass(), llvm::ConvergingVLIWScheduler::SchedulingCost(), llvm::DebugInfoFinder::scopes(), llvm::SUnit::setDepthDirty(), llvm::SUnit::setHeightDirty(), llvm::PMTopLevelManager::setLastUser(), llvm::HexagonShuffler::shuffle(), SimplifyAddOperands(), llvm::SmallVectorTemplateCommon< MachineInstr * >::size(), llvm::SMDiagnostic::SMDiagnostic(), llvm::GCOVBlock::sortDstEdges(), llvm::DebugLocEntry::sortUniqueValues(), SplitAddRecs(), llvm::MachineBasicBlock::SplitCriticalEdge(), splitVectorValues(), llvm::GCOVBlock::src_end(), StrengthenNoWrapFlags(), llvm::DebugInfoFinder::subprograms(), llvm::APInt::toString(), llvm::DebugInfoFinder::types(), llvm::SpillPlacement::Node::update(), llvm::BlockFrequencyInfoImplBase::updateLoopWithIrreducible(), llvm::PHITransAddr::Verify(), llvm::PMDataManager::verifyPreservedAnalysis(), VerifySubExpr(), llvm::SchedDFSImpl::visitPostorderNode(), llvm::LiveRange::vni_end(), WalkChainUsers(), llvm::ScheduleDAGTopologicalSort::WillCreateCycle(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::~BumpPtrAllocatorImpl(), llvm::ManagedStringPool::~ManagedStringPool(), llvm::PMDataManager::~PMDataManager(), and llvm::PMTopLevelManager::~PMTopLevelManager().
template<typename T, typename = void> const_iterator llvm::SmallVectorTemplateCommon< T, typename >::end () const [inline]
Reimplemented in llvm::final< T >, and llvm::final< T >.
Definition at line 115 of file SmallVector.h.
template<typename T, typename = void> reference llvm::SmallVectorTemplateCommon< T, typename >::front () [inline]
Definition at line 147 of file SmallVector.h.
Referenced by llvm::RegsForValue::AddInlineAsmOperands(), llvm::DwarfCompileUnit::attachRangesOrLowHighPC(), llvm::DwarfDebug::beginFunction(), llvm::LiveRange::beginIndex(), GetBranchWeights(), llvm::GCOVFunction::getEntryCount(), llvm::DwarfDebug::isLexicalScopeDIENull(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::IntervalMapImpl::Path::replaceRoot(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Reset(), and llvm::WriteBitcodeToFile().
template<typename T, typename = void> const_reference llvm::SmallVectorTemplateCommon< T, typename >::front () const [inline]
Definition at line 151 of file SmallVector.h.
template<typename T, typename = void> void llvm::SmallVectorTemplateCommon< T, typename >::grow_pod (size_t MinSizeInBytes, size_t TSize) [inline, protected]
Definition at line 80 of file SmallVector.h.
Referenced by llvm::SmallVectorTemplateCommon< MachineInstr * >::grow_pod().
template<typename T, typename = void> bool llvm::SmallVectorTemplateCommon< T, typename >::isSmall () const [inline, protected]
Return true if this is a smallvector which has not had dynamic memory allocated for it.
Definition at line 86 of file SmallVector.h.
template<typename T, typename = void> size_type llvm::SmallVectorTemplateCommon< T, typename >::max_size () const [inline]
Definition at line 128 of file SmallVector.h.
template<typename T, typename = void> reference llvm::SmallVectorTemplateCommon< T, typename >::operator[] (size_type idx) [inline]
Definition at line 138 of file SmallVector.h.
template<typename T, typename = void> const_reference llvm::SmallVectorTemplateCommon< T, typename >::operator[] (size_type idx) const [inline]
Definition at line 142 of file SmallVector.h.
template<typename T, typename = void> reverse_iterator llvm::SmallVectorTemplateCommon< T, typename >::rbegin () [inline]
Definition at line 122 of file SmallVector.h.
Referenced by llvm::PMTopLevelManager::findAnalysisPass(), llvm::SSAUpdaterImpl< UpdaterT >::FindAvailableVals(), llvm::SSAUpdaterImpl< UpdaterT >::FindDominators(), llvm::SSAUpdaterImpl< UpdaterT >::FindPHIPlacement(), fixPhis(), getNoopInput(), llvm::SCEVExpander::hoistIVInc(), llvm::SpillPlacement::iterate(), llvm::opt::ArgList::rend(), and llvm::returnTypeIsEligibleForTailCall().
template<typename T, typename = void> const_reverse_iterator llvm::SmallVectorTemplateCommon< T, typename >::rbegin () const [inline]
Definition at line 123 of file SmallVector.h.
template<typename T, typename = void> reverse_iterator llvm::SmallVectorTemplateCommon< T, typename >::rend () [inline]
Definition at line 124 of file SmallVector.h.
Referenced by llvm::opt::ArgList::begin(), llvm::opt::ArgList::filtered_begin(), llvm::PMTopLevelManager::findAnalysisPass(), llvm::SSAUpdaterImpl< UpdaterT >::FindAvailableVals(), llvm::SSAUpdaterImpl< UpdaterT >::FindDominators(), llvm::SSAUpdaterImpl< UpdaterT >::FindPHIPlacement(), fixPhis(), llvm::SCEVExpander::hoistIVInc(), llvm::SpillPlacement::iterate(), and llvm::returnTypeIsEligibleForTailCall().
template<typename T, typename = void> const_reverse_iterator llvm::SmallVectorTemplateCommon< T, typename >::rend () const [inline]
Definition at line 125 of file SmallVector.h.
template<typename T, typename = void> void llvm::SmallVectorTemplateCommon< T, typename >::resetToSmall () [inline, protected]
Put this vector in a state of being small.
Definition at line 91 of file SmallVector.h.
template<typename T, typename = void> void llvm::SmallVectorTemplateCommon< T, typename >::setEnd (T * P) [inline, protected]
Definition at line 95 of file SmallVector.h.
template<typename T, typename = void> size_type llvm::SmallVectorTemplateCommon< T, typename >::size () const [inline]
Definition at line 127 of file SmallVector.h.
Referenced by llvm::InstCombineWorklist::Add(), llvm::GCOVBlock::addCount(), llvm::GCOVBlock::addDstEdge(), llvm::DwarfDebug::addDwarfTypeUnitType(), llvm::RegsForValue::AddInlineAsmOperands(), llvm::cl::parser< const PassInfo * >::addLiteralOption(), llvm::DbgVariable::addMMIEntry(), llvm::bfi_detail::IrreducibleGraph::addNodesInLoop(), llvm::LoopAccessInfo::addRuntimeCheck(), llvm::AggressiveAntiDepBreaker::AggressiveAntiDepBreaker(), llvm::StatepointLoweringState::allocateStackSlot(), llvm::AllocationOrder::AllocationOrder(), AnalyzeArguments(), llvm::SystemZCCState::AnalyzeCallOperands(), llvm::CCState::AnalyzeCallOperands(), llvm::CCState::AnalyzeCallResult(), llvm::SystemZCCState::AnalyzeFormalArguments(), llvm::CCState::AnalyzeFormalArguments(), llvm::CCState::AnalyzeReturn(), llvm::sys::path::append(), llvm::cl::ValuesClass< DataType >::apply(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::atBeginning(), llvm::DwarfCompileUnit::attachRangesOrLowHighPC(), blockDominatesAnExit(), llvm::yaml::Output::blockScalarString(), buildFromShuffleMostly(), buildGEP(), buildMultiplyTree(), BuildSubAggregate(), buildVector(), llvm::yaml::Output::canElideEmptySequence(), canUseSiblingCall(), canWidenShuffleElements(), llvm::CC_ARM_AAPCS_Custom_Aggregate(), llvm::CCState::CheckReturn(), llvm::ArrayRecycler< MachineOperand >::clear(), CollectBSwapParts(), CollectInsertionElements(), CombineBaseUpdate(), llvm::ShuffleVectorSDNode::commuteMask(), llvm::DebugInfoFinder::compile_unit_count(), llvm::IntEqClasses::compress(), llvm::SCEVAddRecExpr::computeAccessFunctions(), llvm::ComputeASanStackFrameLayout(), llvm::FoldingSetNodeID::ComputeHash(), llvm::EHStreamer::computePadMap(), llvm::LiveRange::containsOneValue(), CreateGCRelocates(), llvm::FunctionLoweringInfo::CreateRegs(), createUniqueEntity(), llvm::LiveRange::createValueCopy(), llvm::DeleteDeadPHIs(), llvm::RuntimeDyldELF::deregisterEHFrames(), llvm::RegisterPressure::dump(), llvm::PHITransAddr::dump(), llvm::opt::Arg::dump(), llvm::LexicalScope::dump(), llvm::MCFragment::dump(), llvm::SlotIndexes::dump(), llvm::SUnit::dumpAll(), llvm::PMTopLevelManager::dumpPasses(), llvm::DWARFContextInMemory::DWARFContextInMemory(), llvm::DIEAbbrev::Emit(), llvm::MCDwarfLineTableHeader::Emit(), EmitAddTreeOfValues(), llvm::MCWinCOFFStreamer::EmitCOFFSecRel32(), llvm::MCWinCOFFStreamer::EmitCOFFSectionIndex(), EmitDarwinBCHeaderAndTrailer(), llvm::PPCFrameLowering::emitEpilogue(), EmitGenDwarfInfo(), llvm::ExecutionEngine::emitGlobals(), llvm::MCObjectStreamer::EmitGPRel32Value(), llvm::MCObjectStreamer::EmitGPRel64Value(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::MCWinCOFFStreamer::EmitInstToData(), llvm::PPCFrameLowering::emitPrologue(), llvm::UnwindOpcodeAssembler::EmitRaw(), llvm::MCObjectStreamer::EmitValueImpl(), llvm::SUnitIterator::end(), llvm::WinCodeViewLineTables::endModule(), llvm::MachineTraceMetrics::Ensemble::Ensemble(), llvm::cl::ExpandResponseFiles(), ExtendUsesToFormExtLoad(), llvm::StringTableBuilder::finalize(), llvm::UnwindOpcodeAssembler::Finalize(), llvm::DIBuilder::finalize(), llvm::DebugLocEntry::finalize(), llvm::finalizeBundle(), llvm::ScalarEvolution::findArrayDimensions(), findArrayDimensionsRec(), llvm::ExecutionEngine::FindFunctionNamed(), llvm::ExecutionEngine::FindGlobalVariableNamed(), llvm::SparseMultiSet< VReg2SUnit, VirtReg2IndexFunctor >::findIndex(), llvm::MachineInstr::findTiedOperandIdx(), llvm::SplitEditor::finish(), fixupVariableFloatArgs(), llvm::MCObjectStreamer::flushPendingLabels(), ForwardSwitchConditionToPHI(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), llvm::object::MachOObjectFile::getAnyRelocationSection(), GetBranchWeights(), llvm::RGPassManager::getContainedPass(), llvm::LPPassManager::getContainedPass(), llvm::FPPassManager::getContainedPass(), llvm::SelectionDAGBuilder::getControlRoot(), llvm::RegsForValue::getCopyFromRegs(), llvm::RegsForValue::getCopyToRegs(), llvm::MCDwarfLineTableHeader::getFile(), llvm::DWARFAbbreviationDeclaration::getFormByIndex(), llvm::DIInliningInfo::getFrame(), getFunctionNameForAddress(), llvm::ExecutionEngine::getGlobalValueAtAddress(), llvm::NVPTXMachineFunctionInfo::getImageHandleSymbol(), llvm::NVPTXMachineFunctionInfo::getImageHandleSymbolIndex(), getIncomingStatepointGCValues(), llvm::DWARFContext::getInliningInfoForAddress(), llvm::CCState::getInRegsParamInfo(), llvm::CCState::getInRegsParamsCount(), llvm::object::MachOObjectFile::getLibraryShortNameByIndex(), llvm::MachineFrameInfo::getLocalFrameObjectCount(), llvm::MachineFrameInfo::getLocalFrameObjectMap(), llvm::SlotIndexes::getMBBFromIndex(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), llvm::ScalarEvolution::getMulExpr(), llvm::LiveRange::getNextValue(), llvm::SelectionDAG::getNode(), getNoopInput(), llvm::DIInliningInfo::getNumberOfFrames(), llvm::GCOVFunction::getNumBlocks(), llvm::PMTopLevelManager::getNumContainedManagers(), llvm::PMDataManager::getNumContainedPasses(), llvm::GCOVBlock::getNumDstEdges(), llvm::ExtractValueInst::getNumIndices(), llvm::InsertValueInst::getNumIndices(), llvm::DebugLocStream::getNumLists(), llvm::BitCodeAbbrev::getNumOperandInfos(), llvm::MCInst::getNumOperands(), llvm::cl::parser< const PassInfo * >::getNumOptions(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::GetNumSlabs(), llvm::GCOVBlock::getNumSrcEdges(), llvm::LiveRange::getNumValNums(), llvm::opt::Arg::getNumValues(), llvm::AMDGPUTargetLowering::getOriginalFunctionArgs(), llvm::MachObjectWriter::getPaddingSize(), llvm::LessRecordRegister::RecordParts::getPart(), llvm::MachineTraceMetrics::getProcResourceCycles(), llvm::CCState::getRemainingRegParmsForType(), llvm::GetReturnInfo(), llvm::SelectionDAGBuilder::getRoot(), llvm::object::MachOObjectFile::getSectionRawFinalSegmentName(), llvm::object::MachOObjectFile::getSectionRawName(), getShuffleInput(), llvm::ScalarEvolution::getSMaxExpr(), GetSymbolFromOperand(), llvm::object::MachOObjectFile::getSymbolSection(), llvm::ScalarEvolution::getUMaxExpr(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::DebugInfoFinder::global_variable_count(), GroupByComplexity(), llvm::IntEqClasses::grow(), llvm::IndexedMap< unsigned >::grow(), HandleMergeInputChains(), llvm::DbgVariable::hasComplexAddress(), llvm::IndexedMap< unsigned >::inBounds(), llvm::raw_svector_ostream::init(), llvm::ScheduleDAGTopologicalSort::InitDAGTopologicalSorting(), llvm::RegPressureTracker::initLiveThru(), InlineCallIfPossible(), llvm::InlineFunction(), llvm::LiveIntervals::insertMBBInMaps(), llvm::SlotIndexes::insertMBBInMaps(), llvm::FoldingSetNodeID::Intern(), isAlternateVectorMask(), isExitBlock(), llvm::DwarfDebug::isLexicalScopeDIENull(), llvm::DOTGraphTraits< ScheduleDAGMI * >::isNodeHidden(), llvm::SUnit::isPred(), isReverseVectorMask(), llvm::StatepointLoweringState::isStackSlotAllocated(), llvm::SUnit::isSucc(), llvm::MCContext::isValidDwarfFileNumber(), isVOP3(), llvm::LiveRange::join(), llvm::LazyCallGraph::LazyCallGraph(), LLVMGetRelocationTypeName(), llvm::MipsSEInstrInfo::loadImmediate(), LookupNearestOption(), llvm::BlockFrequencyInfoImplBase::LoopData::LoopData(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), LowerCallResult(), llvm::FastISel::lowerCallTo(), llvm::TargetLowering::LowerCallTo(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerReturn(), lowerV16I8VectorShuffle(), lowerV8F32VectorShuffle(), lowerV8I16GeneralSingleInputVectorShuffle(), lowerV8I32VectorShuffle(), LowerVectorAllZeroTest(), llvm::object::MachOObjectFile::MachOObjectFile(), llvm::sys::fs::make_absolute(), llvm::PHITransAddr::NeedsPHITranslationFromBlock(), llvm::CCState::nextInRegsParam(), operandsHasOptionalOp(), operandsHaveModifiers(), llvm::FoldingSetNodeID::operator<(), llvm::object::ExportEntry::operator==(), llvm::FoldingSetNodeID::operator==(), llvm::SmallVectorImpl< MachineInstr * >::operator==(), llvm::IndexedMap< unsigned >::operator[](), llvm::SmallVectorTemplateCommon< MachineInstr * >::operator[](), llvm::DWARFDebugLoc::parse(), llvm::DWARFDebugLocDWO::parse(), llvm::cl::parser< const PassInfo * >::parse(), llvm::R600TargetLowering::PerformDAGCombine(), PerformTargetShuffleCombine(), llvm::PHITransAddr::PHITranslateWithInsertion(), placeSplitBlockCarefully(), llvm::MCStreamer::PopSection(), prependCompressionHeader(), llvm::DIEAbbrev::print(), llvm::LiveIntervals::print(), llvm::MachineTraceMetrics::Ensemble::print(), llvm::MachineInstr::print(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::PrintStats(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::DIEAbbrev::Profile(), llvm::promoteLoopAccessesToScalars(), llvm::GCOVFile::readGCDA(), llvm::GCOVFunction::readGCDA(), RecognizeIdentityMask(), redirectValuesFromPredecessorsToPhi(), llvm::RuntimeDyldELF::registerEHFrames(), llvm::RegsForValue::RegsForValue(), llvm::LiveIntervals::releaseMemory(), llvm::sys::path::remove_filename(), removeDuplicatesGCPtrs(), llvm::cl::parser< const PassInfo * >::removeLiteralOption(), llvm::LiveRange::RenumberValues(), llvm::sys::path::replace_extension(), llvm::GenericScheduler::reschedulePhysRegCopies(), llvm::StatepointLoweringState::reserveStackSlot(), llvm::RuntimeDyldImpl::resolveRelocationList(), llvm::raw_svector_ostream::resync(), llvm::AllocationOrder::rewind(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::RegScavenger::scavengeRegister(), llvm::ResourcePriorityQueue::scheduledNode(), llvm::DebugInfoFinder::scope_count(), llvm::object::MachOObjectFile::section_end(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::FastISel::selectPatchpoint(), llvm::EngineBuilder::selectTarget(), llvm::FunctionLoweringInfo::set(), SimplifyAddOperands(), llvm::IndexedMap< unsigned >::size(), llvm::opt::ArgList::size(), llvm::LiveRangeEdit::size(), llvm::MCInst::size(), llvm::SparseSet< RootData >::size(), llvm::LiveRange::size(), llvm::SparseMultiSet< VReg2SUnit, VirtReg2IndexFunctor >::size(), llvm::MDAttachmentMap::size(), llvm::LessRecordRegister::RecordParts::size(), SplitAddRecs(), stablize_order(), llvm::StatepointLoweringState::startNewStatepoint(), llvm::raw_svector_ostream::str(), llvm::DebugInfoFinder::subprogram_count(), llvm::Twine::toNullTerminatedStringRef(), llvm::APInt::toString(), TrackDefUses(), llvm::DebugInfoFinder::type_count(), llvm::IntEqClasses::uncompress(), updatePhysDepsDownwards(), updatePhysDepsUpwards(), llvm::PHITransAddr::Verify(), llvm::MachineTraceMetrics::Ensemble::verify(), llvm::LiveRange::verify(), llvm::MachineTraceMetrics::verifyAnalysis(), VerifyVectorTypes(), llvm::InstCombiner::visitAllocaInst(), llvm::WriteBitcodeToFile(), WriteFunctionLocalMetadata(), llvm::MCAssembler::writeSectionData(), and llvm::opt::Arg::~Arg().
Friends And Related Function Documentation
template<typename T, typename = void> friend struct SmallVectorStorage [friend]
Definition at line 68 of file SmallVector.h.
The documentation for this class was generated from the following file:
SmallVector.h