LLVM: llvm::MachineModuleInfoImpl Class Reference
llvm::MachineModuleInfoImpl Class Reference
MachineModuleInfoImpl - This class can be derived from and used by targets to hold private target-specific information for each Module.
#include <MachineModuleInfo.h>
Public Types
typedef PointerIntPair
< MCSymbol *, 1, bool > StubValueTy
typedef std::vector< std::pair
< MCSymbol *, StubValueTy > > SymbolListTy
Public Member Functions
virtual ~MachineModuleInfoImpl ()
Static Protected Member Functions
static SymbolListTy getSortedStubs (DenseMap< MCSymbol *, StubValueTy > &)
Return the entries from a DenseMap in a deterministic sorted orer.
Detailed Description
MachineModuleInfoImpl - This class can be derived from and used by targets to hold private target-specific information for each Module.
Objects of type are accessed/created with MMI::getInfo and destroyed when the MachineModuleInfo is destroyed.
Definition at line 97 of file MachineModuleInfo.h.
Member Typedef Documentation
typedef PointerIntPair<MCSymbol*, 1, bool> llvm::MachineModuleInfoImpl::StubValueTy
Definition at line 99 of file MachineModuleInfo.h.
typedef std::vector<std::pair<MCSymbol*, StubValueTy> > llvm::MachineModuleInfoImpl::SymbolListTy
Definition at line 101 of file MachineModuleInfo.h.
Constructor & Destructor Documentation
virtual llvm::MachineModuleInfoImpl::~MachineModuleInfoImpl () [virtual]
Member Function Documentation
MachineModuleInfoImpl::SymbolListTy MachineModuleInfoImpl::getSortedStubs (DenseMap< MCSymbol *, StubValueTy > & Map) [static, protected]
Return the entries from a DenseMap in a deterministic sorted orer.
Clears the map.
Definition at line 34 of file MachineModuleInfoImpls.cpp.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::begin(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::tgtok::List, and SortSymbolPair().
Referenced by llvm::MachineModuleInfoMachO::GetFnStubList(), llvm::MachineModuleInfoMachO::GetGVStubList(), llvm::MachineModuleInfoELF::GetGVStubList(), and llvm::MachineModuleInfoMachO::GetHiddenGVStubList().
The documentation for this class was generated from the following files:
MachineModuleInfo.h
MachineModuleInfoImpls.cpp