LLVM: llvm::X86TTIImpl Class Reference
llvm::X86TTIImpl Class Reference
#include <X86TargetTransformInfo.h>
Public Member Functions
X86TTIImpl (const X86TargetMachine *TM, Function &F)
X86TTIImpl (const X86TTIImpl &Arg)
X86TTIImpl (X86TTIImpl &&Arg)
X86TTIImpl & operator= (const X86TTIImpl &RHS)
X86TTIImpl & operator= (X86TTIImpl &&RHS)
Scalar TTI Implementations
TTI::PopcntSupportKind getPopcntSupport (unsigned TyWidth)
Vector TTI Implementations
unsigned getNumberOfRegisters (bool Vector)
unsigned getRegisterBitWidth (bool Vector)
unsigned getMaxInterleaveFactor (unsigned VF)
unsigned getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::OperandValueKind Opd1Info=TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info=TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo=TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo=TTI::OP_None)
unsigned getShuffleCost (TTI::ShuffleKind Kind, Type *Tp, int Index, Type *SubTp)
unsigned getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src)
unsigned getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy)
unsigned getVectorInstrCost (unsigned Opcode, Type *Val, unsigned Index)
unsigned getMemoryOpCost (unsigned Opcode, Type *Src, unsigned Alignment, unsigned AddressSpace)
unsigned getMaskedMemoryOpCost (unsigned Opcode, Type *Src, unsigned Alignment, unsigned AddressSpace)
unsigned getAddressComputationCost (Type *PtrTy, bool IsComplex)
unsigned getReductionCost (unsigned Opcode, Type *Ty, bool IsPairwiseForm)
unsigned getIntImmCost (int64_t)
Calculate the cost of materializing a 64-bit value.
unsigned getIntImmCost (const APInt &Imm, Type *Ty)
unsigned getIntImmCost (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty)
unsigned getIntImmCost (Intrinsic::ID IID, unsigned Idx, const APInt &Imm, Type *Ty)
bool isLegalMaskedLoad (Type *DataType, int Consecutive)
bool isLegalMaskedStore (Type *DataType, int Consecutive)
Detailed Description
Definition at line 28 of file X86TargetTransformInfo.h.
Constructor & Destructor Documentation
llvm::X86TTIImpl::X86TTIImpl (const X86TargetMachine * TM, Function & F) [inline, explicit]
Definition at line 42 of file X86TargetTransformInfo.h.
llvm::X86TTIImpl::X86TTIImpl (const X86TTIImpl & Arg) [inline]
Definition at line 46 of file X86TargetTransformInfo.h.
llvm::X86TTIImpl::X86TTIImpl (X86TTIImpl && Arg) [inline]
Definition at line 48 of file X86TargetTransformInfo.h.
Member Function Documentation
unsigned X86TTIImpl::getAddressComputationCost (Type * PtrTy, bool IsComplex)
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 874 of file X86TargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< X86TTIImpl >::getAddressComputationCost(), and llvm::Type::isVectorTy().
unsigned X86TTIImpl::getArithmeticInstrCost (unsigned Opcode, Type * Ty, TTI::OperandValueKind Opd1Info = TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info = TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo = TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo = TTI::OP_None)
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 87 of file X86TargetTransformInfo.cpp.
References ADD, llvm::CostTblEntry< TypeTy >::Cost, llvm::CostTableLookup(), llvm::BasicTTIImplBase< X86TTIImpl >::getArithmeticInstrCost(), llvm::LShr, llvm::AArch64CC::LT, llvm::ISD::MUL, llvm::TargetTransformInfo::OK_NonUniformConstantValue, llvm::TargetTransformInfo::OK_UniformConstantValue, llvm::TargetTransformInfo::OP_None, llvm::TargetTransformInfo::OP_PowerOf2, llvm::ISD::SDIV, llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SRL, SUB, llvm::ISD::UDIV, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::MVT::v2i64, llvm::MVT::v32i8, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v8i16, llvm::MVT::v8i32, and llvm::MVT::v8i64.
unsigned X86TTIImpl::getCastInstrCost (unsigned Opcode, Type * Dst, Type * Src)
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 463 of file X86TargetTransformInfo.cpp.
References llvm::ConvertCostTableLookup(), llvm::TypeConversionCostTblEntry< TypeTy >::Cost, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::BasicTTIImplBase< X86TTIImpl >::getCastInstrCost(), llvm::EVT::getSimpleVT(), llvm::EVT::isSimple(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SINT_TO_FP, llvm::ISD::TRUNCATE, llvm::ISD::UINT_TO_FP, llvm::MVT::v16f32, llvm::MVT::v16i1, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i1, llvm::MVT::v4i16, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v4i8, llvm::MVT::v8f32, llvm::MVT::v8f64, llvm::MVT::v8i1, llvm::MVT::v8i16, llvm::MVT::v8i32, llvm::MVT::v8i64, llvm::MVT::v8i8, and llvm::ISD::ZERO_EXTEND.
unsigned X86TTIImpl::getCmpSelInstrCost (unsigned Opcode, Type * ValTy, Type * CondTy)
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 667 of file X86TargetTransformInfo.cpp.
References llvm::CostTblEntry< TypeTy >::Cost, llvm::CostTableLookup(), llvm::BasicTTIImplBase< X86TTIImpl >::getCmpSelInstrCost(), llvm::AArch64CC::LT, llvm::ISD::SETCC, llvm::MVT::v16f32, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v32i8, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v8f32, llvm::MVT::v8f64, llvm::MVT::v8i16, llvm::MVT::v8i32, and llvm::MVT::v8i64.
Referenced by getMaskedMemoryOpCost().
unsigned X86TTIImpl::getIntImmCost (int64_t Val)
Calculate the cost of materializing a 64-bit value.
This helper method might only calculate a fraction of a larger immediate. Therefore it is valid to return a cost of ZERO.
Definition at line 970 of file X86TargetTransformInfo.cpp.
References llvm::isInt< 32 >(), llvm::TargetTransformInfo::TCC_Basic, and llvm::TargetTransformInfo::TCC_Free.
Referenced by getIntImmCost().
unsigned X86TTIImpl::getIntImmCost (const APInt & Imm, Type * Ty)
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 980 of file X86TargetTransformInfo.cpp.
References llvm::APInt::ashr(), getIntImmCost(), llvm::Type::getPrimitiveSizeInBits(), llvm::APInt::getSExtValue(), llvm::Type::isIntegerTy(), llvm::APInt::sext(), llvm::APInt::sextOrTrunc(), and llvm::TargetTransformInfo::TCC_Free.
unsigned X86TTIImpl::getIntImmCost (unsigned Opcode, unsigned Idx, const APInt & Imm, Type * Ty)
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 1014 of file X86TargetTransformInfo.cpp.
References llvm::APIntOps::And(), llvm::Call, getIntImmCost(), llvm::Type::getPrimitiveSizeInBits(), llvm::IntToPtr, llvm::Type::isIntegerTy(), llvm::SPII::Load, llvm::LShr, llvm::APIntOps::Or(), llvm::TargetOpcode::PHI, llvm::MipsISD::Ret, llvm::MCID::Select, llvm::SExt, llvm::SPII::Store, llvm::TargetTransformInfo::TCC_Basic, llvm::TargetTransformInfo::TCC_Free, llvm::Trunc, and llvm::APIntOps::Xor().
unsigned X86TTIImpl::getIntImmCost (Intrinsic::ID IID, unsigned Idx, const APInt & Imm, Type * Ty)
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 1083 of file X86TargetTransformInfo.cpp.
References llvm::APInt::getBitWidth(), getIntImmCost(), llvm::Type::getPrimitiveSizeInBits(), llvm::APInt::getSExtValue(), llvm::isInt< 32 >(), llvm::Type::isIntegerTy(), and llvm::TargetTransformInfo::TCC_Free.
unsigned X86TTIImpl::getMaskedMemoryOpCost (unsigned Opcode, Type * Src, unsigned Alignment, unsigned AddressSpace)
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 821 of file X86TargetTransformInfo.cpp.
References llvm::dyn_cast(), llvm::VectorType::get(), llvm::BasicTTIImplBase< X86TTIImpl >::getCFInstrCost(), getCmpSelInstrCost(), llvm::getGlobalContext(), llvm::Type::getInt8Ty(), getMemoryOpCost(), llvm::BasicTTIImplBase< X86TTIImpl >::getMemoryOpCost(), llvm::Type::getScalarType(), getShuffleCost(), llvm::Type::getVectorElementType(), llvm::Type::getVectorNumElements(), isLegalMaskedLoad(), isLegalMaskedStore(), llvm::isPowerOf2_32(), llvm::SPII::Load, llvm::AArch64CC::LT, llvm::TargetTransformInfo::SK_Alternate, llvm::TargetTransformInfo::SK_InsertSubvector, and llvm::SPII::Store.
unsigned X86TTIImpl::getMaxInterleaveFactor (unsigned VF)
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 69 of file X86TargetTransformInfo.cpp.
unsigned X86TTIImpl::getMemoryOpCost (unsigned Opcode, Type * Src, unsigned Alignment, unsigned AddressSpace)
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 776 of file X86TargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< X86TTIImpl >::getMemoryOpCost(), llvm::isPowerOf2_32(), llvm::SPII::Load, llvm::AArch64CC::LT, and llvm::SPII::Store.
Referenced by getMaskedMemoryOpCost().
unsigned X86TTIImpl::getNumberOfRegisters (bool Vector)
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 43 of file X86TargetTransformInfo.cpp.
TargetTransformInfo::PopcntSupportKind X86TTIImpl::getPopcntSupport (unsigned TyWidth)
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 35 of file X86TargetTransformInfo.cpp.
References llvm::isPowerOf2_32(), llvm::TargetTransformInfo::PSK_FastHardware, and llvm::TargetTransformInfo::PSK_Software.
unsigned X86TTIImpl::getReductionCost (unsigned Opcode, Type * Ty, bool IsPairwiseForm)
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 887 of file X86TargetTransformInfo.cpp.
References ADD, llvm::CostTblEntry< TypeTy >::Cost, llvm::CostTableLookup(), llvm::ISD::FADD, llvm::BasicTTIImplBase< X86TTIImpl >::getReductionCost(), llvm::AArch64CC::LT, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v8f32, llvm::MVT::v8i16, and llvm::MVT::v8i32.
unsigned X86TTIImpl::getRegisterBitWidth (bool Vector)
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 55 of file X86TargetTransformInfo.cpp.
unsigned X86TTIImpl::getShuffleCost (TTI::ShuffleKind Kind, Type * Tp, int Index, Type * SubTp)
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 348 of file X86TargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< X86TTIImpl >::getShuffleCost(), llvm::AArch64CC::LT, llvm::TargetTransformInfo::SK_Alternate, llvm::TargetTransformInfo::SK_Reverse, llvm::MVT::v16i16, llvm::MVT::v32i8, llvm::MVT::v4f64, llvm::MVT::v4i64, llvm::MVT::v8f32, llvm::MVT::v8i32, and llvm::ISD::VECTOR_SHUFFLE.
Referenced by getMaskedMemoryOpCost().
unsigned X86TTIImpl::getVectorInstrCost (unsigned Opcode, Type * Val, unsigned Index)
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 737 of file X86TargetTransformInfo.cpp.
References llvm::Type::getScalarType(), llvm::BasicTTIImplBase< X86TTIImpl >::getVectorInstrCost(), llvm::Type::isFloatingPointTy(), llvm::Type::isVectorTy(), and llvm::AArch64CC::LT.
bool X86TTIImpl::isLegalMaskedLoad (Type * DataType, int Consecutive)
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 1118 of file X86TargetTransformInfo.cpp.
References llvm::Type::getPrimitiveSizeInBits().
Referenced by getMaskedMemoryOpCost(), and isLegalMaskedStore().
bool X86TTIImpl::isLegalMaskedStore (Type * DataType, int Consecutive)
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 1129 of file X86TargetTransformInfo.cpp.
References isLegalMaskedLoad().
Referenced by getMaskedMemoryOpCost().
X86TTIImpl& llvm::X86TTIImpl::operator= (const X86TTIImpl & RHS) [inline]
Definition at line 51 of file X86TargetTransformInfo.h.
References llvm::BasicTTIImplBase< X86TTIImpl >::operator=().
X86TTIImpl& llvm::X86TTIImpl::operator= (X86TTIImpl && RHS) [inline]
Definition at line 57 of file X86TargetTransformInfo.h.
References llvm::BasicTTIImplBase< X86TTIImpl >::operator=().
The documentation for this class was generated from the following files:
X86TargetTransformInfo.h
X86TargetTransformInfo.cpp