LLVM: llvm::SystemZMachineFunctionInfo Class Reference
llvm::SystemZMachineFunctionInfo Class Reference
#include <SystemZMachineFunctionInfo.h>
Public Member Functions
SystemZMachineFunctionInfo (MachineFunction &MF)
unsigned getLowSavedGPR () const
void setLowSavedGPR (unsigned Reg)
unsigned getHighSavedGPR () const
void setHighSavedGPR (unsigned Reg)
unsigned getVarArgsFirstGPR () const
void setVarArgsFirstGPR (unsigned GPR)
unsigned getVarArgsFirstFPR () const
void setVarArgsFirstFPR (unsigned FPR)
unsigned getVarArgsFrameIndex () const
void setVarArgsFrameIndex (unsigned FI)
unsigned getRegSaveFrameIndex () const
void setRegSaveFrameIndex (unsigned FI)
bool getManipulatesSP () const
void setManipulatesSP (bool MSP)
unsigned getNumLocalDynamicTLSAccesses () const
void incNumLocalDynamicTLSAccesses ()
Detailed Description
Definition at line 17 of file SystemZMachineFunctionInfo.h.
Constructor & Destructor Documentation
llvm::SystemZMachineFunctionInfo::SystemZMachineFunctionInfo (MachineFunction & MF) [inline, explicit]
Definition at line 29 of file SystemZMachineFunctionInfo.h.
Member Function Documentation
unsigned llvm::SystemZMachineFunctionInfo::getHighSavedGPR () const [inline]
Definition at line 41 of file SystemZMachineFunctionInfo.h.
Referenced by llvm::SystemZFrameLowering::restoreCalleeSavedRegisters().
unsigned llvm::SystemZMachineFunctionInfo::getLowSavedGPR () const [inline]
Definition at line 36 of file SystemZMachineFunctionInfo.h.
Referenced by llvm::SystemZFrameLowering::emitEpilogue(), llvm::SystemZFrameLowering::emitPrologue(), and llvm::SystemZFrameLowering::restoreCalleeSavedRegisters().
bool llvm::SystemZMachineFunctionInfo::getManipulatesSP () const [inline]
Definition at line 64 of file SystemZMachineFunctionInfo.h.
unsigned llvm::SystemZMachineFunctionInfo::getNumLocalDynamicTLSAccesses () const [inline]
Definition at line 68 of file SystemZMachineFunctionInfo.h.
unsigned llvm::SystemZMachineFunctionInfo::getRegSaveFrameIndex () const [inline]
Definition at line 59 of file SystemZMachineFunctionInfo.h.
unsigned llvm::SystemZMachineFunctionInfo::getVarArgsFirstFPR () const [inline]
Definition at line 50 of file SystemZMachineFunctionInfo.h.
unsigned llvm::SystemZMachineFunctionInfo::getVarArgsFirstGPR () const [inline]
Definition at line 46 of file SystemZMachineFunctionInfo.h.
Referenced by llvm::SystemZFrameLowering::processFunctionBeforeCalleeSavedScan(), and llvm::SystemZFrameLowering::spillCalleeSavedRegisters().
unsigned llvm::SystemZMachineFunctionInfo::getVarArgsFrameIndex () const [inline]
Definition at line 54 of file SystemZMachineFunctionInfo.h.
void llvm::SystemZMachineFunctionInfo::incNumLocalDynamicTLSAccesses () [inline]
Definition at line 69 of file SystemZMachineFunctionInfo.h.
void llvm::SystemZMachineFunctionInfo::setHighSavedGPR (unsigned Reg) [inline]
Definition at line 42 of file SystemZMachineFunctionInfo.h.
Referenced by llvm::SystemZFrameLowering::spillCalleeSavedRegisters().
void llvm::SystemZMachineFunctionInfo::setLowSavedGPR (unsigned Reg) [inline]
Definition at line 37 of file SystemZMachineFunctionInfo.h.
Referenced by llvm::SystemZFrameLowering::spillCalleeSavedRegisters().
void llvm::SystemZMachineFunctionInfo::setManipulatesSP (bool MSP) [inline]
Definition at line 65 of file SystemZMachineFunctionInfo.h.
void llvm::SystemZMachineFunctionInfo::setRegSaveFrameIndex (unsigned FI) [inline]
Definition at line 60 of file SystemZMachineFunctionInfo.h.
Referenced by llvm::SystemZTargetLowering::LowerFormalArguments().
void llvm::SystemZMachineFunctionInfo::setVarArgsFirstFPR (unsigned FPR) [inline]
Definition at line 51 of file SystemZMachineFunctionInfo.h.
References FPR.
Referenced by llvm::SystemZTargetLowering::LowerFormalArguments().
void llvm::SystemZMachineFunctionInfo::setVarArgsFirstGPR (unsigned GPR) [inline]
Definition at line 47 of file SystemZMachineFunctionInfo.h.
Referenced by llvm::SystemZTargetLowering::LowerFormalArguments().
void llvm::SystemZMachineFunctionInfo::setVarArgsFrameIndex (unsigned FI) [inline]
Definition at line 55 of file SystemZMachineFunctionInfo.h.
Referenced by llvm::SystemZTargetLowering::LowerFormalArguments().
The documentation for this class was generated from the following files:
SystemZMachineFunctionInfo.h
SystemZMachineFunctionInfo.cpp