LLVM: llvm::SystemZInstPrinter Class Reference
llvm::SystemZInstPrinter Class Reference
#include <SystemZInstPrinter.h>
Public Member Functions
SystemZInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printInstruction (const MCInst *MI, raw_ostream &O)
void printRegName (raw_ostream &O, unsigned RegNo) const override
Print the assembler register name.
void printInst (const MCInst *MI, raw_ostream &O, StringRef Annot, const MCSubtargetInfo &STI) override
Print the specified MCInst to the specified raw_ostream.
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo)
static void printAddress (unsigned Base, int64_t Disp, unsigned Index, raw_ostream &O)
static void printOperand (const MCOperand &MO, const MCAsmInfo *MAI, raw_ostream &O)
Detailed Description
Definition at line 23 of file SystemZInstPrinter.h.
Constructor & Destructor Documentation
llvm::SystemZInstPrinter::SystemZInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) [inline]
Definition at line 25 of file SystemZInstPrinter.h.
Member Function Documentation
static const char* llvm::SystemZInstPrinter::getRegisterName (unsigned RegNo) [static]
Referenced by printAddress(), printOperand(), and printRegName().
void SystemZInstPrinter::printAddress (unsigned Base, int64_t Disp, unsigned Index, raw_ostream & O) [static]
Definition at line 24 of file SystemZInstPrinter.cpp.
References getRegisterName().
Referenced by llvm::SystemZAsmPrinter::PrintAsmMemoryOperand().
void SystemZInstPrinter::printInst (const MCInst * MI, raw_ostream & OS, StringRef Annot, const MCSubtargetInfo & STI) [override, virtual]
Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Definition at line 52 of file SystemZInstPrinter.cpp.
References llvm::MCInstPrinter::printAnnotation(), and printInstruction().
void llvm::SystemZInstPrinter::printInstruction (const MCInst * MI, raw_ostream & O)
Referenced by printInst().
void SystemZInstPrinter::printOperand (const MCOperand & MO, const MCAsmInfo * MAI, raw_ostream & O) [static]
Definition at line 40 of file SystemZInstPrinter.cpp.
References llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), getRegisterName(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm_unreachable, and llvm::MCExpr::print().
void SystemZInstPrinter::printRegName (raw_ostream & OS, unsigned RegNo) const [override, virtual]
Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 59 of file SystemZInstPrinter.cpp.
References getRegisterName().
The documentation for this class was generated from the following files:
SystemZInstPrinter.h
SystemZInstPrinter.cpp