LLVM: llvm::DIEEntry Class Reference
llvm::DIEEntry Class Reference
#include <DIE.h>
Public Member Functions
DIEEntry (DIE &E)
DIE & getEntry () const
void EmitValue (const AsmPrinter *AP, dwarf::Form Form) const
EmitValue - Emit debug information entry offset.
unsigned SizeOf (const AsmPrinter *AP, dwarf::Form Form) const
void print (raw_ostream &O) const
Static Public Member Functions
static unsigned getRefAddrSize (const AsmPrinter *AP)
Returns size of a ref_addr entry.
Detailed Description
Definition at line 234 of file DIE.h.
Constructor & Destructor Documentation
llvm::DIEEntry::DIEEntry (DIE & E) [inline, explicit]
Definition at line 240 of file DIE.h.
Member Function Documentation
void DIEEntry::EmitValue (const AsmPrinter * AP, dwarf::Form Form) const
EmitValue - Emit debug information entry offset.
Definition at line 448 of file DIE.cpp.
References llvm::MCAsmInfo::doesDwarfUseRelocationsAcrossSections(), llvm::dwarf::DW_FORM_ref_addr, llvm::AsmPrinter::EmitInt32(), llvm::AsmPrinter::EmitLabelPlusOffset(), llvm::AsmPrinter::getDwarfDebug(), getRefAddrSize(), llvm::DwarfDebug::lookupUnit(), llvm::AsmPrinter::MAI, llvm::AsmPrinter::OutStreamer, and llvm::DwarfDebug::useSplitDwarf().
DIE& llvm::DIEEntry::getEntry () const [inline]
Definition at line 242 of file DIE.h.
Referenced by llvm::DwarfUnit::addDIEEntry().
unsigned DIEEntry::getRefAddrSize (const AsmPrinter * AP) [static]
Returns size of a ref_addr entry.
Definition at line 469 of file DIE.cpp.
References llvm::AsmPrinter::getDataLayout(), llvm::AsmPrinter::getDwarfDebug(), llvm::DwarfDebug::getDwarfVersion(), and llvm::DataLayout::getPointerSize().
Referenced by EmitValue(), and SizeOf().
void DIEEntry::print (raw_ostream & O) const
Definition at line 482 of file DIE.cpp.
References llvm::format().
unsigned llvm::DIEEntry::SizeOf (const AsmPrinter * AP, dwarf::Form Form) const [inline]
Definition at line 248 of file DIE.h.
References llvm::dwarf::DW_FORM_ref_addr, and getRefAddrSize().
The documentation for this class was generated from the following files:
DIE.h
DIE.cpp