LLVM: llvm::TargetTransformInfoImplBase Class Reference
llvm::TargetTransformInfoImplBase Class Reference
Base class for use as a mix-in that aids implementing a TargetTransformInfo-compatible class.
#include <TargetTransformInfoImpl.h>
Public Member Functions
TargetTransformInfoImplBase (const TargetTransformInfoImplBase &Arg)
TargetTransformInfoImplBase (TargetTransformInfoImplBase &&Arg)
TargetTransformInfoImplBase & operator= (const TargetTransformInfoImplBase &RHS)
TargetTransformInfoImplBase & operator= (TargetTransformInfoImplBase &&RHS)
unsigned getOperationCost (unsigned Opcode, Type *Ty, Type *OpTy)
unsigned getGEPCost (const Value *Ptr, ArrayRef< const Value * > Operands)
unsigned getCallCost (FunctionType *FTy, int NumArgs)
unsigned getIntrinsicCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< Type * > ParamTys)
bool hasBranchDivergence ()
bool isSourceOfDivergence (const Value *V)
bool isLoweredToCall (const Function *F)
void getUnrollingPreferences (Loop *, TTI::UnrollingPreferences &)
bool isLegalAddImmediate (int64_t Imm)
bool isLegalICmpImmediate (int64_t Imm)
bool isLegalAddressingMode (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace)
bool isLegalMaskedStore (Type *DataType, int Consecutive)
bool isLegalMaskedLoad (Type *DataType, int Consecutive)
int getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace)
bool isTruncateFree (Type *Ty1, Type *Ty2)
bool isProfitableToHoist (Instruction *I)
bool isTypeLegal (Type *Ty)
unsigned getJumpBufAlignment ()
unsigned getJumpBufSize ()
bool shouldBuildLookupTables ()
bool enableAggressiveInterleaving (bool LoopHasReductions)
TTI::PopcntSupportKind getPopcntSupport (unsigned IntTyWidthInBit)
bool haveFastSqrt (Type *Ty)
unsigned getFPOpCost (Type *Ty)
unsigned getIntImmCost (const APInt &Imm, Type *Ty)
unsigned getIntImmCost (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty)
unsigned getIntImmCost (Intrinsic::ID IID, unsigned Idx, const APInt &Imm, Type *Ty)
unsigned getNumberOfRegisters (bool Vector)
unsigned getRegisterBitWidth (bool Vector)
unsigned getMaxInterleaveFactor (unsigned VF)
unsigned getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::OperandValueKind Opd1Info, TTI::OperandValueKind Opd2Info, TTI::OperandValueProperties Opd1PropInfo, TTI::OperandValueProperties Opd2PropInfo)
unsigned getShuffleCost (TTI::ShuffleKind Kind, Type *Ty, int Index, Type *SubTp)
unsigned getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src)
unsigned getCFInstrCost (unsigned Opcode)
unsigned getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy)
unsigned getVectorInstrCost (unsigned Opcode, Type *Val, unsigned Index)
unsigned getMemoryOpCost (unsigned Opcode, Type *Src, unsigned Alignment, unsigned AddressSpace)
unsigned getMaskedMemoryOpCost (unsigned Opcode, Type *Src, unsigned Alignment, unsigned AddressSpace)
unsigned getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace)
unsigned getIntrinsicInstrCost (Intrinsic::ID ID, Type *RetTy, ArrayRef< Type * > Tys)
unsigned getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type * > Tys)
unsigned getNumberOfParts (Type *Tp)
unsigned getAddressComputationCost (Type *Tp, bool)
unsigned getReductionCost (unsigned, Type *, bool)
unsigned getCostOfKeepingLiveOverCall (ArrayRef< Type * > Tys)
bool getTgtMemIntrinsic (IntrinsicInst *Inst, MemIntrinsicInfo &Info)
Value * getOrCreateResultFromMemIntrinsic (IntrinsicInst *Inst, Type *ExpectedType)
Protected Types
typedef TargetTransformInfo TTI
Protected Member Functions
TargetTransformInfoImplBase (const DataLayout *DL)
Protected Attributes
const DataLayout * DL
Detailed Description
Base class for use as a mix-in that aids implementing a TargetTransformInfo-compatible class.
Definition at line 29 of file TargetTransformInfoImpl.h.
Member Typedef Documentation
typedef TargetTransformInfo llvm::TargetTransformInfoImplBase::TTI [protected]
Definition at line 31 of file TargetTransformInfoImpl.h.
Constructor & Destructor Documentation
llvm::TargetTransformInfoImplBase::TargetTransformInfoImplBase (const DataLayout * DL) [inline, explicit, protected]
Definition at line 35 of file TargetTransformInfoImpl.h.
llvm::TargetTransformInfoImplBase::TargetTransformInfoImplBase (const TargetTransformInfoImplBase & Arg) [inline]
Definition at line 40 of file TargetTransformInfoImpl.h.
llvm::TargetTransformInfoImplBase::TargetTransformInfoImplBase (TargetTransformInfoImplBase && Arg) [inline]
Definition at line 42 of file TargetTransformInfoImpl.h.
Member Function Documentation
bool llvm::TargetTransformInfoImplBase::enableAggressiveInterleaving (bool LoopHasReductions) [inline]
Reimplemented in llvm::PPCTTIImpl.
Definition at line 242 of file TargetTransformInfoImpl.h.
unsigned llvm::TargetTransformInfoImplBase::getAddressComputationCost (Type * Tp, bool) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::AArch64TTIImpl, llvm::ARMTTIImpl, and llvm::X86TTIImpl.
Definition at line 324 of file TargetTransformInfoImpl.h.
unsigned llvm::TargetTransformInfoImplBase::getArithmeticInstrCost (unsigned Opcode, Type * Ty, TTI::OperandValueKind Opd1Info, TTI::OperandValueKind Opd2Info, TTI::OperandValueProperties Opd1PropInfo, TTI::OperandValueProperties Opd2PropInfo) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::PPCTTIImpl, llvm::X86TTIImpl, and llvm::NVPTXTTIImpl.
Definition at line 270 of file TargetTransformInfoImpl.h.
unsigned llvm::TargetTransformInfoImplBase::getCallCost (FunctionType * FTy, int NumArgs) [inline]
Definition at line 120 of file TargetTransformInfoImpl.h.
References llvm::FunctionType::getNumParams(), and llvm::TargetTransformInfo::TCC_Basic.
unsigned llvm::TargetTransformInfoImplBase::getCallInstrCost (Function * F, Type * RetTy, ArrayRef< Type * > Tys) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, and llvm::BasicTTIImplBase< AMDGPUTTIImpl >.
Definition at line 318 of file TargetTransformInfoImpl.h.
unsigned llvm::TargetTransformInfoImplBase::getCastInstrCost (unsigned Opcode, Type * Dst, Type * Src) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::PPCTTIImpl, and llvm::X86TTIImpl.
Definition at line 283 of file TargetTransformInfoImpl.h.
unsigned llvm::TargetTransformInfoImplBase::getCFInstrCost (unsigned Opcode) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, and llvm::BasicTTIImplBase< AMDGPUTTIImpl >.
Definition at line 285 of file TargetTransformInfoImpl.h.
unsigned llvm::TargetTransformInfoImplBase::getCmpSelInstrCost (unsigned Opcode, Type * ValTy, Type * CondTy) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::PPCTTIImpl, and llvm::X86TTIImpl.
Definition at line 287 of file TargetTransformInfoImpl.h.
unsigned llvm::TargetTransformInfoImplBase::getCostOfKeepingLiveOverCall (ArrayRef< Type * > Tys) [inline]
Reimplemented in llvm::AArch64TTIImpl.
Definition at line 328 of file TargetTransformInfoImpl.h.
unsigned llvm::TargetTransformInfoImplBase::getFPOpCost (Type * Ty) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, and llvm::ARMTTIImpl.
Definition at line 250 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::TCC_Basic.
unsigned llvm::TargetTransformInfoImplBase::getGEPCost (const Value * Ptr, ArrayRef< const Value * > Operands) [inline]
Definition at line 110 of file TargetTransformInfoImpl.h.
References llvm::ArrayRef< T >::size(), llvm::TargetTransformInfo::TCC_Basic, and llvm::TargetTransformInfo::TCC_Free.
Referenced by llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getUserCost().
unsigned llvm::TargetTransformInfoImplBase::getInterleavedMemoryOpCost (unsigned Opcode, Type * VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, and llvm::BasicTTIImplBase< AMDGPUTTIImpl >.
Definition at line 305 of file TargetTransformInfoImpl.h.
unsigned llvm::TargetTransformInfoImplBase::getIntImmCost (const APInt & Imm, Type * Ty) [inline]
Reimplemented in llvm::X86TTIImpl, llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::PPCTTIImpl, and llvm::SystemZTTIImpl.
Definition at line 252 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::TCC_Basic.
Referenced by llvm::PPCTTIImpl::getIntImmCost().
unsigned llvm::TargetTransformInfoImplBase::getIntImmCost (unsigned Opcode, unsigned Idx, const APInt & Imm, Type * Ty) [inline]
Reimplemented in llvm::X86TTIImpl, llvm::AArch64TTIImpl, llvm::PPCTTIImpl, and llvm::SystemZTTIImpl.
Definition at line 254 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::TCC_Free.
unsigned llvm::TargetTransformInfoImplBase::getIntImmCost (Intrinsic::ID IID, unsigned Idx, const APInt & Imm, Type * Ty) [inline]
Reimplemented in llvm::X86TTIImpl, llvm::AArch64TTIImpl, llvm::PPCTTIImpl, and llvm::SystemZTTIImpl.
Definition at line 259 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::TCC_Free.
unsigned llvm::TargetTransformInfoImplBase::getIntrinsicCost (Intrinsic::ID IID, Type * RetTy, ArrayRef< Type * > ParamTys) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, and llvm::BasicTTIImplBase< AMDGPUTTIImpl >.
Definition at line 135 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::TCC_Basic, and llvm::TargetTransformInfo::TCC_Free.
unsigned llvm::TargetTransformInfoImplBase::getIntrinsicInstrCost (Intrinsic::ID ID, Type * RetTy, ArrayRef< Type * > Tys) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, and llvm::BasicTTIImplBase< AMDGPUTTIImpl >.
Definition at line 313 of file TargetTransformInfoImpl.h.
unsigned llvm::TargetTransformInfoImplBase::getJumpBufAlignment () [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, and llvm::BasicTTIImplBase< AMDGPUTTIImpl >.
Definition at line 236 of file TargetTransformInfoImpl.h.
unsigned llvm::TargetTransformInfoImplBase::getJumpBufSize () [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, and llvm::BasicTTIImplBase< AMDGPUTTIImpl >.
Definition at line 238 of file TargetTransformInfoImpl.h.
unsigned llvm::TargetTransformInfoImplBase::getMaskedMemoryOpCost (unsigned Opcode, Type * Src, unsigned Alignment, unsigned AddressSpace) [inline]
Reimplemented in llvm::X86TTIImpl.
Definition at line 300 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicInstrCost().
unsigned llvm::TargetTransformInfoImplBase::getMaxInterleaveFactor (unsigned VF) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::PPCTTIImpl, llvm::X86TTIImpl, and llvm::AMDGPUTTIImpl.
Definition at line 268 of file TargetTransformInfoImpl.h.
unsigned llvm::TargetTransformInfoImplBase::getMemoryOpCost (unsigned Opcode, Type * Src, unsigned Alignment, unsigned AddressSpace) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::PPCTTIImpl, and llvm::X86TTIImpl.
Definition at line 295 of file TargetTransformInfoImpl.h.
unsigned llvm::TargetTransformInfoImplBase::getNumberOfParts (Type * Tp) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, and llvm::BasicTTIImplBase< AMDGPUTTIImpl >.
Definition at line 322 of file TargetTransformInfoImpl.h.
unsigned llvm::TargetTransformInfoImplBase::getNumberOfRegisters (bool Vector) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::AArch64TTIImpl, llvm::PPCTTIImpl, llvm::ARMTTIImpl, llvm::X86TTIImpl, llvm::AMDGPUTTIImpl, llvm::SystemZTTIImpl, and llvm::XCoreTTIImpl.
Definition at line 264 of file TargetTransformInfoImpl.h.
unsigned llvm::TargetTransformInfoImplBase::getOperationCost (unsigned Opcode, Type * Ty, Type * OpTy) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, and llvm::BasicTTIImplBase< AMDGPUTTIImpl >.
Definition at line 54 of file TargetTransformInfoImpl.h.
References DL, llvm::DataLayout::getPointerTypeSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::DataLayout::getTypeSizeInBits(), llvm::IntToPtr, llvm::DataLayout::isLegalInteger(), llvm::Type::isPointerTy(), llvm_unreachable, llvm::TargetTransformInfo::TCC_Basic, llvm::TargetTransformInfo::TCC_Free, and llvm::Trunc.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getOperationCost(), and llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getUserCost().
Value* llvm::TargetTransformInfoImplBase::getOrCreateResultFromMemIntrinsic (IntrinsicInst * Inst, Type * ExpectedType) [inline]
Reimplemented in llvm::AArch64TTIImpl.
Definition at line 334 of file TargetTransformInfoImpl.h.
TTI::PopcntSupportKind llvm::TargetTransformInfoImplBase::getPopcntSupport (unsigned IntTyWidthInBit) [inline]
Reimplemented in llvm::AArch64TTIImpl, llvm::PPCTTIImpl, llvm::AMDGPUTTIImpl, llvm::X86TTIImpl, and llvm::SystemZTTIImpl.
Definition at line 244 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::PSK_Software.
unsigned llvm::TargetTransformInfoImplBase::getReductionCost (unsigned , Type * , bool) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, and llvm::X86TTIImpl.
Definition at line 326 of file TargetTransformInfoImpl.h.
unsigned llvm::TargetTransformInfoImplBase::getRegisterBitWidth (bool Vector) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::PPCTTIImpl, llvm::X86TTIImpl, llvm::AMDGPUTTIImpl, and llvm::SystemZTTIImpl.
Definition at line 266 of file TargetTransformInfoImpl.h.
int llvm::TargetTransformInfoImplBase::getScalingFactorCost (Type * Ty, GlobalValue * BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, and llvm::BasicTTIImplBase< AMDGPUTTIImpl >.
Definition at line 221 of file TargetTransformInfoImpl.h.
References isLegalAddressingMode().
unsigned llvm::TargetTransformInfoImplBase::getShuffleCost (TTI::ShuffleKind Kind, Type * Ty, int Index, Type * SubTp) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::ARMTTIImpl, llvm::PPCTTIImpl, and llvm::X86TTIImpl.
Definition at line 278 of file TargetTransformInfoImpl.h.
bool llvm::TargetTransformInfoImplBase::getTgtMemIntrinsic (IntrinsicInst * Inst, MemIntrinsicInfo & Info) [inline]
Reimplemented in llvm::AArch64TTIImpl.
Definition at line 330 of file TargetTransformInfoImpl.h.
void llvm::TargetTransformInfoImplBase::getUnrollingPreferences (Loop * , TTI::UnrollingPreferences &) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::AArch64TTIImpl, llvm::PPCTTIImpl, and llvm::AMDGPUTTIImpl.
Definition at line 203 of file TargetTransformInfoImpl.h.
unsigned llvm::TargetTransformInfoImplBase::getVectorInstrCost (unsigned Opcode, Type * Val, unsigned Index) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::PPCTTIImpl, and llvm::X86TTIImpl.
Definition at line 291 of file TargetTransformInfoImpl.h.
bool llvm::TargetTransformInfoImplBase::hasBranchDivergence () [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::AMDGPUTTIImpl, and llvm::NVPTXTTIImpl.
Definition at line 165 of file TargetTransformInfoImpl.h.
bool llvm::TargetTransformInfoImplBase::haveFastSqrt (Type * Ty) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, and llvm::BasicTTIImplBase< AMDGPUTTIImpl >.
Definition at line 248 of file TargetTransformInfoImpl.h.
bool llvm::TargetTransformInfoImplBase::isLegalAddImmediate (int64_t Imm) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, and llvm::BasicTTIImplBase< AMDGPUTTIImpl >.
Definition at line 205 of file TargetTransformInfoImpl.h.
bool llvm::TargetTransformInfoImplBase::isLegalAddressingMode (Type * Ty, GlobalValue * BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, and llvm::BasicTTIImplBase< AMDGPUTTIImpl >.
Definition at line 209 of file TargetTransformInfoImpl.h.
Referenced by getScalingFactorCost().
bool llvm::TargetTransformInfoImplBase::isLegalICmpImmediate (int64_t Imm) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, and llvm::BasicTTIImplBase< AMDGPUTTIImpl >.
Definition at line 207 of file TargetTransformInfoImpl.h.
bool llvm::TargetTransformInfoImplBase::isLegalMaskedLoad (Type * DataType, int Consecutive) [inline]
Reimplemented in llvm::X86TTIImpl.
Definition at line 219 of file TargetTransformInfoImpl.h.
bool llvm::TargetTransformInfoImplBase::isLegalMaskedStore (Type * DataType, int Consecutive) [inline]
Reimplemented in llvm::X86TTIImpl.
Definition at line 217 of file TargetTransformInfoImpl.h.
bool llvm::TargetTransformInfoImplBase::isLoweredToCall (const Function * F) [inline]
Definition at line 169 of file TargetTransformInfoImpl.h.
References llvm::Value::getName(), llvm::GlobalValue::hasLocalLinkage(), llvm::Value::hasName(), and llvm::Function::isIntrinsic().
bool llvm::TargetTransformInfoImplBase::isProfitableToHoist (Instruction * I) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, and llvm::BasicTTIImplBase< AMDGPUTTIImpl >.
Definition at line 232 of file TargetTransformInfoImpl.h.
bool llvm::TargetTransformInfoImplBase::isSourceOfDivergence (const Value * V) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, and llvm::NVPTXTTIImpl.
Definition at line 167 of file TargetTransformInfoImpl.h.
bool llvm::TargetTransformInfoImplBase::isTruncateFree (Type * Ty1, Type * Ty2) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, and llvm::BasicTTIImplBase< AMDGPUTTIImpl >.
Definition at line 230 of file TargetTransformInfoImpl.h.
bool llvm::TargetTransformInfoImplBase::isTypeLegal (Type * Ty) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, and llvm::BasicTTIImplBase< AMDGPUTTIImpl >.
Definition at line 234 of file TargetTransformInfoImpl.h.
TargetTransformInfoImplBase& llvm::TargetTransformInfoImplBase::operator= (const TargetTransformInfoImplBase & RHS) [inline]
Definition at line 45 of file TargetTransformInfoImpl.h.
References DL.
Referenced by llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::operator=().
TargetTransformInfoImplBase& llvm::TargetTransformInfoImplBase::operator= (TargetTransformInfoImplBase && RHS) [inline]
Definition at line 49 of file TargetTransformInfoImpl.h.
References DL.
bool llvm::TargetTransformInfoImplBase::shouldBuildLookupTables () [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, and llvm::BasicTTIImplBase< AMDGPUTTIImpl >.
Definition at line 240 of file TargetTransformInfoImpl.h.
Member Data Documentation
const DataLayout* llvm::TargetTransformInfoImplBase::DL [protected]
Definition at line 33 of file TargetTransformInfoImpl.h.
Referenced by getOperationCost(), llvm::AMDGPUTTIImpl::getUnrollingPreferences(), and operator=().
The documentation for this class was generated from the following file:
TargetTransformInfoImpl.h