LLVM: llvm::MipsInstPrinter Class Reference
llvm::MipsInstPrinter Class Reference
#include <MipsInstPrinter.h>
Public Member Functions
MipsInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printInstruction (const MCInst *MI, raw_ostream &O)
void printRegName (raw_ostream &OS, unsigned RegNo) const override
Print the assembler register name.
void printInst (const MCInst *MI, raw_ostream &O, StringRef Annot, const MCSubtargetInfo &STI) override
Print the specified MCInst to the specified raw_ostream.
bool printAliasInstr (const MCInst *MI, raw_ostream &OS)
void printCustomAliasOperand (const MCInst *MI, unsigned OpIdx, unsigned PrintMethodIdx, raw_ostream &O)
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo)
Detailed Description
Definition at line 78 of file MipsInstPrinter.h.
Constructor & Destructor Documentation
llvm::MipsInstPrinter::MipsInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) [inline]
Definition at line 80 of file MipsInstPrinter.h.
Member Function Documentation
static const char* llvm::MipsInstPrinter::getRegisterName (unsigned RegNo) [static]
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveCpLoad(), llvm::MipsTargetAsmStreamer::emitDirectiveCpsetup(), llvm::MipsTargetAsmStreamer::emitFrame(), llvm::MipsAsmPrinter::PrintAsmMemoryOperand(), llvm::MipsAsmPrinter::PrintAsmOperand(), llvm::MipsAsmPrinter::printOperand(), and printRegName().
bool llvm::MipsInstPrinter::printAliasInstr (const MCInst * MI, raw_ostream & OS)
Referenced by printInst().
void llvm::MipsInstPrinter::printCustomAliasOperand (const MCInst * MI, unsigned OpIdx, unsigned PrintMethodIdx, raw_ostream & O)
void MipsInstPrinter::printInst (const MCInst * MI, raw_ostream & OS, StringRef Annot, const MCSubtargetInfo & STI) [override, virtual]
Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Definition at line 79 of file MipsInstPrinter.cpp.
References llvm::MCInst::getOpcode(), printAliasInstr(), llvm::MCInstPrinter::printAnnotation(), and printInstruction().
void llvm::MipsInstPrinter::printInstruction (const MCInst * MI, raw_ostream & O)
Referenced by printInst().
void MipsInstPrinter::printRegName (raw_ostream & OS, unsigned RegNo) const [override, virtual]
Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 75 of file MipsInstPrinter.cpp.
References getRegisterName(), and llvm::StringRef::lower().
The documentation for this class was generated from the following files:
MipsInstPrinter.h
MipsInstPrinter.cpp