LLVM: llvm::BPFInstrInfo Class Reference
llvm::BPFInstrInfo Class Reference
#include <BPFInstrInfo.h>
Public Member Functions
BPFInstrInfo ()
const BPFRegisterInfo & getRegisterInfo () const
void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc) const override
void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned DestReg, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
bool AnalyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify) const override
unsigned RemoveBranch (MachineBasicBlock &MBB) const override
unsigned InsertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, ArrayRef< MachineOperand > Cond, DebugLoc DL) const override
Detailed Description
Definition at line 25 of file BPFInstrInfo.h.
Constructor & Destructor Documentation
BPFInstrInfo::BPFInstrInfo ()
Definition at line 31 of file BPFInstrInfo.cpp.
Member Function Documentation
bool BPFInstrInfo::AnalyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify) const [override]
Definition at line 78 of file BPFInstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::eraseFromParent(), I, and llvm::MachineBasicBlock::isLayoutSuccessor().
void BPFInstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc) const [override]
Definition at line 34 of file BPFInstrInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), contains(), llvm::getKillRegState(), and llvm_unreachable.
const BPFRegisterInfo& llvm::BPFInstrInfo::getRegisterInfo () const [inline]
Definition at line 31 of file BPFInstrInfo.h.
Referenced by llvm::BPFSubtarget::getRegisterInfo().
unsigned BPFInstrInfo::InsertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, ArrayRef< MachineOperand > Cond, DebugLoc DL) const [override]
Definition at line 133 of file BPFInstrInfo.cpp.
References llvm::MachineInstrBuilder::addMBB(), llvm::BuildMI(), llvm::ArrayRef< T >::empty(), and llvm_unreachable.
void BPFInstrInfo::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned DestReg, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const [override]
Definition at line 63 of file BPFInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::BuildMI(), llvm::DL, llvm::MachineBasicBlock::end(), and llvm_unreachable.
unsigned BPFInstrInfo::RemoveBranch (MachineBasicBlock & MBB) const [override]
Definition at line 151 of file BPFInstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), and I.
void BPFInstrInfo::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const [override]
Definition at line 45 of file BPFInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::DL, llvm::MachineBasicBlock::end(), llvm::getKillRegState(), and llvm_unreachable.
The documentation for this class was generated from the following files:
BPFInstrInfo.h
BPFInstrInfo.cpp