LLVM: llvm::ObjectMemoryBuffer Class Reference
llvm::ObjectMemoryBuffer Class Reference
SmallVector-backed MemoryBuffer instance.
#include <ObjectMemoryBuffer.h>
Public Member Functions
ObjectMemoryBuffer (SmallVectorImpl< char > &&SV)
Construct an ObjectMemoryBuffer from the given SmallVector r-value.
ObjectMemoryBuffer (SmallVectorImpl< char > &&SV, StringRef Name)
Construct a named ObjectMemoryBuffer from the given SmallVector r-value and StringRef.
const char * getBufferIdentifier () const override
Return an identifier for this buffer, typically the filename it was read from.
BufferKind getBufferKind () const override
Return information on the memory mechanism used to support the MemoryBuffer.
template<unsigned N>
ObjectMemoryBuffer (SmallVector< char, N > SV)
template<unsigned N>
ObjectMemoryBuffer (SmallVector< char, N > SV, StringRef Name)
const char * getBufferIdentifier () const override
Return an identifier for this buffer, typically the filename it was read from.
BufferKind getBufferKind () const override
Return information on the memory mechanism used to support the MemoryBuffer.
Detailed Description
SmallVector-backed MemoryBuffer instance.
This class enables efficient construction of MemoryBuffers from SmallVector instances. This is useful for MCJIT and Orc, where object files are streamed into SmallVectors, then inspected using ObjectFile (which takes a MemoryBuffer).
Definition at line 30 of file ObjectMemoryBuffer.h.
Constructor & Destructor Documentation
llvm::ObjectMemoryBuffer::ObjectMemoryBuffer (SmallVectorImpl< char > && SV) [inline]
Construct an ObjectMemoryBuffer from the given SmallVector r-value.
FIXME: It'd be nice for this to be a non-templated constructor taking a SmallVectorImpl here instead of a templated one taking a SmallVector<N>, but SmallVector's move-construction/assignment currently only take SmallVectors. If/when that is fixed we can simplify this constructor and the following one.
Definition at line 40 of file ObjectMemoryBuffer.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), and llvm::MemoryBuffer::init().
llvm::ObjectMemoryBuffer::ObjectMemoryBuffer (SmallVectorImpl< char > && SV, StringRef Name) [inline]
Construct a named ObjectMemoryBuffer from the given SmallVector r-value and StringRef.
Definition at line 47 of file ObjectMemoryBuffer.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), and llvm::MemoryBuffer::init().
template<unsigned N> llvm::ObjectMemoryBuffer::ObjectMemoryBuffer (SmallVector< char, N > SV) [inline]
Definition at line 27 of file ObjectBuffer.h.
References llvm::SmallVectorTemplateCommon< T >::begin(), llvm::SmallVectorTemplateCommon< T >::end(), and llvm::MemoryBuffer::init().
template<unsigned N> llvm::ObjectMemoryBuffer::ObjectMemoryBuffer (SmallVector< char, N > SV, StringRef Name) [inline]
Definition at line 33 of file ObjectBuffer.h.
References llvm::SmallVectorTemplateCommon< T >::begin(), llvm::SmallVectorTemplateCommon< T >::end(), and llvm::MemoryBuffer::init().
Member Function Documentation
const char* llvm::ObjectMemoryBuffer::getBufferIdentifier () const [inline, override, virtual]
Return an identifier for this buffer, typically the filename it was read from.
Reimplemented from llvm::MemoryBuffer.
Definition at line 37 of file ObjectBuffer.h.
const char* llvm::ObjectMemoryBuffer::getBufferIdentifier () const [inline, override, virtual]
Return an identifier for this buffer, typically the filename it was read from.
Reimplemented from llvm::MemoryBuffer.
Definition at line 52 of file ObjectMemoryBuffer.h.
BufferKind llvm::ObjectMemoryBuffer::getBufferKind () const [inline, override, virtual]
Return information on the memory mechanism used to support the MemoryBuffer.
Implements llvm::MemoryBuffer.
Definition at line 39 of file ObjectBuffer.h.
References llvm::MemoryBuffer::MemoryBuffer_Malloc.
BufferKind llvm::ObjectMemoryBuffer::getBufferKind () const [inline, override, virtual]
Return information on the memory mechanism used to support the MemoryBuffer.
Implements llvm::MemoryBuffer.
Definition at line 54 of file ObjectMemoryBuffer.h.
References llvm::MemoryBuffer::MemoryBuffer_Malloc.
The documentation for this class was generated from the following files:
ObjectMemoryBuffer.h
ObjectBuffer.h