LLVM: llvm::DIASession Class Reference
llvm::DIASession Class Reference
#include <DIASession.h>
Public Member Functions
DIASession (CComPtr< IDiaSession > DiaSession)
uint64_t getLoadAddress () const override
void setLoadAddress (uint64_t Address) override
std::unique_ptr< PDBSymbolExe > getGlobalScope () const override
std::unique_ptr< PDBSymbol > getSymbolById (uint32_t SymbolId) const override
std::unique_ptr< PDBSymbol > findSymbolByAddress (uint64_t Address, PDB_SymType Type) const override
std::unique_ptr
< IPDBEnumLineNumbers > findLineNumbersByAddress (uint64_t Address, uint32_t Length) const override
std::unique_ptr
< IPDBEnumSourceFiles > getAllSourceFiles () const override
std::unique_ptr
< IPDBEnumSourceFiles > getSourceFilesForCompiland (const PDBSymbolCompiland &Compiland) const override
std::unique_ptr< IPDBSourceFile > getSourceFileById (uint32_t FileId) const override
std::unique_ptr
< IPDBEnumDataStreams > getDebugStreams () const override
Static Public Member Functions
static PDB_ErrorCode createFromPdb (StringRef Path, std::unique_ptr< IPDBSession > &Session)
static PDB_ErrorCode createFromExe (StringRef Path, std::unique_ptr< IPDBSession > &Session)
Detailed Description
Definition at line 18 of file DIASession.h.
Constructor & Destructor Documentation
DIASession::DIASession (CComPtr< IDiaSession > DiaSession) [explicit]
Definition at line 25 of file DIASession.cpp.
Referenced by createFromExe(), and createFromPdb().
Member Function Documentation
PDB_ErrorCode DIASession::createFromExe (StringRef Path, std::unique_ptr< IPDBSession > & Session) [static]
Definition at line 68 of file DIASession.cpp.
References llvm::AlreadyLoaded, llvm::convertUTF8ToUTF16String(), llvm::SmallVectorTemplateCommon< T >::data(), llvm::DebugInfoMismatch, DIASession(), llvm::InvalidFileFormat, llvm::InvalidParameter, llvm::InvalidPath, llvm::NoMemory, llvm::NoPdbImpl, llvm::Success, and llvm::UnknownError.
Referenced by llvm::loadDataForEXE().
PDB_ErrorCode DIASession::createFromPdb (StringRef Path, std::unique_ptr< IPDBSession > & Session) [static]
Definition at line 27 of file DIASession.cpp.
References llvm::AlreadyLoaded, llvm::convertUTF8ToUTF16String(), llvm::SmallVectorTemplateCommon< T >::data(), DIASession(), llvm::InvalidFileFormat, llvm::InvalidParameter, llvm::InvalidPath, llvm::NoMemory, llvm::NoPdbImpl, llvm::Success, and llvm::UnknownError.
Referenced by llvm::loadDataForPDB().
std::unique_ptr< IPDBEnumLineNumbers > DIASession::findLineNumbersByAddress (uint64_t Address, uint32_t Length) const [override, virtual]
Implements llvm::IPDBSession.
Definition at line 161 of file DIASession.cpp.
References llvm::LineNumbers.
std::unique_ptr< PDBSymbol > DIASession::findSymbolByAddress (uint64_t Address, PDB_SymType Type) const [override, virtual]
Implements llvm::IPDBSession.
Definition at line 144 of file DIASession.cpp.
References llvm::PDBSymbol::create(), and llvm::ARMBuildAttrs::Symbol.
std::unique_ptr< IPDBEnumSourceFiles > DIASession::getAllSourceFiles () const [override, virtual]
Implements llvm::IPDBSession.
Definition at line 169 of file DIASession.cpp.
std::unique_ptr< IPDBEnumDataStreams > DIASession::getDebugStreams () const [override, virtual]
Implements llvm::IPDBSession.
Definition at line 199 of file DIASession.cpp.
std::unique_ptr< PDBSymbolExe > DIASession::getGlobalScope () const [override, virtual]
Implements llvm::IPDBSession.
Definition at line 122 of file DIASession.cpp.
References llvm::PDBSymbol::create().
uint64_t DIASession::getLoadAddress () const [override, virtual]
Implements llvm::IPDBSession.
Definition at line 112 of file DIASession.cpp.
References llvm::success.
std::unique_ptr< IPDBSourceFile > DIASession::getSourceFileById (uint32_t FileId) const [override, virtual]
Implements llvm::IPDBSession.
Definition at line 191 of file DIASession.cpp.
std::unique_ptr< IPDBEnumSourceFiles > DIASession::getSourceFilesForCompiland (const PDBSymbolCompiland & Compiland) const [override, virtual]
Implements llvm::IPDBSession.
Definition at line 177 of file DIASession.cpp.
References llvm::DIARawSymbol::getDiaSymbol(), and llvm::PDBSymbol::getRawSymbol().
std::unique_ptr< PDBSymbol > DIASession::getSymbolById (uint32_t SymbolId) const [override, virtual]
Implements llvm::IPDBSession.
Definition at line 134 of file DIASession.cpp.
References llvm::PDBSymbol::create().
void DIASession::setLoadAddress (uint64_t Address) [override, virtual]
Implements llvm::IPDBSession.
Definition at line 118 of file DIASession.cpp.
The documentation for this class was generated from the following files:
DIASession.h
DIASession.cpp