LLVM: llvm::DINode Class Reference
llvm::DINode Class Reference
Tagged DWARF-like metadata node.
#include <DebugInfoMetadata.h>
Public Types
enum DIFlags
Debug info flags.
Public Member Functions
unsigned getTag () const
DINodeRef getRef () const
Static Public Member Functions
static unsigned getFlag (StringRef Flag)
static const char * getFlagString (unsigned Flag)
static unsigned splitFlags (unsigned Flags, SmallVectorImpl< unsigned > &SplitFlags)
Split up a flags bitfield.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
DINode (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=None)
~DINode ()
template<class Ty >
Ty * getOperandAs (unsigned I) const
StringRef getStringOperand (unsigned I) const
Static Protected Member Functions
static MDString * getCanonicalMDString (LLVMContext &Context, StringRef S)
Friends
class LLVMContextImpl
class MDNode
Detailed Description
Tagged DWARF-like metadata node.
A metadata node with a DWARF tag (i.e., a constant named DW_TAG_*, defined in llvm/Support/Dwarf.h). Called DINode because it's potentially used for non-DWARF output.
Definition at line 144 of file DebugInfoMetadata.h.
Member Enumeration Documentation
enum llvm::DINode::DIFlags
Debug info flags.
The three accessibility flags are mutually exclusive and rolled together in the first two bits.
Definition at line 180 of file DebugInfoMetadata.h.
Constructor & Destructor Documentation
llvm::DINode::DINode (LLVMContext & C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2 = None) [inline, protected]
Definition at line 149 of file DebugInfoMetadata.h.
References llvm::Metadata::SubclassData16.
llvm::DINode::~DINode () [protected]
Member Function Documentation
static bool llvm::DINode::classof (const Metadata * MD) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::MDNode.
Reimplemented in llvm::DIImportedEntity, llvm::DIObjCProperty, llvm::DILocalVariable, llvm::DIGlobalVariable, llvm::DIVariable, llvm::DITemplateValueParameter, llvm::DITemplateTypeParameter, llvm::DITemplateParameter, llvm::DINamespace, llvm::DILexicalBlockFile, llvm::DILexicalBlock, llvm::DILexicalBlockBase, llvm::DISubprogram, llvm::DILocalScope, llvm::DICompileUnit, llvm::DISubroutineType, llvm::DICompositeTypeBase, llvm::DIDerivedTypeBase, llvm::DIBasicType, llvm::DIType, llvm::DIFile, llvm::DIScope, llvm::DIEnumerator, llvm::DISubrange, and llvm::GenericDINode.
Definition at line 198 of file DebugInfoMetadata.h.
References llvm::Metadata::DIBasicTypeKind, llvm::Metadata::DICompileUnitKind, llvm::Metadata::DICompositeTypeKind, llvm::Metadata::DIDerivedTypeKind, llvm::Metadata::DIEnumeratorKind, llvm::Metadata::DIFileKind, llvm::Metadata::DIGlobalVariableKind, llvm::Metadata::DIImportedEntityKind, llvm::Metadata::DILexicalBlockFileKind, llvm::Metadata::DILexicalBlockKind, llvm::Metadata::DILocalVariableKind, llvm::Metadata::DINamespaceKind, llvm::Metadata::DIObjCPropertyKind, llvm::Metadata::DISubprogramKind, llvm::Metadata::DISubrangeKind, llvm::Metadata::DISubroutineTypeKind, llvm::Metadata::DITemplateTypeParameterKind, llvm::Metadata::DITemplateValueParameterKind, llvm::Metadata::GenericDINodeKind, and llvm::Metadata::getMetadataID().
static MDString* llvm::DINode::getCanonicalMDString (LLVMContext & Context, StringRef S) [inline, static, protected]
Definition at line 167 of file DebugInfoMetadata.h.
References llvm::StringRef::empty(), and llvm::MDNode::get().
unsigned DINode::getFlag (StringRef Flag) [static]
Definition at line 86 of file DebugInfoMetadata.cpp.
References HANDLE_DI_FLAG.
const char * DINode::getFlagString (unsigned Flag) [static]
Definition at line 93 of file DebugInfoMetadata.cpp.
template<class Ty > Ty* llvm::DINode::getOperandAs (unsigned I) const [inline, protected]
Definition at line 157 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
DINodeRef llvm::DINode::getRef () const [inline]
Reimplemented in llvm::DIType, and llvm::DIScope.
Definition at line 196 of file DebugInfoMetadata.h.
References llvm::MDNode::get().
StringRef llvm::DINode::getStringOperand (unsigned I) const [inline, protected]
Definition at line 161 of file DebugInfoMetadata.h.
Referenced by llvm::DIFile::getDirectory(), llvm::DIGlobalVariable::getDisplayName(), llvm::DIFile::getFilename(), llvm::DICompileUnit::getFlags(), llvm::DIObjCProperty::getGetterName(), llvm::GenericDINode::getHeader(), llvm::DICompositeTypeBase::getIdentifier(), llvm::DIGlobalVariable::getLinkageName(), llvm::DIEnumerator::getName(), llvm::DIType::getName(), llvm::DINamespace::getName(), llvm::DITemplateParameter::getName(), llvm::DIVariable::getName(), llvm::DIObjCProperty::getName(), llvm::DIImportedEntity::getName(), llvm::DICompileUnit::getProducer(), llvm::DIObjCProperty::getSetterName(), and llvm::DICompileUnit::getSplitDebugFilename().
unsigned llvm::DINode::getTag () const [inline]
Reimplemented in llvm::GenericDINode.
Definition at line 174 of file DebugInfoMetadata.h.
References llvm::Metadata::SubclassData16.
Referenced by llvm::DwarfUnit::addBlockByrefAddress(), llvm::DwarfUnit::applySubprogramAttributes(), llvm::DwarfDebug::beginFunction(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), llvm::DIBuilder::createFunction(), llvm::DIBuilder::createMethod(), llvm::DwarfUnit::createTypeDIE(), getBaseTypeSize(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), llvm::DwarfUnit::getOrCreateStaticMemberDIE(), llvm::DbgVariable::getTag(), llvm::DbgVariable::getType(), llvm::MDNodeKeyImpl< DIBasicType >::isKeyOf(), llvm::MDNodeKeyImpl< DIDerivedType >::isKeyOf(), llvm::MDNodeKeyImpl< DICompositeType >::isKeyOf(), llvm::MDNodeKeyImpl< DITemplateValueParameter >::isKeyOf(), llvm::MDNodeKeyImpl< DILocalVariable >::isKeyOf(), llvm::MDNodeKeyImpl< DIImportedEntity >::isKeyOf(), isUnsignedDIType(), WriteDIBasicType(), WriteDICompositeType(), WriteDIDerivedType(), WriteDIImportedEntity(), WriteDILocalVariable(), and WriteDITemplateValueParameter().
unsigned DINode::splitFlags (unsigned Flags, SmallVectorImpl< unsigned > & SplitFlags) [static]
Split up a flags bitfield.
Split Flags into SplitFlags, a vector of its components. Returns any remaining (unrecognized) bits.
Definition at line 104 of file DebugInfoMetadata.cpp.
References llvm::ARM_PROC::A, and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Friends And Related Function Documentation
friend class LLVMContextImpl [friend]
Reimplemented from llvm::MDNode.
Reimplemented in llvm::DIImportedEntity, llvm::DIObjCProperty, llvm::DILocalVariable, llvm::DIGlobalVariable, llvm::DITemplateValueParameter, llvm::DITemplateTypeParameter, llvm::DINamespace, llvm::DILexicalBlockFile, llvm::DILexicalBlock, llvm::DISubprogram, llvm::DICompileUnit, llvm::DISubroutineType, llvm::DICompositeType, llvm::DIDerivedType, llvm::DIBasicType, llvm::DIFile, llvm::DIEnumerator, llvm::DISubrange, and llvm::GenericDINode.
Definition at line 145 of file DebugInfoMetadata.h.
friend class MDNode [friend]
Reimplemented in llvm::DIImportedEntity, llvm::DIObjCProperty, llvm::DILocalVariable, llvm::DIGlobalVariable, llvm::DITemplateValueParameter, llvm::DITemplateTypeParameter, llvm::DINamespace, llvm::DILexicalBlockFile, llvm::DILexicalBlock, llvm::DISubprogram, llvm::DICompileUnit, llvm::DISubroutineType, llvm::DICompositeType, llvm::DIDerivedType, llvm::DIBasicType, llvm::DIFile, llvm::DIEnumerator, llvm::DISubrange, and llvm::GenericDINode.
Definition at line 146 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
DebugInfoMetadata.h
DebugInfoMetadata.cpp