LLVM: llvm::VarBitInit Class Reference
llvm::VarBitInit Class Reference
VarBitInit - Opcode{0} - Represent access to one bit of a variable or field.
#include <Record.h>
Public Member Functions
Init * convertInitializerTo (RecTy *Ty) const override
convertInitializerTo - This virtual function converts to the appropriate Init based on the passed in type.
Init * getBitVar () const override
getBitVar - This method is used to retrieve the initializer for bit reference.
unsigned getBitNum () const override
getBitNum - This method is used to retrieve the bit number of a bit reference.
std::string getAsString () const override
getAsString - Convert this value to a string form.
Init * resolveReferences (Record &R, const RecordVal *RV) const override
resolveReferences - This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
Init * getBit (unsigned B) const override
getBit - This method is used to return the initializer for the specified bit.
Static Public Member Functions
static bool classof (const Init *I)
static VarBitInit * get (TypedInit *T, unsigned B)
Detailed Description
VarBitInit - Opcode{0} - Represent access to one bit of a variable or field.
Definition at line 881 of file Record.h.
Member Function Documentation
static bool llvm::VarBitInit::classof (const Init * I) [inline, static]
Definition at line 897 of file Record.h.
References llvm::Init::getKind(), and llvm::Init::IK_VarBitInit.
Init * VarBitInit::convertInitializerTo (RecTy * Ty) const [override, virtual]
convertInitializerTo - This virtual function converts to the appropriate Init based on the passed in type.
Implements llvm::Init.
Definition at line 1298 of file Record.cpp.
VarBitInit * VarBitInit::get (TypedInit * T, unsigned B) [static]
Definition at line 1287 of file Record.cpp.
References I.
Referenced by llvm::TypedInit::convertInitializerBitRange(), llvm::TypedInit::convertInitializerTo(), and llvm::OpInit::getBit().
std::string VarBitInit::getAsString () const [override, virtual]
getAsString - Convert this value to a string form.
Implements llvm::Init.
Definition at line 1305 of file Record.cpp.
References llvm::Init::getAsString(), and llvm::utostr().
Init* llvm::VarBitInit::getBit (unsigned Bit) const [inline, override, virtual]
getBit - This method is used to return the initializer for the specified bit.
Implements llvm::Init.
Definition at line 910 of file Record.h.
unsigned llvm::VarBitInit::getBitNum () const [inline, override, virtual]
getBitNum - This method is used to retrieve the bit number of a bit reference.
For non-VarBitInit, it simply returns 0.
Reimplemented from llvm::Init.
Definition at line 905 of file Record.h.
Referenced by resolveReferences().
Init* llvm::VarBitInit::getBitVar () const [inline, override, virtual]
getBitVar - This method is used to retrieve the initializer for bit reference.
For non-VarBitInit, it simply returns itself.
Reimplemented from llvm::Init.
Definition at line 904 of file Record.h.
Init * VarBitInit::resolveReferences (Record & R, const RecordVal * RV) const [override, virtual]
resolveReferences - This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 1309 of file Record.cpp.
References llvm::Init::getBit(), getBitNum(), I, and llvm::Init::resolveReferences().
The documentation for this class was generated from the following files:
Record.h
Record.cpp