LLVM: llvm::DILocalVariable Class Reference
llvm::DILocalVariable Class Reference
Local variable.
#include <DebugInfoMetadata.h>
Public Member Functions
DEFINE_MDNODE_GET (DILocalVariable,(unsigned Tag, DILocalScope *Scope, StringRef Name, DIFile *File, unsigned Line, DITypeRef Type, unsigned Arg, unsigned Flags),(Tag, Scope, Name, File, Line, Type, Arg, Flags)) DEFINE_MDNODE_GET(DILocalVariable
unsigned Metadata MDString
Metadata unsigned Metadata
unsigned unsigned Flags
TempDILocalVariable clone () const
Create a (temporary) clone of this.
DILocalScope * getScope () const
Get the local scope for this variable.
unsigned getArg () const
unsigned getFlags () const
bool isArtificial () const
bool isObjectPointer () const
bool isValidLocationForIntrinsic (const DILocation *DL) const
Check that a location is valid for this variable.
Static Public Member Functions
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
Public Attributes
unsigned Tag
unsigned Metadata * Scope
unsigned Metadata MDString * Name
unsigned Metadata MDString
Metadata * File
unsigned Metadata MDString
Metadata unsigned Line
unsigned Metadata MDString
Metadata unsigned Metadata * Type
unsigned Metadata MDString
Metadata unsigned Metadata
unsigned Arg
unsigned Metadata MDString
Metadata unsigned Metadata
unsigned unsigned Flags
unsigned Metadata MDString
Metadata unsigned Metadata
unsigned unsigned Tag
unsigned Metadata MDString
Metadata unsigned Metadata
unsigned unsigned Scope
unsigned Metadata MDString
Metadata unsigned Metadata
unsigned unsigned Name
unsigned Metadata MDString
Metadata unsigned Metadata
unsigned unsigned File
unsigned Metadata MDString
Metadata unsigned Metadata
unsigned unsigned Line
unsigned Metadata MDString
Metadata unsigned Metadata
unsigned unsigned Type
unsigned Metadata MDString
Metadata unsigned Metadata
unsigned unsigned Arg
Friends
class LLVMContextImpl
class MDNode
Detailed Description
Local variable.
TODO: Split between arguments and otherwise. TODO: Use DW_TAG_variable instead of fake tags. TODO: Split up flags.
Definition at line 1858 of file DebugInfoMetadata.h.
Member Function Documentation
static bool llvm::DILocalVariable::classof (const Metadata * MD) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::DIVariable.
Definition at line 1926 of file DebugInfoMetadata.h.
References llvm::Metadata::DILocalVariableKind, and llvm::Metadata::getMetadataID().
unsigned Metadata MDString Metadata unsigned Metadata unsigned unsigned Flags TempDILocalVariable llvm::DILocalVariable::clone () const [inline]
Create a (temporary) clone of this.
Reimplemented from llvm::MDNode.
Definition at line 1902 of file DebugInfoMetadata.h.
llvm::DILocalVariable::DEFINE_MDNODE_GET (DILocalVariable , (unsigned Tag, DILocalScope *Scope, StringRef Name,DIFile *File, unsigned Line, DITypeRef Type, unsigned Arg,unsigned Flags) , (Tag, Scope, Name, File, Line, Type, Arg, Flags))
unsigned llvm::DILocalVariable::getArg () const [inline]
Definition at line 1911 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfFile::addScopeVariable(), llvm::MDNodeKeyImpl< DILocalVariable >::isKeyOf(), and WriteDILocalVariable().
unsigned llvm::DILocalVariable::getFlags () const [inline]
Definition at line 1912 of file DebugInfoMetadata.h.
Referenced by isArtificial(), llvm::MDNodeKeyImpl< DILocalVariable >::isKeyOf(), isObjectPointer(), and WriteDILocalVariable().
DILocalScope* llvm::DILocalVariable::getScope () const [inline]
Get the local scope for this variable.
Variables must be defined in a local scope.
Reimplemented from llvm::DIVariable.
Definition at line 1907 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfUnit::addSourceLine(), llvm::DwarfDebug::beginFunction(), emitDebugValueComment(), llvm::DIBuilder::insertDbgValueIntrinsic(), llvm::DIBuilder::insertDeclare(), isValidLocationForIntrinsic(), and WriteDILocalVariable().
bool llvm::DILocalVariable::isArtificial () const [inline]
Definition at line 1914 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::DbgVariable::isArtificial().
bool llvm::DILocalVariable::isObjectPointer () const [inline]
Definition at line 1915 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::DbgVariable::isObjectPointer().
bool llvm::DILocalVariable::isValidLocationForIntrinsic (const DILocation * DL) const [inline]
Check that a location is valid for this variable.
Check that DL exists, is in the same subprogram, and has the same inlined-at location as this. (Otherwise, it's not a valid attachemnt to a DbgInfoIntrinsic.)
Definition at line 1922 of file DebugInfoMetadata.h.
References getScope(), and llvm::DILocalScope::getSubprogram().
Referenced by llvm::SelectionDAGBuilder::resolveDanglingDebugInfo(), and llvm::FastISel::selectIntrinsicCall().
Friends And Related Function Documentation
friend class LLVMContextImpl [friend]
Reimplemented from llvm::DINode.
Definition at line 1859 of file DebugInfoMetadata.h.
friend class MDNode [friend]
Reimplemented from llvm::DINode.
Definition at line 1860 of file DebugInfoMetadata.h.
Member Data Documentation
unsigned Metadata MDString Metadata unsigned Metadata unsigned llvm::DILocalVariable::Arg
Definition at line 1897 of file DebugInfoMetadata.h.
unsigned Metadata MDString Metadata unsigned Metadata unsigned unsigned llvm::DILocalVariable::Arg
Definition at line 1897 of file DebugInfoMetadata.h.
unsigned Metadata MDString Metadata* llvm::DILocalVariable::File
Definition at line 1897 of file DebugInfoMetadata.h.
unsigned Metadata MDString Metadata unsigned Metadata unsigned unsigned llvm::DILocalVariable::File
Definition at line 1897 of file DebugInfoMetadata.h.
unsigned Metadata MDString Metadata unsigned Metadata unsigned unsigned llvm::DILocalVariable::Flags
Definition at line 1897 of file DebugInfoMetadata.h.
unsigned Metadata MDString Metadata unsigned llvm::DILocalVariable::Line
Reimplemented from llvm::DIVariable.
Definition at line 1897 of file DebugInfoMetadata.h.
unsigned Metadata MDString Metadata unsigned Metadata unsigned unsigned llvm::DILocalVariable::Line
Reimplemented from llvm::DIVariable.
Definition at line 1897 of file DebugInfoMetadata.h.
unsigned Metadata MDString* llvm::DILocalVariable::Name
Definition at line 1897 of file DebugInfoMetadata.h.
unsigned Metadata MDString Metadata unsigned Metadata unsigned unsigned llvm::DILocalVariable::Name
Definition at line 1897 of file DebugInfoMetadata.h.
unsigned Metadata* llvm::DILocalVariable::Scope
Definition at line 1897 of file DebugInfoMetadata.h.
unsigned Metadata MDString Metadata unsigned Metadata unsigned unsigned llvm::DILocalVariable::Scope
Definition at line 1897 of file DebugInfoMetadata.h.
unsigned llvm::DILocalVariable::Tag
Definition at line 1897 of file DebugInfoMetadata.h.
unsigned Metadata MDString Metadata unsigned Metadata unsigned unsigned llvm::DILocalVariable::Tag
Definition at line 1897 of file DebugInfoMetadata.h.
unsigned Metadata MDString Metadata unsigned Metadata* llvm::DILocalVariable::Type
Definition at line 1897 of file DebugInfoMetadata.h.
unsigned Metadata MDString Metadata unsigned Metadata unsigned unsigned llvm::DILocalVariable::Type
Definition at line 1897 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
DebugInfoMetadata.h
DebugInfoMetadata.cpp