LLVM: llvm::TargetRegisterClass Class Reference
llvm::TargetRegisterClass Class Reference
#include <TargetRegisterInfo.h>
Public Types
typedef const MCPhysReg * iterator
typedef const MCPhysReg * const_iterator
typedef const
MVT::SimpleValueType * vt_iterator
typedef const
TargetRegisterClass *const * sc_iterator
Public Member Functions
unsigned getID () const
getID() - Return the register class ID number.
iterator begin () const
begin/end - Return all of the registers in this class.
iterator end () const
unsigned getNumRegs () const
getNumRegs - Return the number of registers in this class.
unsigned getRegister (unsigned i) const
getRegister - Return the specified register in the class.
bool contains (unsigned Reg) const
contains - Return true if the specified register is included in this register class.
bool contains (unsigned Reg1, unsigned Reg2) const
contains - Return true if both registers are in this class.
unsigned getSize () const
getSize - Return the size of the register in bytes, which is also the size of a stack slot allocated to hold a spilled copy of this register.
unsigned getAlignment () const
getAlignment - Return the minimum required alignment for a register of this class.
int getCopyCost () const
getCopyCost - Return the cost of copying a value between two registers in this class.
bool isAllocatable () const
isAllocatable - Return true if this register class may be used to create virtual registers.
bool hasType (MVT vt) const
hasType - return true if this TargetRegisterClass has the ValueType vt.
vt_iterator vt_begin () const
vt_begin / vt_end - Loop over all of the value types that can be represented by values in this register class.
vt_iterator vt_end () const
bool hasSubClass (const TargetRegisterClass *RC) const
hasSubClass - return true if the specified TargetRegisterClass is a proper sub-class of this TargetRegisterClass.
bool hasSubClassEq (const TargetRegisterClass *RC) const
hasSubClassEq - Returns true if RC is a sub-class of or equal to this class.
bool hasSuperClass (const TargetRegisterClass *RC) const
hasSuperClass - return true if the specified TargetRegisterClass is a proper super-class of this TargetRegisterClass.
bool hasSuperClassEq (const TargetRegisterClass *RC) const
hasSuperClassEq - Returns true if RC is a super-class of or equal to this class.
const uint32_t * getSubClassMask () const
getSubClassMask - Returns a bit vector of subclasses, including this one.
const uint16_t * getSuperRegIndices () const
getSuperRegIndices - Returns a 0-terminated list of sub-register indices that project some super-register class into this register class.
sc_iterator getSuperClasses () const
getSuperClasses - Returns a NULL terminated list of super-classes.
bool isASubClass () const
isASubClass - return true if this TargetRegisterClass is a subset class of at least one other TargetRegisterClass.
ArrayRef< MCPhysReg > getRawAllocationOrder (const MachineFunction &MF) const
getRawAllocationOrder - Returns the preferred order for allocating registers from this register class in MF.
unsigned getLaneMask () const
Returns the combination of all lane masks of register in this class.
Public Attributes
const MCRegisterClass * MC
const vt_iterator VTs
const uint32_t * SubClassMask
const uint16_t * SuperRegIndices
const unsigned LaneMask
const uint8_t AllocationPriority
Classes with a higher priority value are assigned first by register allocators using a greedy heuristic.
const bool HasDisjunctSubRegs
Whether the class supports two (or more) disjunct subregister indices.
const sc_iterator SuperClasses
ArrayRef< MCPhysReg >(* OrderFunc)(const MachineFunction &)
Detailed Description
Definition at line 36 of file TargetRegisterInfo.h.
Member Typedef Documentation
typedef const MCPhysReg* llvm::TargetRegisterClass::const_iterator
Definition at line 39 of file TargetRegisterInfo.h.
typedef const MCPhysReg* llvm::TargetRegisterClass::iterator
Definition at line 38 of file TargetRegisterInfo.h.
typedef const TargetRegisterClass* const* llvm::TargetRegisterClass::sc_iterator
Definition at line 41 of file TargetRegisterInfo.h.
typedef const MVT::SimpleValueType* llvm::TargetRegisterClass::vt_iterator
Definition at line 40 of file TargetRegisterInfo.h.
Member Function Documentation
iterator llvm::TargetRegisterClass::begin () const [inline]
begin/end - Return all of the registers in this class.
Definition at line 63 of file TargetRegisterInfo.h.
References llvm::MCRegisterClass::begin(), and MC.
Referenced by llvm::PPCInstrInfo::DefinesPredicate(), llvm::RegScavenger::FindUnusedReg(), llvm::SIRegisterInfo::findUnusedRegister(), getRawAllocationOrder(), llvm::TargetLowering::getRegForInlineAsmConstraint(), GetRegistersForValue(), llvm::RegScavenger::getRegsAvailable(), and llvm::ARMBaseRegisterInfo::getReservedRegs().
bool llvm::TargetRegisterClass::contains (unsigned Reg) const [inline]
contains - Return true if the specified register is included in this register class.
This does not include virtual registers.
Definition at line 78 of file TargetRegisterInfo.h.
References llvm::MCRegisterClass::contains(), and MC.
Referenced by llvm::MachineFunction::addLiveIn(), canFoldCopy(), llvm::SystemZInstrInfo::convertToThreeAddress(), copyHint(), llvm::PPCInstrInfo::DefinesPredicate(), llvm::AMDGPUInstrInfo::getIndirectIndexBegin(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::PPCInstrInfo::insertSelect(), llvm::CoalescerPair::setRegisters(), UpdateOperandRegClass(), and llvm::SIInstrInfo::verifyInstruction().
bool llvm::TargetRegisterClass::contains (unsigned Reg1, unsigned Reg2) const [inline]
contains - Return true if both registers are in this class.
Definition at line 83 of file TargetRegisterInfo.h.
References llvm::MCRegisterClass::contains(), and MC.
iterator llvm::TargetRegisterClass::end () const [inline]
Definition at line 64 of file TargetRegisterInfo.h.
References llvm::MCRegisterClass::end(), and MC.
Referenced by llvm::PPCInstrInfo::DefinesPredicate(), llvm::RegScavenger::FindUnusedReg(), llvm::SIRegisterInfo::findUnusedRegister(), llvm::TargetLowering::getRegForInlineAsmConstraint(), GetRegistersForValue(), llvm::RegScavenger::getRegsAvailable(), and llvm::ARMBaseRegisterInfo::getReservedRegs().
unsigned llvm::TargetRegisterClass::getAlignment () const [inline]
getAlignment - Return the minimum required alignment for a register of this class.
Definition at line 93 of file TargetRegisterInfo.h.
References llvm::MCRegisterClass::getAlignment(), and MC.
Referenced by llvm::PPCFrameLowering::addScavengingSpillSlot(), llvm::HexagonFrameLowering::assignCalleeSavedSpillSlots(), llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), llvm::MipsFunctionInfo::createEhDataRegsFI(), llvm::XCoreFunctionInfo::createEHSpillSlot(), llvm::XCoreFunctionInfo::createFPSpillSlot(), llvm::XCoreFunctionInfo::createLRSpillSlot(), llvm::MipsFunctionInfo::getMoveF64ViaSpillFI(), llvm::MipsSEFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::HexagonFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), and llvm::XCoreFrameLowering::processFunctionBeforeFrameFinalized().
int llvm::TargetRegisterClass::getCopyCost () const [inline]
getCopyCost - Return the cost of copying a value between two registers in this class.
A negative number means the register class is very expensive to copy e.g. status flag register classes.
Definition at line 98 of file TargetRegisterInfo.h.
References llvm::MCRegisterClass::getCopyCost(), and MC.
Referenced by CheckForPhysRegDependency().
unsigned llvm::TargetRegisterClass::getID () const [inline]
getID() - Return the register class ID number.
Definition at line 59 of file TargetRegisterInfo.h.
References llvm::MCRegisterClass::getID(), and MC.
Referenced by llvm::RegsForValue::AddInlineAsmOperands(), GetCostForDef(), llvm::ARMBaseRegisterInfo::getLargestLegalSuperClass(), llvm::MipsRegisterInfo::getRegPressureLimit(), llvm::PPCRegisterInfo::getRegPressureLimit(), llvm::AArch64RegisterInfo::getRegPressureLimit(), llvm::ARMBaseRegisterInfo::getRegPressureLimit(), hasSubClassEq(), INITIALIZE_PASS(), llvm::ResourcePriorityQueue::rawRegPressureDelta(), llvm::ResourcePriorityQueue::regPressureDelta(), and llvm::ResourcePriorityQueue::scheduledNode().
unsigned llvm::TargetRegisterClass::getLaneMask () const [inline]
Returns the combination of all lane masks of register in this class.
The lane masks of the registers are the combination of all lane masks of their subregisters.
Definition at line 203 of file TargetRegisterInfo.h.
References LaneMask.
Referenced by llvm::MachineRegisterInfo::getMaxLaneMaskForVReg().
unsigned llvm::TargetRegisterClass::getNumRegs () const [inline]
getNumRegs - Return the number of registers in this class.
Definition at line 68 of file TargetRegisterInfo.h.
References llvm::MCRegisterClass::getNumRegs(), and MC.
Referenced by llvm::RegisterClassInfo::computePSetLimit(), llvm::MachineRegisterInfo::constrainRegClass(), llvm::AMDGPUInstrInfo::getIndirectIndexBegin(), and getRawAllocationOrder().
ArrayRef<MCPhysReg> llvm::TargetRegisterClass::getRawAllocationOrder (const MachineFunction & MF) const [inline]
getRawAllocationOrder - Returns the preferred order for allocating registers from this register class in MF.
The raw order comes directly from the .td file and may include reserved registers that are not allocatable. Register allocators should also make sure to allocate callee-saved registers only after all the volatiles are used. The RegisterClassInfo class provides filtered allocation orders with callee-saved registers moved to the end.
The MachineFunction argument can be used to tune the allocatable registers based on the characteristics of the function, subtarget, or other criteria.
By default, this method returns all registers in the class.
Definition at line 196 of file TargetRegisterInfo.h.
References begin(), getNumRegs(), llvm::makeArrayRef(), and OrderFunc.
Referenced by getAllocatableSetForRC().
unsigned llvm::TargetRegisterClass::getRegister (unsigned i) const [inline]
getRegister - Return the specified register in the class.
Definition at line 72 of file TargetRegisterInfo.h.
References llvm::MCRegisterClass::getRegister(), and MC.
Referenced by llvm::AMDGPUInstrInfo::expandPostRAPseudo(), llvm::AMDGPUInstrInfo::getIndirectIndexBegin(), llvm::SIRegisterInfo::getPhysRegSubReg(), and llvm::SITargetLowering::getRegForInlineAsmConstraint().
unsigned llvm::TargetRegisterClass::getSize () const [inline]
getSize - Return the size of the register in bytes, which is also the size of a stack slot allocated to hold a spilled copy of this register.
Definition at line 89 of file TargetRegisterInfo.h.
References llvm::MCRegisterClass::getSize(), and MC.
Referenced by llvm::DwarfExpression::AddMachineRegPiece(), llvm::PPCFrameLowering::addScavengingSpillSlot(), llvm::HexagonFrameLowering::assignCalleeSavedSpillSlots(), llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), llvm::MipsFunctionInfo::createEhDataRegsFI(), llvm::XCoreFunctionInfo::createEHSpillSlot(), llvm::XCoreFunctionInfo::createFPSpillSlot(), llvm::XCoreFunctionInfo::createLRSpillSlot(), llvm::MipsFrameLowering::estimateStackSize(), llvm::TargetLoweringBase::findRepresentativeClass(), llvm::TargetRegisterInfo::getCommonSuperRegClass(), getLoadStoreRegOpcode(), llvm::SIInstrInfo::getMemOpBaseRegImmOfs(), llvm::MipsFunctionInfo::getMoveF64ViaSpillFI(), llvm::SIInstrInfo::getMovOpcode(), llvm::SIInstrInfo::getOpSize(), llvm::SIRegisterInfo::getPhysRegSubReg(), llvm::TargetInstrInfo::getStackSlotRange(), llvm::SIInstrInfo::isOperandLegal(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::MipsSEFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::HexagonFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::XCoreFrameLowering::processFunctionBeforeFrameFinalized(), llvm::ARMBaseRegisterInfo::shouldCoalesce(), llvm::SIInstrInfo::splitSMRD(), llvm::SIInstrInfo::storeRegToStackSlot(), llvm::AArch64InstrInfo::storeRegToStackSlot(), and llvm::ARMBaseInstrInfo::storeRegToStackSlot().
const uint32_t* llvm::TargetRegisterClass::getSubClassMask () const [inline]
getSubClassMask - Returns a bit vector of subclasses, including this one.
The vector is indexed by class IDs, see hasSubClassEq() above for how to use it.
Definition at line 153 of file TargetRegisterInfo.h.
References SubClassMask.
Referenced by llvm::TargetRegisterInfo::getAllocatableClass(), llvm::TargetRegisterInfo::getCommonSubClass(), and llvm::TargetRegisterInfo::getMatchingSuperRegClass().
sc_iterator llvm::TargetRegisterClass::getSuperClasses () const [inline]
getSuperClasses - Returns a NULL terminated list of super-classes.
The classes are ordered by ID which is also a topological ordering from large to small classes. The list does NOT include the current class.
Definition at line 172 of file TargetRegisterInfo.h.
References SuperClasses.
Referenced by llvm::ARMBaseRegisterInfo::getLargestLegalSuperClass().
const uint16_t* llvm::TargetRegisterClass::getSuperRegIndices () const [inline]
getSuperRegIndices - Returns a 0-terminated list of sub-register indices that project some super-register class into this register class.
The list has an entry for each Idx such that:
There exists SuperRC where: For all Reg in SuperRC: this->contains(Reg:Idx)
Definition at line 165 of file TargetRegisterInfo.h.
References SuperRegIndices.
bool llvm::TargetRegisterClass::hasSubClass (const TargetRegisterClass * RC) const [inline]
hasSubClass - return true if the specified TargetRegisterClass is a proper sub-class of this TargetRegisterClass.
Definition at line 127 of file TargetRegisterInfo.h.
References hasSubClassEq().
Referenced by llvm::TargetRegisterInfo::getMinimalPhysRegClass(), and hasSuperClass().
bool llvm::TargetRegisterClass::hasSubClassEq (const TargetRegisterClass * RC) const [inline]
hasSubClassEq - Returns true if RC is a sub-class of or equal to this class.
Definition at line 133 of file TargetRegisterInfo.h.
References getID(), and SubClassMask.
Referenced by llvm::MachineFunction::addLiveIn(), canFoldCopy(), hasSubClass(), hasSuperClassEq(), and UpdateOperandRegClass().
bool llvm::TargetRegisterClass::hasSuperClass (const TargetRegisterClass * RC) const [inline]
hasSuperClass - return true if the specified TargetRegisterClass is a proper super-class of this TargetRegisterClass.
Definition at line 140 of file TargetRegisterInfo.h.
References hasSubClass().
bool llvm::TargetRegisterClass::hasSuperClassEq (const TargetRegisterClass * RC) const [inline]
hasSuperClassEq - Returns true if RC is a super-class of or equal to this class.
Definition at line 146 of file TargetRegisterInfo.h.
References hasSubClassEq().
Referenced by llvm::PPCInstrInfo::getOperandLatency(), isFPR64(), and isGPR64().
bool llvm::TargetRegisterClass::hasType (MVT vt) const [inline]
hasType - return true if this TargetRegisterClass has the ValueType vt.
Definition at line 106 of file TargetRegisterInfo.h.
References Other, and VTs.
Referenced by llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::TargetLowering::getRegForInlineAsmConstraint(), llvm::MipsSEInstrInfo::loadRegFromStack(), and llvm::MipsSEInstrInfo::storeRegToStack().
bool llvm::TargetRegisterClass::isAllocatable () const [inline]
isAllocatable - Return true if this register class may be used to create virtual registers.
Definition at line 102 of file TargetRegisterInfo.h.
References llvm::MCRegisterClass::isAllocatable(), and MC.
Referenced by llvm::MachineRegisterInfo::createVirtualRegister(), llvm::TargetRegisterInfo::getAllocatableClass(), getAllocatableSetForRC(), and llvm::MachineRegisterInfo::setRegClass().
bool llvm::TargetRegisterClass::isASubClass () const [inline]
isASubClass - return true if this TargetRegisterClass is a subset class of at least one other TargetRegisterClass.
Definition at line 178 of file TargetRegisterInfo.h.
References SuperClasses.
vt_iterator llvm::TargetRegisterClass::vt_begin () const [inline]
vt_begin / vt_end - Loop over all of the value types that can be represented by values in this register class.
Definition at line 115 of file TargetRegisterInfo.h.
References VTs.
Referenced by GetRegistersForValue(), getRegTy(), and llvm::TargetLoweringBase::isLegalRC().
vt_iterator llvm::TargetRegisterClass::vt_end () const [inline]
Definition at line 119 of file TargetRegisterInfo.h.
References I, llvm::MVT::Other, and VTs.
Referenced by getRegTy(), and llvm::TargetLoweringBase::isLegalRC().
Member Data Documentation
const uint8_t llvm::TargetRegisterClass::AllocationPriority
Classes with a higher priority value are assigned first by register allocators using a greedy heuristic.
The value is in the range [0,63].
Definition at line 51 of file TargetRegisterInfo.h.
const bool llvm::TargetRegisterClass::HasDisjunctSubRegs
Whether the class supports two (or more) disjunct subregister indices.
Definition at line 53 of file TargetRegisterInfo.h.
Referenced by llvm::MachineRegisterInfo::shouldTrackSubRegLiveness().
const unsigned llvm::TargetRegisterClass::LaneMask
Definition at line 48 of file TargetRegisterInfo.h.
Referenced by getLaneMask().
const MCRegisterClass* llvm::TargetRegisterClass::MC
Definition at line 44 of file TargetRegisterInfo.h.
Referenced by begin(), contains(), end(), getAlignment(), getCopyCost(), getID(), llvm::TargetRegisterInfo::getMatchingSuperReg(), getNumRegs(), llvm::TargetRegisterInfo::getRegClassName(), getRegister(), getSize(), and isAllocatable().
ArrayRef<MCPhysReg>(* llvm::TargetRegisterClass::OrderFunc)(const MachineFunction &)
Definition at line 55 of file TargetRegisterInfo.h.
Referenced by getRawAllocationOrder().
const uint32_t* llvm::TargetRegisterClass::SubClassMask
Definition at line 46 of file TargetRegisterInfo.h.
Referenced by getSubClassMask(), and hasSubClassEq().
const sc_iterator llvm::TargetRegisterClass::SuperClasses
Definition at line 54 of file TargetRegisterInfo.h.
Referenced by getSuperClasses(), and isASubClass().
const uint16_t* llvm::TargetRegisterClass::SuperRegIndices
Definition at line 47 of file TargetRegisterInfo.h.
Referenced by getSuperRegIndices().
const vt_iterator llvm::TargetRegisterClass::VTs
Definition at line 45 of file TargetRegisterInfo.h.
Referenced by hasType(), vt_begin(), and vt_end().
The documentation for this class was generated from the following file:
TargetRegisterInfo.h