LLVM: llvm::TargetPassConfig Class Reference
llvm::TargetPassConfig Class Reference
Target-Independent Code Generator Pass Configuration Options.
#include <Passes.h>
Public Member Functions
TargetPassConfig (TargetMachine *tm, PassManagerBase &pm)
TargetPassConfig ()
~TargetPassConfig () override
template<typename TMC >
TMC & getTM () const
Get the right type of TargetMachine for this target.
void setInitialized ()
CodeGenOpt::Level getOptLevel () const
void setStartStopPasses (AnalysisID Start, AnalysisID Stop)
setStartStopPasses - Set the StartAfter and StopAfter passes to allow running only a portion of the normal code-gen pass sequence.
void setDisableVerify (bool Disable)
bool getEnableTailMerge () const
void setEnableTailMerge (bool Enable)
void substitutePass (AnalysisID StandardID, IdentifyingPassPtr TargetID)
Allow the target to override a specific pass without overriding the pass pipeline.
void insertPass (AnalysisID TargetPassID, IdentifyingPassPtr InsertedPassID)
Insert InsertedPassID pass after TargetPassID pass.
void enablePass (AnalysisID PassID)
Allow the target to enable a specific standard pass by default.
void disablePass (AnalysisID PassID)
Allow the target to disable a specific standard pass by default.
IdentifyingPassPtr getPassSubstitution (AnalysisID StandardID) const
Return the pass substituted for StandardID by the target.
bool getOptimizeRegAlloc () const
Return true if the optimized regalloc pipeline is enabled.
bool getEnableShrinkWrap () const
Return true if shrink wrapping is enabled.
bool usingDefaultRegAlloc () const
Return true if the default global register allocator is in use and has not be overriden on the command line with '-regalloc=...'.
virtual void addIRPasses ()
Add common target configurable passes that perform LLVM IR to IR transforms following machine independent optimization.
void addPassesToHandleExceptions ()
Add passes to lower exception handling for the code generator.
virtual void addCodeGenPrepare ()
Add pass to prepare the LLVM IR for code generation.
virtual void addISelPrepare ()
Add common passes that perform LLVM IR to IR transforms in preparation for instruction selection.
virtual bool addInstSelector ()
addInstSelector - This method should install an instruction selector pass, which converts from LLVM code to machine instructions.
virtual void addMachinePasses ()
Add the complete, standard set of LLVM CodeGen passes.
false Return NULL to select the default (generic) machine scheduler.*/virtual ScheduleDAGInstrs *createMachineScheduler(MachineSchedContext *C) const
Create an instance of ScheduleDAGInstrs to be run within the standard MachineScheduler pass for this function and target at the current optimization level.
virtual ScheduleDAGInstrs * createPostMachineScheduler (MachineSchedContext *C) const
Similar to createMachineScheduler but used when postRA machine scheduling is enabled.
Static Public Attributes
static char EarlyTailDuplicateID
Pseudo Pass IDs.
static char PostRAMachineLICMID = 0
PostRAMachineLICM - A clone of the LICM pass that runs during late machine optimization after regalloc.
static char ID
Protected Member Functions
void setOpt (bool &Opt, bool Val)
virtual bool addPreISel ()
Methods with trivial inline returns are convenient points in the common codegen pass pipeline where targets may insert passes.
virtual void addMachineSSAOptimization ()
addMachineSSAOptimization - Add standard passes that optimize machine instructions in SSA form.
virtual bool addILPOpts ()
Add passes that optimize instruction level parallelism for out-of-order targets.
virtual void addPreRegAlloc ()
This method may be implemented by targets that want to run passes immediately before register allocation.
virtual FunctionPass * createTargetRegisterAllocator (bool Optimized)
createTargetRegisterAllocator - Create the register allocator pass for this target at the current optimization level.
virtual void addFastRegAlloc (FunctionPass *RegAllocPass)
addFastRegAlloc - Add the minimum set of target-independent passes that are required for fast register allocation.
virtual void addOptimizedRegAlloc (FunctionPass *RegAllocPass)
addOptimizedRegAlloc - Add passes related to register allocation.
virtual bool addPreRewrite ()
addPreRewrite - Add passes to the optimized register allocation pipeline after register allocation is complete, but before virtual registers are rewritten to physical registers.
virtual void addPostRegAlloc ()
This method may be implemented by targets that want to run passes after register allocation pass pipeline but before prolog-epilog insertion.
virtual void addMachineLateOptimization ()
Add passes that optimize machine instructions after register allocation.
virtual void addPreSched2 ()
This method may be implemented by targets that want to run passes after prolog-epilog insertion and before the second instruction scheduling pass.
virtual bool addGCPasses ()
addGCPasses - Add late codegen passes that analyze code for garbage collection.
virtual void addBlockPlacement ()
Add standard basic block placement passes.
virtual void addPreEmitPass ()
This pass may be implemented by targets that want to run passes immediately before machine code is emitted.
AnalysisID addPass (AnalysisID PassID, bool verifyAfter=true, bool printAfter=true)
Utilities for targets to add passes to the pass manager.
void addPass (Pass *P, bool verifyAfter=true, bool printAfter=true)
Add a pass to the PassManager if that pass is supposed to be run, as determined by the StartAfter and StopAfter options.
FunctionPass * createRegAllocPass (bool Optimized)
addMachinePasses helper to create the target-selected or overriden regalloc pass.
void printAndVerify (const std::string &Banner)
printAndVerify - Add a pass to dump then verify the machine function, if those steps are enabled.
void addPrintPass (const std::string &Banner)
Add a pass to print the machine function if printing is enabled.
void addVerifyPass (const std::string &Banner)
Add a pass to perform basic verification of the machine function if verification is enabled.
Protected Attributes
TargetMachine * TM
PassConfigImpl * Impl
bool Initialized
bool DisableVerify
bool EnableTailMerge
Default setting for -enable-tail-merge on this target.
bool EnableShrinkWrap
Default setting for -enable-shrink-wrap on this target.
Detailed Description
Target-Independent Code Generator Pass Configuration Options.
This is an ImmutablePass solely for the purpose of exposing CodeGen options to the internals of other CodeGen passes.
Definition at line 87 of file CodeGen/Passes.h.
Constructor & Destructor Documentation
TargetPassConfig::TargetPassConfig (TargetMachine * tm, PassManagerBase & pm)
Definition at line 216 of file Passes.cpp.
References EarlyTailDuplicateID, llvm::PassRegistry::getPassRegistry(), Impl, llvm::initializeCodeGen(), llvm::MachineLICMID, PostRAMachineLICMID, substitutePass(), and llvm::TailDuplicateID.
TargetPassConfig::TargetPassConfig ()
Definition at line 253 of file Passes.cpp.
References llvm_unreachable.
TargetPassConfig::~TargetPassConfig () [override]
Definition at line 210 of file Passes.cpp.
References Impl.
Member Function Documentation
void TargetPassConfig::addBlockPlacement () [protected, virtual]
Add standard basic block placement passes.
Definition at line 797 of file Passes.cpp.
References addPass(), EnableBlockPlacementStats, llvm::MachineBlockPlacementID, and llvm::MachineBlockPlacementStatsID.
Referenced by addMachinePasses().
void TargetPassConfig::addCodeGenPrepare () [virtual]
Add pass to prepare the LLVM IR for code generation.
This should be done before exception handling preparation passes.
Definition at line 449 of file Passes.cpp.
References addPass(), llvm::createCodeGenPreparePass(), llvm::createRewriteSymbolsPass(), DisableCGP, getOptLevel(), llvm::CodeGenOpt::None, and TM.
Referenced by addPassesToGenerateCode().
void TargetPassConfig::addFastRegAlloc (FunctionPass * RegAllocPass) [protected, virtual]
addFastRegAlloc - Add the minimum set of target-independent passes that are required for fast register allocation.
Add the minimum set of target-independent passes that are required for register allocation.
No coalescing or scheduling.
Definition at line 714 of file Passes.cpp.
References addPass(), llvm::PHIEliminationID, and llvm::TwoAddressInstructionPassID.
Referenced by addMachinePasses().
bool TargetPassConfig::addGCPasses () [protected, virtual]
addGCPasses - Add late codegen passes that analyze code for garbage collection.
Add standard GC passes.
This should return true if GC info should be printed after these passes.
Definition at line 791 of file Passes.cpp.
References addPass(), and llvm::GCMachineCodeAnalysisID.
Referenced by addMachinePasses().
virtual bool llvm::TargetPassConfig::addILPOpts () [inline, protected, virtual]
Add passes that optimize instruction level parallelism for out-of-order targets.
These passes are run while the machine code is still in SSA form, so they can use MachineTraceMetrics to control their heuristics.
All passes added here should preserve the MachineDominatorTree, MachineLoopInfo, and MachineTraceMetrics analyses.
Definition at line 265 of file CodeGen/Passes.h.
Referenced by addMachineSSAOptimization().
virtual bool llvm::TargetPassConfig::addInstSelector () [inline, virtual]
addInstSelector - This method should install an instruction selector pass, which converts from LLVM code to machine instructions.
Definition at line 209 of file CodeGen/Passes.h.
Referenced by addPassesToGenerateCode().
void TargetPassConfig::addIRPasses () [virtual]
Add common target configurable passes that perform LLVM IR to IR transforms following machine independent optimization.
Definition at line 375 of file Passes.cpp.
References addPass(), llvm::createBasicAliasAnalysisPass(), llvm::createCFLAliasAnalysisPass(), llvm::createConstantHoistingPass(), llvm::createGCLoweringPass(), llvm::createLoopStrengthReducePass(), llvm::createPartiallyInlineLibCallsPass(), llvm::createPrintFunctionPass(), llvm::createScopedNoAliasAAPass(), llvm::createShadowStackGCLoweringPass(), llvm::createTypeBasedAliasAnalysisPass(), llvm::createUnreachableBlockEliminationPass(), llvm::createVerifierPass(), llvm::dbgs(), DisableConstantHoisting, DisableLSR, DisablePartialLibcallInlining, DisableVerify, getOptLevel(), llvm::CodeGenOpt::None, PrintLSR, and UseCFLAA.
Referenced by addPassesToGenerateCode().
void TargetPassConfig::addISelPrepare () [virtual]
Add common passes that perform LLVM IR to IR transforms in preparation for instruction selection.
Definition at line 457 of file Passes.cpp.
References addPass(), addPreISel(), llvm::createPrintFunctionPass(), llvm::createSafeStackPass(), llvm::createStackProtectorPass(), llvm::createVerifierPass(), llvm::dbgs(), DisableVerify, PrintISelInput, and TM.
Referenced by addPassesToGenerateCode().
void TargetPassConfig::addMachineLateOptimization () [protected, virtual]
Add passes that optimize machine instructions after register allocation.
Post RegAlloc Pass Configuration.
Definition at line 775 of file Passes.cpp.
References addPass(), llvm::BranchFolderPassID, llvm::MachineCopyPropagationID, llvm::TargetMachine::requiresStructuredCFG(), llvm::TailDuplicateID, and TM.
Referenced by addMachinePasses().
void TargetPassConfig::addMachinePasses () [virtual]
Add the complete, standard set of LLVM CodeGen passes.
Add the complete set of target-independent postISel code generator passes.
Fully developed targets will not generally override this.
This can be read as the standard order of major LLVM CodeGen stages. Stages with nontrivial configuration or multiple passes are broken out below in addStage routines.
Any TargetPassConfig::addXX routine may be overriden by the Target. The addPre/Post methods with empty header implementations allow injecting target-specific fixups just before or after major stages. Additionally, targets have the flexibility to change pass order within a stage by overriding default implementation of addStage routines below. Each technique has maintainability tradeoffs because alternate pass orders are not well supported. addPre/Post works better if the target pass is easily tied to a common pass. But if it has subtle dependencies on multiple passes, the target should override the stage instead.
TODO: We could use a single addPre/Post(ID) hook to allow pass injection before/after any target-independent pass. But it's currently overkill.
Add passes that optimize machine instructions after register allocation.
Definition at line 493 of file Passes.cpp.
References addBlockPlacement(), addFastRegAlloc(), addGCPasses(), addMachineLateOptimization(), addMachineSSAOptimization(), addOptimizedRegAlloc(), addPass(), addPostRegAlloc(), addPreEmitPass(), addPreRegAlloc(), addPreSched2(), llvm::createGCInfoPrinter(), createRegAllocPass(), llvm::dbgs(), EnableImplicitNullChecks, llvm::ExpandISelPseudosID, llvm::ExpandPostRAPseudosID, getEnableShrinkWrap(), getOptimizeRegAlloc(), getOptLevel(), llvm::PassRegistry::getPassInfo(), llvm::PassRegistry::getPassRegistry(), llvm::PassInfo::getTypeInfo(), if(), llvm::ImplicitNullChecksID, insertPass(), llvm::LocalStackSlotAllocationID, MISchedPostRA, llvm::CodeGenOpt::None, llvm::TargetMachine::Options, llvm::PostMachineSchedulerID, llvm::PostRASchedulerID, printAndVerify(), PrintGCInfo, llvm::TargetOptions::PrintMachineCode, PrintMachineInstrs, llvm::PrologEpilogCodeInserterID, llvm::ShrinkWrapID, llvm::StackMapLivenessID, and TM.
Referenced by addPassesToGenerateCode().
void TargetPassConfig::addMachineSSAOptimization () [protected, virtual]
addMachineSSAOptimization - Add standard passes that optimize machine instructions in SSA form.
Add passes that optimize machine instructions in SSA form.
Definition at line 583 of file Passes.cpp.
References addILPOpts(), addPass(), llvm::DeadMachineInstructionElimID, EarlyTailDuplicateID, llvm::LocalStackSlotAllocationID, llvm::MachineCSEID, llvm::MachineLICMID, llvm::MachineSinkingID, llvm::OptimizePHIsID, llvm::PeepholeOptimizerID, and llvm::StackColoringID.
Referenced by addMachinePasses().
void TargetPassConfig::addOptimizedRegAlloc (FunctionPass * RegAllocPass) [protected, virtual]
addOptimizedRegAlloc - Add passes related to register allocation.
Add standard target-independent passes that are tightly coupled with optimized register allocation, including coalescing, machine instruction scheduling, and register allocation itself.
LLVMTargetMachine provides standard regalloc passes for most targets.
Definition at line 724 of file Passes.cpp.
References addPass(), addPreRewrite(), EarlyLiveIntervals, llvm::LiveIntervalsID, llvm::LiveVariablesID, llvm::MachineLoopInfoID, llvm::MachineSchedulerID, llvm::PHIEliminationID, PostRAMachineLICMID, llvm::ProcessImplicitDefsID, llvm::RegisterCoalescerID, llvm::StackSlotColoringID, llvm::TwoAddressInstructionPassID, and llvm::VirtRegRewriterID.
Referenced by addMachinePasses().
AnalysisID TargetPassConfig::addPass (AnalysisID PassID, bool verifyAfter = true, bool printAfter = true) [protected]
Utilities for targets to add passes to the pass manager.
Add a CodeGen pass at this point in the pipeline after checking for target and command line overrides.
Add a CodeGen pass at this point in the pipeline after checking overrides. Return the pass that was added, or zero if no pass was added. printAfter if true and adding a machine function pass add an extra machine printer pass afterwards verifyAfter if true and adding a machine function pass add an extra machine verification pass afterwards.
addPass cannot return a pointer to the pass instance because is internal the PassManager and the instance we create here may already be freed.
Definition at line 337 of file Passes.cpp.
References llvm::Pass::createPass(), llvm::IdentifyingPassPtr::getID(), llvm::IdentifyingPassPtr::getInstance(), llvm::Pass::getPassID(), getPassSubstitution(), llvm::IdentifyingPassPtr::isInstance(), llvm::IdentifyingPassPtr::isValid(), llvm_unreachable, overridePass(), and P.
Referenced by addBlockPlacement(), addCodeGenPrepare(), addFastRegAlloc(), addGCPasses(), addIRPasses(), addISelPrepare(), addMachineLateOptimization(), addMachinePasses(), addMachineSSAOptimization(), addOptimizedRegAlloc(), addPass(), and addPassesToHandleExceptions().
void TargetPassConfig::addPass (Pass * P, bool verifyAfter = true, bool printAfter = true) [protected]
Add a pass to the PassManager if that pass is supposed to be run, as determined by the StartAfter and StopAfter options.
Add a pass to the PassManager if that pass is supposed to be run.
Takes ownership of the pass. printAfter if true and adding a machine function pass add an extra machine printer pass afterwards verifyAfter if true and adding a machine function pass add an extra machine verification pass afterwards.
If the Started/Stopped flags indicate either that the compilation should start at a later pass or that it should stop after an earlier pass, then do not add the pass. Finally, compare the current pass against the StartAfter and StopAfter options and change the Started/Stopped flags accordingly.
Definition at line 282 of file Passes.cpp.
References addPass(), addPrintPass(), addVerifyPass(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::Pass::createPass(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::Pass::getPassID(), llvm::Pass::getPassName(), I, Impl, Initialized, llvm::PassConfigImpl::InsertedPasses, and llvm::report_fatal_error().
void TargetPassConfig::addPassesToHandleExceptions ()
Add passes to lower exception handling for the code generator.
Turn exception handling constructs into something the code generators can handle.
Definition at line 416 of file Passes.cpp.
References addPass(), llvm::WinEH::ARM, llvm::createDwarfEHPass(), llvm::createLowerInvokePass(), llvm::createSjLjEHPreparePass(), llvm::createUnreachableBlockEliminationPass(), llvm::createWinEHPass(), llvm::DwarfCFI, llvm::MCAsmInfo::getExceptionHandlingType(), llvm::TargetMachine::getMCAsmInfo(), llvm::None, llvm::SjLj, TM, and llvm::WinEH.
Referenced by addPassesToGenerateCode().
virtual void llvm::TargetPassConfig::addPostRegAlloc () [inline, protected, virtual]
This method may be implemented by targets that want to run passes after register allocation pass pipeline but before prolog-epilog insertion.
Definition at line 299 of file CodeGen/Passes.h.
Referenced by addMachinePasses().
virtual void llvm::TargetPassConfig::addPreEmitPass () [inline, protected, virtual]
This pass may be implemented by targets that want to run passes immediately before machine code is emitted.
Definition at line 318 of file CodeGen/Passes.h.
Referenced by addMachinePasses().
virtual bool llvm::TargetPassConfig::addPreISel () [inline, protected, virtual]
Methods with trivial inline returns are convenient points in the common codegen pass pipeline where targets may insert passes.
Methods with out-of-line standard implementations are major CodeGen stages called by addMachinePasses. Some targets may override major stages when inserting passes is insufficient, but maintaining overriden stages is more work. addPreISelPasses - This method should add any "last minute" LLVM->LLVM passes (which are run just before instruction selector).
Definition at line 251 of file CodeGen/Passes.h.
Referenced by addISelPrepare().
virtual void llvm::TargetPassConfig::addPreRegAlloc () [inline, protected, virtual]
This method may be implemented by targets that want to run passes immediately before register allocation.
Definition at line 271 of file CodeGen/Passes.h.
Referenced by addMachinePasses().
virtual bool llvm::TargetPassConfig::addPreRewrite () [inline, protected, virtual]
addPreRewrite - Add passes to the optimized register allocation pipeline after register allocation is complete, but before virtual registers are rewritten to physical registers.
These passes must preserve VirtRegMap and LiveIntervals, and when running after RABasic or RAGreedy, they should take advantage of LiveRegMatrix. When these passes run, VirtRegMap contains legal physreg assignments for all virtual registers.
Definition at line 293 of file CodeGen/Passes.h.
Referenced by addOptimizedRegAlloc().
virtual void llvm::TargetPassConfig::addPreSched2 () [inline, protected, virtual]
This method may be implemented by targets that want to run passes after prolog-epilog insertion and before the second instruction scheduling pass.
Definition at line 306 of file CodeGen/Passes.h.
Referenced by addMachinePasses().
void TargetPassConfig::addPrintPass (const std::string & Banner) [protected]
Add a pass to print the machine function if printing is enabled.
Definition at line 363 of file Passes.cpp.
References llvm::createMachineFunctionPrinterPass(), llvm::dbgs(), llvm::TargetMachine::shouldPrintMachineCode(), and TM.
Referenced by addPass(), and printAndVerify().
void TargetPassConfig::addVerifyPass (const std::string & Banner) [protected]
Add a pass to perform basic verification of the machine function if verification is enabled.
Definition at line 368 of file Passes.cpp.
References llvm::createMachineVerifierPass(), and VerifyMachineCode.
Referenced by addPass(), and printAndVerify().
virtual ScheduleDAGInstrs* llvm::TargetPassConfig::createPostMachineScheduler (MachineSchedContext * C) const [inline, virtual]
Similar to createMachineScheduler but used when postRA machine scheduling is enabled.
Definition at line 234 of file CodeGen/Passes.h.
FunctionPass * TargetPassConfig::createRegAllocPass (bool Optimized) [protected]
addMachinePasses helper to create the target-selected or overriden regalloc pass.
Find and instantiate the register allocation pass requested by this target at the current optimization level.
Different register allocators are defined as separate passes because they may require different analysis.
This helper ensures that the regalloc= option is always available, even for targets that override the default allocator.
FIXME: When MachinePassRegistry register pass IDs instead of function ptrs, this can be folded into addPass.
Definition at line 691 of file Passes.cpp.
References createTargetRegisterAllocator(), llvm::RegisterRegAlloc::getDefault(), RegAlloc, llvm::RegisterRegAlloc::setDefault(), and useDefaultRegisterAllocator().
Referenced by addMachinePasses().
FunctionPass * TargetPassConfig::createTargetRegisterAllocator (bool Optimized) [protected, virtual]
createTargetRegisterAllocator - Create the register allocator pass for this target at the current optimization level.
Instantiate the default register allocator pass for this target for either the optimized or unoptimized allocation path.
This will be added to the pass manager by addFastRegAlloc in the unoptimized case or addOptimizedRegAlloc in the optimized case.
A target that uses the standard regalloc pass order for fast or optimized allocation may still override this for per-target regalloc selection. But -regalloc=... always takes precedence.
Definition at line 675 of file Passes.cpp.
References llvm::createFastRegisterAllocator(), and llvm::createGreedyRegisterAllocator().
Referenced by createRegAllocPass().
false Return NULL to select the llvm::TargetPassConfig::default (generic) const [inline]
Create an instance of ScheduleDAGInstrs to be run within the standard MachineScheduler pass for this function and target at the current optimization level.
This can also be used to plug a new MachineSchedStrategy into an instance of the standard ScheduleDAGMI: return new ScheduleDAGMI(C, make_unique<MyStrategy>(C), /* IsPostRA=
Definition at line 225 of file CodeGen/Passes.h.
void llvm::TargetPassConfig::disablePass (AnalysisID PassID) [inline]
Allow the target to disable a specific standard pass by default.
Definition at line 174 of file CodeGen/Passes.h.
References substitutePass().
void llvm::TargetPassConfig::enablePass (AnalysisID PassID) [inline]
Allow the target to enable a specific standard pass by default.
Definition at line 171 of file CodeGen/Passes.h.
References substitutePass().
bool TargetPassConfig::getEnableShrinkWrap () const
Return true if shrink wrapping is enabled.
Definition at line 620 of file Passes.cpp.
References llvm::cl::BOU_FALSE, llvm::cl::BOU_TRUE, llvm::cl::BOU_UNSET, EnableShrinkWrap, EnableShrinkWrapOpt, getOptLevel(), llvm_unreachable, and llvm::None.
Referenced by addMachinePasses().
bool llvm::TargetPassConfig::getEnableTailMerge () const [inline]
Definition at line 159 of file CodeGen/Passes.h.
References EnableTailMerge.
Referenced by INITIALIZE_PASS().
bool TargetPassConfig::getOptimizeRegAlloc () const
Return true if the optimized regalloc pipeline is enabled.
Register Allocation Pass Configuration.
Definition at line 639 of file Passes.cpp.
References llvm::cl::BOU_FALSE, llvm::cl::BOU_TRUE, llvm::cl::BOU_UNSET, getOptLevel(), llvm_unreachable, llvm::None, and OptimizeRegAlloc.
Referenced by addMachinePasses().
CodeGenOpt::Level llvm::TargetPassConfig::getOptLevel () const [inline]
Definition at line 143 of file CodeGen/Passes.h.
References llvm::TargetMachine::getOptLevel(), and TM.
Referenced by addCodeGenPrepare(), addIRPasses(), addMachinePasses(), getEnableShrinkWrap(), and getOptimizeRegAlloc().
IdentifyingPassPtr TargetPassConfig::getPassSubstitution (AnalysisID StandardID) const
Return the pass substituted for StandardID by the target.
If no substitution exists, return StandardID.
Definition at line 269 of file Passes.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), I, Impl, and llvm::PassConfigImpl::TargetPasses.
Referenced by addPass().
template<typename TMC > TMC& llvm::TargetPassConfig::getTM () const [inline]
Get the right type of TargetMachine for this target.
Definition at line 136 of file CodeGen/Passes.h.
References TM.
void TargetPassConfig::insertPass (AnalysisID TargetPassID, IdentifyingPassPtr InsertedPassID)
Insert InsertedPassID pass after TargetPassID pass.
Insert InsertedPassID pass after TargetPassID.
Definition at line 234 of file Passes.cpp.
References llvm::IdentifyingPassPtr::getID(), llvm::IdentifyingPassPtr::getInstance(), llvm::Pass::getPassID(), Impl, llvm::PassConfigImpl::InsertedPasses, llvm::IdentifyingPassPtr::isInstance(), P, and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by addMachinePasses().
void TargetPassConfig::printAndVerify (const std::string & Banner) [protected]
printAndVerify - Add a pass to dump then verify the machine function, if those steps are enabled.
Definition at line 358 of file Passes.cpp.
References addPrintPass(), and addVerifyPass().
Referenced by addMachinePasses().
void llvm::TargetPassConfig::setDisableVerify (bool Disable) [inline]
Definition at line 157 of file CodeGen/Passes.h.
References DisableVerify, and setOpt().
Referenced by addPassesToGenerateCode().
void llvm::TargetPassConfig::setEnableTailMerge (bool Enable) [inline]
Definition at line 160 of file CodeGen/Passes.h.
References EnableTailMerge, and setOpt().
void llvm::TargetPassConfig::setInitialized () [inline]
Definition at line 141 of file CodeGen/Passes.h.
References Initialized.
Referenced by addPassesToGenerateCode().
void TargetPassConfig::setOpt (bool & Opt, bool Val) [protected]
Definition at line 259 of file Passes.cpp.
References Initialized.
Referenced by setDisableVerify(), and setEnableTailMerge().
void llvm::TargetPassConfig::setStartStopPasses (AnalysisID Start, AnalysisID Stop) [inline]
setStartStopPasses - Set the StartAfter and StopAfter passes to allow running only a portion of the normal code-gen pass sequence.
If the Start pass ID is zero, then compilation will begin at the normal point; otherwise, clear the Started flag to indicate that passes should not be added until the starting pass is seen. If the Stop pass ID is zero, then compilation will continue to the end.
Definition at line 151 of file CodeGen/Passes.h.
Referenced by addPassesToGenerateCode().
void TargetPassConfig::substitutePass (AnalysisID StandardID, IdentifyingPassPtr TargetID)
Allow the target to override a specific pass without overriding the pass pipeline.
When passes are added to the standard pipeline at the point where StandardID is expected, add TargetID in its place.
Definition at line 264 of file Passes.cpp.
References Impl, and llvm::PassConfigImpl::TargetPasses.
Referenced by disablePass(), enablePass(), and TargetPassConfig().
bool TargetPassConfig::usingDefaultRegAlloc () const
Return true if the default global register allocator is in use and has not be overriden on the command line with '-regalloc=...'.
Definition at line 708 of file Passes.cpp.
References RegAlloc.
Member Data Documentation
bool llvm::TargetPassConfig::DisableVerify [protected]
Definition at line 118 of file CodeGen/Passes.h.
Referenced by addIRPasses(), addISelPrepare(), and setDisableVerify().
char llvm::TargetPassConfig::EarlyTailDuplicateID [static]
Pseudo Pass IDs.
These are defined within TargetPassConfig because they are unregistered pass IDs. They are only useful for use with TargetPassConfig APIs to identify multiple occurrences of the same pass. EarlyTailDuplicate - A clone of the TailDuplicate pass that runs early during codegen, on SSA form.
Definition at line 96 of file CodeGen/Passes.h.
Referenced by addMachineSSAOptimization(), overridePass(), and TargetPassConfig().
bool llvm::TargetPassConfig::EnableShrinkWrap [protected]
Default setting for -enable-shrink-wrap on this target.
Definition at line 124 of file CodeGen/Passes.h.
Referenced by getEnableShrinkWrap().
bool llvm::TargetPassConfig::EnableTailMerge [protected]
Default setting for -enable-tail-merge on this target.
Definition at line 121 of file CodeGen/Passes.h.
Referenced by getEnableTailMerge(), and setEnableTailMerge().
char llvm::TargetPassConfig::ID [static]
Definition at line 133 of file CodeGen/Passes.h.
PassConfigImpl* llvm::TargetPassConfig::Impl [protected]
Definition at line 112 of file CodeGen/Passes.h.
Referenced by addPass(), getPassSubstitution(), insertPass(), substitutePass(), TargetPassConfig(), and ~TargetPassConfig().
bool llvm::TargetPassConfig::Initialized [protected]
Definition at line 113 of file CodeGen/Passes.h.
Referenced by addPass(), setInitialized(), and setOpt().
char TargetPassConfig::PostRAMachineLICMID = 0 [static]
PostRAMachineLICM - A clone of the LICM pass that runs during late machine optimization after regalloc.
Definition at line 100 of file CodeGen/Passes.h.
Referenced by addOptimizedRegAlloc(), overridePass(), and TargetPassConfig().
TargetMachine* llvm::TargetPassConfig::TM [protected]
Definition at line 111 of file CodeGen/Passes.h.
Referenced by addCodeGenPrepare(), addISelPrepare(), addMachineLateOptimization(), addMachinePasses(), addPassesToHandleExceptions(), addPrintPass(), getOptLevel(), and getTM().
The documentation for this class was generated from the following files:
CodeGen/Passes.h
Passes.cpp