LLVM: llvm::DIEAbbrev Class Reference
llvm::DIEAbbrev Class Reference
DIEAbbrev - Dwarf abbreviation, describes the organization of a debug information object.
#include <DIE.h>
Public Member Functions
DIEAbbrev (dwarf::Tag T, bool C)
dwarf::Tag getTag () const
unsigned getNumber () const
bool hasChildren () const
const SmallVectorImpl
< DIEAbbrevData > & getData () const
void setChildrenFlag (bool hasChild)
void setNumber (unsigned N)
void AddAttribute (dwarf::Attribute Attribute, dwarf::Form Form)
AddAttribute - Adds another set of attribute information to the abbreviation.
void Profile (FoldingSetNodeID &ID) const
Profile - Used to gather unique data for the abbreviation folding set.
void Emit (const AsmPrinter *AP) const
Emit - Print the abbreviation using the specified asm printer.
void print (raw_ostream &O)
void dump ()
Detailed Description
DIEAbbrev - Dwarf abbreviation, describes the organization of a debug information object.
Definition at line 57 of file DIE.h.
Constructor & Destructor Documentation
llvm::DIEAbbrev::DIEAbbrev (dwarf::Tag T, bool C) [inline]
Definition at line 77 of file DIE.h.
Member Function Documentation
void llvm::DIEAbbrev::AddAttribute (dwarf::Attribute Attribute, dwarf::Form Form) [inline]
AddAttribute - Adds another set of attribute information to the abbreviation.
Definition at line 89 of file DIE.h.
References llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
void DIEAbbrev::dump ()
Definition at line 107 of file DIE.cpp.
References llvm::dbgs(), and print().
void DIEAbbrev::Emit (const AsmPrinter * AP) const
Emit - Print the abbreviation using the specified asm printer.
Definition at line 64 of file DIE.cpp.
References llvm::dwarf::AttributeString(), llvm::dwarf::ChildrenString(), llvm::AsmPrinter::EmitULEB128(), llvm::dwarf::FormEncodingString(), llvm::DIEAbbrevData::getAttribute(), llvm::DIEAbbrevData::getForm(), N, llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::dwarf::TagString().
const SmallVectorImpl<DIEAbbrevData>& llvm::DIEAbbrev::getData () const [inline]
Definition at line 83 of file DIE.h.
unsigned llvm::DIEAbbrev::getNumber () const [inline]
Definition at line 81 of file DIE.h.
dwarf::Tag llvm::DIEAbbrev::getTag () const [inline]
Definition at line 80 of file DIE.h.
bool llvm::DIEAbbrev::hasChildren () const [inline]
Definition at line 82 of file DIE.h.
Referenced by llvm::DwarfFile::computeSizeAndOffset().
void DIEAbbrev::print (raw_ostream & O)
Definition at line 90 of file DIE.cpp.
References llvm::dwarf::AttributeString(), llvm::dwarf::ChildrenString(), llvm::format(), llvm::dwarf::FormEncodingString(), N, llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::dwarf::TagString().
Referenced by dump().
void DIEAbbrev::Profile (FoldingSetNodeID & ID) const
Profile - Used to gather unique data for the abbreviation folding set.
Definition at line 53 of file DIE.cpp.
References llvm::FoldingSetNodeID::AddInteger(), N, and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::DwarfFile::assignAbbrevNumber().
void llvm::DIEAbbrev::setChildrenFlag (bool hasChild) [inline]
Definition at line 84 of file DIE.h.
void llvm::DIEAbbrev::setNumber (unsigned N) [inline]
Definition at line 85 of file DIE.h.
Referenced by llvm::DwarfFile::assignAbbrevNumber().
The documentation for this class was generated from the following files:
DIE.h
DIE.cpp