LLVM: llvm::StructLayout Class Reference
llvm::StructLayout Class Reference
Used to lazily calculate structure layout information for a target machine, based on the DataLayout structure.
#include <DataLayout.h>
Public Member Functions
uint64_t getSizeInBytes () const
uint64_t getSizeInBits () const
unsigned getAlignment () const
unsigned getElementContainingOffset (uint64_t Offset) const
Given a valid byte offset into the structure, returns the structure index that contains it.
uint64_t getElementOffset (unsigned Idx) const
uint64_t getElementOffsetInBits (unsigned Idx) const
Friends
class DataLayout
Detailed Description
Used to lazily calculate structure layout information for a target machine, based on the DataLayout structure.
Definition at line 473 of file DataLayout.h.
Member Function Documentation
unsigned llvm::StructLayout::getAlignment () const [inline]
Definition at line 483 of file DataLayout.h.
unsigned StructLayout::getElementContainingOffset (uint64_t Offset) const
Given a valid byte offset into the structure, returns the structure index that contains it.
getElementContainingOffset - Given a valid offset into the structure, return the structure index that contains it.
Definition at line 74 of file DataLayout.cpp.
References llvm::SI.
Referenced by getNaturalGEPRecursively(), getTypePartition(), LLVMElementAtOffset(), ReadDataFromGlobal(), stripAggregateTypeWrapping(), and SymbolicallyEvaluateGEP().
uint64_t llvm::StructLayout::getElementOffset (unsigned Idx) const [inline]
Definition at line 489 of file DataLayout.h.
Referenced by llvm::GEPOperator::accumulateConstantOffset(), aliasSameBasePointerGEPs(), computeKnownBitsFromOperator(), llvm::ComputeValueVTs(), DecomposeGEPExpression(), llvm::EmitGEPOffset(), emitGlobalConstantStruct(), EvaluateGEPOffsetExpression(), getElementOffsetInBits(), llvm::DataLayout::getIndexedOffset(), getNaturalGEPRecursively(), GetOffsetFromIndex(), llvm::ScalarEvolution::getOffsetOfExpr(), getTypePartition(), llvm::ExecutionEngine::InitializeMemory(), isGEPFoldable(), isGEPKnownNonNull(), LLVMOffsetOfElement(), ReadDataFromGlobal(), llvm::FastISel::selectGetElementPtr(), SRAGlobal(), and SymbolicallyEvaluateGEP().
uint64_t llvm::StructLayout::getElementOffsetInBits (unsigned Idx) const [inline]
Definition at line 494 of file DataLayout.h.
References getElementOffset().
Referenced by HasPadding().
uint64_t llvm::StructLayout::getSizeInBits () const [inline]
Definition at line 481 of file DataLayout.h.
Referenced by llvm::DataLayout::getTypeSizeInBits().
uint64_t llvm::StructLayout::getSizeInBytes () const [inline]
Definition at line 479 of file DataLayout.h.
Referenced by aliasSameBasePointerGEPs(), computeArraySize(), emitGlobalConstantStruct(), getNaturalGEPRecursively(), getTypePartition(), PerformHeapAllocSRoA(), SymbolicallyEvaluateGEP(), and TryToOptimizeStoreOfMallocToGlobal().
Friends And Related Function Documentation
friend class DataLayout [friend]
Definition at line 499 of file DataLayout.h.
The documentation for this class was generated from the following files:
DataLayout.h
DataLayout.cpp