LLVM: llvm::StoreInst Class Reference
llvm::StoreInst Class Reference
StoreInst - an instruction for storing to memory.
#include <Instructions.h>
Public Member Functions
void * operator new (size_t s)
Allocate a User with an operand pointer co-allocated.
StoreInst (Value *Val, Value *Ptr, Instruction *InsertBefore)
StoreInst (Value *Val, Value *Ptr, BasicBlock *InsertAtEnd)
StoreInst (Value *Val, Value *Ptr, bool isVolatile=false, Instruction *InsertBefore=nullptr)
StoreInst (Value *Val, Value *Ptr, bool isVolatile, BasicBlock *InsertAtEnd)
StoreInst (Value *Val, Value *Ptr, bool isVolatile, unsigned Align, Instruction *InsertBefore=nullptr)
StoreInst (Value *Val, Value *Ptr, bool isVolatile, unsigned Align, BasicBlock *InsertAtEnd)
StoreInst (Value *Val, Value *Ptr, bool isVolatile, unsigned Align, AtomicOrdering Order, SynchronizationScope SynchScope=CrossThread, Instruction *InsertBefore=nullptr)
StoreInst (Value *Val, Value *Ptr, bool isVolatile, unsigned Align, AtomicOrdering Order, SynchronizationScope SynchScope, BasicBlock *InsertAtEnd)
bool isVolatile () const
isVolatile - Return true if this is a store to a volatile memory location.
void setVolatile (bool V)
setVolatile - Specify whether this is a volatile store or not.
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
unsigned getAlignment () const
getAlignment - Return the alignment of the access that is being performed
void setAlignment (unsigned Align)
AtomicOrdering getOrdering () const
Returns the ordering effect of this store.
void setOrdering (AtomicOrdering Ordering)
Set the ordering constraint on this store.
SynchronizationScope getSynchScope () const
void setSynchScope (SynchronizationScope xthread)
Specify whether this store instruction is ordered with respect to all concurrently executing threads, or only with respect to signal handlers executing in the same thread.
void setAtomic (AtomicOrdering Ordering, SynchronizationScope SynchScope=CrossThread)
bool isSimple () const
bool isUnordered () const
Value * getValueOperand ()
const Value * getValueOperand () const
Value * getPointerOperand ()
const Value * getPointerOperand () const
unsigned getPointerAddressSpace () const
Returns the address space of the pointer operand.
Static Public Member Functions
static unsigned getPointerOperandIndex ()
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
StoreInst * clone_impl () const override
Detailed Description
StoreInst - an instruction for storing to memory.
Definition at line 309 of file Instructions.h.
Constructor & Destructor Documentation
StoreInst::StoreInst (Value * Val, Value * Ptr, Instruction * InsertBefore)
Definition at line 1002 of file Instructions.cpp.
Referenced by clone_impl().
StoreInst::StoreInst (Value * Val, Value * Ptr, BasicBlock * InsertAtEnd)
Definition at line 1005 of file Instructions.cpp.
StoreInst::StoreInst (Value * Val, Value * Ptr, bool isVolatile = false, Instruction * InsertBefore = nullptr)
Definition at line 1008 of file Instructions.cpp.
StoreInst::StoreInst (Value * Val, Value * Ptr, bool isVolatile, BasicBlock * InsertAtEnd)
Definition at line 1012 of file Instructions.cpp.
StoreInst::StoreInst (Value * Val, Value * Ptr, bool isVolatile, unsigned Align, Instruction * InsertBefore = nullptr)
Definition at line 1016 of file Instructions.cpp.
StoreInst::StoreInst (Value * Val, Value * Ptr, bool isVolatile, unsigned Align, BasicBlock * InsertAtEnd)
Definition at line 1021 of file Instructions.cpp.
StoreInst::StoreInst (Value * Val, Value * Ptr, bool isVolatile, unsigned Align, AtomicOrdering Order, SynchronizationScope SynchScope = CrossThread, Instruction * InsertBefore = nullptr)
Definition at line 1026 of file Instructions.cpp.
References setAlignment(), setAtomic(), and setVolatile().
StoreInst::StoreInst (Value * Val, Value * Ptr, bool isVolatile, unsigned Align, AtomicOrdering Order, SynchronizationScope SynchScope, BasicBlock * InsertAtEnd)
Definition at line 1042 of file Instructions.cpp.
References setAlignment(), setAtomic(), and setVolatile().
Member Function Documentation
static bool llvm::StoreInst::classof (const Instruction * I) [inline, static]
Definition at line 409 of file Instructions.h.
References llvm::Instruction::getOpcode(), and llvm::SPII::Store.
Referenced by classof().
static bool llvm::StoreInst::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::Instruction.
Definition at line 412 of file Instructions.h.
References classof().
StoreInst * StoreInst::clone_impl () const [override, protected, virtual]
Implements llvm::Instruction.
Definition at line 3493 of file Instructions.cpp.
References getAlignment(), llvm::User::getOperand(), getOrdering(), getSynchScope(), isVolatile(), and StoreInst().
llvm::StoreInst::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
unsigned llvm::StoreInst::getAlignment () const [inline]
getAlignment - Return the alignment of the access that is being performed
Definition at line 355 of file Instructions.h.
References llvm::Instruction::getSubclassDataFromInstruction().
Referenced by clone_impl(), combineStoreToNewValue(), getAdjustedAlignment(), setAlignment(), and llvm::InstCombiner::visitStoreInst().
AtomicOrdering llvm::StoreInst::getOrdering () const [inline]
Returns the ordering effect of this store.
Definition at line 362 of file Instructions.h.
References llvm::Instruction::getSubclassDataFromInstruction().
Referenced by llvm::AliasSetTracker::add(), clone_impl(), and isUnordered().
unsigned llvm::StoreInst::getPointerAddressSpace () const [inline]
Returns the address space of the pointer operand.
Definition at line 404 of file Instructions.h.
References llvm::Type::getPointerAddressSpace(), getPointerOperand(), and llvm::Value::getType().
Referenced by combineStoreToNewValue(), and llvm::InstCombiner::visitStoreInst().
Value* llvm::StoreInst::getPointerOperand () [inline]
Definition at line 399 of file Instructions.h.
References llvm::User::getOperand().
Referenced by llvm::MemoryDepChecker::addAccess(), AnalyzeLoadFromClobberingStore(), combineStoreToNewValue(), findSafeStoreForStoreStrongContraction(), llvm::MemoryLocation::get(), getPointerAddressSpace(), isAllocSiteRemovable(), isSafeToSpeculateStore(), and llvm::Interpreter::visitStoreInst().
const Value* llvm::StoreInst::getPointerOperand () const [inline]
Definition at line 400 of file Instructions.h.
References llvm::User::getOperand().
static unsigned llvm::StoreInst::getPointerOperandIndex () [inline, static]
Definition at line 401 of file Instructions.h.
SynchronizationScope llvm::StoreInst::getSynchScope () const [inline]
Definition at line 373 of file Instructions.h.
References llvm::Instruction::getSubclassDataFromInstruction().
Referenced by clone_impl().
Value* llvm::StoreInst::getValueOperand () [inline]
Definition at line 396 of file Instructions.h.
References llvm::User::getOperand().
Referenced by AnalyzeLoadFromClobberingStore(), combineStoreToValueType(), findCommonType(), llvm::MemoryLocation::get(), getAdjustedAlignment(), isIntegerWideningViableForSlice(), isSafeToSpeculateStore(), isVectorPromotionViable(), isVectorPromotionViableForSlice(), llvm::AArch64TargetLowering::shouldExpandAtomicStoreInIR(), llvm::ARMTargetLowering::shouldExpandAtomicStoreInIR(), SpeculativelyExecuteBB(), unpackStoreToAggregate(), and llvm::PtrUseVisitor< SliceBuilder >::visitStoreInst().
const Value* llvm::StoreInst::getValueOperand () const [inline]
Definition at line 397 of file Instructions.h.
References llvm::User::getOperand().
bool llvm::StoreInst::isSimple () const [inline]
Definition at line 391 of file Instructions.h.
References llvm::Instruction::isAtomic(), and isVolatile().
Referenced by combineStoreToValueType(), findSafeStoreForStoreStrongContraction(), isSafeToSpeculateStore(), unpackStoreToAggregate(), and llvm::InstCombiner::visitStoreInst().
bool llvm::StoreInst::isUnordered () const [inline]
Definition at line 392 of file Instructions.h.
References getOrdering(), isVolatile(), and llvm::Unordered.
Referenced by llvm::AliasAnalysis::getModRefInfo().
bool llvm::StoreInst::isVolatile () const [inline]
isVolatile - Return true if this is a store to a volatile memory location.
Definition at line 341 of file Instructions.h.
References llvm::Instruction::getSubclassDataFromInstruction().
Referenced by llvm::AliasSetTracker::add(), AddressIsTaken(), clone_impl(), isAllocSiteRemovable(), isIntegerWideningViableForSlice(), isSimple(), isUnordered(), isVectorPromotionViableForSlice(), and llvm::Interpreter::visitStoreInst().
void* llvm::StoreInst::operator new (size_t Size) [inline]
Allocate a User with an operand pointer co-allocated.
This is used for subclasses which need to allocate a variable number of operands, ie, 'hung off uses'.
Reimplemented from llvm::User.
Definition at line 316 of file Instructions.h.
References llvm::User::operator new().
void StoreInst::setAlignment (unsigned Align)
Definition at line 1058 of file Instructions.cpp.
References getAlignment(), llvm::Instruction::getSubclassDataFromInstruction(), llvm::Log2_32(), and llvm::Value::MaximumAlignment.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateAlignedStore(), StoreInst(), llvm::UpgradeIntrinsicCall(), and llvm::InstCombiner::visitStoreInst().
void llvm::StoreInst::setAtomic (AtomicOrdering Ordering, SynchronizationScope SynchScope = CrossThread) [inline]
Definition at line 385 of file Instructions.h.
References setOrdering(), and setSynchScope().
Referenced by LowerStoreInst(), and StoreInst().
void llvm::StoreInst::setOrdering (AtomicOrdering Ordering) [inline]
Set the ordering constraint on this store.
May not be Acquire or AcquireRelease.
Definition at line 368 of file Instructions.h.
References llvm::Instruction::getSubclassDataFromInstruction().
Referenced by setAtomic().
void llvm::StoreInst::setSynchScope (SynchronizationScope xthread) [inline]
Specify whether this store instruction is ordered with respect to all concurrently executing threads, or only with respect to signal handlers executing in the same thread.
Definition at line 380 of file Instructions.h.
References llvm::Instruction::getSubclassDataFromInstruction().
Referenced by setAtomic().
void llvm::StoreInst::setVolatile (bool V) [inline]
setVolatile - Specify whether this is a volatile store or not.
Definition at line 345 of file Instructions.h.
References llvm::Instruction::getSubclassDataFromInstruction().
Referenced by StoreInst().
The documentation for this class was generated from the following files:
Instructions.h
Instructions.cpp