LLVM: llvm::IndexedMap< T, ToIndexT > Class Template Reference
llvm::IndexedMap< T, ToIndexT > Class Template Reference
#include <IndexedMap.h>
Public Member Functions
IndexedMap ()
IndexedMap (const T &val)
StorageT::reference operator[] (IndexT n)
StorageT::const_reference operator[] (IndexT n) const
void reserve (typename StorageT::size_type s)
void resize (typename StorageT::size_type s)
void clear ()
void grow (IndexT n)
bool inBounds (IndexT n) const
StorageT::size_type size () const
Detailed Description
template<typename T, typename ToIndexT = llvm::identity<unsigned>>
class llvm::IndexedMap< T, ToIndexT >
Definition at line 31 of file IndexedMap.h.
Constructor & Destructor Documentation
template<typename T, typename ToIndexT = llvm::identity<unsigned>> llvm::IndexedMap< T, ToIndexT >::IndexedMap () [inline]
Definition at line 42 of file IndexedMap.h.
template<typename T, typename ToIndexT = llvm::identity<unsigned>> llvm::IndexedMap< T, ToIndexT >::IndexedMap (const T & val) [inline, explicit]
Definition at line 44 of file IndexedMap.h.
Member Function Documentation
template<typename T, typename ToIndexT = llvm::identity<unsigned>> void llvm::IndexedMap< T, ToIndexT >::clear () [inline]
Definition at line 64 of file IndexedMap.h.
Referenced by llvm::FunctionLoweringInfo::clear(), llvm::VirtRegMap::clearAllVirt(), llvm::MachineRegisterInfo::clearVirtRegs(), llvm::LiveIntervals::releaseMemory(), and llvm::LiveVariables::releaseMemory().
template<typename T, typename ToIndexT = llvm::identity<unsigned>> void llvm::IndexedMap< T, ToIndexT >::grow (IndexT n) [inline]
Definition at line 68 of file IndexedMap.h.
Referenced by llvm::FunctionLoweringInfo::AddLiveOutRegInfo(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), llvm::LiveIntervals::createEmptyInterval(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::LiveVariables::getVarInfo(), llvm::FunctionLoweringInfo::InvalidatePHILiveOutRegInfo(), and llvm::SystemZFrameLowering::SystemZFrameLowering().
template<typename T, typename ToIndexT = llvm::identity<unsigned>> bool llvm::IndexedMap< T, ToIndexT >::inBounds (IndexT n) const [inline]
Definition at line 74 of file IndexedMap.h.
Referenced by llvm::FunctionLoweringInfo::GetLiveOutRegInfo(), and llvm::LiveIntervals::hasInterval().
template<typename T, typename ToIndexT = llvm::identity<unsigned>> StorageT::reference llvm::IndexedMap< T, ToIndexT >::operator[] (IndexT n) [inline]
Definition at line 46 of file IndexedMap.h.
template<typename T, typename ToIndexT = llvm::identity<unsigned>> StorageT::const_reference llvm::IndexedMap< T, ToIndexT >::operator[] (IndexT n) const [inline]
Definition at line 51 of file IndexedMap.h.
template<typename T, typename ToIndexT = llvm::identity<unsigned>> void llvm::IndexedMap< T, ToIndexT >::reserve (typename StorageT::size_type s) [inline]
Definition at line 56 of file IndexedMap.h.
Referenced by llvm::MachineRegisterInfo::MachineRegisterInfo().
template<typename T, typename ToIndexT = llvm::identity<unsigned>> void llvm::IndexedMap< T, ToIndexT >::resize (typename StorageT::size_type s) [inline]
Definition at line 60 of file IndexedMap.h.
Referenced by llvm::IndexedMap< unsigned >::grow(), llvm::VirtRegMap::grow(), and llvm::LiveIntervals::runOnMachineFunction().
template<typename T, typename ToIndexT = llvm::identity<unsigned>> StorageT::size_type llvm::IndexedMap< T, ToIndexT >::size () const [inline]
Definition at line 78 of file IndexedMap.h.
Referenced by llvm::MachineRegisterInfo::getNumVirtRegs(), llvm::LiveIntervals::releaseMemory(), and llvm::LiveVariables::runOnMachineFunction().
The documentation for this class was generated from the following file:
IndexedMap.h