LLVM: llvm::MCFragment Class Reference
llvm::MCFragment Class Reference
#include <MCAssembler.h>
Public Types
enum FragmentType {
FT_Align, FT_Data, FT_CompactEncodedInst, FT_Fill,
FT_Relaxable, FT_Org, FT_Dwarf, FT_DwarfFrame,
FT_LEB, FT_SafeSEH
}
Public Member Functions
void destroy ()
Destroys the current fragment.
FragmentType getKind () const
MCSection * getParent () const
void setParent (MCSection *Value)
const MCSymbol * getAtom () const
void setAtom (const MCSymbol *Value)
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
bool hasInstructions () const
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
bool alignToBundleEnd () const
Should this fragment be placed at the end of an aligned bundle?
void setAlignToBundleEnd (bool V)
uint8_t getBundlePadding () const
Get the padding size that must be inserted before this fragment.
void setBundlePadding (uint8_t N)
Set the padding size for this fragment.
void dump ()
Protected Member Functions
MCFragment (FragmentType Kind, bool HasInstructions, uint8_t BundlePadding, MCSection *Parent=nullptr)
~MCFragment ()
Protected Attributes
bool HasInstructions
Friends
class MCAsmLayout
struct ilist_sentinel_traits< MCFragment >
Detailed Description
Definition at line 45 of file MCAssembler.h.
Member Enumeration Documentation
enum llvm::MCFragment::FragmentType
Enumerator:
FT_Align
FT_Data
FT_CompactEncodedInst
FT_Fill
FT_Relaxable
FT_Org
FT_Dwarf
FT_DwarfFrame
FT_LEB
FT_SafeSEH
Definition at line 52 of file MCAssembler.h.
Constructor & Destructor Documentation
MCFragment::MCFragment (FragmentType Kind, bool HasInstructions, uint8_t BundlePadding, MCSection * Parent = nullptr) [protected]
Definition at line 275 of file MCAssembler.cpp.
References llvm::MCSection::getFragmentList(), and llvm::iplist< NodeTy, Traits >::push_back().
MCFragment::~MCFragment () [protected]
Definition at line 273 of file MCAssembler.cpp.
Member Function Documentation
bool llvm::MCFragment::alignToBundleEnd () const [inline]
Should this fragment be placed at the end of an aligned bundle?
Definition at line 132 of file MCAssembler.h.
Referenced by llvm::computeBundlePadding(), and llvm::MCAssembler::writeFragmentPadding().
void MCFragment::destroy ()
Destroys the current fragment.
This must be used instead of delete as MCFragment is non-virtual. This method will dispatch to the appropriate subclass.
Definition at line 284 of file MCAssembler.cpp.
References FT_Align, FT_CompactEncodedInst, FT_Data, FT_Dwarf, FT_DwarfFrame, FT_Fill, FT_LEB, FT_Org, FT_Relaxable, and FT_SafeSEH.
void MCFragment::dump ()
Definition at line 1125 of file MCAssembler.cpp.
References llvm::MCInst::dump_pretty(), llvm::errs(), llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::fixup_begin(), llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::fixup_end(), FT_Align, FT_CompactEncodedInst, FT_Data, FT_Dwarf, FT_DwarfFrame, FT_Fill, FT_LEB, FT_Org, FT_Relaxable, FT_SafeSEH, llvm::MCDwarfLineAddrFragment::getAddrDelta(), llvm::MCDwarfCallFrameFragment::getAddrDelta(), llvm::MCAlignFragment::getAlignment(), getBundlePadding(), llvm::MCEncodedFragmentWithContents< ContentsSize >::getContents(), llvm::MCRelaxableFragment::getInst(), getKind(), llvm::MCDwarfLineAddrFragment::getLineDelta(), llvm::MCAlignFragment::getMaxBytesToEmit(), llvm::MCOrgFragment::getOffset(), llvm::MCFillFragment::getSize(), llvm::MCSafeSEHFragment::getSymbol(), llvm::MCAlignFragment::getValue(), llvm::MCFillFragment::getValue(), llvm::MCOrgFragment::getValue(), llvm::MCLEBFragment::getValue(), llvm::MCAlignFragment::getValueSize(), llvm::MCFillFragment::getValueSize(), llvm::MCAlignFragment::hasEmitNops(), hasInstructions(), llvm::hexdigit(), llvm::MCLEBFragment::isSigned(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
const MCSymbol* llvm::MCFragment::getAtom () const [inline]
Definition at line 121 of file MCAssembler.h.
Referenced by llvm::MCAssembler::getAtom(), and llvm::MachObjectWriter::isSymbolRefDifferenceFullyResolvedImpl().
uint8_t llvm::MCFragment::getBundlePadding () const [inline]
Get the padding size that must be inserted before this fragment.
Used for bundling. By default, no padding is inserted. Note that padding size is restricted to 8 bits. This is an optimization to reduce the amount of space used for each fragment. In practice, larger padding should never be required.
Definition at line 140 of file MCAssembler.h.
Referenced by dump(), and llvm::MCAssembler::writeFragmentPadding().
FragmentType llvm::MCFragment::getKind () const [inline]
Definition at line 116 of file MCAssembler.h.
References Kind.
Referenced by llvm::MCEncodedFragment::classof(), llvm::MCEncodedFragmentWithFixups< 8, 1 >::classof(), llvm::MCDataFragment::classof(), llvm::MCCompactEncodedInstFragment::classof(), llvm::MCRelaxableFragment::classof(), llvm::MCAlignFragment::classof(), llvm::MCFillFragment::classof(), llvm::MCOrgFragment::classof(), llvm::MCLEBFragment::classof(), llvm::MCDwarfLineAddrFragment::classof(), llvm::MCDwarfCallFrameFragment::classof(), llvm::MCSafeSEHFragment::classof(), llvm::MCAssembler::computeFragmentSize(), dump(), and writeFragment().
unsigned llvm::MCFragment::getLayoutOrder () const [inline]
Definition at line 124 of file MCAssembler.h.
MCSection* llvm::MCFragment::getParent () const [inline]
Definition at line 118 of file MCAssembler.h.
Referenced by llvm::MCAssembler::getAtom(), llvm::MachObjectWriter::getFragmentAddress(), llvm::MachObjectWriter::getSymbolAddress(), llvm::MCAsmLayout::invalidateFragmentsFrom(), llvm::MCObjectWriter::isSymbolRefDifferenceFullyResolvedImpl(), llvm::MachObjectWriter::isSymbolRefDifferenceFullyResolvedImpl(), and llvm::MCAsmLayout::layoutFragment().
bool llvm::MCFragment::hasInstructions () const [inline]
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
Definition at line 129 of file MCAssembler.h.
References HasInstructions.
Referenced by dump(), llvm::MCObjectStreamer::getOrCreateDataFragment(), llvm::MCAsmLayout::layoutFragment(), and llvm::MCAssembler::writeFragmentPadding().
void llvm::MCFragment::setAlignToBundleEnd (bool V) [inline]
Definition at line 133 of file MCAssembler.h.
Referenced by llvm::MCELFStreamer::EmitBundleUnlock().
void llvm::MCFragment::setAtom (const MCSymbol * Value) [inline]
Definition at line 122 of file MCAssembler.h.
void llvm::MCFragment::setBundlePadding (uint8_t N) [inline]
Set the padding size for this fragment.
By default it's a no-op, and only some fragments have a meaningful implementation.
Definition at line 144 of file MCAssembler.h.
Referenced by llvm::MCAsmLayout::layoutFragment().
void llvm::MCFragment::setLayoutOrder (unsigned Value) [inline]
Definition at line 125 of file MCAssembler.h.
void llvm::MCFragment::setParent (MCSection * Value) [inline]
Definition at line 119 of file MCAssembler.h.
Referenced by llvm::MCObjectStreamer::flushPendingLabels(), llvm::MCSection::getSubsectionInsertionPoint(), and llvm::MCObjectStreamer::insert().
Friends And Related Function Documentation
friend struct ilist_sentinel_traits< MCFragment > [friend]
Definition at line 106 of file MCAssembler.h.
friend class MCAsmLayout [friend]
Definition at line 46 of file MCAssembler.h.
Member Data Documentation
bool llvm::MCFragment::HasInstructions [protected]
Definition at line 69 of file MCAssembler.h.
Referenced by hasInstructions(), and llvm::MCDataFragment::setHasInstructions().
The documentation for this class was generated from the following files:
MCAssembler.h
MCAssembler.cpp