LLVM: llvm::FileOutputBuffer Class Reference
llvm::FileOutputBuffer Class Reference
FileOutputBuffer - This interface provides simple way to create an in-memory buffer which will be written to a file.
#include <FileOutputBuffer.h>
Public Types
enum { F_executable = 1 }
Public Member Functions
uint8_t * getBufferStart ()
Returns a pointer to the start of the buffer.
uint8_t * getBufferEnd ()
Returns a pointer to the end of the buffer.
size_t getBufferSize () const
Returns size of the buffer.
StringRef getPath () const
Returns path where file will show up if buffer is committed.
std::error_code commit ()
Flushes the content of the buffer to its file and deallocates the buffer.
~FileOutputBuffer ()
If this object was previously committed, the destructor just deletes this object.
Static Public Member Functions
static std::error_code create (StringRef FilePath, size_t Size, std::unique_ptr< FileOutputBuffer > &Result, unsigned Flags=0)
Factory method to create an OutputBuffer object which manages a read/write buffer of the specified size.
Detailed Description
FileOutputBuffer - This interface provides simple way to create an in-memory buffer which will be written to a file.
During the lifetime of these objects, the content or existence of the specified file is undefined. That is, creating an OutputBuffer for a file may immediately remove the file. If the FileOutputBuffer is committed, the target file's content will become the buffer content at the time of the commit. If the FileOutputBuffer is not committed, the file will be deleted in the FileOutputBuffer destructor.
Definition at line 30 of file FileOutputBuffer.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
F_executable
Definition at line 33 of file FileOutputBuffer.h.
Constructor & Destructor Documentation
llvm::FileOutputBuffer::~FileOutputBuffer ()
If this object was previously committed, the destructor just deletes this object.
If this object was not committed, the destructor deallocates the buffer and the target file is never written.
Definition at line 33 of file FileOutputBuffer.cpp.
References llvm::sys::fs::remove().
Member Function Documentation
std::error_code llvm::FileOutputBuffer::commit ()
Flushes the content of the buffer to its file and deallocates the buffer.
If commit() is not called before this object's destructor is called, the file is deleted in the destructor. The optional parameter is used if it turns out you want the file size to be smaller than initially requested.
Definition at line 104 of file FileOutputBuffer.cpp.
References llvm::sys::fs::rename().
std::error_code llvm::FileOutputBuffer::create (StringRef FilePath, size_t Size, std::unique_ptr< FileOutputBuffer > & Result, unsigned Flags = 0) [static]
Factory method to create an OutputBuffer object which manages a read/write buffer of the specified size.
When committed, the buffer will be written to the file at the specified path.
Definition at line 38 of file FileOutputBuffer.cpp.
References llvm::sys::fs::all_exe, llvm::sys::fs::all_read, llvm::sys::fs::all_write, llvm::sys::fs::createUniqueFile(), F_executable, llvm::sys::fs::file_not_found, llvm::make_error_code(), llvm::operation_not_permitted, llvm::sys::fs::regular_file, llvm::sys::fs::remove(), llvm::sys::fs::resize_file(), llvm::MipsISD::Ret, llvm::sys::fs::status(), and llvm::sys::fs::file_status::type().
uint8_t* llvm::FileOutputBuffer::getBufferEnd () [inline]
Returns a pointer to the end of the buffer.
Definition at line 50 of file FileOutputBuffer.h.
size_t llvm::FileOutputBuffer::getBufferSize () const [inline]
Returns size of the buffer.
Definition at line 55 of file FileOutputBuffer.h.
uint8_t* llvm::FileOutputBuffer::getBufferStart () [inline]
Returns a pointer to the start of the buffer.
Definition at line 45 of file FileOutputBuffer.h.
StringRef llvm::FileOutputBuffer::getPath () const [inline]
Returns path where file will show up if buffer is committed.
Definition at line 60 of file FileOutputBuffer.h.
The documentation for this class was generated from the following files:
FileOutputBuffer.h
FileOutputBuffer.cpp