LLVM: llvm::LibCallInfo Class Reference
llvm::LibCallInfo Class Reference
LibCallInfo - Abstract interface to query about library call information.
#include <LibCallSemantics.h>
Public Member Functions
LibCallInfo ()
virtual ~LibCallInfo ()
const LibCallLocationInfo & getLocationInfo (unsigned LocID) const
getLocationInfo - Return information about the specified LocationID.
const LibCallFunctionInfo * getFunctionInfo (const Function *F) const
getFunctionInfo - Return the LibCallFunctionInfo object corresponding to the specified function if we have it.
virtual unsigned getLocationInfo (const LibCallLocationInfo *&Array) const
getLocationInfo - Return descriptors for the locations referenced by this set of libcalls.
virtual const LibCallFunctionInfo * getFunctionInfoArray () const =0
getFunctionInfoArray - Return an array of descriptors that describe the set of libcalls represented by this LibCallInfo object.
Detailed Description
LibCallInfo - Abstract interface to query about library call information.
Instances of this class return known information about some set of libcalls.
Definition at line 127 of file LibCallSemantics.h.
Constructor & Destructor Documentation
llvm::LibCallInfo::LibCallInfo () [inline]
Definition at line 133 of file LibCallSemantics.h.
LibCallInfo::~LibCallInfo () [virtual]
Definition at line 28 of file LibCallSemantics.cpp.
References getMap().
Member Function Documentation
const LibCallFunctionInfo * LibCallInfo::getFunctionInfo (const Function * F) const
getFunctionInfo - Return the LibCallFunctionInfo object corresponding to the specified function if we have it.
Return the LibCallFunctionInfo object corresponding to the specified function if we have it.
If not, return null.
If this is the first time we are querying for this info, lazily construct the StringMap to index it.
Definition at line 45 of file LibCallSemantics.cpp.
References getFunctionInfoArray(), getMap(), llvm::Value::getName(), and llvm::StringMap< ValueTy, AllocatorTy >::lookup().
Referenced by llvm::LibCallAliasAnalysis::getModRefInfo().
virtual const LibCallFunctionInfo* llvm::LibCallInfo::getFunctionInfoArray () const [pure virtual]
getFunctionInfoArray - Return an array of descriptors that describe the set of libcalls represented by this LibCallInfo object.
This array is terminated by an entry with a NULL name.
Referenced by getFunctionInfo().
const LibCallLocationInfo & LibCallInfo::getLocationInfo (unsigned LocID) const
getLocationInfo - Return information about the specified LocationID.
Definition at line 32 of file LibCallSemantics.cpp.
virtual unsigned llvm::LibCallInfo::getLocationInfo (const LibCallLocationInfo *& Array) const [inline, virtual]
getLocationInfo - Return descriptors for the locations referenced by this set of libcalls.
Definition at line 155 of file LibCallSemantics.h.
The documentation for this class was generated from the following files:
LibCallSemantics.h
LibCallSemantics.cpp