LLVM: llvm::MCSymbolCOFF Class Reference
llvm::MCSymbolCOFF Class Reference
#include <MCSymbolCOFF.h>
Public Member Functions
MCSymbolCOFF (const StringMapEntry< bool > *Name, bool isTemporary)
uint16_t getType () const
void setType (uint16_t Ty) const
uint16_t getClass () const
void setClass (uint16_t StorageClass) const
bool isWeakExternal () const
void setIsWeakExternal () const
bool isSafeSEH () const
void setIsSafeSEH () const
Static Public Member Functions
static bool classof (const MCSymbol *S)
Detailed Description
Definition at line 15 of file MCSymbolCOFF.h.
Constructor & Destructor Documentation
llvm::MCSymbolCOFF::MCSymbolCOFF (const StringMapEntry< bool > * Name, bool isTemporary) [inline]
Definition at line 29 of file MCSymbolCOFF.h.
Member Function Documentation
static bool llvm::MCSymbolCOFF::classof (const MCSymbol * S) [inline, static]
Definition at line 60 of file MCSymbolCOFF.h.
References llvm::MCSymbol::isCOFF().
uint16_t llvm::MCSymbolCOFF::getClass () const [inline]
Definition at line 39 of file MCSymbolCOFF.h.
References llvm::MCSymbol::getFlags().
uint16_t llvm::MCSymbolCOFF::getType () const [inline]
Definition at line 32 of file MCSymbolCOFF.h.
bool llvm::MCSymbolCOFF::isSafeSEH () const [inline]
Definition at line 53 of file MCSymbolCOFF.h.
References llvm::MCSymbol::getFlags().
Referenced by llvm::MCWinCOFFStreamer::EmitCOFFSafeSEH().
bool llvm::MCSymbolCOFF::isWeakExternal () const [inline]
Definition at line 46 of file MCSymbolCOFF.h.
References llvm::MCSymbol::getFlags().
void llvm::MCSymbolCOFF::setClass (uint16_t StorageClass) const [inline]
Definition at line 42 of file MCSymbolCOFF.h.
References llvm::MCSymbol::modifyFlags().
void llvm::MCSymbolCOFF::setIsSafeSEH () const [inline]
Definition at line 56 of file MCSymbolCOFF.h.
References llvm::MCSymbol::modifyFlags().
Referenced by llvm::MCWinCOFFStreamer::EmitCOFFSafeSEH().
void llvm::MCSymbolCOFF::setIsWeakExternal () const [inline]
Definition at line 49 of file MCSymbolCOFF.h.
References llvm::MCSymbol::modifyFlags().
void llvm::MCSymbolCOFF::setType (uint16_t Ty) const [inline]
Definition at line 35 of file MCSymbolCOFF.h.
Referenced by llvm::MCWinCOFFStreamer::EmitCOFFSafeSEH().
The documentation for this class was generated from the following file:
MCSymbolCOFF.h