LLVM: llvm::SDNode::use_iterator Class Reference
llvm::SDNode::use_iterator Class Reference
This class provides iterator support for SDUse operands that use a specific SDNode.
#include <SelectionDAGNodes.h>
Public Types
typedef std::iterator
< std::forward_iterator_tag,
SDUse, ptrdiff_t >::reference reference
typedef std::iterator
< std::forward_iterator_tag,
SDUse, ptrdiff_t >::pointer pointer
Public Member Functions
use_iterator (const use_iterator &I)
use_iterator ()
bool operator== (const use_iterator &x) const
bool operator!= (const use_iterator &x) const
bool atEnd () const
Return true if this iterator is at the end of uses list.
use_iterator & operator++ ()
use_iterator operator++ (int)
SDNode * operator* () const
Retrieve a pointer to the current user node.
SDNode * operator-> () const
SDUse & getUse () const
unsigned getOperandNo () const
Retrieve the operand # of this use in its user.
Friends
class SDNode
Detailed Description
This class provides iterator support for SDUse operands that use a specific SDNode.
Definition at line 459 of file SelectionDAGNodes.h.
Member Typedef Documentation
typedef std::iterator<std::forward_iterator_tag, SDUse, ptrdiff_t>::pointer llvm::SDNode::use_iterator::pointer
Definition at line 469 of file SelectionDAGNodes.h.
typedef std::iterator<std::forward_iterator_tag, SDUse, ptrdiff_t>::reference llvm::SDNode::use_iterator::reference
Definition at line 467 of file SelectionDAGNodes.h.
Constructor & Destructor Documentation
llvm::SDNode::use_iterator::use_iterator (const use_iterator & I) [inline]
Definition at line 471 of file SelectionDAGNodes.h.
llvm::SDNode::use_iterator::use_iterator () [inline]
Definition at line 472 of file SelectionDAGNodes.h.
Member Function Documentation
bool llvm::SDNode::use_iterator::atEnd () const [inline]
Return true if this iterator is at the end of uses list.
Definition at line 482 of file SelectionDAGNodes.h.
Referenced by usesAllNormalStores().
unsigned llvm::SDNode::use_iterator::getOperandNo () const [inline]
Retrieve the operand # of this use in its user.
Definition at line 506 of file SelectionDAGNodes.h.
References llvm::SDUse::getUser().
Referenced by hasNonFlagsUse().
SDUse& llvm::SDNode::use_iterator::getUse () const [inline]
Definition at line 503 of file SelectionDAGNodes.h.
Referenced by llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), and llvm::SelectionDAG::ReplaceAllUsesWith().
bool llvm::SDNode::use_iterator::operator!= (const use_iterator & x) const [inline]
Definition at line 477 of file SelectionDAGNodes.h.
References operator==().
SDNode* llvm::SDNode::use_iterator::operator* () const [inline]
Retrieve a pointer to the current user node.
Definition at line 496 of file SelectionDAGNodes.h.
References llvm::SDUse::getUser().
Referenced by operator->().
use_iterator& llvm::SDNode::use_iterator::operator++ () [inline]
Definition at line 485 of file SelectionDAGNodes.h.
References llvm::SDUse::getNext().
use_iterator llvm::SDNode::use_iterator::operator++ (int) [inline]
Definition at line 491 of file SelectionDAGNodes.h.
SDNode* llvm::SDNode::use_iterator::operator-> () const [inline]
Definition at line 501 of file SelectionDAGNodes.h.
References operator*().
bool llvm::SDNode::use_iterator::operator== (const use_iterator & x) const [inline]
Definition at line 474 of file SelectionDAGNodes.h.
Referenced by operator!=().
Friends And Related Function Documentation
friend class SDNode [friend]
Definition at line 464 of file SelectionDAGNodes.h.
The documentation for this class was generated from the following file:
SelectionDAGNodes.h