LLVM: llvm::raw_svector_ostream Class Reference
llvm::raw_svector_ostream Class Reference
A raw_ostream that writes to an SmallVector or SmallString.
#include <raw_ostream.h>
Public Member Functions
raw_svector_ostream (SmallVectorImpl< char > &O)
Construct a new raw_svector_ostream.
~raw_svector_ostream () override
void resync ()
This is called when the SmallVector we're appending to is changed outside of the raw_svector_ostream's control.
StringRef str ()
Flushes the stream contents to the target vector and return a StringRef for the vector contents.
Protected Member Functions
raw_svector_ostream (SmallVectorImpl< char > &O, unsigned)
void init ()
Detailed Description
A raw_ostream that writes to an SmallVector or SmallString.
This is a simple adaptor class. This class does not encounter output errors.
Definition at line 486 of file raw_ostream.h.
Constructor & Destructor Documentation
raw_svector_ostream::raw_svector_ostream (SmallVectorImpl< char > & O, unsigned) [explicit, protected]
Definition at line 764 of file raw_ostream.cpp.
raw_svector_ostream::raw_svector_ostream (SmallVectorImpl< char > & O) [explicit]
Construct a new raw_svector_ostream.
Parameters:
O The vector to write to; this should generally have at least 128 bytes free to avoid any extraneous memory overhead.
Definition at line 767 of file raw_ostream.cpp.
References init().
raw_svector_ostream::~raw_svector_ostream () [override]
Definition at line 780 of file raw_ostream.cpp.
References llvm::raw_ostream::flush().
Member Function Documentation
void raw_svector_ostream::init () [protected]
Definition at line 771 of file raw_ostream.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::capacity(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorImpl< T >::reserve(), llvm::raw_ostream::SetBuffer(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::buffer_ostream::buffer_ostream(), and raw_svector_ostream().
void raw_svector_ostream::resync ()
This is called when the SmallVector we're appending to is changed outside of the raw_svector_ostream's control.
resync - This is called when the SmallVector we're appending to is changed outside of the raw_svector_ostream's control.
It is only safe to do this if the raw_svector_ostream has previously been flushed.
Definition at line 794 of file raw_ostream.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::capacity(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::raw_ostream::GetNumBytesInBuffer(), llvm::SmallVectorImpl< T >::reserve(), llvm::raw_ostream::SetBuffer(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by emitComments(), and llvm::StructType::setName().
StringRef raw_svector_ostream::str ()
Flushes the stream contents to the target vector and return a StringRef for the vector contents.
Definition at line 821 of file raw_ostream.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::raw_ostream::flush(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::ComputeASanStackFrameLayout(), llvm::NVPTXAsmPrinter::doInitialization(), llvm::MCDwarfLineAddr::Emit(), llvm::MCDwarfFrameEmitter::EmitAdvanceLoc(), emitDebugValueComment(), llvm::MCStreamer::EmitSLEB128IntValue(), llvm::MCStreamer::EmitULEB128IntValue(), llvm::opt::Arg::getAsString(), llvm::ExecutionEngine::getConstantValue(), LLVMDisasmInstruction(), LLVMTargetMachineEmitToMemoryBuffer(), llvm::ExecutionEngine::LoadValueFromMemory(), llvm::opt::Arg::render(), llvm::report_fatal_error(), llvm::StructType::setName(), and llvm::buffer_ostream::~buffer_ostream().
The documentation for this class was generated from the following files:
raw_ostream.h
raw_ostream.cpp