LLVM: llvm::DIGlobalVariable Class Reference
llvm::DIGlobalVariable Class Reference
Global variables.
#include <DebugInfoMetadata.h>
Public Member Functions
DEFINE_MDNODE_GET (DIGlobalVariable,(DIScope *Scope, StringRef Name, StringRef LinkageName, DIFile *File, unsigned Line, DITypeRef Type, bool IsLocalToUnit, bool IsDefinition, Constant *Variable, DIDerivedType *StaticDataMemberDeclaration),(Scope, Name, LinkageName, File, Line, Type, IsLocalToUnit, IsDefinition, Variable, StaticDataMemberDeclaration)) DEFINE_MDNODE_GET(DIGlobalVariable
Metadata MDString MDString
Metadata unsigned Metadata
bool bool Metadata Metadata
StaticDataMemberDeclaration
TempDIGlobalVariable clone () const
Create a (temporary) clone of this.
bool isLocalToUnit () const
bool isDefinition () const
StringRef getDisplayName () const
StringRef getLinkageName () const
Constant * getVariable () const
DIDerivedType * getStaticDataMemberDeclaration () const
MDString * getRawLinkageName () const
Metadata * getRawVariable () const
Metadata * getRawStaticDataMemberDeclaration () const
Static Public Member Functions
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
Public Attributes
Metadata * Scope
Metadata MDString * Name
Metadata MDString MDString * LinkageName
Metadata MDString MDString
Metadata * File
Metadata MDString MDString
Metadata unsigned Line
Metadata MDString MDString
Metadata unsigned Metadata * Type
Metadata MDString MDString
Metadata unsigned Metadata
bool IsLocalToUnit
Metadata MDString MDString
Metadata unsigned Metadata
bool bool IsDefinition
Metadata MDString MDString
Metadata unsigned Metadata
bool bool Metadata * Variable
Metadata MDString MDString
Metadata unsigned Metadata
bool bool Metadata Metadata * StaticDataMemberDeclaration
Metadata MDString MDString
Metadata unsigned Metadata
bool bool Metadata Metadata Scope
Metadata MDString MDString
Metadata unsigned Metadata
bool bool Metadata Metadata Name
Metadata MDString MDString
Metadata unsigned Metadata
bool bool Metadata Metadata LinkageName
Metadata MDString MDString
Metadata unsigned Metadata
bool bool Metadata Metadata File
Metadata MDString MDString
Metadata unsigned Metadata
bool bool Metadata Metadata Line
Metadata MDString MDString
Metadata unsigned Metadata
bool bool Metadata Metadata Type
Metadata MDString MDString
Metadata unsigned Metadata
bool bool Metadata Metadata IsLocalToUnit
Metadata MDString MDString
Metadata unsigned Metadata
bool bool Metadata Metadata IsDefinition
Metadata MDString MDString
Metadata unsigned Metadata
bool bool Metadata Metadata Variable
Friends
class LLVMContextImpl
class MDNode
Detailed Description
Global variables.
TODO: Remove DisplayName. It's always equal to Name.
Definition at line 1772 of file DebugInfoMetadata.h.
Member Function Documentation
static bool llvm::DIGlobalVariable::classof (const Metadata * MD) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::DIVariable.
Definition at line 1848 of file DebugInfoMetadata.h.
References llvm::Metadata::DIGlobalVariableKind, and llvm::Metadata::getMetadataID().
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata StaticDataMemberDeclaration TempDIGlobalVariable llvm::DIGlobalVariable::clone () const [inline]
Create a (temporary) clone of this.
Reimplemented from llvm::MDNode.
Definition at line 1829 of file DebugInfoMetadata.h.
llvm::DIGlobalVariable::DEFINE_MDNODE_GET (DIGlobalVariable , (DIScope *Scope, StringRef Name, StringRef LinkageName,DIFile *File, unsigned Line, DITypeRef Type,bool IsLocalToUnit, bool IsDefinition, Constant *Variable,DIDerivedType *StaticDataMemberDeclaration) , (Scope, Name, LinkageName, File, Line, Type, IsLocalToUnit,IsDefinition, Variable, StaticDataMemberDeclaration))
StringRef llvm::DIGlobalVariable::getDisplayName () const [inline]
Definition at line 1833 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
Referenced by llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
StringRef llvm::DIGlobalVariable::getLinkageName () const [inline]
Definition at line 1834 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
Referenced by llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), and llvm::MDNodeKeyImpl< DIGlobalVariable >::isKeyOf().
MDString* llvm::DIGlobalVariable::getRawLinkageName () const [inline]
Definition at line 1844 of file DebugInfoMetadata.h.
Referenced by WriteDIGlobalVariable().
Metadata* llvm::DIGlobalVariable::getRawStaticDataMemberDeclaration () const [inline]
Definition at line 1846 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getStaticDataMemberDeclaration(), and llvm::MDNodeKeyImpl< DIGlobalVariable >::isKeyOf().
Metadata* llvm::DIGlobalVariable::getRawVariable () const [inline]
Definition at line 1845 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getVariable(), llvm::MDNodeKeyImpl< DIGlobalVariable >::isKeyOf(), and WriteDIGlobalVariable().
DIDerivedType* llvm::DIGlobalVariable::getStaticDataMemberDeclaration () const [inline]
Definition at line 1840 of file DebugInfoMetadata.h.
References getRawStaticDataMemberDeclaration().
Referenced by llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), and WriteDIGlobalVariable().
Constant* llvm::DIGlobalVariable::getVariable () const [inline]
Definition at line 1835 of file DebugInfoMetadata.h.
References llvm::C, llvm::dyn_cast(), and getRawVariable().
Referenced by llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
bool llvm::DIGlobalVariable::isDefinition () const [inline]
Definition at line 1832 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), llvm::MDNodeKeyImpl< DIGlobalVariable >::isKeyOf(), and WriteDIGlobalVariable().
bool llvm::DIGlobalVariable::isLocalToUnit () const [inline]
Definition at line 1831 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), llvm::MDNodeKeyImpl< DIGlobalVariable >::isKeyOf(), and WriteDIGlobalVariable().
Friends And Related Function Documentation
friend class LLVMContextImpl [friend]
Reimplemented from llvm::DINode.
Definition at line 1773 of file DebugInfoMetadata.h.
friend class MDNode [friend]
Reimplemented from llvm::DINode.
Definition at line 1774 of file DebugInfoMetadata.h.
Member Data Documentation
Metadata MDString MDString Metadata* llvm::DIGlobalVariable::File
Definition at line 1822 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata llvm::DIGlobalVariable::File
Definition at line 1822 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned Metadata bool bool llvm::DIGlobalVariable::IsDefinition
Definition at line 1822 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata llvm::DIGlobalVariable::IsDefinition
Definition at line 1822 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned Metadata bool llvm::DIGlobalVariable::IsLocalToUnit
Definition at line 1822 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata llvm::DIGlobalVariable::IsLocalToUnit
Definition at line 1822 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned llvm::DIGlobalVariable::Line
Reimplemented from llvm::DIVariable.
Definition at line 1822 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata llvm::DIGlobalVariable::Line
Reimplemented from llvm::DIVariable.
Definition at line 1822 of file DebugInfoMetadata.h.
Metadata MDString MDString* llvm::DIGlobalVariable::LinkageName
Definition at line 1822 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata llvm::DIGlobalVariable::LinkageName
Definition at line 1822 of file DebugInfoMetadata.h.
Metadata MDString* llvm::DIGlobalVariable::Name
Definition at line 1822 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata llvm::DIGlobalVariable::Name
Definition at line 1822 of file DebugInfoMetadata.h.
Metadata* llvm::DIGlobalVariable::Scope
Definition at line 1822 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata llvm::DIGlobalVariable::Scope
Definition at line 1822 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata* llvm::DIGlobalVariable::StaticDataMemberDeclaration
Definition at line 1822 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned Metadata* llvm::DIGlobalVariable::Type
Definition at line 1822 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata llvm::DIGlobalVariable::Type
Definition at line 1822 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata* llvm::DIGlobalVariable::Variable
Definition at line 1822 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata llvm::DIGlobalVariable::Variable
Definition at line 1822 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
DebugInfoMetadata.h
DebugInfoMetadata.cpp