LLVM: llvm::DWARFDebugRangeList Class Reference
llvm::DWARFDebugRangeList Class Reference
#include <DWARFDebugRangeList.h>
Classes
struct RangeListEntry
Public Member Functions
DWARFDebugRangeList ()
void clear ()
void dump (raw_ostream &OS) const
bool extract (DataExtractor data, uint32_t *offset_ptr)
const std::vector
< RangeListEntry > & getEntries ()
DWARFAddressRangesVector getAbsoluteRanges (uint64_t BaseAddress) const
getAbsoluteRanges - Returns absolute address ranges defined by this range list.
Detailed Description
Definition at line 23 of file DWARFDebugRangeList.h.
Constructor & Destructor Documentation
llvm::DWARFDebugRangeList::DWARFDebugRangeList () [inline]
Definition at line 65 of file DWARFDebugRangeList.h.
References clear().
Member Function Documentation
void DWARFDebugRangeList::clear ()
Definition at line 16 of file DWARFDebugRangeList.cpp.
Referenced by DWARFDebugRangeList(), and extract().
void DWARFDebugRangeList::dump (raw_ostream & OS) const
Definition at line 47 of file DWARFDebugRangeList.cpp.
References llvm::format().
Referenced by llvm::DWARFContext::dump().
bool DWARFDebugRangeList::extract (DataExtractor data, uint32_t * offset_ptr)
Definition at line 22 of file DWARFDebugRangeList.cpp.
References clear(), llvm::DWARFDebugRangeList::RangeListEntry::EndAddress, llvm::DataExtractor::getAddress(), llvm::DataExtractor::getAddressSize(), llvm::DWARFDebugRangeList::RangeListEntry::isEndOfListEntry(), llvm::DataExtractor::isValidOffset(), and llvm::DWARFDebugRangeList::RangeListEntry::StartAddress.
Referenced by llvm::DWARFContext::dump(), and llvm::DWARFUnit::extractRangeList().
DWARFAddressRangesVector DWARFDebugRangeList::getAbsoluteRanges (uint64_t BaseAddress) const
getAbsoluteRanges - Returns absolute address ranges defined by this range list.
Has to be passed base address of the compile unit referencing this range list.
Definition at line 58 of file DWARFDebugRangeList.cpp.
Referenced by llvm::DWARFDebugInfoEntryMinimal::getAddressRanges().
const std::vector<RangeListEntry>& llvm::DWARFDebugRangeList::getEntries () [inline]
Definition at line 69 of file DWARFDebugRangeList.h.
The documentation for this class was generated from the following files:
DWARFDebugRangeList.h
DWARFDebugRangeList.cpp