LLVM: llvm::LoadSDNode Class Reference
llvm::LoadSDNode Class Reference
This class is used to represent ISD::LOAD nodes.
#include <SelectionDAGNodes.h>
Public Member Functions
ISD::LoadExtType getExtensionType () const
Return whether this is a plain node, or one of the varieties of value-extending loads.
const SDValue & getBasePtr () const
const SDValue & getOffset () const
Static Public Member Functions
static bool classof (const SDNode *N)
Friends
class SelectionDAG
Detailed Description
This class is used to represent ISD::LOAD nodes.
Definition at line 1926 of file SelectionDAGNodes.h.
Member Function Documentation
static bool llvm::LoadSDNode::classof (const SDNode * N) [inline, static]
Reimplemented from llvm::LSBaseSDNode.
Definition at line 1948 of file SelectionDAGNodes.h.
References llvm::SDNode::getOpcode(), and llvm::ISD::LOAD.
const SDValue& llvm::LoadSDNode::getBasePtr () const [inline]
Reimplemented from llvm::MemSDNode.
Definition at line 1945 of file SelectionDAGNodes.h.
References llvm::SDNode::getOperand().
Referenced by canFoldInAddressingMode(), CheckForMaskedLoad(), createLoadLR(), EltsFromConsecutiveLoads(), ExpandUnalignedLoad(), llvm::PPCTargetLowering::expandVSXLoadForLE(), isLoadIncOrDecStore(), LowerF128Load(), llvm::AMDGPUTargetLowering::LowerLOAD(), llvm::HexagonTargetLowering::LowerLOAD(), llvm::PPCTargetLowering::PerformDAGCombine(), performIntToFpCombine(), PerformLOADCombine(), PerformSTORECombine(), PerformVMOVRRDCombine(), llvm::AMDGPUTargetLowering::ScalarizeVectorLoad(), llvm::TargetLowering::SimplifySetCC(), SkipLoadExtensionForVMULL(), and llvm::AMDGPUTargetLowering::SplitVectorLoad().
ISD::LoadExtType llvm::LoadSDNode::getExtensionType () const [inline]
Return whether this is a plain node, or one of the varieties of value-extending loads.
Definition at line 1941 of file SelectionDAGNodes.h.
References llvm::SDNode::SubclassData.
Referenced by checkValueWidth(), ExpandUnalignedLoad(), llvm::SelectionDAG::getIndexedLoad(), isCalleeLoad(), llvm::ISD::isNormalLoad(), isValidIndexedLoad(), llvm::PPCTargetLowering::isZExtFree(), llvm::AMDGPUTargetLowering::LowerLOAD(), llvm::HexagonTargetLowering::LowerLOAD(), llvm::MipsTargetLowering::lowerLOAD(), PerformLOADCombine(), ReplaceLoadVector(), llvm::AMDGPUTargetLowering::ScalarizeVectorLoad(), llvm::TargetLowering::SimplifySetCC(), SkipLoadExtensionForVMULL(), and llvm::AMDGPUTargetLowering::SplitVectorLoad().
const SDValue& llvm::LoadSDNode::getOffset () const [inline]
Reimplemented from llvm::LSBaseSDNode.
Definition at line 1946 of file SelectionDAGNodes.h.
References llvm::SDNode::getOperand().
Referenced by llvm::SelectionDAG::getIndexedLoad(), isLoadIncOrDecStore(), isValidIndexedLoad(), and LowerF128Load().
Friends And Related Function Documentation
friend class SelectionDAG [friend]
Reimplemented from llvm::SDNode.
Definition at line 1927 of file SelectionDAGNodes.h.
The documentation for this class was generated from the following file:
SelectionDAGNodes.h