LLVM: llvm::RecordVal Class Reference
llvm::RecordVal Class Reference
#include <Record.h>
Public Member Functions
RecordVal (Init *N, RecTy *T, bool P)
RecordVal (const std::string &N, RecTy *T, bool P)
const std::string & getName () const
const Init * getNameInit () const
std::string getNameInitAsString () const
bool getPrefix () const
RecTy * getType () const
Init * getValue () const
bool setValue (Init *V)
void dump () const
void print (raw_ostream &OS, bool PrintSem=true) const
Detailed Description
Definition at line 1110 of file Record.h.
Constructor & Destructor Documentation
RecordVal::RecordVal (Init * N, RecTy * T, bool P)
Definition at line 1530 of file Record.cpp.
References llvm::UnsetInit::convertInitializerTo(), and llvm::UnsetInit::get().
RecordVal::RecordVal (const std::string & N, RecTy * T, bool P)
Definition at line 1536 of file Record.cpp.
References llvm::UnsetInit::convertInitializerTo(), and llvm::UnsetInit::get().
Member Function Documentation
void RecordVal::dump () const
Definition at line 1546 of file Record.cpp.
References llvm::errs().
const std::string & RecordVal::getName () const
Definition at line 1542 of file Record.cpp.
References getNameInit(), and getValue().
const Init* llvm::RecordVal::getNameInit () const [inline]
Definition at line 1120 of file Record.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer().
Referenced by llvm::Record::addValue(), getName(), getNameInitAsString(), and llvm::VarInit::resolveListElementReference().
std::string llvm::RecordVal::getNameInitAsString () const [inline]
Definition at line 1121 of file Record.h.
References llvm::Init::getAsUnquotedString(), and getNameInit().
Referenced by print(), and llvm::Record::resolveReferencesTo().
bool llvm::RecordVal::getPrefix () const [inline]
Definition at line 1125 of file Record.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getInt().
Referenced by print().
RecTy* llvm::RecordVal::getType () const [inline]
Definition at line 1126 of file Record.h.
Referenced by llvm::UnOpInit::Fold(), and print().
Init* llvm::RecordVal::getValue () const [inline]
Definition at line 1127 of file Record.h.
Referenced by llvm::DefInit::getFieldInit(), llvm::VarInit::getFieldType(), getName(), llvm::Record::getValueAsBit(), llvm::Record::getValueAsBitOrUnset(), llvm::Record::getValueAsBitsInit(), llvm::Record::getValueAsDag(), llvm::Record::getValueAsDef(), llvm::Record::getValueAsInt(), llvm::Record::getValueAsListInit(), llvm::Record::getValueAsString(), llvm::Record::getValueInit(), print(), llvm::VarInit::resolveListElementReference(), and llvm::Record::resolveReferencesTo().
void RecordVal::print (raw_ostream & OS, bool PrintSem = true) const
Definition at line 1548 of file Record.cpp.
References getNameInitAsString(), getPrefix(), getType(), and getValue().
Referenced by llvm::operator<<().
bool llvm::RecordVal::setValue (Init * V) [inline]
Definition at line 1129 of file Record.h.
References llvm::Init::convertInitializerTo().
The documentation for this class was generated from the following files:
Record.h
Record.cpp