LLVM: llvm::PrintReg Class Reference
llvm::PrintReg Class Reference
PrintReg - Helper class for printing registers on a raw_ostream.
#include <TargetRegisterInfo.h>
Public Member Functions
PrintReg (unsigned reg, const TargetRegisterInfo *tri=nullptr, unsigned subidx=0)
void print (raw_ostream &) const
Detailed Description
PrintReg - Helper class for printing registers on a raw_ostream.
Prints virtual and physical registers with or without a TRI instance.
The format is: noreg - NoRegister vreg5 - a virtual register. vreg5:sub_8bit - a virtual register with sub-register index (with TRI). EAX - a physical register physreg17 - a physical register when no TRI instance given.
Usage: OS << PrintReg(Reg, TRI) << '
';
Definition at line 946 of file TargetRegisterInfo.h.
Constructor & Destructor Documentation
llvm::PrintReg::PrintReg (unsigned reg, const TargetRegisterInfo * tri = nullptr, unsigned subidx = 0) [inline, explicit]
Definition at line 951 of file TargetRegisterInfo.h.
Member Function Documentation
void PrintReg::print (raw_ostream & OS) const
Definition at line 37 of file TargetRegisterInfo.cpp.
References llvm::MCRegisterInfo::getName(), llvm::TargetRegisterInfo::getSubRegIndexName(), llvm::TargetRegisterInfo::isStackSlot(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::TargetRegisterInfo::stackSlot2Index(), and llvm::TargetRegisterInfo::virtReg2Index().
Referenced by llvm::operator<<().
The documentation for this class was generated from the following files:
TargetRegisterInfo.h
TargetRegisterInfo.cpp