LLVM: llvm::sampleprof::SampleProfileWriterBinary Class Reference
llvm::sampleprof::SampleProfileWriterBinary Class Reference
Sample-based profile writer (binary format).
#include <SampleProfWriter.h>
Public Member Functions
SampleProfileWriterBinary (StringRef F, std::error_code &EC)
bool write (StringRef F, const FunctionSamples &S) override
Write samples to a binary file.
bool write (const Module &M, StringMap< FunctionSamples > &P)
Write all the sample profiles for all the functions in M.
Detailed Description
Sample-based profile writer (binary format).
Definition at line 96 of file SampleProfWriter.h.
Constructor & Destructor Documentation
SampleProfileWriterBinary::SampleProfileWriterBinary (StringRef F, std::error_code & EC)
Definition at line 58 of file SampleProfWriter.cpp.
References llvm::encodeULEB128(), llvm::sampleprof::SampleProfileWriter::OS, llvm::sampleprof::SPMagic(), and llvm::sampleprof::SPVersion().
Member Function Documentation
bool SampleProfileWriterBinary::write (StringRef FName, const FunctionSamples & S) [override, virtual]
Write samples to a binary file.
Returns:
true if the samples were written successfully, false otherwise.
Implements llvm::sampleprof::SampleProfileWriter.
Definition at line 72 of file SampleProfWriter.cpp.
References llvm::sampleprof::LineLocation::Discriminator, llvm::sampleprof::FunctionSamples::empty(), llvm::encodeULEB128(), llvm::sampleprof::FunctionSamples::getBodySamples(), llvm::sampleprof::SampleRecord::getCallTargets(), llvm::sampleprof::FunctionSamples::getHeadSamples(), llvm::sampleprof::SampleRecord::getSamples(), llvm::sampleprof::FunctionSamples::getTotalSamples(), I, llvm::sampleprof::LineLocation::LineOffset, llvm::sampleprof::SampleProfileWriter::OS, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size(), and llvm::StringMapImpl::size().
Referenced by write().
bool llvm::sampleprof::SampleProfileWriterBinary::write (const Module & M, StringMap< FunctionSamples > & P) [inline]
Write all the sample profiles for all the functions in M.
Returns:
true if the file was updated successfully. False, otherwise.
Reimplemented from llvm::sampleprof::SampleProfileWriter.
Definition at line 101 of file SampleProfWriter.h.
References write().
The documentation for this class was generated from the following files:
SampleProfWriter.h
SampleProfWriter.cpp