LLVM: llvm::PassInfo Class Reference
llvm::PassInfo Class Reference
PassInfo class - An instance of this class exists for every pass known by the system, and can be obtained from a live Pass by calling its getPassInfo() method.
#include <PassInfo.h>
Public Types
typedef Pass *(* NormalCtor_t)()
typedef Pass *(* TargetMachineCtor_t)(TargetMachine *)
Public Member Functions
PassInfo (const char *name, const char *arg, const void *pi, NormalCtor_t normal, bool isCFGOnly, bool is_analysis, TargetMachineCtor_t machine=nullptr)
PassInfo ctor - Do not call this directly, this should only be invoked through RegisterPass.
PassInfo (const char *name, const void *pi)
PassInfo ctor - Do not call this directly, this should only be invoked through RegisterPass.
const char * getPassName () const
getPassName - Return the friendly name for the pass, never returns null
const char * getPassArgument () const
getPassArgument - Return the command line option that may be passed to 'opt' that will cause this pass to be run.
const void * getTypeInfo () const
getTypeInfo - Return the id object for the pass...
bool isPassID (const void *IDPtr) const
Return true if this PassID implements the specified ID pointer.
bool isAnalysisGroup () const
isAnalysisGroup - Return true if this is an analysis group, not a normal pass.
bool isAnalysis () const
bool isCFGOnlyPass () const
isCFGOnlyPass - return true if this pass only looks at the CFG for the function.
NormalCtor_t getNormalCtor () const
getNormalCtor - Return a pointer to a function, that when called, creates an instance of the pass and returns it.
void setNormalCtor (NormalCtor_t Ctor)
TargetMachineCtor_t getTargetMachineCtor () const
getTargetMachineCtor - Return a pointer to a function, that when called with a TargetMachine, creates an instance of the pass and returns it.
void setTargetMachineCtor (TargetMachineCtor_t Ctor)
Pass * createPass () const
createPass() - Use this method to create an instance of this pass.
void addInterfaceImplemented (const PassInfo *ItfPI)
addInterfaceImplemented - This method is called when this pass is registered as a member of an analysis group with the RegisterAnalysisGroup template.
const std::vector< const
PassInfo * > & getInterfacesImplemented () const
getInterfacesImplemented - Return a list of all of the analysis group interfaces implemented by this pass.
Detailed Description
PassInfo class - An instance of this class exists for every pass known by the system, and can be obtained from a live Pass by calling its getPassInfo() method.
These objects are set up by the RegisterPass<> template.
Definition at line 30 of file PassInfo.h.
Member Typedef Documentation
typedef Pass*(* llvm::PassInfo::NormalCtor_t)()
Definition at line 32 of file PassInfo.h.
typedef Pass*(* llvm::PassInfo::TargetMachineCtor_t)(TargetMachine *)
Definition at line 33 of file PassInfo.h.
Constructor & Destructor Documentation
llvm::PassInfo::PassInfo (const char * name, const char * arg, const void * pi, NormalCtor_t normal, bool isCFGOnly, bool is_analysis, TargetMachineCtor_t machine = nullptr) [inline]
PassInfo ctor - Do not call this directly, this should only be invoked through RegisterPass.
Definition at line 50 of file PassInfo.h.
llvm::PassInfo::PassInfo (const char * name, const void * pi) [inline]
PassInfo ctor - Do not call this directly, this should only be invoked through RegisterPass.
This version is for use by analysis groups; it does not auto-register the pass.
Definition at line 60 of file PassInfo.h.
Member Function Documentation
void llvm::PassInfo::addInterfaceImplemented (const PassInfo * ItfPI) [inline]
addInterfaceImplemented - This method is called when this pass is registered as a member of an analysis group with the RegisterAnalysisGroup template.
Definition at line 129 of file PassInfo.h.
Referenced by llvm::PassRegistry::registerAnalysisGroup().
Pass* llvm::PassInfo::createPass () const [inline]
createPass() - Use this method to create an instance of this pass.
Definition at line 117 of file PassInfo.h.
References isAnalysisGroup().
Referenced by llvm::PMDataManager::add(), llvm::Pass::createPass(), and llvm::PMTopLevelManager::schedulePass().
const std::vector<const PassInfo*>& llvm::PassInfo::getInterfacesImplemented () const [inline]
getInterfacesImplemented - Return a list of all of the analysis group interfaces implemented by this pass.
Definition at line 136 of file PassInfo.h.
Referenced by llvm::PMTopLevelManager::findAnalysisPass(), and llvm::PMDataManager::recordAvailableAnalysis().
NormalCtor_t llvm::PassInfo::getNormalCtor () const [inline]
getNormalCtor - Return a pointer to a function, that when called, creates an instance of the pass and returns it.
This pointer may be null if there is no default constructor for the pass.
Definition at line 99 of file PassInfo.h.
Referenced by llvm::PassNameParser::ignorablePass(), and llvm::PassRegistry::registerAnalysisGroup().
const char* llvm::PassInfo::getPassArgument () const [inline]
getPassArgument - Return the command line option that may be passed to 'opt' that will cause this pass to be run.
This will return null if there is no argument.
Definition at line 74 of file PassInfo.h.
Referenced by llvm::PassNameParser::ignorablePass(), llvm::PassArgFilter< Args >::operator()(), llvm::PassNameParser::passRegistered(), llvm::PassRegistry::registerPass(), and ShouldPrintBeforeOrAfterPass().
const char* llvm::PassInfo::getPassName () const [inline]
getPassName - Return the friendly name for the pass, never returns null
Definition at line 68 of file PassInfo.h.
Referenced by llvm::Pass::getPassName(), and llvm::PassNameParser::passRegistered().
TargetMachineCtor_t llvm::PassInfo::getTargetMachineCtor () const [inline]
getTargetMachineCtor - Return a pointer to a function, that when called with a TargetMachine, creates an instance of the pass and returns it.
This pointer may be null if there is no constructor with a TargetMachine for the pass.
Definition at line 111 of file PassInfo.h.
Referenced by llvm::PassRegistry::registerAnalysisGroup().
const void* llvm::PassInfo::getTypeInfo () const [inline]
getTypeInfo - Return the id object for the pass...
TODO : Rename
Definition at line 78 of file PassInfo.h.
Referenced by llvm::TargetPassConfig::addMachinePasses(), llvm::AnalysisUsage::addPreserved(), and llvm::PassRegistry::registerPass().
bool llvm::PassInfo::isAnalysis () const [inline]
Definition at line 89 of file PassInfo.h.
Referenced by llvm::PMTopLevelManager::schedulePass().
bool llvm::PassInfo::isAnalysisGroup () const [inline]
isAnalysisGroup - Return true if this is an analysis group, not a normal pass.
Definition at line 88 of file PassInfo.h.
Referenced by createPass(), and llvm::PassRegistry::registerAnalysisGroup().
bool llvm::PassInfo::isCFGOnlyPass () const [inline]
isCFGOnlyPass - return true if this pass only looks at the CFG for the function.
Definition at line 93 of file PassInfo.h.
bool llvm::PassInfo::isPassID (const void * IDPtr) const [inline]
Return true if this PassID implements the specified ID pointer.
Definition at line 81 of file PassInfo.h.
void llvm::PassInfo::setNormalCtor (NormalCtor_t Ctor) [inline]
Definition at line 102 of file PassInfo.h.
Referenced by llvm::PassRegistry::registerAnalysisGroup().
void llvm::PassInfo::setTargetMachineCtor (TargetMachineCtor_t Ctor) [inline]
Definition at line 112 of file PassInfo.h.
Referenced by llvm::PassRegistry::registerAnalysisGroup().
The documentation for this class was generated from the following file:
PassInfo.h