LLVM: llvm::ConstantAggregateZero Class Reference
llvm::ConstantAggregateZero Class Reference
ConstantAggregateZero - All zero aggregate value.
#include <Constants.h>
Public Member Functions
Constant * getSequentialElement () const
getSequentialElement - If this CAZ has array or vector type, return a zero with the right element type.
Constant * getStructElement (unsigned Elt) const
getStructElement - If this CAZ has struct type, return a zero with the right element type for the specified element.
Constant * getElementValue (Constant *C) const
getElementValue - Return a zero of the right value for the specified GEP index.
Constant * getElementValue (unsigned Idx) const
getElementValue - Return a zero of the right value for the specified GEP index.
unsigned getNumElements () const
Return the number of elements in the array, vector, or struct.
Static Public Member Functions
static ConstantAggregateZero * get (Type *Ty)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
ConstantAggregateZero (Type *ty)
void * operator new (size_t s)
Allocate a User with an operand pointer co-allocated.
Friends
class Constant
Detailed Description
ConstantAggregateZero - All zero aggregate value.
Definition at line 305 of file Constants.h.
Constructor & Destructor Documentation
llvm::ConstantAggregateZero::ConstantAggregateZero (Type * ty) [inline, explicit, protected]
Definition at line 313 of file Constants.h.
Member Function Documentation
static bool llvm::ConstantAggregateZero::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::Constant.
Definition at line 344 of file Constants.h.
References llvm::Value::getValueID().
ConstantAggregateZero * ConstantAggregateZero::get (Type * Ty) [static]
Definition at line 1377 of file Constants.cpp.
References llvm::LLVMContextImpl::CAZConstants, llvm::Type::getContext(), llvm::Type::isArrayTy(), llvm::Type::isStructTy(), llvm::Type::isVectorTy(), and llvm::LLVMContext::pImpl.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateVectorSplat(), llvm::ConstantDataSequential::getImpl(), llvm::Constant::getNullValue(), llvm::MapValue(), llvm::ConstantArray::replaceUsesOfWithOnConstant(), llvm::ConstantStruct::replaceUsesOfWithOnConstant(), SimplifyX86insertps(), SimplifyX86vperm2(), and llvm::InstCombiner::visitCallInst().
Constant * ConstantAggregateZero::getElementValue (Constant * C) const
getElementValue - Return a zero of the right value for the specified GEP index.
getElementValue - Return a zero of the right value for the specified GEP index if we can, otherwise return null (e.g.
if C is a ConstantExpr).
Definition at line 785 of file Constants.cpp.
References getSequentialElement(), getStructElement(), and llvm::Value::getType().
Constant * ConstantAggregateZero::getElementValue (unsigned Idx) const
getElementValue - Return a zero of the right value for the specified GEP index.
Definition at line 793 of file Constants.cpp.
References getSequentialElement(), getStructElement(), and llvm::Value::getType().
unsigned ConstantAggregateZero::getNumElements () const
Return the number of elements in the array, vector, or struct.
Definition at line 799 of file Constants.cpp.
References llvm::Type::getStructNumElements(), and llvm::Value::getType().
Constant * ConstantAggregateZero::getSequentialElement () const
getSequentialElement - If this CAZ has array or vector type, return a zero with the right element type.
Definition at line 773 of file Constants.cpp.
References llvm::Constant::getNullValue(), and llvm::Value::getType().
Referenced by getElementValue().
Constant * ConstantAggregateZero::getStructElement (unsigned Elt) const
getStructElement - If this CAZ has struct type, return a zero with the right element type for the specified element.
Definition at line 779 of file Constants.cpp.
References llvm::Constant::getNullValue(), and llvm::Value::getType().
Referenced by getElementValue().
void* llvm::ConstantAggregateZero::operator new (size_t Size) [inline, protected]
Allocate a User with an operand pointer co-allocated.
This is used for subclasses which need to allocate a variable number of operands, ie, 'hung off uses'.
Reimplemented from llvm::User.
Definition at line 317 of file Constants.h.
References operator new().
Friends And Related Function Documentation
friend class Constant [friend]
Definition at line 309 of file Constants.h.
The documentation for this class was generated from the following files:
Constants.h
Constants.cpp