LLVM: llvm::IntInit Class Reference
llvm::IntInit Class Reference
IntInit - 7 - Represent an initialization by a literal integer value.
#include <Record.h>
Public Member Functions
int64_t getValue () const
Init * convertInitializerTo (RecTy *Ty) const override
convertInitializerTo - This virtual function converts to the appropriate Init based on the passed in type.
Init * convertInitializerBitRange (const std::vector< unsigned > &Bits) const override
convertInitializerBitRange - This method is used to implement the bitrange selection operator.
std::string getAsString () const override
getAsString - Convert this value to a string form.
Init * resolveListElementReference (Record &R, const RecordVal *RV, unsigned Elt) const override
resolveListElementReference - This method is used to implement VarListElementInit::resolveReferences.
Init * getBit (unsigned Bit) const override
getBit - This method is used to return the initializer for the specified bit.
Static Public Member Functions
static bool classof (const Init *I)
static IntInit * get (int64_t V)
Detailed Description
IntInit - 7 - Represent an initialization by a literal integer value.
Definition at line 509 of file Record.h.
Member Function Documentation
static bool llvm::IntInit::classof (const Init * I) [inline, static]
Reimplemented from llvm::TypedInit.
Definition at line 519 of file Record.h.
References llvm::Init::getKind(), and llvm::Init::IK_IntInit.
Init * IntInit::convertInitializerBitRange (const std::vector< unsigned > & Bits) const [override, virtual]
convertInitializerBitRange - This method is used to implement the bitrange selection operator.
Given an initializer, it selects the specified bits out, returning them as a new init of bits type. If it is not legal to use the bit subscript operator on this initializer, return null.
Reimplemented from llvm::TypedInit.
Definition at line 441 of file Record.cpp.
References get().
Init * IntInit::convertInitializerTo (RecTy * Ty) const [override, virtual]
convertInitializerTo - This virtual function converts to the appropriate Init based on the passed in type.
Reimplemented from llvm::TypedInit.
Definition at line 414 of file Record.cpp.
References canFitInBitfield(), llvm::BitInit::get(), get(), and getValue().
IntInit * IntInit::get (int64_t V) [static]
Definition at line 394 of file Record.cpp.
References I.
Referenced by convertInitializerBitRange(), llvm::BitInit::convertInitializerTo(), convertInitializerTo(), llvm::UnOpInit::Fold(), and getBit().
std::string IntInit::getAsString () const [override, virtual]
getAsString - Convert this value to a string form.
Implements llvm::Init.
Definition at line 402 of file Record.cpp.
References llvm::itostr().
Init* llvm::IntInit::getBit (unsigned Bit) const [inline, override, virtual]
getBit - This method is used to return the initializer for the specified bit.
Implements llvm::Init.
Definition at line 540 of file Record.h.
References get().
int64_t llvm::IntInit::getValue () const [inline]
Definition at line 524 of file Record.h.
Referenced by convertInitializerTo(), llvm::BinOpInit::Fold(), llvm::TernOpInit::Fold(), and llvm::TernOpInit::resolveReferences().
Init* llvm::IntInit::resolveListElementReference (Record & R, const RecordVal * RV, unsigned Elt) const [inline, override, virtual]
resolveListElementReference - This method is used to implement VarListElementInit::resolveReferences.
If the list element is resolvable now, we return the resolved value, otherwise we return null.
Implements llvm::TypedInit.
Definition at line 535 of file Record.h.
References llvm_unreachable.
The documentation for this class was generated from the following files:
Record.h
Record.cpp