LLVM: llvm::ZExtInst Class Reference
llvm::ZExtInst Class Reference
This class represents zero extension of integer types.
#include <Instructions.h>
Public Member Functions
ZExtInst (Value *S, Type *Ty, const Twine &NameStr="", Instruction *InsertBefore=nullptr)
Constructor with insert-before-instruction semantics.
ZExtInst (Value *S, Type *Ty, const Twine &NameStr, BasicBlock *InsertAtEnd)
Constructor with insert-at-end semantics.
Static Public Member Functions
static bool classof (const Instruction *I)
Methods for support type inquiry through isa, cast, and dyn_cast:
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
ZExtInst * clone_impl () const override
Clone an identical ZExtInst.
Detailed Description
This class represents zero extension of integer types.
Definition at line 3542 of file Instructions.h.
Constructor & Destructor Documentation
ZExtInst::ZExtInst (Value * S, Type * Ty, const Twine & NameStr = "", Instruction * InsertBefore = nullptr)
Constructor with insert-before-instruction semantics.
Parameters:
S The value to be zero extended
Ty The type to zero extend to
NameStr A name for the new instruction
InsertBefore Where to insert the new instruction
Definition at line 2822 of file Instructions.cpp.
References llvm::CastInst::castIsValid(), and llvm::CastInst::getOpcode().
Referenced by clone_impl().
ZExtInst::ZExtInst (Value * S, Type * Ty, const Twine & NameStr, BasicBlock * InsertAtEnd)
Constructor with insert-at-end semantics.
Parameters:
S The value to be zero extended
Ty The type to zero extend to
NameStr A name for the new instruction
InsertAtEnd The block to insert the instruction into
Definition at line 2828 of file Instructions.cpp.
References llvm::CastInst::castIsValid(), and llvm::CastInst::getOpcode().
Member Function Documentation
static bool llvm::ZExtInst::classof (const Instruction * I) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::CastInst.
Definition at line 3565 of file Instructions.h.
References llvm::Instruction::getOpcode().
Referenced by classof().
static bool llvm::ZExtInst::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::CastInst.
Definition at line 3568 of file Instructions.h.
References classof().
ZExtInst * ZExtInst::clone_impl () const [override, protected, virtual]
Clone an identical ZExtInst.
Implements llvm::Instruction.
Definition at line 3525 of file Instructions.cpp.
References llvm::User::getOperand(), llvm::Value::getType(), and ZExtInst().
The documentation for this class was generated from the following files:
Instructions.h
Instructions.cpp