LLVM: llvm::InterferenceCache Class Reference
llvm::InterferenceCache Class Reference
#include <InterferenceCache.h>
Classes
struct BlockInterference
BlockInterference - information about the interference in a single basic block.
class Cursor
Cursor - The primary query interface for the block interference cache.
class Entry
Entry - A cache entry containing interference information for all aliases of PhysReg in all basic blocks.
Public Member Functions
InterferenceCache ()
~InterferenceCache ()
void reinitPhysRegEntries ()
void init (MachineFunction *, LiveIntervalUnion *, SlotIndexes *, LiveIntervals *, const TargetRegisterInfo *)
init - Prepare cache for a new function.
unsigned getMaxCursors () const
getMaxCursors - Return the maximum number of concurrent cursors that can be supported.
Friends
class Cursor
Detailed Description
Definition at line 24 of file InterferenceCache.h.
Constructor & Destructor Documentation
llvm::InterferenceCache::InterferenceCache () [inline]
Definition at line 152 of file InterferenceCache.h.
llvm::InterferenceCache::~InterferenceCache () [inline]
Definition at line 156 of file InterferenceCache.h.
Member Function Documentation
unsigned llvm::InterferenceCache::getMaxCursors () const [inline]
getMaxCursors - Return the maximum number of concurrent cursors that can be supported.
Definition at line 168 of file InterferenceCache.h.
void InterferenceCache::init (MachineFunction * mf, LiveIntervalUnion * liuarray, SlotIndexes * indexes, LiveIntervals * lis, const TargetRegisterInfo * tri)
init - Prepare cache for a new function.
Definition at line 43 of file InterferenceCache.cpp.
References reinitPhysRegEntries().
void InterferenceCache::reinitPhysRegEntries ()
Definition at line 35 of file InterferenceCache.cpp.
References llvm::MCRegisterInfo::getNumRegs().
Referenced by init().
Friends And Related Function Documentation
friend class Cursor [friend]
Definition at line 233 of file InterferenceCache.h.
The documentation for this class was generated from the following files:
InterferenceCache.h
InterferenceCache.cpp