LLVM: llvm::DIImportedEntity Class Reference
llvm::DIImportedEntity Class Reference
An imported module (C++ using directive or similar).
#include <DebugInfoMetadata.h>
Public Member Functions
DEFINE_MDNODE_GET (DIImportedEntity,(unsigned Tag, DIScope *Scope, DINodeRef Entity, unsigned Line, StringRef Name=""),(Tag, Scope, Entity, Line, Name)) DEFINE_MDNODE_GET(DIImportedEntity
unsigned Metadata Metadata
unsigned MDString Name
TempDIImportedEntity clone () const
Create a (temporary) clone of this.
unsigned getLine () const
DIScope * getScope () const
DINodeRef getEntity () const
StringRef getName () const
Metadata * getRawScope () const
Metadata * getRawEntity () const
MDString * getRawName () const
Static Public Member Functions
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
Public Attributes
unsigned Tag
unsigned Metadata * Scope
unsigned Metadata Metadata * Entity
unsigned Metadata Metadata unsigned Line
unsigned Metadata Metadata
unsigned MDString * Name
unsigned Metadata Metadata
unsigned MDString Tag
unsigned Metadata Metadata
unsigned MDString Scope
unsigned Metadata Metadata
unsigned MDString Entity
unsigned Metadata Metadata
unsigned MDString Line
Friends
class LLVMContextImpl
class MDNode
Detailed Description
An imported module (C++ using directive or similar).
Definition at line 2160 of file DebugInfoMetadata.h.
Member Function Documentation
static bool llvm::DIImportedEntity::classof (const Metadata * MD) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::DINode.
Definition at line 2211 of file DebugInfoMetadata.h.
References llvm::Metadata::DIImportedEntityKind, and llvm::Metadata::getMetadataID().
unsigned Metadata Metadata unsigned MDString Name TempDIImportedEntity llvm::DIImportedEntity::clone () const [inline]
Create a (temporary) clone of this.
Reimplemented from llvm::MDNode.
Definition at line 2200 of file DebugInfoMetadata.h.
llvm::DIImportedEntity::DEFINE_MDNODE_GET (DIImportedEntity , (unsigned Tag, DIScope *Scope, DINodeRef Entity,unsigned Line, StringRef Name="") , (Tag, Scope, Entity, Line, Name))
DINodeRef llvm::DIImportedEntity::getEntity () const [inline]
Definition at line 2204 of file DebugInfoMetadata.h.
References getRawEntity().
Referenced by llvm::DwarfCompileUnit::constructImportedEntityDIE(), and WriteDIImportedEntity().
unsigned llvm::DIImportedEntity::getLine () const [inline]
Definition at line 2202 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfCompileUnit::constructImportedEntityDIE(), llvm::MDNodeKeyImpl< DIImportedEntity >::isKeyOf(), and WriteDIImportedEntity().
StringRef llvm::DIImportedEntity::getName () const [inline]
Definition at line 2205 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
Referenced by llvm::DwarfCompileUnit::constructImportedEntityDIE(), and llvm::MDNodeKeyImpl< DIImportedEntity >::isKeyOf().
Metadata* llvm::DIImportedEntity::getRawEntity () const [inline]
Definition at line 2208 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getEntity(), and llvm::MDNodeKeyImpl< DIImportedEntity >::isKeyOf().
MDString* llvm::DIImportedEntity::getRawName () const [inline]
Definition at line 2209 of file DebugInfoMetadata.h.
Referenced by WriteDIImportedEntity().
Metadata* llvm::DIImportedEntity::getRawScope () const [inline]
Definition at line 2207 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getScope(), and llvm::MDNodeKeyImpl< DIImportedEntity >::isKeyOf().
DIScope* llvm::DIImportedEntity::getScope () const [inline]
Definition at line 2203 of file DebugInfoMetadata.h.
References getRawScope().
Referenced by llvm::DwarfCompileUnit::constructImportedEntityDIE(), and WriteDIImportedEntity().
Friends And Related Function Documentation
friend class LLVMContextImpl [friend]
Reimplemented from llvm::DINode.
Definition at line 2161 of file DebugInfoMetadata.h.
friend class MDNode [friend]
Reimplemented from llvm::DINode.
Definition at line 2162 of file DebugInfoMetadata.h.
Member Data Documentation
unsigned Metadata Metadata* llvm::DIImportedEntity::Entity
Definition at line 2196 of file DebugInfoMetadata.h.
unsigned Metadata Metadata unsigned MDString llvm::DIImportedEntity::Entity
Definition at line 2196 of file DebugInfoMetadata.h.
unsigned Metadata Metadata unsigned llvm::DIImportedEntity::Line
Definition at line 2196 of file DebugInfoMetadata.h.
unsigned Metadata Metadata unsigned MDString llvm::DIImportedEntity::Line
Definition at line 2196 of file DebugInfoMetadata.h.
unsigned Metadata Metadata unsigned MDString* llvm::DIImportedEntity::Name
Definition at line 2196 of file DebugInfoMetadata.h.
unsigned Metadata* llvm::DIImportedEntity::Scope
Definition at line 2196 of file DebugInfoMetadata.h.
unsigned Metadata Metadata unsigned MDString llvm::DIImportedEntity::Scope
Definition at line 2196 of file DebugInfoMetadata.h.
unsigned llvm::DIImportedEntity::Tag
Definition at line 2196 of file DebugInfoMetadata.h.
unsigned Metadata Metadata unsigned MDString llvm::DIImportedEntity::Tag
Definition at line 2196 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
DebugInfoMetadata.h
DebugInfoMetadata.cpp