LLVM: llvm::HexagonResource Class Reference
llvm::HexagonResource Class Reference
#include <HexagonShuffler.h>
Public Member Functions
HexagonResource (unsigned s)
void setUnits (unsigned s)
unsigned setWeight (unsigned s)
unsigned getUnits () const
unsigned getWeight () const
Static Public Member Functions
static bool lessUnits (const HexagonResource &A, const HexagonResource &B)
static bool lessWeight (const HexagonResource &A, const HexagonResource &B)
Detailed Description
Definition at line 28 of file HexagonShuffler.h.
Constructor & Destructor Documentation
llvm::HexagonResource::HexagonResource (unsigned s) [inline]
Definition at line 34 of file HexagonShuffler.h.
Member Function Documentation
unsigned llvm::HexagonResource::getUnits () const [inline]
Definition at line 41 of file HexagonShuffler.h.
Referenced by llvm::HexagonShuffler::check(), lessUnits(), and setWeight().
unsigned llvm::HexagonResource::getWeight () const [inline]
Definition at line 42 of file HexagonShuffler.h.
Referenced by lessWeight().
static bool llvm::HexagonResource::lessUnits (const HexagonResource & A, const HexagonResource & B) [inline, static]
Definition at line 45 of file HexagonShuffler.h.
References llvm::countPopulation(), and getUnits().
Referenced by llvm::HexagonInstr::lessCore().
static bool llvm::HexagonResource::lessWeight (const HexagonResource & A, const HexagonResource & B) [inline, static]
Definition at line 49 of file HexagonShuffler.h.
References getWeight().
Referenced by llvm::HexagonInstr::operator<().
void llvm::HexagonResource::setUnits (unsigned s) [inline]
Definition at line 36 of file HexagonShuffler.h.
References HEXAGON_PACKET_SIZE.
Referenced by llvm::HexagonShuffler::check().
unsigned HexagonResource::setWeight (unsigned s)
Definition at line 79 of file HexagonShuffler.cpp.
References llvm::countPopulation(), llvm::countTrailingZeros(), and getUnits().
Referenced by llvm::HexagonShuffler::shuffle().
The documentation for this class was generated from the following files:
HexagonShuffler.h
HexagonShuffler.cpp