LLVM: llvm::ActionHandler Class Reference
llvm::ActionHandler Class Reference
#include <WinEHFuncInfo.h>
Public Member Functions
ActionHandler (BasicBlock *BB, ActionType Type)
ActionType getType () const
BasicBlock * getStartBlock () const
bool hasBeenProcessed ()
void setHandlerBlockOrFunc (Constant *F)
Constant * getHandlerBlockOrFunc ()
void setEHState (int State)
int getEHState () const
Detailed Description
Definition at line 34 of file WinEHFuncInfo.h.
Constructor & Destructor Documentation
llvm::ActionHandler::ActionHandler (BasicBlock * BB, ActionType Type) [inline]
Definition at line 36 of file WinEHFuncInfo.h.
Member Function Documentation
int llvm::ActionHandler::getEHState () const [inline]
Definition at line 48 of file WinEHFuncInfo.h.
Constant* llvm::ActionHandler::getHandlerBlockOrFunc () [inline]
Definition at line 45 of file WinEHFuncInfo.h.
BasicBlock* llvm::ActionHandler::getStartBlock () const [inline]
Definition at line 40 of file WinEHFuncInfo.h.
Referenced by createCleanupHandler().
ActionType llvm::ActionHandler::getType () const [inline]
Definition at line 39 of file WinEHFuncInfo.h.
Referenced by llvm::CatchHandler::classof(), and llvm::CleanupHandler::classof().
bool llvm::ActionHandler::hasBeenProcessed () [inline]
Definition at line 42 of file WinEHFuncInfo.h.
void llvm::ActionHandler::setEHState (int State) [inline]
Definition at line 47 of file WinEHFuncInfo.h.
void llvm::ActionHandler::setHandlerBlockOrFunc (Constant * F) [inline]
Definition at line 44 of file WinEHFuncInfo.h.
References F().
The documentation for this class was generated from the following file:
WinEHFuncInfo.h