LLVM: llvm::GCOVFunction Class Reference
llvm::GCOVFunction Class Reference
GCOVFunction - Collects function information.
#include <GCOV.h>
Public Types
typedef pointee_iterator
< SmallVectorImpl
< std::unique_ptr< GCOVBlock >
>::const_iterator > BlockIterator
Public Member Functions
GCOVFunction (GCOVFile &P)
bool readGCNO (GCOVBuffer &Buffer, GCOV::GCOVVersion Version)
readGCNO - Read a function from the GCNO buffer.
bool readGCDA (GCOVBuffer &Buffer, GCOV::GCOVVersion Version)
readGCDA - Read a function from the GCDA buffer.
StringRef getName () const
StringRef getFilename () const
size_t getNumBlocks () const
uint64_t getEntryCount () const
getEntryCount - Get the number of times the function was called by retrieving the entry block's count.
uint64_t getExitCount () const
getExitCount - Get the number of times the function returned by retrieving the exit block's count.
BlockIterator block_begin () const
BlockIterator block_end () const
iterator_range< BlockIterator > blocks () const
void dump () const
dump - Dump GCOVFunction content to dbgs() for debugging purposes.
void collectLineCounts (FileInfo &FI)
collectLineCounts - Collect line counts.
Detailed Description
GCOVFunction - Collects function information.
Definition at line 257 of file GCOV.h.
Member Typedef Documentation
typedef pointee_iterator<SmallVectorImpl< std::unique_ptr<GCOVBlock> >::const_iterator> llvm::GCOVFunction::BlockIterator
Definition at line 260 of file GCOV.h.
Constructor & Destructor Documentation
llvm::GCOVFunction::GCOVFunction (GCOVFile & P) [inline]
Definition at line 262 of file GCOV.h.
Member Function Documentation
BlockIterator llvm::GCOVFunction::block_begin () const [inline]
Definition at line 271 of file GCOV.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
Referenced by blocks().
BlockIterator llvm::GCOVFunction::block_end () const [inline]
Definition at line 272 of file GCOV.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by blocks().
iterator_range<BlockIterator> llvm::GCOVFunction::blocks () const [inline]
Definition at line 273 of file GCOV.h.
References block_begin(), block_end(), and llvm::make_range().
void GCOVFunction::collectLineCounts (FileInfo & FI)
collectLineCounts - Collect line counts.
This must be used after reading .gcno and .gcda files.
Definition at line 352 of file GCOV.cpp.
References llvm::FileInfo::addFunctionLine(), and llvm::Block.
void GCOVFunction::dump () const
dump - Dump GCOVFunction content to dbgs() for debugging purposes.
Definition at line 343 of file GCOV.cpp.
References llvm::Block, and llvm::dbgs().
uint64_t GCOVFunction::getEntryCount () const
getEntryCount - Get the number of times the function was called by retrieving the entry block's count.
Definition at line 332 of file GCOV.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::front().
uint64_t GCOVFunction::getExitCount () const
getExitCount - Get the number of times the function returned by retrieving the exit block's count.
Definition at line 338 of file GCOV.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back().
StringRef llvm::GCOVFunction::getFilename () const [inline]
Definition at line 266 of file GCOV.h.
Referenced by llvm::GCOVBlock::collectLineCounts().
StringRef llvm::GCOVFunction::getName () const [inline]
Definition at line 265 of file GCOV.h.
Referenced by llvm::FileInfo::print().
size_t llvm::GCOVFunction::getNumBlocks () const [inline]
Definition at line 267 of file GCOV.h.
References llvm::SmallVectorTemplateCommon< T, typename >::size().
bool GCOVFunction::readGCDA (GCOVBuffer & Buff, GCOV::GCOVVersion Version)
readGCDA - Read a function from the GCDA buffer.
Return false if an error occurs.
Definition at line 249 of file GCOV.cpp.
References llvm::GCOVBlock::addCount(), llvm::Block, llvm::NVPTXISD::Dummy, llvm::errs(), llvm::GCOVFile::getChecksum(), llvm::GCOVBlock::getNumDstEdges(), llvm::GCOVBuffer::readArcTag(), llvm::GCOVBuffer::readInt(), llvm::GCOVBuffer::readInt64(), llvm::GCOVBuffer::readString(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::GCOVBlock::sortDstEdges(), and llvm::GCOV::V402.
bool GCOVFunction::readGCNO (GCOVBuffer & Buff, GCOV::GCOVVersion Version)
readGCNO - Read a function from the GCNO buffer.
Return false if an error occurs.
Definition at line 126 of file GCOV.cpp.
References llvm::GCOVBlock::addLine(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::Block, llvm::NVPTXISD::Dummy, llvm::errs(), F(), llvm::GCOVFile::getChecksum(), llvm::GCOVBuffer::getCursor(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::GCOVBuffer::readBlockTag(), llvm::GCOVBuffer::readEdgeTag(), llvm::GCOVBuffer::readInt(), llvm::GCOVBuffer::readLineTag(), llvm::GCOVBuffer::readString(), and llvm::GCOV::V402.
The documentation for this class was generated from the following files:
GCOV.h
GCOV.cpp