LLVM: llvm::StringSaver Class Reference
llvm::StringSaver Class Reference
Saves strings in the inheritor's stable storage and returns a stable raw character pointer.
#include <StringSaver.h>
Public Member Functions
StringSaver (BumpPtrAllocator &Alloc)
const char * save (const char *S)
const char * save (StringRef S)
const char * save (const Twine &S)
const char * save (std::string &S)
Protected Member Functions
~StringSaver ()
virtual const char * saveImpl (StringRef S)
Detailed Description
Saves strings in the inheritor's stable storage and returns a stable raw character pointer.
Definition at line 21 of file StringSaver.h.
Constructor & Destructor Documentation
llvm::StringSaver::~StringSaver () [inline, protected]
Definition at line 23 of file StringSaver.h.
llvm::StringSaver::StringSaver (BumpPtrAllocator & Alloc) [inline]
Definition at line 27 of file StringSaver.h.
Member Function Documentation
const char* llvm::StringSaver::save (const char * S) [inline]
Definition at line 28 of file StringSaver.h.
References save().
Referenced by getSearchPaths(), save(), llvm::cl::TokenizeGNUCommandLine(), and llvm::cl::TokenizeWindowsCommandLine().
const char* llvm::StringSaver::save (StringRef S) [inline]
Definition at line 29 of file StringSaver.h.
References saveImpl().
const char* llvm::StringSaver::save (const Twine & S) [inline]
Definition at line 30 of file StringSaver.h.
References save(), and llvm::Twine::str().
Referenced by save().
const char* llvm::StringSaver::save (std::string & S) [inline]
Definition at line 31 of file StringSaver.h.
References save().
Referenced by save().
const char * StringSaver::saveImpl (StringRef S) [protected, virtual]
Definition at line 14 of file StringSaver.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate(), llvm::StringRef::data(), P, and llvm::StringRef::size().
Referenced by save().
The documentation for this class was generated from the following files:
StringSaver.h
StringSaver.cpp