LLVM: llvm::object::SectionRef Class Reference
llvm::object::SectionRef Class Reference
This is a value type class that represents a single section in the list of sections in the object file.
#include <ObjectFile.h>
Public Member Functions
SectionRef ()
SectionRef (DataRefImpl SectionP, const ObjectFile *Owner)
SectionRef.
bool operator== (const SectionRef &Other) const
bool operator!= (const SectionRef &Other) const
bool operator< (const SectionRef &Other) const
void moveNext ()
std::error_code getName (StringRef &Result) const
uint64_t getAddress () const
uint64_t getSize () const
std::error_code getContents (StringRef &Result) const
uint64_t getAlignment () const
Get the alignment of this section as the actual value (not log 2).
bool isText () const
bool isData () const
bool isBSS () const
bool isVirtual () const
bool containsSymbol (SymbolRef S) const
relocation_iterator relocation_begin () const
relocation_iterator relocation_end () const
iterator_range
< relocation_iterator > relocations () const
section_iterator getRelocatedSection () const
DataRefImpl getRawDataRefImpl () const
const ObjectFile * getObject () const
Friends
class SymbolRef
Detailed Description
This is a value type class that represents a single section in the list of sections in the object file.
Definition at line 76 of file ObjectFile.h.
Constructor & Destructor Documentation
llvm::object::SectionRef::SectionRef () [inline]
Definition at line 82 of file ObjectFile.h.
llvm::object::SectionRef::SectionRef (DataRefImpl SectionP, const ObjectFile * Owner) [inline]
SectionRef.
Definition at line 352 of file ObjectFile.h.
Member Function Documentation
bool llvm::object::SectionRef::containsSymbol (SymbolRef S) const [inline]
Definition at line 409 of file ObjectFile.h.
References llvm::object::BasicSymbolRef::getRawDataRefImpl(), and llvm::object::ObjectFile::sectionContainsSymbol().
uint64_t llvm::object::SectionRef::getAddress () const [inline]
Definition at line 377 of file ObjectFile.h.
References llvm::object::ObjectFile::getSectionAddress().
Referenced by llvm::RuntimeDyldMachO::getRelocationValueRef().
uint64_t llvm::object::SectionRef::getAlignment () const [inline]
Get the alignment of this section as the actual value (not log 2).
Definition at line 389 of file ObjectFile.h.
References llvm::object::ObjectFile::getSectionAlignment().
Referenced by llvm::RuntimeDyldImpl::computeSectionStubBufSize(), llvm::RuntimeDyldImpl::computeTotalAllocSize(), and llvm::RuntimeDyldImpl::emitSection().
std::error_code llvm::object::SectionRef::getContents (StringRef & Result) const [inline]
Definition at line 385 of file ObjectFile.h.
References llvm::object::ObjectFile::getSectionContents().
Referenced by llvm::RuntimeDyldImpl::emitSection().
std::error_code llvm::object::SectionRef::getName (StringRef & Result) const [inline]
Definition at line 373 of file ObjectFile.h.
References llvm::object::ObjectFile::getSectionName().
Referenced by llvm::RuntimeDyldImpl::computeTotalAllocSize(), llvm::RuntimeDyldImpl::emitSection(), llvm::RuntimeDyldELF::finalizeLoad(), llvm::RuntimeDyldCOFFX86_64::finalizeLoad(), llvm::RuntimeDyldMachOI386::finalizeSection(), llvm::RuntimeDyldMachOARM::finalizeSection(), and lookupSection().
const ObjectFile * llvm::object::SectionRef::getObject () const [inline]
Definition at line 430 of file ObjectFile.h.
Referenced by llvm::isReadOnlyData(), llvm::isRequiredForExecution(), and llvm::isZeroInit().
DataRefImpl llvm::object::SectionRef::getRawDataRefImpl () const [inline]
Definition at line 426 of file ObjectFile.h.
Referenced by llvm::object::COFFObjectFile::getCOFFSection(), llvm::object::ELFObjectFile< ELFT >::getSectionFlags(), llvm::object::MachOObjectFile::getSectionType(), llvm::object::ELFObjectFile< ELFT >::getSectionType(), and llvm::RuntimeDyldMachO::populateIndirectSymbolPointersSection().
section_iterator llvm::object::SectionRef::getRelocatedSection () const [inline]
Definition at line 422 of file ObjectFile.h.
References llvm::object::ObjectFile::getRelocatedSection().
uint64_t llvm::object::SectionRef::getSize () const [inline]
Definition at line 381 of file ObjectFile.h.
References llvm::object::ObjectFile::getSectionSize().
Referenced by llvm::RuntimeDyldImpl::computeSectionStubBufSize(), llvm::RuntimeDyldImpl::computeTotalAllocSize(), and llvm::RuntimeDyldImpl::emitSection().
bool llvm::object::SectionRef::isBSS () const [inline]
Definition at line 401 of file ObjectFile.h.
References llvm::object::ObjectFile::isSectionBSS().
bool llvm::object::SectionRef::isData () const [inline]
Definition at line 397 of file ObjectFile.h.
References llvm::object::ObjectFile::isSectionData().
bool llvm::object::SectionRef::isText () const [inline]
Definition at line 393 of file ObjectFile.h.
References llvm::object::ObjectFile::isSectionText().
Referenced by llvm::RuntimeDyldImpl::computeTotalAllocSize(), and llvm::RuntimeDyldMachO::getRelocationValueRef().
bool llvm::object::SectionRef::isVirtual () const [inline]
Definition at line 405 of file ObjectFile.h.
References llvm::object::ObjectFile::isSectionVirtual().
Referenced by llvm::RuntimeDyldImpl::emitSection().
void llvm::object::SectionRef::moveNext () [inline]
Definition at line 369 of file ObjectFile.h.
References llvm::object::ObjectFile::moveSectionNext().
bool llvm::object::SectionRef::operator!= (const SectionRef & Other) const [inline]
Definition at line 361 of file ObjectFile.h.
bool llvm::object::SectionRef::operator< (const SectionRef & Other) const [inline]
Definition at line 365 of file ObjectFile.h.
bool llvm::object::SectionRef::operator== (const SectionRef & Other) const [inline]
Definition at line 357 of file ObjectFile.h.
relocation_iterator llvm::object::SectionRef::relocation_begin () const [inline]
Definition at line 414 of file ObjectFile.h.
References llvm::object::ObjectFile::section_rel_begin().
Referenced by relocations().
relocation_iterator llvm::object::SectionRef::relocation_end () const [inline]
Definition at line 418 of file ObjectFile.h.
References llvm::object::ObjectFile::section_rel_end().
Referenced by relocations().
iterator_range<relocation_iterator> llvm::object::SectionRef::relocations () const [inline]
Definition at line 109 of file ObjectFile.h.
References relocation_begin(), and relocation_end().
Friends And Related Function Documentation
friend class SymbolRef [friend]
Definition at line 77 of file ObjectFile.h.
The documentation for this class was generated from the following file:
ObjectFile.h