LLVM: llvm::DebugEpochBase::HandleBase Class Reference
llvm::DebugEpochBase::HandleBase Class Reference
#include <EpochTracker.h>
Public Member Functions
HandleBase ()
HandleBase (const DebugEpochBase *)
bool isHandleInSync () const
const void * getEpochAddress () const
Detailed Description
Definition at line 31 of file EpochTracker.h.
Constructor & Destructor Documentation
llvm::DebugEpochBase::HandleBase::HandleBase ()
llvm::DebugEpochBase::HandleBase::HandleBase (const DebugEpochBase *) [inline, explicit]
Definition at line 34 of file EpochTracker.h.
Member Function Documentation
const void* llvm::DebugEpochBase::HandleBase::getEpochAddress () const [inline]
Definition at line 36 of file EpochTracker.h.
Referenced by llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::operator!=(), and llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::operator==().
bool llvm::DebugEpochBase::HandleBase::isHandleInSync () const [inline]
Definition at line 35 of file EpochTracker.h.
Referenced by llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::operator!=(), and llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::operator==().
The documentation for this class was generated from the following file:
EpochTracker.h