LLVM: llvm::BPFInstPrinter Class Reference
llvm::BPFInstPrinter Class Reference
#include <BPFInstPrinter.h>
Public Member Functions
BPFInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printInst (const MCInst *MI, raw_ostream &O, StringRef Annot, const MCSubtargetInfo &STI) override
Print the specified MCInst to the specified raw_ostream.
void printOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O, const char *Modifier=nullptr)
void printMemOperand (const MCInst *MI, int OpNo, raw_ostream &O, const char *Modifier=nullptr)
void printImm64Operand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printInstruction (const MCInst *MI, raw_ostream &O)
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo)
Detailed Description
Definition at line 22 of file BPFInstPrinter.h.
Constructor & Destructor Documentation
llvm::BPFInstPrinter::BPFInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) [inline]
Definition at line 24 of file BPFInstPrinter.h.
Member Function Documentation
static const char* llvm::BPFInstPrinter::getRegisterName (unsigned RegNo) [static]
Referenced by printMemOperand(), and printOperand().
void BPFInstPrinter::printImm64Operand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 81 of file BPFInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::MCOperand::isImm().
void BPFInstPrinter::printInst (const MCInst * MI, raw_ostream & OS, StringRef Annot, const MCSubtargetInfo & STI) [override, virtual]
Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Definition at line 29 of file BPFInstPrinter.cpp.
References llvm::MCInstPrinter::printAnnotation(), and printInstruction().
void llvm::BPFInstPrinter::printInstruction (const MCInst * MI, raw_ostream & O)
Referenced by printInst().
void BPFInstPrinter::printMemOperand (const MCInst * MI, int OpNo, raw_ostream & O, const char * Modifier = nullptr)
Definition at line 66 of file BPFInstPrinter.cpp.
References llvm::MCInstPrinter::formatDec(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), llvm::MCOperand::isImm(), and llvm::MCOperand::isReg().
void BPFInstPrinter::printOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O, const char * Modifier = nullptr)
Definition at line 52 of file BPFInstPrinter.cpp.
References llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and printExpr().
The documentation for this class was generated from the following files:
BPFInstPrinter.h
BPFInstPrinter.cpp