LLVM: llvm::MemCpyInst Class Reference
llvm::MemCpyInst Class Reference
MemCpyInst - This class wraps the llvm.memcpy intrinsic.
#include <IntrinsicInst.h>
Static Public Member Functions
static bool classof (const IntrinsicInst *I)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Detailed Description
MemCpyInst - This class wraps the llvm.memcpy intrinsic.
Definition at line 281 of file IntrinsicInst.h.
Member Function Documentation
static bool llvm::MemCpyInst::classof (const IntrinsicInst * I) [inline, static]
Reimplemented from llvm::MemTransferInst.
Definition at line 284 of file IntrinsicInst.h.
References llvm::IntrinsicInst::getIntrinsicID().
Referenced by classof().
static bool llvm::MemCpyInst::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::MemTransferInst.
Definition at line 287 of file IntrinsicInst.h.
References classof().
The documentation for this class was generated from the following file:
IntrinsicInst.h