LLVM: llvm::DIInliningInfo Class Reference
llvm::DIInliningInfo Class Reference
DIInliningInfo - a format-neutral container for inlined code description.
#include <DIContext.h>
Public Member Functions
DIInliningInfo ()
DILineInfo getFrame (unsigned Index) const
uint32_t getNumberOfFrames () const
void addFrame (const DILineInfo &Frame)
Detailed Description
DIInliningInfo - a format-neutral container for inlined code description.
Definition at line 52 of file DIContext.h.
Constructor & Destructor Documentation
llvm::DIInliningInfo::DIInliningInfo () [inline]
Definition at line 55 of file DIContext.h.
Member Function Documentation
void llvm::DIInliningInfo::addFrame (const DILineInfo & Frame) [inline]
Definition at line 63 of file DIContext.h.
References llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by llvm::PDBContext::getInliningInfoForAddress(), and llvm::DWARFContext::getInliningInfoForAddress().
DILineInfo llvm::DIInliningInfo::getFrame (unsigned Index) const [inline]
Definition at line 56 of file DIContext.h.
References llvm::SmallVectorTemplateCommon< T, typename >::size().
uint32_t llvm::DIInliningInfo::getNumberOfFrames () const [inline]
Definition at line 60 of file DIContext.h.
References llvm::SmallVectorTemplateCommon< T, typename >::size().
The documentation for this class was generated from the following file:
DIContext.h