LLVM: llvm::ByteStreamer Class Reference
llvm::ByteStreamer Class Reference
#include <ByteStreamer.h>
Public Member Functions
virtual ~ByteStreamer ()
virtual void EmitInt8 (uint8_t Byte, const Twine &Comment="")=0
virtual void EmitSLEB128 (uint64_t DWord, const Twine &Comment="")=0
virtual void EmitULEB128 (uint64_t DWord, const Twine &Comment="")=0
Detailed Description
Definition at line 26 of file ByteStreamer.h.
Constructor & Destructor Documentation
virtual llvm::ByteStreamer::~ByteStreamer () [inline, virtual]
Definition at line 28 of file ByteStreamer.h.
Member Function Documentation
virtual void llvm::ByteStreamer::EmitInt8 (uint8_t Byte, const Twine & Comment = "") [pure virtual]
Implemented in llvm::BufferByteStreamer, llvm::HashingByteStreamer, and llvm::APByteStreamer.
Referenced by llvm::DwarfDebug::emitDebugLocEntry(), and llvm::DebugLocDwarfExpression::EmitOp().
virtual void llvm::ByteStreamer::EmitSLEB128 (uint64_t DWord, const Twine & Comment = "") [pure virtual]
Implemented in llvm::BufferByteStreamer, llvm::HashingByteStreamer, and llvm::APByteStreamer.
Referenced by llvm::DebugLocDwarfExpression::EmitSigned().
virtual void llvm::ByteStreamer::EmitULEB128 (uint64_t DWord, const Twine & Comment = "") [pure virtual]
Implemented in llvm::BufferByteStreamer, llvm::HashingByteStreamer, and llvm::APByteStreamer.
Referenced by llvm::DebugLocDwarfExpression::EmitUnsigned().
The documentation for this class was generated from the following file:
ByteStreamer.h