LLVM: llvm::DILexicalBlock Class Reference
llvm::DILexicalBlock Class Reference
#include <DebugInfoMetadata.h>
Public Member Functions
DEFINE_MDNODE_GET (DILexicalBlock,(DILocalScope *Scope, DIFile *File, unsigned Line, unsigned Column),(Scope, File, Line, Column)) DEFINE_MDNODE_GET(DILexicalBlock
Metadata Metadata unsigned
unsigned Column
TempDILexicalBlock clone () const
Create a (temporary) clone of this.
unsigned getLine () const
Forwarding accessors to LexicalBlock.
unsigned getColumn () const
Static Public Member Functions
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
Public Attributes
Metadata * Scope
Metadata Metadata * File
Metadata Metadata unsigned Line
Metadata Metadata unsigned unsigned Column
Metadata Metadata unsigned unsigned Scope
Metadata Metadata unsigned unsigned File
Metadata Metadata unsigned unsigned Line
Friends
class LLVMContextImpl
class MDNode
Detailed Description
Definition at line 1457 of file DebugInfoMetadata.h.
Member Function Documentation
static bool llvm::DILexicalBlock::classof (const Metadata * MD) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::DILexicalBlockBase.
Definition at line 1501 of file DebugInfoMetadata.h.
References llvm::Metadata::DILexicalBlockKind, and llvm::Metadata::getMetadataID().
Metadata Metadata unsigned unsigned Column TempDILexicalBlock llvm::DILexicalBlock::clone () const [inline]
Create a (temporary) clone of this.
Reimplemented from llvm::MDNode.
Definition at line 1496 of file DebugInfoMetadata.h.
llvm::DILexicalBlock::DEFINE_MDNODE_GET (DILexicalBlock , (DILocalScope *Scope, DIFile *File,unsigned Line, unsigned Column) , (Scope, File, Line, Column))
unsigned llvm::DILexicalBlock::getColumn () const [inline]
Reimplemented from llvm::DILexicalBlockBase.
Definition at line 1499 of file DebugInfoMetadata.h.
Referenced by llvm::MDNodeKeyImpl< DILexicalBlock >::isKeyOf(), and WriteDILexicalBlock().
unsigned llvm::DILexicalBlock::getLine () const [inline]
Forwarding accessors to LexicalBlock.
TODO: Remove these and update code to use DILexicalBlock directly.
Reimplemented from llvm::DILexicalBlockBase.
Definition at line 1498 of file DebugInfoMetadata.h.
Referenced by llvm::MDNodeKeyImpl< DILexicalBlock >::isKeyOf(), and WriteDILexicalBlock().
Friends And Related Function Documentation
friend class LLVMContextImpl [friend]
Reimplemented from llvm::DINode.
Definition at line 1458 of file DebugInfoMetadata.h.
friend class MDNode [friend]
Reimplemented from llvm::DINode.
Definition at line 1459 of file DebugInfoMetadata.h.
Member Data Documentation
Metadata Metadata unsigned unsigned llvm::DILexicalBlock::Column
Definition at line 1492 of file DebugInfoMetadata.h.
Metadata Metadata* llvm::DILexicalBlock::File
Definition at line 1492 of file DebugInfoMetadata.h.
Metadata Metadata unsigned unsigned llvm::DILexicalBlock::File
Definition at line 1492 of file DebugInfoMetadata.h.
Metadata Metadata unsigned llvm::DILexicalBlock::Line
Definition at line 1492 of file DebugInfoMetadata.h.
Metadata Metadata unsigned unsigned llvm::DILexicalBlock::Line
Definition at line 1492 of file DebugInfoMetadata.h.
Metadata* llvm::DILexicalBlock::Scope
Definition at line 1492 of file DebugInfoMetadata.h.
Metadata Metadata unsigned unsigned llvm::DILexicalBlock::Scope
Definition at line 1492 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
DebugInfoMetadata.h
DebugInfoMetadata.cpp