LLVM: llvm::HexagonAsmInstPrinter Class Reference
llvm::HexagonAsmInstPrinter Class Reference
#include <HexagonInstPrinter.h>
Public Member Functions
HexagonAsmInstPrinter (MCInstPrinter *RawPrinter)
void printInst (MCInst const *MI, raw_ostream &O, StringRef Annot, MCSubtargetInfo const &STI) override
Print the specified MCInst to the specified raw_ostream.
void printRegName (raw_ostream &O, unsigned RegNo) const override
Print the assembler register name.
Public Attributes
std::unique_ptr< MCInstPrinter > RawPrinter
Detailed Description
Definition at line 21 of file HexagonInstPrinter.h.
Constructor & Destructor Documentation
HexagonAsmInstPrinter::HexagonAsmInstPrinter (MCInstPrinter * RawPrinter)
Definition at line 31 of file HexagonInstPrinter.cpp.
Member Function Documentation
void HexagonAsmInstPrinter::printInst (MCInst const * MI, raw_ostream & OS, StringRef Annot, MCSubtargetInfo const & STI) [override, virtual]
Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Definition at line 34 of file HexagonInstPrinter.cpp.
References llvm::HexagonMCInstrInfo::bundleSize(), HEXAGON_PACKET_SIZE, llvm::HexagonMCInstrInfo::isBundle(), RawPrinter, llvm::StringRef::rsplit(), and llvm::StringRef::split().
void HexagonAsmInstPrinter::printRegName (raw_ostream & OS, unsigned RegNo) const [override, virtual]
Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 68 of file HexagonInstPrinter.cpp.
References RawPrinter.
Member Data Documentation
std::unique_ptr<MCInstPrinter> llvm::HexagonAsmInstPrinter::RawPrinter
Definition at line 27 of file HexagonInstPrinter.h.
Referenced by printInst(), and printRegName().
The documentation for this class was generated from the following files:
HexagonInstPrinter.h
HexagonInstPrinter.cpp