LLVM: llvm::LazyCallGraph::iterator Class Reference
llvm::LazyCallGraph::iterator Class Reference
A lazy iterator used for both the entry nodes and child nodes.
#include <LazyCallGraph.h>
Public Member Functions
iterator ()
iterator & operator++ ()
reference operator* () const
Friends
class LazyCallGraph
class LazyCallGraph::Node
Detailed Description
A lazy iterator used for both the entry nodes and child nodes.
When this iterator is dereferenced, if not yet available, a function will be scanned for "calls" or uses of functions and its child information will be constructed. All of these results are accumulated and cached in the graph.
Definition at line 116 of file LazyCallGraph.h.
Constructor & Destructor Documentation
llvm::LazyCallGraph::iterator::iterator () [inline]
Definition at line 134 of file LazyCallGraph.h.
Member Function Documentation
reference llvm::LazyCallGraph::iterator::operator* () const [inline]
Reimplemented from llvm::iterator_adaptor_base< iterator, NodeVectorImplT::iterator, std::forward_iterator_tag, Node >.
Definition at line 144 of file LazyCallGraph.h.
References F(), llvm::PointerUnion< PT1, PT2 >::get(), llvm::LazyCallGraph::get(), llvm::iterator_adaptor_base< iterator, NodeVectorImplT::iterator, std::forward_iterator_tag, Node >::I, and llvm::PointerUnion< PT1, PT2 >::is().
iterator& llvm::LazyCallGraph::iterator::operator++ () [inline]
Reimplemented from llvm::iterator_adaptor_base< iterator, NodeVectorImplT::iterator, std::forward_iterator_tag, Node >.
Definition at line 137 of file LazyCallGraph.h.
References llvm::iterator_adaptor_base< iterator, NodeVectorImplT::iterator, std::forward_iterator_tag, Node >::I, and llvm::PointerUnion< PT1, PT2 >::isNull().
Friends And Related Function Documentation
friend class LazyCallGraph [friend]
Definition at line 119 of file LazyCallGraph.h.
friend class LazyCallGraph::Node [friend]
Definition at line 120 of file LazyCallGraph.h.
The documentation for this class was generated from the following file:
LazyCallGraph.h