LLVM: llvm::StringMap< ValueTy, AllocatorTy > Class Template Reference
llvm::StringMap< ValueTy, AllocatorTy > Class Template Reference
StringMap - This is an unconventional map that is specialized for handling keys that are "strings", which are basically ranges of bytes.
#include <StringMap.h>
Public Types
typedef StringMapEntry< ValueTy > MapEntryTy
typedef const char * key_type
typedef ValueTy mapped_type
typedef StringMapEntry< ValueTy > value_type
typedef size_t size_type
typedef StringMapConstIterator
< ValueTy > const_iterator
typedef StringMapIterator
< ValueTy > iterator
Public Member Functions
StringMap ()
StringMap (unsigned InitialSize)
StringMap (AllocatorTy A)
StringMap (unsigned InitialSize, AllocatorTy A)
StringMap (StringMap &&RHS)
StringMap & operator= (StringMap RHS)
AllocatorTy & getAllocator ()
const AllocatorTy & getAllocator () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
iterator find (StringRef Key)
const_iterator find (StringRef Key) const
ValueTy lookup (StringRef Key) const
lookup - Return the entry for the specified key, or a default constructed value if no such entry exists.
ValueTy & operator[] (StringRef Key)
size_type count (StringRef Key) const
count - Return 1 if the element is in the map, 0 otherwise.
bool insert (MapEntryTy *KeyValue)
insert - Insert the specified key/value pair into the map.
std::pair< iterator, bool > insert (std::pair< StringRef, ValueTy > KV)
insert - Inserts the specified key/value pair into the map if the key isn't already in the map.
void clear ()
void remove (MapEntryTy *KeyValue)
remove - Remove the specified key/value pair from the map, but do not erase it.
void erase (iterator I)
bool erase (StringRef Key)
~StringMap ()
Detailed Description
template<typename ValueTy, typename AllocatorTy = MallocAllocator>
class llvm::StringMap< ValueTy, AllocatorTy >
StringMap - This is an unconventional map that is specialized for handling keys that are "strings", which are basically ranges of bytes.
This does some funky memory allocation and hashing things to make it extremely efficient, storing the string data *after* the value in the map.
Definition at line 213 of file StringMap.h.
Member Typedef Documentation
template<typename ValueTy, typename AllocatorTy = MallocAllocator> typedef StringMapConstIterator<ValueTy> llvm::StringMap< ValueTy, AllocatorTy >::const_iterator
Definition at line 248 of file StringMap.h.
template<typename ValueTy, typename AllocatorTy = MallocAllocator> typedef StringMapIterator<ValueTy> llvm::StringMap< ValueTy, AllocatorTy >::iterator
Definition at line 249 of file StringMap.h.
template<typename ValueTy, typename AllocatorTy = MallocAllocator> typedef const char* llvm::StringMap< ValueTy, AllocatorTy >::key_type
Definition at line 243 of file StringMap.h.
template<typename ValueTy, typename AllocatorTy = MallocAllocator> typedef StringMapEntry<ValueTy> llvm::StringMap< ValueTy, AllocatorTy >::MapEntryTy
Definition at line 216 of file StringMap.h.
template<typename ValueTy, typename AllocatorTy = MallocAllocator> typedef ValueTy llvm::StringMap< ValueTy, AllocatorTy >::mapped_type
Definition at line 244 of file StringMap.h.
template<typename ValueTy, typename AllocatorTy = MallocAllocator> typedef size_t llvm::StringMap< ValueTy, AllocatorTy >::size_type
Definition at line 246 of file StringMap.h.
template<typename ValueTy, typename AllocatorTy = MallocAllocator> typedef StringMapEntry<ValueTy> llvm::StringMap< ValueTy, AllocatorTy >::value_type
Definition at line 245 of file StringMap.h.
Constructor & Destructor Documentation
template<typename ValueTy, typename AllocatorTy = MallocAllocator> llvm::StringMap< ValueTy, AllocatorTy >::StringMap () [inline]
Definition at line 218 of file StringMap.h.
template<typename ValueTy, typename AllocatorTy = MallocAllocator> llvm::StringMap< ValueTy, AllocatorTy >::StringMap (unsigned InitialSize) [inline, explicit]
Definition at line 219 of file StringMap.h.
template<typename ValueTy, typename AllocatorTy = MallocAllocator> llvm::StringMap< ValueTy, AllocatorTy >::StringMap (AllocatorTy A) [inline, explicit]
Definition at line 222 of file StringMap.h.
template<typename ValueTy, typename AllocatorTy = MallocAllocator> llvm::StringMap< ValueTy, AllocatorTy >::StringMap (unsigned InitialSize, AllocatorTy A) [inline]
Definition at line 225 of file StringMap.h.
template<typename ValueTy, typename AllocatorTy = MallocAllocator> llvm::StringMap< ValueTy, AllocatorTy >::StringMap (StringMap< ValueTy, AllocatorTy > && RHS) [inline]
Definition at line 229 of file StringMap.h.
template<typename ValueTy, typename AllocatorTy = MallocAllocator> llvm::StringMap< ValueTy, AllocatorTy >::~StringMap () [inline]
Definition at line 372 of file StringMap.h.
Member Function Documentation
template<typename ValueTy, typename AllocatorTy = MallocAllocator> iterator llvm::StringMap< ValueTy, AllocatorTy >::begin () [inline]
Definition at line 251 of file StringMap.h.
Referenced by llvm::RecordStreamer::begin(), llvm::ValueSymbolTable::end(), llvm::StringTableBuilder::finalize(), llvm::DwarfAccelTable::FinalizeTable(), llvm::ExecutionEngine::getGlobalValueAtAddress(), llvm::LLVMContext::getMDKindNames(), LookupNearestOption(), llvm::opt::OptTable::OptTable(), llvm::DwarfAccelTable::print(), llvm::RuntimeDyldImpl::resolveExternalSymbols(), sortOpts(), llvm::LLVMContextImpl::~LLVMContextImpl(), and llvm::ValueSymbolTable::~ValueSymbolTable().
template<typename ValueTy, typename AllocatorTy = MallocAllocator> const_iterator llvm::StringMap< ValueTy, AllocatorTy >::begin () const [inline]
Definition at line 257 of file StringMap.h.
template<typename ValueTy, typename AllocatorTy = MallocAllocator> void llvm::StringMap< ValueTy, AllocatorTy >::clear () [inline]
Definition at line 336 of file StringMap.h.
Referenced by llvm::StringTableBuilder::clear(), llvm::SelectionDAG::clear(), llvm::ExecutionEngine::clearAllGlobalMappings(), llvm::RuntimeDyldELF::finalizeLoad(), llvm::MCContext::reset(), llvm::LTOCodeGenerator::setModule(), and llvm::LLVMContextImpl::~LLVMContextImpl().
template<typename ValueTy, typename AllocatorTy = MallocAllocator> size_type llvm::StringMap< ValueTy, AllocatorTy >::count (StringRef Key) const [inline]
count - Return 1 if the element is in the map, 0 otherwise.
Definition at line 290 of file StringMap.h.
Referenced by llvm::StringTableBuilder::getOffset(), HandlePrefixedOrGroupedOption(), and llvm::SpecialCaseList::Entry::match().
template<typename ValueTy, typename AllocatorTy = MallocAllocator> iterator llvm::StringMap< ValueTy, AllocatorTy >::end () [inline]
Definition at line 254 of file StringMap.h.
Referenced by llvm::StringMap< uint64_t >::count(), llvm::RecordStreamer::end(), llvm::StringMap< uint64_t >::erase(), llvm::SetTheory::evaluate(), llvm::SetTheory::expand(), llvm::StringTableBuilder::finalize(), llvm::DwarfAccelTable::FinalizeTable(), llvm::StringMap< uint64_t >::find(), llvm::ExecutionEngine::getAddressToGlobalIfAvailable(), llvm::GCModuleInfo::getGCStrategy(), llvm::ExecutionEngine::getGlobalValueAtAddress(), llvm::LLVMContext::getMDKindNames(), getOptionPred(), llvm::PassRegistry::getPassInfo(), llvm::MIRParserImpl::initializeMachineFunction(), llvm::SpecialCaseList::inSection(), llvm::StringPool::intern(), llvm::StringMap< uint64_t >::lookup(), LookupNearestOption(), llvm::opt::OptTable::OptTable(), llvm::MIRParserImpl::parseMachineFunction(), llvm::DwarfAccelTable::print(), llvm::RuntimeDyldELF::processRelocationRef(), llvm::ExecutionEngineState::RemoveMapping(), llvm::orc::LocalCXXRuntimeOverrides::searchOverrides(), sortOpts(), llvm::LLVMContextImpl::~LLVMContextImpl(), and llvm::ValueSymbolTable::~ValueSymbolTable().
template<typename ValueTy, typename AllocatorTy = MallocAllocator> const_iterator llvm::StringMap< ValueTy, AllocatorTy >::end () const [inline]
Definition at line 260 of file StringMap.h.
template<typename ValueTy, typename AllocatorTy = MallocAllocator> void llvm::StringMap< ValueTy, AllocatorTy >::erase (iterator I) [inline]
Definition at line 359 of file StringMap.h.
Referenced by llvm::StringMap< uint64_t >::erase(), and llvm::ExecutionEngineState::RemoveMapping().
template<typename ValueTy, typename AllocatorTy = MallocAllocator> bool llvm::StringMap< ValueTy, AllocatorTy >::erase (StringRef Key) [inline]
Definition at line 365 of file StringMap.h.
template<typename ValueTy, typename AllocatorTy = MallocAllocator> iterator llvm::StringMap< ValueTy, AllocatorTy >::find (StringRef Key) [inline]
Definition at line 264 of file StringMap.h.
Referenced by llvm::StringMap< uint64_t >::count(), llvm::StringMap< uint64_t >::erase(), llvm::SetTheory::evaluate(), llvm::SetTheory::expand(), llvm::ExecutionEngine::getAddressToGlobalIfAvailable(), llvm::GCModuleInfo::getGCStrategy(), getOptionPred(), llvm::PassRegistry::getPassInfo(), HandlePrefixedOrGroupedOption(), llvm::MIRParserImpl::initializeMachineFunction(), llvm::SpecialCaseList::inSection(), llvm::StringPool::intern(), llvm::StringMap< uint64_t >::lookup(), llvm::MIRParserImpl::parseMachineFunction(), llvm::RuntimeDyldELF::processRelocationRef(), llvm::ExecutionEngineState::RemoveMapping(), llvm::RuntimeDyldImpl::resolveExternalSymbols(), and llvm::orc::LocalCXXRuntimeOverrides::searchOverrides().
template<typename ValueTy, typename AllocatorTy = MallocAllocator> const_iterator llvm::StringMap< ValueTy, AllocatorTy >::find (StringRef Key) const [inline]
Definition at line 270 of file StringMap.h.
template<typename ValueTy, typename AllocatorTy = MallocAllocator> AllocatorTy& llvm::StringMap< ValueTy, AllocatorTy >::getAllocator () [inline]
Definition at line 240 of file StringMap.h.
Referenced by llvm::StructType::setName().
template<typename ValueTy, typename AllocatorTy = MallocAllocator> const AllocatorTy& llvm::StringMap< ValueTy, AllocatorTy >::getAllocator () const [inline]
Definition at line 241 of file StringMap.h.
template<typename ValueTy, typename AllocatorTy = MallocAllocator> bool llvm::StringMap< ValueTy, AllocatorTy >::insert (MapEntryTy * KeyValue) [inline]
insert - Insert the specified key/value pair into the map.
If the key already exists in the map, return false and ignore the request, otherwise insert it and return true.
Definition at line 297 of file StringMap.h.
Referenced by llvm::StringTableBuilder::add(), llvm::MCContext::createELFRelSection(), llvm::DwarfStringPool::getEntry(), llvm::MCDwarfLineTableHeader::getFile(), llvm::ConstantDataSequential::getImpl(), llvm::LLVMContext::getMDKindID(), llvm::StringToOffsetTable::GetOrAddStringOffset(), llvm::MCContext::getOrCreateSectionSymbol(), llvm::Module::getOrInsertComdat(), llvm::StringPool::intern(), llvm::StringMap< uint64_t >::operator[](), llvm::MIRParserImpl::parseMachineFunction(), and llvm::StructType::setName().
template<typename ValueTy, typename AllocatorTy = MallocAllocator> std::pair<iterator, bool> llvm::StringMap< ValueTy, AllocatorTy >::insert (std::pair< StringRef, ValueTy > KV) [inline]
insert - Inserts the specified key/value pair into the map if the key isn't already in the map.
The bool component of the returned pair is true if and only if the insertion takes place, and the iterator component of the pair points to the element with key equivalent to the key of the pair.
Definition at line 317 of file StringMap.h.
template<typename ValueTy, typename AllocatorTy = MallocAllocator> ValueTy llvm::StringMap< ValueTy, AllocatorTy >::lookup (StringRef Key) const [inline]
lookup - Return the entry for the specified key, or a default constructed value if no such entry exists.
Definition at line 278 of file StringMap.h.
Referenced by llvm::ValueSymbolTable::empty(), llvm::LibCallInfo::getFunctionInfo(), llvm::Module::getTypeByName(), and llvm::MCContext::lookupSymbol().
template<typename ValueTy, typename AllocatorTy = MallocAllocator> StringMap& llvm::StringMap< ValueTy, AllocatorTy >::operator= (StringMap< ValueTy, AllocatorTy > RHS) [inline]
Definition at line 232 of file StringMap.h.
template<typename ValueTy, typename AllocatorTy = MallocAllocator> ValueTy& llvm::StringMap< ValueTy, AllocatorTy >::operator[] (StringRef Key) [inline]
Definition at line 285 of file StringMap.h.
template<typename ValueTy, typename AllocatorTy = MallocAllocator> void llvm::StringMap< ValueTy, AllocatorTy >::remove (MapEntryTy * KeyValue) [inline]
remove - Remove the specified key/value pair from the map, but do not erase it.
This aborts if the key is not in the map.
Definition at line 355 of file StringMap.h.
Referenced by llvm::StructType::setName().
The documentation for this class was generated from the following file:
StringMap.h