LLVM: llvm::LiveDebugVariables Class Reference
llvm::LiveDebugVariables Class Reference
#include <LiveDebugVariables.h>
Public Member Functions
LiveDebugVariables ()
~LiveDebugVariables () override
void renameRegister (unsigned OldReg, unsigned NewReg, unsigned SubIdx)
renameRegister - Move any user variables in OldReg to NewReg:SubIdx.
void splitRegister (unsigned OldReg, ArrayRef< unsigned > NewRegs, LiveIntervals &LIS)
splitRegister - Move any user variables in OldReg to the live ranges in NewRegs where they are live.
void emitDebugValues (VirtRegMap *VRM)
emitDebugValues - Emit new DBG_VALUE instructions reflecting the changes that happened during register allocation.
void dump ()
dump - Print data structures to dbgs().
Static Public Attributes
static char ID = 0
Detailed Description
Definition at line 34 of file LiveDebugVariables.h.
Constructor & Destructor Documentation
LiveDebugVariables::LiveDebugVariables ()
Definition at line 71 of file LiveDebugVariables.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeLiveDebugVariablesPass().
LiveDebugVariables::~LiveDebugVariables () [override]
Definition at line 780 of file LiveDebugVariables.cpp.
Member Function Documentation
void LiveDebugVariables::dump ()
dump - Print data structures to dbgs().
Definition at line 1055 of file LiveDebugVariables.cpp.
References llvm::dbgs(), and llvm::Pass::print().
void LiveDebugVariables::emitDebugValues (VirtRegMap * VRM)
emitDebugValues - Emit new DBG_VALUE instructions reflecting the changes that happened during register allocation.
Parameters:
VRM Rename virtual registers according to map.
Definition at line 1044 of file LiveDebugVariables.cpp.
void llvm::LiveDebugVariables::renameRegister (unsigned OldReg, unsigned NewReg, unsigned SubIdx)
renameRegister - Move any user variables in OldReg to NewReg:SubIdx.
Parameters:
OldReg Old virtual register that is going away.
NewReg New register holding the user variables.
SubIdx If NewReg is a virtual register, SubIdx may indicate a sub- register.
void LiveDebugVariables::splitRegister (unsigned OldReg, ArrayRef< unsigned > NewRegs, LiveIntervals & LIS)
splitRegister - Move any user variables in OldReg to the live ranges in NewRegs where they are live.
Mark the values as unavailable where no new register is live.
Definition at line 919 of file LiveDebugVariables.cpp.
Member Data Documentation
char LiveDebugVariables::ID = 0 [static]
Definition at line 39 of file LiveDebugVariables.h.
The documentation for this class was generated from the following files:
LiveDebugVariables.h
LiveDebugVariables.cpp