LLVM: llvm::ExtractValueInst Class Reference
llvm::ExtractValueInst Class Reference
ExtractValueInst - This instruction extracts a struct member or array element value from an aggregate value.
#include <Instructions.h>
Public Types
typedef const unsigned * idx_iterator
Public Member Functions
idx_iterator idx_begin () const
idx_iterator idx_end () const
iterator_range< idx_iterator > indices () const
Value * getAggregateOperand ()
const Value * getAggregateOperand () const
ArrayRef< unsigned > getIndices () const
unsigned getNumIndices () const
bool hasIndices () const
Static Public Member Functions
static ExtractValueInst * Create (Value *Agg, ArrayRef< unsigned > Idxs, const Twine &NameStr="", Instruction *InsertBefore=nullptr)
static ExtractValueInst * Create (Value *Agg, ArrayRef< unsigned > Idxs, const Twine &NameStr, BasicBlock *InsertAtEnd)
static Type * getIndexedType (Type *Agg, ArrayRef< unsigned > Idxs)
getIndexedType - Returns the type of the element that would be extracted with an extractvalue instruction with the specified parameters.
static unsigned getAggregateOperandIndex ()
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
ExtractValueInst * clone_impl () const override
Detailed Description
ExtractValueInst - This instruction extracts a struct member or array element value from an aggregate value.
Definition at line 1977 of file Instructions.h.
Member Typedef Documentation
typedef const unsigned* llvm::ExtractValueInst::idx_iterator
Definition at line 2023 of file Instructions.h.
Member Function Documentation
static bool llvm::ExtractValueInst::classof (const Instruction * I) [inline, static]
Reimplemented from llvm::UnaryInstruction.
Definition at line 2053 of file Instructions.h.
References llvm::ExtractValue, and llvm::Instruction::getOpcode().
static bool llvm::ExtractValueInst::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::UnaryInstruction.
Definition at line 2056 of file Instructions.h.
ExtractValueInst * ExtractValueInst::clone_impl () const [override, protected, virtual]
Implements llvm::Instruction.
Definition at line 3473 of file Instructions.cpp.
static ExtractValueInst* llvm::ExtractValueInst::Create (Value * Agg, ArrayRef< unsigned > Idxs, const Twine & NameStr = "", Instruction * InsertBefore = nullptr) [inline, static]
Definition at line 2003 of file Instructions.h.
Referenced by CombineUAddWithOverflow(), llvm::NoFolder::CreateExtractValue(), llvm::IRBuilder< true, TargetFolder >::CreateExtractValue(), llvm::ConstantExpr::getAsInstruction(), ProcessUGT_ADDCST_ADD(), ProcessUMulZExtIdiom(), llvm::InstCombiner::visitExtractValueInst(), and llvm::InstCombiner::visitICmpInst().
static ExtractValueInst* llvm::ExtractValueInst::Create (Value * Agg, ArrayRef< unsigned > Idxs, const Twine & NameStr, BasicBlock * InsertAtEnd) [inline, static]
Definition at line 2010 of file Instructions.h.
Value* llvm::ExtractValueInst::getAggregateOperand () [inline]
Definition at line 2030 of file Instructions.h.
Referenced by llvm::Interpreter::visitExtractValueInst(), and llvm::InstCombiner::visitExtractValueInst().
const Value* llvm::ExtractValueInst::getAggregateOperand () const [inline]
Definition at line 2033 of file Instructions.h.
static unsigned llvm::ExtractValueInst::getAggregateOperandIndex () [inline, static]
Definition at line 2036 of file Instructions.h.
Type * ExtractValueInst::getIndexedType (Type * Agg, ArrayRef< unsigned > Idxs) [static]
getIndexedType - Returns the type of the element that would be extracted with an extractvalue instruction with the specified parameters.
Null is returned if the indices are invalid for the specified type.
Definition at line 1567 of file Instructions.cpp.
References llvm::AArch64DB::ST.
Referenced by BuildSubAggregate(), llvm::FindInsertedValue(), llvm::ConstantExpr::getExtractValue(), llvm::ConstantExpr::getInsertValue(), llvm::Interpreter::visitExtractValueInst(), and llvm::Interpreter::visitInsertValueInst().
ArrayRef<unsigned> llvm::ExtractValueInst::getIndices () const [inline]
Definition at line 2040 of file Instructions.h.
Referenced by computeKnownBitsFromOperator(), llvm::FastISel::selectExtractValue(), llvm::Interpreter::visitExtractValueInst(), and llvm::InstCombiner::visitExtractValueInst().
unsigned llvm::ExtractValueInst::getNumIndices () const [inline]
Definition at line 2044 of file Instructions.h.
References llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by computeKnownBitsFromOperator(), llvm::Interpreter::visitExtractValueInst(), and llvm::InstCombiner::visitExtractValueInst().
bool llvm::ExtractValueInst::hasIndices () const [inline]
Definition at line 2048 of file Instructions.h.
Referenced by llvm::InstCombiner::visitExtractValueInst().
idx_iterator llvm::ExtractValueInst::idx_begin () const [inline]
Definition at line 2024 of file Instructions.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
Referenced by llvm::Interpreter::visitExtractValueInst(), and llvm::InstCombiner::visitExtractValueInst().
idx_iterator llvm::ExtractValueInst::idx_end () const [inline]
Definition at line 2025 of file Instructions.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by llvm::InstCombiner::visitExtractValueInst().
iterator_range<idx_iterator> llvm::ExtractValueInst::indices () const [inline]
Definition at line 2026 of file Instructions.h.
The documentation for this class was generated from the following files:
Instructions.h
Instructions.cpp