LLVM: llvm::DIAEnumSymbols Class Reference
llvm::DIAEnumSymbols Class Reference
#include <DIAEnumSymbols.h>
Public Member Functions
DIAEnumSymbols (const DIASession &Session, CComPtr< IDiaEnumSymbols > DiaEnumerator)
uint32_t getChildCount () const override
std::unique_ptr< PDBSymbol > getChildAtIndex (uint32_t Index) const override
std::unique_ptr< PDBSymbol > getNext () override
void reset () override
DIAEnumSymbols * clone () const override
Detailed Description
Definition at line 20 of file DIAEnumSymbols.h.
Constructor & Destructor Documentation
DIAEnumSymbols::DIAEnumSymbols (const DIASession & Session, CComPtr< IDiaEnumSymbols > DiaEnumerator) [explicit]
Definition at line 17 of file DIAEnumSymbols.cpp.
Referenced by clone().
Member Function Documentation
DIAEnumSymbols * DIAEnumSymbols::clone () const [override, virtual]
Implements llvm::IPDBEnumChildren< PDBSymbol >.
Definition at line 49 of file DIAEnumSymbols.cpp.
References DIAEnumSymbols().
std::unique_ptr< PDBSymbol > DIAEnumSymbols::getChildAtIndex (uint32_t Index) const [override, virtual]
Implements llvm::IPDBEnumChildren< PDBSymbol >.
Definition at line 27 of file DIAEnumSymbols.cpp.
References llvm::PDBSymbol::create().
uint32_t DIAEnumSymbols::getChildCount () const [override, virtual]
Implements llvm::IPDBEnumChildren< PDBSymbol >.
Definition at line 21 of file DIAEnumSymbols.cpp.
std::unique_ptr< PDBSymbol > DIAEnumSymbols::getNext () [override, virtual]
Implements llvm::IPDBEnumChildren< PDBSymbol >.
Definition at line 36 of file DIAEnumSymbols.cpp.
References llvm::PDBSymbol::create().
void DIAEnumSymbols::reset () [override, virtual]
Implements llvm::IPDBEnumChildren< PDBSymbol >.
Definition at line 47 of file DIAEnumSymbols.cpp.
The documentation for this class was generated from the following files:
DIAEnumSymbols.h
DIAEnumSymbols.cpp