LLVM: llvm::LoopAccessInfo Class Reference
llvm::LoopAccessInfo Class Reference
Drive the analysis of memory accesses in the loop.
#include <LoopAccessAnalysis.h>
Classes
struct RuntimePointerCheck
This struct holds information about the memory runtime legality check that a group of pointers do not overlap.
Public Member Functions
LoopAccessInfo (Loop *L, ScalarEvolution *SE, const DataLayout &DL, const TargetLibraryInfo *TLI, AliasAnalysis *AA, DominatorTree *DT, LoopInfo *LI, const ValueToValueMap &Strides)
bool canVectorizeMemory () const
Return true we can analyze the memory accesses in the loop and there are no memory dependence cycles.
const RuntimePointerCheck * getRuntimePointerCheck () const
unsigned getNumRuntimePointerChecks (const SmallVectorImpl< int > *PtrPartition=nullptr) const
Number of memchecks required to prove independence of otherwise may-alias pointers.
bool isUniform (Value *V) const
Returns true if the value V is uniform within the loop.
unsigned getMaxSafeDepDistBytes () const
unsigned getNumStores () const
unsigned getNumLoads () const
std::pair< Instruction
*, Instruction * > addRuntimeCheck (Instruction *Loc, const SmallVectorImpl< int > *PtrPartition=nullptr) const
Add code that checks at runtime if the accessed arrays overlap.
const Optional
< LoopAccessReport > & getReport () const
The diagnostics report generated for the analysis.
const MemoryDepChecker & getDepChecker () const
the Memory Dependence Checker which can determine the loop-independent and loop-carried dependences between memory accesses.
SmallVector< Instruction *, 4 > getInstructionsForAccess (Value *Ptr, bool isWrite) const
Return the list of instructions that use Ptr to read or write memory.
void print (raw_ostream &OS, unsigned Depth=0) const
Print the information about the memory accesses in the loop.
bool hasStoreToLoopInvariantAddress () const
Checks existence of store to invariant address inside loop.
Static Public Member Functions
static bool blockNeedsPredication (BasicBlock *BB, Loop *TheLoop, DominatorTree *DT)
Return true if the block BB needs to be predicated in order for the loop to be vectorized.
Public Attributes
unsigned NumSymbolicStrides
Used to ensure that if the analysis was run with speculating the value of symbolic strides, the client queries it with the same assumption.
Detailed Description
Drive the analysis of memory accesses in the loop.
This class is responsible for analyzing the memory accesses of a loop. It collects the accesses and then its main helper the AccessAnalysis class finds and categorizes the dependences in buildDependenceSets.
For memory dependences that can be analyzed at compile time, it determines whether the dependence is part of cycle inhibiting vectorization. This work is delegated to the MemoryDepChecker class.
For memory dependences that cannot be determined at compile time, it generates run-time checks to prove independence. This is done by AccessAnalysis::canCheckPtrAtRT and the checks are maintained by the RuntimePointerCheck class.
Definition at line 309 of file LoopAccessAnalysis.h.
Constructor & Destructor Documentation
LoopAccessInfo::LoopAccessInfo (Loop * L, ScalarEvolution * SE, const DataLayout & DL, const TargetLibraryInfo * TLI, AliasAnalysis * AA, DominatorTree * DT, LoopInfo * LI, const ValueToValueMap & Strides)
Definition at line 1397 of file LoopAccessAnalysis.cpp.
Member Function Documentation
std::pair< Instruction *, Instruction * > LoopAccessInfo::addRuntimeCheck (Instruction * Loc, const SmallVectorImpl< int > * PtrPartition = nullptr) const
Add code that checks at runtime if the accessed arrays overlap.
Returns a pair of instructions where the first element is the first instruction generated in possibly a sequence of instructions and the second value is the final comparator value or NULL if no check is needed.
If PtrPartition is set, it contains the partition number for pointers (-1 if the pointer belongs to multiple partitions). In this case omit checks between pointers belonging to the same partition.
Definition at line 1310 of file LoopAccessAnalysis.cpp.
References llvm::Check(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateAnd(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateBitCast(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmpULE(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateOr(), llvm::dbgs(), DEBUG, llvm::LoopAccessInfo::RuntimePointerCheck::Ends, llvm::SCEVExpander::expandCodeFor(), llvm::Value::getContext(), getFirstInst(), llvm::Type::getInt8PtrTy(), llvm::Type::getPointerAddressSpace(), llvm::ScalarEvolution::getSCEV(), llvm::ConstantInt::getTrue(), llvm::Intrinsic::getType(), llvm::Value::getType(), llvm::IRBuilder< preserveNames, T, Inserter >::Insert(), llvm::ScalarEvolution::isLoopInvariant(), llvm::LoopAccessInfo::RuntimePointerCheck::Need, llvm::LoopAccessInfo::RuntimePointerCheck::needsChecking(), llvm::LoopAccessInfo::RuntimePointerCheck::Pointers, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::LoopAccessInfo::RuntimePointerCheck::Starts.
bool LoopAccessInfo::blockNeedsPredication (BasicBlock * BB, Loop * TheLoop, DominatorTree * DT) [static]
Return true if the block BB needs to be predicated in order for the loop to be vectorized.
Definition at line 1281 of file LoopAccessAnalysis.cpp.
References llvm::LoopBase< BlockT, LoopT >::contains(), llvm::DominatorTree::dominates(), and llvm::LoopBase< BlockT, LoopT >::getLoopLatch().
bool llvm::LoopAccessInfo::canVectorizeMemory () const [inline]
Return true we can analyze the memory accesses in the loop and there are no memory dependence cycles.
Definition at line 384 of file LoopAccessAnalysis.h.
const MemoryDepChecker& llvm::LoopAccessInfo::getDepChecker () const [inline]
the Memory Dependence Checker which can determine the loop-independent and loop-carried dependences between memory accesses.
Definition at line 428 of file LoopAccessAnalysis.h.
SmallVector<Instruction *, 4> llvm::LoopAccessInfo::getInstructionsForAccess (Value * Ptr, bool isWrite) const [inline]
Return the list of instructions that use Ptr to read or write memory.
Definition at line 432 of file LoopAccessAnalysis.h.
References llvm::MemoryDepChecker::getInstructionsForAccess().
unsigned llvm::LoopAccessInfo::getMaxSafeDepDistBytes () const [inline]
Definition at line 405 of file LoopAccessAnalysis.h.
unsigned llvm::LoopAccessInfo::getNumLoads () const [inline]
Definition at line 407 of file LoopAccessAnalysis.h.
unsigned llvm::LoopAccessInfo::getNumRuntimePointerChecks (const SmallVectorImpl< int > * PtrPartition = nullptr) const [inline]
Number of memchecks required to prove independence of otherwise may-alias pointers.
Definition at line 392 of file LoopAccessAnalysis.h.
References llvm::LoopAccessInfo::RuntimePointerCheck::getNumberOfChecks().
unsigned llvm::LoopAccessInfo::getNumStores () const [inline]
Definition at line 406 of file LoopAccessAnalysis.h.
const Optional<LoopAccessReport>& llvm::LoopAccessInfo::getReport () const [inline]
The diagnostics report generated for the analysis.
E.g. why we couldn't analyze the loop.
Definition at line 424 of file LoopAccessAnalysis.h.
const RuntimePointerCheck* llvm::LoopAccessInfo::getRuntimePointerCheck () const [inline]
Definition at line 386 of file LoopAccessAnalysis.h.
bool llvm::LoopAccessInfo::hasStoreToLoopInvariantAddress () const [inline]
Checks existence of store to invariant address inside loop.
If the loop has any store to invariant address, then it returns true, else returns false.
Definition at line 448 of file LoopAccessAnalysis.h.
bool LoopAccessInfo::isUniform (Value * V) const
Returns true if the value V is uniform within the loop.
Definition at line 1295 of file LoopAccessAnalysis.cpp.
References llvm::ScalarEvolution::getSCEV(), and llvm::ScalarEvolution::isLoopInvariant().
void LoopAccessInfo::print (raw_ostream & OS, unsigned Depth = 0) const
Print the information about the memory accesses in the loop.
Definition at line 1410 of file LoopAccessAnalysis.cpp.
References llvm::MemoryDepChecker::getInterestingDependences(), llvm::MemoryDepChecker::getMemoryInstructions(), llvm::raw_ostream::indent(), llvm::LoopAccessInfo::RuntimePointerCheck::Need, llvm::LoopAccessInfo::RuntimePointerCheck::print(), and llvm::LoopAccessReport::str().
Referenced by llvm::LoopAccessAnalysis::print().
Member Data Documentation
unsigned llvm::LoopAccessInfo::NumSymbolicStrides
Used to ensure that if the analysis was run with speculating the value of symbolic strides, the client queries it with the same assumption.
Only used in DEBUG build but we don't want NDEBUG-dependent ABI.
Definition at line 443 of file LoopAccessAnalysis.h.
The documentation for this class was generated from the following files:
LoopAccessAnalysis.h
LoopAccessAnalysis.cpp