LLVM: llvm::MemSetInst Class Reference
llvm::MemSetInst Class Reference
MemSetInst - This class wraps the llvm.memset intrinsic.
#include <IntrinsicInst.h>
Public Member Functions
Value * getValue () const
get* - Return the arguments to the instruction.
const Use & getValueUse () const
Use & getValueUse ()
void setValue (Value *Val)
Static Public Member Functions
static bool classof (const IntrinsicInst *I)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Detailed Description
MemSetInst - This class wraps the llvm.memset intrinsic.
Definition at line 220 of file IntrinsicInst.h.
Member Function Documentation
static bool llvm::MemSetInst::classof (const IntrinsicInst * I) [inline, static]
Reimplemented from llvm::MemIntrinsic.
Definition at line 235 of file IntrinsicInst.h.
References llvm::IntrinsicInst::getIntrinsicID().
Referenced by classof().
static bool llvm::MemSetInst::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::MemIntrinsic.
Definition at line 238 of file IntrinsicInst.h.
References classof().
Value* llvm::MemSetInst::getValue () const [inline]
get* - Return the arguments to the instruction.
Definition at line 224 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperand().
Referenced by setValue().
const Use& llvm::MemSetInst::getValueUse () const [inline]
Definition at line 225 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperandUse().
Use& llvm::MemSetInst::getValueUse () [inline]
Definition at line 226 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperandUse().
void llvm::MemSetInst::setValue (Value * Val) [inline]
Definition at line 228 of file IntrinsicInst.h.
References llvm::Value::getType(), getValue(), and llvm::CallInst::setArgOperand().
The documentation for this class was generated from the following file:
IntrinsicInst.h