LLVM: llvm::X86MachineFunctionInfo Class Reference
llvm::X86MachineFunctionInfo Class Reference
X86MachineFunctionInfo - This class is derived from MachineFunction and contains private X86 target-specific information for each MachineFunction.
#include <X86MachineFunctionInfo.h>
Public Member Functions
X86MachineFunctionInfo ()
X86MachineFunctionInfo (MachineFunction &MF)
bool getForceFramePointer () const
void setForceFramePointer (bool forceFP)
bool getHasPushSequences () const
void setHasPushSequences (bool HasPush)
bool getRestoreBasePointer () const
void setRestoreBasePointer (const MachineFunction *MF)
int getRestoreBasePointerOffset () const
unsigned getCalleeSavedFrameSize () const
void setCalleeSavedFrameSize (unsigned bytes)
unsigned getBytesToPopOnReturn () const
void setBytesToPopOnReturn (unsigned bytes)
int getRAIndex () const
void setRAIndex (int Index)
int getFAIndex () const
void setFAIndex (int Index)
int getTCReturnAddrDelta () const
void setTCReturnAddrDelta (int delta)
unsigned getSRetReturnReg () const
void setSRetReturnReg (unsigned Reg)
unsigned getGlobalBaseReg () const
void setGlobalBaseReg (unsigned Reg)
int getVarArgsFrameIndex () const
void setVarArgsFrameIndex (int Idx)
int getRegSaveFrameIndex () const
void setRegSaveFrameIndex (int Idx)
unsigned getVarArgsGPOffset () const
void setVarArgsGPOffset (unsigned Offset)
unsigned getVarArgsFPOffset () const
void setVarArgsFPOffset (unsigned Offset)
unsigned getArgumentStackSize () const
void setArgumentStackSize (unsigned size)
unsigned getNumLocalDynamicTLSAccesses () const
void incNumLocalDynamicTLSAccesses ()
SmallVectorImpl
< ForwardedRegister > & getForwardedMustTailRegParms ()
Detailed Description
X86MachineFunctionInfo - This class is derived from MachineFunction and contains private X86 target-specific information for each MachineFunction.
Definition at line 26 of file X86MachineFunctionInfo.h.
Constructor & Destructor Documentation
llvm::X86MachineFunctionInfo::X86MachineFunctionInfo () [inline]
Definition at line 93 of file X86MachineFunctionInfo.h.
llvm::X86MachineFunctionInfo::X86MachineFunctionInfo (MachineFunction & MF) [inline, explicit]
Definition at line 110 of file X86MachineFunctionInfo.h.
Member Function Documentation
unsigned llvm::X86MachineFunctionInfo::getArgumentStackSize () const [inline]
Definition at line 171 of file X86MachineFunctionInfo.h.
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks().
unsigned llvm::X86MachineFunctionInfo::getBytesToPopOnReturn () const [inline]
Definition at line 141 of file X86MachineFunctionInfo.h.
unsigned llvm::X86MachineFunctionInfo::getCalleeSavedFrameSize () const [inline]
Definition at line 138 of file X86MachineFunctionInfo.h.
Referenced by llvm::X86FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitPrologue(), and llvm::X86FrameLowering::getFrameIndexOffset().
int llvm::X86MachineFunctionInfo::getFAIndex () const [inline]
Definition at line 147 of file X86MachineFunctionInfo.h.
Referenced by llvm::X86FrameLowering::getFrameIndexOffset(), and LowerINTRINSIC_W_CHAIN().
bool llvm::X86MachineFunctionInfo::getForceFramePointer () const [inline]
Definition at line 128 of file X86MachineFunctionInfo.h.
SmallVectorImpl<ForwardedRegister>& llvm::X86MachineFunctionInfo::getForwardedMustTailRegParms () [inline]
Definition at line 177 of file X86MachineFunctionInfo.h.
unsigned llvm::X86MachineFunctionInfo::getGlobalBaseReg () const [inline]
Definition at line 156 of file X86MachineFunctionInfo.h.
bool llvm::X86MachineFunctionInfo::getHasPushSequences () const [inline]
Definition at line 131 of file X86MachineFunctionInfo.h.
unsigned llvm::X86MachineFunctionInfo::getNumLocalDynamicTLSAccesses () const [inline]
Definition at line 174 of file X86MachineFunctionInfo.h.
int llvm::X86MachineFunctionInfo::getRAIndex () const [inline]
Definition at line 144 of file X86MachineFunctionInfo.h.
int llvm::X86MachineFunctionInfo::getRegSaveFrameIndex () const [inline]
Definition at line 162 of file X86MachineFunctionInfo.h.
bool llvm::X86MachineFunctionInfo::getRestoreBasePointer () const [inline]
Definition at line 134 of file X86MachineFunctionInfo.h.
Referenced by llvm::X86FrameLowering::emitPrologue(), and llvm::X86FrameLowering::getFrameIndexOffset().
int llvm::X86MachineFunctionInfo::getRestoreBasePointerOffset () const [inline]
Definition at line 136 of file X86MachineFunctionInfo.h.
Referenced by llvm::X86FrameLowering::emitPrologue().
unsigned llvm::X86MachineFunctionInfo::getSRetReturnReg () const [inline]
Definition at line 153 of file X86MachineFunctionInfo.h.
int llvm::X86MachineFunctionInfo::getTCReturnAddrDelta () const [inline]
Definition at line 150 of file X86MachineFunctionInfo.h.
Referenced by llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), llvm::X86FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitPrologue(), llvm::X86FrameLowering::getFrameIndexOffset(), and llvm::X86FrameLowering::processFunctionBeforeCalleeSavedScan().
unsigned llvm::X86MachineFunctionInfo::getVarArgsFPOffset () const [inline]
Definition at line 168 of file X86MachineFunctionInfo.h.
int llvm::X86MachineFunctionInfo::getVarArgsFrameIndex () const [inline]
Definition at line 159 of file X86MachineFunctionInfo.h.
unsigned llvm::X86MachineFunctionInfo::getVarArgsGPOffset () const [inline]
Definition at line 165 of file X86MachineFunctionInfo.h.
void llvm::X86MachineFunctionInfo::incNumLocalDynamicTLSAccesses () [inline]
Definition at line 175 of file X86MachineFunctionInfo.h.
Referenced by LowerToTLSLocalDynamicModel().
void llvm::X86MachineFunctionInfo::setArgumentStackSize (unsigned size) [inline]
Definition at line 172 of file X86MachineFunctionInfo.h.
References size.
void llvm::X86MachineFunctionInfo::setBytesToPopOnReturn (unsigned bytes) [inline]
Definition at line 142 of file X86MachineFunctionInfo.h.
void llvm::X86MachineFunctionInfo::setCalleeSavedFrameSize (unsigned bytes) [inline]
Definition at line 139 of file X86MachineFunctionInfo.h.
Referenced by llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), and llvm::X86FrameLowering::emitPrologue().
void llvm::X86MachineFunctionInfo::setFAIndex (int Index) [inline]
Definition at line 148 of file X86MachineFunctionInfo.h.
Referenced by LowerINTRINSIC_W_CHAIN().
void llvm::X86MachineFunctionInfo::setForceFramePointer (bool forceFP) [inline]
Definition at line 129 of file X86MachineFunctionInfo.h.
void llvm::X86MachineFunctionInfo::setGlobalBaseReg (unsigned Reg) [inline]
Definition at line 157 of file X86MachineFunctionInfo.h.
void llvm::X86MachineFunctionInfo::setHasPushSequences (bool HasPush) [inline]
Definition at line 132 of file X86MachineFunctionInfo.h.
void llvm::X86MachineFunctionInfo::setRAIndex (int Index) [inline]
Definition at line 145 of file X86MachineFunctionInfo.h.
void llvm::X86MachineFunctionInfo::setRegSaveFrameIndex (int Idx) [inline]
Definition at line 163 of file X86MachineFunctionInfo.h.
void X86MachineFunctionInfo::setRestoreBasePointer (const MachineFunction * MF)
Definition at line 18 of file X86MachineFunctionInfo.cpp.
References contains(), llvm::TargetSubtargetInfo::getRegisterInfo(), and llvm::MachineFunction::getSubtarget().
void llvm::X86MachineFunctionInfo::setSRetReturnReg (unsigned Reg) [inline]
Definition at line 154 of file X86MachineFunctionInfo.h.
void llvm::X86MachineFunctionInfo::setTCReturnAddrDelta (int delta) [inline]
Definition at line 151 of file X86MachineFunctionInfo.h.
void llvm::X86MachineFunctionInfo::setVarArgsFPOffset (unsigned Offset) [inline]
Definition at line 169 of file X86MachineFunctionInfo.h.
void llvm::X86MachineFunctionInfo::setVarArgsFrameIndex (int Idx) [inline]
Definition at line 160 of file X86MachineFunctionInfo.h.
void llvm::X86MachineFunctionInfo::setVarArgsGPOffset (unsigned Offset) [inline]
Definition at line 166 of file X86MachineFunctionInfo.h.
The documentation for this class was generated from the following files:
X86MachineFunctionInfo.h
X86MachineFunctionInfo.cpp