LLVM: llvm::DbgValueHistoryMap Class Reference
llvm::DbgValueHistoryMap Class Reference
#include <DbgValueHistoryCalculator.h>
Public Types
typedef std::pair< const
MachineInstr *, const
MachineInstr * > InstrRange
typedef SmallVector
< InstrRange, 4 > InstrRanges
typedef std::pair< const
DILocalVariable *, const
DILocation * > InlinedVariable
typedef MapVector
< InlinedVariable, InstrRanges > InstrRangesMap
Public Member Functions
void startInstrRange (InlinedVariable Var, const MachineInstr &MI)
void endInstrRange (InlinedVariable Var, const MachineInstr &MI)
unsigned getRegisterForVar (InlinedVariable Var) const
bool empty () const
void clear ()
InstrRangesMap::const_iterator begin () const
InstrRangesMap::const_iterator end () const
Detailed Description
Definition at line 26 of file DbgValueHistoryCalculator.h.
Member Typedef Documentation
typedef std::pair<const DILocalVariable *, const DILocation *> llvm::DbgValueHistoryMap::InlinedVariable
Definition at line 36 of file DbgValueHistoryCalculator.h.
typedef std::pair<const MachineInstr *, const MachineInstr *> llvm::DbgValueHistoryMap::InstrRange
Definition at line 33 of file DbgValueHistoryCalculator.h.
typedef SmallVector<InstrRange, 4> llvm::DbgValueHistoryMap::InstrRanges
Definition at line 34 of file DbgValueHistoryCalculator.h.
typedef MapVector<InlinedVariable, InstrRanges> llvm::DbgValueHistoryMap::InstrRangesMap
Definition at line 37 of file DbgValueHistoryCalculator.h.
Member Function Documentation
InstrRangesMap::const_iterator llvm::DbgValueHistoryMap::begin () const [inline]
Definition at line 51 of file DbgValueHistoryCalculator.h.
References llvm::MapVector< KeyT, ValueT, MapType, VectorType >::begin().
void llvm::DbgValueHistoryMap::clear () [inline]
Definition at line 50 of file DbgValueHistoryCalculator.h.
References llvm::MapVector< KeyT, ValueT, MapType, VectorType >::clear().
bool llvm::DbgValueHistoryMap::empty () const [inline]
Definition at line 49 of file DbgValueHistoryCalculator.h.
References llvm::MapVector< KeyT, ValueT, MapType, VectorType >::empty().
InstrRangesMap::const_iterator llvm::DbgValueHistoryMap::end () const [inline]
Definition at line 52 of file DbgValueHistoryCalculator.h.
References llvm::MapVector< KeyT, ValueT, MapType, VectorType >::end().
void DbgValueHistoryMap::endInstrRange (InlinedVariable Var, const MachineInstr & MI)
Definition at line 51 of file DbgValueHistoryCalculator.cpp.
References llvm::MachineInstr::getParent(), llvm::AArch64CC::MI, and Ranges.
Referenced by clobberRegisterUses().
unsigned DbgValueHistoryMap::getRegisterForVar (InlinedVariable Var) const
Definition at line 62 of file DbgValueHistoryCalculator.cpp.
References llvm::MapVector< KeyT, ValueT, MapType, VectorType >::end(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::find(), I, isDescribedByReg(), and Ranges.
Referenced by llvm::calculateDbgValueHistory().
void DbgValueHistoryMap::startInstrRange (InlinedVariable Var, const MachineInstr & MI)
Definition at line 36 of file DbgValueHistoryCalculator.cpp.
References llvm::dbgs(), DEBUG, llvm::MachineInstr::isDebugValue(), and Ranges.
Referenced by llvm::calculateDbgValueHistory().
The documentation for this class was generated from the following files:
DbgValueHistoryCalculator.h
DbgValueHistoryCalculator.cpp