LLVM: llvm::MemIntrinsic Class Reference
llvm::MemIntrinsic Class Reference
MemIntrinsic - This is the common base class for memset/memcpy/memmove.
#include <IntrinsicInst.h>
Public Member Functions
Value * getRawDest () const
const Use & getRawDestUse () const
Use & getRawDestUse ()
Value * getLength () const
const Use & getLengthUse () const
Use & getLengthUse ()
ConstantInt * getAlignmentCst () const
unsigned getAlignment () const
ConstantInt * getVolatileCst () const
bool isVolatile () const
unsigned getDestAddressSpace () const
Value * getDest () const
getDest - This is just like getRawDest, but it strips off any cast instructions that feed it, giving the original input.
void setDest (Value *Ptr)
set* - Set the specified arguments of the instruction.
void setLength (Value *L)
void setAlignment (Constant *A)
void setVolatile (Constant *V)
Type * getAlignmentType () const
Static Public Member Functions
static bool classof (const IntrinsicInst *I)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Detailed Description
MemIntrinsic - This is the common base class for memset/memcpy/memmove.
Definition at line 143 of file IntrinsicInst.h.
Member Function Documentation
static bool llvm::MemIntrinsic::classof (const IntrinsicInst * I) [inline, static]
Reimplemented in llvm::MemMoveInst, llvm::MemCpyInst, llvm::MemTransferInst, and llvm::MemSetInst.
Definition at line 204 of file IntrinsicInst.h.
References llvm::IntrinsicInst::getIntrinsicID().
Referenced by classof().
static bool llvm::MemIntrinsic::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::IntrinsicInst.
Reimplemented in llvm::MemMoveInst, llvm::MemCpyInst, llvm::MemTransferInst, and llvm::MemSetInst.
Definition at line 213 of file IntrinsicInst.h.
References classof().
unsigned llvm::MemIntrinsic::getAlignment () const [inline]
Definition at line 157 of file IntrinsicInst.h.
References getAlignmentCst(), and llvm::ConstantInt::getZExtValue().
ConstantInt* llvm::MemIntrinsic::getAlignmentCst () const [inline]
Definition at line 153 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperand().
Referenced by getAlignment().
Type* llvm::MemIntrinsic::getAlignmentType () const [inline]
Definition at line 199 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperand(), and llvm::Value::getType().
Value* llvm::MemIntrinsic::getDest () const [inline]
getDest - This is just like getRawDest, but it strips off any cast instructions that feed it, giving the original input.
The returned value is guaranteed to be a pointer.
Definition at line 175 of file IntrinsicInst.h.
References getRawDest(), and llvm::Value::stripPointerCasts().
Referenced by AnalyzeLoadFromClobberingMemInst().
unsigned llvm::MemIntrinsic::getDestAddressSpace () const [inline]
Definition at line 168 of file IntrinsicInst.h.
References getRawDest(), and llvm::Value::getType().
Value* llvm::MemIntrinsic::getLength () const [inline]
Definition at line 149 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperand().
Referenced by AnalyzeLoadFromClobberingMemInst(), llvm::MemoryLocation::getForDest(), llvm::MemoryLocation::getForSource(), and setLength().
const Use& llvm::MemIntrinsic::getLengthUse () const [inline]
Definition at line 150 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperandUse().
Use& llvm::MemIntrinsic::getLengthUse () [inline]
Definition at line 151 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperandUse().
Value* llvm::MemIntrinsic::getRawDest () const [inline]
Definition at line 145 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperand().
Referenced by getDest(), getDestAddressSpace(), llvm::MemoryLocation::getForDest(), isAllocSiteRemovable(), and setDest().
const Use& llvm::MemIntrinsic::getRawDestUse () const [inline]
Definition at line 146 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperandUse().
Use& llvm::MemIntrinsic::getRawDestUse () [inline]
Definition at line 147 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperandUse().
ConstantInt* llvm::MemIntrinsic::getVolatileCst () const [inline]
Definition at line 161 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperand().
Referenced by isVolatile().
bool llvm::MemIntrinsic::isVolatile () const [inline]
Definition at line 164 of file IntrinsicInst.h.
References getVolatileCst(), and llvm::ConstantInt::isZero().
Referenced by isAllocSiteRemovable(), and isOnlyCopiedFromConstantGlobal().
void llvm::MemIntrinsic::setAlignment (Constant * A) [inline]
Definition at line 191 of file IntrinsicInst.h.
References llvm::CallInst::setArgOperand().
void llvm::MemIntrinsic::setDest (Value * Ptr) [inline]
set* - Set the specified arguments of the instruction.
Definition at line 179 of file IntrinsicInst.h.
References getRawDest(), llvm::Value::getType(), and llvm::CallInst::setArgOperand().
void llvm::MemIntrinsic::setLength (Value * L) [inline]
Definition at line 185 of file IntrinsicInst.h.
References getLength(), llvm::Value::getType(), and llvm::CallInst::setArgOperand().
void llvm::MemIntrinsic::setVolatile (Constant * V) [inline]
Definition at line 195 of file IntrinsicInst.h.
References llvm::CallInst::setArgOperand().
The documentation for this class was generated from the following file:
IntrinsicInst.h