LLVM: llvm::HexagonTargetObjectFile Class Reference
llvm::HexagonTargetObjectFile Class Reference
#include <HexagonTargetObjectFile.h>
Public Member Functions
void Initialize (MCContext &Ctx, const TargetMachine &TM) override
This method must be called before any actual lowering is done.
bool IsGlobalInSmallSection (const GlobalValue *GV, const TargetMachine &TM, SectionKind Kind) const
IsGlobalInSmallSection - Return true if this global address should be placed into small data/bss section.
bool IsGlobalInSmallSection (const GlobalValue *GV, const TargetMachine &TM) const
IsGlobalInSmallSection - Return true if this global value should be placed into small data/bss section.
bool IsSmallDataEnabled () const
MCSection * SelectSectionForGlobal (const GlobalValue *GV, SectionKind Kind, Mangler &Mang, const TargetMachine &TM) const override
Detailed Description
Definition at line 18 of file HexagonTargetObjectFile.h.
Member Function Documentation
void HexagonTargetObjectFile::Initialize (MCContext & ctx, const TargetMachine & TM) [override, virtual]
This method must be called before any actual lowering is done.
Initialize - this method must be called before any actual lowering is done.
This specifies the current context for codegen, and gives the lowering implementations a chance to set up their default sections.
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 31 of file HexagonTargetObjectFile.cpp.
References llvm::TargetLoweringObjectFile::getContext(), llvm::MCContext::getELFSection(), llvm::TargetLoweringObjectFileELF::InitializeELF(), llvm::TargetMachine::Options, llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_WRITE, llvm::ELF::SHT_NOBITS, llvm::ELF::SHT_PROGBITS, and llvm::TargetOptions::UseInitArray.
bool HexagonTargetObjectFile::IsGlobalInSmallSection (const GlobalValue * GV, const TargetMachine & TM, SectionKind Kind) const
IsGlobalInSmallSection - Return true if this global address should be placed into small data/bss section.
IsGlobalInSmallSection - Return true if this global value should be placed into small data/bss section.
Definition at line 69 of file HexagonTargetObjectFile.cpp.
References llvm::dyn_cast(), llvm::TargetMachine::getDataLayout(), llvm::SequentialType::getElementType(), llvm::GlobalValue::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::SectionKind::isBSS(), llvm::SectionKind::isCommon(), llvm::SectionKind::isDataNoRel(), and IsInSmallSection().
Referenced by IsGlobalInSmallSection(), llvm::HexagonTargetLowering::LowerGLOBALADDRESS(), and SelectSectionForGlobal().
bool HexagonTargetObjectFile::IsGlobalInSmallSection (const GlobalValue * GV, const TargetMachine & TM) const
IsGlobalInSmallSection - Return true if this global value should be placed into small data/bss section.
Definition at line 53 of file HexagonTargetObjectFile.cpp.
References llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::GlobalValue::hasAvailableExternallyLinkage(), llvm::GlobalValue::isDeclaration(), and IsGlobalInSmallSection().
bool HexagonTargetObjectFile::IsSmallDataEnabled () const
Definition at line 47 of file HexagonTargetObjectFile.cpp.
References SmallDataThreshold.
MCSection * HexagonTargetObjectFile::SelectSectionForGlobal (const GlobalValue * GV, SectionKind Kind, Mangler & Mang, const TargetMachine & TM) const [override, virtual]
Reimplemented from llvm::TargetLoweringObjectFileELF.
Definition at line 85 of file HexagonTargetObjectFile.cpp.
References llvm::SectionKind::isBSS(), llvm::SectionKind::isDataNoRel(), and IsGlobalInSmallSection().
The documentation for this class was generated from the following files:
HexagonTargetObjectFile.h
HexagonTargetObjectFile.cpp