LLVM: llvm::SystemZSubtarget Class Reference
llvm::SystemZSubtarget Class Reference
#include <SystemZSubtarget.h>
Public Member Functions
SystemZSubtarget (const Triple &TT, const std::string &CPU, const std::string &FS, const TargetMachine &TM)
const TargetFrameLowering * getFrameLowering () const override
const SystemZInstrInfo * getInstrInfo () const override
const SystemZRegisterInfo * getRegisterInfo () const override
const SystemZTargetLowering * getTargetLowering () const override
const TargetSelectionDAGInfo * getSelectionDAGInfo () const override
bool useAA () const override
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
bool hasDistinctOps () const
bool hasLoadStoreOnCond () const
bool hasHighWord () const
bool hasFPExtension () const
bool hasPopulationCount () const
bool hasFastSerialization () const
bool hasInterlockedAccess1 () const
bool hasMiscellaneousExtensions () const
bool hasTransactionalExecution () const
bool hasProcessorAssist () const
bool hasVector () const
bool isPC32DBLSymbol (const GlobalValue *GV, Reloc::Model RM, CodeModel::Model CM) const
bool isTargetELF () const
Protected Attributes
bool HasDistinctOps
bool HasLoadStoreOnCond
bool HasHighWord
bool HasFPExtension
bool HasPopulationCount
bool HasFastSerialization
bool HasInterlockedAccess1
bool HasMiscellaneousExtensions
bool HasTransactionalExecution
bool HasProcessorAssist
bool HasVector
Detailed Description
Definition at line 34 of file SystemZSubtarget.h.
Constructor & Destructor Documentation
SystemZSubtarget::SystemZSubtarget (const Triple & TT, const std::string & CPU, const std::string & FS, const TargetMachine & TM)
Definition at line 35 of file SystemZSubtarget.cpp.
Member Function Documentation
const TargetFrameLowering* llvm::SystemZSubtarget::getFrameLowering () const [inline, override]
Definition at line 62 of file SystemZSubtarget.h.
Referenced by llvm::SystemZTargetLowering::LowerFormalArguments().
const SystemZInstrInfo* llvm::SystemZSubtarget::getInstrInfo () const [inline, override]
Definition at line 65 of file SystemZSubtarget.h.
Referenced by llvm::SystemZTTIImpl::getIntImmCost().
const SystemZRegisterInfo* llvm::SystemZSubtarget::getRegisterInfo () const [inline, override]
Definition at line 66 of file SystemZSubtarget.h.
References llvm::SystemZInstrInfo::getRegisterInfo().
Referenced by llvm::SystemZTargetLowering::LowerCall(), and llvm::SystemZTargetLowering::SystemZTargetLowering().
const TargetSelectionDAGInfo* llvm::SystemZSubtarget::getSelectionDAGInfo () const [inline, override]
Definition at line 72 of file SystemZSubtarget.h.
const SystemZTargetLowering* llvm::SystemZSubtarget::getTargetLowering () const [inline, override]
Definition at line 69 of file SystemZSubtarget.h.
bool llvm::SystemZSubtarget::hasDistinctOps () const [inline]
Definition at line 83 of file SystemZSubtarget.h.
References HasDistinctOps.
Referenced by llvm::SystemZInstrInfo::convertToThreeAddress().
bool llvm::SystemZSubtarget::hasFastSerialization () const [inline]
Definition at line 98 of file SystemZSubtarget.h.
References HasFastSerialization.
Referenced by llvm::SystemZAsmPrinter::EmitInstruction().
bool llvm::SystemZSubtarget::hasFPExtension () const [inline]
Definition at line 92 of file SystemZSubtarget.h.
References HasFPExtension.
Referenced by llvm::SystemZTargetLowering::SystemZTargetLowering().
bool llvm::SystemZSubtarget::hasHighWord () const [inline]
Definition at line 89 of file SystemZSubtarget.h.
References HasHighWord.
Referenced by llvm::SystemZTargetLowering::SystemZTargetLowering().
bool llvm::SystemZSubtarget::hasInterlockedAccess1 () const [inline]
Definition at line 101 of file SystemZSubtarget.h.
References HasInterlockedAccess1.
bool llvm::SystemZSubtarget::hasLoadStoreOnCond () const [inline]
Definition at line 86 of file SystemZSubtarget.h.
References HasLoadStoreOnCond.
Referenced by llvm::SystemZInstrInfo::isPredicable(), and llvm::SystemZInstrInfo::PredicateInstruction().
bool llvm::SystemZSubtarget::hasMiscellaneousExtensions () const [inline]
Definition at line 104 of file SystemZSubtarget.h.
References HasMiscellaneousExtensions.
Referenced by llvm::SystemZInstrInfo::convertToThreeAddress().
bool llvm::SystemZSubtarget::hasPopulationCount () const [inline]
Definition at line 95 of file SystemZSubtarget.h.
References HasPopulationCount.
Referenced by llvm::SystemZTTIImpl::getPopcntSupport(), and llvm::SystemZTargetLowering::SystemZTargetLowering().
bool llvm::SystemZSubtarget::hasProcessorAssist () const [inline]
Definition at line 112 of file SystemZSubtarget.h.
References HasProcessorAssist.
bool llvm::SystemZSubtarget::hasTransactionalExecution () const [inline]
Definition at line 109 of file SystemZSubtarget.h.
References HasTransactionalExecution.
bool llvm::SystemZSubtarget::hasVector () const [inline]
Definition at line 115 of file SystemZSubtarget.h.
References HasVector.
Referenced by llvm::SystemZTTIImpl::getNumberOfRegisters(), llvm::SystemZTTIImpl::getRegisterBitWidth(), llvm::SystemZTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerReturn(), and llvm::SystemZTargetLowering::SystemZTargetLowering().
bool SystemZSubtarget::isPC32DBLSymbol (const GlobalValue * GV, Reloc::Model RM, CodeModel::Model CM) const
Definition at line 56 of file SystemZSubtarget.cpp.
References bindsLocally(), llvm::GlobalValue::getAlignment(), and llvm::CodeModel::Small.
bool llvm::SystemZSubtarget::isTargetELF () const [inline]
Definition at line 122 of file SystemZSubtarget.h.
References llvm::Triple::isOSBinFormatELF().
void llvm::SystemZSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
bool llvm::SystemZSubtarget::useAA () const [inline, override]
Definition at line 77 of file SystemZSubtarget.h.
Member Data Documentation
bool llvm::SystemZSubtarget::HasDistinctOps [protected]
Definition at line 37 of file SystemZSubtarget.h.
Referenced by hasDistinctOps().
bool llvm::SystemZSubtarget::HasFastSerialization [protected]
Definition at line 42 of file SystemZSubtarget.h.
Referenced by hasFastSerialization().
bool llvm::SystemZSubtarget::HasFPExtension [protected]
Definition at line 40 of file SystemZSubtarget.h.
Referenced by hasFPExtension().
bool llvm::SystemZSubtarget::HasHighWord [protected]
Definition at line 39 of file SystemZSubtarget.h.
Referenced by hasHighWord().
bool llvm::SystemZSubtarget::HasInterlockedAccess1 [protected]
Definition at line 43 of file SystemZSubtarget.h.
Referenced by hasInterlockedAccess1().
bool llvm::SystemZSubtarget::HasLoadStoreOnCond [protected]
Definition at line 38 of file SystemZSubtarget.h.
Referenced by hasLoadStoreOnCond().
bool llvm::SystemZSubtarget::HasMiscellaneousExtensions [protected]
Definition at line 44 of file SystemZSubtarget.h.
Referenced by hasMiscellaneousExtensions().
bool llvm::SystemZSubtarget::HasPopulationCount [protected]
Definition at line 41 of file SystemZSubtarget.h.
Referenced by hasPopulationCount().
bool llvm::SystemZSubtarget::HasProcessorAssist [protected]
Definition at line 46 of file SystemZSubtarget.h.
Referenced by hasProcessorAssist().
bool llvm::SystemZSubtarget::HasTransactionalExecution [protected]
Definition at line 45 of file SystemZSubtarget.h.
Referenced by hasTransactionalExecution().
bool llvm::SystemZSubtarget::HasVector [protected]
Definition at line 47 of file SystemZSubtarget.h.
Referenced by hasVector().
The documentation for this class was generated from the following files:
SystemZSubtarget.h
SystemZSubtarget.cpp