LLVM: llvm::MemoryLocation Class Reference
llvm::MemoryLocation Class Reference
Representation for a specific memory location.
#include <MemoryLocation.h>
Public Member Functions
MemoryLocation (const Value *Ptr=nullptr, uint64_t Size=UnknownSize, const AAMDNodes &AATags=AAMDNodes())
MemoryLocation getWithNewPtr (const Value *NewPtr) const
MemoryLocation getWithNewSize (uint64_t NewSize) const
MemoryLocation getWithoutAATags () const
bool operator== (const MemoryLocation &Other) const
Static Public Member Functions
static MemoryLocation get (const LoadInst *LI)
Return a location with information about the memory reference by the given instruction.
static MemoryLocation get (const StoreInst *SI)
static MemoryLocation get (const VAArgInst *VI)
static MemoryLocation get (const AtomicCmpXchgInst *CXI)
static MemoryLocation get (const AtomicRMWInst *RMWI)
static MemoryLocation get (const Instruction *Inst)
static MemoryLocation getForSource (const MemTransferInst *MTI)
Return a location representing the source of a memory transfer.
static MemoryLocation getForDest (const MemIntrinsic *MI)
Return a location representing the destination of a memory set or transfer.
static MemoryLocation getForArgument (ImmutableCallSite CS, unsigned ArgIdx, const TargetLibraryInfo &TLI)
Return a location representing a particular argument of a call.
Public Attributes
const Value * Ptr
The address of the start of the location.
uint64_t Size
The maximum size of the location, in address-units, or UnknownSize if the size is not known.
AAMDNodes AATags
The metadata nodes which describes the aliasing of the location (each member is null if that kind of information is unavailable).
Detailed Description
Representation for a specific memory location.
This abstraction can be used to represent a specific location in memory. The goal of the location is to represent enough information to describe abstract aliasing, modification, and reference behaviors of whatever value(s) are stored in memory at the particular location.
The primary user of this interface is LLVM's Alias Analysis, but other memory analyses such as MemoryDependence can use it as well.
Definition at line 40 of file MemoryLocation.h.
Constructor & Destructor Documentation
llvm::MemoryLocation::MemoryLocation (const Value * Ptr = nullptr, uint64_t Size = UnknownSize, const AAMDNodes & AATags = AAMDNodes()) [inline, explicit]
Definition at line 95 of file MemoryLocation.h.
Referenced by get(), getForArgument(), getForDest(), and getForSource().
Member Function Documentation
MemoryLocation MemoryLocation::get (const LoadInst * LI) [static]
Return a location with information about the memory reference by the given instruction.
Definition at line 21 of file MemoryLocation.cpp.
References AATags, llvm::DL, llvm::Instruction::getAAMetadata(), llvm::Module::getDataLayout(), llvm::Instruction::getModule(), llvm::LoadInst::getPointerOperand(), llvm::Value::getType(), and MemoryLocation().
Referenced by findSafeStoreForStoreStrongContraction(), GetLocation(), getLocForWrite(), llvm::AliasAnalysis::getModRefInfo(), llvm::MemoryDependenceAnalysis::getNonLocalPointerDependency(), llvm::MemoryDependenceAnalysis::getPointerDependencyFrom(), and isSafeToMove().
MemoryLocation MemoryLocation::get (const StoreInst * SI) [static]
Definition at line 30 of file MemoryLocation.cpp.
References AATags, llvm::DL, llvm::Instruction::getAAMetadata(), llvm::Module::getDataLayout(), llvm::Instruction::getModule(), llvm::StoreInst::getPointerOperand(), llvm::Value::getType(), llvm::StoreInst::getValueOperand(), and MemoryLocation().
MemoryLocation MemoryLocation::get (const VAArgInst * VI) [static]
Definition at line 40 of file MemoryLocation.cpp.
References AATags, llvm::Instruction::getAAMetadata(), llvm::VAArgInst::getPointerOperand(), MemoryLocation(), and UnknownSize.
MemoryLocation MemoryLocation::get (const AtomicCmpXchgInst * CXI) [static]
Definition at line 47 of file MemoryLocation.cpp.
References AATags, llvm::DL, llvm::Instruction::getAAMetadata(), llvm::AtomicCmpXchgInst::getCompareOperand(), llvm::Module::getDataLayout(), llvm::Instruction::getModule(), llvm::AtomicCmpXchgInst::getPointerOperand(), llvm::Value::getType(), and MemoryLocation().
MemoryLocation MemoryLocation::get (const AtomicRMWInst * RMWI) [static]
Definition at line 57 of file MemoryLocation.cpp.
References AATags, llvm::DL, llvm::Instruction::getAAMetadata(), llvm::Module::getDataLayout(), llvm::Instruction::getModule(), llvm::AtomicRMWInst::getPointerOperand(), llvm::Value::getType(), llvm::AtomicRMWInst::getValOperand(), and MemoryLocation().
static MemoryLocation llvm::MemoryLocation::get (const Instruction * Inst) [inline, static]
Definition at line 70 of file MemoryLocation.h.
References I, and llvm_unreachable.
MemoryLocation MemoryLocation::getForArgument (ImmutableCallSite CS, unsigned ArgIdx, const TargetLibraryInfo & TLI) [static]
Return a location representing a particular argument of a call.
Definition at line 110 of file MemoryLocation.cpp.
References AATags, llvm::DL, llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getArgument(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCalledFunction(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getInstruction(), llvm::DataLayout::getTypeStoreSize(), isMemsetPattern16(), MemoryLocation(), and UnknownSize.
Referenced by llvm::AliasAnalysis::getModRefInfo().
MemoryLocation MemoryLocation::getForDest (const MemIntrinsic * MI) [static]
Return a location representing the destination of a memory set or transfer.
Definition at line 80 of file MemoryLocation.cpp.
References AATags, llvm::C, llvm::Instruction::getAAMetadata(), llvm::MemIntrinsic::getLength(), llvm::MemIntrinsic::getRawDest(), MemoryLocation(), Size, and UnknownSize.
Referenced by getLocForWrite().
MemoryLocation MemoryLocation::getForSource (const MemTransferInst * MTI) [static]
Return a location representing the source of a memory transfer.
Definition at line 67 of file MemoryLocation.cpp.
References AATags, llvm::C, llvm::Instruction::getAAMetadata(), llvm::MemIntrinsic::getLength(), llvm::MemTransferInst::getRawSource(), MemoryLocation(), Size, and UnknownSize.
Referenced by getLocForRead().
MemoryLocation llvm::MemoryLocation::getWithNewPtr (const Value * NewPtr) const [inline]
Definition at line 100 of file MemoryLocation.h.
References Ptr.
MemoryLocation llvm::MemoryLocation::getWithNewSize (uint64_t NewSize) const [inline]
Definition at line 106 of file MemoryLocation.h.
References Size.
MemoryLocation llvm::MemoryLocation::getWithoutAATags () const [inline]
Definition at line 112 of file MemoryLocation.h.
References AATags.
bool llvm::MemoryLocation::operator== (const MemoryLocation & Other) const [inline]
Definition at line 118 of file MemoryLocation.h.
References AATags, Ptr, and Size.
Member Data Documentation
AAMDNodes llvm::MemoryLocation::AATags
The metadata nodes which describes the aliasing of the location (each member is null if that kind of information is unavailable).
Definition at line 61 of file MemoryLocation.h.
Referenced by get(), getForArgument(), getForDest(), getForSource(), llvm::DenseMapInfo< MemoryLocation >::getHashValue(), getWithoutAATags(), and operator==().
const Value* llvm::MemoryLocation::Ptr
The address of the start of the location.
Definition at line 48 of file MemoryLocation.h.
Referenced by llvm::AliasAnalysis::callCapturesBefore(), findSafeStoreForStoreStrongContraction(), llvm::MemoryDependenceAnalysis::getDependency(), llvm::DenseMapInfo< MemoryLocation >::getHashValue(), llvm::AliasAnalysis::getModRefInfo(), llvm::MemoryDependenceAnalysis::getNonLocalPointerDependency(), llvm::MemoryDependenceAnalysis::getPointerDependencyFrom(), getWithNewPtr(), isLoadLoadClobberIfExtendedToFullWidth(), isOverwrite(), isPossibleSelfRead(), and operator==().
uint64_t llvm::MemoryLocation::Size
The maximum size of the location, in address-units, or UnknownSize if the size is not known.
Note that an unknown size does not mean the pointer aliases the entire virtual address space, because there are restrictions on stepping out of one object and into another. See http://llvm.org/docs/LangRef.html#pointeraliasing
Definition at line 57 of file MemoryLocation.h.
Referenced by getForDest(), getForSource(), llvm::DenseMapInfo< MemoryLocation >::getHashValue(), getWithNewSize(), isLoadLoadClobberIfExtendedToFullWidth(), isOverwrite(), and operator==().
The documentation for this class was generated from the following files:
MemoryLocation.h
MemoryLocation.cpp