LLVM: llvm::FCmpInst Class Reference
llvm::FCmpInst Class Reference
This instruction compares its operands according to the predicate given to the constructor.
#include <Instructions.h>
Public Member Functions
FCmpInst (Instruction *InsertBefore, Predicate pred, Value *LHS, Value *RHS, const Twine &NameStr="")
Constructor with insert-before-instruction semantics.
FCmpInst (BasicBlock &InsertAtEnd, Predicate pred, Value *LHS, Value *RHS, const Twine &NameStr="")
Constructor with insert-at-end semantics.
FCmpInst (Predicate pred, Value *LHS, Value *RHS, const Twine &NameStr="")
Constructor with no-insertion semantics.
bool isEquality () const
Determine if this is an equality predicate.
bool isCommutative () const
Determine if this is a commutative predicate.
bool isRelational () const
Determine if this a relational predicate.
void swapOperands ()
Exchange the two operands to this instruction in such a way that it does not modify the semantics of the instruction.
Static Public Member Functions
static bool isEquality (Predicate Pred)
Determine if this is an equality predicate.
static bool classof (const Instruction *I)
Methods for support type inquiry through isa, cast, and dyn_cast:
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
FCmpInst * clone_impl () const override
Clone an identical FCmpInst.
Detailed Description
This instruction compares its operands according to the predicate given to the constructor.
It only operates on floating point values or packed vectors of floating point values. The operands must be identical types. Represents a floating point comparison operator.
Definition at line 1211 of file Instructions.h.
Constructor & Destructor Documentation
llvm::FCmpInst::FCmpInst (Instruction * InsertBefore, Predicate pred, Value * LHS, Value * RHS, const Twine & NameStr = "") [inline]
Constructor with insert-before-instruction semantics.
Parameters:
InsertBefore Where to insert
pred The predicate to use for the comparison
LHS The left-hand-side of the expression
RHS The right-hand-side of the expression
NameStr Name of the instruction
Definition at line 1217 of file Instructions.h.
References llvm::User::getOperand(), llvm::Value::getType(), and llvm::CmpInst::LAST_FCMP_PREDICATE.
Referenced by clone_impl().
llvm::FCmpInst::FCmpInst (BasicBlock & InsertAtEnd, Predicate pred, Value * LHS, Value * RHS, const Twine & NameStr = "") [inline]
Constructor with insert-at-end semantics.
Parameters:
InsertAtEnd Block to insert into.
pred The predicate to use for the comparison
LHS The left-hand-side of the expression
RHS The right-hand-side of the expression
NameStr Name of the instruction
Definition at line 1236 of file Instructions.h.
References llvm::User::getOperand(), llvm::Value::getType(), and llvm::CmpInst::LAST_FCMP_PREDICATE.
llvm::FCmpInst::FCmpInst (Predicate pred, Value * LHS, Value * RHS, const Twine & NameStr = "") [inline]
Constructor with no-insertion semantics.
Parameters:
pred The predicate to use for the comparison
LHS The left-hand-side of the expression
RHS The right-hand-side of the expression
NameStr Name of the instruction
Definition at line 1255 of file Instructions.h.
References llvm::User::getOperand(), llvm::Value::getType(), and llvm::CmpInst::LAST_FCMP_PREDICATE.
Member Function Documentation
static bool llvm::FCmpInst::classof (const Instruction * I) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::CmpInst.
Definition at line 1307 of file Instructions.h.
References llvm::FCmp, and llvm::Instruction::getOpcode().
Referenced by classof().
static bool llvm::FCmpInst::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::CmpInst.
Definition at line 1310 of file Instructions.h.
References classof().
FCmpInst * FCmpInst::clone_impl () const [override, protected, virtual]
Clone an identical FCmpInst.
Implements llvm::Instruction.
Definition at line 3465 of file Instructions.cpp.
References FCmpInst(), and llvm::CmpInst::getPredicate().
bool llvm::FCmpInst::isCommutative () const [inline]
Determine if this is a commutative predicate.
Returns:
true if the predicate of this instruction is commutative.
Reimplemented from llvm::CmpInst.
Definition at line 1284 of file Instructions.h.
References llvm::CmpInst::FCMP_FALSE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_TRUE, llvm::CmpInst::FCMP_UNO, llvm::CmpInst::getPredicate(), and isEquality().
static bool llvm::FCmpInst::isEquality (Predicate Pred) [inline, static]
Determine if this is an equality predicate.
Returns:
true if the predicate of this instruction is EQ or NE.
Definition at line 1273 of file Instructions.h.
References llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_UEQ, and llvm::CmpInst::FCMP_UNE.
Referenced by llvm::InstCombiner::FoldFCmp_IntToFP_Cst().
bool llvm::FCmpInst::isEquality () const [inline]
Determine if this is an equality predicate.
Returns:
true if the predicate of this instruction is EQ or NE.
Reimplemented from llvm::CmpInst.
Definition at line 1280 of file Instructions.h.
References llvm::CmpInst::getPredicate(), and isEquality().
Referenced by isCommutative(), isEquality(), and isRelational().
bool llvm::FCmpInst::isRelational () const [inline]
Determine if this a relational predicate.
Returns:
true if the predicate is relational (not EQ or NE).
Definition at line 1294 of file Instructions.h.
References isEquality().
void llvm::FCmpInst::swapOperands () [inline]
Exchange the two operands to this instruction in such a way that it does not modify the semantics of the instruction.
The predicate value may be changed to retain the same result if the predicate is order dependent (e.g. ult). Swap operands and adjust predicate.
Reimplemented from llvm::CmpInst.
Definition at line 1301 of file Instructions.h.
References llvm::CmpInst::getSwappedPredicate(), llvm::CmpInst::setPredicate(), and std::swap().
Referenced by llvm::InstCombiner::visitFCmpInst().
The documentation for this class was generated from the following files:
Instructions.h
Instructions.cpp