LLVM: llvm::MCParsedAsmOperand Class Reference
llvm::MCParsedAsmOperand Class Reference
MCParsedAsmOperand - This abstract class represents a source-level assembly instruction operand.
#include <MCParsedAsmOperand.h>
Public Member Functions
MCParsedAsmOperand ()
virtual ~MCParsedAsmOperand ()
void setConstraint (StringRef C)
StringRef getConstraint ()
void setMCOperandNum (unsigned OpNum)
unsigned getMCOperandNum ()
virtual StringRef getSymName ()
virtual void * getOpDecl ()
virtual bool isToken () const =0
isToken - Is this a token operand?
virtual bool isImm () const =0
isImm - Is this an immediate operand?
virtual bool isReg () const =0
isReg - Is this a register operand?
virtual unsigned getReg () const =0
virtual bool isMem () const =0
isMem - Is this a memory operand?
virtual SMLoc getStartLoc () const =0
getStartLoc - Get the location of the first token of this operand.
virtual SMLoc getEndLoc () const =0
getEndLoc - Get the location of the last token of this operand.
virtual bool needAddressOf () const
needAddressOf - Do we need to emit code to get the address of the variable/label? Only valid when parsing MS-style inline assembly.
virtual bool isOffsetOf () const
isOffsetOf - Do we need to emit code to get the offset of the variable, rather then the value of the variable? Only valid when parsing MS-style inline assembly.
virtual SMLoc getOffsetOfLoc () const
getOffsetOfLoc - Get the location of the offset operator.
virtual void print (raw_ostream &OS) const =0
print - Print a debug representation of the operand to the given stream.
virtual void dump () const
dump - Print to the debug stream.
Detailed Description
MCParsedAsmOperand - This abstract class represents a source-level assembly instruction operand.
It should be subclassed by target-specific code. This base class is used by target-independent clients and is the interface between parsing an asm instruction and recognizing it.
Definition at line 24 of file MCParsedAsmOperand.h.
Constructor & Destructor Documentation
llvm::MCParsedAsmOperand::MCParsedAsmOperand () [inline]
Definition at line 34 of file MCParsedAsmOperand.h.
virtual llvm::MCParsedAsmOperand::~MCParsedAsmOperand () [inline, virtual]
Definition at line 35 of file MCParsedAsmOperand.h.
Member Function Documentation
void MCParsedAsmOperand::dump () const [virtual]
dump - Print to the debug stream.
Definition at line 46 of file MCAsmParser.cpp.
References llvm::dbgs().
StringRef llvm::MCParsedAsmOperand::getConstraint () [inline]
Definition at line 38 of file MCParsedAsmOperand.h.
virtual SMLoc llvm::MCParsedAsmOperand::getEndLoc () const [pure virtual]
getEndLoc - Get the location of the last token of this operand.
Implemented in llvm::X86Operand.
unsigned llvm::MCParsedAsmOperand::getMCOperandNum () [inline]
Definition at line 41 of file MCParsedAsmOperand.h.
virtual SMLoc llvm::MCParsedAsmOperand::getOffsetOfLoc () const [inline, virtual]
getOffsetOfLoc - Get the location of the offset operator.
Reimplemented in llvm::X86Operand.
Definition at line 72 of file MCParsedAsmOperand.h.
virtual void* llvm::MCParsedAsmOperand::getOpDecl () [inline, virtual]
Reimplemented in llvm::X86Operand.
Definition at line 44 of file MCParsedAsmOperand.h.
virtual unsigned llvm::MCParsedAsmOperand::getReg () const [pure virtual]
Implemented in llvm::X86Operand.
virtual SMLoc llvm::MCParsedAsmOperand::getStartLoc () const [pure virtual]
getStartLoc - Get the location of the first token of this operand.
Implemented in llvm::X86Operand.
virtual StringRef llvm::MCParsedAsmOperand::getSymName () [inline, virtual]
Reimplemented in llvm::X86Operand.
Definition at line 43 of file MCParsedAsmOperand.h.
virtual bool llvm::MCParsedAsmOperand::isImm () const [pure virtual]
isImm - Is this an immediate operand?
Implemented in llvm::X86Operand.
virtual bool llvm::MCParsedAsmOperand::isMem () const [pure virtual]
isMem - Is this a memory operand?
Implemented in llvm::X86Operand.
virtual bool llvm::MCParsedAsmOperand::isOffsetOf () const [inline, virtual]
isOffsetOf - Do we need to emit code to get the offset of the variable, rather then the value of the variable? Only valid when parsing MS-style inline assembly.
Reimplemented in llvm::X86Operand.
Definition at line 69 of file MCParsedAsmOperand.h.
virtual bool llvm::MCParsedAsmOperand::isReg () const [pure virtual]
isReg - Is this a register operand?
Implemented in llvm::X86Operand.
virtual bool llvm::MCParsedAsmOperand::isToken () const [pure virtual]
isToken - Is this a token operand?
Implemented in llvm::X86Operand.
virtual bool llvm::MCParsedAsmOperand::needAddressOf () const [inline, virtual]
needAddressOf - Do we need to emit code to get the address of the variable/label? Only valid when parsing MS-style inline assembly.
Reimplemented in llvm::X86Operand.
Definition at line 64 of file MCParsedAsmOperand.h.
virtual void llvm::MCParsedAsmOperand::print (raw_ostream & OS) const [pure virtual]
print - Print a debug representation of the operand to the given stream.
Implemented in llvm::X86Operand.
Referenced by llvm::operator<<().
void llvm::MCParsedAsmOperand::setConstraint (StringRef C) [inline]
Definition at line 37 of file MCParsedAsmOperand.h.
References llvm::StringRef::str().
void llvm::MCParsedAsmOperand::setMCOperandNum (unsigned OpNum) [inline]
Definition at line 40 of file MCParsedAsmOperand.h.
The documentation for this class was generated from the following files:
MCParsedAsmOperand.h
MCAsmParser.cpp