LLVM: llvm::MCSubtargetInfo Class Reference
llvm::MCSubtargetInfo Class Reference
MCSubtargetInfo - Generic base class for all target subtargets.
#include <MCSubtargetInfo.h>
Public Member Functions
void InitMCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS, ArrayRef< SubtargetFeatureKV > PF, ArrayRef< SubtargetFeatureKV > PD, const SubtargetInfoKV *ProcSched, const MCWriteProcResEntry *WPR, const MCWriteLatencyEntry *WL, const MCReadAdvanceEntry *RA, const InstrStage *IS, const unsigned *OC, const unsigned *FP)
const Triple & getTargetTriple () const
getTargetTriple - Return the target triple string.
StringRef getCPU () const
getCPU - Return the CPU string.
const FeatureBitset & getFeatureBits () const
getFeatureBits - Return the feature bits.
void setFeatureBits (const FeatureBitset &FeatureBits_)
setFeatureBits - Set the feature bits.
void InitMCProcessorInfo (StringRef CPU, StringRef FS)
InitMCProcessorInfo - Set or change the CPU (optionally supplemented with feature string).
void InitCPUSchedModel (StringRef CPU)
InitCPUSchedModel - Recompute scheduling model based on CPU.
FeatureBitset ToggleFeature (uint64_t FB)
ToggleFeature - Toggle a feature and returns the re-computed feature bits.
FeatureBitset ToggleFeature (const FeatureBitset &FB)
ToggleFeature - Toggle a feature and returns the re-computed feature bits.
FeatureBitset ToggleFeature (StringRef FS)
ToggleFeature - Toggle a set of features and returns the re-computed feature bits.
FeatureBitset ApplyFeatureFlag (StringRef FS)
Apply a feature flag and return the re-computed feature bits, including all feature bits implied by the flag.
MCSchedModel getSchedModelForCPU (StringRef CPU) const
getSchedModelForCPU - Get the machine model of a CPU.
const MCSchedModel & getSchedModel () const
getSchedModel - Get the machine model for this subtarget's CPU.
const MCWriteProcResEntry * getWriteProcResBegin (const MCSchedClassDesc *SC) const
Return an iterator at the first process resource consumed by the given scheduling class.
const MCWriteProcResEntry * getWriteProcResEnd (const MCSchedClassDesc *SC) const
const MCWriteLatencyEntry * getWriteLatencyEntry (const MCSchedClassDesc *SC, unsigned DefIdx) const
int getReadAdvanceCycles (const MCSchedClassDesc *SC, unsigned UseIdx, unsigned WriteResID) const
InstrItineraryData getInstrItineraryForCPU (StringRef CPU) const
getInstrItineraryForCPU - Get scheduling itinerary of a CPU.
void initInstrItins (InstrItineraryData &InstrItins) const
Initialize an InstrItineraryData instance.
bool isCPUStringValid (StringRef CPU)
Check whether the CPU string is valid.
Detailed Description
MCSubtargetInfo - Generic base class for all target subtargets.
Definition at line 29 of file MCSubtargetInfo.h.
Member Function Documentation
FeatureBitset MCSubtargetInfo::ApplyFeatureFlag (StringRef FS)
Apply a feature flag and return the re-computed feature bits, including all feature bits implied by the flag.
Definition at line 79 of file MCSubtargetInfo.cpp.
References llvm::SubtargetFeatures::ApplyFeatureFlag(), and Features.
StringRef llvm::MCSubtargetInfo::getCPU () const [inline]
getCPU - Return the CPU string.
Definition at line 61 of file MCSubtargetInfo.h.
const FeatureBitset& llvm::MCSubtargetInfo::getFeatureBits () const [inline]
getFeatureBits - Return the feature bits.
Definition at line 67 of file MCSubtargetInfo.h.
Referenced by llvm::CreateX86AsmInstrumentation(), DecodeSETPANInstruction(), DecodeSystemPStateInstruction(), llvm::MipsTargetELFStreamer::finish(), getARMLoadDeprecationInfo(), getARMStoreDeprecationInfo(), llvm::MCInstrDesc::getDeprecatedInfo(), getITDeprecationInfo(), getMCRDeprecationInfo(), isThumb(), llvm::SparcInstPrinter::isV9(), llvm::MipsTargetELFStreamer::MipsTargetELFStreamer(), llvm::AArch64InstPrinter::printBarrierOption(), llvm::ARMInstPrinter::printInst(), llvm::PPCInstPrinter::printInst(), llvm::ARMInstPrinter::printMemBOption(), llvm::AArch64InstPrinter::printMRSSystemRegister(), llvm::ARMInstPrinter::printMSRMaskOperand(), llvm::AArch64InstPrinter::printMSRSystemRegister(), llvm::AArch64InstPrinter::printPrefetchOp(), llvm::AArch64InstPrinter::printSystemPStateField(), and llvm::X86Disassembler::X86GenericDisassembler::X86GenericDisassembler().
InstrItineraryData MCSubtargetInfo::getInstrItineraryForCPU (StringRef CPU) const
getInstrItineraryForCPU - Get scheduling itinerary of a CPU.
Definition at line 112 of file MCSubtargetInfo.cpp.
References getSchedModelForCPU().
Referenced by getItineraryLatency().
int llvm::MCSubtargetInfo::getReadAdvanceCycles (const MCSchedClassDesc * SC, unsigned UseIdx, unsigned WriteResID) const [inline]
Definition at line 127 of file MCSubtargetInfo.h.
References I, llvm::MCSchedClassDesc::NumReadAdvanceEntries, and llvm::MCSchedClassDesc::ReadAdvanceIdx.
Referenced by llvm::TargetSchedModel::computeOperandLatency().
const MCSchedModel& llvm::MCSubtargetInfo::getSchedModel () const [inline]
getSchedModel - Get the machine model for this subtarget's CPU.
Definition at line 106 of file MCSubtargetInfo.h.
Referenced by llvm::TargetSubtargetInfo::enablePostRAScheduler(), getLatency(), llvm::HexagonMCInstrInfo::getUnits(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getUnrollingPreferences(), llvm::MachineTraceMetrics::runOnMachineFunction(), and llvm::ScheduleDAGInstrs::ScheduleDAGInstrs().
MCSchedModel MCSubtargetInfo::getSchedModelForCPU (StringRef CPU) const
getSchedModelForCPU - Get the machine model of a CPU.
Definition at line 86 of file MCSubtargetInfo.cpp.
References llvm::errs(), Found(), llvm::MCSchedModel::GetDefaultSchedModel(), llvm::SubtargetInfoKV::Key, llvm::ArrayRef< T >::size(), and llvm::SubtargetInfoKV::Value.
Referenced by getInstrItineraryForCPU(), and InitCPUSchedModel().
const Triple& llvm::MCSubtargetInfo::getTargetTriple () const [inline]
getTargetTriple - Return the target triple string.
Definition at line 58 of file MCSubtargetInfo.h.
Referenced by llvm::createAArch64ObjectTargetStreamer(), llvm::createARMObjectTargetStreamer(), createObjectTargetStreamer(), and llvm::CreateX86AsmInstrumentation().
const MCWriteLatencyEntry* llvm::MCSubtargetInfo::getWriteLatencyEntry (const MCSchedClassDesc * SC, unsigned DefIdx) const [inline]
Definition at line 119 of file MCSubtargetInfo.h.
References llvm::MCSchedClassDesc::WriteLatencyIdx.
Referenced by llvm::TargetSchedModel::computeOperandLatency(), and getLatency().
const MCWriteProcResEntry* llvm::MCSubtargetInfo::getWriteProcResBegin (const MCSchedClassDesc * SC) const [inline]
Return an iterator at the first process resource consumed by the given scheduling class.
Definition at line 110 of file MCSubtargetInfo.h.
References llvm::MCSchedClassDesc::WriteProcResIdx.
Referenced by llvm::TargetSchedModel::computeOutputLatency(), llvm::TargetSchedModel::getWriteProcResBegin(), and getWriteProcResEnd().
const MCWriteProcResEntry* llvm::MCSubtargetInfo::getWriteProcResEnd (const MCSchedClassDesc * SC) const [inline]
Definition at line 114 of file MCSubtargetInfo.h.
References getWriteProcResBegin(), and llvm::MCSchedClassDesc::NumWriteProcResEntries.
Referenced by llvm::TargetSchedModel::computeOutputLatency(), and llvm::TargetSchedModel::getWriteProcResEnd().
void MCSubtargetInfo::InitCPUSchedModel (StringRef CPU)
InitCPUSchedModel - Recompute scheduling model based on CPU.
Definition at line 30 of file MCSubtargetInfo.cpp.
References llvm::StringRef::empty(), llvm::MCSchedModel::GetDefaultSchedModel(), and getSchedModelForCPU().
Referenced by InitMCProcessorInfo().
void MCSubtargetInfo::initInstrItins (InstrItineraryData & InstrItins) const
Initialize an InstrItineraryData instance.
Definition at line 118 of file MCSubtargetInfo.cpp.
Referenced by llvm::TargetSchedModel::init().
void MCSubtargetInfo::InitMCProcessorInfo (StringRef CPU, StringRef FS)
InitMCProcessorInfo - Set or change the CPU (optionally supplemented with feature string).
Recompute feature bits and scheduling model.
Definition at line 23 of file MCSubtargetInfo.cpp.
References Features, llvm::SubtargetFeatures::getFeatureBits(), and InitCPUSchedModel().
Referenced by InitMCSubtargetInfo().
void MCSubtargetInfo::InitMCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS, ArrayRef< SubtargetFeatureKV > PF, ArrayRef< SubtargetFeatureKV > PD, const SubtargetInfoKV * ProcSched, const MCWriteProcResEntry * WPR, const MCWriteLatencyEntry * WL, const MCReadAdvanceEntry * RA, const InstrStage * IS, const unsigned * OC, const unsigned * FP)
Definition at line 37 of file MCSubtargetInfo.cpp.
References llvm::C, InitMCProcessorInfo(), llvm::SystemZISD::OC, and llvm::X86II::PD.
bool llvm::MCSubtargetInfo::isCPUStringValid (StringRef CPU) [inline]
Check whether the CPU string is valid.
Definition at line 154 of file MCSubtargetInfo.h.
References llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), and Found().
void llvm::MCSubtargetInfo::setFeatureBits (const FeatureBitset & FeatureBits_) [inline]
setFeatureBits - Set the feature bits.
Definition at line 73 of file MCSubtargetInfo.h.
FeatureBitset MCSubtargetInfo::ToggleFeature (uint64_t FB)
ToggleFeature - Toggle a feature and returns the re-computed feature bits.
This version does not change the implied bits.
Definition at line 61 of file MCSubtargetInfo.cpp.
FeatureBitset MCSubtargetInfo::ToggleFeature (const FeatureBitset & FB)
ToggleFeature - Toggle a feature and returns the re-computed feature bits.
This version does not change the implied bits.
Definition at line 66 of file MCSubtargetInfo.cpp.
FeatureBitset MCSubtargetInfo::ToggleFeature (StringRef FS)
ToggleFeature - Toggle a set of features and returns the re-computed feature bits.
ToggleFeature - Toggle a feature and returns the re-computed feature bits.
This version will also change all implied bits.
Definition at line 73 of file MCSubtargetInfo.cpp.
References Features, and llvm::SubtargetFeatures::ToggleFeature().
The documentation for this class was generated from the following files:
MCSubtargetInfo.h
MCSubtargetInfo.cpp