LLVM: llvm::ConstantFPSDNode Class Reference
llvm::ConstantFPSDNode Class Reference
#include <SelectionDAGNodes.h>
Public Member Functions
const APFloat & getValueAPF () const
const ConstantFP * getConstantFPValue () const
bool isZero () const
Return true if the value is positive or negative zero.
bool isNaN () const
Return true if the value is a NaN.
bool isInfinity () const
Return true if the value is an infinity.
bool isNegative () const
Return true if the value is negative.
bool isExactlyValue (double V) const
We don't rely on operator== working on double values, as it returns true for things that are clearly not equal, like -0.0 and 0.0.
bool isExactlyValue (const APFloat &V) const
isExactlyValue - We don't rely on operator== working on double values, as it returns true for things that are clearly not equal, like -0.0 and 0.0.
Static Public Member Functions
static bool isValueValidForType (EVT VT, const APFloat &Val)
static bool classof (const SDNode *N)
Friends
class SelectionDAG
Detailed Description
Definition at line 1434 of file SelectionDAGNodes.h.
Member Function Documentation
static bool llvm::ConstantFPSDNode::classof (const SDNode * N) [inline, static]
Definition at line 1477 of file SelectionDAGNodes.h.
References llvm::ISD::ConstantFP, llvm::SDNode::getOpcode(), and llvm::ISD::TargetConstantFP.
const ConstantFP* llvm::ConstantFPSDNode::getConstantFPValue () const [inline]
Definition at line 1444 of file SelectionDAGNodes.h.
const APFloat& llvm::ConstantFPSDNode::getValueAPF () const [inline]
Definition at line 1443 of file SelectionDAGNodes.h.
Referenced by FoldOperand(), llvm::SelectionDAG::getNode(), isConstVecPow2(), and selectCCOpsAreFMaxCompatible().
bool llvm::ConstantFPSDNode::isExactlyValue (double V) const [inline]
We don't rely on operator== working on double values, as it returns true for things that are clearly not equal, like -0.0 and 0.0.
As such, this method can be used to do an exact bit-for-bit comparison of two floating point values. We leave the version with the double argument here because it's just so convenient to write "2.0" and the like. Without this function we'd have to duplicate its logic everywhere it's called.
Definition at line 1466 of file SelectionDAGNodes.h.
References llvm::APFloat::convert(), and llvm::APFloat::rmNearestTiesToEven.
Referenced by llvm::SelectionDAG::getNode().
bool ConstantFPSDNode::isExactlyValue (const APFloat & V) const
isExactlyValue - We don't rely on operator== working on double values, as it returns true for things that are clearly not equal, like -0.0 and 0.0.
As such, this method can be used to do an exact bit-for-bit comparison of two floating point values.
Definition at line 75 of file SelectionDAG.cpp.
bool llvm::ConstantFPSDNode::isInfinity () const [inline]
Return true if the value is an infinity.
Definition at line 1453 of file SelectionDAGNodes.h.
bool llvm::ConstantFPSDNode::isNaN () const [inline]
Return true if the value is a NaN.
Definition at line 1450 of file SelectionDAGNodes.h.
bool llvm::ConstantFPSDNode::isNegative () const [inline]
Return true if the value is negative.
Definition at line 1456 of file SelectionDAGNodes.h.
Referenced by isNullFPConstant().
bool ConstantFPSDNode::isValueValidForType (EVT VT, const APFloat & Val) [static]
Definition at line 79 of file SelectionDAG.cpp.
References llvm::lltok::APFloat, llvm::SelectionDAG::EVTToAPFloatSemantics(), llvm::EVT::isFloatingPoint(), and llvm::APFloat::rmNearestTiesToEven.
bool llvm::ConstantFPSDNode::isZero () const [inline]
Return true if the value is positive or negative zero.
Definition at line 1447 of file SelectionDAGNodes.h.
Referenced by llvm::SelectionDAG::getNode(), and isNullFPConstant().
Friends And Related Function Documentation
friend class SelectionDAG [friend]
Reimplemented from llvm::SDNode.
Definition at line 1436 of file SelectionDAGNodes.h.
The documentation for this class was generated from the following files:
SelectionDAGNodes.h
SelectionDAG.cpp