LLVM: llvm::object::Archive::Symbol Class Reference
llvm::object::Archive::Symbol Class Reference
#include <Archive.h>
Public Member Functions
bool operator== (const Symbol &other) const
Symbol (const Archive *p, uint32_t symi, uint32_t stri)
StringRef getName () const
ErrorOr< child_iterator > getMember () const
Symbol getNext () const
Detailed Description
Definition at line 135 of file Archive.h.
Constructor & Destructor Documentation
llvm::object::Archive::Symbol::Symbol (const Archive * p, uint32_t symi, uint32_t stri) [inline]
Definition at line 145 of file Archive.h.
Member Function Documentation
ErrorOr< Archive::child_iterator > Archive::Symbol::getMember () const
Definition at line 358 of file Archive.cpp.
References llvm::object::Archive::K_BSD, llvm::object::Archive::K_GNU, llvm::object::Archive::K_MIPS64, llvm::object::parse_failed, llvm::support::endian::read16le(), llvm::support::endian::read32be(), llvm::support::endian::read32le(), and llvm::support::endian::read64be().
Referenced by llvm::object::Archive::findSym().
StringRef Archive::Symbol::getName () const
Definition at line 354 of file Archive.cpp.
References llvm::StringRef::begin(), and llvm::object::Archive::Child::getBuffer().
Referenced by llvm::object::Archive::findSym().
Archive::Symbol Archive::Symbol::getNext () const
Definition at line 407 of file Archive.cpp.
References llvm::object::Archive::K_BSD, and llvm::support::endian::read32le().
Referenced by llvm::object::Archive::symbol_iterator::operator++().
bool llvm::object::Archive::Symbol::operator== (const Symbol & other) const [inline]
Definition at line 141 of file Archive.h.
The documentation for this class was generated from the following files:
Archive.h
Archive.cpp