LLVM: llvm::RuntimeDyldMachO Class Reference
llvm::RuntimeDyldMachO Class Reference
#include <RuntimeDyldMachO.h>
Classes
struct EHFrameRelatedSections
struct SectionOffsetPair
Public Member Functions
std::unique_ptr
< RuntimeDyld::LoadedObjectInfo > loadObject (const object::ObjectFile &O) override
SectionEntry & getSection (unsigned SectionID)
bool isCompatibleFile (const object::ObjectFile &Obj) const override
Static Public Member Functions
static std::unique_ptr
< RuntimeDyldMachO > create (Triple::ArchType Arch, RuntimeDyld::MemoryManager &MemMgr, RuntimeDyld::SymbolResolver &Resolver)
Create a RuntimeDyldMachO instance for the given target architecture.
Protected Member Functions
RuntimeDyldMachO (RuntimeDyld::MemoryManager &MemMgr, RuntimeDyld::SymbolResolver &Resolver)
int64_t memcpyAddend (const RelocationEntry &RE) const
This convenience method uses memcpy to extract a contiguous addend (the addend size and offset are taken from the corresponding fields of the RE).
RelocationEntry getRelocationEntry (unsigned SectionID, const ObjectFile &BaseTObj, const relocation_iterator &RI) const
Given a relocation_iterator for a non-scattered relocation, construct a RelocationEntry and fill in the common fields.
RelocationValueRef getRelocationValueRef (const ObjectFile &BaseTObj, const relocation_iterator &RI, const RelocationEntry &RE, ObjSectionToIDMap &ObjSectionToID)
Construct a RelocationValueRef representing the relocation target.
void makeValueAddendPCRel (RelocationValueRef &Value, const ObjectFile &BaseTObj, const relocation_iterator &RI, unsigned OffsetToNextPC)
Make the RelocationValueRef addend PC-relative.
void dumpRelocationToResolve (const RelocationEntry &RE, uint64_t Value) const
Dump information about the relocation entry (RE) and resolved value.
void populateIndirectSymbolPointersSection (const MachOObjectFile &Obj, const SectionRef &PTSection, unsigned PTSectionID)
Static Protected Member Functions
static section_iterator getSectionByAddress (const MachOObjectFile &Obj, uint64_t Addr)
Protected Attributes
SmallVector
< EHFrameRelatedSections, 2 > UnregisteredEHFrameSections
Detailed Description
Definition at line 27 of file RuntimeDyldMachO.h.
Constructor & Destructor Documentation
llvm::RuntimeDyldMachO::RuntimeDyldMachO (RuntimeDyld::MemoryManager & MemMgr, RuntimeDyld::SymbolResolver & Resolver) [inline, protected]
Definition at line 52 of file RuntimeDyldMachO.h.
Member Function Documentation
std::unique_ptr< RuntimeDyldMachO > llvm::RuntimeDyldMachO::create (Triple::ArchType Arch, RuntimeDyld::MemoryManager & MemMgr, RuntimeDyld::SymbolResolver & Resolver) [static]
Create a RuntimeDyldMachO instance for the given target architecture.
Definition at line 286 of file RuntimeDyldMachO.cpp.
References llvm::Triple::aarch64, llvm::Triple::arm, llvm_unreachable, llvm::Triple::x86, and llvm::Triple::x86_64.
Referenced by llvm::createRuntimeDyldMachO().
void llvm::RuntimeDyldMachO::dumpRelocationToResolve (const RelocationEntry & RE, uint64_t Value) const [protected]
Dump information about the relocation entry (RE) and resolved value.
Definition at line 106 of file RuntimeDyldMachO.cpp.
References llvm::RelocationEntry::Addend, llvm::SectionEntry::Address, llvm::dbgs(), llvm::format(), llvm::RelocationEntry::IsPCRel, llvm::SectionEntry::LoadAddress, llvm::RelocationEntry::Offset, llvm::RelocationEntry::RelType, llvm::ARMBuildAttrs::Section, llvm::RelocationEntry::SectionID, and llvm::RelocationEntry::Size.
Referenced by llvm::RuntimeDyldMachOX86_64::resolveRelocation(), llvm::RuntimeDyldMachOI386::resolveRelocation(), llvm::RuntimeDyldMachOARM::resolveRelocation(), and llvm::RuntimeDyldMachOAArch64::resolveRelocation().
RelocationEntry llvm::RuntimeDyldMachO::getRelocationEntry (unsigned SectionID, const ObjectFile & BaseTObj, const relocation_iterator & RI) const [inline, protected]
Given a relocation_iterator for a non-scattered relocation, construct a RelocationEntry and fill in the common fields.
The 'Addend' field is *not* filled in, since immediate encodings are highly target/opcode specific. For targets/opcodes with simple, contiguous immediates (e.g. X86) the memcpyAddend method can be used to read the immediate.
Definition at line 65 of file RuntimeDyldMachO.h.
References llvm::object::MachOObjectFile::getAnyRelocationLength(), llvm::object::MachOObjectFile::getAnyRelocationPCRel(), llvm::object::MachOObjectFile::getAnyRelocationType(), and llvm::object::MachOObjectFile::getRelocation().
Referenced by llvm::RuntimeDyldMachOX86_64::processRelocationRef(), llvm::RuntimeDyldMachOI386::processRelocationRef(), llvm::RuntimeDyldMachOARM::processRelocationRef(), and llvm::RuntimeDyldMachOAArch64::processRelocationRef().
RelocationValueRef llvm::RuntimeDyldMachO::getRelocationValueRef (const ObjectFile & BaseTObj, const relocation_iterator & RI, const RelocationEntry & RE, ObjSectionToIDMap & ObjSectionToID) [protected]
Construct a RelocationValueRef representing the relocation target.
For Symbols in known sections, this will return a RelocationValueRef representing a (SectionID, Offset) pair. For Symbols whose section is not known, this will return a (SymbolName, Offset) pair, where the Offset is taken from the instruction immediate (held in RE.Addend). In both cases the Addend field is *NOT* fixed up to be PC-relative. That should be done by the caller where appropriate by calling makePCRel on the RelocationValueRef.
Definition at line 53 of file RuntimeDyldMachO.cpp.
References llvm::RelocationEntry::Addend, llvm::StringRef::data(), llvm::object::SectionRef::getAddress(), llvm::object::MachOObjectFile::getAnyRelocationSection(), llvm::object::SymbolRef::getName(), llvm::object::MachOObjectFile::getPlainRelocationExternal(), llvm::object::MachOObjectFile::getRelocation(), llvm::object::SectionRef::isText(), llvm::RelocationValueRef::Offset, llvm::StringMapEntry< ValueTy >::second, llvm::RelocationValueRef::SectionID, llvm::SI, llvm::ARMBuildAttrs::Symbol, and llvm::RelocationValueRef::SymbolName.
Referenced by llvm::RuntimeDyldMachOI386::processRelocationRef(), llvm::RuntimeDyldMachOX86_64::processRelocationRef(), llvm::RuntimeDyldMachOARM::processRelocationRef(), and llvm::RuntimeDyldMachOAArch64::processRelocationRef().
SectionEntry& llvm::RuntimeDyldMachO::getSection (unsigned SectionID) [inline]
Definition at line 127 of file RuntimeDyldMachO.h.
section_iterator llvm::RuntimeDyldMachO::getSectionByAddress (const MachOObjectFile & Obj, uint64_t Addr) [static, protected]
Definition at line 121 of file RuntimeDyldMachO.cpp.
References llvm::object::MachOObjectFile::section_begin(), llvm::object::MachOObjectFile::section_end(), and llvm::SI.
bool llvm::RuntimeDyldMachO::isCompatibleFile (const object::ObjectFile & Obj) const [override, virtual]
Implements llvm::RuntimeDyldImpl.
Definition at line 177 of file RuntimeDyldMachO.cpp.
References llvm::object::Binary::isMachO().
std::unique_ptr< RuntimeDyld::LoadedObjectInfo > llvm::RuntimeDyldMachO::loadObject (const object::ObjectFile & O) [override, virtual]
Implements llvm::RuntimeDyldImpl.
Definition at line 305 of file RuntimeDyldMachO.cpp.
void llvm::RuntimeDyldMachO::makeValueAddendPCRel (RelocationValueRef & Value, const ObjectFile & BaseTObj, const relocation_iterator & RI, unsigned OffsetToNextPC) [protected]
Make the RelocationValueRef addend PC-relative.
Definition at line 89 of file RuntimeDyldMachO.cpp.
References llvm::object::MachOObjectFile::getAnyRelocationPCRel(), llvm::object::MachOObjectFile::getRelocation(), and llvm::RelocationValueRef::Offset.
Referenced by llvm::RuntimeDyldMachOX86_64::processRelocationRef(), llvm::RuntimeDyldMachOI386::processRelocationRef(), llvm::RuntimeDyldMachOARM::processRelocationRef(), and llvm::RuntimeDyldMachOAArch64::processRelocationRef().
int64_t llvm::RuntimeDyldMachO::memcpyAddend (const RelocationEntry & RE) const [protected]
This convenience method uses memcpy to extract a contiguous addend (the addend size and offset are taken from the corresponding fields of the RE).
Definition at line 46 of file RuntimeDyldMachO.cpp.
References llvm::RelocationEntry::Offset, llvm::RelocationEntry::SectionID, and llvm::RelocationEntry::Size.
Referenced by llvm::RuntimeDyldMachOARM::decodeAddend(), llvm::RuntimeDyldMachOI386::processRelocationRef(), and llvm::RuntimeDyldMachOX86_64::processRelocationRef().
void llvm::RuntimeDyldMachO::populateIndirectSymbolPointersSection (const MachOObjectFile & Obj, const SectionRef & PTSection, unsigned PTSectionID) [protected]
Definition at line 138 of file RuntimeDyldMachO.cpp.
References llvm::dbgs(), DEBUG, llvm::MachO::GENERIC_RELOC_VANILLA, llvm::object::MachOObjectFile::getDysymtabLoadCommand(), llvm::object::MachOObjectFile::getIndirectSymbolTableEntry(), llvm::object::SymbolRef::getName(), llvm::object::SectionRef::getRawDataRefImpl(), llvm::object::MachOObjectFile::getSection(), llvm::object::MachOObjectFile::getSymbolByIndex(), llvm::object::MachOObjectFile::is64Bit(), llvm::MachO::section::reserved1, llvm::SI, and llvm::MachO::section::size.
Referenced by llvm::RuntimeDyldMachOI386::finalizeSection(), and llvm::RuntimeDyldMachOARM::finalizeSection().
Member Data Documentation
SmallVector<EHFrameRelatedSections, 2> llvm::RuntimeDyldMachO::UnregisteredEHFrameSections [protected]
Definition at line 50 of file RuntimeDyldMachO.h.
The documentation for this class was generated from the following files:
RuntimeDyldMachO.h
RuntimeDyldMachO.cpp