LLVM: llvm::HexagonRegisterInfo Class Reference
llvm::HexagonRegisterInfo Class Reference
#include <HexagonRegisterInfo.h>
Public Member Functions
HexagonRegisterInfo ()
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
Code Generation virtual methods...
BitVector getReservedRegs (const MachineFunction &MF) const override
void eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
bool requiresRegisterScavenging (const MachineFunction &MF) const override
Returns true since we may need scavenging for a temporary register when generating hardware loop instructions.
bool requiresFrameIndexScavenging (const MachineFunction &MF) const override
Returns true.
bool needsStackRealignment (const MachineFunction &MF) const override
bool useFPForScavengingIndex (const MachineFunction &MF) const override
Returns true if the frame pointer is valid.
bool trackLivenessAfterRegAlloc (const MachineFunction &MF) const override
unsigned getRARegister () const
unsigned getFrameRegister (const MachineFunction &MF) const override
unsigned getFrameRegister () const
unsigned getStackRegister () const
const MCPhysReg * getCallerSavedRegs (const MachineFunction *MF) const
unsigned getFirstCallerSavedNonParamReg () const
bool isEHReturnCalleeSaveReg (unsigned Reg) const
bool isCalleeSaveReg (unsigned Reg) const
Detailed Description
Definition at line 40 of file HexagonRegisterInfo.h.
Constructor & Destructor Documentation
HexagonRegisterInfo::HexagonRegisterInfo ()
Definition at line 42 of file HexagonRegisterInfo.cpp.
Member Function Documentation
void HexagonRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const [override]
Definition at line 111 of file HexagonRegisterInfo.cpp.
References llvm::BP, llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), llvm::dbgs(), F(), llvm::MachineFunction::getFrameInfo(), getFrameRegister(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::HexagonSubtarget::getInstrInfo(), llvm::Value::getName(), llvm::MachineBasicBlock::getNumber(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), getStackRegister(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::MachineInstr::isDebugValue(), llvm::MachineFrameInfo::isFixedObjectIndex(), llvm::MachineInstr::isInlineAsm(), llvm::MachineFrameInfo::isObjectPreAllocated(), llvm_unreachable, llvm::AArch64CC::MI, needsStackRealignment(), llvm::MachineInstr::RemoveOperand(), llvm::MachineInstr::setDesc(), and llvm::SP.
const MCPhysReg * HexagonRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const [override]
Code Generation virtual methods...
Definition at line 77 of file HexagonRegisterInfo.cpp.
References llvm::HexagonSubtarget::getHexagonArchVersion(), llvm::MachineFunction::getSubtarget(), llvm_unreachable, llvm::HexagonSubtarget::V4, and llvm::HexagonSubtarget::V5.
Referenced by llvm::HexagonFrameLowering::processFunctionBeforeCalleeSavedScan().
const MCPhysReg * HexagonRegisterInfo::getCallerSavedRegs (const MachineFunction * MF) const
Definition at line 57 of file HexagonRegisterInfo.cpp.
References llvm::MachineFunction::getSubtarget(), llvm_unreachable, llvm::R10, llvm::R11, llvm::R12, llvm::R13, llvm::R14, llvm::R15, llvm::R8, llvm::R9, llvm::HexagonSubtarget::V4, and llvm::HexagonSubtarget::V5.
Referenced by needToReserveScavengingSpillSlots().
unsigned HexagonRegisterInfo::getFirstCallerSavedNonParamReg () const
Definition at line 254 of file HexagonRegisterInfo.cpp.
unsigned HexagonRegisterInfo::getFrameRegister (const MachineFunction & MF) const [override]
Definition at line 222 of file HexagonRegisterInfo.cpp.
References llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFunction::getSubtarget(), and llvm::TargetFrameLowering::hasFP().
Referenced by llvm::HexagonInstrInfo::expandPostRAPseudo(), and llvm::HexagonTargetLowering::LowerFRAMEADDR().
unsigned HexagonRegisterInfo::getFrameRegister () const
Definition at line 231 of file HexagonRegisterInfo.cpp.
Referenced by eliminateFrameIndex().
unsigned HexagonRegisterInfo::getRARegister () const
Definition at line 217 of file HexagonRegisterInfo.cpp.
Referenced by llvm::HexagonTargetLowering::LowerINLINEASM(), and llvm::HexagonTargetLowering::LowerRETURNADDR().
BitVector HexagonRegisterInfo::getReservedRegs (const MachineFunction & MF) const [override]
Definition at line 93 of file HexagonRegisterInfo.cpp.
References HEXAGON_RESERVED_REG_1, HEXAGON_RESERVED_REG_2, llvm::Reserved, and llvm::BitVector::set().
unsigned HexagonRegisterInfo::getStackRegister () const
Definition at line 236 of file HexagonRegisterInfo.cpp.
Referenced by eliminateFrameIndex().
bool HexagonRegisterInfo::isCalleeSaveReg (unsigned Reg) const
Definition at line 51 of file HexagonRegisterInfo.cpp.
bool HexagonRegisterInfo::isEHReturnCalleeSaveReg (unsigned Reg) const
Definition at line 46 of file HexagonRegisterInfo.cpp.
bool HexagonRegisterInfo::needsStackRealignment (const MachineFunction & MF) const [override]
Definition at line 248 of file HexagonRegisterInfo.cpp.
References llvm::MachineFunction::getFrameInfo(), and llvm::MachineFrameInfo::getMaxAlignment().
Referenced by eliminateFrameIndex().
bool llvm::HexagonRegisterInfo::requiresFrameIndexScavenging (const MachineFunction & MF) const [inline, override]
Returns true.
Spill code for predicate registers might need an extra register.
Definition at line 62 of file HexagonRegisterInfo.h.
bool llvm::HexagonRegisterInfo::requiresRegisterScavenging (const MachineFunction & MF) const [inline, override]
Returns true since we may need scavenging for a temporary register when generating hardware loop instructions.
Definition at line 56 of file HexagonRegisterInfo.h.
bool llvm::HexagonRegisterInfo::trackLivenessAfterRegAlloc (const MachineFunction & MF) const [inline, override]
Definition at line 71 of file HexagonRegisterInfo.h.
bool HexagonRegisterInfo::useFPForScavengingIndex (const MachineFunction & MF) const [override]
Returns true if the frame pointer is valid.
Definition at line 242 of file HexagonRegisterInfo.cpp.
References llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFunction::getSubtarget(), and llvm::TargetFrameLowering::hasFP().
The documentation for this class was generated from the following files:
HexagonRegisterInfo.h
HexagonRegisterInfo.cpp