LLVM: fuzzer::Fuzzer Class Reference
fuzzer::Fuzzer Class Reference
#include <FuzzerInternal.h>
Classes
struct FuzzingOptions
Public Member Functions
Fuzzer (UserSuppliedFuzzer &USF, FuzzingOptions Options)
void AddToCorpus (const Unit &U)
void Loop (size_t NumIterations)
void ShuffleAndMinimize ()
void InitializeTraceState ()
size_t CorpusSize () const
void ReadDir (const std::string &Path, long *Epoch)
void RereadOutputCorpus ()
void SaveCorpus ()
size_t secondsSinceProcessStartUp ()
size_t getTotalNumberOfRuns ()
Unit SubstituteTokens (const Unit &U) const
Static Public Member Functions
static void StaticAlarmCallback ()
Detailed Description
Definition at line 56 of file FuzzerInternal.h.
Constructor & Destructor Documentation
fuzzer::Fuzzer::Fuzzer (UserSuppliedFuzzer & USF, FuzzingOptions Options)
Definition at line 21 of file FuzzerLoop.cpp.
References fuzzer::F, and InitializeTraceState().
Member Function Documentation
void fuzzer::Fuzzer::AddToCorpus (const Unit & U) [inline]
Definition at line 77 of file FuzzerInternal.h.
size_t fuzzer::Fuzzer::CorpusSize () const [inline]
Definition at line 81 of file FuzzerInternal.h.
size_t fuzzer::Fuzzer::getTotalNumberOfRuns () [inline]
Definition at line 94 of file FuzzerInternal.h.
void fuzzer::Fuzzer::InitializeTraceState ()
Definition at line 313 of file FuzzerTraceState.cpp.
References fuzzer::ReallyHaveDFSan().
Referenced by Fuzzer().
void fuzzer::Fuzzer::Loop (size_t NumIterations)
Definition at line 305 of file FuzzerLoop.cpp.
References fuzzer::UserSuppliedFuzzer::CrossOver(), fuzzer::Fuzzer::FuzzingOptions::DoCrossOver, fuzzer::Fuzzer::FuzzingOptions::MaxLen, fuzzer::Fuzzer::FuzzingOptions::MaxNumberOfRuns, RereadOutputCorpus(), and size.
void fuzzer::Fuzzer::ReadDir (const std::string & Path, long * Epoch) [inline]
Definition at line 82 of file FuzzerInternal.h.
References fuzzer::ReadDirToVectorOfUnits().
void fuzzer::Fuzzer::RereadOutputCorpus ()
Definition at line 86 of file FuzzerLoop.cpp.
References fuzzer::Hash(), fuzzer::Fuzzer::FuzzingOptions::MaxLen, fuzzer::Fuzzer::FuzzingOptions::OutputCorpus, fuzzer::Printf(), fuzzer::ReadDirToVectorOfUnits(), fuzzer::Fuzzer::FuzzingOptions::Reload, fuzzer::Fuzzer::FuzzingOptions::Verbosity, and X.
Referenced by Loop().
void fuzzer::Fuzzer::SaveCorpus ()
Definition at line 258 of file FuzzerLoop.cpp.
References fuzzer::DirPlusFile(), fuzzer::Hash(), fuzzer::Fuzzer::FuzzingOptions::OutputCorpus, fuzzer::Printf(), fuzzer::Fuzzer::FuzzingOptions::Verbosity, and fuzzer::WriteToFile().
size_t fuzzer::Fuzzer::secondsSinceProcessStartUp () [inline]
Definition at line 89 of file FuzzerInternal.h.
void fuzzer::Fuzzer::ShuffleAndMinimize ()
Definition at line 114 of file FuzzerLoop.cpp.
References llvm::ARM_PROC::A, llvm::C, fuzzer::Hash(), llvm::IndexedInstrProf::Last, fuzzer::Fuzzer::FuzzingOptions::MaxLen, fuzzer::min(), fuzzer::Fuzzer::FuzzingOptions::PreferSmallDuringInitialShuffle, fuzzer::Printf(), fuzzer::Fuzzer::FuzzingOptions::Verbosity, and X.
void fuzzer::Fuzzer::StaticAlarmCallback () [static]
Definition at line 55 of file FuzzerLoop.cpp.
References fuzzer::F.
Referenced by fuzzer::AlarmHandler().
Unit fuzzer::Fuzzer::SubstituteTokens (const Unit & U) const
Definition at line 182 of file FuzzerLoop.cpp.
References fuzzer::Fuzzer::FuzzingOptions::Tokens.
The documentation for this class was generated from the following files:
FuzzerInternal.h
FuzzerLoop.cpp
FuzzerTraceState.cpp