LLVM: llvm::PPCTargetMachine Class Reference
llvm::PPCTargetMachine Class Reference
PPCTargetMachine - Common code between 32-bit and 64-bit PowerPC targets.
#include <PPCTargetMachine.h>
Public Types
enum PPCABI { PPC_ABI_UNKNOWN, PPC_ABI_ELFv1, PPC_ABI_ELFv2 }
Public Member Functions
PPCTargetMachine (const Target &T, const Triple &TT, StringRef CPU, StringRef FS, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
~PPCTargetMachine () override
const PPCSubtarget * getSubtargetImpl (const Function &F) const override
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
TargetPassConfig * createPassConfig (PassManagerBase &PM) override
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
TargetIRAnalysis getTargetIRAnalysis () override
Get a TargetIRAnalysis implementation for the target.
TargetLoweringObjectFile * getObjFileLowering () const override
bool isELFv2ABI () const
bool isPPC64 () const
Detailed Description
PPCTargetMachine - Common code between 32-bit and 64-bit PowerPC targets.
Definition at line 26 of file PPCTargetMachine.h.
Member Enumeration Documentation
enum llvm::PPCTargetMachine::PPCABI
Enumerator:
PPC_ABI_UNKNOWN
PPC_ABI_ELFv1
PPC_ABI_ELFv2
Definition at line 28 of file PPCTargetMachine.h.
Constructor & Destructor Documentation
PPCTargetMachine::PPCTargetMachine (const Target & T, const Triple & TT, StringRef CPU, StringRef FS, const TargetOptions & Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
Definition at line 167 of file PPCTargetMachine.cpp.
References llvm::LLVMTargetMachine::initAsmInfo().
PPCTargetMachine::~PPCTargetMachine () [override]
Definition at line 179 of file PPCTargetMachine.cpp.
Member Function Documentation
TargetPassConfig * PPCTargetMachine::createPassConfig (PassManagerBase & PM) [override, virtual]
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
createPassConfig - Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
Targets may override this to extend TargetPassConfig.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 256 of file PPCTargetMachine.cpp.
TargetLoweringObjectFile* llvm::PPCTargetMachine::getObjFileLowering () const [inline, override, virtual]
Reimplemented from llvm::TargetMachine.
Definition at line 48 of file PPCTargetMachine.h.
const PPCSubtarget * PPCTargetMachine::getSubtargetImpl (const Function &) const [override, virtual]
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
Reimplemented from llvm::TargetMachine.
Definition at line 200 of file PPCTargetMachine.cpp.
References computeFSAdditions(), llvm::FS, llvm::Function::getFnAttribute(), llvm::TargetMachine::getOptLevel(), llvm::TargetMachine::getTargetTriple(), llvm::Attribute::getValueAsString(), llvm::Attribute::hasAttribute(), I, llvm::Attribute::None, llvm::TargetMachine::resetTargetOptions(), llvm::StringRef::str(), llvm::TargetMachine::TargetCPU, llvm::TargetMachine::TargetFS, and llvm::TargetMachine::TargetTriple.
TargetIRAnalysis PPCTargetMachine::getTargetIRAnalysis () [override, virtual]
Get a TargetIRAnalysis implementation for the target.
This analysis will produce a TTI result which uses the common code generator to answer queries about the IR.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 347 of file PPCTargetMachine.cpp.
References F().
bool llvm::PPCTargetMachine::isELFv2ABI () const [inline]
Definition at line 51 of file PPCTargetMachine.h.
References PPC_ABI_ELFv2.
Referenced by llvm::PPCSubtarget::isELFv2ABI().
bool llvm::PPCTargetMachine::isPPC64 () const [inline]
Definition at line 52 of file PPCTargetMachine.h.
References llvm::Triple::getArch(), llvm::TargetMachine::getTargetTriple(), llvm::Triple::ppc64, and llvm::Triple::ppc64le.
Referenced by llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::getBaseRegister(), llvm::PPCRegisterInfo::getCalleeSavedRegs(), llvm::PPCRegisterInfo::getCallPreservedMask(), llvm::PPCRegisterInfo::getFrameRegister(), llvm::PPCRegisterInfo::getPointerRegClass(), llvm::PPCRegisterInfo::getReservedRegs(), llvm::PPCRegisterInfo::hasReservedSpillSlot(), llvm::PPCSubtarget::isPPC64(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), and llvm::PPCRegisterInfo::materializeFrameBaseRegister().
The documentation for this class was generated from the following files:
PPCTargetMachine.h
PPCTargetMachine.cpp