LLVM: llvm::MCSymbol Class Reference
llvm::MCSymbol Class Reference
MCSymbol - Instances of this class represent a symbol name in the MC file, and MCSymbols are created and uniqued by the MCContext class.
#include <MCSymbol.h>
Classes
union NameEntryStorageTy
The name for a symbol.
Public Member Functions
StringRef getName () const
getName - Get the symbol name.
bool isRegistered () const
void setIsRegistered (bool Value) const
void setUsedInReloc () const
bool isUsedInReloc () const
bool isDefined () const
isDefined - Check if this symbol is defined (i.e., it has an address).
bool isInSection () const
isInSection - Check if this symbol is defined in some section (i.e., it is defined but not absolute).
bool isUndefined () const
isUndefined - Check if this symbol undefined (i.e., implicitly defined).
bool isAbsolute () const
isAbsolute - Check if this is an absolute symbol.
MCSection & getSection () const
Get the section associated with a defined, non-absolute symbol.
void setSection (MCSection &S)
Mark the symbol as defined in the section S.
void setUndefined ()
Mark the symbol as undefined.
bool isELF () const
bool isCOFF () const
bool isMachO () const
bool isVariable () const
isVariable - Check if this is a variable symbol.
const MCExpr * getVariableValue () const
getVariableValue() - Get the value for variable symbols.
void setVariableValue (const MCExpr *Value)
uint32_t getIndex () const
Get the (implementation defined) index.
void setIndex (uint32_t Value) const
Set the (implementation defined) index.
uint64_t getOffset () const
void setOffset (uint64_t Value)
uint64_t getCommonSize () const
Return the size of a 'common' symbol.
void setCommon (uint64_t Size, unsigned Align)
Mark this symbol as being 'common'.
unsigned getCommonAlignment () const
Return the alignment of a 'common' symbol.
bool declareCommon (uint64_t Size, unsigned Align)
Declare this symbol as being 'common'.
bool isCommon () const
Is this a 'common' symbol.
MCFragment * getFragment () const
void setFragment (MCFragment *Value) const
bool isExternal () const
void setExternal (bool Value) const
bool isPrivateExtern () const
void setPrivateExtern (bool Value)
void print (raw_ostream &OS, const MCAsmInfo *MAI) const
print - Print the value to the stream OS.
void dump () const
dump - Print the value to stderr.
Accessors
bool isTemporary () const
isTemporary - Check if this is an assembler temporary symbol.
bool isUsed () const
isUsed - Check if this is used.
void setUsed (bool Value) const
bool isRedefinable () const
Check if this symbol is redefinable.
void setRedefinable (bool Value)
Mark this symbol as redefinable.
void redefineIfPossible ()
Prepare this symbol to be redefined.
Protected Types
enum SymbolKind { SymbolKindUnset, SymbolKindCOFF, SymbolKindELF, SymbolKindMachO }
The kind of the symbol.
enum Contents { SymContentsUnset, SymContentsOffset, SymContentsVariable, SymContentsCommon }
A symbol can contain an Offset, or Value, or be Common, but never more than one of these.
Protected Member Functions
MCSymbol (SymbolKind Kind, const StringMapEntry< bool > *Name, bool isTemporary)
void * operator new (size_t s, const StringMapEntry< bool > *Name, MCContext &Ctx)
uint32_t getFlags () const
Get the (implementation defined) symbol flags.
void setFlags (uint32_t Value) const
Set the (implementation defined) symbol flags.
void modifyFlags (uint32_t Value, uint32_t Mask) const
Modify the flags via a mask.
Protected Attributes
PointerUnion< MCSection
*, MCFragment * > SectionOrFragment
If a symbol has a Fragment, the section is implied, so we only need one pointer.
unsigned IsTemporary: 1
IsTemporary - True if this is an assembler temporary label, which typically does not survive in the .o file's symbol table.
unsigned IsRedefinable: 1
True if this symbol can be redefined.
unsigned IsUsed: 1
IsUsed - True if this symbol has been used.
bool IsRegistered: 1
unsigned IsExternal: 1
This symbol is visible outside this translation unit.
unsigned IsPrivateExtern: 1
This symbol is private extern.
unsigned HasName: 1
True if this symbol is named.
unsigned Kind: 2
LLVM RTTI discriminator.
unsigned IsUsedInReloc: 1
True if we have created a relocation that uses this symbol.
unsigned SymbolContents: 2
This is actually a Contents enumerator, but is unsigned to avoid sign extension and achieve better bitpacking with MSVC.
uint32_t Index = 0
Index field, for use by the object file implementation.
union {
uint64_t Offset
The offset to apply to the fragment address to form this symbol's value.
uint64_t CommonSize
The size of the symbol, if it is 'common'.
const MCExpr * Value
If non-null, the value for a variable symbol.
};
unsigned CommonAlign = -1U
The alignment of the symbol, if it is 'common', or -1.
uint32_t Flags = 0
The Flags field is used by object file implementations to store additional per symbol information which is not easily classified.
Static Protected Attributes
static MCSection * AbsolutePseudoSection = reinterpret_cast<MCSection *>(1)
Friends
class MCExpr
class MCContext
Detailed Description
MCSymbol - Instances of this class represent a symbol name in the MC file, and MCSymbols are created and uniqued by the MCContext class.
MCSymbols should only be constructed with valid names for the object file.
If the symbol is defined/emitted into the current translation unit, the Section member is set to indicate what section it lives in. Otherwise, if it is a reference to an external entity, it has a null section.
Definition at line 38 of file MCSymbol.h.
Member Enumeration Documentation
enum llvm::MCSymbol::Contents [protected]
A symbol can contain an Offset, or Value, or be Common, but never more than one of these.
Enumerator:
SymContentsUnset
SymContentsOffset
SymContentsVariable
SymContentsCommon
Definition at line 51 of file MCSymbol.h.
enum llvm::MCSymbol::SymbolKind [protected]
The kind of the symbol.
If it is any value other than unset then this class is actually one of the appropriate subclasses of MCSymbol.
Enumerator:
SymbolKindUnset
SymbolKindCOFF
SymbolKindELF
SymbolKindMachO
Definition at line 42 of file MCSymbol.h.
Constructor & Destructor Documentation
llvm::MCSymbol::MCSymbol (SymbolKind Kind, const StringMapEntry< bool > * Name, bool isTemporary) [inline, protected]
Definition at line 147 of file MCSymbol.h.
References Offset.
Member Function Documentation
bool llvm::MCSymbol::declareCommon (uint64_t Size, unsigned Align) [inline]
Declare this symbol as being 'common'.
Parameters:
Size - The size of the symbol.
Align - The alignment of the symbol.
Returns:
True if symbol was already declared as a different type
Definition at line 348 of file MCSymbol.h.
References CommonAlign, CommonSize, getOffset(), isCommon(), and setCommon().
void MCSymbol::dump () const
dump - Print the value to stderr.
Definition at line 77 of file MCSymbol.cpp.
References llvm::dbgs().
unsigned llvm::MCSymbol::getCommonAlignment () const [inline]
Return the alignment of a 'common' symbol.
Definition at line 338 of file MCSymbol.h.
Referenced by llvm::MCSymbolMachO::getEncodedFlags().
uint64_t llvm::MCSymbol::getCommonSize () const [inline]
Return the size of a 'common' symbol.
Definition at line 321 of file MCSymbol.h.
Referenced by getSymbolValue(), and llvm::MachObjectWriter::writeNlist().
uint32_t llvm::MCSymbol::getFlags () const [inline, protected]
Get the (implementation defined) symbol flags.
Definition at line 384 of file MCSymbol.h.
Referenced by llvm::MCSymbolELF::getBinding(), llvm::MCSymbolCOFF::getClass(), llvm::MCSymbolMachO::getEncodedFlags(), llvm::MCSymbolELF::getOther(), llvm::MCSymbolELF::getType(), llvm::MCSymbolELF::getVisibility(), llvm::MCSymbolELF::isBindingSet(), llvm::MCSymbolMachO::isNoDeadStrip(), llvm::MCSymbolCOFF::isSafeSEH(), llvm::MCSymbolELF::isSignature(), llvm::MCSymbolMachO::isSymbolResolver(), llvm::MCSymbolMachO::isWeakDefinition(), llvm::MCSymbolCOFF::isWeakExternal(), llvm::MCSymbolMachO::isWeakReference(), llvm::MCSymbolELF::isWeakrefUsedInReloc(), llvm::MCSymbolELF::setBinding(), llvm::MCSymbolELF::setIsSignature(), llvm::MCSymbolELF::setIsWeakrefUsedInReloc(), llvm::MCSymbolELF::setOther(), llvm::MCSymbolELF::setType(), and llvm::MCSymbolELF::setVisibility().
MCFragment* llvm::MCSymbol::getFragment () const [inline]
Definition at line 363 of file MCSymbol.h.
References SymbolContents, and SymContentsCommon.
Referenced by llvm::MCObjectStreamer::emitAbsoluteSymbolDiff(), llvm::MCObjectStreamer::EmitLabel(), llvm::MCAssembler::getAtom(), getLabelOffset(), llvm::MachObjectWriter::getSymbolAddress(), llvm::MCObjectWriter::isSymbolRefDifferenceFullyResolved(), and llvm::MachObjectWriter::isSymbolRefDifferenceFullyResolvedImpl().
uint32_t llvm::MCSymbol::getIndex () const [inline]
Get the (implementation defined) index.
Definition at line 297 of file MCSymbol.h.
Referenced by writeFragment().
StringRef llvm::MCSymbol::getName () const [inline]
getName - Get the symbol name.
Definition at line 198 of file MCSymbol.h.
References llvm::StringMapEntry< ValueTy >::first(), and HasName.
Referenced by llvm::MachObjectWriter::bindIndirectSymbols(), llvm::MCWinCOFFStreamer::EmitCommonSymbol(), llvm::MipsTargetAsmStreamer::emitDirectiveCpsetup(), llvm::MipsTargetAsmStreamer::emitDirectiveEnt(), llvm::EHStreamer::emitExceptionTable(), llvm::MipsAsmPrinter::EmitFunctionBodyEnd(), llvm::AsmPrinter::EmitFunctionEntryLabel(), llvm::AsmPrinter::EmitGlobalVariable(), llvm::TargetLoweringObjectFileELF::emitPersonalityValue(), EvaluateCRExpr(), GetAnonSym(), llvm::MCContext::getAssociativeCOFFSection(), llvm::MCAsmLayout::getBaseSymbol(), llvm::TargetLoweringObjectFileELF::getCFIPersonalitySymbol(), llvm::MCContext::getCOFFSection(), llvm::MCContext::getELFSection(), llvm::MCSymbolMachO::getEncodedFlags(), llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), getLabelOffset(), GetLazyPtr(), llvm::TargetLoweringObjectFileCOFF::getSectionForJumpTable(), getStaticStructorSection(), llvm::MachObjectWriter::getSymbolAddress(), getSymbolOffsetImpl(), hasGOTReference(), llvm::HexagonMCELFStreamer::HexagonMCEmitCommonSymbol(), llvm::MCGenDwarfLabelEntry::Make(), llvm::MCExpr::print(), llvm::DIELabel::print(), llvm::DIEDelta::print(), print(), llvm::MipsAsmPrinter::printOperand(), llvm::NVPTXInstPrinter::printProtoIdent(), llvm::MCSectionELF::PrintSwitchToSection(), printSymbolOperand(), llvm::PPCInstPrinter::printTLSCall(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), SortSymbolPair(), StartsWithGlobalOffsetTable(), and llvm::MachObjectWriter::writeObject().
uint64_t llvm::MCSymbol::getOffset () const [inline]
Definition at line 306 of file MCSymbol.h.
References Index, and Value.
Referenced by declareCommon(), llvm::MCObjectStreamer::emitAbsoluteSymbolDiff(), getLabelOffset(), and setCommon().
MCSection& llvm::MCSymbol::getSection () const [inline]
Get the section associated with a defined, non-absolute symbol.
Definition at line 255 of file MCSymbol.h.
References isInSection().
Referenced by llvm::DwarfCompileUnit::addRange(), llvm::MCWinCOFFStreamer::BeginCOFFSymbolDef(), canUseLocalRelocation(), llvm::MCWinCOFFStreamer::EmitCommonSymbol(), llvm::AsmPrinter::emitDwarfSymbolReference(), llvm::MCWinCOFFStreamer::EmitSymbolAttribute(), llvm::MCExpr::findAssociatedSection(), llvm::MCELFStreamer::Flush(), llvm::WinEH::getUnwindInfoSection(), llvm::MCObjectWriter::isSymbolRefDifferenceFullyResolvedImpl(), and llvm::MachObjectWriter::isSymbolRefDifferenceFullyResolvedImpl().
const MCExpr* llvm::MCSymbol::getVariableValue () const [inline]
getVariableValue() - Get the value for variable symbols.
Definition at line 286 of file MCSymbol.h.
Referenced by canExpand(), llvm::MachObjectWriter::findAliasedSymbol(), llvm::MCAsmLayout::getBaseSymbol(), llvm::MachObjectWriter::getSymbolAddress(), getSymbolOffsetImpl(), llvm::MCParserUtils::isSymbolUsedInExpression(), llvm::MCAssembler::isThumbFunc(), and llvm::MCParserUtils::parseAssignmentExpression().
bool llvm::MCSymbol::isAbsolute () const [inline]
isAbsolute - Check if this is an absolute symbol.
Definition at line 252 of file MCSymbol.h.
References AbsolutePseudoSection.
Referenced by isInSection(), and llvm::MachObjectWriter::writeNlist().
bool llvm::MCSymbol::isCOFF () const [inline]
Definition at line 274 of file MCSymbol.h.
References Kind, and SymbolKindELF.
Referenced by llvm::MCSymbolCOFF::classof().
bool llvm::MCSymbol::isCommon () const [inline]
Is this a 'common' symbol.
Definition at line 359 of file MCSymbol.h.
Referenced by declareCommon(), llvm::MCAsmLayout::getBaseSymbol(), llvm::MCSymbolMachO::getEncodedFlags(), getSymbolValue(), and llvm::MachObjectWriter::writeNlist().
bool llvm::MCSymbol::isDefined () const [inline]
isDefined - Check if this symbol is defined (i.e., it has an address).
Defined symbols are either absolute or in some section.
Definition at line 242 of file MCSymbol.h.
Referenced by llvm::DwarfCompileUnit::attachLowHighPC(), llvm::AsmPrinter::EmitFunctionBody(), llvm::AsmPrinter::EmitFunctionEntryLabel(), llvm::AsmPrinter::EmitGlobalVariable(), llvm::MCSymbolELF::getBinding(), isInSection(), isUndefined(), llvm::MachineModuleInfo::TidyLandingPads(), llvm::MMIAddrLabelMap::UpdateForDeletedBlock(), and llvm::MachObjectWriter::writeNlist().
bool llvm::MCSymbol::isELF () const [inline]
Definition at line 272 of file MCSymbol.h.
Referenced by llvm::MCSymbolELF::classof().
bool llvm::MCSymbol::isExternal () const [inline]
Definition at line 370 of file MCSymbol.h.
Referenced by getSymbolValue(), and llvm::MachObjectWriter::writeNlist().
bool llvm::MCSymbol::isInSection () const [inline]
isInSection - Check if this symbol is defined in some section (i.e., it is defined but not absolute).
Definition at line 246 of file MCSymbol.h.
References isAbsolute(), and isDefined().
Referenced by llvm::MCWinCOFFStreamer::BeginCOFFSymbolDef(), canUseLocalRelocation(), llvm::MCWinCOFFStreamer::EmitCommonSymbol(), llvm::MCWinCOFFStreamer::EmitLocalCommonSymbol(), llvm::MCWinCOFFStreamer::EmitSymbolAttribute(), llvm::MCStreamer::endSection(), getSection(), llvm::WinEH::getUnwindInfoSection(), llvm::MCSection::hasEnded(), llvm::MCAssembler::isSymbolLinkerVisible(), and llvm::MachObjectWriter::isSymbolRefDifferenceFullyResolvedImpl().
bool llvm::MCSymbol::isMachO () const [inline]
Definition at line 276 of file MCSymbol.h.
References Kind, and SymbolKindCOFF.
Referenced by llvm::MCSymbolMachO::classof().
bool llvm::MCSymbol::isPrivateExtern () const [inline]
Definition at line 373 of file MCSymbol.h.
Referenced by llvm::MachObjectWriter::writeNlist().
bool llvm::MCSymbol::isRedefinable () const [inline]
Check if this symbol is redefinable.
Definition at line 222 of file MCSymbol.h.
References IsRedefinable.
bool llvm::MCSymbol::isRegistered () const [inline]
Definition at line 205 of file MCSymbol.h.
References IsRegistered.
Referenced by llvm::MCAssembler::registerSymbol().
bool llvm::MCSymbol::isTemporary () const [inline]
isTemporary - Check if this is an assembler temporary symbol.
Definition at line 215 of file MCSymbol.h.
References IsTemporary.
Referenced by llvm::MCAssembler::isSymbolLinkerVisible(), llvm::MachObjectWriter::isSymbolRefDifferenceFullyResolvedImpl(), and llvm::MCGenDwarfLabelEntry::Make().
bool llvm::MCSymbol::isUndefined () const [inline]
isUndefined - Check if this symbol undefined (i.e., implicitly defined).
Definition at line 249 of file MCSymbol.h.
References isDefined().
Referenced by llvm::MachObjectWriter::doesSymbolRequireExternRelocation(), llvm::AsmPrinter::EmitConstantPool(), llvm::MCWinCOFFStreamer::EmitLabel(), llvm::MCContext::getOrCreateSectionSymbol(), llvm::MachObjectWriter::getSymbolAddress(), llvm::MCObjectWriter::isSymbolRefDifferenceFullyResolved(), llvm::MCParserUtils::parseAssignmentExpression(), and llvm::MachObjectWriter::writeNlist().
bool llvm::MCSymbol::isUsed () const [inline]
isUsed - Check if this is used.
Definition at line 218 of file MCSymbol.h.
References IsUsed.
Referenced by llvm::MCParserUtils::parseAssignmentExpression().
bool llvm::MCSymbol::isUsedInReloc () const [inline]
Definition at line 209 of file MCSymbol.h.
References IsUsedInReloc.
Referenced by llvm::MCSymbolELF::getBinding(), and llvm::MCAssembler::isSymbolLinkerVisible().
bool llvm::MCSymbol::isVariable () const [inline]
isVariable - Check if this is a variable symbol.
Definition at line 281 of file MCSymbol.h.
Referenced by llvm::AsmPrinter::EmitFunctionEntryLabel(), llvm::AsmPrinter::EmitGlobalVariable(), llvm::MCStreamer::EmitLabel(), llvm::MachObjectWriter::findAliasedSymbol(), llvm::MCAsmLayout::getBaseSymbol(), llvm::MachObjectWriter::getSymbolAddress(), getSymbolOffsetImpl(), llvm::MCParserUtils::isSymbolUsedInExpression(), llvm::MCAssembler::isThumbFunc(), llvm::MCParserUtils::parseAssignmentExpression(), and setSection().
void llvm::MCSymbol::modifyFlags (uint32_t Value, uint32_t Mask) const [inline, protected]
Modify the flags via a mask.
Definition at line 390 of file MCSymbol.h.
References Flags, and Value.
Referenced by llvm::MCSymbolMachO::clearReferenceType(), llvm::MCSymbolCOFF::setClass(), llvm::MCSymbolCOFF::setIsSafeSEH(), llvm::MCSymbolCOFF::setIsWeakExternal(), llvm::MCSymbolMachO::setNoDeadStrip(), llvm::MCSymbolMachO::setReferenceTypeUndefinedLazy(), llvm::MCSymbolMachO::setSymbolResolver(), llvm::MCSymbolMachO::setThumbFunc(), llvm::MCSymbolMachO::setWeakDefinition(), and llvm::MCSymbolMachO::setWeakReference().
void * MCSymbol::operator new (size_t s, const StringMapEntry< bool > * Name, MCContext & Ctx) [protected]
Definition at line 22 of file MCSymbol.cpp.
References llvm::MCContext::allocate(), and llvm::static_assert().
void MCSymbol::print (raw_ostream & OS, const MCAsmInfo * MAI) const
print - Print the value to the stream OS.
Definition at line 51 of file MCSymbol.cpp.
References llvm::C, getName(), llvm::MCAsmInfo::isValidUnquotedName(), llvm::report_fatal_error(), and llvm::MCAsmInfo::supportsNameQuoting().
Referenced by EmitGCCInlineAsmStr(), llvm::operator<<(), llvm::MCExpr::print(), printExpr(), llvm::HexagonAsmPrinter::printOperand(), llvm::ARMAsmPrinter::printOperand(), llvm::MipsAsmPrinter::printOperand(), llvm::MCSectionCOFF::PrintSwitchToSection(), and printSymbolOperand().
void llvm::MCSymbol::redefineIfPossible () [inline]
Prepare this symbol to be redefined.
Definition at line 226 of file MCSymbol.h.
References IsRedefinable, SectionOrFragment, SymbolContents, SymContentsUnset, and SymContentsVariable.
Referenced by llvm::AsmPrinter::EmitFunctionEntryLabel(), and llvm::AsmPrinter::EmitGlobalVariable().
void llvm::MCSymbol::setCommon (uint64_t Size, unsigned Align) [inline]
Mark this symbol as being 'common'.
Parameters:
Size - The size of the symbol.
Align - The alignment of the symbol.
Definition at line 330 of file MCSymbol.h.
References Align(), CommonAlign, CommonSize, and getOffset().
Referenced by declareCommon(), and llvm::MCWinCOFFStreamer::EmitCommonSymbol().
void llvm::MCSymbol::setExternal (bool Value) const [inline]
Definition at line 371 of file MCSymbol.h.
Referenced by llvm::MCWinCOFFStreamer::EmitCommonSymbol(), llvm::MCWinCOFFStreamer::EmitLocalCommonSymbol(), and llvm::MCWinCOFFStreamer::EmitSymbolAttribute().
void llvm::MCSymbol::setFlags (uint32_t Value) const [inline, protected]
Set the (implementation defined) symbol flags.
Definition at line 387 of file MCSymbol.h.
References Flags.
Referenced by llvm::MCSymbolELF::setBinding(), llvm::MCSymbolMachO::setDesc(), llvm::MCSymbolELF::setIsSignature(), llvm::MCSymbolELF::setIsWeakrefUsedInReloc(), llvm::MCSymbolELF::setOther(), llvm::MCSymbolELF::setType(), and llvm::MCSymbolELF::setVisibility().
void llvm::MCSymbol::setFragment (MCFragment * Value) const [inline]
Definition at line 366 of file MCSymbol.h.
References llvm::PointerUnion< PT1, PT2 >::dyn_cast(), and SectionOrFragment.
Referenced by llvm::MCObjectStreamer::EmitLabel(), llvm::MCWinCOFFStreamer::EmitLocalCommonSymbol(), and llvm::MCELFStreamer::Flush().
void llvm::MCSymbol::setIndex (uint32_t Value) const [inline]
Set the (implementation defined) index.
Definition at line 302 of file MCSymbol.h.
void llvm::MCSymbol::setIsRegistered (bool Value) const [inline]
Definition at line 206 of file MCSymbol.h.
References IsRegistered, and Value.
Referenced by llvm::MCAssembler::registerSymbol().
void llvm::MCSymbol::setOffset (uint64_t Value) [inline]
Definition at line 312 of file MCSymbol.h.
Referenced by llvm::MCObjectStreamer::EmitLabel().
void llvm::MCSymbol::setPrivateExtern (bool Value) [inline]
Definition at line 374 of file MCSymbol.h.
References IsExternal.
void llvm::MCSymbol::setRedefinable (bool Value) [inline]
Mark this symbol as redefinable.
Definition at line 224 of file MCSymbol.h.
References IsRedefinable, and Value.
Referenced by llvm::MCParserUtils::parseAssignmentExpression().
void llvm::MCSymbol::setSection (MCSection & S) [inline]
Mark the symbol as defined in the section S.
Definition at line 261 of file MCSymbol.h.
References llvm::PointerUnion< PT1, PT2 >::is(), isVariable(), and SectionOrFragment.
Referenced by llvm::MCStreamer::AssignSection().
void llvm::MCSymbol::setUndefined () [inline]
Mark the symbol as undefined.
Definition at line 268 of file MCSymbol.h.
References SectionOrFragment.
Referenced by llvm::MCStreamer::AssignSection().
void llvm::MCSymbol::setUsed (bool Value) const [inline]
Definition at line 219 of file MCSymbol.h.
References IsUsed, and Value.
Referenced by llvm::MCParserUtils::parseAssignmentExpression().
void llvm::MCSymbol::setUsedInReloc () const [inline]
Definition at line 208 of file MCSymbol.h.
References IsUsedInReloc.
void MCSymbol::setVariableValue (const MCExpr * Value)
Definition at line 40 of file MCSymbol.cpp.
References IsUsed, SectionOrFragment, SymbolContents, SymContentsUnset, SymContentsVariable, and Value.
Referenced by llvm::MCStreamer::EmitAssignment(), and llvm::MCELFStreamer::EmitWeakReference().
Friends And Related Function Documentation
friend class MCContext [friend]
Definition at line 136 of file MCSymbol.h.
friend class MCExpr [friend]
Definition at line 135 of file MCSymbol.h.
Member Data Documentation
union { ... } [protected]
MCSection * MCSymbol::AbsolutePseudoSection = reinterpret_cast<MCSection *>(1) [static, protected]
Definition at line 61 of file MCSymbol.h.
Referenced by llvm::MCExpr::findAssociatedSection(), and isAbsolute().
unsigned llvm::MCSymbol::CommonAlign = -1U [protected]
The alignment of the symbol, if it is 'common', or -1.
Definition at line 128 of file MCSymbol.h.
Referenced by declareCommon(), and setCommon().
uint64_t llvm::MCSymbol::CommonSize
The size of the symbol, if it is 'common'.
Definition at line 119 of file MCSymbol.h.
Referenced by declareCommon(), and setCommon().
uint32_t llvm::MCSymbol::Flags = 0 [mutable, protected]
The Flags field is used by object file implementations to store additional per symbol information which is not easily classified.
Definition at line 132 of file MCSymbol.h.
Referenced by llvm::MCSymbolMachO::getEncodedFlags(), modifyFlags(), and setFlags().
unsigned llvm::MCSymbol::HasName [protected]
True if this symbol is named.
A named symbol will have a pointer to the name allocated in the bytes immediately prior to the MCSymbol.
Definition at line 98 of file MCSymbol.h.
Referenced by getName().
uint32_t llvm::MCSymbol::Index = 0 [mutable, protected]
Index field, for use by the object file implementation.
Definition at line 112 of file MCSymbol.h.
Referenced by llvm::MMIAddrLabelMap::getAddrLabelSymbol(), and getOffset().
unsigned llvm::MCSymbol::IsExternal [mutable, protected]
This symbol is visible outside this translation unit.
Definition at line 90 of file MCSymbol.h.
Referenced by setPrivateExtern().
unsigned llvm::MCSymbol::IsPrivateExtern [mutable, protected]
This symbol is private extern.
Definition at line 93 of file MCSymbol.h.
unsigned llvm::MCSymbol::IsRedefinable [protected]
True if this symbol can be redefined.
Definition at line 82 of file MCSymbol.h.
Referenced by isRedefinable(), redefineIfPossible(), and setRedefinable().
bool llvm::MCSymbol::IsRegistered [mutable, protected]
Definition at line 87 of file MCSymbol.h.
Referenced by isRegistered(), and setIsRegistered().
unsigned llvm::MCSymbol::IsTemporary [protected]
IsTemporary - True if this is an assembler temporary label, which typically does not survive in the .o file's symbol table.
Usually "Lfoo" or ".foo".
Definition at line 79 of file MCSymbol.h.
Referenced by isTemporary().
unsigned llvm::MCSymbol::IsUsed [mutable, protected]
IsUsed - True if this symbol has been used.
Definition at line 85 of file MCSymbol.h.
Referenced by isUsed(), setUsed(), and setVariableValue().
unsigned llvm::MCSymbol::IsUsedInReloc [mutable, protected]
True if we have created a relocation that uses this symbol.
Definition at line 105 of file MCSymbol.h.
Referenced by isUsedInReloc(), and setUsedInReloc().
unsigned llvm::MCSymbol::Kind [protected]
LLVM RTTI discriminator.
This is actually a SymbolKind enumerator, but is unsigned to avoid sign extension and achieve better bitpacking with MSVC.
Definition at line 102 of file MCSymbol.h.
Referenced by isCOFF(), and isMachO().
uint64_t llvm::MCSymbol::Offset
The offset to apply to the fragment address to form this symbol's value.
Definition at line 116 of file MCSymbol.h.
Referenced by MCSymbol().
PointerUnion<MCSection *, MCFragment *> llvm::MCSymbol::SectionOrFragment [mutable, protected]
If a symbol has a Fragment, the section is implied, so we only need one pointer.
FIXME: We might be able to simplify this by having the asm streamer create dummy fragments. If this is a section, then it gives the symbol is defined in. This is null for undefined symbols, and the special AbsolutePseudoSection value for absolute symbols. If this is a variable symbol, this caches the variable value's section.
If this is a fragment, then it gives the fragment this symbol's value is relative to, if any.
Definition at line 74 of file MCSymbol.h.
Referenced by redefineIfPossible(), setFragment(), setSection(), setUndefined(), and setVariableValue().
unsigned llvm::MCSymbol::SymbolContents [protected]
This is actually a Contents enumerator, but is unsigned to avoid sign extension and achieve better bitpacking with MSVC.
Definition at line 109 of file MCSymbol.h.
Referenced by getFragment(), redefineIfPossible(), and setVariableValue().
const MCExpr* llvm::MCSymbol::Value
If non-null, the value for a variable symbol.
Definition at line 122 of file MCSymbol.h.
Referenced by getOffset(), modifyFlags(), setIsRegistered(), setRedefinable(), setUsed(), and setVariableValue().
The documentation for this class was generated from the following files:
MCSymbol.h
MCSymbol.cpp