LLVM: true::DivergencePropagator Class Reference
true::DivergencePropagator Class Reference
Public Member Functions
DivergencePropagator (Function &F, TargetTransformInfo &TTI, DominatorTree &DT, PostDominatorTree &PDT, DenseSet< const Value * > &DV)
void populateWithSourcesOfDivergence ()
void propagate ()
Detailed Description
Definition at line 128 of file DivergenceAnalysis.cpp.
Constructor & Destructor Documentation
true::DivergencePropagator::DivergencePropagator (Function & F, TargetTransformInfo & TTI, DominatorTree & DT, PostDominatorTree & PDT, DenseSet< const Value * > & DV) [inline]
Definition at line 130 of file DivergenceAnalysis.cpp.
Member Function Documentation
void true::DivergencePropagator::populateWithSourcesOfDivergence ()
Definition at line 159 of file DivergenceAnalysis.cpp.
References llvm::DenseSet< ValueT, ValueInfoT >::clear(), F(), I, and llvm::inst_range().
void true::DivergencePropagator::propagate ()
Definition at line 272 of file DivergenceAnalysis.cpp.
References llvm::TerminatorInst::getNumSuccessors().
The documentation for this class was generated from the following file:
DivergenceAnalysis.cpp