LLVM: llvm::RecurrenceDescriptor::InstDesc Class Reference
llvm::RecurrenceDescriptor::InstDesc Class Reference
This POD struct holds information about a potential recurrence operation.
#include <LoopUtils.h>
Public Member Functions
InstDesc (bool IsRecur, Instruction *I)
InstDesc (Instruction *I, MinMaxRecurrenceKind K)
bool isRecurrence ()
MinMaxRecurrenceKind getMinMaxKind ()
Instruction * getPatternInst ()
Detailed Description
This POD struct holds information about a potential recurrence operation.
Definition at line 95 of file LoopUtils.h.
Constructor & Destructor Documentation
llvm::RecurrenceDescriptor::InstDesc::InstDesc (bool IsRecur, Instruction * I) [inline]
Definition at line 98 of file LoopUtils.h.
llvm::RecurrenceDescriptor::InstDesc::InstDesc (Instruction * I, MinMaxRecurrenceKind K) [inline]
Definition at line 101 of file LoopUtils.h.
Member Function Documentation
MinMaxRecurrenceKind llvm::RecurrenceDescriptor::InstDesc::getMinMaxKind () [inline]
Definition at line 106 of file LoopUtils.h.
Referenced by llvm::RecurrenceDescriptor::AddReductionVar(), llvm::RecurrenceDescriptor::isMinMaxSelectCmpPattern(), and llvm::RecurrenceDescriptor::isRecurrenceInstr().
Instruction* llvm::RecurrenceDescriptor::InstDesc::getPatternInst () [inline]
Definition at line 108 of file LoopUtils.h.
bool llvm::RecurrenceDescriptor::InstDesc::isRecurrence () [inline]
Definition at line 104 of file LoopUtils.h.
Referenced by llvm::RecurrenceDescriptor::AddReductionVar().
The documentation for this class was generated from the following file:
LoopUtils.h