LLVM: llvm::TargetFrameLowering Class Reference
llvm::TargetFrameLowering Class Reference
Information about stack frame layout on the target.
#include <TargetFrameLowering.h>
Classes
struct SpillSlot
Public Types
enum StackDirection { StackGrowsUp, StackGrowsDown }
Public Member Functions
TargetFrameLowering (StackDirection D, unsigned StackAl, int LAO, unsigned TransAl=1, bool StackReal=true)
virtual ~TargetFrameLowering ()
StackDirection getStackGrowthDirection () const
getStackGrowthDirection - Return the direction the stack grows
unsigned getStackAlignment () const
getStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned on entry to a function.
unsigned getTransientStackAlignment () const
getTransientStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned at all times, even between calls.
bool isStackRealignable () const
isStackRealignable - This method returns whether the stack can be realigned.
int getOffsetOfLocalArea () const
getOffsetOfLocalArea - This method returns the offset of the local area from the stack pointer on entrance to a function.
virtual bool isFPCloseToIncomingSP () const
isFPCloseToIncomingSP - Return true if the frame pointer is close to the incoming stack pointer, false if it is close to the post-prologue stack pointer.
virtual bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI) const
assignCalleeSavedSpillSlots - Allows target to override spill slot assignment logic.
virtual const SpillSlot * getCalleeSavedSpillSlots (unsigned &NumEntries) const
getCalleeSavedSpillSlots - This method returns a pointer to an array of pairs, that contains an entry for each callee saved register that must be spilled to a particular stack location if it is spilled.
virtual bool targetHandlesStackFrameRounding () const
targetHandlesStackFrameRounding - Returns true if the target is responsible for rounding up the stack frame (probably at emitPrologue time).
virtual void emitPrologue (MachineFunction &MF, MachineBasicBlock &MBB) const =0
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
virtual void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const =0
virtual void adjustForSegmentedStacks (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to have the function use segmented stacks.
virtual void adjustForHiPEPrologue (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to add Erlang Run-Time System (ERTS) specific code in the assembly prologue to explicitly handle the stack.
virtual void adjustForFrameAllocatePrologue (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to add an allocation at a fixed offset from the frame pointer.
virtual bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
virtual bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
virtual bool noFramePointerElim (const MachineFunction &MF) const
Return true if the target needs to disable frame pointer elimination.
virtual bool hasFP (const MachineFunction &MF) const =0
hasFP - Return true if the specified function should have a dedicated frame pointer register.
virtual bool hasReservedCallFrame (const MachineFunction &MF) const
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
virtual bool canSimplifyCallFramePseudos (const MachineFunction &MF) const
canSimplifyCallFramePseudos - When possible, it's best to simplify the call frame pseudo ops before doing frame index elimination.
virtual bool needsFrameIndexResolution (const MachineFunction &MF) const
virtual int getFrameIndexOffset (const MachineFunction &MF, int FI) const
getFrameIndexOffset - Returns the displacement from the frame register to the stack frame of the specified index.
virtual int getFrameIndexReference (const MachineFunction &MF, int FI, unsigned &FrameReg) const
getFrameIndexReference - This method should return the base register and offset used to reference a frame index location.
virtual int getFrameIndexReferenceFromSP (const MachineFunction &MF, int FI, unsigned &FrameReg) const
Same as above, except that the 'base register' will always be RSP, not RBP on x86.
virtual void processFunctionBeforeCalleeSavedScan (MachineFunction &MF, RegScavenger *RS=nullptr) const
processFunctionBeforeCalleeSavedScan - This method is called immediately before PrologEpilogInserter scans the physical registers used to determine what callee saved registers should be spilled.
virtual void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS=nullptr) const
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
virtual void eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MI) const
eliminateCallFramePseudoInstr - This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
virtual bool canUseAsPrologue (const MachineBasicBlock &MBB) const
Check whether or not the given MBB can be used as a prologue for the target.
virtual bool canUseAsEpilogue (const MachineBasicBlock &MBB) const
Check whether or not the given MBB can be used as a epilogue for the target.
Detailed Description
Information about stack frame layout on the target.
It holds the direction of stack growth, the known stack alignment on entry to each function, and the offset to the locals area.
The offset to the local area is the offset from the stack pointer on function entry to the first location where function data (local variables, spill locations) can be stored.
Definition at line 33 of file TargetFrameLowering.h.
Member Enumeration Documentation
enum llvm::TargetFrameLowering::StackDirection
Enumerator:
StackGrowsUp
StackGrowsDown
Definition at line 35 of file TargetFrameLowering.h.
Constructor & Destructor Documentation
llvm::TargetFrameLowering::TargetFrameLowering (StackDirection D, unsigned StackAl, int LAO, unsigned TransAl = 1, bool StackReal = true) [inline]
Definition at line 52 of file TargetFrameLowering.h.
TargetFrameLowering::~TargetFrameLowering () [virtual]
Definition at line 23 of file TargetFrameLoweringImpl.cpp.
Member Function Documentation
virtual void llvm::TargetFrameLowering::adjustForFrameAllocatePrologue (MachineFunction & MF, MachineBasicBlock & PrologueMBB) const [inline, virtual]
Adjust the prologue to add an allocation at a fixed offset from the frame pointer.
Definition at line 151 of file TargetFrameLowering.h.
virtual void llvm::TargetFrameLowering::adjustForHiPEPrologue (MachineFunction & MF, MachineBasicBlock & PrologueMBB) const [inline, virtual]
Adjust the prologue to add Erlang Run-Time System (ERTS) specific code in the assembly prologue to explicitly handle the stack.
Reimplemented in llvm::X86FrameLowering.
Definition at line 145 of file TargetFrameLowering.h.
virtual void llvm::TargetFrameLowering::adjustForSegmentedStacks (MachineFunction & MF, MachineBasicBlock & PrologueMBB) const [inline, virtual]
Adjust the prologue to have the function use segmented stacks.
This works by adding a check even before the "normal" function prologue.
Reimplemented in llvm::X86FrameLowering, and llvm::ARMFrameLowering.
Definition at line 140 of file TargetFrameLowering.h.
virtual bool llvm::TargetFrameLowering::assignCalleeSavedSpillSlots (MachineFunction & MF, const TargetRegisterInfo * TRI, std::vector< CalleeSavedInfo > & CSI) const [inline, virtual]
assignCalleeSavedSpillSlots - Allows target to override spill slot assignment logic.
If implemented, assignCalleeSavedSpillSlots() should assign frame slots to all CSI entries and return true. If this method returns false, spill slots will be assigned using generic implementation. assignCalleeSavedSpillSlots() may add, delete or rearrange elements of CSI.
Reimplemented in llvm::X86FrameLowering, and llvm::HexagonFrameLowering.
Definition at line 103 of file TargetFrameLowering.h.
virtual bool llvm::TargetFrameLowering::canSimplifyCallFramePseudos (const MachineFunction & MF) const [inline, virtual]
canSimplifyCallFramePseudos - When possible, it's best to simplify the call frame pseudo ops before doing frame index elimination.
This is possible only when frame index references between the pseudos won't need adjusting for the call frame adjustments. Normally, that's true if the function has a reserved call frame or a frame pointer. Some targets (Thumb2, for example) may have more complicated criteria, however, and can override this behavior.
Reimplemented in llvm::X86FrameLowering, and llvm::ARMFrameLowering.
Definition at line 200 of file TargetFrameLowering.h.
References hasFP(), and hasReservedCallFrame().
virtual bool llvm::TargetFrameLowering::canUseAsEpilogue (const MachineBasicBlock & MBB) const [inline, virtual]
Check whether or not the given MBB can be used as a epilogue for the target.
The epilogue will be inserted before the first terminator of that block. This method is used by the shrink-wrapping pass to decide if MBB will be correctly handled by the target. As soon as the target enable shrink-wrapping without overriding this method, we assume that each basic block is a valid epilogue.
Reimplemented in llvm::X86FrameLowering.
Definition at line 281 of file TargetFrameLowering.h.
virtual bool llvm::TargetFrameLowering::canUseAsPrologue (const MachineBasicBlock & MBB) const [inline, virtual]
Check whether or not the given MBB can be used as a prologue for the target.
The prologue will be inserted first in this basic block. This method is used by the shrink-wrapping pass to decide if MBB will be correctly handled by the target. As soon as the target enable shrink-wrapping without overriding this method, we assume that each basic block is a valid prologue.
Definition at line 269 of file TargetFrameLowering.h.
virtual void llvm::TargetFrameLowering::eliminateCallFramePseudoInstr (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const [inline, virtual]
eliminateCallFramePseudoInstr - This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
It is responsible for eliminating these instructions, replacing them with concrete instructions. This method need only be implemented if using call frame setup/destroy pseudo instructions.
Reimplemented in llvm::X86FrameLowering, llvm::PPCFrameLowering, llvm::SystemZFrameLowering, llvm::Thumb1FrameLowering, llvm::XCoreFrameLowering, llvm::HexagonFrameLowering, llvm::MipsFrameLowering, llvm::BPFFrameLowering, llvm::MSP430FrameLowering, llvm::SparcFrameLowering, llvm::AArch64FrameLowering, and llvm::NVPTXFrameLowering.
Definition at line 254 of file TargetFrameLowering.h.
References llvm_unreachable.
virtual void llvm::TargetFrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const [pure virtual]
Implemented in llvm::X86FrameLowering, llvm::SystemZFrameLowering, llvm::PPCFrameLowering, llvm::AMDGPUFrameLowering, llvm::AArch64FrameLowering, llvm::XCoreFrameLowering, llvm::ARMFrameLowering, llvm::HexagonFrameLowering, llvm::Thumb1FrameLowering, llvm::MSP430FrameLowering, llvm::SparcFrameLowering, llvm::BPFFrameLowering, llvm::MipsSEFrameLowering, llvm::Mips16FrameLowering, and llvm::NVPTXFrameLowering.
virtual void llvm::TargetFrameLowering::emitPrologue (MachineFunction & MF, MachineBasicBlock & MBB) const [pure virtual]
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
Implemented in llvm::X86FrameLowering, llvm::SystemZFrameLowering, llvm::PPCFrameLowering, llvm::AMDGPUFrameLowering, llvm::AArch64FrameLowering, llvm::ARMFrameLowering, llvm::XCoreFrameLowering, llvm::Thumb1FrameLowering, llvm::HexagonFrameLowering, llvm::MSP430FrameLowering, llvm::SparcFrameLowering, llvm::BPFFrameLowering, llvm::MipsSEFrameLowering, llvm::Mips16FrameLowering, and llvm::NVPTXFrameLowering.
virtual const SpillSlot* llvm::TargetFrameLowering::getCalleeSavedSpillSlots (unsigned & NumEntries) const [inline, virtual]
getCalleeSavedSpillSlots - This method returns a pointer to an array of pairs, that contains an entry for each callee saved register that must be spilled to a particular stack location if it is spilled.
Each entry in this array contains a <register,offset> pair, indicating the fixed offset from the incoming stack pointer that each register should be spilled at. If a register is not listed here, the code generator is allowed to spill it anywhere it chooses.
Reimplemented in llvm::PPCFrameLowering, llvm::HexagonFrameLowering, llvm::AMDGPUFrameLowering, and llvm::SystemZFrameLowering.
Definition at line 119 of file TargetFrameLowering.h.
int TargetFrameLowering::getFrameIndexOffset (const MachineFunction & MF, int FI) const [virtual]
getFrameIndexOffset - Returns the displacement from the frame register to the stack frame of the specified index.
This is the default implementation which is overridden for some targets.
Reimplemented in llvm::X86FrameLowering, llvm::ARMFrameLowering, llvm::HexagonFrameLowering, llvm::SystemZFrameLowering, llvm::AArch64FrameLowering, and llvm::AMDGPUFrameLowering.
Definition at line 35 of file TargetFrameLoweringImpl.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getOffsetAdjustment(), getOffsetOfLocalArea(), and llvm::MachineFrameInfo::getStackSize().
Referenced by llvm::SystemZRegisterInfo::eliminateFrameIndex(), getFrameIndexReference(), and llvm::AMDGPUInstrInfo::getIndirectIndexEnd().
int TargetFrameLowering::getFrameIndexReference (const MachineFunction & MF, int FI, unsigned & FrameReg) const [virtual]
getFrameIndexReference - This method should return the base register and offset used to reference a frame index location.
The offset is returned directly, and the base register is returned via FrameReg.
Reimplemented in llvm::X86FrameLowering, llvm::ARMFrameLowering, and llvm::AArch64FrameLowering.
Definition at line 42 of file TargetFrameLoweringImpl.cpp.
References getFrameIndexOffset(), llvm::TargetRegisterInfo::getFrameRegister(), llvm::TargetSubtargetInfo::getRegisterInfo(), and llvm::MachineFunction::getSubtarget().
Referenced by emitDebugValueComment().
virtual int llvm::TargetFrameLowering::getFrameIndexReferenceFromSP (const MachineFunction & MF, int FI, unsigned & FrameReg) const [inline, virtual]
Same as above, except that the 'base register' will always be RSP, not RBP on x86.
This is used exclusively for lowering STATEPOINT nodes. TODO: This should really be a parameterizable choice.
Reimplemented in llvm::X86FrameLowering.
Definition at line 222 of file TargetFrameLowering.h.
References llvm_unreachable.
int llvm::TargetFrameLowering::getOffsetOfLocalArea () const [inline]
getOffsetOfLocalArea - This method returns the offset of the local area from the stack pointer on entrance to a function.
Definition at line 89 of file TargetFrameLowering.h.
Referenced by llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), llvm::SystemZFrameLowering::getFrameIndexOffset(), llvm::X86FrameLowering::getFrameIndexOffset(), getFrameIndexOffset(), llvm::X86FrameLowering::getFrameIndexOffsetFromSP(), and llvm::MachineFrameInfo::print().
unsigned llvm::TargetFrameLowering::getStackAlignment () const [inline]
getStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned on entry to a function.
Typically, this is the largest alignment for any data object in the target.
Definition at line 70 of file TargetFrameLowering.h.
Referenced by llvm::PPCFrameLowering::addScavengingSpillSlot(), llvm::HexagonFrameLowering::assignCalleeSavedSpillSlots(), checkNumAlignedDPRCS2Regs(), llvm::PPCFrameLowering::determineFrameLayout(), llvm::AArch64FrameLowering::eliminateCallFramePseudoInstr(), llvm::MSP430FrameLowering::eliminateCallFramePseudoInstr(), llvm::XCoreFrameLowering::eliminateCallFramePseudoInstr(), llvm::Thumb1FrameLowering::eliminateCallFramePseudoInstr(), llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), llvm::ARMFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), EnsureStackAlignment(), llvm::MipsFrameLowering::estimateStackSize(), llvm::MachineFrameInfo::estimateStackSize(), llvm::MipsTargetLowering::HandleByVal(), llvm::MipsSEFrameLowering::hasReservedCallFrame(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::MachineFunction::MachineFunction(), llvm::HexagonFrameLowering::needsAligna(), llvm::ARMBaseRegisterInfo::needsFrameBaseReg(), llvm::MipsRegisterInfo::needsStackRealignment(), llvm::ARMBaseRegisterInfo::needsStackRealignment(), llvm::PPCRegisterInfo::needsStackRealignment(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::HexagonFrameLowering::processFunctionBeforeFrameFinalized(), and llvm::FunctionLoweringInfo::set().
StackDirection llvm::TargetFrameLowering::getStackGrowthDirection () const [inline]
getStackGrowthDirection - Return the direction the stack grows
Definition at line 64 of file TargetFrameLowering.h.
Referenced by llvm::TargetInstrInfo::getSPAdjust().
unsigned llvm::TargetFrameLowering::getTransientStackAlignment () const [inline]
getTransientStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned at all times, even between calls.
Definition at line 76 of file TargetFrameLowering.h.
Referenced by llvm::MachineFrameInfo::estimateStackSize().
virtual bool llvm::TargetFrameLowering::hasFP (const MachineFunction & MF) const [pure virtual]
hasFP - Return true if the specified function should have a dedicated frame pointer register.
For most targets this is true only if the function has variable sized allocas or if frame pointer elimination is disabled.
Implemented in llvm::X86FrameLowering, llvm::AArch64FrameLowering, llvm::HexagonFrameLowering, llvm::ARMFrameLowering, llvm::XCoreFrameLowering, llvm::MSP430FrameLowering, llvm::SystemZFrameLowering, llvm::PPCFrameLowering, llvm::AMDGPUFrameLowering, llvm::SparcFrameLowering, llvm::MipsFrameLowering, llvm::BPFFrameLowering, and llvm::NVPTXFrameLowering.
Referenced by canSimplifyCallFramePseudos(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), estimateRSStackSizeLimit(), llvm::MSP430RegisterInfo::getCalleeSavedRegs(), llvm::XCoreRegisterInfo::getCalleeSavedRegs(), llvm::MSP430RegisterInfo::getFrameRegister(), llvm::XCoreRegisterInfo::getFrameRegister(), llvm::SystemZRegisterInfo::getFrameRegister(), llvm::HexagonRegisterInfo::getFrameRegister(), llvm::AArch64RegisterInfo::getFrameRegister(), llvm::MipsRegisterInfo::getRegPressureLimit(), llvm::AArch64RegisterInfo::getRegPressureLimit(), llvm::MSP430RegisterInfo::getReservedRegs(), llvm::XCoreRegisterInfo::getReservedRegs(), llvm::SystemZRegisterInfo::getReservedRegs(), llvm::MipsRegisterInfo::getReservedRegs(), llvm::AArch64RegisterInfo::getReservedRegs(), hasReservedCallFrame(), llvm::AArch64RegisterInfo::isReservedReg(), llvm::AArch64RegisterInfo::needsFrameBaseReg(), llvm::ARMBaseRegisterInfo::needsFrameBaseReg(), and llvm::HexagonRegisterInfo::useFPForScavengingIndex().
virtual bool llvm::TargetFrameLowering::hasReservedCallFrame (const MachineFunction & MF) const [inline, virtual]
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
This eliminates the need for add/sub sp brackets around call sites. Returns true if the call frame is included as part of the stack frame.
Reimplemented in llvm::X86FrameLowering, llvm::AArch64FrameLowering, llvm::ARMFrameLowering, llvm::MSP430FrameLowering, llvm::SystemZFrameLowering, llvm::Thumb1FrameLowering, llvm::Mips16FrameLowering, llvm::SparcFrameLowering, and llvm::MipsSEFrameLowering.
Definition at line 189 of file TargetFrameLowering.h.
References hasFP().
Referenced by llvm::MipsRegisterInfo::canRealignStack(), llvm::ARMBaseRegisterInfo::canRealignStack(), canSimplifyCallFramePseudos(), llvm::AArch64FrameLowering::eliminateCallFramePseudoInstr(), llvm::MipsFrameLowering::eliminateCallFramePseudoInstr(), llvm::XCoreFrameLowering::eliminateCallFramePseudoInstr(), llvm::MipsFrameLowering::estimateStackSize(), and llvm::MachineFrameInfo::estimateStackSize().
virtual bool llvm::TargetFrameLowering::isFPCloseToIncomingSP () const [inline, virtual]
isFPCloseToIncomingSP - Return true if the frame pointer is close to the incoming stack pointer, false if it is close to the post-prologue stack pointer.
Reimplemented in llvm::MipsFrameLowering, and llvm::SystemZFrameLowering.
Definition at line 94 of file TargetFrameLowering.h.
bool llvm::TargetFrameLowering::isStackRealignable () const [inline]
isStackRealignable - This method returns whether the stack can be realigned.
Definition at line 82 of file TargetFrameLowering.h.
Referenced by llvm::MachineFunction::MachineFunction().
bool TargetFrameLowering::needsFrameIndexResolution (const MachineFunction & MF) const [virtual]
Reimplemented in llvm::X86FrameLowering.
Definition at line 53 of file TargetFrameLoweringImpl.cpp.
References llvm::MachineFunction::getFrameInfo(), and llvm::MachineFrameInfo::hasStackObjects().
bool TargetFrameLowering::noFramePointerElim (const MachineFunction & MF) const [virtual]
Return true if the target needs to disable frame pointer elimination.
The default implementation just looks at attribute "no-frame-pointer-elim".
Reimplemented in llvm::ARMFrameLowering.
Definition at line 27 of file TargetFrameLoweringImpl.cpp.
References llvm::Function::getFnAttribute(), llvm::MachineFunction::getFunction(), and llvm::Attribute::getValueAsString().
Referenced by llvm::TargetOptions::DisableFramePointerElim().
virtual void llvm::TargetFrameLowering::processFunctionBeforeCalleeSavedScan (MachineFunction & MF, RegScavenger * RS = nullptr) const [inline, virtual]
processFunctionBeforeCalleeSavedScan - This method is called immediately before PrologEpilogInserter scans the physical registers used to determine what callee saved registers should be spilled.
This method is optional.
Reimplemented in llvm::X86FrameLowering, llvm::AArch64FrameLowering, llvm::ARMFrameLowering, llvm::XCoreFrameLowering, llvm::HexagonFrameLowering, llvm::PPCFrameLowering, llvm::Mips16FrameLowering, llvm::SparcFrameLowering, llvm::MipsSEFrameLowering, llvm::BPFFrameLowering, and llvm::SystemZFrameLowering.
Definition at line 232 of file TargetFrameLowering.h.
virtual void llvm::TargetFrameLowering::processFunctionBeforeFrameFinalized (MachineFunction & MF, RegScavenger * RS = nullptr) const [inline, virtual]
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
Once the frame is finalized, MO_FrameIndex operands are replaced with direct constants. This method is optional.
Reimplemented in llvm::XCoreFrameLowering, llvm::PPCFrameLowering, llvm::MSP430FrameLowering, llvm::HexagonFrameLowering, and llvm::SystemZFrameLowering.
Definition at line 242 of file TargetFrameLowering.h.
virtual bool llvm::TargetFrameLowering::restoreCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const [inline, virtual]
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
Returns false otherwise.
Reimplemented in llvm::X86FrameLowering, llvm::PPCFrameLowering, llvm::AArch64FrameLowering, llvm::ARMFrameLowering, llvm::MSP430FrameLowering, llvm::XCoreFrameLowering, llvm::Thumb1FrameLowering, llvm::HexagonFrameLowering, llvm::SystemZFrameLowering, and llvm::Mips16FrameLowering.
Definition at line 169 of file TargetFrameLowering.h.
virtual bool llvm::TargetFrameLowering::spillCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const [inline, virtual]
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
Returns false otherwise.
Reimplemented in llvm::X86FrameLowering, llvm::PPCFrameLowering, llvm::AArch64FrameLowering, llvm::MSP430FrameLowering, llvm::ARMFrameLowering, llvm::XCoreFrameLowering, llvm::Thumb1FrameLowering, llvm::HexagonFrameLowering, llvm::SystemZFrameLowering, llvm::MipsSEFrameLowering, and llvm::Mips16FrameLowering.
Definition at line 158 of file TargetFrameLowering.h.
virtual bool llvm::TargetFrameLowering::targetHandlesStackFrameRounding () const [inline, virtual]
targetHandlesStackFrameRounding - Returns true if the target is responsible for rounding up the stack frame (probably at emitPrologue time).
Reimplemented in llvm::PPCFrameLowering, and llvm::HexagonFrameLowering.
Definition at line 127 of file TargetFrameLowering.h.
The documentation for this class was generated from the following files:
TargetFrameLowering.h
TargetFrameLoweringImpl.cpp