LLVM: llvm::Mips16FrameLowering Class Reference
llvm::Mips16FrameLowering Class Reference
#include <Mips16FrameLowering.h>
Public Member Functions
Mips16FrameLowering (const MipsSubtarget &STI)
void emitPrologue (MachineFunction &MF, MachineBasicBlock &MBB) const override
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const override
bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const override
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const override
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
bool hasReservedCallFrame (const MachineFunction &MF) const override
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
void processFunctionBeforeCalleeSavedScan (MachineFunction &MF, RegScavenger *RS) const override
processFunctionBeforeCalleeSavedScan - This method is called immediately before PrologEpilogInserter scans the physical registers used to determine what callee saved registers should be spilled.
Detailed Description
Definition at line 20 of file Mips16FrameLowering.h.
Constructor & Destructor Documentation
Mips16FrameLowering::Mips16FrameLowering (const MipsSubtarget & STI) [explicit]
Definition at line 32 of file Mips16FrameLowering.cpp.
Member Function Documentation
void Mips16FrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const [override, virtual]
Implements llvm::TargetFrameLowering.
Definition at line 83 of file Mips16FrameLowering.cpp.
References llvm::BuildMI(), llvm::MachineFunction::getFrameInfo(), llvm::MipsSubtarget::getInstrInfo(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::MachineFrameInfo::getStackSize(), llvm::MipsFrameLowering::hasFP(), llvm::Mips16InstrInfo::restoreFrame(), llvm::SP, llvm::MipsFrameLowering::STI, and TII.
void Mips16FrameLowering::emitPrologue (MachineFunction & MF, MachineBasicBlock & MBB) const [override, virtual]
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
Implements llvm::TargetFrameLowering.
Definition at line 35 of file Mips16FrameLowering.cpp.
References llvm::MachineModuleInfo::addFrameInst(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::TargetOpcode::CFI_INSTRUCTION, llvm::MCCFIInstruction::createDefCfaOffset(), llvm::MCCFIInstruction::createOffset(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::FrameSetup, llvm::MachineFunction::front(), llvm::MachineModuleInfo::getContext(), llvm::MCRegisterInfo::getDwarfRegNum(), llvm::MachineFunction::getFrameInfo(), llvm::MipsSubtarget::getInstrInfo(), llvm::MachineFunction::getMMI(), llvm::MCContext::getRegisterInfo(), llvm::MipsFrameLowering::hasFP(), I, llvm::Mips16InstrInfo::makeFrame(), llvm::MachineInstrBuilder::setMIFlag(), llvm::SP, llvm::MipsFrameLowering::STI, and TII.
bool Mips16FrameLowering::hasReservedCallFrame (const MachineFunction & MF) const [override, virtual]
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
This eliminates the need for add/sub sp brackets around call sites. Returns true if the call frame is included as part of the stack frame.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 148 of file Mips16FrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getMaxCallFrameSize(), and llvm::MachineFrameInfo::hasVarSizedObjects().
void Mips16FrameLowering::processFunctionBeforeCalleeSavedScan (MachineFunction & MF, RegScavenger * RS) const [override, virtual]
processFunctionBeforeCalleeSavedScan - This method is called immediately before PrologEpilogInserter scans the physical registers used to determine what callee saved registers should be spilled.
This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 156 of file Mips16FrameLowering.cpp.
References llvm::MipsSubtarget::getInstrInfo(), llvm::MachineFunction::getRegInfo(), llvm::Mips16InstrInfo::getRegisterInfo(), llvm::MipsRegisterInfo::getReservedRegs(), llvm::MipsFrameLowering::hasFP(), llvm::Reserved, llvm::MachineRegisterInfo::setPhysRegUsed(), llvm::MipsFrameLowering::STI, and TII.
bool Mips16FrameLowering::restoreCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const [override, virtual]
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 133 of file Mips16FrameLowering.cpp.
bool Mips16FrameLowering::spillCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const [override, virtual]
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 105 of file Mips16FrameLowering.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::MachineFunction::begin(), llvm::MachineFunction::getFrameInfo(), llvm::MachineBasicBlock::getParent(), and llvm::MachineFrameInfo::isReturnAddressTaken().
The documentation for this class was generated from the following files:
Mips16FrameLowering.h
Mips16FrameLowering.cpp