LLVM: llvm::SDLoc Class Reference
llvm::SDLoc Class Reference
Wrapper class for IR location info (IR ordering and DebugLoc) to be passed into SDNode creation functions.
#include <SelectionDAGNodes.h>
Public Member Functions
SDLoc ()
SDLoc (const SDNode *N)
SDLoc (const SDValue V)
SDLoc (const Instruction *I, int Order)
unsigned getIROrder ()
DebugLoc getDebugLoc ()
Detailed Description
Wrapper class for IR location info (IR ordering and DebugLoc) to be passed into SDNode creation functions.
When an SDNode is created from the DAGBuilder, the DebugLoc is extracted from the original Instruction, and IROrder is the ordinal position of the instruction. When an SDNode is created after the DAG is being built, both DebugLoc and the IROrder are propagated from the original SDNode. So SDLoc class provides two constructors besides the default one, one to be used by the DAGBuilder, the other to be used by others.
Definition at line 820 of file SelectionDAGNodes.h.
Constructor & Destructor Documentation
llvm::SDLoc::SDLoc () [inline]
Definition at line 828 of file SelectionDAGNodes.h.
llvm::SDLoc::SDLoc (const SDNode * N) [inline]
Definition at line 829 of file SelectionDAGNodes.h.
llvm::SDLoc::SDLoc (const SDValue V) [inline]
Definition at line 832 of file SelectionDAGNodes.h.
llvm::SDLoc::SDLoc (const Instruction * I, int Order) [inline]
Definition at line 835 of file SelectionDAGNodes.h.
Member Function Documentation
DebugLoc llvm::SDLoc::getDebugLoc () [inline]
Definition at line 845 of file SelectionDAGNodes.h.
References llvm::Instruction::getDebugLoc(), llvm::SDNode::getDebugLoc(), I, and N.
Referenced by llvm::SelectionDAG::getAddrSpaceCast(), llvm::SelectionDAG::getAtomic(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getConvertRndSat(), llvm::SelectionDAG::getEHLabel(), llvm::SelectionDAG::getGlobalAddress(), llvm::SelectionDAG::getIndexedStore(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getMaskedGather(), llvm::SelectionDAG::getMaskedLoad(), llvm::SelectionDAG::getMaskedScatter(), llvm::SelectionDAG::getMaskedStore(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTruncStore(), and llvm::SelectionDAG::getVectorShuffle().
unsigned llvm::SDLoc::getIROrder () [inline]
Definition at line 838 of file SelectionDAGNodes.h.
References llvm::SDNode::getIROrder(), and N.
Referenced by llvm::SelectionDAG::getAddrSpaceCast(), llvm::SelectionDAG::getAtomic(), llvm::SelectionDAG::getConvertRndSat(), llvm::SelectionDAG::getEHLabel(), llvm::SelectionDAG::getGlobalAddress(), llvm::SelectionDAG::getIndexedStore(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getMaskedGather(), llvm::SelectionDAG::getMaskedLoad(), llvm::SelectionDAG::getMaskedScatter(), llvm::SelectionDAG::getMaskedStore(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTruncStore(), and llvm::SelectionDAG::getVectorShuffle().
The documentation for this class was generated from the following file:
SelectionDAGNodes.h