LLVM: llvm::DICompositeTypeBase Class Reference
llvm::DICompositeTypeBase Class Reference
Base class for DICompositeType and DISubroutineType.
#include <DebugInfoMetadata.h>
Public Member Functions
DINodeArray getElements () const
Get the elements of the composite type.
DITypeRef getVTableHolder () const
DITemplateParameterArray getTemplateParams () const
StringRef getIdentifier () const
unsigned getRuntimeLang () const
Metadata * getRawElements () const
Metadata * getRawVTableHolder () const
Metadata * getRawTemplateParams () const
MDString * getRawIdentifier () const
void replaceElements (DINodeArray Elements)
Replace operands.
void replaceVTableHolder (DITypeRef VTableHolder)
void replaceTemplateParams (DITemplateParameterArray TemplateParams)
Static Public Member Functions
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
DICompositeTypeBase (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, unsigned Line, unsigned RuntimeLang, uint64_t SizeInBits, uint64_t AlignInBits, uint64_t OffsetInBits, unsigned Flags, ArrayRef< Metadata * > Ops)
~DICompositeTypeBase ()
Detailed Description
Base class for DICompositeType and DISubroutineType.
TODO: Delete; they're not really related.
Definition at line 768 of file DebugInfoMetadata.h.
Constructor & Destructor Documentation
llvm::DICompositeTypeBase::DICompositeTypeBase (LLVMContext & C, unsigned ID, StorageType Storage, unsigned Tag, unsigned Line, unsigned RuntimeLang, uint64_t SizeInBits, uint64_t AlignInBits, uint64_t OffsetInBits, unsigned Flags, ArrayRef< Metadata * > Ops) [inline, protected]
Definition at line 772 of file DebugInfoMetadata.h.
llvm::DICompositeTypeBase::~DICompositeTypeBase () [protected]
Member Function Documentation
static bool llvm::DICompositeTypeBase::classof (const Metadata * MD) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::DIDerivedTypeBase.
Reimplemented in llvm::DISubroutineType.
Definition at line 826 of file DebugInfoMetadata.h.
References llvm::Metadata::DICompositeTypeKind, llvm::Metadata::DISubroutineTypeKind, and llvm::Metadata::getMetadataID().
DINodeArray llvm::DICompositeTypeBase::getElements () const [inline]
Get the elements of the composite type.
Note:
Calling this is only valid for DICompositeType. This assertion can be removed once DISubroutineType has been separated from "composite types".
Definition at line 788 of file DebugInfoMetadata.h.
References getRawElements().
Referenced by llvm::DwarfUnit::constructTypeDIE(), replaceElements(), and WriteDICompositeType().
StringRef llvm::DICompositeTypeBase::getIdentifier () const [inline]
Definition at line 796 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
Referenced by llvm::MDNodeKeyImpl< DICompositeType >::isKeyOf().
Metadata* llvm::DICompositeTypeBase::getRawElements () const [inline]
Definition at line 799 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getElements(), llvm::DISubroutineType::getRawTypeArray(), and llvm::MDNodeKeyImpl< DICompositeType >::isKeyOf().
MDString* llvm::DICompositeTypeBase::getRawIdentifier () const [inline]
Definition at line 802 of file DebugInfoMetadata.h.
Referenced by WriteDICompositeType().
Metadata* llvm::DICompositeTypeBase::getRawTemplateParams () const [inline]
Definition at line 801 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getTemplateParams(), and llvm::MDNodeKeyImpl< DICompositeType >::isKeyOf().
Metadata* llvm::DICompositeTypeBase::getRawVTableHolder () const [inline]
Definition at line 800 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getVTableHolder(), and llvm::MDNodeKeyImpl< DICompositeType >::isKeyOf().
unsigned llvm::DICompositeTypeBase::getRuntimeLang () const [inline]
Definition at line 797 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfUnit::constructTypeDIE(), llvm::MDNodeKeyImpl< DICompositeType >::isKeyOf(), and WriteDICompositeType().
DITemplateParameterArray llvm::DICompositeTypeBase::getTemplateParams () const [inline]
Definition at line 793 of file DebugInfoMetadata.h.
References getRawTemplateParams().
Referenced by llvm::DwarfUnit::constructTypeDIE(), and WriteDICompositeType().
DITypeRef llvm::DICompositeTypeBase::getVTableHolder () const [inline]
Definition at line 792 of file DebugInfoMetadata.h.
References getRawVTableHolder().
Referenced by llvm::DwarfUnit::constructTypeDIE(), and WriteDICompositeType().
void llvm::DICompositeTypeBase::replaceElements (DINodeArray Elements) [inline]
Replace operands.
If this isUniqued() and not isResolved(), on a uniquing collision this will be RAUW'ed and deleted. Use a TrackingMDRef to keep track of its movement if necessary.
Definition at line 810 of file DebugInfoMetadata.h.
References getElements(), and llvm::MDNode::replaceOperandWith().
Referenced by llvm::DIBuilder::replaceArrays().
void llvm::DICompositeTypeBase::replaceTemplateParams (DITemplateParameterArray TemplateParams) [inline]
Definition at line 821 of file DebugInfoMetadata.h.
References llvm::MDNode::replaceOperandWith().
Referenced by llvm::DIBuilder::replaceArrays().
void llvm::DICompositeTypeBase::replaceVTableHolder (DITypeRef VTableHolder) [inline]
Definition at line 818 of file DebugInfoMetadata.h.
References llvm::MDNode::replaceOperandWith().
Referenced by llvm::DIBuilder::replaceVTableHolder().
The documentation for this class was generated from the following file:
DebugInfoMetadata.h