LLVM: llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy > Class Template Reference
llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy > Class Template Reference
Analogous to CallSiteBase, this provides most of the actual functionality for Statepoint and ImmutableStatepoint.
#include <Statepoint.h>
Public Types
enum {
IDPos = 0, NumPatchBytesPos = 1, ActualCalleePos = 2, NumCallArgsPos = 3,
FlagsPos = 4, CallArgsBeginPos = 5
}
typedef CallSiteTy::arg_iterator arg_iterator
Public Member Functions
CallSiteTy getCallSite ()
Return the underlying CallSite.
uint64_t getFlags () const
uint64_t getID ()
Return the ID associated with this statepoint.
uint32_t getNumPatchBytes ()
Return the number of patchable bytes associated with this statepoint.
ValueTy * getActualCallee ()
Return the value actually being called or invoked.
Type * getActualReturnType ()
Return the type of the value returned by the call underlying the statepoint.
int getNumCallArgs ()
Number of arguments to be passed to the actual callee.
CallSiteTy::arg_iterator call_args_begin ()
CallSiteTy::arg_iterator call_args_end ()
iterator_range< arg_iterator > call_args ()
range adapter for call arguments
int getNumTotalGCTransitionArgs ()
Number of GC transition args.
CallSiteTy::arg_iterator gc_transition_args_begin ()
CallSiteTy::arg_iterator gc_transition_args_end ()
iterator_range< arg_iterator > gc_transition_args ()
range adapter for GC transition arguments
int getNumTotalVMSArgs ()
Number of additional arguments excluding those intended for garbage collection.
CallSiteTy::arg_iterator vm_state_begin ()
CallSiteTy::arg_iterator vm_state_end ()
iterator_range< arg_iterator > vm_state_args ()
range adapter for vm state arguments
CallSiteTy::arg_iterator gc_args_begin ()
CallSiteTy::arg_iterator gc_args_end ()
iterator_range< arg_iterator > gc_args ()
range adapter for gc arguments
std::vector< GCRelocateOperands > getRelocates ()
Get list of all gc reloactes linked to this statepoint May contain several relocations for the same base/derived pair.
void verify ()
Asserts if this statepoint is malformed.
Protected Member Functions
StatepointBase (InstructionTy *I)
StatepointBase (CallSiteTy CS)
Detailed Description
template<typename InstructionTy, typename ValueTy, typename CallSiteTy>
class llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >
Analogous to CallSiteBase, this provides most of the actual functionality for Statepoint and ImmutableStatepoint.
It is templatized to allow easily specializing of const and non-const concrete subtypes. This is structured analogous to CallSite rather than the IntrinsicInst.h helpers since we want to support invokable statepoints in the near future. TODO: This does not currently allow the if(Statepoint S = ...) idiom used with CallSites. Consider refactoring to support.
Definition at line 60 of file Statepoint.h.
Member Typedef Documentation
template<typename InstructionTy, typename ValueTy, typename CallSiteTy> typedef CallSiteTy::arg_iterator llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::arg_iterator
Definition at line 74 of file Statepoint.h.
Member Enumeration Documentation
template<typename InstructionTy, typename ValueTy, typename CallSiteTy> anonymous enum
Enumerator:
IDPos
NumPatchBytesPos
ActualCalleePos
NumCallArgsPos
FlagsPos
CallArgsBeginPos
Definition at line 76 of file Statepoint.h.
Constructor & Destructor Documentation
template<typename InstructionTy, typename ValueTy, typename CallSiteTy> llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::StatepointBase (InstructionTy * I) [inline, explicit, protected]
Definition at line 66 of file Statepoint.h.
template<typename InstructionTy, typename ValueTy, typename CallSiteTy> llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::StatepointBase (CallSiteTy CS) [inline, explicit, protected]
Definition at line 69 of file Statepoint.h.
Member Function Documentation
template<typename InstructionTy, typename ValueTy, typename CallSiteTy> iterator_range<arg_iterator> llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::call_args () [inline]
range adapter for call arguments
Definition at line 138 of file Statepoint.h.
template<typename InstructionTy, typename ValueTy, typename CallSiteTy> CallSiteTy::arg_iterator llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::call_args_begin () [inline]
Definition at line 127 of file Statepoint.h.
Referenced by llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::call_args(), llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::call_args_end(), and llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::verify().
template<typename InstructionTy, typename ValueTy, typename CallSiteTy> CallSiteTy::arg_iterator llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::call_args_end () [inline]
Definition at line 131 of file Statepoint.h.
Referenced by llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::call_args(), llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::gc_transition_args_begin(), llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::getNumTotalGCTransitionArgs(), and llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::verify().
template<typename InstructionTy, typename ValueTy, typename CallSiteTy> iterator_range<arg_iterator> llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::gc_args () [inline]
range adapter for gc arguments
Definition at line 193 of file Statepoint.h.
Referenced by insertParsePoints(), and lowerStatepointMetaArgs().
template<typename InstructionTy, typename ValueTy, typename CallSiteTy> CallSiteTy::arg_iterator llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::gc_args_begin () [inline]
Definition at line 187 of file Statepoint.h.
Referenced by llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::gc_args(), insertParsePoints(), and llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::verify().
template<typename InstructionTy, typename ValueTy, typename CallSiteTy> CallSiteTy::arg_iterator llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::gc_args_end () [inline]
Definition at line 188 of file Statepoint.h.
Referenced by llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::gc_args(), insertParsePoints(), and llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::verify().
template<typename InstructionTy, typename ValueTy, typename CallSiteTy> iterator_range<arg_iterator> llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::gc_transition_args () [inline]
range adapter for GC transition arguments
Definition at line 159 of file Statepoint.h.
Referenced by llvm::SelectionDAGBuilder::LowerStatepoint().
template<typename InstructionTy, typename ValueTy, typename CallSiteTy> CallSiteTy::arg_iterator llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::gc_transition_args_begin () [inline]
Definition at line 147 of file Statepoint.h.
Referenced by llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::gc_transition_args(), llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::gc_transition_args_end(), and llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::verify().
template<typename InstructionTy, typename ValueTy, typename CallSiteTy> CallSiteTy::arg_iterator llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::gc_transition_args_end () [inline]
Definition at line 152 of file Statepoint.h.
Referenced by llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::gc_transition_args(), llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::getNumTotalVMSArgs(), llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::verify(), and llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::vm_state_begin().
template<typename InstructionTy, typename ValueTy, typename CallSiteTy> ValueTy* llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::getActualCallee () [inline]
Return the value actually being called or invoked.
Definition at line 109 of file Statepoint.h.
Referenced by llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::getActualReturnType(), and lowerCallFromStatepoint().
template<typename InstructionTy, typename ValueTy, typename CallSiteTy> Type* llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::getActualReturnType () [inline]
Return the type of the value returned by the call underlying the statepoint.
Definition at line 115 of file Statepoint.h.
Referenced by lowerCallFromStatepoint().
template<typename InstructionTy, typename ValueTy, typename CallSiteTy> CallSiteTy llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::getCallSite () [inline]
Return the underlying CallSite.
Definition at line 86 of file Statepoint.h.
Referenced by lowerCallFromStatepoint(), llvm::SelectionDAGBuilder::LowerStatepoint(), and lowerStatepointMetaArgs().
template<typename InstructionTy, typename ValueTy, typename CallSiteTy> uint64_t llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::getFlags () const [inline]
Definition at line 88 of file Statepoint.h.
Referenced by llvm::SelectionDAGBuilder::LowerStatepoint().
template<typename InstructionTy, typename ValueTy, typename CallSiteTy> uint64_t llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::getID () [inline]
Return the ID associated with this statepoint.
Definition at line 94 of file Statepoint.h.
Referenced by llvm::SelectionDAGBuilder::LowerStatepoint().
template<typename InstructionTy, typename ValueTy, typename CallSiteTy> int llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::getNumCallArgs () [inline]
Number of arguments to be passed to the actual callee.
Definition at line 122 of file Statepoint.h.
Referenced by llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::call_args_end(), lowerCallFromStatepoint(), and llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::verify().
template<typename InstructionTy, typename ValueTy, typename CallSiteTy> uint32_t llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::getNumPatchBytes () [inline]
Return the number of patchable bytes associated with this statepoint.
Definition at line 100 of file Statepoint.h.
Referenced by llvm::SelectionDAGBuilder::LowerStatepoint().
template<typename InstructionTy, typename ValueTy, typename CallSiteTy> int llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::getNumTotalGCTransitionArgs () [inline]
Number of GC transition args.
Definition at line 143 of file Statepoint.h.
Referenced by llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::gc_transition_args_end().
template<typename InstructionTy, typename ValueTy, typename CallSiteTy> int llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::getNumTotalVMSArgs () [inline]
Number of additional arguments excluding those intended for garbage collection.
Definition at line 166 of file Statepoint.h.
Referenced by lowerStatepointMetaArgs(), and llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::vm_state_end().
template<typename InstructionTy , typename ValueTy , typename CallSiteTy > std::vector< GCRelocateOperands > llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::getRelocates ()
Get list of all gc reloactes linked to this statepoint May contain several relocations for the same base/derived pair.
For example this could happen due to relocations on unwinding path of invoke.
Definition at line 318 of file Statepoint.h.
References llvm::isGCRelocate(), llvm::LandingPad, and llvm::Value::users().
Referenced by getIncomingStatepointGCValues(), and lowerStatepointMetaArgs().
template<typename InstructionTy, typename ValueTy, typename CallSiteTy> void llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::verify () [inline]
Asserts if this statepoint is malformed.
Common cases for failure include incorrect length prefixes for variable length sections or illegal values for parameters.
Definition at line 207 of file Statepoint.h.
Referenced by llvm::SelectionDAGBuilder::LowerStatepoint().
template<typename InstructionTy, typename ValueTy, typename CallSiteTy> iterator_range<arg_iterator> llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::vm_state_args () [inline]
range adapter for vm state arguments
Definition at line 183 of file Statepoint.h.
Referenced by insertParsePoints(), and lowerStatepointMetaArgs().
template<typename InstructionTy, typename ValueTy, typename CallSiteTy> CallSiteTy::arg_iterator llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::vm_state_begin () [inline]
Definition at line 171 of file Statepoint.h.
Referenced by lowerStatepointMetaArgs(), llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::verify(), llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::vm_state_args(), and llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::vm_state_end().
template<typename InstructionTy, typename ValueTy, typename CallSiteTy> CallSiteTy::arg_iterator llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::vm_state_end () [inline]
Definition at line 176 of file Statepoint.h.
Referenced by llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::gc_args_begin(), lowerStatepointMetaArgs(), llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::verify(), and llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::vm_state_args().
The documentation for this class was generated from the following file:
Statepoint.h