LLVM: llvm::TargetTransformInfoImplCRTPBase< T > Class Template Reference
llvm::TargetTransformInfoImplCRTPBase< T > Class Template Reference
CRTP base class for use as a mix-in that aids implementing a TargetTransformInfo-compatible class.
#include <TargetTransformInfoImpl.h>
Public Member Functions
TargetTransformInfoImplCRTPBase (const TargetTransformInfoImplCRTPBase &Arg)
TargetTransformInfoImplCRTPBase (TargetTransformInfoImplCRTPBase &&Arg)
TargetTransformInfoImplCRTPBase & operator= (const TargetTransformInfoImplCRTPBase &RHS)
TargetTransformInfoImplCRTPBase & operator= (TargetTransformInfoImplCRTPBase &&RHS)
unsigned getCallCost (const Function *F, int NumArgs)
unsigned getCallCost (const Function *F, ArrayRef< const Value * > Arguments)
unsigned getIntrinsicCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< const Value * > Arguments)
unsigned getUserCost (const User *U)
Protected Member Functions
TargetTransformInfoImplCRTPBase (const DataLayout *DL)
Detailed Description
template<typename T>
class llvm::TargetTransformInfoImplCRTPBase< T >
CRTP base class for use as a mix-in that aids implementing a TargetTransformInfo-compatible class.
Definition at line 343 of file TargetTransformInfoImpl.h.
Constructor & Destructor Documentation
template<typename T> llvm::TargetTransformInfoImplCRTPBase< T >::TargetTransformInfoImplCRTPBase (const DataLayout * DL) [inline, explicit, protected]
Definition at line 348 of file TargetTransformInfoImpl.h.
template<typename T> llvm::TargetTransformInfoImplCRTPBase< T >::TargetTransformInfoImplCRTPBase (const TargetTransformInfoImplCRTPBase< T > & Arg) [inline]
Definition at line 353 of file TargetTransformInfoImpl.h.
template<typename T> llvm::TargetTransformInfoImplCRTPBase< T >::TargetTransformInfoImplCRTPBase (TargetTransformInfoImplCRTPBase< T > && Arg) [inline]
Definition at line 355 of file TargetTransformInfoImpl.h.
Member Function Documentation
template<typename T> unsigned llvm::TargetTransformInfoImplCRTPBase< T >::getCallCost (const Function * F, int NumArgs) [inline]
Definition at line 370 of file TargetTransformInfoImpl.h.
Referenced by llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getCallCost(), and llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getUserCost().
template<typename T> unsigned llvm::TargetTransformInfoImplCRTPBase< T >::getCallCost (const Function * F, ArrayRef< const Value * > Arguments) [inline]
Definition at line 392 of file TargetTransformInfoImpl.h.
template<typename T> unsigned llvm::TargetTransformInfoImplCRTPBase< T >::getIntrinsicCost (Intrinsic::ID IID, Type * RetTy, ArrayRef< const Value * > Arguments) [inline]
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, and llvm::BasicTTIImplBase< AMDGPUTTIImpl >.
Definition at line 401 of file TargetTransformInfoImpl.h.
Referenced by llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getCallCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicCost(), and llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getIntrinsicCost().
template<typename T> unsigned llvm::TargetTransformInfoImplCRTPBase< T >::getUserCost (const User * U) [inline]
Definition at line 413 of file TargetTransformInfoImpl.h.
template<typename T> TargetTransformInfoImplCRTPBase& llvm::TargetTransformInfoImplCRTPBase< T >::operator= (const TargetTransformInfoImplCRTPBase< T > & RHS) [inline]
Definition at line 358 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::operator=().
template<typename T> TargetTransformInfoImplCRTPBase& llvm::TargetTransformInfoImplCRTPBase< T >::operator= (TargetTransformInfoImplCRTPBase< T > && RHS) [inline]
Definition at line 363 of file TargetTransformInfoImpl.h.
The documentation for this class was generated from the following file:
TargetTransformInfoImpl.h