LLVM: llvm::Registry< T, U > Class Template Reference
llvm::Registry< T, U > Class Template Reference
A global registry used in conjunction with static constructors to make pluggable components (like targets or garbage collectors) "just work" when linked with an executable.
#include <Registry.h>
Classes
class Add
A static registration template.
class iterator
Iterators for registry entries.
class listener
Abstract base class for registry listeners, which are informed when new entries are added to the registry.
class node
Node in linked list of entries.
Public Types
typedef U traits
typedef U::entry entry
Static Public Member Functions
static iterator begin ()
static iterator end ()
static iterator_range< iterator > entries ()
Friends
class node
class listener
Detailed Description
template<typename T, typename U = RegistryTraits<T>>
class llvm::Registry< T, U >
A global registry used in conjunction with static constructors to make pluggable components (like targets or garbage collectors) "just work" when linked with an executable.
Definition at line 61 of file Registry.h.
Member Typedef Documentation
template<typename T , typename U = RegistryTraits<T>> typedef U::entry llvm::Registry< T, U >::entry
Definition at line 64 of file Registry.h.
template<typename T , typename U = RegistryTraits<T>> typedef U llvm::Registry< T, U >::traits
Definition at line 63 of file Registry.h.
Member Function Documentation
template<typename T , typename U = RegistryTraits<T>> static iterator llvm::Registry< T, U >::begin () [inline, static]
Definition at line 121 of file Registry.h.
Referenced by llvm::Registry< T, U >::entries(), llvm::GCModuleInfo::getGCStrategy(), and llvm::Registry< T, U >::listener::init().
template<typename T , typename U = RegistryTraits<T>> static iterator llvm::Registry< T, U >::end () [inline, static]
Definition at line 122 of file Registry.h.
Referenced by llvm::Registry< T, U >::entries(), llvm::GCModuleInfo::getGCStrategy(), and llvm::Registry< T, U >::listener::init().
template<typename T , typename U = RegistryTraits<T>> static iterator_range<iterator> llvm::Registry< T, U >::entries () [inline, static]
Definition at line 124 of file Registry.h.
References llvm::Registry< T, U >::begin(), and llvm::Registry< T, U >::end().
Referenced by llvm::GCModuleInfo::getGCStrategy().
Friends And Related Function Documentation
template<typename T , typename U = RegistryTraits<T>> friend class listener [friend]
Definition at line 81 of file Registry.h.
template<typename T , typename U = RegistryTraits<T>> friend class node [friend]
Definition at line 78 of file Registry.h.
The documentation for this class was generated from the following file:
Registry.h