LLVM: llvm::BitInit Class Reference
llvm::BitInit Class Reference
BitInit - true/false - Represent a concrete initializer for a bit.
#include <Record.h>
Public Member Functions
bool getValue () const
Init * convertInitializerTo (RecTy *Ty) const override
convertInitializerTo - This virtual function converts to the appropriate Init based on the passed in type.
Init * getBit (unsigned Bit) const override
getBit - This method is used to return the initializer for the specified bit.
std::string getAsString () const override
getAsString - Convert this value to a string form.
Static Public Member Functions
static bool classof (const Init *I)
static BitInit * get (bool V)
Detailed Description
BitInit - true/false - Represent a concrete initializer for a bit.
Definition at line 427 of file Record.h.
Member Function Documentation
static bool llvm::BitInit::classof (const Init * I) [inline, static]
Definition at line 435 of file Record.h.
References llvm::Init::getKind(), and llvm::Init::IK_BitInit.
Init * BitInit::convertInitializerTo (RecTy * Ty) const [override, virtual]
convertInitializerTo - This virtual function converts to the appropriate Init based on the passed in type.
Implements llvm::Init.
Definition at line 242 of file Record.cpp.
References llvm::BitsInit::get(), llvm::IntInit::get(), and getValue().
BitInit * BitInit::get (bool V) [static]
Definition at line 235 of file Record.cpp.
Referenced by llvm::IntInit::convertInitializerTo().
std::string llvm::BitInit::getAsString () const [inline, override, virtual]
getAsString - Convert this value to a string form.
Implements llvm::Init.
Definition at line 449 of file Record.h.
Init* llvm::BitInit::getBit (unsigned Bit) const [inline, override, virtual]
getBit - This method is used to return the initializer for the specified bit.
Implements llvm::Init.
Definition at line 444 of file Record.h.
bool llvm::BitInit::getValue () const [inline]
Definition at line 440 of file Record.h.
Referenced by convertInitializerTo().
The documentation for this class was generated from the following files:
Record.h
Record.cpp