LLVM: llvm::SITargetLowering Class Reference
llvm::SITargetLowering Class Reference
#include <SIISelLowering.h>
Public Member Functions
SITargetLowering (TargetMachine &tm, const AMDGPUSubtarget &STI)
bool isShuffleMaskLegal (const SmallVectorImpl< int > &, EVT) const override
Targets can use this to indicate that they only support *some* VECTOR_SHUFFLE operations, those with specific masks.
bool isLegalAddressingMode (const AddrMode &AM, Type *Ty, unsigned AS) const override
Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
bool allowsMisalignedMemoryAccesses (EVT VT, unsigned AS, unsigned Align, bool *IsFast) const override
Determine if the target supports unaligned memory accesses.
EVT getOptimalMemOpType (uint64_t Size, unsigned DstAlign, unsigned SrcAlign, bool IsMemset, bool ZeroMemset, bool MemcpyStrSrc, MachineFunction &MF) const override
Returns the target specific optimal type for load and store operations as a result of memset, memcpy, and memmove lowering.
TargetLoweringBase::LegalizeTypeAction getPreferredVectorAction (EVT VT) const override
Return the preferred vector type legalization action.
bool shouldConvertConstantLoadToIntImm (const APInt &Imm, Type *Ty) const override
Return true if it is beneficial to convert a load of a constant to just the constant itself.
SDValue LowerFormalArguments (SDValue Chain, CallingConv::ID CallConv, bool isVarArg, const SmallVectorImpl< ISD::InputArg > &Ins, SDLoc DL, SelectionDAG &DAG, SmallVectorImpl< SDValue > &InVals) const override
This hook must be implemented to lower the incoming (formal) arguments, described by the Ins array, into the specified DAG.
MachineBasicBlock * EmitInstrWithCustomInserter (MachineInstr *MI, MachineBasicBlock *BB) const override
This method should be implemented by targets that mark instructions with the 'usesCustomInserter' flag.
bool enableAggressiveFMAFusion (EVT VT) const override
Return true if target always beneficiates from combining into FMA for a given value type.
EVT getSetCCResultType (LLVMContext &Context, EVT VT) const override
Return the ValueType of the result of SETCC operations.
MVT getScalarShiftAmountTy (EVT VT) const override
bool isFMAFasterThanFMulAndFAdd (EVT VT) const override
Return true if an FMA operation is faster than a pair of fmul and fadd instructions.
SDValue LowerOperation (SDValue Op, SelectionDAG &DAG) const override
This callback is invoked for operations that are unsupported by the target, which are registered to use 'custom' lowering, and whose defined values are all legal.
SDValue PerformDAGCombine (SDNode *N, DAGCombinerInfo &DCI) const override
This method will be invoked for all target nodes and for any target-independent nodes that the target has registered with invoke it for.
SDNode * PostISelFolding (MachineSDNode *N, SelectionDAG &DAG) const override
Fold the instructions after selecting them.
void AdjustInstrPostInstrSelection (MachineInstr *MI, SDNode *Node) const override
Assign the register class depending on the number of bits set in the writemask.
int32_t analyzeImmediate (const SDNode *N) const
Analyze the possible immediate value Op.
SDValue CreateLiveInRegister (SelectionDAG &DAG, const TargetRegisterClass *RC, unsigned Reg, EVT VT) const override
Helper function that adds Reg to the LiveIn list of the DAG's MachineFunction.
void legalizeTargetIndependentNode (SDNode *Node, SelectionDAG &DAG) const
Legalize target independent instructions (e.g.
MachineSDNode * wrapAddr64Rsrc (SelectionDAG &DAG, SDLoc DL, SDValue Ptr) const
MachineSDNode * buildRSRC (SelectionDAG &DAG, SDLoc DL, SDValue Ptr, uint32_t RsrcDword1, uint64_t RsrcDword2And3) const
Return a resource descriptor with the 'Add TID' bit enabled The TID (Thread ID) is multipled by the stride value (bits [61:48] of the resource descriptor) to create an offset, which is added to the resource ponter.
MachineSDNode * buildScratchRSRC (SelectionDAG &DAG, SDLoc DL, SDValue Ptr) const
std::pair< unsigned, const
TargetRegisterClass * > getRegForInlineAsmConstraint (const TargetRegisterInfo *TRI, const std::string &Constraint, MVT VT) const override
Given a physical register constraint (e.g.
SDValue copyToM0 (SelectionDAG &DAG, SDValue Chain, SDLoc DL, SDValue V) const
Detailed Description
Definition at line 23 of file SIISelLowering.h.
Constructor & Destructor Documentation
SITargetLowering::SITargetLowering (TargetMachine & tm, const AMDGPUSubtarget & STI)
Definition at line 38 of file SIISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::ADDC, llvm::ISD::ADDE, llvm::TargetLoweringBase::AddPromotedToType(), llvm::TargetLoweringBase::addRegisterClass(), llvm::ISD::AND, llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_CMP_SWAP_WITH_SUCCESS, llvm::ISD::ATOMIC_LOAD, llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_MAX, llvm::ISD::ATOMIC_LOAD_MIN, llvm::ISD::ATOMIC_LOAD_NAND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, llvm::ISD::ATOMIC_LOAD_UMAX, llvm::ISD::ATOMIC_LOAD_UMIN, llvm::ISD::ATOMIC_LOAD_XOR, llvm::ISD::ATOMIC_STORE, llvm::ISD::ATOMIC_SWAP, llvm::ISD::BITCAST, llvm::ISD::BRCOND, llvm::ISD::BSWAP, llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, llvm::TargetLoweringBase::computeRegisterProperties(), llvm::ISD::CONCAT_VECTORS, llvm::TargetLoweringBase::Custom, llvm::TargetLoweringBase::Expand, llvm::ISD::EXTLOAD, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FADD, llvm::ISD::FCEIL, llvm::ISD::FCOS, llvm::ISD::FDIV, llvm::ISD::FFLOOR, llvm::ISD::FMAXNUM, llvm::ISD::FMINNUM, llvm::MVT::fp_valuetypes(), llvm::ISD::FrameIndex, llvm::ISD::FRINT, llvm::ISD::FSIN, llvm::ISD::FSUB, llvm::ISD::FTRUNC, llvm::AMDGPUSubtarget::getGeneration(), llvm::AMDGPUSubtarget::getRegisterInfo(), llvm::ISD::GlobalAddress, llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::MVT::integer_valuetypes(), llvm::MVT::integer_vector_valuetypes(), llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::TargetLoweringBase::Legal, llvm::ISD::LOAD, llvm::ISD::OR, llvm::MVT::Other, llvm::TargetLoweringBase::Promote, llvm::Sched::RegPressure, llvm::AMDGPUSubtarget::SEA_ISLANDS, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::TargetLoweringBase::setLoadExtAction(), llvm::TargetLoweringBase::setOperationAction(), llvm::TargetLoweringBase::setSchedulingPreference(), llvm::TargetLoweringBase::setTargetDAGCombine(), llvm::TargetLoweringBase::setTruncStoreAction(), llvm::ISD::SEXTLOAD, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::STORE, llvm::ISD::SUBC, llvm::ISD::SUBE, llvm::AMDGPUTargetLowering::Subtarget, llvm::ISD::UDIV, llvm::ISD::UINT_TO_FP, llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::ISD::UREM, llvm::MVT::v16f32, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::MVT::v2f32, llvm::MVT::v2i1, llvm::MVT::v2i16, llvm::MVT::v2i32, llvm::MVT::v2i8, llvm::MVT::v32i8, llvm::MVT::v4f32, llvm::MVT::v4i1, llvm::MVT::v4i16, llvm::MVT::v4i32, llvm::MVT::v4i8, llvm::MVT::v64i8, llvm::MVT::v8f32, llvm::MVT::v8i16, llvm::MVT::v8i32, llvm::ISD::VECTOR_SHUFFLE, and llvm::ISD::ZEXTLOAD.
Member Function Documentation
void SITargetLowering::AdjustInstrPostInstrSelection (MachineInstr * MI, SDNode * Node) const [override, virtual]
Assign the register class depending on the number of bits set in the writemask.
Reimplemented from llvm::TargetLowering.
Definition at line 2059 of file SIISelLowering.cpp.
References llvm::AMDGPU::getAtomicNoRetOp(), llvm::MachineOperand::getImm(), llvm::AMDGPUSubtarget::getInstrInfo(), llvm::AMDGPUInstrInfo::getMaskedMIMGOp(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::SDNode::hasAnyUseOfValue(), llvm::SIInstrInfo::isMIMG(), llvm::SIInstrInfo::legalizeOperands(), llvm::MachineInstr::RemoveOperand(), llvm::MachineInstr::setDesc(), llvm::MachineRegisterInfo::setRegClass(), llvm::AMDGPUTargetLowering::Subtarget, and TII.
bool SITargetLowering::allowsMisalignedMemoryAccesses (EVT , unsigned AddrSpace, unsigned Align, bool *) const [override, virtual]
Determine if the target supports unaligned memory accesses.
This function returns true if the target allows unaligned memory accesses of the specified type in the given address space. If true, it also returns whether the unaligned memory access is "fast" in the last argument by reference. This is used, for example, in situations where an array copy/move/set is converted to a sequence of store operations. Its use helps to ensure that such replacements don't generate code that causes an alignment error (trap) on the target machine.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 336 of file SIISelLowering.cpp.
References llvm::EVT::bitsGT(), llvm::EVT::bitsLT(), llvm::MVT::i32, llvm::EVT::isSimple(), AMDGPUAS::LOCAL_ADDRESS, and Other.
int32_t SITargetLowering::analyzeImmediate (const SDNode * N) const
Analyze the possible immediate value Op.
Returns -1 if it isn't an immediate, 0 if it's and inline immediate and the immediate value if it's a literal immediate
Definition at line 1901 of file SIISelLowering.cpp.
References llvm::MVT::f32, llvm::FloatToBits(), llvm::AMDGPUSubtarget::getInstrInfo(), llvm::SIInstrInfo::isInlineConstant(), llvm::isUInt< 32 >(), llvm::AMDGPUTargetLowering::Subtarget, and TII.
MachineSDNode * SITargetLowering::buildRSRC (SelectionDAG & DAG, SDLoc DL, SDValue Ptr, uint32_t RsrcDword1, uint64_t RsrcDword2And3) const
Return a resource descriptor with the 'Add TID' bit enabled The TID (Thread ID) is multipled by the stride value (bits [61:48] of the resource descriptor) to create an offset, which is added to the resource ponter.
Definition at line 2156 of file SIISelLowering.cpp.
References buildSMovImm32(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetExtractSubreg(), llvm::MVT::i32, llvm::TargetOpcode::REG_SEQUENCE, and llvm::MVT::v4i32.
Referenced by buildScratchRSRC().
MachineSDNode * SITargetLowering::buildScratchRSRC (SelectionDAG & DAG, SDLoc DL, SDValue Ptr) const
Definition at line 2188 of file SIISelLowering.cpp.
References buildRSRC(), llvm::SIInstrInfo::getDefaultRsrcDataFormat(), llvm::AMDGPUSubtarget::getInstrInfo(), llvm::AMDGPU::RSRC_TID_ENABLE, llvm::AMDGPUTargetLowering::Subtarget, and TII.
SDValue SITargetLowering::copyToM0 (SelectionDAG & DAG, SDValue Chain, SDLoc DL, SDValue V) const
Definition at line 908 of file SIISelLowering.cpp.
References llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getRegister(), llvm::SDValue::getValueType(), and llvm::MVT::i32.
SDValue SITargetLowering::CreateLiveInRegister (SelectionDAG & DAG, const TargetRegisterClass * RC, unsigned Reg, EVT VT) const [override, virtual]
Helper function that adds Reg to the LiveIn list of the DAG's MachineFunction.
Returns:
a RegisterSDNode representing Reg.
Reimplemented from llvm::AMDGPUTargetLowering.
Definition at line 2199 of file SIISelLowering.cpp.
References llvm::SelectionDAG::getCopyFromReg(), and llvm::SelectionDAG::getEntryNode().
MachineBasicBlock * SITargetLowering::EmitInstrWithCustomInserter (MachineInstr * MI, MachineBasicBlock * MBB) const [override, virtual]
This method should be implemented by targets that mark instructions with the 'usesCustomInserter' flag.
These instructions are special in various ways, which require special support to insert. The specified MachineInstr is created but not inserted into any basic blocks, and this method is called to expand it into a sequence of instructions, potentially also creating new basic blocks and control flow. As long as the returned basic block is different (i.e., we created a new one), the custom inserter is free to modify the rest of MBB.
Reimplemented from llvm::TargetLowering.
Definition at line 658 of file SIISelLowering.cpp.
References llvm::MachineInstrBuilder::addOperand(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getDebugLoc(), llvm::AMDGPUSubtarget::getInstrInfo(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), I, llvm::AArch64CC::MI, llvm::AMDGPUTargetLowering::Subtarget, and TII.
bool SITargetLowering::enableAggressiveFMAFusion (EVT VT) const [override, virtual]
Return true if target always beneficiates from combining into FMA for a given value type.
This must typically return false on targets where FMA takes more cycles to execute than FADD.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 686 of file SIISelLowering.cpp.
EVT SITargetLowering::getOptimalMemOpType (uint64_t , unsigned , unsigned , bool , bool , bool , MachineFunction &) const [override, virtual]
Returns the target specific optimal type for load and store operations as a result of memset, memcpy, and memmove lowering.
If DstAlign is zero that means it's safe to destination alignment can satisfy any constraint. Similarly if SrcAlign is zero it means there isn't a need to check it against alignment requirement, probably because the source does not need to be loaded. If 'IsMemset' is true, that means it's expanding a memset. If 'ZeroMemset' is true, that means it's a memset of zero. 'MemcpyStrSrc' indicates whether the memcpy source is constant so it does not need to be loaded. It returns EVT::Other if the type should be determined using generic target-independent logic.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 375 of file SIISelLowering.cpp.
References Other, llvm::MVT::v2i32, and llvm::MVT::v4i32.
TargetLoweringBase::LegalizeTypeAction SITargetLowering::getPreferredVectorAction (EVT VT) const [override, virtual]
Return the preferred vector type legalization action.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 396 of file SIISelLowering.cpp.
References llvm::EVT::bitsLE(), llvm::EVT::getScalarType(), llvm::EVT::getVectorNumElements(), llvm::MVT::i16, and llvm::TargetLoweringBase::TypeSplitVector.
std::pair< unsigned, const TargetRegisterClass * > SITargetLowering::getRegForInlineAsmConstraint (const TargetRegisterInfo * TRI, const std::string & Constraint, MVT VT) const [override, virtual]
Given a physical register constraint (e.g.
{edx}), return the register number and the register class for the register.
Given a register class constraint, like 'r', if this corresponds directly to an LLVM register class, return a register of 0 and the register class pointer.
This should only be used for C_Register constraints. On error, this returns a register number of 0 and a null register class pointer.
Reimplemented from llvm::TargetLowering.
Definition at line 2213 of file SIISelLowering.cpp.
References llvm::StringRef::getAsInteger(), llvm::TargetRegisterClass::getRegister(), llvm::MVT::i32, llvm::MVT::i64, llvm_unreachable, llvm::MVT::SimpleTy, llvm::StringRef::size(), and llvm::StringRef::substr().
MVT SITargetLowering::getScalarShiftAmountTy (EVT VT) const [override, virtual]
Reimplemented from llvm::TargetLoweringBase.
Definition at line 704 of file SIISelLowering.cpp.
References llvm::MVT::i32.
EVT SITargetLowering::getSetCCResultType (LLVMContext & Context, EVT VT) const [override, virtual]
Return the ValueType of the result of SETCC operations.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 697 of file SIISelLowering.cpp.
References llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::MVT::i1, and llvm::EVT::isVector().
bool SITargetLowering::isFMAFasterThanFMulAndFAdd (EVT) const [override, virtual]
Return true if an FMA operation is faster than a pair of fmul and fadd instructions.
fmuladd intrinsics will be expanded to FMAs when this method returns true, otherwise fmuladd is expanded to fmul + fadd.
NOTE: This may be called before legalization on types for which FMAs are not legal, but should return true if those types will eventually legalize to types that support FMAs. After legalization, it will only be called on types that support FMAs (via Legal or Custom actions)
Reimplemented from llvm::TargetLoweringBase.
Definition at line 723 of file SIISelLowering.cpp.
References llvm::MVT::f32, llvm::MVT::f64, llvm::EVT::getScalarType(), llvm::EVT::getSimpleVT(), llvm::AMDGPUSubtarget::hasFastFMAF32(), llvm::AMDGPUSubtarget::hasFP32Denormals(), llvm::EVT::isSimple(), llvm::MVT::SimpleTy, and llvm::AMDGPUTargetLowering::Subtarget.
bool SITargetLowering::isLegalAddressingMode (const AddrMode & AM, Type * Ty, unsigned AS) const [override, virtual]
Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
isLegalAddressingMode - Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
The type may be VoidTy, in which case only return true if the addressing mode is legal for a load/store of any legal type. TODO: Handle pre/postinc as well.
If the address space cannot be determined, it will be -1.
TODO: Remove default argument
Reimplemented from llvm::TargetLoweringBase.
Definition at line 257 of file SIISelLowering.cpp.
References llvm::TargetLoweringBase::AddrMode::BaseGV, llvm::TargetLoweringBase::AddrMode::BaseOffs, AMDGPUAS::CONSTANT_ADDRESS, AMDGPUAS::FLAT_ADDRESS, AMDGPUAS::GLOBAL_ADDRESS, llvm::TargetLoweringBase::AddrMode::HasBaseReg, llvm::isUInt< 16 >(), llvm_unreachable, AMDGPUAS::LOCAL_ADDRESS, AMDGPUAS::PRIVATE_ADDRESS, AMDGPUAS::REGION_ADDRESS, llvm::TargetLoweringBase::AddrMode::Scale, and AMDGPUAS::UNKNOWN_ADDRESS_SPACE.
bool SITargetLowering::isShuffleMaskLegal (const SmallVectorImpl< int > & , EVT) const [override, virtual]
Targets can use this to indicate that they only support *some* VECTOR_SHUFFLE operations, those with specific masks.
By default, if a target supports the VECTOR_SHUFFLE node, all mask values are assumed to be legal.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 250 of file SIISelLowering.cpp.
void SITargetLowering::legalizeTargetIndependentNode (SDNode * Node, SelectionDAG & DAG) const
Legalize target independent instructions (e.g.
INSERT_SUBREG) with frame index operands. LLVM assumes that inputs are to these instructions are registers.
Definition at line 2021 of file SIISelLowering.cpp.
References llvm::DL, llvm::SelectionDAG::getMachineNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::SelectionDAG::UpdateNodeOperands().
Referenced by PostISelFolding().
SDValue SITargetLowering::LowerFormalArguments (SDValue , CallingConv::ID , bool , const SmallVectorImpl< ISD::InputArg > & , SDLoc , SelectionDAG & , SmallVectorImpl< SDValue > &) const [override, virtual]
This hook must be implemented to lower the incoming (formal) arguments, described by the Ins array, into the specified DAG.
The implementation should fill in the InVals array with legal-type argument values, and return the resulting token chain value.
Reimplemented from llvm::TargetLowering.
Definition at line 466 of file SIISelLowering.cpp.
References llvm::AMDGPUMachineFunction::ABIArgOffset, llvm::MachineFunction::addLiveIn(), llvm::AMDGPUTargetLowering::AnalyzeFormalArguments(), llvm::SmallVectorImpl< T >::append(), llvm::ISD::AssertZext, llvm::sys::path::begin(), llvm::ISD::BUILD_VECTOR, llvm::CallingConv::C, ShaderType::COMPUTE, llvm::dyn_cast(), llvm::ISD::InputArg::Flags, llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::MachineFunction::getFunction(), llvm::Function::getFunctionType(), llvm::AMDGPUSubtarget::getGeneration(), llvm::MachineFunction::getInfo(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::ISD::InputArg::getOrigArgIndex(), llvm::AMDGPUTargetLowering::getOriginalFunctionArgs(), llvm::FunctionType::getParamType(), llvm::SIRegisterInfo::getPhysRegSubReg(), llvm::SIRegisterInfo::getPreloadedValue(), llvm::AMDGPUSubtarget::getRegisterInfo(), llvm::SelectionDAG::getRoot(), llvm::AMDGPUMachineFunction::getShaderType(), llvm::EVT::getStoreSize(), llvm::MVT::getStoreSize(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::Type::getVectorNumElements(), llvm::MVT::i16, llvm::MVT::i64, llvm::SIRegisterInfo::INPUT_PTR, llvm::MipsISD::Ins, llvm::AMDGPUSubtarget::isAmdHsaOS(), llvm::ISD::ArgFlagsTy::isByVal(), llvm::ISD::ArgFlagsTy::isInReg(), llvm::CCValAssign::isMemLoc(), llvm::CCValAssign::isRegLoc(), llvm::MVT::isVector(), AMDGPUAS::LOCAL_ADDRESS, llvm::SIMachineFunctionInfo::NumUserSGPRs, llvm::ISD::InputArg::PartOffset, ShaderType::PIXEL, llvm::SIMachineFunctionInfo::PSInputAddr, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SIRegisterInfo::SCRATCH_PTR, llvm::SIMachineFunctionInfo::ScratchOffsetReg, llvm::ISD::ArgFlagsTy::setSplit(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::Skipped, llvm::AMDGPUSubtarget::SOUTHERN_ISLANDS, llvm::AMDGPUTargetLowering::Subtarget, llvm::ISD::InputArg::Used, and llvm::ISD::InputArg::VT.
SDValue SITargetLowering::LowerOperation (SDValue Op, SelectionDAG & DAG) const [override, virtual]
This callback is invoked for operations that are unsupported by the target, which are registered to use 'custom' lowering, and whose defined values are all legal.
If the target has no operations that require custom lowering, it need not implement this. The default implementation of this aborts.
Reimplemented from llvm::AMDGPUTargetLowering.
Definition at line 749 of file SIISelLowering.cpp.
References llvm::ISD::BRCOND, llvm::ISD::FCOS, llvm::ISD::FDIV, llvm::ISD::FrameIndex, llvm::ISD::FSIN, llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::SDNode::getNumValues(), llvm::SDValue::getOpcode(), llvm::ISD::GlobalAddress, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::ISD::LOAD, llvm::ISD::SELECT, and llvm::ISD::STORE.
SDValue SITargetLowering::PerformDAGCombine (SDNode * N, DAGCombinerInfo & DCI) const [override, virtual]
This method will be invoked for all target nodes and for any target-independent nodes that the target has registered with invoke it for.
The semantics are as follows: Return Value: SDValue.Val == 0 - No change was made SDValue.Val == N - N was replaced, is dead, and is already handled. otherwise - N should be replaced by the returned Operand.
In addition, methods provided by DAGCombinerInfo may be used to perform more complex transformations.
Reimplemented from llvm::AMDGPUTargetLowering.
Definition at line 1722 of file SIISelLowering.cpp.
References llvm::ARM_PROC::A, llvm::AfterLegalizeDAG, llvm::ISD::AND, llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_CMP_SWAP_WITH_SUCCESS, llvm::ISD::ATOMIC_LOAD, llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_MAX, llvm::ISD::ATOMIC_LOAD_MIN, llvm::ISD::ATOMIC_LOAD_NAND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, llvm::ISD::ATOMIC_LOAD_UMAX, llvm::ISD::ATOMIC_LOAD_UMIN, llvm::ISD::ATOMIC_LOAD_XOR, llvm::ISD::ATOMIC_STORE, llvm::ISD::ATOMIC_SWAP, llvm::TargetLowering::DAGCombinerInfo::CommitTargetLoweringOpt(), llvm::AMDGPUISD::CVT_F32_UBYTE0, llvm::AMDGPUISD::CVT_F32_UBYTE1, llvm::AMDGPUISD::CVT_F32_UBYTE2, llvm::AMDGPUISD::CVT_F32_UBYTE3, llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::DL, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FADD, llvm::ISD::FMAD, llvm::ISD::FMAXNUM, llvm::ISD::FMINNUM, llvm::ISD::FNEG, llvm::AMDGPUISD::FP_CLASS, llvm::ISD::FSUB, llvm::MemSDNode::getAddressSpace(), llvm::MemSDNode::getBasePtr(), llvm::APInt::getBitsSet(), llvm::SelectionDAG::getConstantFP(), llvm::TargetLowering::DAGCombinerInfo::getDAGCombineLevel(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::TargetMachine::getOptLevel(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::TargetLoweringBase::getTargetMachine(), llvm::SDNode::getValueType(), llvm::AMDGPUSubtarget::hasFP32Denormals(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::ISD::LOAD, llvm::TargetLoweringBase::None, llvm::SDNode::op_begin(), llvm::SDNode::op_end(), llvm::ISD::OR, AMDGPUAS::PRIVATE_ADDRESS, llvm::ISD::SETCC, llvm::ISD::SHL, llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::STORE, llvm::AMDGPUTargetLowering::Subtarget, llvm::ISD::UINT_TO_FP, llvm::ISD::UMAX, llvm::ISD::UMIN, and llvm::SelectionDAG::UpdateNodeOperands().
SDNode * SITargetLowering::PostISelFolding (MachineSDNode * N, SelectionDAG & DAG) const [override, virtual]
Fold the instructions after selecting them.
Reimplemented from llvm::AMDGPUTargetLowering.
Definition at line 2041 of file SIISelLowering.cpp.
References llvm::AMDGPUSubtarget::getInstrInfo(), llvm::SDNode::getMachineOpcode(), llvm::TargetOpcode::INSERT_SUBREG, llvm::SIInstrInfo::isMIMG(), legalizeTargetIndependentNode(), llvm::TargetOpcode::REG_SEQUENCE, llvm::AMDGPUTargetLowering::Subtarget, and TII.
bool SITargetLowering::shouldConvertConstantLoadToIntImm (const APInt & Imm, Type * Ty) const [override, virtual]
Return true if it is beneficial to convert a load of a constant to just the constant itself.
On some targets it might be more efficient to use a combination of arithmetic instructions to materialize the constant instead of loading it from a constant pool.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 403 of file SIISelLowering.cpp.
References llvm::AMDGPUSubtarget::getInstrInfo(), llvm::SIInstrInfo::isInlineConstant(), llvm::AMDGPUTargetLowering::Subtarget, and TII.
MachineSDNode * SITargetLowering::wrapAddr64Rsrc (SelectionDAG & DAG, SDLoc DL, SDValue Ptr) const
Definition at line 2105 of file SIISelLowering.cpp.
References buildSMovImm32(), llvm::SIInstrInfo::getDefaultRsrcDataFormat(), llvm::AMDGPUSubtarget::getInstrInfo(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getTargetConstant(), llvm::MVT::i32, llvm::TargetOpcode::REG_SEQUENCE, llvm::AMDGPUTargetLowering::Subtarget, TII, llvm::MVT::v2i32, and llvm::MVT::v4i32.
The documentation for this class was generated from the following files:
SIISelLowering.h
SIISelLowering.cpp