LLVM: llvm::opt::final Class Reference
llvm::opt::final Class Reference
DerivedArgList - An ordered collection of driver arguments, whose storage may be in another argument list.
#include <ArgList.h>
Public Member Functions
InputArgList (const char *const *ArgBegin, const char *const *ArgEnd)
InputArgList (InputArgList &&RHS)
InputArgList & operator= (InputArgList &&RHS)
~InputArgList ()
const char * getArgString (unsigned Index) const override
getArgString - Return the input argument string at Index.
unsigned getNumInputArgStrings () const override
getNumInputArgStrings - Return the number of original argument strings, which are guaranteed to be the first strings in the argument string list.
DerivedArgList (const InputArgList &BaseArgs)
Construct a new derived arg list from BaseArgs.
const char * getArgString (unsigned Index) const override
getArgString - Return the input argument string at Index.
unsigned getNumInputArgStrings () const override
getNumInputArgStrings - Return the number of original argument strings, which are guaranteed to be the first strings in the argument string list.
const InputArgList & getBaseArgs () const
Arg Synthesis
unsigned MakeIndex (StringRef String0) const
MakeIndex - Get an index for the given string(s).
unsigned MakeIndex (StringRef String0, StringRef String1) const
const char * MakeArgStringRef (StringRef Str) const override
Construct a constant string pointer whose lifetime will match that of the ArgList.
void AddSynthesizedArg (Arg *A)
AddSynthesizedArg - Add a argument to the list of synthesized arguments (to be freed).
const char * MakeArgStringRef (StringRef Str) const override
Construct a constant string pointer whose lifetime will match that of the ArgList.
void AddFlagArg (const Arg *BaseArg, const Option Opt)
AddFlagArg - Construct a new FlagArg for the given option Id and append it to the argument list.
void AddPositionalArg (const Arg *BaseArg, const Option Opt, StringRef Value)
AddPositionalArg - Construct a new Positional arg for the given option Id, with the provided Value and append it to the argument list.
void AddSeparateArg (const Arg *BaseArg, const Option Opt, StringRef Value)
AddSeparateArg - Construct a new Positional arg for the given option Id, with the provided Value and append it to the argument list.
void AddJoinedArg (const Arg *BaseArg, const Option Opt, StringRef Value)
AddJoinedArg - Construct a new Positional arg for the given option Id, with the provided Value and append it to the argument list.
Arg * MakeFlagArg (const Arg *BaseArg, const Option Opt) const
MakeFlagArg - Construct a new FlagArg for the given option Id.
Arg * MakePositionalArg (const Arg *BaseArg, const Option Opt, StringRef Value) const
MakePositionalArg - Construct a new Positional arg for the given option Id, with the provided Value.
Arg * MakeSeparateArg (const Arg *BaseArg, const Option Opt, StringRef Value) const
MakeSeparateArg - Construct a new Positional arg for the given option Id, with the provided Value.
Arg * MakeJoinedArg (const Arg *BaseArg, const Option Opt, StringRef Value) const
MakeJoinedArg - Construct a new Positional arg for the given option Id, with the provided Value.
Detailed Description
DerivedArgList - An ordered collection of driver arguments, whose storage may be in another argument list.
Definition at line 309 of file ArgList.h.
Constructor & Destructor Documentation
llvm::opt::final::~InputArgList () [inline]
Definition at line 345 of file ArgList.h.
Member Function Documentation
void llvm::opt::final::AddFlagArg (const Arg * BaseArg, const Option Opt) [inline]
AddFlagArg - Construct a new FlagArg for the given option Id and append it to the argument list.
Definition at line 405 of file ArgList.h.
References llvm::sys::path::append().
void llvm::opt::final::AddJoinedArg (const Arg * BaseArg, const Option Opt, StringRef Value) [inline]
AddJoinedArg - Construct a new Positional arg for the given option Id, with the provided Value and append it to the argument list.
Definition at line 429 of file ArgList.h.
References llvm::sys::path::append().
void llvm::opt::final::AddPositionalArg (const Arg * BaseArg, const Option Opt, StringRef Value) [inline]
AddPositionalArg - Construct a new Positional arg for the given option Id, with the provided Value and append it to the argument list.
Definition at line 412 of file ArgList.h.
References llvm::sys::path::append().
void llvm::opt::final::AddSeparateArg (const Arg * BaseArg, const Option Opt, StringRef Value) [inline]
AddSeparateArg - Construct a new Positional arg for the given option Id, with the provided Value and append it to the argument list.
Definition at line 421 of file ArgList.h.
References llvm::sys::path::append().
void llvm::opt::final::AddSynthesizedArg (Arg * A)
AddSynthesizedArg - Add a argument to the list of synthesized arguments (to be freed).
llvm::opt::final::DerivedArgList (const InputArgList & BaseArgs)
Construct a new derived arg list from BaseArgs.
const char* llvm::opt::final::getArgString (unsigned Index) const [inline, override, virtual]
getArgString - Return the input argument string at Index.
Implements llvm::opt::ArgList.
Definition at line 347 of file ArgList.h.
const char* llvm::opt::final::getArgString (unsigned Index) const [inline, override, virtual]
getArgString - Return the input argument string at Index.
Implements llvm::opt::ArgList.
Definition at line 381 of file ArgList.h.
const InputArgList& llvm::opt::final::getBaseArgs () const [inline]
Definition at line 389 of file ArgList.h.
unsigned llvm::opt::final::getNumInputArgStrings () const [inline, override, virtual]
getNumInputArgStrings - Return the number of original argument strings, which are guaranteed to be the first strings in the argument string list.
Implements llvm::opt::ArgList.
Definition at line 351 of file ArgList.h.
unsigned llvm::opt::final::getNumInputArgStrings () const [inline, override, virtual]
getNumInputArgStrings - Return the number of original argument strings, which are guaranteed to be the first strings in the argument string list.
Implements llvm::opt::ArgList.
Definition at line 385 of file ArgList.h.
llvm::opt::final::InputArgList (const char *const * ArgBegin, const char *const * ArgEnd)
llvm::opt::final::InputArgList (InputArgList && RHS) [inline]
Definition at line 333 of file ArgList.h.
const char* llvm::opt::final::MakeArgStringRef (StringRef Str) const [override, virtual]
Construct a constant string pointer whose lifetime will match that of the ArgList.
Implements llvm::opt::ArgList.
const char* llvm::opt::final::MakeArgStringRef (StringRef Str) const [override, virtual]
Construct a constant string pointer whose lifetime will match that of the ArgList.
Implements llvm::opt::ArgList.
Arg* llvm::opt::final::MakeFlagArg (const Arg * BaseArg, const Option Opt) const
MakeFlagArg - Construct a new FlagArg for the given option Id.
unsigned llvm::opt::final::MakeIndex (StringRef String0) const
MakeIndex - Get an index for the given string(s).
unsigned llvm::opt::final::MakeIndex (StringRef String0, StringRef String1) const
Arg* llvm::opt::final::MakeJoinedArg (const Arg * BaseArg, const Option Opt, StringRef Value) const
MakeJoinedArg - Construct a new Positional arg for the given option Id, with the provided Value.
Arg* llvm::opt::final::MakePositionalArg (const Arg * BaseArg, const Option Opt, StringRef Value) const
MakePositionalArg - Construct a new Positional arg for the given option Id, with the provided Value.
Arg* llvm::opt::final::MakeSeparateArg (const Arg * BaseArg, const Option Opt, StringRef Value) const
MakeSeparateArg - Construct a new Positional arg for the given option Id, with the provided Value.
InputArgList& llvm::opt::final::operator= (InputArgList && RHS) [inline]
Definition at line 337 of file ArgList.h.
References llvm::opt::ArgList::operator=().
The documentation for this class was generated from the following file:
ArgList.h