LLVM: llvm::MemTransferInst Class Reference
llvm::MemTransferInst Class Reference
MemTransferInst - This class wraps the llvm.memcpy/memmove intrinsics.
#include <IntrinsicInst.h>
Public Member Functions
Value * getRawSource () const
get* - Return the arguments to the instruction.
const Use & getRawSourceUse () const
Use & getRawSourceUse ()
Value * getSource () const
getSource - This is just like getRawSource, but it strips off any cast instructions that feed it, giving the original input.
unsigned getSourceAddressSpace () const
void setSource (Value *Ptr)
Static Public Member Functions
static bool classof (const IntrinsicInst *I)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Detailed Description
MemTransferInst - This class wraps the llvm.memcpy/memmove intrinsics.
Definition at line 245 of file IntrinsicInst.h.
Member Function Documentation
static bool llvm::MemTransferInst::classof (const IntrinsicInst * I) [inline, static]
Reimplemented from llvm::MemIntrinsic.
Reimplemented in llvm::MemMoveInst, and llvm::MemCpyInst.
Definition at line 269 of file IntrinsicInst.h.
References llvm::IntrinsicInst::getIntrinsicID().
Referenced by classof().
static bool llvm::MemTransferInst::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::MemIntrinsic.
Reimplemented in llvm::MemMoveInst, and llvm::MemCpyInst.
Definition at line 273 of file IntrinsicInst.h.
References classof().
Value* llvm::MemTransferInst::getRawSource () const [inline]
get* - Return the arguments to the instruction.
Definition at line 249 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperand().
Referenced by llvm::MemoryLocation::getForSource(), getSource(), getSourceAddressSpace(), and setSource().
const Use& llvm::MemTransferInst::getRawSourceUse () const [inline]
Definition at line 250 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperandUse().
Use& llvm::MemTransferInst::getRawSourceUse () [inline]
Definition at line 251 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperandUse().
Value* llvm::MemTransferInst::getSource () const [inline]
getSource - This is just like getRawSource, but it strips off any cast instructions that feed it, giving the original input.
The returned value is guaranteed to be a pointer.
Definition at line 256 of file IntrinsicInst.h.
References getRawSource(), and llvm::Value::stripPointerCasts().
Referenced by AnalyzeLoadFromClobberingMemInst(), GetMemInstValueForLoad(), and isOnlyCopiedFromConstantGlobal().
unsigned llvm::MemTransferInst::getSourceAddressSpace () const [inline]
Definition at line 258 of file IntrinsicInst.h.
References getRawSource(), and llvm::Value::getType().
void llvm::MemTransferInst::setSource (Value * Ptr) [inline]
Definition at line 262 of file IntrinsicInst.h.
References getRawSource(), llvm::Value::getType(), and llvm::CallInst::setArgOperand().
The documentation for this class was generated from the following file:
IntrinsicInst.h