LLVM: llvm::AMDGPUInstPrinter Class Reference
llvm::AMDGPUInstPrinter Class Reference
#include <AMDGPUInstPrinter.h>
Public Member Functions
AMDGPUInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printInstruction (const MCInst *MI, raw_ostream &O)
void printInst (const MCInst *MI, raw_ostream &O, StringRef Annot, const MCSubtargetInfo &STI) override
Print the specified MCInst to the specified raw_ostream.
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo)
static void printRegOperand (unsigned RegNo, raw_ostream &O, const MCRegisterInfo &MRI)
Detailed Description
Definition at line 22 of file AMDGPUInstPrinter.h.
Constructor & Destructor Documentation
llvm::AMDGPUInstPrinter::AMDGPUInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) [inline]
Definition at line 24 of file AMDGPUInstPrinter.h.
Member Function Documentation
static const char* llvm::AMDGPUInstPrinter::getRegisterName (unsigned RegNo) [static]
Referenced by printRegOperand().
void AMDGPUInstPrinter::printInst (const MCInst * MI, raw_ostream & OS, StringRef Annot, const MCSubtargetInfo & STI) [override, virtual]
Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Definition at line 22 of file AMDGPUInstPrinter.cpp.
References llvm::raw_ostream::flush(), llvm::MCInstPrinter::printAnnotation(), and printInstruction().
Referenced by llvm::AMDGPUAsmPrinter::EmitInstruction().
void llvm::AMDGPUInstPrinter::printInstruction (const MCInst * MI, raw_ostream & O)
Referenced by printInst().
void AMDGPUInstPrinter::printRegOperand (unsigned RegNo, raw_ostream & O, const MCRegisterInfo & MRI) [static]
Definition at line 130 of file AMDGPUInstPrinter.cpp.
References llvm::MCRegisterClass::contains(), llvm::MCRegisterInfo::getEncodingValue(), llvm::MCRegisterInfo::getRegClass(), and getRegisterName().
Referenced by llvm::AMDGPUAsmPrinter::PrintAsmOperand().
The documentation for this class was generated from the following files:
AMDGPUInstPrinter.h
AMDGPUInstPrinter.cpp