LLVM: llvm::DIADataStream Class Reference
llvm::DIADataStream Class Reference
#include <DIADataStream.h>
Public Member Functions
DIADataStream (CComPtr< IDiaEnumDebugStreamData > DiaStreamData)
uint32_t getRecordCount () const override
std::string getName () const override
llvm::Optional< RecordType > getItemAtIndex (uint32_t Index) const override
bool getNext (RecordType &Record) override
void reset () override
DIADataStream * clone () const override
Detailed Description
Definition at line 17 of file DIADataStream.h.
Constructor & Destructor Documentation
DIADataStream::DIADataStream (CComPtr< IDiaEnumDebugStreamData > DiaStreamData) [explicit]
Definition at line 15 of file DIADataStream.cpp.
Referenced by clone().
Member Function Documentation
DIADataStream * DIADataStream::clone () const [override, virtual]
Implements llvm::IPDBDataStream.
Definition at line 67 of file DIADataStream.cpp.
References DIADataStream().
llvm::Optional< DIADataStream::RecordType > DIADataStream::getItemAtIndex (uint32_t Index) const [override, virtual]
Implements llvm::IPDBDataStream.
Definition at line 37 of file DIADataStream.cpp.
References llvm::SmallVectorImpl< T >::resize().
std::string DIADataStream::getName () const [override, virtual]
Implements llvm::IPDBDataStream.
Definition at line 23 of file DIADataStream.cpp.
References llvm::convertUTF16ToUTF8String().
bool DIADataStream::getNext (RecordType & Record) [override, virtual]
Implements llvm::IPDBDataStream.
Definition at line 50 of file DIADataStream.cpp.
References llvm::SmallVectorImpl< T >::clear(), and llvm::SmallVectorImpl< T >::resize().
uint32_t DIADataStream::getRecordCount () const [override, virtual]
Implements llvm::IPDBDataStream.
Definition at line 18 of file DIADataStream.cpp.
void DIADataStream::reset () [override, virtual]
Implements llvm::IPDBDataStream.
Definition at line 65 of file DIADataStream.cpp.
The documentation for this class was generated from the following files:
DIADataStream.h
DIADataStream.cpp