LLVM: llvm::GCOVBlock Class Reference
llvm::GCOVBlock Class Reference
GCOVBlock - Collects block information.
#include <GCOV.h>
Classes
struct EdgeWeight
struct SortDstEdgesFunctor
Public Types
typedef SmallVectorImpl
< GCOVEdge * >::const_iterator EdgeIterator
Public Member Functions
GCOVBlock (GCOVFunction &P, uint32_t N)
~GCOVBlock ()
~GCOVBlock - Delete GCOVBlock and its content.
const GCOVFunction & getParent () const
void addLine (uint32_t N)
uint32_t getLastLine () const
void addCount (size_t DstEdgeNo, uint64_t N)
addCount - Add to block counter while storing the edge count.
uint64_t getCount () const
void addSrcEdge (GCOVEdge *Edge)
void addDstEdge (GCOVEdge *Edge)
size_t getNumSrcEdges () const
size_t getNumDstEdges () const
void sortDstEdges ()
sortDstEdges - Sort destination edges by block number, nop if already sorted.
EdgeIterator src_begin () const
EdgeIterator src_end () const
iterator_range< EdgeIterator > srcs () const
EdgeIterator dst_begin () const
EdgeIterator dst_end () const
iterator_range< EdgeIterator > dsts () const
void dump () const
dump - Dump GCOVBlock content to dbgs() for debugging purposes.
void collectLineCounts (FileInfo &FI)
collectLineCounts - Collect line counts.
Detailed Description
GCOVBlock - Collects block information.
Definition at line 292 of file GCOV.h.
Member Typedef Documentation
typedef SmallVectorImpl<GCOVEdge *>::const_iterator llvm::GCOVBlock::EdgeIterator
Definition at line 307 of file GCOV.h.
Constructor & Destructor Documentation
llvm::GCOVBlock::GCOVBlock (GCOVFunction & P, uint32_t N) [inline]
Definition at line 309 of file GCOV.h.
GCOVBlock::~GCOVBlock ()
~GCOVBlock - Delete GCOVBlock and its content.
Definition at line 367 of file GCOV.cpp.
References llvm::SmallVectorImpl< T >::clear().
Member Function Documentation
void GCOVBlock::addCount (size_t DstEdgeNo, uint64_t N)
addCount - Add to block counter while storing the edge count.
If the destination has no outgoing edges, also update that block's count too.
Definition at line 375 of file GCOV.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::GCOVFunction::readGCDA().
void llvm::GCOVBlock::addDstEdge (GCOVEdge * Edge) [inline]
Definition at line 323 of file GCOV.h.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::GCOVEdge::Dst, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::GCOVEdge::Src.
void llvm::GCOVBlock::addLine (uint32_t N) [inline]
Definition at line 314 of file GCOV.h.
References llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by llvm::GCOVFunction::readGCNO().
void llvm::GCOVBlock::addSrcEdge (GCOVEdge * Edge) [inline]
Definition at line 319 of file GCOV.h.
References llvm::GCOVEdge::Dst, and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
void GCOVBlock::collectLineCounts (FileInfo & FI)
collectLineCounts - Collect line counts.
This must be used after reading .gcno and .gcda files.
Definition at line 394 of file GCOV.cpp.
References llvm::FileInfo::addBlockLine(), llvm::GCOVFunction::getFilename(), and N.
EdgeIterator llvm::GCOVBlock::dst_begin () const [inline]
Definition at line 340 of file GCOV.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
Referenced by dsts().
EdgeIterator llvm::GCOVBlock::dst_end () const [inline]
Definition at line 341 of file GCOV.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by dsts().
iterator_range<EdgeIterator> llvm::GCOVBlock::dsts () const [inline]
Definition at line 342 of file GCOV.h.
References dst_begin(), dst_end(), and llvm::make_range().
void GCOVBlock::dump () const
dump - Dump GCOVBlock content to dbgs() for debugging purposes.
Definition at line 400 of file GCOV.cpp.
References llvm::dbgs(), llvm::SmallVectorBase::empty(), and N.
uint64_t llvm::GCOVBlock::getCount () const [inline]
Definition at line 317 of file GCOV.h.
uint32_t llvm::GCOVBlock::getLastLine () const [inline]
Definition at line 315 of file GCOV.h.
References llvm::SmallVectorTemplateCommon< T, typename >::back().
size_t llvm::GCOVBlock::getNumDstEdges () const [inline]
Definition at line 331 of file GCOV.h.
References llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::GCOVFunction::readGCDA().
size_t llvm::GCOVBlock::getNumSrcEdges () const [inline]
Definition at line 330 of file GCOV.h.
References llvm::SmallVectorTemplateCommon< T, typename >::size().
const GCOVFunction& llvm::GCOVBlock::getParent () const [inline]
Definition at line 313 of file GCOV.h.
void GCOVBlock::sortDstEdges ()
sortDstEdges - Sort destination edges by block number, nop if already sorted.
This is required for printing branch info in the correct order.
Definition at line 385 of file GCOV.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by llvm::GCOVFunction::readGCDA().
EdgeIterator llvm::GCOVBlock::src_begin () const [inline]
Definition at line 334 of file GCOV.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
Referenced by srcs().
EdgeIterator llvm::GCOVBlock::src_end () const [inline]
Definition at line 335 of file GCOV.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by srcs().
iterator_range<EdgeIterator> llvm::GCOVBlock::srcs () const [inline]
Definition at line 336 of file GCOV.h.
References llvm::make_range(), src_begin(), and src_end().
The documentation for this class was generated from the following files:
GCOV.h
GCOV.cpp