LLVM: llvm::SimplifyCFGPass Class Reference
llvm::SimplifyCFGPass Class Reference
A pass to simplify and canonicalize the CFG of a function.
#include <SimplifyCFG.h>
Public Member Functions
SimplifyCFGPass ()
Construct a pass with the default thresholds.
SimplifyCFGPass (int BonusInstThreshold)
Construct a pass with a specific bonus threshold.
PreservedAnalyses run (Function &F, AnalysisManager< Function > *AM)
Run the pass over the function.
Static Public Member Functions
static StringRef name ()
Detailed Description
A pass to simplify and canonicalize the CFG of a function.
This pass iteratively simplifies the entire CFG of a function, removing unnecessary control flows and bringing it into the canonical form expected by the rest of the mid-level optimizer.
Definition at line 28 of file SimplifyCFG.h.
Constructor & Destructor Documentation
SimplifyCFGPass::SimplifyCFGPass ()
Construct a pass with the default thresholds.
Definition at line 175 of file SimplifyCFGPass.cpp.
SimplifyCFGPass::SimplifyCFGPass (int BonusInstThreshold)
Construct a pass with a specific bonus threshold.
Definition at line 178 of file SimplifyCFGPass.cpp.
Member Function Documentation
static StringRef llvm::SimplifyCFGPass::name () [inline, static]
Definition at line 32 of file SimplifyCFG.h.
PreservedAnalyses SimplifyCFGPass::run (Function & F, AnalysisManager< Function > * AM)
Run the pass over the function.
Definition at line 181 of file SimplifyCFGPass.cpp.
References llvm::PreservedAnalyses::all(), F(), llvm::detail::AnalysisManagerBase< AnalysisManager< IRUnitT >, IRUnitT >::getResult(), llvm::PreservedAnalyses::none(), and simplifyFunctionCFG().
The documentation for this class was generated from the following files:
SimplifyCFG.h
SimplifyCFGPass.cpp