LLVM: llvm::TargetLoweringObjectFileCOFF Class Reference
llvm::TargetLoweringObjectFileCOFF Class Reference
#include <TargetLoweringObjectFileImpl.h>
Public Member Functions
~TargetLoweringObjectFileCOFF () override
MCSection * getExplicitSectionGlobal (const GlobalValue *GV, SectionKind Kind, Mangler &Mang, const TargetMachine &TM) const override
Targets should implement this method to assign a section to globals with an explicit section specfied.
MCSection * SelectSectionForGlobal (const GlobalValue *GV, SectionKind Kind, Mangler &Mang, const TargetMachine &TM) const override
void getNameWithPrefix (SmallVectorImpl< char > &OutName, const GlobalValue *GV, bool CannotUsePrivateLabel, Mangler &Mang, const TargetMachine &TM) const override
MCSection * getSectionForJumpTable (const Function &F, Mangler &Mang, const TargetMachine &TM) const override
StringRef getDepLibFromLinkerOpt (StringRef LinkerOption) const override
Extract the dependent library name from a linker option string.
void emitModuleFlags (MCStreamer &Streamer, ArrayRef< Module::ModuleFlagEntry > ModuleFlags, Mangler &Mang, const TargetMachine &TM) const override
Emit Obj-C garbage collection and linker options.
MCSection * getStaticCtorSection (unsigned Priority, const MCSymbol *KeySym) const override
MCSection * getStaticDtorSection (unsigned Priority, const MCSymbol *KeySym) const override
Detailed Description
Definition at line 134 of file TargetLoweringObjectFileImpl.h.
Constructor & Destructor Documentation
llvm::TargetLoweringObjectFileCOFF::~TargetLoweringObjectFileCOFF () [inline, override]
Definition at line 136 of file TargetLoweringObjectFileImpl.h.
Member Function Documentation
void TargetLoweringObjectFileCOFF::emitModuleFlags (MCStreamer & Streamer, ArrayRef< Module::ModuleFlagEntry > ModuleFlags, Mangler & Mang, const TargetMachine & TM) const [override, virtual]
Emit Obj-C garbage collection and linker options.
Only linker option emission is implemented for COFF.
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 1002 of file TargetLoweringObjectFileImpl.cpp.
References llvm::ArrayRef< T >::begin(), llvm::MCStreamer::EmitBytes(), llvm::ArrayRef< T >::end(), llvm::MCObjectFileInfo::getDrectveSection(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::MDString::getString(), llvm::Module::ModuleFlagEntry::Key, llvm::MCStreamer::SwitchSection(), and llvm::Module::ModuleFlagEntry::Val.
StringRef TargetLoweringObjectFileCOFF::getDepLibFromLinkerOpt (StringRef LinkerOption) const [override, virtual]
Extract the dependent library name from a linker option string.
Returns StringRef() if the option does not specify a library.
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 994 of file TargetLoweringObjectFileImpl.cpp.
References llvm::StringRef::startswith(), and llvm::StringRef::substr().
MCSection * TargetLoweringObjectFileCOFF::getExplicitSectionGlobal (const GlobalValue * GV, SectionKind Kind, Mangler & Mang, const TargetMachine & TM) const [override, virtual]
Targets should implement this method to assign a section to globals with an explicit section specfied.
The implementation of this method can assume that GV->hasSection() is true.
Implements llvm::TargetLoweringObjectFile.
Definition at line 859 of file TargetLoweringObjectFileImpl.cpp.
References Characteristics, llvm::MCContext::getCOFFSection(), getCOFFSectionFlags(), getComdatGVForCOFF(), llvm::TargetLoweringObjectFile::getContext(), llvm::MCSymbol::getName(), llvm::GlobalValue::getSection(), getSelectionForCOFF(), llvm::TargetMachine::getSymbol(), llvm::GlobalValue::hasComdat(), llvm::GlobalValue::hasPrivateLinkage(), llvm::COFF::IMAGE_COMDAT_SELECT_ASSOCIATIVE, and llvm::COFF::IMAGE_SCN_LNK_COMDAT.
void TargetLoweringObjectFileCOFF::getNameWithPrefix (SmallVectorImpl< char > & OutName, const GlobalValue * GV, bool CannotUsePrivateLabel, Mangler & Mang, const TargetMachine & TM) const [override, virtual]
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 957 of file TargetLoweringObjectFileImpl.cpp.
References llvm::TargetMachine::getDataSections(), llvm::TargetMachine::getFunctionSections(), llvm::Mangler::getNameWithPrefix(), and llvm::GlobalValue::hasPrivateLinkage().
Referenced by SelectSectionForGlobal().
MCSection * TargetLoweringObjectFileCOFF::getSectionForJumpTable (const Function & F, Mangler & Mang, const TargetMachine & TM) const [override, virtual]
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 968 of file TargetLoweringObjectFileImpl.cpp.
References llvm::C, Characteristics, llvm::MCContext::getCOFFSection(), getCOFFSectionFlags(), getCOFFSectionNameForUniqueGlobal(), llvm::GlobalObject::getComdat(), llvm::TargetLoweringObjectFile::getContext(), llvm::TargetMachine::getFunctionSections(), llvm::MCSymbol::getName(), llvm::SectionKind::getReadOnly(), llvm::TargetMachine::getSymbol(), llvm::GlobalValue::hasPrivateLinkage(), llvm::COFF::IMAGE_COMDAT_SELECT_ASSOCIATIVE, llvm::COFF::IMAGE_SCN_LNK_COMDAT, Kind, and llvm::MCObjectFileInfo::ReadOnlySection.
MCSection * TargetLoweringObjectFileCOFF::getStaticCtorSection (unsigned Priority, const MCSymbol * KeySym) const [override, virtual]
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 1037 of file TargetLoweringObjectFileImpl.cpp.
References llvm::MCContext::getAssociativeCOFFSection(), llvm::TargetLoweringObjectFile::getContext(), and llvm::MCObjectFileInfo::StaticCtorSection.
MCSection * TargetLoweringObjectFileCOFF::getStaticDtorSection (unsigned Priority, const MCSymbol * KeySym) const [override, virtual]
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 1043 of file TargetLoweringObjectFileImpl.cpp.
References llvm::MCContext::getAssociativeCOFFSection(), llvm::TargetLoweringObjectFile::getContext(), and llvm::MCObjectFileInfo::StaticDtorSection.
MCSection * TargetLoweringObjectFileCOFF::SelectSectionForGlobal (const GlobalValue * GV, SectionKind Kind, Mangler & Mang, const TargetMachine & TM) const [override, virtual]
Implements llvm::TargetLoweringObjectFile.
Definition at line 901 of file TargetLoweringObjectFileImpl.cpp.
References llvm::MCObjectFileInfo::BSSSection, Characteristics, llvm::MCObjectFileInfo::DataSection, llvm::MCContext::getCOFFSection(), getCOFFSectionFlags(), getCOFFSectionNameForUniqueGlobal(), getComdatGVForCOFF(), llvm::TargetLoweringObjectFile::getContext(), llvm::TargetMachine::getDataSections(), llvm::TargetMachine::getFunctionSections(), llvm::MCSymbol::getName(), getNameWithPrefix(), getSelectionForCOFF(), llvm::TargetMachine::getSymbol(), llvm::GlobalValue::hasComdat(), llvm::GlobalValue::hasPrivateLinkage(), llvm::COFF::IMAGE_COMDAT_SELECT_NODUPLICATES, llvm::COFF::IMAGE_SCN_LNK_COMDAT, llvm::SectionKind::isBSS(), llvm::SectionKind::isCommon(), llvm::SectionKind::isReadOnly(), llvm::SectionKind::isReadOnlyWithRel(), llvm::SectionKind::isText(), llvm::SectionKind::isThreadLocal(), llvm::MCObjectFileInfo::ReadOnlySection, llvm::MCObjectFileInfo::TextSection, and llvm::MCObjectFileInfo::TLSDataSection.
The documentation for this class was generated from the following files:
TargetLoweringObjectFileImpl.h
TargetLoweringObjectFileImpl.cpp