LLVM: llvm::HandleSDNode Class Reference
llvm::HandleSDNode Class Reference
This class is used to form a handle around another node that is persistent and is updated across invocations of replaceAllUsesWith on its operand.
#include <SelectionDAGNodes.h>
Public Member Functions
HandleSDNode (SDValue X)
~HandleSDNode ()
const SDValue & getValue () const
Detailed Description
This class is used to form a handle around another node that is persistent and is updated across invocations of replaceAllUsesWith on its operand.
This node should be directly created by end-users and not added to the AllNodes list.
Definition at line 1061 of file SelectionDAGNodes.h.
Constructor & Destructor Documentation
llvm::HandleSDNode::HandleSDNode (SDValue X) [inline, explicit]
Definition at line 1064 of file SelectionDAGNodes.h.
References llvm::SDNode::InitOperands().
HandleSDNode::~HandleSDNode ()
Definition at line 6550 of file SelectionDAG.cpp.
References llvm::SDNode::DropOperands().
Member Function Documentation
const SDValue& llvm::HandleSDNode::getValue () const [inline]
Definition at line 1069 of file SelectionDAGNodes.h.
Referenced by llvm::SelectionDAG::RemoveDeadNodes().
The documentation for this class was generated from the following files:
SelectionDAGNodes.h
SelectionDAG.cpp