LLVM: llvm::ARMAsmPrinter Class Reference
llvm::ARMAsmPrinter Class Reference
#include <ARMAsmPrinter.h>
Public Member Functions
ARMAsmPrinter (TargetMachine &TM, std::unique_ptr< MCStreamer > Streamer)
const char * getPassName () const override
getPassName - Return a nice clean name for a pass.
void printOperand (const MachineInstr *MI, int OpNum, raw_ostream &O)
bool PrintAsmOperand (const MachineInstr *MI, unsigned OpNum, unsigned AsmVariant, const char *ExtraCode, raw_ostream &O) override
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
bool PrintAsmMemoryOperand (const MachineInstr *MI, unsigned OpNum, unsigned AsmVariant, const char *ExtraCode, raw_ostream &O) override
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address.
void emitInlineAsmEnd (const MCSubtargetInfo &StartInfo, const MCSubtargetInfo *EndInfo) const override
Let the target do anything it needs to do after emitting inlineasm.
void EmitJumpTableAddrs (const MachineInstr *MI)
void EmitJumpTableInsts (const MachineInstr *MI)
void EmitJumpTableTBInst (const MachineInstr *MI, unsigned OffsetWidth)
void EmitInstruction (const MachineInstr *MI) override
Targets should implement this to emit instructions.
bool runOnMachineFunction (MachineFunction &F) override
runOnMachineFunction - This uses the EmitInstruction() method to print assembly for each instruction.
void EmitConstantPool () override
Print to the current output stream assembly representations of the constants in the constant pool MCP.
void EmitFunctionBodyEnd () override
Targets can override this to emit stuff after the last basic block in the function.
void EmitFunctionEntryLabel () override
EmitFunctionEntryLabel - Emit the label that is the entrypoint for the function.
void EmitStartOfAsmFile (Module &M) override
This virtual method can be overridden by targets that want to emit something at the start of their file.
void EmitEndOfAsmFile (Module &M) override
This virtual method can be overridden by targets that want to emit something at the end of their file.
void EmitXXStructor (const Constant *CV) override
Targets can override this to change how global constants that are part of a C++ static/global constructor list are emitted.
bool lowerOperand (const MachineOperand &MO, MCOperand &MCOp)
unsigned getISAEncoding () override
Get the value for DW_AT_APPLE_isa. Zero if no isa encoding specified.
void EmitMachineConstantPoolValue (MachineConstantPoolValue *MCPV) override
EmitMachineConstantPoolValue - Print a machine constantpool value to the .s file.
Detailed Description
Definition at line 32 of file ARMAsmPrinter.h.
Constructor & Destructor Documentation
ARMAsmPrinter::ARMAsmPrinter (TargetMachine & TM, std::unique_ptr< MCStreamer > Streamer) [explicit]
Definition at line 60 of file ARMAsmPrinter.cpp.
Member Function Documentation
void llvm::ARMAsmPrinter::EmitConstantPool () [inline, override, virtual]
Print to the current output stream assembly representations of the constants in the constant pool MCP.
EmitConstantPool - Print to the current output stream assembly representations of the constants in the constant pool MCP.
This is used to print out constants which have been "spilled to memory" by the code generator.
Reimplemented from llvm::AsmPrinter.
Definition at line 80 of file ARMAsmPrinter.h.
void ARMAsmPrinter::EmitEndOfAsmFile (Module &) [override, virtual]
This virtual method can be overridden by targets that want to emit something at the end of their file.
Reimplemented from llvm::AsmPrinter.
Definition at line 475 of file ARMAsmPrinter.cpp.
References llvm::AsmPrinter::EmitAlignment(), emitNonLazySymbolPointer(), llvm::MachineModuleInfoMachO::GetGVStubList(), llvm::MachineModuleInfoMachO::GetHiddenGVStubList(), llvm::MCObjectFileInfo::getNonLazySymbolPointerSection(), llvm::MachineModuleInfo::getObjFileInfo(), llvm::AsmPrinter::getObjFileLowering(), llvm::TargetMachine::getTargetTriple(), llvm::Triple::isOSBinFormatMachO(), llvm::MCAF_SubsectionsViaSymbols, llvm::AsmPrinter::MMI, llvm::AsmPrinter::OutStreamer, and llvm::AsmPrinter::TM.
void ARMAsmPrinter::EmitFunctionBodyEnd () [override, virtual]
Targets can override this to emit stuff after the last basic block in the function.
Reimplemented from llvm::AsmPrinter.
Definition at line 65 of file ARMAsmPrinter.cpp.
References llvm::MCDR_DataRegionEnd, and llvm::AsmPrinter::OutStreamer.
void ARMAsmPrinter::EmitFunctionEntryLabel () [override, virtual]
EmitFunctionEntryLabel - Emit the label that is the entrypoint for the function.
This can be overridden by targets as required to do custom stuff.
Reimplemented from llvm::AsmPrinter.
Definition at line 74 of file ARMAsmPrinter.cpp.
References llvm::AsmPrinter::CurrentFnSym, llvm::ARMFunctionInfo::isThumbFunction(), llvm::MCAF_Code16, and llvm::AsmPrinter::OutStreamer.
void ARMAsmPrinter::emitInlineAsmEnd (const MCSubtargetInfo & StartInfo, const MCSubtargetInfo * EndInfo) const [override, virtual]
Let the target do anything it needs to do after emitting inlineasm.
This callback can be used restore the original mode in case the inlineasm contains directives to switch modes. StartInfo - the original subtarget info before inline asm EndInfo - the final subtarget info after parsing the inline asm, or NULL if the value is unknown.
Reimplemented from llvm::AsmPrinter.
Definition at line 421 of file ARMAsmPrinter.cpp.
References isThumb(), llvm::MCAF_Code16, llvm::MCAF_Code32, and llvm::AsmPrinter::OutStreamer.
void ARMAsmPrinter::EmitInstruction (const MachineInstr *) [override, virtual]
Targets should implement this to emit instructions.
CONSTPOOL_ENTRY - This instruction represents a floating constant pool in the function. The first operand is the ID# for this instruction, the second is the index into the MachineConstantPool that this is, the third is the size in bytes of this constant pool entry. The required alignment is specified on the basic block holding this MI.
Reimplemented from llvm::AsmPrinter.
Definition at line 1194 of file ARMAsmPrinter.cpp.
References llvm::MCInstBuilder::addImm(), llvm::MCInst::addOperand(), llvm::MCInstBuilder::addReg(), llvm::ARMCC::AL, llvm::BX, llvm::MachineConstantPoolEntry::ConstVal, llvm::convertAddSubFlagsOpcode(), llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCOperand::createExpr(), llvm::MCOperand::createImm(), llvm::ARMMCExpr::createLower16(), llvm::MCOperand::createReg(), llvm::MCBinaryExpr::createSub(), llvm::MCContext::createTempSymbol(), llvm::ARMMCExpr::createUpper16(), llvm::TargetOpcode::DBG_VALUE, llvm::AsmPrinter::EmitGlobalConstant(), EmitJumpTableAddrs(), EmitJumpTableInsts(), EmitJumpTableTBInst(), EmitMachineConstantPoolValue(), llvm::AsmPrinter::EmitToStreamer(), llvm::MachineInstr::FrameSetup, llvm::MachineConstantPool::getConstants(), llvm::AsmPrinter::GetCPISymbol(), llvm::TargetMachine::getDataLayout(), llvm::MachineInstr::getFlag(), llvm::AsmPrinter::getFunctionNumber(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), getPICLabel(), llvm::DataLayout::getPrivateGlobalPrefix(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getTargetFlags(), llvm::ARMSubtarget::hasV5TOps(), llvm::MachineConstantPoolEntry::isMachineConstantPoolEntry(), llvm::ARMSubtarget::isTargetEHABICompatible(), llvm::ARMSubtarget::isTargetMachO(), llvm::Label, llvm_unreachable, llvm::LowerARMMachineInstrToMCInst(), llvm::MachineConstantPoolEntry::MachineCPVal, llvm::MCDR_DataRegion, llvm::MCDR_DataRegionEnd, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::MCInst::setOpcode(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::SP, llvm::AsmPrinter::TM, llvm::ISD::TRAP, and llvm::MachineConstantPoolEntry::Val.
void ARMAsmPrinter::EmitJumpTableAddrs (const MachineInstr * MI)
Definition at line 929 of file ARMAsmPrinter.cpp.
References llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCBinaryExpr::createSub(), llvm::AsmPrinter::EmitAlignment(), llvm::MachineOperand::getIndex(), llvm::MachineFunction::getJumpTableInfo(), llvm::MachineJumpTableInfo::getJumpTables(), llvm::MachineInstr::getOperand(), llvm::TargetMachine::getRelocationModel(), llvm::MachineBasicBlock::getSymbol(), llvm::ARMFunctionInfo::isThumbFunction(), llvm::HexagonISD::JT, llvm::MCDR_DataRegionEnd, llvm::MCDR_DataRegionJT32, llvm::AsmPrinter::MF, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, llvm::Reloc::PIC_, and llvm::AsmPrinter::TM.
Referenced by EmitInstruction().
void ARMAsmPrinter::EmitJumpTableInsts (const MachineInstr * MI)
Definition at line 976 of file ARMAsmPrinter.cpp.
References llvm::ARMCC::AL, llvm::MCSymbolRefExpr::create(), llvm::AsmPrinter::EmitToStreamer(), llvm::MachineOperand::getIndex(), llvm::MachineFunction::getJumpTableInfo(), llvm::MachineJumpTableInfo::getJumpTables(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getSymbol(), llvm::HexagonISD::JT, llvm::AsmPrinter::MF, llvm::AsmPrinter::OutContext, and llvm::AsmPrinter::OutStreamer.
Referenced by EmitInstruction().
void ARMAsmPrinter::EmitJumpTableTBInst (const MachineInstr * MI, unsigned OffsetWidth)
Definition at line 1000 of file ARMAsmPrinter.cpp.
References llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCBinaryExpr::createDiv(), llvm::MCBinaryExpr::createSub(), llvm::AsmPrinter::EmitAlignment(), llvm::AsmPrinter::GetCPISymbol(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineFunction::getJumpTableInfo(), llvm::MachineJumpTableInfo::getJumpTables(), llvm::MachineInstr::getOperand(), llvm::HexagonISD::JT, llvm::MCDR_DataRegionEnd, llvm::MCDR_DataRegionJT16, llvm::MCDR_DataRegionJT8, llvm::AsmPrinter::MF, llvm::AsmPrinter::OutContext, and llvm::AsmPrinter::OutStreamer.
Referenced by EmitInstruction().
void ARMAsmPrinter::EmitMachineConstantPoolValue (MachineConstantPoolValue * MCPV) [override, virtual]
EmitMachineConstantPoolValue - Print a machine constantpool value to the .s file.
Reimplemented from llvm::AsmPrinter.
Definition at line 871 of file ARMAsmPrinter.cpp.
References llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCBinaryExpr::createSub(), llvm::MCContext::createTempSymbol(), llvm::AsmPrinter::GetBlockAddressSymbol(), llvm::AsmPrinter::getCurExceptionSym(), llvm::TargetMachine::getDataLayout(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::AsmPrinter::getFunctionNumber(), getGV(), llvm::ARMConstantPoolValue::getLabelId(), llvm::ARMConstantPoolValue::getModifier(), getModifierVariantKind(), llvm::ARMConstantPoolValue::getPCAdjustment(), getPICLabel(), llvm::DataLayout::getPrivateGlobalPrefix(), llvm::AsmPrinter::getSymbol(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineConstantPoolValue::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::ARMConstantPoolValue::isBlockAddress(), llvm::ARMConstantPoolValue::isExtSymbol(), llvm::ARMConstantPoolValue::isGlobalValue(), llvm::ARMConstantPoolValue::isLSDA(), llvm::ARMConstantPoolValue::isMachineBasicBlock(), llvm::ARMSubtarget::isTargetMachO(), llvm::ARMII::MO_NONLAZY, llvm::ARMConstantPoolValue::mustAddCurrentAddress(), llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, and llvm::AsmPrinter::TM.
Referenced by EmitInstruction().
void ARMAsmPrinter::EmitStartOfAsmFile (Module &) [override, virtual]
This virtual method can be overridden by targets that want to emit something at the start of their file.
Reimplemented from llvm::AsmPrinter.
Definition at line 431 of file ARMAsmPrinter.cpp.
References llvm::Triple::ARMSubArch_v6m, llvm::Triple::ARMSubArch_v7m, llvm::Triple::getArch(), llvm::Module::getModuleInlineAsm(), llvm::Triple::getSubArch(), llvm::TargetMachine::getTargetTriple(), llvm::Triple::isOSBinFormatELF(), isThumb(), llvm::MCAF_Code16, llvm::MCAF_SyntaxUnified, llvm::AsmPrinter::OutStreamer, llvm::Triple::thumb, llvm::Triple::thumbeb, and llvm::AsmPrinter::TM.
void ARMAsmPrinter::EmitXXStructor (const Constant * CV) [override, virtual]
Targets can override this to change how global constants that are part of a C++ static/global constructor list are emitted.
Reimplemented from llvm::AsmPrinter.
Definition at line 83 of file ARMAsmPrinter.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::dyn_cast(), llvm::TargetMachine::getDataLayout(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::ARMSubtarget::isTargetELF(), llvm::ARMII::MO_NO_FLAG, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, llvm::Constant::stripPointerCasts(), llvm::AsmPrinter::TM, llvm::MCSymbolRefExpr::VK_ARM_TARGET1, and llvm::MCSymbolRefExpr::VK_None.
unsigned llvm::ARMAsmPrinter::getISAEncoding () [inline, override, virtual]
Get the value for DW_AT_APPLE_isa. Zero if no isa encoding specified.
Reimplemented from llvm::AsmPrinter.
Definition at line 106 of file ARMAsmPrinter.h.
References llvm::Triple::ARMSubArch_v6m, llvm::Triple::ARMSubArch_v7m, llvm::ARM::DW_ISA_ARM_arm, llvm::ARM::DW_ISA_ARM_thumb, llvm::Triple::getArch(), llvm::Triple::getSubArch(), llvm::TargetMachine::getTargetTriple(), llvm::Triple::isOSBinFormatMachO(), isThumb(), llvm::Triple::thumb, and llvm::Triple::thumbeb.
const char* llvm::ARMAsmPrinter::getPassName () const [inline, override, virtual]
getPassName - Return a nice clean name for a pass.
This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 58 of file ARMAsmPrinter.h.
bool ARMAsmPrinter::lowerOperand (const MachineOperand & MO, MCOperand & MCOp)
Definition at line 68 of file ARMMCInstLower.cpp.
References llvm::APFloat::convert(), llvm::APFloat::convertToDouble(), llvm::MCSymbolRefExpr::create(), llvm::MCOperand::createExpr(), llvm::MCOperand::createFPImm(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MachineOperand::getBlockAddress(), llvm::AsmPrinter::GetBlockAddressSymbol(), llvm::AsmPrinter::GetCPISymbol(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::MachineOperand::getFPImm(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::AsmPrinter::GetJTISymbol(), llvm::MachineOperand::getMBB(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getSymbolName(), llvm::MachineOperand::getTargetFlags(), llvm::MachineOperand::getType(), llvm::ConstantFP::getValueAPF(), llvm::APFloat::IEEEdouble, llvm::MachineOperand::isImplicit(), llvm_unreachable, llvm::MachineOperand::MO_BlockAddress, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_FPImmediate, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_JumpTableIndex, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_Register, llvm::MachineOperand::MO_RegisterMask, llvm::AsmPrinter::OutContext, and llvm::APFloat::rmTowardZero.
Referenced by llvm::LowerARMMachineInstrToMCInst().
bool ARMAsmPrinter::PrintAsmMemoryOperand (const MachineInstr * MI, unsigned OpNo, unsigned AsmVariant, const char * ExtraCode, raw_ostream & OS) [override, virtual]
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address.
Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Reimplemented from llvm::AsmPrinter.
Definition at line 392 of file ARMAsmPrinter.cpp.
References llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::ARMInstPrinter::getRegisterName(), and llvm::MachineOperand::isReg().
bool ARMAsmPrinter::PrintAsmOperand (const MachineInstr * MI, unsigned OpNo, unsigned AsmVariant, const char * ExtraCode, raw_ostream & O) [override, virtual]
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
PrintAsmOperand - Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Targets should override this to format as appropriate.
Reimplemented from llvm::AsmPrinter.
Definition at line 217 of file ARMAsmPrinter.cpp.
References contains(), llvm::MachineOperand::getImm(), llvm::InlineAsm::getNumOperandRegisters(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::ARMInstPrinter::getRegisterName(), llvm::MCRegisterInfo::getSubReg(), llvm::MachineFunction::getSubtarget(), llvm::InlineAsm::hasRegClassConstraint(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isReg(), llvm::InlineAsm::isUseOperandTiedToDef(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::AsmPrinter::MF, llvm::InlineAsm::MIOp_FirstOperand, and printOperand().
void ARMAsmPrinter::printOperand (const MachineInstr * MI, int OpNum, raw_ostream & O)
Definition at line 146 of file ARMAsmPrinter.cpp.
References contains(), llvm::AsmPrinter::GetCPISymbol(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineOperand::getMBB(), llvm::MachineOperand::getOffset(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::ARMInstPrinter::getRegisterName(), llvm::MachineOperand::getSubReg(), llvm::MCRegisterInfo::getSubReg(), llvm::MachineFunction::getSubtarget(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getTargetFlags(), llvm::MachineOperand::getType(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm_unreachable, llvm::AsmPrinter::MAI, llvm::AsmPrinter::MF, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_GlobalAddress, llvm::ARMII::MO_HI16, llvm::MachineOperand::MO_Immediate, llvm::ARMII::MO_LO16, llvm::MachineOperand::MO_MachineBasicBlock, llvm::ARMII::MO_PLT, llvm::MachineOperand::MO_Register, llvm::Pass::print(), llvm::MCSymbol::print(), and llvm::AsmPrinter::printOffset().
Referenced by PrintAsmOperand().
bool ARMAsmPrinter::runOnMachineFunction (MachineFunction & F) [override, virtual]
runOnMachineFunction - This uses the EmitInstruction() method to print assembly for each instruction.
Reimplemented from llvm::AsmPrinter.
Definition at line 103 of file ARMAsmPrinter.cpp.
References llvm::ARMCC::AL, llvm::SmallVectorImpl< T >::clear(), llvm::AsmPrinter::CurrentFnSym, llvm::AsmPrinter::EmitAlignment(), llvm::AsmPrinter::EmitFunctionBody(), llvm::AsmPrinter::EmitToStreamer(), llvm::SmallVectorBase::empty(), llvm::MachineFunction::getConstantPool(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getSubtarget(), llvm::GlobalValue::hasInternalLinkage(), llvm::COFF::IMAGE_SYM_CLASS_EXTERNAL, llvm::COFF::IMAGE_SYM_CLASS_STATIC, llvm::COFF::IMAGE_SYM_DTYPE_FUNCTION, llvm::ARMSubtarget::isTargetCOFF(), llvm::MCAF_Code16, llvm::AsmPrinter::OutStreamer, llvm::COFF::SCT_COMPLEX_TYPE_SHIFT, llvm::AsmPrinter::SetupMachineFunction(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
The documentation for this class was generated from the following files:
ARMAsmPrinter.h
ARMAsmPrinter.cpp
ARMMCInstLower.cpp