LLVM: llvm::XCoreTargetObjectFile Class Reference
llvm::XCoreTargetObjectFile Class Reference
#include <XCoreTargetObjectFile.h>
Public Member Functions
void Initialize (MCContext &Ctx, const TargetMachine &TM) override
This method must be called before any actual lowering is done.
MCSection * getExplicitSectionGlobal (const GlobalValue *GV, SectionKind Kind, Mangler &Mang, const TargetMachine &TM) const override
Targets should implement this method to assign a section to globals with an explicit section specfied.
MCSection * SelectSectionForGlobal (const GlobalValue *GV, SectionKind Kind, Mangler &Mang, const TargetMachine &TM) const override
MCSection * getSectionForConstant (SectionKind Kind, const Constant *C) const override
Given a constant with the SectionKind, return a section that it should be placed in.
Detailed Description
Definition at line 19 of file XCoreTargetObjectFile.h.
Member Function Documentation
MCSection * XCoreTargetObjectFile::getExplicitSectionGlobal (const GlobalValue * GV, SectionKind Kind, Mangler & Mang, const TargetMachine & TM) const [override, virtual]
Targets should implement this method to assign a section to globals with an explicit section specfied.
The implementation of this method can assume that GV->hasSection() is true.
Reimplemented from llvm::TargetLoweringObjectFileELF.
Definition at line 99 of file XCoreTargetObjectFile.cpp.
References llvm::TargetLoweringObjectFile::getContext(), llvm::MCContext::getELFSection(), llvm::GlobalValue::getSection(), getXCoreSectionFlags(), getXCoreSectionType(), llvm::SectionKind::isReadOnly(), llvm::report_fatal_error(), and llvm::StringRef::startswith().
MCSection * XCoreTargetObjectFile::getSectionForConstant (SectionKind Kind, const Constant * C) const [override, virtual]
Given a constant with the SectionKind, return a section that it should be placed in.
Given a mergeable constant with the specified size and relocation information, return a section that it should be placed in.
Reimplemented from llvm::TargetLoweringObjectFileELF.
Definition at line 146 of file XCoreTargetObjectFile.cpp.
References llvm::SectionKind::isMergeableConst16(), llvm::SectionKind::isMergeableConst4(), llvm::SectionKind::isMergeableConst8(), llvm::SectionKind::isReadOnly(), llvm::SectionKind::isReadOnlyWithRel(), llvm::MCObjectFileInfo::MergeableConst16Section, llvm::MCObjectFileInfo::MergeableConst4Section, llvm::MCObjectFileInfo::MergeableConst8Section, and llvm::MCObjectFileInfo::ReadOnlySection.
void XCoreTargetObjectFile::Initialize (MCContext & ctx, const TargetMachine & TM) [override, virtual]
This method must be called before any actual lowering is done.
Initialize - this method must be called before any actual lowering is done.
This specifies the current context for codegen, and gives the lowering implementations a chance to set up their default sections.
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 21 of file XCoreTargetObjectFile.cpp.
References llvm::MCObjectFileInfo::BSSSection, llvm::MCObjectFileInfo::CStringSection, llvm::MCObjectFileInfo::DataRelROSection, llvm::MCObjectFileInfo::DataSection, llvm::MCContext::getELFSection(), llvm::MCObjectFileInfo::MergeableConst16Section, llvm::MCObjectFileInfo::MergeableConst4Section, llvm::MCObjectFileInfo::MergeableConst8Section, llvm::MCObjectFileInfo::ReadOnlySection, llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_MERGE, llvm::ELF::SHF_STRINGS, llvm::ELF::SHF_WRITE, llvm::ELF::SHT_NOBITS, llvm::ELF::SHT_PROGBITS, llvm::ELF::XCORE_SHF_CP_SECTION, and llvm::ELF::XCORE_SHF_DP_SECTION.
MCSection * XCoreTargetObjectFile::SelectSectionForGlobal (const GlobalValue * GV, SectionKind Kind, Mangler & Mang, const TargetMachine & TM) const [override, virtual]
Reimplemented from llvm::TargetLoweringObjectFileELF.
Definition at line 112 of file XCoreTargetObjectFile.cpp.
References llvm::MCObjectFileInfo::BSSSection, llvm::CodeModelLargeSize, llvm::MCObjectFileInfo::CStringSection, llvm::MCObjectFileInfo::DataRelROSection, llvm::MCObjectFileInfo::DataSection, llvm::TargetMachine::getCodeModel(), llvm::TargetMachine::getDataLayout(), llvm::GlobalValue::getLinkage(), llvm::Type::getPointerElementType(), llvm::GlobalValue::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::SectionKind::isBSS(), llvm::SectionKind::isCommon(), llvm::SectionKind::isDataRel(), llvm::GlobalValue::isLocalLinkage(), llvm::SectionKind::isMergeable1ByteCString(), llvm::SectionKind::isMergeableConst16(), llvm::SectionKind::isMergeableConst4(), llvm::SectionKind::isMergeableConst8(), llvm::SectionKind::isReadOnly(), llvm::SectionKind::isReadOnlyWithRel(), llvm::Type::isSized(), llvm::SectionKind::isText(), llvm::SectionKind::isThreadLocal(), llvm::MCObjectFileInfo::MergeableConst16Section, llvm::MCObjectFileInfo::MergeableConst4Section, llvm::MCObjectFileInfo::MergeableConst8Section, llvm::MCObjectFileInfo::ReadOnlySection, llvm::report_fatal_error(), llvm::CodeModel::Small, and llvm::MCObjectFileInfo::TextSection.
The documentation for this class was generated from the following files:
XCoreTargetObjectFile.h
XCoreTargetObjectFile.cpp