LLVM: llvm::AddrSpaceCastInst Class Reference
llvm::AddrSpaceCastInst Class Reference
This class represents a conversion between pointers from one address space to another.
#include <Instructions.h>
Public Member Functions
AddrSpaceCastInst (Value *S, Type *Ty, const Twine &NameStr="", Instruction *InsertBefore=nullptr)
Constructor with insert-before-instruction semantics.
AddrSpaceCastInst (Value *S, Type *Ty, const Twine &NameStr, BasicBlock *InsertAtEnd)
Constructor with insert-at-end-of-block semantics.
Static Public Member Functions
static bool classof (const Instruction *I)
Methods for support type inquiry through isa, cast, and dyn_cast:
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
AddrSpaceCastInst * clone_impl () const override
Clone an identical AddrSpaceCastInst.
Detailed Description
This class represents a conversion between pointers from one address space to another.
Definition at line 3955 of file Instructions.h.
Constructor & Destructor Documentation
AddrSpaceCastInst::AddrSpaceCastInst (Value * S, Type * Ty, const Twine & NameStr = "", Instruction * InsertBefore = nullptr)
Constructor with insert-before-instruction semantics.
Parameters:
S The value to be casted
Ty The type to casted to
NameStr A name for the new instruction
InsertBefore Where to insert the new instruction
Definition at line 2953 of file Instructions.cpp.
References llvm::CastInst::castIsValid(), and llvm::CastInst::getOpcode().
Referenced by clone_impl().
AddrSpaceCastInst::AddrSpaceCastInst (Value * S, Type * Ty, const Twine & NameStr, BasicBlock * InsertAtEnd)
Constructor with insert-at-end-of-block semantics.
Parameters:
S The value to be casted
Ty The type to casted to
NameStr A name for the new instruction
InsertAtEnd The block to insert the instruction into
Definition at line 2959 of file Instructions.cpp.
References llvm::CastInst::castIsValid(), and llvm::CastInst::getOpcode().
Member Function Documentation
static bool llvm::AddrSpaceCastInst::classof (const Instruction * I) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::CastInst.
Definition at line 3978 of file Instructions.h.
References llvm::AddrSpaceCast, and llvm::Instruction::getOpcode().
Referenced by classof().
static bool llvm::AddrSpaceCastInst::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::CastInst.
Definition at line 3981 of file Instructions.h.
References classof().
AddrSpaceCastInst * AddrSpaceCastInst::clone_impl () const [override, protected, virtual]
Clone an identical AddrSpaceCastInst.
Implements llvm::Instruction.
Definition at line 3569 of file Instructions.cpp.
References AddrSpaceCastInst(), llvm::User::getOperand(), and llvm::Value::getType().
The documentation for this class was generated from the following files:
Instructions.h
Instructions.cpp