LLVM: llvm::MemoryDepChecker Class Reference
llvm::MemoryDepChecker Class Reference
Checks memory dependences among accesses to the same underlying object to determine whether there vectorization is legal or not (and at which vectorization factor).
#include <LoopAccessAnalysis.h>
Classes
struct Dependence
Dependece between memory access instructions.
Public Types
typedef PointerIntPair< Value
*, 1, bool > MemAccessInfo
typedef SmallPtrSet
< MemAccessInfo, 8 > MemAccessInfoSet
typedef EquivalenceClasses
< MemAccessInfo > DepCandidates
Set of potential dependent memory accesses.
Public Member Functions
MemoryDepChecker (ScalarEvolution *Se, const Loop *L)
void addAccess (StoreInst *SI)
Register the location (instructions are given increasing numbers) of a write access.
void addAccess (LoadInst *LI)
Register the location (instructions are given increasing numbers) of a write access.
bool areDepsSafe (DepCandidates &AccessSets, MemAccessInfoSet &CheckDeps, const ValueToValueMap &Strides)
Check whether the dependencies between the accesses are safe.
bool isSafeForVectorization () const
No memory dependence was encountered that would inhibit vectorization.
unsigned getMaxSafeDepDistBytes ()
The maximum number of bytes of a vector register we can vectorize the accesses safely with.
bool shouldRetryWithRuntimeCheck ()
In same cases when the dependency check fails we can still vectorize the loop with a dynamic array access check.
const SmallVectorImpl
< Dependence > * getInterestingDependences () const
Returns the interesting dependences.
void clearInterestingDependences ()
const SmallVectorImpl
< Instruction * > & getMemoryInstructions () const
The vector of memory access instructions.
SmallVector< Instruction *, 4 > getInstructionsForAccess (Value *Ptr, bool isWrite) const
Find the set of instructions that read or write via Ptr.
Detailed Description
Checks memory dependences among accesses to the same underlying object to determine whether there vectorization is legal or not (and at which vectorization factor).
Note: This class will compute a conservative dependence for access to different underlying pointers. Clients, such as the loop vectorizer, will sometimes deal these potential dependencies by emitting runtime checks.
We use the ScalarEvolution framework to symbolically evalutate access functions pairs. Since we currently don't restructure the loop we can rely on the program order of memory accesses to determine their safety. At the moment we will only deem accesses as safe for: A negative constant distance assuming program order.
Safe: tmp = a[i + 1]; OR a[i + 1] = x; a[i] = tmp; y = a[i];
The latter case is safe because later checks guarantuee that there can't be a cycle through a phi node (that is, we check that "x" and "y" is not the same variable: a header phi can only be an induction or a reduction, a reduction can't have a memory sink, an induction can't have a memory source). This is important and must not be violated (or we have to resort to checking for cycles through memory).
A positive constant distance assuming program order that is bigger than the biggest memory access.
tmp = a[i] OR b[i] = x a[i+2] = tmp y = b[i+2];
Safe distance: 2 x sizeof(a[0]), and 2 x sizeof(b[0]), respectively.
Zero distances and all accesses have the same size.
Definition at line 123 of file LoopAccessAnalysis.h.
Member Typedef Documentation
typedef EquivalenceClasses<MemAccessInfo> llvm::MemoryDepChecker::DepCandidates
Set of potential dependent memory accesses.
Definition at line 128 of file LoopAccessAnalysis.h.
typedef PointerIntPair<Value *, 1, bool> llvm::MemoryDepChecker::MemAccessInfo
Definition at line 125 of file LoopAccessAnalysis.h.
typedef SmallPtrSet<MemAccessInfo, 8> llvm::MemoryDepChecker::MemAccessInfoSet
Definition at line 126 of file LoopAccessAnalysis.h.
Constructor & Destructor Documentation
llvm::MemoryDepChecker::MemoryDepChecker (ScalarEvolution * Se, const Loop * L) [inline]
Definition at line 180 of file LoopAccessAnalysis.h.
Member Function Documentation
void llvm::MemoryDepChecker::addAccess (StoreInst * SI) [inline]
Register the location (instructions are given increasing numbers) of a write access.
Definition at line 187 of file LoopAccessAnalysis.h.
References llvm::StoreInst::getPointerOperand(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
void llvm::MemoryDepChecker::addAccess (LoadInst * LI) [inline]
Register the location (instructions are given increasing numbers) of a write access.
Definition at line 196 of file LoopAccessAnalysis.h.
References llvm::LoadInst::getPointerOperand(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
bool MemoryDepChecker::areDepsSafe (DepCandidates & AccessSets, MemAccessInfoSet & CheckDeps, const ValueToValueMap & Strides)
Check whether the dependencies between the accesses are safe.
Only checks sets with elements in CheckDeps.
Definition at line 897 of file LoopAccessAnalysis.cpp.
References llvm::sys::path::begin(), llvm::SmallPtrSetImpl< PtrType >::begin(), llvm::dbgs(), DEBUG, llvm::SmallPtrSetImplBase::empty(), llvm::sys::path::end(), llvm::SmallPtrSetImpl< PtrType >::erase(), llvm::EquivalenceClasses< ElemTy >::findValue(), llvm::EquivalenceClasses< ElemTy >::getLeaderValue(), I, MaxInterestingDependence, llvm::EquivalenceClasses< ElemTy >::member_begin(), llvm::EquivalenceClasses< ElemTy >::member_end(), and std::swap().
void llvm::MemoryDepChecker::clearInterestingDependences () [inline]
Definition at line 228 of file LoopAccessAnalysis.h.
References llvm::SmallVectorImpl< T >::clear().
SmallVector< Instruction *, 4 > MemoryDepChecker::getInstructionsForAccess (Value * Ptr, bool isWrite) const
Find the set of instructions that read or write via Ptr.
Definition at line 964 of file LoopAccessAnalysis.cpp.
Referenced by llvm::LoopAccessInfo::getInstructionsForAccess().
const SmallVectorImpl<Dependence>* llvm::MemoryDepChecker::getInterestingDependences () const [inline]
Returns the interesting dependences.
If null is returned we exceeded the MaxInterestingDependence threshold and this information is not available.
Definition at line 224 of file LoopAccessAnalysis.h.
Referenced by llvm::LoopAccessInfo::print().
unsigned llvm::MemoryDepChecker::getMaxSafeDepDistBytes () [inline]
The maximum number of bytes of a vector register we can vectorize the accesses safely with.
Definition at line 215 of file LoopAccessAnalysis.h.
const SmallVectorImpl<Instruction *>& llvm::MemoryDepChecker::getMemoryInstructions () const [inline]
The vector of memory access instructions.
The indices are used as instruction identifiers in the Dependence class.
Definition at line 232 of file LoopAccessAnalysis.h.
Referenced by llvm::LoopAccessInfo::print().
bool llvm::MemoryDepChecker::isSafeForVectorization () const [inline]
No memory dependence was encountered that would inhibit vectorization.
Definition at line 211 of file LoopAccessAnalysis.h.
bool llvm::MemoryDepChecker::shouldRetryWithRuntimeCheck () [inline]
In same cases when the dependency check fails we can still vectorize the loop with a dynamic array access check.
Definition at line 219 of file LoopAccessAnalysis.h.
The documentation for this class was generated from the following files:
LoopAccessAnalysis.h
LoopAccessAnalysis.cpp