LLVM: llvm::NewArchiveIterator Class Reference
llvm::NewArchiveIterator Class Reference
#include <ArchiveWriter.h>
Public Member Functions
NewArchiveIterator (object::Archive::child_iterator I, StringRef Name)
NewArchiveIterator (StringRef I, StringRef Name)
NewArchiveIterator ()
bool isNewMember () const
StringRef getName () const
object::Archive::child_iterator getOld () const
StringRef getNew () const
llvm::ErrorOr< int > getFD (sys::fs::file_status &NewStatus) const
const sys::fs::file_status & getStatus () const
Detailed Description
Definition at line 23 of file ArchiveWriter.h.
Constructor & Destructor Documentation
NewArchiveIterator::NewArchiveIterator (object::Archive::child_iterator I, StringRef Name)
Definition at line 39 of file ArchiveWriter.cpp.
NewArchiveIterator::NewArchiveIterator (StringRef I, StringRef Name)
Definition at line 43 of file ArchiveWriter.cpp.
NewArchiveIterator::NewArchiveIterator ()
Definition at line 37 of file ArchiveWriter.cpp.
Member Function Documentation
llvm::ErrorOr< int > NewArchiveIterator::getFD (sys::fs::file_status & NewStatus) const
Definition at line 61 of file ArchiveWriter.cpp.
References llvm::sys::fs::directory_file, llvm::is_a_directory, llvm::make_error_code(), llvm::sys::fs::openFileForRead(), llvm::sys::fs::status(), and llvm::sys::fs::file_status::type().
Referenced by llvm::writeArchive().
StringRef NewArchiveIterator::getName () const
Definition at line 46 of file ArchiveWriter.cpp.
StringRef NewArchiveIterator::getNew () const
Definition at line 55 of file ArchiveWriter.cpp.
Referenced by llvm::writeArchive().
object::Archive::child_iterator NewArchiveIterator::getOld () const
Definition at line 50 of file ArchiveWriter.cpp.
Referenced by llvm::writeArchive().
const sys::fs::file_status& llvm::NewArchiveIterator::getStatus () const
bool NewArchiveIterator::isNewMember () const
Definition at line 48 of file ArchiveWriter.cpp.
Referenced by llvm::writeArchive().
The documentation for this class was generated from the following files:
ArchiveWriter.h
ArchiveWriter.cpp