LLVM: llvm::TargetSelectionDAGInfo Class Reference
llvm::TargetSelectionDAGInfo Class Reference
TargetSelectionDAGInfo - Targets can subclass this to parameterize the SelectionDAG lowering and instruction selection process.
#include <TargetSelectionDAGInfo.h>
Public Member Functions
TargetSelectionDAGInfo (const DataLayout *DL)
virtual ~TargetSelectionDAGInfo ()
virtual SDValue EmitTargetCodeForMemcpy (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const
EmitTargetCodeForMemcpy - Emit target-specific code that performs a memcpy.
virtual SDValue EmitTargetCodeForMemmove (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const
EmitTargetCodeForMemmove - Emit target-specific code that performs a memmove.
virtual SDValue EmitTargetCodeForMemset (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, MachinePointerInfo DstPtrInfo) const
EmitTargetCodeForMemset - Emit target-specific code that performs a memset.
virtual std::pair< SDValue,
SDValue > EmitTargetCodeForMemcmp (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const
EmitTargetCodeForMemcmp - Emit target-specific code that performs a memcmp, in cases where that is faster than a libcall.
virtual std::pair< SDValue,
SDValue > EmitTargetCodeForMemchr (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Src, SDValue Char, SDValue Length, MachinePointerInfo SrcPtrInfo) const
EmitTargetCodeForMemchr - Emit target-specific code that performs a memchr, in cases where that is faster than a libcall.
virtual std::pair< SDValue,
SDValue > EmitTargetCodeForStrcpy (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Dest, SDValue Src, MachinePointerInfo DestPtrInfo, MachinePointerInfo SrcPtrInfo, bool isStpcpy) const
EmitTargetCodeForStrcpy - Emit target-specific code that performs a strcpy or stpcpy, in cases where that is faster than a libcall.
virtual std::pair< SDValue,
SDValue > EmitTargetCodeForStrcmp (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const
EmitTargetCodeForStrcmp - Emit target-specific code that performs a strcmp, in cases where that is faster than a libcall.
virtual std::pair< SDValue,
SDValue > EmitTargetCodeForStrlen (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Src, MachinePointerInfo SrcPtrInfo) const
virtual std::pair< SDValue,
SDValue > EmitTargetCodeForStrnlen (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Src, SDValue MaxLength, MachinePointerInfo SrcPtrInfo) const
Protected Member Functions
const DataLayout * getDataLayout () const
Detailed Description
TargetSelectionDAGInfo - Targets can subclass this to parameterize the SelectionDAG lowering and instruction selection process.
Definition at line 29 of file TargetSelectionDAGInfo.h.
Constructor & Destructor Documentation
TargetSelectionDAGInfo::TargetSelectionDAGInfo (const DataLayout * DL) [explicit]
Definition at line 18 of file TargetSelectionDAGInfo.cpp.
TargetSelectionDAGInfo::~TargetSelectionDAGInfo () [virtual]
Definition at line 22 of file TargetSelectionDAGInfo.cpp.
Member Function Documentation
virtual std::pair<SDValue, SDValue> llvm::TargetSelectionDAGInfo::EmitTargetCodeForMemchr (SelectionDAG & DAG, SDLoc dl, SDValue Chain, SDValue Src, SDValue Char, SDValue Length, MachinePointerInfo SrcPtrInfo) const [inline, virtual]
EmitTargetCodeForMemchr - Emit target-specific code that performs a memchr, in cases where that is faster than a libcall.
The first returned SDValue is the result of the memchr and the second is the chain. Both SDValues can be null if a normal libcall should be used.
Reimplemented in llvm::SystemZSelectionDAGInfo.
Definition at line 117 of file TargetSelectionDAGInfo.h.
virtual std::pair<SDValue, SDValue> llvm::TargetSelectionDAGInfo::EmitTargetCodeForMemcmp (SelectionDAG & DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const [inline, virtual]
EmitTargetCodeForMemcmp - Emit target-specific code that performs a memcmp, in cases where that is faster than a libcall.
The first returned SDValue is the result of the memcmp and the second is the chain. Both SDValues can be null if a normal libcall should be used.
Reimplemented in llvm::SystemZSelectionDAGInfo.
Definition at line 103 of file TargetSelectionDAGInfo.h.
virtual SDValue llvm::TargetSelectionDAGInfo::EmitTargetCodeForMemcpy (SelectionDAG & DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const [inline, virtual]
EmitTargetCodeForMemcpy - Emit target-specific code that performs a memcpy.
This can be used by targets to provide code sequences for cases that don't fit the target's parameters for simple loads/stores and can be more efficient than using a library call. This function can return a null SDValue if the target declines to use custom code and a different lowering strategy should be used.
If AlwaysInline is true, the size is constant and the target should not emit any calls and is strongly encouraged to attempt to emit inline code even if it is beyond the usual threshold because this intrinsic is being expanded in a place where calls are not feasible (e.g. within the prologue for another call). If the target chooses to decline an AlwaysInline request here, legalize will resort to using simple loads and stores.
Reimplemented in llvm::ARMSelectionDAGInfo, llvm::X86SelectionDAGInfo, llvm::XCoreSelectionDAGInfo, llvm::SystemZSelectionDAGInfo, and llvm::HexagonSelectionDAGInfo.
Definition at line 56 of file TargetSelectionDAGInfo.h.
Referenced by llvm::SelectionDAG::getMemcpy().
virtual SDValue llvm::TargetSelectionDAGInfo::EmitTargetCodeForMemmove (SelectionDAG & DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const [inline, virtual]
EmitTargetCodeForMemmove - Emit target-specific code that performs a memmove.
This can be used by targets to provide code sequences for cases that don't fit the target's parameters for simple loads/stores and can be more efficient than using a library call. This function can return a null SDValue if the target declines to use custom code and a different lowering strategy should be used.
Reimplemented in llvm::ARMSelectionDAGInfo.
Definition at line 73 of file TargetSelectionDAGInfo.h.
Referenced by llvm::SelectionDAG::getMemmove().
virtual SDValue llvm::TargetSelectionDAGInfo::EmitTargetCodeForMemset (SelectionDAG & DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, MachinePointerInfo DstPtrInfo) const [inline, virtual]
EmitTargetCodeForMemset - Emit target-specific code that performs a memset.
This can be used by targets to provide code sequences for cases that don't fit the target's parameters for simple stores and can be more efficient than using a library call. This function can return a null SDValue if the target declines to use custom code and a different lowering strategy should be used.
Reimplemented in llvm::ARMSelectionDAGInfo, llvm::X86SelectionDAGInfo, llvm::SystemZSelectionDAGInfo, and llvm::AArch64SelectionDAGInfo.
Definition at line 89 of file TargetSelectionDAGInfo.h.
Referenced by llvm::SelectionDAG::getMemset().
virtual std::pair<SDValue, SDValue> llvm::TargetSelectionDAGInfo::EmitTargetCodeForStrcmp (SelectionDAG & DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const [inline, virtual]
EmitTargetCodeForStrcmp - Emit target-specific code that performs a strcmp, in cases where that is faster than a libcall.
The first returned SDValue is the result of the strcmp and the second is the chain. Both SDValues can be null if a normal libcall should be used.
Reimplemented in llvm::SystemZSelectionDAGInfo.
Definition at line 144 of file TargetSelectionDAGInfo.h.
virtual std::pair<SDValue, SDValue> llvm::TargetSelectionDAGInfo::EmitTargetCodeForStrcpy (SelectionDAG & DAG, SDLoc DL, SDValue Chain, SDValue Dest, SDValue Src, MachinePointerInfo DestPtrInfo, MachinePointerInfo SrcPtrInfo, bool isStpcpy) const [inline, virtual]
EmitTargetCodeForStrcpy - Emit target-specific code that performs a strcpy or stpcpy, in cases where that is faster than a libcall.
The first returned SDValue is the result of the copy (the start of the destination string for strcpy, a pointer to the null terminator for stpcpy) and the second is the chain. Both SDValues can be null if a normal libcall should be used.
Reimplemented in llvm::SystemZSelectionDAGInfo.
Definition at line 130 of file TargetSelectionDAGInfo.h.
virtual std::pair<SDValue, SDValue> llvm::TargetSelectionDAGInfo::EmitTargetCodeForStrlen (SelectionDAG & DAG, SDLoc DL, SDValue Chain, SDValue Src, MachinePointerInfo SrcPtrInfo) const [inline, virtual]
Reimplemented in llvm::SystemZSelectionDAGInfo.
Definition at line 153 of file TargetSelectionDAGInfo.h.
virtual std::pair<SDValue, SDValue> llvm::TargetSelectionDAGInfo::EmitTargetCodeForStrnlen (SelectionDAG & DAG, SDLoc DL, SDValue Chain, SDValue Src, SDValue MaxLength, MachinePointerInfo SrcPtrInfo) const [inline, virtual]
Reimplemented in llvm::SystemZSelectionDAGInfo.
Definition at line 159 of file TargetSelectionDAGInfo.h.
const DataLayout* llvm::TargetSelectionDAGInfo::getDataLayout () const [inline, protected]
Definition at line 36 of file TargetSelectionDAGInfo.h.
Referenced by llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), and llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset().
The documentation for this class was generated from the following files:
TargetSelectionDAGInfo.h
TargetSelectionDAGInfo.cpp