LLVM: llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT > Class Template Reference
llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT > Class Template Reference
#include <DenseMap.h>
Inherits llvm::DebugEpochBase.
Public Types
typedef unsigned size_type
typedef KeyT key_type
typedef ValueT mapped_type
typedef BucketT value_type
typedef DenseMapIterator< KeyT,
ValueT, KeyInfoT, BucketT > iterator
typedef DenseMapIterator< KeyT,
ValueT, KeyInfoT, BucketT,
true > const_iterator
Public Member Functions
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bool LLVM_ATTRIBUTE_UNUSED_RESULT empty () const
unsigned size () const
void resize (size_type Size)
Grow the densemap so that it has at least Size buckets. Does not shrink.
void clear ()
size_type count (const KeyT &Val) const
Return 1 if the specified key is in the map, 0 otherwise.
iterator find (const KeyT &Val)
const_iterator find (const KeyT &Val) const
template<class LookupKeyT >
iterator find_as (const LookupKeyT &Val)
Alternate version of find() which allows a different, and possibly less expensive, key type.
template<class LookupKeyT >
const_iterator find_as (const LookupKeyT &Val) const
ValueT lookup (const KeyT &Val) const
lookup - Return the entry for the specified key, or a default constructed value if no such entry exists.
std::pair< iterator, bool > insert (const std::pair< KeyT, ValueT > &KV)
std::pair< iterator, bool > insert (std::pair< KeyT, ValueT > &&KV)
template<typename InputIt >
void insert (InputIt I, InputIt E)
insert - Range insertion of pairs.
bool erase (const KeyT &Val)
void erase (iterator I)
value_type & FindAndConstruct (const KeyT &Key)
ValueT & operator[] (const KeyT &Key)
value_type & FindAndConstruct (KeyT &&Key)
ValueT & operator[] (KeyT &&Key)
bool isPointerIntoBucketsArray (const void *Ptr) const
isPointerIntoBucketsArray - Return true if the specified pointer points somewhere into the DenseMap's array of buckets (i.e.
const void * getPointerIntoBucketsArray () const
getPointerIntoBucketsArray() - Return an opaque pointer into the buckets array.
size_t getMemorySize () const
Return the approximate size (in bytes) of the actual map.
Protected Member Functions
DenseMapBase ()
void destroyAll ()
void initEmpty ()
void moveFromOldBuckets (BucketT *OldBucketsBegin, BucketT *OldBucketsEnd)
template<typename OtherBaseT >
void copyFrom (const DenseMapBase< OtherBaseT, KeyT, ValueT, KeyInfoT, BucketT > &other)
Static Protected Member Functions
static unsigned getHashValue (const KeyT &Val)
template<typename LookupKeyT >
static unsigned getHashValue (const LookupKeyT &Val)
static const KeyT getEmptyKey ()
static const KeyT getTombstoneKey ()
Detailed Description
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT>
class llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >
Definition at line 54 of file DenseMap.h.
Member Typedef Documentation
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> typedef DenseMapIterator<KeyT, ValueT, KeyInfoT, BucketT, true> llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::const_iterator
Definition at line 63 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> typedef DenseMapIterator<KeyT, ValueT, KeyInfoT, BucketT> llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::iterator
Definition at line 61 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> typedef KeyT llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::key_type
Definition at line 57 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> typedef ValueT llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::mapped_type
Definition at line 58 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> typedef unsigned llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size_type
Definition at line 56 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> typedef BucketT llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::value_type
Definition at line 59 of file DenseMap.h.
Constructor & Destructor Documentation
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::DenseMapBase () [protected]
Member Function Documentation
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin () [inline]
Definition at line 64 of file DenseMap.h.
Referenced by llvm::ValueMap< const GlobalValue *, std::unique_ptr< const MipsCallEntry > >::begin(), llvm::DenseSet< StructType *, StructTypeKeyInfo >::begin(), llvm::AliasSetTracker::clear(), llvm::DominatorTreeBase< MachineBasicBlock >::compare(), llvm::DwarfUnit::constructContainingTypeDIEs(), FindMostPopularDest(), llvm::PMTopLevelManager::initializeAllAnalysisInfo(), llvm::ConstantUniqueMap< ConstantStruct >::map_begin(), llvm::ValueEnumerator::print(), llvm::ScalarEvolution::releaseMemory(), llvm::PMDataManager::removeNotPreservedAnalysis(), llvm::ReplaceableMetadataImpl::replaceAllUsesWith(), llvm::ReplaceableMetadataImpl::resolveAllUses(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::PMTopLevelManager::setLastUser(), SpeculativelyExecuteBB(), llvm::ScalarEvolution::verifyAnalysis(), llvm::OptionRegistry::~OptionRegistry(), and llvm::PMTopLevelManager::~PMTopLevelManager().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> const_iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin () const [inline]
Definition at line 71 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear () [inline]
Definition at line 91 of file DenseMap.h.
Referenced by llvm::ScheduleDAGInstrs::buildSchedGraph(), llvm::VirtRegAuxInfo::calculateSpillWeightAndHint(), llvm::StatepointLoweringState::clear(), llvm::DenseSet< StructType *, StructTypeKeyInfo >::clear(), llvm::PredIteratorCache::clear(), llvm::objcarc::ProvenanceAnalysis::clear(), llvm::BlotMapVector< KeyT, ValueT >::clear(), llvm::LoopBlocksDFS::clear(), llvm::ValueMap< const GlobalValue *, std::unique_ptr< const MipsCallEntry > >::clear(), llvm::SDDbgInfo::clear(), llvm::FunctionLoweringInfo::clear(), llvm::GCModuleInfo::clear(), llvm::SelectionDAG::clear(), llvm::AliasSetTracker::clear(), llvm::SelectionDAGBuilder::clear(), llvm::SelectionDAGBuilder::clearDanglingDebugInfo(), llvm::DIEHash::computeCUSignature(), llvm::DIEHash::computeTypeSignature(), llvm::MachineModuleInfo::EndFunction(), llvm::DwarfDebug::endFunction(), llvm::DwarfDebug::endModule(), llvm::SelectionDAGBuilder::init(), llvm::MachineSSAUpdater::Initialize(), llvm::SSAUpdater::Initialize(), INITIALIZE_PASS(), llvm::PMDataManager::initializeAnalysisInfo(), llvm::LazyCallGraph::SCC::insertIncomingEdge(), llvm::LoopInfoBase< BasicBlock, Loop >::LoopInfoBase(), llvm::MemoryDependenceAnalysis::releaseMemory(), llvm::SlotIndexes::releaseMemory(), llvm::LoopInfoBase< BasicBlock, Loop >::releaseMemory(), llvm::LoopAccessAnalysis::releaseMemory(), llvm::ScalarEvolution::releaseMemory(), llvm::MachObjectWriter::reset(), llvm::MCStreamer::reset(), llvm::MCContext::reset(), llvm::DominatorTreeBase< MachineBasicBlock >::reset(), llvm::SplitEditor::reset(), llvm::ReplaceableMetadataImpl::resolveAllUses(), llvm::FastISel::startNewBlock(), llvm::StatepointLoweringState::startNewStatepoint(), and llvm::InstCombineWorklist::Zap().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> template<typename OtherBaseT > void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::copyFrom (const DenseMapBase< OtherBaseT, KeyT, ValueT, KeyInfoT, BucketT > & other) [inline, protected]
Definition at line 314 of file DenseMap.h.
Referenced by llvm::DenseMap< unsigned, unsigned >::copyFrom(), and llvm::SmallDenseMap< SDValue, SDValue, 8 >::copyFrom().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> size_type llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count (const KeyT & Val) const [inline]
Return 1 if the specified key is in the map, 0 otherwise.
Definition at line 119 of file DenseMap.h.
Referenced by llvm::WinCodeViewLineTables::beginFunction(), llvm::DFAPacketizer::canReserveResources(), llvm::EHStreamer::computePadMap(), llvm::DenseSet< StructType *, StructTypeKeyInfo >::count(), llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::count(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::WinCodeViewLineTables::endFunction(), llvm::DwarfDebug::endFunction(), llvm::LoopBlocksTraversal::finishPostorder(), llvm::StatepointLoweringState::getLocation(), llvm::FastISel::getRegForValue(), llvm::SlotIndexes::hasIndex(), llvm::LoopBlocksDFS::hasPreorder(), llvm::MachineSSAUpdater::HasValueForBlock(), llvm::SSAUpdater::HasValueForBlock(), llvm::MachineModuleInfo::hasWinEHFuncInfo(), llvm::ARMBaseInstrInfo::isFpMLxInstruction(), llvm::PPCRegisterInfo::needsFrameBaseReg(), llvm::MemoryDependenceAnalysis::removeInstruction(), llvm::ReplaceableMetadataImpl::replaceAllUsesWith(), llvm::scc_iterator< GraphT, GT >::ReplaceNode(), llvm::DFAPacketizer::reserveResources(), selectIncomingValueForBlock(), llvm::FastISel::selectIntrinsicCall(), llvm::FastISel::selectOperator(), llvm::FunctionLoweringInfo::set(), llvm::StatepointLoweringState::setLocation(), llvm::Value::setValueName(), llvm::SCEVApplyRewriter::visitAddRecExpr(), and llvm::SCEVParameterRewriter::visitUnknown().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::destroyAll () [inline, protected]
Definition at line 264 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> bool LLVM_ATTRIBUTE_UNUSED_RESULT llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty () const [inline]
Definition at line 79 of file DenseMap.h.
Referenced by llvm::DenseMapBase< DenseMap< BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >, BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >::begin(), llvm::IDFCalculator::calculate(), llvm::calculateWinCXXEHStateNumbers(), CompactSwizzlableVector(), llvm::AddressPool::emit(), llvm::DenseSet< StructType *, StructTypeKeyInfo >::empty(), llvm::BlotMapVector< KeyT, ValueT >::empty(), llvm::ValueMap< const GlobalValue *, std::unique_ptr< const MipsCallEntry > >::empty(), llvm::sampleprof::FunctionSamples::empty(), llvm::DwarfDebug::endFunction(), llvm::WinCodeViewLineTables::endModule(), llvm::MachineModuleInfo::hasCallSiteLandingPad(), llvm::LazyCallGraph::insertEdge(), llvm::AddressPool::isEmpty(), llvm::TargetLoweringBase::isSlowDivBypassed(), llvm::PMDataManager::recordAvailableAnalysis(), llvm::LazyCallGraph::removeEdge(), ReorganizeVector(), llvm::ReplaceableMetadataImpl::replaceAllUsesWith(), llvm::ReplaceableMetadataImpl::resolveAllUses(), llvm::SlotIndexes::runOnMachineFunction(), llvm::InstCombineWorklist::Zap(), llvm::ReplaceableMetadataImpl::~ReplaceableMetadataImpl(), and llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::~ScopedHashTable().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end () [inline]
Definition at line 68 of file DenseMap.h.
Referenced by llvm::bfi_detail::IrreducibleGraph::addEdges(), llvm::InstrProfWriter::addFunctionCounts(), AddPHINodeEntriesForMappedBlock(), llvm::ValueMapCallbackVH< KeyT, ValueT, Config >::allUsesReplacedWith(), llvm::DenseMapBase< DenseMap< BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >, BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >::begin(), llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::begin(), llvm::WinException::beginFunction(), llvm::DwarfDebug::beginFunction(), llvm::DwarfDebug::beginInstruction(), llvm::BlotMapVector< KeyT, ValueT >::blot(), llvm::bypassSlowDivision(), llvm::AliasSetTracker::clear(), llvm::DominatorTreeBase< MachineBasicBlock >::compare(), llvm::ObjectSizeOffsetEvaluator::compute(), llvm::EHStreamer::computeCallSiteTable(), llvm::DwarfUnit::constructContainingTypeDIEs(), llvm::SelectionDAGBuilder::CopyToExportRegsIfNeeded(), llvm::AliasSetTracker::copyValue(), llvm::SelectionDAGBuilder::CopyValueToVirtualRegister(), llvm::ValueMap< const GlobalValue *, std::unique_ptr< const MipsCallEntry > >::count(), llvm::AliasSetTracker::deleteValue(), llvm::DWARFAcceleratorTable::dump(), llvm::ValueMap< const GlobalValue *, std::unique_ptr< const MipsCallEntry > >::end(), llvm::DenseSet< StructType *, StructTypeKeyInfo >::end(), llvm::DwarfDebug::endInstruction(), llvm::ValueMap< const GlobalValue *, std::unique_ptr< const MipsCallEntry > >::erase(), llvm::DWARFFormValue::extractValue(), llvm::BlotMapVector< KeyT, ValueT >::find(), llvm::StratifiedSets< T >::find(), llvm::DenseMapBase< DenseMap< BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >, BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >::find(), llvm::DenseMapBase< DenseMap< BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >, BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >::find_as(), llvm::PMDataManager::findAnalysisPass(), findPreviousSpillSlot(), llvm::SelectionDAGBuilder::findValue(), llvm::ScalarEvolution::forgetLoop(), llvm::ScalarEvolution::forgetValue(), llvm::PMDataManager::freePass(), llvm::OptionRegistry::get(), llvm::FunctionLoweringInfo::getArgumentFrameIndex(), llvm::ValueEnumerator::getAttributeGroupID(), llvm::ValueEnumerator::getAttributeID(), llvm::ARMFunctionInfo::getCoalescedWeight(), llvm::SelectionDAGBuilder::getCopyFromRegs(), llvm::GCModuleInfo::getFunctionInfo(), llvm::SlotIndexes::getIndexAfter(), llvm::SlotIndexes::getIndexBefore(), llvm::ValueEnumerator::getInstructionID(), llvm::SlotIndexes::getInstructionIndex(), llvm::SparseSolver::getLatticeState(), getMappedReg(), llvm::DominatorTreeBase< MachineBasicBlock >::getNode(), llvm::PBQP::RegAlloc::GraphMetadata::getNodeIdForVReg(), llvm::ConstantUniqueMap< ConstantStruct >::getOrCreate(), llvm::ARMFunctionInfo::getOriginalCPIdx(), llvm::SparseSolver::getOrInitValueState(), llvm::PassRegistry::getPassInfo(), llvm::TargetPassConfig::getPassSubstitution(), llvm::LoopBlocksDFS::getPostorder(), llvm::Function::getPrefixData(), llvm::Function::getPrologueData(), llvm::orc::GlobalRenamer::getRename(), llvm::ScalarEvolution::getSCEV(), llvm::SDDbgInfo::getSDDbgValues(), llvm::MCRegisterInfo::getSEHRegNum(), llvm::ScheduleDAGInstrs::getSUnit(), llvm::ValueEnumerator::getTypeID(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::Value::getValueName(), llvm::NVPTXAsmPrinter::getVirtualRegisterName(), llvm::LoopBlocksDFS::hasPostorder(), llvm::PMTopLevelManager::initializeAllAnalysisInfo(), llvm::SlotIndexes::insertMachineInstrInMaps(), llvm::ARMBaseInstrInfo::isFpMLxInstruction(), llvm::ValueMap< const GlobalValue *, std::unique_ptr< const MipsCallEntry > >::lookup(), llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::lookup(), llvm::FastISel::lookUpRegForValue(), llvm::FastISel::lowerArguments(), llvm::ConstantUniqueMap< ConstantStruct >::map_end(), llvm::DWARFDebugLoc::parse(), llvm::DWARFDebugLine::LineTable::parse(), llvm::ValueEnumerator::print(), llvm::ScalarEvolution::releaseMemory(), llvm::InstCombineWorklist::Remove(), llvm::ConstantUniqueMap< ConstantStruct >::remove(), llvm::LoopInfoBase< BasicBlock, Loop >::removeBlock(), llvm::MemoryDependenceAnalysis::removeInstruction(), llvm::SlotIndexes::removeMachineInstrFromMaps(), llvm::PMDataManager::removeNotPreservedAnalysis(), llvm::SlotIndexes::repairIndexesInRange(), llvm::ReplaceableMetadataImpl::replaceAllUsesWith(), llvm::SlotIndexes::replaceMachineInstrInMaps(), llvm::ConstantUniqueMap< ConstantStruct >::replaceOperandsInPlace(), llvm::replaceSymbolicStrideSCEV(), replaceUndefValuesInPhi(), llvm::ReplaceableMetadataImpl::resolveAllUses(), reuseOrInsertFastDiv(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::FastISel::selectExtractValue(), selectIncomingValueForBlock(), llvm::FunctionLoweringInfo::set(), llvm::TargetLibraryInfoImpl::setAvailableWithName(), useFuncSeen(), llvm::ScalarEvolution::verifyAnalysis(), llvm::OptionRegistry::~OptionRegistry(), and llvm::PMTopLevelManager::~PMTopLevelManager().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> const_iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end () const [inline]
Definition at line 75 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> bool llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase (const KeyT & Val) [inline]
Definition at line 206 of file DenseMap.h.
Referenced by llvm::DwarfDebug::addDwarfTypeUnitType(), llvm::ValueMapCallbackVH< KeyT, ValueT, Config >::allUsesReplacedWith(), llvm::BlotMapVector< KeyT, ValueT >::blot(), llvm::LoopInfoBase< BasicBlock, Loop >::changeLoopFor(), llvm::ObjectSizeOffsetEvaluator::compute(), llvm::ValueMapCallbackVH< KeyT, ValueT, Config >::deleted(), llvm::AliasSetTracker::deleteValue(), llvm::Instruction::dropUnknownMetadata(), llvm::WinCodeViewLineTables::endFunction(), llvm::DenseSet< StructType *, StructTypeKeyInfo >::erase(), llvm::ValueMap< const GlobalValue *, std::unique_ptr< const MipsCallEntry > >::erase(), llvm::DominatorTreeBase< MachineBasicBlock >::eraseNode(), llvm::PBQP::RegAlloc::GraphMetadata::eraseNodeIdForVReg(), llvm::ScalarEvolution::forgetLoop(), llvm::ScalarEvolution::forgetValue(), llvm::PMDataManager::freePass(), llvm::ScalarEvolution::getSCEV(), llvm::ValueEnumerator::purgeFunction(), llvm::InstCombineWorklist::Remove(), llvm::AliasSetTracker::remove(), llvm::ConstantUniqueMap< ConstantStruct >::remove(), llvm::LoopInfoBase< BasicBlock, Loop >::removeBlock(), llvm::MemoryDependenceAnalysis::removeInstruction(), llvm::LazyCallGraph::SCC::removeIntraSCCEdge(), llvm::SlotIndexes::removeMachineInstrFromMaps(), llvm::PMDataManager::removeNotPreservedAnalysis(), llvm::InstCombineWorklist::RemoveOne(), llvm::ReplaceableMetadataImpl::replaceAllUsesWith(), llvm::SlotIndexes::replaceMachineInstrInMaps(), llvm::scc_iterator< GraphT, GT >::ReplaceNode(), llvm::BlockAddress::replaceUsesOfWithOnConstant(), llvm::Instruction::setMetadata(), llvm::Function::setPrefixData(), llvm::Function::setPrologueData(), llvm::Value::setValueName(), and splitVectorValues().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase (iterator I) [inline]
Definition at line 217 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find (const KeyT & Val) [inline]
Definition at line 124 of file DenseMap.h.
Referenced by llvm::bfi_detail::IrreducibleGraph::addEdges(), llvm::InstrProfWriter::addFunctionCounts(), AddPHINodeEntriesForMappedBlock(), llvm::ValueMapCallbackVH< KeyT, ValueT, Config >::allUsesReplacedWith(), llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::begin(), llvm::WinException::beginFunction(), llvm::DwarfDebug::beginFunction(), llvm::DwarfDebug::beginInstruction(), llvm::BlotMapVector< KeyT, ValueT >::blot(), llvm::bypassSlowDivision(), llvm::DominatorTreeBase< MachineBasicBlock >::compare(), llvm::ObjectSizeOffsetEvaluator::compute(), llvm::EHStreamer::computeCallSiteTable(), llvm::SelectionDAGBuilder::CopyToExportRegsIfNeeded(), llvm::SelectionDAGBuilder::CopyValueToVirtualRegister(), llvm::DWARFAcceleratorTable::dump(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::DwarfDebug::endInstruction(), llvm::DWARFFormValue::extractValue(), llvm::BlotMapVector< KeyT, ValueT >::find(), llvm::StratifiedSets< T >::find(), llvm::DenseSet< StructType *, StructTypeKeyInfo >::find(), llvm::PMDataManager::findAnalysisPass(), llvm::PMTopLevelManager::findAnalysisUsage(), findPreviousSpillSlot(), llvm::SelectionDAGBuilder::findValue(), llvm::ScalarEvolution::forgetLoop(), llvm::PMDataManager::freePass(), llvm::OptionRegistry::get(), llvm::FunctionLoweringInfo::getArgumentFrameIndex(), llvm::ValueEnumerator::getAttributeGroupID(), llvm::ValueEnumerator::getAttributeID(), llvm::ARMFunctionInfo::getCoalescedWeight(), llvm::SelectionDAGBuilder::getCopyFromRegs(), llvm::GCModuleInfo::getFunctionInfo(), llvm::SlotIndexes::getIndexAfter(), llvm::SlotIndexes::getIndexBefore(), llvm::ValueEnumerator::getInstructionID(), llvm::SlotIndexes::getInstructionIndex(), llvm::SparseSolver::getLatticeState(), getMappedReg(), llvm::TargetLibraryInfo::getName(), llvm::DominatorTreeBase< MachineBasicBlock >::getNode(), llvm::PBQP::RegAlloc::GraphMetadata::getNodeIdForVReg(), llvm::ARMFunctionInfo::getOriginalCPIdx(), llvm::SparseSolver::getOrInitValueState(), llvm::PassRegistry::getPassInfo(), llvm::TargetPassConfig::getPassSubstitution(), llvm::LoopBlocksDFS::getPostorder(), llvm::Function::getPrefixData(), llvm::Function::getPrologueData(), llvm::orc::GlobalRenamer::getRename(), llvm::SDDbgInfo::getSDDbgValues(), llvm::MCRegisterInfo::getSEHRegNum(), llvm::ScheduleDAGInstrs::getSUnit(), llvm::ValueEnumerator::getTypeID(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::Value::getValueName(), llvm::NVPTXAsmPrinter::getVirtualRegisterName(), llvm::LoopBlocksDFS::hasPostorder(), llvm::PMTopLevelManager::initializeAllAnalysisInfo(), llvm::SlotIndexes::insertMachineInstrInMaps(), llvm::ARMBaseInstrInfo::isFpMLxInstruction(), llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::lookup(), llvm::FastISel::lookUpRegForValue(), llvm::FastISel::lowerArguments(), llvm::DWARFDebugLoc::parse(), llvm::DWARFDebugLine::LineTable::parse(), llvm::InstCombineWorklist::Remove(), llvm::ConstantUniqueMap< ConstantStruct >::remove(), llvm::LoopInfoBase< BasicBlock, Loop >::removeBlock(), llvm::MemoryDependenceAnalysis::removeInstruction(), llvm::SlotIndexes::removeMachineInstrFromMaps(), llvm::SlotIndexes::repairIndexesInRange(), llvm::SlotIndexes::replaceMachineInstrInMaps(), llvm::replaceSymbolicStrideSCEV(), replaceUndefValuesInPhi(), reuseOrInsertFastDiv(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::FastISel::selectExtractValue(), selectIncomingValueForBlock(), llvm::FunctionLoweringInfo::set(), llvm::TargetLibraryInfoImpl::setAvailableWithName(), and useFuncSeen().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> const_iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find (const KeyT & Val) const [inline]
Definition at line 130 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> template<class LookupKeyT > iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find_as (const LookupKeyT & Val) [inline]
Alternate version of find() which allows a different, and possibly less expensive, key type.
The DenseMapInfo is responsible for supplying methods getHashValue(LookupKeyT) and isEqual(LookupKeyT, KeyT) for each key type used.
Definition at line 143 of file DenseMap.h.
Referenced by llvm::AliasSetTracker::copyValue(), llvm::ValueMap< const GlobalValue *, std::unique_ptr< const MipsCallEntry > >::count(), llvm::AliasSetTracker::deleteValue(), llvm::ValueMap< const GlobalValue *, std::unique_ptr< const MipsCallEntry > >::erase(), llvm::ValueMap< const GlobalValue *, std::unique_ptr< const MipsCallEntry > >::find(), llvm::ConstantUniqueMap< ConstantStruct >::find(), llvm::DenseSet< StructType *, StructTypeKeyInfo >::find_as(), llvm::ScalarEvolution::forgetLoop(), llvm::ScalarEvolution::forgetValue(), llvm::ScalarEvolution::getSCEV(), and llvm::ValueMap< const GlobalValue *, std::unique_ptr< const MipsCallEntry > >::lookup().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> template<class LookupKeyT > const_iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find_as (const LookupKeyT & Val) const [inline]
Definition at line 150 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> value_type& llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::FindAndConstruct (const KeyT & Key) [inline]
Definition at line 225 of file DenseMap.h.
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), llvm::ValueMap< const GlobalValue *, std::unique_ptr< const MipsCallEntry > >::FindAndConstruct(), and llvm::DenseMapBase< DenseMap< BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >, BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >::operator[]().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> value_type& llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::FindAndConstruct (KeyT && Key) [inline]
Definition at line 237 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> static const KeyT llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getEmptyKey () [inline, static, protected]
Definition at line 343 of file DenseMap.h.
Referenced by llvm::DenseMapBase< DenseMap< BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >, BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >::clear(), llvm::DenseMapBase< DenseMap< BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >, BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >::copyFrom(), llvm::DenseMapBase< DenseMap< BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >, BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >::destroyAll(), llvm::DenseMapBase< DenseMap< BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >, BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >::getEmptyKey(), llvm::DenseMapBase< DenseMap< BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >, BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >::initEmpty(), and llvm::DenseMapBase< DenseMap< BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >, BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >::moveFromOldBuckets().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> static unsigned llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getHashValue (const KeyT & Val) [inline, static, protected]
Definition at line 336 of file DenseMap.h.
Referenced by llvm::DenseMapBase< DenseMap< BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >, BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >::getHashValue().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> template<typename LookupKeyT > static unsigned llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getHashValue (const LookupKeyT & Val) [inline, static, protected]
Definition at line 340 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> size_t llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getMemorySize () const [inline]
Return the approximate size (in bytes) of the actual map.
This is just the raw memory used by DenseMap. If entries are pointers to objects, the size of the referenced objects are not included.
Definition at line 532 of file DenseMap.h.
Referenced by llvm::DenseSet< StructType *, StructTypeKeyInfo >::getMemorySize().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> const void* llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getPointerIntoBucketsArray () const [inline]
getPointerIntoBucketsArray() - Return an opaque pointer into the buckets array.
In conjunction with the previous method, this can be used to determine whether an insertion caused the DenseMap to reallocate.
Definition at line 259 of file DenseMap.h.
Referenced by llvm::ValueMap< const GlobalValue *, std::unique_ptr< const MipsCallEntry > >::getPointerIntoBucketsArray().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> static const KeyT llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getTombstoneKey () [inline, static, protected]
Definition at line 346 of file DenseMap.h.
Referenced by llvm::DenseMapBase< DenseMap< BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >, BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >::clear(), llvm::DenseMapBase< DenseMap< BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >, BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >::copyFrom(), llvm::DenseMapBase< DenseMap< BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >, BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >::destroyAll(), llvm::DenseMapBase< DenseMap< BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >, BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >::erase(), llvm::DenseMapBase< DenseMap< BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >, BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >::getTombstoneKey(), and llvm::DenseMapBase< DenseMap< BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >, BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >::moveFromOldBuckets().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::initEmpty () [inline, protected]
Definition at line 277 of file DenseMap.h.
Referenced by llvm::DenseMap< unsigned, unsigned >::grow(), llvm::DenseMap< unsigned, unsigned >::init(), llvm::SmallDenseMap< SDValue, SDValue, 8 >::init(), llvm::DenseMapBase< DenseMap< BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >, BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >::moveFromOldBuckets(), llvm::DenseMap< unsigned, unsigned >::shrink_and_clear(), and llvm::SmallDenseMap< SDValue, SDValue, 8 >::shrink_and_clear().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> std::pair<iterator, bool> llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert (const std::pair< KeyT, ValueT > & KV) [inline]
Definition at line 169 of file DenseMap.h.
Referenced by llvm::InstCombineWorklist::Add(), llvm::InstCombineWorklist::AddInitialGroup(), llvm::DwarfUnit::applySubprogramAttributes(), llvm::ARMBaseInstrInfo::ARMBaseInstrInfo(), llvm::MachObjectWriter::bindIndirectSymbols(), llvm::DWARFContextInMemory::DWARFContextInMemory(), findCallees(), gatherIncomingValuesToPhi(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), llvm::generateDITypeIdentifierMap(), llvm::ARMFunctionInfo::getCoalescedWeight(), llvm::AddressPool::getIndex(), llvm::orc::GlobalRenamer::getRename(), llvm::ScalarEvolution::getSCEV(), llvm::BlotMapVector< KeyT, ValueT >::insert(), llvm::DenseSet< StructType *, StructTypeKeyInfo >::insert(), llvm::ValueMap< const GlobalValue *, std::unique_ptr< const MipsCallEntry > >::insert(), llvm::DenseMapBase< DenseMap< BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >, BasicBlock *, BasicBlock *, DenseMapInfo< BasicBlock * >, detail::DenseMapPair< BasicBlock *, BasicBlock * > >::insert(), llvm::DwarfFile::insertDIE(), llvm::DwarfUnit::insertDIE(), insertFastDiv(), llvm::SlotIndexes::insertMachineInstrInMaps(), llvm::LazyCallGraph::LazyCallGraph(), llvm::makeSubprogramMap(), llvm::BlotMapVector< KeyT, ValueT >::operator[](), pushDepHeight(), reassociateOps(), llvm::ARMFunctionInfo::recordCPEClone(), llvm::PassRegistry::registerPass(), llvm::MemoryDependenceAnalysis::removeInstruction(), llvm::SlotIndexes::replaceMachineInstrInMaps(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::SlotIndexes::runOnMachineFunction(), selectIncomingValueForBlock(), and llvm::LoopBlocksTraversal::visitPreorder().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> std::pair<iterator, bool> llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert (std::pair< KeyT, ValueT > && KV) [inline]
Definition at line 184 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> template<typename InputIt > void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert (InputIt I, InputIt E) [inline]
insert - Range insertion of pairs.
Definition at line 200 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> bool llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::isPointerIntoBucketsArray (const void * Ptr) const [inline]
isPointerIntoBucketsArray - Return true if the specified pointer points somewhere into the DenseMap's array of buckets (i.e.
either to a key or value in the DenseMap).
Definition at line 252 of file DenseMap.h.
Referenced by llvm::ValueMap< const GlobalValue *, std::unique_ptr< const MipsCallEntry > >::isPointerIntoBucketsArray().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> ValueT llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup (const KeyT & Val) const [inline]
lookup - Return the entry for the specified key, or a default constructed value if no such entry exists.
Definition at line 159 of file DenseMap.h.
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), llvm::IDFCalculator::calculate(), llvm::DwarfCompileUnit::collectDeadVariables(), llvm::DwarfCompileUnit::createScopeChildrenDIE(), llvm::DIBuilder::finalize(), llvm::DwarfCompileUnit::finishSubprogramDefinition(), llvm::DwarfFile::getDIE(), llvm::DwarfUnit::getDIE(), llvm::DominatorTreeBase< MachineBasicBlock >::getIDom(), llvm::ValueAsMetadata::getIfExists(), llvm::MachineTraceMetrics::Trace::getInstrCycles(), llvm::DwarfDebug::getLabelAfterInsn(), llvm::DwarfDebug::getLabelBeforeInsn(), llvm::LoopInfoBase< BasicBlock, Loop >::getLoopFor(), llvm::Function::getMetadata(), llvm::ValueEnumerator::getMetadataOrNullID(), llvm::MCStreamer::GetSymbolOrder(), INITIALIZE_PASS(), llvm::LazyCallGraph::SCC::insertIncomingEdge(), llvm::LazyCallGraph::SCC::insertIntraSCCEdge(), llvm::LazyCallGraph::SCC::insertOutgoingEdge(), llvm::LazyCallGraph::lookup(), llvm::BlockAddress::lookup(), llvm::LazyCallGraph::lookupSCC(), llvm::DwarfDebug::lookupUnit(), MapMetadataImpl(), llvm::LazyCallGraph::SCC::removeInterSCCEdge(), llvm::LazyCallGraph::SCC::removeIntraSCCEdge(), and llvm::MachObjectWriter::writeSection().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::moveFromOldBuckets (BucketT * OldBucketsBegin, BucketT * OldBucketsEnd) [inline, protected]
Definition at line 288 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> ValueT& llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::operator[] (const KeyT & Key) [inline]
Definition at line 233 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> ValueT& llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::operator[] (KeyT && Key) [inline]
Definition at line 245 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::resize (size_type Size) [inline]
Grow the densemap so that it has at least Size buckets. Does not shrink.
Definition at line 85 of file DenseMap.h.
Referenced by llvm::InstCombineWorklist::AddInitialGroup(), llvm::DenseSet< StructType *, StructTypeKeyInfo >::resize(), and llvm::ValueMap< const GlobalValue *, std::unique_ptr< const MipsCallEntry > >::resize().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> unsigned llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size () const [inline]
Definition at line 82 of file DenseMap.h.
Referenced by llvm::MCStreamer::AssignSection(), llvm::DominatorTreeBase< MachineBasicBlock >::compare(), llvm::AddressPool::emit(), findBasePointers(), llvm::AddressPool::getIndex(), llvm::LoopAccessAnalysis::getInfo(), llvm::orc::GlobalRenamer::getRename(), llvm::ValueEnumerator::print(), llvm::AliasSetTracker::print(), llvm::DenseSet< StructType *, StructTypeKeyInfo >::size(), llvm::ValueMap< const GlobalValue *, std::unique_ptr< const MipsCallEntry > >::size(), llvm::StratifiedSetsBuilder< T >::size(), llvm::ScalarEvolution::verifyAnalysis(), llvm::sampleprof::SampleProfileWriterBinary::write(), and llvm::MachObjectWriter::writeObject().
The documentation for this class was generated from the following file:
DenseMap.h