LLVM: llvm::SDDbgInfo Class Reference
llvm::SDDbgInfo Class Reference
Keeps track of dbg_value information through SDISel.
#include <SelectionDAG.h>
Public Types
typedef SmallVectorImpl
< SDDbgValue * >::iterator DbgIterator
Public Member Functions
SDDbgInfo ()
void add (SDDbgValue *V, const SDNode *Node, bool isParameter)
void erase (const SDNode *Node)
Invalidate all DbgValues attached to the node and remove it from the Node-to-DbgValues map.
void clear ()
BumpPtrAllocator & getAlloc ()
bool empty () const
ArrayRef< SDDbgValue * > getSDDbgValues (const SDNode *Node)
DbgIterator DbgBegin ()
DbgIterator DbgEnd ()
DbgIterator ByvalParmDbgBegin ()
DbgIterator ByvalParmDbgEnd ()
Detailed Description
Keeps track of dbg_value information through SDISel.
We do not build SDNodes for these so as not to perturb the generated code; instead the info is kept off to the side in this structure. Each SDNode may have one or more associated dbg_value entries. This information is kept in DbgValMap. Byval parameters are handled separately because they don't use alloca's, which busts the normal mechanism. There is good reason for handling all parameters separately: they may not have code generated for them, they should always go at the beginning of the function regardless of other code motion, and debug info for them is potentially useful even if the parameter is unused. Right now only byval parameters are handled separately.
Definition at line 114 of file SelectionDAG.h.
Member Typedef Documentation
typedef SmallVectorImpl<SDDbgValue*>::iterator llvm::SDDbgInfo::DbgIterator
Definition at line 158 of file SelectionDAG.h.
Constructor & Destructor Documentation
llvm::SDDbgInfo::SDDbgInfo () [inline]
Definition at line 124 of file SelectionDAG.h.
Member Function Documentation
void llvm::SDDbgInfo::add (SDDbgValue * V, const SDNode * Node, bool isParameter) [inline]
Definition at line 126 of file SelectionDAG.h.
References llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by llvm::SelectionDAG::AddDbgValue().
DbgIterator llvm::SDDbgInfo::ByvalParmDbgBegin () [inline]
Definition at line 161 of file SelectionDAG.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
Referenced by llvm::SelectionDAG::ByvalParmDbgBegin().
DbgIterator llvm::SDDbgInfo::ByvalParmDbgEnd () [inline]
Definition at line 162 of file SelectionDAG.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by llvm::SelectionDAG::ByvalParmDbgEnd().
void llvm::SDDbgInfo::clear () [inline]
Definition at line 138 of file SelectionDAG.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::SmallVectorImpl< T >::clear(), and llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Reset().
Referenced by llvm::SelectionDAG::clear().
DbgIterator llvm::SDDbgInfo::DbgBegin () [inline]
Definition at line 159 of file SelectionDAG.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
Referenced by llvm::SelectionDAG::DbgBegin().
DbgIterator llvm::SDDbgInfo::DbgEnd () [inline]
Definition at line 160 of file SelectionDAG.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by llvm::SelectionDAG::DbgEnd().
bool llvm::SDDbgInfo::empty () const [inline]
Definition at line 147 of file SelectionDAG.h.
References llvm::SmallVectorBase::empty().
Referenced by llvm::SelectionDAG::hasDebugValues().
void SDDbgInfo::erase (const SDNode * Node)
Invalidate all DbgValues attached to the node and remove it from the Node-to-DbgValues map.
Definition at line 701 of file SelectionDAG.cpp.
References I.
BumpPtrAllocator& llvm::SDDbgInfo::getAlloc () [inline]
Definition at line 145 of file SelectionDAG.h.
Referenced by llvm::SelectionDAG::getConstantDbgValue(), llvm::SelectionDAG::getDbgValue(), and llvm::SelectionDAG::getFrameIndexDbgValue().
ArrayRef<SDDbgValue*> llvm::SDDbgInfo::getSDDbgValues (const SDNode * Node) [inline]
Definition at line 151 of file SelectionDAG.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and I.
Referenced by llvm::SelectionDAG::AddDbgValue(), and llvm::SelectionDAG::GetDbgValues().
The documentation for this class was generated from the following files:
SelectionDAG.h
SelectionDAG.cpp