LLVM: llvm::PBQP::RegAlloc::MatrixMetadata Class Reference
llvm::PBQP::RegAlloc::MatrixMetadata Class Reference
Metadata to speed allocatability test.
#include <RegAllocPBQP.h>
Public Member Functions
MatrixMetadata (const Matrix &M)
unsigned getWorstRow () const
unsigned getWorstCol () const
const bool * getUnsafeRows () const
const bool * getUnsafeCols () const
Detailed Description
Metadata to speed allocatability test.
Keeps track of the number of infinities in each row and column.
Definition at line 38 of file RegAllocPBQP.h.
Constructor & Destructor Documentation
llvm::PBQP::RegAlloc::MatrixMetadata::MatrixMetadata (const Matrix & M) [inline]
Definition at line 43 of file RegAllocPBQP.h.
References llvm::PBQP::Matrix::getCols(), and llvm::PBQP::Matrix::getRows().
Member Function Documentation
const bool* llvm::PBQP::RegAlloc::MatrixMetadata::getUnsafeCols () const [inline]
Definition at line 71 of file RegAllocPBQP.h.
Referenced by llvm::PBQP::RegAlloc::NodeMetadata::handleAddEdge(), and llvm::PBQP::RegAlloc::NodeMetadata::handleRemoveEdge().
const bool* llvm::PBQP::RegAlloc::MatrixMetadata::getUnsafeRows () const [inline]
Definition at line 70 of file RegAllocPBQP.h.
Referenced by llvm::PBQP::RegAlloc::NodeMetadata::handleAddEdge(), and llvm::PBQP::RegAlloc::NodeMetadata::handleRemoveEdge().
unsigned llvm::PBQP::RegAlloc::MatrixMetadata::getWorstCol () const [inline]
Definition at line 69 of file RegAllocPBQP.h.
Referenced by llvm::PBQP::RegAlloc::NodeMetadata::handleAddEdge(), and llvm::PBQP::RegAlloc::NodeMetadata::handleRemoveEdge().
unsigned llvm::PBQP::RegAlloc::MatrixMetadata::getWorstRow () const [inline]
Definition at line 68 of file RegAllocPBQP.h.
Referenced by llvm::PBQP::RegAlloc::NodeMetadata::handleAddEdge(), and llvm::PBQP::RegAlloc::NodeMetadata::handleRemoveEdge().
The documentation for this class was generated from the following file:
RegAllocPBQP.h