LLVM: llvm::TypedDINodeRef< T > Class Template Reference
llvm::TypedDINodeRef< T > Class Template Reference
Pointer union between a subclass of DINode and MDString.
#include <DebugInfoMetadata.h>
Public Member Functions
TypedDINodeRef ()
TypedDINodeRef (std::nullptr_t)
TypedDINodeRef (const Metadata *MD)
Construct from a raw pointer.
template<class U >
TypedDINodeRef (const TypedDINodeRef< U > &X, typename std::enable_if< std::is_convertible< U *, T * >::value >::type *=nullptr)
operator Metadata * () const
bool operator== (const TypedDINodeRef< T > &X) const
bool operator!= (const TypedDINodeRef< T > &X) const
template<class MapTy >
T * resolve (const MapTy &Map) const
Static Public Member Functions
static TypedDINodeRef get (const T *N)
Create a reference.
Detailed Description
template<class T>
class llvm::TypedDINodeRef< T >
Pointer union between a subclass of DINode and MDString.
DICompositeType can be referenced via an MDString unique identifier. This class allows some type safety in the face of that, requiring either a node of a particular type or an MDString.
Definition at line 49 of file DebugInfoMetadata.h.
Constructor & Destructor Documentation
template<class T> llvm::TypedDINodeRef< T >::TypedDINodeRef ()
template<class T> llvm::TypedDINodeRef< T >::TypedDINodeRef (std::nullptr_t) [inline]
Definition at line 54 of file DebugInfoMetadata.h.
template<class T> llvm::TypedDINodeRef< T >::TypedDINodeRef (const Metadata * MD) [inline, explicit]
Construct from a raw pointer.
Definition at line 57 of file DebugInfoMetadata.h.
template<class T> template<class U > llvm::TypedDINodeRef< T >::TypedDINodeRef (const TypedDINodeRef< U > & X, typename std::enable_if< std::is_convertible< U *, T * >::value >::type * = nullptr) [inline]
Definition at line 62 of file DebugInfoMetadata.h.
Member Function Documentation
template<class T > TypedDINodeRef< T > llvm::TypedDINodeRef< T >::get (const T * N) [static]
Create a reference.
Get a reference to N, using an MDString reference if available.
Definition at line 909 of file DebugInfoMetadata.h.
Referenced by llvm::DIBuilder::createArrayType(), llvm::DIBuilder::createClassType(), llvm::DIBuilder::createEnumerationType(), llvm::DIBuilder::createForwardDecl(), llvm::DIBuilder::createFriend(), llvm::DIBuilder::createFunction(), llvm::DIBuilder::createGlobalVariable(), llvm::DIBuilder::createImportedDeclaration(), llvm::DIBuilder::createInheritance(), llvm::DIBuilder::createLocalVariable(), llvm::DIBuilder::createMemberPointerType(), llvm::DIBuilder::createMemberType(), llvm::DIBuilder::createMethod(), llvm::DIBuilder::createObjCIVar(), llvm::DIBuilder::createObjCProperty(), llvm::DIBuilder::createPointerType(), llvm::DIBuilder::createQualifiedType(), llvm::DIBuilder::createReferenceType(), llvm::DIBuilder::createReplaceableCompositeType(), llvm::DIBuilder::createStaticMemberType(), llvm::DIBuilder::createStructType(), llvm::DIBuilder::createTempFunctionFwdDecl(), llvm::DIBuilder::createTempGlobalVariableFwdDecl(), llvm::DIBuilder::createTemplateTypeParameter(), createTemplateValueParameterHelper(), llvm::DIBuilder::createTypedef(), llvm::DIBuilder::createUnionType(), llvm::DIBuilder::createVectorType(), llvm::DIBuilder::getOrCreateTypeArray(), and llvm::DIBuilder::replaceVTableHolder().
template<class T> llvm::TypedDINodeRef< T >::operator Metadata * () const [inline]
Definition at line 68 of file DebugInfoMetadata.h.
template<class T> bool llvm::TypedDINodeRef< T >::operator!= (const TypedDINodeRef< T > & X) const [inline]
Definition at line 71 of file DebugInfoMetadata.h.
template<class T> bool llvm::TypedDINodeRef< T >::operator== (const TypedDINodeRef< T > & X) const [inline]
Definition at line 70 of file DebugInfoMetadata.h.
template<class T> template<class MapTy > T* llvm::TypedDINodeRef< T >::resolve (const MapTy & Map) const [inline]
Definition at line 78 of file DebugInfoMetadata.h.
References I.
Referenced by llvm::DIBuilder::createFunction(), llvm::DbgVariable::getType(), llvm::DbgVariable::isBlockByrefVariable(), and llvm::DwarfDebug::resolve().
The documentation for this class was generated from the following file:
DebugInfoMetadata.h