LLVM: llvm::StratifiedSetsBuilder< T > Class Template Reference
llvm::StratifiedSetsBuilder< T > Class Template Reference
#include <StratifiedSets.h>
Classes
struct BuilderLink
Public Member Functions
StratifiedSets< T > build ()
std::size_t size () const
std::size_t numSets () const
bool has (const T &Elem) const
bool add (const T &Main)
bool addAbove (const T &Main, const T &ToAdd)
bool addBelow (const T &Main, const T &ToAdd)
bool addWith (const T &Main, const T &ToAdd)
void noteAttribute (const T &Main, unsigned AttrNum)
void noteAttributes (const T &Main, const StratifiedAttrs &NewAttrs)
StratifiedAttrs getAttributes (const T &Main)
bool getAttribute (const T &Main, unsigned AttrNum)
StratifiedAttrs getRawAttributes (const T &Main)
bool getRawAttribute (const T &Main, unsigned AttrNum)
Detailed Description
template<typename T>
class llvm::StratifiedSetsBuilder< T >
Definition at line 213 of file StratifiedSets.h.
Member Function Documentation
template<typename T> bool llvm::StratifiedSetsBuilder< T >::add (const T & Main) [inline]
Definition at line 396 of file StratifiedSets.h.
Referenced by buildSetsFrom().
template<typename T> bool llvm::StratifiedSetsBuilder< T >::addAbove (const T & Main, const T & ToAdd) [inline]
Definition at line 407 of file StratifiedSets.h.
References llvm::StratifiedSetsBuilder< T >::has().
Referenced by buildSetsFrom().
template<typename T> bool llvm::StratifiedSetsBuilder< T >::addBelow (const T & Main, const T & ToAdd) [inline]
Definition at line 420 of file StratifiedSets.h.
References llvm::StratifiedSetsBuilder< T >::has().
Referenced by buildSetsFrom().
template<typename T> bool llvm::StratifiedSetsBuilder< T >::addWith (const T & Main, const T & ToAdd) [inline]
Definition at line 430 of file StratifiedSets.h.
References llvm::StratifiedSetsBuilder< T >::has().
Referenced by buildSetsFrom().
template<typename T> StratifiedSets<T> llvm::StratifiedSetsBuilder< T >::build () [inline]
Definition at line 383 of file StratifiedSets.h.
Referenced by buildSetsFrom().
template<typename T> bool llvm::StratifiedSetsBuilder< T >::getAttribute (const T & Main, unsigned AttrNum) [inline]
Definition at line 464 of file StratifiedSets.h.
References llvm::StratifiedSetsBuilder< T >::getAttributes(), and llvm::StratifiedLink::SetSentinel.
template<typename T> StratifiedAttrs llvm::StratifiedSetsBuilder< T >::getAttributes (const T & Main) [inline]
Definition at line 451 of file StratifiedSets.h.
References llvm::StratifiedSetsBuilder< T >::has(), and llvm::Link.
Referenced by llvm::StratifiedSetsBuilder< T >::getAttribute().
template<typename T> bool llvm::StratifiedSetsBuilder< T >::getRawAttribute (const T & Main, unsigned AttrNum) [inline]
Definition at line 483 of file StratifiedSets.h.
References llvm::StratifiedSetsBuilder< T >::getRawAttributes(), and llvm::StratifiedLink::SetSentinel.
template<typename T> StratifiedAttrs llvm::StratifiedSetsBuilder< T >::getRawAttributes (const T & Main) [inline]
Definition at line 473 of file StratifiedSets.h.
References llvm::StratifiedSetsBuilder< T >::has(), and llvm::Link.
Referenced by llvm::StratifiedSetsBuilder< T >::getRawAttribute().
template<typename T> bool llvm::StratifiedSetsBuilder< T >::has (const T & Elem) const [inline]
Definition at line 394 of file StratifiedSets.h.
Referenced by llvm::StratifiedSetsBuilder< T >::addAbove(), llvm::StratifiedSetsBuilder< T >::addBelow(), llvm::StratifiedSetsBuilder< T >::addWith(), llvm::StratifiedSetsBuilder< T >::getAttributes(), llvm::StratifiedSetsBuilder< T >::getRawAttributes(), llvm::StratifiedSetsBuilder< T >::noteAttribute(), and llvm::StratifiedSetsBuilder< T >::noteAttributes().
template<typename T> void llvm::StratifiedSetsBuilder< T >::noteAttribute (const T & Main, unsigned AttrNum) [inline]
Definition at line 436 of file StratifiedSets.h.
References llvm::StratifiedSetsBuilder< T >::has(), llvm::Link, and llvm::StratifiedLink::SetSentinel.
template<typename T> void llvm::StratifiedSetsBuilder< T >::noteAttributes (const T & Main, const StratifiedAttrs & NewAttrs) [inline]
Definition at line 444 of file StratifiedSets.h.
References llvm::StratifiedSetsBuilder< T >::has(), and llvm::Link.
Referenced by buildSetsFrom().
template<typename T> std::size_t llvm::StratifiedSetsBuilder< T >::numSets () const [inline]
Definition at line 392 of file StratifiedSets.h.
template<typename T> std::size_t llvm::StratifiedSetsBuilder< T >::size () const [inline]
Definition at line 391 of file StratifiedSets.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size().
The documentation for this class was generated from the following file:
StratifiedSets.h