LLVM: llvm::MCELFStreamer Class Reference
llvm::MCELFStreamer Class Reference
#include <MCELFStreamer.h>
Classes
struct LocalCommon
Public Member Functions
MCELFStreamer (MCContext &Context, MCAsmBackend &TAB, raw_pwrite_stream &OS, MCCodeEmitter *Emitter)
~MCELFStreamer () override
void reset () override
state management
MCStreamer Interface
void InitSections (bool NoExecStack) override
Create the default sections and set the initial one.
void ChangeSection (MCSection *Section, const MCExpr *Subsection) override
Update streamer for a new active section.
void EmitLabel (MCSymbol *Symbol) override
Emit a label for Symbol into the current section.
void EmitAssemblerFlag (MCAssemblerFlag Flag) override
Note in the output the specified Flag.
void EmitThumbFunc (MCSymbol *Func) override
Note in the output that the specified Func is a Thumb mode function (ARM target only).
void EmitWeakReference (MCSymbol *Alias, const MCSymbol *Symbol) override
Emit an weak reference from Alias to Symbol.
bool EmitSymbolAttribute (MCSymbol *Symbol, MCSymbolAttr Attribute) override
Add the given Attribute to Symbol.
void EmitSymbolDesc (MCSymbol *Symbol, unsigned DescValue) override
Set the DescValue for the Symbol.
void EmitCommonSymbol (MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment) override
Emit a common symbol.
void BeginCOFFSymbolDef (const MCSymbol *Symbol) override
Start emitting COFF symbol definition.
void EmitCOFFSymbolStorageClass (int StorageClass) override
Emit the storage class of the symbol.
void EmitCOFFSymbolType (int Type) override
Emit the type of the symbol.
void EndCOFFSymbolDef () override
Marks the end of the symbol definition.
void emitELFSize (MCSymbolELF *Symbol, const MCExpr *Value) override
Emit an ELF .size directive.
void EmitLocalCommonSymbol (MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment) override
Emit a local common (.lcomm) symbol.
void EmitZerofill (MCSection *Section, MCSymbol *Symbol=nullptr, uint64_t Size=0, unsigned ByteAlignment=0) override
Emit the zerofill section and an optional symbol.
void EmitTBSSSymbol (MCSection *Section, MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment=0) override
Emit a thread local bss (.tbss) symbol.
void EmitValueImpl (const MCExpr *Value, unsigned Size, const SMLoc &Loc=SMLoc()) override
Emit the expression Value into the output as a native integer of the given Size bytes.
void EmitFileDirective (StringRef Filename) override
Switch to a new logical file.
void EmitIdent (StringRef IdentString) override
Emit the "identifiers" directive.
void EmitValueToAlignment (unsigned, int64_t, unsigned, unsigned) override
Emit some number of copies of Value until the byte alignment ByteAlignment is reached.
void Flush () override
Causes any cached state to be written out.
void FinishImpl () override
Streamer specific finalization.
void EmitBundleAlignMode (unsigned AlignPow2) override
Set the bundle alignment mode from now on in the section.
void EmitBundleLock (bool AlignToEnd) override
The following instructions are a bundle-locked group.
void EmitBundleUnlock () override
Ends a bundle-locked group.
Detailed Description
Definition at line 28 of file MCELFStreamer.h.
Constructor & Destructor Documentation
llvm::MCELFStreamer::MCELFStreamer (MCContext & Context, MCAsmBackend & TAB, raw_pwrite_stream & OS, MCCodeEmitter * Emitter) [inline]
Definition at line 30 of file MCELFStreamer.h.
MCELFStreamer::~MCELFStreamer () [override]
Definition at line 44 of file MCELFStreamer.cpp.
Member Function Documentation
void MCELFStreamer::BeginCOFFSymbolDef (const MCSymbol * Symbol) [override, virtual]
Start emitting COFF symbol definition.
Parameters:
Symbol - The symbol to have its External & Type fields set.
Reimplemented from llvm::MCStreamer.
Definition at line 680 of file MCELFStreamer.cpp.
References llvm_unreachable.
void MCELFStreamer::ChangeSection (MCSection * , const MCExpr *) [override, virtual]
Update streamer for a new active section.
This is called by PopSection and SwitchSection, if the current section changes.
Reimplemented from llvm::MCObjectStreamer.
Definition at line 146 of file MCELFStreamer.cpp.
References llvm::HexStyle::Asm, llvm::MCObjectStreamer::getAssembler(), llvm::MCSection::getBeginSymbol(), llvm::MCStreamer::getContext(), llvm::MCStreamer::getCurrentSectionOnly(), llvm::MCContext::getOrCreateSectionSymbol(), llvm::MCAssembler::registerSymbol(), llvm::report_fatal_error(), llvm::ARMBuildAttrs::Section, llvm::MCSection::setBeginSymbol(), setSectionAlignmentForBundling(), and llvm::ELF::STT_SECTION.
void MCELFStreamer::EmitAssemblerFlag (MCAssemblerFlag Flag) [override, virtual]
Note in the output the specified Flag.
Reimplemented from llvm::MCStreamer.
Definition at line 120 of file MCELFStreamer.cpp.
References llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getBackend(), llvm::MCAsmBackend::handleAssemblerFlag(), llvm_unreachable, llvm::MCAF_Code16, llvm::MCAF_Code32, llvm::MCAF_Code64, llvm::MCAF_SubsectionsViaSymbols, llvm::MCAF_SyntaxUnified, and llvm::MCAssembler::setSubsectionsViaSymbols().
void MCELFStreamer::EmitBundleAlignMode (unsigned AlignPow2) [override, virtual]
Set the bundle alignment mode from now on in the section.
The argument is the power of 2 to which the alignment is set. The value 0 means turn the bundle alignment off.
Reimplemented from llvm::MCObjectStreamer.
Definition at line 563 of file MCELFStreamer.cpp.
References llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getBundleAlignSize(), llvm::report_fatal_error(), and llvm::MCAssembler::setBundleAlignSize().
void MCELFStreamer::EmitBundleLock (bool AlignToEnd) [override, virtual]
The following instructions are a bundle-locked group.
Parameters:
AlignToEnd - If true, the bundle-locked group will be aligned to the end of a bundle.
Reimplemented from llvm::MCObjectStreamer.
Definition at line 573 of file MCELFStreamer.cpp.
References llvm::MCSection::BundleLocked, llvm::MCSection::BundleLockedAlignToEnd, llvm::MCObjectStreamer::getAssembler(), llvm::MCStreamer::getCurrentSectionOnly(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::report_fatal_error(), llvm::MCSection::setBundleGroupBeforeFirstInst(), and llvm::MCSection::setBundleLockState().
void MCELFStreamer::EmitBundleUnlock () [override, virtual]
Ends a bundle-locked group.
Reimplemented from llvm::MCObjectStreamer.
Definition at line 594 of file MCELFStreamer.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::MCSection::BundleLockedAlignToEnd, llvm::SmallVectorBase::empty(), llvm::MCObjectStreamer::getAssembler(), llvm::MCSection::getBundleLockState(), llvm::MCStreamer::getCurrentSectionOnly(), llvm::MCObjectStreamer::getOrCreateDataFragment(), llvm::MCAssembler::getRelaxAll(), llvm::MCSection::isBundleGroupBeforeFirstInst(), llvm::MCSection::NotBundleLocked, llvm::SmallVectorTemplateBase< T, isPodLike >::pop_back(), llvm::report_fatal_error(), llvm::MCFragment::setAlignToBundleEnd(), and llvm::MCSection::setBundleLockState().
void MCELFStreamer::EmitCOFFSymbolStorageClass (int StorageClass) [override, virtual]
Emit the storage class of the symbol.
Parameters:
StorageClass - The storage class the symbol should have.
Reimplemented from llvm::MCStreamer.
Definition at line 684 of file MCELFStreamer.cpp.
References llvm_unreachable.
void MCELFStreamer::EmitCOFFSymbolType (int Type) [override, virtual]
Emit the type of the symbol.
Parameters:
Type - A COFF type identifier (see COFF::SymbolType in X86COFF.h)
Reimplemented from llvm::MCStreamer.
Definition at line 688 of file MCELFStreamer.cpp.
References llvm_unreachable.
void MCELFStreamer::EmitCommonSymbol (MCSymbol * Symbol, uint64_t Size, unsigned ByteAlignment) [override, virtual]
Emit a common symbol.
Parameters:
Symbol - The common symbol to emit.
Size - The size of the common symbol.
ByteAlignment - The alignment of the symbol if non-zero. This must be a power of 2.
Implements llvm::MCStreamer.
Definition at line 302 of file MCELFStreamer.cpp.
References llvm::MCStreamer::AssignSection(), llvm::MCConstantExpr::create(), llvm::MCObjectStreamer::getAssembler(), llvm::MCStreamer::getContext(), llvm::MCAssembler::getContext(), llvm::MCContext::getELFSection(), llvm::MCAssembler::registerSymbol(), llvm::report_fatal_error(), llvm::ARMBuildAttrs::Section, llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_WRITE, llvm::ELF::SHT_NOBITS, llvm::ELF::STB_GLOBAL, llvm::ELF::STB_LOCAL, llvm::ELF::STT_OBJECT, and llvm::ARMBuildAttrs::Symbol.
Referenced by EmitLocalCommonSymbol(), and llvm::HexagonMCELFStreamer::HexagonMCEmitCommonSymbol().
void MCELFStreamer::emitELFSize (MCSymbolELF * Symbol, const MCExpr * Value) [override, virtual]
Emit an ELF .size directive.
This corresponds to an assembler statement such as: .size symbol, expression
Reimplemented from llvm::MCStreamer.
Definition at line 332 of file MCELFStreamer.cpp.
References llvm::MCSymbolELF::setSize().
void MCELFStreamer::EmitFileDirective (StringRef Filename) [override, virtual]
Switch to a new logical file.
This is used to implement the '.file "foo.c"' assembler directive.
Reimplemented from llvm::MCStreamer.
Definition at line 367 of file MCELFStreamer.cpp.
References llvm::MCAssembler::addFileName(), and llvm::MCObjectStreamer::getAssembler().
void MCELFStreamer::EmitIdent (StringRef IdentString) [override, virtual]
Emit the "identifiers" directive.
This implements the '.ident "version foo"' assembler directive.
Reimplemented from llvm::MCStreamer.
Definition at line 371 of file MCELFStreamer.cpp.
References llvm::MCObjectStreamer::EmitBytes(), llvm::MCStreamer::EmitIntValue(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getContext(), llvm::MCContext::getELFSection(), llvm::MCStreamer::PopSection(), llvm::MCStreamer::PushSection(), llvm::ELF::SHF_MERGE, llvm::ELF::SHF_STRINGS, llvm::ELF::SHT_PROGBITS, and llvm::MCStreamer::SwitchSection().
void MCELFStreamer::EmitLabel (MCSymbol * Symbol) [override, virtual]
Emit a label for Symbol into the current section.
This corresponds to an assembler statement such as: foo:
Parameters:
Symbol - The symbol to emit. A given symbol should only be emitted as a label once, and symbols emitted as a label should never be used in an assignment.
Reimplemented from llvm::MCObjectStreamer.
Reimplemented in llvm::MipsELFStreamer.
Definition at line 108 of file MCELFStreamer.cpp.
References llvm::MCSectionELF::getFlags(), llvm::ARMBuildAttrs::Section, llvm::ELF::SHF_TLS, llvm::ELF::STT_TLS, and llvm::ARMBuildAttrs::Symbol.
void MCELFStreamer::EmitLocalCommonSymbol (MCSymbol * Symbol, uint64_t Size, unsigned ByteAlignment) [override, virtual]
Emit a local common (.lcomm) symbol.
Parameters:
Symbol - The common symbol to emit.
Size - The size of the common symbol.
ByteAlignment - The alignment of the common symbol in bytes.
Reimplemented from llvm::MCStreamer.
Definition at line 336 of file MCELFStreamer.cpp.
References EmitCommonSymbol(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::registerSymbol(), llvm::ELF::STB_LOCAL, and llvm::ARMBuildAttrs::Symbol.
bool MCELFStreamer::EmitSymbolAttribute (MCSymbol * Symbol, MCSymbolAttr Attribute) [override, virtual]
Add the given Attribute to Symbol.
Implements llvm::MCStreamer.
Definition at line 199 of file MCELFStreamer.cpp.
References CombineSymbolTypes(), llvm::MCObjectStreamer::getAssembler(), llvm::MCStreamer::getCurrentSectionOnly(), llvm::MCAssembler::getIndirectSymbols(), llvm::MCSA_ELF_TypeCommon, llvm::MCSA_ELF_TypeFunction, llvm::MCSA_ELF_TypeGnuUniqueObject, llvm::MCSA_ELF_TypeIndFunction, llvm::MCSA_ELF_TypeNoType, llvm::MCSA_ELF_TypeObject, llvm::MCSA_ELF_TypeTLS, llvm::MCSA_Global, llvm::MCSA_Hidden, llvm::MCSA_IndirectSymbol, llvm::MCSA_Internal, llvm::MCSA_Invalid, llvm::MCSA_LazyReference, llvm::MCSA_Local, llvm::MCSA_NoDeadStrip, llvm::MCSA_PrivateExtern, llvm::MCSA_Protected, llvm::MCSA_Reference, llvm::MCSA_SymbolResolver, llvm::MCSA_Weak, llvm::MCSA_WeakDefAutoPrivate, llvm::MCSA_WeakDefinition, llvm::MCSA_WeakReference, llvm::MCAssembler::registerSymbol(), llvm::IndirectSymbolData::Section, llvm::ELF::STB_GLOBAL, llvm::ELF::STB_GNU_UNIQUE, llvm::ELF::STB_LOCAL, llvm::ELF::STB_WEAK, llvm::ELF::STT_FUNC, llvm::ELF::STT_GNU_IFUNC, llvm::ELF::STT_NOTYPE, llvm::ELF::STT_OBJECT, llvm::ELF::STT_TLS, llvm::ELF::STV_HIDDEN, llvm::ELF::STV_INTERNAL, llvm::ELF::STV_PROTECTED, llvm::ARMBuildAttrs::Symbol, and llvm::IndirectSymbolData::Symbol.
void MCELFStreamer::EmitSymbolDesc (MCSymbol * Symbol, unsigned DescValue) [override, virtual]
Set the DescValue for the Symbol.
Parameters:
Symbol - The symbol to have its n_desc field set.
DescValue - The value to set into the n_desc field.
Reimplemented from llvm::MCStreamer.
Definition at line 676 of file MCELFStreamer.cpp.
References llvm_unreachable.
void MCELFStreamer::EmitTBSSSymbol (MCSection * Section, MCSymbol * Symbol, uint64_t Size, unsigned ByteAlignment = 0) [override, virtual]
Emit a thread local bss (.tbss) symbol.
Parameters:
Section - The thread local common section.
Symbol - The thread local common symbol to emit.
Size - The size of the symbol.
ByteAlignment - The alignment of the thread local common symbol if non-zero. This must be a power of 2 on some targets.
Reimplemented from llvm::MCStreamer.
Definition at line 701 of file MCELFStreamer.cpp.
References llvm_unreachable.
void MCELFStreamer::EmitThumbFunc (MCSymbol * Func) [override, virtual]
Note in the output that the specified Func is a Thumb mode function (ARM target only).
Reimplemented from llvm::MCStreamer.
Definition at line 672 of file MCELFStreamer.cpp.
References llvm_unreachable.
void MCELFStreamer::EmitValueImpl (const MCExpr * Value, unsigned Size, const SMLoc & Loc = SMLoc()) [override, virtual]
Emit the expression Value into the output as a native integer of the given Size bytes.
This is used to implement assembler directives such as .word, .quad, etc.
Parameters:
Value - The value to emit.
Size - The size of the integer (in bytes) to emit. This must match a native machine width.
Loc - The location of the expression for error reporting.
Reimplemented from llvm::MCObjectStreamer.
Reimplemented in llvm::MipsELFStreamer.
Definition at line 346 of file MCELFStreamer.cpp.
References llvm::report_fatal_error().
void MCELFStreamer::EmitValueToAlignment (unsigned ByteAlignment, int64_t Value, unsigned ValueSize, unsigned MaxBytesToEmit) [override, virtual]
Emit some number of copies of Value until the byte alignment ByteAlignment is reached.
If the number of bytes need to emit for the alignment is not a multiple of ValueSize, then the contents of the emitted fill bytes is undefined.
This used to implement the .align assembler directive.
Parameters:
ByteAlignment - The alignment to reach. This must be a power of two on some targets.
Value - The value to use when filling bytes.
ValueSize - The size of the integer (in bytes) to emit for Value. This must match a native machine width.
MaxBytesToEmit - The maximum numbers of bytes to emit, or 0. If the alignment cannot be reached in this many bytes, no bytes are emitted.
Reimplemented from llvm::MCObjectStreamer.
Definition at line 354 of file MCELFStreamer.cpp.
References llvm::report_fatal_error().
void MCELFStreamer::EmitWeakReference (MCSymbol * Alias, const MCSymbol * Symbol) [override, virtual]
Emit an weak reference from Alias to Symbol.
This corresponds to an assembler statement such as: .weakref alias, symbol
Parameters:
Alias - The alias that is being created.
Symbol - The symbol being aliased.
Reimplemented from llvm::MCObjectStreamer.
Definition at line 173 of file MCELFStreamer.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::MCObjectStreamer::getAssembler(), llvm::MCStreamer::getContext(), llvm::MCAssembler::registerSymbol(), llvm::MCSymbol::setVariableValue(), and llvm::MCSymbolRefExpr::VK_WEAKREF.
void MCELFStreamer::EmitZerofill (MCSection * Section, MCSymbol * Symbol = nullptr, uint64_t Size = 0, unsigned ByteAlignment = 0) [override, virtual]
Emit the zerofill section and an optional symbol.
Parameters:
Section - The zerofill section to create and or to put the symbol
Symbol - The zerofill symbol to emit, if non-NULL.
Size - The size of the zerofill symbol.
ByteAlignment - The alignment of the zerofill symbol if non-zero. This must be a power of 2 on some targets.
Implements llvm::MCStreamer.
Definition at line 696 of file MCELFStreamer.cpp.
References llvm_unreachable.
void MCELFStreamer::EndCOFFSymbolDef () [override, virtual]
Marks the end of the symbol definition.
Reimplemented from llvm::MCStreamer.
Definition at line 692 of file MCELFStreamer.cpp.
References llvm_unreachable.
void MCELFStreamer::FinishImpl () [override, virtual]
Streamer specific finalization.
Reimplemented from llvm::MCObjectStreamer.
Definition at line 651 of file MCELFStreamer.cpp.
References llvm::MCObjectStreamer::EmitFrames(), Flush(), llvm::MCObjectStreamer::getAssembler(), llvm::MCStreamer::getCurrentSectionOnly(), and setSectionAlignmentForBundling().
void MCELFStreamer::Flush () [override, virtual]
Causes any cached state to be written out.
Reimplemented from llvm::MCStreamer.
Definition at line 628 of file MCELFStreamer.cpp.
References llvm::LCOMM::ByteAlignment, llvm::MCSection::getAlignment(), llvm::MCObjectStreamer::getAssembler(), llvm::MCSymbol::getSection(), llvm::MCAssembler::registerSection(), llvm::ARMBuildAttrs::Section, llvm::MCSection::setAlignment(), llvm::MCSymbol::setFragment(), and llvm::ARMBuildAttrs::Symbol.
Referenced by FinishImpl().
void MCELFStreamer::InitSections (bool NoExecStack) [override, virtual]
Create the default sections and set the initial one.
Reimplemented from llvm::MCStreamer.
Definition at line 89 of file MCELFStreamer.cpp.
References llvm::MCObjectStreamer::EmitCodeAlignment(), llvm::MCContext::getAsmInfo(), llvm::MCObjectFileInfo::getBSSSection(), llvm::MCStreamer::getContext(), llvm::MCObjectFileInfo::getDataSection(), llvm::MCAsmInfo::getNonexecutableStackSection(), llvm::MCContext::getObjectFileInfo(), llvm::MCObjectFileInfo::getTextSection(), and llvm::MCStreamer::SwitchSection().
void llvm::MCELFStreamer::reset () [inline, override, virtual]
state management
Reimplemented from llvm::MCObjectStreamer.
Definition at line 37 of file MCELFStreamer.h.
References llvm::SmallVectorImpl< T >::clear().
The documentation for this class was generated from the following files:
MCELFStreamer.h
MCELFStreamer.cpp