LLVM: llvm::raw_ostream Class Reference
llvm::raw_ostream Class Reference
This class implements an extremely fast bulk output stream that can *only* output to a stream.
#include <raw_ostream.h>
Public Types
enum Colors {
BLACK = 0, RED, GREEN, YELLOW,
BLUE, MAGENTA, CYAN, WHITE,
SAVEDCOLOR
}
Public Member Functions
raw_ostream (bool unbuffered=false)
virtual ~raw_ostream ()
uint64_t tell () const
tell - Return the current offset with the file.
void SetBuffered ()
Set the stream to be buffered, with an automatically determined buffer size.
void SetBufferSize (size_t Size)
Set the stream to be buffered, using the specified buffer size.
size_t GetBufferSize () const
void SetUnbuffered ()
Set the stream to be unbuffered.
size_t GetNumBytesInBuffer () const
void flush ()
raw_ostream & operator<< (char C)
raw_ostream & operator<< (unsigned char C)
raw_ostream & operator<< (signed char C)
raw_ostream & operator<< (StringRef Str)
raw_ostream & operator<< (const char *Str)
raw_ostream & operator<< (const std::string &Str)
raw_ostream & operator<< (const llvm::SmallVectorImpl< char > &Str)
raw_ostream & operator<< (unsigned long N)
raw_ostream & operator<< (long N)
raw_ostream & operator<< (unsigned long long N)
raw_ostream & operator<< (long long N)
raw_ostream & operator<< (const void *P)
raw_ostream & operator<< (unsigned int N)
raw_ostream & operator<< (int N)
raw_ostream & operator<< (double N)
raw_ostream & write_hex (unsigned long long N)
Output N in hexadecimal, without any prefix or padding.
raw_ostream & write_escaped (StringRef Str, bool UseHexEscapes=false)
Output Str, turning '\', '', '
', '"', and anything that doesn't satisfy std::isprint into an escape sequence.
raw_ostream & write (unsigned char C)
raw_ostream & write (const char *Ptr, size_t Size)
raw_ostream & operator<< (const format_object_base &Fmt)
raw_ostream & operator<< (const FormattedString &)
raw_ostream & operator<< (const FormattedNumber &)
raw_ostream & indent (unsigned NumSpaces)
indent - Insert 'NumSpaces' spaces.
virtual raw_ostream & changeColor (enum Colors Color, bool Bold=false, bool BG=false)
Changes the foreground color of text that will be output from this point forward.
virtual raw_ostream & resetColor ()
Resets the colors to terminal defaults.
virtual raw_ostream & reverseColor ()
Reverses the forground and background colors.
virtual bool is_displayed () const
This function determines if this stream is connected to a "tty" or "console" window.
virtual bool has_colors () const
This function determines if this stream is displayed and supports colors.
Protected Member Functions
void SetBuffer (char *BufferStart, size_t Size)
Use the provided buffer as the raw_ostream buffer.
virtual size_t preferred_buffer_size () const
Return an efficient buffer size for the underlying output mechanism.
const char * getBufferStart () const
Return the beginning of the current stream buffer, or 0 if the stream is unbuffered.
Detailed Description
This class implements an extremely fast bulk output stream that can *only* output to a stream.
It does not support seeking, reopening, rewinding, line buffered disciplines etc. It is a simple buffer that outputs a chunk at a time.
Definition at line 38 of file raw_ostream.h.
Member Enumeration Documentation
enum llvm::raw_ostream::Colors
Enumerator:
BLACK
RED
GREEN
YELLOW
BLUE
MAGENTA
CYAN
WHITE
SAVEDCOLOR
Definition at line 71 of file raw_ostream.h.
Constructor & Destructor Documentation
llvm::raw_ostream::raw_ostream (bool unbuffered = false) [inline, explicit]
Definition at line 83 of file raw_ostream.h.
raw_ostream::~raw_ostream () [virtual]
Definition at line 62 of file raw_ostream.cpp.
Member Function Documentation
virtual raw_ostream& llvm::raw_ostream::changeColor (enum Colors Color, bool Bold = false, bool BG = false) [inline, virtual]
Changes the foreground color of text that will be output from this point forward.
Parameters:
Color ANSI color to use, the special SAVEDCOLOR can be used to change only the bold attribute, and keep colors untouched
Bold bold/brighter text, default false
BG if true change the background, default: change foreground
Returns:
itself so it can be used within << invocations
Reimplemented in llvm::raw_fd_ostream, and llvm::formatted_raw_ostream.
Definition at line 234 of file raw_ostream.h.
Referenced by llvm::formatted_raw_ostream::changeColor(), llvm::SMDiagnostic::print(), and llvm::dwarf::syntax::WithColor::WithColor().
void llvm::raw_ostream::flush () [inline]
Definition at line 134 of file raw_ostream.h.
Referenced by llvm::raw_fd_ostream::changeColor(), llvm::raw_fd_ostream::close(), emitComments(), llvm::MCWinCOFFStreamer::EmitCommonSymbol(), llvm::AMDGPUAsmPrinter::EmitInstruction(), llvm::MCWinCOFFStreamer::EmitInstToData(), llvm::MCObjectStreamer::EmitInstToFragment(), llvm::MCJIT::emitObject(), getBlockName(), getBlockNum(), llvm::NVPTXAsmPrinter::getVirtualRegisterName(), LLVMDisasmInstruction(), LLVMGetDiagInfoDescription(), LLVMLinkModules(), LLVMParseBitcodeInContext(), LLVMParseIRInContext(), LLVMPrintModuleToString(), LLVMPrintTypeToString(), LLVMPrintValueToString(), LLVMTargetMachineEmit(), LLVMTargetMachineEmitToFile(), LLVMTargetMachineEmitToMemoryBuffer(), llvm::orc::SimpleCompiler::operator()(), PrintCurStackTrace(), llvm::opt::OptTable::PrintHelp(), llvm::AMDGPUInstPrinter::printInst(), llvm::PrintStatistics(), llvm::raw_fd_ostream::resetColor(), llvm::raw_fd_ostream::reverseColor(), llvm::raw_fd_ostream::seek(), SetBufferSize(), SetUnbuffered(), llvm::raw_string_ostream::str(), llvm::raw_svector_ostream::str(), llvm::sys::StrError(), llvm::InstrProfWriter::writeBuffer(), llvm::circular_raw_ostream::~circular_raw_ostream(), llvm::formatted_raw_ostream::~formatted_raw_ostream(), llvm::raw_fd_ostream::~raw_fd_ostream(), llvm::raw_null_ostream::~raw_null_ostream(), llvm::raw_os_ostream::~raw_os_ostream(), llvm::raw_string_ostream::~raw_string_ostream(), and llvm::raw_svector_ostream::~raw_svector_ostream().
size_t llvm::raw_ostream::GetBufferSize () const [inline]
Definition at line 108 of file raw_ostream.h.
References preferred_buffer_size().
const char* llvm::raw_ostream::getBufferStart () const [inline, protected]
Return the beginning of the current stream buffer, or 0 if the stream is unbuffered.
Definition at line 298 of file raw_ostream.h.
Referenced by llvm::formatted_raw_ostream::PadToColumn().
size_t llvm::raw_ostream::GetNumBytesInBuffer () const [inline]
Definition at line 126 of file raw_ostream.h.
Referenced by llvm::formatted_raw_ostream::PadToColumn(), llvm::raw_svector_ostream::resync(), and tell().
virtual bool llvm::raw_ostream::has_colors () const [inline, virtual]
This function determines if this stream is displayed and supports colors.
Reimplemented in llvm::raw_fd_ostream.
Definition at line 256 of file raw_ostream.h.
References is_displayed().
Referenced by llvm::SMDiagnostic::print(), llvm::dwarf::syntax::WithColor::WithColor(), and llvm::dwarf::syntax::WithColor::~WithColor().
raw_ostream & raw_ostream::indent (unsigned NumSpaces)
indent - Insert 'NumSpaces' spaces.
Definition at line 459 of file raw_ostream.cpp.
References llvm::array_lengthof(), fuzzer::min(), and write().
Referenced by llvm::IPDBSourceFile::dump(), llvm::DWARFDebugInfoEntryMinimal::dump(), llvm::DWARFDebugLoc::dump(), llvm::DWARFDebugLocDWO::dump(), llvm::LexicalScope::dump(), llvm::DWARFDebugInfoEntryMinimal::dumpAttribute(), llvm::RGPassManager::dumpPassStructure(), llvm::LPPassManager::dumpPassStructure(), llvm::Pass::dumpPassStructure(), llvm::FPPassManager::dumpPassStructure(), dumpRanges(), llvm::StringMatcher::Emit(), emitBasicBlockLoopComments(), operator<<(), llvm::formatted_raw_ostream::PadToColumn(), llvm::MemoryDepChecker::Dependence::print(), llvm::LoopBase< BlockT, LoopT >::print(), llvm::LoopAccessInfo::RuntimePointerCheck::print(), llvm::RegionBase< Tr >::print(), llvm::LoopAccessInfo::print(), llvm::LoopAccessAnalysis::print(), PrintChildLoopComment(), llvm::PrintDomTree(), llvm::cl::generic_parser_base::printGenericOptionDiff(), PrintHelpOptionList(), printHelpStr(), llvm::cl::generic_parser_base::printOptionInfo(), llvm::cl::basic_parser_impl::printOptionName(), PrintParentLoopComment(), llvm::DOTGraphTraits< RegionInfoPass * >::printRegionCluster(), printrWithDepthHelper(), and printWithSpacePadding().
virtual bool llvm::raw_ostream::is_displayed () const [inline, virtual]
This function determines if this stream is connected to a "tty" or "console" window.
That is, the output would be displayed to the user rather than being put on a pipe or stored in a file.
Reimplemented in llvm::raw_fd_ostream, and llvm::formatted_raw_ostream.
Definition at line 253 of file raw_ostream.h.
Referenced by llvm::CheckBitcodeOutputToConsole(), has_colors(), and llvm::formatted_raw_ostream::is_displayed().
raw_ostream& llvm::raw_ostream::operator<< (char C) [inline]
Definition at line 139 of file raw_ostream.h.
References llvm::C, and write().
Referenced by operator<<().
raw_ostream& llvm::raw_ostream::operator<< (unsigned char C) [inline]
Definition at line 146 of file raw_ostream.h.
References llvm::C, and write().
raw_ostream& llvm::raw_ostream::operator<< (signed char C) [inline]
Definition at line 153 of file raw_ostream.h.
References llvm::C, and write().
raw_ostream& llvm::raw_ostream::operator<< (StringRef Str) [inline]
Definition at line 160 of file raw_ostream.h.
References llvm::StringRef::data(), llvm::StringRef::size(), and write().
raw_ostream& llvm::raw_ostream::operator<< (const char * Str) [inline]
Definition at line 173 of file raw_ostream.h.
References operator<<().
raw_ostream& llvm::raw_ostream::operator<< (const std::string & Str) [inline]
Definition at line 180 of file raw_ostream.h.
References write().
raw_ostream& llvm::raw_ostream::operator<< (const llvm::SmallVectorImpl< char > & Str) [inline]
Definition at line 185 of file raw_ostream.h.
References write().
raw_ostream & raw_ostream::operator<< (unsigned long N)
Definition at line 108 of file raw_ostream.cpp.
References write().
raw_ostream & raw_ostream::operator<< (long N)
Definition at line 124 of file raw_ostream.cpp.
raw_ostream & raw_ostream::operator<< (unsigned long long N)
Definition at line 134 of file raw_ostream.cpp.
References write().
raw_ostream & raw_ostream::operator<< (long long N)
Definition at line 150 of file raw_ostream.cpp.
raw_ostream & raw_ostream::operator<< (const void * P)
Definition at line 220 of file raw_ostream.cpp.
References write_hex().
raw_ostream& llvm::raw_ostream::operator<< (unsigned int N) [inline]
Definition at line 194 of file raw_ostream.h.
raw_ostream& llvm::raw_ostream::operator<< (int N) [inline]
Definition at line 198 of file raw_ostream.h.
raw_ostream & raw_ostream::operator<< (double N)
Definition at line 226 of file raw_ostream.cpp.
References llvm::format(), and operator<<().
raw_ostream & raw_ostream::operator<< (const format_object_base & Fmt)
Definition at line 359 of file raw_ostream.cpp.
References llvm::SmallVectorTemplateCommon< T >::data(), llvm::format_object_base::print(), llvm::SmallVectorImpl< T >::resize(), and write().
raw_ostream & raw_ostream::operator<< (const FormattedString & FS)
Definition at line 399 of file raw_ostream.cpp.
References indent(), operator<<(), and llvm::StringRef::size().
raw_ostream & raw_ostream::operator<< (const FormattedNumber & FN)
Definition at line 410 of file raw_ostream.cpp.
References llvm::ARM_PROC::A, llvm::countLeadingZeros(), indent(), N, and write().
size_t raw_ostream::preferred_buffer_size () const [protected, virtual]
Return an efficient buffer size for the underlying output mechanism.
Definition at line 75 of file raw_ostream.cpp.
Referenced by GetBufferSize(), and SetBuffered().
virtual raw_ostream& llvm::raw_ostream::resetColor () [inline, virtual]
Resets the colors to terminal defaults.
Call this when you are done outputting colored text, or before program exit.
Reimplemented in llvm::raw_fd_ostream, and llvm::formatted_raw_ostream.
Definition at line 245 of file raw_ostream.h.
Referenced by llvm::SMDiagnostic::print(), llvm::formatted_raw_ostream::resetColor(), and llvm::dwarf::syntax::WithColor::~WithColor().
virtual raw_ostream& llvm::raw_ostream::reverseColor () [inline, virtual]
Reverses the forground and background colors.
Reimplemented in llvm::raw_fd_ostream, and llvm::formatted_raw_ostream.
Definition at line 248 of file raw_ostream.h.
Referenced by llvm::formatted_raw_ostream::reverseColor().
void llvm::raw_ostream::SetBuffer (char * BufferStart, size_t Size) [inline, protected]
Use the provided buffer as the raw_ostream buffer.
This is intended for use only by subclasses which can arrange for the output to go directly into the desired output buffer, instead of being copied on each flush.
Definition at line 289 of file raw_ostream.h.
Referenced by llvm::raw_svector_ostream::init(), and llvm::raw_svector_ostream::resync().
void raw_ostream::SetBuffered ()
Set the stream to be buffered, with an automatically determined buffer size.
Definition at line 80 of file raw_ostream.cpp.
References preferred_buffer_size(), SetBufferSize(), and SetUnbuffered().
Referenced by write().
void llvm::raw_ostream::SetBufferSize (size_t Size) [inline]
Set the stream to be buffered, using the specified buffer size.
Definition at line 103 of file raw_ostream.h.
References flush().
Referenced by SetBuffered().
void llvm::raw_ostream::SetUnbuffered () [inline]
Set the stream to be unbuffered.
When unbuffered, the stream will flush after every write. This routine will also flush the buffer immediately when the stream is being set to unbuffered.
Definition at line 121 of file raw_ostream.h.
References flush().
Referenced by SetBuffered().
uint64_t llvm::raw_ostream::tell () const [inline]
tell - Return the current offset with the file.
Definition at line 92 of file raw_ostream.h.
References GetNumBytesInBuffer().
Referenced by llvm::OnDiskChainedHashTableGenerator< Info >::Emit(), llvm::MCAssembler::Finish(), printLine(), printWithSpacePadding(), llvm::raw_pwrite_stream::pwrite(), llvm::writeArchive(), llvm::MachObjectWriter::writeDysymtabLoadCommand(), writeFragment(), llvm::MachObjectWriter::writeHeader(), llvm::MachObjectWriter::writeLinkeditLoadCommand(), llvm::MachObjectWriter::writeLinkerOptionsLoadCommand(), llvm::MachObjectWriter::writeObject(), llvm::MachObjectWriter::writeSection(), llvm::MCAssembler::writeSectionData(), llvm::MachObjectWriter::writeSegmentLoadCommand(), writeStringTable(), writeSymbolTable(), and llvm::MachObjectWriter::writeSymtabLoadCommand().
raw_ostream & raw_ostream::write (unsigned char C)
Definition at line 276 of file raw_ostream.cpp.
References llvm::C, LLVM_UNLIKELY, and SetBuffered().
Referenced by llvm::raw_fd_ostream::changeColor(), EmitGCCInlineAsmStr(), EmitMSInlineAsmStr(), llvm::circular_raw_ostream::flushBufferWithBanner(), indent(), operator<<(), llvm::raw_fd_ostream::resetColor(), llvm::raw_fd_ostream::reverseColor(), llvm::support::endian::Writer< endian >::write(), write(), write_hex(), llvm::yaml::BinaryRef::writeAsBinary(), llvm::yaml::BinaryRef::writeAsHex(), and llvm::WriteBitcodeToFile().
raw_ostream & raw_ostream::write (const char * Ptr, size_t Size)
Definition at line 296 of file raw_ostream.cpp.
References LLVM_UNLIKELY, SetBuffered(), and write().
raw_ostream & raw_ostream::write_escaped (StringRef Str, bool UseHexEscapes = false)
Output Str, turning '\', '', '
', '"', and anything that doesn't satisfy std::isprint into an escape sequence.
Definition at line 178 of file raw_ostream.cpp.
References llvm::StringRef::size().
Referenced by llvm::DWARFFormValue::dump(), llvm::StringToOffsetTable::EmitString(), and llvm::MCExternalSymbolizer::tryAddingPcLoadReferenceComment().
raw_ostream & raw_ostream::write_hex (unsigned long long N)
Output N in hexadecimal, without any prefix or padding.
Definition at line 160 of file raw_ostream.cpp.
References write().
Referenced by dumpDataAux(), operator<<(), llvm::DIEInteger::print(), llvm::AArch64InstPrinter::printAlignedLabel(), printHex32(), llvm::AArch64InstPrinter::printLogicalImm32(), llvm::AArch64InstPrinter::printLogicalImm64(), llvm::ARMInstPrinter::printNEONModImmOperand(), llvm::ARMInstPrinter::printOperand(), and llvm::HexagonShuffler::shuffle().
The documentation for this class was generated from the following files:
raw_ostream.h
raw_ostream.cpp