LLVM: llvm::Operator Class Reference
llvm::Operator Class Reference
This is a utility class that provides an abstraction for the common functionality between Instructions and ConstantExprs.
#include <Operator.h>
Public Member Functions
unsigned getOpcode () const
Return the opcode for this Instruction or ConstantExpr.
Static Public Member Functions
static unsigned getOpcode (const Value *V)
If V is an Instruction or ConstantExpr, return its opcode.
static bool classof (const Instruction *)
static bool classof (const ConstantExpr *)
static bool classof (const Value *V)
Protected Member Functions
~Operator () override
Detailed Description
This is a utility class that provides an abstraction for the common functionality between Instructions and ConstantExprs.
Definition at line 32 of file Operator.h.
Constructor & Destructor Documentation
llvm::Operator::~Operator () [override, protected]
Definition at line 143 of file User.cpp.
References llvm_unreachable.
Member Function Documentation
static bool llvm::Operator::classof (const Instruction *) [inline, static]
Reimplemented in llvm::ConcreteOperator< Operator, Instruction::ZExt >, llvm::ConcreteOperator< PossiblyExactOperator, Instruction::SDiv >, llvm::ConcreteOperator< Operator, Instruction::BitCast >, llvm::ConcreteOperator< OverflowingBinaryOperator, Instruction::Add >, llvm::ConcreteOperator< OverflowingBinaryOperator, Instruction::Sub >, llvm::ConcreteOperator< OverflowingBinaryOperator, Instruction::Shl >, llvm::ConcreteOperator< PossiblyExactOperator, Instruction::UDiv >, llvm::ConcreteOperator< PossiblyExactOperator, Instruction::LShr >, llvm::ConcreteOperator< Operator, Instruction::GetElementPtr >, llvm::ConcreteOperator< PossiblyExactOperator, Instruction::AShr >, llvm::ConcreteOperator< OverflowingBinaryOperator, Instruction::Mul >, llvm::ConcreteOperator< Operator, Instruction::PtrToInt >, llvm::FPMathOperator, llvm::PossiblyExactOperator, and llvm::OverflowingBinaryOperator.
Definition at line 64 of file Operator.h.
static bool llvm::Operator::classof (const ConstantExpr *) [inline, static]
Reimplemented in llvm::ConcreteOperator< Operator, Instruction::ZExt >, llvm::ConcreteOperator< PossiblyExactOperator, Instruction::SDiv >, llvm::ConcreteOperator< Operator, Instruction::BitCast >, llvm::ConcreteOperator< OverflowingBinaryOperator, Instruction::Add >, llvm::ConcreteOperator< OverflowingBinaryOperator, Instruction::Sub >, llvm::ConcreteOperator< OverflowingBinaryOperator, Instruction::Shl >, llvm::ConcreteOperator< PossiblyExactOperator, Instruction::UDiv >, llvm::ConcreteOperator< PossiblyExactOperator, Instruction::LShr >, llvm::ConcreteOperator< Operator, Instruction::GetElementPtr >, llvm::ConcreteOperator< PossiblyExactOperator, Instruction::AShr >, llvm::ConcreteOperator< OverflowingBinaryOperator, Instruction::Mul >, llvm::ConcreteOperator< Operator, Instruction::PtrToInt >, llvm::PossiblyExactOperator, and llvm::OverflowingBinaryOperator.
Definition at line 65 of file Operator.h.
static bool llvm::Operator::classof (const Value * V) [inline, static]
Reimplemented from llvm::User.
Reimplemented in llvm::ConcreteOperator< Operator, Instruction::ZExt >, llvm::ConcreteOperator< PossiblyExactOperator, Instruction::SDiv >, llvm::ConcreteOperator< Operator, Instruction::BitCast >, llvm::ConcreteOperator< OverflowingBinaryOperator, Instruction::Add >, llvm::ConcreteOperator< OverflowingBinaryOperator, Instruction::Sub >, llvm::ConcreteOperator< OverflowingBinaryOperator, Instruction::Shl >, llvm::ConcreteOperator< PossiblyExactOperator, Instruction::UDiv >, llvm::ConcreteOperator< PossiblyExactOperator, Instruction::LShr >, llvm::ConcreteOperator< Operator, Instruction::GetElementPtr >, llvm::ConcreteOperator< PossiblyExactOperator, Instruction::AShr >, llvm::ConcreteOperator< OverflowingBinaryOperator, Instruction::Mul >, llvm::ConcreteOperator< Operator, Instruction::PtrToInt >, llvm::FPMathOperator, llvm::PossiblyExactOperator, and llvm::OverflowingBinaryOperator.
Definition at line 66 of file Operator.h.
unsigned llvm::Operator::getOpcode () const [inline]
Return the opcode for this Instruction or ConstantExpr.
Definition at line 48 of file Operator.h.
References I.
Referenced by llvm::CannotBeNegativeZero(), llvm::CannotBeOrderedLessThanZero(), computeKnownBitsFromOperator(), llvm::ComputeMultiple(), ComputeNumSignBits(), ComputeSpeculationCost(), DecomposeGEPExpression(), llvm::GetPointerBaseWithConstantOffset(), llvm::GetUnderlyingObject(), getUnderlyingObjectFromInt(), getUnderlyingObjects(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getUserCost(), INITIALIZE_PASS(), llvm::isSafeToSpeculativelyExecute(), llvm::Value::stripAndAccumulateInBoundsConstantOffsets(), and stripAndComputeConstantOffsets().
static unsigned llvm::Operator::getOpcode (const Value * V) [inline, static]
If V is an Instruction or ConstantExpr, return its opcode.
Otherwise return UserOp1.
Definition at line 56 of file Operator.h.
References llvm::WinEH::CE, I, and llvm::UserOp1.
The documentation for this class was generated from the following files:
Operator.h
User.cpp