LLVM: llvm::coverage::CounterMappingContext Class Reference
llvm::coverage::CounterMappingContext Class Reference
A Counter mapping context is used to connect the counters, expressions and the obtained counter values.
#include <CoverageMapping.h>
Public Member Functions
CounterMappingContext (ArrayRef< CounterExpression > Expressions, ArrayRef< uint64_t > CounterValues=ArrayRef< uint64_t >())
void setCounts (ArrayRef< uint64_t > Counts)
void dump (const Counter &C, llvm::raw_ostream &OS) const
void dump (const Counter &C) const
ErrorOr< int64_t > evaluate (const Counter &C) const
Return the number of times that a region of code associated with this counter was executed.
Detailed Description
A Counter mapping context is used to connect the counters, expressions and the obtained counter values.
Definition at line 233 of file CoverageMapping.h.
Constructor & Destructor Documentation
llvm::coverage::CounterMappingContext::CounterMappingContext (ArrayRef< CounterExpression > Expressions, ArrayRef< uint64_t > CounterValues = ArrayRef<uint64_t>()) [inline]
Definition at line 238 of file CoverageMapping.h.
Member Function Documentation
void CounterMappingContext::dump (const Counter & C, llvm::raw_ostream & OS) const
Definition at line 123 of file CoverageMapping.cpp.
References llvm::coverage::Counter::CounterValueReference, llvm::ArrayRef< T >::empty(), evaluate(), llvm::coverage::Counter::Expression, llvm::coverage::Counter::getCounterID(), llvm::coverage::Counter::getExpressionID(), llvm::coverage::Counter::getKind(), llvm::ArrayRef< T >::size(), llvm::coverage::CounterExpression::Subtract, and llvm::coverage::Counter::Zero.
void llvm::coverage::CounterMappingContext::dump (const Counter & C) const [inline]
Definition at line 245 of file CoverageMapping.h.
References llvm::dbgs(), and dump().
Referenced by dump().
ErrorOr< int64_t > CounterMappingContext::evaluate (const Counter & C) const
Return the number of times that a region of code associated with this counter was executed.
Definition at line 152 of file CoverageMapping.cpp.
References llvm::argument_out_of_domain, llvm::coverage::Counter::CounterValueReference, llvm::coverage::Counter::Expression, llvm::coverage::Counter::getCounterID(), llvm::coverage::Counter::getExpressionID(), llvm::coverage::Counter::getKind(), llvm_unreachable, llvm::make_error_code(), llvm::ArrayRef< T >::size(), llvm::coverage::CounterExpression::Subtract, and llvm::coverage::Counter::Zero.
Referenced by dump(), and llvm::coverage::CoverageMapping::load().
void llvm::coverage::CounterMappingContext::setCounts (ArrayRef< uint64_t > Counts) [inline]
Definition at line 242 of file CoverageMapping.h.
Referenced by llvm::coverage::CoverageMapping::load().
The documentation for this class was generated from the following files:
CoverageMapping.h
CoverageMapping.cpp