LLVM: llvm::SparcELFTargetObjectFile Class Reference
llvm::SparcELFTargetObjectFile Class Reference
#include <SparcTargetObjectFile.h>
Public Member Functions
SparcELFTargetObjectFile ()
const MCExpr * getTTypeGlobalReference (const GlobalValue *GV, unsigned Encoding, Mangler &Mang, const TargetMachine &TM, MachineModuleInfo *MMI, MCStreamer &Streamer) const override
Return an MCExpr to use for a reference to the specified type info global variable from exception handling information.
Detailed Description
Definition at line 20 of file SparcTargetObjectFile.h.
Constructor & Destructor Documentation
llvm::SparcELFTargetObjectFile::SparcELFTargetObjectFile () [inline]
Definition at line 22 of file SparcTargetObjectFile.h.
Member Function Documentation
const MCExpr * SparcELFTargetObjectFile::getTTypeGlobalReference (const GlobalValue * GV, unsigned Encoding, Mangler & Mang, const TargetMachine & TM, MachineModuleInfo * MMI, MCStreamer & Streamer) const [override, virtual]
Return an MCExpr to use for a reference to the specified type info global variable from exception handling information.
Reimplemented from llvm::TargetLoweringObjectFileELF.
Definition at line 18 of file SparcTargetObjectFile.cpp.
References llvm::SparcMCExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::dwarf::DW_EH_PE_pcrel, llvm::TargetLoweringObjectFile::getContext(), llvm::MachineModuleInfoELF::getGVStubEntry(), llvm::MachineModuleInfo::getObjFileInfo(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer(), llvm::TargetMachine::getSymbol(), llvm::TargetLoweringObjectFile::getSymbolWithGlobalValueBase(), llvm::GlobalValue::hasLocalLinkage(), and llvm::SparcMCExpr::VK_Sparc_R_DISP32.
The documentation for this class was generated from the following files:
SparcTargetObjectFile.h
SparcTargetObjectFile.cpp