LLVM: llvm::SystemZAsmPrinter Class Reference
llvm::SystemZAsmPrinter Class Reference
#include <SystemZAsmPrinter.h>
Public Member Functions
SystemZAsmPrinter (TargetMachine &TM, std::unique_ptr< MCStreamer > Streamer)
const char * getPassName () const override
getPassName - Return a nice clean name for a pass.
void EmitInstruction (const MachineInstr *MI) override
Targets should implement this to emit instructions.
void EmitMachineConstantPoolValue (MachineConstantPoolValue *MCPV) override
bool PrintAsmOperand (const MachineInstr *MI, unsigned OpNo, unsigned AsmVariant, const char *ExtraCode, raw_ostream &OS) override
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
bool PrintAsmMemoryOperand (const MachineInstr *MI, unsigned OpNo, unsigned AsmVariant, const char *ExtraCode, raw_ostream &OS) override
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address.
Detailed Description
Definition at line 24 of file SystemZAsmPrinter.h.
Constructor & Destructor Documentation
llvm::SystemZAsmPrinter::SystemZAsmPrinter (TargetMachine & TM, std::unique_ptr< MCStreamer > Streamer) [inline]
Definition at line 26 of file SystemZAsmPrinter.h.
Member Function Documentation
void SystemZAsmPrinter::EmitInstruction (const MachineInstr *) [override, virtual]
Targets should implement this to emit instructions.
Reimplemented from llvm::AsmPrinter.
Definition at line 104 of file SystemZAsmPrinter.cpp.
References llvm::MCInstBuilder::addExpr(), llvm::MCInstBuilder::addImm(), llvm::MCInstBuilder::addReg(), llvm::ISD::BR, llvm::AsmPrinter::EmitToStreamer(), llvm::MachineFunction::getContext(), getGlobalOffsetTable(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::SystemZMC::getRegAsGR32(), llvm::SystemZMC::getRegAsGR64(), llvm::SystemZMC::getRegAsGRH32(), llvm::SystemZMC::getRegAsVR128(), llvm::MachineFunction::getSubtarget(), getTLSGetOffset(), llvm::ARMCP::GOT, llvm::SystemZSubtarget::hasFastSerialization(), LOWER_HIGH, LOWER_LOW, lowerRIEfLow(), lowerSubvectorLoad(), lowerSubvectorStore(), llvm::AsmPrinter::MF, llvm::AsmPrinter::OutStreamer, llvm::MCID::Return, llvm::SystemZISD::TLS_GDCALL, llvm::SystemZISD::TLS_LDCALL, llvm::MCSymbolRefExpr::VK_PLT, llvm::MCSymbolRefExpr::VK_TLSGD, and llvm::MCSymbolRefExpr::VK_TLSLDM.
void SystemZAsmPrinter::EmitMachineConstantPoolValue (MachineConstantPoolValue * MCPV) [override, virtual]
Reimplemented from llvm::AsmPrinter.
Definition at line 284 of file SystemZAsmPrinter.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::TargetMachine::getDataLayout(), getModifierVariantKind(), llvm::AsmPrinter::getSymbol(), llvm::DataLayout::getTypeAllocSize(), llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, and llvm::AsmPrinter::TM.
const char* llvm::SystemZAsmPrinter::getPassName () const [inline, override, virtual]
getPassName - Return a nice clean name for a pass.
This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 30 of file SystemZAsmPrinter.h.
bool SystemZAsmPrinter::PrintAsmMemoryOperand (const MachineInstr * MI, unsigned OpNo, unsigned AsmVariant, const char * ExtraCode, raw_ostream & OS) [override, virtual]
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address.
Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Reimplemented from llvm::AsmPrinter.
Definition at line 313 of file SystemZAsmPrinter.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), and llvm::SystemZInstPrinter::printAddress().
bool SystemZAsmPrinter::PrintAsmOperand (const MachineInstr * MI, unsigned OpNo, unsigned AsmVariant, const char * ExtraCode, raw_ostream & O) [override, virtual]
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
PrintAsmOperand - Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Targets should override this to format as appropriate.
Reimplemented from llvm::AsmPrinter.
Definition at line 296 of file SystemZAsmPrinter.cpp.
References llvm::MachineFunction::getContext(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::isImm(), llvm::AsmPrinter::MAI, llvm::AsmPrinter::MF, and printOperand().
The documentation for this class was generated from the following files:
SystemZAsmPrinter.h
SystemZAsmPrinter.cpp