LLVM: llvm::DINamespace Class Reference
llvm::DINamespace Class Reference
#include <DebugInfoMetadata.h>
Public Member Functions
DEFINE_MDNODE_GET (DINamespace,(DIScope *Scope, DIFile *File, StringRef Name, unsigned Line),(Scope, File, Name, Line)) DEFINE_MDNODE_GET(DINamespace
Metadata Metadata MDString
unsigned Line TempDINamespace clone () const
Create a (temporary) clone of this.
unsigned getLine () const
DIScope * getScope () const
StringRef getName () const
Metadata * getRawScope () const
MDString * getRawName () const
Static Public Member Functions
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
Public Attributes
Metadata * Scope
Metadata Metadata * File
Metadata Metadata MDString * Name
Metadata Metadata MDString unsigned Line
Metadata Metadata MDString unsigned Scope
Metadata Metadata MDString unsigned File
Metadata Metadata MDString unsigned Name
Friends
class LLVMContextImpl
class MDNode
Detailed Description
Definition at line 1576 of file DebugInfoMetadata.h.
Member Function Documentation
static bool llvm::DINamespace::classof (const Metadata * MD) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::DIScope.
Definition at line 1621 of file DebugInfoMetadata.h.
References llvm::Metadata::DINamespaceKind, and llvm::Metadata::getMetadataID().
Metadata Metadata MDString unsigned Line TempDINamespace llvm::DINamespace::clone () const [inline]
Create a (temporary) clone of this.
Reimplemented from llvm::MDNode.
Definition at line 1612 of file DebugInfoMetadata.h.
llvm::DINamespace::DEFINE_MDNODE_GET (DINamespace , (DIScope *Scope, DIFile *File, StringRef Name,unsigned Line) , (Scope, File, Name, Line))
unsigned llvm::DINamespace::getLine () const [inline]
Definition at line 1614 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfUnit::addSourceLine(), llvm::MDNodeKeyImpl< DINamespace >::isKeyOf(), and WriteDINamespace().
StringRef llvm::DINamespace::getName () const [inline]
Reimplemented from llvm::DIScope.
Definition at line 1616 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
Referenced by llvm::DwarfUnit::getOrCreateNameSpace(), and llvm::MDNodeKeyImpl< DINamespace >::isKeyOf().
MDString* llvm::DINamespace::getRawName () const [inline]
Definition at line 1619 of file DebugInfoMetadata.h.
Referenced by WriteDINamespace().
Metadata* llvm::DINamespace::getRawScope () const [inline]
Definition at line 1618 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getScope(), and llvm::MDNodeKeyImpl< DINamespace >::isKeyOf().
DIScope* llvm::DINamespace::getScope () const [inline]
Reimplemented from llvm::DIScope.
Definition at line 1615 of file DebugInfoMetadata.h.
References getRawScope().
Referenced by llvm::DwarfUnit::getOrCreateNameSpace(), and WriteDINamespace().
Friends And Related Function Documentation
friend class LLVMContextImpl [friend]
Reimplemented from llvm::DINode.
Definition at line 1577 of file DebugInfoMetadata.h.
friend class MDNode [friend]
Reimplemented from llvm::DINode.
Definition at line 1578 of file DebugInfoMetadata.h.
Member Data Documentation
Metadata Metadata* llvm::DINamespace::File
Definition at line 1608 of file DebugInfoMetadata.h.
Metadata Metadata MDString unsigned llvm::DINamespace::File
Definition at line 1608 of file DebugInfoMetadata.h.
Metadata Metadata MDString unsigned llvm::DINamespace::Line
Definition at line 1608 of file DebugInfoMetadata.h.
Metadata Metadata MDString* llvm::DINamespace::Name
Definition at line 1608 of file DebugInfoMetadata.h.
Metadata Metadata MDString unsigned llvm::DINamespace::Name
Definition at line 1608 of file DebugInfoMetadata.h.
Metadata* llvm::DINamespace::Scope
Definition at line 1608 of file DebugInfoMetadata.h.
Metadata Metadata MDString unsigned llvm::DINamespace::Scope
Definition at line 1608 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
DebugInfoMetadata.h
DebugInfoMetadata.cpp