LLVM: llvm::object::MachOBindEntry Class Reference
llvm::object::MachOBindEntry Class Reference
MachOBindEntry encapsulates the current state in the decompression of binding opcodes.
#include <MachO.h>
Public Types
enum Kind { Regular, Lazy, Weak }
Public Member Functions
MachOBindEntry (ArrayRef< uint8_t > Opcodes, bool is64Bit, MachOBindEntry::Kind)
uint32_t segmentIndex () const
uint64_t segmentOffset () const
StringRef typeName () const
StringRef symbolName () const
uint32_t flags () const
int64_t addend () const
int ordinal () const
bool operator== (const MachOBindEntry &) const
void moveNext ()
Friends
class MachOObjectFile
Detailed Description
MachOBindEntry encapsulates the current state in the decompression of binding opcodes.
This allows you to iterate through the compressed table of bindings using: for (const llvm::object::MachOBindEntry &Entry : Obj->bindTable()) { }
Definition at line 144 of file Object/MachO.h.
Member Enumeration Documentation
enum llvm::object::MachOBindEntry::Kind
Enumerator:
Regular
Lazy
Weak
Definition at line 146 of file Object/MachO.h.
Constructor & Destructor Documentation
MachOBindEntry::MachOBindEntry (ArrayRef< uint8_t > Opcodes, bool is64Bit, MachOBindEntry::Kind BK)
Definition at line 1641 of file MachOObjectFile.cpp.
Member Function Documentation
int64_t MachOBindEntry::addend () const
Definition at line 1865 of file MachOObjectFile.cpp.
uint32_t MachOBindEntry::flags () const
Definition at line 1867 of file MachOObjectFile.cpp.
void MachOBindEntry::moveNext ()
Definition at line 1659 of file MachOObjectFile.cpp.
References llvm::MachO::BIND_IMMEDIATE_MASK, llvm::MachO::BIND_OPCODE_ADD_ADDR_ULEB, llvm::MachO::BIND_OPCODE_DO_BIND, llvm::MachO::BIND_OPCODE_DO_BIND_ADD_ADDR_IMM_SCALED, llvm::MachO::BIND_OPCODE_DO_BIND_ADD_ADDR_ULEB, llvm::MachO::BIND_OPCODE_DO_BIND_ULEB_TIMES_SKIPPING_ULEB, llvm::MachO::BIND_OPCODE_DONE, llvm::MachO::BIND_OPCODE_MASK, llvm::MachO::BIND_OPCODE_SET_ADDEND_SLEB, llvm::MachO::BIND_OPCODE_SET_DYLIB_ORDINAL_IMM, llvm::MachO::BIND_OPCODE_SET_DYLIB_ORDINAL_ULEB, llvm::MachO::BIND_OPCODE_SET_DYLIB_SPECIAL_IMM, llvm::MachO::BIND_OPCODE_SET_SEGMENT_AND_OFFSET_ULEB, llvm::MachO::BIND_OPCODE_SET_SYMBOL_TRAILING_FLAGS_IMM, llvm::MachO::BIND_OPCODE_SET_TYPE_IMM, llvm::MachO::BIND_SYMBOL_FLAGS_NON_WEAK_DEFINITION, llvm::dbgs(), DEBUG_WITH_TYPE, llvm::ArrayRef< T >::end(), llvm::format(), P, and llvm::Weak.
bool MachOBindEntry::operator== (const MachOBindEntry & Other) const
Definition at line 1871 of file MachOObjectFile.cpp.
int MachOBindEntry::ordinal () const
Definition at line 1869 of file MachOObjectFile.cpp.
uint32_t MachOBindEntry::segmentIndex () const
Definition at line 1847 of file MachOObjectFile.cpp.
uint64_t MachOBindEntry::segmentOffset () const
Definition at line 1849 of file MachOObjectFile.cpp.
StringRef MachOBindEntry::symbolName () const
Definition at line 1863 of file MachOObjectFile.cpp.
StringRef MachOBindEntry::typeName () const
Definition at line 1851 of file MachOObjectFile.cpp.
References llvm::MachO::BIND_TYPE_POINTER, llvm::MachO::BIND_TYPE_TEXT_ABSOLUTE32, and llvm::MachO::BIND_TYPE_TEXT_PCREL32.
Friends And Related Function Documentation
friend class MachOObjectFile [friend]
Definition at line 163 of file Object/MachO.h.
The documentation for this class was generated from the following files:
Object/MachO.h
MachOObjectFile.cpp