LLVM: llvm::MipsTargetMachine Class Reference
llvm::MipsTargetMachine Class Reference
#include <MipsTargetMachine.h>
Public Member Functions
MipsTargetMachine (const Target &T, const Triple &TT, StringRef CPU, StringRef FS, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL, bool isLittle)
~MipsTargetMachine () override
TargetIRAnalysis getTargetIRAnalysis () override
Get a TargetIRAnalysis implementation for the target.
const MipsSubtarget * getSubtargetImpl () const
const MipsSubtarget * getSubtargetImpl (const Function &F) const override
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
void resetSubtarget (MachineFunction *MF)
Reset the subtarget for the Mips target.
TargetPassConfig * createPassConfig (PassManagerBase &PM) override
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
TargetLoweringObjectFile * getObjFileLowering () const override
bool isLittleEndian () const
const MipsABIInfo & getABI () const
Detailed Description
Definition at line 29 of file MipsTargetMachine.h.
Constructor & Destructor Documentation
MipsTargetMachine::MipsTargetMachine (const Target & T, const Triple & TT, StringRef CPU, StringRef FS, const TargetOptions & Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL, bool isLittle)
Definition at line 85 of file MipsTargetMachine.cpp.
References llvm::LLVMTargetMachine::initAsmInfo().
MipsTargetMachine::~MipsTargetMachine () [override]
Definition at line 103 of file MipsTargetMachine.cpp.
Member Function Documentation
TargetPassConfig * MipsTargetMachine::createPassConfig (PassManagerBase & PM) [override, virtual]
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
createPassConfig - Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
Targets may override this to extend TargetPassConfig.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 204 of file MipsTargetMachine.cpp.
const MipsABIInfo& llvm::MipsTargetMachine::getABI () const [inline]
Definition at line 68 of file MipsTargetMachine.h.
Referenced by llvm::MipsAsmPrinter::EmitStartOfAsmFile(), and llvm::MipsSubtarget::getABI().
TargetLoweringObjectFile* llvm::MipsTargetMachine::getObjFileLowering () const [inline, override, virtual]
Reimplemented from llvm::TargetMachine.
Definition at line 63 of file MipsTargetMachine.h.
const MipsSubtarget* llvm::MipsTargetMachine::getSubtargetImpl () const [inline]
Definition at line 49 of file MipsTargetMachine.h.
Referenced by resetSubtarget().
const MipsSubtarget * MipsTargetMachine::getSubtargetImpl (const Function &) const [override, virtual]
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
Reimplemented from llvm::TargetMachine.
Definition at line 124 of file MipsTargetMachine.cpp.
References llvm::StringRef::empty(), llvm::FS, llvm::Function::getFnAttribute(), llvm::Attribute::getValueAsString(), llvm::Attribute::hasAttribute(), llvm::Function::hasFnAttribute(), I, llvm::Attribute::None, llvm::TargetMachine::resetTargetOptions(), llvm::StringRef::str(), llvm::TargetMachine::TargetCPU, llvm::TargetMachine::TargetFS, and llvm::TargetMachine::TargetTriple.
TargetIRAnalysis MipsTargetMachine::getTargetIRAnalysis () [override, virtual]
Get a TargetIRAnalysis implementation for the target.
This analysis will produce a TTI result which uses the common code generator to answer queries about the IR.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 235 of file MipsTargetMachine.cpp.
References llvm::MipsSubtarget::allowMixed16_32(), DEBUG, llvm::errs(), F(), and llvm::TargetMachine::getDataLayout().
bool llvm::MipsTargetMachine::isLittleEndian () const [inline]
Definition at line 67 of file MipsTargetMachine.h.
Referenced by assureFPCallStub(), createFPFnStub(), and llvm::MipsAsmPrinter::EmitStartOfAsmFile().
void MipsTargetMachine::resetSubtarget (MachineFunction * MF)
Reset the subtarget for the Mips target.
Definition at line 165 of file MipsTargetMachine.cpp.
References llvm::dbgs(), DEBUG, llvm::MachineFunction::getFunction(), getSubtargetImpl(), and llvm::MachineFunction::setSubtarget().
The documentation for this class was generated from the following files:
MipsTargetMachine.h
MipsTargetMachine.cpp