LLVM: llvm::XCoreSubtarget Class Reference
llvm::XCoreSubtarget Class Reference
#include <XCoreSubtarget.h>
Public Member Functions
XCoreSubtarget (const Triple &TT, const std::string &CPU, const std::string &FS, const TargetMachine &TM)
This constructor initializes the data members to match that of the specified triple.
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
const XCoreInstrInfo * getInstrInfo () const override
const XCoreFrameLowering * getFrameLowering () const override
const XCoreTargetLowering * getTargetLowering () const override
const XCoreSelectionDAGInfo * getSelectionDAGInfo () const override
const TargetRegisterInfo * getRegisterInfo () const override
Detailed Description
Definition at line 32 of file XCoreSubtarget.h.
Constructor & Destructor Documentation
XCoreSubtarget::XCoreSubtarget (const Triple & TT, const std::string & CPU, const std::string & FS, const TargetMachine & TM)
This constructor initializes the data members to match that of the specified triple.
Definition at line 28 of file XCoreSubtarget.cpp.
Member Function Documentation
const XCoreFrameLowering* llvm::XCoreSubtarget::getFrameLowering () const [inline, override]
Definition at line 51 of file XCoreSubtarget.h.
const XCoreInstrInfo* llvm::XCoreSubtarget::getInstrInfo () const [inline, override]
Definition at line 50 of file XCoreSubtarget.h.
Referenced by llvm::XCoreTargetLowering::EmitInstrWithCustomInserter().
const TargetRegisterInfo* llvm::XCoreSubtarget::getRegisterInfo () const [inline, override]
Definition at line 60 of file XCoreSubtarget.h.
References llvm::XCoreInstrInfo::getRegisterInfo().
Referenced by llvm::XCoreTargetLowering::XCoreTargetLowering().
const XCoreSelectionDAGInfo* llvm::XCoreSubtarget::getSelectionDAGInfo () const [inline, override]
Definition at line 57 of file XCoreSubtarget.h.
const XCoreTargetLowering* llvm::XCoreSubtarget::getTargetLowering () const [inline, override]
Definition at line 54 of file XCoreSubtarget.h.
void llvm::XCoreSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
Definition of function is auto generated by tblgen.
The documentation for this class was generated from the following files:
XCoreSubtarget.h
XCoreSubtarget.cpp