LLVM: llvm::TargetIndexSDNode Class Reference
llvm::TargetIndexSDNode Class Reference
Completely target-dependent object reference.
#include <SelectionDAGNodes.h>
Public Member Functions
TargetIndexSDNode (int Idx, EVT VT, int64_t Ofs, unsigned char TF)
unsigned char getTargetFlags () const
int getIndex () const
int64_t getOffset () const
Static Public Member Functions
static bool classof (const SDNode *N)
Friends
class SelectionDAG
Detailed Description
Completely target-dependent object reference.
Definition at line 1603 of file SelectionDAGNodes.h.
Constructor & Destructor Documentation
llvm::TargetIndexSDNode::TargetIndexSDNode (int Idx, EVT VT, int64_t Ofs, unsigned char TF) [inline]
Definition at line 1610 of file SelectionDAGNodes.h.
Member Function Documentation
static bool llvm::TargetIndexSDNode::classof (const SDNode * N) [inline, static]
Definition at line 1619 of file SelectionDAGNodes.h.
References llvm::SDNode::getOpcode().
int llvm::TargetIndexSDNode::getIndex () const [inline]
Definition at line 1616 of file SelectionDAGNodes.h.
Referenced by AddNodeIDCustom().
int64_t llvm::TargetIndexSDNode::getOffset () const [inline]
Definition at line 1617 of file SelectionDAGNodes.h.
Referenced by AddNodeIDCustom().
unsigned char llvm::TargetIndexSDNode::getTargetFlags () const [inline]
Definition at line 1615 of file SelectionDAGNodes.h.
Referenced by AddNodeIDCustom().
Friends And Related Function Documentation
friend class SelectionDAG [friend]
Reimplemented from llvm::SDNode.
Definition at line 1607 of file SelectionDAGNodes.h.
The documentation for this class was generated from the following file:
SelectionDAGNodes.h