LLVM: llvm::MDNodeOpsKey Class Reference
llvm::MDNodeOpsKey Class Reference
Structure for hashing arbitrary MDNode operands.
#include <LLVMContextImpl.h>
Public Member Functions
unsigned getHash () const
Protected Member Functions
MDNodeOpsKey (ArrayRef< Metadata * > Ops)
template<class NodeTy >
MDNodeOpsKey (const NodeTy *N, unsigned Offset=0)
template<class NodeTy >
bool compareOps (const NodeTy *RHS, unsigned Offset=0) const
Static Protected Member Functions
static unsigned calculateHash (MDNode *N, unsigned Offset=0)
Detailed Description
Structure for hashing arbitrary MDNode operands.
Definition at line 171 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
llvm::MDNodeOpsKey::MDNodeOpsKey (ArrayRef< Metadata * > Ops) [inline, protected]
Definition at line 178 of file LLVMContextImpl.h.
template<class NodeTy > llvm::MDNodeOpsKey::MDNodeOpsKey (const NodeTy * N, unsigned Offset = 0) [inline, protected]
Definition at line 182 of file LLVMContextImpl.h.
Member Function Documentation
unsigned MDNodeOpsKey::calculateHash (MDNode * N, unsigned Offset = 0) [static, protected]
Definition at line 204 of file LLVMContextImpl.cpp.
References llvm::hash_combine_range(), llvm::MDNode::op_begin(), and llvm::MDNode::op_end().
Referenced by llvm::MDNodeKeyImpl< MDTuple >::calculateHash(), and llvm::MDNodeKeyImpl< GenericDINode >::calculateHash().
template<class NodeTy > bool llvm::MDNodeOpsKey::compareOps (const NodeTy * RHS, unsigned Offset = 0) const [inline, protected]
Definition at line 186 of file LLVMContextImpl.h.
References llvm::ArrayRef< T >::empty(), and getHash().
unsigned llvm::MDNodeOpsKey::getHash () const [inline]
Definition at line 208 of file LLVMContextImpl.h.
Referenced by compareOps().
The documentation for this class was generated from the following files:
LLVMContextImpl.h
LLVMContextImpl.cpp