LLVM: llvm::GenericDINode Class Reference
llvm::GenericDINode Class Reference
Generic tagged DWARF-like metadata node.
#include <DebugInfoMetadata.h>
Public Member Functions
unsigned getHash () const
DEFINE_MDNODE_GET (GenericDINode,(unsigned Tag, StringRef Header, ArrayRef< Metadata * > DwarfOps),(Tag, Header, DwarfOps)) DEFINE_MDNODE_GET(GenericDINode
unsigned MDString ArrayRef
< Metadata * > DwarfOps
TempGenericDINode clone () const
Return a (temporary) clone of this.
unsigned getTag () const
StringRef getHeader () const
op_iterator dwarf_op_begin () const
op_iterator dwarf_op_end () const
op_range dwarf_operands () const
unsigned getNumDwarfOperands () const
const MDOperand & getDwarfOperand (unsigned I) const
void replaceDwarfOperandWith (unsigned I, Metadata *New)
Static Public Member Functions
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
Public Attributes
unsigned Tag
unsigned MDString * Header
unsigned MDString ArrayRef
< Metadata * > DwarfOps
unsigned MDString ArrayRef
< Metadata * > Tag
unsigned MDString ArrayRef
< Metadata * > Header
Friends
class LLVMContextImpl
class MDNode
Detailed Description
Generic tagged DWARF-like metadata node.
An un-specialized DWARF-like metadata node. The first operand is a (possibly empty) null-separated MDString header that contains arbitrary fields. The remaining operands are dwarf_operands(), and are pointers to other metadata.
Definition at line 243 of file DebugInfoMetadata.h.
Member Function Documentation
static bool llvm::GenericDINode::classof (const Metadata * MD) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::DINode.
Definition at line 305 of file DebugInfoMetadata.h.
References llvm::Metadata::GenericDINodeKind, and llvm::Metadata::getMetadataID().
unsigned MDString ArrayRef<Metadata *> DwarfOps TempGenericDINode llvm::GenericDINode::clone () const [inline]
Return a (temporary) clone of this.
Reimplemented from llvm::MDNode.
Definition at line 286 of file DebugInfoMetadata.h.
llvm::GenericDINode::DEFINE_MDNODE_GET (GenericDINode , (unsigned Tag, StringRef Header,ArrayRef< Metadata * > DwarfOps) , (Tag, Header, DwarfOps))
op_iterator llvm::GenericDINode::dwarf_op_begin () const [inline]
Definition at line 291 of file DebugInfoMetadata.h.
References llvm::MDNode::op_begin().
Referenced by dwarf_operands().
op_iterator llvm::GenericDINode::dwarf_op_end () const [inline]
Definition at line 292 of file DebugInfoMetadata.h.
References llvm::MDNode::op_end().
Referenced by dwarf_operands().
op_range llvm::GenericDINode::dwarf_operands () const [inline]
Definition at line 293 of file DebugInfoMetadata.h.
References dwarf_op_begin(), and dwarf_op_end().
const MDOperand& llvm::GenericDINode::getDwarfOperand (unsigned I) const [inline]
Definition at line 298 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
unsigned llvm::GenericDINode::getHash () const [inline]
Definition at line 276 of file DebugInfoMetadata.h.
References llvm::Metadata::SubclassData32.
StringRef llvm::GenericDINode::getHeader () const [inline]
Definition at line 289 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
Referenced by llvm::MDNodeKeyImpl< GenericDINode >::isKeyOf().
unsigned llvm::GenericDINode::getNumDwarfOperands () const [inline]
Definition at line 297 of file DebugInfoMetadata.h.
References llvm::MDNode::getNumOperands().
unsigned llvm::GenericDINode::getTag () const [inline]
Reimplemented from llvm::DINode.
Definition at line 288 of file DebugInfoMetadata.h.
References llvm::Metadata::SubclassData16.
Referenced by llvm::MDNodeKeyImpl< GenericDINode >::isKeyOf(), and WriteGenericDINode().
void llvm::GenericDINode::replaceDwarfOperandWith (unsigned I, Metadata * New) [inline]
Definition at line 301 of file DebugInfoMetadata.h.
References llvm::MDNode::replaceOperandWith().
Friends And Related Function Documentation
friend class LLVMContextImpl [friend]
Reimplemented from llvm::DINode.
Definition at line 244 of file DebugInfoMetadata.h.
friend class MDNode [friend]
Reimplemented from llvm::DINode.
Definition at line 245 of file DebugInfoMetadata.h.
Member Data Documentation
unsigned MDString ArrayRef<Metadata *> llvm::GenericDINode::DwarfOps
Definition at line 281 of file DebugInfoMetadata.h.
unsigned MDString* llvm::GenericDINode::Header
Definition at line 281 of file DebugInfoMetadata.h.
unsigned MDString ArrayRef<Metadata *> llvm::GenericDINode::Header
Definition at line 281 of file DebugInfoMetadata.h.
unsigned llvm::GenericDINode::Tag
Definition at line 281 of file DebugInfoMetadata.h.
unsigned MDString ArrayRef<Metadata *> llvm::GenericDINode::Tag
Definition at line 281 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
DebugInfoMetadata.h
DebugInfoMetadata.cpp