LLVM: llvm::LowerExpectIntrinsicPass Class Reference
llvm::LowerExpectIntrinsicPass Class Reference
#include <LowerExpectIntrinsic.h>
Public Member Functions
PreservedAnalyses run (Function &F)
Run the pass over the function.
Static Public Member Functions
static StringRef name ()
Detailed Description
Definition at line 24 of file LowerExpectIntrinsic.h.
Member Function Documentation
static StringRef llvm::LowerExpectIntrinsicPass::name () [inline, static]
Definition at line 26 of file LowerExpectIntrinsic.h.
PreservedAnalyses LowerExpectIntrinsicPass::run (Function & F)
Run the pass over the function.
This will lower all of th expect intrinsic calls in this function into branch weight metadata. That metadata will subsequently feed the analysis of the probabilities and frequencies of the CFG. After running this pass, no more expect intrinsics remain, allowing the rest of the optimizer to ignore them.
Definition at line 161 of file LowerExpectIntrinsic.cpp.
References llvm::PreservedAnalyses::all(), lowerExpectIntrinsic(), and llvm::PreservedAnalyses::none().
The documentation for this class was generated from the following files:
LowerExpectIntrinsic.h
LowerExpectIntrinsic.cpp