LLVM: llvm::NVPTXFloatMCExpr Class Reference
llvm::NVPTXFloatMCExpr Class Reference
#include <NVPTXMCExpr.h>
Public Types
enum VariantKind { VK_NVPTX_None, VK_NVPTX_SINGLE_PREC_FLOAT, VK_NVPTX_DOUBLE_PREC_FLOAT }
Public Member Functions
VariantKind getKind () const
getOpcode - Get the kind of this expression.
APFloat getAPFloat () const
getSubExpr - Get the child of this expression.
void printImpl (raw_ostream &OS, const MCAsmInfo *MAI) const override
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const override
void visitUsedExpr (MCStreamer &Streamer) const override
MCSection * findAssociatedSection () const override
Find the "associated section" for this expression, which is currently defined as the absolute section for constants, or otherwise the section associated with the first defined symbol in the expression.
void fixELFSymbolsInTLSFixups (MCAssembler &Asm) const override
Static Public Member Functions
static bool classof (const MCExpr *E)
Construction
static const NVPTXFloatMCExpr * create (VariantKind Kind, APFloat Flt, MCContext &Ctx)
static const NVPTXFloatMCExpr * createConstantFPSingle (APFloat Flt, MCContext &Ctx)
static const NVPTXFloatMCExpr * createConstantFPDouble (APFloat Flt, MCContext &Ctx)
Detailed Description
Definition at line 20 of file NVPTXMCExpr.h.
Member Enumeration Documentation
enum llvm::NVPTXFloatMCExpr::VariantKind
Enumerator:
VK_NVPTX_None
VK_NVPTX_SINGLE_PREC_FLOAT
VK_NVPTX_DOUBLE_PREC_FLOAT
Definition at line 22 of file NVPTXMCExpr.h.
Member Function Documentation
static bool llvm::NVPTXFloatMCExpr::classof (const MCExpr * E) [inline, static]
Reimplemented from llvm::MCTargetExpr.
Definition at line 74 of file NVPTXMCExpr.h.
const NVPTXFloatMCExpr * NVPTXFloatMCExpr::create (VariantKind Kind, APFloat Flt, MCContext & Ctx) [static]
Definition at line 19 of file NVPTXMCExpr.cpp.
Referenced by createConstantFPDouble(), and createConstantFPSingle().
static const NVPTXFloatMCExpr* llvm::NVPTXFloatMCExpr::createConstantFPDouble (APFloat Flt, MCContext & Ctx) [inline, static]
Definition at line 47 of file NVPTXMCExpr.h.
References create(), and VK_NVPTX_DOUBLE_PREC_FLOAT.
static const NVPTXFloatMCExpr* llvm::NVPTXFloatMCExpr::createConstantFPSingle (APFloat Flt, MCContext & Ctx) [inline, static]
Definition at line 42 of file NVPTXMCExpr.h.
References create(), and VK_NVPTX_SINGLE_PREC_FLOAT.
bool llvm::NVPTXFloatMCExpr::evaluateAsRelocatableImpl (MCValue & Res, const MCAsmLayout * Layout, const MCFixup * Fixup) const [inline, override, virtual]
Implements llvm::MCTargetExpr.
Definition at line 63 of file NVPTXMCExpr.h.
MCSection* llvm::NVPTXFloatMCExpr::findAssociatedSection () const [inline, override, virtual]
Find the "associated section" for this expression, which is currently defined as the absolute section for constants, or otherwise the section associated with the first defined symbol in the expression.
Implements llvm::MCTargetExpr.
Definition at line 69 of file NVPTXMCExpr.h.
void llvm::NVPTXFloatMCExpr::fixELFSymbolsInTLSFixups (MCAssembler & Asm) const [inline, override, virtual]
Implements llvm::MCTargetExpr.
Definition at line 72 of file NVPTXMCExpr.h.
APFloat llvm::NVPTXFloatMCExpr::getAPFloat () const [inline]
getSubExpr - Get the child of this expression.
Definition at line 58 of file NVPTXMCExpr.h.
Referenced by printImpl().
VariantKind llvm::NVPTXFloatMCExpr::getKind () const [inline]
getOpcode - Get the kind of this expression.
Reimplemented from llvm::MCExpr.
Definition at line 55 of file NVPTXMCExpr.h.
void NVPTXFloatMCExpr::printImpl (raw_ostream & OS, const MCAsmInfo * MAI) const [override, virtual]
Implements llvm::MCTargetExpr.
Definition at line 23 of file NVPTXMCExpr.cpp.
References llvm::APFloat::bitcastToAPInt(), llvm::APFloat::convert(), getAPFloat(), llvm::APInt::getZExtValue(), llvm::APFloat::IEEEdouble, llvm::APFloat::IEEEsingle, llvm_unreachable, llvm::APFloat::rmNearestTiesToEven, llvm::utohexstr(), VK_NVPTX_DOUBLE_PREC_FLOAT, and VK_NVPTX_SINGLE_PREC_FLOAT.
void llvm::NVPTXFloatMCExpr::visitUsedExpr (MCStreamer & Streamer) const [inline, override, virtual]
Implements llvm::MCTargetExpr.
Definition at line 68 of file NVPTXMCExpr.h.
The documentation for this class was generated from the following files:
NVPTXMCExpr.h
NVPTXMCExpr.cpp