LLVM: llvm::GCRelocateOperands Class Reference
llvm::GCRelocateOperands Class Reference
Wraps a call to a gc.relocate and provides access to it's operands.
#include <Statepoint.h>
Public Member Functions
GCRelocateOperands (const User *U)
GCRelocateOperands (const Instruction *inst)
GCRelocateOperands (CallSite CS)
bool isTiedToInvoke () const
Return true if this relocate is tied to the invoke statepoint.
ImmutableCallSite getUnderlyingCallSite ()
Get enclosed relocate intrinsic.
const Instruction * getStatepoint ()
The statepoint with which this gc.relocate is associated.
unsigned getBasePtrIndex ()
The index into the associate statepoint's argument list which contains the base pointer of the pointer whose relocation this gc.relocate describes.
unsigned getDerivedPtrIndex ()
The index into the associate statepoint's argument list which contains the pointer whose relocation this gc.relocate describes.
Value * getBasePtr ()
Value * getDerivedPtr ()
Detailed Description
Wraps a call to a gc.relocate and provides access to it's operands.
TODO: This should likely be refactored to resememble the wrappers in InstrinsicInst.h.
Definition at line 249 of file Statepoint.h.
Constructor & Destructor Documentation
llvm::GCRelocateOperands::GCRelocateOperands (const User * U) [inline]
Definition at line 253 of file Statepoint.h.
References llvm::isGCRelocate().
llvm::GCRelocateOperands::GCRelocateOperands (const Instruction * inst) [inline]
Definition at line 254 of file Statepoint.h.
References llvm::isGCRelocate().
llvm::GCRelocateOperands::GCRelocateOperands (CallSite CS) [inline]
Definition at line 257 of file Statepoint.h.
References llvm::isGCRelocate().
Member Function Documentation
Value* llvm::GCRelocateOperands::getBasePtr () [inline]
Definition at line 305 of file Statepoint.h.
References llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_begin(), llvm::CS, getBasePtrIndex(), and getStatepoint().
Referenced by simplifyRelocatesOffABase().
unsigned llvm::GCRelocateOperands::getBasePtrIndex () [inline]
The index into the associate statepoint's argument list which contains the base pointer of the pointer whose relocation this gc.relocate describes.
Definition at line 295 of file Statepoint.h.
References llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getArgument().
Referenced by computeBaseDerivedRelocateMap(), getBasePtr(), and simplifyRelocatesOffABase().
Value* llvm::GCRelocateOperands::getDerivedPtr () [inline]
Definition at line 310 of file Statepoint.h.
References llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_begin(), llvm::CS, getDerivedPtrIndex(), and getStatepoint().
Referenced by findPreviousSpillSlot(), insertRelocationStores(), isDereferenceablePointer(), simplifyRelocatesOffABase(), and llvm::InstCombiner::visitCallInst().
unsigned llvm::GCRelocateOperands::getDerivedPtrIndex () [inline]
The index into the associate statepoint's argument list which contains the pointer whose relocation this gc.relocate describes.
Definition at line 301 of file Statepoint.h.
References llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getArgument().
Referenced by computeBaseDerivedRelocateMap(), getDerivedPtr(), and simplifyRelocatesOffABase().
const Instruction* llvm::GCRelocateOperands::getStatepoint () [inline]
The statepoint with which this gc.relocate is associated.
Definition at line 271 of file Statepoint.h.
References llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getArgument(), getParent(), llvm::BasicBlock::getTerminator(), and llvm::isStatepoint().
Referenced by findPreviousSpillSlot(), getBasePtr(), and getDerivedPtr().
ImmutableCallSite llvm::GCRelocateOperands::getUnderlyingCallSite () [inline]
Get enclosed relocate intrinsic.
Definition at line 268 of file Statepoint.h.
bool llvm::GCRelocateOperands::isTiedToInvoke () const [inline]
Return true if this relocate is tied to the invoke statepoint.
This includes relocates which are on the unwinding path.
Definition at line 261 of file Statepoint.h.
References llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getArgument().
The documentation for this class was generated from the following file:
Statepoint.h