LLVM: llvm::AArch64_MachoTargetObjectFile Class Reference
llvm::AArch64_MachoTargetObjectFile Class Reference
AArch64_MachoTargetObjectFile - This TLOF implementation is used for Darwin.
#include <AArch64TargetObjectFile.h>
Public Member Functions
AArch64_MachoTargetObjectFile ()
const MCExpr * getTTypeGlobalReference (const GlobalValue *GV, unsigned Encoding, Mangler &Mang, const TargetMachine &TM, MachineModuleInfo *MMI, MCStreamer &Streamer) const override
The mach-o version of this method defaults to returning a stub reference.
MCSymbol * getCFIPersonalitySymbol (const GlobalValue *GV, Mangler &Mang, const TargetMachine &TM, MachineModuleInfo *MMI) const override
const MCExpr * getIndirectSymViaGOTPCRel (const MCSymbol *Sym, const MCValue &MV, int64_t Offset, MachineModuleInfo *MMI, MCStreamer &Streamer) const override
Get MachO PC relative GOT entry relocation.
Detailed Description
AArch64_MachoTargetObjectFile - This TLOF implementation is used for Darwin.
Definition at line 25 of file AArch64TargetObjectFile.h.
Constructor & Destructor Documentation
AArch64_MachoTargetObjectFile::AArch64_MachoTargetObjectFile ()
Definition at line 27 of file AArch64TargetObjectFile.cpp.
References llvm::TargetLoweringObjectFile::SupportGOTPCRelWithOffset.
Member Function Documentation
MCSymbol * AArch64_MachoTargetObjectFile::getCFIPersonalitySymbol (const GlobalValue * GV, Mangler & Mang, const TargetMachine & TM, MachineModuleInfo * MMI) const [override, virtual]
Reimplemented from llvm::TargetLoweringObjectFileMachO.
Definition at line 54 of file AArch64TargetObjectFile.cpp.
References llvm::TargetMachine::getSymbol().
const MCExpr * AArch64_MachoTargetObjectFile::getIndirectSymViaGOTPCRel (const MCSymbol * Sym, const MCValue & MV, int64_t Offset, MachineModuleInfo * MMI, MCStreamer & Streamer) const [override, virtual]
Get MachO PC relative GOT entry relocation.
Reimplemented from llvm::TargetLoweringObjectFileMachO.
Definition at line 60 of file AArch64TargetObjectFile.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), llvm::MCContext::createTempSymbol(), llvm::MCStreamer::EmitLabel(), llvm::MCValue::getConstant(), llvm::TargetLoweringObjectFile::getContext(), and llvm::MCSymbolRefExpr::VK_GOT.
const MCExpr * AArch64_MachoTargetObjectFile::getTTypeGlobalReference (const GlobalValue * GV, unsigned Encoding, Mangler & Mang, const TargetMachine & TM, MachineModuleInfo * MMI, MCStreamer & Streamer) const [override, virtual]
The mach-o version of this method defaults to returning a stub reference.
Reimplemented from llvm::TargetLoweringObjectFileMachO.
Definition at line 32 of file AArch64TargetObjectFile.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), llvm::MCContext::createTempSymbol(), llvm::dwarf::DW_EH_PE_indirect, llvm::dwarf::DW_EH_PE_pcrel, llvm::MCStreamer::EmitLabel(), llvm::TargetLoweringObjectFile::getContext(), llvm::TargetMachine::getSymbol(), and llvm::MCSymbolRefExpr::VK_GOT.
The documentation for this class was generated from the following files:
AArch64TargetObjectFile.h
AArch64TargetObjectFile.cpp