LLVM: llvm::ImmutableMapRef< KeyT, ValT, ValInfo > Class Template Reference
llvm::ImmutableMapRef< KeyT, ValT, ValInfo > Class Template Reference
#include <ImmutableMap.h>
Classes
class iterator
Public Types
typedef ValInfo::value_type value_type
typedef ValInfo::value_type_ref value_type_ref
typedef ValInfo::key_type key_type
typedef ValInfo::key_type_ref key_type_ref
typedef ValInfo::data_type data_type
typedef ValInfo::data_type_ref data_type_ref
typedef ImutAVLTree< ValInfo > TreeTy
typedef TreeTy::Factory FactoryTy
Public Member Functions
ImmutableMapRef (const TreeTy *R, FactoryTy *F)
Constructs a map from a pointer to a tree root.
ImmutableMapRef (const ImmutableMap< KeyT, ValT > &X, typename ImmutableMap< KeyT, ValT >::Factory &F)
ImmutableMapRef (const ImmutableMapRef &X)
ImmutableMapRef & operator= (const ImmutableMapRef &X)
~ImmutableMapRef ()
void manualRetain ()
void manualRelease ()
ImmutableMapRef add (key_type_ref K, data_type_ref D) const
ImmutableMapRef remove (key_type_ref K) const
bool contains (key_type_ref K) const
ImmutableMap< KeyT, ValT > asImmutableMap () const
bool operator== (const ImmutableMapRef &RHS) const
bool operator!= (const ImmutableMapRef &RHS) const
bool isEmpty () const
void verify () const
iterator begin () const
iterator end () const
data_type * lookup (key_type_ref K) const
value_type * getMaxElement () const
getMaxElement - Returns the <key,value> pair in the ImmutableMap for which key is the highest in the ordering of keys in the map.
unsigned getHeight () const
void Profile (FoldingSetNodeID &ID) const
Static Public Member Functions
static ImmutableMapRef getEmptyMap (FactoryTy *F)
static void Profile (FoldingSetNodeID &ID, const ImmutableMapRef &M)
Protected Attributes
TreeTy * Root
FactoryTy * Factory
Detailed Description
template<typename KeyT, typename ValT, typename ValInfo = ImutKeyValueInfo<KeyT,ValT>>
class llvm::ImmutableMapRef< KeyT, ValT, ValInfo >
Definition at line 253 of file ImmutableMap.h.
Member Typedef Documentation
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> typedef ValInfo::data_type llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::data_type
Definition at line 259 of file ImmutableMap.h.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> typedef ValInfo::data_type_ref llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::data_type_ref
Definition at line 260 of file ImmutableMap.h.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> typedef TreeTy::Factory llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::FactoryTy
Definition at line 262 of file ImmutableMap.h.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> typedef ValInfo::key_type llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::key_type
Definition at line 257 of file ImmutableMap.h.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> typedef ValInfo::key_type_ref llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::key_type_ref
Definition at line 258 of file ImmutableMap.h.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> typedef ImutAVLTree<ValInfo> llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::TreeTy
Definition at line 261 of file ImmutableMap.h.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> typedef ValInfo::value_type llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::value_type
Definition at line 255 of file ImmutableMap.h.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> typedef ValInfo::value_type_ref llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::value_type_ref
Definition at line 256 of file ImmutableMap.h.
Constructor & Destructor Documentation
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::ImmutableMapRef (const TreeTy * R, FactoryTy * F) [inline, explicit]
Constructs a map from a pointer to a tree root.
In general one should use a Factory object to create maps instead of directly invoking the constructor, but there are cases where make this constructor public is useful.
Definition at line 273 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::retain(), and llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Root.
Referenced by llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::add(), llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::getEmptyMap(), and llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::remove().
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::ImmutableMapRef (const ImmutableMap< KeyT, ValT > & X, typename ImmutableMap< KeyT, ValT >::Factory & F) [inline, explicit]
Definition at line 279 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::retain(), and llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Root.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::ImmutableMapRef (const ImmutableMapRef< KeyT, ValT, ValInfo > & X) [inline]
Definition at line 286 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::retain(), and llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Root.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::~ImmutableMapRef () [inline]
Definition at line 306 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::release(), and llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Root.
Member Function Documentation
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> ImmutableMapRef llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::add (key_type_ref K, data_type_ref D) const [inline]
Definition at line 323 of file ImmutableMap.h.
References llvm::ImutAVLFactory< ImutInfo >::add(), llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Factory, llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::ImmutableMapRef(), and llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Root.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> ImmutableMap<KeyT, ValT> llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::asImmutableMap () const [inline]
Definition at line 337 of file ImmutableMap.h.
References llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Factory, llvm::ImutAVLFactory< ImutInfo >::getCanonicalTree(), and llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Root.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> iterator llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::begin () const [inline]
Definition at line 371 of file ImmutableMap.h.
References llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Root.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> bool llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::contains (key_type_ref K) const [inline]
Definition at line 333 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::contains(), and llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Root.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> iterator llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::end () const [inline]
Definition at line 372 of file ImmutableMap.h.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> static ImmutableMapRef llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::getEmptyMap (FactoryTy * F) [inline, static]
Definition at line 311 of file ImmutableMap.h.
References llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::ImmutableMapRef().
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> unsigned llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::getHeight () const [inline]
Definition at line 394 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::getHeight(), and llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Root.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> value_type* llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::getMaxElement () const [inline]
getMaxElement - Returns the <key,value> pair in the ImmutableMap for which key is the highest in the ordering of keys in the map.
This method returns NULL if the map is empty.
Definition at line 386 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::getMaxElement(), llvm::ImutAVLTree< ImutInfo >::getValue(), and llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Root.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> bool llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::isEmpty () const [inline]
Definition at line 349 of file ImmutableMap.h.
References llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Root.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> data_type* llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::lookup (key_type_ref K) const [inline]
Definition at line 374 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::find(), llvm::ImutAVLTree< ImutInfo >::getValue(), and llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Root.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> void llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::manualRelease () [inline]
Definition at line 319 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::release(), and llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Root.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> void llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::manualRetain () [inline]
Definition at line 315 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::retain(), and llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Root.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> bool llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::operator!= (const ImmutableMapRef< KeyT, ValT, ValInfo > & RHS) const [inline]
Definition at line 345 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::isNotEqual(), and llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Root.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> ImmutableMapRef& llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::operator= (const ImmutableMapRef< KeyT, ValT, ValInfo > & X) [inline]
Definition at line 292 of file ImmutableMap.h.
References llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Factory, llvm::ImutAVLTree< ImutInfo >::release(), llvm::ImutAVLTree< ImutInfo >::retain(), and llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Root.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> bool llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::operator== (const ImmutableMapRef< KeyT, ValT, ValInfo > & RHS) const [inline]
Definition at line 341 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::isEqual(), and llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Root.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> static void llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Profile (FoldingSetNodeID & ID, const ImmutableMapRef< KeyT, ValT, ValInfo > & M) [inline, static]
Definition at line 396 of file ImmutableMap.h.
References llvm::FoldingSetNodeID::AddPointer(), and llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Root.
Referenced by llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Profile().
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> void llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Profile (FoldingSetNodeID & ID) const [inline]
Definition at line 400 of file ImmutableMap.h.
References llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Profile().
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> ImmutableMapRef llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::remove (key_type_ref K) const [inline]
Definition at line 328 of file ImmutableMap.h.
References llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Factory, llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::ImmutableMapRef(), llvm::ImutAVLFactory< ImutInfo >::remove(), and llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Root.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> void llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::verify () const [inline]
Definition at line 355 of file ImmutableMap.h.
References llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Root.
Member Data Documentation
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> FactoryTy* llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Factory [protected]
Definition at line 266 of file ImmutableMap.h.
Referenced by llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::add(), llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::asImmutableMap(), llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::operator=(), and llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::remove().
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> TreeTy* llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Root [protected]
Definition at line 265 of file ImmutableMap.h.
Referenced by llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::add(), llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::asImmutableMap(), llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::begin(), llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::contains(), llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::getHeight(), llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::getMaxElement(), llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::ImmutableMapRef(), llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::isEmpty(), llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::lookup(), llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::manualRelease(), llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::manualRetain(), llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::operator!=(), llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::operator=(), llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::operator==(), llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::Profile(), llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::remove(), llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::verify(), and llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::~ImmutableMapRef().
The documentation for this class was generated from the following file:
ImmutableMap.h