LLVM: llvm::FaultMapParser::FunctionInfoAccessor Class Reference
llvm::FaultMapParser::FunctionInfoAccessor Class Reference
#include <FaultMaps.h>
Public Member Functions
FunctionInfoAccessor ()
FunctionInfoAccessor (const uint8_t *P, const uint8_t *E)
FunctionAddrType getFunctionAddr () const
NumFaultingPCsType getNumFaultingPCs () const
FunctionFaultInfoAccessor getFunctionFaultInfoAt (uint32_t Index) const
FunctionInfoAccessor getNextFunctionInfo () const
Detailed Description
Definition at line 140 of file FaultMaps.h.
Constructor & Destructor Documentation
llvm::FaultMapParser::FunctionInfoAccessor::FunctionInfoAccessor () [inline]
Definition at line 161 of file FaultMaps.h.
Referenced by getNextFunctionInfo().
llvm::FaultMapParser::FunctionInfoAccessor::FunctionInfoAccessor (const uint8_t * P, const uint8_t * E) [inline, explicit]
Definition at line 163 of file FaultMaps.h.
Member Function Documentation
FunctionAddrType llvm::FaultMapParser::FunctionInfoAccessor::getFunctionAddr () const [inline]
Definition at line 166 of file FaultMaps.h.
Referenced by llvm::operator<<().
FunctionFaultInfoAccessor llvm::FaultMapParser::FunctionInfoAccessor::getFunctionFaultInfoAt (uint32_t Index) const [inline]
Definition at line 174 of file FaultMaps.h.
References getNumFaultingPCs(), and llvm::FaultMapParser::FunctionFaultInfoAccessor::Size.
Referenced by llvm::operator<<().
FunctionInfoAccessor llvm::FaultMapParser::FunctionInfoAccessor::getNextFunctionInfo () const [inline]
Definition at line 181 of file FaultMaps.h.
References FunctionInfoAccessor(), getNumFaultingPCs(), and llvm::FaultMapParser::FunctionFaultInfoAccessor::Size.
Referenced by llvm::operator<<().
NumFaultingPCsType llvm::FaultMapParser::FunctionInfoAccessor::getNumFaultingPCs () const [inline]
Definition at line 170 of file FaultMaps.h.
Referenced by getFunctionFaultInfoAt(), getNextFunctionInfo(), and llvm::operator<<().
The documentation for this class was generated from the following file:
FaultMaps.h