LLVM: llvm::DIExpression::expr_op_iterator Class Reference
llvm::DIExpression::expr_op_iterator Class Reference
An iterator for expression operands.
#include <DebugInfoMetadata.h>
Public Member Functions
expr_op_iterator (element_iterator I)
element_iterator getBase () const
const ExprOperand & operator* () const
const ExprOperand * operator-> () const
expr_op_iterator & operator++ ()
expr_op_iterator operator++ (int)
expr_op_iterator getNext () const
Get the next iterator.
bool operator== (const expr_op_iterator &X) const
bool operator!= (const expr_op_iterator &X) const
Detailed Description
An iterator for expression operands.
Definition at line 2016 of file DebugInfoMetadata.h.
Constructor & Destructor Documentation
llvm::DIExpression::expr_op_iterator::expr_op_iterator (element_iterator I) [inline, explicit]
Definition at line 2021 of file DebugInfoMetadata.h.
Referenced by getNext().
Member Function Documentation
element_iterator llvm::DIExpression::expr_op_iterator::getBase () const [inline]
Definition at line 2023 of file DebugInfoMetadata.h.
References llvm::DIExpression::ExprOperand::get().
Referenced by operator!=(), and operator==().
expr_op_iterator llvm::DIExpression::expr_op_iterator::getNext () const [inline]
Get the next iterator.
std::next() doesn't work because this is technically an input_iterator, but it's a perfectly valid operation. This is an accessor to provide the same functionality.
Definition at line 2042 of file DebugInfoMetadata.h.
References expr_op_iterator().
bool llvm::DIExpression::expr_op_iterator::operator!= (const expr_op_iterator & X) const [inline]
Definition at line 2047 of file DebugInfoMetadata.h.
References getBase().
const ExprOperand& llvm::DIExpression::expr_op_iterator::operator* () const [inline]
Definition at line 2024 of file DebugInfoMetadata.h.
expr_op_iterator& llvm::DIExpression::expr_op_iterator::operator++ () [inline]
Definition at line 2027 of file DebugInfoMetadata.h.
expr_op_iterator llvm::DIExpression::expr_op_iterator::operator++ (int) [inline]
Definition at line 2031 of file DebugInfoMetadata.h.
References T.
const ExprOperand* llvm::DIExpression::expr_op_iterator::operator-> () const [inline]
Definition at line 2025 of file DebugInfoMetadata.h.
bool llvm::DIExpression::expr_op_iterator::operator== (const expr_op_iterator & X) const [inline]
Definition at line 2044 of file DebugInfoMetadata.h.
References getBase().
The documentation for this class was generated from the following file:
DebugInfoMetadata.h