LLVM: llvm::MCGenDwarfInfo Class Reference
llvm::MCGenDwarfInfo Class Reference
#include <MCDwarf.h>
Static Public Member Functions
static void Emit (MCStreamer *MCOS)
Detailed Description
Definition at line 263 of file MCDwarf.h.
Member Function Documentation
void MCGenDwarfInfo::Emit (MCStreamer * MCOS) [static]
Definition at line 836 of file MCDwarf.cpp.
References llvm::MCContext::createTempSymbol(), llvm::MCAsmInfo::doesDwarfUseRelocationsAcrossSections(), EmitGenDwarfAbbrev(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), EmitGenDwarfRanges(), llvm::MCStreamer::EmitLabel(), llvm::SetVector< T, Vector, Set >::empty(), llvm::MCContext::finalizeDwarfSections(), llvm::MCContext::getAsmInfo(), llvm::MCStreamer::getContext(), llvm::MCObjectFileInfo::getDwarfAbbrevSection(), llvm::MCObjectFileInfo::getDwarfARangesSection(), llvm::MCObjectFileInfo::getDwarfInfoSection(), llvm::MCStreamer::getDwarfLineTableSymbol(), llvm::MCObjectFileInfo::getDwarfRangesSection(), llvm::MCContext::getDwarfVersion(), llvm::MCContext::getGenDwarfSectionSyms(), llvm::MCContext::getObjectFileInfo(), llvm::SetVector< T, Vector, Set >::size(), and llvm::MCStreamer::SwitchSection().
Referenced by llvm::MCObjectStreamer::FinishImpl().
The documentation for this class was generated from the following files:
MCDwarf.h
MCDwarf.cpp