LLVM: llvm::SpecialCaseList Class Reference
llvm::SpecialCaseList Class Reference
#include <SpecialCaseList.h>
Classes
struct Entry
Represents a set of regular expressions.
Public Member Functions
~SpecialCaseList ()
bool inSection (StringRef Section, StringRef Query, StringRef Category=StringRef()) const
Returns true, if special case list contains a line.
Static Public Member Functions
static std::unique_ptr
< SpecialCaseList > create (const std::vector< std::string > &Paths, std::string &Error)
Parses the special case list entries from files.
static std::unique_ptr
< SpecialCaseList > create (const MemoryBuffer *MB, std::string &Error)
Parses the special case list from a memory buffer.
static std::unique_ptr
< SpecialCaseList > createOrDie (const std::vector< std::string > &Paths)
Parses the special case list entries from files.
Detailed Description
Definition at line 60 of file SpecialCaseList.h.
Constructor & Destructor Documentation
llvm::SpecialCaseList::~SpecialCaseList ()
Definition at line 155 of file SpecialCaseList.cpp.
Member Function Documentation
std::unique_ptr< SpecialCaseList > llvm::SpecialCaseList::create (const std::vector< std::string > & Paths, std::string & Error) [static]
Parses the special case list entries from files.
On failure, returns 0 and writes an error message to string.
Definition at line 50 of file SpecialCaseList.cpp.
References llvm::ErrorOr< T >::get(), llvm::ErrorOr< T >::getError(), and llvm::MemoryBuffer::getFile().
Referenced by createOrDie().
std::unique_ptr< SpecialCaseList > llvm::SpecialCaseList::create (const MemoryBuffer * MB, std::string & Error) [static]
Parses the special case list from a memory buffer.
On failure, returns 0 and writes an error message to string.
Definition at line 70 of file SpecialCaseList.cpp.
std::unique_ptr< SpecialCaseList > llvm::SpecialCaseList::createOrDie (const std::vector< std::string > & Paths) [static]
Parses the special case list entries from files.
On failure, reports a fatal error.
Definition at line 80 of file SpecialCaseList.cpp.
References create(), llvm::lltok::Error, and llvm::report_fatal_error().
bool llvm::SpecialCaseList::inSection (StringRef Section, StringRef Query, StringRef Category = StringRef()) const
Returns true, if special case list contains a line.
   @Section:<E>=@Category
and satisfies a wildcard expression <E>.
Definition at line 157 of file SpecialCaseList.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::StringMapEntry< ValueTy >::getValue(), and I.
The documentation for this class was generated from the following files:
SpecialCaseList.h
SpecialCaseList.cpp