LLVM: llvm::FenceInst Class Reference
llvm::FenceInst Class Reference
FenceInst - an instruction for ordering other memory operations.
#include <Instructions.h>
Public Member Functions
void * operator new (size_t s)
Allocate a User with an operand pointer co-allocated.
FenceInst (LLVMContext &C, AtomicOrdering Ordering, SynchronizationScope SynchScope=CrossThread, Instruction *InsertBefore=nullptr)
FenceInst (LLVMContext &C, AtomicOrdering Ordering, SynchronizationScope SynchScope, BasicBlock *InsertAtEnd)
AtomicOrdering getOrdering () const
Returns the ordering effect of this fence.
void setOrdering (AtomicOrdering Ordering)
Set the ordering constraint on this fence.
SynchronizationScope getSynchScope () const
void setSynchScope (SynchronizationScope xthread)
Specify whether this fence orders other operations with respect to all concurrently executing threads, or only with respect to signal handlers executing in the same thread.
Static Public Member Functions
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
FenceInst * clone_impl () const override
Detailed Description
FenceInst - an instruction for ordering other memory operations.
Definition at line 435 of file Instructions.h.
Constructor & Destructor Documentation
FenceInst::FenceInst (LLVMContext & C, AtomicOrdering Ordering, SynchronizationScope SynchScope = CrossThread, Instruction * InsertBefore = nullptr)
Definition at line 1178 of file Instructions.cpp.
References setOrdering(), and setSynchScope().
Referenced by clone_impl().
FenceInst::FenceInst (LLVMContext & C, AtomicOrdering Ordering, SynchronizationScope SynchScope, BasicBlock * InsertAtEnd)
Definition at line 1186 of file Instructions.cpp.
References setOrdering(), and setSynchScope().
Member Function Documentation
static bool llvm::FenceInst::classof (const Instruction * I) [inline, static]
Definition at line 480 of file Instructions.h.
References llvm::Instruction::getOpcode().
static bool llvm::FenceInst::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::Instruction.
Definition at line 483 of file Instructions.h.
FenceInst * FenceInst::clone_impl () const [override, protected, virtual]
Implements llvm::Instruction.
Definition at line 3517 of file Instructions.cpp.
References FenceInst(), llvm::Value::getContext(), getOrdering(), and getSynchScope().
AtomicOrdering llvm::FenceInst::getOrdering () const [inline]
Returns the ordering effect of this fence.
Definition at line 456 of file Instructions.h.
Referenced by clone_impl().
SynchronizationScope llvm::FenceInst::getSynchScope () const [inline]
Definition at line 467 of file Instructions.h.
Referenced by clone_impl().
void* llvm::FenceInst::operator new (size_t Size) [inline]
Allocate a User with an operand pointer co-allocated.
This is used for subclasses which need to allocate a variable number of operands, ie, 'hung off uses'.
Reimplemented from llvm::User.
Definition at line 442 of file Instructions.h.
References llvm::User::operator new().
void llvm::FenceInst::setOrdering (AtomicOrdering Ordering) [inline]
Set the ordering constraint on this fence.
May only be Acquire, Release, AcquireRelease, or SequentiallyConsistent.
Definition at line 462 of file Instructions.h.
Referenced by FenceInst().
void llvm::FenceInst::setSynchScope (SynchronizationScope xthread) [inline]
Specify whether this fence orders other operations with respect to all concurrently executing threads, or only with respect to signal handlers executing in the same thread.
Definition at line 474 of file Instructions.h.
Referenced by FenceInst().
The documentation for this class was generated from the following files:
Instructions.h
Instructions.cpp