LLVM: llvm::MachineModuleInfo Class Reference
llvm::MachineModuleInfo Class Reference
MachineModuleInfo - This class contains meta information specific to a module.
#include <MachineModuleInfo.h>
Classes
struct VariableDbgInfo
Public Types
typedef SmallVector
< VariableDbgInfo, 4 > VariableDbgInfoMapTy
Public Member Functions
MachineModuleInfo ()
MachineModuleInfo (const MCAsmInfo &MAI, const MCRegisterInfo &MRI, const MCObjectFileInfo *MOFI)
~MachineModuleInfo () override
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
bool doFinalization (Module &) override
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
void EndFunction ()
EndFunction - Discard function meta information.
const MCContext & getContext () const
MCContext & getContext ()
void setModule (const Module *M)
const Module * getModule () const
const Function * getWinEHParent (const Function *F) const
WinEHFuncInfo & getWinEHFuncInfo (const Function *F)
bool hasWinEHFuncInfo (const Function *F) const
template<typename Ty >
Ty & getObjFileInfo ()
getInfo - Keep track of various per-function pieces of information for backends that would like to do so.
template<typename Ty >
const Ty & getObjFileInfo () const
bool hasDebugInfo () const
hasDebugInfo - Returns true if valid debug info is present.
void setDebugInfoAvailability (bool avail)
bool callsEHReturn () const
void setCallsEHReturn (bool b)
bool callsUnwindInit () const
void setCallsUnwindInit (bool b)
bool usesVAFloatArgument () const
void setUsesVAFloatArgument (bool b)
bool usesMorestackAddr () const
void setUsesMorestackAddr (bool b)
const std::vector
< MCCFIInstruction > & getFrameInstructions () const
Returns a reference to a list of cfi instructions in the current function's prologue.
unsigned
LLVM_ATTRIBUTE_UNUSED_RESULT addFrameInst (const MCCFIInstruction &Inst)
MCSymbol * getAddrLabelSymbol (const BasicBlock *BB)
getAddrLabelSymbol - Return the symbol to be used for the specified basic block when its address is taken.
std::vector< MCSymbol * > getAddrLabelSymbolToEmit (const BasicBlock *BB)
getAddrLabelSymbolToEmit - Return the symbol to be used for the specified basic block when its address is taken.
void takeDeletedSymbolsForFunction (const Function *F, std::vector< MCSymbol * > &Result)
takeDeletedSymbolsForFunction - If the specified function has had any references to address-taken blocks generated, but the block got deleted, return the symbol now so we can emit it.
LandingPadInfo & getOrCreateLandingPadInfo (MachineBasicBlock *LandingPad)
getOrCreateLandingPadInfo - Find or create an LandingPadInfo for the specified MachineBasicBlock.
void addInvoke (MachineBasicBlock *LandingPad, MCSymbol *BeginLabel, MCSymbol *EndLabel)
addInvoke - Provide the begin and end labels of an invoke style call and associate it with a try landing pad block.
MCSymbol * addLandingPad (MachineBasicBlock *LandingPad)
addLandingPad - Add a new panding pad.
void addPersonality (MachineBasicBlock *LandingPad, const Function *Personality)
addPersonality - Provide the personality function for the exception information.
void addWinEHState (MachineBasicBlock *LandingPad, int State)
unsigned getPersonalityIndex () const
getPersonalityIndex - Get index of the current personality function inside Personalitites array
const std::vector< const
Function * > & getPersonalities () const
getPersonalities - Return array of personality functions ever seen.
void addCatchTypeInfo (MachineBasicBlock *LandingPad, ArrayRef< const GlobalValue * > TyInfo)
addCatchTypeInfo - Provide the catch typeinfo for a landing pad.
void addFilterTypeInfo (MachineBasicBlock *LandingPad, ArrayRef< const GlobalValue * > TyInfo)
addFilterTypeInfo - Provide the filter typeinfo for a landing pad.
void addCleanup (MachineBasicBlock *LandingPad)
addCleanup - Add a cleanup action for a landing pad.
void addSEHCatchHandler (MachineBasicBlock *LandingPad, const Function *Filter, const BlockAddress *RecoverLabel)
void addSEHCleanupHandler (MachineBasicBlock *LandingPad, const Function *Cleanup)
unsigned getTypeIDFor (const GlobalValue *TI)
getTypeIDFor - Return the type id for the specified typeinfo.
int getFilterIDFor (std::vector< unsigned > &TyIds)
getFilterIDFor - Return the id of the filter encoded by TyIds.
void TidyLandingPads (DenseMap< MCSymbol *, uintptr_t > *LPMap=nullptr)
TidyLandingPads - Remap landing pad labels and remove any deleted landing pads.
const std::vector
< LandingPadInfo > & getLandingPads () const
getLandingPads - Return a reference to the landing pad info for the current function.
void setCallSiteLandingPad (MCSymbol *Sym, ArrayRef< unsigned > Sites)
setCallSiteLandingPad - Map the landing pad's EH symbol to the call site indexes.
SmallVectorImpl< unsigned > & getCallSiteLandingPad (MCSymbol *Sym)
getCallSiteLandingPad - Get the call site indexes for a landing pad EH symbol.
bool hasCallSiteLandingPad (MCSymbol *Sym)
hasCallSiteLandingPad - Return true if the landing pad Eh symbol has an associated call site.
void setCallSiteBeginLabel (MCSymbol *BeginLabel, unsigned Site)
setCallSiteBeginLabel - Map the begin label for a call site.
unsigned getCallSiteBeginLabel (MCSymbol *BeginLabel)
getCallSiteBeginLabel - Get the call site number for a begin label.
bool hasCallSiteBeginLabel (MCSymbol *BeginLabel)
hasCallSiteBeginLabel - Return true if the begin label has a call site number associated with it.
void setCurrentCallSite (unsigned Site)
setCurrentCallSite - Set the call site currently being processed.
unsigned getCurrentCallSite ()
getCurrentCallSite - Get the call site currently being processed, if any.
const std::vector< const
GlobalValue * > & getTypeInfos () const
getTypeInfos - Return a reference to the C++ typeinfo for the current function.
const std::vector< unsigned > & getFilterIds () const
getFilterIds - Return a reference to the typeids encoding filters used in the current function.
const Function * getPersonality () const
getPersonality - Return a personality function if available.
EHPersonality getPersonalityType ()
Classify the personality function amongst known EH styles.
void setVariableDbgInfo (const DILocalVariable *Var, const DIExpression *Expr, unsigned Slot, const DILocation *Loc)
setVariableDbgInfo - Collect information used to emit debugging information of a variable.
VariableDbgInfoMapTy & getVariableDbgInfo ()
Public Attributes
VariableDbgInfoMapTy VariableDbgInfos
Static Public Attributes
static char ID
Detailed Description
MachineModuleInfo - This class contains meta information specific to a module.
Queries can be made by different debugging and exception handling schemes and reformated for specific use.
Definition at line 114 of file MachineModuleInfo.h.
Member Typedef Documentation
typedef SmallVector<VariableDbgInfo, 4> llvm::MachineModuleInfo::VariableDbgInfoMapTy
Definition at line 200 of file MachineModuleInfo.h.
Constructor & Destructor Documentation
MachineModuleInfo::MachineModuleInfo ()
Definition at line 262 of file MachineModuleInfo.cpp.
References llvm_unreachable.
MachineModuleInfo::MachineModuleInfo (const MCAsmInfo & MAI, const MCRegisterInfo & MRI, const MCObjectFileInfo * MOFI)
Definition at line 255 of file MachineModuleInfo.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeMachineModuleInfoPass().
MachineModuleInfo::~MachineModuleInfo () [override]
Definition at line 269 of file MachineModuleInfo.cpp.
Member Function Documentation
void MachineModuleInfo::addCatchTypeInfo (MachineBasicBlock * LandingPad, ArrayRef< const GlobalValue * > TyInfo)
addCatchTypeInfo - Provide the catch typeinfo for a landing pad.
Definition at line 422 of file MachineModuleInfo.cpp.
References getOrCreateLandingPadInfo(), getTypeIDFor(), N, llvm::ArrayRef< T >::size(), and llvm::LandingPadInfo::TypeIds.
Referenced by llvm::AddLandingPadInfo().
void MachineModuleInfo::addCleanup (MachineBasicBlock * LandingPad)
addCleanup - Add a cleanup action for a landing pad.
Definition at line 443 of file MachineModuleInfo.cpp.
References getOrCreateLandingPadInfo(), and llvm::LandingPadInfo::TypeIds.
Referenced by llvm::AddLandingPadInfo().
void MachineModuleInfo::addFilterTypeInfo (MachineBasicBlock * LandingPad, ArrayRef< const GlobalValue * > TyInfo)
addFilterTypeInfo - Provide the filter typeinfo for a landing pad.
Definition at line 432 of file MachineModuleInfo.cpp.
References getFilterIDFor(), getOrCreateLandingPadInfo(), getTypeIDFor(), I, llvm::ArrayRef< T >::size(), and llvm::LandingPadInfo::TypeIds.
Referenced by llvm::AddLandingPadInfo().
unsigned LLVM_ATTRIBUTE_UNUSED_RESULT llvm::MachineModuleInfo::addFrameInst (const MCCFIInstruction & Inst) [inline]
Definition at line 279 of file MachineModuleInfo.h.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), EmitCfiOffset(), EmitDefCfaOffset(), EmitDefCfaRegister(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), and llvm::SystemZFrameLowering::emitPrologue().
void MachineModuleInfo::addInvoke (MachineBasicBlock * LandingPad, MCSymbol * BeginLabel, MCSymbol * EndLabel)
addInvoke - Provide the begin and end labels of an invoke style call and associate it with a try landing pad block.
Definition at line 378 of file MachineModuleInfo.cpp.
References llvm::LandingPadInfo::BeginLabels, llvm::LandingPadInfo::EndLabels, getOrCreateLandingPadInfo(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
MCSymbol * MachineModuleInfo::addLandingPad (MachineBasicBlock * LandingPad)
addLandingPad - Add a new panding pad.
addLandingPad - Provide the label of a try LandingPad block.
Returns the label ID for the landing pad entry.
Definition at line 387 of file MachineModuleInfo.cpp.
References llvm::MCContext::createTempSymbol(), getOrCreateLandingPadInfo(), and llvm::LandingPadInfo::LandingPadLabel.
void MachineModuleInfo::addPersonality (MachineBasicBlock * LandingPad, const Function * Personality)
addPersonality - Provide the personality function for the exception information.
Definition at line 396 of file MachineModuleInfo.cpp.
References getOrCreateLandingPadInfo(), and llvm::LandingPadInfo::Personality.
Referenced by llvm::AddLandingPadInfo().
void MachineModuleInfo::addSEHCatchHandler (MachineBasicBlock * LandingPad, const Function * Filter, const BlockAddress * RecoverLabel)
Definition at line 448 of file MachineModuleInfo.cpp.
References llvm::SEHHandler::FilterOrFinally, getOrCreateLandingPadInfo(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SEHHandler::RecoverBA, and llvm::LandingPadInfo::SEHHandlers.
void MachineModuleInfo::addSEHCleanupHandler (MachineBasicBlock * LandingPad, const Function * Cleanup)
Definition at line 458 of file MachineModuleInfo.cpp.
References llvm::Cleanup, llvm::SEHHandler::FilterOrFinally, getOrCreateLandingPadInfo(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SEHHandler::RecoverBA, and llvm::LandingPadInfo::SEHHandlers.
void MachineModuleInfo::addWinEHState (MachineBasicBlock * LandingPad, int State)
Definition at line 413 of file MachineModuleInfo.cpp.
References getOrCreateLandingPadInfo(), and llvm::LandingPadInfo::WinEHState.
Referenced by llvm::FunctionLoweringInfo::set().
bool llvm::MachineModuleInfo::callsEHReturn () const [inline]
Definition at line 249 of file MachineModuleInfo.h.
Referenced by findDeadCallerSavedReg(), llvm::X86FrameLowering::hasFP(), and llvm::XCoreFrameLowering::processFunctionBeforeCalleeSavedScan().
bool llvm::MachineModuleInfo::callsUnwindInit () const [inline]
Definition at line 252 of file MachineModuleInfo.h.
Referenced by llvm::X86FrameLowering::hasFP(), and llvm::XCoreFrameLowering::processFunctionBeforeCalleeSavedScan().
bool MachineModuleInfo::doFinalization (Module &) [override, virtual]
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
Reimplemented from llvm::Pass.
Definition at line 288 of file MachineModuleInfo.cpp.
References llvm::MCContext::reset().
bool MachineModuleInfo::doInitialization (Module &) [override, virtual]
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Reimplemented from llvm::Pass.
Definition at line 272 of file MachineModuleInfo.cpp.
References llvm::Unknown.
void MachineModuleInfo::EndFunction ()
EndFunction - Discard function meta information.
Definition at line 305 of file MachineModuleInfo.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::SmallVectorImpl< T >::clear(), llvm::Unknown, and VariableDbgInfos.
Referenced by llvm::AsmPrinter::EmitFunctionBody().
MCSymbol * MachineModuleInfo::getAddrLabelSymbol (const BasicBlock * BB)
getAddrLabelSymbol - Return the symbol to be used for the specified basic block when its address is taken.
This cannot be its normal LBB label because the block may be accessed outside its containing function.
Definition at line 327 of file MachineModuleInfo.cpp.
References llvm::MMIAddrLabelMap::getAddrLabelSymbol().
Referenced by llvm::AsmPrinter::GetBlockAddressSymbol().
std::vector< MCSymbol * > MachineModuleInfo::getAddrLabelSymbolToEmit (const BasicBlock * BB)
getAddrLabelSymbolToEmit - Return the symbol to be used for the specified basic block when its address is taken.
If other blocks were RAUW'd to this one, we may have to emit them as well, return the whole set.
Definition at line 338 of file MachineModuleInfo.cpp.
References llvm::MMIAddrLabelMap::getAddrLabelSymbolToEmit().
Referenced by llvm::AsmPrinter::EmitBasicBlockStart().
unsigned llvm::MachineModuleInfo::getCallSiteBeginLabel (MCSymbol * BeginLabel) [inline]
getCallSiteBeginLabel - Get the call site number for a begin label.
Definition at line 395 of file MachineModuleInfo.h.
References hasCallSiteBeginLabel().
Referenced by llvm::EHStreamer::computeCallSiteTable().
SmallVectorImpl<unsigned>& llvm::MachineModuleInfo::getCallSiteLandingPad (MCSymbol * Sym) [inline]
getCallSiteLandingPad - Get the call site indexes for a landing pad EH symbol.
Definition at line 377 of file MachineModuleInfo.h.
References hasCallSiteLandingPad().
const MCContext& llvm::MachineModuleInfo::getContext () const [inline]
Definition at line 217 of file MachineModuleInfo.h.
Referenced by addPassesToGenerateCode(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::DwarfDebug::beginInstruction(), llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), emitDebugValueComment(), llvm::AsmPrinter::EmitDwarfRegOp(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::AsmPrinter::emitImplicitDef(), emitKill(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), llvm::DwarfDebug::endInstruction(), LowerEXCEPTIONINFO(), and LowerINTRINSIC_WO_CHAIN().
MCContext& llvm::MachineModuleInfo::getContext () [inline]
Definition at line 218 of file MachineModuleInfo.h.
unsigned llvm::MachineModuleInfo::getCurrentCallSite () [inline]
getCurrentCallSite - Get the call site currently being processed, if any.
return zero if none.
Definition at line 412 of file MachineModuleInfo.h.
int MachineModuleInfo::getFilterIDFor (std::vector< unsigned > & TyIds)
getFilterIDFor - Return the id of the filter encoded by TyIds.
getFilterIDFor - Return the filter id for the specified typeinfos.
This is function wide.
Definition at line 531 of file MachineModuleInfo.cpp.
References I.
Referenced by addFilterTypeInfo().
const std::vector<unsigned>& llvm::MachineModuleInfo::getFilterIds () const [inline]
getFilterIds - Return a reference to the typeids encoding filters used in the current function.
Definition at line 422 of file MachineModuleInfo.h.
Referenced by llvm::EHStreamer::computeActionsTable(), llvm::EHStreamer::emitExceptionTable(), and llvm::EHStreamer::emitTypeInfos().
const std::vector<MCCFIInstruction>& llvm::MachineModuleInfo::getFrameInstructions () const [inline]
Returns a reference to a list of cfi instructions in the current function's prologue.
Used to construct frame maps for debug and exception handling comsumers.
Definition at line 274 of file MachineModuleInfo.h.
Referenced by llvm::AsmPrinter::emitCFIInstruction().
const std::vector<LandingPadInfo>& llvm::MachineModuleInfo::getLandingPads () const [inline]
getLandingPads - Return a reference to the landing pad info for the current function.
Definition at line 367 of file MachineModuleInfo.h.
Referenced by llvm::DwarfCFIException::beginFunction(), llvm::WinException::beginFunction(), llvm::EHStreamer::emitExceptionTable(), llvm::AsmPrinter::EmitFunctionBody(), llvm::ARMException::endFunction(), llvm::DwarfCFIExceptionBase::markFunctionEnd(), and llvm::AsmPrinter::SetupMachineFunction().
const Module* llvm::MachineModuleInfo::getModule () const [inline]
Definition at line 221 of file MachineModuleInfo.h.
Referenced by llvm::DwarfDebug::beginModule(), llvm::DwarfDebug::DwarfDebug(), EmitGCCInlineAsmStr(), EmitMSInlineAsmStr(), llvm::WinException::endModule(), and llvm::WinCodeViewLineTables::WinCodeViewLineTables().
template<typename Ty > Ty& llvm::MachineModuleInfo::getObjFileInfo () [inline]
getInfo - Keep track of various per-function pieces of information for backends that would like to do so.
Definition at line 233 of file MachineModuleInfo.h.
Referenced by llvm::AsmPrinter::doFinalization(), llvm::ARMAsmPrinter::EmitEndOfAsmFile(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::TargetLoweringObjectFileMachO::getCFIPersonalitySymbol(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), getMachOMMI(), llvm::SparcELFTargetObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference(), and printSymbolOperand().
template<typename Ty > const Ty& llvm::MachineModuleInfo::getObjFileInfo () const [inline]
Definition at line 240 of file MachineModuleInfo.h.
LandingPadInfo & MachineModuleInfo::getOrCreateLandingPadInfo (MachineBasicBlock * LandingPad)
getOrCreateLandingPadInfo - Find or create an LandingPadInfo for the specified MachineBasicBlock.
Definition at line 364 of file MachineModuleInfo.cpp.
References llvm::LandingPadInfo::LandingPadBlock, and N.
Referenced by addCatchTypeInfo(), addCleanup(), addFilterTypeInfo(), addInvoke(), addLandingPad(), addPersonality(), addSEHCatchHandler(), addSEHCleanupHandler(), and addWinEHState().
const std::vector<const Function *>& llvm::MachineModuleInfo::getPersonalities () const [inline]
getPersonalities - Return array of personality functions ever seen.
Definition at line 329 of file MachineModuleInfo.h.
Referenced by llvm::DwarfCFIException::endModule().
const Function * MachineModuleInfo::getPersonality () const
getPersonality - Return a personality function if available.
getPersonality - Return the personality function for the current function.
The presence of one is required to emit exception handling info.
Definition at line 560 of file MachineModuleInfo.cpp.
Referenced by llvm::DwarfCFIException::beginFunction(), llvm::WinException::beginFunction(), llvm::ARMException::endFunction(), and getPersonalityType().
unsigned MachineModuleInfo::getPersonalityIndex () const
getPersonalityIndex - Get index of the current personality function inside Personalitites array
getPersonalityIndex - Return unique index for current personality function.
NULL/first personality function should always get zero index.
Definition at line 577 of file MachineModuleInfo.cpp.
EHPersonality MachineModuleInfo::getPersonalityType ()
Classify the personality function amongst known EH styles.
Definition at line 567 of file MachineModuleInfo.cpp.
References llvm::classifyEHPersonality(), F(), getPersonality(), and Unknown.
Referenced by llvm::WinException::endFunction().
unsigned MachineModuleInfo::getTypeIDFor (const GlobalValue * TI)
getTypeIDFor - Return the type id for the specified typeinfo.
This is function wide.
Definition at line 521 of file MachineModuleInfo.cpp.
References N.
Referenced by addCatchTypeInfo(), addFilterTypeInfo(), and llvm::SelectionDAGBuilder::visitLandingPadClauseBB().
const std::vector<const GlobalValue *>& llvm::MachineModuleInfo::getTypeInfos () const [inline]
getTypeInfos - Return a reference to the C++ typeinfo for the current function.
Definition at line 416 of file MachineModuleInfo.h.
Referenced by llvm::EHStreamer::emitExceptionTable(), and llvm::EHStreamer::emitTypeInfos().
VariableDbgInfoMapTy& llvm::MachineModuleInfo::getVariableDbgInfo () [inline]
Definition at line 440 of file MachineModuleInfo.h.
References VariableDbgInfos.
WinEHFuncInfo & MachineModuleInfo::getWinEHFuncInfo (const Function * F)
Definition at line 605 of file MachineModuleInfo.cpp.
References getWinEHParent().
Referenced by llvm::WinException::beginFunction(), and llvm::FunctionLoweringInfo::set().
const Function * MachineModuleInfo::getWinEHParent (const Function * F) const
Definition at line 597 of file MachineModuleInfo.cpp.
References llvm::StringRef::empty(), llvm::Function::getFnAttribute(), llvm::Module::getFunction(), llvm::Value::getName(), llvm::GlobalValue::getParent(), and llvm::Attribute::getValueAsString().
Referenced by llvm::WinException::beginFunction(), getWinEHFuncInfo(), hasWinEHFuncInfo(), and llvm::FunctionLoweringInfo::set().
bool llvm::MachineModuleInfo::hasCallSiteBeginLabel (MCSymbol * BeginLabel) [inline]
hasCallSiteBeginLabel - Return true if the begin label has a call site number associated with it.
Definition at line 403 of file MachineModuleInfo.h.
Referenced by getCallSiteBeginLabel().
bool llvm::MachineModuleInfo::hasCallSiteLandingPad (MCSymbol * Sym) [inline]
hasCallSiteLandingPad - Return true if the landing pad Eh symbol has an associated call site.
Definition at line 385 of file MachineModuleInfo.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty().
Referenced by getCallSiteLandingPad().
bool llvm::MachineModuleInfo::hasDebugInfo () const [inline]
hasDebugInfo - Returns true if valid debug info is present.
Definition at line 246 of file MachineModuleInfo.h.
Referenced by llvm::WinCodeViewLineTables::beginFunction(), llvm::DwarfDebug::beginFunction(), llvm::AsmPrinter::EmitFunctionBody(), llvm::AArch64FrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::DwarfDebug::endFunction(), llvm::DwarfDebug::endModule(), llvm::AsmPrinter::needsCFIMoves(), llvm::XCoreRegisterInfo::needsFrameMoves(), llvm::FastISel::selectIntrinsicCall(), llvm::FunctionLoweringInfo::set(), and llvm::AsmPrinter::SetupMachineFunction().
bool llvm::MachineModuleInfo::hasWinEHFuncInfo (const Function * F) const [inline]
Definition at line 225 of file MachineModuleInfo.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), and getWinEHParent().
void llvm::MachineModuleInfo::setCallsEHReturn (bool b) [inline]
Definition at line 250 of file MachineModuleInfo.h.
void llvm::MachineModuleInfo::setCallSiteBeginLabel (MCSymbol * BeginLabel, unsigned Site) [inline]
setCallSiteBeginLabel - Map the begin label for a call site.
Definition at line 390 of file MachineModuleInfo.h.
void MachineModuleInfo::setCallSiteLandingPad (MCSymbol * Sym, ArrayRef< unsigned > Sites)
setCallSiteLandingPad - Map the landing pad's EH symbol to the call site indexes.
Definition at line 514 of file MachineModuleInfo.cpp.
References llvm::ArrayRef< T >::begin(), and llvm::ArrayRef< T >::end().
void llvm::MachineModuleInfo::setCallsUnwindInit (bool b) [inline]
Definition at line 253 of file MachineModuleInfo.h.
void llvm::MachineModuleInfo::setCurrentCallSite (unsigned Site) [inline]
setCurrentCallSite - Set the call site currently being processed.
Definition at line 408 of file MachineModuleInfo.h.
void llvm::MachineModuleInfo::setDebugInfoAvailability (bool avail) [inline]
Definition at line 247 of file MachineModuleInfo.h.
Referenced by llvm::DwarfDebug::beginModule(), and llvm::WinCodeViewLineTables::WinCodeViewLineTables().
void llvm::MachineModuleInfo::setModule (const Module * M) [inline]
Definition at line 220 of file MachineModuleInfo.h.
void llvm::MachineModuleInfo::setUsesMorestackAddr (bool b) [inline]
Definition at line 267 of file MachineModuleInfo.h.
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks().
void llvm::MachineModuleInfo::setUsesVAFloatArgument (bool b) [inline]
Definition at line 259 of file MachineModuleInfo.h.
Referenced by llvm::ComputeUsesVAFloatArgument().
void llvm::MachineModuleInfo::setVariableDbgInfo (const DILocalVariable * Var, const DIExpression * Expr, unsigned Slot, const DILocation * Loc) [inline]
setVariableDbgInfo - Collect information used to emit debugging information of a variable.
Definition at line 435 of file MachineModuleInfo.h.
References llvm::SmallVectorImpl< T >::emplace_back(), and VariableDbgInfos.
Referenced by llvm::FunctionLoweringInfo::set().
void MachineModuleInfo::takeDeletedSymbolsForFunction (const Function * F, std::vector< MCSymbol * > & Result)
takeDeletedSymbolsForFunction - If the specified function has had any references to address-taken blocks generated, but the block got deleted, return the symbol now so we can emit it.
This prevents emitting a reference to a symbol that has no definition.
Definition at line 351 of file MachineModuleInfo.cpp.
void MachineModuleInfo::TidyLandingPads (DenseMap< MCSymbol *, uintptr_t > * LPMap = nullptr)
TidyLandingPads - Remap landing pad labels and remove any deleted landing pads.
Definition at line 469 of file MachineModuleInfo.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::LandingPadInfo::BeginLabels, llvm::LandingPadInfo::EndLabels, llvm::SmallVectorImpl< T >::erase(), llvm::MCSymbol::isDefined(), llvm::LandingPadInfo::LandingPadBlock, llvm::LandingPadInfo::LandingPadLabel, and llvm::LandingPadInfo::TypeIds.
Referenced by llvm::WinException::endFunction(), and llvm::DwarfCFIExceptionBase::markFunctionEnd().
bool llvm::MachineModuleInfo::usesMorestackAddr () const [inline]
Definition at line 263 of file MachineModuleInfo.h.
Referenced by llvm::AsmPrinter::doFinalization().
bool llvm::MachineModuleInfo::usesVAFloatArgument () const [inline]
Definition at line 255 of file MachineModuleInfo.h.
Referenced by llvm::ComputeUsesVAFloatArgument(), and llvm::X86AsmPrinter::EmitEndOfAsmFile().
Member Data Documentation
char llvm::MachineModuleInfo::ID [static]
Definition at line 188 of file MachineModuleInfo.h.
VariableDbgInfoMapTy llvm::MachineModuleInfo::VariableDbgInfos
Definition at line 201 of file MachineModuleInfo.h.
Referenced by EndFunction(), getVariableDbgInfo(), and setVariableDbgInfo().
The documentation for this class was generated from the following files:
MachineModuleInfo.h
MachineModuleInfo.cpp