LLVM: llvm::DwarfTypeUnit Class Reference
llvm::DwarfTypeUnit Class Reference
#include <DwarfUnit.h>
Public Member Functions
DwarfTypeUnit (unsigned UID, DwarfCompileUnit &CU, AsmPrinter *A, DwarfDebug *DW, DwarfFile *DWU, MCDwarfDwoLineTable *SplitLineTable=nullptr)
void setTypeSignature (uint64_t Signature)
uint64_t getTypeSignature () const
void setType (const DIE *Ty)
void emitHeader (bool UseOffsets) override
Emit the header for this unit, not including the initial length field.
unsigned getHeaderSize () const override
Compute the size of a header for this unit, not including the initial length field.
DwarfCompileUnit & getCU () override
Detailed Description
Definition at line 379 of file DwarfUnit.h.
Constructor & Destructor Documentation
DwarfTypeUnit::DwarfTypeUnit (unsigned UID, DwarfCompileUnit & CU, AsmPrinter * A, DwarfDebug * DW, DwarfFile * DWU, MCDwarfDwoLineTable * SplitLineTable = nullptr)
Definition at line 75 of file DwarfUnit.cpp.
References llvm::DwarfUnit::addSectionOffset(), llvm::dwarf::DW_AT_stmt_list, and llvm::DwarfUnit::UnitDie.
Member Function Documentation
void DwarfTypeUnit::emitHeader (bool UseOffsets) [override, virtual]
Emit the header for this unit, not including the initial length field.
Reimplemented from llvm::DwarfUnit.
Definition at line 1464 of file DwarfUnit.cpp.
References llvm::DwarfUnit::Asm, and llvm::AsmPrinter::OutStreamer.
DwarfCompileUnit& llvm::DwarfTypeUnit::getCU () [inline, override, virtual]
Implements llvm::DwarfUnit.
Definition at line 403 of file DwarfUnit.h.
unsigned llvm::DwarfTypeUnit::getHeaderSize () const [inline, override, virtual]
Compute the size of a header for this unit, not including the initial length field.
Reimplemented from llvm::DwarfUnit.
Definition at line 399 of file DwarfUnit.h.
uint64_t llvm::DwarfTypeUnit::getTypeSignature () const [inline]
Definition at line 394 of file DwarfUnit.h.
Referenced by llvm::DIETypeSignature::EmitValue(), and llvm::DIETypeSignature::print().
void llvm::DwarfTypeUnit::setType (const DIE * Ty) [inline]
Definition at line 395 of file DwarfUnit.h.
void llvm::DwarfTypeUnit::setTypeSignature (uint64_t Signature) [inline]
Definition at line 393 of file DwarfUnit.h.
The documentation for this class was generated from the following files:
DwarfUnit.h
DwarfUnit.cpp