LLVM: llvm::InstrProfIncrementInst Class Reference
llvm::InstrProfIncrementInst Class Reference
This represents the llvm.instrprof_increment intrinsic.
#include <IntrinsicInst.h>
Public Member Functions
GlobalVariable * getName () const
Return a constant reference to the value's name.
ConstantInt * getHash () const
ConstantInt * getNumCounters () const
ConstantInt * getIndex () const
Static Public Member Functions
static bool classof (const IntrinsicInst *I)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Detailed Description
This represents the llvm.instrprof_increment intrinsic.
Definition at line 349 of file IntrinsicInst.h.
Member Function Documentation
static bool llvm::InstrProfIncrementInst::classof (const IntrinsicInst * I) [inline, static]
Definition at line 351 of file IntrinsicInst.h.
References llvm::IntrinsicInst::getIntrinsicID().
Referenced by classof().
static bool llvm::InstrProfIncrementInst::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::IntrinsicInst.
Definition at line 354 of file IntrinsicInst.h.
References classof().
ConstantInt* llvm::InstrProfIncrementInst::getHash () const [inline]
Definition at line 363 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperand().
ConstantInt* llvm::InstrProfIncrementInst::getIndex () const [inline]
Definition at line 371 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperand().
GlobalVariable* llvm::InstrProfIncrementInst::getName () const [inline]
Return a constant reference to the value's name.
This is cheap and guaranteed to return the same reference as long as the value is not modified.
Reimplemented from llvm::Value.
Definition at line 358 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperand(), and llvm::Value::stripPointerCasts().
Referenced by getVarName().
ConstantInt* llvm::InstrProfIncrementInst::getNumCounters () const [inline]
Definition at line 367 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperand().
The documentation for this class was generated from the following file:
IntrinsicInst.h