LLVM: llvm::MaskedGatherSDNode Class Reference
llvm::MaskedGatherSDNode Class Reference
This class is used to represent an MGATHER node.
#include <SelectionDAGNodes.h>
Public Member Functions
MaskedGatherSDNode (unsigned Order, DebugLoc dl, ArrayRef< SDValue > Operands, SDVTList VTs, EVT MemVT, MachineMemOperand *MMO)
Static Public Member Functions
static bool classof (const SDNode *N)
Friends
class SelectionDAG
Detailed Description
This class is used to represent an MGATHER node.
Definition at line 2086 of file SelectionDAGNodes.h.
Constructor & Destructor Documentation
llvm::MaskedGatherSDNode::MaskedGatherSDNode (unsigned Order, DebugLoc dl, ArrayRef< SDValue > Operands, SDVTList VTs, EVT MemVT, MachineMemOperand * MMO) [inline]
Definition at line 2089 of file SelectionDAGNodes.h.
References llvm::MaskedGatherScatterSDNode::getMask(), llvm::MaskedGatherScatterSDNode::getValue(), llvm::SDNode::getValueType(), and llvm::MVT::i1.
Member Function Documentation
static bool llvm::MaskedGatherSDNode::classof (const SDNode * N) [inline, static]
Reimplemented from llvm::MaskedGatherScatterSDNode.
Definition at line 2102 of file SelectionDAGNodes.h.
References llvm::SDNode::getOpcode(), and llvm::ISD::MGATHER.
Friends And Related Function Documentation
friend class SelectionDAG [friend]
Reimplemented from llvm::MaskedGatherScatterSDNode.
Definition at line 2088 of file SelectionDAGNodes.h.
The documentation for this class was generated from the following file:
SelectionDAGNodes.h