LLVM: llvm::Target Class Reference
llvm::Target Class Reference
Target - Wrapper for Target specific information.
#include <TargetRegistry.h>
Public Types
typedef bool(* ArchMatchFnTy)(Triple::ArchType Arch)
typedef MCAsmInfo *(* MCAsmInfoCtorFnTy)(const MCRegisterInfo &MRI, const Triple &TT)
typedef MCCodeGenInfo *(* MCCodeGenInfoCtorFnTy)(StringRef TT, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
typedef MCInstrInfo *(* MCInstrInfoCtorFnTy)(void)
typedef MCInstrAnalysis *(* MCInstrAnalysisCtorFnTy)(const MCInstrInfo *Info)
typedef MCRegisterInfo *(* MCRegInfoCtorFnTy)(StringRef TT)
typedef MCSubtargetInfo *(* MCSubtargetInfoCtorFnTy)(const Triple &TT, StringRef CPU, StringRef Features)
typedef TargetMachine *(* TargetMachineCtorTy)(const Target &T, StringRef TT, StringRef CPU, StringRef Features, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
typedef AsmPrinter *(* AsmPrinterCtorTy)(TargetMachine &TM, std::unique_ptr< MCStreamer > &&Streamer)
typedef MCAsmBackend *(* MCAsmBackendCtorTy)(const Target &T, const MCRegisterInfo &MRI, const Triple &TT, StringRef CPU)
typedef MCTargetAsmParser *(* MCAsmParserCtorTy)(MCSubtargetInfo &STI, MCAsmParser &P, const MCInstrInfo &MII, const MCTargetOptions &Options)
typedef MCDisassembler *(* MCDisassemblerCtorTy)(const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
typedef MCInstPrinter *(* MCInstPrinterCtorTy)(const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
typedef MCCodeEmitter *(* MCCodeEmitterCtorTy)(const MCInstrInfo &II, const MCRegisterInfo &MRI, MCContext &Ctx)
typedef MCStreamer *(* ELFStreamerCtorTy)(const Triple &T, MCContext &Ctx, MCAsmBackend &TAB, raw_pwrite_stream &OS, MCCodeEmitter *Emitter, bool RelaxAll)
typedef MCStreamer *(* MachOStreamerCtorTy)(MCContext &Ctx, MCAsmBackend &TAB, raw_pwrite_stream &OS, MCCodeEmitter *Emitter, bool RelaxAll, bool DWARFMustBeAtTheEnd)
typedef MCStreamer *(* COFFStreamerCtorTy)(MCContext &Ctx, MCAsmBackend &TAB, raw_pwrite_stream &OS, MCCodeEmitter *Emitter, bool RelaxAll)
typedef MCTargetStreamer *(* NullTargetStreamerCtorTy)(MCStreamer &S)
typedef MCTargetStreamer *(* AsmTargetStreamerCtorTy)(MCStreamer &S, formatted_raw_ostream &OS, MCInstPrinter *InstPrint, bool IsVerboseAsm)
typedef MCTargetStreamer *(* ObjectTargetStreamerCtorTy)(MCStreamer &S, const MCSubtargetInfo &STI)
typedef MCRelocationInfo *(* MCRelocationInfoCtorTy)(const Triple &TT, MCContext &Ctx)
typedef MCSymbolizer *(* MCSymbolizerCtorTy)(StringRef TT, LLVMOpInfoCallback GetOpInfo, LLVMSymbolLookupCallback SymbolLookUp, void *DisInfo, MCContext *Ctx, std::unique_ptr< MCRelocationInfo > &&RelInfo)
Public Member Functions
Target ()
bool hasJIT () const
hasJIT - Check if this targets supports the just-in-time compilation.
bool hasTargetMachine () const
hasTargetMachine - Check if this target supports code generation.
bool hasMCAsmBackend () const
hasMCAsmBackend - Check if this target supports .o generation.
MCAsmInfo * createMCAsmInfo (const MCRegisterInfo &MRI, StringRef TheTriple) const
createMCAsmInfo - Create a MCAsmInfo implementation for the specified target triple.
MCCodeGenInfo * createMCCodeGenInfo (StringRef Triple, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL) const
createMCCodeGenInfo - Create a MCCodeGenInfo implementation.
MCInstrInfo * createMCInstrInfo () const
createMCInstrInfo - Create a MCInstrInfo implementation.
MCInstrAnalysis * createMCInstrAnalysis (const MCInstrInfo *Info) const
createMCInstrAnalysis - Create a MCInstrAnalysis implementation.
MCRegisterInfo * createMCRegInfo (StringRef Triple) const
createMCRegInfo - Create a MCRegisterInfo implementation.
MCSubtargetInfo * createMCSubtargetInfo (StringRef TheTriple, StringRef CPU, StringRef Features) const
createMCSubtargetInfo - Create a MCSubtargetInfo implementation.
TargetMachine * createTargetMachine (StringRef Triple, StringRef CPU, StringRef Features, const TargetOptions &Options, Reloc::Model RM=Reloc::Default, CodeModel::Model CM=CodeModel::Default, CodeGenOpt::Level OL=CodeGenOpt::Default) const
createTargetMachine - Create a target specific machine implementation for the specified Triple.
MCAsmBackend * createMCAsmBackend (const MCRegisterInfo &MRI, StringRef TheTriple, StringRef CPU) const
createMCAsmBackend - Create a target specific assembly parser.
MCTargetAsmParser * createMCAsmParser (MCSubtargetInfo &STI, MCAsmParser &Parser, const MCInstrInfo &MII, const MCTargetOptions &Options) const
createMCAsmParser - Create a target specific assembly parser.
AsmPrinter * createAsmPrinter (TargetMachine &TM, std::unique_ptr< MCStreamer > &&Streamer) const
createAsmPrinter - Create a target specific assembly printer pass.
MCDisassembler * createMCDisassembler (const MCSubtargetInfo &STI, MCContext &Ctx) const
MCInstPrinter * createMCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI) const
MCCodeEmitter * createMCCodeEmitter (const MCInstrInfo &II, const MCRegisterInfo &MRI, MCContext &Ctx) const
createMCCodeEmitter - Create a target specific code emitter.
MCStreamer * createMCObjectStreamer (const Triple &T, MCContext &Ctx, MCAsmBackend &TAB, raw_pwrite_stream &OS, MCCodeEmitter *Emitter, const MCSubtargetInfo &STI, bool RelaxAll, bool DWARFMustBeAtTheEnd) const
Create a target specific MCStreamer.
MCStreamer * createAsmStreamer (MCContext &Ctx, std::unique_ptr< formatted_raw_ostream > OS, bool IsVerboseAsm, bool UseDwarfDirectory, MCInstPrinter *InstPrint, MCCodeEmitter *CE, MCAsmBackend *TAB, bool ShowInst) const
MCTargetStreamer * createAsmTargetStreamer (MCStreamer &S, formatted_raw_ostream &OS, MCInstPrinter *InstPrint, bool IsVerboseAsm) const
MCStreamer * createNullStreamer (MCContext &Ctx) const
MCTargetStreamer * createNullTargetStreamer (MCStreamer &S) const
MCRelocationInfo * createMCRelocationInfo (StringRef TT, MCContext &Ctx) const
createMCRelocationInfo - Create a target specific MCRelocationInfo.
MCSymbolizer * createMCSymbolizer (StringRef TT, LLVMOpInfoCallback GetOpInfo, LLVMSymbolLookupCallback SymbolLookUp, void *DisInfo, MCContext *Ctx, std::unique_ptr< MCRelocationInfo > &&RelInfo) const
createMCSymbolizer - Create a target specific MCSymbolizer.
Target Information
const Target * getNext () const
const char * getName () const
getName - Get the target name.
const char * getShortDescription () const
getShortDescription - Get a short description of the target.
Friends
struct TargetRegistry
Detailed Description
Target - Wrapper for Target specific information.
For registration purposes, this is a POD type so that targets can be registered without the use of static constructors.
Targets should implement a single global instance of this class (which will be zero initialized), and pass that instance to the TargetRegistry as part of their initialization.
Definition at line 87 of file TargetRegistry.h.
Member Typedef Documentation
typedef bool(* llvm::Target::ArchMatchFnTy)(Triple::ArchType Arch)
Definition at line 91 of file TargetRegistry.h.
typedef AsmPrinter*(* llvm::Target::AsmPrinterCtorTy)(TargetMachine &TM, std::unique_ptr< MCStreamer > &&Streamer)
Definition at line 111 of file TargetRegistry.h.
typedef MCTargetStreamer*(* llvm::Target::AsmTargetStreamerCtorTy)(MCStreamer &S, formatted_raw_ostream &OS, MCInstPrinter *InstPrint, bool IsVerboseAsm)
Definition at line 145 of file TargetRegistry.h.
typedef MCStreamer*(* llvm::Target::COFFStreamerCtorTy)(MCContext &Ctx, MCAsmBackend &TAB, raw_pwrite_stream &OS, MCCodeEmitter *Emitter, bool RelaxAll)
Definition at line 140 of file TargetRegistry.h.
typedef MCStreamer*(* llvm::Target::ELFStreamerCtorTy)(const Triple &T, MCContext &Ctx, MCAsmBackend &TAB, raw_pwrite_stream &OS, MCCodeEmitter *Emitter, bool RelaxAll)
Definition at line 130 of file TargetRegistry.h.
typedef MCStreamer*(* llvm::Target::MachOStreamerCtorTy)(MCContext &Ctx, MCAsmBackend &TAB, raw_pwrite_stream &OS, MCCodeEmitter *Emitter, bool RelaxAll, bool DWARFMustBeAtTheEnd)
Definition at line 135 of file TargetRegistry.h.
typedef MCAsmBackend*(* llvm::Target::MCAsmBackendCtorTy)(const Target &T, const MCRegisterInfo &MRI, const Triple &TT, StringRef CPU)
Definition at line 113 of file TargetRegistry.h.
typedef MCAsmInfo*(* llvm::Target::MCAsmInfoCtorFnTy)(const MCRegisterInfo &MRI, const Triple &TT)
Definition at line 93 of file TargetRegistry.h.
typedef MCTargetAsmParser*(* llvm::Target::MCAsmParserCtorTy)(MCSubtargetInfo &STI, MCAsmParser &P, const MCInstrInfo &MII, const MCTargetOptions &Options)
Definition at line 116 of file TargetRegistry.h.
typedef MCCodeEmitter*(* llvm::Target::MCCodeEmitterCtorTy)(const MCInstrInfo &II, const MCRegisterInfo &MRI, MCContext &Ctx)
Definition at line 127 of file TargetRegistry.h.
typedef MCCodeGenInfo*(* llvm::Target::MCCodeGenInfoCtorFnTy)(StringRef TT, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
Definition at line 95 of file TargetRegistry.h.
typedef MCDisassembler*(* llvm::Target::MCDisassemblerCtorTy)(const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
Definition at line 119 of file TargetRegistry.h.
typedef MCInstPrinter*(* llvm::Target::MCInstPrinterCtorTy)(const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
Definition at line 122 of file TargetRegistry.h.
typedef MCInstrAnalysis*(* llvm::Target::MCInstrAnalysisCtorFnTy)(const MCInstrInfo *Info)
Definition at line 99 of file TargetRegistry.h.
typedef MCInstrInfo*(* llvm::Target::MCInstrInfoCtorFnTy)(void)
Definition at line 98 of file TargetRegistry.h.
typedef MCRegisterInfo*(* llvm::Target::MCRegInfoCtorFnTy)(StringRef TT)
Definition at line 100 of file TargetRegistry.h.
typedef MCRelocationInfo*(* llvm::Target::MCRelocationInfoCtorTy)(const Triple &TT, MCContext &Ctx)
Definition at line 150 of file TargetRegistry.h.
typedef MCSubtargetInfo*(* llvm::Target::MCSubtargetInfoCtorFnTy)(const Triple &TT, StringRef CPU, StringRef Features)
Definition at line 101 of file TargetRegistry.h.
typedef MCSymbolizer*(* llvm::Target::MCSymbolizerCtorTy)(StringRef TT, LLVMOpInfoCallback GetOpInfo, LLVMSymbolLookupCallback SymbolLookUp, void *DisInfo, MCContext *Ctx, std::unique_ptr< MCRelocationInfo > &&RelInfo)
Definition at line 152 of file TargetRegistry.h.
typedef MCTargetStreamer*(* llvm::Target::NullTargetStreamerCtorTy)(MCStreamer &S)
Definition at line 144 of file TargetRegistry.h.
typedef MCTargetStreamer*(* llvm::Target::ObjectTargetStreamerCtorTy)(MCStreamer &S, const MCSubtargetInfo &STI)
Definition at line 148 of file TargetRegistry.h.
typedef TargetMachine*(* llvm::Target::TargetMachineCtorTy)(const Target &T, StringRef TT, StringRef CPU, StringRef Features, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
Definition at line 104 of file TargetRegistry.h.
Constructor & Destructor Documentation
llvm::Target::Target () [inline]
Definition at line 252 of file TargetRegistry.h.
Member Function Documentation
AsmPrinter* llvm::Target::createAsmPrinter (TargetMachine & TM, std::unique_ptr< MCStreamer > && Streamer) const [inline]
createAsmPrinter - Create a target specific assembly printer pass.
This takes ownership of the MCStreamer object.
Definition at line 391 of file TargetRegistry.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile(), and llvm::LLVMTargetMachine::addPassesToEmitMC().
MCStreamer* llvm::Target::createAsmStreamer (MCContext & Ctx, std::unique_ptr< formatted_raw_ostream > OS, bool IsVerboseAsm, bool UseDwarfDirectory, MCInstPrinter * InstPrint, MCCodeEmitter * CE, MCAsmBackend * TAB, bool ShowInst) const [inline]
Definition at line 464 of file TargetRegistry.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile().
MCTargetStreamer* llvm::Target::createAsmTargetStreamer (MCStreamer & S, formatted_raw_ostream & OS, MCInstPrinter * InstPrint, bool IsVerboseAsm) const [inline]
Definition at line 477 of file TargetRegistry.h.
MCAsmBackend* llvm::Target::createMCAsmBackend (const MCRegisterInfo & MRI, StringRef TheTriple, StringRef CPU) const [inline]
createMCAsmBackend - Create a target specific assembly parser.
Parameters:
TheTriple The target triple string.
Definition at line 369 of file TargetRegistry.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile(), and llvm::LLVMTargetMachine::addPassesToEmitMC().
MCAsmInfo* llvm::Target::createMCAsmInfo (const MCRegisterInfo & MRI, StringRef TheTriple) const [inline]
createMCAsmInfo - Create a MCAsmInfo implementation for the specified target triple.
Parameters:
TheTriple This argument is used to determine the target machine feature set; it should always be provided. Generally this should be either the target triple from the module, or the target triple of the host if that does not exist.
Definition at line 290 of file TargetRegistry.h.
Referenced by llvm::LLVMTargetMachine::initAsmInfo(), llvm::object::IRObjectFile::IRObjectFile(), and LLVMCreateDisasmCPUFeatures().
MCTargetAsmParser* llvm::Target::createMCAsmParser (MCSubtargetInfo & STI, MCAsmParser & Parser, const MCInstrInfo & MII, const MCTargetOptions & Options) const [inline]
createMCAsmParser - Create a target specific assembly parser.
Parameters:
Parser The target independent parser implementation to use for parsing and lexing.
Definition at line 380 of file TargetRegistry.h.
Referenced by llvm::object::IRObjectFile::IRObjectFile().
MCCodeEmitter* llvm::Target::createMCCodeEmitter (const MCInstrInfo & II, const MCRegisterInfo & MRI, MCContext & Ctx) const [inline]
createMCCodeEmitter - Create a target specific code emitter.
Definition at line 415 of file TargetRegistry.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile(), and llvm::LLVMTargetMachine::addPassesToEmitMC().
MCCodeGenInfo* llvm::Target::createMCCodeGenInfo (StringRef Triple, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL) const [inline]
createMCCodeGenInfo - Create a MCCodeGenInfo implementation.
Definition at line 299 of file TargetRegistry.h.
Referenced by llvm::LLVMTargetMachine::LLVMTargetMachine().
MCDisassembler* llvm::Target::createMCDisassembler (const MCSubtargetInfo & STI, MCContext & Ctx) const [inline]
Definition at line 398 of file TargetRegistry.h.
Referenced by LLVMCreateDisasmCPUFeatures().
MCInstPrinter* llvm::Target::createMCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) const [inline]
Definition at line 405 of file TargetRegistry.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile(), LLVMCreateDisasmCPUFeatures(), and LLVMSetDisasmOptions().
MCInstrAnalysis* llvm::Target::createMCInstrAnalysis (const MCInstrInfo * Info) const [inline]
createMCInstrAnalysis - Create a MCInstrAnalysis implementation.
Definition at line 317 of file TargetRegistry.h.
MCInstrInfo* llvm::Target::createMCInstrInfo () const [inline]
createMCInstrInfo - Create a MCInstrInfo implementation.
Definition at line 309 of file TargetRegistry.h.
Referenced by createX86Disassembler(), llvm::LLVMTargetMachine::initAsmInfo(), llvm::object::IRObjectFile::IRObjectFile(), and LLVMCreateDisasmCPUFeatures().
MCStreamer* llvm::Target::createMCObjectStreamer (const Triple & T, MCContext & Ctx, MCAsmBackend & TAB, raw_pwrite_stream & OS, MCCodeEmitter * Emitter, const MCSubtargetInfo & STI, bool RelaxAll, bool DWARFMustBeAtTheEnd) const [inline]
Create a target specific MCStreamer.
Parameters:
T The target triple.
Ctx The target context.
TAB The target assembler backend object. Takes ownership.
OS The stream object.
Emitter The target independent assembler object.Takes ownership.
RelaxAll Relax all fixups?
Definition at line 431 of file TargetRegistry.h.
References llvm::Triple::COFF, llvm::createELFStreamer(), llvm::createMachOStreamer(), llvm::Triple::ELF, llvm::Triple::getObjectFormat(), llvm::Triple::isOSWindows(), llvm_unreachable, and llvm::Triple::MachO.
MCRegisterInfo* llvm::Target::createMCRegInfo (StringRef Triple) const [inline]
createMCRegInfo - Create a MCRegisterInfo implementation.
Definition at line 325 of file TargetRegistry.h.
Referenced by llvm::LLVMTargetMachine::initAsmInfo(), llvm::object::IRObjectFile::IRObjectFile(), and LLVMCreateDisasmCPUFeatures().
MCRelocationInfo* llvm::Target::createMCRelocationInfo (StringRef TT, MCContext & Ctx) const [inline]
createMCRelocationInfo - Create a target specific MCRelocationInfo.
Parameters:
TT The target triple.
Ctx The target context.
Definition at line 502 of file TargetRegistry.h.
Referenced by LLVMCreateDisasmCPUFeatures().
MCSubtargetInfo* llvm::Target::createMCSubtargetInfo (StringRef TheTriple, StringRef CPU, StringRef Features) const [inline]
createMCSubtargetInfo - Create a MCSubtargetInfo implementation.
Parameters:
TheTriple This argument is used to determine the target machine feature set; it should always be provided. Generally this should be either the target triple from the module, or the target triple of the host if that does not exist.
CPU This specifies the name of the target CPU.
Features This specifies the string representation of the additional target features.
Definition at line 340 of file TargetRegistry.h.
Referenced by llvm::AsmPrinter::doInitialization(), llvm::LLVMTargetMachine::initAsmInfo(), llvm::object::IRObjectFile::IRObjectFile(), and LLVMCreateDisasmCPUFeatures().
MCSymbolizer* llvm::Target::createMCSymbolizer (StringRef TT, LLVMOpInfoCallback GetOpInfo, LLVMSymbolLookupCallback SymbolLookUp, void * DisInfo, MCContext * Ctx, std::unique_ptr< MCRelocationInfo > && RelInfo) const [inline]
createMCSymbolizer - Create a target specific MCSymbolizer.
Parameters:
TT The target triple.
GetOpInfo The function to get the symbolic information for operands.
SymbolLookUp The function to lookup a symbol name.
DisInfo The pointer to the block of symbolic information for above call back.
Ctx The target context.
RelInfo The relocation information for this target. Takes ownership.
Definition at line 522 of file TargetRegistry.h.
Referenced by LLVMCreateDisasmCPUFeatures().
MCStreamer* llvm::Target::createNullStreamer (MCContext & Ctx) const [inline]
Definition at line 486 of file TargetRegistry.h.
MCTargetStreamer* llvm::Target::createNullTargetStreamer (MCStreamer & S) const [inline]
Definition at line 492 of file TargetRegistry.h.
Referenced by llvm::object::IRObjectFile::IRObjectFile().
TargetMachine* llvm::Target::createTargetMachine (StringRef Triple, StringRef CPU, StringRef Features, const TargetOptions & Options, Reloc::Model RM = Reloc::Default, CodeModel::Model CM = CodeModel::Default, CodeGenOpt::Level OL = CodeGenOpt::Default) const [inline]
createTargetMachine - Create a target specific machine implementation for the specified Triple.
Parameters:
Triple This argument is used to determine the target machine feature set; it should always be provided. Generally this should be either the target triple from the module, or the target triple of the host if that does not exist.
Definition at line 355 of file TargetRegistry.h.
References llvm::NVPTX::PTXCvtMode::RM.
Referenced by llvm::EngineBuilder::selectTarget().
const char* llvm::Target::getName () const [inline]
getName - Get the target name.
Definition at line 265 of file TargetRegistry.h.
Referenced by LLVMGetTargetFromName(), llvm::TargetRegistry::lookupTarget(), and llvm::EngineBuilder::selectTarget().
const Target* llvm::Target::getNext () const [inline]
Definition at line 262 of file TargetRegistry.h.
Referenced by llvm::TargetRegistry::iterator::operator++().
const char* llvm::Target::getShortDescription () const [inline]
getShortDescription - Get a short description of the target.
Definition at line 268 of file TargetRegistry.h.
bool llvm::Target::hasJIT () const [inline]
hasJIT - Check if this targets supports the just-in-time compilation.
Definition at line 273 of file TargetRegistry.h.
Referenced by llvm::EngineBuilder::create().
bool llvm::Target::hasMCAsmBackend () const [inline]
hasMCAsmBackend - Check if this target supports .o generation.
Definition at line 279 of file TargetRegistry.h.
bool llvm::Target::hasTargetMachine () const [inline]
hasTargetMachine - Check if this target supports code generation.
Definition at line 276 of file TargetRegistry.h.
Friends And Related Function Documentation
friend struct TargetRegistry [friend]
Definition at line 89 of file TargetRegistry.h.
The documentation for this class was generated from the following file:
TargetRegistry.h