LLVM: llvm::LiveQueryResult Class Reference
llvm::LiveQueryResult Class Reference
Result of a LiveRange query.
#include <LiveInterval.h>
Public Member Functions
LiveQueryResult (VNInfo *EarlyVal, VNInfo *LateVal, SlotIndex EndPoint, bool Kill)
VNInfo * valueIn () const
Return the value that is live-in to the instruction.
bool isKill () const
Return true if the live-in value is killed by this instruction.
bool isDeadDef () const
Return true if this instruction has a dead def.
VNInfo * valueOut () const
Return the value leaving the instruction, if any.
VNInfo * valueOutOrDead () const
Returns the value alive at the end of the instruction, if any.
VNInfo * valueDefined () const
Return the value defined by this instruction, if any.
SlotIndex endPoint () const
Return the end point of the last live range segment to interact with the instruction, if any.
Detailed Description
Result of a LiveRange query.
This class hides the implementation details of live ranges, and it should be used as the primary interface for examining live ranges around instructions.
Definition at line 86 of file LiveInterval.h.
Constructor & Destructor Documentation
llvm::LiveQueryResult::LiveQueryResult (VNInfo * EarlyVal, VNInfo * LateVal, SlotIndex EndPoint, bool Kill) [inline]
Definition at line 93 of file LiveInterval.h.
Member Function Documentation
SlotIndex llvm::LiveQueryResult::endPoint () const [inline]
Return the end point of the last live range segment to interact with the instruction, if any.
The end point is an invalid SlotIndex only if the live range doesn't intersect the instruction at all.
The end point may be at or past the end of the instruction's basic block. That means the value was live out of the block.
Definition at line 143 of file LiveInterval.h.
Referenced by llvm::LiveIntervals::pruneValue().
bool llvm::LiveQueryResult::isDeadDef () const [inline]
Return true if this instruction has a dead def.
Definition at line 113 of file LiveInterval.h.
References llvm::SlotIndex::isDead().
Referenced by llvm::RegPressureTracker::bumpUpwardPressure(), llvm::RegPressureTracker::recede(), and valueOut().
bool llvm::LiveQueryResult::isKill () const [inline]
Return true if the live-in value is killed by this instruction.
This means that either the live range ends at the instruction, or it changes value.
Definition at line 108 of file LiveInterval.h.
Referenced by llvm::RegPressureTracker::advance(), llvm::RegPressureTracker::bumpDownwardPressure(), and llvm::RegPressureTracker::recede().
VNInfo* llvm::LiveQueryResult::valueDefined () const [inline]
Return the value defined by this instruction, if any.
This includes dead defs, it is the value created by the instruction's def operands.
Definition at line 131 of file LiveInterval.h.
Referenced by llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::RegPressureTracker::recede(), and llvm::LiveIntervals::shrinkToUses().
VNInfo* llvm::LiveQueryResult::valueIn () const [inline]
Return the value that is live-in to the instruction.
This is the value that will be read by the instruction's use operands. Return NULL if no value is live-in.
Definition at line 101 of file LiveInterval.h.
Referenced by llvm::ScheduleDAGInstrs::addVRegUseDeps(), llvm::ScheduleDAGMILive::computeCyclicCriticalPath(), llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::LiveIntervals::pruneValue(), llvm::LiveIntervals::shrinkToUses(), and llvm::ScheduleDAGMILive::updatePressureDiffs().
VNInfo* llvm::LiveQueryResult::valueOut () const [inline]
Return the value leaving the instruction, if any.
This can be a live-through value, or a live def. A dead def returns NULL.
Definition at line 119 of file LiveInterval.h.
References isDeadDef().
VNInfo* llvm::LiveQueryResult::valueOutOrDead () const [inline]
Returns the value alive at the end of the instruction, if any.
This can be a live-through value, a live def or a dead def.
Definition at line 125 of file LiveInterval.h.
Referenced by llvm::LiveIntervals::pruneValue().
The documentation for this class was generated from the following file:
LiveInterval.h