LLVM: llvm::SDDbgValue Class Reference
llvm::SDDbgValue Class Reference
SDDbgValue - Holds the information from a dbg_value node through SDISel.
#include <SDNodeDbgValue.h>
Public Types
enum DbgValueKind { SDNODE = 0, CONST = 1, FRAMEIX = 2 }
Public Member Functions
SDDbgValue (MDNode *Var, MDNode *Expr, SDNode *N, unsigned R, bool indir, uint64_t off, DebugLoc dl, unsigned O)
SDDbgValue (MDNode *Var, MDNode *Expr, const Value *C, uint64_t off, DebugLoc dl, unsigned O)
SDDbgValue (MDNode *Var, MDNode *Expr, unsigned FI, uint64_t off, DebugLoc dl, unsigned O)
DbgValueKind getKind () const
MDNode * getVariable () const
MDNode * getExpression () const
SDNode * getSDNode () const
unsigned getResNo () const
const Value * getConst () const
unsigned getFrameIx () const
bool isIndirect () const
uint64_t getOffset () const
DebugLoc getDebugLoc () const
unsigned getOrder () const
void setIsInvalidated ()
bool isInvalidated () const
Detailed Description
SDDbgValue - Holds the information from a dbg_value node through SDISel.
We do not use SDValue here to avoid including its header.
Definition at line 30 of file SDNodeDbgValue.h.
Member Enumeration Documentation
enum llvm::SDDbgValue::DbgValueKind
Enumerator:
SDNODE
CONST
FRAMEIX
Definition at line 32 of file SDNodeDbgValue.h.
Constructor & Destructor Documentation
llvm::SDDbgValue::SDDbgValue (MDNode * Var, MDNode * Expr, SDNode * N, unsigned R, bool indir, uint64_t off, DebugLoc dl, unsigned O) [inline]
Definition at line 57 of file SDNodeDbgValue.h.
References SDNODE.
llvm::SDDbgValue::SDDbgValue (MDNode * Var, MDNode * Expr, const Value * C, uint64_t off, DebugLoc dl, unsigned O) [inline]
Definition at line 66 of file SDNodeDbgValue.h.
References llvm::C, and CONST.
llvm::SDDbgValue::SDDbgValue (MDNode * Var, MDNode * Expr, unsigned FI, uint64_t off, DebugLoc dl, unsigned O) [inline]
Definition at line 74 of file SDNodeDbgValue.h.
References FRAMEIX.
Member Function Documentation
const Value* llvm::SDDbgValue::getConst () const [inline]
Definition at line 97 of file SDNodeDbgValue.h.
References CONST.
Referenced by llvm::InstrEmitter::EmitDbgValue().
DebugLoc llvm::SDDbgValue::getDebugLoc () const [inline]
Definition at line 109 of file SDNodeDbgValue.h.
Referenced by llvm::InstrEmitter::EmitDbgValue(), and llvm::SelectionDAG::TransferDbgValues().
MDNode* llvm::SDDbgValue::getExpression () const [inline]
Definition at line 88 of file SDNodeDbgValue.h.
Referenced by llvm::InstrEmitter::EmitDbgValue(), and llvm::SelectionDAG::TransferDbgValues().
unsigned llvm::SDDbgValue::getFrameIx () const [inline]
Definition at line 100 of file SDNodeDbgValue.h.
References FRAMEIX.
Referenced by llvm::InstrEmitter::EmitDbgValue().
DbgValueKind llvm::SDDbgValue::getKind () const [inline]
Definition at line 82 of file SDNodeDbgValue.h.
Referenced by llvm::InstrEmitter::EmitDbgValue(), and llvm::SelectionDAG::TransferDbgValues().
uint64_t llvm::SDDbgValue::getOffset () const [inline]
Definition at line 106 of file SDNodeDbgValue.h.
Referenced by llvm::InstrEmitter::EmitDbgValue(), and llvm::SelectionDAG::TransferDbgValues().
unsigned llvm::SDDbgValue::getOrder () const [inline]
Definition at line 113 of file SDNodeDbgValue.h.
Referenced by llvm::SelectionDAG::TransferDbgValues().
unsigned llvm::SDDbgValue::getResNo () const [inline]
Definition at line 94 of file SDNodeDbgValue.h.
References SDNODE.
Referenced by llvm::InstrEmitter::EmitDbgValue().
SDNode* llvm::SDDbgValue::getSDNode () const [inline]
Definition at line 91 of file SDNodeDbgValue.h.
References SDNODE.
Referenced by llvm::InstrEmitter::EmitDbgValue().
MDNode* llvm::SDDbgValue::getVariable () const [inline]
Definition at line 85 of file SDNodeDbgValue.h.
Referenced by llvm::InstrEmitter::EmitDbgValue(), and llvm::SelectionDAG::TransferDbgValues().
bool llvm::SDDbgValue::isIndirect () const [inline]
Definition at line 103 of file SDNodeDbgValue.h.
Referenced by llvm::InstrEmitter::EmitDbgValue(), and llvm::SelectionDAG::TransferDbgValues().
bool llvm::SDDbgValue::isInvalidated () const [inline]
Definition at line 119 of file SDNodeDbgValue.h.
void llvm::SDDbgValue::setIsInvalidated () [inline]
Definition at line 118 of file SDNodeDbgValue.h.
Member Data Documentation
const Value* llvm::SDDbgValue::Const
Definition at line 43 of file SDNodeDbgValue.h.
unsigned llvm::SDDbgValue::FrameIx
Definition at line 44 of file SDNodeDbgValue.h.
SDNode* llvm::SDDbgValue::Node
Definition at line 40 of file SDNodeDbgValue.h.
unsigned llvm::SDDbgValue::ResNo
Definition at line 41 of file SDNodeDbgValue.h.
struct { ... } llvm::SDDbgValue::s
The documentation for this class was generated from the following file:
SDNodeDbgValue.h