LLVM: llvm::MCLOHContainer Class Reference
llvm::MCLOHContainer Class Reference
#include <MCLinkerOptimizationHint.h>
Public Types
typedef SmallVectorImpl
< MCLOHDirective > LOHDirectives
Public Member Functions
MCLOHContainer ()
const LOHDirectives & getDirectives () const
Const accessor to the directives.
void addDirective (MCLOHType Kind, const MCLOHDirective::LOHArgs &Args)
Add the directive of the given kind Kind with the given arguments Args to the container.
uint64_t getEmitSize (const MachObjectWriter &ObjWriter, const MCAsmLayout &Layout) const
Get the size of the directives if emitted.
void emit (MachObjectWriter &ObjWriter, const MCAsmLayout &Layout) const
Emit all Linker Optimization Hint in one big table.
void reset ()
Detailed Description
Definition at line 153 of file MCLinkerOptimizationHint.h.
Member Typedef Documentation
typedef SmallVectorImpl<MCLOHDirective> llvm::MCLOHContainer::LOHDirectives
Definition at line 161 of file MCLinkerOptimizationHint.h.
Constructor & Destructor Documentation
llvm::MCLOHContainer::MCLOHContainer () [inline]
Definition at line 163 of file MCLinkerOptimizationHint.h.
Member Function Documentation
void llvm::MCLOHContainer::addDirective (MCLOHType Kind, const MCLOHDirective::LOHArgs & Args) [inline]
Add the directive of the given kind Kind with the given arguments Args to the container.
Definition at line 172 of file MCLinkerOptimizationHint.h.
References llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
void llvm::MCLOHContainer::emit (MachObjectWriter & ObjWriter, const MCAsmLayout & Layout) const [inline]
Emit all Linker Optimization Hint in one big table.
Each line of the table is emitted by LOHDirective::emit.
Definition at line 188 of file MCLinkerOptimizationHint.h.
const LOHDirectives& llvm::MCLOHContainer::getDirectives () const [inline]
Const accessor to the directives.
Definition at line 166 of file MCLinkerOptimizationHint.h.
uint64_t llvm::MCLOHContainer::getEmitSize (const MachObjectWriter & ObjWriter, const MCAsmLayout & Layout) const [inline]
Get the size of the directives if emitted.
Definition at line 177 of file MCLinkerOptimizationHint.h.
Referenced by llvm::MachObjectWriter::writeObject().
void llvm::MCLOHContainer::reset () [inline]
Definition at line 193 of file MCLinkerOptimizationHint.h.
References llvm::SmallVectorImpl< T >::clear().
Referenced by llvm::MCAssembler::reset().
The documentation for this class was generated from the following file:
MCLinkerOptimizationHint.h