LLVM: llvm::MSP430InstPrinter Class Reference
llvm::MSP430InstPrinter Class Reference
#include <MSP430InstPrinter.h>
Public Member Functions
MSP430InstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printInst (const MCInst *MI, raw_ostream &O, StringRef Annot, const MCSubtargetInfo &STI) override
Print the specified MCInst to the specified raw_ostream.
void printInstruction (const MCInst *MI, raw_ostream &O)
void printOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O, const char *Modifier=nullptr)
void printPCRelImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printSrcMemOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O, const char *Modifier=nullptr)
void printCCOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo)
Detailed Description
Definition at line 22 of file MSP430InstPrinter.h.
Constructor & Destructor Documentation
llvm::MSP430InstPrinter::MSP430InstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) [inline]
Definition at line 24 of file MSP430InstPrinter.h.
Member Function Documentation
static const char* llvm::MSP430InstPrinter::getRegisterName (unsigned RegNo) [static]
Referenced by printOperand(), and printSrcMemOperand().
void MSP430InstPrinter::printCCOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 90 of file MSP430InstPrinter.cpp.
References MSP430CC::COND_E, MSP430CC::COND_GE, MSP430CC::COND_HS, MSP430CC::COND_L, MSP430CC::COND_LO, MSP430CC::COND_NE, llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm_unreachable.
void MSP430InstPrinter::printInst (const MCInst * MI, raw_ostream & OS, StringRef Annot, const MCSubtargetInfo & STI) [override, virtual]
Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Definition at line 29 of file MSP430InstPrinter.cpp.
References llvm::MCInstPrinter::printAnnotation(), and printInstruction().
void llvm::MSP430InstPrinter::printInstruction (const MCInst * MI, raw_ostream & O)
Referenced by printInst().
void MSP430InstPrinter::printOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O, const char * Modifier = nullptr)
Definition at line 46 of file MSP430InstPrinter.cpp.
References llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm::MCInstPrinter::MAI, and llvm::MCExpr::print().
void MSP430InstPrinter::printPCRelImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 35 of file MSP430InstPrinter.cpp.
References llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCInstPrinter::MAI, and llvm::MCExpr::print().
void MSP430InstPrinter::printSrcMemOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O, const char * Modifier = nullptr)
Definition at line 61 of file MSP430InstPrinter.cpp.
References llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCInstPrinter::MAI, and llvm::MCExpr::print().
The documentation for this class was generated from the following files:
MSP430InstPrinter.h
MSP430InstPrinter.cpp