LLVM: llvm::cl::alias Class Reference
llvm::cl::alias Class Reference
#include <CommandLine.h>
Public Member Functions
void setAliasFor (Option &O)
template<class... Mods>
alias (const Mods &...Ms)
Detailed Description
Definition at line 1569 of file CommandLine.h.
Constructor & Destructor Documentation
template<class... Mods> llvm::cl::alias::alias (const Mods &... Ms) [inline, explicit]
Definition at line 1611 of file CommandLine.h.
References llvm::cl::apply().
Member Function Documentation
void llvm::cl::alias::setAliasFor (Option & O) [inline]
Definition at line 1604 of file CommandLine.h.
References llvm::cl::Option::error().
Referenced by llvm::cl::aliasopt::apply().
The documentation for this class was generated from the following files:
CommandLine.h
CommandLine.cpp