LLVM: llvm::DISubprogram Class Reference
llvm::DISubprogram Class Reference
Subprogram description.
#include <DebugInfoMetadata.h>
Public Member Functions
DEFINE_MDNODE_GET (DISubprogram,(DIScopeRef Scope, StringRef Name, StringRef LinkageName, DIFile *File, unsigned Line, DISubroutineType *Type, bool IsLocalToUnit, bool IsDefinition, unsigned ScopeLine, DITypeRef ContainingType, unsigned Virtuality, unsigned VirtualIndex, unsigned Flags, bool IsOptimized, Constant *Function=nullptr, DITemplateParameterArray TemplateParams=nullptr, DISubprogram *Declaration=nullptr, DILocalVariableArray Variables=nullptr),(Scope, Name, LinkageName, File, Line, Type, IsLocalToUnit, IsDefinition, ScopeLine, ContainingType, Virtuality, VirtualIndex, Flags, IsOptimized, Function, TemplateParams, Declaration, Variables)) DEFINE_MDNODE_GET(DISubprogram
bool describes (const Function *F) const
Check if this subprogram decribes the given function.
void replaceFunction (Function *F)
Replace the function.
void replaceFunction (ConstantAsMetadata *MD)
void replaceFunction (std::nullptr_t)
Static Public Member Functions
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
Public Attributes
Metadata * Scope
Metadata MDString * Name
Metadata MDString MDString * LinkageName
Metadata MDString MDString
Metadata * File
Metadata MDString MDString
Metadata unsigned Line
Metadata MDString MDString
Metadata unsigned Metadata * Type
Metadata MDString MDString
Metadata unsigned Metadata
bool IsLocalToUnit
Metadata MDString MDString
Metadata unsigned Metadata
bool bool IsDefinition
Metadata MDString MDString
Metadata unsigned Metadata
bool bool unsigned ScopeLine
Metadata MDString MDString
Metadata unsigned Metadata
bool bool unsigned Metadata * ContainingType
Metadata MDString MDString
Metadata unsigned Metadata
bool bool unsigned Metadata
unsigned Virtuality
Metadata MDString MDString
Metadata unsigned Metadata
bool bool unsigned Metadata
unsigned unsigned VirtualIndex
Metadata MDString MDString
Metadata unsigned Metadata
bool bool unsigned Metadata
unsigned unsigned unsigned Flags
Metadata MDString MDString
Metadata unsigned Metadata
bool bool unsigned Metadata
unsigned unsigned unsigned
bool IsOptimized
Metadata MDString MDString
Metadata unsigned Metadata
bool bool unsigned Metadata
unsigned unsigned unsigned
bool Metadata * Function = nullptr
Metadata MDString MDString
Metadata unsigned Metadata
bool bool unsigned Metadata
unsigned unsigned unsigned
bool Metadata Metadata * TemplateParams = nullptr
Metadata MDString MDString
Metadata unsigned Metadata
bool bool unsigned Metadata
unsigned unsigned unsigned
bool Metadata Metadata
Metadata * Declaration = nullptr
Metadata MDString MDString
Metadata unsigned Metadata
bool bool unsigned Metadata
unsigned unsigned unsigned
bool Metadata Metadata
Metadata Metadata * Variables
Friends
class LLVMContextImpl
class MDNode
Detailed Description
Subprogram description.
TODO: Remove DisplayName. It's always equal to Name. TODO: Split up flags.
Definition at line 1238 of file DebugInfoMetadata.h.
Member Function Documentation
static bool llvm::DISubprogram::classof (const Metadata * MD) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::DILocalScope.
Definition at line 1427 of file DebugInfoMetadata.h.
References llvm::Metadata::DISubprogramKind, and llvm::Metadata::getMetadataID().
llvm::DISubprogram::DEFINE_MDNODE_GET (DISubprogram , (DIScopeRef Scope, StringRef Name, StringRef LinkageName,DIFile *File, unsigned Line, DISubroutineType *Type,bool IsLocalToUnit, bool IsDefinition, unsigned ScopeLine,DITypeRef ContainingType, unsigned Virtuality,unsigned VirtualIndex, unsigned Flags, bool IsOptimized,Constant *Function=nullptr,DITemplateParameterArray TemplateParams=nullptr,DISubprogram *Declaration=nullptr,DILocalVariableArray Variables=nullptr) , (Scope, Name, LinkageName, File, Line, Type, IsLocalToUnit,IsDefinition, ScopeLine, ContainingType, Virtuality,VirtualIndex, Flags, IsOptimized, Function, TemplateParams,Declaration, Variables))
bool DISubprogram::describes (const Function * F) const
Check if this subprogram decribes the given function.
FIXME: Should this be looking through bitcasts?
Definition at line 368 of file DebugInfoMetadata.cpp.
References llvm::StringRef::empty(), llvm::Value::getName(), llvm::DIScope::getName(), and Name.
void DISubprogram::replaceFunction (Function * F)
Replace the function.
If isUniqued() and not isResolved(), this could node will be RAUW'ed and deleted out from under the caller. Use a TrackingMDRef if that's a problem.
Definition at line 378 of file DebugInfoMetadata.cpp.
References llvm::ConstantAsMetadata::get().
void llvm::DISubprogram::replaceFunction (ConstantAsMetadata * MD) [inline]
Definition at line 1418 of file DebugInfoMetadata.h.
References llvm::MDNode::replaceOperandWith().
void llvm::DISubprogram::replaceFunction (std::nullptr_t) [inline]
Definition at line 1419 of file DebugInfoMetadata.h.
References llvm::MDNode::replaceOperandWith().
Friends And Related Function Documentation
friend class LLVMContextImpl [friend]
Reimplemented from llvm::DINode.
Definition at line 1239 of file DebugInfoMetadata.h.
friend class MDNode [friend]
Reimplemented from llvm::DINode.
Definition at line 1240 of file DebugInfoMetadata.h.
Member Data Documentation
Metadata MDString MDString Metadata unsigned Metadata bool bool unsigned Metadata* llvm::DISubprogram::ContainingType
Definition at line 1314 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned Metadata bool bool unsigned Metadata unsigned unsigned unsigned bool Metadata Metadata Metadata* llvm::DISubprogram::Declaration = nullptr
Definition at line 1319 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata* llvm::DISubprogram::File
Definition at line 1314 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned Metadata bool bool unsigned Metadata unsigned unsigned unsigned llvm::DISubprogram::Flags
Definition at line 1314 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned Metadata bool bool unsigned Metadata unsigned unsigned unsigned bool Metadata* llvm::DISubprogram::Function = nullptr
Definition at line 1318 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned Metadata bool bool llvm::DISubprogram::IsDefinition
Definition at line 1314 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned Metadata bool llvm::DISubprogram::IsLocalToUnit
Definition at line 1314 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned Metadata bool bool unsigned Metadata unsigned unsigned unsigned bool llvm::DISubprogram::IsOptimized
Definition at line 1314 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned llvm::DISubprogram::Line
Definition at line 1314 of file DebugInfoMetadata.h.
Metadata MDString MDString* llvm::DISubprogram::LinkageName
Definition at line 1314 of file DebugInfoMetadata.h.
Metadata MDString* llvm::DISubprogram::Name
Definition at line 1314 of file DebugInfoMetadata.h.
Referenced by describes().
Metadata* llvm::DISubprogram::Scope
Definition at line 1314 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned Metadata bool bool unsigned llvm::DISubprogram::ScopeLine
Definition at line 1314 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned Metadata bool bool unsigned Metadata unsigned unsigned unsigned bool Metadata Metadata* llvm::DISubprogram::TemplateParams = nullptr
Definition at line 1318 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned Metadata* llvm::DISubprogram::Type
Definition at line 1314 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned Metadata bool bool unsigned Metadata unsigned unsigned unsigned bool Metadata Metadata Metadata Metadata* llvm::DISubprogram::Variables
Definition at line 1319 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned Metadata bool bool unsigned Metadata unsigned unsigned llvm::DISubprogram::VirtualIndex
Definition at line 1314 of file DebugInfoMetadata.h.
Metadata MDString MDString Metadata unsigned Metadata bool bool unsigned Metadata unsigned llvm::DISubprogram::Virtuality
Definition at line 1314 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
DebugInfoMetadata.h
DebugInfoMetadata.cpp