LLVM: llvm::DIEString Class Reference
llvm::DIEString Class Reference
DIEString - A container for string values.
#include <DIE.h>
Public Member Functions
DIEString (DwarfStringPoolEntryRef S)
StringRef getString () const
getString - Grab the string out of the object.
void EmitValue (const AsmPrinter *AP, dwarf::Form Form) const
EmitValue - Emit string value.
unsigned SizeOf (const AsmPrinter *AP, dwarf::Form Form) const
SizeOf - Determine size of delta value in bytes.
void print (raw_ostream &O) const
Detailed Description
DIEString - A container for string values.
Definition at line 212 of file DIE.h.
Constructor & Destructor Documentation
llvm::DIEString::DIEString (DwarfStringPoolEntryRef S) [inline]
Definition at line 216 of file DIE.h.
Member Function Documentation
void DIEString::EmitValue (const AsmPrinter * AP, dwarf::Form Form) const
EmitValue - Emit string value.
Definition at line 395 of file DIE.cpp.
References llvm::MCAsmInfo::doesDwarfUseRelocationsAcrossSections(), llvm::dwarf::DW_FORM_GNU_str_index, llvm::dwarf::DW_FORM_strp, llvm::DwarfStringPoolEntryRef::getIndex(), llvm::DwarfStringPoolEntryRef::getOffset(), llvm::DwarfStringPoolEntryRef::getSymbol(), and llvm::AsmPrinter::MAI.
StringRef llvm::DIEString::getString () const [inline]
getString - Grab the string out of the object.
Definition at line 219 of file DIE.h.
References llvm::DwarfStringPoolEntryRef::getString().
void DIEString::print (raw_ostream & O) const
Definition at line 437 of file DIE.cpp.
References llvm::DwarfStringPoolEntryRef::getString().
unsigned DIEString::SizeOf (const AsmPrinter * AP, dwarf::Form Form) const
SizeOf - Determine size of delta value in bytes.
Definition at line 419 of file DIE.cpp.
References llvm::MCAsmInfo::doesDwarfUseRelocationsAcrossSections(), llvm::dwarf::DW_FORM_GNU_str_index, llvm::dwarf::DW_FORM_strp, llvm::DwarfStringPoolEntryRef::getIndex(), llvm::DwarfStringPoolEntryRef::getOffset(), llvm::DwarfStringPoolEntryRef::getSymbol(), and llvm::AsmPrinter::MAI.
The documentation for this class was generated from the following files:
DIE.h
DIE.cpp