LLVM: llvm::AddressPool Class Reference
llvm::AddressPool Class Reference
#include <AddressPool.h>
Classes
struct AddressPoolEntry
Public Member Functions
AddressPool ()
unsigned getIndex (const MCSymbol *Sym, bool TLS=false)
Returns the index into the address pool with the given label/symbol.
void emit (AsmPrinter &Asm, MCSection *AddrSection)
bool isEmpty ()
bool hasBeenUsed () const
void resetUsedFlag ()
Detailed Description
Definition at line 22 of file AddressPool.h.
Constructor & Destructor Documentation
llvm::AddressPool::AddressPool () [inline]
Definition at line 37 of file AddressPool.h.
Member Function Documentation
void AddressPool::emit (AsmPrinter & Asm, MCSection * AddrSection)
Definition at line 27 of file AddressPool.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty(), llvm::AsmPrinter::getDataLayout(), llvm::TargetLoweringObjectFile::getDebugThreadLocalSymbol(), llvm::AsmPrinter::getObjFileLowering(), llvm::DataLayout::getPointerSize(), I, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size().
Referenced by llvm::DwarfDebug::endModule().
unsigned AddressPool::getIndex (const MCSymbol * Sym, bool TLS = false)
Returns the index into the address pool with the given label/symbol.
Definition at line 19 of file AddressPool.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size(), and llvm::TLS.
Referenced by llvm::DwarfCompileUnit::addLabelAddress(), llvm::DwarfUnit::addOpAddress(), and llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
bool llvm::AddressPool::hasBeenUsed () const [inline]
Definition at line 47 of file AddressPool.h.
Referenced by llvm::DwarfDebug::addDwarfTypeUnitType().
bool llvm::AddressPool::isEmpty () [inline]
Definition at line 45 of file AddressPool.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty().
void llvm::AddressPool::resetUsedFlag () [inline]
Definition at line 49 of file AddressPool.h.
Referenced by llvm::DwarfDebug::addDwarfTypeUnitType().
The documentation for this class was generated from the following files:
AddressPool.h
AddressPool.cpp