LLVM: llvm::OpInit Class Reference
llvm::OpInit Class Reference
OpInit - Base class for operators.
#include <Record.h>
Public Member Functions
virtual OpInit * clone (std::vector< Init * > &Operands) const =0
virtual unsigned getNumOperands () const =0
virtual Init * getOperand (unsigned i) const =0
virtual Init * Fold (Record *CurRec, MultiClass *CurMultiClass) const =0
Init * resolveListElementReference (Record &R, const RecordVal *RV, unsigned Elt) const override
resolveListElementReference - This method is used to implement VarListElementInit::resolveReferences.
Init * getBit (unsigned Bit) const override
getBit - This method is used to return the initializer for the specified bit.
Static Public Member Functions
static bool classof (const Init *I)
Protected Member Functions
OpInit (InitKind K, RecTy *Type)
Detailed Description
OpInit - Base class for operators.
Definition at line 648 of file Record.h.
Constructor & Destructor Documentation
llvm::OpInit::OpInit (InitKind K, RecTy * Type) [inline, explicit, protected]
Definition at line 653 of file Record.h.
Member Function Documentation
static bool llvm::OpInit::classof (const Init * I) [inline, static]
Reimplemented from llvm::TypedInit.
Reimplemented in llvm::TernOpInit, llvm::BinOpInit, and llvm::UnOpInit.
Definition at line 656 of file Record.h.
References llvm::Init::getKind(), llvm::Init::IK_FirstOpInit, and llvm::Init::IK_LastOpInit.
virtual OpInit* llvm::OpInit::clone (std::vector< Init * > & Operands) const [pure virtual]
Implemented in llvm::TernOpInit, llvm::BinOpInit, and llvm::UnOpInit.
Referenced by EvaluateOperation(), and ForeachHelper().
virtual Init* llvm::OpInit::Fold (Record * CurRec, MultiClass * CurMultiClass) const [pure virtual]
Implemented in llvm::TernOpInit, llvm::BinOpInit, and llvm::UnOpInit.
Referenced by EvaluateOperation(), ForeachHelper(), and resolveListElementReference().
Init * OpInit::getBit (unsigned Bit) const [override, virtual]
getBit - This method is used to return the initializer for the specified bit.
Implements llvm::Init.
Definition at line 600 of file Record.cpp.
References llvm::BitRecTy::get(), llvm::VarBitInit::get(), and llvm::TypedInit::getType().
virtual unsigned llvm::OpInit::getNumOperands () const [pure virtual]
Implemented in llvm::TernOpInit, llvm::BinOpInit, and llvm::UnOpInit.
Referenced by EvaluateOperation(), and ForeachHelper().
virtual Init* llvm::OpInit::getOperand (unsigned i) const [pure virtual]
Implemented in llvm::TernOpInit, llvm::BinOpInit, and llvm::UnOpInit.
Referenced by EvaluateOperation(), and ForeachHelper().
Init * OpInit::resolveListElementReference (Record & R, const RecordVal * RV, unsigned Elt) const [override, virtual]
resolveListElementReference - This method is used to implement VarListElementInit::resolveReferences.
If the list element is resolvable now, we return the resolved value, otherwise we return null.
Implements llvm::TypedInit.
Definition at line 582 of file Record.cpp.
References llvm::dyn_cast(), Fold(), llvm::VarListElementInit::get(), llvm::TypedInit::resolveListElementReference(), and llvm::Init::resolveReferences().
The documentation for this class was generated from the following files:
Record.h
Record.cpp