LLVM: llvm::DIType Class Reference
llvm::DIType Class Reference
Base class for types.
#include <DebugInfoMetadata.h>
Public Member Functions
TempDIType clone () const
Create a (temporary) clone of this.
unsigned getLine () const
uint64_t getSizeInBits () const
uint64_t getAlignInBits () const
uint64_t getOffsetInBits () const
unsigned getFlags () const
DIScopeRef getScope () const
StringRef getName () const
Metadata * getRawScope () const
MDString * getRawName () const
void setFlags (unsigned NewFlags)
bool isPrivate () const
bool isProtected () const
bool isPublic () const
bool isForwardDecl () const
bool isAppleBlockExtension () const
bool isBlockByrefStruct () const
bool isVirtual () const
bool isArtificial () const
bool isObjectPointer () const
bool isObjcClassComplete () const
bool isVector () const
bool isStaticMember () const
bool isLValueReference () const
bool isRValueReference () const
DITypeRef getRef () const
Static Public Member Functions
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
DIType (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, unsigned Line, uint64_t SizeInBits, uint64_t AlignInBits, uint64_t OffsetInBits, unsigned Flags, ArrayRef< Metadata * > Ops)
~DIType ()
Detailed Description
Base class for types.
TODO: Remove the hardcoded name and context, since many types don't use them. TODO: Split up flags.
Definition at line 514 of file DebugInfoMetadata.h.
Constructor & Destructor Documentation
llvm::DIType::DIType (LLVMContext & C, unsigned ID, StorageType Storage, unsigned Tag, unsigned Line, uint64_t SizeInBits, uint64_t AlignInBits, uint64_t OffsetInBits, unsigned Flags, ArrayRef< Metadata * > Ops) [inline, protected]
Definition at line 522 of file DebugInfoMetadata.h.
llvm::DIType::~DIType () [protected]
Member Function Documentation
static bool llvm::DIType::classof (const Metadata * MD) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::DIScope.
Reimplemented in llvm::DISubroutineType, llvm::DICompositeTypeBase, llvm::DIDerivedTypeBase, and llvm::DIBasicType.
Definition at line 578 of file DebugInfoMetadata.h.
References llvm::Metadata::DIBasicTypeKind, llvm::Metadata::DICompositeTypeKind, llvm::Metadata::DIDerivedTypeKind, llvm::Metadata::DISubroutineTypeKind, and llvm::Metadata::getMetadataID().
TempDIType llvm::DIType::clone () const [inline]
Create a (temporary) clone of this.
Reimplemented from llvm::MDNode.
Reimplemented in llvm::DISubroutineType.
Definition at line 531 of file DebugInfoMetadata.h.
References llvm::MDNode::clone().
Referenced by createTypeWithFlags().
uint64_t llvm::DIType::getAlignInBits () const [inline]
Definition at line 537 of file DebugInfoMetadata.h.
Referenced by llvm::MDNodeKeyImpl< DIBasicType >::isKeyOf(), llvm::MDNodeKeyImpl< DIDerivedType >::isKeyOf(), llvm::MDNodeKeyImpl< DICompositeType >::isKeyOf(), WriteDIBasicType(), WriteDICompositeType(), and WriteDIDerivedType().
unsigned llvm::DIType::getFlags () const [inline]
Definition at line 539 of file DebugInfoMetadata.h.
Referenced by isAppleBlockExtension(), isArtificial(), isBlockByrefStruct(), isForwardDecl(), llvm::MDNodeKeyImpl< DIDerivedType >::isKeyOf(), llvm::MDNodeKeyImpl< DICompositeType >::isKeyOf(), llvm::MDNodeKeyImpl< DISubroutineType >::isKeyOf(), isLValueReference(), isObjcClassComplete(), isObjectPointer(), isPrivate(), isProtected(), isPublic(), isRValueReference(), isStaticMember(), isVector(), isVirtual(), WriteDICompositeType(), WriteDIDerivedType(), and WriteDISubroutineType().
unsigned llvm::DIType::getLine () const [inline]
Definition at line 535 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfUnit::addSourceLine(), llvm::MDNodeKeyImpl< DIDerivedType >::isKeyOf(), llvm::MDNodeKeyImpl< DICompositeType >::isKeyOf(), WriteDICompositeType(), and WriteDIDerivedType().
StringRef llvm::DIType::getName () const [inline]
Reimplemented from llvm::DIScope.
Definition at line 542 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
Referenced by llvm::DwarfCompileUnit::addGlobalType(), llvm::DwarfUnit::constructTypeDIE(), llvm::DwarfUnit::getOrCreateStaticMemberDIE(), llvm::MDNodeKeyImpl< DIBasicType >::isKeyOf(), llvm::MDNodeKeyImpl< DIDerivedType >::isKeyOf(), llvm::MDNodeKeyImpl< DICompositeType >::isKeyOf(), and isUnsignedDIType().
uint64_t llvm::DIType::getOffsetInBits () const [inline]
Definition at line 538 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfUnit::addBlockByrefAddress(), llvm::MDNodeKeyImpl< DIDerivedType >::isKeyOf(), llvm::MDNodeKeyImpl< DICompositeType >::isKeyOf(), WriteDICompositeType(), and WriteDIDerivedType().
MDString* llvm::DIType::getRawName () const [inline]
Definition at line 546 of file DebugInfoMetadata.h.
Referenced by WriteDIBasicType(), WriteDICompositeType(), and WriteDIDerivedType().
Metadata* llvm::DIType::getRawScope () const [inline]
Definition at line 545 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getScope(), llvm::MDNodeKeyImpl< DIDerivedType >::isKeyOf(), and llvm::MDNodeKeyImpl< DICompositeType >::isKeyOf().
DITypeRef llvm::DIType::getRef () const [inline]
Reimplemented from llvm::DIScope.
Definition at line 576 of file DebugInfoMetadata.h.
References llvm::MDNode::get().
DIScopeRef llvm::DIType::getScope () const [inline]
Reimplemented from llvm::DIScope.
Definition at line 541 of file DebugInfoMetadata.h.
References getRawScope().
Referenced by llvm::DwarfUnit::createTypeDIE(), llvm::DwarfUnit::getOrCreateStaticMemberDIE(), WriteDICompositeType(), and WriteDIDerivedType().
uint64_t llvm::DIType::getSizeInBits () const [inline]
Definition at line 536 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfUnit::constructTypeDIE(), getBaseTypeSize(), llvm::MDNodeKeyImpl< DIBasicType >::isKeyOf(), llvm::MDNodeKeyImpl< DIDerivedType >::isKeyOf(), llvm::MDNodeKeyImpl< DICompositeType >::isKeyOf(), WriteDIBasicType(), WriteDICompositeType(), and WriteDIDerivedType().
bool llvm::DIType::isAppleBlockExtension () const [inline]
Definition at line 563 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::DwarfUnit::constructTypeDIE().
bool llvm::DIType::isArtificial () const [inline]
Definition at line 566 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::DwarfUnit::constructSubprogramArguments(), llvm::DIBuilder::createArtificialType(), and llvm::DbgVariable::isArtificial().
bool llvm::DIType::isBlockByrefStruct () const [inline]
Definition at line 564 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::DbgVariable::getType().
bool llvm::DIType::isForwardDecl () const [inline]
Definition at line 562 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::DwarfUnit::constructTypeDIE().
bool llvm::DIType::isLValueReference () const [inline]
Definition at line 573 of file DebugInfoMetadata.h.
References getFlags().
bool llvm::DIType::isObjcClassComplete () const [inline]
Definition at line 568 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::DwarfUnit::constructTypeDIE().
bool llvm::DIType::isObjectPointer () const [inline]
Definition at line 567 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::DIBuilder::createObjectPointerType(), and llvm::DbgVariable::isObjectPointer().
bool llvm::DIType::isPrivate () const [inline]
Definition at line 553 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::DwarfUnit::getOrCreateStaticMemberDIE().
bool llvm::DIType::isProtected () const [inline]
Definition at line 556 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::DwarfUnit::getOrCreateStaticMemberDIE().
bool llvm::DIType::isPublic () const [inline]
Definition at line 559 of file DebugInfoMetadata.h.
References getFlags().
Referenced by llvm::DwarfUnit::getOrCreateStaticMemberDIE().
bool llvm::DIType::isRValueReference () const [inline]
Definition at line 574 of file DebugInfoMetadata.h.
References getFlags().
bool llvm::DIType::isStaticMember () const [inline]
Definition at line 572 of file DebugInfoMetadata.h.
References getFlags().
bool llvm::DIType::isVector () const [inline]
Definition at line 571 of file DebugInfoMetadata.h.
References getFlags().
bool llvm::DIType::isVirtual () const [inline]
Definition at line 565 of file DebugInfoMetadata.h.
References getFlags().
void llvm::DIType::setFlags (unsigned NewFlags) [inline]
Definition at line 548 of file DebugInfoMetadata.h.
References llvm::MDNode::isUniqued().
The documentation for this class was generated from the following file:
DebugInfoMetadata.h