LLVM: llvm::SystemZTTIImpl Class Reference
llvm::SystemZTTIImpl Class Reference
#include <SystemZTargetTransformInfo.h>
Public Member Functions
SystemZTTIImpl (const SystemZTargetMachine *TM, Function &F)
SystemZTTIImpl (const SystemZTTIImpl &Arg)
SystemZTTIImpl (SystemZTTIImpl &&Arg)
SystemZTTIImpl & operator= (const SystemZTTIImpl &RHS)
SystemZTTIImpl & operator= (SystemZTTIImpl &&RHS)
Scalar TTI Implementations
unsigned getIntImmCost (const APInt &Imm, Type *Ty)
unsigned getIntImmCost (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty)
unsigned getIntImmCost (Intrinsic::ID IID, unsigned Idx, const APInt &Imm, Type *Ty)
TTI::PopcntSupportKind getPopcntSupport (unsigned TyWidth)
Vector TTI Implementations
unsigned getNumberOfRegisters (bool Vector)
unsigned getRegisterBitWidth (bool Vector)
Detailed Description
Definition at line 19 of file SystemZTargetTransformInfo.h.
Constructor & Destructor Documentation
llvm::SystemZTTIImpl::SystemZTTIImpl (const SystemZTargetMachine * TM, Function & F) [inline, explicit]
Definition at line 31 of file SystemZTargetTransformInfo.h.
llvm::SystemZTTIImpl::SystemZTTIImpl (const SystemZTTIImpl & Arg) [inline]
Definition at line 35 of file SystemZTargetTransformInfo.h.
llvm::SystemZTTIImpl::SystemZTTIImpl (SystemZTTIImpl && Arg) [inline]
Definition at line 37 of file SystemZTargetTransformInfo.h.
Member Function Documentation
unsigned SystemZTTIImpl::getIntImmCost (const APInt & Imm, Type * Ty)
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 34 of file SystemZTargetTransformInfo.cpp.
References llvm::APInt::getBitWidth(), llvm::Type::getPrimitiveSizeInBits(), llvm::APInt::getSExtValue(), llvm::APInt::getZExtValue(), llvm::isInt< 32 >(), llvm::Type::isIntegerTy(), llvm::isUInt< 32 >(), llvm::TargetTransformInfo::TCC_Basic, and llvm::TargetTransformInfo::TCC_Free.
Referenced by getIntImmCost().
unsigned SystemZTTIImpl::getIntImmCost (unsigned Opcode, unsigned Idx, const APInt & Imm, Type * Ty)
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 66 of file SystemZTargetTransformInfo.cpp.
References llvm::APIntOps::And(), llvm::Call, llvm::APInt::getBitWidth(), llvm::SystemZSubtarget::getInstrInfo(), getIntImmCost(), llvm::Type::getPrimitiveSizeInBits(), llvm::APInt::getSExtValue(), llvm::APInt::getZExtValue(), llvm::IntToPtr, llvm::isInt< 16 >(), llvm::isInt< 32 >(), llvm::Type::isIntegerTy(), llvm::SystemZInstrInfo::isRxSBGMask(), llvm::isUInt< 32 >(), llvm::SPII::Load, llvm::LShr, llvm::APIntOps::Or(), llvm::TargetOpcode::PHI, llvm::MipsISD::Ret, llvm::MCID::Select, llvm::SExt, llvm::SPII::Store, llvm::TargetTransformInfo::TCC_Basic, llvm::TargetTransformInfo::TCC_Free, TII, llvm::Trunc, and llvm::APIntOps::Xor().
unsigned SystemZTTIImpl::getIntImmCost (Intrinsic::ID IID, unsigned Idx, const APInt & Imm, Type * Ty)
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 184 of file SystemZTargetTransformInfo.cpp.
References llvm::APInt::getBitWidth(), getIntImmCost(), llvm::Type::getPrimitiveSizeInBits(), llvm::APInt::getSExtValue(), llvm::APInt::getZExtValue(), llvm::isInt< 32 >(), llvm::Type::isIntegerTy(), llvm::isUInt< 32 >(), and llvm::TargetTransformInfo::TCC_Free.
unsigned SystemZTTIImpl::getNumberOfRegisters (bool Vector)
Reimplemented from llvm::BasicTTIImplBase< SystemZTTIImpl >.
Definition at line 241 of file SystemZTargetTransformInfo.cpp.
References llvm::SystemZSubtarget::hasVector().
TargetTransformInfo::PopcntSupportKind SystemZTTIImpl::getPopcntSupport (unsigned TyWidth)
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 234 of file SystemZTargetTransformInfo.cpp.
References llvm::SystemZSubtarget::hasPopulationCount(), llvm::isPowerOf2_32(), llvm::TargetTransformInfo::PSK_FastHardware, and llvm::TargetTransformInfo::PSK_Software.
unsigned SystemZTTIImpl::getRegisterBitWidth (bool Vector)
Reimplemented from llvm::BasicTTIImplBase< SystemZTTIImpl >.
Definition at line 251 of file SystemZTargetTransformInfo.cpp.
References llvm::SystemZSubtarget::hasVector().
SystemZTTIImpl& llvm::SystemZTTIImpl::operator= (const SystemZTTIImpl & RHS) [inline]
Definition at line 40 of file SystemZTargetTransformInfo.h.
References llvm::BasicTTIImplBase< SystemZTTIImpl >::operator=().
SystemZTTIImpl& llvm::SystemZTTIImpl::operator= (SystemZTTIImpl && RHS) [inline]
Definition at line 46 of file SystemZTargetTransformInfo.h.
References llvm::BasicTTIImplBase< SystemZTTIImpl >::operator=().
The documentation for this class was generated from the following files:
SystemZTargetTransformInfo.h
SystemZTargetTransformInfo.cpp