LLVM: llvm::MaskedGatherScatterSDNode Class Reference
llvm::MaskedGatherScatterSDNode Class Reference
This is a base class used to represent MGATHER and MSCATTER nodes.
#include <SelectionDAGNodes.h>
Public Member Functions
MaskedGatherScatterSDNode (ISD::NodeType NodeTy, unsigned Order, DebugLoc dl, ArrayRef< SDValue > Operands, SDVTList VTs, EVT MemVT, MachineMemOperand *MMO)
const SDValue & getBasePtr () const
const SDValue & getIndex () const
const SDValue & getMask () const
const SDValue & getValue () const
Static Public Member Functions
static bool classof (const SDNode *N)
Friends
class SelectionDAG
Detailed Description
This is a base class used to represent MGATHER and MSCATTER nodes.
Definition at line 2056 of file SelectionDAGNodes.h.
Constructor & Destructor Documentation
llvm::MaskedGatherScatterSDNode::MaskedGatherScatterSDNode (ISD::NodeType NodeTy, unsigned Order, DebugLoc dl, ArrayRef< SDValue > Operands, SDVTList VTs, EVT MemVT, MachineMemOperand * MMO) [inline]
Definition at line 2061 of file SelectionDAGNodes.h.
References llvm::ArrayRef< T >::data(), llvm::SDNode::InitOperands(), and llvm::ArrayRef< T >::size().
Member Function Documentation
static bool llvm::MaskedGatherScatterSDNode::classof (const SDNode * N) [inline, static]
Reimplemented from llvm::MemSDNode.
Reimplemented in llvm::MaskedScatterSDNode, and llvm::MaskedGatherSDNode.
Definition at line 2078 of file SelectionDAGNodes.h.
References llvm::SDNode::getOpcode(), llvm::ISD::MGATHER, and llvm::ISD::MSCATTER.
const SDValue& llvm::MaskedGatherScatterSDNode::getBasePtr () const [inline]
Reimplemented from llvm::MemSDNode.
Definition at line 2073 of file SelectionDAGNodes.h.
References llvm::SDNode::getOperand().
const SDValue& llvm::MaskedGatherScatterSDNode::getIndex () const [inline]
Definition at line 2074 of file SelectionDAGNodes.h.
References llvm::SDNode::getOperand().
const SDValue& llvm::MaskedGatherScatterSDNode::getMask () const [inline]
Definition at line 2075 of file SelectionDAGNodes.h.
References llvm::SDNode::getOperand().
Referenced by llvm::MaskedGatherSDNode::MaskedGatherSDNode(), and llvm::MaskedScatterSDNode::MaskedScatterSDNode().
const SDValue& llvm::MaskedGatherScatterSDNode::getValue () const [inline]
Definition at line 2076 of file SelectionDAGNodes.h.
References llvm::SDNode::getOperand().
Referenced by llvm::MaskedGatherSDNode::MaskedGatherSDNode(), and llvm::MaskedScatterSDNode::MaskedScatterSDNode().
Friends And Related Function Documentation
friend class SelectionDAG [friend]
Reimplemented from llvm::SDNode.
Reimplemented in llvm::MaskedScatterSDNode, and llvm::MaskedGatherSDNode.
Definition at line 2060 of file SelectionDAGNodes.h.
The documentation for this class was generated from the following file:
SelectionDAGNodes.h