LLVM: llvm::DIETypeSignature Class Reference
llvm::DIETypeSignature Class Reference
A signature reference to a type unit.
#include <DIE.h>
Public Member Functions
DIETypeSignature (const DwarfTypeUnit &Unit)
void EmitValue (const AsmPrinter *AP, dwarf::Form Form) const
unsigned SizeOf (const AsmPrinter *AP, dwarf::Form Form) const
void print (raw_ostream &O) const
Detailed Description
A signature reference to a type unit.
Definition at line 260 of file DIE.h.
Constructor & Destructor Documentation
llvm::DIETypeSignature::DIETypeSignature (const DwarfTypeUnit & Unit) [inline, explicit]
Definition at line 266 of file DIE.h.
Member Function Documentation
void DIETypeSignature::EmitValue (const AsmPrinter * AP, dwarf::Form Form) const
Definition at line 490 of file DIE.cpp.
References llvm::dwarf::DW_FORM_ref_sig8, llvm::DwarfTypeUnit::getTypeSignature(), and llvm::AsmPrinter::OutStreamer.
void DIETypeSignature::print (raw_ostream & O) const
Definition at line 497 of file DIE.cpp.
References llvm::format(), and llvm::DwarfTypeUnit::getTypeSignature().
unsigned llvm::DIETypeSignature::SizeOf (const AsmPrinter * AP, dwarf::Form Form) const [inline]
Definition at line 269 of file DIE.h.
References llvm::dwarf::DW_FORM_ref_sig8.
The documentation for this class was generated from the following files:
DIE.h
DIE.cpp