LLVM: llvm::AArch64TTIImpl Class Reference
llvm::AArch64TTIImpl Class Reference
#include <AArch64TargetTransformInfo.h>
Public Member Functions
AArch64TTIImpl (const AArch64TargetMachine *TM, Function &F)
AArch64TTIImpl (const AArch64TTIImpl &Arg)
AArch64TTIImpl (AArch64TTIImpl &&Arg)
AArch64TTIImpl & operator= (const AArch64TTIImpl &RHS)
AArch64TTIImpl & operator= (AArch64TTIImpl &&RHS)
Scalar TTI Implementations
unsigned getIntImmCost (int64_t Val)
Calculate the cost of materializing a 64-bit value.
unsigned getIntImmCost (const APInt &Imm, Type *Ty)
Calculate the cost of materializing the given constant.
unsigned getIntImmCost (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty)
unsigned getIntImmCost (Intrinsic::ID IID, unsigned Idx, const APInt &Imm, Type *Ty)
TTI::PopcntSupportKind getPopcntSupport (unsigned TyWidth)
Vector TTI Implementations
unsigned getNumberOfRegisters (bool Vector)
unsigned getRegisterBitWidth (bool Vector)
unsigned getMaxInterleaveFactor (unsigned VF)
unsigned getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src)
unsigned getVectorInstrCost (unsigned Opcode, Type *Val, unsigned Index)
unsigned getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::OperandValueKind Opd1Info=TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info=TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo=TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo=TTI::OP_None)
unsigned getAddressComputationCost (Type *Ty, bool IsComplex)
unsigned getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy)
unsigned getMemoryOpCost (unsigned Opcode, Type *Src, unsigned Alignment, unsigned AddressSpace)
unsigned getCostOfKeepingLiveOverCall (ArrayRef< Type * > Tys)
void getUnrollingPreferences (Loop *L, TTI::UnrollingPreferences &UP)
Value * getOrCreateResultFromMemIntrinsic (IntrinsicInst *Inst, Type *ExpectedType)
bool getTgtMemIntrinsic (IntrinsicInst *Inst, MemIntrinsicInfo &Info)
Detailed Description
Definition at line 29 of file AArch64TargetTransformInfo.h.
Constructor & Destructor Documentation
llvm::AArch64TTIImpl::AArch64TTIImpl (const AArch64TargetMachine * TM, Function & F) [inline, explicit]
Definition at line 52 of file AArch64TargetTransformInfo.h.
llvm::AArch64TTIImpl::AArch64TTIImpl (const AArch64TTIImpl & Arg) [inline]
Definition at line 57 of file AArch64TargetTransformInfo.h.
llvm::AArch64TTIImpl::AArch64TTIImpl (AArch64TTIImpl && Arg) [inline]
Definition at line 60 of file AArch64TargetTransformInfo.h.
Member Function Documentation
unsigned AArch64TTIImpl::getAddressComputationCost (Type * Ty, bool IsComplex)
Reimplemented from llvm::BasicTTIImplBase< AArch64TTIImpl >.
Definition at line 334 of file AArch64TargetTransformInfo.cpp.
References llvm::Type::isVectorTy().
unsigned AArch64TTIImpl::getArithmeticInstrCost (unsigned Opcode, Type * Ty, TTI::OperandValueKind Opd1Info = TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info = TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo = TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo = TTI::OP_None)
Reimplemented from llvm::BasicTTIImplBase< AArch64TTIImpl >.
Definition at line 287 of file AArch64TargetTransformInfo.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::BasicTTIImplBase< AArch64TTIImpl >::getArithmeticInstrCost(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::AArch64CC::LT, llvm::ISD::MUL, llvm::TargetTransformInfo::OK_UniformConstantValue, llvm::TargetTransformInfo::OP_None, llvm::TargetTransformInfo::OP_PowerOf2, llvm::ISD::OR, llvm::ISD::SDIV, llvm::MCID::Select, and llvm::ISD::XOR.
unsigned AArch64TTIImpl::getCastInstrCost (unsigned Opcode, Type * Dst, Type * Src)
Reimplemented from llvm::BasicTTIImplBase< AArch64TTIImpl >.
Definition at line 179 of file AArch64TargetTransformInfo.cpp.
References llvm::array_lengthof(), llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::BasicTTIImplBase< AArch64TTIImpl >::getCastInstrCost(), llvm::EVT::getSimpleVT(), llvm::TargetLoweringBase::getValueType(), llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::EVT::isSimple(), llvm::ISD::SINT_TO_FP, llvm::ISD::UINT_TO_FP, llvm::MVT::v2f32, llvm::MVT::v2f64, llvm::MVT::v2i16, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v2i8, llvm::MVT::v4f32, llvm::MVT::v4i16, llvm::MVT::v4i32, and llvm::MVT::v4i8.
unsigned AArch64TTIImpl::getCmpSelInstrCost (unsigned Opcode, Type * ValTy, Type * CondTy)
Reimplemented from llvm::BasicTTIImplBase< AArch64TTIImpl >.
Definition at line 349 of file AArch64TargetTransformInfo.cpp.
References llvm::ConvertCostTableLookup(), llvm::TypeConversionCostTblEntry< TypeTy >::Cost, llvm::BasicTTIImplBase< AArch64TTIImpl >::getCmpSelInstrCost(), llvm::EVT::getSimpleVT(), llvm::TargetLoweringBase::getValueType(), llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::EVT::isSimple(), llvm::Type::isVectorTy(), llvm::ISD::SELECT, llvm::MVT::v16i1, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i64, llvm::MVT::v4i1, llvm::MVT::v4i64, llvm::MVT::v8i1, llvm::MVT::v8i32, and llvm::MVT::v8i64.
unsigned AArch64TTIImpl::getCostOfKeepingLiveOverCall (ArrayRef< Type * > Tys)
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 410 of file AArch64TargetTransformInfo.cpp.
References getMemoryOpCost(), I, llvm::SPII::Load, and llvm::SPII::Store.
unsigned AArch64TTIImpl::getIntImmCost (int64_t Val)
Calculate the cost of materializing a 64-bit value.
This helper method might only calculate a fraction of a larger immediate. Therefore it is valid to return a cost of ZERO.
Definition at line 26 of file AArch64TargetTransformInfo.cpp.
References llvm::countLeadingZeros(), and llvm::AArch64_AM::isLogicalImmediate().
Referenced by getIntImmCost().
unsigned AArch64TTIImpl::getIntImmCost (const APInt & Imm, Type * Ty)
Calculate the cost of materializing the given constant.
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 40 of file AArch64TargetTransformInfo.cpp.
References llvm::APInt::ashr(), getIntImmCost(), llvm::Type::getPrimitiveSizeInBits(), llvm::APInt::getSExtValue(), llvm::Type::isIntegerTy(), llvm::APInt::sext(), and llvm::APInt::sextOrTrunc().
unsigned AArch64TTIImpl::getIntImmCost (unsigned Opcode, unsigned Idx, const APInt & Imm, Type * Ty)
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 64 of file AArch64TargetTransformInfo.cpp.
References llvm::APIntOps::And(), llvm::Call, getIntImmCost(), llvm::Type::getPrimitiveSizeInBits(), llvm::IntToPtr, llvm::Type::isIntegerTy(), llvm::SPII::Load, llvm::LShr, llvm::APIntOps::Or(), llvm::TargetOpcode::PHI, llvm::MipsISD::Ret, llvm::MCID::Select, llvm::SExt, llvm::SPII::Store, llvm::TargetTransformInfo::TCC_Basic, llvm::TargetTransformInfo::TCC_Free, llvm::Trunc, and llvm::APIntOps::Xor().
unsigned AArch64TTIImpl::getIntImmCost (Intrinsic::ID IID, unsigned Idx, const APInt & Imm, Type * Ty)
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 130 of file AArch64TargetTransformInfo.cpp.
References llvm::APInt::getBitWidth(), getIntImmCost(), llvm::Type::getPrimitiveSizeInBits(), llvm::APInt::getSExtValue(), llvm::Type::isIntegerTy(), llvm::TargetTransformInfo::TCC_Basic, and llvm::TargetTransformInfo::TCC_Free.
unsigned AArch64TTIImpl::getMaxInterleaveFactor (unsigned VF)
Reimplemented from llvm::BasicTTIImplBase< AArch64TTIImpl >.
Definition at line 422 of file AArch64TargetTransformInfo.cpp.
References llvm::AArch64Subtarget::isCortexA57().
unsigned AArch64TTIImpl::getMemoryOpCost (unsigned Opcode, Type * Src, unsigned Alignment, unsigned AddressSpace)
Reimplemented from llvm::BasicTTIImplBase< AArch64TTIImpl >.
Definition at line 380 of file AArch64TargetTransformInfo.cpp.
References llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::Type::getVectorElementType(), llvm::Type::getVectorNumElements(), llvm::Type::isIntegerTy(), llvm::Type::isVectorTy(), llvm::AArch64CC::LT, and llvm::SPII::Store.
Referenced by getCostOfKeepingLiveOverCall().
unsigned llvm::AArch64TTIImpl::getNumberOfRegisters (bool Vector) [inline]
Reimplemented from llvm::BasicTTIImplBase< AArch64TTIImpl >.
Definition at line 95 of file AArch64TargetTransformInfo.h.
References llvm::AArch64Subtarget::hasNEON().
Value * AArch64TTIImpl::getOrCreateResultFromMemIntrinsic (IntrinsicInst * Inst, Type * ExpectedType)
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 443 of file AArch64TargetTransformInfo.cpp.
References llvm::IRBuilder< preserveNames, T, Inserter >::CreateInsertValue(), llvm::dyn_cast(), llvm::UndefValue::get(), llvm::CallInst::getArgOperand(), llvm::StructType::getElementType(), llvm::IntrinsicInst::getIntrinsicID(), llvm::CallInst::getNumArgOperands(), llvm::StructType::getNumElements(), and llvm::Value::getType().
TargetTransformInfo::PopcntSupportKind AArch64TTIImpl::getPopcntSupport (unsigned TyWidth)
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 171 of file AArch64TargetTransformInfo.cpp.
References llvm::isPowerOf2_32(), llvm::TargetTransformInfo::PSK_FastHardware, and llvm::TargetTransformInfo::PSK_Software.
unsigned llvm::AArch64TTIImpl::getRegisterBitWidth (bool Vector) [inline]
Reimplemented from llvm::BasicTTIImplBase< AArch64TTIImpl >.
Definition at line 104 of file AArch64TargetTransformInfo.h.
References llvm::AArch64Subtarget::hasNEON().
bool AArch64TTIImpl::getTgtMemIntrinsic (IntrinsicInst * Inst, MemIntrinsicInfo & Info)
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 479 of file AArch64TargetTransformInfo.cpp.
References llvm::CallInst::getArgOperand(), llvm::IntrinsicInst::getIntrinsicID(), llvm::CallInst::getNumArgOperands(), llvm::MemIntrinsicInfo::MatchingId, llvm::MemIntrinsicInfo::NumMemRefs, llvm::MemIntrinsicInfo::PtrVal, llvm::MemIntrinsicInfo::ReadMem, llvm::MemIntrinsicInfo::Vol, and llvm::MemIntrinsicInfo::WriteMem.
void AArch64TTIImpl::getUnrollingPreferences (Loop * L, TTI::UnrollingPreferences & UP)
Reimplemented from llvm::BasicTTIImplBase< AArch64TTIImpl >.
Definition at line 428 of file AArch64TargetTransformInfo.cpp.
References llvm::LoopBase< BlockT, LoopT >::getLoopDepth(), llvm::BasicTTIImplBase< AArch64TTIImpl >::getUnrollingPreferences(), llvm::TargetTransformInfo::UnrollingPreferences::PartialOptSizeThreshold, and llvm::TargetTransformInfo::UnrollingPreferences::PartialThreshold.
unsigned AArch64TTIImpl::getVectorInstrCost (unsigned Opcode, Type * Val, unsigned Index)
Reimplemented from llvm::BasicTTIImplBase< AArch64TTIImpl >.
Definition at line 262 of file AArch64TargetTransformInfo.cpp.
References llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::Type::isVectorTy(), and llvm::AArch64CC::LT.
AArch64TTIImpl& llvm::AArch64TTIImpl::operator= (const AArch64TTIImpl & RHS) [inline]
Definition at line 63 of file AArch64TargetTransformInfo.h.
References llvm::BasicTTIImplBase< AArch64TTIImpl >::operator=().
AArch64TTIImpl& llvm::AArch64TTIImpl::operator= (AArch64TTIImpl && RHS) [inline]
Definition at line 70 of file AArch64TargetTransformInfo.h.
References llvm::BasicTTIImplBase< AArch64TTIImpl >::operator=().
The documentation for this class was generated from the following files:
AArch64TargetTransformInfo.h
AArch64TargetTransformInfo.cpp