LLVM: llvm::ConstantUniqueMap< ConstantClass > Class Template Reference
llvm::ConstantUniqueMap< ConstantClass > Class Template Reference
#include <ConstantsContext.h>
Classes
struct MapInfo
Public Types
typedef ConstantInfo
< ConstantClass >::ValType ValType
typedef ConstantInfo
< ConstantClass >::TypeClass TypeClass
typedef std::pair< TypeClass
*, ValType > LookupKey
typedef DenseMap
< ConstantClass *, char,
MapInfo > MapTy
Public Member Functions
MapTy::iterator map_begin ()
MapTy::iterator map_end ()
void freeConstants ()
ConstantClass * getOrCreate (TypeClass *Ty, ValType V)
Return the specified constant from the map, creating it if necessary.
MapTy::iterator find (LookupKey Lookup)
Find the constant by lookup key.
void insert (ConstantClass *CP)
Insert the constant into its proper slot.
void remove (ConstantClass *CP)
Remove this constant from the map.
ConstantClass * replaceOperandsInPlace (ArrayRef< Constant * > Operands, ConstantClass *CP, Value *From, Constant *To, unsigned NumUpdated=0, unsigned OperandNo=~0u)
void dump () const
Detailed Description
template<class ConstantClass>
class llvm::ConstantUniqueMap< ConstantClass >
Definition at line 516 of file ConstantsContext.h.
Member Typedef Documentation
template<class ConstantClass> typedef std::pair<TypeClass *, ValType> llvm::ConstantUniqueMap< ConstantClass >::LookupKey
Definition at line 520 of file ConstantsContext.h.
template<class ConstantClass> typedef DenseMap<ConstantClass *, char, MapInfo> llvm::ConstantUniqueMap< ConstantClass >::MapTy
Definition at line 551 of file ConstantsContext.h.
template<class ConstantClass> typedef ConstantInfo<ConstantClass>::TypeClass llvm::ConstantUniqueMap< ConstantClass >::TypeClass
Definition at line 519 of file ConstantsContext.h.
template<class ConstantClass> typedef ConstantInfo<ConstantClass>::ValType llvm::ConstantUniqueMap< ConstantClass >::ValType
Definition at line 518 of file ConstantsContext.h.
Member Function Documentation
template<class ConstantClass> void llvm::ConstantUniqueMap< ConstantClass >::dump () const [inline]
Definition at line 633 of file ConstantsContext.h.
template<class ConstantClass> MapTy::iterator llvm::ConstantUniqueMap< ConstantClass >::find (LookupKey Lookup) [inline]
Find the constant by lookup key.
Definition at line 593 of file ConstantsContext.h.
Referenced by llvm::ConstantUniqueMap< ConstantStruct >::getOrCreate(), and llvm::ConstantUniqueMap< ConstantStruct >::replaceOperandsInPlace().
template<class ConstantClass> void llvm::ConstantUniqueMap< ConstantClass >::freeConstants () [inline]
Definition at line 560 of file ConstantsContext.h.
Referenced by llvm::LLVMContextImpl::~LLVMContextImpl().
template<class ConstantClass> ConstantClass* llvm::ConstantUniqueMap< ConstantClass >::getOrCreate (TypeClass * Ty, ValType V) [inline]
Return the specified constant from the map, creating it if necessary.
Definition at line 578 of file ConstantsContext.h.
Referenced by llvm::InlineAsm::get(), llvm::ConstantArray::get(), llvm::ConstantStruct::get(), llvm::ConstantVector::get(), llvm::ConstantExpr::get(), llvm::ConstantExpr::getExtractElement(), llvm::ConstantExpr::getExtractValue(), llvm::ConstantExpr::getFCmp(), getFoldedCast(), llvm::ConstantExpr::getGetElementPtr(), llvm::ConstantExpr::getICmp(), llvm::ConstantExpr::getInsertElement(), llvm::ConstantExpr::getInsertValue(), llvm::ConstantExpr::getSelect(), and llvm::ConstantExpr::getShuffleVector().
template<class ConstantClass> void llvm::ConstantUniqueMap< ConstantClass >::insert (ConstantClass * CP) [inline]
Insert the constant into its proper slot.
Definition at line 598 of file ConstantsContext.h.
Referenced by llvm::ConstantUniqueMap< ConstantStruct >::replaceOperandsInPlace().
template<class ConstantClass> MapTy::iterator llvm::ConstantUniqueMap< ConstantClass >::map_begin () [inline]
Definition at line 557 of file ConstantsContext.h.
Referenced by llvm::LLVMContextImpl::dropTriviallyDeadConstantArrays(), and llvm::LLVMContextImpl::~LLVMContextImpl().
template<class ConstantClass> MapTy::iterator llvm::ConstantUniqueMap< ConstantClass >::map_end () [inline]
Definition at line 558 of file ConstantsContext.h.
Referenced by llvm::LLVMContextImpl::dropTriviallyDeadConstantArrays(), and llvm::LLVMContextImpl::~LLVMContextImpl().
template<class ConstantClass> void llvm::ConstantUniqueMap< ConstantClass >::remove (ConstantClass * CP) [inline]
Remove this constant from the map.
Definition at line 601 of file ConstantsContext.h.
template<class ConstantClass> ConstantClass* llvm::ConstantUniqueMap< ConstantClass >::replaceOperandsInPlace (ArrayRef< Constant * > Operands, ConstantClass * CP, Value * From, Constant * To, unsigned NumUpdated = 0, unsigned OperandNo = ~0u) [inline]
Definition at line 608 of file ConstantsContext.h.
The documentation for this class was generated from the following file:
ConstantsContext.h