LLVM: llvm::PtrToIntOperator Class Reference
llvm::PtrToIntOperator Class Reference
#include <Operator.h>
Public Member Functions
Value * getPointerOperand ()
const Value * getPointerOperand () const
Type * getPointerOperandType () const
Method to return the pointer operand as a PointerType.
unsigned getPointerAddressSpace () const
Method to return the address space of the pointer operand.
Static Public Member Functions
static unsigned getPointerOperandIndex ()
Friends
class PtrToInt
class ConstantExpr
Detailed Description
Definition at line 452 of file Operator.h.
Member Function Documentation
unsigned llvm::PtrToIntOperator::getPointerAddressSpace () const [inline]
Method to return the address space of the pointer operand.
Definition at line 474 of file Operator.h.
Value* llvm::PtrToIntOperator::getPointerOperand () [inline]
Definition at line 458 of file Operator.h.
References llvm::User::getOperand().
const Value* llvm::PtrToIntOperator::getPointerOperand () const [inline]
Definition at line 461 of file Operator.h.
References llvm::User::getOperand().
static unsigned llvm::PtrToIntOperator::getPointerOperandIndex () [inline, static]
Definition at line 464 of file Operator.h.
Type* llvm::PtrToIntOperator::getPointerOperandType () const [inline]
Method to return the pointer operand as a PointerType.
Definition at line 469 of file Operator.h.
References getPointerOperand().
Friends And Related Function Documentation
friend class ConstantExpr [friend]
Definition at line 455 of file Operator.h.
friend class PtrToInt [friend]
Definition at line 454 of file Operator.h.
The documentation for this class was generated from the following file:
Operator.h