LLVM: llvm::GCStrategy Class Reference
llvm::GCStrategy Class Reference
GCStrategy describes a garbage collector algorithm's code generation requirements, and provides overridable hooks for those needs which cannot be abstractly described.
#include <GCStrategy.h>
Public Member Functions
GCStrategy ()
virtual ~GCStrategy ()
const std::string & getName () const
Return the name of the GC strategy.
bool customWriteBarrier () const
By default, write barriers are replaced with simple store instructions.
bool customReadBarrier () const
By default, read barriers are replaced with simple load instructions.
bool useStatepoints () const
Returns true if this strategy is expecting the use of gc.statepoints, and false otherwise.
Statepoint Specific Properties
virtual Optional< bool > isGCManagedPointer (const Value *V) const
If the value specified can be reliably distinguished, returns true for pointers to GC managed locations and false for pointers to non-GC managed locations.
GCRoot Specific Properties
These properties and overrides only apply to collector strategies using GCRoot.
bool needsSafePoints () const
True if safe points of any kind are required.
bool needsSafePoint (GC::PointKind Kind) const
True if the given kind of safe point is required.
bool customRoots () const
By default, roots are left for the code generator so it can generate a stack map.
bool initializeRoots () const
If set, gcroot intrinsics should initialize their allocas to null before the first use.
bool usesMetadata () const
If set, appropriate metadata tables must be emitted by the back-end (assembler, JIT, or otherwise).
Protected Attributes
bool UseStatepoints
unsigned NeededSafePoints
Uses gc.statepoints as opposed to gc.roots, if set, none of the other options can be anything but their default values.
bool CustomReadBarriers
Default is to insert loads.
bool CustomWriteBarriers
Default is to insert stores.
bool CustomRoots
Default is to pass through to backend.
bool InitRoots
If set, roots are nulled during lowering.
bool UsesMetadata
If set, backend must emit metadata tables.
Friends
class GCModuleInfo
Detailed Description
GCStrategy describes a garbage collector algorithm's code generation requirements, and provides overridable hooks for those needs which cannot be abstractly described.
GCStrategy objects must be looked up through the Function. The objects themselves are owned by the Context and must be immutable.
Definition at line 78 of file GCStrategy.h.
Constructor & Destructor Documentation
GCStrategy::GCStrategy ()
Definition at line 19 of file GCStrategy.cpp.
virtual llvm::GCStrategy::~GCStrategy () [inline, virtual]
Definition at line 97 of file GCStrategy.h.
Member Function Documentation
bool llvm::GCStrategy::customReadBarrier () const [inline]
By default, read barriers are replaced with simple load instructions.
If true, you must provide a custom pass to lower calls to .gcread.
Definition at line 111 of file GCStrategy.h.
References CustomReadBarriers.
Referenced by NeedsDefaultLoweringPass().
bool llvm::GCStrategy::customRoots () const [inline]
By default, roots are left for the code generator so it can generate a stack map.
If true, you must provide a custom pass to lower calls to .gcroot.
Definition at line 148 of file GCStrategy.h.
References CustomRoots.
bool llvm::GCStrategy::customWriteBarrier () const [inline]
By default, write barriers are replaced with simple store instructions.
If true, you must provide a custom pass to lower calls to .gcwrite.
Definition at line 106 of file GCStrategy.h.
References CustomWriteBarriers.
Referenced by NeedsDefaultLoweringPass().
const std::string& llvm::GCStrategy::getName () const [inline]
Return the name of the GC strategy.
This is the value of the collector name string specified on functions which use this strategy.
Definition at line 101 of file GCStrategy.h.
bool llvm::GCStrategy::initializeRoots () const [inline]
If set, gcroot intrinsics should initialize their allocas to null before the first use.
This is necessary for most GCs and is enabled by default.
Definition at line 153 of file GCStrategy.h.
References InitRoots.
Referenced by NeedsDefaultLoweringPass().
virtual Optional<bool> llvm::GCStrategy::isGCManagedPointer (const Value * V) const [inline, virtual]
If the value specified can be reliably distinguished, returns true for pointers to GC managed locations and false for pointers to non-GC managed locations.
Note a GCStrategy can always return 'None' (i.e. an empty optional indicating it can't reliably distinguish.
Definition at line 124 of file GCStrategy.h.
References llvm::None.
Referenced by lowerStatepointMetaArgs().
bool llvm::GCStrategy::needsSafePoint (GC::PointKind Kind) const [inline]
True if the given kind of safe point is required.
By default, none are recorded.
Definition at line 141 of file GCStrategy.h.
References NeededSafePoints.
bool llvm::GCStrategy::needsSafePoints () const [inline]
True if safe points of any kind are required.
By default, none are recorded.
Definition at line 137 of file GCStrategy.h.
References NeededSafePoints.
bool llvm::GCStrategy::usesMetadata () const [inline]
If set, appropriate metadata tables must be emitted by the back-end (assembler, JIT, or otherwise).
For statepoint, this method is currently unsupported. The stackmap information can be found in the StackMap section as described in the documentation.
Definition at line 159 of file GCStrategy.h.
References UsesMetadata.
bool llvm::GCStrategy::useStatepoints () const [inline]
Returns true if this strategy is expecting the use of gc.statepoints, and false otherwise.
Definition at line 115 of file GCStrategy.h.
References UseStatepoints.
Referenced by llvm::SelectionDAGBuilder::LowerStatepoint().
Friends And Related Function Documentation
friend class GCModuleInfo [friend]
Definition at line 81 of file GCStrategy.h.
Member Data Documentation
bool llvm::GCStrategy::CustomReadBarriers [protected]
Default is to insert loads.
Definition at line 89 of file GCStrategy.h.
Referenced by customReadBarrier().
bool llvm::GCStrategy::CustomRoots [protected]
Default is to pass through to backend.
Definition at line 91 of file GCStrategy.h.
Referenced by customRoots().
bool llvm::GCStrategy::CustomWriteBarriers [protected]
Default is to insert stores.
Definition at line 90 of file GCStrategy.h.
Referenced by customWriteBarrier().
bool llvm::GCStrategy::InitRoots [protected]
If set, roots are nulled during lowering.
Definition at line 92 of file GCStrategy.h.
Referenced by initializeRoots().
unsigned llvm::GCStrategy::NeededSafePoints [protected]
Uses gc.statepoints as opposed to gc.roots, if set, none of the other options can be anything but their default values.
Bitmask of required safe points.
Definition at line 88 of file GCStrategy.h.
Referenced by needsSafePoint(), and needsSafePoints().
bool llvm::GCStrategy::UsesMetadata [protected]
If set, backend must emit metadata tables.
Definition at line 93 of file GCStrategy.h.
Referenced by usesMetadata().
bool llvm::GCStrategy::UseStatepoints [protected]
Definition at line 84 of file GCStrategy.h.
Referenced by useStatepoints().
The documentation for this class was generated from the following files:
GCStrategy.h
GCStrategy.cpp