LLVM: llvm::AMDGPUSubtarget Class Reference
llvm::AMDGPUSubtarget Class Reference
#include <AMDGPUSubtarget.h>
Public Types
enum Generation {
R600 = 0, R700, EVERGREEN, NORTHERN_ISLANDS,
SOUTHERN_ISLANDS, SEA_ISLANDS, VOLCANIC_ISLANDS
}
enum { FIXED_SGPR_COUNT_FOR_INIT_BUG = 80 }
Public Member Functions
AMDGPUSubtarget (const Triple &TT, StringRef CPU, StringRef FS, TargetMachine &TM)
AMDGPUSubtarget & initializeSubtargetDependencies (const Triple &TT, StringRef GPU, StringRef FS)
const AMDGPUFrameLowering * getFrameLowering () const override
const AMDGPUInstrInfo * getInstrInfo () const override
const AMDGPURegisterInfo * getRegisterInfo () const override
AMDGPUTargetLowering * getTargetLowering () const override
const InstrItineraryData * getInstrItineraryData () const override
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
bool is64bit () const
bool hasVertexCache () const
short getTexVTXClauseSize () const
Generation getGeneration () const
bool hasHWFP64 () const
bool hasCaymanISA () const
bool hasFP32Denormals () const
bool hasFP64Denormals () const
bool hasFastFMAF32 () const
bool hasFlatAddressSpace () const
bool hasBFE () const
bool hasBFI () const
bool hasBFM () const
bool hasBCNT (unsigned Size) const
bool hasMulU24 () const
bool hasMulI24 () const
bool hasFFBL () const
bool hasFFBH () const
bool hasCARRY () const
bool hasBORROW () const
bool IsIRStructurizerEnabled () const
bool isPromoteAllocaEnabled () const
bool isIfCvtEnabled () const
bool loadStoreOptEnabled () const
unsigned getWavefrontSize () const
unsigned getStackEntrySize () const
bool hasCFAluBug () const
int getLocalMemorySize () const
bool hasSGPRInitBug () const
int getLDSBankCount () const
unsigned getAmdKernelCodeChipID () const
bool enableMachineScheduler () const override
void overrideSchedPolicy (MachineSchedPolicy &Policy, MachineInstr *begin, MachineInstr *end, unsigned NumRegionInstrs) const override
bool isTargetELF () const
StringRef getDeviceName () const
bool dumpCode () const
bool r600ALUEncoding () const
bool isAmdHsaOS () const
bool isVGPRSpillingEnabled (const SIMachineFunctionInfo *MFI) const
unsigned getMaxWavesPerCU () const
bool enableSubRegLiveness () const override
Detailed Description
Definition at line 34 of file AMDGPUSubtarget.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
FIXED_SGPR_COUNT_FOR_INIT_BUG
Definition at line 47 of file AMDGPUSubtarget.h.
enum llvm::AMDGPUSubtarget::Generation
Enumerator:
R600
R700
EVERGREEN
NORTHERN_ISLANDS
SOUTHERN_ISLANDS
SEA_ISLANDS
VOLCANIC_ISLANDS
Definition at line 37 of file AMDGPUSubtarget.h.
Constructor & Destructor Documentation
AMDGPUSubtarget::AMDGPUSubtarget (const Triple & TT, StringRef CPU, StringRef FS, TargetMachine & TM)
Definition at line 64 of file AMDGPUSubtarget.cpp.
References getGeneration(), initializeSubtargetDependencies(), and NORTHERN_ISLANDS.
Member Function Documentation
bool llvm::AMDGPUSubtarget::dumpCode () const [inline]
Definition at line 256 of file AMDGPUSubtarget.h.
Referenced by llvm::AMDGPUAsmPrinter::EmitInstruction(), and llvm::AMDGPUAsmPrinter::runOnMachineFunction().
bool llvm::AMDGPUSubtarget::enableMachineScheduler () const [inline, override]
Definition at line 239 of file AMDGPUSubtarget.h.
bool llvm::AMDGPUSubtarget::enableSubRegLiveness () const [inline, override]
Definition at line 275 of file AMDGPUSubtarget.h.
unsigned AMDGPUSubtarget::getAmdKernelCodeChipID () const
Definition at line 105 of file AMDGPUSubtarget.cpp.
References getGeneration(), llvm_unreachable, and SEA_ISLANDS.
StringRef llvm::AMDGPUSubtarget::getDeviceName () const [inline]
Definition at line 252 of file AMDGPUSubtarget.h.
const AMDGPUFrameLowering* llvm::AMDGPUSubtarget::getFrameLowering () const [inline, override]
Definition at line 93 of file AMDGPUSubtarget.h.
Generation llvm::AMDGPUSubtarget::getGeneration () const [inline]
Definition at line 123 of file AMDGPUSubtarget.h.
Referenced by AMDGPUSubtarget(), llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::R600InstrInfo::buildSlotOfVectorInstruction(), canFoldOffset(), llvm::AMDGPUTargetLowering::CombineFMinMaxLegacy(), llvm::SIRegisterInfo::eliminateFrameIndex(), getAmdKernelCodeChipID(), getMaxWavesPerCU(), llvm::AMDGPUTTIImpl::getNumberOfRegisters(), llvm::SIRegisterInfo::getRegPressureSetLimit(), getStackEntrySize(), hasBCNT(), hasBFE(), hasBFI(), hasBORROW(), hasCARRY(), hasCFAluBug(), hasFFBH(), hasFFBL(), hasMulI24(), hasMulU24(), initializeSubtargetDependencies(), llvm::SITargetLowering::LowerFormalArguments(), llvm::AMDGPUTargetLowering::LowerLOAD(), llvm::SIInstrInfo::moveToVALU(), overrideSchedPolicy(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::AMDGPUInstrInfo::pseudoToMCOpcode(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), and llvm::SITargetLowering::SITargetLowering().
const AMDGPUInstrInfo* llvm::AMDGPUSubtarget::getInstrInfo () const [inline, override]
Definition at line 96 of file AMDGPUSubtarget.h.
Referenced by llvm::SITargetLowering::AdjustInstrPostInstrSelection(), llvm::SITargetLowering::analyzeImmediate(), llvm::SITargetLowering::buildScratchRSRC(), llvm::AMDGPUAsmPrinter::EmitInstruction(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::AMDGPUMCInstLower::lower(), llvm::R600TargetLowering::LowerOperation(), llvm::SITargetLowering::PostISelFolding(), llvm::SITargetLowering::shouldConvertConstantLoadToIntImm(), and llvm::SITargetLowering::wrapAddr64Rsrc().
const InstrItineraryData* llvm::AMDGPUSubtarget::getInstrItineraryData () const [inline, override]
Definition at line 105 of file AMDGPUSubtarget.h.
int llvm::AMDGPUSubtarget::getLDSBankCount () const [inline]
Definition at line 233 of file AMDGPUSubtarget.h.
int llvm::AMDGPUSubtarget::getLocalMemorySize () const [inline]
Definition at line 225 of file AMDGPUSubtarget.h.
unsigned llvm::AMDGPUSubtarget::getMaxWavesPerCU () const [inline]
Definition at line 267 of file AMDGPUSubtarget.h.
References getGeneration(), llvm_unreachable, and SOUTHERN_ISLANDS.
Referenced by llvm::SIRegisterInfo::getRegPressureSetLimit().
const AMDGPURegisterInfo* llvm::AMDGPUSubtarget::getRegisterInfo () const [inline, override]
Definition at line 99 of file AMDGPUSubtarget.h.
Referenced by llvm::SITargetLowering::LowerFormalArguments(), llvm::R600TargetLowering::R600TargetLowering(), and llvm::SITargetLowering::SITargetLowering().
unsigned AMDGPUSubtarget::getStackEntrySize () const
Definition at line 91 of file AMDGPUSubtarget.cpp.
References getGeneration(), getWavefrontSize(), hasCaymanISA(), llvm_unreachable, and NORTHERN_ISLANDS.
AMDGPUTargetLowering* llvm::AMDGPUSubtarget::getTargetLowering () const [inline, override]
Definition at line 102 of file AMDGPUSubtarget.h.
short llvm::AMDGPUSubtarget::getTexVTXClauseSize () const [inline]
Definition at line 119 of file AMDGPUSubtarget.h.
Referenced by llvm::R600SchedStrategy::initialize().
unsigned llvm::AMDGPUSubtarget::getWavefrontSize () const [inline]
Definition at line 214 of file AMDGPUSubtarget.h.
Referenced by llvm::SIMachineFunctionInfo::getMaximumWorkGroupSize(), and getStackEntrySize().
bool llvm::AMDGPUSubtarget::hasBCNT (unsigned Size) const [inline]
Definition at line 163 of file AMDGPUSubtarget.h.
References EVERGREEN, getGeneration(), and SOUTHERN_ISLANDS.
Referenced by llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), and llvm::AMDGPUTTIImpl::getPopcntSupport().
bool llvm::AMDGPUSubtarget::hasBFE () const [inline]
Definition at line 151 of file AMDGPUSubtarget.h.
References EVERGREEN, and getGeneration().
Referenced by hasBFM(), and llvm::R600TargetLowering::R600TargetLowering().
bool llvm::AMDGPUSubtarget::hasBFI () const [inline]
Definition at line 155 of file AMDGPUSubtarget.h.
References EVERGREEN, and getGeneration().
Referenced by llvm::AMDGPUTargetLowering::AMDGPUTargetLowering().
bool llvm::AMDGPUSubtarget::hasBFM () const [inline]
Definition at line 159 of file AMDGPUSubtarget.h.
References hasBFE().
bool llvm::AMDGPUSubtarget::hasBORROW () const [inline]
Definition at line 194 of file AMDGPUSubtarget.h.
References EVERGREEN, and getGeneration().
Referenced by llvm::R600TargetLowering::R600TargetLowering().
bool llvm::AMDGPUSubtarget::hasCARRY () const [inline]
Definition at line 190 of file AMDGPUSubtarget.h.
References EVERGREEN, and getGeneration().
Referenced by llvm::R600TargetLowering::R600TargetLowering().
bool llvm::AMDGPUSubtarget::hasCaymanISA () const [inline]
Definition at line 131 of file AMDGPUSubtarget.h.
Referenced by getStackEntrySize(), hasMulI24(), llvm::R600SchedStrategy::initialize(), and llvm::R600InstrInfo::isTransOnly().
bool llvm::AMDGPUSubtarget::hasCFAluBug () const [inline]
Definition at line 220 of file AMDGPUSubtarget.h.
References getGeneration(), and NORTHERN_ISLANDS.
bool llvm::AMDGPUSubtarget::hasFastFMAF32 () const [inline]
Definition at line 143 of file AMDGPUSubtarget.h.
Referenced by llvm::SITargetLowering::isFMAFasterThanFMulAndFAdd().
bool llvm::AMDGPUSubtarget::hasFFBH () const [inline]
Definition at line 186 of file AMDGPUSubtarget.h.
References EVERGREEN, and getGeneration().
Referenced by llvm::AMDGPUTargetLowering::AMDGPUTargetLowering().
bool llvm::AMDGPUSubtarget::hasFFBL () const [inline]
Definition at line 182 of file AMDGPUSubtarget.h.
References EVERGREEN, and getGeneration().
Referenced by llvm::AMDGPUTargetLowering::AMDGPUTargetLowering().
bool llvm::AMDGPUSubtarget::hasFlatAddressSpace () const [inline]
Definition at line 147 of file AMDGPUSubtarget.h.
bool llvm::AMDGPUSubtarget::hasFP32Denormals () const [inline]
Definition at line 135 of file AMDGPUSubtarget.h.
Referenced by llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), getFPMode(), llvm::SITargetLowering::isFMAFasterThanFMulAndFAdd(), and llvm::SITargetLowering::PerformDAGCombine().
bool llvm::AMDGPUSubtarget::hasFP64Denormals () const [inline]
Definition at line 139 of file AMDGPUSubtarget.h.
Referenced by getFPMode().
bool llvm::AMDGPUSubtarget::hasHWFP64 () const [inline]
Definition at line 127 of file AMDGPUSubtarget.h.
bool llvm::AMDGPUSubtarget::hasMulI24 () const [inline]
Definition at line 177 of file AMDGPUSubtarget.h.
References getGeneration(), hasCaymanISA(), and SOUTHERN_ISLANDS.
bool llvm::AMDGPUSubtarget::hasMulU24 () const [inline]
Definition at line 173 of file AMDGPUSubtarget.h.
References EVERGREEN, and getGeneration().
bool llvm::AMDGPUSubtarget::hasSGPRInitBug () const [inline]
Definition at line 229 of file AMDGPUSubtarget.h.
Referenced by llvm::SIRegisterInfo::getReservedRegs().
bool llvm::AMDGPUSubtarget::hasVertexCache () const [inline]
Definition at line 115 of file AMDGPUSubtarget.h.
Referenced by llvm::R600InstrInfo::usesTextureCache(), and llvm::R600InstrInfo::usesVertexCache().
AMDGPUSubtarget & AMDGPUSubtarget::initializeSubtargetDependencies (const Triple & TT, StringRef GPU, StringRef FS)
Definition at line 35 of file AMDGPUSubtarget.cpp.
References llvm::Triple::amdgcn, llvm::FS, llvm::Triple::getArch(), getGeneration(), NORTHERN_ISLANDS, and ParseSubtargetFeatures().
Referenced by AMDGPUSubtarget().
bool llvm::AMDGPUSubtarget::is64bit () const [inline]
Definition at line 111 of file AMDGPUSubtarget.h.
bool llvm::AMDGPUSubtarget::isAmdHsaOS () const [inline]
Definition at line 262 of file AMDGPUSubtarget.h.
References llvm::Triple::AMDHSA, and llvm::Triple::getOS().
Referenced by llvm::SIInstrInfo::getDefaultRsrcDataFormat(), llvm::SITargetLowering::LowerFormalArguments(), and llvm::AMDGPUAsmPrinter::runOnMachineFunction().
bool llvm::AMDGPUSubtarget::isIfCvtEnabled () const [inline]
Definition at line 206 of file AMDGPUSubtarget.h.
bool llvm::AMDGPUSubtarget::IsIRStructurizerEnabled () const [inline]
Definition at line 198 of file AMDGPUSubtarget.h.
bool llvm::AMDGPUSubtarget::isPromoteAllocaEnabled () const [inline]
Definition at line 202 of file AMDGPUSubtarget.h.
bool llvm::AMDGPUSubtarget::isTargetELF () const [inline]
Definition at line 248 of file AMDGPUSubtarget.h.
bool AMDGPUSubtarget::isVGPRSpillingEnabled (const SIMachineFunctionInfo * MFI) const
Definition at line 112 of file AMDGPUSubtarget.cpp.
References ShaderType::COMPUTE, and llvm::AMDGPUMachineFunction::getShaderType().
Referenced by llvm::SIInstrInfo::loadRegFromStackSlot(), and llvm::SIInstrInfo::storeRegToStackSlot().
bool llvm::AMDGPUSubtarget::loadStoreOptEnabled () const [inline]
Definition at line 210 of file AMDGPUSubtarget.h.
void AMDGPUSubtarget::overrideSchedPolicy (MachineSchedPolicy & Policy, MachineInstr * begin, MachineInstr * end, unsigned NumRegionInstrs) const [override]
Definition at line 117 of file AMDGPUSubtarget.cpp.
References getGeneration(), llvm::MachineSchedPolicy::OnlyBottomUp, llvm::MachineSchedPolicy::OnlyTopDown, llvm::MachineSchedPolicy::ShouldTrackPressure, and SOUTHERN_ISLANDS.
void llvm::AMDGPUSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
Referenced by initializeSubtargetDependencies().
bool llvm::AMDGPUSubtarget::r600ALUEncoding () const [inline]
Definition at line 259 of file AMDGPUSubtarget.h.
The documentation for this class was generated from the following files:
AMDGPUSubtarget.h
AMDGPUSubtarget.cpp