LLVM: llvm::PtrToIntInst Class Reference
llvm::PtrToIntInst Class Reference
This class represents a cast from a pointer to an integer.
#include <Instructions.h>
Public Member Functions
PtrToIntInst (Value *S, Type *Ty, const Twine &NameStr="", Instruction *InsertBefore=nullptr)
Constructor with insert-before-instruction semantics.
PtrToIntInst (Value *S, Type *Ty, const Twine &NameStr, BasicBlock *InsertAtEnd)
Constructor with insert-at-end-of-block semantics.
Value * getPointerOperand ()
Gets the pointer operand.
const Value * getPointerOperand () const
Gets the pointer operand.
unsigned getPointerAddressSpace () const
Returns the address space of the pointer operand.
Static Public Member Functions
static unsigned getPointerOperandIndex ()
Gets the operand index of the pointer operand.
static bool classof (const Instruction *I)
Methods for support type inquiry through isa, cast, and dyn_cast:
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
PtrToIntInst * clone_impl () const override
Clone an identical PtrToIntInst.
Detailed Description
This class represents a cast from a pointer to an integer.
Definition at line 3870 of file Instructions.h.
Constructor & Destructor Documentation
PtrToIntInst::PtrToIntInst (Value * S, Type * Ty, const Twine & NameStr = "", Instruction * InsertBefore = nullptr)
Constructor with insert-before-instruction semantics.
Parameters:
S The value to be converted
Ty The type to convert to
NameStr A name for the new instruction
InsertBefore Where to insert the new instruction
Definition at line 2917 of file Instructions.cpp.
References llvm::CastInst::castIsValid(), and llvm::CastInst::getOpcode().
Referenced by clone_impl().
PtrToIntInst::PtrToIntInst (Value * S, Type * Ty, const Twine & NameStr, BasicBlock * InsertAtEnd)
Constructor with insert-at-end-of-block semantics.
Parameters:
S The value to be converted
Ty The type to convert to
NameStr A name for the new instruction
InsertAtEnd The block to insert the instruction into
Definition at line 2923 of file Instructions.cpp.
References llvm::CastInst::castIsValid(), and llvm::CastInst::getOpcode().
Member Function Documentation
static bool llvm::PtrToIntInst::classof (const Instruction * I) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::CastInst.
Definition at line 3905 of file Instructions.h.
References llvm::Instruction::getOpcode().
Referenced by classof().
static bool llvm::PtrToIntInst::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::CastInst.
Definition at line 3908 of file Instructions.h.
References classof().
PtrToIntInst * PtrToIntInst::clone_impl () const [override, protected, virtual]
Clone an identical PtrToIntInst.
Implements llvm::Instruction.
Definition at line 3557 of file Instructions.cpp.
References llvm::User::getOperand(), llvm::Value::getType(), and PtrToIntInst().
unsigned llvm::PtrToIntInst::getPointerAddressSpace () const [inline]
Returns the address space of the pointer operand.
Definition at line 3900 of file Instructions.h.
References llvm::Type::getPointerAddressSpace(), getPointerOperand(), and llvm::Value::getType().
Referenced by llvm::InstCombiner::visitPtrToInt().
Value* llvm::PtrToIntInst::getPointerOperand () [inline]
Gets the pointer operand.
Definition at line 3893 of file Instructions.h.
References llvm::User::getOperand().
Referenced by getPointerAddressSpace().
const Value* llvm::PtrToIntInst::getPointerOperand () const [inline]
Gets the pointer operand.
Definition at line 3895 of file Instructions.h.
References llvm::User::getOperand().
static unsigned llvm::PtrToIntInst::getPointerOperandIndex () [inline, static]
Gets the operand index of the pointer operand.
Definition at line 3897 of file Instructions.h.
The documentation for this class was generated from the following files:
Instructions.h
Instructions.cpp