LLVM: llvm::MipsAsmPrinter Class Reference
llvm::MipsAsmPrinter Class Reference
#include <MipsAsmPrinter.h>
Public Member Functions
MipsAsmPrinter (TargetMachine &TM, std::unique_ptr< MCStreamer > Streamer)
const char * getPassName () const override
getPassName - Return a nice clean name for a pass.
bool runOnMachineFunction (MachineFunction &MF) override
Emit the specified function out to the OutStreamer.
void EmitConstantPool () override
Print to the current output stream assembly representations of the constants in the constant pool MCP.
void EmitInstruction (const MachineInstr *MI) override
Targets should implement this to emit instructions.
void printSavedRegsBitmask ()
void emitFrameDirective ()
Frame Directive.
const char * getCurrentABIString () const
Emit Set directives.
void EmitFunctionEntryLabel () override
EmitFunctionEntryLabel - Emit the label that is the entrypoint for the function.
void EmitFunctionBodyStart () override
EmitFunctionBodyStart - Targets can override this to emit stuff before the first basic block in the function.
void EmitFunctionBodyEnd () override
EmitFunctionBodyEnd - Targets can override this to emit stuff after the last basic block in the function.
void EmitBasicBlockEnd (const MachineBasicBlock &MBB) override
Targets can override this to emit stuff at the end of a basic block.
bool isBlockOnlyReachableByFallthrough (const MachineBasicBlock *MBB) const override
isBlockOnlyReachableByFallthough - Return true if the basic block has exactly one predecessor and the control transfer mechanism between the predecessor and this block is a fall-through.
bool PrintAsmOperand (const MachineInstr *MI, unsigned OpNo, unsigned AsmVariant, const char *ExtraCode, raw_ostream &O) override
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
bool PrintAsmMemoryOperand (const MachineInstr *MI, unsigned OpNum, unsigned AsmVariant, const char *ExtraCode, raw_ostream &O) override
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address.
void printOperand (const MachineInstr *MI, int opNum, raw_ostream &O)
void printUnsignedImm (const MachineInstr *MI, int opNum, raw_ostream &O)
void printUnsignedImm8 (const MachineInstr *MI, int opNum, raw_ostream &O)
void printMemOperand (const MachineInstr *MI, int opNum, raw_ostream &O)
void printMemOperandEA (const MachineInstr *MI, int opNum, raw_ostream &O)
void printFCCOperand (const MachineInstr *MI, int opNum, raw_ostream &O, const char *Modifier=nullptr)
void printRegisterList (const MachineInstr *MI, int opNum, raw_ostream &O)
void EmitStartOfAsmFile (Module &M) override
This virtual method can be overridden by targets that want to emit something at the start of their file.
void EmitEndOfAsmFile (Module &M) override
This virtual method can be overridden by targets that want to emit something at the end of their file.
void PrintDebugValueComment (const MachineInstr *MI, raw_ostream &OS)
Public Attributes
const MipsSubtarget * Subtarget
const MipsFunctionInfo * MipsFI
MipsMCInstLower MCInstLowering
Detailed Description
Definition at line 33 of file MipsAsmPrinter.h.
Constructor & Destructor Documentation
llvm::MipsAsmPrinter::MipsAsmPrinter (TargetMachine & TM, std::unique_ptr< MCStreamer > Streamer) [inline, explicit]
Definition at line 101 of file MipsAsmPrinter.h.
Member Function Documentation
void MipsAsmPrinter::EmitBasicBlockEnd (const MachineBasicBlock & MBB) [override, virtual]
Targets can override this to emit stuff at the end of a basic block.
Reimplemented from llvm::AsmPrinter.
Definition at line 386 of file MipsAsmPrinter.cpp.
References llvm::MipsTargetStreamer::emitDirectiveInsn(), llvm::MachineBasicBlock::size(), and fuzzer::TS.
void llvm::MipsAsmPrinter::EmitConstantPool () [inline, override, virtual]
Print to the current output stream assembly representations of the constants in the constant pool MCP.
EmitConstantPool - Print to the current output stream assembly representations of the constants in the constant pool MCP.
This is used to print out constants which have been "spilled to memory" by the code generator.
Reimplemented from llvm::AsmPrinter.
Definition at line 112 of file MipsAsmPrinter.h.
References llvm::AsmPrinter::EmitConstantPool().
void MipsAsmPrinter::EmitEndOfAsmFile (Module &) [override, virtual]
This virtual method can be overridden by targets that want to emit something at the end of their file.
Reimplemented from llvm::AsmPrinter.
Definition at line 1040 of file MipsAsmPrinter.cpp.
References llvm::MCContext::getObjectFileInfo(), llvm::MCObjectFileInfo::getTextSection(), llvm::AsmPrinter::OutContext, and llvm::MCStreamer::SwitchSection().
void MipsAsmPrinter::emitFrameDirective ()
Frame Directive.
Definition at line 300 of file MipsAsmPrinter.cpp.
References llvm::MipsTargetStreamer::emitFrame(), llvm::MachineFunction::getFrameInfo(), llvm::TargetRegisterInfo::getFrameRegister(), llvm::MCRegisterInfo::getRARegister(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), and llvm::AsmPrinter::MF.
Referenced by EmitFunctionBodyStart().
void MipsAsmPrinter::EmitFunctionBodyEnd () [override, virtual]
EmitFunctionBodyEnd - Targets can override this to emit stuff after the last basic block in the function.
Reimplemented from llvm::AsmPrinter.
Definition at line 366 of file MipsAsmPrinter.cpp.
References llvm::AsmPrinter::CurrentFnSym, llvm::MCStreamer::EmitDataRegion(), llvm::MipsTargetStreamer::emitDirectiveEnd(), llvm::MipsTargetStreamer::emitDirectiveSetAt(), llvm::MipsTargetStreamer::emitDirectiveSetMacro(), llvm::MipsTargetStreamer::emitDirectiveSetReorder(), llvm::MCSymbol::getName(), llvm::MipsSubtarget::inMips16Mode(), llvm::MCDR_DataRegionEnd, Subtarget, and fuzzer::TS.
void MipsAsmPrinter::EmitFunctionBodyStart () [override, virtual]
EmitFunctionBodyStart - Targets can override this to emit stuff before the first basic block in the function.
Reimplemented from llvm::AsmPrinter.
Definition at line 345 of file MipsAsmPrinter.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetNoAt(), llvm::MipsTargetStreamer::emitDirectiveSetNoMacro(), llvm::MipsTargetStreamer::emitDirectiveSetNoReorder(), emitFrameDirective(), llvm::MachineFunction::getContext(), llvm::MachineFunction::getFunction(), llvm::Function::hasFnAttribute(), llvm::MipsMCInstLower::Initialize(), llvm::MipsSubtarget::inMips16Mode(), MCInstLowering, llvm::AsmPrinter::MF, llvm::Attribute::Naked, printSavedRegsBitmask(), Subtarget, and fuzzer::TS.
void MipsAsmPrinter::EmitFunctionEntryLabel () [override, virtual]
EmitFunctionEntryLabel - Emit the label that is the entrypoint for the function.
This can be overridden by targets as required to do custom stuff.
Reimplemented from llvm::AsmPrinter.
Definition at line 321 of file MipsAsmPrinter.cpp.
References llvm::AsmPrinter::CurrentFnSym, llvm::AsmPrinter::EmitAlignment(), llvm::MipsTargetStreamer::emitDirectiveEnt(), llvm::MipsTargetStreamer::emitDirectiveSetMicroMips(), llvm::MipsTargetStreamer::emitDirectiveSetMips16(), llvm::MipsTargetStreamer::emitDirectiveSetNoMicroMips(), llvm::MipsTargetStreamer::emitDirectiveSetNoMips16(), llvm::MCStreamer::EmitLabel(), llvm::MachineFunction::getAlignment(), llvm::MipsSubtarget::inMicroMipsMode(), llvm::MipsSubtarget::inMips16Mode(), llvm::MipsSubtarget::isTargetNaCl(), llvm::AsmPrinter::MF, llvm::MIPS_NACL_BUNDLE_ALIGN, Subtarget, and fuzzer::TS.
void MipsAsmPrinter::EmitInstruction (const MachineInstr *) [override, virtual]
Targets should implement this to emit instructions.
Reimplemented from llvm::AsmPrinter.
Definition at line 132 of file MipsAsmPrinter.cpp.
References llvm::MachineConstantPoolEntry::ConstVal, llvm::MCStreamer::EmitDataRegion(), llvm::AsmPrinter::EmitGlobalConstant(), llvm::MCStreamer::EmitLabel(), llvm::AsmPrinter::EmitMachineConstantPoolValue(), llvm::AsmPrinter::EmitToStreamer(), llvm::MipsTargetStreamer::forbidModuleDirective(), llvm::MachineConstantPool::getConstants(), llvm::AsmPrinter::GetCPISymbol(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), I, llvm::MipsSubtarget::inMips16Mode(), llvm::MachineBasicBlock::instr_end(), llvm::MachineInstr::isDebugValue(), llvm::MachineConstantPoolEntry::isMachineConstantPoolEntry(), llvm_unreachable, llvm::MipsMCInstLower::Lower(), llvm::MachineConstantPoolEntry::MachineCPVal, llvm::MCDR_DataRegion, llvm::MCDR_DataRegionEnd, MCInstLowering, llvm::AArch64CC::MI, PrintDebugValueComment(), Subtarget, fuzzer::TS, and llvm::MachineConstantPoolEntry::Val.
void MipsAsmPrinter::EmitStartOfAsmFile (Module &) [override, virtual]
This virtual method can be overridden by targets that want to emit something at the start of their file.
Reimplemented from llvm::AsmPrinter.
Definition at line 690 of file MipsAsmPrinter.cpp.
References llvm::MipsTargetStreamer::emitDirectiveAbiCalls(), llvm::MipsTargetStreamer::emitDirectiveModuleFP(), llvm::MipsTargetStreamer::emitDirectiveModuleOddSPReg(), llvm::MipsTargetStreamer::emitDirectiveNaN2008(), llvm::MipsTargetStreamer::emitDirectiveNaNLegacy(), llvm::MipsTargetStreamer::emitDirectiveOptionPic0(), llvm::FS, llvm::MipsTargetMachine::getABI(), getCurrentABIString(), llvm::MCContext::getELFSection(), llvm::TargetMachine::getRelocationModel(), llvm::TargetMachine::getTargetCPU(), llvm::TargetMachine::getTargetFeatureString(), llvm::TargetMachine::getTargetTriple(), llvm::MipsSubtarget::isABICalls(), llvm::MipsABIInfo::IsEABI(), llvm::MipsTargetMachine::isLittleEndian(), llvm::MipsABIInfo::IsN64(), llvm::MipsABIInfo::IsO32(), llvm::AsmPrinter::OutContext, llvm::NVPTX::PTXCvtMode::RM, llvm::MIPS_MC::selectMipsCPU(), llvm::ELF::SHT_PROGBITS, llvm::Reloc::Static, llvm::MCStreamer::SwitchSection(), llvm::AsmPrinter::TM, and llvm::MipsTargetStreamer::updateABIInfo().
const char * MipsAsmPrinter::getCurrentABIString () const
Emit Set directives.
Definition at line 311 of file MipsAsmPrinter.cpp.
References llvm_unreachable, and llvm::AsmPrinter::TM.
Referenced by EmitStartOfAsmFile().
const char* llvm::MipsAsmPrinter::getPassName () const [inline, override, virtual]
getPassName - Return a nice clean name for a pass.
This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 106 of file MipsAsmPrinter.h.
bool MipsAsmPrinter::isBlockOnlyReachableByFallthrough (const MachineBasicBlock * MBB) const [override, virtual]
isBlockOnlyReachableByFallthough - Return true if the basic block has exactly one predecessor and the control transfer mechanism between the predecessor and this block is a fall-through.
Reimplemented from llvm::AsmPrinter.
Definition at line 395 of file MipsAsmPrinter.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::empty(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getBasicBlock(), I, llvm::MachineBasicBlock::isLandingPad(), llvm::MachineBasicBlock::isLayoutSuccessor(), llvm::MachineBasicBlock::pred_begin(), llvm::MachineBasicBlock::pred_empty(), and llvm::MachineBasicBlock::pred_end().
bool MipsAsmPrinter::PrintAsmMemoryOperand (const MachineInstr * MI, unsigned OpNo, unsigned AsmVariant, const char * ExtraCode, raw_ostream & OS) [override, virtual]
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address.
Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Reimplemented from llvm::AsmPrinter.
Definition at line 534 of file MipsAsmPrinter.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MipsInstPrinter::getRegisterName(), and llvm::MachineOperand::isImm().
bool MipsAsmPrinter::PrintAsmOperand (const MachineInstr * MI, unsigned OpNo, unsigned AsmVariant, const char * ExtraCode, raw_ostream & O) [override, virtual]
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
PrintAsmOperand - Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Targets should override this to format as appropriate.
Reimplemented from llvm::AsmPrinter.
Definition at line 435 of file MipsAsmPrinter.cpp.
References llvm::MachineOperand::getImm(), llvm::InlineAsm::getNumOperandRegisters(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MipsInstPrinter::getRegisterName(), llvm::MachineOperand::getType(), llvm::MipsSubtarget::isGP64bit(), llvm::MachineOperand::isImm(), llvm::MipsSubtarget::isLittle(), llvm::MachineOperand::isReg(), llvm::MachineOperand::MO_Immediate, printOperand(), Subtarget, and llvm::utohexstr().
void MipsAsmPrinter::PrintDebugValueComment (const MachineInstr * MI, raw_ostream & OS)
Definition at line 1056 of file MipsAsmPrinter.cpp.
Referenced by EmitInstruction().
void MipsAsmPrinter::printFCCOperand (const MachineInstr * MI, int opNum, raw_ostream & O, const char * Modifier = nullptr)
Definition at line 676 of file MipsAsmPrinter.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), and llvm::Mips::MipsFCCToString().
void MipsAsmPrinter::printMemOperand (const MachineInstr * MI, int opNum, raw_ostream & O)
Definition at line 643 of file MipsAsmPrinter.cpp.
References llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), and printOperand().
void MipsAsmPrinter::printMemOperandEA (const MachineInstr * MI, int opNum, raw_ostream & O)
Definition at line 666 of file MipsAsmPrinter.cpp.
References printOperand().
void MipsAsmPrinter::printOperand (const MachineInstr * MI, int opNum, raw_ostream & O)
Definition at line 560 of file MipsAsmPrinter.cpp.
References llvm::DL, llvm::MachineOperand::getBlockAddress(), llvm::AsmPrinter::GetBlockAddressSymbol(), llvm::TargetMachine::getDataLayout(), llvm::AsmPrinter::getFunctionNumber(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineOperand::getMBB(), llvm::MCSymbol::getName(), llvm::MachineOperand::getOffset(), llvm::MachineInstr::getOperand(), llvm::DataLayout::getPrivateGlobalPrefix(), llvm::MachineOperand::getReg(), llvm::MipsInstPrinter::getRegisterName(), llvm::AsmPrinter::getSymbol(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getTargetFlags(), llvm::MachineOperand::getType(), llvm_unreachable, llvm::StringRef::lower(), llvm::AsmPrinter::MAI, llvm::MipsII::MO_ABS_HI, llvm::MipsII::MO_ABS_LO, llvm::MachineOperand::MO_BlockAddress, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_GlobalAddress, llvm::MipsII::MO_GOT, llvm::MipsII::MO_GOT_CALL, llvm::MipsII::MO_GOT_DISP, llvm::MipsII::MO_GOT_OFST, llvm::MipsII::MO_GOT_PAGE, llvm::MipsII::MO_GOTTPREL, llvm::MipsII::MO_GPOFF_HI, llvm::MipsII::MO_GPOFF_LO, llvm::MipsII::MO_GPREL, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_Register, llvm::MipsII::MO_TLSGD, llvm::MipsII::MO_TPREL_HI, llvm::MipsII::MO_TPREL_LO, llvm::Pass::print(), llvm::MCSymbol::print(), and llvm::AsmPrinter::TM.
Referenced by PrintAsmOperand(), printMemOperand(), printMemOperandEA(), printRegisterList(), printUnsignedImm(), and printUnsignedImm8().
void MipsAsmPrinter::printRegisterList (const MachineInstr * MI, int opNum, raw_ostream & O)
Definition at line 683 of file MipsAsmPrinter.cpp.
References llvm::MachineInstr::getNumOperands(), and printOperand().
void MipsAsmPrinter::printSavedRegsBitmask ()
Definition at line 247 of file MipsAsmPrinter.cpp.
References contains(), llvm::MipsTargetStreamer::emitFMask(), llvm::MipsTargetStreamer::emitMask(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MCRegisterInfo::getEncodingValue(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), I, llvm::AsmPrinter::MF, and fuzzer::TS.
Referenced by EmitFunctionBodyStart().
void MipsAsmPrinter::printUnsignedImm (const MachineInstr * MI, int opNum, raw_ostream & O)
Definition at line 624 of file MipsAsmPrinter.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::isImm(), and printOperand().
void MipsAsmPrinter::printUnsignedImm8 (const MachineInstr * MI, int opNum, raw_ostream & O)
Definition at line 633 of file MipsAsmPrinter.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::isImm(), and printOperand().
bool MipsAsmPrinter::runOnMachineFunction (MachineFunction & MF) [override, virtual]
Emit the specified function out to the OutStreamer.
Reimplemented from llvm::AsmPrinter.
Definition at line 60 of file MipsAsmPrinter.cpp.
References llvm::MachineFunction::getConstantPool(), llvm::MachineFunction::getInfo(), llvm::AsmPrinter::getObjFileLowering(), llvm::MachineFunction::getSubtarget(), llvm::MipsSubtarget::inMips16Mode(), llvm::MipsSubtarget::isTargetNaCl(), MipsFI, llvm::AsmPrinter::OutContext, llvm::MipsFunctionInfo::StubsNeeded, Subtarget, llvm::ARMBuildAttrs::Symbol, and llvm::AsmPrinter::TM.
Member Data Documentation
MipsMCInstLower llvm::MipsAsmPrinter::MCInstLowering
Definition at line 99 of file MipsAsmPrinter.h.
Referenced by EmitFunctionBodyStart(), and EmitInstruction().
const MipsFunctionInfo* llvm::MipsAsmPrinter::MipsFI
Definition at line 98 of file MipsAsmPrinter.h.
Referenced by runOnMachineFunction().
const MipsSubtarget* llvm::MipsAsmPrinter::Subtarget
Definition at line 97 of file MipsAsmPrinter.h.
Referenced by EmitFunctionBodyEnd(), EmitFunctionBodyStart(), EmitFunctionEntryLabel(), EmitInstruction(), PrintAsmOperand(), and runOnMachineFunction().
The documentation for this class was generated from the following files:
MipsAsmPrinter.h
MipsAsmPrinter.cpp