LLVM: llvm::TargetLibraryInfoWrapperPass Class Reference
llvm::TargetLibraryInfoWrapperPass Class Reference
#include <TargetLibraryInfo.h>
Public Member Functions
TargetLibraryInfoWrapperPass ()
TargetLibraryInfoWrapperPass (const Triple &T)
TargetLibraryInfoWrapperPass (const TargetLibraryInfoImpl &TLI)
TargetLibraryInfo & getTLI ()
const TargetLibraryInfo & getTLI () const
Static Public Attributes
static char ID
Detailed Description
Definition at line 310 of file TargetLibraryInfo.h.
Constructor & Destructor Documentation
TargetLibraryInfoWrapperPass::TargetLibraryInfoWrapperPass ()
Definition at line 580 of file TargetLibraryInfo.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeTargetLibraryInfoWrapperPassPass().
TargetLibraryInfoWrapperPass::TargetLibraryInfoWrapperPass (const Triple & T) [explicit]
Definition at line 585 of file TargetLibraryInfo.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeTargetLibraryInfoWrapperPassPass().
TargetLibraryInfoWrapperPass::TargetLibraryInfoWrapperPass (const TargetLibraryInfoImpl & TLI) [explicit]
Definition at line 590 of file TargetLibraryInfo.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeTargetLibraryInfoWrapperPassPass().
Member Function Documentation
TargetLibraryInfo& llvm::TargetLibraryInfoWrapperPass::getTLI () [inline]
Definition at line 322 of file TargetLibraryInfo.h.
const TargetLibraryInfo& llvm::TargetLibraryInfoWrapperPass::getTLI () const [inline]
Definition at line 323 of file TargetLibraryInfo.h.
Member Data Documentation
char llvm::TargetLibraryInfoWrapperPass::ID [static]
Definition at line 317 of file TargetLibraryInfo.h.
The documentation for this class was generated from the following files:
TargetLibraryInfo.h
TargetLibraryInfo.cpp