LLVM: llvm::PPCTTIImpl Class Reference
llvm::PPCTTIImpl Class Reference
#include <PPCTargetTransformInfo.h>
Public Member Functions
PPCTTIImpl (const PPCTargetMachine *TM, Function &F)
PPCTTIImpl (const PPCTTIImpl &Arg)
PPCTTIImpl (PPCTTIImpl &&Arg)
PPCTTIImpl & operator= (const PPCTTIImpl &RHS)
PPCTTIImpl & operator= (PPCTTIImpl &&RHS)
Scalar TTI Implementations
unsigned getIntImmCost (const APInt &Imm, Type *Ty)
unsigned getIntImmCost (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty)
unsigned getIntImmCost (Intrinsic::ID IID, unsigned Idx, const APInt &Imm, Type *Ty)
TTI::PopcntSupportKind getPopcntSupport (unsigned TyWidth)
void getUnrollingPreferences (Loop *L, TTI::UnrollingPreferences &UP)
Vector TTI Implementations
bool enableAggressiveInterleaving (bool LoopHasReductions)
unsigned getNumberOfRegisters (bool Vector)
unsigned getRegisterBitWidth (bool Vector)
unsigned getMaxInterleaveFactor (unsigned VF)
unsigned getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::OperandValueKind Opd1Info=TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info=TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo=TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo=TTI::OP_None)
unsigned getShuffleCost (TTI::ShuffleKind Kind, Type *Tp, int Index, Type *SubTp)
unsigned getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src)
unsigned getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy)
unsigned getVectorInstrCost (unsigned Opcode, Type *Val, unsigned Index)
unsigned getMemoryOpCost (unsigned Opcode, Type *Src, unsigned Alignment, unsigned AddressSpace)
Detailed Description
Definition at line 28 of file PPCTargetTransformInfo.h.
Constructor & Destructor Documentation
llvm::PPCTTIImpl::PPCTTIImpl (const PPCTargetMachine * TM, Function & F) [inline, explicit]
Definition at line 40 of file PPCTargetTransformInfo.h.
llvm::PPCTTIImpl::PPCTTIImpl (const PPCTTIImpl & Arg) [inline]
Definition at line 44 of file PPCTargetTransformInfo.h.
llvm::PPCTTIImpl::PPCTTIImpl (PPCTTIImpl && Arg) [inline]
Definition at line 46 of file PPCTargetTransformInfo.h.
Member Function Documentation
bool PPCTTIImpl::enableAggressiveInterleaving (bool LoopHasReductions)
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 199 of file PPCTargetTransformInfo.cpp.
unsigned PPCTTIImpl::getArithmeticInstrCost (unsigned Opcode, Type * Ty, TTI::OperandValueKind Opd1Info = TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info = TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo = TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo = TTI::OP_None)
Reimplemented from llvm::BasicTTIImplBase< PPCTTIImpl >.
Definition at line 249 of file PPCTargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< PPCTTIImpl >::getArithmeticInstrCost(), and llvm::TargetLoweringBase::InstructionOpcodeToISD().
unsigned PPCTTIImpl::getCastInstrCost (unsigned Opcode, Type * Dst, Type * Src)
Reimplemented from llvm::BasicTTIImplBase< PPCTTIImpl >.
Definition at line 265 of file PPCTargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< PPCTTIImpl >::getCastInstrCost(), and llvm::TargetLoweringBase::InstructionOpcodeToISD().
unsigned PPCTTIImpl::getCmpSelInstrCost (unsigned Opcode, Type * ValTy, Type * CondTy)
Reimplemented from llvm::BasicTTIImplBase< PPCTTIImpl >.
Definition at line 271 of file PPCTargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< PPCTTIImpl >::getCmpSelInstrCost().
unsigned PPCTTIImpl::getIntImmCost (const APInt & Imm, Type * Ty)
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 38 of file PPCTargetTransformInfo.cpp.
References DisablePPCConstHoist, llvm::APInt::getBitWidth(), llvm::TargetTransformInfoImplBase::getIntImmCost(), llvm::Type::getPrimitiveSizeInBits(), llvm::APInt::getSExtValue(), llvm::APInt::getZExtValue(), llvm::isInt< 16 >(), llvm::isInt< 32 >(), llvm::Type::isIntegerTy(), llvm::TargetTransformInfo::TCC_Basic, and llvm::TargetTransformInfo::TCC_Free.
Referenced by getIntImmCost().
unsigned PPCTTIImpl::getIntImmCost (unsigned Opcode, unsigned Idx, const APInt & Imm, Type * Ty)
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 101 of file PPCTargetTransformInfo.cpp.
References llvm::APIntOps::And(), llvm::Call, DisablePPCConstHoist, llvm::APInt::getBitWidth(), getIntImmCost(), llvm::TargetTransformInfoImplBase::getIntImmCost(), llvm::Type::getPrimitiveSizeInBits(), llvm::APInt::getSExtValue(), llvm::APInt::getZExtValue(), llvm::isInt< 16 >(), llvm::Type::isIntegerTy(), llvm::PPCSubtarget::isPPC64(), llvm::isShiftedMask_32(), llvm::isShiftedMask_64(), llvm::isUInt< 16 >(), llvm::SPII::Load, llvm::LShr, llvm::APIntOps::Or(), llvm::TargetOpcode::PHI, llvm::MipsISD::Ret, llvm::MCID::Select, llvm::SPII::Store, llvm::TargetTransformInfo::TCC_Basic, llvm::TargetTransformInfo::TCC_Free, and llvm::APIntOps::Xor().
unsigned PPCTTIImpl::getIntImmCost (Intrinsic::ID IID, unsigned Idx, const APInt & Imm, Type * Ty)
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 67 of file PPCTargetTransformInfo.cpp.
References DisablePPCConstHoist, llvm::APInt::getBitWidth(), getIntImmCost(), llvm::TargetTransformInfoImplBase::getIntImmCost(), llvm::Type::getPrimitiveSizeInBits(), llvm::APInt::getSExtValue(), llvm::isInt< 16 >(), llvm::Type::isIntegerTy(), and llvm::TargetTransformInfo::TCC_Free.
unsigned PPCTTIImpl::getMaxInterleaveFactor (unsigned VF)
Reimplemented from llvm::BasicTTIImplBase< PPCTTIImpl >.
Definition at line 222 of file PPCTargetTransformInfo.cpp.
References llvm::PPC::DIR_440, llvm::PPC::DIR_A2, llvm::PPC::DIR_E500mc, llvm::PPC::DIR_E5500, llvm::PPC::DIR_PWR7, llvm::PPC::DIR_PWR8, and llvm::PPCSubtarget::getDarwinDirective().
unsigned PPCTTIImpl::getMemoryOpCost (unsigned Opcode, Type * Src, unsigned Alignment, unsigned AddressSpace)
Reimplemented from llvm::BasicTTIImplBase< PPCTTIImpl >.
Definition at line 316 of file PPCTargetTransformInfo.cpp.
References ExtractElement(), llvm::BasicTTIImplBase< PPCTTIImpl >::getMemoryOpCost(), llvm::Type::getPrimitiveSizeInBits(), llvm::TargetLoweringBase::getTypeLegalizationCost(), getVectorInstrCost(), llvm::Type::getVectorNumElements(), llvm::PPCSubtarget::hasVSX(), llvm::Type::isVectorTy(), llvm::SPII::Load, llvm::AArch64CC::LT, llvm::SPII::Store, llvm::MVT::v2f64, and llvm::MVT::v2i64.
unsigned PPCTTIImpl::getNumberOfRegisters (bool Vector)
Reimplemented from llvm::BasicTTIImplBase< PPCTTIImpl >.
Definition at line 203 of file PPCTargetTransformInfo.cpp.
References llvm::PPCSubtarget::hasAltivec(), llvm::PPCSubtarget::hasQPX(), and llvm::PPCSubtarget::hasVSX().
TargetTransformInfo::PopcntSupportKind PPCTTIImpl::getPopcntSupport (unsigned TyWidth)
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 31 of file PPCTargetTransformInfo.cpp.
References llvm::PPCSubtarget::hasPOPCNTD(), llvm::isPowerOf2_32(), llvm::TargetTransformInfo::PSK_FastHardware, and llvm::TargetTransformInfo::PSK_Software.
unsigned PPCTTIImpl::getRegisterBitWidth (bool Vector)
Reimplemented from llvm::BasicTTIImplBase< PPCTTIImpl >.
Definition at line 209 of file PPCTargetTransformInfo.cpp.
References llvm::PPCSubtarget::hasAltivec(), llvm::PPCSubtarget::hasQPX(), and llvm::PPCSubtarget::isPPC64().
unsigned PPCTTIImpl::getShuffleCost (TTI::ShuffleKind Kind, Type * Tp, int Index, Type * SubTp)
Reimplemented from llvm::BasicTTIImplBase< PPCTTIImpl >.
Definition at line 260 of file PPCTargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< PPCTTIImpl >::getShuffleCost().
void PPCTTIImpl::getUnrollingPreferences (Loop * L, TTI::UnrollingPreferences & UP)
Reimplemented from llvm::BasicTTIImplBase< PPCTTIImpl >.
Definition at line 184 of file PPCTargetTransformInfo.cpp.
References llvm::TargetTransformInfo::UnrollingPreferences::AllowExpensiveTripCount, llvm::PPC::DIR_A2, llvm::PPCSubtarget::getDarwinDirective(), llvm::BasicTTIImplBase< PPCTTIImpl >::getUnrollingPreferences(), llvm::TargetTransformInfo::UnrollingPreferences::Partial, and llvm::TargetTransformInfo::UnrollingPreferences::Runtime.
unsigned PPCTTIImpl::getVectorInstrCost (unsigned Opcode, Type * Val, unsigned Index)
Reimplemented from llvm::BasicTTIImplBase< PPCTTIImpl >.
Definition at line 276 of file PPCTargetTransformInfo.cpp.
References llvm::ISD::EXTRACT_VECTOR_ELT, llvm::Type::getScalarType(), llvm::BasicTTIImplBase< PPCTTIImpl >::getVectorInstrCost(), llvm::PPCSubtarget::hasQPX(), llvm::PPCSubtarget::hasVSX(), llvm::ISD::INSERT_VECTOR_ELT, llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::Type::isDoubleTy(), llvm::Type::isFloatingPointTy(), and llvm::Type::isVectorTy().
Referenced by getMemoryOpCost().
PPCTTIImpl& llvm::PPCTTIImpl::operator= (const PPCTTIImpl & RHS) [inline]
Definition at line 49 of file PPCTargetTransformInfo.h.
References llvm::BasicTTIImplBase< PPCTTIImpl >::operator=().
PPCTTIImpl& llvm::PPCTTIImpl::operator= (PPCTTIImpl && RHS) [inline]
Definition at line 55 of file PPCTargetTransformInfo.h.
References llvm::BasicTTIImplBase< PPCTTIImpl >::operator=().
The documentation for this class was generated from the following files:
PPCTargetTransformInfo.h
PPCTargetTransformInfo.cpp