LLVM: llvm::GetElementPtrConstantExpr Class Reference
llvm::GetElementPtrConstantExpr Class Reference
GetElementPtrConstantExpr - This class is private to Constants.cpp, and is used behind the scenes to implement getelementpr constant exprs.
#include <ConstantsContext.h>
Public Member Functions
Type * getSourceElementType () const
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
Static Public Member Functions
static GetElementPtrConstantExpr * Create (Constant *C, ArrayRef< Constant * > IdxList, Type *DestTy, unsigned Flags)
static GetElementPtrConstantExpr * Create (Type *SrcElementTy, Constant *C, ArrayRef< Constant * > IdxList, Type *DestTy, unsigned Flags)
Detailed Description
GetElementPtrConstantExpr - This class is private to Constants.cpp, and is used behind the scenes to implement getelementpr constant exprs.
Definition at line 212 of file ConstantsContext.h.
Member Function Documentation
static GetElementPtrConstantExpr* llvm::GetElementPtrConstantExpr::Create (Constant * C, ArrayRef< Constant * > IdxList, Type * DestTy, unsigned Flags) [inline, static]
Definition at line 219 of file ConstantsContext.h.
References llvm::C, llvm::Type::getScalarType(), and llvm::Value::getType().
Referenced by llvm::ConstantExprKeyType::create().
static GetElementPtrConstantExpr* llvm::GetElementPtrConstantExpr::Create (Type * SrcElementTy, Constant * C, ArrayRef< Constant * > IdxList, Type * DestTy, unsigned Flags) [inline, static]
Definition at line 227 of file ConstantsContext.h.
References llvm::ArrayRef< T >::size(), and llvm::Value::SubclassOptionalData.
llvm::GetElementPtrConstantExpr::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
Type * GetElementPtrConstantExpr::getSourceElementType () const
Definition at line 2408 of file Constants.cpp.
The documentation for this class was generated from the following files:
ConstantsContext.h
Constants.cpp
LLVMContextImpl.cpp