LLVM: llvm::DbgDeclareInst Class Reference
llvm::DbgDeclareInst Class Reference
DbgDeclareInst - This represents the llvm.dbg.declare instruction.
#include <IntrinsicInst.h>
Public Member Functions
Value * getAddress () const
DbgDeclareInst - This represents the llvm.dbg.declare instruction.
DILocalVariable * getVariable () const
DIExpression * getExpression () const
Metadata * getRawVariable () const
Metadata * getRawExpression () const
Static Public Member Functions
static bool classof (const IntrinsicInst *I)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Detailed Description
DbgDeclareInst - This represents the llvm.dbg.declare instruction.
Definition at line 82 of file IntrinsicInst.h.
Member Function Documentation
static bool llvm::DbgDeclareInst::classof (const IntrinsicInst * I) [inline, static]
Reimplemented from llvm::DbgInfoIntrinsic.
Definition at line 100 of file IntrinsicInst.h.
References llvm::IntrinsicInst::getIntrinsicID().
Referenced by classof().
static bool llvm::DbgDeclareInst::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::DbgInfoIntrinsic.
Definition at line 103 of file IntrinsicInst.h.
References classof().
Value * DbgDeclareInst::getAddress () const
DbgDeclareInst - This represents the llvm.dbg.declare instruction.
Definition at line 66 of file IntrinsicInst.cpp.
References llvm::CallInst::getArgOperand(), and getValueImpl().
Referenced by llvm::LowerDbgDeclare(), and llvm::FastISel::selectIntrinsicCall().
DIExpression* llvm::DbgDeclareInst::getExpression () const [inline]
Definition at line 88 of file IntrinsicInst.h.
References getRawExpression().
Referenced by llvm::ConvertDebugDeclareToDebugValue(), llvm::LowerDbgDeclare(), llvm::replaceDbgDeclareForAlloca(), and llvm::FastISel::selectIntrinsicCall().
Metadata* llvm::DbgDeclareInst::getRawExpression () const [inline]
Definition at line 95 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperand(), and llvm::Instruction::getMetadata().
Referenced by getExpression().
Metadata* llvm::DbgDeclareInst::getRawVariable () const [inline]
Definition at line 92 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperand(), and llvm::Instruction::getMetadata().
Referenced by getVariable().
DILocalVariable* llvm::DbgDeclareInst::getVariable () const [inline]
Definition at line 85 of file IntrinsicInst.h.
References getRawVariable().
Referenced by llvm::ConvertDebugDeclareToDebugValue(), llvm::LowerDbgDeclare(), llvm::DebugInfoFinder::processDeclare(), llvm::replaceDbgDeclareForAlloca(), and llvm::FastISel::selectIntrinsicCall().
The documentation for this class was generated from the following files:
IntrinsicInst.h
IntrinsicInst.cpp