LLVM: llvm::df_iterator< GraphT, SetType, ExtStorage, GT > Class Template Reference
llvm::df_iterator< GraphT, SetType, ExtStorage, GT > Class Template Reference
#include <DepthFirstIterator.h>
Public Types
typedef super::pointer pointer
Public Member Functions
bool operator== (const df_iterator &x) const
bool operator!= (const df_iterator &x) const
pointer operator* () const
NodeType * operator-> () const
df_iterator & operator++ ()
df_iterator & skipChildren ()
Skips all children of the current node and traverses to next node.
df_iterator operator++ (int)
bool nodeVisited (NodeType *Node) const
unsigned getPathLength () const
getPathLength - Return the length of the path from the entry node to the current node, counting both nodes.
NodeType * getPath (unsigned n) const
getPath - Return the n'th node in the path from the entry node to the current node.
Static Public Member Functions
static df_iterator begin (const GraphT &G)
static df_iterator end (const GraphT &G)
static df_iterator begin (const GraphT &G, SetType &S)
static df_iterator end (const GraphT &G, SetType &S)
Detailed Description
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>>
class llvm::df_iterator< GraphT, SetType, ExtStorage, GT >
Definition at line 66 of file DepthFirstIterator.h.
Member Typedef Documentation
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> typedef super::pointer llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::pointer
Reimplemented in llvm::RegionBase< Tr >::block_iterator_wrapper< IsConst >.
Definition at line 130 of file DepthFirstIterator.h.
Member Function Documentation
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> static df_iterator llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::begin (const GraphT & G) [inline, static]
Definition at line 133 of file DepthFirstIterator.h.
Referenced by llvm::df_begin().
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> static df_iterator llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::begin (const GraphT & G, SetType & S) [inline, static]
Definition at line 139 of file DepthFirstIterator.h.
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> static df_iterator llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::end (const GraphT & G) [inline, static]
Definition at line 136 of file DepthFirstIterator.h.
Referenced by llvm::df_end().
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> static df_iterator llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::end (const GraphT & G, SetType & S) [inline, static]
Definition at line 142 of file DepthFirstIterator.h.
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> NodeType* llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::getPath (unsigned n) const [inline]
getPath - Return the n'th node in the path from the entry node to the current node.
Definition at line 193 of file DepthFirstIterator.h.
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> unsigned llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::getPathLength () const [inline]
getPathLength - Return the length of the path from the entry node to the current node, counting both nodes.
Definition at line 189 of file DepthFirstIterator.h.
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> bool llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::nodeVisited (NodeType * Node) const [inline]
Definition at line 183 of file DepthFirstIterator.h.
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> bool llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::operator!= (const df_iterator< GraphT, SetType, ExtStorage, GT > & x) const [inline]
Definition at line 147 of file DepthFirstIterator.h.
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> pointer llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::operator* () const [inline]
Reimplemented in llvm::RegionBase< Tr >::block_iterator_wrapper< IsConst >.
Definition at line 149 of file DepthFirstIterator.h.
Referenced by llvm::RegionBase< Tr >::block_iterator_wrapper< IsConst >::operator*().
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> df_iterator& llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::operator++ () [inline]
Definition at line 157 of file DepthFirstIterator.h.
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> df_iterator llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::operator++ (int) [inline]
Definition at line 173 of file DepthFirstIterator.h.
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> NodeType* llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::operator-> () const [inline]
Definition at line 155 of file DepthFirstIterator.h.
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> bool llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::operator== (const df_iterator< GraphT, SetType, ExtStorage, GT > & x) const [inline]
Definition at line 144 of file DepthFirstIterator.h.
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> df_iterator& llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::skipChildren () [inline]
Skips all children of the current node and traverses to next node.
Note: This function takes care of incrementing the iterator. If you always increment and call this function, you risk walking off the end.
Definition at line 166 of file DepthFirstIterator.h.
The documentation for this class was generated from the following file:
DepthFirstIterator.h