LLVM: llvm::PBQP::RegAlloc::PBQPRAGraph Class Reference
llvm::PBQP::RegAlloc::PBQPRAGraph Class Reference
#include <RegAllocPBQP.h>
Public Member Functions
PBQPRAGraph (GraphMetadata Metadata)
void dump () const
Dump this graph to dbgs().
void dump (raw_ostream &OS) const
Dump this graph to an output stream.
void printDot (raw_ostream &OS) const
Print a representation of this graph in DOT format.
Detailed Description
Definition at line 564 of file RegAllocPBQP.h.
Constructor & Destructor Documentation
llvm::PBQP::RegAlloc::PBQPRAGraph::PBQPRAGraph (GraphMetadata Metadata) [inline]
Definition at line 568 of file RegAllocPBQP.h.
Member Function Documentation
void PBQP::RegAlloc::PBQPRAGraph::dump () const
Dump this graph to dbgs().
Definition at line 857 of file RegAllocPBQP.cpp.
References llvm::dbgs(), and llvm::dump().
void PBQP::RegAlloc::PBQPRAGraph::dump (raw_ostream & OS) const
Dump this graph to an output stream.
Parameters:
OS Output stream to print on.
Definition at line 836 of file RegAllocPBQP.cpp.
References llvm::PBQP::Graph< RegAllocSolverImpl >::edgeIds(), llvm::PBQP::Graph< RegAllocSolverImpl >::getEdgeCosts(), llvm::PBQP::Graph< RegAllocSolverImpl >::getEdgeNode1Id(), llvm::PBQP::Graph< RegAllocSolverImpl >::getEdgeNode2Id(), llvm::PBQP::Graph< RegAllocSolverImpl >::getNodeCosts(), and llvm::PBQP::Graph< RegAllocSolverImpl >::nodeIds().
void PBQP::RegAlloc::PBQPRAGraph::printDot (raw_ostream & OS) const
Print a representation of this graph in DOT format.
Parameters:
OS Output stream to print on.
Definition at line 859 of file RegAllocPBQP.cpp.
The documentation for this class was generated from the following files:
RegAllocPBQP.h
RegAllocPBQP.cpp