LLVM: llvm::ContextAndReplaceableUses Class Reference
llvm::ContextAndReplaceableUses Class Reference
Pointer to the context, with optional RAUW support.
#include <Metadata.h>
Public Member Functions
ContextAndReplaceableUses (LLVMContext &Context)
ContextAndReplaceableUses (std::unique_ptr< ReplaceableMetadataImpl > ReplaceableUses)
~ContextAndReplaceableUses ()
operator LLVMContext & ()
bool hasReplaceableUses () const
Whether this contains RAUW support.
LLVMContext & getContext () const
ReplaceableMetadataImpl * getReplaceableUses () const
void makeReplaceable (std::unique_ptr< ReplaceableMetadataImpl > ReplaceableUses)
Assign RAUW support to this.
std::unique_ptr
< ReplaceableMetadataImpl > takeReplaceableUses ()
Drop RAUW support.
Detailed Description
Pointer to the context, with optional RAUW support.
Either a raw (non-null) pointer to the LLVMContext, or an owned pointer to ReplaceableMetadataImpl (which has a reference to LLVMContext).
Definition at line 642 of file Metadata.h.
Constructor & Destructor Documentation
llvm::ContextAndReplaceableUses::ContextAndReplaceableUses (LLVMContext & Context) [inline]
Definition at line 653 of file Metadata.h.
llvm::ContextAndReplaceableUses::ContextAndReplaceableUses (std::unique_ptr< ReplaceableMetadataImpl > ReplaceableUses) [inline]
Definition at line 654 of file Metadata.h.
References getReplaceableUses().
llvm::ContextAndReplaceableUses::~ContextAndReplaceableUses () [inline]
Definition at line 659 of file Metadata.h.
References getReplaceableUses().
Member Function Documentation
LLVMContext& llvm::ContextAndReplaceableUses::getContext () const [inline]
Definition at line 667 of file Metadata.h.
References llvm::PointerUnion< PT1, PT2 >::get(), llvm::ReplaceableMetadataImpl::getContext(), getReplaceableUses(), and hasReplaceableUses().
Referenced by llvm::MDNode::getContext(), makeReplaceable(), and operator LLVMContext &().
ReplaceableMetadataImpl* llvm::ContextAndReplaceableUses::getReplaceableUses () const [inline]
Definition at line 672 of file Metadata.h.
References llvm::PointerUnion< PT1, PT2 >::get(), and hasReplaceableUses().
Referenced by ContextAndReplaceableUses(), getContext(), makeReplaceable(), llvm::MDNode::replaceAllUsesWith(), takeReplaceableUses(), and ~ContextAndReplaceableUses().
bool llvm::ContextAndReplaceableUses::hasReplaceableUses () const [inline]
Whether this contains RAUW support.
Definition at line 664 of file Metadata.h.
References llvm::PointerUnion< PT1, PT2 >::is().
Referenced by getContext(), getReplaceableUses(), llvm::MDNode::isResolved(), and takeReplaceableUses().
void llvm::ContextAndReplaceableUses::makeReplaceable (std::unique_ptr< ReplaceableMetadataImpl > ReplaceableUses) [inline]
Assign RAUW support to this.
Make this replaceable, taking ownership of ReplaceableUses (which must not be null).
Definition at line 683 of file Metadata.h.
References getContext(), and getReplaceableUses().
llvm::ContextAndReplaceableUses::operator LLVMContext & () [inline]
Definition at line 661 of file Metadata.h.
References getContext().
std::unique_ptr<ReplaceableMetadataImpl> llvm::ContextAndReplaceableUses::takeReplaceableUses () [inline]
Drop RAUW support.
Cede ownership of RAUW support, returning it.
Definition at line 694 of file Metadata.h.
References getReplaceableUses(), and hasReplaceableUses().
The documentation for this class was generated from the following file:
Metadata.h