LLVM: llvm::JITSymbolBase Class Reference
llvm::JITSymbolBase Class Reference
Base class for symbols in the JIT.
#include <JITSymbolFlags.h>
Public Member Functions
JITSymbolBase (JITSymbolFlags Flags)
JITSymbolFlags getFlags () const
bool isWeak () const
bool isExported () const
Static Public Member Functions
static JITSymbolFlags flagsFromGlobalValue (const GlobalValue &GV)
Detailed Description
Base class for symbols in the JIT.
Definition at line 51 of file JITSymbolFlags.h.
Constructor & Destructor Documentation
llvm::JITSymbolBase::JITSymbolBase (JITSymbolFlags Flags) [inline]
Definition at line 53 of file JITSymbolFlags.h.
Member Function Documentation
static JITSymbolFlags llvm::JITSymbolBase::flagsFromGlobalValue (const GlobalValue & GV) [inline, static]
Definition at line 65 of file JITSymbolFlags.h.
References llvm::Exported, llvm::GlobalValue::hasHiddenVisibility(), llvm::GlobalValue::hasLocalLinkage(), llvm::GlobalValue::hasWeakLinkage(), llvm::None, and llvm::Weak.
JITSymbolFlags llvm::JITSymbolBase::getFlags () const [inline]
Definition at line 55 of file JITSymbolFlags.h.
bool llvm::JITSymbolBase::isExported () const [inline]
Definition at line 61 of file JITSymbolFlags.h.
References llvm::Exported.
bool llvm::JITSymbolBase::isWeak () const [inline]
Definition at line 57 of file JITSymbolFlags.h.
References llvm::Weak.
The documentation for this class was generated from the following file:
JITSymbolFlags.h