LLVM: llvm::DIELoc Class Reference
llvm::DIELoc Class Reference
DIELoc - Represents an expression location.
#include <DIE.h>
Public Member Functions
DIELoc ()
unsigned ComputeSize (const AsmPrinter *AP) const
ComputeSize - Calculate the size of the location expression.
dwarf::Form BestForm (unsigned DwarfVersion) const
BestForm - Choose the best form for data.
void EmitValue (const AsmPrinter *AP, dwarf::Form Form) const
EmitValue - Emit location data.
unsigned SizeOf (const AsmPrinter *AP, dwarf::Form Form) const
SizeOf - Determine size of location data in bytes.
void print (raw_ostream &O) const
Detailed Description
DIELoc - Represents an expression location.
Definition at line 572 of file DIE.h.
Constructor & Destructor Documentation
llvm::DIELoc::DIELoc () [inline]
Definition at line 576 of file DIE.h.
Member Function Documentation
dwarf::Form llvm::DIELoc::BestForm (unsigned DwarfVersion) const [inline]
BestForm - Choose the best form for data.
Definition at line 584 of file DIE.h.
References llvm::dwarf::DW_FORM_block, llvm::dwarf::DW_FORM_block1, llvm::dwarf::DW_FORM_block2, llvm::dwarf::DW_FORM_block4, and llvm::dwarf::DW_FORM_exprloc.
Referenced by llvm::DwarfUnit::addBlock().
unsigned DIELoc::ComputeSize (const AsmPrinter * AP) const
ComputeSize - Calculate the size of the location expression.
ComputeSize - calculate the size of the location expression.
Definition at line 508 of file DIE.cpp.
References SizeOf().
Referenced by llvm::DwarfUnit::addBlock().
void DIELoc::EmitValue (const AsmPrinter * AP, dwarf::Form Form) const
EmitValue - Emit location data.
Definition at line 519 of file DIE.cpp.
References llvm::dwarf::DW_FORM_block, llvm::dwarf::DW_FORM_block1, llvm::dwarf::DW_FORM_block2, llvm::dwarf::DW_FORM_block4, llvm::dwarf::DW_FORM_exprloc, llvm::AsmPrinter::EmitInt16(), llvm::AsmPrinter::EmitInt32(), llvm::AsmPrinter::EmitInt8(), llvm::AsmPrinter::EmitULEB128(), and llvm_unreachable.
void DIELoc::print (raw_ostream & O) const
Definition at line 549 of file DIE.cpp.
unsigned DIELoc::SizeOf (const AsmPrinter * AP, dwarf::Form Form) const
SizeOf - Determine size of location data in bytes.
Definition at line 536 of file DIE.cpp.
References llvm::dwarf::DW_FORM_block, llvm::dwarf::DW_FORM_block1, llvm::dwarf::DW_FORM_block2, llvm::dwarf::DW_FORM_block4, llvm::dwarf::DW_FORM_exprloc, llvm::getULEB128Size(), and llvm_unreachable.
Referenced by ComputeSize().
The documentation for this class was generated from the following files:
DIE.h
DIE.cpp