LLVM: llvm::AArch64InstPrinter Class Reference
llvm::AArch64InstPrinter Class Reference
#include <AArch64InstPrinter.h>
Public Member Functions
AArch64InstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printInst (const MCInst *MI, raw_ostream &O, StringRef Annot, const MCSubtargetInfo &STI) override
Print the specified MCInst to the specified raw_ostream.
void printRegName (raw_ostream &OS, unsigned RegNo) const override
Print the assembler register name.
virtual void printInstruction (const MCInst *MI, const MCSubtargetInfo &STI, raw_ostream &O)
virtual bool printAliasInstr (const MCInst *MI, const MCSubtargetInfo &STI, raw_ostream &O)
virtual void printCustomAliasOperand (const MCInst *MI, unsigned OpIdx, unsigned PrintMethodIdx, const MCSubtargetInfo &STI, raw_ostream &O)
virtual StringRef getRegName (unsigned RegNo) const
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo, unsigned AltIdx=AArch64::NoRegAltName)
Protected Member Functions
bool printSysAlias (const MCInst *MI, raw_ostream &O)
void printOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printHexImm (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printPostIncOperand (const MCInst *MI, unsigned OpNo, unsigned Imm, raw_ostream &O)
template<int Amount>
void printPostIncOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printVRegOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printSysCROperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printAddSubImm (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printLogicalImm32 (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printLogicalImm64 (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printShifter (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printShiftedRegister (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printExtendedRegister (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printArithExtend (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printMemExtend (const MCInst *MI, unsigned OpNum, raw_ostream &O, char SrcRegKind, unsigned Width)
template<char SrcRegKind, unsigned Width>
void printMemExtend (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printCondCode (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printInverseCondCode (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printAlignedLabel (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printUImm12Offset (const MCInst *MI, unsigned OpNum, unsigned Scale, raw_ostream &O)
void printAMIndexedWB (const MCInst *MI, unsigned OpNum, unsigned Scale, raw_ostream &O)
template<int Scale>
void printUImm12Offset (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
template<int BitWidth>
void printAMIndexedWB (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printAMNoIndex (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
template<int Scale>
void printImmScale (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printPrefetchOp (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printFPImmOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printVectorList (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O, StringRef LayoutSuffix)
void printImplicitlyTypedVectorList (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
Print a list of vector registers where the type suffix is implicit (i.e.
template<unsigned NumLanes, char LaneKind>
void printTypedVectorList (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printVectorIndex (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printAdrpLabel (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printBarrierOption (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printMSRSystemRegister (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printMRSSystemRegister (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printSystemPStateField (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printSIMDType10Operand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
template<unsigned size>
void printGPRSeqPairsClassOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
Detailed Description
Definition at line 26 of file AArch64InstPrinter.h.
Constructor & Destructor Documentation
AArch64InstPrinter::AArch64InstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI)
Definition at line 35 of file AArch64InstPrinter.cpp.
Member Function Documentation
static const char* llvm::AArch64InstPrinter::getRegisterName (unsigned RegNo, unsigned AltIdx = AArch64::NoRegAltName) [static]
Reimplemented in llvm::AArch64AppleInstPrinter.
Referenced by getRegName(), printAMIndexedWB(), printAMNoIndex(), printExtendedRegister(), printGPRSeqPairsClassOperand(), printInst(), printOperand(), printPostIncOperand(), printRegName(), printShiftedRegister(), printSysAlias(), printVectorList(), and printVRegOperand().
virtual StringRef llvm::AArch64InstPrinter::getRegName (unsigned RegNo) const [inline, virtual]
Reimplemented in llvm::AArch64AppleInstPrinter.
Definition at line 44 of file AArch64InstPrinter.h.
References getRegisterName().
void AArch64InstPrinter::printAddSubImm (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 952 of file AArch64InstPrinter.cpp.
References llvm::MCInstPrinter::CommentStream, llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::AArch64_AM::getShiftValue(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCInstPrinter::MAI, llvm::MCExpr::print(), and printShifter().
void AArch64InstPrinter::printAdrpLabel (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 1294 of file AArch64InstPrinter.cpp.
References llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isImm(), llvm::MCInstPrinter::MAI, and llvm::MCExpr::print().
virtual bool llvm::AArch64InstPrinter::printAliasInstr (const MCInst * MI, const MCSubtargetInfo & STI, raw_ostream & O) [virtual]
Reimplemented in llvm::AArch64AppleInstPrinter.
Referenced by printInst().
void AArch64InstPrinter::printAlignedLabel (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 1269 of file AArch64InstPrinter.cpp.
References llvm::dwarf::syntax::Address, llvm::dyn_cast(), llvm::MCExpr::evaluateAsAbsolute(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isImm(), llvm::MCInstPrinter::MAI, llvm::MCExpr::print(), and llvm::raw_ostream::write_hex().
void AArch64InstPrinter::printAMIndexedWB (const MCInst * MI, unsigned OpNum, unsigned Scale, raw_ostream & O) [protected]
Definition at line 1098 of file AArch64InstPrinter.cpp.
References llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCInstPrinter::MAI, and llvm::MCExpr::print().
Referenced by printAMIndexedWB().
template<int BitWidth> void llvm::AArch64InstPrinter::printAMIndexedWB (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [inline, protected]
Definition at line 110 of file AArch64InstPrinter.h.
References printAMIndexedWB().
void AArch64InstPrinter::printAMNoIndex (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 1074 of file AArch64InstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), and getRegisterName().
void AArch64InstPrinter::printArithExtend (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 1016 of file AArch64InstPrinter.cpp.
References llvm::AArch64_AM::getArithExtendType(), llvm::AArch64_AM::getArithShiftValue(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::AArch64_AM::getShiftExtendName(), llvm::SP, llvm::AArch64_AM::UXTW, and llvm::AArch64_AM::UXTX.
Referenced by printExtendedRegister().
void AArch64InstPrinter::printBarrierOption (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 1310 of file AArch64InstPrinter.cpp.
References llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCOperand::getImm(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), and llvm::AArch64NamedImmMapper::toString().
void AArch64InstPrinter::printCondCode (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 1060 of file AArch64InstPrinter.cpp.
References llvm::AArch64CC::getCondCodeName(), llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
virtual void llvm::AArch64InstPrinter::printCustomAliasOperand (const MCInst * MI, unsigned OpIdx, unsigned PrintMethodIdx, const MCSubtargetInfo & STI, raw_ostream & O) [virtual]
Reimplemented in llvm::AArch64AppleInstPrinter.
void AArch64InstPrinter::printExtendedRegister (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 1009 of file AArch64InstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), and printArithExtend().
void AArch64InstPrinter::printFPImmOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 1125 of file AArch64InstPrinter.cpp.
References llvm::format(), llvm::MCOperand::getFPImm(), llvm::AArch64_AM::getFPImmFloat(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::MCOperand::isFPImm().
template<unsigned size> void AArch64InstPrinter::printGPRSeqPairsClassOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 1182 of file AArch64InstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), llvm::MCRegisterInfo::getSubReg(), llvm::MCInstPrinter::MRI, size, and llvm::static_assert().
void AArch64InstPrinter::printHexImm (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 915 of file AArch64InstPrinter.cpp.
References llvm::format(), llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
template<int Scale> void AArch64InstPrinter::printImmScale (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 1081 of file AArch64InstPrinter.cpp.
References llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
void AArch64InstPrinter::printImplicitlyTypedVectorList (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Print a list of vector registers where the type suffix is implicit (i.e.
attached to the instruction rather than the registers).
Definition at line 1243 of file AArch64InstPrinter.cpp.
References printVectorList().
void AArch64InstPrinter::printInst (const MCInst * MI, raw_ostream & OS, StringRef Annot, const MCSubtargetInfo & STI) [override, virtual]
Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Reimplemented in llvm::AArch64AppleInstPrinter.
Definition at line 50 of file AArch64InstPrinter.cpp.
References llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), llvm::getWRegFromXReg(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCInstPrinter::MAI, llvm::MCExpr::print(), printAliasInstr(), llvm::MCInstPrinter::printAnnotation(), printInstruction(), and printSysAlias().
virtual void llvm::AArch64InstPrinter::printInstruction (const MCInst * MI, const MCSubtargetInfo & STI, raw_ostream & O) [virtual]
Reimplemented in llvm::AArch64AppleInstPrinter.
Referenced by printInst().
void AArch64InstPrinter::printInverseCondCode (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 1067 of file AArch64InstPrinter.cpp.
References llvm::AArch64CC::getCondCodeName(), llvm::MCOperand::getImm(), llvm::AArch64CC::getInvertedCondCode(), and llvm::MCInst::getOperand().
void AArch64InstPrinter::printLogicalImm32 (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 974 of file AArch64InstPrinter.cpp.
References llvm::AArch64_AM::decodeLogicalImmediate(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::raw_ostream::write_hex().
void AArch64InstPrinter::printLogicalImm64 (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 982 of file AArch64InstPrinter.cpp.
References llvm::AArch64_AM::decodeLogicalImmediate(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::raw_ostream::write_hex().
void AArch64InstPrinter::printMemExtend (const MCInst * MI, unsigned OpNum, raw_ostream & O, char SrcRegKind, unsigned Width) [protected]
Definition at line 1043 of file AArch64InstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::Log2_32().
Referenced by printMemExtend().
template<char SrcRegKind, unsigned Width> void llvm::AArch64InstPrinter::printMemExtend (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [inline, protected]
Definition at line 87 of file AArch64InstPrinter.h.
References printMemExtend().
void AArch64InstPrinter::printMRSSystemRegister (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 1330 of file AArch64InstPrinter.cpp.
References llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::StringRef::upper().
void AArch64InstPrinter::printMSRSystemRegister (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 1341 of file AArch64InstPrinter.cpp.
References llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::StringRef::upper().
void AArch64InstPrinter::printOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 900 of file AArch64InstPrinter.cpp.
References llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm::MCInstPrinter::MAI, and llvm::MCExpr::print().
void AArch64InstPrinter::printPostIncOperand (const MCInst * MI, unsigned OpNo, unsigned Imm, raw_ostream & O) [protected]
Definition at line 922 of file AArch64InstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), llvm::MCOperand::isReg(), and llvm_unreachable.
Referenced by printPostIncOperand().
template<int Amount> void llvm::AArch64InstPrinter::printPostIncOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) [inline, protected]
Definition at line 60 of file AArch64InstPrinter.h.
References printPostIncOperand().
void AArch64InstPrinter::printPrefetchOp (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 1112 of file AArch64InstPrinter.cpp.
References llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::AArch64NamedImmMapper::toString().
void AArch64InstPrinter::printRegName (raw_ostream & OS, unsigned RegNo) const [override, virtual]
Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 45 of file AArch64InstPrinter.cpp.
References getRegisterName().
void AArch64InstPrinter::printShiftedRegister (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 1002 of file AArch64InstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), and printShifter().
void AArch64InstPrinter::printShifter (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 990 of file AArch64InstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::AArch64_AM::getShiftExtendName(), llvm::AArch64_AM::getShiftType(), llvm::AArch64_AM::getShiftValue(), and llvm::AArch64_AM::LSL.
Referenced by printAddSubImm(), and printShiftedRegister().
void AArch64InstPrinter::printSIMDType10Operand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 1366 of file AArch64InstPrinter.cpp.
References llvm::AArch64_AM::decodeAdvSIMDModImmType10(), llvm::format(), llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
bool AArch64InstPrinter::printSysAlias (const MCInst * MI, raw_ostream & O) [protected]
Definition at line 677 of file AArch64InstPrinter.cpp.
References llvm::HexStyle::Asm, llvm::MCOperand::getImm(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), and llvm::StringRef::npos.
Referenced by printInst().
void AArch64InstPrinter::printSysCROperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 944 of file AArch64InstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::MCOperand::isImm().
void AArch64InstPrinter::printSystemPStateField (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 1352 of file AArch64InstPrinter.cpp.
References llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::AArch64NamedImmMapper::toString(), and llvm::StringRef::upper().
template<unsigned NumLanes, char LaneKind> void AArch64InstPrinter::printTypedVectorList (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 1251 of file AArch64InstPrinter.cpp.
References llvm::itostr(), and printVectorList().
void AArch64InstPrinter::printUImm12Offset (const MCInst * MI, unsigned OpNum, unsigned Scale, raw_ostream & O) [protected]
Definition at line 1087 of file AArch64InstPrinter.cpp.
References llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCInstPrinter::MAI, and llvm::MCExpr::print().
Referenced by printUImm12Offset().
template<int Scale> void llvm::AArch64InstPrinter::printUImm12Offset (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [inline, protected]
Definition at line 104 of file AArch64InstPrinter.h.
References printUImm12Offset().
void AArch64InstPrinter::printVectorIndex (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 1263 of file AArch64InstPrinter.cpp.
References llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
void AArch64InstPrinter::printVectorList (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O, StringRef LayoutSuffix) [protected]
Definition at line 1198 of file AArch64InstPrinter.cpp.
References llvm::MCRegisterClass::contains(), llvm::MCRegisterInfo::getMatchingSuperReg(), getNextVectorRegister(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCRegisterInfo::getRegClass(), getRegisterName(), llvm::MCRegisterInfo::getSubReg(), and llvm::MCInstPrinter::MRI.
Referenced by printImplicitlyTypedVectorList(), llvm::AArch64AppleInstPrinter::printInst(), and printTypedVectorList().
void AArch64InstPrinter::printVRegOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) [protected]
Definition at line 935 of file AArch64InstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), and llvm::MCOperand::isReg().
The documentation for this class was generated from the following files:
AArch64InstPrinter.h
AArch64InstPrinter.cpp