LLVM: llvm::MachineSDNode Class Reference
llvm::MachineSDNode Class Reference
An SDNode that represents everything that will be needed to construct a MachineInstr.
#include <SelectionDAGNodes.h>
Public Types
typedef MachineMemOperand ** mmo_iterator
Public Member Functions
mmo_iterator memoperands_begin () const
mmo_iterator memoperands_end () const
bool memoperands_empty () const
void setMemRefs (mmo_iterator NewMemRefs, mmo_iterator NewMemRefsEnd)
Assign this MachineSDNodes's memory reference descriptor list.
Static Public Member Functions
static bool classof (const SDNode *N)
Friends
class SelectionDAG
Detailed Description
An SDNode that represents everything that will be needed to construct a MachineInstr.
These nodes are created during the instruction selection proper phase.
Definition at line 2132 of file SelectionDAGNodes.h.
Member Typedef Documentation
typedef MachineMemOperand** llvm::MachineSDNode::mmo_iterator
Definition at line 2134 of file SelectionDAGNodes.h.
Member Function Documentation
static bool llvm::MachineSDNode::classof (const SDNode * N) [inline, static]
Definition at line 2163 of file SelectionDAGNodes.h.
References llvm::SDNode::isMachineOpcode().
mmo_iterator llvm::MachineSDNode::memoperands_begin () const [inline]
Definition at line 2150 of file SelectionDAGNodes.h.
Referenced by CloneNodeWithValues(), and llvm::ARMBaseInstrInfo::getOperandLatency().
bool llvm::MachineSDNode::memoperands_empty () const [inline]
Definition at line 2152 of file SelectionDAGNodes.h.
Referenced by llvm::ARMBaseInstrInfo::getOperandLatency().
mmo_iterator llvm::MachineSDNode::memoperands_end () const [inline]
Definition at line 2151 of file SelectionDAGNodes.h.
Referenced by CloneNodeWithValues().
void llvm::MachineSDNode::setMemRefs (mmo_iterator NewMemRefs, mmo_iterator NewMemRefsEnd) [inline]
Assign this MachineSDNodes's memory reference descriptor list.
This does not transfer ownership.
Definition at line 2156 of file SelectionDAGNodes.h.
Referenced by CloneNodeWithValues().
Friends And Related Function Documentation
friend class SelectionDAG [friend]
Reimplemented from llvm::SDNode.
Definition at line 2137 of file SelectionDAGNodes.h.
The documentation for this class was generated from the following file:
SelectionDAGNodes.h