LLVM: llvm::sys::fs::file_status Class Reference
llvm::sys::fs::file_status Class Reference
file_status - Represents the result of a call to stat and friends.
#include <FileSystem.h>
Public Member Functions
file_status ()
file_status (file_type Type)
file_status (file_type Type, perms Perms, dev_t Dev, ino_t Ino, time_t MTime, uid_t UID, gid_t GID, off_t Size)
file_type type () const
perms permissions () const
TimeValue getLastModificationTime () const
UniqueID getUniqueID () const
uint32_t getUser () const
uint32_t getGroup () const
uint64_t getSize () const
void type (file_type v)
void permissions (perms p)
Friends
bool equivalent (file_status A, file_status B)
Do file_status's represent the same thing?
Detailed Description
file_status - Represents the result of a call to stat and friends.
It has a platform-specific member to store the result.
Definition at line 138 of file FileSystem.h.
Constructor & Destructor Documentation
llvm::sys::fs::file_status::file_status () [inline]
Definition at line 161 of file FileSystem.h.
llvm::sys::fs::file_status::file_status (file_type Type) [inline]
Definition at line 165 of file FileSystem.h.
llvm::sys::fs::file_status::file_status (file_type Type, perms Perms, dev_t Dev, ino_t Ino, time_t MTime, uid_t UID, gid_t GID, off_t Size) [inline]
Definition at line 169 of file FileSystem.h.
Member Function Documentation
uint32_t llvm::sys::fs::file_status::getGroup () const [inline]
Definition at line 203 of file FileSystem.h.
Referenced by llvm::writeArchive().
TimeValue llvm::sys::fs::file_status::getLastModificationTime () const
Referenced by llvm::writeArchive().
uint64_t llvm::sys::fs::file_status::getSize () const [inline]
Definition at line 204 of file FileSystem.h.
Referenced by llvm::sys::fs::file_size(), getOpenFileImpl(), shouldUseMmap(), and llvm::writeArchive().
UniqueID llvm::sys::fs::file_status::getUniqueID () const
Referenced by llvm::sys::fs::getUniqueID().
uint32_t llvm::sys::fs::file_status::getUser () const [inline]
Definition at line 202 of file FileSystem.h.
Referenced by llvm::writeArchive().
perms llvm::sys::fs::file_status::permissions () const [inline]
Definition at line 197 of file FileSystem.h.
Referenced by llvm::writeArchive().
void llvm::sys::fs::file_status::permissions (perms p) [inline]
Definition at line 219 of file FileSystem.h.
file_type llvm::sys::fs::file_status::type () const [inline]
Definition at line 196 of file FileSystem.h.
Referenced by llvm::FileOutputBuffer::create(), llvm::sys::fs::exists(), llvm::NewArchiveIterator::getFD(), getOpenFileImpl(), llvm::sys::fs::is_directory(), llvm::sys::fs::is_regular_file(), llvm::raw_fd_ostream::raw_fd_ostream(), and llvm::sys::fs::status_known().
void llvm::sys::fs::file_status::type (file_type v) [inline]
Definition at line 218 of file FileSystem.h.
Friends And Related Function Documentation
bool equivalent (file_status A, file_status B) [friend]
Do file_status's represent the same thing?
Parameters:
A Input file_status.
B Input file_status.
assert(status_known(A) || status_known(B));
Returns:
True if A and B both represent the same file system entity, false otherwise.
The documentation for this class was generated from the following file:
FileSystem.h