LLVM: llvm::ExecutionEngineState Class Reference
llvm::ExecutionEngineState Class Reference
Helper class for helping synchronize access to the global address map table.
#include <ExecutionEngine.h>
Public Types
typedef StringMap< uint64_t > GlobalAddressMapTy
Public Member Functions
GlobalAddressMapTy & getGlobalAddressMap ()
std::map< uint64_t, std::string > & getGlobalAddressReverseMap ()
uint64_t RemoveMapping (StringRef Name)
Erase an entry from the mapping table.
Detailed Description
Helper class for helping synchronize access to the global address map table.
Access to this class should be serialized under a mutex.
Definition at line 60 of file ExecutionEngine/ExecutionEngine.h.
Member Typedef Documentation
typedef StringMap<uint64_t> llvm::ExecutionEngineState::GlobalAddressMapTy
Definition at line 62 of file ExecutionEngine/ExecutionEngine.h.
Member Function Documentation
GlobalAddressMapTy& llvm::ExecutionEngineState::getGlobalAddressMap () [inline]
Definition at line 78 of file ExecutionEngine/ExecutionEngine.h.
Referenced by llvm::ExecutionEngine::addGlobalMapping(), llvm::ExecutionEngine::clearAllGlobalMappings(), llvm::ExecutionEngine::getAddressToGlobalIfAvailable(), llvm::ExecutionEngine::getGlobalValueAtAddress(), and llvm::ExecutionEngine::updateGlobalMapping().
std::map<uint64_t, std::string>& llvm::ExecutionEngineState::getGlobalAddressReverseMap () [inline]
Definition at line 82 of file ExecutionEngine/ExecutionEngine.h.
Referenced by llvm::ExecutionEngine::addGlobalMapping(), llvm::ExecutionEngine::clearAllGlobalMappings(), llvm::ExecutionEngine::getGlobalValueAtAddress(), and llvm::ExecutionEngine::updateGlobalMapping().
uint64_t ExecutionEngineState::RemoveMapping (StringRef Name)
Erase an entry from the mapping table.
Returns:
The address that ToUnmap was happed to.
Definition at line 165 of file ExecutionEngine.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::erase(), llvm::StringMap< ValueTy, AllocatorTy >::find(), and I.
Referenced by llvm::ExecutionEngine::clearGlobalMappingsFromModule(), and llvm::ExecutionEngine::updateGlobalMapping().
The documentation for this class was generated from the following files:
ExecutionEngine/ExecutionEngine.h
ExecutionEngine.cpp