LLVM: llvm::sys::TimeValue Class Reference
llvm::sys::TimeValue Class Reference
This class is used where a precise fixed point in time is required.
#include <TimeValue.h>
Public Types
enum TimeConversions {
NANOSECONDS_PER_SECOND = 1000000000, MICROSECONDS_PER_SECOND = 1000000, MILLISECONDS_PER_SECOND = 1000, NANOSECONDS_PER_MICROSECOND = 1000,
NANOSECONDS_PER_MILLISECOND = 1000000, NANOSECONDS_PER_WIN32_TICK = 100
}
typedef int64_t SecondsType
Type used for representing seconds.
typedef int32_t NanoSecondsType
Type used for representing nanoseconds.
Public Member Functions
TimeValue ()
Default construct a time value, initializing to ZeroTime.
TimeValue (SecondsType seconds, NanoSecondsType nanos=0)
Caller provides the exact value in seconds and nanoseconds.
TimeValue (double new_time)
Caller provides the exact value as a double in seconds with the fractional part representing nanoseconds.
TimeValue & operator+= (const TimeValue &that)
Add that to this.
TimeValue & operator-= (const TimeValue &that)
Subtract that from this.
int operator< (const TimeValue &that) const
Determine if this is less than that.
int operator> (const TimeValue &that) const
Determine if this is greather than that.
int operator<= (const TimeValue &that) const
Determine if this is less than or equal to that.
int operator>= (const TimeValue &that) const
Determine if this is greater than or equal to that.
int operator== (const TimeValue &that) const
Determines if two TimeValue objects represent the same moment in time.
int operator!= (const TimeValue &that) const
Determines if two TimeValue objects represent times that are not the same.
SecondsType seconds () const
Returns only the seconds component of the TimeValue.
NanoSecondsType nanoseconds () const
Returns only the nanoseconds component of the TimeValue.
uint32_t microseconds () const
Returns only the fractional portion of the TimeValue rounded down to the nearest microsecond (divide by one thousand).
uint32_t milliseconds () const
Returns only the fractional portion of the TimeValue rounded down to the nearest millisecond (divide by one million).
uint64_t usec () const
Returns the TimeValue as a number of microseconds.
uint64_t msec () const
Returns the TimeValue as a number of milliseconds.
uint64_t toEpochTime () const
Converts the TimeValue into the corresponding number of seconds since the epoch (00:00:00 Jan 1,1970).
uint64_t toWin32Time () const
Converts the TimeValue into the corresponding number of "ticks" for Win32 platforms, correcting for the difference in Win32 zero time.
void getTimespecTime (uint64_t &seconds, uint32_t &nanos) const
Provides the seconds and nanoseconds as results in its arguments after correction for the Posix zero time.
std::string str () const
Provides conversion of the TimeValue into a readable time & date.
void seconds (SecondsType sec)
The seconds component of the TimeValue is set to sec without modifying the nanoseconds part.
void nanoseconds (NanoSecondsType nanos)
The nanoseconds component of the TimeValue is set to nanos without modifying the seconds part.
void microseconds (int32_t micros)
The seconds component remains unchanged.
void milliseconds (int32_t millis)
The seconds component remains unchanged.
void usec (int64_t microseconds)
Converts from microsecond format to TimeValue format.
void msec (int64_t milliseconds)
Converts from millisecond format to TimeValue format.
void fromEpochTime (SecondsType seconds)
Converts the seconds argument from PosixTime to the corresponding TimeValue and assigns that value to this.
void fromWin32Time (uint64_t win32Time)
Converts the win32Time argument from Windows FILETIME to the corresponding TimeValue and assigns that value to this.
Static Public Member Functions
static TimeValue now ()
This is a static constructor that returns a TimeValue that represents the current time.
Constants
static TimeValue MinTime ()
A constant TimeValue representing the smallest time value permissible by the class.
static TimeValue MaxTime ()
A constant TimeValue representing the largest time value permissible by the class.
static TimeValue ZeroTime ()
A constant TimeValue representing the base time, or zero time of 00:00:00 (midnight) January 1st, 2000.
static TimeValue PosixZeroTime ()
A constant TimeValue for the Posix base time which is 00:00:00 (midnight) January 1st, 1970.
static TimeValue Win32ZeroTime ()
A constant TimeValue for the Win32 base time which is 00:00:00 (midnight) January 1st, 1601.
Friends
TimeValue operator+ (const TimeValue &tv1, const TimeValue &tv2)
Adds two TimeValue objects together.
TimeValue operator- (const TimeValue &tv1, const TimeValue &tv2)
Subtracts two TimeValue objects.
Detailed Description
This class is used where a precise fixed point in time is required.
The range of TimeValue spans many hundreds of billions of years both past and present. The precision of TimeValue is to the nanosecond. However, the actual precision of its values will be determined by the resolution of the system clock. The TimeValue class is used in conjunction with several other lib/System interfaces to specify the time at which a call should timeout, etc.
Since:
1.4 Provides an abstraction for a fixed point in time.
Definition at line 31 of file TimeValue.h.
Member Typedef Documentation
typedef int32_t llvm::sys::TimeValue::NanoSecondsType
Type used for representing nanoseconds.
Definition at line 77 of file TimeValue.h.
typedef int64_t llvm::sys::TimeValue::SecondsType
Type used for representing seconds.
Definition at line 76 of file TimeValue.h.
Member Enumeration Documentation
enum llvm::sys::TimeValue::TimeConversions
Enumerator:
NANOSECONDS_PER_SECOND
One Billion.
MICROSECONDS_PER_SECOND
One Million.
MILLISECONDS_PER_SECOND
One Thousand.
NANOSECONDS_PER_MICROSECOND
One Thousand.
NANOSECONDS_PER_MILLISECOND
One Million.
NANOSECONDS_PER_WIN32_TICK
Win32 tick is 10^7 Hz (10ns)
Definition at line 79 of file TimeValue.h.
Constructor & Destructor Documentation
llvm::sys::TimeValue::TimeValue () [inline]
Default construct a time value, initializing to ZeroTime.
Definition at line 91 of file TimeValue.h.
Referenced by MaxTime(), MinTime(), PosixZeroTime(), Win32ZeroTime(), and ZeroTime().
llvm::sys::TimeValue::TimeValue (SecondsType seconds, NanoSecondsType nanos = 0) [inline, explicit]
Caller provides the exact value in seconds and nanoseconds.
The nanos argument defaults to zero for convenience. Explicit constructor
Definition at line 96 of file TimeValue.h.
llvm::sys::TimeValue::TimeValue (double new_time) [inline, explicit]
Caller provides the exact value as a double in seconds with the fractional part representing nanoseconds.
Double Constructor.
Definition at line 102 of file TimeValue.h.
References NANOSECONDS_PER_SECOND.
Member Function Documentation
void llvm::sys::TimeValue::fromEpochTime (SecondsType seconds) [inline]
Converts the seconds argument from PosixTime to the corresponding TimeValue and assigns that value to this.
Convert seconds form PosixTime to TimeValue
Definition at line 324 of file TimeValue.h.
References MILLISECONDS_PER_SECOND, and NANOSECONDS_PER_MILLISECOND.
Referenced by llvm::object::ArchiveMemberHeader::getLastModified().
void llvm::sys::TimeValue::fromWin32Time (uint64_t win32Time) [inline]
Converts the win32Time argument from Windows FILETIME to the corresponding TimeValue and assigns that value to this.
Convert seconds form Windows FILETIME to TimeValue
Definition at line 333 of file TimeValue.h.
void llvm::sys::TimeValue::getTimespecTime (uint64_t & seconds, uint32_t & nanos) const [inline]
Provides the seconds and nanoseconds as results in its arguments after correction for the Posix zero time.
Convert to timespec time (ala POSIX.1b)
Definition at line 259 of file TimeValue.h.
static TimeValue llvm::sys::TimeValue::MaxTime () [inline, static]
A constant TimeValue representing the largest time value permissible by the class.
MaxTime is some point in the distant future, about 300 billion years AD. The largest possible time value.
Definition at line 49 of file TimeValue.h.
References INT64_MAX, and TimeValue().
uint32_t llvm::sys::TimeValue::microseconds () const [inline]
Returns only the fractional portion of the TimeValue rounded down to the nearest microsecond (divide by one thousand).
Retrieve the fractional part as microseconds;
Definition at line 209 of file TimeValue.h.
Referenced by llvm::TimeRecord::getCurrentTime().
void llvm::sys::TimeValue::microseconds (int32_t micros) [inline]
The seconds component remains unchanged.
Set the nanoseconds component using a number of microseconds.
Definition at line 293 of file TimeValue.h.
uint32_t llvm::sys::TimeValue::milliseconds () const [inline]
Returns only the fractional portion of the TimeValue rounded down to the nearest millisecond (divide by one million).
Retrieve the fractional part as milliseconds;
Definition at line 216 of file TimeValue.h.
References NANOSECONDS_PER_MICROSECOND.
void llvm::sys::TimeValue::milliseconds (int32_t millis) [inline]
The seconds component remains unchanged.
Set the nanoseconds component using a number of milliseconds.
Definition at line 300 of file TimeValue.h.
References NANOSECONDS_PER_MICROSECOND.
static TimeValue llvm::sys::TimeValue::MinTime () [inline, static]
A constant TimeValue representing the smallest time value permissible by the class.
MinTime is some point in the distant past, about 300 billion years BCE. The smallest possible time value.
Definition at line 41 of file TimeValue.h.
References INT64_MIN, and TimeValue().
uint64_t llvm::sys::TimeValue::msec () const [inline]
Returns the TimeValue as a number of milliseconds.
Note that the value returned can overflow because the range of a uint64_t is smaller than the range of a TimeValue. Nevertheless, this is useful on some operating systems and is therefore provided. Convert to a number of milliseconds (can overflow)
Definition at line 235 of file TimeValue.h.
void llvm::sys::TimeValue::msec (int64_t milliseconds) [inline]
Converts from millisecond format to TimeValue format.
Definition at line 314 of file TimeValue.h.
References MICROSECONDS_PER_SECOND, and NANOSECONDS_PER_MICROSECOND.
NanoSecondsType llvm::sys::TimeValue::nanoseconds () const [inline]
Returns only the nanoseconds component of the TimeValue.
The seconds portion is ignored. Retrieve the nanoseconds component.
Definition at line 204 of file TimeValue.h.
void llvm::sys::TimeValue::nanoseconds (NanoSecondsType nanos) [inline]
The nanoseconds component of the TimeValue is set to nanos without modifying the seconds part.
This is useful for basic computations involving just the nanoseconds portion. Note that the TimeValue will be normalized after this call so that the fractional (nanoseconds) portion will have the smallest equivalent value. Set the nanoseconds component using a number of nanoseconds.
Definition at line 286 of file TimeValue.h.
static TimeValue llvm::sys::TimeValue::now () [static]
This is a static constructor that returns a TimeValue that represents the current time.
Creates a TimeValue with the current time (UTC).
Referenced by llvm::PMDataManager::dumpPassInfo(), and writeSymbolTable().
int llvm::sys::TimeValue::operator!= (const TimeValue & that) const [inline]
Determines if two TimeValue objects represent times that are not the same.
Returns:
True iff *this != that.
Definition at line 181 of file TimeValue.h.
TimeValue& llvm::sys::TimeValue::operator+= (const TimeValue & that) [inline]
Add that to this.
Returns:
this Incrementing assignment operator.
Definition at line 121 of file TimeValue.h.
TimeValue& llvm::sys::TimeValue::operator-= (const TimeValue & that) [inline]
Subtract that from this.
Returns:
this Decrementing assignment operator.
Definition at line 131 of file TimeValue.h.
int llvm::sys::TimeValue::operator< (const TimeValue & that) const [inline]
Determine if this is less than that.
Returns:
True iff *this < that. True if this < that.
Definition at line 141 of file TimeValue.h.
int llvm::sys::TimeValue::operator<= (const TimeValue & that) const [inline]
Determine if this is less than or equal to that.
Returns:
True iff *this <= that. True if this <= that.
Definition at line 158 of file TimeValue.h.
int llvm::sys::TimeValue::operator== (const TimeValue & that) const [inline]
Determines if two TimeValue objects represent the same moment in time.
Returns:
True iff *this == that.
Definition at line 173 of file TimeValue.h.
int llvm::sys::TimeValue::operator> (const TimeValue & that) const [inline]
Determine if this is greather than that.
Returns:
True iff *this > that. True if this > that.
Definition at line 146 of file TimeValue.h.
int llvm::sys::TimeValue::operator>= (const TimeValue & that) const [inline]
Determine if this is greater than or equal to that.
Returns:
True iff *this >= that.
Definition at line 162 of file TimeValue.h.
static TimeValue llvm::sys::TimeValue::PosixZeroTime () [inline, static]
A constant TimeValue for the Posix base time which is 00:00:00 (midnight) January 1st, 1970.
00:00:00 Jan 1, 1970 UTC.
Definition at line 63 of file TimeValue.h.
References TimeValue().
SecondsType llvm::sys::TimeValue::seconds () const [inline]
Returns only the seconds component of the TimeValue.
The nanoseconds portion is ignored. No rounding is performed. Retrieve the seconds component
Definition at line 199 of file TimeValue.h.
Referenced by llvm::TimeRecord::getCurrentTime().
void llvm::sys::TimeValue::seconds (SecondsType sec) [inline]
The seconds component of the TimeValue is set to sec without modifying the nanoseconds part.
This is useful for whole second arithmetic. Set the seconds component.
Definition at line 275 of file TimeValue.h.
std::string llvm::sys::TimeValue::str () const
Provides conversion of the TimeValue into a readable time & date.
Returns:
std::string containing the readable time value Convert time to a string.
Referenced by llvm::PMDataManager::dumpPassInfo().
uint64_t llvm::sys::TimeValue::toEpochTime () const [inline]
Converts the TimeValue into the corresponding number of seconds since the epoch (00:00:00 Jan 1,1970).
Definition at line 242 of file TimeValue.h.
References MILLISECONDS_PER_SECOND, and NANOSECONDS_PER_MILLISECOND.
Referenced by printRestOfMemberHeader().
uint64_t llvm::sys::TimeValue::toWin32Time () const [inline]
Converts the TimeValue into the corresponding number of "ticks" for Win32 platforms, correcting for the difference in Win32 zero time.
Convert to Win32's FILETIME (100ns intervals since 00:00:00 Jan 1, 1601 UTC)
Definition at line 250 of file TimeValue.h.
uint64_t llvm::sys::TimeValue::usec () const [inline]
Returns the TimeValue as a number of microseconds.
Note that the value returned can overflow because the range of a uint64_t is smaller than the range of a TimeValue. Nevertheless, this is useful on some operating systems and is therefore provided. Convert to a number of microseconds (can overflow)
Definition at line 225 of file TimeValue.h.
void llvm::sys::TimeValue::usec (int64_t microseconds) [inline]
Converts from microsecond format to TimeValue format.
Definition at line 306 of file TimeValue.h.
static TimeValue llvm::sys::TimeValue::Win32ZeroTime () [inline, static]
A constant TimeValue for the Win32 base time which is 00:00:00 (midnight) January 1st, 1601.
00:00:00 Jan 1, 1601 UTC.
Definition at line 70 of file TimeValue.h.
References TimeValue().
static TimeValue llvm::sys::TimeValue::ZeroTime () [inline, static]
A constant TimeValue representing the base time, or zero time of 00:00:00 (midnight) January 1st, 2000.
00:00:00 Jan 1, 2000 UTC.
Definition at line 56 of file TimeValue.h.
References TimeValue().
Friends And Related Function Documentation
TimeValue operator+ (const TimeValue & tv1, const TimeValue & tv2) [friend]
Adds two TimeValue objects together.
Returns:
The sum of the two operands as a new TimeValue Addition operator.
Definition at line 371 of file TimeValue.h.
TimeValue operator- (const TimeValue & tv1, const TimeValue & tv2) [friend]
Subtracts two TimeValue objects.
Returns:
The difference of the two operands as a new TimeValue Subtraction operator.
Definition at line 377 of file TimeValue.h.
The documentation for this class was generated from the following files:
TimeValue.h
TimeValue.cpp