LLVM: llvm::DominatorTreeBase< NodeT > Class Template Reference
llvm::DominatorTreeBase< NodeT > Class Template Reference
Core dominator tree base class.
#include <GenericDomTree.h>
Classes
struct InfoRec
Public Member Functions
DominatorTreeBase (bool isPostDom)
DominatorTreeBase (DominatorTreeBase &&Arg)
DominatorTreeBase & operator= (DominatorTreeBase &&RHS)
bool compare (const DominatorTreeBase &Other) const
compare - Return false if the other dominator tree base matches this dominator tree base.
void releaseMemory ()
DomTreeNodeBase< NodeT > * getNode (NodeT *BB) const
getNode - return the (Post)DominatorTree node for the specified basic block.
DomTreeNodeBase< NodeT > * operator[] (NodeT *BB) const
DomTreeNodeBase< NodeT > * getRootNode ()
getRootNode - This returns the entry node for the CFG of the function.
const DomTreeNodeBase< NodeT > * getRootNode () const
void getDescendants (NodeT *R, SmallVectorImpl< NodeT * > &Result) const
Get all nodes dominated by R, including R itself.
bool properlyDominates (const DomTreeNodeBase< NodeT > *A, const DomTreeNodeBase< NodeT > *B) const
properlyDominates - Returns true iff A dominates B and A != B.
bool properlyDominates (const NodeT *A, const NodeT *B) const
bool isReachableFromEntry (const NodeT *A) const
isReachableFromEntry - Return true if A is dominated by the entry block of the function containing it.
bool isReachableFromEntry (const DomTreeNodeBase< NodeT > *A) const
bool dominates (const DomTreeNodeBase< NodeT > *A, const DomTreeNodeBase< NodeT > *B) const
dominates - Returns true iff A dominates B.
bool dominates (const NodeT *A, const NodeT *B) const
NodeT * getRoot () const
NodeT * findNearestCommonDominator (NodeT *A, NodeT *B)
findNearestCommonDominator - Find nearest common dominator basic block for basic block A and B.
const NodeT * findNearestCommonDominator (const NodeT *A, const NodeT *B)
DomTreeNodeBase< NodeT > * addNewBlock (NodeT *BB, NodeT *DomBB)
addNewBlock - Add a new node to the dominator tree information.
void changeImmediateDominator (DomTreeNodeBase< NodeT > *N, DomTreeNodeBase< NodeT > *NewIDom)
changeImmediateDominator - This method is used to update the dominator tree information when a node's immediate dominator changes.
void changeImmediateDominator (NodeT *BB, NodeT *NewBB)
void eraseNode (NodeT *BB)
eraseNode - Removes a node from the dominator tree.
void splitBlock (NodeT *NewBB)
splitBlock - BB is split and now it has one successor.
void print (raw_ostream &o) const
print - Convert to human readable form
void updateDFSNumbers () const
updateDFSNumbers - Assign In and Out numbers to the nodes while walking dominator tree in dfs order.
template<class FT >
void recalculate (FT &F)
recalculate - compute a dominator tree for the given function
Protected Types
typedef DenseMap< NodeT
*, std::unique_ptr
< DomTreeNodeBase< NodeT > > > DomTreeNodeMapType
Protected Member Functions
void reset ()
template<class N , class GraphT >
void Split (DominatorTreeBase< typename GraphT::NodeType > &DT, typename GraphT::NodeType *NewBB)
DomTreeNodeBase< NodeT > * getNodeForBlock (NodeT *BB)
NodeT * getIDom (NodeT *BB) const
void addRoot (NodeT *BB)
template<>
void addRoot (MachineBasicBlock *MBB)
Protected Attributes
DomTreeNodeMapType DomTreeNodes
DomTreeNodeBase< NodeT > * RootNode
bool DFSInfoValid
unsigned int SlowQueries
DenseMap< NodeT *, NodeT * > IDoms
std::vector< NodeT * > Vertex
DenseMap< NodeT *, InfoRec > Info
Friends
template<class GraphT >
GraphT::NodeType * Eval (DominatorTreeBase< typename GraphT::NodeType > &DT, typename GraphT::NodeType *V, unsigned LastLinked)
template<class GraphT >
unsigned DFSPass (DominatorTreeBase< typename GraphT::NodeType > &DT, typename GraphT::NodeType *V, unsigned N)
template<class FuncT , class N >
void Calculate (DominatorTreeBase< typename GraphTraits< N >::NodeType > &DT, FuncT &F)
Detailed Description
template<class NodeT>
class llvm::DominatorTreeBase< NodeT >
Core dominator tree base class.
This class is a generic template over graph nodes. It is instantiated for various graphs in the LLVM IR or in the code generator.
Definition at line 186 of file GenericDomTree.h.
Member Typedef Documentation
template<class NodeT> typedef DenseMap<NodeT *, std::unique_ptr<DomTreeNodeBase<NodeT> > > llvm::DominatorTreeBase< NodeT >::DomTreeNodeMapType [protected]
Definition at line 216 of file GenericDomTree.h.
Constructor & Destructor Documentation
template<class NodeT> llvm::DominatorTreeBase< NodeT >::DominatorTreeBase (bool isPostDom) [inline, explicit]
Definition at line 316 of file GenericDomTree.h.
template<class NodeT> llvm::DominatorTreeBase< NodeT >::DominatorTreeBase (DominatorTreeBase< NodeT > && Arg) [inline]
Definition at line 319 of file GenericDomTree.h.
Member Function Documentation
template<class NodeT> DomTreeNodeBase<NodeT>* llvm::DominatorTreeBase< NodeT >::addNewBlock (NodeT * BB, NodeT * DomBB) [inline]
addNewBlock - Add a new node to the dominator tree information.
This creates a new node as a child of DomBB dominator node,linking it into the children list of the immediate dominator.
Definition at line 556 of file GenericDomTree.h.
Referenced by cloneLoopWithPreheader(), llvm::DominatorTreeBase< MachineBasicBlock >::Split(), llvm::SplitBlock(), and llvm::SplitBlockAndInsertIfThen().
template<> void llvm::DominatorTreeBase< MachineBasicBlock >::addRoot (MachineBasicBlock * MBB) [inline, protected]
Definition at line 28 of file MachineDominators.h.
template<class NodeT> void llvm::DominatorTreeBase< NodeT >::addRoot (NodeT * BB) [inline, protected]
Definition at line 662 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< MachineBasicBlock >::recalculate().
template<class NodeT> void llvm::DominatorTreeBase< NodeT >::changeImmediateDominator (DomTreeNodeBase< NodeT > * N, DomTreeNodeBase< NodeT > * NewIDom) [inline]
changeImmediateDominator - This method is used to update the dominator tree information when a node's immediate dominator changes.
Definition at line 568 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< MachineBasicBlock >::changeImmediateDominator(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), simplifyOneLoop(), llvm::DominatorTreeBase< MachineBasicBlock >::Split(), llvm::SplitBlock(), and llvm::SplitBlockAndInsertIfThen().
template<class NodeT> void llvm::DominatorTreeBase< NodeT >::changeImmediateDominator (NodeT * BB, NodeT * NewBB) [inline]
Definition at line 575 of file GenericDomTree.h.
template<class NodeT> bool llvm::DominatorTreeBase< NodeT >::compare (const DominatorTreeBase< NodeT > & Other) const [inline]
compare - Return false if the other dominator tree base matches this dominator tree base.
Otherwise return true.
Definition at line 345 of file GenericDomTree.h.
template<class NodeT> bool llvm::DominatorTreeBase< NodeT >::dominates (const DomTreeNodeBase< NodeT > * A, const DomTreeNodeBase< NodeT > * B) const [inline]
dominates - Returns true iff A dominates B.
Note that this is not a constant time operation!
Definition at line 438 of file GenericDomTree.h.
Referenced by llvm::LoopInfoBase< BlockT, LoopT >::Analyze(), llvm::MachinePostDominatorTree::dominates(), llvm::PostDominatorTree::dominates(), llvm::DominatorTreeBase< MachineBasicBlock >::findNearestCommonDominator(), llvm::DominatorTreeBase< MachineBasicBlock >::properlyDominates(), and llvm::DominatorTreeBase< MachineBasicBlock >::Split().
template<class NodeT> bool llvm::DominatorTreeBase< NodeT >::dominates (const NodeT * A, const NodeT * B) const
Definition at line 752 of file GenericDomTree.h.
template<class NodeT> void llvm::DominatorTreeBase< NodeT >::eraseNode (NodeT * BB) [inline]
eraseNode - Removes a node from the dominator tree.
Block must not dominate any other blocks. Removes node from its immediate dominator's children list. Deletes dominator node associated with basic block BB.
Definition at line 582 of file GenericDomTree.h.
Referenced by llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), and simplifyOneLoop().
template<class NodeT> NodeT* llvm::DominatorTreeBase< NodeT >::findNearestCommonDominator (NodeT * A, NodeT * B) [inline]
findNearestCommonDominator - Find nearest common dominator basic block for basic block A and B.
If there is no such block then return NULL.
Definition at line 483 of file GenericDomTree.h.
Referenced by llvm::PostDominatorTree::findNearestCommonDominator(), llvm::MachinePostDominatorTree::findNearestCommonDominator(), llvm::DominatorTreeBase< MachineBasicBlock >::findNearestCommonDominator(), getInsertPointForUses(), and llvm::DominatorTreeBase< MachineBasicBlock >::Split().
template<class NodeT> const NodeT* llvm::DominatorTreeBase< NodeT >::findNearestCommonDominator (const NodeT * A, const NodeT * B) [inline]
Definition at line 542 of file GenericDomTree.h.
template<class NodeT> void llvm::DominatorTreeBase< NodeT >::getDescendants (NodeT * R, SmallVectorImpl< NodeT * > & Result) const [inline]
Get all nodes dominated by R, including R itself.
Definition at line 396 of file GenericDomTree.h.
Referenced by llvm::PostDominatorTree::getDescendants().
template<class NodeT> NodeT* llvm::DominatorTreeBase< NodeT >::getIDom (NodeT * BB) const [inline, protected]
Definition at line 660 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< MachineBasicBlock >::getNodeForBlock().
template<class NodeT> DomTreeNodeBase<NodeT>* llvm::DominatorTreeBase< NodeT >::getNode (NodeT * BB) const [inline]
getNode - return the (Post)DominatorTree node for the specified basic block.
This is the same as using operator[] on this class.
Definition at line 376 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< MachineBasicBlock >::addNewBlock(), blockDominatesAnExit(), llvm::IDFCalculator::calculate(), llvm::DominatorTreeBase< MachineBasicBlock >::changeImmediateDominator(), cloneLoopWithPreheader(), containsUnconditionalCallSafepoint(), llvm::DominatorTreeBase< MachineBasicBlock >::eraseNode(), llvm::DominatorTreeBase< MachineBasicBlock >::findNearestCommonDominator(), llvm::DominatorTreeBase< MachineBasicBlock >::getDescendants(), llvm::MachinePostDominatorTree::getNode(), llvm::PostDominatorTree::getNode(), llvm::DominatorTreeBase< MachineBasicBlock >::getNodeForBlock(), llvm::DominatorTreeBase< MachineBasicBlock >::isReachableFromEntry(), isSimplifiedLoopNest(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), llvm::MachinePostDominatorTree::operator[](), llvm::PostDominatorTree::operator[](), llvm::DominatorTreeBase< MachineBasicBlock >::operator[](), processInstruction(), simplifyOneLoop(), llvm::DominatorTreeBase< MachineBasicBlock >::Split(), llvm::SplitBlock(), and llvm::SplitBlockAndInsertIfThen().
template<class NodeT> DomTreeNodeBase<NodeT>* llvm::DominatorTreeBase< NodeT >::getNodeForBlock (NodeT * BB) [inline, protected]
Definition at line 643 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< MachineBasicBlock >::getNodeForBlock().
template<class NodeT> NodeT* llvm::DominatorTreeBase< NodeT >::getRoot () const [inline]
Definition at line 476 of file GenericDomTree.h.
template<class NodeT> DomTreeNodeBase<NodeT>* llvm::DominatorTreeBase< NodeT >::getRootNode () [inline]
getRootNode - This returns the entry node for the CFG of the function.
If this tree represents the post-dominance relations for a function, however, this root may be a node with the block == NULL. This is the case when there are multiple exit nodes from a particular function. Consumers of post-dominance information must be capable of dealing with this possibility.
Definition at line 392 of file GenericDomTree.h.
Referenced by llvm::LoopInfoBase< BlockT, LoopT >::Analyze(), llvm::IDFCalculator::calculate(), llvm::DominatorTree::compare(), llvm::GraphTraits< DominatorTree * >::getEntryNode(), llvm::DOTGraphTraits< DominatorTree * >::getNodeLabel(), llvm::MachinePostDominatorTree::getRootNode(), llvm::PostDominatorTree::getRootNode(), llvm::DominatorTreeBase< MachineBasicBlock >::print(), and llvm::DominatorTreeBase< MachineBasicBlock >::updateDFSNumbers().
template<class NodeT> const DomTreeNodeBase<NodeT>* llvm::DominatorTreeBase< NodeT >::getRootNode () const [inline]
Definition at line 393 of file GenericDomTree.h.
template<class NodeT> bool llvm::DominatorTreeBase< NodeT >::isReachableFromEntry (const NodeT * A) const [inline]
isReachableFromEntry - Return true if A is dominated by the entry block of the function containing it.
Definition at line 427 of file GenericDomTree.h.
Referenced by llvm::LoopInfoBase< BlockT, LoopT >::Analyze(), llvm::discoverAndMapSubloop(), llvm::DominatorTreeBase< MachineBasicBlock >::dominates(), llvm::DominatorTreeBase< MachineBasicBlock >::isReachableFromEntry(), and llvm::DominatorTreeBase< MachineBasicBlock >::Split().
template<class NodeT> bool llvm::DominatorTreeBase< NodeT >::isReachableFromEntry (const DomTreeNodeBase< NodeT > * A) const [inline]
Definition at line 433 of file GenericDomTree.h.
template<class NodeT> DominatorTreeBase& llvm::DominatorTreeBase< NodeT >::operator= (DominatorTreeBase< NodeT > && RHS) [inline]
Definition at line 329 of file GenericDomTree.h.
template<class NodeT> DomTreeNodeBase<NodeT>* llvm::DominatorTreeBase< NodeT >::operator[] (NodeT * BB) const [inline]
Definition at line 383 of file GenericDomTree.h.
template<class NodeT> void llvm::DominatorTreeBase< NodeT >::print (raw_ostream & o) const [inline]
print - Convert to human readable form
Definition at line 613 of file GenericDomTree.h.
Referenced by llvm::MachinePostDominatorTree::print(), llvm::PostDominatorTree::print(), llvm::MachineDominatorTree::print(), llvm::DominatorTreeWrapperPass::print(), and llvm::DominatorTree::verifyDomTree().
template<class NodeT> bool llvm::DominatorTreeBase< NodeT >::properlyDominates (const DomTreeNodeBase< NodeT > * A, const DomTreeNodeBase< NodeT > * B) const [inline]
properlyDominates - Returns true iff A dominates B and A != B.
Note that this is not a constant time operation!
Definition at line 414 of file GenericDomTree.h.
Referenced by llvm::ForwardDominanceFrontierBase< BlockT >::calculate(), isLoopInvariant(), llvm::PostDominatorTree::properlyDominates(), and llvm::MachinePostDominatorTree::properlyDominates().
template<class NodeT> bool llvm::DominatorTreeBase< NodeT >::properlyDominates (const NodeT * A, const NodeT * B) const
Definition at line 763 of file GenericDomTree.h.
template<class NodeT> template<class FT > void llvm::DominatorTreeBase< NodeT >::recalculate (FT & F) [inline]
recalculate - compute a dominator tree for the given function
Definition at line 717 of file GenericDomTree.h.
Referenced by AddAliasScopeMetadata(), AddAlignmentAssumptions(), llvm::DominatorTreeAnalysis::run(), llvm::MachinePostDominatorTree::runOnMachineFunction(), llvm::MachineDominatorTree::runOnMachineFunction(), llvm::UnrollLoop(), and llvm::DominatorTree::verifyDomTree().
template<class NodeT> void llvm::DominatorTreeBase< NodeT >::releaseMemory () [inline]
Definition at line 371 of file GenericDomTree.h.
Referenced by llvm::PostDominatorTree::releaseMemory(), llvm::MachineDominatorTree::releaseMemory(), and llvm::DominatorTreeWrapperPass::releaseMemory().
template<class NodeT> void llvm::DominatorTreeBase< NodeT >::reset () [inline, protected]
Definition at line 240 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< MachineBasicBlock >::recalculate(), and llvm::DominatorTreeBase< MachineBasicBlock >::releaseMemory().
template<class NodeT> template<class N , class GraphT > void llvm::DominatorTreeBase< NodeT >::Split (DominatorTreeBase< typename GraphT::NodeType > & DT, typename GraphT::NodeType * NewBB) [inline, protected]
Definition at line 253 of file GenericDomTree.h.
template<class NodeT> void llvm::DominatorTreeBase< NodeT >::splitBlock (NodeT * NewBB) [inline]
splitBlock - BB is split and now it has one successor.
Update dominator tree to reflect this change.
Definition at line 603 of file GenericDomTree.h.
Referenced by insertUniqueBackedgeBlock(), and UpdateAnalysisInformation().
template<class NodeT> void llvm::DominatorTreeBase< NodeT >::updateDFSNumbers () const [inline]
updateDFSNumbers - Assign In and Out numbers to the nodes while walking dominator tree in dfs order.
Definition at line 667 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< MachineBasicBlock >::dominates().
Friends And Related Function Documentation
template<class NodeT> template<class FuncT , class N > void Calculate (DominatorTreeBase< typename GraphTraits< N >::NodeType > & DT, FuncT & F) [friend]
template<class NodeT> template<class GraphT > unsigned DFSPass (DominatorTreeBase< typename GraphT::NodeType > & DT, typename GraphT::NodeType * V, unsigned N) [friend]
Definition at line 34 of file GenericDomTreeConstruction.h.
template<class NodeT> template<class GraphT > GraphT::NodeType* Eval (DominatorTreeBase< typename GraphT::NodeType > & DT, typename GraphT::NodeType * V, unsigned LastLinked) [friend]
Definition at line 108 of file GenericDomTreeConstruction.h.
Member Data Documentation
template<class NodeT> bool llvm::DominatorTreeBase< NodeT >::DFSInfoValid [mutable, protected]
Definition at line 220 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< MachineBasicBlock >::addNewBlock(), llvm::DominatorTreeBase< MachineBasicBlock >::changeImmediateDominator(), llvm::DominatorTreeBase< MachineBasicBlock >::dominates(), llvm::DominatorTreeBase< MachineBasicBlock >::findNearestCommonDominator(), llvm::DominatorTreeBase< MachineBasicBlock >::operator=(), llvm::DominatorTreeBase< MachineBasicBlock >::print(), llvm::DominatorTreeBase< MachineBasicBlock >::reset(), and llvm::DominatorTreeBase< MachineBasicBlock >::updateDFSNumbers().
template<class NodeT> DomTreeNodeMapType llvm::DominatorTreeBase< NodeT >::DomTreeNodes [protected]
Definition at line 217 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< MachineBasicBlock >::addNewBlock(), llvm::DominatorTreeBase< MachineBasicBlock >::compare(), llvm::DominatorTreeBase< MachineBasicBlock >::eraseNode(), llvm::DominatorTreeBase< MachineBasicBlock >::getNode(), llvm::DominatorTreeBase< MachineBasicBlock >::getNodeForBlock(), llvm::DominatorTreeBase< MachineBasicBlock >::operator=(), llvm::DominatorTreeBase< MachineBasicBlock >::recalculate(), and llvm::DominatorTreeBase< MachineBasicBlock >::reset().
template<class NodeT> DenseMap<NodeT *, NodeT *> llvm::DominatorTreeBase< NodeT >::IDoms [protected]
Definition at line 232 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< MachineBasicBlock >::getIDom(), llvm::DominatorTreeBase< MachineBasicBlock >::operator=(), llvm::DominatorTreeBase< MachineBasicBlock >::recalculate(), and llvm::DominatorTreeBase< MachineBasicBlock >::reset().
template<class NodeT> DenseMap<NodeT *, InfoRec> llvm::DominatorTreeBase< NodeT >::Info [protected]
Definition at line 238 of file GenericDomTree.h.
Referenced by llvm::DFSPass(), llvm::Eval(), and llvm::DominatorTreeBase< MachineBasicBlock >::operator=().
template<class NodeT> DomTreeNodeBase<NodeT>* llvm::DominatorTreeBase< NodeT >::RootNode [protected]
Definition at line 218 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< MachineBasicBlock >::getRootNode(), llvm::DominatorTreeBase< MachineBasicBlock >::operator=(), and llvm::DominatorTreeBase< MachineBasicBlock >::reset().
template<class NodeT> unsigned int llvm::DominatorTreeBase< NodeT >::SlowQueries [mutable, protected]
Definition at line 221 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< MachineBasicBlock >::dominates(), llvm::DominatorTreeBase< MachineBasicBlock >::operator=(), llvm::DominatorTreeBase< MachineBasicBlock >::print(), llvm::DominatorTreeBase< MachineBasicBlock >::reset(), and llvm::DominatorTreeBase< MachineBasicBlock >::updateDFSNumbers().
template<class NodeT> std::vector<NodeT *> llvm::DominatorTreeBase< NodeT >::Vertex [protected]
Definition at line 235 of file GenericDomTree.h.
Referenced by llvm::DFSPass(), llvm::Eval(), llvm::DominatorTreeBase< MachineBasicBlock >::operator=(), llvm::DominatorTreeBase< MachineBasicBlock >::recalculate(), and llvm::DominatorTreeBase< MachineBasicBlock >::reset().
The documentation for this class was generated from the following file:
GenericDomTree.h