LLVM: llvm::AttrBuilder Class Reference
llvm::AttrBuilder Class Reference
#include <Attributes.h>
Public Types
typedef std::pair< std::string,
std::string > td_type
typedef std::map< std::string,
std::string >::iterator td_iterator
typedef std::map< std::string,
std::string >::const_iterator td_const_iterator
typedef llvm::iterator_range
< td_iterator > td_range
typedef llvm::iterator_range
< td_const_iterator > td_const_range
Public Member Functions
AttrBuilder ()
AttrBuilder (uint64_t Val)
AttrBuilder (const Attribute &A)
AttrBuilder (AttributeSet AS, unsigned Idx)
void clear ()
AttrBuilder & addAttribute (Attribute::AttrKind Val)
Add an attribute to the builder.
AttrBuilder & addAttribute (Attribute A)
Add the Attribute object to the builder.
AttrBuilder & addAttribute (StringRef A, StringRef V=StringRef())
Add the target-dependent attribute to the builder.
AttrBuilder & removeAttribute (Attribute::AttrKind Val)
Remove an attribute from the builder.
AttrBuilder & removeAttributes (AttributeSet A, uint64_t Index)
Remove the attributes from the builder.
AttrBuilder & removeAttribute (StringRef A)
Remove the target-dependent attribute to the builder.
AttrBuilder & merge (const AttrBuilder &B)
Add the attributes from the builder.
AttrBuilder & remove (const AttrBuilder &B)
Remove the attributes from the builder.
bool overlaps (const AttrBuilder &B) const
Return true if the builder has any attribute that's in the specified builder.
bool contains (Attribute::AttrKind A) const
Return true if the builder has the specified attribute.
bool contains (StringRef A) const
Return true if the builder has the specified target-dependent attribute.
bool hasAttributes () const
Return true if the builder has IR-level attributes.
bool hasAttributes (AttributeSet A, uint64_t Index) const
Return true if the builder has any attribute that's in the specified attribute.
bool hasAlignmentAttr () const
Return true if the builder has an alignment attribute.
uint64_t getAlignment () const
Retrieve the alignment attribute, if it exists.
uint64_t getStackAlignment () const
Retrieve the stack alignment attribute, if it exists.
uint64_t getDereferenceableBytes () const
Retrieve the number of dereferenceable bytes, if the dereferenceable attribute exists (zero is returned otherwise).
uint64_t getDereferenceableOrNullBytes () const
Retrieve the number of dereferenceable_or_null bytes, if the dereferenceable_or_null attribute exists (zero is returned otherwise).
AttrBuilder & addAlignmentAttr (unsigned Align)
This turns an int alignment (which must be a power of 2) into the form used internally in Attribute.
AttrBuilder & addStackAlignmentAttr (unsigned Align)
This turns an int stack alignment (which must be a power of 2) into the form used internally in Attribute.
AttrBuilder & addDereferenceableAttr (uint64_t Bytes)
This turns the number of dereferenceable bytes into the form used internally in Attribute.
AttrBuilder & addDereferenceableOrNullAttr (uint64_t Bytes)
This turns the number of dereferenceable_or_null bytes into the form used internally in Attribute.
bool empty () const
Return true if the builder contains no target-independent attributes.
td_iterator td_begin ()
td_iterator td_end ()
td_const_iterator td_begin () const
td_const_iterator td_end () const
td_range td_attrs ()
td_const_range td_attrs () const
bool td_empty () const
bool operator== (const AttrBuilder &B)
bool operator!= (const AttrBuilder &B)
AttrBuilder & addRawValue (uint64_t Val)
Add the raw value to the internal representation.
Detailed Description
Definition at line 433 of file Attributes.h.
Member Typedef Documentation
typedef std::map<std::string, std::string>::const_iterator llvm::AttrBuilder::td_const_iterator
Definition at line 543 of file Attributes.h.
typedef llvm::iterator_range<td_const_iterator> llvm::AttrBuilder::td_const_range
Definition at line 545 of file Attributes.h.
typedef std::map<std::string, std::string>::iterator llvm::AttrBuilder::td_iterator
Definition at line 542 of file Attributes.h.
typedef llvm::iterator_range<td_iterator> llvm::AttrBuilder::td_range
Definition at line 544 of file Attributes.h.
typedef std::pair<std::string, std::string> llvm::AttrBuilder::td_type
Definition at line 541 of file Attributes.h.
Constructor & Destructor Documentation
llvm::AttrBuilder::AttrBuilder () [inline]
Definition at line 441 of file Attributes.h.
llvm::AttrBuilder::AttrBuilder (uint64_t Val) [inline, explicit]
Definition at line 444 of file Attributes.h.
References addRawValue().
llvm::AttrBuilder::AttrBuilder (const Attribute & A) [inline]
Definition at line 449 of file Attributes.h.
References addAttribute().
AttrBuilder::AttrBuilder (AttributeSet AS, unsigned Idx)
Definition at line 1090 of file Attributes.cpp.
References addAttribute(), llvm::AttributeSetImpl::begin(), llvm::AttributeSetImpl::end(), llvm::AttributeSetImpl::getNumAttributes(), llvm::AttributeSetImpl::getSlotIndex(), I, and llvm::ARM_PROC::IE.
Member Function Documentation
AttrBuilder & AttrBuilder::addAlignmentAttr (unsigned Align)
This turns an int alignment (which must be a power of 2) into the form used internally in Attribute.
Definition at line 1205 of file Attributes.cpp.
References Align(), llvm::Attribute::Alignment, and llvm::isPowerOf2_32().
Referenced by decodeLLVMAttributesForBitcode(), getParameterABIAttributes(), LLVMSetInstrParamAlignment(), and LLVMSetParamAlignment().
AttrBuilder & AttrBuilder::addAttribute (Attribute::AttrKind Val)
Add an attribute to the builder.
Definition at line 1112 of file Attributes.cpp.
References llvm::Attribute::Alignment, llvm::Attribute::Dereferenceable, llvm::Attribute::EndAttrKinds, and llvm::Attribute::StackAlignment.
Referenced by llvm::AttributeSet::addAttribute(), addAttribute(), llvm::AttributeSet::addAttributes(), AdjustCallerSSPLevel(), AttrBuilder(), getParameterABIAttributes(), LLVMAddTargetDependentFunctionAttr(), RemoveDerefAttrAtIndex(), ReplaceWithStatepoint(), and llvm::AttributeFuncs::typeIncompatible().
AttrBuilder & AttrBuilder::addAttribute (Attribute A)
Add the Attribute object to the builder.
Definition at line 1121 of file Attributes.cpp.
References addAttribute(), llvm::Attribute::Alignment, llvm::Attribute::Dereferenceable, llvm::Attribute::DereferenceableOrNull, llvm::Attribute::getAlignment(), llvm::Attribute::getDereferenceableBytes(), llvm::Attribute::getDereferenceableOrNullBytes(), llvm::Attribute::getKindAsEnum(), llvm::Attribute::getKindAsString(), llvm::Attribute::getStackAlignment(), llvm::Attribute::getValueAsString(), llvm::Attribute::isStringAttribute(), Kind, and llvm::Attribute::StackAlignment.
AttrBuilder & AttrBuilder::addAttribute (StringRef A, StringRef V = StringRef())
Add the target-dependent attribute to the builder.
Definition at line 1141 of file Attributes.cpp.
References llvm::ARM_PROC::A.
AttrBuilder & AttrBuilder::addDereferenceableAttr (uint64_t Bytes)
This turns the number of dereferenceable bytes into the form used internally in Attribute.
Definition at line 1228 of file Attributes.cpp.
References llvm::Attribute::Dereferenceable.
Referenced by llvm::AttributeSet::addDereferenceableAttr(), and llvm::AttributeFuncs::typeIncompatible().
AttrBuilder & AttrBuilder::addDereferenceableOrNullAttr (uint64_t Bytes)
This turns the number of dereferenceable_or_null bytes into the form used internally in Attribute.
Definition at line 1236 of file Attributes.cpp.
References llvm::Attribute::DereferenceableOrNull.
Referenced by llvm::AttributeSet::addDereferenceableOrNullAttr(), and llvm::AttributeFuncs::typeIncompatible().
AttrBuilder & AttrBuilder::addRawValue (uint64_t Val)
Add the raw value to the internal representation.
Definition at line 1352 of file Attributes.cpp.
References llvm::ARM_PROC::A, llvm::Attribute::Alignment, llvm::Attribute::Dereferenceable, llvm::Attribute::DereferenceableOrNull, llvm::Attribute::EndAttrKinds, llvm::AttributeImpl::getAttrMask(), I, llvm::Attribute::None, and llvm::Attribute::StackAlignment.
Referenced by AttrBuilder(), and decodeLLVMAttributesForBitcode().
AttrBuilder & AttrBuilder::addStackAlignmentAttr (unsigned Align)
This turns an int stack alignment (which must be a power of 2) into the form used internally in Attribute.
Definition at line 1216 of file Attributes.cpp.
References Align(), llvm::isPowerOf2_32(), and llvm::Attribute::StackAlignment.
void AttrBuilder::clear ()
Definition at line 1107 of file Attributes.cpp.
bool llvm::AttrBuilder::contains (Attribute::AttrKind A) const [inline]
Return true if the builder has the specified attribute.
Definition at line 487 of file Attributes.h.
References llvm::ARM_PROC::A, and llvm::Attribute::EndAttrKinds.
Referenced by llvm::AttributeSet::get(), and overlaps().
bool AttrBuilder::contains (StringRef A) const
Return true if the builder has the specified target-dependent attribute.
Definition at line 1302 of file Attributes.cpp.
bool llvm::AttrBuilder::empty () const [inline]
Return true if the builder contains no target-independent attributes.
Definition at line 538 of file Attributes.h.
Referenced by RemoveDerefAttrAtIndex().
uint64_t llvm::AttrBuilder::getAlignment () const [inline]
Retrieve the alignment attribute, if it exists.
Definition at line 507 of file Attributes.h.
Referenced by llvm::AttributeSet::get().
uint64_t llvm::AttrBuilder::getDereferenceableBytes () const [inline]
Retrieve the number of dereferenceable bytes, if the dereferenceable attribute exists (zero is returned otherwise).
Definition at line 514 of file Attributes.h.
Referenced by llvm::AttributeSet::get().
uint64_t llvm::AttrBuilder::getDereferenceableOrNullBytes () const [inline]
Retrieve the number of dereferenceable_or_null bytes, if the dereferenceable_or_null attribute exists (zero is returned otherwise).
Definition at line 518 of file Attributes.h.
Referenced by llvm::AttributeSet::get().
uint64_t llvm::AttrBuilder::getStackAlignment () const [inline]
Retrieve the stack alignment attribute, if it exists.
Definition at line 510 of file Attributes.h.
Referenced by llvm::AttributeSet::get().
bool AttrBuilder::hasAlignmentAttr () const
Return true if the builder has an alignment attribute.
Definition at line 1335 of file Attributes.cpp.
Referenced by llvm::AttributeSet::removeAttributes().
bool AttrBuilder::hasAttributes () const
Return true if the builder has IR-level attributes.
Definition at line 1306 of file Attributes.cpp.
Referenced by llvm::AttributeSet::get().
bool AttrBuilder::hasAttributes (AttributeSet A, uint64_t Index) const
Return true if the builder has any attribute that's in the specified attribute.
Definition at line 1310 of file Attributes.cpp.
References llvm::AttributeSet::begin(), llvm::AttributeSet::end(), llvm::Attribute::getKindAsString(), llvm::AttributeSet::getNumSlots(), llvm::AttributeSet::getSlotIndex(), I, llvm::Attribute::isEnumAttribute(), llvm::Attribute::isIntAttribute(), llvm::Attribute::isStringAttribute(), and llvm::Slot.
AttrBuilder & AttrBuilder::merge (const AttrBuilder & B)
Add the attributes from the builder.
Definition at line 1245 of file Attributes.cpp.
References I, and td_attrs().
bool llvm::AttrBuilder::operator!= (const AttrBuilder & B) [inline]
Definition at line 561 of file Attributes.h.
bool AttrBuilder::operator== (const AttrBuilder & B)
Definition at line 1339 of file Attributes.cpp.
References I.
bool AttrBuilder::overlaps (const AttrBuilder & B) const
Return true if the builder has any attribute that's in the specified builder.
Definition at line 1289 of file Attributes.cpp.
References contains(), I, and td_attrs().
AttrBuilder & AttrBuilder::remove (const AttrBuilder & B)
Remove the attributes from the builder.
Definition at line 1267 of file Attributes.cpp.
References I, and td_attrs().
Referenced by llvm::AttributeSet::removeAttributes().
AttrBuilder & AttrBuilder::removeAttribute (Attribute::AttrKind Val)
Remove an attribute from the builder.
Definition at line 1146 of file Attributes.cpp.
References llvm::Attribute::Alignment, llvm::Attribute::Dereferenceable, llvm::Attribute::DereferenceableOrNull, llvm::Attribute::EndAttrKinds, and llvm::Attribute::StackAlignment.
AttrBuilder & AttrBuilder::removeAttribute (StringRef A)
Remove the target-dependent attribute to the builder.
Definition at line 1198 of file Attributes.cpp.
References I.
AttrBuilder & AttrBuilder::removeAttributes (AttributeSet A, uint64_t Index)
Remove the attributes from the builder.
Definition at line 1162 of file Attributes.cpp.
References llvm::Attribute::Alignment, llvm::AttributeSet::begin(), llvm::Attribute::Dereferenceable, llvm::Attribute::DereferenceableOrNull, llvm::AttributeSet::end(), llvm::Attribute::getKindAsString(), llvm::AttributeSet::getNumSlots(), llvm::AttributeSet::getSlotIndex(), I, llvm::Attribute::isEnumAttribute(), llvm::Attribute::isIntAttribute(), llvm::Attribute::isStringAttribute(), Kind, llvm::Slot, and llvm::Attribute::StackAlignment.
Referenced by llvm::AttributeSet::removeAttributes().
td_range llvm::AttrBuilder::td_attrs () [inline]
Definition at line 553 of file Attributes.h.
References td_begin(), and td_end().
Referenced by llvm::AttributeSet::get(), merge(), overlaps(), and remove().
td_const_range llvm::AttrBuilder::td_attrs () const [inline]
Definition at line 554 of file Attributes.h.
References td_begin(), and td_end().
td_iterator llvm::AttrBuilder::td_begin () [inline]
Definition at line 547 of file Attributes.h.
Referenced by td_attrs().
td_const_iterator llvm::AttrBuilder::td_begin () const [inline]
Definition at line 550 of file Attributes.h.
bool llvm::AttrBuilder::td_empty () const [inline]
Definition at line 558 of file Attributes.h.
td_iterator llvm::AttrBuilder::td_end () [inline]
Definition at line 548 of file Attributes.h.
Referenced by td_attrs().
td_const_iterator llvm::AttrBuilder::td_end () const [inline]
Definition at line 551 of file Attributes.h.
The documentation for this class was generated from the following files:
Attributes.h
Attributes.cpp