LLVM: llvm::MCAsmInfoDarwin Class Reference
llvm::MCAsmInfoDarwin Class Reference
#include <MCAsmInfoDarwin.h>
Public Member Functions
MCAsmInfoDarwin ()
bool isSectionAtomizableBySymbols (const MCSection &Section) const override
True if the section is atomized using the symbols in it.
Detailed Description
Definition at line 21 of file MCAsmInfoDarwin.h.
Constructor & Destructor Documentation
MCAsmInfoDarwin::MCAsmInfoDarwin () [explicit]
Definition at line 58 of file MCAsmInfoDarwin.cpp.
References llvm::MCAsmInfo::AlignmentIsInBytes, llvm::MCAsmInfo::COMMDirectiveAlignmentIsInBytes, llvm::MCAsmInfo::DwarfUsesRelocationsAcrossSections, llvm::MCAsmInfo::HasAggressiveSymbolFolding, llvm::MCAsmInfo::HasDotTypeDotSizeDirective, llvm::MCAsmInfo::HasMachoTBSSDirective, llvm::MCAsmInfo::HasMachoZeroFillDirective, llvm::MCAsmInfo::HasNoDeadStrip, llvm::MCAsmInfo::HasSingleParameterDotFile, llvm::MCAsmInfo::HasStaticCtorDtorReferenceInStaticMode, llvm::MCAsmInfo::HasSubsectionsViaSymbols, llvm::MCAsmInfo::HasWeakDefCanBeHiddenDirective, llvm::MCAsmInfo::HasWeakDefDirective, llvm::MCAsmInfo::HiddenDeclarationVisibilityAttr, llvm::MCAsmInfo::HiddenVisibilityAttr, llvm::MCAsmInfo::InlineAsmEnd, llvm::MCAsmInfo::InlineAsmStart, llvm::MCAsmInfo::LCOMMDirectiveAlignmentType, llvm::MCAsmInfo::LinkerPrivateGlobalPrefix, llvm::LCOMM::Log2Alignment, llvm::MCSA_Invalid, llvm::MCSA_PrivateExtern, llvm::MCAsmInfo::ProtectedVisibilityAttr, llvm::MCAsmInfo::SetDirectiveSuppressesReloc, llvm::MCAsmInfo::UseIntegratedAssembler, llvm::MCAsmInfo::UseLogicalShr, llvm::MCAsmInfo::WeakRefDirective, and llvm::MCAsmInfo::ZeroDirective.
Member Function Documentation
bool MCAsmInfoDarwin::isSectionAtomizableBySymbols (const MCSection & Section) const [override, virtual]
True if the section is atomized using the symbols in it.
This is false if the section is not atomized at all (most ELF sections) or if it is atomized based on its contents (MachO' __TEXT,__cstring for example).
Reimplemented from llvm::MCAsmInfo.
Definition at line 21 of file MCAsmInfoDarwin.cpp.
References llvm::MCSectionMachO::getSectionName(), llvm::MCSectionMachO::getSegmentName(), llvm::MCSectionMachO::getType(), llvm::MachO::S_16BYTE_LITERALS, llvm::MachO::S_4BYTE_LITERALS, llvm::MachO::S_8BYTE_LITERALS, llvm::MachO::S_CSTRING_LITERALS, llvm::MachO::S_INTERPOSING, llvm::MachO::S_LAZY_SYMBOL_POINTERS, llvm::MachO::S_LITERAL_POINTERS, llvm::MachO::S_MOD_INIT_FUNC_POINTERS, llvm::MachO::S_MOD_TERM_FUNC_POINTERS, llvm::MachO::S_NON_LAZY_SYMBOL_POINTERS, and llvm::ARMBuildAttrs::Section.
The documentation for this class was generated from the following files:
MCAsmInfoDarwin.h
MCAsmInfoDarwin.cpp