LLVM: llvm::DIEnumerator Class Reference
llvm::DIEnumerator Class Reference
Enumeration value.
#include <DebugInfoMetadata.h>
Public Member Functions
DEFINE_MDNODE_GET (DIEnumerator,(int64_t Value, StringRef Name),(Value, Name)) DEFINE_MDNODE_GET(DIEnumerator
int64_t MDString Name
TempDIEnumerator clone () const
Create a (temporary) clone of this.
int64_t getValue () const
StringRef getName () const
MDString * getRawName () const
Static Public Member Functions
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
Public Attributes
int64_t MDString * Name
int64_t MDString Value
Friends
class LLVMContextImpl
class MDNode
Detailed Description
Enumeration value.
TODO: Add a pointer to the context (DW_TAG_enumeration_type) once that no longer creates a type cycle.
Definition at line 353 of file DebugInfoMetadata.h.
Member Function Documentation
static bool llvm::DIEnumerator::classof (const Metadata * MD) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::DINode.
Definition at line 392 of file DebugInfoMetadata.h.
References llvm::Metadata::DIEnumeratorKind, and llvm::Metadata::getMetadataID().
int64_t MDString Name TempDIEnumerator llvm::DIEnumerator::clone () const [inline]
Create a (temporary) clone of this.
Reimplemented from llvm::MDNode.
Definition at line 385 of file DebugInfoMetadata.h.
llvm::DIEnumerator::DEFINE_MDNODE_GET (DIEnumerator , (int64_t Value, StringRef Name) , (Value, Name))
StringRef llvm::DIEnumerator::getName () const [inline]
Definition at line 388 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
Referenced by llvm::MDNodeKeyImpl< DIEnumerator >::isKeyOf().
MDString* llvm::DIEnumerator::getRawName () const [inline]
Definition at line 390 of file DebugInfoMetadata.h.
Referenced by WriteDIEnumerator().
int64_t llvm::DIEnumerator::getValue () const [inline]
Definition at line 387 of file DebugInfoMetadata.h.
Referenced by llvm::MDNodeKeyImpl< DIEnumerator >::isKeyOf(), and WriteDIEnumerator().
Friends And Related Function Documentation
friend class LLVMContextImpl [friend]
Reimplemented from llvm::DINode.
Definition at line 354 of file DebugInfoMetadata.h.
friend class MDNode [friend]
Reimplemented from llvm::DINode.
Definition at line 355 of file DebugInfoMetadata.h.
Member Data Documentation
int64_t MDString* llvm::DIEnumerator::Name
Definition at line 382 of file DebugInfoMetadata.h.
int64_t MDString llvm::DIEnumerator::Value
Definition at line 382 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
DebugInfoMetadata.h
DebugInfoMetadata.cpp