LLVM: llvm::Triple Class Reference
llvm::Triple Class Reference
Triple - Helper class for working with autoconf configuration names.
#include <Triple.h>
Public Types
enum ArchType {
UnknownArch, arm, armeb, aarch64,
aarch64_be, bpfel, bpfeb, hexagon,
mips, mipsel, mips64, mips64el,
msp430, ppc, ppc64, ppc64le,
r600, amdgcn, sparc, sparcv9,
sparcel, systemz, tce, thumb,
thumbeb, x86, x86_64, xcore,
nvptx, nvptx64, le32, le64,
amdil, amdil64, hsail, hsail64,
spir, spir64, kalimba, shave,
LastArchType = shave
}
enum SubArchType {
NoSubArch, ARMSubArch_v8_1a, ARMSubArch_v8, ARMSubArch_v7,
ARMSubArch_v7em, ARMSubArch_v7m, ARMSubArch_v7s, ARMSubArch_v6,
ARMSubArch_v6m, ARMSubArch_v6k, ARMSubArch_v6t2, ARMSubArch_v5,
ARMSubArch_v5te, ARMSubArch_v4t, KalimbaSubArch_v3, KalimbaSubArch_v4,
KalimbaSubArch_v5
}
enum VendorType {
UnknownVendor, Apple, PC, SCEI,
BGP, BGQ, Freescale, IBM,
ImaginationTechnologies, MipsTechnologies, NVIDIA, CSR,
LastVendorType = CSR
}
enum OSType {
UnknownOS, CloudABI, Darwin, DragonFly,
FreeBSD, IOS, KFreeBSD, Linux,
Lv2, MacOSX, NetBSD, OpenBSD,
Solaris, Win32, Haiku, Minix,
RTEMS, NaCl, CNK, Bitrig,
AIX, CUDA, NVCL, AMDHSA,
PS4, LastOSType = PS4
}
enum EnvironmentType {
UnknownEnvironment, GNU, GNUEABI, GNUEABIHF,
GNUX32, CODE16, EABI, EABIHF,
Android, MSVC, Itanium, Cygnus,
LastEnvironmentType = Cygnus
}
enum ObjectFormatType { UnknownObjectFormat, COFF, ELF, MachO }
Public Member Functions
std::string normalize () const
Return the normalized form of this triple's string.
ArchType getArch () const
getArch - Get the parsed architecture type of this triple.
SubArchType getSubArch () const
getSubArch - get the parsed subarchitecture type for this triple.
VendorType getVendor () const
getVendor - Get the parsed vendor type of this triple.
OSType getOS () const
getOS - Get the parsed operating system type of this triple.
bool hasEnvironment () const
hasEnvironment - Does this triple have the optional environment (fourth) component?
EnvironmentType getEnvironment () const
getEnvironment - Get the parsed environment type of this triple.
void getEnvironmentVersion (unsigned &Major, unsigned &Minor, unsigned &Micro) const
Parse the version number from the OS name component of the triple, if present.
ObjectFormatType getObjectFormat () const
getFormat - Get the object format for this triple.
void getOSVersion (unsigned &Major, unsigned &Minor, unsigned &Micro) const
getOSVersion - Parse the version number from the OS name component of the triple, if present.
unsigned getOSMajorVersion () const
getOSMajorVersion - Return just the major version number, this is specialized because it is a common query.
bool getMacOSXVersion (unsigned &Major, unsigned &Minor, unsigned &Micro) const
getMacOSXVersion - Parse the version number as with getOSVersion and then translate generic "darwin" versions to the corresponding OS X versions.
void getiOSVersion (unsigned &Major, unsigned &Minor, unsigned &Micro) const
getiOSVersion - Parse the version number as with getOSVersion.
const std::string & str () const
const std::string & getTriple () const
StringRef getArchName () const
getArchName - Get the architecture (first) component of the triple.
StringRef getVendorName () const
getVendorName - Get the vendor (second) component of the triple.
StringRef getOSName () const
getOSName - Get the operating system (third) component of the triple.
StringRef getEnvironmentName () const
getEnvironmentName - Get the optional environment (fourth) component of the triple, or "" if empty.
StringRef getOSAndEnvironmentName () const
getOSAndEnvironmentName - Get the operating system and optional environment components as a single string (separated by a '-' if the environment component is present).
bool isArch64Bit () const
Test whether the architecture is 64-bit.
bool isArch32Bit () const
Test whether the architecture is 32-bit.
bool isArch16Bit () const
Test whether the architecture is 16-bit.
bool isOSVersionLT (unsigned Major, unsigned Minor=0, unsigned Micro=0) const
isOSVersionLT - Helper function for doing comparisons against version numbers included in the target triple.
bool isOSVersionLT (const Triple &Other) const
unsigned isMacOSXVersionLT (unsigned Major, unsigned Minor=0, unsigned Micro=0) const
isMacOSXVersionLT - Comparison function for checking OS X version compatibility, which handles supporting skewed version numbering schemes used by the "darwin" triples.
bool isMacOSX () const
isMacOSX - Is this a Mac OS X triple.
bool isiOS () const
Is this an iOS triple.
bool isOSDarwin () const
isOSDarwin - Is this a "Darwin" OS (OS X or iOS).
bool isOSNetBSD () const
bool isOSOpenBSD () const
bool isOSFreeBSD () const
bool isOSDragonFly () const
bool isOSSolaris () const
bool isOSBitrig () const
bool isWindowsMSVCEnvironment () const
bool isKnownWindowsMSVCEnvironment () const
bool isWindowsItaniumEnvironment () const
bool isWindowsCygwinEnvironment () const
bool isWindowsGNUEnvironment () const
bool isOSCygMing () const
Tests for either Cygwin or MinGW OS.
bool isOSMSVCRT () const
Is this a "Windows" OS targeting a "MSVCRT.dll" environment.
bool isOSWindows () const
Tests whether the OS is Windows.
bool isOSNaCl () const
Tests whether the OS is NaCl (Native Client)
bool isOSLinux () const
Tests whether the OS is Linux.
bool isOSBinFormatELF () const
Tests whether the OS uses the ELF binary format.
bool isOSBinFormatCOFF () const
Tests whether the OS uses the COFF binary format.
bool isOSBinFormatMachO () const
Tests whether the environment is MachO.
bool isPS4CPU () const
Tests whether the target is the PS4 CPU.
bool isPS4 () const
Tests whether the target is the PS4 platform.
void setArch (ArchType Kind)
setArch - Set the architecture (first) component of the triple to a known type.
void setVendor (VendorType Kind)
setVendor - Set the vendor (second) component of the triple to a known type.
void setOS (OSType Kind)
setOS - Set the operating system (third) component of the triple to a known type.
void setEnvironment (EnvironmentType Kind)
setEnvironment - Set the environment (fourth) component of the triple to a known type.
void setObjectFormat (ObjectFormatType Kind)
setObjectFormat - Set the object file format
void setTriple (const Twine &Str)
setTriple - Set all components to the new triple Str.
void setArchName (StringRef Str)
setArchName - Set the architecture (first) component of the triple by name.
void setVendorName (StringRef Str)
setVendorName - Set the vendor (second) component of the triple by name.
void setOSName (StringRef Str)
setOSName - Set the operating system (third) component of the triple by name.
void setEnvironmentName (StringRef Str)
setEnvironmentName - Set the optional environment (fourth) component of the triple by name.
void setOSAndEnvironmentName (StringRef Str)
setOSAndEnvironmentName - Set the operating system and optional environment components with a single string.
llvm::Triple get32BitArchVariant () const
Form a triple with a 32-bit variant of the current architecture.
llvm::Triple get64BitArchVariant () const
Form a triple with a 64-bit variant of the current architecture.
const char * getARMCPUForArch (StringRef Arch=StringRef()) const
Get the (LLVM) name of the minimum ARM CPU for the arch we are targeting.
Constructors
Triple ()
Default constructor is the same as an empty string and leaves all triple fields unknown.
Triple (const Twine &Str)
Construct a triple from the string representation provided.
Triple (const Twine &ArchStr, const Twine &VendorStr, const Twine &OSStr)
Construct a triple from string representations of the architecture, vendor, and OS.
Triple (const Twine &ArchStr, const Twine &VendorStr, const Twine &OSStr, const Twine &EnvironmentStr)
Construct a triple from string representations of the architecture, vendor, OS, and environment.
bool operator== (const Triple &Other) const
Static Public Member Functions
static std::string normalize (StringRef Str)
normalize - Turn an arbitrary machine specification into the canonical triple form (or something sensible that the Triple class understands if nothing better can reasonably be done).
static const char * getArchTypeName (ArchType Kind)
getArchTypeName - Get the canonical name for the Kind architecture.
static const char * getArchTypePrefix (ArchType Kind)
getArchTypePrefix - Get the "prefix" canonical name for the Kind architecture.
static const char * getVendorTypeName (VendorType Kind)
getVendorTypeName - Get the canonical name for the Kind vendor.
static const char * getOSTypeName (OSType Kind)
getOSTypeName - Get the canonical name for the Kind operating system.
static const char * getEnvironmentTypeName (EnvironmentType Kind)
getEnvironmentTypeName - Get the canonical name for the Kind environment.
static ArchType getArchTypeForLLVMName (StringRef Str)
getArchTypeForLLVMName - The canonical type for the given LLVM architecture name (e.g., "x86").
Detailed Description
Triple - Helper class for working with autoconf configuration names.
For historical reasons, we also call these 'triples' (they used to contain exactly three fields).
Configuration names are strings in the canonical form: ARCHITECTURE-VENDOR-OPERATING_SYSTEM or ARCHITECTURE-VENDOR-OPERATING_SYSTEM-ENVIRONMENT
This class is used for clients which want to support arbitrary configuration names, but also want to implement certain special behavior for particular configurations. This class isolates the mapping from the components of the configuration name to well known IDs.
At its core the Triple class is designed to be a wrapper for a triple string; the constructor does not change or normalize the triple string. Clients that need to handle the non-canonical triples that users often specify should use the normalize method.
See autoconf/config.guess for a glimpse into what configuration names look like in practice.
Definition at line 44 of file Triple.h.
Member Enumeration Documentation
enum llvm::Triple::ArchType
Enumerator:
UnknownArch
arm
armeb
aarch64
aarch64_be
bpfel
bpfeb
hexagon
mips
mipsel
mips64
mips64el
msp430
ppc
ppc64
ppc64le
r600
amdgcn
sparc
sparcv9
sparcel
systemz
tce
thumb
thumbeb
x86
x86_64
xcore
nvptx
nvptx64
le32
le64
amdil
amdil64
hsail
hsail64
spir
spir64
kalimba
shave
LastArchType
Definition at line 46 of file Triple.h.
enum llvm::Triple::EnvironmentType
Enumerator:
UnknownEnvironment
GNU
GNUEABI
GNUEABIHF
GNUX32
CODE16
EABI
EABIHF
Android
MSVC
Itanium
Cygnus
LastEnvironmentType
Definition at line 156 of file Triple.h.
enum llvm::Triple::ObjectFormatType
Enumerator:
UnknownObjectFormat
COFF
ELF
MachO
Definition at line 173 of file Triple.h.
enum llvm::Triple::OSType
Enumerator:
UnknownOS
CloudABI
Darwin
DragonFly
FreeBSD
IOS
KFreeBSD
Linux
Lv2
MacOSX
NetBSD
OpenBSD
Solaris
Win32
Haiku
Minix
RTEMS
NaCl
CNK
Bitrig
AIX
CUDA
NVCL
AMDHSA
PS4
LastOSType
Definition at line 127 of file Triple.h.
enum llvm::Triple::SubArchType
Enumerator:
NoSubArch
ARMSubArch_v8_1a
ARMSubArch_v8
ARMSubArch_v7
ARMSubArch_v7em
ARMSubArch_v7m
ARMSubArch_v7s
ARMSubArch_v6
ARMSubArch_v6m
ARMSubArch_v6k
ARMSubArch_v6t2
ARMSubArch_v5
ARMSubArch_v5te
ARMSubArch_v4t
KalimbaSubArch_v3
KalimbaSubArch_v4
KalimbaSubArch_v5
Definition at line 90 of file Triple.h.
enum llvm::Triple::VendorType
Enumerator:
UnknownVendor
Apple
PC
SCEI
BGP
BGQ
Freescale
IBM
ImaginationTechnologies
MipsTechnologies
NVIDIA
CSR
LastVendorType
Definition at line 111 of file Triple.h.
Constructor & Destructor Documentation
llvm::Triple::Triple () [inline]
Default constructor is the same as an empty string and leaves all triple fields unknown.
Definition at line 208 of file Triple.h.
Referenced by setArchName(), and setTriple().
Triple::Triple (const Twine & Str) [explicit]
Construct a triple from the string representation provided.
This stores the string representation and parses the various pieces into enum members.
Definition at line 543 of file Triple.cpp.
References getDefaultFormat(), and UnknownObjectFormat.
Triple::Triple (const Twine & ArchStr, const Twine & VendorStr, const Twine & OSStr)
Construct a triple from string representations of the architecture, vendor, and OS.
This joins each argument into a canonical string representation and parses them into enum members. It leaves the environment unknown and omits it from the string representation.
Definition at line 561 of file Triple.cpp.
References getDefaultFormat().
Triple::Triple (const Twine & ArchStr, const Twine & VendorStr, const Twine & OSStr, const Twine & EnvironmentStr)
Construct a triple from string representations of the architecture, vendor, OS, and environment.
This joins each argument into a canonical string representation and parses them into enum members.
Definition at line 576 of file Triple.cpp.
References getDefaultFormat(), and UnknownObjectFormat.
Member Function Documentation
Triple Triple::get32BitArchVariant () const
Form a triple with a 32-bit variant of the current architecture.
This can be used to move across "families" of architectures where useful.
Returns:
A new triple with a 32-bit architecture or an unknown architecture if no such variant can be found.
Definition at line 1048 of file Triple.cpp.
References aarch64, aarch64_be, amdgcn, amdil, amdil64, arm, armeb, bpfeb, bpfel, getArch(), hexagon, hsail, hsail64, kalimba, le32, le64, mips, mips64, mips64el, mipsel, msp430, nvptx, nvptx64, ppc, ppc64, ppc64le, r600, setArch(), shave, sparc, sparcel, sparcv9, spir, spir64, systemz, T, tce, thumb, thumbeb, UnknownArch, x86, x86_64, and xcore.
Referenced by llvm::sys::getProcessTriple().
Triple Triple::get64BitArchVariant () const
Form a triple with a 64-bit variant of the current architecture.
This can be used to move across "families" of architectures where useful.
Returns:
A new triple with a 64-bit architecture or an unknown architecture if no such variant can be found.
Definition at line 1101 of file Triple.cpp.
References aarch64, aarch64_be, amdgcn, amdil, amdil64, arm, armeb, bpfeb, bpfel, getArch(), hexagon, hsail, hsail64, kalimba, le32, le64, mips, mips64, mips64el, mipsel, msp430, nvptx, nvptx64, ppc, ppc64, ppc64le, r600, setArch(), shave, sparc, sparcel, sparcv9, spir, spir64, systemz, T, tce, thumb, thumbeb, UnknownArch, x86, x86_64, and xcore.
Referenced by llvm::sys::getProcessTriple().
ArchType llvm::Triple::getArch () const [inline]
getArch - Get the parsed architecture type of this triple.
Definition at line 236 of file Triple.h.
Referenced by llvm::AArch64MCAsmInfoELF::AArch64MCAsmInfoELF(), llvm::ARMELFMCAsmInfo::ARMELFMCAsmInfo(), llvm::ARMMCAsmInfoDarwin::ARMMCAsmInfoDarwin(), llvm::BPFMCAsmInfo::BPFMCAsmInfo(), computeDataLayout(), computeFSAdditions(), llvm::MipsABIInfo::computeTargetABI(), computeTargetABI(), llvm::createAMDGPUAsmBackend(), createELFStreamer(), llvm::createPPCAsmBackend(), createPPCMCAsmInfo(), createPPCMCCodeGenInfo(), createPPCMCRegisterInfo(), createSparcMCSubtargetInfo(), createTLOF(), createX86MCAsmInfo(), createX86MCCodeGenInfo(), createX86MCRegisterInfo(), createX86MCRelocationInfo(), EmitDarwinBCHeaderAndTrailer(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::ARMAsmPrinter::EmitStartOfAsmFile(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), get32BitArchVariant(), get64BitArchVariant(), getDataLayoutString(), getDefaultFormat(), llvm::SubtargetFeatures::getDefaultSubtargetFeatures(), llvm::X86_MC::getDwarfRegFlavour(), getiOSVersion(), llvm::ARMAsmPrinter::getISAEncoding(), llvm::DataLayout::getManglingComponent(), hasSinCosPiStret(), initialize(), llvm::AMDGPUSubtarget::initializeSubtargetDependencies(), llvm::MCObjectFileInfo::InitMCObjectFileInfo(), isArch16Bit(), isArch32Bit(), isArch64Bit(), llvm::PPCTargetMachine::isPPC64(), isPS4(), loadBinaryFormat(), llvm::TargetRegistry::lookupTarget(), llvm::MipsMCAsmInfo::MipsMCAsmInfo(), llvm::NVPTXMCAsmInfo::NVPTXMCAsmInfo(), llvm::ARM_MC::ParseARMTriple(), llvm::X86_MC::ParseX86Triple(), llvm::PPCELFMCAsmInfo::PPCELFMCAsmInfo(), llvm::MIPS_MC::selectMipsCPU(), llvm::EngineBuilder::selectTarget(), llvm::SparcELFMCAsmInfo::SparcELFMCAsmInfo(), triplesMatch(), useCompactUnwind(), llvm::X86ELFMCAsmInfo::X86ELFMCAsmInfo(), llvm::X86MCAsmInfoDarwin::X86MCAsmInfoDarwin(), llvm::X86MCAsmInfoGNUCOFF::X86MCAsmInfoGNUCOFF(), and llvm::X86MCAsmInfoMicrosoft::X86MCAsmInfoMicrosoft().
StringRef Triple::getArchName () const
getArchName - Get the architecture (first) component of the triple.
Definition at line 775 of file Triple.cpp.
References llvm::StringRef::split().
Referenced by llvm::createARMAsmBackend(), llvm::createX86_64AsmBackend(), llvm::object::MachOUniversalBinary::ObjectForArch::getArchTypeName(), getARMCPUForArch(), setEnvironmentName(), setOSAndEnvironmentName(), setOSName(), and setVendorName().
Triple::ArchType Triple::getArchTypeForLLVMName (StringRef Str) [static]
getArchTypeForLLVMName - The canonical type for the given LLVM architecture name (e.g., "x86").
Definition at line 215 of file Triple.cpp.
References aarch64, aarch64_be, amdgcn, amdil, amdil64, arm, armeb, llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), hexagon, hsail, hsail64, kalimba, le32, le64, mips, mips64, mips64el, mipsel, msp430, nvptx, nvptx64, parseBPFArch(), ppc, ppc64, ppc64le, r600, shave, sparc, sparcel, sparcv9, spir, spir64, llvm::StringSwitch< T, R >::StartsWith(), systemz, tce, thumb, thumbeb, UnknownArch, x86, x86_64, and xcore.
Referenced by llvm::TargetRegistry::lookupTarget(), and llvm::EngineBuilder::selectTarget().
const char * Triple::getArchTypeName (ArchType Kind) [static]
getArchTypeName - Get the canonical name for the Kind architecture.
Definition at line 20 of file Triple.cpp.
References aarch64, aarch64_be, amdgcn, amdil, amdil64, arm, armeb, bpfeb, bpfel, hexagon, hsail, hsail64, kalimba, le32, le64, llvm_unreachable, mips, mips64, mips64el, mipsel, msp430, nvptx, nvptx64, ppc, ppc64, ppc64le, r600, shave, sparc, sparcel, sparcv9, spir, spir64, systemz, tce, thumb, thumbeb, UnknownArch, x86, x86_64, and xcore.
Referenced by setArch().
const char * Triple::getArchTypePrefix (ArchType Kind) [static]
getArchTypePrefix - Get the "prefix" canonical name for the Kind architecture.
This is the prefix used by the architecture specific builtins, and is suitable for passing to
See also:
Intrinsic::getIntrinsicForGCCBuiltin().
Returns:
- The architecture prefix, or 0 if none is defined.
Definition at line 68 of file Triple.cpp.
References aarch64, aarch64_be, amdgcn, amdil, amdil64, arm, armeb, bpfeb, bpfel, hexagon, hsail, hsail64, kalimba, le32, le64, mips, mips64, mips64el, mipsel, nvptx, nvptx64, ppc, ppc64, ppc64le, r600, shave, sparc, sparcel, sparcv9, spir, spir64, systemz, thumb, thumbeb, x86, x86_64, and xcore.
const char * Triple::getARMCPUForArch (StringRef Arch = StringRef()) const
Get the (LLVM) name of the minimum ARM CPU for the arch we are targeting.
Parameters:
Arch the architecture name (e.g., "armv7s"). If it is an empty string then the triple's arch name is used.
Definition at line 1154 of file Triple.cpp.
References EABI, EABIHF, llvm::StringRef::empty(), FreeBSD, getArchName(), llvm::ARMTargetParser::getCanonicalArchName(), llvm::ARMTargetParser::getDefaultCPU(), getEnvironment(), getOS(), GNUEABI, GNUEABIHF, llvm_unreachable, NaCl, NetBSD, and Win32.
EnvironmentType llvm::Triple::getEnvironment () const [inline]
getEnvironment - Get the parsed environment type of this triple.
Definition at line 254 of file Triple.h.
Referenced by computeDataLayout(), computeTargetABI(), llvm::createX86_64AsmBackend(), getARMCPUForArch(), getEnvironmentVersion(), InitLibcallNames(), llvm::ARMSubtarget::isTargetAEABI(), llvm::ARMSubtarget::isTargetAndroid(), llvm::ARMSubtarget::isTargetEHABICompatible(), llvm::ARMSubtarget::isTargetHardFloat(), isWindowsCygwinEnvironment(), isWindowsGNUEnvironment(), llvm::X86_MC::ParseX86Triple(), and llvm::X86ELFMCAsmInfo::X86ELFMCAsmInfo().
StringRef Triple::getEnvironmentName () const
getEnvironmentName - Get the optional environment (fourth) component of the triple, or "" if empty.
Definition at line 790 of file Triple.cpp.
References llvm::StringRef::split().
Referenced by getEnvironmentVersion(), and setOSName().
const char * Triple::getEnvironmentTypeName (EnvironmentType Kind) [static]
getEnvironmentTypeName - Get the canonical name for the Kind environment.
Definition at line 181 of file Triple.cpp.
References Android, CODE16, Cygnus, EABI, EABIHF, GNU, GNUEABI, GNUEABIHF, GNUX32, Itanium, llvm_unreachable, MSVC, and UnknownEnvironment.
Referenced by getEnvironmentVersion(), setEnvironment(), and setObjectFormat().
void Triple::getEnvironmentVersion (unsigned & Major, unsigned & Minor, unsigned & Micro) const
Parse the version number from the OS name component of the triple, if present.
For example, "fooos1.2.3" would return (1, 2, 3).
If an entry is not defined, it will be returned as 0.
Definition at line 836 of file Triple.cpp.
References getEnvironment(), getEnvironmentName(), getEnvironmentTypeName(), parseVersionFromName(), llvm::StringRef::size(), llvm::StringRef::startswith(), and llvm::StringRef::substr().
void Triple::getiOSVersion (unsigned & Major, unsigned & Minor, unsigned & Micro) const
getiOSVersion - Parse the version number as with getOSVersion.
This should only be called with IOS triples.
Definition at line 896 of file Triple.cpp.
References aarch64, Darwin, getArch(), getOS(), getOSVersion(), IOS, llvm_unreachable, and MacOSX.
bool Triple::getMacOSXVersion (unsigned & Major, unsigned & Minor, unsigned & Micro) const
getMacOSXVersion - Parse the version number as with getOSVersion and then translate generic "darwin" versions to the corresponding OS X versions.
This may also be called with IOS triples but the OS X version number is just set to a constant 10.4.0 in that case. Returns true if successful.
Definition at line 857 of file Triple.cpp.
References Darwin, getOS(), getOSVersion(), IOS, llvm_unreachable, and MacOSX.
ObjectFormatType llvm::Triple::getObjectFormat () const [inline]
getFormat - Get the object format for this triple.
Definition at line 266 of file Triple.h.
Referenced by computeTargetABI(), llvm::createAArch64ObjectTargetStreamer(), llvm::createARMAsmBackend(), llvm::createARMObjectTargetStreamer(), llvm::Target::createMCObjectStreamer(), createObjectTargetStreamer(), llvm::MCObjectFileInfo::InitMCObjectFileInfo(), and llvm::ARMTargetLowering::LowerOperation().
OSType llvm::Triple::getOS () const [inline]
getOS - Get the parsed operating system type of this triple.
Definition at line 245 of file Triple.h.
Referenced by llvm::ARMELFMCAsmInfo::ARMELFMCAsmInfo(), computeTargetABI(), llvm::createAArch64beAsmBackend(), llvm::createAArch64leAsmBackend(), llvm::createARMAsmBackend(), llvm::createHexagonAsmBackend(), llvm::createMipsAsmBackendEB32(), llvm::createMipsAsmBackendEB64(), llvm::createMipsAsmBackendEL32(), llvm::createMipsAsmBackendEL64(), llvm::createPPCAsmBackend(), llvm::createSparcAsmBackend(), llvm::createSystemZMCAsmBackend(), llvm::createX86_32AsmBackend(), llvm::createX86_64AsmBackend(), llvm::NVPTXAsmPrinter::doInitialization(), getARMCPUForArch(), getDataLayoutString(), getiOSVersion(), getMacOSXVersion(), getOSVersion(), initialize(), llvm::AMDGPUSubtarget::isAmdHsaOS(), isiOS(), isOSDragonFly(), isOSFreeBSD(), isPS4(), isWindowsCygwinEnvironment(), isWindowsGNUEnvironment(), isWindowsMSVCEnvironment(), llvm::NVPTXTargetMachine::NVPTXTargetMachine(), and triplesMatch().
StringRef Triple::getOSAndEnvironmentName () const
getOSAndEnvironmentName - Get the operating system and optional environment components as a single string (separated by a '-' if the environment component is present).
Definition at line 796 of file Triple.cpp.
References llvm::StringRef::split().
Referenced by setArchName(), and setVendorName().
unsigned llvm::Triple::getOSMajorVersion () const [inline]
getOSMajorVersion - Return just the major version number, this is specialized because it is a common query.
Definition at line 278 of file Triple.h.
StringRef Triple::getOSName () const
getOSName - Get the operating system (third) component of the triple.
Definition at line 784 of file Triple.cpp.
References llvm::StringRef::split().
Referenced by getOSVersion(), and setEnvironmentName().
const char * Triple::getOSTypeName (OSType Kind) [static]
getOSTypeName - Get the canonical name for the Kind operating system.
Definition at line 148 of file Triple.cpp.
References AIX, AMDHSA, Bitrig, CloudABI, CNK, CUDA, Darwin, DragonFly, FreeBSD, Haiku, IOS, KFreeBSD, Linux, llvm_unreachable, Lv2, MacOSX, Minix, NaCl, NetBSD, NVCL, OpenBSD, PS4, RTEMS, Solaris, UnknownOS, and Win32.
Referenced by getOSVersion(), and setOS().
void Triple::getOSVersion (unsigned & Major, unsigned & Minor, unsigned & Micro) const
getOSVersion - Parse the version number from the OS name component of the triple, if present.
For example, "fooos1.2.3" would return (1, 2, 3).
If an entry is not defined, it will be returned as 0.
Definition at line 846 of file Triple.cpp.
References getOS(), getOSName(), getOSTypeName(), parseVersionFromName(), llvm::StringRef::size(), llvm::StringRef::startswith(), and llvm::StringRef::substr().
Referenced by llvm::AsmPrinter::doInitialization(), getiOSVersion(), and getMacOSXVersion().
SubArchType llvm::Triple::getSubArch () const [inline]
getSubArch - get the parsed subarchitecture type for this triple.
Definition at line 239 of file Triple.h.
Referenced by llvm::ARMAsmPrinter::EmitStartOfAsmFile(), llvm::ARMAsmPrinter::getISAEncoding(), llvm::ARM_MC::ParseARMTriple(), and triplesMatch().
const std::string& llvm::Triple::getTriple () const [inline]
Definition at line 300 of file Triple.h.
Referenced by llvm::TargetRegistry::lookupTarget(), and llvm::EngineBuilder::selectTarget().
VendorType llvm::Triple::getVendor () const [inline]
getVendor - Get the parsed vendor type of this triple.
Definition at line 242 of file Triple.h.
Referenced by llvm::SubtargetFeatures::getDefaultSubtargetFeatures(), llvm::PPCSubtarget::isBGQ(), isPS4(), mergeTriples(), and triplesMatch().
StringRef Triple::getVendorName () const
getVendorName - Get the vendor (second) component of the triple.
Definition at line 779 of file Triple.cpp.
References llvm::StringRef::split().
Referenced by setArchName(), setEnvironmentName(), setOSAndEnvironmentName(), and setOSName().
const char * Triple::getVendorTypeName (VendorType Kind) [static]
getVendorTypeName - Get the canonical name for the Kind vendor.
Definition at line 128 of file Triple.cpp.
References Apple, BGP, BGQ, CSR, Freescale, IBM, ImaginationTechnologies, llvm_unreachable, MipsTechnologies, NVIDIA, PC, SCEI, and UnknownVendor.
Referenced by setVendor().
bool llvm::Triple::hasEnvironment () const [inline]
hasEnvironment - Does this triple have the optional environment (fourth) component?
Definition at line 249 of file Triple.h.
Referenced by setOSName().
bool Triple::isArch16Bit () const
Test whether the architecture is 16-bit.
Note that this tests for 16-bit pointer width, and nothing else.
Definition at line 1044 of file Triple.cpp.
References getArch(), and getArchPointerBitWidth().
bool Triple::isArch32Bit () const
Test whether the architecture is 32-bit.
Note that this tests for 32-bit pointer width, and nothing else.
Definition at line 1040 of file Triple.cpp.
References getArch(), and getArchPointerBitWidth().
Referenced by llvm::sys::getProcessTriple().
bool Triple::isArch64Bit () const
Test whether the architecture is 64-bit.
Note that this tests for 64-bit pointer width, and nothing else. Note that we intentionally expose only three predicates, 64-bit, 32-bit, and 16-bit. The inner details of pointer width for particular architectures is not summed up in the triple, and so only a coarse grained predicate system is provided.
Definition at line 1036 of file Triple.cpp.
References getArch(), and getArchPointerBitWidth().
Referenced by computeDataLayout(), and llvm::sys::getProcessTriple().
bool llvm::Triple::isiOS () const [inline]
Is this an iOS triple.
Definition at line 389 of file Triple.h.
References Darwin, getOS(), and MacOSX.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), llvm::ARMSubtarget::hasSinCos(), hasSinCosPiStret(), initialize(), isOSOpenBSD(), llvm::AArch64Subtarget::isTargetIOS(), llvm::ARMSubtarget::isTargetIOS(), llvm::EngineBuilder::selectTarget(), and useCompactUnwind().
bool llvm::Triple::isKnownWindowsMSVCEnvironment () const [inline]
Definition at line 426 of file Triple.h.
Referenced by createTLOF(), llvm::AsmPrinter::doInitialization(), llvm::MCWinCOFFStreamer::EmitCommonSymbol(), and llvm::X86AsmPrinter::EmitEndOfAsmFile().
bool llvm::Triple::isMacOSX () const [inline]
isMacOSX - Is this a Mac OS X triple.
For legacy reasons, we support both "darwin" and "osx" as OS X triples.
Definition at line 384 of file Triple.h.
Referenced by computeTargetABI(), createPPCAsmPrinterPass(), llvm::AsmPrinter::doInitialization(), hasSinCosPiStret(), initialize(), llvm::PPCSubtarget::isDarwin(), isOSOpenBSD(), llvm::PPCMCAsmInfoDarwin::PPCMCAsmInfoDarwin(), PrepareCall(), useCompactUnwind(), and llvm::X86MCAsmInfoDarwin::X86MCAsmInfoDarwin().
unsigned llvm::Triple::isMacOSXVersionLT (unsigned Major, unsigned Minor = 0, unsigned Micro = 0) const [inline]
isMacOSXVersionLT - Comparison function for checking OS X version compatibility, which handles supporting skewed version numbering schemes used by the "darwin" triples.
Definition at line 369 of file Triple.h.
Referenced by hasSinCosPiStret(), initialize(), llvm::PPCMCAsmInfoDarwin::PPCMCAsmInfoDarwin(), PrepareCall(), useCompactUnwind(), and llvm::X86MCAsmInfoDarwin::X86MCAsmInfoDarwin().
bool llvm::Triple::isOSBinFormatCOFF () const [inline]
Tests whether the OS uses the COFF binary format.
Definition at line 474 of file Triple.h.
Referenced by createTLOF(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), llvm::DataLayout::getManglingComponent(), llvm::AArch64Subtarget::isTargetCOFF(), and llvm::ARMSubtarget::isTargetCOFF().
bool llvm::Triple::isOSBinFormatELF () const [inline]
Tests whether the OS uses the ELF binary format.
Definition at line 469 of file Triple.h.
Referenced by llvm::createAArch64beAsmBackend(), llvm::createAArch64leAsmBackend(), createAArch64MCAsmInfo(), createAArch64MCCodeGenInfo(), llvm::createARMAsmBackend(), createTLOF(), llvm::createX86_32AsmBackend(), llvm::createX86_64AsmBackend(), createX86MCAsmInfo(), createX86MCRelocationInfo(), llvm::AsmPrinter::doFinalization(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::ARMAsmPrinter::EmitStartOfAsmFile(), llvm::AArch64RegisterInfo::getTLSCallPreservedMask(), llvm::AArch64Subtarget::isTargetELF(), llvm::SystemZSubtarget::isTargetELF(), llvm::PPCSubtarget::isTargetELF(), llvm::ARMSubtarget::isTargetELF(), and llvm::AArch64MCInstLower::LowerSymbolOperand().
bool llvm::Triple::isOSBinFormatMachO () const [inline]
Tests whether the environment is MachO.
Definition at line 479 of file Triple.h.
Referenced by computeDataLayout(), computeTargetABI(), llvm::createAArch64leAsmBackend(), createAArch64MCAsmInfo(), createAArch64MCCodeGenInfo(), createARMMCAsmInfo(), createARMMCRelocationInfo(), createTLOF(), llvm::createX86_32AsmBackend(), llvm::createX86_64AsmBackend(), createX86MCAsmInfo(), createX86MCRelocationInfo(), llvm::ARMAsmPrinter::EmitEndOfAsmFile(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), llvm::ARMAsmPrinter::getISAEncoding(), llvm::DataLayout::getManglingComponent(), llvm::MCObjectFileInfo::InitMCObjectFileInfo(), llvm::AArch64Subtarget::isTargetMachO(), llvm::PPCSubtarget::isTargetMachO(), and llvm::ARMSubtarget::isTargetMachO().
bool llvm::Triple::isOSBitrig () const [inline]
Definition at line 416 of file Triple.h.
bool llvm::Triple::isOSCygMing () const [inline]
Tests for either Cygwin or MinGW OS.
Definition at line 443 of file Triple.h.
Referenced by createX86MCAsmInfo(), llvm::X86_MC::getDwarfRegFlavour(), and initialize().
bool llvm::Triple::isOSDarwin () const [inline]
isOSDarwin - Is this a "Darwin" OS (OS X or iOS).
Definition at line 394 of file Triple.h.
Referenced by computeDataLayout(), createAArch64MCCodeGenInfo(), createARMMCAsmInfo(), createARMMCCodeGenInfo(), llvm::createPPCAsmBackend(), createPPCMCAsmInfo(), createPPCMCCodeGenInfo(), createPPCMCInstPrinter(), createTLOF(), createX86MCCodeGenInfo(), llvm::AsmPrinter::doInitialization(), getDataLayoutString(), getDefaultFormat(), llvm::X86_MC::getDwarfRegFlavour(), llvm::AArch64RegisterInfo::getReservedRegs(), GetSymbolFromOperand(), llvm::AArch64RegisterInfo::getTLSCallPreservedMask(), hasSinCosPiStret(), InitLibcallNames(), llvm::AArch64RegisterInfo::isReservedReg(), llvm::AArch64Subtarget::isTargetDarwin(), llvm::ARMSubtarget::isTargetDarwin(), llvm::AArch64MCInstLower::LowerSymbolOperand(), and useCompactUnwind().
bool llvm::Triple::isOSDragonFly () const [inline]
Definition at line 410 of file Triple.h.
References getOS(), and OpenBSD.
bool llvm::Triple::isOSFreeBSD () const [inline]
Definition at line 406 of file Triple.h.
References getOS(), and NetBSD.
bool llvm::Triple::isOSLinux () const [inline]
Tests whether the OS is Linux.
Definition at line 464 of file Triple.h.
Referenced by createTLOF(), initialize(), llvm::AArch64Subtarget::isTargetLinux(), and llvm::ARMSubtarget::isTargetLinux().
bool llvm::Triple::isOSMSVCRT () const [inline]
Is this a "Windows" OS targeting a "MSVCRT.dll" environment.
Definition at line 448 of file Triple.h.
bool llvm::Triple::isOSNaCl () const [inline]
Tests whether the OS is NaCl (Native Client)
Definition at line 459 of file Triple.h.
Referenced by computeDataLayout(), createMCStreamer(), createTLOF(), llvm::MipsSubtarget::isTargetNaCl(), llvm::ARMSubtarget::isTargetNaCl(), and llvm::ARM_MC::ParseARMTriple().
bool llvm::Triple::isOSNetBSD () const [inline]
Definition at line 398 of file Triple.h.
Referenced by llvm::ARMSubtarget::isTargetNetBSD().
bool llvm::Triple::isOSOpenBSD () const [inline]
Definition at line 402 of file Triple.h.
References isiOS(), and isMacOSX().
Referenced by CreatePrologue(), and InitLibcallNames().
bool llvm::Triple::isOSSolaris () const [inline]
Definition at line 412 of file Triple.h.
bool llvm::Triple::isOSVersionLT (unsigned Major, unsigned Minor = 0, unsigned Micro = 0) const [inline]
isOSVersionLT - Helper function for doing comparisons against version numbers included in the target triple.
Definition at line 345 of file Triple.h.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), llvm::ARMSubtarget::hasSinCos(), hasSinCosPiStret(), initialize(), and mergeTriples().
bool llvm::Triple::isOSVersionLT (const Triple & Other) const [inline]
Definition at line 360 of file Triple.h.
bool llvm::Triple::isOSWindows () const [inline]
Tests whether the OS is Windows.
Definition at line 454 of file Triple.h.
References isWindowsGNUEnvironment(), isWindowsItaniumEnvironment(), and isWindowsMSVCEnvironment().
Referenced by computeDataLayout(), computeTargetABI(), llvm::createARMAsmBackend(), llvm::Target::createMCObjectStreamer(), createTLOF(), llvm::createX86_32AsmBackend(), llvm::createX86_64AsmBackend(), createX86MCCodeGenInfo(), getDefaultFormat(), llvm::DataLayout::getManglingComponent(), initialize(), llvm::MCObjectFileInfo::InitMCObjectFileInfo(), llvm::AArch64Subtarget::isTargetWindows(), llvm::ARMSubtarget::isTargetWindows(), and llvm::X86MCAsmInfoGNUCOFF::X86MCAsmInfoGNUCOFF().
bool llvm::Triple::isPS4 () const [inline]
Tests whether the target is the PS4 platform.
Definition at line 491 of file Triple.h.
References getArch(), getOS(), getVendor(), PS4, SCEI, and x86_64.
bool llvm::Triple::isPS4CPU () const [inline]
Tests whether the target is the PS4 CPU.
Definition at line 484 of file Triple.h.
bool llvm::Triple::isWindowsCygwinEnvironment () const [inline]
Definition at line 434 of file Triple.h.
References getEnvironment(), getOS(), MSVC, and Win32.
bool llvm::Triple::isWindowsGNUEnvironment () const [inline]
Definition at line 438 of file Triple.h.
References getEnvironment(), getOS(), Itanium, and Win32.
Referenced by isOSWindows().
bool llvm::Triple::isWindowsItaniumEnvironment () const [inline]
Definition at line 430 of file Triple.h.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), createARMMCAsmInfo(), createX86MCAsmInfo(), isOSWindows(), and llvm::ARMTargetLowering::LowerOperation().
bool llvm::Triple::isWindowsMSVCEnvironment () const [inline]
Definition at line 420 of file Triple.h.
References getOS(), and Solaris.
Referenced by createARMMCAsmInfo(), createX86MCAsmInfo(), and isOSWindows().
std::string Triple::normalize (StringRef Str) [static]
normalize - Turn an arbitrary machine specification into the canonical triple form (or something sensible that the Triple class understands if nothing better can reasonably be done).
In particular, it handles the common case in which otherwise valid components are in the wrong order.
Definition at line 590 of file Triple.cpp.
References Android, llvm::array_lengthof(), COFF, llvm::StringRef::empty(), Found(), getObjectFormatTypeName(), llvm_unreachable, parseArch(), parseEnvironment(), parseFormat(), parseOS(), parseVendor(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorImpl< T >::resize(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::StringRef::split(), llvm::StringRef::startswith(), llvm::Twine::str(), std::swap(), UnknownArch, UnknownEnvironment, UnknownObjectFormat, UnknownOS, UnknownVendor, and Win32.
std::string llvm::Triple::normalize () const [inline]
Return the normalized form of this triple's string.
Definition at line 231 of file Triple.h.
Referenced by llvm::sys::getProcessTriple().
bool llvm::Triple::operator== (const Triple & Other) const [inline]
Definition at line 215 of file Triple.h.
void Triple::setArch (ArchType Kind)
setArch - Set the architecture (first) component of the triple to a known type.
Definition at line 923 of file Triple.cpp.
References getArchTypeName(), and setArchName().
Referenced by get32BitArchVariant(), get64BitArchVariant(), llvm::TargetRegistry::lookupTarget(), and llvm::EngineBuilder::selectTarget().
void Triple::setArchName (StringRef Str)
setArchName - Set the architecture (first) component of the triple by name.
Definition at line 951 of file Triple.cpp.
References getOSAndEnvironmentName(), getVendorName(), setTriple(), and Triple().
Referenced by setArch().
void Triple::setEnvironment (EnvironmentType Kind)
setEnvironment - Set the environment (fourth) component of the triple to a known type.
Definition at line 935 of file Triple.cpp.
References getDefaultFormat(), getEnvironmentTypeName(), getObjectFormatTypeName(), setEnvironmentName(), and str().
void Triple::setEnvironmentName (StringRef Str)
setEnvironmentName - Set the optional environment (fourth) component of the triple by name.
Definition at line 974 of file Triple.cpp.
References getArchName(), getOSName(), getVendorName(), and setTriple().
Referenced by setEnvironment(), and setObjectFormat().
void Triple::setObjectFormat (ObjectFormatType Kind)
setObjectFormat - Set the object file format
Definition at line 943 of file Triple.cpp.
References getEnvironmentTypeName(), getObjectFormatTypeName(), setEnvironmentName(), str(), and UnknownEnvironment.
void Triple::setOS (OSType Kind)
setOS - Set the operating system (third) component of the triple to a known type.
Definition at line 931 of file Triple.cpp.
References getOSTypeName(), and setOSName().
void Triple::setOSAndEnvironmentName (StringRef Str)
setOSAndEnvironmentName - Set the operating system and optional environment components with a single string.
Definition at line 979 of file Triple.cpp.
References getArchName(), getVendorName(), and setTriple().
void Triple::setOSName (StringRef Str)
setOSName - Set the operating system (third) component of the triple by name.
Definition at line 966 of file Triple.cpp.
References getArchName(), getEnvironmentName(), getVendorName(), hasEnvironment(), and setTriple().
Referenced by setOS().
void Triple::setTriple (const Twine & Str)
setTriple - Set all components to the new triple Str.
Definition at line 919 of file Triple.cpp.
References Triple().
Referenced by llvm::EngineBuilder::selectTarget(), setArchName(), setEnvironmentName(), setOSAndEnvironmentName(), setOSName(), and setVendorName().
void Triple::setVendor (VendorType Kind)
setVendor - Set the vendor (second) component of the triple to a known type.
Definition at line 927 of file Triple.cpp.
References getVendorTypeName(), and setVendorName().
void Triple::setVendorName (StringRef Str)
setVendorName - Set the vendor (second) component of the triple by name.
Definition at line 962 of file Triple.cpp.
References getArchName(), getOSAndEnvironmentName(), and setTriple().
Referenced by setVendor().
const std::string& llvm::Triple::str () const [inline]
Definition at line 298 of file Triple.h.
Referenced by llvm::AsmPrinter::doInitialization(), llvm::sys::getProcessTriple(), llvm::AsmPrinter::getTargetTriple(), llvm::orc::OrcX86_64::insertCompileCallbackTrampolines(), llvm::LLVMTargetMachine::LLVMTargetMachine(), mergeTriples(), setEnvironment(), and setObjectFormat().
The documentation for this class was generated from the following files:
Triple.h
Triple.cpp