LLVM: llvm::NVPTXTargetObjectFile Class Reference
llvm::NVPTXTargetObjectFile Class Reference
#include <NVPTXTargetObjectFile.h>
Public Member Functions
NVPTXTargetObjectFile ()
virtual ~NVPTXTargetObjectFile ()
void Initialize (MCContext &ctx, const TargetMachine &TM) override
This method must be called before any actual lowering is done.
MCSection * getSectionForConstant (SectionKind Kind, const Constant *C) const override
Given a constant with the SectionKind, return a section that it should be placed in.
MCSection * getExplicitSectionGlobal (const GlobalValue *GV, SectionKind Kind, Mangler &Mang, const TargetMachine &TM) const override
Targets should implement this method to assign a section to globals with an explicit section specfied.
MCSection * SelectSectionForGlobal (const GlobalValue *GV, SectionKind Kind, Mangler &Mang, const TargetMachine &TM) const override
Detailed Description
Definition at line 21 of file NVPTXTargetObjectFile.h.
Constructor & Destructor Documentation
llvm::NVPTXTargetObjectFile::NVPTXTargetObjectFile () [inline]
Definition at line 24 of file NVPTXTargetObjectFile.h.
References llvm::MCObjectFileInfo::BSSSection, llvm::MCObjectFileInfo::DataSection, llvm::MCObjectFileInfo::DwarfAbbrevSection, llvm::MCObjectFileInfo::DwarfARangesSection, llvm::MCObjectFileInfo::DwarfDebugInlineSection, llvm::MCObjectFileInfo::DwarfFrameSection, llvm::MCObjectFileInfo::DwarfInfoSection, llvm::MCObjectFileInfo::DwarfLineSection, llvm::MCObjectFileInfo::DwarfLocSection, llvm::MCObjectFileInfo::DwarfPubTypesSection, llvm::MCObjectFileInfo::DwarfRangesSection, llvm::MCObjectFileInfo::DwarfStrSection, llvm::MCObjectFileInfo::EHFrameSection, llvm::MCObjectFileInfo::LSDASection, llvm::MCObjectFileInfo::ReadOnlySection, llvm::MCObjectFileInfo::StaticCtorSection, llvm::MCObjectFileInfo::StaticDtorSection, and llvm::MCObjectFileInfo::TextSection.
NVPTXTargetObjectFile::~NVPTXTargetObjectFile () [virtual]
Definition at line 4502 of file NVPTXISelLowering.cpp.
References llvm::MCObjectFileInfo::BSSSection, llvm::MCObjectFileInfo::DataSection, llvm::MCObjectFileInfo::DwarfAbbrevSection, llvm::MCObjectFileInfo::DwarfARangesSection, llvm::MCObjectFileInfo::DwarfDebugInlineSection, llvm::MCObjectFileInfo::DwarfFrameSection, llvm::MCObjectFileInfo::DwarfInfoSection, llvm::MCObjectFileInfo::DwarfLineSection, llvm::MCObjectFileInfo::DwarfLocSection, llvm::MCObjectFileInfo::DwarfPubTypesSection, llvm::MCObjectFileInfo::DwarfRangesSection, llvm::MCObjectFileInfo::DwarfStrSection, llvm::MCObjectFileInfo::EHFrameSection, llvm::MCObjectFileInfo::LSDASection, llvm::MCObjectFileInfo::ReadOnlySection, llvm::MCObjectFileInfo::StaticCtorSection, llvm::MCObjectFileInfo::StaticDtorSection, and llvm::MCObjectFileInfo::TextSection.
Member Function Documentation
MCSection* llvm::NVPTXTargetObjectFile::getExplicitSectionGlobal (const GlobalValue * GV, SectionKind Kind, Mangler & Mang, const TargetMachine & TM) const [inline, override, virtual]
Targets should implement this method to assign a section to globals with an explicit section specfied.
The implementation of this method can assume that GV->hasSection() is true.
Implements llvm::TargetLoweringObjectFile.
Definition at line 92 of file NVPTXTargetObjectFile.h.
References llvm::MCObjectFileInfo::DataSection.
MCSection* llvm::NVPTXTargetObjectFile::getSectionForConstant (SectionKind Kind, const Constant * C) const [inline, override, virtual]
Given a constant with the SectionKind, return a section that it should be placed in.
Given a mergable constant with the specified size and relocation information, return a section that it should be placed in.
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 87 of file NVPTXTargetObjectFile.h.
References llvm::MCObjectFileInfo::ReadOnlySection.
void llvm::NVPTXTargetObjectFile::Initialize (MCContext & ctx, const TargetMachine & TM) [inline, override, virtual]
This method must be called before any actual lowering is done.
Initialize - this method must be called before any actual lowering is done.
This specifies the current context for codegen, and gives the lowering implementations a chance to set up their default sections.
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 48 of file NVPTXTargetObjectFile.h.
References llvm::MCObjectFileInfo::BSSSection, llvm::MCObjectFileInfo::DataSection, llvm::MCObjectFileInfo::DwarfAbbrevSection, llvm::MCObjectFileInfo::DwarfARangesSection, llvm::MCObjectFileInfo::DwarfDebugInlineSection, llvm::MCObjectFileInfo::DwarfFrameSection, llvm::MCObjectFileInfo::DwarfInfoSection, llvm::MCObjectFileInfo::DwarfLineSection, llvm::MCObjectFileInfo::DwarfLocSection, llvm::MCObjectFileInfo::DwarfPubTypesSection, llvm::MCObjectFileInfo::DwarfRangesSection, llvm::MCObjectFileInfo::DwarfStrSection, llvm::MCObjectFileInfo::EHFrameSection, llvm::SectionKind::getBSS(), llvm::SectionKind::getDataRel(), llvm::SectionKind::getMetadata(), llvm::SectionKind::getReadOnly(), llvm::SectionKind::getText(), llvm::MCObjectFileInfo::LSDASection, llvm::MCObjectFileInfo::ReadOnlySection, llvm::MCObjectFileInfo::StaticCtorSection, llvm::MCObjectFileInfo::StaticDtorSection, llvm::MCSection::SV_ELF, and llvm::MCObjectFileInfo::TextSection.
MCSection * NVPTXTargetObjectFile::SelectSectionForGlobal (const GlobalValue * GV, SectionKind Kind, Mangler & Mang, const TargetMachine & TM) const [override, virtual]
Implements llvm::TargetLoweringObjectFile.
Definition at line 4525 of file NVPTXISelLowering.cpp.
References llvm::MCObjectFileInfo::getDataSection().
The documentation for this class was generated from the following files:
NVPTXTargetObjectFile.h
NVPTXISelLowering.cpp