LLVM: llvm::yaml::final Class Reference
llvm::yaml::final Class Reference
A null value.
#include <YAMLParser.h>
Public Types
enum MappingType { MT_Block, MT_Flow, MT_Inline }
enum SequenceType { ST_Block, ST_Flow, ST_Indentless }
typedef
basic_collection_iterator
< MappingNode, KeyValueNode > iterator
typedef
basic_collection_iterator
< SequenceNode, Node > iterator
Public Member Functions
NullNode (std::unique_ptr< Document > &D)
ScalarNode (std::unique_ptr< Document > &D, StringRef Anchor, StringRef Tag, StringRef Val)
StringRef getRawValue () const
StringRef getValue (SmallVectorImpl< char > &Storage) const
Gets the value of this node as a StringRef.
BlockScalarNode (std::unique_ptr< Document > &D, StringRef Anchor, StringRef Tag, StringRef Value, StringRef RawVal)
StringRef getValue () const
Gets the value of this node as a StringRef.
KeyValueNode (std::unique_ptr< Document > &D)
Node * getKey ()
Parse and return the key.
Node * getValue ()
Parse and return the value.
void skip () override
MappingNode (std::unique_ptr< Document > &D, StringRef Anchor, StringRef Tag, MappingType MT)
iterator begin ()
iterator end ()
void skip () override
SequenceNode (std::unique_ptr< Document > &D, StringRef Anchor, StringRef Tag, SequenceType ST)
void increment ()
iterator begin ()
iterator end ()
void skip () override
AliasNode (std::unique_ptr< Document > &D, StringRef Val)
StringRef getName () const
Node * getTarget ()
Static Public Member Functions
static bool classof (const Node *N)
static bool classof (const Node *N)
static bool classof (const Node *N)
static bool classof (const Node *N)
static bool classof (const Node *N)
static bool classof (const Node *N)
static bool classof (const Node *N)
Friends
class basic_collection_iterator< MappingNode, KeyValueNode >
class basic_collection_iterator< SequenceNode, Node >
template<class T >
T::iterator yaml::begin (T &)
template<class T >
void yaml::skip (T &)
template<class T >
T::iterator yaml::begin (T &)
template<class T >
void yaml::skip (T &)
Detailed Description
A null value.
Represents an alias to a Node with an anchor.
Represents a YAML sequence created from either a block sequence for a flow sequence.
Represents a YAML map created from either a block map for a flow map.
A key and value pair.
A block scalar node is an opaque datum that can be presented as a series of zero or more Unicode scalar values.
A scalar node is an opaque datum that can be presented as a series of zero or more Unicode scalar values.
Example: !!null null
Example: Adena
Example: | Hello World
While not technically a Node under the YAML representation graph, it is easier to treat them this way.
TODO: Consider making this not a child of Node.
Example: Section: .text
This parses the YAML stream as increment() is called.
Example: Name: _main Scope: Global
This parses the YAML stream as increment() is called.
Example:
Hello
World
Example: AnchorName
Definition at line 175 of file YAMLParser.h.
Member Typedef Documentation
typedef basic_collection_iterator<MappingNode, KeyValueNode> llvm::yaml::final::iterator
Definition at line 390 of file YAMLParser.h.
typedef basic_collection_iterator<SequenceNode, Node> llvm::yaml::final::iterator
Definition at line 446 of file YAMLParser.h.
Member Enumeration Documentation
enum llvm::yaml::final::MappingType
Enumerator:
MT_Block
MT_Flow
MT_Inline
An inline mapping node is used for "[key: value]".
Definition at line 378 of file YAMLParser.h.
enum llvm::yaml::final::SequenceType
Enumerator:
ST_Block
ST_Flow
ST_Indentless
Definition at line 425 of file YAMLParser.h.
Member Function Documentation
llvm::yaml::final::AliasNode (std::unique_ptr< Document > & D, StringRef Val) [inline]
Definition at line 478 of file YAMLParser.h.
iterator llvm::yaml::final::begin () [inline]
Definition at line 394 of file YAMLParser.h.
References llvm::yaml::begin().
iterator llvm::yaml::final::begin () [inline]
Definition at line 452 of file YAMLParser.h.
References llvm::yaml::begin().
llvm::yaml::final::BlockScalarNode (std::unique_ptr< Document > & D, StringRef Anchor, StringRef Tag, StringRef Value, StringRef RawVal) [inline]
Definition at line 237 of file YAMLParser.h.
References llvm::StringRef::begin(), llvm::StringRef::end(), and llvm::SMLoc::getFromPointer().
static bool llvm::yaml::final::classof (const Node * N) [inline, static]
Definition at line 182 of file YAMLParser.h.
References llvm::yaml::Node::getType().
static bool llvm::yaml::final::classof (const Node * N) [inline, static]
Definition at line 214 of file YAMLParser.h.
References llvm::yaml::Node::getType().
static bool llvm::yaml::final::classof (const Node * N) [inline, static]
Definition at line 248 of file YAMLParser.h.
References llvm::yaml::Node::getType().
static bool llvm::yaml::final::classof (const Node * N) [inline, static]
Definition at line 291 of file YAMLParser.h.
References llvm::yaml::Node::getType().
static bool llvm::yaml::final::classof (const Node * N) [inline, static]
Definition at line 400 of file YAMLParser.h.
References llvm::yaml::Node::getType().
static bool llvm::yaml::final::classof (const Node * N) [inline, static]
Definition at line 458 of file YAMLParser.h.
References llvm::yaml::Node::getType().
static bool llvm::yaml::final::classof (const Node * N) [inline, static]
Definition at line 484 of file YAMLParser.h.
References llvm::yaml::Node::getType().
iterator llvm::yaml::final::end () [inline]
Definition at line 396 of file YAMLParser.h.
iterator llvm::yaml::final::end () [inline]
Definition at line 454 of file YAMLParser.h.
Node* llvm::yaml::final::getKey ()
Parse and return the key.
This may be called multiple times.
Returns:
The key, or nullptr if failed() == true.
StringRef llvm::yaml::final::getName () const [inline]
Definition at line 481 of file YAMLParser.h.
StringRef llvm::yaml::final::getRawValue () const [inline]
Definition at line 205 of file YAMLParser.h.
Node* llvm::yaml::final::getTarget ()
StringRef llvm::yaml::final::getValue (SmallVectorImpl< char > & Storage) const
Gets the value of this node as a StringRef.
Parameters:
Storage is used to store the content of the returned StringRef iff it requires any modification from how it appeared in the source. This happens with escaped characters and multi-line literals.
StringRef llvm::yaml::final::getValue () const [inline]
Gets the value of this node as a StringRef.
Definition at line 246 of file YAMLParser.h.
Node* llvm::yaml::final::getValue ()
Parse and return the value.
This may be called multiple times.
Returns:
The value, or nullptr if failed() == true.
void llvm::yaml::final::increment ()
llvm::yaml::final::KeyValueNode (std::unique_ptr< Document > & D) [inline]
Definition at line 267 of file YAMLParser.h.
llvm::yaml::final::MappingNode (std::unique_ptr< Document > & D, StringRef Anchor, StringRef Tag, MappingType MT) [inline]
Definition at line 384 of file YAMLParser.h.
llvm::yaml::final::NullNode (std::unique_ptr< Document > & D) [inline]
Definition at line 179 of file YAMLParser.h.
llvm::yaml::final::ScalarNode (std::unique_ptr< Document > & D, StringRef Anchor, StringRef Tag, StringRef Val) [inline]
Definition at line 194 of file YAMLParser.h.
References llvm::StringRef::begin(), llvm::StringRef::end(), and llvm::SMLoc::getFromPointer().
llvm::yaml::final::SequenceNode (std::unique_ptr< Document > & D, StringRef Anchor, StringRef Tag, SequenceType ST) [inline]
Definition at line 438 of file YAMLParser.h.
void llvm::yaml::final::skip () [inline, override, virtual]
Reimplemented from llvm::yaml::Node.
Definition at line 285 of file YAMLParser.h.
void llvm::yaml::final::skip () [inline, override, virtual]
Reimplemented from llvm::yaml::Node.
Definition at line 398 of file YAMLParser.h.
References llvm::yaml::skip().
void llvm::yaml::final::skip () [inline, override, virtual]
Reimplemented from llvm::yaml::Node.
Definition at line 456 of file YAMLParser.h.
References llvm::yaml::skip().
Friends And Related Function Documentation
friend class basic_collection_iterator< MappingNode, KeyValueNode > [friend]
Definition at line 389 of file YAMLParser.h.
friend class basic_collection_iterator< SequenceNode, Node > [friend]
Definition at line 445 of file YAMLParser.h.
template<class T > T::iterator yaml::begin (T &) [friend]
template<class T > T::iterator yaml::begin (T &) [friend]
template<class T > void yaml::skip (T &) [friend]
template<class T > void yaml::skip (T &) [friend]
The documentation for this class was generated from the following file:
YAMLParser.h