LLVM: llvm::SystemZCCState Class Reference
llvm::SystemZCCState Class Reference
#include <SystemZCallingConv.h>
Public Member Functions
SystemZCCState (CallingConv::ID CC, bool isVarArg, MachineFunction &MF, SmallVectorImpl< CCValAssign > &locs, LLVMContext &C)
void AnalyzeFormalArguments (const SmallVectorImpl< ISD::InputArg > &Ins, CCAssignFn Fn)
AnalyzeFormalArguments - Analyze an array of argument values, incorporating info about the formals into this state.
void AnalyzeCallOperands (const SmallVectorImpl< ISD::OutputArg > &Outs, CCAssignFn Fn)
AnalyzeCallOperands - Analyze the outgoing arguments to a call, incorporating info about the passed values into this state.
void AnalyzeCallOperands (const SmallVectorImpl< MVT > &Outs, SmallVectorImpl< ISD::ArgFlagsTy > &Flags, CCAssignFn Fn)
bool IsFixed (unsigned ValNo)
bool IsShortVector (unsigned ValNo)
Detailed Description
Definition at line 25 of file SystemZCallingConv.h.
Constructor & Destructor Documentation
llvm::SystemZCCState::SystemZCCState (CallingConv::ID CC, bool isVarArg, MachineFunction & MF, SmallVectorImpl< CCValAssign > & locs, LLVMContext & C) [inline]
Definition at line 40 of file SystemZCallingConv.h.
Member Function Documentation
void llvm::SystemZCCState::AnalyzeCallOperands (const SmallVectorImpl< ISD::OutputArg > & Outs, CCAssignFn Fn) [inline]
AnalyzeCallOperands - Analyze the outgoing arguments to a call, incorporating info about the passed values into this state.
Analyze the outgoing arguments to a call, incorporating info about the passed values into this state.
Reimplemented from llvm::CCState.
Definition at line 58 of file SystemZCallingConv.h.
References llvm::SmallVectorImpl< T >::clear(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::SystemZTargetLowering::LowerCall().
void llvm::SystemZCCState::AnalyzeCallOperands (const SmallVectorImpl< MVT > & Outs, SmallVectorImpl< ISD::ArgFlagsTy > & Flags, CCAssignFn Fn)
void llvm::SystemZCCState::AnalyzeFormalArguments (const SmallVectorImpl< ISD::InputArg > & Ins, CCAssignFn Fn) [inline]
AnalyzeFormalArguments - Analyze an array of argument values, incorporating info about the formals into this state.
Analyze an array of argument values, incorporating info about the formals into this state.
Reimplemented from llvm::CCState.
Definition at line 44 of file SystemZCallingConv.h.
References llvm::SmallVectorImpl< T >::clear(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::SystemZTargetLowering::LowerFormalArguments().
bool llvm::SystemZCCState::IsFixed (unsigned ValNo) [inline]
Definition at line 78 of file SystemZCallingConv.h.
bool llvm::SystemZCCState::IsShortVector (unsigned ValNo) [inline]
Definition at line 79 of file SystemZCallingConv.h.
The documentation for this class was generated from the following file:
SystemZCallingConv.h