LLVM: llvm::LoopAccessReport Class Reference
llvm::LoopAccessReport Class Reference
Optimization analysis message produced during vectorization.
#include <LoopAccessAnalysis.h>
Public Member Functions
LoopAccessReport (const Instruction *I=nullptr)
template<typename A >
LoopAccessReport & operator<< (const A &Value)
const Instruction * getInstr () const
std::string & str ()
const std::string & str () const
operator Twine ()
Static Public Member Functions
static void emitAnalysis (const LoopAccessReport &Message, const Function *TheFunction, const Loop *TheLoop, const char *PassName)
Emit an analysis note for PassName with the debug location from the instruction in Message if available.
Protected Member Functions
LoopAccessReport (const Twine &Message, const Instruction *I)
Detailed Description
Optimization analysis message produced during vectorization.
Messages inform the user why vectorization did not occur.
Definition at line 39 of file LoopAccessAnalysis.h.
Constructor & Destructor Documentation
llvm::LoopAccessReport::LoopAccessReport (const Twine & Message, const Instruction * I) [inline, protected]
Definition at line 44 of file LoopAccessAnalysis.h.
llvm::LoopAccessReport::LoopAccessReport (const Instruction * I = nullptr) [inline]
Definition at line 48 of file LoopAccessAnalysis.h.
Member Function Documentation
void LoopAccessReport::emitAnalysis (const LoopAccessReport & Message, const Function * TheFunction, const Loop * TheLoop, const char * PassName) [static]
Emit an analysis note for PassName with the debug location from the instruction in Message if available.
Otherwise use the location of TheLoop.
Definition at line 65 of file LoopAccessAnalysis.cpp.
References llvm::DL, llvm::emitOptimizationRemarkAnalysis(), llvm::Function::getContext(), getInstr(), llvm::Loop::getStartLoc(), I, and str().
const Instruction* llvm::LoopAccessReport::getInstr () const [inline]
Definition at line 56 of file LoopAccessAnalysis.h.
Referenced by emitAnalysis().
llvm::LoopAccessReport::operator Twine () [inline]
Definition at line 60 of file LoopAccessAnalysis.h.
template<typename A > LoopAccessReport& llvm::LoopAccessReport::operator<< (const A & Value) [inline]
Definition at line 50 of file LoopAccessAnalysis.h.
std::string& llvm::LoopAccessReport::str () [inline]
Definition at line 58 of file LoopAccessAnalysis.h.
Referenced by emitAnalysis(), and llvm::LoopAccessInfo::print().
const std::string& llvm::LoopAccessReport::str () const [inline]
Definition at line 59 of file LoopAccessAnalysis.h.
The documentation for this class was generated from the following files:
LoopAccessAnalysis.h
LoopAccessAnalysis.cpp