LLVM: llvm::MSP430Subtarget Class Reference
llvm::MSP430Subtarget Class Reference
#include <MSP430Subtarget.h>
Public Member Functions
MSP430Subtarget (const Triple &TT, const std::string &CPU, const std::string &FS, const TargetMachine &TM)
This constructor initializes the data members to match that of the specified triple.
MSP430Subtarget & initializeSubtargetDependencies (StringRef CPU, StringRef FS)
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
const TargetFrameLowering * getFrameLowering () const override
const MSP430InstrInfo * getInstrInfo () const override
const TargetRegisterInfo * getRegisterInfo () const override
const MSP430TargetLowering * getTargetLowering () const override
const MSP430SelectionDAGInfo * getSelectionDAGInfo () const override
Detailed Description
Definition at line 32 of file MSP430Subtarget.h.
Constructor & Destructor Documentation
MSP430Subtarget::MSP430Subtarget (const Triple & TT, const std::string & CPU, const std::string & FS, const TargetMachine & TM)
This constructor initializes the data members to match that of the specified triple.
Definition at line 34 of file MSP430Subtarget.cpp.
Member Function Documentation
const TargetFrameLowering* llvm::MSP430Subtarget::getFrameLowering () const [inline, override]
Definition at line 53 of file MSP430Subtarget.h.
const MSP430InstrInfo* llvm::MSP430Subtarget::getInstrInfo () const [inline, override]
Definition at line 56 of file MSP430Subtarget.h.
const TargetRegisterInfo* llvm::MSP430Subtarget::getRegisterInfo () const [inline, override]
Definition at line 57 of file MSP430Subtarget.h.
References llvm::MSP430InstrInfo::getRegisterInfo().
Referenced by llvm::MSP430TargetLowering::MSP430TargetLowering().
const MSP430SelectionDAGInfo* llvm::MSP430Subtarget::getSelectionDAGInfo () const [inline, override]
Definition at line 63 of file MSP430Subtarget.h.
const MSP430TargetLowering* llvm::MSP430Subtarget::getTargetLowering () const [inline, override]
Definition at line 60 of file MSP430Subtarget.h.
MSP430Subtarget & MSP430Subtarget::initializeSubtargetDependencies (StringRef CPU, StringRef FS)
Definition at line 29 of file MSP430Subtarget.cpp.
References ParseSubtargetFeatures().
void llvm::MSP430Subtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
Definition of function is auto generated by tblgen.
Referenced by initializeSubtargetDependencies().
The documentation for this class was generated from the following files:
MSP430Subtarget.h
MSP430Subtarget.cpp