LLVM: llvm::DWARFAcceleratorTable Class Reference
llvm::DWARFAcceleratorTable Class Reference
#include <DWARFAcceleratorTable.h>
Classes
struct Header
struct HeaderData
Public Member Functions
DWARFAcceleratorTable (DataExtractor AccelSection, DataExtractor StringSection, const RelocAddrMap &Relocs)
bool extract ()
void dump (raw_ostream &OS) const
Detailed Description
Definition at line 20 of file DWARFAcceleratorTable.h.
Constructor & Destructor Documentation
llvm::DWARFAcceleratorTable::DWARFAcceleratorTable (DataExtractor AccelSection, DataExtractor StringSection, const RelocAddrMap & Relocs) [inline]
Definition at line 44 of file DWARFAcceleratorTable.h.
Member Function Documentation
void llvm::DWARFAcceleratorTable::dump (raw_ostream & OS) const
Definition at line 49 of file DWARFAcceleratorTable.cpp.
References llvm::dwarf::AtomTypeString(), llvm::Data, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::format(), llvm::dwarf::FormEncodingString(), llvm::DataExtractor::getCStr(), llvm::DataExtractor::getU32(), fuzzer::Hash(), if(), llvm::DataExtractor::isValidOffset(), llvm::DataExtractor::isValidOffsetForDataOfSize(), and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Referenced by dumpAccelSection().
bool llvm::DWARFAcceleratorTable::extract ()
Definition at line 17 of file DWARFAcceleratorTable.cpp.
References llvm::DataExtractor::getU16(), llvm::DataExtractor::getU32(), and llvm::DataExtractor::isValidOffset().
Referenced by dumpAccelSection().
The documentation for this class was generated from the following files:
DWARFAcceleratorTable.h
DWARFAcceleratorTable.cpp