LLVM: llvm::PDBSymDumper Class Reference
llvm::PDBSymDumper Class Reference
#include <PDBSymDumper.h>
Public Member Functions
PDBSymDumper (bool ShouldRequireImpl)
virtual ~PDBSymDumper ()
virtual void dump (const PDBSymbolAnnotation &Symbol)
virtual void dump (const PDBSymbolBlock &Symbol)
virtual void dump (const PDBSymbolCompiland &Symbol)
virtual void dump (const PDBSymbolCompilandDetails &Symbol)
virtual void dump (const PDBSymbolCompilandEnv &Symbol)
virtual void dump (const PDBSymbolCustom &Symbol)
virtual void dump (const PDBSymbolData &Symbol)
virtual void dump (const PDBSymbolExe &Symbol)
virtual void dump (const PDBSymbolFunc &Symbol)
virtual void dump (const PDBSymbolFuncDebugEnd &Symbol)
virtual void dump (const PDBSymbolFuncDebugStart &Symbol)
virtual void dump (const PDBSymbolLabel &Symbol)
virtual void dump (const PDBSymbolPublicSymbol &Symbol)
virtual void dump (const PDBSymbolThunk &Symbol)
virtual void dump (const PDBSymbolTypeArray &Symbol)
virtual void dump (const PDBSymbolTypeBaseClass &Symbol)
virtual void dump (const PDBSymbolTypeBuiltin &Symbol)
virtual void dump (const PDBSymbolTypeCustom &Symbol)
virtual void dump (const PDBSymbolTypeDimension &Symbol)
virtual void dump (const PDBSymbolTypeEnum &Symbol)
virtual void dump (const PDBSymbolTypeFriend &Symbol)
virtual void dump (const PDBSymbolTypeFunctionArg &Symbol)
virtual void dump (const PDBSymbolTypeFunctionSig &Symbol)
virtual void dump (const PDBSymbolTypeManaged &Symbol)
virtual void dump (const PDBSymbolTypePointer &Symbol)
virtual void dump (const PDBSymbolTypeTypedef &Symbol)
virtual void dump (const PDBSymbolTypeUDT &Symbol)
virtual void dump (const PDBSymbolTypeVTable &Symbol)
virtual void dump (const PDBSymbolTypeVTableShape &Symbol)
virtual void dump (const PDBSymbolUnknown &Symbol)
virtual void dump (const PDBSymbolUsingNamespace &Symbol)
Detailed Description
Definition at line 19 of file PDBSymDumper.h.
Constructor & Destructor Documentation
PDBSymDumper::PDBSymDumper (bool ShouldRequireImpl)
Definition at line 19 of file PDBSymDumper.cpp.
PDBSymDumper::~PDBSymDumper () [virtual]
Definition at line 22 of file PDBSymDumper.cpp.
Member Function Documentation
void PDBSymDumper::dump (const PDBSymbolAnnotation & Symbol) [virtual]
Definition at line 24 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
Referenced by llvm::PDBSymbolUnknown::dump(), llvm::PDBSymbolFunc::dump(), llvm::PDBSymbolTypeEnum::dump(), llvm::PDBSymbolFuncDebugEnd::dump(), llvm::PDBSymbolAnnotation::dump(), llvm::PDBSymbolTypeBuiltin::dump(), llvm::PDBSymbolPublicSymbol::dump(), llvm::PDBSymbolTypeFunctionArg::dump(), llvm::PDBSymbolLabel::dump(), llvm::PDBSymbolBlock::dump(), llvm::PDBSymbolTypeUDT::dump(), llvm::PDBSymbolFuncDebugStart::dump(), llvm::PDBSymbolTypeVTable::dump(), llvm::PDBSymbolTypeManaged::dump(), llvm::PDBSymbolTypeBaseClass::dump(), llvm::PDBSymbolTypeVTableShape::dump(), llvm::PDBSymbolCompiland::dump(), llvm::PDBSymbolUsingNamespace::dump(), llvm::PDBSymbolCompilandEnv::dump(), llvm::PDBSymbolTypeFriend::dump(), llvm::PDBSymbolTypeTypedef::dump(), llvm::PDBSymbolTypeCustom::dump(), llvm::PDBSymbolTypeDimension::dump(), llvm::PDBSymbolCompilandDetails::dump(), llvm::PDBSymbolThunk::dump(), llvm::PDBSymbolExe::dump(), llvm::PDBSymbolData::dump(), llvm::PDBSymbolTypePointer::dump(), llvm::PDBSymbolTypeArray::dump(), llvm::PDBSymbolCustom::dump(), and llvm::PDBSymbolTypeFunctionSig::dump().
void PDBSymDumper::dump (const PDBSymbolBlock & Symbol) [virtual]
Definition at line 28 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolCompiland & Symbol) [virtual]
Definition at line 32 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolCompilandDetails & Symbol) [virtual]
Definition at line 36 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolCompilandEnv & Symbol) [virtual]
Definition at line 40 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolCustom & Symbol) [virtual]
Definition at line 44 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolData & Symbol) [virtual]
Definition at line 48 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolExe & Symbol) [virtual]
Definition at line 52 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolFunc & Symbol) [virtual]
Definition at line 56 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolFuncDebugEnd & Symbol) [virtual]
Definition at line 60 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolFuncDebugStart & Symbol) [virtual]
Definition at line 64 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolLabel & Symbol) [virtual]
Definition at line 68 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolPublicSymbol & Symbol) [virtual]
Definition at line 72 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolThunk & Symbol) [virtual]
Definition at line 76 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolTypeArray & Symbol) [virtual]
Definition at line 80 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolTypeBaseClass & Symbol) [virtual]
Definition at line 84 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolTypeBuiltin & Symbol) [virtual]
Definition at line 88 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolTypeCustom & Symbol) [virtual]
Definition at line 92 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolTypeDimension & Symbol) [virtual]
Definition at line 96 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolTypeEnum & Symbol) [virtual]
Definition at line 100 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolTypeFriend & Symbol) [virtual]
Definition at line 104 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolTypeFunctionArg & Symbol) [virtual]
Definition at line 108 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolTypeFunctionSig & Symbol) [virtual]
Definition at line 112 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolTypeManaged & Symbol) [virtual]
Definition at line 116 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolTypePointer & Symbol) [virtual]
Definition at line 120 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolTypeTypedef & Symbol) [virtual]
Definition at line 124 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolTypeUDT & Symbol) [virtual]
Definition at line 128 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolTypeVTable & Symbol) [virtual]
Definition at line 132 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolTypeVTableShape & Symbol) [virtual]
Definition at line 136 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolUnknown & Symbol) [virtual]
Definition at line 140 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
void PDBSymDumper::dump (const PDBSymbolUsingNamespace & Symbol) [virtual]
Definition at line 144 of file PDBSymDumper.cpp.
References PDB_SYMDUMP_UNREACHABLE.
The documentation for this class was generated from the following files:
PDBSymDumper.h
PDBSymDumper.cpp