LLVM: llvm::final< T > Class Template Reference
llvm::final< T > Class Template Reference
FoldingSet - This template class is used to instantiate a specialized implementation of the folding set to the node class T.
#include <FoldingSet.h>
Classes
struct UnitOffsetComparator
Public Types
typedef FoldingSetIterator< T > iterator
typedef FoldingSetIterator
< const T > const_iterator
typedef
FoldingSetBucketIterator< T > bucket_iterator
typedef FoldingSetIterator< T > iterator
typedef FoldingSetIterator
< const T > const_iterator
typedef
FoldingSetBucketIterator< T > bucket_iterator
typedef llvm::SmallVectorImpl
< std::unique_ptr< UnitType > > UnitVector
typedef UnitVector::iterator iterator
typedef llvm::iterator_range
< typename
UnitVector::iterator > iterator_range
Public Member Functions
FoldingSet (unsigned Log2InitSize=6)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bucket_iterator bucket_begin (unsigned hash)
bucket_iterator bucket_end (unsigned hash)
T * GetOrInsertNode (Node *N)
GetOrInsertNode - If there is an existing simple Node exactly equal to the specified node, return it.
T * FindNodeOrInsertPos (const FoldingSetNodeID &ID, void *&InsertPos)
FindNodeOrInsertPos - Look up the node specified by ID.
ContextualFoldingSet (Ctx Context, unsigned Log2InitSize=6)
Ctx getContext () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bucket_iterator bucket_begin (unsigned hash)
bucket_iterator bucket_end (unsigned hash)
T * GetOrInsertNode (Node *N)
GetOrInsertNode - If there is an existing simple Node exactly equal to the specified node, return it.
T * FindNodeOrInsertPos (const FoldingSetNodeID &ID, void *&InsertPos)
FindNodeOrInsertPos - Look up the node specified by ID.
Model (T Impl)
~Model () override
unsigned getOperationCost (unsigned Opcode, Type *Ty, Type *OpTy) override
unsigned getGEPCost (const Value *Ptr, ArrayRef< const Value * > Operands) override
unsigned getCallCost (FunctionType *FTy, int NumArgs) override
unsigned getCallCost (const Function *F, int NumArgs) override
unsigned getCallCost (const Function *F, ArrayRef< const Value * > Arguments) override
unsigned getIntrinsicCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< Type * > ParamTys) override
unsigned getIntrinsicCost (Intrinsic::ID IID, Type *RetTy, ArrayRef< const Value * > Arguments) override
unsigned getUserCost (const User *U) override
bool hasBranchDivergence () override
bool isSourceOfDivergence (const Value *V) override
bool isLoweredToCall (const Function *F) override
void getUnrollingPreferences (Loop *L, UnrollingPreferences &UP) override
bool isLegalAddImmediate (int64_t Imm) override
bool isLegalICmpImmediate (int64_t Imm) override
bool isLegalAddressingMode (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) override
bool isLegalMaskedStore (Type *DataType, int Consecutive) override
bool isLegalMaskedLoad (Type *DataType, int Consecutive) override
int getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) override
bool isTruncateFree (Type *Ty1, Type *Ty2) override
bool isProfitableToHoist (Instruction *I) override
bool isTypeLegal (Type *Ty) override
unsigned getJumpBufAlignment () override
unsigned getJumpBufSize () override
bool shouldBuildLookupTables () override
bool enableAggressiveInterleaving (bool LoopHasReductions) override
PopcntSupportKind getPopcntSupport (unsigned IntTyWidthInBit) override
bool haveFastSqrt (Type *Ty) override
unsigned getFPOpCost (Type *Ty) override
unsigned getIntImmCost (const APInt &Imm, Type *Ty) override
unsigned getIntImmCost (unsigned Opc, unsigned Idx, const APInt &Imm, Type *Ty) override
unsigned getIntImmCost (Intrinsic::ID IID, unsigned Idx, const APInt &Imm, Type *Ty) override
unsigned getNumberOfRegisters (bool Vector) override
unsigned getRegisterBitWidth (bool Vector) override
unsigned getMaxInterleaveFactor (unsigned VF) override
unsigned getArithmeticInstrCost (unsigned Opcode, Type *Ty, OperandValueKind Opd1Info, OperandValueKind Opd2Info, OperandValueProperties Opd1PropInfo, OperandValueProperties Opd2PropInfo) override
unsigned getShuffleCost (ShuffleKind Kind, Type *Tp, int Index, Type *SubTp) override
unsigned getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src) override
unsigned getCFInstrCost (unsigned Opcode) override
unsigned getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy) override
unsigned getVectorInstrCost (unsigned Opcode, Type *Val, unsigned Index) override
unsigned getMemoryOpCost (unsigned Opcode, Type *Src, unsigned Alignment, unsigned AddressSpace) override
unsigned getMaskedMemoryOpCost (unsigned Opcode, Type *Src, unsigned Alignment, unsigned AddressSpace) override
unsigned getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace) override
unsigned getReductionCost (unsigned Opcode, Type *Ty, bool IsPairwiseForm) override
unsigned getIntrinsicInstrCost (Intrinsic::ID ID, Type *RetTy, ArrayRef< Type * > Tys) override
unsigned getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type * > Tys) override
unsigned getNumberOfParts (Type *Tp) override
unsigned getAddressComputationCost (Type *Ty, bool IsComplex) override
unsigned getCostOfKeepingLiveOverCall (ArrayRef< Type * > Tys) override
bool getTgtMemIntrinsic (IntrinsicInst *Inst, MemIntrinsicInfo &Info) override
Value * getOrCreateResultFromMemIntrinsic (IntrinsicInst *Inst, Type *ExpectedType) override
DWARFUnitSection ()
DWARFUnitSection (DWARFUnitSection &&DUS)
UnitType * getUnitForOffset (uint32_t Offset) const override
Returns the Unit that contains the given section offset in the same section this Unit originated from.
format_object (const char *fmt, const Ts &...vals)
int snprint (char *Buffer, unsigned BufferSize) const override
Call snprintf() for this object, on the given buffer and size.
BumpPtrStringSaver (BumpPtrAllocator &Alloc)
X86ATTInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printRegName (raw_ostream &OS, unsigned RegNo) const override
Print the assembler register name.
void printInst (const MCInst *MI, raw_ostream &OS, StringRef Annot, const MCSubtargetInfo &STI) override
Print the specified MCInst to the specified raw_ostream.
bool printAliasInstr (const MCInst *MI, raw_ostream &OS)
void printCustomAliasOperand (const MCInst *MI, unsigned OpIdx, unsigned PrintMethodIdx, raw_ostream &O)
void printInstruction (const MCInst *MI, raw_ostream &OS)
void printOperand (const MCInst *MI, unsigned OpNo, raw_ostream &OS)
void printMemReference (const MCInst *MI, unsigned Op, raw_ostream &OS)
void printSSEAVXCC (const MCInst *MI, unsigned Op, raw_ostream &OS)
void printXOPCC (const MCInst *MI, unsigned Op, raw_ostream &OS)
void printPCRelImm (const MCInst *MI, unsigned OpNo, raw_ostream &OS)
void printSrcIdx (const MCInst *MI, unsigned OpNo, raw_ostream &OS)
void printDstIdx (const MCInst *MI, unsigned OpNo, raw_ostream &OS)
void printMemOffset (const MCInst *MI, unsigned OpNo, raw_ostream &OS)
void printRoundingControl (const MCInst *MI, unsigned Op, raw_ostream &OS)
void printU8Imm (const MCInst *MI, unsigned Op, raw_ostream &OS)
void printanymem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printopaquemem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printi8mem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printi16mem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printi32mem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printi64mem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printi128mem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printi256mem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printi512mem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printf32mem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printf64mem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printf80mem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printf128mem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printf256mem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printf512mem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printSrcIdx8 (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printSrcIdx16 (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printSrcIdx32 (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printSrcIdx64 (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printDstIdx8 (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printDstIdx16 (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printDstIdx32 (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printDstIdx64 (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printMemOffs8 (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printMemOffs16 (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printMemOffs32 (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printMemOffs64 (const MCInst *MI, unsigned OpNo, raw_ostream &O)
X86IntelInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printRegName (raw_ostream &OS, unsigned RegNo) const override
Print the assembler register name.
void printInst (const MCInst *MI, raw_ostream &OS, StringRef Annot, const MCSubtargetInfo &STI) override
Print the specified MCInst to the specified raw_ostream.
void printInstruction (const MCInst *MI, raw_ostream &O)
void printOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printMemReference (const MCInst *MI, unsigned Op, raw_ostream &O)
void printSSEAVXCC (const MCInst *MI, unsigned Op, raw_ostream &O)
void printXOPCC (const MCInst *MI, unsigned Op, raw_ostream &O)
void printPCRelImm (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printMemOffset (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printSrcIdx (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printDstIdx (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printRoundingControl (const MCInst *MI, unsigned Op, raw_ostream &OS)
void printU8Imm (const MCInst *MI, unsigned Op, raw_ostream &O)
void printanymem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printopaquemem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printi8mem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printi16mem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printi32mem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printi64mem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printi128mem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printi256mem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printi512mem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printf32mem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printf64mem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printf80mem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printf128mem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printf256mem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printf512mem (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printSrcIdx8 (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printSrcIdx16 (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printSrcIdx32 (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printSrcIdx64 (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printDstIdx8 (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printDstIdx16 (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printDstIdx32 (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printDstIdx64 (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printMemOffs8 (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printMemOffs16 (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printMemOffs32 (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printMemOffs64 (const MCInst *MI, unsigned OpNo, raw_ostream &O)
X86InstrInfo (X86Subtarget &STI)
const X86RegisterInfo & getRegisterInfo () const
getRegisterInfo - TargetInstrInfo is a superset of MRegister info.
int getSPAdjust (const MachineInstr *MI) const override
getSPAdjust - This returns the stack pointer adjustment made by this instruction.
bool isCoalescableExtInstr (const MachineInstr &MI, unsigned &SrcReg, unsigned &DstReg, unsigned &SubIdx) const override
isCoalescableExtInstr - Return true if the instruction is a "coalescable" extension instruction.
unsigned isLoadFromStackSlot (const MachineInstr *MI, int &FrameIndex) const override
unsigned isLoadFromStackSlotPostFE (const MachineInstr *MI, int &FrameIndex) const override
isLoadFromStackSlotPostFE - Check for post-frame ptr elimination stack locations as well.
unsigned isStoreToStackSlot (const MachineInstr *MI, int &FrameIndex) const override
unsigned isStoreToStackSlotPostFE (const MachineInstr *MI, int &FrameIndex) const override
isStoreToStackSlotPostFE - Check for post-frame ptr elimination stack locations as well.
bool isReallyTriviallyReMaterializable (const MachineInstr *MI, AliasAnalysis *AA) const override
void reMaterialize (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, unsigned DestReg, unsigned SubIdx, const MachineInstr *Orig, const TargetRegisterInfo &TRI) const override
bool classifyLEAReg (MachineInstr *MI, const MachineOperand &Src, unsigned LEAOpcode, bool AllowSP, unsigned &NewSrc, bool &isKill, bool &isUndef, MachineOperand &ImplicitOp) const
Given an operand within a MachineInstr, insert preceding code to put it into the right format for a particular kind of LEA instruction.
MachineInstr * convertToThreeAddress (MachineFunction::iterator &MFI, MachineBasicBlock::iterator &MBBI, LiveVariables *LV) const override
convertToThreeAddress - This method must be implemented by targets that set the M_CONVERTIBLE_TO_3_ADDR flag.
MachineInstr * commuteInstruction (MachineInstr *MI, bool NewMI) const override
commuteInstruction - We have a few instructions that must be hacked on to commute them.
bool findCommutedOpIndices (MachineInstr *MI, unsigned &SrcOpIdx1, unsigned &SrcOpIdx2) const override
bool isUnpredicatedTerminator (const MachineInstr *MI) const override
bool AnalyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify) const override
bool getMemOpBaseRegImmOfs (MachineInstr *LdSt, unsigned &BaseReg, unsigned &Offset, const TargetRegisterInfo *TRI) const override
bool AnalyzeBranchPredicate (MachineBasicBlock &MBB, TargetInstrInfo::MachineBranchPredicate &MBP, bool AllowModify=false) const override
unsigned RemoveBranch (MachineBasicBlock &MBB) const override
unsigned InsertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, ArrayRef< MachineOperand > Cond, DebugLoc DL) const override
bool canInsertSelect (const MachineBasicBlock &, ArrayRef< MachineOperand > Cond, unsigned, unsigned, int &, int &, int &) const override
void insertSelect (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, DebugLoc DL, unsigned DstReg, ArrayRef< MachineOperand > Cond, unsigned TrueReg, unsigned FalseReg) const override
void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc) const override
void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
void storeRegToAddr (MachineFunction &MF, unsigned SrcReg, bool isKill, SmallVectorImpl< MachineOperand > &Addr, const TargetRegisterClass *RC, MachineInstr::mmo_iterator MMOBegin, MachineInstr::mmo_iterator MMOEnd, SmallVectorImpl< MachineInstr * > &NewMIs) const
void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, unsigned DestReg, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
void loadRegFromAddr (MachineFunction &MF, unsigned DestReg, SmallVectorImpl< MachineOperand > &Addr, const TargetRegisterClass *RC, MachineInstr::mmo_iterator MMOBegin, MachineInstr::mmo_iterator MMOEnd, SmallVectorImpl< MachineInstr * > &NewMIs) const
bool expandPostRAPseudo (MachineBasicBlock::iterator MI) const override
MachineInstr * foldMemoryOperandImpl (MachineFunction &MF, MachineInstr *MI, ArrayRef< unsigned > Ops, MachineBasicBlock::iterator InsertPt, int FrameIndex) const override
foldMemoryOperand - If this target supports it, fold a load or store of the specified stack slot into the specified machine instruction for the specified operand(s).
MachineInstr * foldMemoryOperandImpl (MachineFunction &MF, MachineInstr *MI, ArrayRef< unsigned > Ops, MachineBasicBlock::iterator InsertPt, MachineInstr *LoadMI) const override
foldMemoryOperand - Same as the previous version except it allows folding of any load and store from / to any address, not just from a specific stack slot.
bool canFoldMemoryOperand (const MachineInstr *, ArrayRef< unsigned >) const override
canFoldMemoryOperand - Returns true if the specified load / store is folding is possible.
bool unfoldMemoryOperand (MachineFunction &MF, MachineInstr *MI, unsigned Reg, bool UnfoldLoad, bool UnfoldStore, SmallVectorImpl< MachineInstr * > &NewMIs) const override
unfoldMemoryOperand - Separate a single instruction which folded a load or a store or a load and a store into two or more instruction.
bool unfoldMemoryOperand (SelectionDAG &DAG, SDNode *N, SmallVectorImpl< SDNode * > &NewNodes) const override
unsigned getOpcodeAfterMemoryUnfold (unsigned Opc, bool UnfoldLoad, bool UnfoldStore, unsigned *LoadRegIndex=nullptr) const override
getOpcodeAfterMemoryUnfold - Returns the opcode of the would be new instruction after load / store are unfolded from an instruction of the specified opcode.
bool areLoadsFromSameBasePtr (SDNode *Load1, SDNode *Load2, int64_t &Offset1, int64_t &Offset2) const override
areLoadsFromSameBasePtr - This is used by the pre-regalloc scheduler to determine if two loads are loading from the same base address.
bool shouldScheduleLoadsNear (SDNode *Load1, SDNode *Load2, int64_t Offset1, int64_t Offset2, unsigned NumLoads) const override
shouldScheduleLoadsNear - This is a used by the pre-regalloc scheduler to determine (in conjunction with areLoadsFromSameBasePtr) if two loads should be scheduled togther.
bool shouldScheduleAdjacent (MachineInstr *First, MachineInstr *Second) const override
void getNoopForMachoTarget (MCInst &NopInst) const override
bool ReverseBranchCondition (SmallVectorImpl< MachineOperand > &Cond) const override
bool isSafeToMoveRegClassDefs (const TargetRegisterClass *RC) const override
isSafeToMoveRegClassDefs - Return true if it's safe to move a machine instruction that defines the specified register class.
bool isSafeToClobberEFLAGS (MachineBasicBlock &MBB, MachineBasicBlock::iterator I) const
isSafeToClobberEFLAGS - Return true if it's safe insert an instruction tha would clobber the EFLAGS condition register.
unsigned getGlobalBaseReg (MachineFunction *MF) const
getGlobalBaseReg - Return a virtual register initialized with the the global base register value.
std::pair< uint16_t, uint16_t > getExecutionDomain (const MachineInstr *MI) const override
void setExecutionDomain (MachineInstr *MI, unsigned Domain) const override
unsigned getPartialRegUpdateClearance (const MachineInstr *MI, unsigned OpNum, const TargetRegisterInfo *TRI) const override
unsigned getUndefRegClearance (const MachineInstr *MI, unsigned &OpNum, const TargetRegisterInfo *TRI) const override
void breakPartialRegDependency (MachineBasicBlock::iterator MI, unsigned OpNum, const TargetRegisterInfo *TRI) const override
MachineInstr * foldMemoryOperandImpl (MachineFunction &MF, MachineInstr *MI, unsigned OpNum, ArrayRef< MachineOperand > MOs, MachineBasicBlock::iterator InsertPt, unsigned Size, unsigned Alignment, bool AllowCommute) const
void getUnconditionalBranch (MCInst &Branch, const MCSymbolRefExpr *BranchTarget) const override
void getTrap (MCInst &MI) const override
unsigned getJumpInstrTableEntryBound () const override
bool isHighLatencyDef (int opc) const override
bool hasHighOperandLatency (const TargetSchedModel &SchedModel, const MachineRegisterInfo *MRI, const MachineInstr *DefMI, unsigned DefIdx, const MachineInstr *UseMI, unsigned UseIdx) const override
bool useMachineCombiner () const override
bool getMachineCombinerPatterns (MachineInstr &Root, SmallVectorImpl< MachineCombinerPattern::MC_PATTERN > &P) const override
Return true when there is potentially a faster code sequence for an instruction chain ending in <Root>.
void genAlternativeCodeSequence (MachineInstr &Root, MachineCombinerPattern::MC_PATTERN P, SmallVectorImpl< MachineInstr * > &InsInstrs, SmallVectorImpl< MachineInstr * > &DelInstrs, DenseMap< unsigned, unsigned > &InstrIdxForVirtReg) const override
When getMachineCombinerPatterns() finds a pattern, this function generates the instructions that could replace the original code sequence.
bool analyzeCompare (const MachineInstr *MI, unsigned &SrcReg, unsigned &SrcReg2, int &CmpMask, int &CmpValue) const override
analyzeCompare - For a comparison instruction, return the source registers in SrcReg and SrcReg2 if having two register operands, and the value it compares against in CmpValue.
bool optimizeCompareInstr (MachineInstr *CmpInstr, unsigned SrcReg, unsigned SrcReg2, int CmpMask, int CmpValue, const MachineRegisterInfo *MRI) const override
optimizeCompareInstr - Check if there exists an earlier instruction that operates on the same source operands and sets flags in the same way as Compare; remove Compare if possible.
MachineInstr * optimizeLoadInstr (MachineInstr *MI, const MachineRegisterInfo *MRI, unsigned &FoldAsLoadDefReg, MachineInstr *&DefMI) const override
optimizeLoadInstr - Try to remove the load by folding it to a register operand at the use.
X86TargetLowering (const X86TargetMachine &TM, const X86Subtarget &STI)
unsigned getJumpTableEncoding () const override
Return the entry encoding for a jump table in the current function.
bool useSoftFloat () const override
MVT getScalarShiftAmountTy (EVT LHSTy) const override
const MCExpr * LowerCustomJumpTableEntry (const MachineJumpTableInfo *MJTI, const MachineBasicBlock *MBB, unsigned uid, MCContext &Ctx) const override
SDValue getPICJumpTableRelocBase (SDValue Table, SelectionDAG &DAG) const override
Returns relocation base for the given PIC jumptable.
const MCExpr * getPICJumpTableRelocBaseExpr (const MachineFunction *MF, unsigned JTI, MCContext &Ctx) const override
This returns the relocation base for the given PIC jumptable, the same as getPICJumpTableRelocBase, but as an MCExpr.
unsigned getByValTypeAlignment (Type *Ty) const override
Return the desired alignment for ByVal aggregate function arguments in the caller parameter area.
EVT getOptimalMemOpType (uint64_t Size, unsigned DstAlign, unsigned SrcAlign, bool IsMemset, bool ZeroMemset, bool MemcpyStrSrc, MachineFunction &MF) const override
Returns the target specific optimal type for load and store operations as a result of memset, memcpy, and memmove lowering.
bool isSafeMemOpType (MVT VT) const override
Returns true if it's safe to use load / store of the specified type to expand memcpy / memset inline.
bool allowsMisalignedMemoryAccesses (EVT VT, unsigned AS, unsigned Align, bool *Fast) const override
Returns true if the target allows unaligned memory accesses.
SDValue LowerOperation (SDValue Op, SelectionDAG &DAG) const override
Provide custom lowering hooks for some operations.
void ReplaceNodeResults (SDNode *N, SmallVectorImpl< SDValue > &Results, SelectionDAG &DAG) const override
Replace the results of node with an illegal result type with new values built out of custom code.
SDValue PerformDAGCombine (SDNode *N, DAGCombinerInfo &DCI) const override
This method will be invoked for all target nodes and for any target-independent nodes that the target has registered with invoke it for.
bool isTypeDesirableForOp (unsigned Opc, EVT VT) const override
Return true if the target has native support for the specified value type and it is 'desirable' to use the type for the given node type.
bool IsDesirableToPromoteOp (SDValue Op, EVT &PVT) const override
Return true if the target has native support for the specified value type and it is 'desirable' to use the type.
MachineBasicBlock * EmitInstrWithCustomInserter (MachineInstr *MI, MachineBasicBlock *MBB) const override
This method should be implemented by targets that mark instructions with the 'usesCustomInserter' flag.
const char * getTargetNodeName (unsigned Opcode) const override
This method returns the name of a target specific DAG node.
bool isCheapToSpeculateCttz () const override
Return true if it is cheap to speculate a call to intrinsic cttz.
bool isCheapToSpeculateCtlz () const override
Return true if it is cheap to speculate a call to intrinsic ctlz.
EVT getSetCCResultType (LLVMContext &Context, EVT VT) const override
Return the value type to use for ISD::SETCC.
void computeKnownBitsForTargetNode (const SDValue Op, APInt &KnownZero, APInt &KnownOne, const SelectionDAG &DAG, unsigned Depth=0) const override
Determine which of the bits specified in Mask are known to be either zero or one and return them in the KnownZero/KnownOne bitsets.
unsigned ComputeNumSignBitsForTargetNode (SDValue Op, const SelectionDAG &DAG, unsigned Depth) const override
Determine the number of bits in the operation that are sign bits.
bool isGAPlusOffset (SDNode *N, const GlobalValue *&GA, int64_t &Offset) const override
Returns true (and the GlobalValue and the offset) if the node is a GlobalAddress + offset.
SDValue getReturnAddressFrameIndex (SelectionDAG &DAG) const
bool ExpandInlineAsm (CallInst *CI) const override
This hook allows the target to expand an inline asm call to be explicit llvm code if it wants to.
ConstraintType getConstraintType (const std::string &Constraint) const override
Given a constraint, return the type of constraint it is for this target.
ConstraintWeight getSingleConstraintMatchWeight (AsmOperandInfo &info, const char *constraint) const override
Examine constraint string and operand type and determine a weight value.
const char * LowerXConstraint (EVT ConstraintVT) const override
Try to replace an X constraint, which matches anything, with another that has more specific requirements based on the type of the corresponding operand.
void LowerAsmOperandForConstraint (SDValue Op, std::string &Constraint, std::vector< SDValue > &Ops, SelectionDAG &DAG) const override
Lower the specified operand into the Ops vector.
unsigned getInlineAsmMemConstraint (const std::string &ConstraintCode) const override
std::pair< unsigned, const
TargetRegisterClass * > getRegForInlineAsmConstraint (const TargetRegisterInfo *TRI, const std::string &Constraint, MVT VT) const override
Given a physical register constraint (e.g.
bool isLegalAddressingMode (const AddrMode &AM, Type *Ty, unsigned AS) const override
Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
bool isLegalICmpImmediate (int64_t Imm) const override
Return true if the specified immediate is legal icmp immediate, that is the target has icmp instructions which can compare a register against the immediate without having to materialize the immediate into a register.
bool isLegalAddImmediate (int64_t Imm) const override
Return true if the specified immediate is legal add immediate, that is the target has add instructions which can add a register and the immediate without having to materialize the immediate into a register.
int getScalingFactorCost (const AddrMode &AM, Type *Ty, unsigned AS) const override
Return the cost of the scaling factor used in the addressing mode represented by AM for this target, for a load/store of the specified type.
bool isVectorShiftByScalarCheap (Type *Ty) const override
Return true if it's significantly cheaper to shift a vector by a uniform scalar than by an amount which will vary across each lane.
bool isTruncateFree (Type *Ty1, Type *Ty2) const override
Return true if it's free to truncate a value of type Ty1 to type Ty2.
bool isTruncateFree (EVT VT1, EVT VT2) const override
bool allowTruncateForTailCall (Type *Ty1, Type *Ty2) const override
Return true if a truncation from Ty1 to Ty2 is permitted when deciding whether a call is in tail position.
bool isZExtFree (Type *Ty1, Type *Ty2) const override
Return true if any actual instruction that defines a value of type Ty1 implicit zero-extends the value to Ty2 in the result register.
bool isZExtFree (EVT VT1, EVT VT2) const override
bool isZExtFree (SDValue Val, EVT VT2) const override
Return true if zero-extending the specific node Val to type VT2 is free (either because it's implicitly zero-extended such as ARM ldrb / ldrh or because it's folded such as X86 zero-extending loads).
bool isVectorLoadExtDesirable (SDValue) const override
Return true if folding a vector load into ExtVal (a sign, zero, or any extend node) is profitable.
bool isFMAFasterThanFMulAndFAdd (EVT VT) const override
Return true if an FMA operation is faster than a pair of fmul and fadd instructions.
bool isNarrowingProfitable (EVT VT1, EVT VT2) const override
Return true if it's profitable to narrow operations of type VT1 to VT2.
bool isFPImmLegal (const APFloat &Imm, EVT VT) const override
Returns true if the target can instruction select the specified FP immediate natively.
bool isShuffleMaskLegal (const SmallVectorImpl< int > &Mask, EVT VT) const override
Targets can use this to indicate that they only support *some* VECTOR_SHUFFLE operations, those with specific masks.
bool isVectorClearMaskLegal (const SmallVectorImpl< int > &Mask, EVT VT) const override
Similar to isShuffleMaskLegal.
bool ShouldShrinkFPConstant (EVT VT) const override
If true, then instruction selection should seek to shrink the FP constant of the specified type to a smaller type in order to save space and / or reduce runtime.
bool shouldReduceLoadWidth (SDNode *Load, ISD::LoadExtType ExtTy, EVT NewVT) const override
Return true if we believe it is correct and profitable to reduce the load node to a smaller type.
bool isScalarFPTypeInSSEReg (EVT VT) const
Return true if the specified scalar FP type is computed in an SSE register, not on the X87 floating point stack.
bool isTargetFTOL () const
Return true if the target uses the MSVC _ftol2 routine for fptoui.
bool isIntegerTypeFTOL (EVT VT) const
Return true if the MSVC _ftol2 routine should be used for fptoui to the given type.
bool shouldConvertConstantLoadToIntImm (const APInt &Imm, Type *Ty) const override
Returns true if it is beneficial to convert a load of a constant to just the constant itself.
bool isExtractSubvectorCheap (EVT ResVT, unsigned Index) const override
Return true if EXTRACT_SUBVECTOR is cheap for this result type with this index.
const char * getClearCacheBuiltinName () const override
Intel processors have a unified instruction and data cache.
unsigned getRegisterByName (const char *RegName, EVT VT) const override
Return the register ID of the name passed in.
FastISel * createFastISel (FunctionLoweringInfo &funcInfo, const TargetLibraryInfo *libInfo) const override
This method returns a target specific FastISel object, or null if the target does not support "fast" ISel.
bool getStackCookieLocation (unsigned &AddressSpace, unsigned &Offset) const override
Return true if the target stores stack protector cookies at a fixed offset in some non-standard address space, and populates the address space and offset as appropriate.
SDValue BuildFILD (SDValue Op, EVT SrcVT, SDValue Chain, SDValue StackSlot, SelectionDAG &DAG) const
bool isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const override
Returns true if a cast between SrcAS and DestAS is a noop.
bool useLoadStackGuardNode () const override
If this function returns true, SelectionDAGBuilder emits a LOAD_STACK_GUARD node when it is lowering Intrinsic::stackprotector.
LegalizeTypeAction getPreferredVectorAction (EVT VT) const override
Customize the preferred legalization strategy for certain types.
X86RegisterInfo (const Triple &TT)
int getSEHRegNum (unsigned i) const
bool trackLivenessAfterRegAlloc (const MachineFunction &MF) const override
Code Generation virtual methods...
const TargetRegisterClass * getMatchingSuperRegClass (const TargetRegisterClass *A, const TargetRegisterClass *B, unsigned Idx) const override
getMatchingSuperRegClass - Return a subclass of the specified register class A so that each register in it has a sub-register of the specified sub-register index which is in the specified register class B.
const TargetRegisterClass * getSubClassWithSubReg (const TargetRegisterClass *RC, unsigned Idx) const override
const TargetRegisterClass * getLargestLegalSuperClass (const TargetRegisterClass *RC, const MachineFunction &MF) const override
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind=0) const override
getPointerRegClass - Returns a TargetRegisterClass used for pointer values.
const TargetRegisterClass * getCrossCopyRegClass (const TargetRegisterClass *RC) const override
getCrossCopyRegClass - Returns a legal register class to copy a register in the specified class to or from.
unsigned getRegPressureLimit (const TargetRegisterClass *RC, MachineFunction &MF) const override
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
getCalleeSavedRegs - Return a null-terminated list of all of the callee-save registers on this target.
const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID) const override
const uint32_t * getNoPreservedMask () const
BitVector getReservedRegs (const MachineFunction &MF) const override
getReservedRegs - Returns a bitset indexed by physical register number indicating if a register is a special register that has particular uses and should be considered unavailable at all times, e.g.
void adjustStackMapLiveOutMask (uint32_t *Mask) const override
bool hasBasePointer (const MachineFunction &MF) const
bool canRealignStack (const MachineFunction &MF) const
bool needsStackRealignment (const MachineFunction &MF) const override
bool hasReservedSpillSlot (const MachineFunction &MF, unsigned Reg, int &FrameIdx) const override
void eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
unsigned getFrameRegister (const MachineFunction &MF) const override
unsigned getPtrSizedFrameRegister (const MachineFunction &MF) const
unsigned getStackRegister () const
unsigned getBaseRegister () const
unsigned getSlotSize () const
X86Subtarget (const Triple &TT, const std::string &CPU, const std::string &FS, const X86TargetMachine &TM, unsigned StackAlignOverride)
This constructor initializes the data members to match that of the specified triple.
const X86TargetLowering * getTargetLowering () const override
const X86InstrInfo * getInstrInfo () const override
const X86FrameLowering * getFrameLowering () const override
const X86SelectionDAGInfo * getSelectionDAGInfo () const override
const X86RegisterInfo * getRegisterInfo () const override
unsigned getStackAlignment () const
Returns the minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function for this subtarget.
unsigned getMaxInlineSizeThreshold () const
Returns the maximum memset / memcpy size that still makes it profitable to inline the call.
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
bool is64Bit () const
Is this x86_64? (disregarding specific ABI / programming model)
bool is32Bit () const
bool is16Bit () const
bool isTarget64BitILP32 () const
Is this x86_64 with the ILP32 programming model (x32 ABI)?
bool isTarget64BitLP64 () const
Is this x86_64 with the LP64 programming model (standard AMD64, no x32)?
PICStyles::Style getPICStyle () const
void setPICStyle (PICStyles::Style Style)
bool hasCMov () const
bool hasMMX () const
bool hasSSE1 () const
bool hasSSE2 () const
bool hasSSE3 () const
bool hasSSSE3 () const
bool hasSSE41 () const
bool hasSSE42 () const
bool hasAVX () const
bool hasAVX2 () const
bool hasAVX512 () const
bool hasFp256 () const
bool hasInt256 () const
bool hasSSE4A () const
bool has3DNow () const
bool has3DNowA () const
bool hasPOPCNT () const
bool hasAES () const
bool hasPCLMUL () const
bool hasFMA () const
bool hasFMA4 () const
bool hasXOP () const
bool hasTBM () const
bool hasMOVBE () const
bool hasRDRAND () const
bool hasF16C () const
bool hasFSGSBase () const
bool hasLZCNT () const
bool hasBMI () const
bool hasBMI2 () const
bool hasRTM () const
bool hasHLE () const
bool hasADX () const
bool hasSHA () const
bool hasPRFCHW () const
bool hasRDSEED () const
bool isBTMemSlow () const
bool isSHLDSlow () const
bool isUnalignedMemAccessFast () const
bool isUnalignedMem32Slow () const
bool hasSSEUnalignedMem () const
bool hasCmpxchg16b () const
bool useLeaForSP () const
bool hasSlowDivide32 () const
bool hasSlowDivide64 () const
bool padShortFunctions () const
bool callRegIndirect () const
bool LEAusesAG () const
bool slowLEA () const
bool slowIncDec () const
bool hasCDI () const
bool hasPFI () const
bool hasERI () const
bool hasDQI () const
bool hasBWI () const
bool hasVLX () const
bool hasMPX () const
bool isAtom () const
bool isSLM () const
bool useSoftFloat () const
const Triple & getTargetTriple () const
bool isTargetDarwin () const
bool isTargetFreeBSD () const
bool isTargetDragonFly () const
bool isTargetSolaris () const
bool isTargetPS4 () const
bool isTargetELF () const
bool isTargetCOFF () const
bool isTargetMachO () const
bool isTargetLinux () const
bool isTargetNaCl () const
bool isTargetNaCl32 () const
bool isTargetNaCl64 () const
bool isTargetWindowsMSVC () const
bool isTargetKnownWindowsMSVC () const
bool isTargetWindowsCygwin () const
bool isTargetWindowsGNU () const
bool isTargetWindowsItanium () const
bool isTargetCygMing () const
bool isOSWindows () const
bool isTargetWin64 () const
bool isTargetWin32 () const
bool isPICStyleSet () const
bool isPICStyleGOT () const
bool isPICStyleRIPRel () const
bool isPICStyleStubPIC () const
bool isPICStyleStubNoDynamic () const
bool isPICStyleStubAny () const
bool isCallingConvWin64 (CallingConv::ID CC) const
unsigned char ClassifyGlobalReference (const GlobalValue *GV, const TargetMachine &TM) const
ClassifyGlobalReference - Classify a global variable reference for the current subtarget according to how we should reference it in a non-pcrel context.
unsigned char ClassifyBlockAddressReference () const
Classify a blockaddress reference for the current subtarget according to how we should reference it in a non-pcrel context.
bool IsLegalToCallImmediateAddr (const TargetMachine &TM) const
Return true if the subtarget allows calls to immediate address.
const char * getBZeroEntry () const
This function returns the name of a function which has an interface like the non-standard bzero function, if such a function exists on the current subtarget and it is considered prefereable over memset with zero passed as the second argument.
bool hasSinCos () const
This function returns true if the target has sincos() routine in its compiler runtime or math libraries.
bool enableMachineScheduler () const override
Enable the MachineScheduler pass for all X86 subtargets.
bool enableEarlyIfConversion () const override
const InstrItineraryData * getInstrItineraryData () const override
Return the instruction itineraries based on the subtarget selection.
AntiDepBreakMode getAntiDepBreakMode () const override
X86TargetMachine (const Target &T, const Triple &TT, StringRef CPU, StringRef FS, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
~X86TargetMachine () override
const X86Subtarget * getSubtargetImpl (const Function &F) const override
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
TargetIRAnalysis getTargetIRAnalysis () override
Get a TargetIRAnalysis implementation for the target.
TargetPassConfig * createPassConfig (PassManagerBase &PM) override
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
TargetLoweringObjectFile * getObjFileLowering () const override
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo)
static const char * getRegisterName (unsigned RegNo)
static bool isX86_64ExtendedReg (const MachineOperand &MO)
Protected Types
enum X86SSEEnum {
NoMMXSSE, MMX, SSE1, SSE2,
SSE3, SSSE3, SSE41, SSE42,
AVX, AVX2, AVX512F
}
enum X863DNowEnum { NoThreeDNow, ThreeDNow, ThreeDNowA }
enum X86ProcFamilyEnum { Others, IntelAtom, IntelSLM }
Protected Member Functions
std::pair< const
TargetRegisterClass *, uint8_t > findRepresentativeClass (const TargetRegisterInfo *TRI, MVT VT) const override
Return the largest legal super-reg register class of the register class for the specified type and its associated "cost".
Protected Attributes
X86ProcFamilyEnum X86ProcFamily
X86 processor family: Intel Atom, and others.
PICStyles::Style PICStyle
Which PIC style to use.
X86SSEEnum X86SSELevel
MMX, SSE1, SSE2, SSE3, SSSE3, SSE41, SSE42, or none supported.
X863DNowEnum X863DNowLevel
3DNow, 3DNow Athlon, or none supported.
bool HasCMov
True if this processor has conditional move instructions (generally pentium pro+).
bool HasX86_64
True if the processor supports X86-64 instructions.
bool HasPOPCNT
True if the processor supports POPCNT.
bool HasSSE4A
True if the processor supports SSE4A instructions.
bool HasAES
Target has AES instructions.
bool HasPCLMUL
Target has carry-less multiplication.
bool HasFMA
Target has 3-operand fused multiply-add.
bool HasFMA4
Target has 4-operand fused multiply-add.
bool HasXOP
Target has XOP instructions.
bool HasTBM
Target has TBM instructions.
bool HasMOVBE
True if the processor has the MOVBE instruction.
bool HasRDRAND
True if the processor has the RDRAND instruction.
bool HasF16C
Processor has 16-bit floating point conversion instructions.
bool HasFSGSBase
Processor has FS/GS base insturctions.
bool HasLZCNT
Processor has LZCNT instruction.
bool HasBMI
Processor has BMI1 instructions.
bool HasBMI2
Processor has BMI2 instructions.
bool HasRTM
Processor has RTM instructions.
bool HasHLE
Processor has HLE.
bool HasADX
Processor has ADX instructions.
bool HasSHA
Processor has SHA instructions.
bool HasPRFCHW
Processor has PRFCHW instructions.
bool HasRDSEED
Processor has RDSEED instructions.
bool IsBTMemSlow
True if BT (bit test) of memory instructions are slow.
bool IsSHLDSlow
True if SHLD instructions are slow.
bool IsUAMemFast
True if unaligned memory access is fast.
bool IsUAMem32Slow
True if unaligned 32-byte memory accesses are slow.
bool HasSSEUnalignedMem
True if SSE operations can have unaligned memory operands.
bool HasCmpxchg16b
True if this processor has the CMPXCHG16B instruction; this is true for most x86-64 chips, but not the first AMD chips.
bool UseLeaForSP
True if the LEA instruction should be used for adjusting the stack pointer.
bool HasSlowDivide32
True if 8-bit divisions are significantly faster than 32-bit divisions and should be used when possible.
bool HasSlowDivide64
True if 16-bit divides are significantly faster than 64-bit divisions and should be used when possible.
bool PadShortFunctions
True if the short functions should be padded to prevent a stall when returning too early.
bool CallRegIndirect
True if the Calls with memory reference should be converted to a register-based indirect call.
bool LEAUsesAG
True if the LEA instruction inputs have to be ready at address generation (AG) time.
bool SlowLEA
True if the LEA instruction with certain arguments is slow.
bool SlowIncDec
True if INC and DEC instructions are slow when writing to flags.
bool HasPFI
Processor has AVX-512 PreFetch Instructions.
bool HasERI
Processor has AVX-512 Exponential and Reciprocal Instructions.
bool HasCDI
Processor has AVX-512 Conflict Detection Instructions.
bool HasDQI
Processor has AVX-512 Doubleword and Quadword instructions.
bool HasBWI
Processor has AVX-512 Byte and Word instructions.
bool HasVLX
Processor has AVX-512 Vector Length eXtenstions.
bool HasMPX
Processot supports MPX - Memory Protection Extensions.
bool UseSoftFloat
Use software floating point for code generation.
unsigned stackAlignment
The minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function.
unsigned MaxInlineSizeThreshold
Max.
Triple TargetTriple
What processor and OS we're targeting.
InstrItineraryData InstrItins
Instruction itineraries for scheduling.
Detailed Description
template<class T>
class llvm::final< T >
FoldingSet - This template class is used to instantiate a specialized implementation of the folding set to the node class T.
These are templated helper classes used by the format function that capture the object to be formated and the format string.
Concrete instance of DWARFUnitSection, specialized for one Unit type.
ContextualFoldingSet - This template class is a further refinement of FoldingSet which provides a context argument when calling Profile on its nodes.
T must be a subclass of FoldingSetNode and implement a Profile function.
Currently, that argument is fixed at initialization time.
T must be a subclass of FoldingSetNode and implement a Profile function with signature void Profile(llvm::FoldingSetNodeID &, Ctx);
When actually printed, this synthesizes the string into a temporary buffer provided and returns whether or not it is big enough.
Definition at line 396 of file FoldingSet.h.
Member Typedef Documentation
template<class T > typedef FoldingSetBucketIterator<T> llvm::final< T >::bucket_iterator
Definition at line 431 of file FoldingSet.h.
template<class T > typedef FoldingSetBucketIterator<T> llvm::final< T >::bucket_iterator
Definition at line 510 of file FoldingSet.h.
template<class T > typedef FoldingSetIterator<const T> llvm::final< T >::const_iterator
Reimplemented from llvm::SmallVectorTemplateCommon< std::unique_ptr< UnitType > >.
Definition at line 427 of file FoldingSet.h.
template<class T > typedef FoldingSetIterator<const T> llvm::final< T >::const_iterator
Reimplemented from llvm::SmallVectorTemplateCommon< std::unique_ptr< UnitType > >.
Definition at line 506 of file FoldingSet.h.
template<class T > typedef UnitVector::iterator llvm::final< T >::iterator
Reimplemented from llvm::SmallVectorImpl< std::unique_ptr< UnitType > >.
Definition at line 72 of file DWARFUnit.h.
template<class T > typedef FoldingSetIterator<T> llvm::final< T >::iterator
Reimplemented from llvm::SmallVectorImpl< std::unique_ptr< UnitType > >.
Definition at line 423 of file FoldingSet.h.
template<class T > typedef FoldingSetIterator<T> llvm::final< T >::iterator
Reimplemented from llvm::SmallVectorImpl< std::unique_ptr< UnitType > >.
Definition at line 502 of file FoldingSet.h.
template<class T > typedef llvm::iterator_range<typename UnitVector::iterator> llvm::final< T >::iterator_range
Definition at line 73 of file DWARFUnit.h.
template<class T > typedef llvm::SmallVectorImpl<std::unique_ptr<UnitType> > llvm::final< T >::UnitVector
Definition at line 71 of file DWARFUnit.h.
Member Enumeration Documentation
template<class T > enum llvm::final::X863DNowEnum [protected]
Enumerator:
NoThreeDNow
ThreeDNow
ThreeDNowA
Definition at line 53 of file X86Subtarget.h.
template<class T > enum llvm::final::X86ProcFamilyEnum [protected]
Enumerator:
Others
IntelAtom
IntelSLM
Definition at line 57 of file X86Subtarget.h.
template<class T > enum llvm::final::X86SSEEnum [protected]
Enumerator:
NoMMXSSE
MMX
SSE1
SSE2
SSE3
SSSE3
SSE41
SSE42
AVX
AVX2
AVX512F
Definition at line 49 of file X86Subtarget.h.
Constructor & Destructor Documentation
template<class T > llvm::final< T >::~Model () [inline, override]
Definition at line 630 of file TargetTransformInfo.h.
template<class T > llvm::final< T >::~X86TargetMachine () [override]
Member Function Documentation
template<class T > void llvm::final< T >::adjustStackMapLiveOutMask (uint32_t * Mask) const [override]
template<class T > bool llvm::final< T >::allowsMisalignedMemoryAccesses (EVT VT, unsigned AS, unsigned Align, bool * Fast) const [override, virtual]
Returns true if the target allows unaligned memory accesses.
of the specified type. Returns whether it is "fast" by reference in the second argument.
Reimplemented from llvm::TargetLoweringBase.
template<class T > bool llvm::final< T >::allowTruncateForTailCall (Type * , Type *) const [override, virtual]
Return true if a truncation from Ty1 to Ty2 is permitted when deciding whether a call is in tail position.
Typically this means that both results would be assigned to the same register or stack slot, but it could mean the target performs adequate checks of its own before proceeding with the tail call.
Reimplemented from llvm::TargetLoweringBase.
template<class T > bool llvm::final< T >::AnalyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify) const [override]
template<class T > bool llvm::final< T >::AnalyzeBranchPredicate (MachineBasicBlock & MBB, TargetInstrInfo::MachineBranchPredicate & MBP, bool AllowModify = false) const [override]
template<class T > bool llvm::final< T >::analyzeCompare (const MachineInstr * MI, unsigned & SrcReg, unsigned & SrcReg2, int & CmpMask, int & CmpValue) const [override]
analyzeCompare - For a comparison instruction, return the source registers in SrcReg and SrcReg2 if having two register operands, and the value it compares against in CmpValue.
Return true if the comparison instruction can be analyzed.
template<class T > bool llvm::final< T >::areLoadsFromSameBasePtr (SDNode * Load1, SDNode * Load2, int64_t & Offset1, int64_t & Offset2) const [override]
areLoadsFromSameBasePtr - This is used by the pre-regalloc scheduler to determine if two loads are loading from the same base address.
It should only return true if the base pointers are the same and the only differences between the two addresses are the offset. It also returns the offsets by reference.
template<class T > iterator llvm::final< T >::begin () [inline]
Reimplemented from llvm::SmallVectorTemplateCommon< std::unique_ptr< UnitType > >.
Definition at line 424 of file FoldingSet.h.
template<class T > const_iterator llvm::final< T >::begin () const [inline]
Reimplemented from llvm::SmallVectorTemplateCommon< std::unique_ptr< UnitType > >.
Definition at line 428 of file FoldingSet.h.
template<class T > iterator llvm::final< T >::begin () [inline]
Reimplemented from llvm::SmallVectorTemplateCommon< std::unique_ptr< UnitType > >.
Definition at line 503 of file FoldingSet.h.
template<class T > const_iterator llvm::final< T >::begin () const [inline]
Reimplemented from llvm::SmallVectorTemplateCommon< std::unique_ptr< UnitType > >.
Definition at line 507 of file FoldingSet.h.
template<class T > void llvm::final< T >::breakPartialRegDependency (MachineBasicBlock::iterator MI, unsigned OpNum, const TargetRegisterInfo * TRI) const [override]
template<class T > bucket_iterator llvm::final< T >::bucket_begin (unsigned hash) [inline]
Definition at line 433 of file FoldingSet.h.
template<class T > bucket_iterator llvm::final< T >::bucket_begin (unsigned hash) [inline]
Definition at line 512 of file FoldingSet.h.
template<class T > bucket_iterator llvm::final< T >::bucket_end (unsigned hash) [inline]
Definition at line 437 of file FoldingSet.h.
template<class T > bucket_iterator llvm::final< T >::bucket_end (unsigned hash) [inline]
Definition at line 516 of file FoldingSet.h.
template<class T > SDValue llvm::final< T >::BuildFILD (SDValue Op, EVT SrcVT, SDValue Chain, SDValue StackSlot, SelectionDAG & DAG) const
template<class T > llvm::final< T >::BumpPtrStringSaver (BumpPtrAllocator & Alloc) [inline]
Definition at line 39 of file StringSaver.h.
template<class T > bool llvm::final< T >::callRegIndirect () const [inline]
Definition at line 368 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::canFoldMemoryOperand (const MachineInstr * , ArrayRef< unsigned >) const [override]
canFoldMemoryOperand - Returns true if the specified load / store is folding is possible.
template<class T > bool llvm::final< T >::canInsertSelect (const MachineBasicBlock & , ArrayRef< MachineOperand > Cond, unsigned , unsigned , int & , int & , int &) const [override]
template<class T > bool llvm::final< T >::canRealignStack (const MachineFunction & MF) const
template<class T > unsigned char llvm::final< T >::ClassifyBlockAddressReference () const
Classify a blockaddress reference for the current subtarget according to how we should reference it in a non-pcrel context.
template<class T > unsigned char llvm::final< T >::ClassifyGlobalReference (const GlobalValue * GV, const TargetMachine & TM) const
ClassifyGlobalReference - Classify a global variable reference for the current subtarget according to how we should reference it in a non-pcrel context.
template<class T > bool llvm::final< T >::classifyLEAReg (MachineInstr * MI, const MachineOperand & Src, unsigned LEAOpcode, bool AllowSP, unsigned & NewSrc, bool & isKill, bool & isUndef, MachineOperand & ImplicitOp) const
Given an operand within a MachineInstr, insert preceding code to put it into the right format for a particular kind of LEA instruction.
This may involve using an appropriate super-register instead (with an implicit use of the original) or creating a new virtual register and inserting COPY instructions to get the data into the right class.
Reference parameters are set to indicate how caller should add this operand to the LEA instruction.
template<class T > MachineInstr* llvm::final< T >::commuteInstruction (MachineInstr * MI, bool NewMI) const [override]
commuteInstruction - We have a few instructions that must be hacked on to commute them.
template<class T > void llvm::final< T >::computeKnownBitsForTargetNode (const SDValue Op, APInt & KnownZero, APInt & KnownOne, const SelectionDAG & DAG, unsigned Depth = 0) const [override, virtual]
Determine which of the bits specified in Mask are known to be either zero or one and return them in the KnownZero/KnownOne bitsets.
Reimplemented from llvm::TargetLowering.
template<class T > unsigned llvm::final< T >::ComputeNumSignBitsForTargetNode (SDValue Op, const SelectionDAG & DAG, unsigned Depth) const [override, virtual]
Determine the number of bits in the operation that are sign bits.
Reimplemented from llvm::TargetLowering.
template<class T > llvm::final< T >::ContextualFoldingSet (Ctx Context, unsigned Log2InitSize = 6) [inline, explicit]
Definition at line 495 of file FoldingSet.h.
template<class T > MachineInstr* llvm::final< T >::convertToThreeAddress (MachineFunction::iterator & MFI, MachineBasicBlock::iterator & MBBI, LiveVariables * LV) const [override]
convertToThreeAddress - This method must be implemented by targets that set the M_CONVERTIBLE_TO_3_ADDR flag.
When this flag is set, the target may be able to convert a two-address instruction into a true three-address instruction on demand. This allows the X86 target (for example) to convert ADD and SHL instructions into LEA instructions if they would require register copies due to two-addressness.
This method returns a null pointer if the transformation cannot be performed, otherwise it returns the new instruction.
template<class T > void llvm::final< T >::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc) const [override]
template<class T > FastISel* llvm::final< T >::createFastISel (FunctionLoweringInfo & funcInfo, const TargetLibraryInfo * libInfo) const [override, virtual]
This method returns a target specific FastISel object, or null if the target does not support "fast" ISel.
Reimplemented from llvm::TargetLowering.
template<class T > TargetPassConfig* llvm::final< T >::createPassConfig (PassManagerBase & PM) [override, virtual]
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
createPassConfig - Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
Targets may override this to extend TargetPassConfig.
Reimplemented from llvm::LLVMTargetMachine.
template<class T > llvm::final< T >::DWARFUnitSection () [inline]
Definition at line 67 of file DWARFUnit.h.
template<class T > llvm::final< T >::DWARFUnitSection (DWARFUnitSection && DUS) [inline]
Definition at line 68 of file DWARFUnit.h.
template<class T > void llvm::final< T >::eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const [override]
template<class T > MachineBasicBlock* llvm::final< T >::EmitInstrWithCustomInserter (MachineInstr * MI, MachineBasicBlock * MBB) const [override, virtual]
This method should be implemented by targets that mark instructions with the 'usesCustomInserter' flag.
These instructions are special in various ways, which require special support to insert. The specified MachineInstr is created but not inserted into any basic blocks, and this method is called to expand it into a sequence of instructions, potentially also creating new basic blocks and control flow. As long as the returned basic block is different (i.e., we created a new one), the custom inserter is free to modify the rest of MBB.
Reimplemented from llvm::TargetLowering.
template<class T > bool llvm::final< T >::enableAggressiveInterleaving (bool LoopHasReductions) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 704 of file TargetTransformInfo.h.
template<class T > bool llvm::final< T >::enableEarlyIfConversion () const [override]
template<class T > bool llvm::final< T >::enableMachineScheduler () const [inline, override]
Enable the MachineScheduler pass for all X86 subtargets.
Definition at line 479 of file X86Subtarget.h.
template<class T > iterator llvm::final< T >::end () [inline]
Reimplemented from llvm::SmallVectorTemplateCommon< std::unique_ptr< UnitType > >.
Definition at line 425 of file FoldingSet.h.
template<class T > const_iterator llvm::final< T >::end () const [inline]
Reimplemented from llvm::SmallVectorTemplateCommon< std::unique_ptr< UnitType > >.
Definition at line 429 of file FoldingSet.h.
template<class T > iterator llvm::final< T >::end () [inline]
Reimplemented from llvm::SmallVectorTemplateCommon< std::unique_ptr< UnitType > >.
Definition at line 504 of file FoldingSet.h.
template<class T > const_iterator llvm::final< T >::end () const [inline]
Reimplemented from llvm::SmallVectorTemplateCommon< std::unique_ptr< UnitType > >.
Definition at line 508 of file FoldingSet.h.
template<class T > bool llvm::final< T >::ExpandInlineAsm (CallInst *) const [override, virtual]
This hook allows the target to expand an inline asm call to be explicit llvm code if it wants to.
This is useful for turning simple inline asms into LLVM intrinsics, which gives the compiler more information about the behavior of the code.
Reimplemented from llvm::TargetLowering.
template<class T > bool llvm::final< T >::expandPostRAPseudo (MachineBasicBlock::iterator MI) const [override]
template<class T > bool llvm::final< T >::findCommutedOpIndices (MachineInstr * MI, unsigned & SrcOpIdx1, unsigned & SrcOpIdx2) const [override]
template<class T > T* llvm::final< T >::FindNodeOrInsertPos (const FoldingSetNodeID & ID, void *& InsertPos) [inline]
FindNodeOrInsertPos - Look up the node specified by ID.
If it exists, return it. If not, return the insertion token that will make insertion faster.
Reimplemented from llvm::FoldingSetImpl.
Definition at line 451 of file FoldingSet.h.
References llvm::FoldingSetImpl::FindNodeOrInsertPos().
template<class T > T* llvm::final< T >::FindNodeOrInsertPos (const FoldingSetNodeID & ID, void *& InsertPos) [inline]
FindNodeOrInsertPos - Look up the node specified by ID.
If it exists, return it. If not, return the insertion token that will make insertion faster.
Reimplemented from llvm::FoldingSetImpl.
Definition at line 530 of file FoldingSet.h.
References llvm::FoldingSetImpl::FindNodeOrInsertPos().
template<class T > std::pair<const TargetRegisterClass *, uint8_t> llvm::final< T >::findRepresentativeClass (const TargetRegisterInfo * TRI, MVT VT) const [override, protected, virtual]
Return the largest legal super-reg register class of the register class for the specified type and its associated "cost".
findRepresentativeClass - Return the largest legal super-reg register class of the register class for the specified type and its associated "cost".
Reimplemented from llvm::TargetLoweringBase.
template<class T > llvm::final< T >::FoldingSet (unsigned Log2InitSize = 6) [inline, explicit]
Definition at line 419 of file FoldingSet.h.
template<class T > MachineInstr* llvm::final< T >::foldMemoryOperandImpl (MachineFunction & MF, MachineInstr * MI, ArrayRef< unsigned > Ops, MachineBasicBlock::iterator InsertPt, int FrameIndex) const [override]
foldMemoryOperand - If this target supports it, fold a load or store of the specified stack slot into the specified machine instruction for the specified operand(s).
If this is possible, the target should perform the folding and return true, otherwise it should return false. If it folds the instruction, it is likely that the MachineInstruction the iterator references has been changed.
template<class T > MachineInstr* llvm::final< T >::foldMemoryOperandImpl (MachineFunction & MF, MachineInstr * MI, ArrayRef< unsigned > Ops, MachineBasicBlock::iterator InsertPt, MachineInstr * LoadMI) const [override]
foldMemoryOperand - Same as the previous version except it allows folding of any load and store from / to any address, not just from a specific stack slot.
template<class T > MachineInstr* llvm::final< T >::foldMemoryOperandImpl (MachineFunction & MF, MachineInstr * MI, unsigned OpNum, ArrayRef< MachineOperand > MOs, MachineBasicBlock::iterator InsertPt, unsigned Size, unsigned Alignment, bool AllowCommute) const
template<class T > llvm::final< T >::format_object (const char * fmt, const Ts &... vals) [inline]
Definition at line 93 of file Format.h.
template<class T > void llvm::final< T >::genAlternativeCodeSequence (MachineInstr & Root, MachineCombinerPattern::MC_PATTERN P, SmallVectorImpl< MachineInstr * > & InsInstrs, SmallVectorImpl< MachineInstr * > & DelInstrs, DenseMap< unsigned, unsigned > & InstrIdxForVirtReg) const [override]
When getMachineCombinerPatterns() finds a pattern, this function generates the instructions that could replace the original code sequence.
template<class T > unsigned llvm::final< T >::getAddressComputationCost (Type * Ty, bool IsComplex) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 793 of file TargetTransformInfo.h.
template<class T > AntiDepBreakMode llvm::final< T >::getAntiDepBreakMode () const [inline, override]
Definition at line 488 of file X86Subtarget.h.
References llvm::TargetSubtargetInfo::ANTIDEP_CRITICAL.
template<class T > unsigned llvm::final< T >::getArithmeticInstrCost (unsigned Opcode, Type * Ty, OperandValueKind Opd1Info, OperandValueKind Opd2Info, OperandValueProperties Opd1PropInfo, OperandValueProperties Opd2PropInfo) [inline, override]
Definition at line 737 of file TargetTransformInfo.h.
template<class T > unsigned llvm::final< T >::getBaseRegister () const [inline]
Definition at line 126 of file X86RegisterInfo.h.
template<class T > unsigned llvm::final< T >::getByValTypeAlignment (Type * Ty) const [override, virtual]
Return the desired alignment for ByVal aggregate function arguments in the caller parameter area.
For X86, aggregates that contains are placed at 16-byte boundaries while the rest are at 4-byte boundaries.
Reimplemented from llvm::TargetLoweringBase.
template<class T > const char* llvm::final< T >::getBZeroEntry () const
This function returns the name of a function which has an interface like the non-standard bzero function, if such a function exists on the current subtarget and it is considered prefereable over memset with zero passed as the second argument.
Otherwise it returns null.
template<class T > unsigned llvm::final< T >::getCallCost (FunctionType * FTy, int NumArgs) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 639 of file TargetTransformInfo.h.
template<class T > unsigned llvm::final< T >::getCallCost (const Function * F, int NumArgs) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 642 of file TargetTransformInfo.h.
template<class T > unsigned llvm::final< T >::getCallCost (const Function * F, ArrayRef< const Value * > Arguments) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 645 of file TargetTransformInfo.h.
template<class T > const MCPhysReg* llvm::final< T >::getCalleeSavedRegs (const MachineFunction * MF) const [override]
getCalleeSavedRegs - Return a null-terminated list of all of the callee-save registers on this target.
template<class T > unsigned llvm::final< T >::getCallInstrCost (Function * F, Type * RetTy, ArrayRef< Type * > Tys) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 786 of file TargetTransformInfo.h.
template<class T > const uint32_t* llvm::final< T >::getCallPreservedMask (const MachineFunction & MF, CallingConv::ID) const [override]
template<class T > unsigned llvm::final< T >::getCastInstrCost (unsigned Opcode, Type * Dst, Type * Src) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 748 of file TargetTransformInfo.h.
template<class T > unsigned llvm::final< T >::getCFInstrCost (unsigned Opcode) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 751 of file TargetTransformInfo.h.
template<class T > const char* llvm::final< T >::getClearCacheBuiltinName () const [inline, override, virtual]
Intel processors have a unified instruction and data cache.
Reimplemented from llvm::TargetLowering.
Definition at line 871 of file X86ISelLowering.h.
template<class T > unsigned llvm::final< T >::getCmpSelInstrCost (unsigned Opcode, Type * ValTy, Type * CondTy) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 754 of file TargetTransformInfo.h.
template<class T > ConstraintType llvm::final< T >::getConstraintType (const std::string & Constraint) const [override, virtual]
Given a constraint, return the type of constraint it is for this target.
Reimplemented from llvm::TargetLowering.
template<class T > Ctx llvm::final< T >::getContext () const [inline]
Definition at line 499 of file FoldingSet.h.
template<class T > unsigned llvm::final< T >::getCostOfKeepingLiveOverCall (ArrayRef< Type * > Tys) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 796 of file TargetTransformInfo.h.
template<class T > const TargetRegisterClass* llvm::final< T >::getCrossCopyRegClass (const TargetRegisterClass * RC) const [override]
getCrossCopyRegClass - Returns a legal register class to copy a register in the specified class to or from.
Returns NULL if it is possible to copy between a two registers of the specified class.
template<class T > std::pair<uint16_t, uint16_t> llvm::final< T >::getExecutionDomain (const MachineInstr * MI) const [override]
template<class T > unsigned llvm::final< T >::getFPOpCost (Type * Ty) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 712 of file TargetTransformInfo.h.
template<class T > const X86FrameLowering* llvm::final< T >::getFrameLowering () const [inline, override]
Definition at line 263 of file X86Subtarget.h.
template<class T > unsigned llvm::final< T >::getFrameRegister (const MachineFunction & MF) const [override]
template<class T > unsigned llvm::final< T >::getGEPCost (const Value * Ptr, ArrayRef< const Value * > Operands) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 635 of file TargetTransformInfo.h.
template<class T > unsigned llvm::final< T >::getGlobalBaseReg (MachineFunction * MF) const
getGlobalBaseReg - Return a virtual register initialized with the the global base register value.
Output instructions required to initialize the register in the function entry block, if necessary.
template<class T > unsigned llvm::final< T >::getInlineAsmMemConstraint (const std::string & ConstraintCode) const [inline, override, virtual]
Reimplemented from llvm::TargetLowering.
Definition at line 729 of file X86ISelLowering.h.
References llvm::InlineAsm::Constraint_i, llvm::InlineAsm::Constraint_o, llvm::InlineAsm::Constraint_v, llvm::InlineAsm::Constraint_X, and llvm::TargetLowering::getInlineAsmMemConstraint().
template<class T > const X86InstrInfo* llvm::final< T >::getInstrInfo () const [inline, override]
Definition at line 262 of file X86Subtarget.h.
template<class T > const InstrItineraryData* llvm::final< T >::getInstrItineraryData () const [inline, override]
Return the instruction itineraries based on the subtarget selection.
Definition at line 484 of file X86Subtarget.h.
template<class T > unsigned llvm::final< T >::getInterleavedMemoryOpCost (unsigned Opcode, Type * VecTy, unsigned Factor, ArrayRef< unsigned > Indices, unsigned Alignment, unsigned AddressSpace) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 770 of file TargetTransformInfo.h.
template<class T > unsigned llvm::final< T >::getIntImmCost (const APInt & Imm, Type * Ty) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 716 of file TargetTransformInfo.h.
template<class T > unsigned llvm::final< T >::getIntImmCost (unsigned Opc, unsigned Idx, const APInt & Imm, Type * Ty) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 719 of file TargetTransformInfo.h.
template<class T > unsigned llvm::final< T >::getIntImmCost (Intrinsic::ID IID, unsigned Idx, const APInt & Imm, Type * Ty) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 723 of file TargetTransformInfo.h.
template<class T > unsigned llvm::final< T >::getIntrinsicCost (Intrinsic::ID IID, Type * RetTy, ArrayRef< Type * > ParamTys) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 649 of file TargetTransformInfo.h.
template<class T > unsigned llvm::final< T >::getIntrinsicCost (Intrinsic::ID IID, Type * RetTy, ArrayRef< const Value * > Arguments) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 653 of file TargetTransformInfo.h.
template<class T > unsigned llvm::final< T >::getIntrinsicInstrCost (Intrinsic::ID ID, Type * RetTy, ArrayRef< Type * > Tys) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 782 of file TargetTransformInfo.h.
template<class T > unsigned llvm::final< T >::getJumpBufAlignment () [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 699 of file TargetTransformInfo.h.
template<class T > unsigned llvm::final< T >::getJumpBufSize () [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 700 of file TargetTransformInfo.h.
template<class T > unsigned llvm::final< T >::getJumpInstrTableEntryBound () const [override]
template<class T > unsigned llvm::final< T >::getJumpTableEncoding () const [override, virtual]
Return the entry encoding for a jump table in the current function.
getJumpTableEncoding - Return the entry encoding for a jump table in the current function.
The returned value is a member of the MachineJumpTableInfo::JTEntryKind enum.
Reimplemented from llvm::TargetLowering.
template<class T > const TargetRegisterClass* llvm::final< T >::getLargestLegalSuperClass (const TargetRegisterClass * RC, const MachineFunction & MF) const [override]
template<class T > bool llvm::final< T >::getMachineCombinerPatterns (MachineInstr & Root, SmallVectorImpl< MachineCombinerPattern::MC_PATTERN > & P) const [override]
Return true when there is potentially a faster code sequence for an instruction chain ending in <Root>.
All potential patterns are output in the <Pattern> array.
template<class T > unsigned llvm::final< T >::getMaskedMemoryOpCost (unsigned Opcode, Type * Src, unsigned Alignment, unsigned AddressSpace) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 766 of file TargetTransformInfo.h.
template<class T > const TargetRegisterClass* llvm::final< T >::getMatchingSuperRegClass (const TargetRegisterClass * A, const TargetRegisterClass * B, unsigned Idx) const [override]
getMatchingSuperRegClass - Return a subclass of the specified register class A so that each register in it has a sub-register of the specified sub-register index which is in the specified register class B.
template<class T > unsigned llvm::final< T >::getMaxInlineSizeThreshold () const [inline]
Returns the maximum memset / memcpy size that still makes it profitable to inline the call.
Definition at line 280 of file X86Subtarget.h.
template<class T > unsigned llvm::final< T >::getMaxInterleaveFactor (unsigned VF) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 733 of file TargetTransformInfo.h.
template<class T > bool llvm::final< T >::getMemOpBaseRegImmOfs (MachineInstr * LdSt, unsigned & BaseReg, unsigned & Offset, const TargetRegisterInfo * TRI) const [override]
template<class T > unsigned llvm::final< T >::getMemoryOpCost (unsigned Opcode, Type * Src, unsigned Alignment, unsigned AddressSpace) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 762 of file TargetTransformInfo.h.
template<class T > void llvm::final< T >::getNoopForMachoTarget (MCInst & NopInst) const [override]
template<class T > const uint32_t* llvm::final< T >::getNoPreservedMask () const
template<class T > unsigned llvm::final< T >::getNumberOfParts (Type * Tp) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 790 of file TargetTransformInfo.h.
template<class T > unsigned llvm::final< T >::getNumberOfRegisters (bool Vector) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 727 of file TargetTransformInfo.h.
template<class T > TargetLoweringObjectFile* llvm::final< T >::getObjFileLowering () const [inline, override, virtual]
Reimplemented from llvm::TargetMachine.
Definition at line 42 of file X86TargetMachine.h.
template<class T > unsigned llvm::final< T >::getOpcodeAfterMemoryUnfold (unsigned Opc, bool UnfoldLoad, bool UnfoldStore, unsigned * LoadRegIndex = nullptr) const [override]
getOpcodeAfterMemoryUnfold - Returns the opcode of the would be new instruction after load / store are unfolded from an instruction of the specified opcode.
It returns zero if the specified unfolding is not possible. If LoadRegIndex is non-null, it is filled in with the operand index of the operand which will hold the register holding the loaded value.
template<class T > unsigned llvm::final< T >::getOperationCost (unsigned Opcode, Type * Ty, Type * OpTy) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 632 of file TargetTransformInfo.h.
template<class T > EVT llvm::final< T >::getOptimalMemOpType (uint64_t Size, unsigned DstAlign, unsigned SrcAlign, bool IsMemset, bool ZeroMemset, bool MemcpyStrSrc, MachineFunction & MF) const [override, virtual]
Returns the target specific optimal type for load and store operations as a result of memset, memcpy, and memmove lowering.
If DstAlign is zero that means it's safe to destination alignment can satisfy any constraint. Similarly if SrcAlign is zero it means there isn't a need to check it against alignment requirement, probably because the source does not need to be loaded. If 'IsMemset' is true, that means it's expanding a memset. If 'ZeroMemset' is true, that means it's a memset of zero. 'MemcpyStrSrc' indicates whether the memcpy source is constant so it does not need to be loaded. It returns EVT::Other if the type should be determined using generic target-independent logic.
Reimplemented from llvm::TargetLoweringBase.
template<class T > Value* llvm::final< T >::getOrCreateResultFromMemIntrinsic (IntrinsicInst * Inst, Type * ExpectedType) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 803 of file TargetTransformInfo.h.
template<class T > T* llvm::final< T >::GetOrInsertNode (Node * N) [inline]
GetOrInsertNode - If there is an existing simple Node exactly equal to the specified node, return it.
Otherwise, insert 'N' and return it instead.
Reimplemented from llvm::FoldingSetImpl.
Definition at line 444 of file FoldingSet.h.
References llvm::FoldingSetImpl::GetOrInsertNode().
template<class T > T* llvm::final< T >::GetOrInsertNode (Node * N) [inline]
GetOrInsertNode - If there is an existing simple Node exactly equal to the specified node, return it.
Otherwise, insert 'N' and return it instead.
Reimplemented from llvm::FoldingSetImpl.
Definition at line 523 of file FoldingSet.h.
References llvm::FoldingSetImpl::GetOrInsertNode().
template<class T > unsigned llvm::final< T >::getPartialRegUpdateClearance (const MachineInstr * MI, unsigned OpNum, const TargetRegisterInfo * TRI) const [override]
template<class T > SDValue llvm::final< T >::getPICJumpTableRelocBase (SDValue Table, SelectionDAG & DAG) const [override, virtual]
Returns relocation base for the given PIC jumptable.
Reimplemented from llvm::TargetLowering.
template<class T > const MCExpr* llvm::final< T >::getPICJumpTableRelocBaseExpr (const MachineFunction * MF, unsigned JTI, MCContext & Ctx) const [override, virtual]
This returns the relocation base for the given PIC jumptable, the same as getPICJumpTableRelocBase, but as an MCExpr.
getPICJumpTableRelocBaseExpr - This returns the relocation base for the given PIC jumptable, the same as getPICJumpTableRelocBase, but as an MCExpr.
Reimplemented from llvm::TargetLowering.
template<class T > PICStyles::Style llvm::final< T >::getPICStyle () const [inline]
Definition at line 318 of file X86Subtarget.h.
template<class T > const TargetRegisterClass* llvm::final< T >::getPointerRegClass (const MachineFunction & MF, unsigned Kind = 0) const [override]
getPointerRegClass - Returns a TargetRegisterClass used for pointer values.
template<class T > PopcntSupportKind llvm::final< T >::getPopcntSupport (unsigned IntTyWidthInBit) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 707 of file TargetTransformInfo.h.
template<class T > LegalizeTypeAction llvm::final< T >::getPreferredVectorAction (EVT VT) const [override, virtual]
Customize the preferred legalization strategy for certain types.
Reimplemented from llvm::TargetLoweringBase.
template<class T > unsigned llvm::final< T >::getPtrSizedFrameRegister (const MachineFunction & MF) const
template<class T > unsigned llvm::final< T >::getReductionCost (unsigned Opcode, Type * Ty, bool IsPairwiseForm) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 778 of file TargetTransformInfo.h.
template<class T > std::pair<unsigned, const TargetRegisterClass *> llvm::final< T >::getRegForInlineAsmConstraint (const TargetRegisterInfo * TRI, const std::string & Constraint, MVT VT) const [override, virtual]
Given a physical register constraint (e.g.
{edx}), return the register number and the register class for the register. This should only be used for C_Register constraints. On error, this returns a register number of 0.
Reimplemented from llvm::TargetLowering.
template<class T > unsigned llvm::final< T >::getRegisterBitWidth (bool Vector) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 730 of file TargetTransformInfo.h.
template<class T > unsigned llvm::final< T >::getRegisterByName (const char * RegName, EVT VT) const [override, virtual]
Return the register ID of the name passed in.
Used by named register global variables extension. There is no target-independent behaviour so the default action is to bail.
Reimplemented from llvm::TargetLowering.
template<class T > const X86RegisterInfo& llvm::final< T >::getRegisterInfo () const [inline]
getRegisterInfo - TargetInstrInfo is a superset of MRegister info.
As such, whenever a client has an instance of instruction info, it should always be able to get register info as well (through this method).
Definition at line 195 of file X86InstrInfo.h.
template<class T > const X86RegisterInfo* llvm::final< T >::getRegisterInfo () const [inline, override]
Definition at line 269 of file X86Subtarget.h.
template<class T > static const char* llvm::final< T >::getRegisterName (unsigned RegNo) [static]
template<class T > static const char* llvm::final< T >::getRegisterName (unsigned RegNo) [static]
template<class T > unsigned llvm::final< T >::getRegPressureLimit (const TargetRegisterClass * RC, MachineFunction & MF) const [override]
template<class T > BitVector llvm::final< T >::getReservedRegs (const MachineFunction & MF) const [override]
getReservedRegs - Returns a bitset indexed by physical register number indicating if a register is a special register that has particular uses and should be considered unavailable at all times, e.g.
SP, RA. This is used by register scavenger to determine what registers are free.
template<class T > SDValue llvm::final< T >::getReturnAddressFrameIndex (SelectionDAG & DAG) const
template<class T > MVT llvm::final< T >::getScalarShiftAmountTy (EVT LHSTy) const [inline, override, virtual]
Reimplemented from llvm::TargetLoweringBase.
Definition at line 601 of file X86ISelLowering.h.
References llvm::MVT::i8.
template<class T > int llvm::final< T >::getScalingFactorCost (Type * Ty, GlobalValue * BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 686 of file TargetTransformInfo.h.
template<class T > int llvm::final< T >::getScalingFactorCost (const AddrMode & AM, Type * Ty, unsigned AS) const [override, virtual]
Return the cost of the scaling factor used in the addressing mode represented by AM for this target, for a load/store of the specified type.
If the AM is supported, the return value must be >= 0. If the AM is not supported, it returns a negative value.
Reimplemented from llvm::TargetLoweringBase.
template<class T > int llvm::final< T >::getSEHRegNum (unsigned i) const
template<class T > const X86SelectionDAGInfo* llvm::final< T >::getSelectionDAGInfo () const [inline, override]
Definition at line 266 of file X86Subtarget.h.
template<class T > EVT llvm::final< T >::getSetCCResultType (LLVMContext & Context, EVT VT) const [override, virtual]
Return the value type to use for ISD::SETCC.
Reimplemented from llvm::TargetLoweringBase.
template<class T > unsigned llvm::final< T >::getShuffleCost (ShuffleKind Kind, Type * Tp, int Index, Type * SubTp) [inline, override]
Definition at line 744 of file TargetTransformInfo.h.
template<class T > ConstraintWeight llvm::final< T >::getSingleConstraintMatchWeight (AsmOperandInfo & info, const char * constraint) const [override, virtual]
Examine constraint string and operand type and determine a weight value.
The operand object must already have been set up with the operand type.
Reimplemented from llvm::TargetLowering.
template<class T > unsigned llvm::final< T >::getSlotSize () const [inline]
Definition at line 128 of file X86RegisterInfo.h.
template<class T > int llvm::final< T >::getSPAdjust (const MachineInstr * MI) const [override]
getSPAdjust - This returns the stack pointer adjustment made by this instruction.
For x86, we need to handle more complex call sequences involving PUSHes.
template<class T > unsigned llvm::final< T >::getStackAlignment () const [inline]
Returns the minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function for this subtarget.
Definition at line 276 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::getStackCookieLocation (unsigned & AddressSpace, unsigned & Offset) const [override, virtual]
Return true if the target stores stack protector cookies at a fixed offset in some non-standard address space, and populates the address space and offset as appropriate.
Reimplemented from llvm::TargetLoweringBase.
template<class T > unsigned llvm::final< T >::getStackRegister () const [inline]
Definition at line 125 of file X86RegisterInfo.h.
template<class T > const TargetRegisterClass* llvm::final< T >::getSubClassWithSubReg (const TargetRegisterClass * RC, unsigned Idx) const [override]
template<class T > const X86Subtarget* llvm::final< T >::getSubtargetImpl (const Function &) const [override, virtual]
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
Reimplemented from llvm::TargetMachine.
template<class T > TargetIRAnalysis llvm::final< T >::getTargetIRAnalysis () [override, virtual]
Get a TargetIRAnalysis implementation for the target.
This analysis will produce a TTI result which uses the common code generator to answer queries about the IR.
Reimplemented from llvm::LLVMTargetMachine.
template<class T > const X86TargetLowering* llvm::final< T >::getTargetLowering () const [inline, override]
Definition at line 259 of file X86Subtarget.h.
template<class T > const char* llvm::final< T >::getTargetNodeName (unsigned Opcode) const [override, virtual]
This method returns the name of a target specific DAG node.
Reimplemented from llvm::TargetLowering.
template<class T > const Triple& llvm::final< T >::getTargetTriple () const [inline]
Reimplemented from llvm::TargetMachine.
Definition at line 384 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::getTgtMemIntrinsic (IntrinsicInst * Inst, MemIntrinsicInfo & Info) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 799 of file TargetTransformInfo.h.
template<class T > void llvm::final< T >::getTrap (MCInst & MI) const [override]
template<class T > void llvm::final< T >::getUnconditionalBranch (MCInst & Branch, const MCSymbolRefExpr * BranchTarget) const [override]
template<class T > unsigned llvm::final< T >::getUndefRegClearance (const MachineInstr * MI, unsigned & OpNum, const TargetRegisterInfo * TRI) const [override]
template<class T > UnitType* llvm::final< T >::getUnitForOffset (uint32_t Offset) const [inline, override, virtual]
Returns the Unit that contains the given section offset in the same section this Unit originated from.
Implements llvm::DWARFUnitSectionBase.
Definition at line 75 of file DWARFUnit.h.
References llvm::sys::path::begin(), and llvm::sys::path::end().
template<class T > void llvm::final< T >::getUnrollingPreferences (Loop * L, UnrollingPreferences & UP) [inline, override]
Definition at line 665 of file TargetTransformInfo.h.
template<class T > unsigned llvm::final< T >::getUserCost (const User * U) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 657 of file TargetTransformInfo.h.
template<class T > unsigned llvm::final< T >::getVectorInstrCost (unsigned Opcode, Type * Val, unsigned Index) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 758 of file TargetTransformInfo.h.
template<class T > bool llvm::final< T >::has3DNow () const [inline]
Definition at line 335 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::has3DNowA () const [inline]
Definition at line 336 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasADX () const [inline]
Definition at line 354 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasAES () const [inline]
Definition at line 338 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasAVX () const [inline]
Definition at line 329 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasAVX2 () const [inline]
Definition at line 330 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasAVX512 () const [inline]
Definition at line 331 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasBasePointer (const MachineFunction & MF) const
template<class T > bool llvm::final< T >::hasBMI () const [inline]
Definition at line 350 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasBMI2 () const [inline]
Definition at line 351 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasBranchDivergence () [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 658 of file TargetTransformInfo.h.
template<class T > bool llvm::final< T >::hasBWI () const [inline]
Definition at line 376 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasCDI () const [inline]
Definition at line 372 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasCMov () const [inline]
Definition at line 321 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasCmpxchg16b () const [inline]
Definition at line 363 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasDQI () const [inline]
Definition at line 375 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasERI () const [inline]
Definition at line 374 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasF16C () const [inline]
Definition at line 347 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasFMA () const [inline]
Definition at line 340 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasFMA4 () const [inline]
Definition at line 342 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasFp256 () const [inline]
Definition at line 332 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasFSGSBase () const [inline]
Definition at line 348 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasHighOperandLatency (const TargetSchedModel & SchedModel, const MachineRegisterInfo * MRI, const MachineInstr * DefMI, unsigned DefIdx, const MachineInstr * UseMI, unsigned UseIdx) const [override]
template<class T > bool llvm::final< T >::hasHLE () const [inline]
Definition at line 353 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasInt256 () const [inline]
Definition at line 333 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasLZCNT () const [inline]
Definition at line 349 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasMMX () const [inline]
Definition at line 322 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasMOVBE () const [inline]
Definition at line 345 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasMPX () const [inline]
Definition at line 378 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasPCLMUL () const [inline]
Definition at line 339 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasPFI () const [inline]
Definition at line 373 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasPOPCNT () const [inline]
Definition at line 337 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasPRFCHW () const [inline]
Definition at line 356 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasRDRAND () const [inline]
Definition at line 346 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasRDSEED () const [inline]
Definition at line 357 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasReservedSpillSlot (const MachineFunction & MF, unsigned Reg, int & FrameIdx) const [override]
template<class T > bool llvm::final< T >::hasRTM () const [inline]
Definition at line 352 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasSHA () const [inline]
Definition at line 355 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasSinCos () const
This function returns true if the target has sincos() routine in its compiler runtime or math libraries.
template<class T > bool llvm::final< T >::hasSlowDivide32 () const [inline]
Definition at line 365 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasSlowDivide64 () const [inline]
Definition at line 366 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasSSE1 () const [inline]
Definition at line 323 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasSSE2 () const [inline]
Definition at line 324 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasSSE3 () const [inline]
Definition at line 325 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasSSE41 () const [inline]
Definition at line 327 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasSSE42 () const [inline]
Definition at line 328 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasSSE4A () const [inline]
Definition at line 334 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasSSEUnalignedMem () const [inline]
Definition at line 362 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasSSSE3 () const [inline]
Definition at line 326 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasTBM () const [inline]
Definition at line 344 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasVLX () const [inline]
Definition at line 377 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::hasXOP () const [inline]
Definition at line 343 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::haveFastSqrt (Type * Ty) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 710 of file TargetTransformInfo.h.
template<class T > unsigned llvm::final< T >::InsertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, ArrayRef< MachineOperand > Cond, DebugLoc DL) const [override]
template<class T > void llvm::final< T >::insertSelect (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, DebugLoc DL, unsigned DstReg, ArrayRef< MachineOperand > Cond, unsigned TrueReg, unsigned FalseReg) const [override]
template<class T > bool llvm::final< T >::is16Bit () const [inline]
Definition at line 302 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::is32Bit () const [inline]
Definition at line 298 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::is64Bit () const [inline]
Is this x86_64? (disregarding specific ABI / programming model)
Definition at line 294 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::isAtom () const [inline]
Definition at line 380 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::isBTMemSlow () const [inline]
Definition at line 358 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::isCallingConvWin64 (CallingConv::ID CC) const [inline]
Definition at line 449 of file X86Subtarget.h.
References llvm::CallingConv::X86_64_SysV, and llvm::CallingConv::X86_64_Win64.
template<class T > bool llvm::final< T >::isCheapToSpeculateCtlz () const [override, virtual]
Return true if it is cheap to speculate a call to intrinsic ctlz.
Reimplemented from llvm::TargetLoweringBase.
template<class T > bool llvm::final< T >::isCheapToSpeculateCttz () const [override, virtual]
Return true if it is cheap to speculate a call to intrinsic cttz.
Reimplemented from llvm::TargetLoweringBase.
template<class T > bool llvm::final< T >::isCoalescableExtInstr (const MachineInstr & MI, unsigned & SrcReg, unsigned & DstReg, unsigned & SubIdx) const [override]
isCoalescableExtInstr - Return true if the instruction is a "coalescable" extension instruction.
That is, it's like a copy where it's legal for the source to overlap the destination. e.g. X86::MOVSX64rr32. If this returns true, then it's expected the pre-extension value is available as a subreg of the result register. This also returns the sub-register index in SubIdx.
template<class T > bool llvm::final< T >::IsDesirableToPromoteOp (SDValue Op, EVT & PVT) const [override, virtual]
Return true if the target has native support for the specified value type and it is 'desirable' to use the type.
e.g. On x86 i16 is legal, but undesirable since i16 instruction encodings are longer and some i16 instructions are slow.
Reimplemented from llvm::TargetLowering.
template<class T > bool llvm::final< T >::isExtractSubvectorCheap (EVT ResVT, unsigned Index) const [override, virtual]
Return true if EXTRACT_SUBVECTOR is cheap for this result type with this index.
Reimplemented from llvm::TargetLoweringBase.
template<class T > bool llvm::final< T >::isFMAFasterThanFMulAndFAdd (EVT VT) const [override, virtual]
Return true if an FMA operation is faster than a pair of fmul and fadd instructions.
fmuladd intrinsics will be expanded to FMAs when this method returns true, otherwise fmuladd is expanded to fmul + fadd.
Reimplemented from llvm::TargetLoweringBase.
template<class T > bool llvm::final< T >::isFPImmLegal (const APFloat & Imm, EVT VT) const [override, virtual]
Returns true if the target can instruction select the specified FP immediate natively.
If false, the legalizer will materialize the FP immediate as a load from a constant pool.
Reimplemented from llvm::TargetLoweringBase.
template<class T > bool llvm::final< T >::isGAPlusOffset (SDNode * N, const GlobalValue *& GA, int64_t & Offset) const [override, virtual]
Returns true (and the GlobalValue and the offset) if the node is a GlobalAddress + offset.
isGAPlusOffset - Returns true (and the GlobalValue and the offset) if the node is a GlobalAddress + offset.
Reimplemented from llvm::TargetLowering.
template<class T > bool llvm::final< T >::isHighLatencyDef (int opc) const [override]
template<class T > bool llvm::final< T >::isIntegerTypeFTOL (EVT VT) const [inline]
Return true if the MSVC _ftol2 routine should be used for fptoui to the given type.
Definition at line 857 of file X86ISelLowering.h.
References llvm::MVT::i64.
template<class T > bool llvm::final< T >::isLegalAddImmediate (int64_t Imm) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 668 of file TargetTransformInfo.h.
template<class T > bool llvm::final< T >::isLegalAddImmediate (int64_t Imm) const [override, virtual]
Return true if the specified immediate is legal add immediate, that is the target has add instructions which can add a register and the immediate without having to materialize the immediate into a register.
Reimplemented from llvm::TargetLoweringBase.
template<class T > bool llvm::final< T >::isLegalAddressingMode (Type * Ty, GlobalValue * BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 674 of file TargetTransformInfo.h.
template<class T > bool llvm::final< T >::isLegalAddressingMode (const AddrMode & AM, Type * Ty, unsigned AS) const [override, virtual]
Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
Reimplemented from llvm::TargetLoweringBase.
template<class T > bool llvm::final< T >::isLegalICmpImmediate (int64_t Imm) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 671 of file TargetTransformInfo.h.
template<class T > bool llvm::final< T >::isLegalICmpImmediate (int64_t Imm) const [override, virtual]
Return true if the specified immediate is legal icmp immediate, that is the target has icmp instructions which can compare a register against the immediate without having to materialize the immediate into a register.
Reimplemented from llvm::TargetLoweringBase.
template<class T > bool llvm::final< T >::isLegalMaskedLoad (Type * DataType, int Consecutive) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 683 of file TargetTransformInfo.h.
template<class T > bool llvm::final< T >::isLegalMaskedStore (Type * DataType, int Consecutive) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 680 of file TargetTransformInfo.h.
template<class T > bool llvm::final< T >::IsLegalToCallImmediateAddr (const TargetMachine & TM) const
Return true if the subtarget allows calls to immediate address.
template<class T > unsigned llvm::final< T >::isLoadFromStackSlot (const MachineInstr * MI, int & FrameIndex) const [override]
template<class T > unsigned llvm::final< T >::isLoadFromStackSlotPostFE (const MachineInstr * MI, int & FrameIndex) const [override]
isLoadFromStackSlotPostFE - Check for post-frame ptr elimination stack locations as well.
This uses a heuristic so it isn't reliable for correctness.
template<class T > bool llvm::final< T >::isLoweredToCall (const Function * F) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 662 of file TargetTransformInfo.h.
template<class T > bool llvm::final< T >::isNarrowingProfitable (EVT VT1, EVT VT2) const [override, virtual]
Return true if it's profitable to narrow operations of type VT1 to VT2.
e.g. on x86, it's profitable to narrow from i32 to i8 but not from i32 to i16.
Reimplemented from llvm::TargetLoweringBase.
template<class T > bool llvm::final< T >::isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const [override, virtual]
Returns true if a cast between SrcAS and DestAS is a noop.
Reimplemented from llvm::TargetLoweringBase.
template<class T > bool llvm::final< T >::isOSWindows () const [inline]
Definition at line 423 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::isPICStyleGOT () const [inline]
Definition at line 434 of file X86Subtarget.h.
References llvm::ARMCP::GOT.
template<class T > bool llvm::final< T >::isPICStyleRIPRel () const [inline]
Definition at line 435 of file X86Subtarget.h.
References llvm::PICStyles::RIPRel.
template<class T > bool llvm::final< T >::isPICStyleSet () const [inline]
Definition at line 433 of file X86Subtarget.h.
References llvm::None.
template<class T > bool llvm::final< T >::isPICStyleStubAny () const [inline]
Definition at line 444 of file X86Subtarget.h.
References llvm::PICStyles::StubDynamicNoPIC, and llvm::PICStyles::StubPIC.
template<class T > bool llvm::final< T >::isPICStyleStubNoDynamic () const [inline]
Definition at line 441 of file X86Subtarget.h.
References llvm::PICStyles::StubDynamicNoPIC.
template<class T > bool llvm::final< T >::isPICStyleStubPIC () const [inline]
Definition at line 437 of file X86Subtarget.h.
References llvm::PICStyles::StubPIC.
template<class T > bool llvm::final< T >::isProfitableToHoist (Instruction * I) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 695 of file TargetTransformInfo.h.
template<class T > bool llvm::final< T >::isReallyTriviallyReMaterializable (const MachineInstr * MI, AliasAnalysis * AA) const [override]
template<class T > bool llvm::final< T >::isSafeMemOpType (MVT VT) const [override, virtual]
Returns true if it's safe to use load / store of the specified type to expand memcpy / memset inline.
This is mostly true for all types except for some special cases. For example, on X86 targets without SSE2 f64 load / store are done with fldl / fstpl which also does type conversion. Note the specified type doesn't have to be legal as the hook is used before type legalization.
Reimplemented from llvm::TargetLoweringBase.
template<class T > bool llvm::final< T >::isSafeToClobberEFLAGS (MachineBasicBlock & MBB, MachineBasicBlock::iterator I) const
isSafeToClobberEFLAGS - Return true if it's safe insert an instruction tha would clobber the EFLAGS condition register.
Note the result may be conservative. If it cannot definitely determine the safety after visiting a few instructions in each direction it assumes it's not safe.
template<class T > bool llvm::final< T >::isSafeToMoveRegClassDefs (const TargetRegisterClass * RC) const [override]
isSafeToMoveRegClassDefs - Return true if it's safe to move a machine instruction that defines the specified register class.
template<class T > bool llvm::final< T >::isScalarFPTypeInSSEReg (EVT VT) const [inline]
Return true if the specified scalar FP type is computed in an SSE register, not on the X87 floating point stack.
Definition at line 847 of file X86ISelLowering.h.
References llvm::MVT::f32, and llvm::MVT::f64.
template<class T > bool llvm::final< T >::isSHLDSlow () const [inline]
Definition at line 359 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::isShuffleMaskLegal (const SmallVectorImpl< int > & Mask, EVT VT) const [override, virtual]
Targets can use this to indicate that they only support *some* VECTOR_SHUFFLE operations, those with specific masks.
By default, if a target supports the VECTOR_SHUFFLE node, all mask values are assumed to be legal.
Reimplemented from llvm::TargetLoweringBase.
template<class T > bool llvm::final< T >::isSLM () const [inline]
Definition at line 381 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::isSourceOfDivergence (const Value * V) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 659 of file TargetTransformInfo.h.
template<class T > unsigned llvm::final< T >::isStoreToStackSlot (const MachineInstr * MI, int & FrameIndex) const [override]
template<class T > unsigned llvm::final< T >::isStoreToStackSlotPostFE (const MachineInstr * MI, int & FrameIndex) const [override]
isStoreToStackSlotPostFE - Check for post-frame ptr elimination stack locations as well.
This uses a heuristic so it isn't reliable for correctness.
template<class T > bool llvm::final< T >::isTarget64BitILP32 () const [inline]
Is this x86_64 with the ILP32 programming model (x32 ABI)?
Definition at line 307 of file X86Subtarget.h.
References llvm::Triple::GNUX32.
template<class T > bool llvm::final< T >::isTarget64BitLP64 () const [inline]
Is this x86_64 with the LP64 programming model (standard AMD64, no x32)?
Definition at line 313 of file X86Subtarget.h.
References llvm::Triple::GNUX32.
template<class T > bool llvm::final< T >::isTargetCOFF () const [inline]
Definition at line 393 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::isTargetCygMing () const [inline]
Definition at line 421 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::isTargetDarwin () const [inline]
Definition at line 386 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::isTargetDragonFly () const [inline]
Definition at line 388 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::isTargetELF () const [inline]
Definition at line 392 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::isTargetFreeBSD () const [inline]
Definition at line 387 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::isTargetFTOL () const
Return true if the target uses the MSVC _ftol2 routine for fptoui.
template<class T > bool llvm::final< T >::isTargetKnownWindowsMSVC () const [inline]
Definition at line 405 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::isTargetLinux () const [inline]
Definition at line 396 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::isTargetMachO () const [inline]
Definition at line 394 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::isTargetNaCl () const [inline]
Definition at line 397 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::isTargetNaCl32 () const [inline]
Definition at line 398 of file X86Subtarget.h.
References is64Bit().
template<class T > bool llvm::final< T >::isTargetNaCl64 () const [inline]
Definition at line 399 of file X86Subtarget.h.
References is64Bit().
template<class T > bool llvm::final< T >::isTargetPS4 () const [inline]
Definition at line 390 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::isTargetSolaris () const [inline]
Definition at line 389 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::isTargetWin32 () const [inline]
Definition at line 429 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::isTargetWin64 () const [inline]
Definition at line 425 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::isTargetWindowsCygwin () const [inline]
Definition at line 409 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::isTargetWindowsGNU () const [inline]
Definition at line 413 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::isTargetWindowsItanium () const [inline]
Definition at line 417 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::isTargetWindowsMSVC () const [inline]
Definition at line 401 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::isTruncateFree (Type * Ty1, Type * Ty2) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 692 of file TargetTransformInfo.h.
template<class T > bool llvm::final< T >::isTruncateFree (Type * Ty1, Type * Ty2) const [override, virtual]
Return true if it's free to truncate a value of type Ty1 to type Ty2.
e.g. On x86 it's free to truncate a i32 value in register EAX to i16 by referencing its sub-register AX.
Reimplemented from llvm::TargetLoweringBase.
template<class T > bool llvm::final< T >::isTruncateFree (EVT VT1, EVT VT2) const [override, virtual]
Reimplemented from llvm::TargetLoweringBase.
template<class T > bool llvm::final< T >::isTypeDesirableForOp (unsigned Opc, EVT VT) const [override, virtual]
Return true if the target has native support for the specified value type and it is 'desirable' to use the type for the given node type.
e.g. On x86 i16 is legal, but undesirable since i16 instruction encodings are longer and some i16 instructions are slow.
Reimplemented from llvm::TargetLowering.
template<class T > bool llvm::final< T >::isTypeLegal (Type * Ty) [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 698 of file TargetTransformInfo.h.
template<class T > bool llvm::final< T >::isUnalignedMem32Slow () const [inline]
Definition at line 361 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::isUnalignedMemAccessFast () const [inline]
Definition at line 360 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::isUnpredicatedTerminator (const MachineInstr * MI) const [override]
template<class T > bool llvm::final< T >::isVectorClearMaskLegal (const SmallVectorImpl< int > & Mask, EVT VT) const [override, virtual]
Similar to isShuffleMaskLegal.
This is used by Targets can use this to indicate if there is a suitable VECTOR_SHUFFLE that can be used to replace a VAND with a constant pool entry.
Reimplemented from llvm::TargetLoweringBase.
template<class T > bool llvm::final< T >::isVectorLoadExtDesirable (SDValue) const [override, virtual]
Return true if folding a vector load into ExtVal (a sign, zero, or any extend node) is profitable.
Reimplemented from llvm::TargetLoweringBase.
template<class T > bool llvm::final< T >::isVectorShiftByScalarCheap (Type * Ty) const [override, virtual]
Return true if it's significantly cheaper to shift a vector by a uniform scalar than by an amount which will vary across each lane.
On x86, for example, there is a "psllw" instruction for the former case, but no simple instruction for a general "a << b" operation on vectors.
Reimplemented from llvm::TargetLoweringBase.
template<class T > static bool llvm::final< T >::isX86_64ExtendedReg (const MachineOperand & MO) [inline, static]
Definition at line 409 of file X86InstrInfo.h.
References llvm::MachineOperand::getReg(), llvm::MachineOperand::isReg(), and llvm::X86II::isX86_64ExtendedReg().
template<class T > bool llvm::final< T >::isZExtFree (Type * Ty1, Type * Ty2) const [override, virtual]
Return true if any actual instruction that defines a value of type Ty1 implicit zero-extends the value to Ty2 in the result register.
This does not necessarily include registers defined in unknown ways, such as incoming arguments, or copies from unknown virtual registers. Also, if isTruncateFree(Ty2, Ty1) is true, this does not necessarily apply to truncate instructions. e.g. on x86-64, all instructions that define 32-bit values implicit zero-extend the result out to 64 bits.
Reimplemented from llvm::TargetLoweringBase.
template<class T > bool llvm::final< T >::isZExtFree (EVT VT1, EVT VT2) const [override, virtual]
Reimplemented from llvm::TargetLoweringBase.
template<class T > bool llvm::final< T >::isZExtFree (SDValue Val, EVT VT2) const [override, virtual]
Return true if zero-extending the specific node Val to type VT2 is free (either because it's implicitly zero-extended such as ARM ldrb / ldrh or because it's folded such as X86 zero-extending loads).
Reimplemented from llvm::TargetLoweringBase.
template<class T > bool llvm::final< T >::LEAusesAG () const [inline]
Definition at line 369 of file X86Subtarget.h.
template<class T > void llvm::final< T >::loadRegFromAddr (MachineFunction & MF, unsigned DestReg, SmallVectorImpl< MachineOperand > & Addr, const TargetRegisterClass * RC, MachineInstr::mmo_iterator MMOBegin, MachineInstr::mmo_iterator MMOEnd, SmallVectorImpl< MachineInstr * > & NewMIs) const
template<class T > void llvm::final< T >::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, unsigned DestReg, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const [override]
template<class T > void llvm::final< T >::LowerAsmOperandForConstraint (SDValue Op, std::string & Constraint, std::vector< SDValue > & Ops, SelectionDAG & DAG) const [override, virtual]
Lower the specified operand into the Ops vector.
If it is invalid, don't add anything to Ops. If hasMemory is true it means one of the asm constraint of the inline asm instruction being processed is 'm'.
Reimplemented from llvm::TargetLowering.
template<class T > const MCExpr* llvm::final< T >::LowerCustomJumpTableEntry (const MachineJumpTableInfo * MJTI, const MachineBasicBlock * MBB, unsigned uid, MCContext & Ctx) const [override, virtual]
Reimplemented from llvm::TargetLowering.
template<class T > SDValue llvm::final< T >::LowerOperation (SDValue Op, SelectionDAG & DAG) const [override, virtual]
Provide custom lowering hooks for some operations.
Reimplemented from llvm::TargetLowering.
template<class T > const char* llvm::final< T >::LowerXConstraint (EVT ConstraintVT) const [override, virtual]
Try to replace an X constraint, which matches anything, with another that has more specific requirements based on the type of the corresponding operand.
LowerXConstraint - try to replace an X constraint, which matches anything, with another that has more specific requirements based on the type of the corresponding operand.
This returns null if there is no replacement to make.
Reimplemented from llvm::TargetLowering.
template<class T > llvm::final< T >::Model (T Impl) [inline]
Definition at line 629 of file TargetTransformInfo.h.
template<class T > bool llvm::final< T >::needsStackRealignment (const MachineFunction & MF) const [override]
template<class T > bool llvm::final< T >::optimizeCompareInstr (MachineInstr * CmpInstr, unsigned SrcReg, unsigned SrcReg2, int CmpMask, int CmpValue, const MachineRegisterInfo * MRI) const [override]
optimizeCompareInstr - Check if there exists an earlier instruction that operates on the same source operands and sets flags in the same way as Compare; remove Compare if possible.
template<class T > MachineInstr* llvm::final< T >::optimizeLoadInstr (MachineInstr * MI, const MachineRegisterInfo * MRI, unsigned & FoldAsLoadDefReg, MachineInstr *& DefMI) const [override]
optimizeLoadInstr - Try to remove the load by folding it to a register operand at the use.
We fold the load instructions if and only if the def and use are in the same BB. We only look at one load and see whether it can be folded into MI. FoldAsLoadDefReg is the virtual register defined by the load we are trying to fold. DefMI returns the machine instruction that defines FoldAsLoadDefReg, and the function returns the machine instruction generated due to folding.
template<class T > bool llvm::final< T >::padShortFunctions () const [inline]
Definition at line 367 of file X86Subtarget.h.
template<class T > void llvm::final< T >::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
Definition of function is auto generated by tblgen.
template<class T > SDValue llvm::final< T >::PerformDAGCombine (SDNode * N, DAGCombinerInfo & DCI) const [override, virtual]
This method will be invoked for all target nodes and for any target-independent nodes that the target has registered with invoke it for.
The semantics are as follows: Return Value: SDValue.Val == 0 - No change was made SDValue.Val == N - N was replaced, is dead, and is already handled. otherwise - N should be replaced by the returned Operand.
In addition, methods provided by DAGCombinerInfo may be used to perform more complex transformations.
Reimplemented from llvm::TargetLowering.
template<class T > bool llvm::final< T >::printAliasInstr (const MCInst * MI, raw_ostream & OS)
template<class T > void llvm::final< T >::printanymem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 49 of file X86IntelInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printanymem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 55 of file X86ATTInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printCustomAliasOperand (const MCInst * MI, unsigned OpIdx, unsigned PrintMethodIdx, raw_ostream & O)
template<class T > void llvm::final< T >::printDstIdx (const MCInst * MI, unsigned OpNo, raw_ostream & O)
template<class T > void llvm::final< T >::printDstIdx (const MCInst * MI, unsigned OpNo, raw_ostream & OS)
template<class T > void llvm::final< T >::printDstIdx16 (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 118 of file X86ATTInstPrinter.h.
template<class T > void llvm::final< T >::printDstIdx16 (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 132 of file X86IntelInstPrinter.h.
template<class T > void llvm::final< T >::printDstIdx32 (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 121 of file X86ATTInstPrinter.h.
template<class T > void llvm::final< T >::printDstIdx32 (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 136 of file X86IntelInstPrinter.h.
template<class T > void llvm::final< T >::printDstIdx64 (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 124 of file X86ATTInstPrinter.h.
template<class T > void llvm::final< T >::printDstIdx64 (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 140 of file X86IntelInstPrinter.h.
template<class T > void llvm::final< T >::printDstIdx8 (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 115 of file X86ATTInstPrinter.h.
template<class T > void llvm::final< T >::printDstIdx8 (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 128 of file X86IntelInstPrinter.h.
template<class T > void llvm::final< T >::printf128mem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 93 of file X86ATTInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printf128mem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 98 of file X86IntelInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printf256mem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 96 of file X86ATTInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printf256mem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 102 of file X86IntelInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printf32mem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 84 of file X86ATTInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printf32mem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 86 of file X86IntelInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printf512mem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 99 of file X86ATTInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printf512mem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 106 of file X86IntelInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printf64mem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 87 of file X86ATTInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printf64mem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 90 of file X86IntelInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printf80mem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 90 of file X86ATTInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printf80mem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 94 of file X86IntelInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printi128mem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 74 of file X86IntelInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printi128mem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 75 of file X86ATTInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printi16mem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 62 of file X86IntelInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printi16mem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 66 of file X86ATTInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printi256mem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 78 of file X86IntelInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printi256mem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 78 of file X86ATTInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printi32mem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 66 of file X86IntelInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printi32mem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 69 of file X86ATTInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printi512mem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 81 of file X86ATTInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printi512mem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 82 of file X86IntelInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printi64mem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 70 of file X86IntelInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printi64mem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 72 of file X86ATTInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printi8mem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 58 of file X86IntelInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printi8mem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 63 of file X86ATTInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printInst (const MCInst * MI, raw_ostream & OS, StringRef Annot, const MCSubtargetInfo & STI) [override, virtual]
Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
template<class T > void llvm::final< T >::printInst (const MCInst * MI, raw_ostream & OS, StringRef Annot, const MCSubtargetInfo & STI) [override, virtual]
Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
template<class T > void llvm::final< T >::printInstruction (const MCInst * MI, raw_ostream & O)
template<class T > void llvm::final< T >::printInstruction (const MCInst * MI, raw_ostream & OS)
template<class T > void llvm::final< T >::printMemOffs16 (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 130 of file X86ATTInstPrinter.h.
template<class T > void llvm::final< T >::printMemOffs16 (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 148 of file X86IntelInstPrinter.h.
template<class T > void llvm::final< T >::printMemOffs32 (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 133 of file X86ATTInstPrinter.h.
template<class T > void llvm::final< T >::printMemOffs32 (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 152 of file X86IntelInstPrinter.h.
template<class T > void llvm::final< T >::printMemOffs64 (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 136 of file X86ATTInstPrinter.h.
template<class T > void llvm::final< T >::printMemOffs64 (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 156 of file X86IntelInstPrinter.h.
template<class T > void llvm::final< T >::printMemOffs8 (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 127 of file X86ATTInstPrinter.h.
template<class T > void llvm::final< T >::printMemOffs8 (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 144 of file X86IntelInstPrinter.h.
template<class T > void llvm::final< T >::printMemOffset (const MCInst * MI, unsigned OpNo, raw_ostream & O)
template<class T > void llvm::final< T >::printMemOffset (const MCInst * MI, unsigned OpNo, raw_ostream & OS)
template<class T > void llvm::final< T >::printMemReference (const MCInst * MI, unsigned Op, raw_ostream & O)
template<class T > void llvm::final< T >::printMemReference (const MCInst * MI, unsigned Op, raw_ostream & OS)
template<class T > void llvm::final< T >::printopaquemem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 53 of file X86IntelInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printopaquemem (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 59 of file X86ATTInstPrinter.h.
References printMemReference().
template<class T > void llvm::final< T >::printOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
template<class T > void llvm::final< T >::printOperand (const MCInst * MI, unsigned OpNo, raw_ostream & OS)
template<class T > void llvm::final< T >::printPCRelImm (const MCInst * MI, unsigned OpNo, raw_ostream & O)
template<class T > void llvm::final< T >::printPCRelImm (const MCInst * MI, unsigned OpNo, raw_ostream & OS)
template<class T > void llvm::final< T >::printRegName (raw_ostream & OS, unsigned RegNo) const [override, virtual]
Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
template<class T > void llvm::final< T >::printRegName (raw_ostream & OS, unsigned RegNo) const [override, virtual]
Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
template<class T > void llvm::final< T >::printRoundingControl (const MCInst * MI, unsigned Op, raw_ostream & OS)
template<class T > void llvm::final< T >::printRoundingControl (const MCInst * MI, unsigned Op, raw_ostream & OS)
template<class T > void llvm::final< T >::printSrcIdx (const MCInst * MI, unsigned OpNo, raw_ostream & O)
template<class T > void llvm::final< T >::printSrcIdx (const MCInst * MI, unsigned OpNo, raw_ostream & OS)
template<class T > void llvm::final< T >::printSrcIdx16 (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 106 of file X86ATTInstPrinter.h.
template<class T > void llvm::final< T >::printSrcIdx16 (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 116 of file X86IntelInstPrinter.h.
template<class T > void llvm::final< T >::printSrcIdx32 (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 109 of file X86ATTInstPrinter.h.
template<class T > void llvm::final< T >::printSrcIdx32 (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 120 of file X86IntelInstPrinter.h.
template<class T > void llvm::final< T >::printSrcIdx64 (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 112 of file X86ATTInstPrinter.h.
template<class T > void llvm::final< T >::printSrcIdx64 (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 124 of file X86IntelInstPrinter.h.
template<class T > void llvm::final< T >::printSrcIdx8 (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 103 of file X86ATTInstPrinter.h.
template<class T > void llvm::final< T >::printSrcIdx8 (const MCInst * MI, unsigned OpNo, raw_ostream & O) [inline]
Definition at line 112 of file X86IntelInstPrinter.h.
template<class T > void llvm::final< T >::printSSEAVXCC (const MCInst * MI, unsigned Op, raw_ostream & O)
template<class T > void llvm::final< T >::printSSEAVXCC (const MCInst * MI, unsigned Op, raw_ostream & OS)
template<class T > void llvm::final< T >::printU8Imm (const MCInst * MI, unsigned Op, raw_ostream & O)
template<class T > void llvm::final< T >::printU8Imm (const MCInst * MI, unsigned Op, raw_ostream & OS)
template<class T > void llvm::final< T >::printXOPCC (const MCInst * MI, unsigned Op, raw_ostream & O)
template<class T > void llvm::final< T >::printXOPCC (const MCInst * MI, unsigned Op, raw_ostream & OS)
template<class T > void llvm::final< T >::reMaterialize (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, unsigned DestReg, unsigned SubIdx, const MachineInstr * Orig, const TargetRegisterInfo & TRI) const [override]
template<class T > unsigned llvm::final< T >::RemoveBranch (MachineBasicBlock & MBB) const [override]
template<class T > void llvm::final< T >::ReplaceNodeResults (SDNode * N, SmallVectorImpl< SDValue > & Results, SelectionDAG & DAG) const [override, virtual]
Replace the results of node with an illegal result type with new values built out of custom code.
Reimplemented from llvm::TargetLowering.
template<class T > bool llvm::final< T >::ReverseBranchCondition (SmallVectorImpl< MachineOperand > & Cond) const [override]
template<class T > void llvm::final< T >::setExecutionDomain (MachineInstr * MI, unsigned Domain) const [override]
template<class T > void llvm::final< T >::setPICStyle (PICStyles::Style Style) [inline]
Definition at line 319 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::shouldBuildLookupTables () [inline, override, virtual]
Implements llvm::TargetTransformInfo::Concept.
Definition at line 701 of file TargetTransformInfo.h.
template<class T > bool llvm::final< T >::shouldConvertConstantLoadToIntImm (const APInt & Imm, Type * Ty) const [override, virtual]
Returns true if it is beneficial to convert a load of a constant to just the constant itself.
Reimplemented from llvm::TargetLoweringBase.
template<class T > bool llvm::final< T >::shouldReduceLoadWidth (SDNode * Load, ISD::LoadExtType ExtTy, EVT NewVT) const [override, virtual]
Return true if we believe it is correct and profitable to reduce the load node to a smaller type.
Reimplemented from llvm::TargetLoweringBase.
template<class T > bool llvm::final< T >::shouldScheduleAdjacent (MachineInstr * First, MachineInstr * Second) const [override]
template<class T > bool llvm::final< T >::shouldScheduleLoadsNear (SDNode * Load1, SDNode * Load2, int64_t Offset1, int64_t Offset2, unsigned NumLoads) const [override]
shouldScheduleLoadsNear - This is a used by the pre-regalloc scheduler to determine (in conjunction with areLoadsFromSameBasePtr) if two loads should be scheduled togther.
On some targets if two loads are loading from addresses in the same cache line, it's better if they are scheduled together. This function takes two integers that represent the load offsets from the common base address. It returns true if it decides it's desirable to schedule the two loads together. "NumLoads" is the number of loads that have already been scheduled after Load1.
template<class T > bool llvm::final< T >::ShouldShrinkFPConstant (EVT VT) const [inline, override, virtual]
If true, then instruction selection should seek to shrink the FP constant of the specified type to a smaller type in order to save space and / or reduce runtime.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 833 of file X86ISelLowering.h.
References llvm::MVT::f80.
template<class T > bool llvm::final< T >::slowIncDec () const [inline]
Definition at line 371 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::slowLEA () const [inline]
Definition at line 370 of file X86Subtarget.h.
template<class T > int llvm::final< T >::snprint (char * Buffer, unsigned BufferSize) const [inline, override, virtual]
Call snprintf() for this object, on the given buffer and size.
Implements llvm::format_object_base.
Definition at line 96 of file Format.h.
template<class T > void llvm::final< T >::storeRegToAddr (MachineFunction & MF, unsigned SrcReg, bool isKill, SmallVectorImpl< MachineOperand > & Addr, const TargetRegisterClass * RC, MachineInstr::mmo_iterator MMOBegin, MachineInstr::mmo_iterator MMOEnd, SmallVectorImpl< MachineInstr * > & NewMIs) const
template<class T > void llvm::final< T >::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const [override]
template<class T > bool llvm::final< T >::trackLivenessAfterRegAlloc (const MachineFunction & MF) const [override]
Code Generation virtual methods...
template<class T > bool llvm::final< T >::unfoldMemoryOperand (MachineFunction & MF, MachineInstr * MI, unsigned Reg, bool UnfoldLoad, bool UnfoldStore, SmallVectorImpl< MachineInstr * > & NewMIs) const [override]
unfoldMemoryOperand - Separate a single instruction which folded a load or a store or a load and a store into two or more instruction.
If this is possible, returns true as well as the new instructions by reference.
template<class T > bool llvm::final< T >::unfoldMemoryOperand (SelectionDAG & DAG, SDNode * N, SmallVectorImpl< SDNode * > & NewNodes) const [override]
template<class T > bool llvm::final< T >::useLeaForSP () const [inline]
Definition at line 364 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::useLoadStackGuardNode () const [override, virtual]
If this function returns true, SelectionDAGBuilder emits a LOAD_STACK_GUARD node when it is lowering Intrinsic::stackprotector.
Reimplemented from llvm::TargetLowering.
template<class T > bool llvm::final< T >::useMachineCombiner () const [inline, override]
Definition at line 457 of file X86InstrInfo.h.
template<class T > bool llvm::final< T >::useSoftFloat () const [inline, virtual]
Reimplemented from llvm::TargetLoweringBase.
Definition at line 382 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::useSoftFloat () const [override, virtual]
Reimplemented from llvm::TargetLoweringBase.
template<class T > llvm::final< T >::X86ATTInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) [inline]
Definition at line 26 of file X86ATTInstPrinter.h.
template<class T > llvm::final< T >::X86InstrInfo (X86Subtarget & STI) [explicit]
template<class T > llvm::final< T >::X86IntelInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) [inline]
Definition at line 26 of file X86IntelInstPrinter.h.
template<class T > llvm::final< T >::X86RegisterInfo (const Triple & TT)
template<class T > llvm::final< T >::X86Subtarget (const Triple & TT, const std::string & CPU, const std::string & FS, const X86TargetMachine & TM, unsigned StackAlignOverride)
This constructor initializes the data members to match that of the specified triple.
template<class T > llvm::final< T >::X86TargetLowering (const X86TargetMachine & TM, const X86Subtarget & STI) [explicit]
template<class T > llvm::final< T >::X86TargetMachine (const Target & T, const Triple & TT, StringRef CPU, StringRef FS, const TargetOptions & Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
Member Data Documentation
template<class T > bool llvm::final< T >::CallRegIndirect [protected]
True if the Calls with memory reference should be converted to a register-based indirect call.
Definition at line 181 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasADX [protected]
Processor has ADX instructions.
Definition at line 132 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasAES [protected]
Target has AES instructions.
Definition at line 87 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasBMI [protected]
Processor has BMI1 instructions.
Definition at line 120 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasBMI2 [protected]
Processor has BMI2 instructions.
Definition at line 123 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasBWI [protected]
Processor has AVX-512 Byte and Word instructions.
Definition at line 206 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasCDI [protected]
Processor has AVX-512 Conflict Detection Instructions.
Definition at line 200 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasCMov [protected]
True if this processor has conditional move instructions (generally pentium pro+).
Definition at line 75 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasCmpxchg16b [protected]
True if this processor has the CMPXCHG16B instruction; this is true for most x86-64 chips, but not the first AMD chips.
Definition at line 161 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasDQI [protected]
Processor has AVX-512 Doubleword and Quadword instructions.
Definition at line 203 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasERI [protected]
Processor has AVX-512 Exponential and Reciprocal Instructions.
Definition at line 197 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasF16C [protected]
Processor has 16-bit floating point conversion instructions.
Definition at line 111 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasFMA [protected]
Target has 3-operand fused multiply-add.
Definition at line 93 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasFMA4 [protected]
Target has 4-operand fused multiply-add.
Definition at line 96 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasFSGSBase [protected]
Processor has FS/GS base insturctions.
Definition at line 114 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasHLE [protected]
Processor has HLE.
Definition at line 129 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasLZCNT [protected]
Processor has LZCNT instruction.
Definition at line 117 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasMOVBE [protected]
True if the processor has the MOVBE instruction.
Definition at line 105 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasMPX [protected]
Processot supports MPX - Memory Protection Extensions.
Definition at line 212 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasPCLMUL [protected]
Target has carry-less multiplication.
Definition at line 90 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasPFI [protected]
Processor has AVX-512 PreFetch Instructions.
Definition at line 194 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasPOPCNT [protected]
True if the processor supports POPCNT.
Definition at line 81 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasPRFCHW [protected]
Processor has PRFCHW instructions.
Definition at line 138 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasRDRAND [protected]
True if the processor has the RDRAND instruction.
Definition at line 108 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasRDSEED [protected]
Processor has RDSEED instructions.
Definition at line 141 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasRTM [protected]
Processor has RTM instructions.
Definition at line 126 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasSHA [protected]
Processor has SHA instructions.
Definition at line 135 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasSlowDivide32 [protected]
True if 8-bit divisions are significantly faster than 32-bit divisions and should be used when possible.
Definition at line 169 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasSlowDivide64 [protected]
True if 16-bit divides are significantly faster than 64-bit divisions and should be used when possible.
Definition at line 173 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasSSE4A [protected]
True if the processor supports SSE4A instructions.
Definition at line 84 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasSSEUnalignedMem [protected]
True if SSE operations can have unaligned memory operands.
This may require setting a configuration bit in the processor.
Definition at line 157 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasTBM [protected]
Target has TBM instructions.
Definition at line 102 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasVLX [protected]
Processor has AVX-512 Vector Length eXtenstions.
Definition at line 209 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasX86_64 [protected]
True if the processor supports X86-64 instructions.
Definition at line 78 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::HasXOP [protected]
Target has XOP instructions.
Definition at line 99 of file X86Subtarget.h.
template<class T > InstrItineraryData llvm::final< T >::InstrItins [protected]
Instruction itineraries for scheduling.
Definition at line 229 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::IsBTMemSlow [protected]
True if BT (bit test) of memory instructions are slow.
Definition at line 144 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::IsSHLDSlow [protected]
True if SHLD instructions are slow.
Definition at line 147 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::IsUAMem32Slow [protected]
True if unaligned 32-byte memory accesses are slow.
Definition at line 153 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::IsUAMemFast [protected]
True if unaligned memory access is fast.
Definition at line 150 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::LEAUsesAG [protected]
True if the LEA instruction inputs have to be ready at address generation (AG) time.
Definition at line 185 of file X86Subtarget.h.
template<class T > unsigned llvm::final< T >::MaxInlineSizeThreshold [protected]
Max.
memset / memcpy size that is turned into rep/movs, rep/stos ops.
Definition at line 223 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::PadShortFunctions [protected]
True if the short functions should be padded to prevent a stall when returning too early.
Definition at line 177 of file X86Subtarget.h.
template<class T > PICStyles::Style llvm::final< T >::PICStyle [protected]
Which PIC style to use.
Definition at line 65 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::SlowIncDec [protected]
True if INC and DEC instructions are slow when writing to flags.
Definition at line 191 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::SlowLEA [protected]
True if the LEA instruction with certain arguments is slow.
Definition at line 188 of file X86Subtarget.h.
template<class T > unsigned llvm::final< T >::stackAlignment [protected]
The minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function.
Definition at line 219 of file X86Subtarget.h.
template<class T > Triple llvm::final< T >::TargetTriple [protected]
What processor and OS we're targeting.
Reimplemented from llvm::TargetMachine.
Definition at line 226 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::UseLeaForSP [protected]
True if the LEA instruction should be used for adjusting the stack pointer.
This is an optimization for Intel Atom processors.
Definition at line 165 of file X86Subtarget.h.
template<class T > bool llvm::final< T >::UseSoftFloat [protected]
Use software floating point for code generation.
Definition at line 215 of file X86Subtarget.h.
template<class T > X863DNowEnum llvm::final< T >::X863DNowLevel [protected]
3DNow, 3DNow Athlon, or none supported.
Definition at line 71 of file X86Subtarget.h.
template<class T > X86ProcFamilyEnum llvm::final< T >::X86ProcFamily [protected]
X86 processor family: Intel Atom, and others.
Definition at line 62 of file X86Subtarget.h.
template<class T > X86SSEEnum llvm::final< T >::X86SSELevel [protected]
MMX, SSE1, SSE2, SSE3, SSSE3, SSE41, SSE42, or none supported.
Definition at line 68 of file X86Subtarget.h.
The documentation for this class was generated from the following files:
FoldingSet.h
X86Subtarget.h
DWARFUnit.h
X86InstrInfo.h
TargetTransformInfo.h
Format.h
X86ATTInstPrinter.h
X86ISelLowering.h
X86RegisterInfo.h
X86TargetMachine.h
StringSaver.h
X86IntelInstPrinter.h