LLVM: llvm::IRBuilderBase Class Reference
llvm::IRBuilderBase Class Reference
Common base class shared among various IRBuilders.
#include <IRBuilder.h>
Classes
class FastMathFlagGuard
class InsertPoint
InsertPoint - A saved insertion point.
class InsertPointGuard
Public Member Functions
IRBuilderBase (LLVMContext &context, MDNode *FPMathTag=nullptr)
void ClearInsertionPoint ()
Clear the insertion point: created instructions will not be inserted into a block.
BasicBlock * GetInsertBlock () const
BasicBlock::iterator GetInsertPoint () const
LLVMContext & getContext () const
void SetInsertPoint (BasicBlock *TheBB)
This specifies that created instructions should be appended to the end of the specified block.
void SetInsertPoint (Instruction *I)
This specifies that created instructions should be inserted before the specified instruction.
void SetInsertPoint (BasicBlock *TheBB, BasicBlock::iterator IP)
This specifies that created instructions should be inserted at the specified point.
void SetInsertPoint (Use &U)
Find the nearest point that dominates this use, and specify that created instructions should be inserted at this point.
void SetCurrentDebugLocation (DebugLoc L)
Set location information used by debugging information.
const DebugLoc & getCurrentDebugLocation () const
Get location information used by debugging information.
void SetInstDebugLocation (Instruction *I) const
If this builder has a current debug location, set it on the specified instruction.
Type * getCurrentFunctionReturnType () const
Get the return type of the current function that we're emitting into.
InsertPoint saveIP () const
Returns the current insert point.
InsertPoint saveAndClearIP ()
Returns the current insert point, clearing it in the process.
void restoreIP (InsertPoint IP)
Sets the current insert point to a previously-saved location.
MDNode * getDefaultFPMathTag () const
Get the floating point math metadata being used.
FastMathFlags getFastMathFlags () const
Get the flags to be applied to created floating point ops.
void clearFastMathFlags ()
Clear the fast-math flags.
void SetDefaultFPMathTag (MDNode *FPMathTag)
Set the floating point math metadata to be used.
void SetFastMathFlags (FastMathFlags NewFMF)
Set the fast-math flags to be used with generated fp-math operators.
GlobalVariable * CreateGlobalString (StringRef Str, const Twine &Name="", unsigned AddressSpace=0)
Make a new global variable with initializer type i8*.
ConstantInt * getInt1 (bool V)
Get a constant value representing either true or false.
ConstantInt * getTrue ()
Get the constant value for i1 true.
ConstantInt * getFalse ()
Get the constant value for i1 false.
ConstantInt * getInt8 (uint8_t C)
Get a constant 8-bit value.
ConstantInt * getInt16 (uint16_t C)
Get a constant 16-bit value.
ConstantInt * getInt32 (uint32_t C)
Get a constant 32-bit value.
ConstantInt * getInt64 (uint64_t C)
Get a constant 64-bit value.
ConstantInt * getIntN (unsigned N, uint64_t C)
Get a constant N-bit value, zero extended or truncated from a 64-bit value.
ConstantInt * getInt (const APInt &AI)
Get a constant integer value.
IntegerType * getInt1Ty ()
Fetch the type representing a single bit.
IntegerType * getInt8Ty ()
Fetch the type representing an 8-bit integer.
IntegerType * getInt16Ty ()
Fetch the type representing a 16-bit integer.
IntegerType * getInt32Ty ()
Fetch the type representing a 32-bit integer.
IntegerType * getInt64Ty ()
Fetch the type representing a 64-bit integer.
IntegerType * getInt128Ty ()
Fetch the type representing a 128-bit integer.
IntegerType * getIntNTy (unsigned N)
Fetch the type representing an N-bit integer.
Type * getHalfTy ()
Fetch the type representing a 16-bit floating point value.
Type * getFloatTy ()
Fetch the type representing a 32-bit floating point value.
Type * getDoubleTy ()
Fetch the type representing a 64-bit floating point value.
Type * getVoidTy ()
Fetch the type representing void.
PointerType * getInt8PtrTy (unsigned AddrSpace=0)
Fetch the type representing a pointer to an 8-bit integer value.
IntegerType * getIntPtrTy (const DataLayout &DL, unsigned AddrSpace=0)
Fetch the type representing a pointer to an integer value.
CallInst * CreateMemSet (Value *Ptr, Value *Val, uint64_t Size, unsigned Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert a memset to the specified pointer and the specified value.
CallInst * CreateMemSet (Value *Ptr, Value *Val, Value *Size, unsigned Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateMemCpy (Value *Dst, Value *Src, uint64_t Size, unsigned Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert a memcpy between the specified pointers.
CallInst * CreateMemCpy (Value *Dst, Value *Src, Value *Size, unsigned Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateMemMove (Value *Dst, Value *Src, uint64_t Size, unsigned Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert a memmove between the specified pointers.
CallInst * CreateMemMove (Value *Dst, Value *Src, Value *Size, unsigned Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateLifetimeStart (Value *Ptr, ConstantInt *Size=nullptr)
Create a lifetime.start intrinsic.
CallInst * CreateLifetimeEnd (Value *Ptr, ConstantInt *Size=nullptr)
Create a lifetime.end intrinsic.
CallInst * CreateMaskedLoad (Value *Ptr, unsigned Align, Value *Mask, Value *PassThru=0, const Twine &Name="")
Create a call to Masked Load intrinsic.
CallInst * CreateMaskedStore (Value *Val, Value *Ptr, unsigned Align, Value *Mask)
Create a call to Masked Store intrinsic.
CallInst * CreateAssumption (Value *Cond)
Create an assume intrinsic call that allows the optimizer to assume that the provided condition will be true.
CallInst * CreateGCStatepointCall (uint64_t ID, uint32_t NumPatchBytes, Value *ActualCallee, ArrayRef< Value * > CallArgs, ArrayRef< Value * > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine &Name="")
Create a call to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
CallInst * CreateGCStatepointCall (uint64_t ID, uint32_t NumPatchBytes, Value *ActualCallee, ArrayRef< Use > CallArgs, ArrayRef< Value * > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine &Name="")
InvokeInst * CreateGCStatepointInvoke (uint64_t ID, uint32_t NumPatchBytes, Value *ActualInvokee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Value * > InvokeArgs, ArrayRef< Value * > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine &Name="")
brief Create an invoke to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
InvokeInst * CreateGCStatepointInvoke (uint64_t ID, uint32_t NumPatchBytes, Value *ActualInvokee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Use > InvokeArgs, ArrayRef< Value * > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine &Name="")
CallInst * CreateGCResult (Instruction *Statepoint, Type *ResultType, const Twine &Name="")
Create a call to the experimental.gc.result intrinsic to extract the result from a call wrapped in a statepoint.
CallInst * CreateGCRelocate (Instruction *Statepoint, int BaseOffset, int DerivedOffset, Type *ResultType, const Twine &Name="")
Create a call to the experimental.gc.relocate intrinsics to project the relocated value of one pointer from the statepoint.
Protected Attributes
BasicBlock * BB
BasicBlock::iterator InsertPt
LLVMContext & Context
MDNode * DefaultFPMathTag
FastMathFlags FMF
Detailed Description
Common base class shared among various IRBuilders.
Definition at line 52 of file IRBuilder.h.
Constructor & Destructor Documentation
llvm::IRBuilderBase::IRBuilderBase (LLVMContext & context, MDNode * FPMathTag = nullptr) [inline]
Definition at line 63 of file IRBuilder.h.
References ClearInsertionPoint().
Member Function Documentation
void llvm::IRBuilderBase::clearFastMathFlags () [inline]
Clear the fast-math flags.
Definition at line 183 of file IRBuilder.h.
References llvm::FastMathFlags::clear(), and FMF.
void llvm::IRBuilderBase::ClearInsertionPoint () [inline]
Clear the insertion point: created instructions will not be inserted into a block.
Definition at line 74 of file IRBuilder.h.
References BB, and InsertPt.
Referenced by llvm::SCEVExpander::clearInsertPoint(), IRBuilderBase(), restoreIP(), and saveAndClearIP().
CallInst * IRBuilderBase::CreateAssumption (Value * Cond)
Create an assume intrinsic call that allows the optimizer to assume that the provided condition will be true.
Definition at line 194 of file IRBuilder.cpp.
References BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt1Ty(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), and llvm::Value::getType().
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateAlignmentAssumption().
CallInst * IRBuilderBase::CreateGCRelocate (Instruction * Statepoint, int BaseOffset, int DerivedOffset, Type * ResultType, const Twine & Name = "")
Create a call to the experimental.gc.relocate intrinsics to project the relocated value of one pointer from the statepoint.
Definition at line 346 of file IRBuilder.cpp.
References BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt32(), llvm::BasicBlock::getParent(), and llvm::GlobalValue::getParent().
CallInst * IRBuilderBase::CreateGCResult (Instruction * Statepoint, Type * ResultType, const Twine & Name = "")
Create a call to the experimental.gc.result intrinsic to extract the result from a call wrapped in a statepoint.
Definition at line 334 of file IRBuilder.cpp.
References BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), llvm::BasicBlock::getParent(), and llvm::GlobalValue::getParent().
CallInst * IRBuilderBase::CreateGCStatepointCall (uint64_t ID, uint32_t NumPatchBytes, Value * ActualCallee, ArrayRef< Value * > CallArgs, ArrayRef< Value * > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine & Name = "")
Create a call to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
Definition at line 269 of file IRBuilder.cpp.
References BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), llvm::SequentialType::getElementType(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), getStatepointArgs(), and llvm::Value::getType().
Referenced by CreateGCStatepointCall().
CallInst * IRBuilderBase::CreateGCStatepointCall (uint64_t ID, uint32_t NumPatchBytes, Value * ActualCallee, ArrayRef< Use > CallArgs, ArrayRef< Value * > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine & Name = "")
Definition at line 290 of file IRBuilder.cpp.
References CreateGCStatepointCall().
InvokeInst * IRBuilderBase::CreateGCStatepointInvoke (uint64_t ID, uint32_t NumPatchBytes, Value * ActualInvokee, BasicBlock * NormalDest, BasicBlock * UnwindDest, ArrayRef< Value * > InvokeArgs, ArrayRef< Value * > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine & Name = "")
brief Create an invoke to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
Definition at line 301 of file IRBuilder.cpp.
References BB, createInvokeHelper(), llvm::Intrinsic::getDeclaration(), llvm::SequentialType::getElementType(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), getStatepointArgs(), and llvm::Value::getType().
Referenced by CreateGCStatepointInvoke().
InvokeInst * IRBuilderBase::CreateGCStatepointInvoke (uint64_t ID, uint32_t NumPatchBytes, Value * ActualInvokee, BasicBlock * NormalDest, BasicBlock * UnwindDest, ArrayRef< Use > InvokeArgs, ArrayRef< Value * > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine & Name = "")
Definition at line 322 of file IRBuilder.cpp.
References CreateGCStatepointInvoke().
GlobalVariable * IRBuilderBase::CreateGlobalString (StringRef Str, const Twine & Name = "", unsigned AddressSpace = 0)
Make a new global variable with initializer type i8*.
CreateGlobalString - Make a new global variable with an initializer that has array of i8 type filled in with the nul terminated string value specified.
Make a new global variable with an initializer that has array of i8 type filled in with the null terminated string value specified. The new global variable will be marked mergable with any others of the same contents. If Name is specified, it is the name of the global variable created.
If Name is specified, it is the name of the global variable created.
Definition at line 27 of file IRBuilder.cpp.
References BB, Context, llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), getString(), llvm::Value::getType(), llvm::GlobalValue::NotThreadLocal, llvm::GlobalValue::PrivateLinkage, and llvm::GlobalValue::setUnnamedAddr().
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateGlobalStringPtr().
CallInst * IRBuilderBase::CreateLifetimeEnd (Value * Ptr, ConstantInt * Size = nullptr)
Create a lifetime.end intrinsic.
If the pointer isn't i8* it will be converted.
Definition at line 179 of file IRBuilder.cpp.
References BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt64(), getInt64Ty(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::ConstantInt::getType(), and llvm::Value::getType().
CallInst * IRBuilderBase::CreateLifetimeStart (Value * Ptr, ConstantInt * Size = nullptr)
Create a lifetime.start intrinsic.
If the pointer isn't i8* it will be converted.
Definition at line 164 of file IRBuilder.cpp.
References BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt64(), getInt64Ty(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::ConstantInt::getType(), and llvm::Value::getType().
CallInst * IRBuilderBase::CreateMaskedLoad (Value * Ptr, unsigned Align, Value * Mask, Value * PassThru = 0, const Twine & Name = "")
Create a call to Masked Load intrinsic.
Create a call to a Masked Load intrinsic.
Ptr - the base pointer for the load Align - alignment of the source location Mask - an vector of booleans which indicates what vector lanes should be accessed in memory PassThru - a pass-through value that is used to fill the masked-off lanes of the result Name - name of the result variable
Definition at line 212 of file IRBuilder.cpp.
References llvm::UndefValue::get(), getInt32(), llvm::Value::getType(), and llvm::Type::isPointerTy().
CallInst * IRBuilderBase::CreateMaskedStore (Value * Val, Value * Ptr, unsigned Align, Value * Mask)
Create a call to Masked Store intrinsic.
Create a call to a Masked Store intrinsic.
Val - the data to be stored, Ptr - the base pointer for the store Align - alignment of the destination location Mask - an vector of booleans which indicates what vector lanes should be accessed in memory
Definition at line 231 of file IRBuilder.cpp.
References getInt32(), and llvm::Value::getType().
CallInst* llvm::IRBuilderBase::CreateMemCpy (Value * Dst, Value * Src, uint64_t Size, unsigned Align, bool isVolatile = false, MDNode * TBAATag = nullptr, MDNode * TBAAStructTag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr) [inline]
Create and insert a memcpy between the specified pointers.
If the pointers aren't i8*, they will be converted. If a TBAA tag is specified, it will be added to the instruction. Likewise with alias.scope and noalias tags.
Definition at line 394 of file IRBuilder.h.
References getInt64(), and isVolatile().
CallInst * IRBuilderBase::CreateMemCpy (Value * Dst, Value * Src, Value * Size, unsigned Align, bool isVolatile = false, MDNode * TBAATag = nullptr, MDNode * TBAAStructTag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr)
Definition at line 107 of file IRBuilder.cpp.
References BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt1(), getInt32(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Value::getType(), llvm::LLVMContext::MD_alias_scope, llvm::LLVMContext::MD_noalias, llvm::LLVMContext::MD_tbaa, llvm::LLVMContext::MD_tbaa_struct, and llvm::Instruction::setMetadata().
CallInst* llvm::IRBuilderBase::CreateMemMove (Value * Dst, Value * Src, uint64_t Size, unsigned Align, bool isVolatile = false, MDNode * TBAATag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr) [inline]
Create and insert a memmove between the specified pointers.
If the pointers aren't i8*, they will be converted. If a TBAA tag is specified, it will be added to the instruction. Likewise with alias.scope and noalias tags.
Definition at line 415 of file IRBuilder.h.
References getInt64(), and isVolatile().
CallInst * IRBuilderBase::CreateMemMove (Value * Dst, Value * Src, Value * Size, unsigned Align, bool isVolatile = false, MDNode * TBAATag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr)
Definition at line 138 of file IRBuilder.cpp.
References BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt1(), getInt32(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Value::getType(), llvm::LLVMContext::MD_alias_scope, llvm::LLVMContext::MD_noalias, llvm::LLVMContext::MD_tbaa, and llvm::Instruction::setMetadata().
CallInst* llvm::IRBuilderBase::CreateMemSet (Value * Ptr, Value * Val, uint64_t Size, unsigned Align, bool isVolatile = false, MDNode * TBAATag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr) [inline]
Create and insert a memset to the specified pointer and the specified value.
If the pointer isn't an i8*, it will be converted. If a TBAA tag is specified, it will be added to the instruction. Likewise with alias.scope and noalias tags.
Definition at line 376 of file IRBuilder.h.
References getInt64(), and isVolatile().
CallInst * IRBuilderBase::CreateMemSet (Value * Ptr, Value * Val, Value * Size, unsigned Align, bool isVolatile = false, MDNode * TBAATag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr)
Definition at line 82 of file IRBuilder.cpp.
References BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt1(), getInt32(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Value::getType(), llvm::LLVMContext::MD_alias_scope, llvm::LLVMContext::MD_noalias, llvm::LLVMContext::MD_tbaa, and llvm::Instruction::setMetadata().
LLVMContext& llvm::IRBuilderBase::getContext () const [inline]
Definition at line 81 of file IRBuilder.h.
References Context.
Referenced by generateUnsignedDivisionCode().
const DebugLoc& llvm::IRBuilderBase::getCurrentDebugLocation () const [inline]
Get location information used by debugging information.
Definition at line 123 of file IRBuilder.h.
Type * IRBuilderBase::getCurrentFunctionReturnType () const
Get the return type of the current function that we're emitting into.
Definition at line 41 of file IRBuilder.cpp.
References BB, llvm::BasicBlock::getParent(), and llvm::Function::getReturnType().
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateAggregateRet().
MDNode* llvm::IRBuilderBase::getDefaultFPMathTag () const [inline]
Get the floating point math metadata being used.
Definition at line 177 of file IRBuilder.h.
References DefaultFPMathTag.
Type* llvm::IRBuilderBase::getDoubleTy () [inline]
Fetch the type representing a 64-bit floating point value.
Definition at line 347 of file IRBuilder.h.
References Context.
ConstantInt* llvm::IRBuilderBase::getFalse () [inline]
Get the constant value for i1 false.
Definition at line 262 of file IRBuilder.h.
References Context.
Referenced by llvm::UpgradeIntrinsicCall().
FastMathFlags llvm::IRBuilderBase::getFastMathFlags () const [inline]
Get the flags to be applied to created floating point ops.
Definition at line 180 of file IRBuilder.h.
References FMF.
Type* llvm::IRBuilderBase::getFloatTy () [inline]
Fetch the type representing a 32-bit floating point value.
Definition at line 342 of file IRBuilder.h.
References Context.
Type* llvm::IRBuilderBase::getHalfTy () [inline]
Fetch the type representing a 16-bit floating point value.
Definition at line 337 of file IRBuilder.h.
References Context.
BasicBlock* llvm::IRBuilderBase::GetInsertBlock () const [inline]
Definition at line 79 of file IRBuilder.h.
References BB.
Referenced by callIntrinsic(), createCallHelper(), createInvokeHelper(), llvm::EmitBinaryFloatFnCall(), llvm::EmitFPutC(), llvm::EmitFPutS(), llvm::EmitFWrite(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::EmitMemChr(), llvm::EmitMemCmp(), llvm::EmitMemCpyChk(), llvm::EmitPutChar(), llvm::EmitPutS(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::EmitStrChr(), llvm::EmitStrCpy(), llvm::EmitStrLen(), llvm::EmitStrNCmp(), llvm::EmitStrNCpy(), llvm::EmitStrNLen(), llvm::EmitUnaryFloatFnCall(), generateUnsignedDivisionCode(), insertSinCosCall(), llvm::ARMTargetLowering::makeDMB(), saveAndClearIP(), and saveIP().
BasicBlock::iterator llvm::IRBuilderBase::GetInsertPoint () const [inline]
Definition at line 80 of file IRBuilder.h.
References InsertPt.
Referenced by createCallHelper(), createInvokeHelper(), llvm::expandDivision(), llvm::expandRemainder(), generateUnsignedDivisionCode(), saveAndClearIP(), and saveIP().
ConstantInt* llvm::IRBuilderBase::getInt (const APInt & AI) [inline]
Get a constant integer value.
Definition at line 293 of file IRBuilder.h.
References Context, and llvm::ConstantInt::get().
ConstantInt* llvm::IRBuilderBase::getInt1 (bool V) [inline]
Get a constant value representing either true or false.
Definition at line 252 of file IRBuilder.h.
References llvm::ConstantInt::get(), and getInt1Ty().
Referenced by CreateMemCpy(), CreateMemMove(), and CreateMemSet().
IntegerType* llvm::IRBuilderBase::getInt128Ty () [inline]
Fetch the type representing a 128-bit integer.
Definition at line 327 of file IRBuilder.h.
References Context.
ConstantInt* llvm::IRBuilderBase::getInt16 (uint16_t C) [inline]
Get a constant 16-bit value.
Definition at line 272 of file IRBuilder.h.
References llvm::ConstantInt::get(), and getInt16Ty().
IntegerType* llvm::IRBuilderBase::getInt16Ty () [inline]
Fetch the type representing a 16-bit integer.
Definition at line 312 of file IRBuilder.h.
References Context.
Referenced by getInt16().
IntegerType* llvm::IRBuilderBase::getInt1Ty () [inline]
Fetch the type representing a single bit.
Definition at line 302 of file IRBuilder.h.
References Context.
Referenced by CreateAssumption(), and getInt1().
ConstantInt* llvm::IRBuilderBase::getInt32 (uint32_t C) [inline]
Get a constant 32-bit value.
Definition at line 277 of file IRBuilder.h.
References llvm::ConstantInt::get(), and getInt32Ty().
Referenced by CreateGCRelocate(), CreateMaskedLoad(), CreateMaskedStore(), CreateMemCpy(), CreateMemMove(), CreateMemSet(), createOrdering(), llvm::IRBuilder< true, TargetFolder >::CreateShuffleVector(), generateSignedDivisionCode(), generateSignedRemainderCode(), generateUnsignedDivisionCode(), getInterleavedMask(), getSequentialMask(), getStatepointArgs(), getStridedMask(), llvm::ARMTargetLowering::makeDMB(), OptimizeIntegerToVectorInsertions(), OptimizeIntToFloatBitCast(), simplifyAllocaArraySize(), llvm::UpgradeIntrinsicCall(), UpgradeX86PSLLDQIntrinsics(), and UpgradeX86PSRLDQIntrinsics().
IntegerType* llvm::IRBuilderBase::getInt32Ty () [inline]
Fetch the type representing a 32-bit integer.
Definition at line 317 of file IRBuilder.h.
References Context.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateVectorSplat(), llvm::EmitFPutC(), llvm::EmitFPutS(), llvm::EmitMemChr(), llvm::EmitMemCmp(), llvm::EmitPutChar(), llvm::EmitPutS(), llvm::EmitStrChr(), llvm::EmitStrNCmp(), llvm::expandDivisionUpTo32Bits(), llvm::expandRemainderUpTo32Bits(), getInt32(), getSequentialMask(), and insertSinCosCall().
ConstantInt* llvm::IRBuilderBase::getInt64 (uint64_t C) [inline]
Get a constant 64-bit value.
Definition at line 282 of file IRBuilder.h.
References llvm::ConstantInt::get(), and getInt64Ty().
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateExtractElement(), llvm::IRBuilder< true, TargetFolder >::CreateInsertElement(), CreateLifetimeEnd(), CreateLifetimeStart(), CreateMemCpy(), CreateMemMove(), CreateMemSet(), generateSignedDivisionCode(), generateSignedRemainderCode(), generateUnsignedDivisionCode(), and getStatepointArgs().
IntegerType* llvm::IRBuilderBase::getInt64Ty () [inline]
Fetch the type representing a 64-bit integer.
Definition at line 322 of file IRBuilder.h.
References Context.
Referenced by CreateLifetimeEnd(), CreateLifetimeStart(), llvm::expandDivisionUpTo64Bits(), llvm::expandRemainderUpTo64Bits(), and getInt64().
ConstantInt* llvm::IRBuilderBase::getInt8 (uint8_t C) [inline]
Get a constant 8-bit value.
Definition at line 267 of file IRBuilder.h.
References llvm::ConstantInt::get(), and getInt8Ty().
Referenced by llvm::UpgradeIntrinsicCall(), UpgradeX86PSLLDQIntrinsics(), and UpgradeX86PSRLDQIntrinsics().
PointerType* llvm::IRBuilderBase::getInt8PtrTy (unsigned AddrSpace = 0) [inline]
Fetch the type representing a pointer to an 8-bit integer value.
Definition at line 357 of file IRBuilder.h.
References Context.
Referenced by llvm::CastToCStr(), llvm::EmitFPutS(), llvm::EmitFWrite(), llvm::EmitMemChr(), llvm::EmitMemCmp(), llvm::EmitMemCpyChk(), llvm::EmitPutS(), llvm::EmitStrChr(), llvm::EmitStrCpy(), llvm::EmitStrLen(), llvm::EmitStrNCmp(), llvm::EmitStrNCpy(), and llvm::EmitStrNLen().
IntegerType* llvm::IRBuilderBase::getInt8Ty () [inline]
Fetch the type representing an 8-bit integer.
Definition at line 307 of file IRBuilder.h.
References Context.
Referenced by convertTransferToLoop(), and getInt8().
ConstantInt* llvm::IRBuilderBase::getIntN (unsigned N, uint64_t C) [inline]
Get a constant N-bit value, zero extended or truncated from a 64-bit value.
Definition at line 288 of file IRBuilder.h.
References llvm::ConstantInt::get(), and getIntNTy().
IntegerType* llvm::IRBuilderBase::getIntNTy (unsigned N) [inline]
Fetch the type representing an N-bit integer.
Definition at line 332 of file IRBuilder.h.
References Context.
Referenced by getIntN().
IntegerType* llvm::IRBuilderBase::getIntPtrTy (const DataLayout & DL, unsigned AddrSpace = 0) [inline]
Fetch the type representing a pointer to an integer value.
Definition at line 362 of file IRBuilder.h.
References Context, and llvm::DataLayout::getIntPtrType().
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateAlignmentAssumption().
ConstantInt* llvm::IRBuilderBase::getTrue () [inline]
Get the constant value for i1 true.
Definition at line 257 of file IRBuilder.h.
References Context.
Referenced by generateUnsignedDivisionCode().
Type* llvm::IRBuilderBase::getVoidTy () [inline]
Fetch the type representing void.
Definition at line 352 of file IRBuilder.h.
References Context.
void llvm::IRBuilderBase::restoreIP (InsertPoint IP) [inline]
Sets the current insert point to a previously-saved location.
Definition at line 169 of file IRBuilder.h.
References ClearInsertionPoint(), llvm::IRBuilderBase::InsertPoint::getBlock(), llvm::IRBuilderBase::InsertPoint::getPoint(), llvm::IRBuilderBase::InsertPoint::isSet(), and SetInsertPoint().
Referenced by llvm::IRBuilderBase::InsertPointGuard::~InsertPointGuard().
InsertPoint llvm::IRBuilderBase::saveAndClearIP () [inline]
Returns the current insert point, clearing it in the process.
Definition at line 162 of file IRBuilder.h.
References ClearInsertionPoint(), GetInsertBlock(), GetInsertPoint(), and llvm::IP.
InsertPoint llvm::IRBuilderBase::saveIP () const [inline]
Returns the current insert point.
Definition at line 157 of file IRBuilder.h.
References GetInsertBlock(), and GetInsertPoint().
void llvm::IRBuilderBase::SetCurrentDebugLocation (DebugLoc L) [inline]
Set location information used by debugging information.
Definition at line 120 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::IRBuilder(), makeStatepointExplicitImpl(), llvm::SCEVExpander::replaceCongruentIVs(), SetInsertPoint(), simplifyRelocatesOffABase(), SimplifyTerminatorOnSelect(), TryToSimplifyUncondBranchWithICmpInIt(), and llvm::IRBuilderBase::InsertPointGuard::~InsertPointGuard().
void llvm::IRBuilderBase::SetDefaultFPMathTag (MDNode * FPMathTag) [inline]
Set the floating point math metadata to be used.
Definition at line 186 of file IRBuilder.h.
References DefaultFPMathTag.
void llvm::IRBuilderBase::SetFastMathFlags (FastMathFlags NewFMF) [inline]
Set the fast-math flags to be used with generated fp-math operators.
Definition at line 189 of file IRBuilder.h.
References FMF.
void llvm::IRBuilderBase::SetInsertPoint (BasicBlock * TheBB) [inline]
This specifies that created instructions should be appended to the end of the specified block.
Definition at line 85 of file IRBuilder.h.
References BB, llvm::BasicBlock::end(), and InsertPt.
Referenced by combineLoadToOperationType(), llvm::SCEVExpander::expandCodeFor(), FoldTwoEntryPHINode(), generatedUnsignedRemainderCode(), generateSignedDivisionCode(), generateSignedRemainderCode(), generateUnsignedDivisionCode(), insertSinCosCall(), llvm::IRBuilder< true, TargetFolder >::IRBuilder(), makeStatepointExplicitImpl(), ProcessUGT_ADDCST_ADD(), ProcessUMulZExtIdiom(), restoreIP(), SetInsertPoint(), SimplifyBranchOnICmpChain(), SimplifyCondBranchToTwoReturns(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), SwitchToLookupTable(), SwitchToSelect(), TryToSimplifyUncondBranchWithICmpInIt(), llvm::UpgradeIntrinsicCall(), and llvm::ObjectSizeOffsetEvaluator::visitPHINode().
void llvm::IRBuilderBase::SetInsertPoint (Instruction * I) [inline]
This specifies that created instructions should be inserted before the specified instruction.
Definition at line 92 of file IRBuilder.h.
References BB, llvm::BasicBlock::end(), llvm::Instruction::getDebugLoc(), llvm::Instruction::getParent(), I, InsertPt, and SetCurrentDebugLocation().
void llvm::IRBuilderBase::SetInsertPoint (BasicBlock * TheBB, BasicBlock::iterator IP) [inline]
This specifies that created instructions should be inserted at the specified point.
Definition at line 101 of file IRBuilder.h.
References BB, InsertPt, and llvm::IP.
void llvm::IRBuilderBase::SetInsertPoint (Use & U) [inline]
Find the nearest point that dominates this use, and specify that created instructions should be inserted at this point.
Definition at line 108 of file IRBuilder.h.
References llvm::BasicBlock::getTerminator(), llvm::Use::getUser(), and SetInsertPoint().
void llvm::IRBuilderBase::SetInstDebugLocation (Instruction * I) const [inline]
If this builder has a current debug location, set it on the specified instruction.
Definition at line 127 of file IRBuilder.h.
References llvm::Instruction::setDebugLoc().
Referenced by createCallHelper(), createInvokeHelper(), and llvm::IRBuilder< true, TargetFolder >::Insert().
Member Data Documentation
BasicBlock* llvm::IRBuilderBase::BB [protected]
Definition at line 55 of file IRBuilder.h.
Referenced by ClearInsertionPoint(), CreateAssumption(), CreateGCRelocate(), CreateGCResult(), CreateGCStatepointCall(), CreateGCStatepointInvoke(), CreateGlobalString(), CreateLifetimeEnd(), CreateLifetimeStart(), CreateMemCpy(), CreateMemMove(), CreateMemSet(), getCurrentFunctionReturnType(), GetInsertBlock(), llvm::IRBuilder< true, TargetFolder >::Insert(), and SetInsertPoint().
LLVMContext& llvm::IRBuilderBase::Context [protected]
Definition at line 57 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateAggregateRet(), llvm::IRBuilder< true, TargetFolder >::CreateConstGEP1_32(), llvm::IRBuilder< true, TargetFolder >::CreateConstGEP1_64(), llvm::IRBuilder< true, TargetFolder >::CreateConstGEP2_32(), llvm::IRBuilder< true, TargetFolder >::CreateConstGEP2_64(), llvm::IRBuilder< true, TargetFolder >::CreateConstInBoundsGEP1_32(), llvm::IRBuilder< true, TargetFolder >::CreateConstInBoundsGEP1_64(), llvm::IRBuilder< true, TargetFolder >::CreateConstInBoundsGEP2_32(), llvm::IRBuilder< true, TargetFolder >::CreateConstInBoundsGEP2_64(), llvm::IRBuilder< true, TargetFolder >::CreateFence(), CreateGlobalString(), llvm::IRBuilder< true, TargetFolder >::CreateGlobalStringPtr(), llvm::IRBuilder< true, TargetFolder >::CreatePtrDiff(), llvm::IRBuilder< true, TargetFolder >::CreateRet(), llvm::IRBuilder< true, TargetFolder >::CreateRetVoid(), llvm::IRBuilder< true, TargetFolder >::CreateUnreachable(), getContext(), getDoubleTy(), getFalse(), getFloatTy(), getHalfTy(), getInt(), getInt128Ty(), getInt16Ty(), getInt1Ty(), getInt32Ty(), getInt64Ty(), getInt8PtrTy(), getInt8Ty(), getIntNTy(), getIntPtrTy(), getTrue(), and getVoidTy().
MDNode* llvm::IRBuilderBase::DefaultFPMathTag [protected]
Definition at line 59 of file IRBuilder.h.
Referenced by getDefaultFPMathTag(), SetDefaultFPMathTag(), and llvm::IRBuilderBase::FastMathFlagGuard::~FastMathFlagGuard().
FastMathFlags llvm::IRBuilderBase::FMF [protected]
Definition at line 60 of file IRBuilder.h.
Referenced by clearFastMathFlags(), getFastMathFlags(), SetFastMathFlags(), and llvm::IRBuilderBase::FastMathFlagGuard::~FastMathFlagGuard().
BasicBlock::iterator llvm::IRBuilderBase::InsertPt [protected]
Definition at line 56 of file IRBuilder.h.
Referenced by ClearInsertionPoint(), GetInsertPoint(), llvm::IRBuilder< true, TargetFolder >::Insert(), and SetInsertPoint().
The documentation for this class was generated from the following files:
IRBuilder.h
IRBuilder.cpp