LLVM: llvm::object::ELFObjectFileBase Class Reference
llvm::object::ELFObjectFileBase Class Reference
#include <ELFObjectFile.h>
Public Member Functions
virtual ErrorOr< int64_t > getRelocationAddend (DataRefImpl Rel) const =0
virtual bool hasRelocationAddend (DataRefImpl Rel) const =0
virtual std::pair
< symbol_iterator,
symbol_iterator > getELFDynamicSymbolIterators () const =0
virtual uint64_t getSectionFlags (SectionRef Sec) const =0
virtual uint32_t getSectionType (SectionRef Sec) const =0
Static Public Member Functions
static bool classof (const Binary *v)
Protected Member Functions
ELFObjectFileBase (unsigned int Type, MemoryBufferRef Source)
Detailed Description
Definition at line 38 of file ELFObjectFile.h.
Constructor & Destructor Documentation
llvm::ELFObjectFileBase::ELFObjectFileBase (unsigned int Type, MemoryBufferRef Source) [protected]
Definition at line 20 of file ELFObjectFile.cpp.
Member Function Documentation
static bool llvm::object::ELFObjectFileBase::classof (const Binary * v) [inline, static]
Reimplemented from llvm::object::ObjectFile.
Reimplemented in llvm::object::ELFObjectFile< ELFT >.
Definition at line 55 of file ELFObjectFile.h.
References llvm::object::Binary::isELF().
virtual std::pair<symbol_iterator, symbol_iterator> llvm::object::ELFObjectFileBase::getELFDynamicSymbolIterators () const [pure virtual]
Implemented in llvm::object::ELFObjectFile< ELFT >.
virtual ErrorOr<int64_t> llvm::object::ELFObjectFileBase::getRelocationAddend (DataRefImpl Rel) const [pure virtual]
Implemented in llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::RuntimeDyldELF::processRelocationRef().
virtual uint64_t llvm::object::ELFObjectFileBase::getSectionFlags (SectionRef Sec) const [pure virtual]
Implemented in llvm::object::ELFObjectFile< ELFT >.
virtual uint32_t llvm::object::ELFObjectFileBase::getSectionType (SectionRef Sec) const [pure virtual]
Implemented in llvm::object::ELFObjectFile< ELFT >.
virtual bool llvm::object::ELFObjectFileBase::hasRelocationAddend (DataRefImpl Rel) const [pure virtual]
Implemented in llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::RuntimeDyldELF::processRelocationRef().
The documentation for this class was generated from the following files:
ELFObjectFile.h
ELFObjectFile.cpp