LLVM: llvm::IntrinsicInst Class Reference
llvm::IntrinsicInst Class Reference
IntrinsicInst - A useful wrapper class for inspecting calls to intrinsic functions.
#include <IntrinsicInst.h>
Public Member Functions
Intrinsic::ID getIntrinsicID () const
getIntrinsicID - Return the intrinsic ID of this intrinsic.
Static Public Member Functions
static bool classof (const CallInst *I)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Detailed Description
IntrinsicInst - A useful wrapper class for inspecting calls to intrinsic functions.
This allows the standard isa/dyncast/cast functionality to work with calls to intrinsic functions.
Definition at line 37 of file IntrinsicInst.h.
Member Function Documentation
static bool llvm::IntrinsicInst::classof (const CallInst * I) [inline, static]
Definition at line 49 of file IntrinsicInst.h.
References llvm::CallInst::getCalledFunction().
Referenced by classof().
static bool llvm::IntrinsicInst::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::CallInst.
Reimplemented in llvm::InstrProfIncrementInst, llvm::VACopyInst, llvm::VAEndInst, llvm::VAStartInst, llvm::MemMoveInst, llvm::MemCpyInst, llvm::MemTransferInst, llvm::MemSetInst, llvm::MemIntrinsic, llvm::DbgValueInst, llvm::DbgDeclareInst, and llvm::DbgInfoIntrinsic.
Definition at line 54 of file IntrinsicInst.h.
References classof().
Intrinsic::ID llvm::IntrinsicInst::getIntrinsicID () const [inline]
getIntrinsicID - Return the intrinsic ID of this intrinsic.
Definition at line 44 of file IntrinsicInst.h.
References llvm::CallInst::getCalledFunction(), and llvm::Function::getIntrinsicID().
Referenced by allPredCameFromBeginCatch(), allSuccessorsReachEndCatch(), AnalyzeLoadFromClobberingMemInst(), llvm::DbgInfoIntrinsic::classof(), llvm::DbgDeclareInst::classof(), llvm::DbgValueInst::classof(), llvm::MemIntrinsic::classof(), llvm::MemSetInst::classof(), llvm::MemTransferInst::classof(), llvm::MemCpyInst::classof(), llvm::MemMoveInst::classof(), llvm::VAStartInst::classof(), llvm::VAEndInst::classof(), llvm::VACopyInst::classof(), llvm::InstrProfIncrementInst::classof(), detectLog2OfHalf(), FindInitTrampoline(), FindInitTrampolineFromAlloca(), llvm::BasicBlock::getFirstNonPHIOrDbgOrLifetime(), getLocForWrite(), llvm::AArch64TTIImpl::getOrCreateResultFromMemIntrinsic(), llvm::AArch64TTIImpl::getTgtMemIntrinsic(), insertRelocationStores(), isAssumeIntrinsic(), llvm::FastISel::isCommutativeIntrinsic(), isIntegerWideningViableForSlice(), isNVVMAtomic(), isVectorPromotionViableForSlice(), llvm::onlyUsedByLifetimeMarkers(), llvm::parseEHActions(), readsLaneId(), readsThreadIndex(), llvm::FastISel::selectIntrinsicCall(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitFPTrunc(), and llvm::PtrUseVisitor< SliceBuilder >::visitIntrinsicInst().
The documentation for this class was generated from the following file:
IntrinsicInst.h