LLVM: llvm::cl::OptionValueCopy< DataType > Class Template Reference
llvm::cl::OptionValueCopy< DataType > Class Template Reference
#include <CommandLine.h>
Public Member Functions
OptionValueCopy ()
bool hasValue () const
const DataType & getValue () const
void setValue (const DataType &V)
bool compare (const DataType &V) const
bool compare (const GenericOptionValue &V) const override
Protected Member Functions
~OptionValueCopy ()
OptionValueCopy (const OptionValueCopy &)
OptionValueCopy & operator= (const OptionValueCopy &)
Detailed Description
template<class DataType>
class llvm::cl::OptionValueCopy< DataType >
Definition at line 397 of file CommandLine.h.
Constructor & Destructor Documentation
template<class DataType> llvm::cl::OptionValueCopy< DataType >::~OptionValueCopy () [protected]
template<class DataType> llvm::cl::OptionValueCopy< DataType >::OptionValueCopy (const OptionValueCopy< DataType > &) [protected]
template<class DataType> llvm::cl::OptionValueCopy< DataType >::OptionValueCopy () [inline]
Definition at line 407 of file CommandLine.h.
Member Function Documentation
template<class DataType> bool llvm::cl::OptionValueCopy< DataType >::compare (const DataType & V) const [inline]
Definition at line 421 of file CommandLine.h.
Referenced by llvm::cl::OptionValueCopy< cl::boolOrDefault >::compare().
template<class DataType> bool llvm::cl::OptionValueCopy< DataType >::compare (const GenericOptionValue & V) const [inline, override, virtual]
Implements llvm::cl::GenericOptionValue.
Definition at line 423 of file CommandLine.h.
template<class DataType> const DataType& llvm::cl::OptionValueCopy< DataType >::getValue () const [inline]
Definition at line 411 of file CommandLine.h.
Referenced by llvm::cl::OptionValueCopy< cl::boolOrDefault >::compare().
template<class DataType> bool llvm::cl::OptionValueCopy< DataType >::hasValue () const [inline]
Definition at line 409 of file CommandLine.h.
Referenced by llvm::cl::OptionValueCopy< cl::boolOrDefault >::compare().
template<class DataType> OptionValueCopy& llvm::cl::OptionValueCopy< DataType >::operator= (const OptionValueCopy< DataType > &) [protected]
template<class DataType> void llvm::cl::OptionValueCopy< DataType >::setValue (const DataType & V) [inline]
Definition at line 416 of file CommandLine.h.
The documentation for this class was generated from the following file:
CommandLine.h