LLVM: llvm::MCCodeGenInfo Class Reference
llvm::MCCodeGenInfo Class Reference
#include <MCCodeGenInfo.h>
Public Member Functions
void initMCCodeGenInfo (Reloc::Model RM=Reloc::Default, CodeModel::Model CM=CodeModel::Default, CodeGenOpt::Level OL=CodeGenOpt::Default)
Reloc::Model getRelocationModel () const
CodeModel::Model getCodeModel () const
CodeGenOpt::Level getOptLevel () const
void setOptLevel (CodeGenOpt::Level Level)
Detailed Description
Definition at line 22 of file MCCodeGenInfo.h.
Member Function Documentation
CodeModel::Model llvm::MCCodeGenInfo::getCodeModel () const [inline]
Definition at line 42 of file MCCodeGenInfo.h.
Referenced by llvm::TargetMachine::getCodeModel().
CodeGenOpt::Level llvm::MCCodeGenInfo::getOptLevel () const [inline]
Definition at line 44 of file MCCodeGenInfo.h.
Referenced by llvm::TargetMachine::getOptLevel().
Reloc::Model llvm::MCCodeGenInfo::getRelocationModel () const [inline]
Definition at line 40 of file MCCodeGenInfo.h.
Referenced by llvm::TargetMachine::getRelocationModel().
void MCCodeGenInfo::initMCCodeGenInfo (Reloc::Model RM = Reloc::Default, CodeModel::Model CM = CodeModel::Default, CodeGenOpt::Level OL = CodeGenOpt::Default)
Definition at line 18 of file MCCodeGenInfo.cpp.
References llvm::NVPTX::PTXCvtMode::RM.
Referenced by createAArch64MCCodeGenInfo(), createAMDGPUMCCodeGenInfo(), createARMMCCodeGenInfo(), createBPFMCCodeGenInfo(), createHexagonMCCodeGenInfo(), createMipsMCCodeGenInfo(), createMSP430MCCodeGenInfo(), createNVPTXMCCodeGenInfo(), createPPCMCCodeGenInfo(), createSparcMCCodeGenInfo(), createSparcV9MCCodeGenInfo(), createSystemZMCCodeGenInfo(), createX86MCCodeGenInfo(), and createXCoreMCCodeGenInfo().
void llvm::MCCodeGenInfo::setOptLevel (CodeGenOpt::Level Level) [inline]
Definition at line 47 of file MCCodeGenInfo.h.
Referenced by llvm::TargetMachine::setOptLevel().
The documentation for this class was generated from the following files:
MCCodeGenInfo.h
MCCodeGenInfo.cpp