LLVM: llvm::AMDGPUTargetMachine Class Reference
llvm::AMDGPUTargetMachine Class Reference
#include <AMDGPUTargetMachine.h>
Public Member Functions
AMDGPUTargetMachine (const Target &T, const Triple &TT, StringRef FS, StringRef CPU, TargetOptions Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
~AMDGPUTargetMachine ()
const AMDGPUSubtarget * getSubtargetImpl () const
const AMDGPUSubtarget * getSubtargetImpl (const Function &) const override
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
const AMDGPUIntrinsicInfo * getIntrinsicInfo () const override
If intrinsic information is available, return it. If not, return null.
TargetIRAnalysis getTargetIRAnalysis () override
Get a TargetIRAnalysis implementation for the target.
TargetLoweringObjectFile * getObjFileLowering () const override
Protected Attributes
TargetLoweringObjectFile * TLOF
AMDGPUSubtarget Subtarget
AMDGPUIntrinsicInfo IntrinsicInfo
Detailed Description
Definition at line 31 of file AMDGPUTargetMachine.h.
Constructor & Destructor Documentation
AMDGPUTargetMachine::AMDGPUTargetMachine (const Target & T, const Triple & TT, StringRef FS, StringRef CPU, TargetOptions Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
Definition at line 68 of file AMDGPUTargetMachine.cpp.
References llvm::LLVMTargetMachine::initAsmInfo(), and llvm::TargetMachine::setRequiresStructuredCFG().
AMDGPUTargetMachine::~AMDGPUTargetMachine ()
Definition at line 81 of file AMDGPUTargetMachine.cpp.
References TLOF.
Member Function Documentation
const AMDGPUIntrinsicInfo* llvm::AMDGPUTargetMachine::getIntrinsicInfo () const [inline, override, virtual]
If intrinsic information is available, return it. If not, return null.
Reimplemented from llvm::TargetMachine.
Definition at line 49 of file AMDGPUTargetMachine.h.
References IntrinsicInfo.
TargetLoweringObjectFile* llvm::AMDGPUTargetMachine::getObjFileLowering () const [inline, override, virtual]
Reimplemented from llvm::TargetMachine.
Definition at line 54 of file AMDGPUTargetMachine.h.
References TLOF.
const AMDGPUSubtarget* llvm::AMDGPUTargetMachine::getSubtargetImpl () const [inline]
Definition at line 45 of file AMDGPUTargetMachine.h.
References Subtarget.
const AMDGPUSubtarget* llvm::AMDGPUTargetMachine::getSubtargetImpl (const Function &) const [inline, override, virtual]
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
Reimplemented from llvm::TargetMachine.
Definition at line 46 of file AMDGPUTargetMachine.h.
References Subtarget.
TargetIRAnalysis AMDGPUTargetMachine::getTargetIRAnalysis () [override, virtual]
Get a TargetIRAnalysis implementation for the target.
This analysis will produce a TTI result which uses the common code generator to answer queries about the IR.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 158 of file AMDGPUTargetMachine.cpp.
References F().
Member Data Documentation
AMDGPUIntrinsicInfo llvm::AMDGPUTargetMachine::IntrinsicInfo [protected]
Definition at line 37 of file AMDGPUTargetMachine.h.
Referenced by getIntrinsicInfo().
AMDGPUSubtarget llvm::AMDGPUTargetMachine::Subtarget [protected]
Definition at line 36 of file AMDGPUTargetMachine.h.
Referenced by getSubtargetImpl().
TargetLoweringObjectFile* llvm::AMDGPUTargetMachine::TLOF [protected]
Definition at line 35 of file AMDGPUTargetMachine.h.
Referenced by getObjFileLowering(), and ~AMDGPUTargetMachine().
The documentation for this class was generated from the following files:
AMDGPUTargetMachine.h
AMDGPUTargetMachine.cpp