LLVM: llvm::ReturnInst Class Reference
llvm::ReturnInst Class Reference
ReturnInst - Return a value (possibly void), from a function.
#include <Instructions.h>
Public Member Functions
~ReturnInst () override
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Provide fast operand accessors.
Value * getReturnValue () const
Convenience accessor. Returns null if there is no return value.
unsigned getNumSuccessors () const
Return the number of successors that this terminator has.
Static Public Member Functions
static ReturnInst * Create (LLVMContext &C, Value *retVal=nullptr, Instruction *InsertBefore=nullptr)
static ReturnInst * Create (LLVMContext &C, Value *retVal, BasicBlock *InsertAtEnd)
static ReturnInst * Create (LLVMContext &C, BasicBlock *InsertAtEnd)
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
ReturnInst * clone_impl () const override
Detailed Description
ReturnInst - Return a value (possibly void), from a function.
Execution does not continue in this function any longer.
Definition at line 2521 of file Instructions.h.
Constructor & Destructor Documentation
ReturnInst::~ReturnInst () [override]
Definition at line 638 of file Instructions.cpp.
Member Function Documentation
static bool llvm::ReturnInst::classof (const Instruction * I) [inline, static]
Reimplemented from llvm::TerminatorInst.
Definition at line 2567 of file Instructions.h.
References llvm::Instruction::getOpcode(), and llvm::MipsISD::Ret.
static bool llvm::ReturnInst::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::TerminatorInst.
Definition at line 2570 of file Instructions.h.
ReturnInst * ReturnInst::clone_impl () const [override, protected, virtual]
Implements llvm::Instruction.
Definition at line 3605 of file Instructions.cpp.
References llvm::User::getNumOperands().
static ReturnInst* llvm::ReturnInst::Create (LLVMContext & C, Value * retVal = nullptr, Instruction * InsertBefore = nullptr) [inline, static]
Definition at line 2543 of file Instructions.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateAggregateRet(), llvm::IRBuilder< true, TargetFolder >::CreateRet(), llvm::IRBuilder< true, TargetFolder >::CreateRetVoid(), llvm::createSanitizerCtorAndInitFunctions(), and llvm::UnifyFunctionExitNodes::runOnFunction().
static ReturnInst* llvm::ReturnInst::Create (LLVMContext & C, Value * retVal, BasicBlock * InsertAtEnd) [inline, static]
Definition at line 2547 of file Instructions.h.
static ReturnInst* llvm::ReturnInst::Create (LLVMContext & C, BasicBlock * InsertAtEnd) [inline, static]
Definition at line 2551 of file Instructions.h.
llvm::ReturnInst::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Provide fast operand accessors.
unsigned llvm::ReturnInst::getNumSuccessors () const [inline]
Return the number of successors that this terminator has.
Reimplemented from llvm::TerminatorInst.
Definition at line 2564 of file Instructions.h.
Value* llvm::ReturnInst::getReturnValue () const [inline]
Convenience accessor. Returns null if there is no return value.
Definition at line 2560 of file Instructions.h.
Referenced by llvm::BasicBlock::getTerminatingMustTailCall(), llvm::InlineFunction(), isEmptyFunction(), SimplifyCondBranchToTwoReturns(), and llvm::Interpreter::visitReturnInst().
The documentation for this class was generated from the following files:
Instructions.h
Instructions.cpp