LLVM: llvm::AtomicSDNode Class Reference
llvm::AtomicSDNode Class Reference
This is an SDNode representing atomic operations.
#include <SelectionDAGNodes.h>
Public Member Functions
AtomicSDNode (unsigned Opc, unsigned Order, DebugLoc dl, SDVTList VTL, EVT MemVT, SDValue Chain, SDValue Ptr, SDValue Cmp, SDValue Swp, MachineMemOperand *MMO, AtomicOrdering Ordering, SynchronizationScope SynchScope)
AtomicSDNode (unsigned Opc, unsigned Order, DebugLoc dl, SDVTList VTL, EVT MemVT, SDValue Chain, SDValue Ptr, SDValue Val, MachineMemOperand *MMO, AtomicOrdering Ordering, SynchronizationScope SynchScope)
AtomicSDNode (unsigned Opc, unsigned Order, DebugLoc dl, SDVTList VTL, EVT MemVT, SDValue Chain, SDValue Ptr, MachineMemOperand *MMO, AtomicOrdering Ordering, SynchronizationScope SynchScope)
AtomicSDNode (unsigned Opc, unsigned Order, DebugLoc dl, SDVTList VTL, EVT MemVT, const SDValue *AllOps, SDUse *DynOps, unsigned NumOps, MachineMemOperand *MMO, AtomicOrdering SuccessOrdering, AtomicOrdering FailureOrdering, SynchronizationScope SynchScope)
const SDValue & getBasePtr () const
const SDValue & getVal () const
AtomicOrdering getSuccessOrdering () const
AtomicOrdering getFailureOrdering () const
bool isCompareAndSwap () const
Static Public Member Functions
static bool classof (const SDNode *N)
Detailed Description
This is an SDNode representing atomic operations.
Definition at line 1207 of file SelectionDAGNodes.h.
Constructor & Destructor Documentation
llvm::AtomicSDNode::AtomicSDNode (unsigned Opc, unsigned Order, DebugLoc dl, SDVTList VTL, EVT MemVT, SDValue Chain, SDValue Ptr, SDValue Cmp, SDValue Swp, MachineMemOperand * MMO, AtomicOrdering Ordering, SynchronizationScope SynchScope) [inline]
Definition at line 1243 of file SelectionDAGNodes.h.
References llvm::SDNode::InitOperands().
llvm::AtomicSDNode::AtomicSDNode (unsigned Opc, unsigned Order, DebugLoc dl, SDVTList VTL, EVT MemVT, SDValue Chain, SDValue Ptr, SDValue Val, MachineMemOperand * MMO, AtomicOrdering Ordering, SynchronizationScope SynchScope) [inline]
Definition at line 1251 of file SelectionDAGNodes.h.
References llvm::SDNode::InitOperands().
llvm::AtomicSDNode::AtomicSDNode (unsigned Opc, unsigned Order, DebugLoc dl, SDVTList VTL, EVT MemVT, SDValue Chain, SDValue Ptr, MachineMemOperand * MMO, AtomicOrdering Ordering, SynchronizationScope SynchScope) [inline]
Definition at line 1260 of file SelectionDAGNodes.h.
References llvm::SDNode::InitOperands().
llvm::AtomicSDNode::AtomicSDNode (unsigned Opc, unsigned Order, DebugLoc dl, SDVTList VTL, EVT MemVT, const SDValue * AllOps, SDUse * DynOps, unsigned NumOps, MachineMemOperand * MMO, AtomicOrdering SuccessOrdering, AtomicOrdering FailureOrdering, SynchronizationScope SynchScope) [inline]
Definition at line 1269 of file SelectionDAGNodes.h.
References llvm::array_lengthof(), and llvm::SDNode::InitOperands().
Member Function Documentation
static bool llvm::AtomicSDNode::classof (const SDNode * N) [inline, static]
Reimplemented from llvm::MemSDNode.
Definition at line 1300 of file SelectionDAGNodes.h.
References llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_CMP_SWAP_WITH_SUCCESS, llvm::ISD::ATOMIC_LOAD, llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_MAX, llvm::ISD::ATOMIC_LOAD_MIN, llvm::ISD::ATOMIC_LOAD_NAND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, llvm::ISD::ATOMIC_LOAD_UMAX, llvm::ISD::ATOMIC_LOAD_UMIN, llvm::ISD::ATOMIC_LOAD_XOR, llvm::ISD::ATOMIC_STORE, llvm::ISD::ATOMIC_SWAP, and llvm::SDNode::getOpcode().
const SDValue& llvm::AtomicSDNode::getBasePtr () const [inline]
Reimplemented from llvm::MemSDNode.
Definition at line 1281 of file SelectionDAGNodes.h.
References llvm::SDNode::getOperand().
AtomicOrdering llvm::AtomicSDNode::getFailureOrdering () const [inline]
Definition at line 1290 of file SelectionDAGNodes.h.
AtomicOrdering llvm::AtomicSDNode::getSuccessOrdering () const [inline]
Definition at line 1284 of file SelectionDAGNodes.h.
References llvm::MemSDNode::getOrdering().
const SDValue& llvm::AtomicSDNode::getVal () const [inline]
Definition at line 1282 of file SelectionDAGNodes.h.
References llvm::SDNode::getOperand().
bool llvm::AtomicSDNode::isCompareAndSwap () const [inline]
Definition at line 1294 of file SelectionDAGNodes.h.
References llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_CMP_SWAP_WITH_SUCCESS, and llvm::SDNode::getOpcode().
The documentation for this class was generated from the following file:
SelectionDAGNodes.h