LLVM: llvm::SparcInstPrinter Class Reference
llvm::SparcInstPrinter Class Reference
#include <SparcInstPrinter.h>
Public Member Functions
SparcInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printRegName (raw_ostream &OS, unsigned RegNo) const override
Print the assembler register name.
void printInst (const MCInst *MI, raw_ostream &O, StringRef Annot, const MCSubtargetInfo &STI) override
Print the specified MCInst to the specified raw_ostream.
bool printSparcAliasInstr (const MCInst *MI, const MCSubtargetInfo &STI, raw_ostream &OS)
bool isV9 (const MCSubtargetInfo &STI) const
void printInstruction (const MCInst *MI, const MCSubtargetInfo &STI, raw_ostream &O)
bool printAliasInstr (const MCInst *MI, const MCSubtargetInfo &STI, raw_ostream &O)
void printCustomAliasOperand (const MCInst *MI, unsigned OpIdx, unsigned PrintMethodIdx, const MCSubtargetInfo &STI, raw_ostream &O)
void printOperand (const MCInst *MI, int opNum, const MCSubtargetInfo &STI, raw_ostream &OS)
void printMemOperand (const MCInst *MI, int opNum, const MCSubtargetInfo &STI, raw_ostream &OS, const char *Modifier=nullptr)
void printCCOperand (const MCInst *MI, int opNum, const MCSubtargetInfo &STI, raw_ostream &OS)
bool printGetPCX (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &OS)
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo)
Detailed Description
Definition at line 24 of file SparcInstPrinter.h.
Constructor & Destructor Documentation
llvm::SparcInstPrinter::SparcInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) [inline]
Definition at line 26 of file SparcInstPrinter.h.
Member Function Documentation
static const char* llvm::SparcInstPrinter::getRegisterName (unsigned RegNo) [static]
Referenced by llvm::SparcTargetAsmStreamer::emitSparcRegisterIgnore(), and llvm::SparcTargetAsmStreamer::emitSparcRegisterScratch().
bool SparcInstPrinter::isV9 (const MCSubtargetInfo & STI) const
Definition at line 37 of file SparcInstPrinter.cpp.
References llvm::MCSubtargetInfo::getFeatureBits().
bool llvm::SparcInstPrinter::printAliasInstr (const MCInst * MI, const MCSubtargetInfo & STI, raw_ostream & O)
void SparcInstPrinter::printCCOperand (const MCInst * MI, int opNum, const MCSubtargetInfo & STI, raw_ostream & OS)
Definition at line 149 of file SparcInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), and llvm::SPARCCondCodeToString().
void llvm::SparcInstPrinter::printCustomAliasOperand (const MCInst * MI, unsigned OpIdx, unsigned PrintMethodIdx, const MCSubtargetInfo & STI, raw_ostream & O)
bool SparcInstPrinter::printGetPCX (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & OS)
Definition at line 173 of file SparcInstPrinter.cpp.
References llvm_unreachable.
void SparcInstPrinter::printInst (const MCInst * MI, raw_ostream & OS, StringRef Annot, const MCSubtargetInfo & STI) [override, virtual]
Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Definition at line 46 of file SparcInstPrinter.cpp.
void llvm::SparcInstPrinter::printInstruction (const MCInst * MI, const MCSubtargetInfo & STI, raw_ostream & O)
void SparcInstPrinter::printMemOperand (const MCInst * MI, int opNum, const MCSubtargetInfo & STI, raw_ostream & OS, const char * Modifier = nullptr)
Definition at line 126 of file SparcInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and printOperand().
void SparcInstPrinter::printOperand (const MCInst * MI, int opNum, const MCSubtargetInfo & STI, raw_ostream & OS)
Definition at line 107 of file SparcInstPrinter.cpp.
References llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and llvm::MCExpr::print().
void SparcInstPrinter::printRegName (raw_ostream & OS, unsigned RegNo) const [override, virtual]
Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 41 of file SparcInstPrinter.cpp.
References llvm::StringRef::lower().
bool SparcInstPrinter::printSparcAliasInstr (const MCInst * MI, const MCSubtargetInfo & STI, raw_ostream & OS)
Definition at line 53 of file SparcInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and printOperand().
The documentation for this class was generated from the following files:
SparcInstPrinter.h
SparcInstPrinter.cpp