LLVM: llvm::MCLEBFragment Class Reference
llvm::MCLEBFragment Class Reference
#include <MCAssembler.h>
Public Member Functions
MCLEBFragment (const MCExpr &Value_, bool IsSigned_, MCSection *Sec=nullptr)
Accessors
const MCExpr & getValue () const
bool isSigned () const
SmallString< 8 > & getContents ()
const SmallString< 8 > & getContents () const
Static Public Member Functions
static bool classof (const MCFragment *F)
Detailed Description
Definition at line 396 of file MCAssembler.h.
Constructor & Destructor Documentation
llvm::MCLEBFragment::MCLEBFragment (const MCExpr & Value_, bool IsSigned_, MCSection * Sec = nullptr) [inline]
Definition at line 407 of file MCAssembler.h.
References llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Member Function Documentation
static bool llvm::MCLEBFragment::classof (const MCFragment * F) [inline, static]
Definition at line 424 of file MCAssembler.h.
References llvm::MCFragment::FT_LEB, and llvm::MCFragment::getKind().
SmallString<8>& llvm::MCLEBFragment::getContents () [inline]
Definition at line 419 of file MCAssembler.h.
Referenced by writeFragment().
const SmallString<8>& llvm::MCLEBFragment::getContents () const [inline]
Definition at line 420 of file MCAssembler.h.
const MCExpr& llvm::MCLEBFragment::getValue () const [inline]
Definition at line 415 of file MCAssembler.h.
Referenced by llvm::MCFragment::dump().
bool llvm::MCLEBFragment::isSigned () const [inline]
Definition at line 417 of file MCAssembler.h.
Referenced by llvm::MCFragment::dump().
The documentation for this class was generated from the following file:
MCAssembler.h