LLVM: llvm::MaskedLoadStoreSDNode Class Reference
llvm::MaskedLoadStoreSDNode Class Reference
This base class is used to represent MLOAD and MSTORE nodes.
#include <SelectionDAGNodes.h>
Public Member Functions
MaskedLoadStoreSDNode (ISD::NodeType NodeTy, unsigned Order, DebugLoc dl, SDValue *Operands, unsigned numOperands, SDVTList VTs, EVT MemVT, MachineMemOperand *MMO)
const SDValue & getBasePtr () const
const SDValue & getMask () const
Static Public Member Functions
static bool classof (const SDNode *N)
Friends
class SelectionDAG
Detailed Description
This base class is used to represent MLOAD and MSTORE nodes.
Definition at line 1983 of file SelectionDAGNodes.h.
Constructor & Destructor Documentation
llvm::MaskedLoadStoreSDNode::MaskedLoadStoreSDNode (ISD::NodeType NodeTy, unsigned Order, DebugLoc dl, SDValue * Operands, unsigned numOperands, SDVTList VTs, EVT MemVT, MachineMemOperand * MMO) [inline]
Definition at line 1988 of file SelectionDAGNodes.h.
References llvm::SDNode::InitOperands().
Member Function Documentation
static bool llvm::MaskedLoadStoreSDNode::classof (const SDNode * N) [inline, static]
Reimplemented from llvm::MemSDNode.
Reimplemented in llvm::MaskedStoreSDNode, and llvm::MaskedLoadSDNode.
Definition at line 2002 of file SelectionDAGNodes.h.
References llvm::SDNode::getOpcode(), llvm::ISD::MLOAD, and llvm::ISD::MSTORE.
const SDValue& llvm::MaskedLoadStoreSDNode::getBasePtr () const [inline]
Reimplemented from llvm::MemSDNode.
Definition at line 1999 of file SelectionDAGNodes.h.
References llvm::SDNode::getOperand().
Referenced by PerformMLOADCombine(), and PerformMSTORECombine().
const SDValue& llvm::MaskedLoadStoreSDNode::getMask () const [inline]
Definition at line 2000 of file SelectionDAGNodes.h.
References llvm::SDNode::getOperand().
Referenced by PerformMLOADCombine(), and PerformMSTORECombine().
Friends And Related Function Documentation
friend class SelectionDAG [friend]
Reimplemented from llvm::SDNode.
Reimplemented in llvm::MaskedStoreSDNode, and llvm::MaskedLoadSDNode.
Definition at line 1987 of file SelectionDAGNodes.h.
The documentation for this class was generated from the following file:
SelectionDAGNodes.h