LLVM: llvm::BitCodeAbbrev Class Reference
llvm::BitCodeAbbrev Class Reference
BitCodeAbbrev - This class represents an abbreviation record.
#include <BitCodes.h>
Public Member Functions
unsigned getNumOperandInfos () const
const BitCodeAbbrevOp & getOperandInfo (unsigned N) const
void Add (const BitCodeAbbrevOp &OpInfo)
Friends
class RefCountedBase< BitCodeAbbrev >
Detailed Description
BitCodeAbbrev - This class represents an abbreviation record.
An abbreviation allows a complex record that has redundancy to be stored in a specialized format instead of the fully-general, fully-vbr, format.
Definition at line 165 of file BitCodes.h.
Member Function Documentation
void llvm::BitCodeAbbrev::Add (const BitCodeAbbrevOp & OpInfo) [inline]
Definition at line 179 of file BitCodes.h.
References llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by llvm::BitstreamCursor::ReadAbbrevRecord(), WriteBlockInfo(), WriteConstants(), WriteModuleInfo(), WriteModuleMetadata(), and WriteTypeTable().
unsigned llvm::BitCodeAbbrev::getNumOperandInfos () const [inline]
Definition at line 172 of file BitCodes.h.
References llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::BitstreamCursor::ReadAbbrevRecord(), llvm::BitstreamCursor::readRecord(), and llvm::BitstreamCursor::skipRecord().
const BitCodeAbbrevOp& llvm::BitCodeAbbrev::getOperandInfo (unsigned N) const [inline]
Definition at line 175 of file BitCodes.h.
Referenced by llvm::BitstreamCursor::readRecord(), and llvm::BitstreamCursor::skipRecord().
Friends And Related Function Documentation
friend class RefCountedBase< BitCodeAbbrev > [friend]
Definition at line 169 of file BitCodes.h.
The documentation for this class was generated from the following file:
BitCodes.h