LLVM: llvm::MCAlignFragment Class Reference
llvm::MCAlignFragment Class Reference
#include <MCAssembler.h>
Public Member Functions
MCAlignFragment (unsigned Alignment, int64_t Value, unsigned ValueSize, unsigned MaxBytesToEmit, MCSection *Sec=nullptr)
Accessors
unsigned getAlignment () const
int64_t getValue () const
unsigned getValueSize () const
unsigned getMaxBytesToEmit () const
bool hasEmitNops () const
void setEmitNops (bool Value)
Static Public Member Functions
static bool classof (const MCFragment *F)
Detailed Description
Definition at line 285 of file MCAssembler.h.
Constructor & Destructor Documentation
llvm::MCAlignFragment::MCAlignFragment (unsigned Alignment, int64_t Value, unsigned ValueSize, unsigned MaxBytesToEmit, MCSection * Sec = nullptr) [inline]
Definition at line 306 of file MCAssembler.h.
Member Function Documentation
static bool llvm::MCAlignFragment::classof (const MCFragment * F) [inline, static]
Definition at line 328 of file MCAssembler.h.
References llvm::MCFragment::FT_Align, and llvm::MCFragment::getKind().
unsigned llvm::MCAlignFragment::getAlignment () const [inline]
Definition at line 315 of file MCAssembler.h.
Referenced by llvm::MCAssembler::computeFragmentSize(), and llvm::MCFragment::dump().
unsigned llvm::MCAlignFragment::getMaxBytesToEmit () const [inline]
Definition at line 321 of file MCAssembler.h.
Referenced by llvm::MCAssembler::computeFragmentSize(), and llvm::MCFragment::dump().
int64_t llvm::MCAlignFragment::getValue () const [inline]
Definition at line 317 of file MCAssembler.h.
Referenced by llvm::MCFragment::dump(), and writeFragment().
unsigned llvm::MCAlignFragment::getValueSize () const [inline]
Definition at line 319 of file MCAssembler.h.
Referenced by llvm::MCFragment::dump(), and writeFragment().
bool llvm::MCAlignFragment::hasEmitNops () const [inline]
Definition at line 323 of file MCAssembler.h.
Referenced by llvm::MCAssembler::computeFragmentSize(), llvm::MCFragment::dump(), and writeFragment().
void llvm::MCAlignFragment::setEmitNops (bool Value) [inline]
Definition at line 324 of file MCAssembler.h.
The documentation for this class was generated from the following file:
MCAssembler.h