LLVM: llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy > Class Template Reference
llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy > Class Template Reference
#include <CallSite.h>
Public Types
typedef IterTy arg_iterator
arg_iterator - The type of iterator to use when looping over actual arguments at this call site.
Public Member Functions
bool isCall () const
isCall - true if a CallInst is enclosed.
bool isInvoke () const
isInvoke - true if a InvokeInst is enclosed.
InstrTy * getInstruction () const
InstrTy * operator-> () const
operator bool () const
ValTy * getCalledValue () const
getCalledValue - Return the pointer to function that is being called.
FunTy * getCalledFunction () const
getCalledFunction - Return the function being called if this is a direct call, otherwise return null (if it's an indirect call).
void setCalledFunction (Value *V)
setCalledFunction - Set the callee to the specified value.
bool isCallee (Value::const_user_iterator UI) const
isCallee - Determine whether the passed iterator points to the callee operand's Use.
bool isCallee (const Use *U) const
Determine whether this Use is the callee operand's Use.
ValTy * getArgument (unsigned ArgNo) const
void setArgument (unsigned ArgNo, Value *newVal)
unsigned getArgumentNo (Value::const_user_iterator I) const
Given a value use iterator, returns the argument that corresponds to it.
unsigned getArgumentNo (const Use *U) const
Given a use for an argument, get the argument number that corresponds to it.
IterTy arg_begin () const
arg_begin/arg_end - Return iterators corresponding to the actual argument list for a call site.
IterTy arg_end () const
iterator_range< IterTy > args () const
bool arg_empty () const
unsigned arg_size () const
Type * getType () const
getType - Return the type of the instruction that generated this call site
FunTy * getCaller () const
getCaller - Return the caller function for this call site
bool isMustTailCall () const
Tests if this call site must be tail call optimized.
bool isTailCall () const
Tests if this call site is marked as a tail call.
CallingConv::ID getCallingConv () const
getCallingConv/setCallingConv - get or set the calling convention of the call.
void setCallingConv (CallingConv::ID CC)
FunctionType * getFunctionType () const
void mutateFunctionType (FunctionType *Ty) const
const AttributeSet & getAttributes () const
getAttributes/setAttributes - get or set the parameter attributes of the call.
void setAttributes (const AttributeSet &PAL)
bool hasFnAttr (Attribute::AttrKind A) const
Return true if this function has the given attribute.
bool paramHasAttr (unsigned i, Attribute::AttrKind A) const
Return true if the call or the callee has the given attribute.
uint16_t getParamAlignment (uint16_t i) const
Extract the alignment for a call or parameter (0=unknown).
uint64_t getDereferenceableBytes (uint16_t i) const
Extract the number of dereferenceable bytes for a call or parameter (0=unknown).
uint64_t getDereferenceableOrNullBytes (uint16_t i) const
Extract the number of dereferenceable_or_null bytes for a call or parameter (0=unknown).
bool isNoBuiltin () const
Return true if the call should not be treated as a call to a builtin.
bool isNoInline () const
Return true if the call should not be inlined.
void setIsNoInline (bool Value=true)
bool doesNotAccessMemory () const
Determine if the call does not access memory.
void setDoesNotAccessMemory ()
bool onlyReadsMemory () const
Determine if the call does not access or only reads memory.
void setOnlyReadsMemory ()
bool doesNotReturn () const
Determine if the call cannot return.
void setDoesNotReturn ()
bool doesNotThrow () const
Determine if the call cannot unwind.
void setDoesNotThrow ()
bool doesNotCapture (unsigned ArgNo) const
Determine whether this argument is not captured.
bool isByValArgument (unsigned ArgNo) const
Determine whether this argument is passed by value.
bool isInAllocaArgument (unsigned ArgNo) const
Determine whether this argument is passed in an alloca.
bool isByValOrInAllocaArgument (unsigned ArgNo) const
Determine whether this argument is passed by value or in an alloca.
bool hasInAllocaArgument () const
Determine if there are is an inalloca argument.
bool doesNotAccessMemory (unsigned ArgNo) const
bool onlyReadsMemory (unsigned ArgNo) const
bool isReturnNonNull () const
Return true if the return value is known to be not null.
bool hasArgument (const Value *Arg) const
hasArgument - Returns true if this CallSite passes the given Value* as an argument to the called function.
Protected Member Functions
CallSiteBase ()
CallSiteBase (CallTy *CI)
CallSiteBase (InvokeTy *II)
CallSiteBase (ValTy *II)
Protected Attributes
PointerIntPair< InstrTy
*, 1, bool > I
Detailed Description
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator>
class llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >
Definition at line 47 of file CallSite.h.
Member Typedef Documentation
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> typedef IterTy llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_iterator
arg_iterator - The type of iterator to use when looping over actual arguments at this call site.
Definition at line 143 of file CallSite.h.
Constructor & Destructor Documentation
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::CallSiteBase () [inline, protected]
Definition at line 51 of file CallSite.h.
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::CallSiteBase (CallTy * CI) [inline, protected]
Definition at line 52 of file CallSite.h.
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::CallSiteBase (InvokeTy * II) [inline, protected]
Definition at line 53 of file CallSite.h.
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::CallSiteBase (ValTy * II) [inline, explicit, protected]
Definition at line 54 of file CallSite.h.
Member Function Documentation
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> IterTy llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_begin () const [inline]
arg_begin/arg_end - Return iterators corresponding to the actual argument list for a call site.
Definition at line 147 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::arg_empty(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::arg_size(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::args(), llvm::AliasAnalysis::callCapturesBefore(), llvm::objcarc::CanAlterRefCount(), determinePointerReadAttrs(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getArgument(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getArgumentNo(), llvm::GCRelocateOperands::getBasePtr(), llvm::objcarc::GetCallSiteClass(), llvm::GCRelocateOperands::getDerivedPtr(), llvm::AliasAnalysis::getModRefInfo(), HandleCallsInBlockInlinedThroughInvoke(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::hasArgument(), llvm::InlineFunction(), llvm::FastISel::lowerCall(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::IntrinsicLowering::LowerIntrinsicCall(), makeStatepointExplicitImpl(), llvm::PointerMayBeCaptured(), ReplaceFPIntrinsicWithCall(), ReplaceWithStatepoint(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::setArgument(), llvm::SimplifyInstruction(), and llvm::Interpreter::visitCallSite().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_empty () const [inline]
Definition at line 157 of file CallSite.h.
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> IterTy llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_end () const [inline]
Definition at line 153 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::arg_empty(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::arg_size(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::args(), llvm::AliasAnalysis::callCapturesBefore(), llvm::objcarc::CanAlterRefCount(), determinePointerReadAttrs(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getArgument(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getArgumentNo(), llvm::objcarc::GetCallSiteClass(), llvm::AliasAnalysis::getModRefInfo(), HandleCallsInBlockInlinedThroughInvoke(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::hasArgument(), llvm::FastISel::lowerCall(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::IntrinsicLowering::LowerIntrinsicCall(), makeStatepointExplicitImpl(), llvm::PointerMayBeCaptured(), ReplaceFPIntrinsicWithCall(), ReplaceWithStatepoint(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::setArgument(), llvm::SimplifyInstruction(), and llvm::Interpreter::visitCallSite().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> unsigned llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_size () const [inline]
Definition at line 158 of file CallSite.h.
Referenced by addStackMapLiveVars(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::hasInAllocaArgument(), llvm::InlineFunction(), llvm::FastISel::lowerCall(), llvm::SelectionDAGBuilder::LowerCallTo(), matchOutlinedFinallyCall(), OptimizeAwayTrappingUsesOfValue(), and llvm::Interpreter::visitCallSite().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> iterator_range<IterTy> llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::args () const [inline]
Definition at line 154 of file CallSite.h.
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::doesNotAccessMemory () const [inline]
Determine if the call does not access memory.
Definition at line 260 of file CallSite.h.
Referenced by llvm::AliasAnalysis::callCapturesBefore(), determinePointerReadAttrs(), and llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::doesNotAccessMemory().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::doesNotAccessMemory (unsigned ArgNo) const [inline]
Definition at line 321 of file CallSite.h.
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::doesNotCapture (unsigned ArgNo) const [inline]
Determine whether this argument is not captured.
Definition at line 295 of file CallSite.h.
Referenced by llvm::AliasAnalysis::callCapturesBefore(), determinePointerReadAttrs(), and llvm::PointerMayBeCaptured().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::doesNotReturn () const [inline]
Determine if the call cannot return.
Definition at line 276 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::doesNotReturn(), llvm::FastISel::CallLoweringInfo::setCallee(), and llvm::TargetLowering::CallLoweringInfo::setCallee().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::doesNotThrow () const [inline]
Determine if the call cannot unwind.
Definition at line 284 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::doesNotThrow(), llvm::InlineFunction(), and llvm::PointerMayBeCaptured().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> ValTy* llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getArgument (unsigned ArgNo) const [inline]
Definition at line 115 of file CallSite.h.
Referenced by AddAlignmentAssumptions(), addStackMapLiveVars(), AllCallersPassInValidPointerForArgument(), llvm::GCRelocateOperands::getBasePtrIndex(), llvm::GCRelocateOperands::getDerivedPtrIndex(), llvm::MemoryLocation::getForArgument(), llvm::GCRelocateOperands::getStatepoint(), getStoredPointerOperand(), llvm::GCRelocateOperands::isTiedToInvoke(), llvm::PatternMatch::Argument_match< Opnd_t >::match(), matchOutlinedFinallyCall(), OptimizeAwayTrappingUsesOfValue(), llvm::TargetLowering::ParseConstraints(), llvm::ObjectSizeOffsetVisitor::visitCallSite(), and llvm::ObjectSizeOffsetEvaluator::visitCallSite().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> unsigned llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getArgumentNo (Value::const_user_iterator I) const [inline]
Given a value use iterator, returns the argument that corresponds to it.
Iterator must actually correspond to an argument.
Definition at line 128 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getArgumentNo().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> unsigned llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getArgumentNo (const Use * U) const [inline]
Given a use for an argument, get the argument number that corresponds to it.
Definition at line 134 of file CallSite.h.
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> const AttributeSet& llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getAttributes () const [inline]
getAttributes/setAttributes - get or set the parameter attributes of the call.
Definition at line 211 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getAttributes(), LLVMAddInstrAttribute(), LLVMRemoveInstrAttribute(), LLVMSetInstrParamAlignment(), RemoveNestAttribute(), and ReplaceWithStatepoint().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> FunTy* llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCalledFunction () const [inline]
getCalledFunction - Return the function being called if this is a direct call, otherwise return null (if it's an indirect call).
Definition at line 95 of file CallSite.h.
Referenced by AddAliasScopeMetadata(), AddAlignmentAssumptions(), llvm::CallGraphNode::addCalledFunction(), llvm::CodeMetrics::analyzeBasicBlock(), CloneAliasScopeMetadata(), determinePointerReadAttrs(), getCalledFunction(), llvm::MemoryLocation::getForArgument(), llvm::InlineCostAnalysis::getInlineCost(), llvm::Inliner::getInlineThreshold(), llvm::AliasAnalysis::getModRefBehavior(), llvm::LibCallAliasAnalysis::getModRefInfo(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getUnrollingPreferences(), InlineCallIfPossible(), llvm::InlineFunction(), llvm::InlineCostAnalysis::isInlineViable(), llvm::isStatepoint(), makeStatepointExplicitImpl(), llvm::Inliner::runOnSCC(), UpdateCallGraphAfterInlining(), and llvm::Interpreter::visitCallSite().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> ValTy* llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCalledValue () const [inline]
getCalledValue - Return the pointer to function that is being called.
Definition at line 87 of file CallSite.h.
Referenced by llvm::CodeMetrics::analyzeBasicBlock(), analyzeParsePointLiveness(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getCalledFunction(), llvm::FastISel::lowerCall(), llvm::FastISel::lowerCallTo(), llvm::SelectionDAGBuilder::LowerCallTo(), OptimizeAwayTrappingUsesOfValue(), llvm::TargetLowering::ParseConstraints(), PrepareCall(), ReplaceWithStatepoint(), llvm::FunctionLoweringInfo::set(), llvm::FastISel::CallLoweringInfo::setCallee(), llvm::SimplifyInstruction(), and llvm::Interpreter::visitCallSite().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> FunTy* llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCaller () const [inline]
getCaller - Return the caller function for this call site
Definition at line 166 of file CallSite.h.
Referenced by AddAlignmentAssumptions(), emitAnalysis(), llvm::InlineCostAnalysis::getInlineCost(), llvm::Inliner::getInlineThreshold(), InlineCallIfPossible(), and llvm::Inliner::runOnSCC().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> CallingConv::ID llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCallingConv () const [inline]
getCallingConv/setCallingConv - get or set the calling convention of the call.
Definition at line 194 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getCallingConv(), llvm::SelectionDAGBuilder::lowerCallOperands(), llvm::FastISel::CallLoweringInfo::setCallee(), and llvm::TargetLowering::CallLoweringInfo::setCallee().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> uint64_t llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getDereferenceableBytes (uint16_t i) const [inline]
Extract the number of dereferenceable bytes for a call or parameter (0=unknown).
Definition at line 235 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getDereferenceableBytes(), and llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::isReturnNonNull().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> uint64_t llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getDereferenceableOrNullBytes (uint16_t i) const [inline]
Extract the number of dereferenceable_or_null bytes for a call or parameter (0=unknown).
Definition at line 241 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getDereferenceableOrNullBytes().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> FunctionType* llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getFunctionType () const [inline]
Definition at line 201 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getFunctionType().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> InstrTy* llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getInstruction () const [inline]
Definition at line 81 of file CallSite.h.
Referenced by AddAlignmentAssumptions(), llvm::CallGraphNode::addCalledFunction(), analyzeParsePointLiveness(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::arg_begin(), llvm::AliasAnalysis::callCapturesBefore(), CloneAliasScopeMetadata(), doesNotRequireEntrySafepointBefore(), emitAnalysis(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getArgumentNo(), getCalledFunction(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getCalledValue(), llvm::MemoryLocation::getForArgument(), llvm::MemoryDependenceAnalysis::getNonLocalCallDependency(), llvm::NVPTXTargetLowering::getPrototype(), llvm::InlineFunction(), insertParsePoints(), insertUseHolderAfter(), isAssumeIntrinsic(), llvm::isGCRelocate(), llvm::isGCResult(), llvm::InlineCostAnalysis::isInlineViable(), llvm::isInTailCallPosition(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::isInvoke(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::isMustTailCall(), llvm::isStatepoint(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::isTailCall(), llvm::FastISel::lowerCallTo(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::TargetLowering::LowerCallTo(), lowerStatepointMetaArgs(), makeStatepointExplicit(), makeStatepointExplicitImpl(), needsStatepoint(), llvm::CallSite::operator<(), PrintModRefResults(), recomputeLiveInValues(), rematerializeLiveValues(), llvm::CallGraphNode::removeCallEdgeFor(), llvm::CallGraphNode::replaceCallEdge(), ReplaceWithStatepoint(), llvm::Inliner::runOnSCC(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::setArgument(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::setCalledFunction(), llvm::FastISel::CallLoweringInfo::setCallee(), llvm::TargetLowering::CallLoweringInfo::setCallee(), UpdateCallGraphAfterInlining(), llvm::Interpreter::visitCallSite(), llvm::ObjectSizeOffsetVisitor::visitCallSite(), llvm::InstVisitor< ObjectSizeOffsetVisitor, SizeOffsetType >::visitCallSite(), llvm::ObjectSizeOffsetEvaluator::visitCallSite(), and llvm::PtrUseVisitor< SliceBuilder >::visitCallSite().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> uint16_t llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getParamAlignment (uint16_t i) const [inline]
Extract the alignment for a call or parameter (0=unknown).
Definition at line 229 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getParamAlignment(), llvm::FastISel::ArgListEntry::setAttributes(), and llvm::TargetLowering::ArgListEntry::setAttributes().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> Type* llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getType () const [inline]
getType - Return the type of the instruction that generated this call site
Definition at line 162 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::isReturnNonNull(), llvm::TargetLowering::ParseConstraints(), and ReplaceWithStatepoint().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::hasArgument (const Value * Arg) const [inline]
hasArgument - Returns true if this CallSite passes the given Value* as an argument to the called function.
Definition at line 345 of file CallSite.h.
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::hasFnAttr (Attribute::AttrKind A) const [inline]
Return true if this function has the given attribute.
Definition at line 219 of file CallSite.h.
Referenced by llvm::Function::callsFunctionThatReturnsTwice(), llvm::InlineCostAnalysis::getInlineCost(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::hasFnAttr(), and hasReturnsTwiceAttr().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::hasInAllocaArgument () const [inline]
Determine if there are is an inalloca argument.
Only the last argument can have the inalloca attribute.
Definition at line 317 of file CallSite.h.
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isByValArgument (unsigned ArgNo) const [inline]
Determine whether this argument is passed by value.
Definition at line 300 of file CallSite.h.
Referenced by llvm::AliasAnalysis::callCapturesBefore(), and llvm::InlineFunction().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isByValOrInAllocaArgument (unsigned ArgNo) const [inline]
Determine whether this argument is passed by value or in an alloca.
Definition at line 310 of file CallSite.h.
Referenced by isSafeToEliminateVarargsCast().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isCall () const [inline]
isCall - true if a CallInst is enclosed.
Note that !isCall() does not mean it is an InvokeInst enclosed, it also could signify a NULL Instruction pointer.
Definition at line 75 of file CallSite.h.
Referenced by insertUseHolderAfter(), llvm::InlineCostAnalysis::isInlineViable(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::isMustTailCall(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::isTailCall(), makeStatepointExplicitImpl(), llvm::PatternMatch::Argument_match< Opnd_t >::match(), needsStatepoint(), rematerializeLiveValues(), ReplaceWithStatepoint(), and llvm::InstVisitor< ObjectSizeOffsetVisitor, SizeOffsetType >::visitCallSite().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isCallee (Value::const_user_iterator UI) const [inline]
isCallee - Determine whether the passed iterator points to the callee operand's Use.
Definition at line 108 of file CallSite.h.
Referenced by AddressIsTaken(), and llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::isCallee().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isCallee (const Use * U) const [inline]
Determine whether this Use is the callee operand's Use.
Definition at line 113 of file CallSite.h.
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isInAllocaArgument (unsigned ArgNo) const [inline]
Determine whether this argument is passed in an alloca.
Definition at line 305 of file CallSite.h.
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isInvoke () const [inline]
isInvoke - true if a InvokeInst is enclosed.
Definition at line 79 of file CallSite.h.
Referenced by lowerStatepointMetaArgs(), rematerializeLiveValues(), ReplaceWithStatepoint(), and llvm::InstVisitor< ObjectSizeOffsetVisitor, SizeOffsetType >::visitCallSite().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isMustTailCall () const [inline]
Tests if this call site must be tail call optimized.
Only a CallInst can be tail call optimized.
Definition at line 170 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::isMustTailCall().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isNoBuiltin () const [inline]
Return true if the call should not be treated as a call to a builtin.
Definition at line 247 of file CallSite.h.
Referenced by getCalledFunction(), and llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::isNoBuiltin().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isNoInline () const [inline]
Return true if the call should not be inlined.
Definition at line 252 of file CallSite.h.
Referenced by llvm::CodeMetrics::analyzeBasicBlock(), llvm::InlineCostAnalysis::getInlineCost(), and llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::isNoInline().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isReturnNonNull () const [inline]
Return true if the return value is known to be not null.
This may be because it has the nonnull attribute, or because at least one byte is dereferenceable and the pointer is in addrspace(0).
Definition at line 333 of file CallSite.h.
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isTailCall () const [inline]
Tests if this call site is marked as a tail call.
Definition at line 175 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::isTailCall().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> void llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::mutateFunctionType (FunctionType * Ty) const [inline]
Definition at line 205 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::mutateFunctionType().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::onlyReadsMemory () const [inline]
Determine if the call does not access or only reads memory.
Definition at line 268 of file CallSite.h.
Referenced by llvm::AliasAnalysis::callCapturesBefore(), determinePointerReadAttrs(), llvm::objcarc::GetCallSiteClass(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::onlyReadsMemory(), and llvm::PointerMayBeCaptured().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::onlyReadsMemory (unsigned ArgNo) const [inline]
Definition at line 325 of file CallSite.h.
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::operator bool () const [inline, explicit]
Definition at line 83 of file CallSite.h.
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> InstrTy* llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::operator-> () const [inline]
Definition at line 82 of file CallSite.h.
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::paramHasAttr (unsigned i, Attribute::AttrKind A) const [inline]
Return true if the call or the callee has the given attribute.
Definition at line 224 of file CallSite.h.
Referenced by computeBytesPoppedByCallee(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::doesNotAccessMemory(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::doesNotCapture(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::hasInAllocaArgument(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::isByValArgument(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::isByValOrInAllocaArgument(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::isInAllocaArgument(), llvm::isNoAliasCall(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::isReturnNonNull(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::onlyReadsMemory(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::paramHasAttr(), llvm::FastISel::ArgListEntry::setAttributes(), llvm::TargetLowering::ArgListEntry::setAttributes(), llvm::FastISel::CallLoweringInfo::setCallee(), and llvm::TargetLowering::CallLoweringInfo::setCallee().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> void llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setArgument (unsigned ArgNo, Value * newVal) [inline]
Definition at line 120 of file CallSite.h.
Referenced by OptimizeAwayTrappingUsesOfValue().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> void llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setAttributes (const AttributeSet & PAL) [inline]
Definition at line 214 of file CallSite.h.
Referenced by LLVMAddInstrAttribute(), LLVMRemoveInstrAttribute(), LLVMSetInstrParamAlignment(), RemoveNestAttribute(), and llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::setAttributes().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> void llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setCalledFunction (Value * V) [inline]
setCalledFunction - Set the callee to the specified value.
Definition at line 101 of file CallSite.h.
Referenced by OptimizeAwayTrappingUsesOfValue().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> void llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setCallingConv (CallingConv::ID CC) [inline]
Definition at line 197 of file CallSite.h.
Referenced by ChangeCalleesToFastCall(), and llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::setCallingConv().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> void llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setDoesNotAccessMemory () [inline]
Definition at line 263 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::setDoesNotAccessMemory().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> void llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setDoesNotReturn () [inline]
Definition at line 279 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::setDoesNotReturn().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> void llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setDoesNotThrow () [inline]
Definition at line 287 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::setDoesNotThrow().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> void llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setIsNoInline (bool Value = true) [inline]
Definition at line 255 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::setIsNoInline().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> void llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setOnlyReadsMemory () [inline]
Definition at line 271 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::setOnlyReadsMemory().
Member Data Documentation
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> PointerIntPair<InstrTy*, 1, bool> llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::I [protected]
Definition at line 49 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getInstruction(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::isCall(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::isInvoke(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::operator bool(), llvm::CallSite::operator!=(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::operator->(), and llvm::CallSite::operator==().
The documentation for this class was generated from the following file:
CallSite.h