LLVM: llvm::MaskedLoadSDNode Class Reference
llvm::MaskedLoadSDNode Class Reference
This class is used to represent an MLOAD node.
#include <SelectionDAGNodes.h>
Public Member Functions
MaskedLoadSDNode (unsigned Order, DebugLoc dl, SDValue *Operands, unsigned numOperands, SDVTList VTs, ISD::LoadExtType ETy, EVT MemVT, MachineMemOperand *MMO)
ISD::LoadExtType getExtensionType () const
const SDValue & getSrc0 () const
Static Public Member Functions
static bool classof (const SDNode *N)
Friends
class SelectionDAG
Detailed Description
This class is used to represent an MLOAD node.
Definition at line 2009 of file SelectionDAGNodes.h.
Constructor & Destructor Documentation
llvm::MaskedLoadSDNode::MaskedLoadSDNode (unsigned Order, DebugLoc dl, SDValue * Operands, unsigned numOperands, SDVTList VTs, ISD::LoadExtType ETy, EVT MemVT, MachineMemOperand * MMO) [inline]
Definition at line 2012 of file SelectionDAGNodes.h.
References llvm::SDNode::SubclassData.
Member Function Documentation
static bool llvm::MaskedLoadSDNode::classof (const SDNode * N) [inline, static]
Reimplemented from llvm::MaskedLoadStoreSDNode.
Definition at line 2024 of file SelectionDAGNodes.h.
References llvm::SDNode::getOpcode(), and llvm::ISD::MLOAD.
ISD::LoadExtType llvm::MaskedLoadSDNode::getExtensionType () const [inline]
Definition at line 2020 of file SelectionDAGNodes.h.
References llvm::SDNode::SubclassData.
Referenced by PerformMLOADCombine().
const SDValue& llvm::MaskedLoadSDNode::getSrc0 () const [inline]
Definition at line 2023 of file SelectionDAGNodes.h.
References llvm::SDNode::getOperand().
Referenced by PerformMLOADCombine().
Friends And Related Function Documentation
friend class SelectionDAG [friend]
Reimplemented from llvm::MaskedLoadStoreSDNode.
Definition at line 2011 of file SelectionDAGNodes.h.
The documentation for this class was generated from the following file:
SelectionDAGNodes.h