LLVM: llvm::AMDGPUAsmPrinter Class Reference
llvm::AMDGPUAsmPrinter Class Reference
#include <AMDGPUAsmPrinter.h>
Classes
struct SIProgramInfo
Public Member Functions
AMDGPUAsmPrinter (TargetMachine &TM, std::unique_ptr< MCStreamer > Streamer)
bool runOnMachineFunction (MachineFunction &MF) override
Emit the specified function out to the OutStreamer.
const char * getPassName () const override
getPassName - Return a nice clean name for a pass.
void EmitInstruction (const MachineInstr *MI) override
Implemented in AMDGPUMCInstLower.cpp.
void EmitEndOfAsmFile (Module &M) override
This virtual method can be overridden by targets that want to emit something at the end of their file.
bool PrintAsmOperand (const MachineInstr *MI, unsigned OpNo, unsigned AsmVariant, const char *ExtraCode, raw_ostream &O) override
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
Protected Attributes
std::vector< std::string > DisasmLines
std::vector< std::string > HexLines
size_t DisasmLineMaxLen
Detailed Description
Definition at line 23 of file AMDGPUAsmPrinter.h.
Constructor & Destructor Documentation
AMDGPUAsmPrinter::AMDGPUAsmPrinter (TargetMachine & TM, std::unique_ptr< MCStreamer > Streamer) [explicit]
Definition at line 88 of file AMDGPUAsmPrinter.cpp.
Member Function Documentation
void AMDGPUAsmPrinter::EmitEndOfAsmFile (Module &) [override, virtual]
This virtual method can be overridden by targets that want to emit something at the end of their file.
Reimplemented from llvm::AsmPrinter.
Definition at line 92 of file AMDGPUAsmPrinter.cpp.
References END_OF_TEXT_LABEL_NAME, llvm::AsmPrinter::getObjFileLowering(), llvm::MCContext::getOrCreateSymbol(), llvm::MCObjectFileInfo::getTextSection(), llvm::AsmPrinter::OutContext, and llvm::AsmPrinter::OutStreamer.
void AMDGPUAsmPrinter::EmitInstruction (const MachineInstr * MI) [override, virtual]
Implemented in AMDGPUMCInstLower.cpp.
Reimplemented from llvm::AsmPrinter.
Definition at line 94 of file AMDGPUMCInstLower.cpp.
References DisasmLineMaxLen, DisasmLines, llvm::MachineInstr::dump(), llvm::AMDGPUSubtarget::dumpCode(), llvm::AsmPrinter::EmitToStreamer(), llvm::MCCodeEmitter::encodeInstruction(), llvm::MachineBasicBlock::end(), llvm::errs(), llvm::raw_ostream::flush(), llvm::format(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::AMDGPUSubtarget::getInstrInfo(), llvm::TargetMachine::getMCAsmInfo(), llvm::MachineInstr::getParent(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), HexLines, I, llvm::MachineInstr::isBundle(), llvm::AsmPrinter::MF, llvm::AArch64CC::MI, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, llvm::AMDGPUInstPrinter::printInst(), llvm::SmallVectorTemplateCommon< T >::size(), and llvm::AsmPrinter::TM.
const char* llvm::AMDGPUAsmPrinter::getPassName () const [inline, override, virtual]
getPassName - Return a nice clean name for a pass.
This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 93 of file AMDGPUAsmPrinter.h.
bool AMDGPUAsmPrinter::PrintAsmOperand (const MachineInstr * MI, unsigned OpNo, unsigned AsmVariant, const char * ExtraCode, raw_ostream & O) [override, virtual]
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
PrintAsmOperand - Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Targets should override this to format as appropriate.
Reimplemented from llvm::AsmPrinter.
Definition at line 583 of file AMDGPUAsmPrinter.cpp.
References llvm::MachineFunction::getFunction(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::TargetMachine::getSubtargetImpl(), llvm::AMDGPUInstPrinter::printRegOperand(), and llvm::AsmPrinter::TM.
bool AMDGPUAsmPrinter::runOnMachineFunction (MachineFunction & MF) [override, virtual]
Emit the specified function out to the OutStreamer.
Reimplemented from llvm::AsmPrinter.
Definition at line 102 of file AMDGPUAsmPrinter.cpp.
References DisasmLineMaxLen, DisasmLines, llvm::AMDGPUSubtarget::dumpCode(), llvm::AsmPrinter::EmitFunctionBody(), llvm::MachineFunction::getAlignment(), llvm::TargetLoweringObjectFile::getContext(), llvm::MCContext::getELFSection(), llvm::AMDGPUSubtarget::getGeneration(), llvm::MachineFunction::getInfo(), llvm::AsmPrinter::getObjFileLowering(), llvm::MachineFunction::getSubtarget(), HexLines, llvm::AMDGPUSubtarget::isAmdHsaOS(), llvm::AsmPrinter::isVerbose(), llvm::AsmPrinter::OutStreamer, llvm::MachineFunction::setAlignment(), llvm::AsmPrinter::SetupMachineFunction(), llvm::ELF::SHT_NOTE, llvm::ELF::SHT_PROGBITS, size, llvm::AMDGPUSubtarget::SOUTHERN_ISLANDS, and llvm::R600MachineFunctionInfo::StackSize.
Member Data Documentation
size_t llvm::AMDGPUAsmPrinter::DisasmLineMaxLen [protected]
Definition at line 108 of file AMDGPUAsmPrinter.h.
Referenced by EmitInstruction(), and runOnMachineFunction().
std::vector<std::string> llvm::AMDGPUAsmPrinter::DisasmLines [protected]
Definition at line 107 of file AMDGPUAsmPrinter.h.
Referenced by EmitInstruction(), and runOnMachineFunction().
std::vector<std::string> llvm::AMDGPUAsmPrinter::HexLines [protected]
Definition at line 107 of file AMDGPUAsmPrinter.h.
Referenced by EmitInstruction(), and runOnMachineFunction().
The documentation for this class was generated from the following files:
AMDGPUAsmPrinter.h
AMDGPUAsmPrinter.cpp
AMDGPUMCInstLower.cpp