LLVM: llvm::PDBSymbolTypeEnum Class Reference
llvm::PDBSymbolTypeEnum Class Reference
#include <PDBSymbolTypeEnum.h>
Public Member Functions
PDBSymbolTypeEnum (const IPDBSession &PDBSession, std::unique_ptr< IPDBRawSymbol > EnumTypeSymbol)
void dump (PDBSymDumper &Dumper) const override
Dumps the contents of a symbol a raw_ostream.
std::unique_ptr< PDBSymbolTypeUDT > getClassParent () const
std::unique_ptr
< PDBSymbolTypeBuiltin > getUnderlyingType () const
Detailed Description
Definition at line 20 of file PDBSymbolTypeEnum.h.
Constructor & Destructor Documentation
PDBSymbolTypeEnum::PDBSymbolTypeEnum (const IPDBSession & PDBSession, std::unique_ptr< IPDBRawSymbol > EnumTypeSymbol)
Definition at line 21 of file PDBSymbolTypeEnum.cpp.
Member Function Documentation
void PDBSymbolTypeEnum::dump (PDBSymDumper & Dumper) const [override, virtual]
Dumps the contents of a symbol a raw_ostream.
By default this will just call dump() on the underlying RawSymbol, which allows us to discover unknown properties, but individual implementations of PDBSymbol may override the behavior to only dump known fields.
Implements llvm::PDBSymbol.
Definition at line 34 of file PDBSymbolTypeEnum.cpp.
References llvm::PDBSymDumper::dump().
std::unique_ptr< PDBSymbolTypeUDT > PDBSymbolTypeEnum::getClassParent () const
Definition at line 25 of file PDBSymbolTypeEnum.cpp.
References llvm::IPDBSession::getConcreteSymbolById(), and llvm::PDBSymbol::Session.
std::unique_ptr< PDBSymbolTypeBuiltin > PDBSymbolTypeEnum::getUnderlyingType () const
Definition at line 30 of file PDBSymbolTypeEnum.cpp.
References llvm::IPDBSession::getConcreteSymbolById(), and llvm::PDBSymbol::Session.
The documentation for this class was generated from the following files:
PDBSymbolTypeEnum.h
PDBSymbolTypeEnum.cpp