LLVM: llvm::PDBSymbolTypeFunctionSig Class Reference
llvm::PDBSymbolTypeFunctionSig Class Reference
#include <PDBSymbolTypeFunctionSig.h>
Public Member Functions
PDBSymbolTypeFunctionSig (const IPDBSession &PDBSession, std::unique_ptr< IPDBRawSymbol > Symbol)
std::unique_ptr< PDBSymbol > getReturnType () const
std::unique_ptr< IPDBEnumSymbols > getArguments () const
std::unique_ptr< PDBSymbol > getClassParent () const
void dump (PDBSymDumper &Dumper) const override
Dumps the contents of a symbol a raw_ostream.
void dumpArgList (raw_ostream &OS) const
Detailed Description
Definition at line 20 of file PDBSymbolTypeFunctionSig.h.
Constructor & Destructor Documentation
PDBSymbolTypeFunctionSig::PDBSymbolTypeFunctionSig (const IPDBSession & PDBSession, std::unique_ptr< IPDBRawSymbol > Symbol)
Definition at line 68 of file PDBSymbolTypeFunctionSig.cpp.
Member Function Documentation
void PDBSymbolTypeFunctionSig::dump (PDBSymDumper & Dumper) const [override, virtual]
Dumps the contents of a symbol a raw_ostream.
By default this will just call dump() on the underlying RawSymbol, which allows us to discover unknown properties, but individual implementations of PDBSymbol may override the behavior to only dump known fields.
Implements llvm::PDBSymbol.
Definition at line 88 of file PDBSymbolTypeFunctionSig.cpp.
References llvm::PDBSymDumper::dump().
void llvm::PDBSymbolTypeFunctionSig::dumpArgList (raw_ostream & OS) const
std::unique_ptr< IPDBEnumSymbols > PDBSymbolTypeFunctionSig::getArguments () const
Definition at line 77 of file PDBSymbolTypeFunctionSig.cpp.
References llvm::PDBSymbol::Session.
std::unique_ptr< PDBSymbol > PDBSymbolTypeFunctionSig::getClassParent () const
Definition at line 81 of file PDBSymbolTypeFunctionSig.cpp.
References llvm::IPDBSession::getSymbolById(), and llvm::PDBSymbol::Session.
std::unique_ptr< PDBSymbol > PDBSymbolTypeFunctionSig::getReturnType () const
Definition at line 72 of file PDBSymbolTypeFunctionSig.cpp.
References llvm::IPDBSession::getSymbolById(), and llvm::PDBSymbol::Session.
The documentation for this class was generated from the following files:
PDBSymbolTypeFunctionSig.h
PDBSymbolTypeFunctionSig.cpp