LLVM: llvm::SmallVectorBase Class Reference
llvm::SmallVectorBase Class Reference
This is all the non-templated stuff common to all SmallVectors.
#include <SmallVector.h>
Inherited by llvm::SmallVectorTemplateCommon< T, typename >, llvm::SmallVectorTemplateCommon< AllocaInst * >, llvm::SmallVectorTemplateCommon< AnalysisID >, llvm::SmallVectorTemplateCommon< Arg * >, llvm::SmallVectorTemplateCommon< AsmRewrite >, llvm::SmallVectorTemplateCommon< Atom >, llvm::SmallVectorTemplateCommon< AttributeSpec >, llvm::SmallVectorTemplateCommon< BasicBlock * >, llvm::SmallVectorTemplateCommon< BitCodeAbbrevOp >, llvm::SmallVectorTemplateCommon< BitTestCase >, llvm::SmallVectorTemplateCommon< Block >, llvm::SmallVectorTemplateCommon< BlockFrequency >, llvm::SmallVectorTemplateCommon< BlockInfo >, llvm::SmallVectorTemplateCommon< BlockInterference >, llvm::SmallVectorTemplateCommon< BlockMass >, llvm::SmallVectorTemplateCommon< BlockNode >, llvm::SmallVectorTemplateCommon< bool >, llvm::SmallVectorTemplateCommon< ByValInfo >, llvm::SmallVectorTemplateCommon< CCValAssign >, llvm::SmallVectorTemplateCommon< char >, llvm::SmallVectorTemplateCommon< const CallInst * >, llvm::SmallVectorTemplateCommon< const char * >, llvm::SmallVectorTemplateCommon< const DIExpression * >, llvm::SmallVectorTemplateCommon< const Function * >, llvm::SmallVectorTemplateCommon< const LocalAsMetadata * >, llvm::SmallVectorTemplateCommon< const MachineInstr * >, llvm::SmallVectorTemplateCommon< const SCEV * >, llvm::SmallVectorTemplateCommon< const uint32_t * >, llvm::SmallVectorTemplateCommon< const Value * >, llvm::SmallVectorTemplateCommon< ConstantPoolEntry >, llvm::SmallVectorTemplateCommon< CriticalEdge >, llvm::SmallVectorTemplateCommon< Dependence >, llvm::SmallVectorTemplateCommon< DICompileUnit * >, llvm::SmallVectorTemplateCommon< DIEAbbrevData >, llvm::SmallVectorTemplateCommon< DIGlobalVariable * >, llvm::SmallVectorTemplateCommon< DILineInfo >, llvm::SmallVectorTemplateCommon< DIScope * >, llvm::SmallVectorTemplateCommon< DISubprogram * >, llvm::SmallVectorTemplateCommon< DIType * >, llvm::SmallVectorTemplateCommon< DWARFDebugInfoEntryMinimal >, llvm::SmallVectorTemplateCommon< EHFrameRelatedSections >, llvm::SmallVectorTemplateCommon< Entry >, llvm::SmallVectorTemplateCommon< EVT >, llvm::SmallVectorTemplateCommon< FixedBlockInfo >, llvm::SmallVectorTemplateCommon< ForwardedRegister >, llvm::SmallVectorTemplateCommon< FreeList * >, llvm::SmallVectorTemplateCommon< Function * >, llvm::SmallVectorTemplateCommon< GCOVEdge * >, llvm::SmallVectorTemplateCommon< HandlerInfo >, llvm::SmallVectorTemplateCommon< HexagonInstr >, llvm::SmallVectorTemplateCommon< IdxMBBPair >, llvm::SmallVectorTemplateCommon< ImmutablePass * >, llvm::SmallVectorTemplateCommon< InsnRange >, llvm::SmallVectorTemplateCommon< Inst >, llvm::SmallVectorTemplateCommon< InState >, llvm::SmallVectorTemplateCommon< Instruction * >, llvm::SmallVectorTemplateCommon< int >, llvm::SmallVectorTemplateCommon< ISD::ArgFlagsTy >, llvm::SmallVectorTemplateCommon< ISD::InputArg >, llvm::SmallVectorTemplateCommon< ISD::OutputArg >, llvm::SmallVectorTemplateCommon< LayoutAlignElem >, llvm::SmallVectorTemplateCommon< LexicalScope * >, llvm::SmallVectorTemplateCommon< List >, llvm::SmallVectorTemplateCommon< LiveInBlock >, llvm::SmallVectorTemplateCommon< LiveInReg >, llvm::SmallVectorTemplateCommon< LiveInterval * >, llvm::SmallVectorTemplateCommon< LiveOutInfo >, llvm::SmallVectorTemplateCommon< LiveOutPair >, llvm::SmallVectorTemplateCommon< LiveOutReg >, llvm::SmallVectorTemplateCommon< LiveRange * >, llvm::SmallVectorTemplateCommon< LiveRange::Segment >, llvm::SmallVectorTemplateCommon< LoadCommandInfo >, llvm::SmallVectorTemplateCommon< Location >, llvm::SmallVectorTemplateCommon< LocationList >, llvm::SmallVectorTemplateCommon< MachineBasicBlock * >, llvm::SmallVectorTemplateCommon< MachineInstr * >, llvm::SmallVectorTemplateCommon< MCDataFragment * >, llvm::SmallVectorTemplateCommon< MCDwarfFile >, llvm::SmallVectorTemplateCommon< MCFixup >, llvm::SmallVectorTemplateCommon< MCLOHDirective >, llvm::SmallVectorTemplateCommon< MCOperand >, llvm::SmallVectorTemplateCommon< MCPhysReg >, llvm::SmallVectorTemplateCommon< MCSection * >, llvm::SmallVectorTemplateCommon< MCSymbol * >, llvm::SmallVectorTemplateCommon< Metadata * >, llvm::SmallVectorTemplateCommon< MILOHDirective >, llvm::SmallVectorTemplateCommon< MVT >, llvm::SmallVectorTemplateCommon< Node * >, llvm::SmallVectorTemplateCommon< NodeState >, llvm::SmallVectorTemplateCommon< object::OwningBinary< object::Archive > >, llvm::SmallVectorTemplateCommon< OptionInfo >, llvm::SmallVectorTemplateCommon< Pass * >, llvm::SmallVectorTemplateCommon< PHINode * >, llvm::SmallVectorTemplateCommon< PhiT * >, llvm::SmallVectorTemplateCommon< PMDataManager * >, llvm::SmallVectorTemplateCommon< PointerAlignElem >, llvm::SmallVectorTemplateCommon< PointerUnion< Function *, Node * > >, llvm::SmallVectorTemplateCommon< RangeSpan >, llvm::SmallVectorTemplateCommon< RangeSpanList >, llvm::SmallVectorTemplateCommon< RegUnitInfo >, llvm::SmallVectorTemplateCommon< RootData >, llvm::SmallVectorTemplateCommon< ScavengedInfo >, llvm::SmallVectorTemplateCommon< SCC * >, llvm::SmallVectorTemplateCommon< SDDbgValue * >, llvm::SmallVectorTemplateCommon< SDep >, llvm::SmallVectorTemplateCommon< SDNode * >, llvm::SmallVectorTemplateCommon< SDValue >, llvm::SmallVectorTemplateCommon< SectionEntry >, llvm::SmallVectorTemplateCommon< Segment >, llvm::SmallVectorTemplateCommon< SEHHandler >, llvm::SmallVectorTemplateCommon< SID >, llvm::SmallVectorTemplateCommon< SimpleKey >, llvm::SmallVectorTemplateCommon< SlotIndex >, llvm::SmallVectorTemplateCommon< SmallString< 32 > >, llvm::SmallVectorTemplateCommon< SmallVector< unsigned, 8 > >, llvm::SmallVectorTemplateCommon< SMFixIt >, llvm::SmallVectorTemplateCommon< SMLoc >, llvm::SmallVectorTemplateCommon< SMSNode >, llvm::SmallVectorTemplateCommon< std::pair< AnalysisID, IdentifyingPassPtr > >, llvm::SmallVectorTemplateCommon< std::pair< AtomType, Form > >, llvm::SmallVectorTemplateCommon< std::pair< BlockFrequency, unsigned > >, llvm::SmallVectorTemplateCommon< std::pair< BlockNode, BlockMass > >, llvm::SmallVectorTemplateCommon< std::pair< bool, StringRef > >, llvm::SmallVectorTemplateCommon< std::pair< const char *, std::pair< int, const char * > > >, llvm::SmallVectorTemplateCommon< std::pair< const MDNode *, const MDNode * > >, llvm::SmallVectorTemplateCommon< std::pair< const TargetRegisterClass *, MachineOperand * > >, llvm::SmallVectorTemplateCommon< std::pair< int, int64_t > >, llvm::SmallVectorTemplateCommon< std::pair< KeyT, ValueT > >, llvm::SmallVectorTemplateCommon< std::pair< MCSectionSubPair, MCSectionSubPair > >, llvm::SmallVectorTemplateCommon< std::pair< MCSymbol *, int > >, llvm::SmallVectorTemplateCommon< std::pair< Node *, iterator > >, llvm::SmallVectorTemplateCommon< std::pair< SlotIndex, SlotIndex > >, llvm::SmallVectorTemplateCommon< std::pair< std::string, GCOVCoverage > >, llvm::SmallVectorTemplateCommon< std::pair< std::unique_ptr< DwarfTypeUnit >, const DICompositeType * > >, llvm::SmallVectorTemplateCommon< std::pair< unsigned, MCFragment * > >, llvm::SmallVectorTemplateCommon< std::pair< unsigned, MCSymbol * > >, llvm::SmallVectorTemplateCommon< std::pair< unsigned, TrackingMDNodeRef > >, llvm::SmallVectorTemplateCommon< std::pair< unsigned, unsigned > >, llvm::SmallVectorTemplateCommon< std::pair< void *, size_t > >, llvm::SmallVectorTemplateCommon< std::string * >, llvm::SmallVectorTemplateCommon< std::string >, llvm::SmallVectorTemplateCommon< std::unique_ptr< Arg > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< DbgVariable > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< DwarfUnit > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< GCOVBlock > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< GCOVEdge > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< GCOVFunction > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< GCStrategy > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< MemoryBuffer > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< MipsOptionRecord > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< Module > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< object::ObjectFile > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< UnitType > >, llvm::SmallVectorTemplateCommon< StringRef >, llvm::SmallVectorTemplateCommon< SUnit * >, llvm::SmallVectorTemplateCommon< sys::MemoryBlock >, llvm::SmallVectorTemplateCommon< T >, llvm::SmallVectorTemplateCommon< TraceBlockInfo >, llvm::SmallVectorTemplateCommon< TrackingMDNodeRef >, llvm::SmallVectorTemplateCommon< TrackingVH< Value > >, llvm::SmallVectorTemplateCommon< TreeData >, llvm::SmallVectorTemplateCommon< uint32_t >, llvm::SmallVectorTemplateCommon< uint64_t >, llvm::SmallVectorTemplateCommon< uint8_t >, llvm::SmallVectorTemplateCommon< uintptr_t >, llvm::SmallVectorTemplateCommon< unsigned >, llvm::SmallVectorTemplateCommon< unsigned char >, llvm::SmallVectorTemplateCommon< UseToVisit >, llvm::SmallVectorTemplateCommon< Value * >, llvm::SmallVectorTemplateCommon< Value >, llvm::SmallVectorTemplateCommon< ValueT >, llvm::SmallVectorTemplateCommon< VariableDbgInfo >, llvm::SmallVectorTemplateCommon< VarInfo >, llvm::SmallVectorTemplateCommon< VersionMapEntry >, llvm::SmallVectorTemplateCommon< VNInfo * >, llvm::SmallVectorTemplateCommon< void * >, llvm::SmallVectorTemplateCommon< VReg2SUnit >, llvm::SmallVectorTemplateCommon< WeakVH >, llvm::SmallVectorTemplateCommon< Weight >, llvm::SmallVectorTemplateCommon< WinEHHandlerType >, llvm::SmallVectorTemplateCommon< WinEHTryBlockMapEntry >, and llvm::SmallVectorTemplateCommon< WinEHUnwindMapEntry >.
Public Member Functions
size_t size_in_bytes () const
This returns size()*sizeof(T).
size_t capacity_in_bytes () const
capacity_in_bytes - This returns capacity()*sizeof(T).
bool LLVM_ATTRIBUTE_UNUSED_RESULT empty () const
Protected Member Functions
SmallVectorBase (void *FirstEl, size_t Size)
void grow_pod (void *FirstEl, size_t MinSizeInBytes, size_t TSize)
This is an implementation of the grow() method which only works on POD-like data types and is out of line to reduce code duplication.
Protected Attributes
void * BeginX
void * EndX
void * CapacityX
Detailed Description
This is all the non-templated stuff common to all SmallVectors.
Definition at line 34 of file SmallVector.h.
Constructor & Destructor Documentation
llvm::SmallVectorBase::SmallVectorBase (void * FirstEl, size_t Size) [inline, protected]
Definition at line 39 of file SmallVector.h.
Member Function Documentation
size_t llvm::SmallVectorBase::capacity_in_bytes () const [inline]
capacity_in_bytes - This returns capacity()*sizeof(T).
Definition at line 53 of file SmallVector.h.
References BeginX, and CapacityX.
Referenced by llvm::capacity_in_bytes(), and grow_pod().
bool LLVM_ATTRIBUTE_UNUSED_RESULT llvm::SmallVectorBase::empty () const [inline]
Definition at line 57 of file SmallVector.h.
References BeginX, and EndX.
Referenced by llvm::PMDataManager::add(), AddAliasScopeMetadata(), addBlockAndPredsToSet(), llvm::DwarfDebug::addDwarfTypeUnitType(), llvm::InstCombineWorklist::AddInitialGroup(), llvm::RegsForValue::AddInlineAsmOperands(), addInstructionToGraph(), llvm::DbgVariable::addMMIEntry(), llvm::DwarfCompileUnit::addRange(), addRange(), AddReachableCodeToWorklist(), llvm::RecurrenceDescriptor::AddReductionVar(), llvm::MachineInstr::addRegisterDead(), llvm::MachineInstr::addRegisterKilled(), advanceToNextLeafType(), llvm::AllocationOrder::AllocationOrder(), llvm::LoopInfoBase< BlockT, LoopT >::Analyze(), llvm::SparcInstrInfo::AnalyzeBranch(), llvm::MSP430InstrInfo::AnalyzeBranch(), llvm::ARMBaseInstrInfo::AnalyzeBranch(), llvm::SystemZInstrInfo::AnalyzeBranch(), llvm::sys::path::append(), llvm::LiveRange::append(), llvm::A57ChainingConstraint::apply(), AreAnyUnderlyingObjectsAnAlloca(), argsAreStructReturn(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::atEnd(), llvm::SmallVectorTemplateCommon< MachineInstr * >::back(), llvm::DwarfDebug::beginFunction(), llvm::yaml::Output::blockScalarString(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), buildGEP(), buildMultiplyTree(), llvm::ScheduleDAGInstrs::buildSchedGraph(), buildSetsFrom(), llvm::IDFCalculator::calculate(), callIsStructReturn(), llvm::MachineBasicBlock::canFallThrough(), llvm::SSAUpdaterImpl< UpdaterT >::CheckIfPHIMatches(), llvm::StatepointLoweringState::clear(), llvm::ArrayRecycler< MachineOperand >::clear(), llvm::RegPressureTracker::closeBottom(), llvm::RegPressureTracker::closeTop(), combineRedundantDWordShuffle(), completeEphemeralValues(), llvm::SCEVAddRecExpr::computeAccessFunctions(), llvm::ConstantAggrKeyType< ConstantClass >::ConstantAggrKeyType(), llvm::ConstantExprKeyType::ConstantExprKeyType(), ConstantFoldGetElementPtrImpl(), constexprToEdges(), ConstHasGlobalValuePredicate(), llvm::LiveInterval::constructMainRangeFromSubranges(), containsConstantSomewhere(), llvm::convertUTF8ToUTF16String(), CrashHandler(), DeleteDeadInstruction(), DeleteTriviallyDeadInstructions(), llvm::SCEVAddRecExpr::delinearize(), determinePointerReadAttrs(), llvm::AsmPrinter::doFinalization(), llvm::LexicalScope::dump(), llvm::GCOVBlock::dump(), llvm::ScheduleDAGSDNodes::dumpNode(), llvm::LiveRangeEdit::eliminateDeadDefs(), EliminateDeadSwitchCases(), llvm::EmitAnyX86InstComments(), llvm::MCELFStreamer::EmitBundleUnlock(), llvm::ConstantPool::emitEntries(), llvm::PPCFrameLowering::emitEpilogue(), llvm::X86AsmPrinter::EmitInstruction(), llvm::PPCFrameLowering::emitPrologue(), llvm::ScheduleDAGSDNodes::EmitSchedule(), llvm::ConstantPool::empty(), llvm::SDDbgInfo::empty(), llvm::SparseSet< RootData >::empty(), llvm::LoopAccessInfo::RuntimePointerCheck::empty(), llvm::LiveRange::empty(), llvm::MDAttachmentMap::empty(), llvm::Eval(), extendSegmentsToUses(), llvm::ScalarEvolution::findArrayDimensions(), findCallees(), llvm::objcarc::FindDependencies(), llvm::FindFunctionBackedges(), FindMostPopularDest(), firstRealType(), FixTail(), llvm::LiveRange::flushSegmentSet(), llvm::InstCombiner::FoldCmpLoadFromIndexedGlobal(), llvm::ScalarEvolution::forgetLoop(), llvm::ScalarEvolution::forgetValue(), llvm::formLCSSA(), llvm::SmallVectorTemplateCommon< MachineInstr * >::front(), llvm::ScalarEvolution::getAddExpr(), llvm::SelectionDAGBuilder::getControlRoot(), llvm::RegsForValue::getCopyFromRegs(), llvm::MCStreamer::getCurrentSection(), llvm::DominatorTreeBase< MachineBasicBlock >::getDescendants(), llvm::MCDwarfLineTableHeader::getFile(), llvm::ScheduleDAGSDNodes::getGraphNodeLabel(), llvm::ScalarEvolution::getMulExpr(), llvm::MemoryDependenceAnalysis::getNonLocalCallDependency(), llvm::MCStreamer::getPreviousSection(), llvm::SelectionDAGBuilder::getRoot(), llvm::ScalarEvolution::getSMaxExpr(), llvm::MCSection::getSubsectionInsertionPoint(), getTargetShuffleMask(), llvm::Intrinsic::getType(), llvm::ScalarEvolution::getUMaxExpr(), getUnderlyingObjects(), llvm::GetUnderlyingObjects(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::getVisitState(), llvm::LiveRange::hasAtLeastOneValue(), llvm::DbgVariable::hasComplexAddress(), llvm::SDNode::hasPredecessorHelper(), llvm::ScheduleDAGTopologicalSort::InitDAGTopologicalSorting(), llvm::DbgVariable::initializeDbgValue(), llvm::DbgVariable::initializeMMI(), llvm::InlineFunction(), llvm::LazyCallGraph::insertEdge(), llvm::LazyCallGraph::SCC::insertIncomingEdge(), insertParsePoints(), llvm::MachineTraceMetrics::Ensemble::invalidate(), isAllocSiteRemovable(), llvm::LazyCallGraph::SCC::isDescendantOf(), llvm::InstCombineWorklist::isEmpty(), isEphemeralValueOf(), isGuaranteedToExecute(), isLeakCheckerRoot(), llvm::DwarfDebug::isLexicalScopeDIENull(), isObjectSizeLessThanOrEq(), isOnlyCopiedFromConstantGlobal(), isPotentiallyReachableInner(), IsStoredObjCPointer(), llvm::MCContext::isValidDwarfFileNumber(), IsValueFullyAvailableInBlock(), isVectorPromotionViable(), llvm::SpillPlacement::iterate(), LinearizeExprTree(), llvm::HexagonTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), LowerCallResult(), llvm::TargetLowering::LowerCallTo(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::SystemZTargetLowering::LowerReturn(), llvm::MapMetadata(), markAliveBlocks(), llvm::object::ExportEntry::moveNext(), llvm::SIInstrInfo::moveToVALU(), nextRealType(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator*(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator++(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator--(), llvm::BranchFolder::OptimizeFunction(), PrepareTailCall(), llvm::MachineInstr::print(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), processInstruction(), llvm::promoteLoopAccessesToScalars(), llvm::BitstreamCursor::ReadBlockEnd(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), relocationViaAlloca(), llvm::Inliner::removeDeadFunctions(), llvm::SelectionDAG::RemoveDeadNodes(), llvm::PMDataManager::removeDeadPasses(), llvm::LazyCallGraph::removeEdge(), llvm::MemoryDependenceAnalysis::removeInstruction(), llvm::LazyCallGraph::SCC::removeIntraSCCEdge(), llvm::IntervalMapImpl::Path::replaceRoot(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Reset(), llvm::HexagonInstrInfo::ReverseBranchCondition(), rewriteLoopExitBlock(), rewriteNonInstructionUses(), llvm::DAGTypeLegalizer::run(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::SlotIndexes::runOnMachineFunction(), llvm::Inliner::runOnSCC(), llvm::SpillPlacement::scanActiveBundles(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::EngineBuilder::selectTarget(), llvm::SUnit::setDepthDirty(), llvm::SUnit::setHeightDirty(), llvm::simplifyLoop(), simplifyOneLoop(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::skipToParent(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), llvm::SmallVector< unsigned, 0 >::SmallVector(), SplitAddRecs(), llvm::SplitCriticalEdge(), llvm::SplitLandingPadPredecessors(), splitVectorValues(), llvm::StatepointLoweringState::startNewStatepoint(), llvm::MCStreamer::SubSection(), llvm::cl::TokenizeGNUCommandLine(), llvm::cl::TokenizeWindowsCommandLine(), llvm::APFloat::toString(), tryBuildVectorShuffle(), TurnSwitchRangeIntoICmp(), llvm::UnrollLoop(), llvm::DominatorTreeBase< MachineBasicBlock >::updateDFSNumbers(), updateLiveness(), llvm::MachineBasicBlock::updateTerminator(), verifyCTRBranch(), llvm::LoopBase< BlockT, LoopT >::verifyLoop(), llvm::SCEVTraversal< SV >::visitAll(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitLandingPadInst(), llvm::PtrUseVisitor< SliceBuilder >::visitPtr(), WriteMetadataAttachment(), WriteModuleMetadataStore(), llvm::ArrayRecycler< MachineOperand >::~ArrayRecycler(), and llvm::AsmPrinter::~AsmPrinter().
void SmallVectorBase::grow_pod (void * FirstEl, size_t MinSizeInBytes, size_t TSize) [protected]
This is an implementation of the grow() method which only works on POD-like data types and is out of line to reduce code duplication.
grow_pod - This is an implementation of the grow() method which only works on POD-like datatypes and is out of line to reduce code duplication.
Definition at line 19 of file SmallVector.cpp.
References BeginX, capacity_in_bytes(), CapacityX, EndX, and size_in_bytes().
size_t llvm::SmallVectorBase::size_in_bytes () const [inline]
This returns size()*sizeof(T).
Definition at line 48 of file SmallVector.h.
References BeginX, and EndX.
Referenced by grow_pod().
Member Data Documentation
void* llvm::SmallVectorBase::BeginX [protected]
Definition at line 36 of file SmallVector.h.
Referenced by llvm::SmallVectorTemplateCommon< MachineInstr * >::begin(), capacity_in_bytes(), llvm::SmallVectorImpl< MachineInstr * >::clear(), empty(), grow_pod(), llvm::SmallVectorTemplateCommon< MachineInstr * >::isSmall(), llvm::SmallVectorTemplateCommon< MachineInstr * >::resetToSmall(), size_in_bytes(), and llvm::SmallVectorImpl< T >::swap().
void * llvm::SmallVectorBase::CapacityX [protected]
Definition at line 36 of file SmallVector.h.
Referenced by capacity_in_bytes(), llvm::SmallVectorTemplateCommon< MachineInstr * >::capacity_ptr(), llvm::SmallVectorImpl< MachineInstr * >::emplace_back(), grow_pod(), llvm::SmallVectorImpl< MachineInstr * >::insert(), llvm::SmallVectorTemplateBase< LiveOutInfo, isPodLike< LiveOutInfo >::value >::push_back(), llvm::SmallVectorTemplateBase< T, true >::push_back(), llvm::SmallVectorTemplateCommon< MachineInstr * >::resetToSmall(), and llvm::SmallVectorImpl< T >::swap().
void * llvm::SmallVectorBase::EndX [protected]
Definition at line 36 of file SmallVector.h.
Referenced by llvm::SmallVectorImpl< MachineInstr * >::clear(), llvm::SmallVectorImpl< MachineInstr * >::emplace_back(), empty(), llvm::SmallVectorTemplateCommon< MachineInstr * >::end(), grow_pod(), llvm::SmallVectorImpl< MachineInstr * >::insert(), llvm::SmallVectorTemplateBase< LiveOutInfo, isPodLike< LiveOutInfo >::value >::push_back(), llvm::SmallVectorTemplateBase< T, true >::push_back(), llvm::SmallVectorTemplateCommon< MachineInstr * >::resetToSmall(), llvm::SmallVectorTemplateCommon< MachineInstr * >::setEnd(), size_in_bytes(), and llvm::SmallVectorImpl< T >::swap().
The documentation for this class was generated from the following files:
SmallVector.h
SmallVector.cpp