LLVM: llvm::X86_64MachoTargetObjectFile Class Reference
llvm::X86_64MachoTargetObjectFile Class Reference
X86_64MachoTargetObjectFile - This TLOF implementation is used for Darwin x86-64.
#include <X86TargetObjectFile.h>
Public Member Functions
const MCExpr * getTTypeGlobalReference (const GlobalValue *GV, unsigned Encoding, Mangler &Mang, const TargetMachine &TM, MachineModuleInfo *MMI, MCStreamer &Streamer) const override
The mach-o version of this method defaults to returning a stub reference.
MCSymbol * getCFIPersonalitySymbol (const GlobalValue *GV, Mangler &Mang, const TargetMachine &TM, MachineModuleInfo *MMI) const override
const MCExpr * getIndirectSymViaGOTPCRel (const MCSymbol *Sym, const MCValue &MV, int64_t Offset, MachineModuleInfo *MMI, MCStreamer &Streamer) const override
Get MachO PC relative GOT entry relocation.
Detailed Description
X86_64MachoTargetObjectFile - This TLOF implementation is used for Darwin x86-64.
Definition at line 20 of file X86TargetObjectFile.h.
Member Function Documentation
MCSymbol * X86_64MachoTargetObjectFile::getCFIPersonalitySymbol (const GlobalValue * GV, Mangler & Mang, const TargetMachine & TM, MachineModuleInfo * MMI) const [override, virtual]
Reimplemented from llvm::TargetLoweringObjectFileMachO.
Definition at line 44 of file X86TargetObjectFile.cpp.
References llvm::TargetMachine::getSymbol().
const MCExpr * X86_64MachoTargetObjectFile::getIndirectSymViaGOTPCRel (const MCSymbol * Sym, const MCValue & MV, int64_t Offset, MachineModuleInfo * MMI, MCStreamer & Streamer) const [override, virtual]
Get MachO PC relative GOT entry relocation.
Reimplemented from llvm::TargetLoweringObjectFileMachO.
Definition at line 50 of file X86TargetObjectFile.cpp.
References llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCValue::getConstant(), and llvm::MCSymbolRefExpr::VK_GOTPCREL.
const MCExpr * X86_64MachoTargetObjectFile::getTTypeGlobalReference (const GlobalValue * GV, unsigned Encoding, Mangler & Mang, const TargetMachine & TM, MachineModuleInfo * MMI, MCStreamer & Streamer) const [override, virtual]
The mach-o version of this method defaults to returning a stub reference.
Reimplemented from llvm::TargetLoweringObjectFileMachO.
Definition at line 25 of file X86TargetObjectFile.cpp.
References llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::dwarf::DW_EH_PE_indirect, llvm::dwarf::DW_EH_PE_pcrel, llvm::TargetMachine::getSymbol(), llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference(), and llvm::MCSymbolRefExpr::VK_GOTPCREL.
The documentation for this class was generated from the following files:
X86TargetObjectFile.h
X86TargetObjectFile.cpp