LLVM: llvm::DITemplateParameter Class Reference
llvm::DITemplateParameter Class Reference
Base class for template parameters.
#include <DebugInfoMetadata.h>
Public Member Functions
StringRef getName () const
DITypeRef getType () const
MDString * getRawName () const
Metadata * getRawType () const
Static Public Member Functions
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
DITemplateParameter (LLVMContext &Context, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops)
~DITemplateParameter ()
Detailed Description
Base class for template parameters.
Definition at line 1627 of file DebugInfoMetadata.h.
Constructor & Destructor Documentation
llvm::DITemplateParameter::DITemplateParameter (LLVMContext & Context, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops) [inline, protected]
Definition at line 1629 of file DebugInfoMetadata.h.
llvm::DITemplateParameter::~DITemplateParameter () [protected]
Member Function Documentation
static bool llvm::DITemplateParameter::classof (const Metadata * MD) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::DINode.
Reimplemented in llvm::DITemplateValueParameter, and llvm::DITemplateTypeParameter.
Definition at line 1641 of file DebugInfoMetadata.h.
References llvm::Metadata::DITemplateTypeParameterKind, llvm::Metadata::DITemplateValueParameterKind, and llvm::Metadata::getMetadataID().
StringRef llvm::DITemplateParameter::getName () const [inline]
Definition at line 1635 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
Referenced by llvm::MDNodeKeyImpl< DITemplateTypeParameter >::isKeyOf(), and llvm::MDNodeKeyImpl< DITemplateValueParameter >::isKeyOf().
MDString* llvm::DITemplateParameter::getRawName () const [inline]
Definition at line 1638 of file DebugInfoMetadata.h.
Referenced by WriteDITemplateTypeParameter(), and WriteDITemplateValueParameter().
Metadata* llvm::DITemplateParameter::getRawType () const [inline]
Definition at line 1639 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getType(), llvm::MDNodeKeyImpl< DITemplateTypeParameter >::isKeyOf(), and llvm::MDNodeKeyImpl< DITemplateValueParameter >::isKeyOf().
DITypeRef llvm::DITemplateParameter::getType () const [inline]
Definition at line 1636 of file DebugInfoMetadata.h.
References getRawType().
Referenced by WriteDITemplateTypeParameter(), and WriteDITemplateValueParameter().
The documentation for this class was generated from the following file:
DebugInfoMetadata.h