LLVM: llvm::Module Class Reference
llvm::Module Class Reference
A Module instance is used to store all the information related to an LLVM module.
#include <Module.h>
Classes
struct ModuleFlagEntry
Public Member Functions
Module (StringRef ModuleID, LLVMContext &C)
The Module constructor.
~Module ()
The module destructor. This will dropAllReferences.
const std::string & getModuleIdentifier () const
Get the module identifier which is, essentially, the name of the module.
StringRef getName () const
Get a short "name" for the module.
const std::string getDataLayoutStr () const
Get the data layout string for the module's target platform.
const DataLayout & getDataLayout () const
Get the data layout for the module's target platform.
const std::string & getTargetTriple () const
Get the target triple which is a string describing the target host.
LLVMContext & getContext () const
Get the global data context.
const std::string & getModuleInlineAsm () const
Get any module-scope inline assembly blocks.
RandomNumberGenerator * createRNG (const Pass *P) const
Get a RandomNumberGenerator salted for use with this module.
void setModuleIdentifier (StringRef ID)
Set the module identifier.
void setDataLayout (StringRef Desc)
Set the data layout.
void setDataLayout (const DataLayout &Other)
void setTargetTriple (StringRef T)
Set the target triple.
void setModuleInlineAsm (StringRef Asm)
Set the module-scope inline assembly blocks.
void appendModuleInlineAsm (StringRef Asm)
Append to the module-scope inline assembly blocks.
GlobalValue * getNamedValue (StringRef Name) const
Return the global value in the module with the specified name, of arbitrary type.
unsigned getMDKindID (StringRef Name) const
Return a unique non-zero ID for the specified metadata kind.
void getMDKindNames (SmallVectorImpl< StringRef > &Result) const
Populate client supplied SmallVector with the name for custom metadata IDs registered in this LLVMContext.
StructType * getTypeByName (StringRef Name) const
Return the type with the specified name, or null if there is none by that name.
std::vector< StructType * > getIdentifiedStructTypes () const
Constant * getOrInsertFunction (StringRef Name, FunctionType *T, AttributeSet AttributeList)
Look up the specified function in the module symbol table.
Constant * getOrInsertFunction (StringRef Name, FunctionType *T)
Constant * getOrInsertFunction (StringRef Name, AttributeSet AttributeList, Type *RetTy,...) LLVM_END_WITH_NULL
Look up the specified function in the module symbol table.
Constant * getOrInsertFunction (StringRef Name, Type *RetTy,...) LLVM_END_WITH_NULL
Same as above, but without the attributes.
Function * getFunction (StringRef Name) const
Look up the specified function in the module symbol table.
GlobalVariable * getGlobalVariable (StringRef Name) const
Look up the specified global variable in the module symbol table.
GlobalVariable * getGlobalVariable (StringRef Name, bool AllowInternal) const
GlobalVariable * getGlobalVariable (StringRef Name, bool AllowInternal=false)
getGlobalVariable - Look up the specified global variable in the module symbol table.
GlobalVariable * getNamedGlobal (StringRef Name)
Return the global variable in the module with the specified name, of arbitrary type.
const GlobalVariable * getNamedGlobal (StringRef Name) const
Constant * getOrInsertGlobal (StringRef Name, Type *Ty)
Look up the specified global in the module symbol table.
GlobalAlias * getNamedAlias (StringRef Name) const
Return the global alias in the module with the specified name, of arbitrary type.
NamedMDNode * getNamedMetadata (const Twine &Name) const
Return the first NamedMDNode in the module with the specified name.
NamedMDNode * getOrInsertNamedMetadata (StringRef Name)
Return the named MDNode in the module with the specified name.
void eraseNamedMetadata (NamedMDNode *NMD)
Remove the given NamedMDNode from this module and delete it.
Comdat * getOrInsertComdat (StringRef Name)
Return the Comdat in the module with the specified name.
void getModuleFlagsMetadata (SmallVectorImpl< ModuleFlagEntry > &Flags) const
Returns the module flags in the provided vector.
Metadata * getModuleFlag (StringRef Key) const
Return the corresponding value if Key appears in module flags, otherwise return null.
NamedMDNode * getModuleFlagsMetadata () const
Returns the NamedMDNode in the module that represents module-level flags.
NamedMDNode * getOrInsertModuleFlagsMetadata ()
Returns the NamedMDNode in the module that represents module-level flags.
void addModuleFlag (ModFlagBehavior Behavior, StringRef Key, Metadata *Val)
Add a module-level flag to the module-level flags metadata.
void addModuleFlag (ModFlagBehavior Behavior, StringRef Key, Constant *Val)
void addModuleFlag (ModFlagBehavior Behavior, StringRef Key, uint32_t Val)
void addModuleFlag (MDNode *Node)
void setMaterializer (GVMaterializer *GVM)
Sets the GVMaterializer to GVM.
GVMaterializer * getMaterializer () const
Retrieves the GVMaterializer, if any, for this Module.
bool isDematerializable (const GlobalValue *GV) const
Returns true if this GV was loaded from this Module's GVMaterializer and the GVMaterializer knows how to dematerialize the GV.
std::error_code materialize (GlobalValue *GV)
Make sure the GlobalValue is fully read.
void dematerialize (GlobalValue *GV)
If the GlobalValue is read in, and if the GVMaterializer supports it, release the memory for the function, and set it up to be materialized lazily.
std::error_code materializeAll ()
Make sure all GlobalValues in this Module are fully read.
std::error_code materializeAllPermanently ()
Make sure all GlobalValues in this Module are fully read and clear the Materializer.
std::error_code materializeMetadata ()
const GlobalListType & getGlobalList () const
Get the Module's list of global variables (constant).
GlobalListType & getGlobalList ()
Get the Module's list of global variables.
const FunctionListType & getFunctionList () const
Get the Module's list of functions (constant).
FunctionListType & getFunctionList ()
Get the Module's list of functions.
const AliasListType & getAliasList () const
Get the Module's list of aliases (constant).
AliasListType & getAliasList ()
Get the Module's list of aliases.
const NamedMDListType & getNamedMDList () const
Get the Module's list of named metadata (constant).
NamedMDListType & getNamedMDList ()
Get the Module's list of named metadata.
const ValueSymbolTable & getValueSymbolTable () const
Get the symbol table of global variable and function identifiers.
ValueSymbolTable & getValueSymbolTable ()
Get the Module's symbol table of global variable and function identifiers.
const ComdatSymTabType & getComdatSymbolTable () const
Get the Module's symbol table for COMDATs (constant).
ComdatSymTabType & getComdatSymbolTable ()
Get the Module's symbol table for COMDATs.
global_iterator global_begin ()
const_global_iterator global_begin () const
global_iterator global_end ()
const_global_iterator global_end () const
bool global_empty () const
iterator_range< global_iterator > globals ()
iterator_range
< const_global_iterator > globals () const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_t size () const
bool empty () const
iterator_range< iterator > functions ()
iterator_range< const_iterator > functions () const
alias_iterator alias_begin ()
const_alias_iterator alias_begin () const
alias_iterator alias_end ()
const_alias_iterator alias_end () const
size_t alias_size () const
bool alias_empty () const
iterator_range< alias_iterator > aliases ()
iterator_range
< const_alias_iterator > aliases () const
named_metadata_iterator named_metadata_begin ()
const_named_metadata_iterator named_metadata_begin () const
named_metadata_iterator named_metadata_end ()
const_named_metadata_iterator named_metadata_end () const
size_t named_metadata_size () const
bool named_metadata_empty () const
iterator_range
< named_metadata_iterator > named_metadata ()
iterator_range
< const_named_metadata_iterator > named_metadata () const
void dropTriviallyDeadConstantArrays ()
Destroy ConstantArrays in LLVMContext if they are not used.
void print (raw_ostream &OS, AssemblyAnnotationWriter *AAW, bool ShouldPreserveUseListOrder=false) const
Print the module to an output stream with an optional AssemblyAnnotationWriter.
void dump () const
Dump the module to stderr (for debugging).
void dropAllReferences ()
This function causes all the subinstructions to "let go" of all references that they are maintaining.
unsigned getDwarfVersion () const
Returns the Dwarf Version by checking module flags.
PICLevel::Level getPICLevel () const
Returns the PIC level (small or large model)
void setPICLevel (PICLevel::Level PL)
Set the PIC level (small or large model)
Static Public Member Functions
static GlobalListType Module::* getSublistAccess (GlobalVariable *)
static FunctionListType Module::* getSublistAccess (Function *)
static AliasListType Module::* getSublistAccess (GlobalAlias *)
static NamedMDListType Module::* getSublistAccess (NamedMDNode *)
Friends
class Constant
Types And Enumerations
enum ModFlagBehavior {
Error = 1, Warning = 2, Require = 3, Override = 4,
Append = 5, AppendUnique = 6, ModFlagBehaviorFirstVal = Error, ModFlagBehaviorLastVal = AppendUnique
}
This enumeration defines the supported behaviors of module flags.
typedef iplist< GlobalVariable > GlobalListType
The type for the list of global variables.
typedef iplist< Function > FunctionListType
The type for the list of functions.
typedef iplist< GlobalAlias > AliasListType
The type for the list of aliases.
typedef ilist< NamedMDNode > NamedMDListType
The type for the list of named metadata.
typedef StringMap< Comdat > ComdatSymTabType
The type of the comdat "symbol" table.
typedef GlobalListType::iterator global_iterator
The Global Variable iterator.
typedef
GlobalListType::const_iterator const_global_iterator
The Global Variable constant iterator.
typedef FunctionListType::iterator iterator
The Function iterators.
typedef
FunctionListType::const_iterator const_iterator
The Function constant iterator.
typedef
FunctionListType::reverse_iterator reverse_iterator
The Function reverse iterator.
typedef
FunctionListType::const_reverse_iterator const_reverse_iterator
The Function constant reverse iterator.
typedef AliasListType::iterator alias_iterator
The Global Alias iterators.
typedef
AliasListType::const_iterator const_alias_iterator
The Global Alias constant iterator.
typedef NamedMDListType::iterator named_metadata_iterator
The named metadata iterators.
typedef
NamedMDListType::const_iterator const_named_metadata_iterator
The named metadata constant iterators.
static bool isValidModFlagBehavior (Metadata *MD, ModFlagBehavior &MFB)
Checks if Metadata represents a valid ModFlagBehavior, and stores the converted result in MFB.
Detailed Description
A Module instance is used to store all the information related to an LLVM module.
Modules are the top level container of all other LLVM Intermediate Representation (IR) objects. Each module directly contains a list of globals variables, a list of functions, a list of libraries (or other modules) this module depends on, a symbol table, and various data about the target's characteristics.
A module maintains a GlobalValRefMap object that is used to hold all constant references to global variables in the module. When a global variable is destroyed, it should have no entries in the GlobalValueRefMap. The main container class for the LLVM Intermediate Representation.
Definition at line 114 of file Module.h.
Member Typedef Documentation
typedef AliasListType::iterator llvm::Module::alias_iterator
The Global Alias iterators.
Definition at line 145 of file Module.h.
typedef iplist<GlobalAlias> llvm::Module::AliasListType
The type for the list of aliases.
Definition at line 123 of file Module.h.
typedef StringMap<Comdat> llvm::Module::ComdatSymTabType
The type of the comdat "symbol" table.
Definition at line 127 of file Module.h.
typedef AliasListType::const_iterator llvm::Module::const_alias_iterator
The Global Alias constant iterator.
Definition at line 147 of file Module.h.
typedef GlobalListType::const_iterator llvm::Module::const_global_iterator
The Global Variable constant iterator.
Definition at line 132 of file Module.h.
typedef FunctionListType::const_iterator llvm::Module::const_iterator
The Function constant iterator.
Definition at line 137 of file Module.h.
typedef NamedMDListType::const_iterator llvm::Module::const_named_metadata_iterator
The named metadata constant iterators.
Definition at line 152 of file Module.h.
typedef FunctionListType::const_reverse_iterator llvm::Module::const_reverse_iterator
The Function constant reverse iterator.
Definition at line 142 of file Module.h.
typedef iplist<Function> llvm::Module::FunctionListType
The type for the list of functions.
Definition at line 121 of file Module.h.
typedef GlobalListType::iterator llvm::Module::global_iterator
The Global Variable iterator.
Definition at line 130 of file Module.h.
typedef iplist<GlobalVariable> llvm::Module::GlobalListType
The type for the list of global variables.
Definition at line 119 of file Module.h.
typedef FunctionListType::iterator llvm::Module::iterator
The Function iterators.
Definition at line 135 of file Module.h.
typedef NamedMDListType::iterator llvm::Module::named_metadata_iterator
The named metadata iterators.
Definition at line 150 of file Module.h.
typedef ilist<NamedMDNode> llvm::Module::NamedMDListType
The type for the list of named metadata.
Definition at line 125 of file Module.h.
typedef FunctionListType::reverse_iterator llvm::Module::reverse_iterator
The Function reverse iterator.
Definition at line 140 of file Module.h.
Member Enumeration Documentation
enum llvm::Module::ModFlagBehavior
This enumeration defines the supported behaviors of module flags.
Enumerator:
Error
Emits an error if two values disagree, otherwise the resulting value is that of the operands.
Warning
Emits a warning if two values disagree.
The result value will be the operand for the flag from the first module being linked.
Require
Adds a requirement that another module flag be present and have a specified value after linking is performed.
The value must be a metadata pair, where the first element of the pair is the ID of the module flag to be restricted, and the second element of the pair is the value the module flag should be restricted to. This behavior can be used to restrict the allowable results (via triggering of an error) of linking IDs with the **Override** behavior.
Override
Uses the specified value, regardless of the behavior or value of the other module.
If both modules specify **Override**, but the values differ, an error will be emitted.
Append
Appends the two values, which are required to be metadata nodes.
AppendUnique
Appends the two values, which are required to be metadata nodes.
However, duplicate entries in the second list are dropped during the append operation.
ModFlagBehaviorFirstVal
ModFlagBehaviorLastVal
Definition at line 155 of file Module.h.
Constructor & Destructor Documentation
Module::Module (StringRef ModuleID, LLVMContext & C) [explicit]
The Module constructor.
Note that there is no default constructor. You must provide a name for the module upon construction.
Definition at line 48 of file Module.cpp.
Module::~Module ()
The module destructor. This will dropAllReferences.
Definition at line 55 of file Module.cpp.
References llvm::iplist< NodeTy, Traits >::clear(), and dropAllReferences().
Member Function Documentation
void Module::addModuleFlag (ModFlagBehavior Behavior, StringRef Key, Metadata * Val)
Add a module-level flag to the module-level flags metadata.
addModuleFlag - Add a module-level flag to the module-level flags metadata.
It will create the module-level flags named metadata if it doesn't already exist.
Definition at line 340 of file Module.cpp.
References llvm::NamedMDNode::addOperand(), llvm::ConstantInt::get(), llvm::ConstantAsMetadata::get(), llvm::MDString::get(), llvm::MDNode::get(), llvm::Type::getInt32Ty(), and getOrInsertModuleFlagsMetadata().
Referenced by addModuleFlag(), and setPICLevel().
void Module::addModuleFlag (ModFlagBehavior Behavior, StringRef Key, Constant * Val)
Definition at line 348 of file Module.cpp.
References addModuleFlag(), and llvm::ConstantAsMetadata::get().
void Module::addModuleFlag (ModFlagBehavior Behavior, StringRef Key, uint32_t Val)
Definition at line 352 of file Module.cpp.
References addModuleFlag(), llvm::ConstantInt::get(), and llvm::Type::getInt32Ty().
void Module::addModuleFlag (MDNode * Node)
Definition at line 357 of file Module.cpp.
References llvm::NamedMDNode::addOperand(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), and getOrInsertModuleFlagsMetadata().
alias_iterator llvm::Module::alias_begin () [inline]
Definition at line 559 of file Module.h.
Referenced by llvm::CloneModule(), and llvm::TypeFinder::run().
const_alias_iterator llvm::Module::alias_begin () const [inline]
Definition at line 560 of file Module.h.
bool llvm::Module::alias_empty () const [inline]
Definition at line 564 of file Module.h.
alias_iterator llvm::Module::alias_end () [inline]
Definition at line 561 of file Module.h.
Referenced by llvm::CloneModule(), llvm::TypeFinder::run(), and skipEmpty().
const_alias_iterator llvm::Module::alias_end () const [inline]
Definition at line 562 of file Module.h.
size_t llvm::Module::alias_size () const [inline]
Definition at line 563 of file Module.h.
iterator_range<alias_iterator> llvm::Module::aliases () [inline]
Definition at line 566 of file Module.h.
Referenced by dropAllReferences(), orderModule(), and llvm::Inliner::removeDeadFunctions().
iterator_range<const_alias_iterator> llvm::Module::aliases () const [inline]
Definition at line 569 of file Module.h.
References llvm::iplist< NodeTy, Traits >::begin().
void llvm::Module::appendModuleInlineAsm (StringRef Asm) [inline]
Append to the module-scope inline assembly blocks.
A trailing newline is added if the input doesn't have one.
Definition at line 299 of file Module.h.
Referenced by llvm::orc::OrcX86_64::insertCompileCallbackTrampolines(), and llvm::orc::OrcX86_64::insertResolverBlock().
iterator llvm::Module::begin () [inline]
Definition at line 539 of file Module.h.
Referenced by llvm::IntrinsicLowering::AddPrototypes(), llvm::ExecutionEngine::clearGlobalMappingsFromModule(), llvm::CloneModule(), LLVMGetFirstFunction(), LLVMGetLastFunction(), LLVMGetPreviousFunction(), llvm::TypeFinder::run(), StripSymbolNames(), llvm::object::IRObjectFile::symbol_begin_impl(), llvm::verifyModule(), llvm::InstVisitor< ObjectSizeOffsetVisitor, SizeOffsetType >::visit(), and WriteModule().
const_iterator llvm::Module::begin () const [inline]
Definition at line 540 of file Module.h.
RandomNumberGenerator * Module::createRNG (const Pass * P) const
Get a RandomNumberGenerator salted for use with this module.
The RNG can be seeded via -rng-seed=<uint64> and is salted with the ModuleID and the provided pass salt. The returned RNG should not be shared across threads or passes.
A unique RNG per pass ensures a reproducible random stream even when other randomness consuming passes are added or removed. In addition, the random stream will be reproducible across LLVM versions when the pass does not change.
Definition at line 66 of file Module.cpp.
References llvm::sys::path::filename(), getModuleIdentifier(), and llvm::Pass::getPassName().
void Module::dematerialize (GlobalValue * GV)
If the GlobalValue is read in, and if the GVMaterializer supports it, release the memory for the function, and set it up to be materialized lazily.
If !isDematerializable(), this method is a no-op.
Definition at line 397 of file Module.cpp.
Referenced by llvm::GlobalValue::dematerialize().
void Module::dropAllReferences ()
This function causes all the subinstructions to "let go" of all references that they are maintaining.
This allows one to 'delete' a whole class at a time, even though there may be circular references... first all references are dropped, and all use counts go to zero. Then everything is delete'd for real. Note that no operations are valid on an object that has "dropped all references", except operator delete.
Definition at line 447 of file Module.cpp.
References aliases(), llvm::Function::dropAllReferences(), F(), and globals().
Referenced by ~Module().
void Module::dropTriviallyDeadConstantArrays ()
Destroy ConstantArrays in LLVMContext if they are not used.
ConstantArrays constructed during linking can cause quadratic memory explosion. Releasing all unused constants can cause a 20% LTO compile-time slowdown for a large application.
NOTE: Constants are currently owned by LLVMContext. This can then only be called where all uses of the LLVMContext are understood.
Definition at line 183 of file LLVMContextImpl.cpp.
References llvm::LLVMContextImpl::dropTriviallyDeadConstantArrays(), and llvm::LLVMContext::pImpl.
LLVM_DUMP_METHOD void Module::dump () const
Dump the module to stderr (for debugging).
Definition at line 3265 of file AsmWriter.cpp.
References llvm::dbgs(), and print().
bool llvm::Module::empty () const [inline]
Definition at line 548 of file Module.h.
iterator llvm::Module::end () [inline]
Definition at line 541 of file Module.h.
Referenced by llvm::IntrinsicLowering::AddPrototypes(), llvm::ExecutionEngine::clearGlobalMappingsFromModule(), llvm::CloneModule(), LLVMGetFirstFunction(), LLVMGetLastFunction(), LLVMGetNextFunction(), llvm::TypeFinder::run(), StripSymbolNames(), llvm::verifyModule(), llvm::InstVisitor< ObjectSizeOffsetVisitor, SizeOffsetType >::visit(), and WriteModule().
const_iterator llvm::Module::end () const [inline]
Definition at line 542 of file Module.h.
void Module::eraseNamedMetadata (NamedMDNode * NMD)
Remove the given NamedMDNode from this module and delete it.
eraseNamedMetadata - Remove the given NamedMDNode from this module and delete it.
Definition at line 275 of file Module.cpp.
References llvm::iplist< NodeTy, Traits >::erase(), and llvm::NamedMDNode::getName().
Referenced by llvm::NamedMDNode::eraseFromParent().
iterator_range<iterator> llvm::Module::functions () [inline]
Definition at line 550 of file Module.h.
References llvm::iplist< NodeTy, Traits >::begin().
Referenced by llvm::AsmPrinter::doInitialization().
iterator_range<const_iterator> llvm::Module::functions () const [inline]
Definition at line 553 of file Module.h.
References llvm::iplist< NodeTy, Traits >::begin().
const AliasListType& llvm::Module::getAliasList () const [inline]
Get the Module's list of aliases (constant).
Definition at line 500 of file Module.h.
Referenced by llvm::GlobalAlias::eraseFromParent(), and llvm::GlobalAlias::removeFromParent().
AliasListType& llvm::Module::getAliasList () [inline]
Get the Module's list of aliases.
Definition at line 502 of file Module.h.
const ComdatSymTabType& llvm::Module::getComdatSymbolTable () const [inline]
Get the Module's symbol table for COMDATs (constant).
Definition at line 518 of file Module.h.
Referenced by rewriteComdat().
ComdatSymTabType& llvm::Module::getComdatSymbolTable () [inline]
Get the Module's symbol table for COMDATs.
Definition at line 520 of file Module.h.
LLVMContext& llvm::Module::getContext () const [inline]
Get the global data context.
Returns:
LLVMContext - a container for LLVM's global information
Definition at line 259 of file Module.h.
Referenced by llvm::LTOCodeGenerator::addModule(), llvm::IntrinsicLowering::AddPrototypes(), appendToGlobalArray(), assureFPCallStub(), llvm::CloneModule(), createFPFnStub(), createFree(), CreateGCRelocates(), createPrivateGlobalForSourceLoc(), createPrivateGlobalForString(), createPrivateNonConstGlobalForString(), llvm::createSanitizerCtorAndInitFunctions(), llvm::EmitFPutC(), llvm::EmitFPutS(), llvm::EmitFWrite(), EmitGCCInlineAsmStr(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::EmitMemChr(), llvm::EmitMemCmp(), llvm::EmitMemCpyChk(), EmitMSInlineAsmStr(), llvm::EmitPutS(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::EmitStrChr(), llvm::EmitStrCpy(), llvm::EmitStrLen(), llvm::EmitStrNCmp(), llvm::EmitStrNCpy(), llvm::EmitStrNLen(), EnsureFPIntrinsicsExist(), findBasePointer(), fixupFPReturnAndCall(), llvm::objcarc::ARCMDKindCache::get(), llvm::Intrinsic::getDeclaration(), getTypeByName(), InsertSafepointPoll(), insertUseHolderAfter(), llvm::Linker::Linker(), llvm::legacy::PassManagerImpl::run(), llvm::LTOCodeGenerator::setModule(), SwitchToLookupTable(), and llvm::UpgradeDebugInfo().
const DataLayout & Module::getDataLayout () const
Get the data layout for the module's target platform.
Definition at line 372 of file Module.cpp.
Referenced by AddAlignmentAssumptions(), llvm::IVUsers::AddUsersImpl(), AllCallersPassInValidPointerForArgument(), AnalyzeLoadFromClobberingStore(), llvm::objcarc::CanAlterRefCount(), llvm::objcarc::CanUse(), checkStringCopyLibFuncSignature(), llvm::CloneModule(), combineInstructionsOverFunction(), EmitCamlGlobal(), llvm::LazyValueInfo::eraseBlock(), llvm::FindAvailableLoadedValue(), FindLoopCounter(), findPHIToPartitionLoops(), llvm::MemoryLocation::get(), llvm::LazyValueInfo::getConstant(), llvm::LazyValueInfo::getConstantOnEdge(), llvm::ScalarEvolution::getEffectiveSCEVType(), getGEPInductionOperand(), llvm::LoopAccessAnalysis::getInfo(), llvm::MemoryDependenceAnalysis::getLoadLoadClobberFullWidthSize(), GetLoadValueForLoad(), llvm::Mangler::getNameWithPrefix(), llvm::ScalarEvolution::getOffsetOfExpr(), llvm::MemoryDependenceAnalysis::getPointerDependencyFrom(), llvm::LazyValueInfo::getPredicateAt(), llvm::LazyValueInfo::getPredicateOnEdge(), llvm::ScalarEvolution::getSizeOfExpr(), getStrideFromPointer(), llvm::ScalarEvolution::getTypeSizeInBits(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), HandleByValArgument(), HandleByValArgumentInit(), llvm::hoistRegion(), llvm::DataLayout::init(), InlineCallIfPossible(), llvm::InlineFunction(), llvm::isInductionPHI(), isLoadLoadClobberIfExtendedToFullWidth(), isSafePHIToSpeculate(), isSafeSelectToSpeculate(), llvm::isSafeToLoadUnconditionally(), llvm::isSafeToSpeculativelyExecute(), llvm::isStridedPtr(), replaceAndRecursivelySimplifyImpl(), llvm::LibCallAliasAnalysis::runOnFunction(), llvm::LazyValueInfo::runOnFunction(), llvm::SimplifyCFG(), simplifyOneLoop(), llvm::LazyValueInfo::threadEdge(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopProlog(), and visitIVCast().
const std::string llvm::Module::getDataLayoutStr () const [inline]
Get the data layout string for the module's target platform.
This is equivalent to getDataLayout()->getStringRepresentation().
Definition at line 246 of file Module.h.
Referenced by WriteModuleInfo().
unsigned Module::getDwarfVersion () const
Returns the Dwarf Version by checking module flags.
Definition at line 458 of file Module.cpp.
References llvm::dwarf::DWARF_VERSION, and getModuleFlag().
Referenced by llvm::DwarfDebug::DwarfDebug().
Function * Module::getFunction (StringRef Name) const
Look up the specified function in the module symbol table.
If it does not exist, return null.
Definition at line 188 of file Module.cpp.
References getNamedValue().
Referenced by assureFPCallStub(), FindCXAAtExit(), llvm::MCJIT::findModuleForSymbol(), llvm::SparcTargetLowering::getSRetArgSize(), llvm::MachineModuleInfo::getWinEHParent(), hasReturnsTwiceAttr(), InsertSafepointPoll(), llvm::MIRParserImpl::parseMachineFunction(), and llvm::StripDebugInfo().
const FunctionListType& llvm::Module::getFunctionList () const [inline]
Get the Module's list of functions (constant).
Definition at line 493 of file Module.h.
Referenced by llvm::Function::eraseFromParent(), llvm::Function::removeFromParent(), and llvm::CallGraph::removeFunctionFromModule().
FunctionListType& llvm::Module::getFunctionList () [inline]
Get the Module's list of functions.
Definition at line 495 of file Module.h.
const GlobalListType& llvm::Module::getGlobalList () const [inline]
Get the Module's list of global variables (constant).
Definition at line 486 of file Module.h.
Referenced by llvm::NVPTXAsmPrinter::doFinalization(), llvm::GlobalVariable::eraseFromParent(), llvm::GlobalVariable::GlobalVariable(), OptimizeGlobalAddressOfMalloc(), llvm::GlobalVariable::removeFromParent(), SRAGlobal(), and TryToShrinkGlobalToBoolean().
GlobalListType& llvm::Module::getGlobalList () [inline]
Get the Module's list of global variables.
Definition at line 488 of file Module.h.
GlobalVariable* llvm::Module::getGlobalVariable (StringRef Name) const [inline]
Look up the specified global variable in the module symbol table.
If it does not exist, return null. If AllowInternal is set to true, this function will return types that have InternalLinkage. By default, these types are not returned.
Definition at line 367 of file Module.h.
Referenced by llvm::collectUsedGlobalVariables(), llvm::MCJIT::findModuleForSymbol(), getNamedGlobal(), and StripSymbolNames().
GlobalVariable* llvm::Module::getGlobalVariable (StringRef Name, bool AllowInternal) const [inline]
Definition at line 371 of file Module.h.
GlobalVariable * Module::getGlobalVariable (StringRef Name, bool AllowLocal = false)
getGlobalVariable - Look up the specified global variable in the module symbol table.
If it does not exist, return null. The type argument should be the underlying type of the global, i.e., it should not have the top-level PointerType, which represents the address of the global. If AllowLocal is set to true, this function will return types that have an local. By default, these types are not returned.
Definition at line 203 of file Module.cpp.
References getNamedValue().
std::vector< StructType * > Module::getIdentifiedStructTypes () const
Definition at line 426 of file Module.cpp.
References llvm::TypeFinder::begin(), llvm::TypeFinder::end(), llvm::MipsISD::Ret, and llvm::TypeFinder::run().
GVMaterializer* llvm::Module::getMaterializer () const [inline]
Retrieves the GVMaterializer, if any, for this Module.
Definition at line 458 of file Module.h.
unsigned Module::getMDKindID (StringRef Name) const
Return a unique non-zero ID for the specified metadata kind.
getMDKindID - Return a unique non-zero ID for the specified metadata kind.
This ID is uniqued across modules in the current LLVMContext.
Definition at line 94 of file Module.cpp.
References llvm::LLVMContext::getMDKindID().
Referenced by llvm::UpgradeIntrinsicCall().
void Module::getMDKindNames (SmallVectorImpl< StringRef > & Result) const
Populate client supplied SmallVector with the name for custom metadata IDs registered in this LLVMContext.
getMDKindNames - Populate client supplied SmallVector with the name for custom metadata IDs registered in this LLVMContext.
ID #0 is not used, so it is filled in as an empty string.
Definition at line 101 of file Module.cpp.
References llvm::LLVMContext::getMDKindNames().
Referenced by WriteModuleMetadataStore().
Metadata * Module::getModuleFlag (StringRef Key) const
Return the corresponding value if Key appears in module flags, otherwise return null.
Definition at line 313 of file Module.cpp.
References getModuleFlagsMetadata().
Referenced by llvm::getDebugMetadataVersionFromModule(), getDwarfVersion(), and getPICLevel().
void Module::getModuleFlagsMetadata (SmallVectorImpl< ModuleFlagEntry > & Flags) const
Returns the module flags in the provided vector.
getModuleFlagsMetadata - Returns the module flags in the provided vector.
Definition at line 293 of file Module.cpp.
References getModuleFlagsMetadata(), isValidModFlagBehavior(), llvm::NamedMDNode::operands(), and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
NamedMDNode * Module::getModuleFlagsMetadata () const
Returns the NamedMDNode in the module that represents module-level flags.
getModuleFlagsMetadata - Returns the NamedMDNode in the module that represents module-level flags.
This method returns null if there are no module-level flags.
Definition at line 326 of file Module.cpp.
References getNamedMetadata().
Referenced by getModuleFlag(), and getModuleFlagsMetadata().
const std::string& llvm::Module::getModuleIdentifier () const [inline]
Get the module identifier which is, essentially, the name of the module.
Returns:
the module identifier as a string
Definition at line 236 of file Module.h.
Referenced by llvm::CloneModule(), createRNG(), llvm::AsmPrinter::doInitialization(), EmitCamlGlobal(), llvm::LazyCallGraph::LazyCallGraph(), llvm::DiagnosticPrinterRawOStream::operator<<(), and llvm::LazyCallGraphPrinterPass::run().
const std::string& llvm::Module::getModuleInlineAsm () const [inline]
Get any module-scope inline assembly blocks.
Returns:
a string containing the module-scope inline assembly blocks.
Definition at line 263 of file Module.h.
Referenced by llvm::CloneModule(), llvm::AsmPrinter::doInitialization(), llvm::NVPTXAsmPrinter::doInitialization(), llvm::ARMAsmPrinter::EmitStartOfAsmFile(), and WriteModuleInfo().
StringRef llvm::Module::getName () const [inline]
Get a short "name" for the module.
This is useful for debugging or logging. It is essentially a convenience wrapper around getModuleIdentifier().
Definition at line 242 of file Module.h.
GlobalAlias * Module::getNamedAlias (StringRef Name) const
Return the global alias in the module with the specified name, of arbitrary type.
This method returns null if a global with the specified name is not found.
Definition at line 246 of file Module.cpp.
References getNamedValue().
GlobalVariable* llvm::Module::getNamedGlobal (StringRef Name) [inline]
Return the global variable in the module with the specified name, of arbitrary type.
This method returns null if a global with the specified name is not found.
Definition at line 380 of file Module.h.
References getGlobalVariable().
Referenced by appendToGlobalArray(), llvm::orc::getConstructors(), llvm::orc::getDestructors(), and llvm::ExecutionEngine::runStaticConstructorsDestructors().
const GlobalVariable* llvm::Module::getNamedGlobal (StringRef Name) const [inline]
Definition at line 383 of file Module.h.
const NamedMDListType& llvm::Module::getNamedMDList () const [inline]
Get the Module's list of named metadata (constant).
Definition at line 507 of file Module.h.
NamedMDListType& llvm::Module::getNamedMDList () [inline]
Get the Module's list of named metadata.
Definition at line 509 of file Module.h.
NamedMDNode * Module::getNamedMetadata (const Twine & Name) const
Return the first NamedMDNode in the module with the specified name.
getNamedMetadata - Return the first NamedMDNode in the module with the specified name.
This method returns null if a NamedMDNode with the specified name is not found.
Definition at line 253 of file Module.cpp.
References lookup(), and llvm::Twine::toStringRef().
Referenced by llvm::DwarfDebug::beginModule(), cacheAnnotationFromMD(), getModuleFlagsMetadata(), hasDebugInfo(), llvm::makeSubprogramMap(), llvm::DebugInfoFinder::processModule(), and llvm::WinCodeViewLineTables::WinCodeViewLineTables().
GlobalValue * Module::getNamedValue (StringRef Name) const
Return the global value in the module with the specified name, of arbitrary type.
getNamedValue - Return the first global value in the module with the specified name, of arbitrary type.
This method returns null if a global with the specified name is not found.
Definition at line 88 of file Module.cpp.
References getValueSymbolTable(), and llvm::ValueSymbolTable::lookup().
Referenced by forceRenaming(), getComdatGVForCOFF(), getFunction(), getGlobalVariable(), getNamedAlias(), getOrInsertFunction(), getOrInsertGlobal(), and llvm::objcarc::ModuleHasARC().
Comdat * Module::getOrInsertComdat (StringRef Name)
Return the Comdat in the module with the specified name.
It is created if it didn't already exist.
Definition at line 465 of file Module.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::insert().
Referenced by rewriteComdat().
Constant * Module::getOrInsertFunction (StringRef Name, FunctionType * T, AttributeSet AttributeList)
Look up the specified function in the module symbol table.
Four possibilities: 1. If it does not exist, add a prototype for the function and return it. 2. If it exists, and has a local linkage, the existing function is renamed and a new one is inserted. 3. Otherwise, if the existing function has the correct prototype, return the existing function. 4. Finally, the function exists but has the wrong prototype: return the function with a constantexpr cast to the right prototype.
Definition at line 115 of file Module.cpp.
References llvm::Function::Create(), llvm::GlobalValue::ExternalLinkage, F(), llvm::ConstantExpr::getBitCast(), getNamedValue(), llvm::GlobalValue::getType(), llvm::PointerType::getUnqual(), llvm::Function::isIntrinsic(), llvm::iplist< NodeTy, Traits >::push_back(), and llvm::Function::setAttributes().
Referenced by llvm::IntrinsicLowering::AddPrototypes(), createFree(), createMalloc(), llvm::createSanitizerCtorAndInitFunctions(), llvm::EmitBinaryFloatFnCall(), llvm::EmitFPutC(), llvm::EmitFPutS(), llvm::EmitFWrite(), llvm::EmitMemChr(), llvm::EmitMemCmp(), llvm::EmitMemCpyChk(), llvm::EmitPutChar(), llvm::EmitPutS(), llvm::EmitStrChr(), llvm::EmitStrCpy(), llvm::EmitStrLen(), llvm::EmitStrNCmp(), llvm::EmitStrNCpy(), llvm::EmitStrNLen(), llvm::EmitUnaryFloatFnCall(), EnsureFunctionExists(), fixupFPReturnAndCall(), llvm::Intrinsic::getDeclaration(), getOrInsertFunction(), insertSinCosCall(), insertUseHolderAfter(), and ReplaceCallWith().
Constant * Module::getOrInsertFunction (StringRef Name, FunctionType * T)
Definition at line 138 of file Module.cpp.
References getOrInsertFunction().
Constant * Module::getOrInsertFunction (StringRef Name, AttributeSet AttributeList, Type * RetTy, ...)
Look up the specified function in the module symbol table.
If it does not exist, add a prototype for the function and return it. This function guarantees to return a constant of pointer to the specified function type or a ConstantExpr BitCast of that type if the named function has a different type. This version of the method takes a null terminated list of function arguments, which makes it easier for clients to use.
Definition at line 148 of file Module.cpp.
References llvm::FunctionType::get(), and getOrInsertFunction().
Constant * Module::getOrInsertFunction (StringRef Name, Type * RetTy, ...)
Same as above, but without the attributes.
Definition at line 167 of file Module.cpp.
References llvm::FunctionType::get(), and getOrInsertFunction().
Constant * Module::getOrInsertGlobal (StringRef Name, Type * Ty)
Look up the specified global in the module symbol table.
getOrInsertGlobal - Look up the specified global in the module symbol table.
1. If it does not exist, add a declaration of the global and return it. 2. Else, the global exists but has the wrong type: return the function with a constantexpr cast to the right type. 3. Finally, if the existing global is the correct declaration, return the existing global.
Definition at line 217 of file Module.cpp.
References llvm::GlobalValue::ExternalLinkage, llvm::PointerType::get(), llvm::ConstantExpr::getBitCast(), getNamedValue(), llvm::Type::getPointerAddressSpace(), and llvm::GlobalValue::getType().
Referenced by CreatePrologue().
NamedMDNode * Module::getOrInsertModuleFlagsMetadata ()
Returns the NamedMDNode in the module that represents module-level flags.
getOrInsertModuleFlagsMetadata - Returns the NamedMDNode in the module that represents module-level flags.
If module-level flags aren't found, it creates the named metadata that contains them.
Definition at line 333 of file Module.cpp.
References getOrInsertNamedMetadata().
Referenced by addModuleFlag().
NamedMDNode * Module::getOrInsertNamedMetadata (StringRef Name)
Return the named MDNode in the module with the specified name.
getOrInsertNamedMetadata - Return the first named MDNode in the module with the specified name.
This method returns a new NamedMDNode if a NamedMDNode with the specified name is not found.
Definition at line 262 of file Module.cpp.
References llvm::ilist< NodeTy >::push_back().
Referenced by llvm::CloneModule(), llvm::DIBuilder::createCompileUnit(), and getOrInsertModuleFlagsMetadata().
PICLevel::Level Module::getPICLevel () const
Returns the PIC level (small or large model)
Definition at line 471 of file Module.cpp.
References Default, and getModuleFlag().
static GlobalListType Module::* llvm::Module::getSublistAccess (GlobalVariable *) [inline, static]
Definition at line 489 of file Module.h.
static FunctionListType Module::* llvm::Module::getSublistAccess (Function *) [inline, static]
Definition at line 496 of file Module.h.
static AliasListType Module::* llvm::Module::getSublistAccess (GlobalAlias *) [inline, static]
Definition at line 503 of file Module.h.
static NamedMDListType Module::* llvm::Module::getSublistAccess (NamedMDNode *) [inline, static]
Definition at line 510 of file Module.h.
const std::string& llvm::Module::getTargetTriple () const [inline]
Get the target triple which is a string describing the target host.
Returns:
a string containing the target triple.
Definition at line 255 of file Module.h.
Referenced by llvm::CloneModule(), llvm::LTOModule::getTargetTriple(), llvm::orc::OrcX86_64::insertCompileCallbackTrampolines(), llvm::orc::OrcX86_64::insertResolverBlock(), insertSinCosCall(), llvm::TargetLibraryAnalysis::run(), llvm::WriteBitcodeToFile(), and WriteModuleInfo().
StructType * Module::getTypeByName (StringRef Name) const
Return the type with the specified name, or null if there is none by that name.
getTypeByName - Return the type with the specified name, or null if there is none by that name.
Definition at line 622 of file Type.cpp.
References getContext(), llvm::StringMap< ValueTy, AllocatorTy >::lookup(), llvm::LLVMContextImpl::NamedStructTypes, and llvm::LLVMContext::pImpl.
const ValueSymbolTable& llvm::Module::getValueSymbolTable () const [inline]
Get the symbol table of global variable and function identifiers.
Definition at line 514 of file Module.h.
Referenced by getNamedValue(), and WriteModule().
ValueSymbolTable& llvm::Module::getValueSymbolTable () [inline]
Get the Module's symbol table of global variable and function identifiers.
Definition at line 516 of file Module.h.
global_iterator llvm::Module::global_begin () [inline]
Definition at line 524 of file Module.h.
Referenced by llvm::ExecutionEngine::clearGlobalMappingsFromModule(), llvm::CloneModule(), LLVMGetFirstGlobal(), LLVMGetLastGlobal(), LLVMGetPreviousGlobal(), llvm::TypeFinder::run(), and StripSymbolNames().
const_global_iterator llvm::Module::global_begin () const [inline]
Definition at line 525 of file Module.h.
bool llvm::Module::global_empty () const [inline]
Definition at line 528 of file Module.h.
global_iterator llvm::Module::global_end () [inline]
Definition at line 526 of file Module.h.
Referenced by llvm::ExecutionEngine::clearGlobalMappingsFromModule(), llvm::CloneModule(), LLVMGetFirstGlobal(), LLVMGetLastGlobal(), LLVMGetNextGlobal(), llvm::TypeFinder::run(), and StripSymbolNames().
const_global_iterator llvm::Module::global_end () const [inline]
Definition at line 527 of file Module.h.
iterator_range<global_iterator> llvm::Module::globals () [inline]
Definition at line 530 of file Module.h.
Referenced by llvm::AsmPrinter::computeGlobalGOTEquivs(), llvm::AsmPrinter::doFinalization(), dropAllReferences(), llvm::ExecutionEngine::emitGlobals(), orderModule(), predictUseListOrder(), llvm::Inliner::removeDeadFunctions(), llvm::ValueEnumerator::ValueEnumerator(), and WriteModuleInfo().
iterator_range<const_global_iterator> llvm::Module::globals () const [inline]
Definition at line 533 of file Module.h.
bool Module::isDematerializable (const GlobalValue * GV) const
Returns true if this GV was loaded from this Module's GVMaterializer and the GVMaterializer knows how to dematerialize the GV.
Definition at line 384 of file Module.cpp.
Referenced by llvm::GlobalValue::isDematerializable().
bool Module::isValidModFlagBehavior (Metadata * MD, ModFlagBehavior & MFB) [static]
Checks if Metadata represents a valid ModFlagBehavior, and stores the converted result in MFB.
Definition at line 280 of file Module.cpp.
References ModFlagBehaviorFirstVal, and ModFlagBehaviorLastVal.
Referenced by getModuleFlagsMetadata().
std::error_code Module::materialize (GlobalValue * GV)
Make sure the GlobalValue is fully read.
If the module is corrupt, this returns true and fills in the optional string with information about the problem. If successful, this returns false.
Definition at line 390 of file Module.cpp.
Referenced by llvm::GlobalValue::materialize().
std::error_code Module::materializeAll ()
Make sure all GlobalValues in this Module are fully read.
Definition at line 402 of file Module.cpp.
Referenced by materializeAllPermanently().
std::error_code Module::materializeAllPermanently ()
Make sure all GlobalValues in this Module are fully read and clear the Materializer.
If the module is corrupt, this DOES NOT clear the old Materializer.
Definition at line 408 of file Module.cpp.
References materializeAll().
std::error_code Module::materializeMetadata ()
Definition at line 416 of file Module.cpp.
iterator_range<named_metadata_iterator> llvm::Module::named_metadata () [inline]
Definition at line 588 of file Module.h.
References llvm::iplist< NodeTy, Traits >::begin().
Referenced by WriteModuleMetadata().
iterator_range<const_named_metadata_iterator> llvm::Module::named_metadata () const [inline]
Definition at line 592 of file Module.h.
References llvm::iplist< NodeTy, Traits >::begin().
named_metadata_iterator llvm::Module::named_metadata_begin () [inline]
Definition at line 575 of file Module.h.
References llvm::iplist< NodeTy, Traits >::rend().
Referenced by llvm::CloneModule(), llvm::TypeFinder::run(), and llvm::StripDebugInfo().
const_named_metadata_iterator llvm::Module::named_metadata_begin () const [inline]
Definition at line 576 of file Module.h.
References llvm::iplist< NodeTy, Traits >::rend().
bool llvm::Module::named_metadata_empty () const [inline]
Definition at line 586 of file Module.h.
Referenced by WriteModuleMetadata().
named_metadata_iterator llvm::Module::named_metadata_end () [inline]
Definition at line 580 of file Module.h.
Referenced by llvm::CloneModule(), llvm::TypeFinder::run(), and llvm::StripDebugInfo().
const_named_metadata_iterator llvm::Module::named_metadata_end () const [inline]
Definition at line 581 of file Module.h.
size_t llvm::Module::named_metadata_size () const [inline]
Definition at line 585 of file Module.h.
void Module::print (raw_ostream & OS, AssemblyAnnotationWriter * AAW, bool ShouldPreserveUseListOrder = false) const
Print the module to an output stream with an optional AssemblyAnnotationWriter.
If ShouldPreserveUseListOrder, then include uselistorder directives so that use-lists can be recreated when reading the assembly.
Definition at line 3103 of file AsmWriter.cpp.
Referenced by dump(), llvm::operator<<(), llvm::yaml::BlockScalarTraits< Module >::output(), and llvm::PrintModulePass::run().
reverse_iterator llvm::Module::rbegin () [inline]
Definition at line 543 of file Module.h.
Referenced by predictUseListOrder().
const_reverse_iterator llvm::Module::rbegin () const [inline]
Definition at line 544 of file Module.h.
reverse_iterator llvm::Module::rend () [inline]
Definition at line 545 of file Module.h.
Referenced by predictUseListOrder().
const_reverse_iterator llvm::Module::rend () const [inline]
Definition at line 546 of file Module.h.
void Module::setDataLayout (StringRef Desc)
Set the data layout.
Definition at line 366 of file Module.cpp.
References llvm::DataLayout::reset().
Referenced by llvm::CloneModule(), llvm::MCJIT::generateCodeForModule(), LLVMTargetMachineEmit(), and llvm::LTOCodeGenerator::optimize().
void Module::setDataLayout (const DataLayout & Other)
Definition at line 370 of file Module.cpp.
References Other.
void Module::setMaterializer (GVMaterializer * GVM)
Sets the GVMaterializer to GVM.
This module must not yet have a Materializer. To reset the materializer for a module that already has one, call MaterializeAllPermanently first. Destroying this module will destroy its materializer without materializing any more GlobalValues. Without destroying the Module, there is no way to detach or destroy a materializer without materializing all the GVs it controls, to avoid leaving orphan unmaterialized GVs.
Definition at line 377 of file Module.cpp.
Referenced by getBitcodeModuleImpl().
void llvm::Module::setModuleIdentifier (StringRef ID) [inline]
Set the module identifier.
Definition at line 279 of file Module.h.
void llvm::Module::setModuleInlineAsm (StringRef Asm) [inline]
Set the module-scope inline assembly blocks.
A trailing newline is added if the input doesn't have one.
Definition at line 290 of file Module.h.
Referenced by llvm::CloneModule().
void Module::setPICLevel (PICLevel::Level PL)
Set the PIC level (small or large model)
Definition at line 481 of file Module.cpp.
References addModuleFlag(), and llvm::lltok::Error.
void llvm::Module::setTargetTriple (StringRef T) [inline]
Set the target triple.
Definition at line 286 of file Module.h.
Referenced by llvm::CloneModule(), and llvm::LTOModule::setTargetTriple().
size_t llvm::Module::size () const [inline]
Definition at line 547 of file Module.h.
Friends And Related Function Documentation
friend class Constant [friend]
Definition at line 222 of file Module.h.
The documentation for this class was generated from the following files:
Module.h
AsmWriter.cpp
LLVMContextImpl.cpp
Module.cpp
Type.cpp