LLVM: llvm::DWARFDebugLoc Class Reference
llvm::DWARFDebugLoc Class Reference
#include <DWARFDebugLoc.h>
Classes
struct Entry
A single location within a location list.
struct LocationList
A list of locations that contain one variable.
Public Member Functions
DWARFDebugLoc (const RelocAddrMap &LocRelocMap)
void dump (raw_ostream &OS) const
Print the location lists found within the debug_loc section.
void parse (DataExtractor data, unsigned AddressSize)
Parse the debug_loc section accessible via the 'data' parameter using the specified address size to interpret the address ranges.
Detailed Description
Definition at line 21 of file DWARFDebugLoc.h.
Constructor & Destructor Documentation
llvm::DWARFDebugLoc::DWARFDebugLoc (const RelocAddrMap & LocRelocMap) [inline]
Definition at line 51 of file DWARFDebugLoc.h.
Member Function Documentation
void DWARFDebugLoc::dump (raw_ostream & OS) const
Print the location lists found within the debug_loc section.
Definition at line 18 of file DWARFDebugLoc.cpp.
References llvm::format(), and llvm::raw_ostream::indent().
void DWARFDebugLoc::parse (DataExtractor data, unsigned AddressSize)
Parse the debug_loc section accessible via the 'data' parameter using the specified address size to interpret the address ranges.
Definition at line 38 of file DWARFDebugLoc.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::StringRef::begin(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::StringRef::end(), llvm::errs(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::DataExtractor::getData(), llvm::DataExtractor::getU16(), llvm::DataExtractor::getUnsigned(), if(), llvm::DataExtractor::isValidOffset(), llvm::SmallVectorImpl< T >::resize(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::StringRef::substr().
The documentation for this class was generated from the following files:
DWARFDebugLoc.h
DWARFDebugLoc.cpp