LLVM: llvm::PPCFunctionInfo Class Reference
llvm::PPCFunctionInfo Class Reference
PPCFunctionInfo - This class is derived from MachineFunction private PowerPC target-specific information for each MachineFunction.
#include <PPCMachineFunctionInfo.h>
Public Member Functions
PPCFunctionInfo (MachineFunction &MF)
int getFramePointerSaveIndex () const
void setFramePointerSaveIndex (int Idx)
int getReturnAddrSaveIndex () const
void setReturnAddrSaveIndex (int idx)
int getBasePointerSaveIndex () const
void setBasePointerSaveIndex (int Idx)
int getPICBasePointerSaveIndex () const
void setPICBasePointerSaveIndex (int Idx)
unsigned getMinReservedArea () const
void setMinReservedArea (unsigned size)
int getTailCallSPDelta () const
void setTailCallSPDelta (int size)
void setMustSaveLR (bool U)
MustSaveLR - This is set when the prolog/epilog inserter does its initial scan of the function.
bool mustSaveLR () const
void setHasSpills ()
bool hasSpills () const
void setHasNonRISpills ()
bool hasNonRISpills () const
void setSpillsCR ()
bool isCRSpilled () const
void setSpillsVRSAVE ()
bool isVRSAVESpilled () const
void setLRStoreRequired ()
bool isLRStoreRequired () const
void setUsesTOCBasePtr ()
bool usesTOCBasePtr () const
void setHasFastCall ()
bool hasFastCall () const
int getVarArgsFrameIndex () const
void setVarArgsFrameIndex (int Index)
int getVarArgsStackOffset () const
void setVarArgsStackOffset (int Offset)
unsigned getVarArgsNumGPR () const
void setVarArgsNumGPR (unsigned Num)
unsigned getVarArgsNumFPR () const
void setVarArgsNumFPR (unsigned Num)
int getCRSpillFrameIndex () const
void setCRSpillFrameIndex (int idx)
const SmallVectorImpl< unsigned > & getMustSaveCRs () const
void addMustSaveCR (unsigned Reg)
void setUsesPICBase (bool uses)
bool usesPICBase () const
MCSymbol * getPICOffsetSymbol () const
Detailed Description
PPCFunctionInfo - This class is derived from MachineFunction private PowerPC target-specific information for each MachineFunction.
Definition at line 23 of file PPCMachineFunctionInfo.h.
Constructor & Destructor Documentation
llvm::PPCFunctionInfo::PPCFunctionInfo (MachineFunction & MF) [inline, explicit]
Definition at line 108 of file PPCMachineFunctionInfo.h.
Member Function Documentation
void llvm::PPCFunctionInfo::addMustSaveCR (unsigned Reg) [inline]
Definition at line 194 of file PPCMachineFunctionInfo.h.
References llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by llvm::PPCFrameLowering::spillCalleeSavedRegisters().
int llvm::PPCFunctionInfo::getBasePointerSaveIndex () const [inline]
Definition at line 136 of file PPCMachineFunctionInfo.h.
Referenced by llvm::PPCFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitPrologue(), llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan(), and llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized().
int llvm::PPCFunctionInfo::getCRSpillFrameIndex () const [inline]
Definition at line 189 of file PPCMachineFunctionInfo.h.
Referenced by llvm::PPCRegisterInfo::hasReservedSpillSlot().
int llvm::PPCFunctionInfo::getFramePointerSaveIndex () const [inline]
Definition at line 130 of file PPCMachineFunctionInfo.h.
Referenced by llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::PPCFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitPrologue(), llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan(), and llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized().
unsigned llvm::PPCFunctionInfo::getMinReservedArea () const [inline]
Definition at line 142 of file PPCMachineFunctionInfo.h.
Referenced by CalculateTailCallSPDiff(), and llvm::PPCFrameLowering::emitEpilogue().
const SmallVectorImpl<unsigned>& llvm::PPCFunctionInfo::getMustSaveCRs () const [inline]
Definition at line 193 of file PPCMachineFunctionInfo.h.
Referenced by llvm::PPCFrameLowering::emitEpilogue(), and llvm::PPCFrameLowering::emitPrologue().
int llvm::PPCFunctionInfo::getPICBasePointerSaveIndex () const [inline]
Definition at line 139 of file PPCMachineFunctionInfo.h.
Referenced by llvm::PPCFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitPrologue(), llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan(), and llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized().
MCSymbol * PPCFunctionInfo::getPICOffsetSymbol () const
Definition at line 20 of file PPCMachineFunctionInfo.cpp.
References llvm::DL, llvm::MachineFunction::getContext(), llvm::TargetMachine::getDataLayout(), llvm::MachineFunction::getFunctionNumber(), llvm::MCContext::getOrCreateSymbol(), llvm::DataLayout::getPrivateGlobalPrefix(), and llvm::MachineFunction::getTarget().
int llvm::PPCFunctionInfo::getReturnAddrSaveIndex () const [inline]
Definition at line 133 of file PPCMachineFunctionInfo.h.
int llvm::PPCFunctionInfo::getTailCallSPDelta () const [inline]
Definition at line 145 of file PPCMachineFunctionInfo.h.
Referenced by llvm::PPCFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan(), and llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized().
int llvm::PPCFunctionInfo::getVarArgsFrameIndex () const [inline]
Definition at line 177 of file PPCMachineFunctionInfo.h.
unsigned llvm::PPCFunctionInfo::getVarArgsNumFPR () const [inline]
Definition at line 186 of file PPCMachineFunctionInfo.h.
unsigned llvm::PPCFunctionInfo::getVarArgsNumGPR () const [inline]
Definition at line 183 of file PPCMachineFunctionInfo.h.
int llvm::PPCFunctionInfo::getVarArgsStackOffset () const [inline]
Definition at line 180 of file PPCMachineFunctionInfo.h.
bool llvm::PPCFunctionInfo::hasFastCall () const [inline]
Definition at line 175 of file PPCMachineFunctionInfo.h.
Referenced by llvm::PPCFrameLowering::emitEpilogue().
bool llvm::PPCFunctionInfo::hasNonRISpills () const [inline]
Definition at line 160 of file PPCMachineFunctionInfo.h.
Referenced by hasNonRISpills().
bool llvm::PPCFunctionInfo::hasSpills () const [inline]
Definition at line 157 of file PPCMachineFunctionInfo.h.
Referenced by hasSpills().
bool llvm::PPCFunctionInfo::isCRSpilled () const [inline]
Definition at line 163 of file PPCMachineFunctionInfo.h.
Referenced by spillsCR().
bool llvm::PPCFunctionInfo::isLRStoreRequired () const [inline]
Definition at line 169 of file PPCMachineFunctionInfo.h.
Referenced by MustSaveLR().
bool llvm::PPCFunctionInfo::isVRSAVESpilled () const [inline]
Definition at line 166 of file PPCMachineFunctionInfo.h.
Referenced by spillsVRSAVE().
bool llvm::PPCFunctionInfo::mustSaveLR () const [inline]
Definition at line 154 of file PPCMachineFunctionInfo.h.
Referenced by llvm::PPCFrameLowering::emitEpilogue(), and llvm::PPCFrameLowering::emitPrologue().
void llvm::PPCFunctionInfo::setBasePointerSaveIndex (int Idx) [inline]
Definition at line 137 of file PPCMachineFunctionInfo.h.
Referenced by llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan().
void llvm::PPCFunctionInfo::setCRSpillFrameIndex (int idx) [inline]
Definition at line 190 of file PPCMachineFunctionInfo.h.
Referenced by llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan().
void llvm::PPCFunctionInfo::setFramePointerSaveIndex (int Idx) [inline]
Definition at line 131 of file PPCMachineFunctionInfo.h.
Referenced by llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan().
void llvm::PPCFunctionInfo::setHasFastCall () [inline]
Definition at line 174 of file PPCMachineFunctionInfo.h.
void llvm::PPCFunctionInfo::setHasNonRISpills () [inline]
Definition at line 159 of file PPCMachineFunctionInfo.h.
Referenced by fixupFuncForFI(), llvm::PPCInstrInfo::loadRegFromStackSlot(), and llvm::PPCInstrInfo::storeRegToStackSlot().
void llvm::PPCFunctionInfo::setHasSpills () [inline]
Definition at line 156 of file PPCMachineFunctionInfo.h.
Referenced by llvm::PPCInstrInfo::loadRegFromStackSlot(), and llvm::PPCInstrInfo::storeRegToStackSlot().
void llvm::PPCFunctionInfo::setLRStoreRequired () [inline]
Definition at line 168 of file PPCMachineFunctionInfo.h.
void llvm::PPCFunctionInfo::setMinReservedArea (unsigned size) [inline]
Definition at line 143 of file PPCMachineFunctionInfo.h.
References size.
void llvm::PPCFunctionInfo::setMustSaveLR (bool U) [inline]
MustSaveLR - This is set when the prolog/epilog inserter does its initial scan of the function.
It is true if the LR/LR8 register is ever explicitly defined/clobbered in the machine function (e.g. by calls and movpctolr, which is used in PIC generation), or if the LR stack slot is explicitly referenced by builtin_return_address.
Definition at line 153 of file PPCMachineFunctionInfo.h.
Referenced by llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan().
void llvm::PPCFunctionInfo::setPICBasePointerSaveIndex (int Idx) [inline]
Definition at line 140 of file PPCMachineFunctionInfo.h.
Referenced by llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan().
void llvm::PPCFunctionInfo::setReturnAddrSaveIndex (int idx) [inline]
Definition at line 134 of file PPCMachineFunctionInfo.h.
void llvm::PPCFunctionInfo::setSpillsCR () [inline]
Definition at line 162 of file PPCMachineFunctionInfo.h.
Referenced by llvm::PPCInstrInfo::loadRegFromStackSlot(), llvm::PPCFrameLowering::spillCalleeSavedRegisters(), and llvm::PPCInstrInfo::storeRegToStackSlot().
void llvm::PPCFunctionInfo::setSpillsVRSAVE () [inline]
Definition at line 165 of file PPCMachineFunctionInfo.h.
Referenced by llvm::PPCInstrInfo::loadRegFromStackSlot(), and llvm::PPCInstrInfo::storeRegToStackSlot().
void llvm::PPCFunctionInfo::setTailCallSPDelta (int size) [inline]
Definition at line 146 of file PPCMachineFunctionInfo.h.
References size.
Referenced by CalculateTailCallSPDiff().
void llvm::PPCFunctionInfo::setUsesPICBase (bool uses) [inline]
Definition at line 196 of file PPCMachineFunctionInfo.h.
void llvm::PPCFunctionInfo::setUsesTOCBasePtr () [inline]
Definition at line 171 of file PPCMachineFunctionInfo.h.
Referenced by setUsesTOCBasePtr().
void llvm::PPCFunctionInfo::setVarArgsFrameIndex (int Index) [inline]
Definition at line 178 of file PPCMachineFunctionInfo.h.
void llvm::PPCFunctionInfo::setVarArgsNumFPR (unsigned Num) [inline]
Definition at line 187 of file PPCMachineFunctionInfo.h.
void llvm::PPCFunctionInfo::setVarArgsNumGPR (unsigned Num) [inline]
Definition at line 184 of file PPCMachineFunctionInfo.h.
void llvm::PPCFunctionInfo::setVarArgsStackOffset (int Offset) [inline]
Definition at line 181 of file PPCMachineFunctionInfo.h.
bool llvm::PPCFunctionInfo::usesPICBase () const [inline]
Definition at line 197 of file PPCMachineFunctionInfo.h.
Referenced by llvm::PPCFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitPrologue(), llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan(), and llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized().
bool llvm::PPCFunctionInfo::usesTOCBasePtr () const [inline]
Definition at line 172 of file PPCMachineFunctionInfo.h.
Referenced by llvm::PPCRegisterInfo::getReservedRegs().
The documentation for this class was generated from the following files:
PPCMachineFunctionInfo.h
PPCMachineFunctionInfo.cpp