LLVM: llvm::tool_output_file Class Reference
llvm::tool_output_file Class Reference
This class contains a raw_fd_ostream and adds a few extra features commonly needed for compiler-like tool output files:
#include <ToolOutputFile.h>
Classes
class CleanupInstaller
This class is declared before the raw_fd_ostream so that it is constructed before the raw_fd_ostream is constructed and destructed after the raw_fd_ostream is destructed.
Public Member Functions
tool_output_file (StringRef Filename, std::error_code &EC, sys::fs::OpenFlags Flags)
This constructor's arguments are passed to to raw_fd_ostream's constructor.
tool_output_file (StringRef Filename, int FD)
raw_fd_ostream & os ()
Return the contained raw_fd_ostream.
void keep ()
Indicate that the tool's job wrt this output file has been successful and the file should not be deleted.
Detailed Description
This class contains a raw_fd_ostream and adds a few extra features commonly needed for compiler-like tool output files:
The file is automatically deleted if the process is killed.
The file is automatically deleted when the tool_output_file object is destroyed unless the client calls keep().
Definition at line 26 of file ToolOutputFile.h.
Constructor & Destructor Documentation
tool_output_file::tool_output_file (StringRef Filename, std::error_code & EC, sys::fs::OpenFlags Flags)
This constructor's arguments are passed to to raw_fd_ostream's constructor.
Definition at line 37 of file ToolOutputFile.cpp.
tool_output_file::tool_output_file (StringRef Filename, int FD)
Definition at line 45 of file ToolOutputFile.cpp.
Member Function Documentation
void llvm::tool_output_file::keep () [inline]
Indicate that the tool's job wrt this output file has been successful and the file should not be deleted.
Definition at line 58 of file ToolOutputFile.h.
Referenced by createDependencyFile(), llvm::TableGenMain(), llvm::writeArchive(), and llvm::LTOCodeGenerator::writeMergedModules().
raw_fd_ostream& llvm::tool_output_file::os () [inline]
Return the contained raw_fd_ostream.
Definition at line 54 of file ToolOutputFile.h.
Referenced by createDependencyFile(), llvm::TableGenMain(), llvm::writeArchive(), and llvm::LTOCodeGenerator::writeMergedModules().
The documentation for this class was generated from the following files:
ToolOutputFile.h
ToolOutputFile.cpp