LLVM: llvm::InstrItineraryData Class Reference
llvm::InstrItineraryData Class Reference
Itinerary data supplied by a subtarget to be used by a target.
#include <MCInstrItineraries.h>
Public Member Functions
InstrItineraryData ()
Ctors.
InstrItineraryData (const MCSchedModel &SM, const InstrStage *S, const unsigned *OS, const unsigned *F)
bool isEmpty () const
Returns true if there are no itineraries.
bool isEndMarker (unsigned ItinClassIndx) const
Returns true if the index is for the end marker itinerary.
const InstrStage * beginStage (unsigned ItinClassIndx) const
Return the first stage of the itinerary.
const InstrStage * endStage (unsigned ItinClassIndx) const
Return the last+1 stage of the itinerary.
unsigned getStageLatency (unsigned ItinClassIndx) const
Return the total stage latency of the given class.
int getOperandCycle (unsigned ItinClassIndx, unsigned OperandIdx) const
Return the cycle for the given class and operand.
bool hasPipelineForwarding (unsigned DefClass, unsigned DefIdx, unsigned UseClass, unsigned UseIdx) const
Return true if there is a pipeline forwarding between instructions of itinerary classes DefClass and UseClasses so that value produced by an instruction of itinerary class DefClass, operand index DefIdx can be bypassed when it's read by an instruction of itinerary class UseClass, operand index UseIdx.
int getOperandLatency (unsigned DefClass, unsigned DefIdx, unsigned UseClass, unsigned UseIdx) const
Compute and return the use operand latency of a given itinerary class and operand index if the value is produced by an instruction of the specified itinerary class and def operand index.
int getNumMicroOps (unsigned ItinClassIndx) const
Return the number of micro-ops that the given class decodes to.
Public Attributes
MCSchedModel SchedModel
Basic machine properties.
const InstrStage * Stages
Array of stages selected.
const unsigned * OperandCycles
Array of operand cycles selected.
const unsigned * Forwardings
Array of pipeline forwarding pathes.
const InstrItinerary * Itineraries
Array of itineraries selected.
Detailed Description
Itinerary data supplied by a subtarget to be used by a target.
Definition at line 109 of file MCInstrItineraries.h.
Constructor & Destructor Documentation
llvm::InstrItineraryData::InstrItineraryData () [inline]
Ctors.
Definition at line 118 of file MCInstrItineraries.h.
llvm::InstrItineraryData::InstrItineraryData (const MCSchedModel & SM, const InstrStage * S, const unsigned * OS, const unsigned * F) [inline]
Definition at line 122 of file MCInstrItineraries.h.
Member Function Documentation
const InstrStage* llvm::InstrItineraryData::beginStage (unsigned ItinClassIndx) const [inline]
Return the first stage of the itinerary.
Definition at line 137 of file MCInstrItineraries.h.
References llvm::InstrItinerary::FirstStage, Itineraries, and Stages.
Referenced by llvm::DFAPacketizer::canReserveResources(), llvm::ScoreboardHazardRecognizer::EmitInstruction(), llvm::ScoreboardHazardRecognizer::getHazardType(), getStageLatency(), llvm::DFAPacketizer::reserveResources(), and llvm::ScoreboardHazardRecognizer::ScoreboardHazardRecognizer().
const InstrStage* llvm::InstrItineraryData::endStage (unsigned ItinClassIndx) const [inline]
Return the last+1 stage of the itinerary.
Definition at line 143 of file MCInstrItineraries.h.
References Itineraries, llvm::InstrItinerary::LastStage, and Stages.
Referenced by llvm::ScoreboardHazardRecognizer::EmitInstruction(), llvm::ScoreboardHazardRecognizer::getHazardType(), getStageLatency(), and llvm::ScoreboardHazardRecognizer::ScoreboardHazardRecognizer().
int llvm::InstrItineraryData::getNumMicroOps (unsigned ItinClassIndx) const [inline]
Return the number of micro-ops that the given class decodes to.
Return -1 for classes that require dynamic lookup via TargetInstrInfo.
Definition at line 230 of file MCInstrItineraries.h.
References isEmpty(), Itineraries, and llvm::InstrItinerary::NumMicroOps.
Referenced by llvm::TargetSchedModel::getNumMicroOps(), llvm::ARMBaseInstrInfo::getNumMicroOps(), and getNumMicroOpsSwiftLdSt().
int llvm::InstrItineraryData::getOperandCycle (unsigned ItinClassIndx, unsigned OperandIdx) const [inline]
Return the cycle for the given class and operand.
Return -1 if no cycle is specified for the operand.
Definition at line 169 of file MCInstrItineraries.h.
References llvm::InstrItinerary::FirstOperandCycle, isEmpty(), Itineraries, llvm::InstrItinerary::LastOperandCycle, and OperandCycles.
Referenced by llvm::TargetSchedModel::computeOperandLatency(), llvm::TargetInstrInfo::computeOperandLatency(), getItineraryLatency(), getOperandLatency(), llvm::ARMBaseInstrInfo::getOperandLatency(), llvm::TargetInstrInfo::getOperandLatency(), llvm::ARMTargetLowering::getSchedulingPreference(), and llvm::TargetInstrInfo::hasLowDefLatency().
int llvm::InstrItineraryData::getOperandLatency (unsigned DefClass, unsigned DefIdx, unsigned UseClass, unsigned UseIdx) const [inline]
Compute and return the use operand latency of a given itinerary class and operand index if the value is produced by an instruction of the specified itinerary class and def operand index.
Definition at line 207 of file MCInstrItineraries.h.
References getOperandCycle(), hasPipelineForwarding(), and isEmpty().
Referenced by llvm::TargetInstrInfo::getOperandLatency().
unsigned llvm::InstrItineraryData::getStageLatency (unsigned ItinClassIndx) const [inline]
Return the total stage latency of the given class.
The latency is the maximum completion time for any stage in the itinerary. If no stages exist, it defaults to one cycle.
Definition at line 151 of file MCInstrItineraries.h.
References beginStage(), endStage(), and isEmpty().
Referenced by llvm::TargetInstrInfo::getInstrLatency().
bool llvm::InstrItineraryData::hasPipelineForwarding (unsigned DefClass, unsigned DefIdx, unsigned UseClass, unsigned UseIdx) const [inline]
Return true if there is a pipeline forwarding between instructions of itinerary classes DefClass and UseClasses so that value produced by an instruction of itinerary class DefClass, operand index DefIdx can be bypassed when it's read by an instruction of itinerary class UseClass, operand index UseIdx.
Definition at line 186 of file MCInstrItineraries.h.
References llvm::InstrItinerary::FirstOperandCycle, Forwardings, Itineraries, and llvm::InstrItinerary::LastOperandCycle.
Referenced by getOperandLatency().
bool llvm::InstrItineraryData::isEmpty () const [inline]
Returns true if there are no itineraries.
Definition at line 128 of file MCInstrItineraries.h.
References Itineraries.
Referenced by llvm::TargetInstrInfo::computeDefOperandLatency(), llvm::ScheduleDAGSDNodes::computeLatency(), llvm::TargetInstrInfo::computeOperandLatency(), llvm::ScoreboardHazardRecognizer::EmitInstruction(), llvm::ScoreboardHazardRecognizer::getHazardType(), llvm::TargetInstrInfo::getInstrLatency(), getNumMicroOps(), llvm::ARMBaseInstrInfo::getNumMicroOps(), llvm::TargetInstrInfo::getNumMicroOps(), getOperandCycle(), getOperandLatency(), llvm::ARMBaseInstrInfo::getOperandLatency(), llvm::TargetInstrInfo::getOperandLatency(), llvm::ARMTargetLowering::getSchedulingPreference(), getStageLatency(), llvm::TargetSchedModel::hasInstrItineraries(), llvm::TargetInstrInfo::hasLowDefLatency(), and llvm::ScoreboardHazardRecognizer::ScoreboardHazardRecognizer().
bool llvm::InstrItineraryData::isEndMarker (unsigned ItinClassIndx) const [inline]
Returns true if the index is for the end marker itinerary.
Definition at line 131 of file MCInstrItineraries.h.
References Itineraries.
Referenced by llvm::ScoreboardHazardRecognizer::ScoreboardHazardRecognizer().
Member Data Documentation
const unsigned* llvm::InstrItineraryData::Forwardings
Array of pipeline forwarding pathes.
Definition at line 114 of file MCInstrItineraries.h.
Referenced by hasPipelineForwarding().
const InstrItinerary* llvm::InstrItineraryData::Itineraries
Array of itineraries selected.
Definition at line 115 of file MCInstrItineraries.h.
Referenced by beginStage(), endStage(), getNumMicroOps(), llvm::TargetInstrInfo::getNumMicroOps(), getOperandCycle(), hasPipelineForwarding(), isEmpty(), and isEndMarker().
const unsigned* llvm::InstrItineraryData::OperandCycles
Array of operand cycles selected.
Definition at line 113 of file MCInstrItineraries.h.
Referenced by getOperandCycle().
MCSchedModel llvm::InstrItineraryData::SchedModel
Basic machine properties.
Definition at line 111 of file MCInstrItineraries.h.
Referenced by llvm::TargetInstrInfo::computeDefOperandLatency(), llvm::TargetInstrInfo::computeOperandLatency(), llvm::ResourcePriorityQueue::reserveResources(), and llvm::ScoreboardHazardRecognizer::ScoreboardHazardRecognizer().
const InstrStage* llvm::InstrItineraryData::Stages
Array of stages selected.
Definition at line 112 of file MCInstrItineraries.h.
Referenced by beginStage(), and endStage().
The documentation for this class was generated from the following file:
MCInstrItineraries.h