LLVM: llvm::MCDwarfFrameEmitter Class Reference
llvm::MCDwarfFrameEmitter Class Reference
#include <MCDwarf.h>
Static Public Member Functions
static void Emit (MCObjectStreamer &streamer, MCAsmBackend *MAB, bool isEH)
static void EmitAdvanceLoc (MCObjectStreamer &Streamer, uint64_t AddrDelta)
static void EncodeAdvanceLoc (MCContext &Context, uint64_t AddrDelta, raw_ostream &OS)
Detailed Description
Definition at line 480 of file MCDwarf.h.
Member Function Documentation
void MCDwarfFrameEmitter::Emit (MCObjectStreamer & streamer, MCAsmBackend * MAB, bool isEH) [static]
Definition at line 1493 of file MCDwarf.cpp.
References llvm::MCDwarfFrameInfo::CompactUnwindEncoding, llvm::MCContext::createTempSymbol(), llvm::MCObjectStreamer::EmitLabel(), llvm::MCObjectStreamer::EmitValueToAlignment(), llvm::MCStreamer::generateCompactUnwindEncodings(), llvm::MCContext::getAsmInfo(), llvm::MCObjectFileInfo::getCompactUnwindDwarfEHFrameOnly(), llvm::MCObjectFileInfo::getCompactUnwindSection(), llvm::MCStreamer::getContext(), llvm::MCStreamer::getDwarfFrameInfos(), llvm::MCObjectFileInfo::getDwarfFrameSection(), llvm::MCContext::getObjectFileInfo(), llvm::MCAsmInfo::getPointerSize(), llvm::MCObjectFileInfo::getSupportsCompactUnwindWithoutEHFrame(), llvm::MCDwarfFrameInfo::IsSignalFrame, llvm::MCDwarfFrameInfo::IsSimple, llvm::MCDwarfFrameInfo::Lsda, llvm::MCDwarfFrameInfo::LsdaEncoding, llvm::MCDwarfFrameInfo::Personality, llvm::MCDwarfFrameInfo::PersonalityEncoding, llvm::ARMBuildAttrs::Section, llvm::ArrayRef< T >::size(), and llvm::MCStreamer::SwitchSection().
Referenced by llvm::MCObjectStreamer::EmitFrames().
void MCDwarfFrameEmitter::EmitAdvanceLoc (MCObjectStreamer & Streamer, uint64_t AddrDelta) [static]
Definition at line 1570 of file MCDwarf.cpp.
References llvm::MCObjectStreamer::EmitBytes(), EncodeAdvanceLoc(), llvm::MCStreamer::getContext(), and llvm::raw_svector_ostream::str().
Referenced by llvm::MCObjectStreamer::EmitDwarfAdvanceFrameAddr().
void MCDwarfFrameEmitter::EncodeAdvanceLoc (MCContext & Context, uint64_t AddrDelta, raw_ostream & OS) [static]
Definition at line 1579 of file MCDwarf.cpp.
References llvm::dwarf::DW_CFA_advance_loc, llvm::dwarf::DW_CFA_advance_loc1, llvm::dwarf::DW_CFA_advance_loc2, llvm::dwarf::DW_CFA_advance_loc4, llvm::MCContext::getAsmInfo(), llvm::MCAsmInfo::isLittleEndian(), llvm::isUInt< 16 >(), llvm::isUInt< 32 >(), llvm::isUInt< 8 >(), llvm::isUIntN(), ScaleAddrDelta(), and llvm::support::endian::Writer< endian >::write().
Referenced by EmitAdvanceLoc().
The documentation for this class was generated from the following files:
MCDwarf.h
MCDwarf.cpp