LLVM: llvm::SequentialType Class Reference
llvm::SequentialType Class Reference
SequentialType - This is the superclass of the array, pointer and vector type classes.
#include <DerivedTypes.h>
Public Member Functions
Type * getElementType () const
Static Public Member Functions
static bool classof (const Type *T)
Methods for support type inquiry through isa, cast, and dyn_cast.
Protected Member Functions
SequentialType (TypeID TID, Type *ElType)
Detailed Description
SequentialType - This is the superclass of the array, pointer and vector type classes.
All of these represent "arrays" in memory. The array type represents a specifically sized array, pointer types are unsized/unknown size arrays, vector types represent specifically sized arrays that allow for use of SIMD instructions. SequentialType holds the common features of all, which stem from the fact that all three lay their components out in memory identically.
Definition at line 310 of file DerivedTypes.h.
Constructor & Destructor Documentation
llvm::SequentialType::SequentialType (TypeID TID, Type * ElType) [inline, protected]
Definition at line 316 of file DerivedTypes.h.
References llvm::Type::ContainedTys, and llvm::Type::NumContainedTys.
Member Function Documentation
static bool llvm::SequentialType::classof (const Type * T) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast.
Reimplemented from llvm::CompositeType.
Reimplemented in llvm::PointerType, llvm::VectorType, and llvm::ArrayType.
Definition at line 326 of file DerivedTypes.h.
References llvm::Type::ArrayTyID, llvm::Type::getTypeID(), llvm::Type::PointerTyID, and llvm::Type::VectorTyID.
Type* llvm::SequentialType::getElementType () const [inline]
Definition at line 323 of file DerivedTypes.h.
References llvm::Type::ContainedTys.
Referenced by appendToGlobalArray(), BitCastConstantVector(), llvm::orc::cloneFunctionDecl(), llvm::orc::cloneGlobalVariableDecl(), computeKnownBitsFromOperator(), llvm::ConstantArray::ConstantArray(), llvm::ConstantFoldCastInstruction(), ConstantFoldGetElementPtrImpl(), ConstantFoldVectorCall(), llvm::ConstantVector::ConstantVector(), copyGlobalVariableProto(), llvm::IRBuilderBase::CreateGCStatepointCall(), llvm::IRBuilderBase::CreateGCStatepointInvoke(), emitGlobalConstantDataSequential(), emitGlobalConstantVector(), llvm::AsmPrinter::EmitGlobalVariable(), llvm::ExecutionEngine::EmitGlobalVariable(), fixupFPReturnAndCall(), FoldBitCast(), FoldReinterpretLoadFromConstPtr(), llvm::ConstantExpr::getAddrSpaceCast(), llvm::Constant::getAllOnesValue(), llvm::getConstantStringInfo(), llvm::ExecutionEngine::getConstantValue(), llvm::VectorType::getDoubleElementsVectorType(), llvm::ConstantDataSequential::getElementType(), llvm::EVT::getEVT(), llvm::VectorType::getExtendedElementVectorType(), llvm::ConstantInt::getFalse(), llvm::InlineAsm::getFunctionType(), llvm::VectorType::getHalfElementsVectorType(), llvm::VectorType::getInteger(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getInterleavedMemoryOpCost(), llvm::getMallocAllocatedType(), getNaturalGEPWithOffset(), getOpenCLAlignment(), llvm::DataLayout::getPreferredAlignment(), llvm::NVPTXTargetLowering::getPrototype(), getStrideFromPointer(), llvm::AArch64TargetLowering::getTgtMemIntrinsic(), llvm::ARMTargetLowering::getTgtMemIntrinsic(), llvm::ConstantInt::getTrue(), llvm::VectorType::getTruncatedElementVectorType(), llvm::DataLayout::getTypeSizeInBits(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::GlobalValue::getValueType(), llvm::TargetLoweringBase::getValueType(), llvm::MVT::getVT(), HandleByValArgument(), HasPadding(), INITIALIZE_PASS(), InsertSafepointPoll(), isArray(), llvm::Type::isEmptyTy(), isGEPFoldable(), llvm::HexagonTargetObjectFile::IsGlobalInSmallSection(), llvm::MipsTargetObjectFile::IsGlobalInSmallSectionImpl(), isHomogeneousAggregate(), llvm::isImageOrSamplerVal(), isLeakCheckerRoot(), llvm::isSafeToLoadUnconditionally(), llvm::ShuffleVectorInst::isValidOperands(), isVectorPromotionViable(), isVectorPromotionViableForSlice(), isZero(), llvm::ExecutionEngine::LoadValueFromMemory(), llvm::NVPTXTargetLowering::LowerCall(), llvm::FastISel::lowerCall(), llvm::FastISel::lowerCallTo(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::TargetLowering::LowerCallTo(), OptimizeGlobalAddressOfMalloc(), OptimizeIntegerToVectorInsertions(), OptimizeIntToFloatBitCast(), OptimizeVectorResize(), llvm::TargetLowering::ParseConstraints(), PerformHeapAllocSRoA(), ScalarizeMaskedLoad(), ScalarizeMaskedStore(), llvm::GlobalVariable::setInitializer(), StripPtrCastKeepAS(), TryToShrinkGlobalToBoolean(), upgradeGlobalArray(), llvm::InstCombiner::visitAddrSpaceCast(), llvm::Interpreter::visitAllocaInst(), llvm::ObjectSizeOffsetVisitor::visitArgument(), llvm::InstCombiner::visitBitCast(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::ObjectSizeOffsetVisitor::visitGlobalVariable(), llvm::InstCombiner::visitLandingPadInst(), llvm::InstCombiner::visitShuffleVectorInst(), and WriteTypeTable().
The documentation for this class was generated from the following file:
DerivedTypes.h