LLVM: llvm::PMTopLevelManager Class Reference
llvm::PMTopLevelManager Class Reference
PMTopLevelManager manages LastUser info and collects common APIs used by top level pass managers.
#include <LegacyPassManagers.h>
Public Member Functions
void schedulePass (Pass *P)
Schedule pass P for execution.
void setLastUser (ArrayRef< Pass * > AnalysisPasses, Pass *P)
Set pass P as the last user of the given analysis passes.
void collectLastUses (SmallVectorImpl< Pass * > &LastUses, Pass *P)
Collect passes whose last user is P.
Pass * findAnalysisPass (AnalysisID AID)
Find the pass that implements Analysis AID.
const PassInfo * findAnalysisPassInfo (AnalysisID AID) const
Retrieve the PassInfo for an analysis.
AnalysisUsage * findAnalysisUsage (Pass *P)
Find analysis usage information for the pass P.
virtual ~PMTopLevelManager ()
Destructor.
void addImmutablePass (ImmutablePass *P)
Add immutable pass and initialize it.
SmallVectorImpl< ImmutablePass * > & getImmutablePasses ()
void addPassManager (PMDataManager *Manager)
void addIndirectPassManager (PMDataManager *Manager)
void dumpPasses () const
void dumpArguments () const
Public Attributes
PMStack activeStack
Protected Member Functions
PMTopLevelManager (PMDataManager *PMDM)
Initialize top level manager. Create first pass manager.
unsigned getNumContainedManagers () const
void initializeAllAnalysisInfo ()
Protected Attributes
SmallVector< PMDataManager *, 8 > PassManagers
Collection of pass managers.
Detailed Description
PMTopLevelManager manages LastUser info and collects common APIs used by top level pass managers.
Definition at line 167 of file LegacyPassManagers.h.
Constructor & Destructor Documentation
PMTopLevelManager::PMTopLevelManager (PMDataManager * PMDM) [explicit, protected]
Initialize top level manager. Create first pass manager.
Definition at line 497 of file LegacyPassManager.cpp.
References llvm::PMDataManager::setTopLevelManager().
PMTopLevelManager::~PMTopLevelManager () [virtual]
Destructor.
Definition at line 796 of file LegacyPassManager.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::SmallVectorTemplateCommon< T, typename >::end(), I, and PassManagers.
Member Function Documentation
void llvm::PMTopLevelManager::addImmutablePass (ImmutablePass * P) [inline]
Add immutable pass and initialize it.
Definition at line 207 of file LegacyPassManagers.h.
References llvm::ImmutablePass::initializePass(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by schedulePass().
void llvm::PMTopLevelManager::addIndirectPassManager (PMDataManager * Manager) [inline]
Definition at line 222 of file LegacyPassManagers.h.
References llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by llvm::LoopPass::assignPassManager(), llvm::CallGraphSCCPass::assignPassManager(), llvm::RegionPass::assignPassManager(), llvm::FunctionPass::assignPassManager(), and llvm::BasicBlockPass::assignPassManager().
void llvm::PMTopLevelManager::addPassManager (PMDataManager * Manager) [inline]
Definition at line 216 of file LegacyPassManagers.h.
References PassManagers, and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
void PMTopLevelManager::collectLastUses (SmallVectorImpl< Pass * > & LastUses, Pass * P)
Collect passes whose last user is P.
Definition at line 556 of file LegacyPassManager.cpp.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::end(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by llvm::PMDataManager::dumpLastUses(), and llvm::PMDataManager::removeDeadPasses().
void PMTopLevelManager::dumpArguments () const
Definition at line 751 of file LegacyPassManager.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::dbgs(), llvm::SmallVectorTemplateCommon< T, typename >::end(), findAnalysisPassInfo(), I, PassDebugging, and PassManagers.
Referenced by llvm::PMDataManager::addLowerLevelRequiredPass(), llvm::legacy::FunctionPassManagerImpl::doInitialization(), and llvm::legacy::PassManagerImpl::run().
void PMTopLevelManager::dumpPasses () const
Definition at line 733 of file LegacyPassManager.cpp.
References PassDebugging, PassManagers, and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::PMDataManager::addLowerLevelRequiredPass(), llvm::legacy::FunctionPassManagerImpl::doInitialization(), and llvm::legacy::PassManagerImpl::run().
Pass * PMTopLevelManager::findAnalysisPass (AnalysisID AID)
Find the pass that implements Analysis AID.
Search immutable passes and all pass managers. If desired pass is not found then return NULL.
Definition at line 688 of file LegacyPassManager.cpp.
References findAnalysisPassInfo(), llvm::PassInfo::getInterfacesImplemented(), I, P, PassManagers, llvm::SmallVectorTemplateCommon< T, typename >::rbegin(), and llvm::SmallVectorTemplateCommon< T, typename >::rend().
Referenced by llvm::PMDataManager::findAnalysisPass(), and schedulePass().
const PassInfo * PMTopLevelManager::findAnalysisPassInfo (AnalysisID AID) const
Retrieve the PassInfo for an analysis.
Definition at line 721 of file LegacyPassManager.cpp.
References llvm::PassRegistry::getPassInfo(), and llvm::PassRegistry::getPassRegistry().
Referenced by llvm::PMDataManager::add(), dumpArguments(), llvm::PMDataManager::dumpPassArguments(), findAnalysisPass(), llvm::PMDataManager::freePass(), llvm::PMDataManager::recordAvailableAnalysis(), and schedulePass().
AnalysisUsage * PMTopLevelManager::findAnalysisUsage (Pass * P)
Find analysis usage information for the pass P.
Definition at line 570 of file LegacyPassManager.cpp.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and llvm::Pass::getAnalysisUsage().
Referenced by llvm::PMDataManager::collectRequiredAnalysis(), llvm::PMDataManager::initializeAnalysisImpl(), llvm::PMDataManager::preserveHigherLevelAnalysis(), llvm::PMDataManager::removeNotPreservedAnalysis(), schedulePass(), and llvm::PMDataManager::verifyPreservedAnalysis().
SmallVectorImpl<ImmutablePass *>& llvm::PMTopLevelManager::getImmutablePasses () [inline]
Definition at line 212 of file LegacyPassManagers.h.
Referenced by llvm::legacy::FunctionPassManagerImpl::doFinalization(), llvm::legacy::FunctionPassManagerImpl::doInitialization(), and llvm::legacy::PassManagerImpl::run().
unsigned llvm::PMTopLevelManager::getNumContainedManagers () const [inline, protected]
Definition at line 171 of file LegacyPassManagers.h.
References PassManagers, and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::legacy::FunctionPassManagerImpl::doFinalization(), llvm::legacy::FunctionPassManagerImpl::doInitialization(), llvm::legacy::FunctionPassManagerImpl::releaseMemoryOnTheFly(), llvm::legacy::FunctionPassManagerImpl::run(), and llvm::legacy::PassManagerImpl::run().
void PMTopLevelManager::initializeAllAnalysisInfo () [protected]
Definition at line 770 of file LegacyPassManager.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), and PassManagers.
Referenced by llvm::legacy::FunctionPassManagerImpl::run(), and llvm::legacy::PassManagerImpl::run().
void PMTopLevelManager::schedulePass (Pass * P)
Schedule pass P for execution.
Make sure that passes required by P are run before P is run. Update analysis info maintained by the manager. Remove dead passes. This is a recursive function.
Definition at line 586 of file LegacyPassManager.cpp.
References activeStack, addImmutablePass(), llvm::Pass::assignPassManager(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::PassInfo::createPass(), llvm::Pass::createPrinterPass(), llvm::dbgs(), llvm::SmallVectorTemplateCommon< T, typename >::end(), findAnalysisPass(), findAnalysisPassInfo(), findAnalysisUsage(), llvm::Pass::getAsImmutablePass(), llvm::Pass::getPassID(), llvm::Pass::getPassName(), llvm::Pass::getPotentialPassManagerType(), llvm::AnalysisUsage::getRequiredSet(), I, llvm::PMDataManager::initializeAnalysisImpl(), llvm::IP, llvm::PassInfo::isAnalysis(), llvm::Pass::preparePassManager(), llvm::PMDataManager::recordAvailableAnalysis(), llvm::Pass::setResolver(), ShouldPrintAfterPass(), and ShouldPrintBeforePass().
Referenced by llvm::LoopPass::assignPassManager(), llvm::CallGraphSCCPass::assignPassManager(), and llvm::RegionPass::assignPassManager().
void PMTopLevelManager::setLastUser (ArrayRef< Pass * > AnalysisPasses, Pass * P)
Set pass P as the last user of the given analysis passes.
Definition at line 505 of file LegacyPassManager.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::PMDataManager::getAsPass(), llvm::PMDataManager::getDepth(), llvm::AnalysisResolver::getPMDataManager(), llvm::AnalysisUsage::getRequiredTransitiveSet(), llvm::Pass::getResolver(), I, and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Referenced by llvm::PMDataManager::add().
Member Data Documentation
PMStack llvm::PMTopLevelManager::activeStack
Definition at line 231 of file LegacyPassManagers.h.
Referenced by llvm::RGPassManager::runOnFunction(), llvm::LPPassManager::runOnFunction(), and schedulePass().
SmallVector<PMDataManager *, 8> llvm::PMTopLevelManager::PassManagers [protected]
Collection of pass managers.
Definition at line 236 of file LegacyPassManagers.h.
Referenced by addPassManager(), dumpArguments(), dumpPasses(), findAnalysisPass(), getNumContainedManagers(), initializeAllAnalysisInfo(), and ~PMTopLevelManager().
The documentation for this class was generated from the following files:
LegacyPassManagers.h
LegacyPassManager.cpp