LLVM: llvm::MDAttachmentMap Class Reference
llvm::MDAttachmentMap Class Reference
Map-like storage for metadata attachments.
#include <LLVMContextImpl.h>
Public Member Functions
bool empty () const
size_t size () const
MDNode * lookup (unsigned ID) const
Get a particular attachment (if any).
void set (unsigned ID, MDNode &MD)
Set an attachment to a particular node.
void erase (unsigned ID)
Remove an attachment.
void getAll (SmallVectorImpl< std::pair< unsigned, MDNode * >> &Result) const
Copy out all the attachments.
template<class PredTy >
void remove_if (PredTy shouldRemove)
Erase matching attachments.
Detailed Description
Map-like storage for metadata attachments.
Definition at line 858 of file LLVMContextImpl.h.
Member Function Documentation
bool llvm::MDAttachmentMap::empty () const [inline]
Definition at line 862 of file LLVMContextImpl.h.
References llvm::SmallVectorBase::empty().
Referenced by erase().
void MDAttachmentMap::erase (unsigned ID)
Remove an attachment.
Remove the attachment at ID, if any.
Definition at line 1003 of file Metadata.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), I, and llvm::SmallVectorTemplateBase< T, isPodLike >::pop_back().
void MDAttachmentMap::getAll (SmallVectorImpl< std::pair< unsigned, MDNode * >> & Result) const
Copy out all the attachments.
Copies all the current attachments into Result, sorting by attachment ID. This function does not clear Result.
Definition at line 1029 of file Metadata.cpp.
References llvm::array_pod_sort(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorTemplateCommon< T, typename >::end().
MDNode * MDAttachmentMap::lookup (unsigned ID) const
Get a particular attachment (if any).
Definition at line 1022 of file Metadata.cpp.
References I.
template<class PredTy > void llvm::MDAttachmentMap::remove_if (PredTy shouldRemove) [inline]
Erase matching attachments.
Erases all attachments matching the shouldRemove predicate.
Definition at line 888 of file LLVMContextImpl.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), and llvm::SmallVectorImpl< T >::erase().
void MDAttachmentMap::set (unsigned ID, MDNode & MD)
Set an attachment to a particular node.
Set the ID attachment to MD, replacing the current attachment at ID (if anyway).
Definition at line 993 of file Metadata.cpp.
References I.
size_t llvm::MDAttachmentMap::size () const [inline]
Definition at line 863 of file LLVMContextImpl.h.
References llvm::SmallVectorTemplateCommon< T, typename >::size().
The documentation for this class was generated from the following files:
LLVMContextImpl.h
Metadata.cpp