LLVM: llvm::TargetFolder Class Reference
llvm::TargetFolder Class Reference
TargetFolder - Create constants with target dependent folding.
#include <TargetFolder.h>
Public Member Functions
TargetFolder (const DataLayout &DL)
Constant * CreateAdd (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const
Constant * CreateFAdd (Constant *LHS, Constant *RHS) const
Constant * CreateSub (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const
Constant * CreateFSub (Constant *LHS, Constant *RHS) const
Constant * CreateMul (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const
Constant * CreateFMul (Constant *LHS, Constant *RHS) const
Constant * CreateUDiv (Constant *LHS, Constant *RHS, bool isExact=false) const
Constant * CreateSDiv (Constant *LHS, Constant *RHS, bool isExact=false) const
Constant * CreateFDiv (Constant *LHS, Constant *RHS) const
Constant * CreateURem (Constant *LHS, Constant *RHS) const
Constant * CreateSRem (Constant *LHS, Constant *RHS) const
Constant * CreateFRem (Constant *LHS, Constant *RHS) const
Constant * CreateShl (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const
Constant * CreateLShr (Constant *LHS, Constant *RHS, bool isExact=false) const
Constant * CreateAShr (Constant *LHS, Constant *RHS, bool isExact=false) const
Constant * CreateAnd (Constant *LHS, Constant *RHS) const
Constant * CreateOr (Constant *LHS, Constant *RHS) const
Constant * CreateXor (Constant *LHS, Constant *RHS) const
Constant * CreateBinOp (Instruction::BinaryOps Opc, Constant *LHS, Constant *RHS) const
Constant * CreateNeg (Constant *C, bool HasNUW=false, bool HasNSW=false) const
Constant * CreateFNeg (Constant *C) const
Constant * CreateNot (Constant *C) const
Constant * CreateGetElementPtr (Type *Ty, Constant *C, ArrayRef< Constant * > IdxList) const
Constant * CreateGetElementPtr (Type *Ty, Constant *C, Constant *Idx) const
Constant * CreateGetElementPtr (Type *Ty, Constant *C, ArrayRef< Value * > IdxList) const
Constant * CreateInBoundsGetElementPtr (Type *Ty, Constant *C, ArrayRef< Constant * > IdxList) const
Constant * CreateInBoundsGetElementPtr (Type *Ty, Constant *C, Constant *Idx) const
Constant * CreateInBoundsGetElementPtr (Type *Ty, Constant *C, ArrayRef< Value * > IdxList) const
Constant * CreateCast (Instruction::CastOps Op, Constant *C, Type *DestTy) const
Constant * CreateIntCast (Constant *C, Type *DestTy, bool isSigned) const
Constant * CreatePointerCast (Constant *C, Type *DestTy) const
Constant * CreateFPCast (Constant *C, Type *DestTy) const
Constant * CreateBitCast (Constant *C, Type *DestTy) const
Constant * CreateIntToPtr (Constant *C, Type *DestTy) const
Constant * CreatePtrToInt (Constant *C, Type *DestTy) const
Constant * CreateZExtOrBitCast (Constant *C, Type *DestTy) const
Constant * CreateSExtOrBitCast (Constant *C, Type *DestTy) const
Constant * CreateTruncOrBitCast (Constant *C, Type *DestTy) const
Constant * CreatePointerBitCastOrAddrSpaceCast (Constant *C, Type *DestTy) const
Constant * CreateICmp (CmpInst::Predicate P, Constant *LHS, Constant *RHS) const
Constant * CreateFCmp (CmpInst::Predicate P, Constant *LHS, Constant *RHS) const
Constant * CreateSelect (Constant *C, Constant *True, Constant *False) const
Constant * CreateExtractElement (Constant *Vec, Constant *Idx) const
Constant * CreateInsertElement (Constant *Vec, Constant *NewElt, Constant *Idx) const
Constant * CreateShuffleVector (Constant *V1, Constant *V2, Constant *Mask) const
Constant * CreateExtractValue (Constant *Agg, ArrayRef< unsigned > IdxList) const
Constant * CreateInsertValue (Constant *Agg, Constant *Val, ArrayRef< unsigned > IdxList) const
Detailed Description
TargetFolder - Create constants with target dependent folding.
Definition at line 32 of file TargetFolder.h.
Constructor & Destructor Documentation
llvm::TargetFolder::TargetFolder (const DataLayout & DL) [inline, explicit]
Definition at line 44 of file TargetFolder.h.
Member Function Documentation
Constant* llvm::TargetFolder::CreateAdd (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const [inline]
Definition at line 50 of file TargetFolder.h.
References llvm::ConstantExpr::getAdd().
Constant* llvm::TargetFolder::CreateAnd (Constant * LHS, Constant * RHS) const [inline]
Definition at line 99 of file TargetFolder.h.
References llvm::ConstantExpr::getAnd().
Constant* llvm::TargetFolder::CreateAShr (Constant * LHS, Constant * RHS, bool isExact = false) const [inline]
Definition at line 96 of file TargetFolder.h.
References llvm::ConstantExpr::getAShr().
Constant* llvm::TargetFolder::CreateBinOp (Instruction::BinaryOps Opc, Constant * LHS, Constant * RHS) const [inline]
Definition at line 109 of file TargetFolder.h.
References llvm::ConstantExpr::get().
Constant* llvm::TargetFolder::CreateBitCast (Constant * C, Type * DestTy) const [inline]
Definition at line 190 of file TargetFolder.h.
References CreateCast().
Constant* llvm::TargetFolder::CreateCast (Instruction::CastOps Op, Constant * C, Type * DestTy) const [inline]
Definition at line 168 of file TargetFolder.h.
References llvm::ConstantExpr::getCast(), and llvm::Value::getType().
Referenced by CreateBitCast(), CreateIntToPtr(), and CreatePtrToInt().
Constant* llvm::TargetFolder::CreateExtractElement (Constant * Vec, Constant * Idx) const [inline]
Definition at line 243 of file TargetFolder.h.
References llvm::ConstantExpr::getExtractElement().
Constant* llvm::TargetFolder::CreateExtractValue (Constant * Agg, ArrayRef< unsigned > IdxList) const [inline]
Definition at line 257 of file TargetFolder.h.
References llvm::ConstantExpr::getExtractValue().
Constant* llvm::TargetFolder::CreateFAdd (Constant * LHS, Constant * RHS) const [inline]
Definition at line 54 of file TargetFolder.h.
References llvm::ConstantExpr::getFAdd().
Constant* llvm::TargetFolder::CreateFCmp (CmpInst::Predicate P, Constant * LHS, Constant * RHS) const [inline]
Definition at line 230 of file TargetFolder.h.
References llvm::ConstantExpr::getCompare().
Constant* llvm::TargetFolder::CreateFDiv (Constant * LHS, Constant * RHS) const [inline]
Definition at line 77 of file TargetFolder.h.
References llvm::ConstantExpr::getFDiv().
Constant* llvm::TargetFolder::CreateFMul (Constant * LHS, Constant * RHS) const [inline]
Definition at line 68 of file TargetFolder.h.
References llvm::ConstantExpr::getFMul().
Constant* llvm::TargetFolder::CreateFNeg (Constant * C) const [inline]
Definition at line 122 of file TargetFolder.h.
References llvm::ConstantExpr::getFNeg().
Constant* llvm::TargetFolder::CreateFPCast (Constant * C, Type * DestTy) const [inline]
Definition at line 185 of file TargetFolder.h.
References llvm::ConstantExpr::getFPCast(), and llvm::Value::getType().
Constant* llvm::TargetFolder::CreateFRem (Constant * LHS, Constant * RHS) const [inline]
Definition at line 86 of file TargetFolder.h.
References llvm::ConstantExpr::getFRem().
Constant* llvm::TargetFolder::CreateFSub (Constant * LHS, Constant * RHS) const [inline]
Definition at line 61 of file TargetFolder.h.
References llvm::ConstantExpr::getFSub().
Constant* llvm::TargetFolder::CreateGetElementPtr (Type * Ty, Constant * C, ArrayRef< Constant * > IdxList) const [inline]
Definition at line 133 of file TargetFolder.h.
References llvm::ConstantExpr::getGetElementPtr().
Constant* llvm::TargetFolder::CreateGetElementPtr (Type * Ty, Constant * C, Constant * Idx) const [inline]
Definition at line 137 of file TargetFolder.h.
References llvm::ConstantExpr::getGetElementPtr().
Constant* llvm::TargetFolder::CreateGetElementPtr (Type * Ty, Constant * C, ArrayRef< Value * > IdxList) const [inline]
Definition at line 143 of file TargetFolder.h.
References llvm::ConstantExpr::getGetElementPtr().
Constant* llvm::TargetFolder::CreateICmp (CmpInst::Predicate P, Constant * LHS, Constant * RHS) const [inline]
Definition at line 226 of file TargetFolder.h.
References llvm::ConstantExpr::getCompare().
Constant* llvm::TargetFolder::CreateInBoundsGetElementPtr (Type * Ty, Constant * C, ArrayRef< Constant * > IdxList) const [inline]
Definition at line 148 of file TargetFolder.h.
References llvm::ConstantExpr::getInBoundsGetElementPtr().
Constant* llvm::TargetFolder::CreateInBoundsGetElementPtr (Type * Ty, Constant * C, Constant * Idx) const [inline]
Definition at line 152 of file TargetFolder.h.
References llvm::ConstantExpr::getInBoundsGetElementPtr().
Constant* llvm::TargetFolder::CreateInBoundsGetElementPtr (Type * Ty, Constant * C, ArrayRef< Value * > IdxList) const [inline]
Definition at line 159 of file TargetFolder.h.
References llvm::ConstantExpr::getInBoundsGetElementPtr().
Constant* llvm::TargetFolder::CreateInsertElement (Constant * Vec, Constant * NewElt, Constant * Idx) const [inline]
Definition at line 247 of file TargetFolder.h.
References llvm::ConstantExpr::getInsertElement().
Constant* llvm::TargetFolder::CreateInsertValue (Constant * Agg, Constant * Val, ArrayRef< unsigned > IdxList) const [inline]
Definition at line 262 of file TargetFolder.h.
References llvm::ConstantExpr::getInsertValue().
Constant* llvm::TargetFolder::CreateIntCast (Constant * C, Type * DestTy, bool isSigned) const [inline]
Definition at line 174 of file TargetFolder.h.
References llvm::ConstantExpr::getIntegerCast(), and llvm::Value::getType().
Constant* llvm::TargetFolder::CreateIntToPtr (Constant * C, Type * DestTy) const [inline]
Definition at line 193 of file TargetFolder.h.
References CreateCast(), and llvm::IntToPtr.
Constant* llvm::TargetFolder::CreateLShr (Constant * LHS, Constant * RHS, bool isExact = false) const [inline]
Definition at line 93 of file TargetFolder.h.
References llvm::ConstantExpr::getLShr().
Constant* llvm::TargetFolder::CreateMul (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const [inline]
Definition at line 64 of file TargetFolder.h.
References llvm::ConstantExpr::getMul().
Constant* llvm::TargetFolder::CreateNeg (Constant * C, bool HasNUW = false, bool HasNSW = false) const [inline]
Definition at line 118 of file TargetFolder.h.
References llvm::ConstantExpr::getNeg().
Constant* llvm::TargetFolder::CreateNot (Constant * C) const [inline]
Definition at line 125 of file TargetFolder.h.
References llvm::ConstantExpr::getNot().
Constant* llvm::TargetFolder::CreateOr (Constant * LHS, Constant * RHS) const [inline]
Definition at line 102 of file TargetFolder.h.
References llvm::ConstantExpr::getOr().
Constant* llvm::TargetFolder::CreatePointerBitCastOrAddrSpaceCast (Constant * C, Type * DestTy) const [inline]
Definition at line 215 of file TargetFolder.h.
References llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast(), and llvm::Value::getType().
Constant* llvm::TargetFolder::CreatePointerCast (Constant * C, Type * DestTy) const [inline]
Definition at line 180 of file TargetFolder.h.
References llvm::ConstantExpr::getPointerCast(), and llvm::Value::getType().
Constant* llvm::TargetFolder::CreatePtrToInt (Constant * C, Type * DestTy) const [inline]
Definition at line 196 of file TargetFolder.h.
References CreateCast().
Constant* llvm::TargetFolder::CreateSDiv (Constant * LHS, Constant * RHS, bool isExact = false) const [inline]
Definition at line 74 of file TargetFolder.h.
References llvm::ConstantExpr::getSDiv().
Constant* llvm::TargetFolder::CreateSelect (Constant * C, Constant * True, Constant * False) const [inline]
Definition at line 239 of file TargetFolder.h.
References llvm::ConstantExpr::getSelect().
Constant* llvm::TargetFolder::CreateSExtOrBitCast (Constant * C, Type * DestTy) const [inline]
Definition at line 204 of file TargetFolder.h.
References llvm::ConstantExpr::getSExtOrBitCast(), and llvm::Value::getType().
Constant* llvm::TargetFolder::CreateShl (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const [inline]
Definition at line 89 of file TargetFolder.h.
References llvm::ConstantExpr::getShl().
Constant* llvm::TargetFolder::CreateShuffleVector (Constant * V1, Constant * V2, Constant * Mask) const [inline]
Definition at line 252 of file TargetFolder.h.
References llvm::ConstantExpr::getShuffleVector().
Constant* llvm::TargetFolder::CreateSRem (Constant * LHS, Constant * RHS) const [inline]
Definition at line 83 of file TargetFolder.h.
References llvm::ConstantExpr::getSRem().
Constant* llvm::TargetFolder::CreateSub (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const [inline]
Definition at line 57 of file TargetFolder.h.
References llvm::ConstantExpr::getSub().
Constant* llvm::TargetFolder::CreateTruncOrBitCast (Constant * C, Type * DestTy) const [inline]
Definition at line 209 of file TargetFolder.h.
References llvm::ConstantExpr::getTruncOrBitCast(), and llvm::Value::getType().
Constant* llvm::TargetFolder::CreateUDiv (Constant * LHS, Constant * RHS, bool isExact = false) const [inline]
Definition at line 71 of file TargetFolder.h.
References llvm::ConstantExpr::getUDiv().
Constant* llvm::TargetFolder::CreateURem (Constant * LHS, Constant * RHS) const [inline]
Definition at line 80 of file TargetFolder.h.
References llvm::ConstantExpr::getURem().
Constant* llvm::TargetFolder::CreateXor (Constant * LHS, Constant * RHS) const [inline]
Definition at line 105 of file TargetFolder.h.
References llvm::ConstantExpr::getXor().
Constant* llvm::TargetFolder::CreateZExtOrBitCast (Constant * C, Type * DestTy) const [inline]
Definition at line 199 of file TargetFolder.h.
References llvm::Value::getType(), and llvm::ConstantExpr::getZExtOrBitCast().
The documentation for this class was generated from the following file:
TargetFolder.h