LLVM: llvm::ARMTTIImpl Class Reference
llvm::ARMTTIImpl Class Reference
#include <ARMTargetTransformInfo.h>
Public Member Functions
ARMTTIImpl (const ARMBaseTargetMachine *TM, Function &F)
ARMTTIImpl (const ARMTTIImpl &Arg)
ARMTTIImpl (ARMTTIImpl &&Arg)
ARMTTIImpl & operator= (const ARMTTIImpl &RHS)
ARMTTIImpl & operator= (ARMTTIImpl &&RHS)
Scalar TTI Implementations
unsigned getIntImmCost (const APInt &Imm, Type *Ty)
Vector TTI Implementations
unsigned getNumberOfRegisters (bool Vector)
unsigned getRegisterBitWidth (bool Vector)
unsigned getMaxInterleaveFactor (unsigned VF)
unsigned getShuffleCost (TTI::ShuffleKind Kind, Type *Tp, int Index, Type *SubTp)
unsigned getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src)
unsigned getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy)
unsigned getVectorInstrCost (unsigned Opcode, Type *Val, unsigned Index)
unsigned getAddressComputationCost (Type *Val, bool IsComplex)
unsigned getFPOpCost (Type *Ty)
unsigned getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::OperandValueKind Op1Info=TTI::OK_AnyValue, TTI::OperandValueKind Op2Info=TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo=TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo=TTI::OP_None)
unsigned getMemoryOpCost (unsigned Opcode, Type *Src, unsigned Alignment, unsigned AddressSpace)
Detailed Description
Definition at line 28 of file ARMTargetTransformInfo.h.
Constructor & Destructor Documentation
llvm::ARMTTIImpl::ARMTTIImpl (const ARMBaseTargetMachine * TM, Function & F) [inline, explicit]
Definition at line 44 of file ARMTargetTransformInfo.h.
llvm::ARMTTIImpl::ARMTTIImpl (const ARMTTIImpl & Arg) [inline]
Definition at line 48 of file ARMTargetTransformInfo.h.
llvm::ARMTTIImpl::ARMTTIImpl (ARMTTIImpl && Arg) [inline]
Definition at line 50 of file ARMTargetTransformInfo.h.
Member Function Documentation
unsigned ARMTTIImpl::getAddressComputationCost (Type * Val, bool IsComplex)
Reimplemented from llvm::BasicTTIImplBase< ARMTTIImpl >.
Definition at line 302 of file ARMTargetTransformInfo.cpp.
References llvm::Type::isVectorTy().
unsigned ARMTTIImpl::getArithmeticInstrCost (unsigned Opcode, Type * Ty, TTI::OperandValueKind Op1Info = TTI::OK_AnyValue, TTI::OperandValueKind Op2Info = TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo = TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo = TTI::OP_None)
Reimplemented from llvm::BasicTTIImplBase< ARMTTIImpl >.
Definition at line 392 of file ARMTargetTransformInfo.cpp.
References llvm::CostTblEntry< TypeTy >::Cost, llvm::CostTableLookup(), llvm::BasicTTIImplBase< ARMTTIImpl >::getArithmeticInstrCost(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::ARMSubtarget::hasNEON(), llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::AArch64CC::LT, llvm::TargetTransformInfo::OK_UniformConstantValue, llvm::ISD::SDIV, llvm::ISD::SREM, llvm::ISD::UDIV, llvm::ISD::UREM, llvm::MVT::v16i8, llvm::MVT::v1i64, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v4i16, llvm::MVT::v4i32, llvm::MVT::v8i16, and llvm::MVT::v8i8.
unsigned ARMTTIImpl::getCastInstrCost (unsigned Opcode, Type * Dst, Type * Src)
Reimplemented from llvm::BasicTTIImplBase< ARMTTIImpl >.
Definition at line 50 of file ARMTargetTransformInfo.cpp.
References llvm::ConvertCostTableLookup(), llvm::CostTblEntry< TypeTy >::Cost, llvm::TypeConversionCostTblEntry< TypeTy >::Cost, llvm::CostTableLookup(), llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::BasicTTIImplBase< ARMTTIImpl >::getCastInstrCost(), llvm::EVT::getSimpleVT(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::TargetLoweringBase::getValueType(), llvm::ARMSubtarget::hasNEON(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::EVT::isSimple(), llvm::EVT::isVector(), llvm::Type::isVectorTy(), llvm::AArch64CC::LT, llvm::ISD::SIGN_EXTEND, llvm::ISD::SINT_TO_FP, llvm::ISD::TRUNCATE, llvm::ISD::UINT_TO_FP, llvm::MVT::v16f32, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::MVT::v2f32, llvm::MVT::v2f64, llvm::MVT::v2i16, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v2i8, llvm::MVT::v4f32, llvm::MVT::v4i1, llvm::MVT::v4i16, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v4i8, llvm::MVT::v8f32, llvm::MVT::v8i16, llvm::MVT::v8i32, llvm::MVT::v8i64, llvm::MVT::v8i8, and llvm::ISD::ZERO_EXTEND.
unsigned ARMTTIImpl::getCmpSelInstrCost (unsigned Opcode, Type * ValTy, Type * CondTy)
Reimplemented from llvm::BasicTTIImplBase< ARMTTIImpl >.
Definition at line 268 of file ARMTargetTransformInfo.cpp.
References llvm::ConvertCostTableLookup(), llvm::TypeConversionCostTblEntry< TypeTy >::Cost, llvm::BasicTTIImplBase< ARMTTIImpl >::getCmpSelInstrCost(), llvm::EVT::getSimpleVT(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::TargetLoweringBase::getValueType(), llvm::ARMSubtarget::hasNEON(), llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::EVT::isSimple(), llvm::Type::isVectorTy(), llvm::AArch64CC::LT, llvm::ISD::SELECT, llvm::MVT::v16i1, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i64, llvm::MVT::v4i1, llvm::MVT::v4i64, llvm::MVT::v8i1, llvm::MVT::v8i32, and llvm::MVT::v8i64.
unsigned ARMTTIImpl::getFPOpCost (Type * Ty)
Reimplemented from llvm::BasicTTIImplBase< ARMTTIImpl >.
Definition at line 317 of file ARMTargetTransformInfo.cpp.
References llvm::ARMSubtarget::hasVFP2(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), llvm::ARMSubtarget::isFPOnlySP(), llvm::ARMSubtarget::isThumb1Only(), llvm::TargetTransformInfo::TCC_Basic, and llvm::TargetTransformInfo::TCC_Expensive.
unsigned ARMTTIImpl::getIntImmCost (const APInt & Imm, Type * Ty)
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 18 of file ARMTargetTransformInfo.cpp.
References llvm::tgtok::Bits, llvm::Type::getPrimitiveSizeInBits(), llvm::APInt::getSExtValue(), llvm::ARM_AM::getSOImmVal(), llvm::ARM_AM::getT2SOImmVal(), llvm::APInt::getZExtValue(), llvm::ARMSubtarget::hasV6T2Ops(), llvm::Type::isIntegerTy(), llvm::ARMSubtarget::isThumb(), llvm::ARMSubtarget::isThumb2(), and llvm::ARM_AM::isThumbImmShiftedVal().
unsigned llvm::ARMTTIImpl::getMaxInterleaveFactor (unsigned VF) [inline]
Reimplemented from llvm::BasicTTIImplBase< ARMTTIImpl >.
Definition at line 99 of file ARMTargetTransformInfo.h.
References llvm::ARMSubtarget::isCortexA15(), and llvm::ARMSubtarget::isSwift().
unsigned ARMTTIImpl::getMemoryOpCost (unsigned Opcode, Type * Src, unsigned Alignment, unsigned AddressSpace)
Reimplemented from llvm::BasicTTIImplBase< ARMTTIImpl >.
Definition at line 468 of file ARMTargetTransformInfo.cpp.
References llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::Type::getVectorElementType(), llvm::Type::isDoubleTy(), llvm::Type::isVectorTy(), and llvm::AArch64CC::LT.
unsigned llvm::ARMTTIImpl::getNumberOfRegisters (bool Vector) [inline]
Reimplemented from llvm::BasicTTIImplBase< ARMTTIImpl >.
Definition at line 77 of file ARMTargetTransformInfo.h.
References llvm::ARMSubtarget::hasNEON(), and llvm::ARMSubtarget::isThumb1Only().
unsigned llvm::ARMTTIImpl::getRegisterBitWidth (bool Vector) [inline]
Reimplemented from llvm::BasicTTIImplBase< ARMTTIImpl >.
Definition at line 89 of file ARMTargetTransformInfo.h.
References llvm::ARMSubtarget::hasNEON().
unsigned ARMTTIImpl::getShuffleCost (TTI::ShuffleKind Kind, Type * Tp, int Index, Type * SubTp)
Reimplemented from llvm::BasicTTIImplBase< ARMTTIImpl >.
Definition at line 336 of file ARMTargetTransformInfo.cpp.
References llvm::CostTblEntry< TypeTy >::Cost, llvm::CostTableLookup(), llvm::BasicTTIImplBase< ARMTTIImpl >::getShuffleCost(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::AArch64CC::LT, llvm::TargetTransformInfo::SK_Alternate, llvm::TargetTransformInfo::SK_Reverse, llvm::MVT::v16i8, llvm::MVT::v2f32, llvm::MVT::v2f64, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v4i16, llvm::MVT::v4i32, llvm::MVT::v8i16, and llvm::ISD::VECTOR_SHUFFLE.
unsigned ARMTTIImpl::getVectorInstrCost (unsigned Opcode, Type * Val, unsigned Index)
Reimplemented from llvm::BasicTTIImplBase< ARMTTIImpl >.
Definition at line 248 of file ARMTargetTransformInfo.cpp.
References ExtractElement(), llvm::Type::getScalarSizeInBits(), llvm::Type::getVectorElementType(), llvm::BasicTTIImplBase< ARMTTIImpl >::getVectorInstrCost(), llvm::InsertElement, llvm::Type::isIntegerTy(), llvm::ARMSubtarget::isSwift(), and llvm::Type::isVectorTy().
ARMTTIImpl& llvm::ARMTTIImpl::operator= (const ARMTTIImpl & RHS) [inline]
Definition at line 53 of file ARMTargetTransformInfo.h.
References llvm::BasicTTIImplBase< ARMTTIImpl >::operator=().
ARMTTIImpl& llvm::ARMTTIImpl::operator= (ARMTTIImpl && RHS) [inline]
Definition at line 59 of file ARMTargetTransformInfo.h.
References llvm::BasicTTIImplBase< ARMTTIImpl >::operator=().
The documentation for this class was generated from the following files:
ARMTargetTransformInfo.h
ARMTargetTransformInfo.cpp