LLVM: llvm::DbgValueInst Class Reference
llvm::DbgValueInst Class Reference
DbgValueInst - This represents the llvm.dbg.value instruction.
#include <IntrinsicInst.h>
Public Member Functions
const Value * getValue () const
DbgValueInst - This represents the llvm.dbg.value instruction.
Value * getValue ()
uint64_t getOffset () const
DILocalVariable * getVariable () const
DIExpression * getExpression () const
Metadata * getRawVariable () const
Metadata * getRawExpression () const
Static Public Member Functions
static bool classof (const IntrinsicInst *I)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Detailed Description
DbgValueInst - This represents the llvm.dbg.value instruction.
Definition at line 110 of file IntrinsicInst.h.
Member Function Documentation
static bool llvm::DbgValueInst::classof (const IntrinsicInst * I) [inline, static]
Reimplemented from llvm::DbgInfoIntrinsic.
Definition at line 133 of file IntrinsicInst.h.
References llvm::IntrinsicInst::getIntrinsicID().
Referenced by classof().
static bool llvm::DbgValueInst::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::DbgInfoIntrinsic.
Definition at line 136 of file IntrinsicInst.h.
References classof().
DIExpression* llvm::DbgValueInst::getExpression () const [inline]
Definition at line 121 of file IntrinsicInst.h.
References getRawExpression().
Referenced by llvm::SelectionDAGBuilder::resolveDanglingDebugInfo(), and llvm::FastISel::selectIntrinsicCall().
uint64_t llvm::DbgValueInst::getOffset () const [inline]
Definition at line 114 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperand().
Referenced by llvm::SelectionDAGBuilder::resolveDanglingDebugInfo(), and llvm::FastISel::selectIntrinsicCall().
Metadata* llvm::DbgValueInst::getRawExpression () const [inline]
Definition at line 128 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperand(), and llvm::Instruction::getMetadata().
Referenced by getExpression().
Metadata* llvm::DbgValueInst::getRawVariable () const [inline]
Definition at line 125 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperand(), and llvm::Instruction::getMetadata().
Referenced by getVariable().
const Value * DbgValueInst::getValue () const
DbgValueInst - This represents the llvm.dbg.value instruction.
Definition at line 77 of file IntrinsicInst.cpp.
Referenced by llvm::FastISel::selectIntrinsicCall().
Value * DbgValueInst::getValue ()
Definition at line 81 of file IntrinsicInst.cpp.
References llvm::CallInst::getArgOperand(), and getValueImpl().
DILocalVariable* llvm::DbgValueInst::getVariable () const [inline]
Definition at line 118 of file IntrinsicInst.h.
References getRawVariable().
Referenced by llvm::DebugInfoFinder::processValue(), llvm::SelectionDAGBuilder::resolveDanglingDebugInfo(), and llvm::FastISel::selectIntrinsicCall().
The documentation for this class was generated from the following files:
IntrinsicInst.h
IntrinsicInst.cpp