LLVM: llvm::MachinePassRegistryNode Class Reference
llvm::MachinePassRegistryNode Class Reference
MachinePassRegistryNode - Machine pass node stored in registration list.
#include <MachinePassRegistry.h>
Public Member Functions
MachinePassRegistryNode (const char *N, const char *D, MachinePassCtor C)
MachinePassRegistryNode * getNext () const
MachinePassRegistryNode ** getNextAddress ()
const char * getName () const
const char * getDescription () const
MachinePassCtor getCtor () const
void setNext (MachinePassRegistryNode *N)
Detailed Description
MachinePassRegistryNode - Machine pass node stored in registration list.
Definition at line 50 of file MachinePassRegistry.h.
Constructor & Destructor Documentation
llvm::MachinePassRegistryNode::MachinePassRegistryNode (const char * N, const char * D, MachinePassCtor C) [inline]
Definition at line 61 of file MachinePassRegistry.h.
Member Function Documentation
MachinePassCtor llvm::MachinePassRegistryNode::getCtor () const [inline]
Definition at line 73 of file MachinePassRegistry.h.
Referenced by llvm::MachinePassRegistry::Add().
const char* llvm::MachinePassRegistryNode::getDescription () const [inline]
Definition at line 72 of file MachinePassRegistry.h.
Referenced by llvm::MachinePassRegistry::Add().
const char* llvm::MachinePassRegistryNode::getName () const [inline]
Definition at line 71 of file MachinePassRegistry.h.
Referenced by llvm::MachinePassRegistry::Add(), and llvm::MachinePassRegistry::Remove().
MachinePassRegistryNode* llvm::MachinePassRegistryNode::getNext () const [inline]
Reimplemented in llvm::MachineSchedRegistry, llvm::RegisterScheduler, and llvm::RegisterRegAlloc.
Definition at line 69 of file MachinePassRegistry.h.
Referenced by llvm::MachinePassRegistry::setDefault().
MachinePassRegistryNode** llvm::MachinePassRegistryNode::getNextAddress () [inline]
Definition at line 70 of file MachinePassRegistry.h.
void llvm::MachinePassRegistryNode::setNext (MachinePassRegistryNode * N) [inline]
Definition at line 74 of file MachinePassRegistry.h.
Referenced by llvm::MachinePassRegistry::Add().
The documentation for this class was generated from the following file:
MachinePassRegistry.h