LLVM: llvm::LLVMTargetMachine Class Reference
llvm::LLVMTargetMachine Class Reference
This class describes a target machine that is implemented with the LLVM target-independent code generator.
#include <TargetMachine.h>
Public Member Functions
TargetIRAnalysis getTargetIRAnalysis () override
Get a TargetIRAnalysis implementation for the target.
virtual TargetPassConfig * createPassConfig (PassManagerBase &PM)
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
bool addPassesToEmitFile (PassManagerBase &PM, raw_pwrite_stream &Out, CodeGenFileType FileType, bool DisableVerify=true, AnalysisID StartAfter=nullptr, AnalysisID StopAfter=nullptr, MachineFunctionInitializer *MFInitializer=nullptr) override
Add passes to the specified pass manager to get the specified file emitted.
bool addPassesToEmitMC (PassManagerBase &PM, MCContext *&Ctx, raw_pwrite_stream &OS, bool DisableVerify=true) override
Add passes to the specified pass manager to get machine code emitted with the MCJIT.
Protected Member Functions
LLVMTargetMachine (const Target &T, StringRef DataLayoutString, const Triple &TargetTriple, StringRef CPU, StringRef FS, TargetOptions Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
void initAsmInfo ()
Detailed Description
This class describes a target machine that is implemented with the LLVM target-independent code generator.
Definition at line 240 of file Target/TargetMachine.h.
Constructor & Destructor Documentation
LLVMTargetMachine::LLVMTargetMachine (const Target & T, StringRef DataLayoutString, const Triple & TargetTriple, StringRef CPU, StringRef FS, TargetOptions Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL) [protected]
Definition at line 74 of file LLVMTargetMachine.cpp.
References llvm::TargetMachine::CodeGenInfo, llvm::Target::createMCCodeGenInfo(), llvm::NVPTX::PTXCvtMode::RM, and llvm::Triple::str().
Member Function Documentation
bool LLVMTargetMachine::addPassesToEmitFile (PassManagerBase & PM, raw_pwrite_stream & Out, CodeGenFileType FileType, bool DisableVerify = true, AnalysisID StartAfter = nullptr, AnalysisID StopAfter = nullptr, MachineFunctionInitializer * MFInitializer = nullptr) [override, virtual]
Add passes to the specified pass manager to get the specified file emitted.
Typically this will involve several steps of code generation.
Reimplemented from llvm::TargetMachine.
Definition at line 144 of file LLVMTargetMachine.cpp.
References addPassesToGenerateCode(), llvm::MCTargetOptions::AsmVerbose, llvm::TargetMachine::CGFT_AssemblyFile, llvm::TargetMachine::CGFT_Null, llvm::TargetMachine::CGFT_ObjectFile, llvm::Target::createAsmPrinter(), llvm::Target::createAsmStreamer(), llvm::Target::createMCAsmBackend(), llvm::Target::createMCCodeEmitter(), llvm::Target::createMCInstPrinter(), llvm::createNullStreamer(), llvm::createPrintMIRPass(), llvm::MCAsmInfo::getAssemblerDialect(), llvm::TargetMachine::getMCAsmInfo(), llvm::TargetMachine::getMCInstrInfo(), llvm::TargetMachine::getMCRegisterInfo(), llvm::TargetMachine::getMCSubtargetInfo(), llvm::TargetMachine::getTarget(), llvm::TargetMachine::getTargetTriple(), llvm::TargetOptions::MCOptions, llvm::MCTargetOptions::MCRelaxAll, llvm::MCTargetOptions::MCSaveTempLabels, llvm::MCTargetOptions::MCUseDwarfDirectory, llvm::TargetMachine::MII, llvm::TargetMachine::MRI, llvm::TargetMachine::Options, llvm::outs(), Printer, llvm::MCStreamer::reset(), llvm::MCContext::setAllowTemporaryLabels(), llvm::MCContext::setUseNamesOnTempLabels(), llvm::MCTargetOptions::ShowMCEncoding, llvm::MCTargetOptions::ShowMCInst, llvm::TargetMachine::STI, T, and llvm::TargetMachine::TargetCPU.
bool LLVMTargetMachine::addPassesToEmitMC (PassManagerBase & PM, MCContext *& Ctx, raw_pwrite_stream & Out, bool DisableVerify = true) [override, virtual]
Add passes to the specified pass manager to get machine code emitted with the MCJIT.
addPassesToEmitMC - Add passes to the specified pass manager to get machine code emitted with the MCJIT.
This method returns true if machine code is not supported. It fills the MCContext Ctx pointer which can be used to build custom MCStreamer.
Reimplemented from llvm::TargetMachine.
Reimplemented in llvm::NVPTXTargetMachine.
Definition at line 230 of file LLVMTargetMachine.cpp.
References addPassesToGenerateCode(), llvm::Target::createAsmPrinter(), llvm::Target::createMCAsmBackend(), llvm::Target::createMCCodeEmitter(), llvm::TargetMachine::getMCInstrInfo(), llvm::TargetMachine::getMCRegisterInfo(), llvm::TargetMachine::getMCSubtargetInfo(), llvm::TargetMachine::getTarget(), llvm::TargetMachine::getTargetTriple(), llvm::TargetOptions::MCOptions, llvm::MCTargetOptions::MCRelaxAll, llvm::MCTargetOptions::MCSaveTempLabels, llvm::TargetMachine::MRI, llvm::TargetMachine::Options, Printer, llvm::MCContext::setAllowTemporaryLabels(), llvm::TargetMachine::STI, and llvm::TargetMachine::TargetCPU.
TargetPassConfig * LLVMTargetMachine::createPassConfig (PassManagerBase & PM) [virtual]
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
createPassConfig - Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
Targets may override this to extend TargetPassConfig.
Reimplemented in llvm::GCNTargetMachine, llvm::R600TargetMachine, llvm::MipsTargetMachine, llvm::ARMBaseTargetMachine, llvm::NVPTXTargetMachine, llvm::PPCTargetMachine, llvm::SystemZTargetMachine, llvm::final< T >, llvm::HexagonTargetMachine, llvm::MSP430TargetMachine, llvm::AArch64TargetMachine, llvm::SparcTargetMachine, llvm::XCoreTargetMachine, and llvm::BPFTargetMachine.
Definition at line 249 of file Passes.cpp.
Referenced by addPassesToGenerateCode().
TargetIRAnalysis LLVMTargetMachine::getTargetIRAnalysis () [override, virtual]
Get a TargetIRAnalysis implementation for the target.
This analysis will produce a TTI result which uses the common code generator to answer queries about the IR.
Reimplemented from llvm::TargetMachine.
Reimplemented in llvm::NVPTXTargetMachine, llvm::AMDGPUTargetMachine, llvm::ARMBaseTargetMachine, llvm::MipsTargetMachine, llvm::PPCTargetMachine, llvm::AArch64TargetMachine, llvm::SystemZTargetMachine, llvm::XCoreTargetMachine, and llvm::final< T >.
Definition at line 84 of file LLVMTargetMachine.cpp.
References F().
Referenced by addPassesToGenerateCode().
void LLVMTargetMachine::initAsmInfo () [protected]
Definition at line 45 of file LLVMTargetMachine.cpp.
References llvm::TargetMachine::AsmInfo, llvm::TargetOptions::CompressDebugSections, llvm::Target::createMCAsmInfo(), llvm::Target::createMCInstrInfo(), llvm::Target::createMCRegInfo(), llvm::Target::createMCSubtargetInfo(), llvm::TargetOptions::DisableIntegratedAS, llvm::TargetMachine::getTargetCPU(), llvm::TargetMachine::getTargetFeatureString(), llvm::TargetMachine::getTargetTriple(), llvm::TargetMachine::MII, llvm::TargetMachine::MRI, llvm::TargetMachine::Options, llvm::MCAsmInfo::setCompressDebugSections(), llvm::MCAsmInfo::setUseIntegratedAssembler(), llvm::TargetMachine::STI, and llvm::TargetMachine::TheTarget.
Referenced by llvm::AArch64TargetMachine::AArch64TargetMachine(), llvm::AMDGPUTargetMachine::AMDGPUTargetMachine(), llvm::ARMTargetMachine::ARMTargetMachine(), llvm::BPFTargetMachine::BPFTargetMachine(), llvm::HexagonTargetMachine::HexagonTargetMachine(), llvm::MipsTargetMachine::MipsTargetMachine(), llvm::MSP430TargetMachine::MSP430TargetMachine(), llvm::NVPTXTargetMachine::NVPTXTargetMachine(), llvm::PPCTargetMachine::PPCTargetMachine(), llvm::SparcTargetMachine::SparcTargetMachine(), llvm::SystemZTargetMachine::SystemZTargetMachine(), llvm::ThumbTargetMachine::ThumbTargetMachine(), and llvm::XCoreTargetMachine::XCoreTargetMachine().
The documentation for this class was generated from the following files:
Target/TargetMachine.h
LLVMTargetMachine.cpp
Passes.cpp