LLVM: llvm::DWARFUnitSectionBase Class Reference
llvm::DWARFUnitSectionBase Class Reference
Base class for all DWARFUnitSection classes.
#include <DWARFUnit.h>
Public Member Functions
virtual DWARFUnit * getUnitForOffset (uint32_t Offset) const =0
Returns the Unit that contains the given section offset in the same section this Unit originated from.
void parse (DWARFContext &C, const DWARFSection &Section)
void parseDWO (DWARFContext &C, const DWARFSection &DWOSection)
Protected Member Functions
virtual void parseImpl (DWARFContext &Context, const DWARFSection &Section, const DWARFDebugAbbrev *DA, StringRef RS, StringRef SS, StringRef SOS, StringRef AOS, bool isLittleEndian)=0
~DWARFUnitSectionBase ()
Detailed Description
Base class for all DWARFUnitSection classes.
This provides the functionality common to all unit types.
Definition at line 35 of file DWARFUnit.h.
Constructor & Destructor Documentation
llvm::DWARFUnitSectionBase::~DWARFUnitSectionBase () [protected]
Member Function Documentation
virtual DWARFUnit* llvm::DWARFUnitSectionBase::getUnitForOffset (uint32_t Offset) const [pure virtual]
Returns the Unit that contains the given section offset in the same section this Unit originated from.
Implemented in llvm::final< T >.
Referenced by findUnitAndExtractFast().
void DWARFUnitSectionBase::parse (DWARFContext & C, const DWARFSection & Section)
Definition at line 20 of file DWARFUnit.cpp.
References llvm::DWARFContext::getAddrSection(), llvm::DWARFContext::getDebugAbbrev(), llvm::DWARFContext::getRangeSection(), llvm::DWARFContext::getStringSection(), and llvm::DWARFContext::isLittleEndian().
void DWARFUnitSectionBase::parseDWO (DWARFContext & C, const DWARFSection & DWOSection)
Definition at line 26 of file DWARFUnit.cpp.
References llvm::DWARFContext::getAddrSection(), llvm::DWARFContext::getDebugAbbrevDWO(), llvm::DWARFContext::getRangeDWOSection(), llvm::DWARFContext::getStringDWOSection(), llvm::DWARFContext::getStringOffsetDWOSection(), and llvm::DWARFContext::isLittleEndian().
virtual void llvm::DWARFUnitSectionBase::parseImpl (DWARFContext & Context, const DWARFSection & Section, const DWARFDebugAbbrev * DA, StringRef RS, StringRef SS, StringRef SOS, StringRef AOS, bool isLittleEndian) [protected, pure virtual]
The documentation for this class was generated from the following files:
DWARFUnit.h
DWARFUnit.cpp