LLVM: llvm::DIBasicType Class Reference
llvm::DIBasicType Class Reference
Basic type, like 'int' or 'float'.
#include <DebugInfoMetadata.h>
Public Member Functions
DEFINE_MDNODE_GET (DIBasicType,(unsigned Tag, StringRef Name),(Tag, Name, 0, 0, 0)) DEFINE_MDNODE_GET(DIBasicType
unsigned StringRef uint64_t
uint64_t unsigned Encoding DEFINE_MDNODE_GET (DIBasicType,(unsigned Tag, MDString *Name, uint64_t SizeInBits, uint64_t AlignInBits, unsigned Encoding),(Tag, Name, SizeInBits, AlignInBits, Encoding)) TempDIBasicType clone() const
unsigned getEncoding () const
Static Public Member Functions
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
Public Attributes
unsigned Tag
unsigned StringRef Name
unsigned StringRef uint64_t SizeInBits
unsigned StringRef uint64_t
uint64_t AlignInBits
unsigned StringRef uint64_t
uint64_t unsigned Encoding
unsigned StringRef uint64_t
uint64_t unsigned Tag
unsigned StringRef uint64_t
uint64_t unsigned Name
unsigned StringRef uint64_t
uint64_t unsigned SizeInBits
unsigned StringRef uint64_t
uint64_t unsigned AlignInBits
Friends
class LLVMContextImpl
class MDNode
Detailed Description
Basic type, like 'int' or 'float'.
TODO: Split out DW_TAG_unspecified_type. TODO: Drop unused accessors.
Definition at line 595 of file DebugInfoMetadata.h.
Member Function Documentation
static bool llvm::DIBasicType::classof (const Metadata * MD) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::DIType.
Definition at line 642 of file DebugInfoMetadata.h.
References llvm::Metadata::DIBasicTypeKind, and llvm::Metadata::getMetadataID().
llvm::DIBasicType::DEFINE_MDNODE_GET (DIBasicType , (unsigned Tag, StringRef Name) , (Tag, Name, 0, 0, 0))
unsigned StringRef uint64_t uint64_t unsigned Encoding llvm::DIBasicType::DEFINE_MDNODE_GET (DIBasicType , (unsigned Tag, MDString *Name, uint64_t SizeInBits,uint64_t AlignInBits, unsigned Encoding) , (Tag, Name, SizeInBits, AlignInBits, Encoding)) const [inline]
Definition at line 633 of file DebugInfoMetadata.h.
unsigned llvm::DIBasicType::getEncoding () const [inline]
Definition at line 640 of file DebugInfoMetadata.h.
Referenced by emitDebugLocValue(), llvm::MDNodeKeyImpl< DIBasicType >::isKeyOf(), and WriteDIBasicType().
Friends And Related Function Documentation
friend class LLVMContextImpl [friend]
Reimplemented from llvm::DINode.
Definition at line 596 of file DebugInfoMetadata.h.
friend class MDNode [friend]
Reimplemented from llvm::DINode.
Definition at line 597 of file DebugInfoMetadata.h.
Member Data Documentation
unsigned StringRef uint64_t uint64_t llvm::DIBasicType::AlignInBits
Reimplemented from llvm::DIType.
Definition at line 630 of file DebugInfoMetadata.h.
unsigned StringRef uint64_t uint64_t unsigned llvm::DIBasicType::AlignInBits
Reimplemented from llvm::DIType.
Definition at line 630 of file DebugInfoMetadata.h.
unsigned StringRef uint64_t uint64_t unsigned llvm::DIBasicType::Encoding
Definition at line 630 of file DebugInfoMetadata.h.
unsigned StringRef llvm::DIBasicType::Name
Definition at line 630 of file DebugInfoMetadata.h.
unsigned StringRef uint64_t uint64_t unsigned llvm::DIBasicType::Name
Definition at line 630 of file DebugInfoMetadata.h.
unsigned StringRef uint64_t llvm::DIBasicType::SizeInBits
Reimplemented from llvm::DIType.
Definition at line 630 of file DebugInfoMetadata.h.
unsigned StringRef uint64_t uint64_t unsigned llvm::DIBasicType::SizeInBits
Reimplemented from llvm::DIType.
Definition at line 630 of file DebugInfoMetadata.h.
unsigned llvm::DIBasicType::Tag
Definition at line 630 of file DebugInfoMetadata.h.
unsigned StringRef uint64_t uint64_t unsigned llvm::DIBasicType::Tag
Definition at line 630 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
DebugInfoMetadata.h
DebugInfoMetadata.cpp