LLVM: llvm::TargetLoweringObjectFileMachO Class Reference
llvm::TargetLoweringObjectFileMachO Class Reference
#include <TargetLoweringObjectFileImpl.h>
Public Member Functions
~TargetLoweringObjectFileMachO () override
TargetLoweringObjectFileMachO ()
StringRef getDepLibFromLinkerOpt (StringRef LinkerOption) const override
Extract the dependent library name from a linker option string.
void emitModuleFlags (MCStreamer &Streamer, ArrayRef< Module::ModuleFlagEntry > ModuleFlags, Mangler &Mang, const TargetMachine &TM) const override
Emit the module flags that specify the garbage collection information.
MCSection * SelectSectionForGlobal (const GlobalValue *GV, SectionKind Kind, Mangler &Mang, const TargetMachine &TM) const override
MCSection * getExplicitSectionGlobal (const GlobalValue *GV, SectionKind Kind, Mangler &Mang, const TargetMachine &TM) const override
Targets should implement this method to assign a section to globals with an explicit section specfied.
MCSection * getSectionForConstant (SectionKind Kind, const Constant *C) const override
Given a constant with the SectionKind, return a section that it should be placed in.
const MCExpr * getTTypeGlobalReference (const GlobalValue *GV, unsigned Encoding, Mangler &Mang, const TargetMachine &TM, MachineModuleInfo *MMI, MCStreamer &Streamer) const override
The mach-o version of this method defaults to returning a stub reference.
MCSymbol * getCFIPersonalitySymbol (const GlobalValue *GV, Mangler &Mang, const TargetMachine &TM, MachineModuleInfo *MMI) const override
const MCExpr * getIndirectSymViaGOTPCRel (const MCSymbol *Sym, const MCValue &MV, int64_t Offset, MachineModuleInfo *MMI, MCStreamer &Streamer) const override
Get MachO PC relative GOT entry relocation.
Detailed Description
Definition at line 88 of file TargetLoweringObjectFileImpl.h.
Constructor & Destructor Documentation
llvm::TargetLoweringObjectFileMachO::~TargetLoweringObjectFileMachO () [inline, override]
Definition at line 90 of file TargetLoweringObjectFileImpl.h.
TargetLoweringObjectFileMachO::TargetLoweringObjectFileMachO ()
Definition at line 438 of file TargetLoweringObjectFileImpl.cpp.
References llvm::TargetLoweringObjectFile::SupportIndirectSymViaGOTPCRel.
Member Function Documentation
void TargetLoweringObjectFileMachO::emitModuleFlags (MCStreamer & Streamer, ArrayRef< Module::ModuleFlagEntry > ModuleFlags, Mangler & Mang, const TargetMachine & TM) const [override, virtual]
Emit the module flags that specify the garbage collection information.
emitModuleFlags - Perform code emission for module flags.
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 455 of file TargetLoweringObjectFileImpl.cpp.
References llvm::MCStreamer::AddBlankLine(), llvm::ArrayRef< T >::begin(), llvm::Module::ModuleFlagEntry::Behavior, llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitLinkerOptions(), llvm::StringRef::empty(), llvm::ArrayRef< T >::end(), llvm::TargetLoweringObjectFile::getContext(), llvm::SectionKind::getDataNoRel(), llvm::MCContext::getMachOSection(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), getString(), llvm::MDString::getString(), llvm::Module::ModuleFlagEntry::Key, llvm::MCSectionMachO::ParseSectionSpecifier(), llvm::report_fatal_error(), llvm::Module::Require, llvm::ARMBuildAttrs::Section, llvm::MCStreamer::SwitchSection(), and llvm::Module::ModuleFlagEntry::Val.
MCSymbol * TargetLoweringObjectFileMachO::getCFIPersonalitySymbol (const GlobalValue * GV, Mangler & Mang, const TargetMachine & TM, MachineModuleInfo * MMI) const [override, virtual]
Reimplemented from llvm::TargetLoweringObjectFile.
Reimplemented in llvm::AArch64_MachoTargetObjectFile, and llvm::X86_64MachoTargetObjectFile.
Definition at line 696 of file TargetLoweringObjectFileImpl.cpp.
References llvm::MachineModuleInfoMachO::getGVStubEntry(), llvm::MachineModuleInfo::getObjFileInfo(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer(), llvm::TargetMachine::getSymbol(), llvm::TargetLoweringObjectFile::getSymbolWithGlobalValueBase(), and llvm::GlobalValue::hasLocalLinkage().
StringRef TargetLoweringObjectFileMachO::getDepLibFromLinkerOpt (StringRef LinkerOption) const [override, virtual]
Extract the dependent library name from a linker option string.
getDepLibFromLinkerOpt - Extract the dependent library name from a linker option string.
Returns StringRef() if the option does not specify a library.
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 446 of file TargetLoweringObjectFileImpl.cpp.
References llvm::StringRef::startswith(), and llvm::StringRef::substr().
MCSection * TargetLoweringObjectFileMachO::getExplicitSectionGlobal (const GlobalValue * GV, SectionKind Kind, Mangler & Mang, const TargetMachine & TM) const [override, virtual]
Targets should implement this method to assign a section to globals with an explicit section specfied.
The implementation of this method can assume that GV->hasSection() is true.
Implements llvm::TargetLoweringObjectFile.
Definition at line 538 of file TargetLoweringObjectFileImpl.cpp.
References checkMachOComdat(), llvm::TargetLoweringObjectFile::getContext(), llvm::MCContext::getMachOSection(), llvm::Value::getName(), llvm::GlobalValue::getSection(), llvm::MCSectionMachO::getStubSize(), llvm::MCSectionMachO::getTypeAndAttributes(), llvm::MCSectionMachO::ParseSectionSpecifier(), llvm::report_fatal_error(), and llvm::ARMBuildAttrs::Section.
const MCExpr * TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel (const MCSymbol * Sym, const MCValue & MV, int64_t Offset, MachineModuleInfo * MMI, MCStreamer & Streamer) const [override, virtual]
Get MachO PC relative GOT entry relocation.
Reimplemented from llvm::TargetLoweringObjectFile.
Reimplemented in llvm::AArch64_MachoTargetObjectFile, and llvm::X86_64MachoTargetObjectFile.
Definition at line 716 of file TargetLoweringObjectFileImpl.cpp.
References llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCBinaryExpr::createSub(), llvm::TargetLoweringObjectFile::DL, llvm::MCValue::getConstant(), llvm::TargetLoweringObjectFile::getContext(), llvm::MachineModuleInfoMachO::getGVStubEntry(), llvm::MCSymbol::getName(), llvm::MachineModuleInfo::getObjFileInfo(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer(), llvm::DataLayout::getPrivateGlobalPrefix(), llvm::MCValue::getSymB(), llvm::MCSymbolRefExpr::getSymbol(), and llvm::MCSymbolRefExpr::VK_None.
MCSection * TargetLoweringObjectFileMachO::getSectionForConstant (SectionKind Kind, const Constant * C) const [override, virtual]
Given a constant with the SectionKind, return a section that it should be placed in.
Given a mergable constant with the specified size and relocation information, return a section that it should be placed in.
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 648 of file TargetLoweringObjectFileImpl.cpp.
References llvm::MCObjectFileInfo::ConstDataSection, llvm::MCObjectFileInfo::EightByteConstantSection, llvm::MCObjectFileInfo::FourByteConstantSection, llvm::SectionKind::isDataRel(), llvm::SectionKind::isMergeableConst16(), llvm::SectionKind::isMergeableConst4(), llvm::SectionKind::isMergeableConst8(), llvm::SectionKind::isReadOnlyWithRel(), llvm::MCObjectFileInfo::ReadOnlySection, and llvm::MCObjectFileInfo::SixteenByteConstantSection.
const MCExpr * TargetLoweringObjectFileMachO::getTTypeGlobalReference (const GlobalValue * GV, unsigned Encoding, Mangler & Mang, const TargetMachine & TM, MachineModuleInfo * MMI, MCStreamer & Streamer) const [override, virtual]
The mach-o version of this method defaults to returning a stub reference.
Reimplemented from llvm::TargetLoweringObjectFile.
Reimplemented in llvm::AArch64_MachoTargetObjectFile, and llvm::X86_64MachoTargetObjectFile.
Definition at line 664 of file TargetLoweringObjectFileImpl.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::dwarf::DW_EH_PE_indirect, llvm::TargetLoweringObjectFile::getContext(), llvm::MachineModuleInfoMachO::getGVStubEntry(), llvm::MachineModuleInfoMachO::getHiddenGVStubEntry(), llvm::MachineModuleInfo::getObjFileInfo(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer(), llvm::TargetMachine::getSymbol(), llvm::TargetLoweringObjectFile::getSymbolWithGlobalValueBase(), llvm::TargetLoweringObjectFile::getTTypeReference(), llvm::GlobalValue::hasHiddenVisibility(), and llvm::GlobalValue::hasLocalLinkage().
Referenced by llvm::X86_64MachoTargetObjectFile::getTTypeGlobalReference().
MCSection * TargetLoweringObjectFileMachO::SelectSectionForGlobal (const GlobalValue * GV, SectionKind Kind, Mangler & Mang, const TargetMachine & TM) const [override, virtual]
Implements llvm::TargetLoweringObjectFile.
Definition at line 580 of file TargetLoweringObjectFileImpl.cpp.
References checkMachOComdat(), llvm::MCObjectFileInfo::ConstDataSection, llvm::MCObjectFileInfo::ConstTextCoalSection, llvm::MCObjectFileInfo::CStringSection, llvm::MCObjectFileInfo::DataBSSSection, llvm::MCObjectFileInfo::DataCoalSection, llvm::MCObjectFileInfo::DataCommonSection, llvm::MCObjectFileInfo::DataSection, llvm::MCObjectFileInfo::EightByteConstantSection, llvm::MCObjectFileInfo::FourByteConstantSection, llvm::TargetMachine::getDataLayout(), llvm::DataLayout::getPreferredAlignment(), llvm::GlobalValue::hasExternalLinkage(), llvm::GlobalValue::hasPrivateLinkage(), llvm::SectionKind::isBSSExtern(), llvm::SectionKind::isBSSLocal(), llvm::SectionKind::isMergeable1ByteCString(), llvm::SectionKind::isMergeable2ByteCString(), llvm::SectionKind::isMergeableConst(), llvm::SectionKind::isMergeableConst16(), llvm::SectionKind::isMergeableConst4(), llvm::SectionKind::isMergeableConst8(), llvm::SectionKind::isReadOnly(), llvm::SectionKind::isReadOnlyWithRel(), llvm::SectionKind::isText(), llvm::SectionKind::isThreadBSS(), llvm::SectionKind::isThreadData(), llvm::GlobalValue::isWeakForLinker(), llvm::MCObjectFileInfo::ReadOnlySection, llvm::MCObjectFileInfo::SixteenByteConstantSection, llvm::MCObjectFileInfo::TextCoalSection, llvm::MCObjectFileInfo::TextSection, llvm::MCObjectFileInfo::TLSBSSSection, llvm::MCObjectFileInfo::TLSDataSection, and llvm::MCObjectFileInfo::UStringSection.
The documentation for this class was generated from the following files:
TargetLoweringObjectFileImpl.h
TargetLoweringObjectFileImpl.cpp