LLVM: llvm::GlobalAddressSDNode Class Reference
llvm::GlobalAddressSDNode Class Reference
#include <SelectionDAGNodes.h>
Public Member Functions
const GlobalValue * getGlobal () const
int64_t getOffset () const
unsigned char getTargetFlags () const
unsigned getAddressSpace () const
Static Public Member Functions
static bool classof (const SDNode *N)
Friends
class SelectionDAG
Detailed Description
Definition at line 1483 of file SelectionDAGNodes.h.
Member Function Documentation
static bool llvm::GlobalAddressSDNode::classof (const SDNode * N) [inline, static]
Definition at line 1499 of file SelectionDAGNodes.h.
References llvm::SDNode::getOpcode(), llvm::ISD::GlobalAddress, llvm::ISD::GlobalTLSAddress, llvm::ISD::TargetGlobalAddress, and llvm::ISD::TargetGlobalTLSAddress.
unsigned GlobalAddressSDNode::getAddressSpace () const
Definition at line 6979 of file SelectionDAG.cpp.
References llvm::PointerType::getAddressSpace(), getGlobal(), and llvm::GlobalValue::getType().
Referenced by AddNodeIDCustom(), and llvm::AMDGPUTargetLowering::LowerGlobalAddress().
const GlobalValue* llvm::GlobalAddressSDNode::getGlobal () const [inline]
Definition at line 1493 of file SelectionDAGNodes.h.
Referenced by AddNodeIDCustom(), getAddressSpace(), GetTLSADDR(), llvm::TargetLowering::isGAPlusOffset(), isMemSrcFromString(), llvm::TargetLowering::isOffsetFoldingLegal(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), LowerToTLSExecModel(), LowerToTLSLocalDynamicModel(), and PrepareCall().
int64_t llvm::GlobalAddressSDNode::getOffset () const [inline]
Definition at line 1494 of file SelectionDAGNodes.h.
Referenced by AddNodeIDCustom(), GetTLSADDR(), llvm::TargetLowering::isGAPlusOffset(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), LowerToTLSExecModel(), and LowerToTLSLocalDynamicModel().
unsigned char llvm::GlobalAddressSDNode::getTargetFlags () const [inline]
Definition at line 1495 of file SelectionDAGNodes.h.
Referenced by AddNodeIDCustom().
Friends And Related Function Documentation
friend class SelectionDAG [friend]
Reimplemented from llvm::SDNode.
Definition at line 1487 of file SelectionDAGNodes.h.
The documentation for this class was generated from the following files:
SelectionDAGNodes.h
SelectionDAG.cpp