LLVM: llvm::PPCTargetLowering Class Reference
llvm::PPCTargetLowering Class Reference
#include <PPCISelLowering.h>
Classes
struct ReuseLoadInfo
Public Member Functions
PPCTargetLowering (const PPCTargetMachine &TM, const PPCSubtarget &STI)
const char * getTargetNodeName (unsigned Opcode) const override
getTargetNodeName() - This method returns the name of a target specific DAG node.
MVT getScalarShiftAmountTy (EVT LHSTy) const override
bool isCheapToSpeculateCttz () const override
Return true if it is cheap to speculate a call to intrinsic cttz.
bool isCheapToSpeculateCtlz () const override
Return true if it is cheap to speculate a call to intrinsic ctlz.
EVT getSetCCResultType (LLVMContext &Context, EVT VT) const override
getSetCCResultType - Return the ISD::SETCC ValueType
bool enableAggressiveFMAFusion (EVT VT) const override
Return true if target always beneficiates from combining into FMA for a given value type.
bool getPreIndexedAddressParts (SDNode *N, SDValue &Base, SDValue &Offset, ISD::MemIndexedMode &AM, SelectionDAG &DAG) const override
getPreIndexedAddressParts - returns true by value, base pointer and offset pointer and addressing mode by reference if the node's address can be legally represented as pre-indexed load / store address.
bool SelectAddressRegReg (SDValue N, SDValue &Base, SDValue &Index, SelectionDAG &DAG) const
SelectAddressRegReg - Given the specified addressed, check to see if it can be represented as an indexed [r+r] operation.
bool SelectAddressRegImm (SDValue N, SDValue &Disp, SDValue &Base, SelectionDAG &DAG, bool Aligned) const
SelectAddressRegImm - Returns true if the address N can be represented by a base register plus a signed 16-bit displacement [r+imm], and if it is not better represented as reg+reg.
bool SelectAddressRegRegOnly (SDValue N, SDValue &Base, SDValue &Index, SelectionDAG &DAG) const
SelectAddressRegRegOnly - Given the specified addressed, force it to be represented as an indexed [r+r] operation.
Sched::Preference getSchedulingPreference (SDNode *N) const override
Some scheduler, e.g.
SDValue LowerOperation (SDValue Op, SelectionDAG &DAG) const override
LowerOperation - Provide custom lowering hooks for some operations.
void ReplaceNodeResults (SDNode *N, SmallVectorImpl< SDValue > &Results, SelectionDAG &DAG) const override
ReplaceNodeResults - Replace the results of node with an illegal result type with new values built out of custom code.
SDValue expandVSXLoadForLE (SDNode *N, DAGCombinerInfo &DCI) const
SDValue expandVSXStoreForLE (SDNode *N, DAGCombinerInfo &DCI) const
SDValue PerformDAGCombine (SDNode *N, DAGCombinerInfo &DCI) const override
This method will be invoked for all target nodes and for any target-independent nodes that the target has registered with invoke it for.
SDValue BuildSDIVPow2 (SDNode *N, const APInt &Divisor, SelectionDAG &DAG, std::vector< SDNode * > *Created) const override
unsigned getRegisterByName (const char *RegName, EVT VT) const override
Return the register ID of the name passed in.
void computeKnownBitsForTargetNode (const SDValue Op, APInt &KnownZero, APInt &KnownOne, const SelectionDAG &DAG, unsigned Depth=0) const override
Determine which of the bits specified in Mask are known to be either zero or one and return them in the KnownZero/KnownOne bitsets.
unsigned getPrefLoopAlignment (MachineLoop *ML) const override
Return the preferred loop alignment.
Instruction * emitLeadingFence (IRBuilder<> &Builder, AtomicOrdering Ord, bool IsStore, bool IsLoad) const override
Inserts in the IR a target-specific intrinsic specifying a fence.
Instruction * emitTrailingFence (IRBuilder<> &Builder, AtomicOrdering Ord, bool IsStore, bool IsLoad) const override
MachineBasicBlock * EmitInstrWithCustomInserter (MachineInstr *MI, MachineBasicBlock *MBB) const override
This method should be implemented by targets that mark instructions with the 'usesCustomInserter' flag.
MachineBasicBlock * EmitAtomicBinary (MachineInstr *MI, MachineBasicBlock *MBB, unsigned AtomicSize, unsigned BinOpcode) const
MachineBasicBlock * EmitPartwordAtomicBinary (MachineInstr *MI, MachineBasicBlock *MBB, bool is8bit, unsigned Opcode) const
MachineBasicBlock * emitEHSjLjSetJmp (MachineInstr *MI, MachineBasicBlock *MBB) const
MachineBasicBlock * emitEHSjLjLongJmp (MachineInstr *MI, MachineBasicBlock *MBB) const
ConstraintType getConstraintType (const std::string &Constraint) const override
getConstraintType - Given a constraint, return the type of constraint it is for this target.
ConstraintWeight getSingleConstraintMatchWeight (AsmOperandInfo &info, const char *constraint) const override
Examine constraint string and operand type and determine a weight value.
std::pair< unsigned, const
TargetRegisterClass * > getRegForInlineAsmConstraint (const TargetRegisterInfo *TRI, const std::string &Constraint, MVT VT) const override
Given a physical register constraint (e.g.
unsigned getByValTypeAlignment (Type *Ty) const override
getByValTypeAlignment - Return the desired alignment for ByVal aggregate function arguments in the caller parameter area.
void LowerAsmOperandForConstraint (SDValue Op, std::string &Constraint, std::vector< SDValue > &Ops, SelectionDAG &DAG) const override
LowerAsmOperandForConstraint - Lower the specified operand into the Ops vector.
unsigned getInlineAsmMemConstraint (const std::string &ConstraintCode) const override
bool isLegalAddressingMode (const AddrMode &AM, Type *Ty, unsigned AS) const override
isLegalAddressingMode - Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
bool isLegalICmpImmediate (int64_t Imm) const override
isLegalICmpImmediate - Return true if the specified immediate is legal icmp immediate, that is the target has icmp instructions which can compare a register against the immediate without having to materialize the immediate into a register.
bool isLegalAddImmediate (int64_t Imm) const override
isLegalAddImmediate - Return true if the specified immediate is legal add immediate, that is the target has add instructions which can add a register and the immediate without having to materialize the immediate into a register.
bool isTruncateFree (Type *Ty1, Type *Ty2) const override
isTruncateFree - Return true if it's free to truncate a value of type Ty1 to type Ty2.
bool isTruncateFree (EVT VT1, EVT VT2) const override
bool isZExtFree (SDValue Val, EVT VT2) const override
Return true if zero-extending the specific node Val to type VT2 is free (either because it's implicitly zero-extended such as ARM ldrb / ldrh or because it's folded such as X86 zero-extending loads).
bool isFPExtFree (EVT VT) const override
Return true if an fpext operation is free (for instance, because single-precision floating-point numbers are implicitly extended to double-precision).
bool shouldConvertConstantLoadToIntImm (const APInt &Imm, Type *Ty) const override
Returns true if it is beneficial to convert a load of a constant to just the constant itself.
bool isOffsetFoldingLegal (const GlobalAddressSDNode *GA) const override
Return true if folding a constant offset with the given GlobalAddress is legal.
bool getTgtMemIntrinsic (IntrinsicInfo &Info, const CallInst &I, unsigned Intrinsic) const override
Given an intrinsic, checks if on the target the intrinsic will need to map to a MemIntrinsicNode (touches memory).
EVT getOptimalMemOpType (uint64_t Size, unsigned DstAlign, unsigned SrcAlign, bool IsMemset, bool ZeroMemset, bool MemcpyStrSrc, MachineFunction &MF) const override
getOptimalMemOpType - Returns the target specific optimal type for load and store operations as a result of memset, memcpy, and memmove lowering.
bool allowsMisalignedMemoryAccesses (EVT VT, unsigned AddrSpace, unsigned Align=1, bool *Fast=nullptr) const override
Is unaligned memory access allowed for the given type, and is it fast relative to software emulation.
bool isFMAFasterThanFMulAndFAdd (EVT VT) const override
isFMAFasterThanFMulAndFAdd - Return true if an FMA operation is faster than a pair of fmul and fadd instructions.
const MCPhysReg * getScratchRegisters (CallingConv::ID CC) const override
Returns a 0 terminated array of registers that can be safely used as scratch registers.
bool shouldExpandBuildVectorWithShuffles (EVT VT, unsigned DefinedValues) const override
FastISel * createFastISel (FunctionLoweringInfo &FuncInfo, const TargetLibraryInfo *LibInfo) const override
createFastISel - This method returns a target-specific FastISel object, or null if the target does not support "fast" instruction selection.
bool functionArgumentNeedsConsecutiveRegisters (Type *Ty, CallingConv::ID CallConv, bool isVarArg) const override
Returns true if an argument of type Ty needs to be passed in a contiguous block of registers in calling convention CallConv.
Detailed Description
Definition at line 410 of file PPCISelLowering.h.
Constructor & Destructor Documentation
PPCTargetLowering::PPCTargetLowering (const PPCTargetMachine & TM, const PPCSubtarget & STI) [explicit]
Definition at line 61 of file PPCISelLowering.cpp.
References llvm::ISD::ADD, llvm::TargetLoweringBase::AddPromotedToType(), llvm::TargetLoweringBase::addRegisterClass(), llvm::ISD::ADJUST_TRAMPOLINE, llvm::ISD::AND, ANDIGlueBug, llvm::ISD::ANY_EXTEND, llvm::ISD::ATOMIC_LOAD, llvm::ISD::ATOMIC_STORE, llvm::ISD::BITCAST, llvm::ISD::BlockAddress, llvm::ISD::BR_CC, llvm::ISD::BR_JT, llvm::ISD::BRCOND, llvm::ISD::BSWAP, llvm::ISD::BUILD_PAIR, llvm::ISD::BUILD_VECTOR, llvm::TargetLoweringBase::computeRegisterProperties(), llvm::ISD::CONCAT_VECTORS, llvm::ISD::ConstantPool, llvm::RTLIB::COS_PPCF128, llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::TargetLoweringBase::Custom, llvm::PPC::DIR_970, llvm::PPC::DIR_A2, llvm::PPC::DIR_E500mc, llvm::PPC::DIR_E5500, llvm::PPC::DIR_PWR4, llvm::PPC::DIR_PWR5, llvm::PPC::DIR_PWR5X, llvm::PPC::DIR_PWR6, llvm::PPC::DIR_PWR6X, llvm::PPC::DIR_PWR7, llvm::PPC::DIR_PWR8, llvm::ISD::DYNAMIC_STACKALLOC, llvm::ISD::EH_SJLJ_LONGJMP, llvm::ISD::EH_SJLJ_SETJMP, llvm::PPCSubtarget::enableMachineScheduler(), llvm::RTLIB::EXP2_PPCF128, llvm::RTLIB::EXP_PPCF128, llvm::TargetLoweringBase::Expand, llvm::ISD::EXTLOAD, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FABS, llvm::ISD::FADD, llvm::ISD::FCEIL, llvm::ISD::FCOPYSIGN, llvm::ISD::FCOS, llvm::ISD::FDIV, llvm::ISD::FEXP, llvm::ISD::FEXP2, llvm::ISD::FFLOOR, llvm::ISD::FGETSIGN, llvm::ISD::FLOG, llvm::ISD::FLOG10, llvm::ISD::FLOG2, llvm::ISD::FLT_ROUNDS_, llvm::ISD::FMA, llvm::ISD::FMAXNUM, llvm::ISD::FMINNUM, llvm::ISD::FMUL, llvm::ISD::FNEARBYINT, llvm::ISD::FNEG, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FP_ROUND_INREG, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FPOW, llvm::ISD::FPOWI, llvm::ISD::FREM, llvm::ISD::FRINT, llvm::ISD::FROUND, llvm::ISD::FSIN, llvm::ISD::FSINCOS, llvm::ISD::FSQRT, llvm::ISD::FSUB, llvm::ISD::FTRUNC, llvm::PPCSubtarget::getDarwinDirective(), llvm::PPCSubtarget::getRegisterInfo(), llvm::ISD::GlobalAddress, llvm::ISD::GlobalTLSAddress, llvm::PPCSubtarget::has64BitSupport(), llvm::PPCSubtarget::hasAltivec(), llvm::PPCSubtarget::hasFCPSGN(), llvm::PPCSubtarget::hasFPCVT(), llvm::PPCSubtarget::hasFPRND(), llvm::PPCSubtarget::hasFRE(), llvm::PPCSubtarget::hasFRES(), llvm::PPCSubtarget::hasFRSQRTE(), llvm::PPCSubtarget::hasFRSQRTES(), llvm::PPCSubtarget::hasFSQRT(), llvm::PPCSubtarget::hasLFIWAX(), llvm::PPCSubtarget::hasP8Altivec(), llvm::PPCSubtarget::hasP8Vector(), llvm::PPCSubtarget::hasPOPCNTD(), llvm::PPCSubtarget::hasQPX(), llvm::PPCSubtarget::hasVSX(), llvm::Sched::Hybrid, llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::ISD::INIT_TRAMPOLINE, llvm::ISD::INSERT_VECTOR_ELT, llvm::MVT::integer_valuetypes(), llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::PPCSubtarget::isDarwin(), llvm::PPCSubtarget::isPPC64(), llvm::PPCSubtarget::isSVR4ABI(), llvm::ISD::JumpTable, llvm::TargetLoweringBase::Legal, llvm::ISD::LOAD, llvm::RTLIB::LOG10_PPCF128, llvm::RTLIB::LOG2_PPCF128, llvm::RTLIB::LOG_PPCF128, llvm::TargetLoweringBase::MaxStoresPerMemcpy, llvm::TargetLoweringBase::MaxStoresPerMemcpyOptSize, llvm::TargetLoweringBase::MaxStoresPerMemmove, llvm::TargetLoweringBase::MaxStoresPerMemmoveOptSize, llvm::TargetLoweringBase::MaxStoresPerMemset, llvm::TargetLoweringBase::MaxStoresPerMemsetOptSize, llvm::ISD::MUL, llvm::ISD::MULHS, llvm::ISD::MULHU, llvm::TargetMachine::Options, llvm::ISD::OR, llvm::MVT::Other, llvm::RTLIB::POW_PPCF128, llvm::MVT::ppcf128, llvm::ISD::PRE_INC, llvm::ISD::PREFETCH, llvm::TargetLoweringBase::Promote, llvm::ISD::READCYCLECOUNTER, llvm::RTLIB::REM_PPCF128, llvm::ISD::ROTR, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SDIV, llvm::ISD::SDIVREM, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::TargetLoweringBase::setBooleanContents(), llvm::TargetLoweringBase::setBooleanVectorContents(), llvm::ISD::SETCC, llvm::TargetLoweringBase::setCondCodeAction(), llvm::TargetLoweringBase::setExceptionPointerRegister(), llvm::TargetLoweringBase::setExceptionSelectorRegister(), llvm::TargetLoweringBase::setHasMultipleConditionRegisters(), llvm::TargetLoweringBase::setIndexedLoadAction(), llvm::TargetLoweringBase::setIndexedStoreAction(), llvm::TargetLoweringBase::setInsertFencesForAtomic(), llvm::TargetLoweringBase::setJumpIsExpensive(), llvm::TargetLoweringBase::setLibcallName(), llvm::TargetLoweringBase::setLoadExtAction(), llvm::TargetLoweringBase::setMinFunctionAlignment(), llvm::TargetLoweringBase::setMinStackArgumentAlignment(), llvm::ISD::SETO, llvm::ISD::SETOGE, llvm::ISD::SETOLE, llvm::ISD::SETONE, llvm::TargetLoweringBase::setOperationAction(), llvm::TargetLoweringBase::setPrefFunctionAlignment(), llvm::TargetLoweringBase::setPrefLoopAlignment(), llvm::TargetLoweringBase::setSchedulingPreference(), llvm::TargetLoweringBase::setStackPointerRegisterToSaveRestore(), llvm::TargetLoweringBase::setTargetDAGCombine(), llvm::TargetLoweringBase::setTruncStoreAction(), llvm::ISD::SETUEQ, llvm::ISD::SETUGT, llvm::ISD::SETULT, llvm::ISD::SETUO, llvm::TargetLoweringBase::setUseUnderscoreLongJmp(), llvm::TargetLoweringBase::setUseUnderscoreSetJmp(), llvm::ISD::SEXTLOAD, llvm::ISD::SHL, llvm::RTLIB::SHL_I128, llvm::ISD::SHL_PARTS, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::RTLIB::SIN_PPCF128, llvm::ISD::SINT_TO_FP, llvm::ISD::SMUL_LOHI, llvm::Sched::Source, llvm::RTLIB::SQRT_PPCF128, llvm::ISD::SRA, llvm::RTLIB::SRA_I128, llvm::ISD::SRA_PARTS, llvm::ISD::SREM, llvm::ISD::SRL, llvm::RTLIB::SRL_I128, llvm::ISD::SRL_PARTS, llvm::ISD::STACKRESTORE, llvm::ISD::STACKSAVE, llvm::ISD::STORE, llvm::ISD::SUB, llvm::ISD::TRAP, llvm::ISD::TRUNCATE, llvm::ISD::UDIV, llvm::ISD::UDIVREM, llvm::ISD::UINT_TO_FP, llvm::ISD::UMUL_LOHI, llvm::TargetOptions::UnsafeFPMath, llvm::ISD::UREM, llvm::PPCSubtarget::use64BitRegs(), llvm::PPCSubtarget::useCRBits(), llvm::MVT::v16i8, llvm::MVT::v1i128, llvm::MVT::v2f64, llvm::MVT::v2i16, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v2i8, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i1, llvm::MVT::v4i32, llvm::MVT::v8i16, llvm::ISD::VAARG, llvm::ISD::VACOPY, llvm::ISD::VAEND, llvm::ISD::VASTART, llvm::ISD::VECTOR_SHUFFLE, llvm::MVT::vector_valuetypes(), llvm::ISD::VSELECT, llvm::ISD::XOR, llvm::ISD::ZERO_EXTEND, llvm::TargetLoweringBase::ZeroOrNegativeOneBooleanContent, llvm::TargetLoweringBase::ZeroOrOneBooleanContent, and llvm::ISD::ZEXTLOAD.
Member Function Documentation
bool PPCTargetLowering::allowsMisalignedMemoryAccesses (EVT VT, unsigned AddrSpace, unsigned Align = 1, bool * Fast = nullptr) const [override, virtual]
Is unaligned memory access allowed for the given type, and is it fast relative to software emulation.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 11252 of file PPCISelLowering.cpp.
References DisablePPCUnaligned, llvm::EVT::getSimpleVT(), llvm::PPCSubtarget::hasVSX(), llvm::EVT::isSimple(), llvm::MVT::isVector(), llvm::MVT::ppcf128, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v4f32, and llvm::MVT::v4i32.
SDValue PPCTargetLowering::BuildSDIVPow2 (SDNode * N, const APInt & Divisor, SelectionDAG & DAG, std::vector< SDNode * > * Created) const [override, virtual]
Reimplemented from llvm::TargetLowering.
Definition at line 10484 of file PPCISelLowering.cpp.
References llvm::countTrailingZeros(), llvm::DL, llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::MVT::i64, llvm::APInt::isPowerOf2(), llvm::PPCSubtarget::isPPC64(), llvm::PPCISD::SRA_ADDZE, and llvm::ISD::SUB.
void PPCTargetLowering::computeKnownBitsForTargetNode (const SDValue Op, APInt & KnownZero, APInt & KnownOne, const SelectionDAG & DAG, unsigned Depth = 0) const [override, virtual]
Determine which of the bits specified in Mask are known to be either zero or one and return them in the KnownZero/KnownOne bitsets.
computeKnownBitsForTargetNode - Determine which of the bits specified in Mask are known to be either zero or one and return them in the KnownZero/KnownOne bitsets.
Reimplemented from llvm::TargetLowering.
Definition at line 10519 of file PPCISelLowering.cpp.
References llvm::APInt::getBitWidth(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::MVT::i16, llvm::ISD::INTRINSIC_WO_CHAIN, and llvm::PPCISD::LBRX.
FastISel * PPCTargetLowering::createFastISel (FunctionLoweringInfo & FuncInfo, const TargetLibraryInfo * LibInfo) const [override, virtual]
createFastISel - This method returns a target-specific FastISel object, or null if the target does not support "fast" instruction selection.
Reimplemented from llvm::TargetLowering.
Definition at line 11340 of file PPCISelLowering.cpp.
MachineBasicBlock * PPCTargetLowering::EmitAtomicBinary (MachineInstr * MI, MachineBasicBlock * MBB, unsigned AtomicSize, unsigned BinOpcode) const
Definition at line 7914 of file PPCISelLowering.cpp.
References llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineFunction::CreateMachineBasicBlock(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineBasicBlock::end(), F(), llvm::MCInstrInfo::get(), llvm::MachineBasicBlock::getBasicBlock(), llvm::MachineInstr::getDebugLoc(), llvm::PPCSubtarget::getInstrInfo(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::PPCSubtarget::hasPartwordAtomics(), llvm::MachineFunction::insert(), llvm_unreachable, llvm::PPC::PRED_NE, llvm::MachineBasicBlock::splice(), TII, and llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs().
Referenced by EmitInstrWithCustomInserter(), and EmitPartwordAtomicBinary().
MachineBasicBlock * PPCTargetLowering::emitEHSjLjLongJmp (MachineInstr * MI, MachineBasicBlock * MBB) const
Definition at line 8280 of file PPCISelLowering.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::BP, llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::DL, llvm::MachineInstr::eraseFromParent(), llvm::MCInstrInfo::get(), llvm::MachineInstr::getDebugLoc(), llvm::PPCSubtarget::getInstrInfo(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::TargetLoweringBase::getPointerTy(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::TargetMachine::getRelocationModel(), llvm::MVT::getStoreSize(), llvm::MachineFunction::getTarget(), llvm::MVT::i64, llvm::PPCSubtarget::isSVR4ABI(), llvm::AArch64DB::LD, llvm::MachineInstr::memoperands_begin(), llvm::MachineInstr::memoperands_end(), llvm::PPCISD::MTCTR, llvm::Reloc::PIC_, llvm::MachineInstrBuilder::setMemRefs(), setUsesTOCBasePtr(), llvm::SP, and TII.
Referenced by EmitInstrWithCustomInserter().
llvm::MachineBasicBlock * PPCTargetLowering::emitEHSjLjSetJmp (MachineInstr * MI, MachineBasicBlock * MBB) const
Definition at line 8132 of file PPCISelLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineInstrBuilder::addRegMask(), llvm::MachineBasicBlock::addSuccessor(), llvm::MachineBasicBlock::begin(), llvm::BP, llvm::BuildMI(), llvm::MachineFunction::CreateMachineBasicBlock(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::DL, llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), llvm::MCInstrInfo::get(), llvm::MachineBasicBlock::getBasicBlock(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFunction(), llvm::PPCSubtarget::getInstrInfo(), llvm::PPCRegisterInfo::getNoPreservedMask(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::TargetLoweringBase::getPointerTy(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::TargetLoweringBase::getRegClassFor(), llvm::MachineFunction::getRegInfo(), llvm::PPCSubtarget::getRegisterInfo(), llvm::MVT::getStoreSize(), llvm::Function::hasFnAttribute(), llvm::TargetRegisterClass::hasType(), I, llvm::MVT::i64, llvm::MachineFunction::insert(), llvm::PPCSubtarget::isPPC64(), llvm::PPCSubtarget::isSVR4ABI(), llvm::MachineInstr::memoperands_begin(), llvm::MachineInstr::memoperands_end(), llvm::Attribute::Naked, llvm::TargetOpcode::PHI, llvm::MachineInstrBuilder::setMemRefs(), setUsesTOCBasePtr(), llvm::MachineBasicBlock::splice(), TII, and llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs().
Referenced by EmitInstrWithCustomInserter().
MachineBasicBlock * PPCTargetLowering::EmitInstrWithCustomInserter (MachineInstr * MI, MachineBasicBlock * MBB) const [override, virtual]
This method should be implemented by targets that mark instructions with the 'usesCustomInserter' flag.
These instructions are special in various ways, which require special support to insert. The specified MachineInstr is created but not inserted into any basic blocks, and this method is called to expand it into a sequence of instructions, potentially also creating new basic blocks and control flow. As long as the returned basic block is different (i.e., we created a new one), the custom inserter is free to modify the rest of MBB.
Reimplemented from llvm::TargetLowering.
Definition at line 8389 of file PPCISelLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstr::addOperand(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), AND, llvm::PPCISD::ANDIo_1_EQ_BIT, llvm::PPCISD::ANDIo_1_GT_BIT, llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::TargetOpcode::COPY, llvm::MachineOperand::CreateImm(), llvm::MachineFunction::CreateMachineBasicBlock(), llvm::MachineOperand::CreateReg(), llvm::MachineRegisterInfo::createVirtualRegister(), EmitAtomicBinary(), emitEHSjLjLongJmp(), emitEHSjLjSetJmp(), EmitPartwordAtomicBinary(), llvm::TargetLoweringBase::emitPatchPoint(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), F(), llvm::ISD::FADD, llvm::MCInstrInfo::get(), llvm::MachineBasicBlock::getBasicBlock(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getImm(), llvm::PPCSubtarget::getInstrInfo(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::PPCSubtarget::hasISEL(), llvm::PPCSubtarget::hasPartwordAtomics(), llvm::MachineFunction::insert(), llvm::TargetInstrInfo::insertSelect(), llvm::PPCSubtarget::isPPC64(), llvm::PPCSubtarget::isSVR4ABI(), llvm_unreachable, llvm::PPCISD::MFFS, OR, llvm::TargetOpcode::PATCHPOINT, llvm::TargetOpcode::PHI, llvm::PPC::PRED_BIT_SET, llvm::PPC::PRED_NE, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), setUsesTOCBasePtr(), llvm::MachineBasicBlock::splice(), llvm::TargetOpcode::STACKMAP, TII, llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs(), and XOR.
Instruction * PPCTargetLowering::emitLeadingFence (IRBuilder<> & Builder, AtomicOrdering Ord, bool IsStore, bool IsLoad) const [override, virtual]
Inserts in the IR a target-specific intrinsic specifying a fence.
It is called by AtomicExpandPass before expanding an AtomicRMW/AtomicCmpXchg/AtomicStore/AtomicLoad. RMW and CmpXchg set both IsStore and IsLoad to true. This function should either return a nullptr, or a pointer to an IR-level Instruction*. Even complex fence sequences can be represented by a single Instruction* through an intrinsic to be lowered later. Backends with !getInsertFencesForAtomic() should keep a no-op here. Backends should override this method to produce target-specific intrinsic for their fences. FIXME: Please note that the default implementation here in terms of IR-level fences exists for historical/compatibility reasons and is unsound* ! Fences cannot, in general, be used to restore sequential consistency. For example, consider the following example: atomic<int> x = y = 0; int r1, r2, r3, r4; Thread 0: x.store(1); Thread 1: y.store(1); Thread 2: r1 = x.load(); r2 = y.load(); Thread 3: r3 = y.load(); r4 = x.load(); r1 = r3 = 1 and r2 = r4 = 0 is impossible as long as the accesses are all seq_cst. But if they are lowered to monotonic accesses, no amount of IR-level fences can prevent it.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 7891 of file PPCISelLowering.cpp.
References callIntrinsic(), llvm::isAtLeastRelease(), and llvm::SequentiallyConsistent.
MachineBasicBlock * PPCTargetLowering::EmitPartwordAtomicBinary (MachineInstr * MI, MachineBasicBlock * MBB, bool is8bit, unsigned Opcode) const
Definition at line 7999 of file PPCISelLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), AND, llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineFunction::CreateMachineBasicBlock(), llvm::MachineRegisterInfo::createVirtualRegister(), EmitAtomicBinary(), llvm::MachineBasicBlock::end(), F(), llvm::MCInstrInfo::get(), llvm::MachineBasicBlock::getBasicBlock(), llvm::MachineInstr::getDebugLoc(), llvm::PPCSubtarget::getInstrInfo(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::PPCSubtarget::hasPartwordAtomics(), llvm::MachineFunction::insert(), llvm::PPCSubtarget::isPPC64(), OR, llvm::PPC::PRED_NE, llvm::MachineBasicBlock::splice(), TII, and llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs().
Referenced by EmitInstrWithCustomInserter().
Instruction * PPCTargetLowering::emitTrailingFence (IRBuilder<> & Builder, AtomicOrdering Ord, bool IsStore, bool IsLoad) const [override, virtual]
Reimplemented from llvm::TargetLoweringBase.
Definition at line 7901 of file PPCISelLowering.cpp.
References callIntrinsic(), and llvm::isAtLeastAcquire().
bool PPCTargetLowering::enableAggressiveFMAFusion (EVT VT) const [override, virtual]
Return true if target always beneficiates from combining into FMA for a given value type.
This must typically return false on targets where FMA takes more cycles to execute than FADD.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1068 of file PPCISelLowering.cpp.
References llvm::EVT::isFloatingPoint().
SDValue PPCTargetLowering::expandVSXLoadForLE (SDNode * N, DAGCombinerInfo & DCI) const
Definition at line 9840 of file PPCISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::AddToWorklist(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::MemSDNode::getBasePtr(), llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::MemSDNode::getMemOperand(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::EVT::getSimpleVT(), llvm::MachineMemOperand::getSize(), llvm::SDValue::getValue(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::ISD::INTRINSIC_W_CHAIN, llvm_unreachable, llvm::SPII::Load, llvm::ISD::LOAD, llvm::PPCISD::LXVD2X, llvm::MVT::Other, and llvm::PPCISD::XXSWAPD.
Referenced by PerformDAGCombine().
SDValue PPCTargetLowering::expandVSXStoreForLE (SDNode * N, DAGCombinerInfo & DCI) const
Definition at line 9887 of file PPCISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::AddToWorklist(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::StoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::MemSDNode::getMemOperand(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::EVT::getSimpleVT(), llvm::MachineMemOperand::getSize(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::ISD::INTRINSIC_VOID, llvm_unreachable, llvm::MVT::Other, llvm::SPII::Store, llvm::ISD::STORE, llvm::PPCISD::STXVD2X, and llvm::PPCISD::XXSWAPD.
Referenced by PerformDAGCombine().
bool llvm::PPCTargetLowering::functionArgumentNeedsConsecutiveRegisters (Type * Ty, CallingConv::ID CallConv, bool isVarArg) const [inline, override, virtual]
Returns true if an argument of type Ty needs to be passed in a contiguous block of registers in calling convention CallConv.
Reimplemented from llvm::TargetLowering.
Definition at line 638 of file PPCISelLowering.h.
References llvm::Type::isArrayTy().
unsigned PPCTargetLowering::getByValTypeAlignment (Type * Ty) const [override, virtual]
getByValTypeAlignment - Return the desired alignment for ByVal aggregate function arguments in the caller parameter area.
This is the actual alignment, not its logarithm.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 955 of file PPCISelLowering.cpp.
References Align(), getMaxByValAlign(), llvm::PPCSubtarget::hasAltivec(), llvm::PPCSubtarget::hasQPX(), llvm::PPCSubtarget::isDarwin(), and llvm::PPCSubtarget::isPPC64().
PPCTargetLowering::ConstraintType PPCTargetLowering::getConstraintType (const std::string & Constraint) const [override, virtual]
getConstraintType - Given a constraint, return the type of constraint it is for this target.
Reimplemented from llvm::TargetLowering.
Definition at line 10595 of file PPCISelLowering.cpp.
References llvm::TargetLowering::C_Memory, and llvm::TargetLowering::C_RegisterClass.
unsigned llvm::PPCTargetLowering::getInlineAsmMemConstraint (const std::string & ConstraintCode) const [inline, override, virtual]
Reimplemented from llvm::TargetLowering.
Definition at line 542 of file PPCISelLowering.h.
References llvm::InlineAsm::Constraint_es, llvm::InlineAsm::Constraint_o, llvm::InlineAsm::Constraint_Q, llvm::InlineAsm::Constraint_Z, and llvm::InlineAsm::Constraint_Zy.
EVT PPCTargetLowering::getOptimalMemOpType (uint64_t Size, unsigned DstAlign, unsigned SrcAlign, bool IsMemset, bool ZeroMemset, bool MemcpyStrSrc, MachineFunction & MF) const [override, virtual]
getOptimalMemOpType - Returns the target specific optimal type for load and store operations as a result of memset, memcpy, and memmove lowering.
If DstAlign is zero that means it's safe to destination alignment can satisfy any constraint. Similarly if SrcAlign is zero it means there isn't a need to check it against alignment requirement, probably because the source does not need to be loaded. If 'IsMemset' is true, that means it's expanding a memset. If 'ZeroMemset' is true, that means it's a memset of zero. 'MemcpyStrSrc' indicates whether the memcpy source is constant so it does not need to be loaded. It returns EVT::Other if the type should be determined using generic target-independent logic.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 11161 of file PPCISelLowering.cpp.
References F(), llvm::MachineFunction::getFunction(), llvm::TargetLoweringBase::getTargetMachine(), llvm::PPCSubtarget::hasAltivec(), llvm::Function::hasFnAttribute(), llvm::PPCSubtarget::hasP8Vector(), llvm::PPCSubtarget::hasQPX(), llvm::PPCSubtarget::hasVSX(), llvm::MVT::i64, llvm::PPCSubtarget::isPPC64(), llvm::Attribute::NoImplicitFloat, llvm::CodeGenOpt::None, and llvm::MVT::v4i32.
unsigned PPCTargetLowering::getPrefLoopAlignment (MachineLoop * ML) const [override, virtual]
Return the preferred loop alignment.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 10559 of file PPCISelLowering.cpp.
References llvm::LoopBase< BlockT, LoopT >::block_begin(), llvm::LoopBase< BlockT, LoopT >::block_end(), llvm::PPC::DIR_970, llvm::PPC::DIR_PWR4, llvm::PPC::DIR_PWR5, llvm::PPC::DIR_PWR5X, llvm::PPC::DIR_PWR6, llvm::PPC::DIR_PWR6X, llvm::PPC::DIR_PWR7, llvm::PPC::DIR_PWR8, llvm::PPCSubtarget::getDarwinDirective(), llvm::PPCSubtarget::getInstrInfo(), llvm::PPCInstrInfo::GetInstSizeInBytes(), I, llvm::ARM_PROC::IE, and TII.
bool PPCTargetLowering::getPreIndexedAddressParts (SDNode * N, SDValue & Base, SDValue & Offset, ISD::MemIndexedMode & AM, SelectionDAG & DAG) const [override, virtual]
getPreIndexedAddressParts - returns true by value, base pointer and offset pointer and addressing mode by reference if the node's address can be legally represented as pre-indexed load / store address.
Reimplemented from llvm::TargetLowering.
Definition at line 1745 of file PPCISelLowering.cpp.
References DisablePPCPreinc, llvm::SDValue::getNode(), llvm::PPCSubtarget::hasQPX(), llvm::MVT::i32, llvm::MVT::i64, llvm::SDNode::isPredecessorOf(), llvm::EVT::isVector(), llvm::AArch64DB::LD, llvm::ISD::PRE_INC, SelectAddressRegImm(), SelectAddressRegReg(), SelectAddressRegRegOnly(), llvm::ISD::SEXTLOAD, llvm::AArch64DB::ST, std::swap(), llvm::MVT::v4f32, and llvm::MVT::v4f64.
std::pair< unsigned, const TargetRegisterClass * > PPCTargetLowering::getRegForInlineAsmConstraint (const TargetRegisterInfo * TRI, const std::string & Constraint, MVT VT) const [override, virtual]
Given a physical register constraint (e.g.
{edx}), return the register number and the register class for the register.
Given a register class constraint, like 'r', if this corresponds directly to an LLVM register class, return a register of 0 and the register class pointer.
This should only be used for C_Register constraints. On error, this returns a register number of 0 and a null register class pointer.
Reimplemented from llvm::TargetLowering.
Definition at line 10679 of file PPCISelLowering.cpp.
References llvm::StringRef::equals_lower(), llvm::MVT::f32, llvm::TargetRegisterInfo::getMatchingSuperReg(), llvm::PPCSubtarget::hasQPX(), llvm::MVT::i64, llvm::PPCSubtarget::isPPC64(), and llvm::MVT::v4f32.
unsigned PPCTargetLowering::getRegisterByName (const char * RegName, EVT VT) const [override, virtual]
Return the register ID of the name passed in.
Used by named register global variables extension. There is no target-independent behaviour so the default action is to bail.
Reimplemented from llvm::TargetLowering.
Definition at line 10930 of file PPCISelLowering.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), llvm::MVT::i64, is64Bit(), llvm::PPCSubtarget::isDarwinABI(), llvm::PPCSubtarget::isPPC64(), llvm::R13, and llvm::report_fatal_error().
MVT llvm::PPCTargetLowering::getScalarShiftAmountTy (EVT LHSTy) const [inline, override, virtual]
Reimplemented from llvm::TargetLoweringBase.
Definition at line 421 of file PPCISelLowering.h.
References llvm::MVT::i32.
Sched::Preference PPCTargetLowering::getSchedulingPreference (SDNode *) const [override, virtual]
Some scheduler, e.g.
hybrid, can switch to different scheduling heuristics for different nodes. This function returns the preference (or none) for the given node.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 11331 of file PPCISelLowering.cpp.
References DisableILPPref, llvm::PPCSubtarget::enableMachineScheduler(), llvm::TargetLoweringBase::getSchedulingPreference(), and llvm::Sched::ILP.
const MCPhysReg * PPCTargetLowering::getScratchRegisters (CallingConv::ID CC) const [override, virtual]
Returns a 0 terminated array of registers that can be safely used as scratch registers.
Reimplemented from llvm::TargetLowering.
Definition at line 11305 of file PPCISelLowering.cpp.
EVT PPCTargetLowering::getSetCCResultType (LLVMContext & Context, EVT VT) const [override, virtual]
getSetCCResultType - Return the ISD::SETCC ValueType
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1058 of file PPCISelLowering.cpp.
References llvm::EVT::changeVectorElementTypeToInteger(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::PPCSubtarget::hasQPX(), llvm::MVT::i1, llvm::MVT::i32, llvm::EVT::isVector(), and llvm::PPCSubtarget::useCRBits().
Referenced by ReplaceNodeResults().
TargetLowering::ConstraintWeight PPCTargetLowering::getSingleConstraintMatchWeight (AsmOperandInfo & info, const char * constraint) const [override, virtual]
Examine constraint string and operand type and determine a weight value.
Examine constraint type and operand type and determine a weight value.
The operand object must already have been set up with the operand type.
This object must already have been set up with the operand type and the current alternative constraint selected.
Reimplemented from llvm::TargetLowering.
Definition at line 10627 of file PPCISelLowering.cpp.
References llvm::TargetLowering::AsmOperandInfo::CallOperandVal, llvm::TargetLowering::CW_Default, llvm::TargetLowering::CW_Invalid, llvm::TargetLowering::CW_Memory, llvm::TargetLowering::CW_Register, llvm::Value::getType(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), llvm::Type::isIntegerTy(), and llvm::Type::isVectorTy().
const char * PPCTargetLowering::getTargetNodeName (unsigned Opcode) const [override, virtual]
getTargetNodeName() - This method returns the name of a target specific DAG node.
Reimplemented from llvm::TargetLowering.
Definition at line 968 of file PPCISelLowering.cpp.
References llvm::PPCISD::ADD_TLS, llvm::PPCISD::ADDI_DTPREL_L, llvm::PPCISD::ADDI_TLSGD_L, llvm::PPCISD::ADDI_TLSGD_L_ADDR, llvm::PPCISD::ADDI_TLSLD_L, llvm::PPCISD::ADDI_TLSLD_L_ADDR, llvm::PPCISD::ADDIS_DTPREL_HA, llvm::PPCISD::ADDIS_GOT_TPREL_HA, llvm::PPCISD::ADDIS_TLSGD_HA, llvm::PPCISD::ADDIS_TLSLD_HA, llvm::PPCISD::ANDIo_1_EQ_BIT, llvm::PPCISD::ANDIo_1_GT_BIT, llvm::PPCISD::BCTRL, llvm::PPCISD::BCTRL_LOAD_TOC, llvm::PPCISD::BDNZ, llvm::PPCISD::BDZ, llvm::PPCISD::CALL, llvm::PPCISD::CALL_NOP, llvm::PPCISD::CLRBHRB, llvm::PPCISD::CMPB, llvm::PPCISD::COND_BRANCH, llvm::PPCISD::CR6SET, llvm::PPCISD::CR6UNSET, llvm::PPCISD::DYNALLOC, llvm::PPCISD::EH_SJLJ_LONGJMP, llvm::PPCISD::EH_SJLJ_SETJMP, llvm::PPCISD::FADDRTZ, llvm::PPCISD::FCFID, llvm::PPCISD::FCFIDS, llvm::PPCISD::FCFIDU, llvm::PPCISD::FCFIDUS, llvm::PPCISD::FCTIDUZ, llvm::PPCISD::FCTIDZ, llvm::PPCISD::FCTIWUZ, llvm::PPCISD::FCTIWZ, llvm::PPCISD::FIRST_NUMBER, llvm::PPCISD::FRE, llvm::PPCISD::FRSQRTE, llvm::PPCISD::FSEL, llvm::PPCISD::GET_TLS_ADDR, llvm::PPCISD::GET_TLSLD_ADDR, llvm::PPCISD::GlobalBaseReg, llvm::PPCISD::Hi, llvm::PPCISD::LBRX, llvm::PPCISD::LD_GOT_TPREL_L, llvm::PPCISD::LFIWAX, llvm::PPCISD::LFIWZX, llvm::PPCISD::Lo, llvm::PPCISD::LXVD2X, llvm::PPCISD::MFBHRBE, llvm::PPCISD::MFFS, llvm::PPCISD::MFOCRF, llvm::PPCISD::MFVSR, llvm::PPCISD::MTCTR, llvm::PPCISD::MTVSRA, llvm::PPCISD::MTVSRZ, llvm::PPCISD::PPC32_GOT, llvm::PPCISD::PPC32_PICGOT, llvm::PPCISD::QBFLT, llvm::PPCISD::QVALIGNI, llvm::PPCISD::QVESPLATI, llvm::PPCISD::QVFPERM, llvm::PPCISD::QVGPCI, llvm::PPCISD::QVLFSb, llvm::PPCISD::READ_TIME_BASE, llvm::PPCISD::RET_FLAG, llvm::PPCISD::RFEBB, llvm::PPCISD::SC, llvm::PPCISD::SHL, llvm::PPCISD::SRA, llvm::PPCISD::SRA_ADDZE, llvm::PPCISD::SRL, llvm::PPCISD::STBRX, llvm::PPCISD::STFIWX, llvm::PPCISD::STXVD2X, llvm::PPCISD::TC_RETURN, llvm::PPCISD::TOC_ENTRY, llvm::PPCISD::VADD_SPLAT, llvm::PPCISD::VCMP, llvm::PPCISD::VCMPo, llvm::PPCISD::VMADDFP, llvm::PPCISD::VNMSUBFP, llvm::PPCISD::VPERM, and llvm::PPCISD::XXSWAPD.
bool PPCTargetLowering::getTgtMemIntrinsic (IntrinsicInfo & , const CallInst & , unsigned) const [override, virtual]
Given an intrinsic, checks if on the target the intrinsic will need to map to a MemIntrinsicNode (touches memory).
If this is the case, it returns true and store the intrinsic information into the IntrinsicInfo that was passed to the function.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 10958 of file PPCISelLowering.cpp.
References llvm::TargetLoweringBase::IntrinsicInfo::align, llvm::CallInst::getArgOperand(), llvm::EVT::getStoreSize(), llvm::MVT::i16, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::TargetLoweringBase::IntrinsicInfo::memVT, llvm::TargetLoweringBase::IntrinsicInfo::offset, llvm::TargetLoweringBase::IntrinsicInfo::opc, llvm::TargetLoweringBase::IntrinsicInfo::ptrVal, llvm::TargetLoweringBase::IntrinsicInfo::readMem, llvm::TargetLoweringBase::IntrinsicInfo::size, llvm::MVT::v2f32, llvm::MVT::v2f64, llvm::MVT::v4f32, llvm::MVT::v4i32, llvm::TargetLoweringBase::IntrinsicInfo::vol, and llvm::TargetLoweringBase::IntrinsicInfo::writeMem.
bool llvm::PPCTargetLowering::isCheapToSpeculateCtlz () const [inline, override, virtual]
Return true if it is cheap to speculate a call to intrinsic ctlz.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 427 of file PPCISelLowering.h.
bool llvm::PPCTargetLowering::isCheapToSpeculateCttz () const [inline, override, virtual]
Return true if it is cheap to speculate a call to intrinsic cttz.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 423 of file PPCISelLowering.h.
bool PPCTargetLowering::isFMAFasterThanFMulAndFAdd (EVT VT) const [override, virtual]
isFMAFasterThanFMulAndFAdd - Return true if an FMA operation is faster than a pair of fmul and fadd instructions.
fmuladd intrinsics will be expanded to FMAs when this method returns true, otherwise fmuladd is expanded to fmul + fadd.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 11287 of file PPCISelLowering.cpp.
References llvm::MVT::f32, llvm::EVT::getScalarType(), llvm::EVT::getSimpleVT(), llvm::EVT::isSimple(), and llvm::MVT::SimpleTy.
bool PPCTargetLowering::isFPExtFree (EVT VT) const [override, virtual]
Return true if an fpext operation is free (for instance, because single-precision floating-point numbers are implicitly extended to double-precision).
Reimplemented from llvm::TargetLoweringBase.
Definition at line 11239 of file PPCISelLowering.cpp.
References llvm::EVT::isFloatingPoint().
bool PPCTargetLowering::isLegalAddImmediate (int64_t Imm) const [override, virtual]
isLegalAddImmediate - Return true if the specified immediate is legal add immediate, that is the target has add instructions which can add a register and the immediate without having to materialize the immediate into a register.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 11248 of file PPCISelLowering.cpp.
References llvm::isInt< 16 >(), and llvm::isUInt< 16 >().
bool PPCTargetLowering::isLegalAddressingMode (const AddrMode & AM, Type * Ty, unsigned AS) const [override, virtual]
isLegalAddressingMode - Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 10827 of file PPCISelLowering.cpp.
References llvm::TargetLoweringBase::AddrMode::BaseGV, llvm::TargetLoweringBase::AddrMode::BaseOffs, llvm::TargetLoweringBase::AddrMode::HasBaseReg, llvm::Type::isVectorTy(), and llvm::TargetLoweringBase::AddrMode::Scale.
bool PPCTargetLowering::isLegalICmpImmediate (int64_t Imm) const [override, virtual]
isLegalICmpImmediate - Return true if the specified immediate is legal icmp immediate, that is the target has icmp instructions which can compare a register against the immediate without having to materialize the immediate into a register.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 11244 of file PPCISelLowering.cpp.
References llvm::isInt< 16 >(), and llvm::isUInt< 16 >().
bool PPCTargetLowering::isOffsetFoldingLegal (const GlobalAddressSDNode * GA) const [override, virtual]
Return true if folding a constant offset with the given GlobalAddress is legal.
It is frequently not legal in PIC relocation models.
Reimplemented from llvm::TargetLowering.
Definition at line 10953 of file PPCISelLowering.cpp.
bool PPCTargetLowering::isTruncateFree (Type * Ty1, Type * Ty2) const [override, virtual]
isTruncateFree - Return true if it's free to truncate a value of type Ty1 to type Ty2.
e.g. On PPC it's free to truncate a i64 value in register X1 to i32 by referencing its sub-register R1.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 11203 of file PPCISelLowering.cpp.
References llvm::Type::getPrimitiveSizeInBits(), and llvm::Type::isIntegerTy().
bool PPCTargetLowering::isTruncateFree (EVT VT1, EVT VT2) const [override, virtual]
Reimplemented from llvm::TargetLoweringBase.
Definition at line 11211 of file PPCISelLowering.cpp.
References llvm::EVT::getSizeInBits(), and llvm::EVT::isInteger().
bool PPCTargetLowering::isZExtFree (SDValue Val, EVT VT2) const [override, virtual]
Return true if zero-extending the specific node Val to type VT2 is free (either because it's implicitly zero-extended such as ARM ldrb / ldrh or because it's folded such as X86 zero-extending loads).
Reimplemented from llvm::TargetLoweringBase.
Definition at line 11219 of file PPCISelLowering.cpp.
References llvm::LoadSDNode::getExtensionType(), llvm::MemSDNode::getMemoryVT(), llvm::MVT::i1, llvm::MVT::i16, llvm::PPCSubtarget::isPPC64(), llvm::ISD::NON_EXTLOAD, and llvm::ISD::ZEXTLOAD.
void PPCTargetLowering::LowerAsmOperandForConstraint (SDValue Op, std::string & Constraint, std::vector< SDValue > & Ops, SelectionDAG & DAG) const [override, virtual]
LowerAsmOperandForConstraint - Lower the specified operand into the Ops vector.
If it is invalid, don't add anything to Ops.
Reimplemented from llvm::TargetLowering.
Definition at line 10751 of file PPCISelLowering.cpp.
References llvm::dyn_cast(), llvm::SDValue::getNode(), llvm::ConstantSDNode::getSExtValue(), llvm::SelectionDAG::getTargetConstant(), llvm::MVT::i64, llvm::isInt< 16 >(), llvm::isPowerOf2_64(), llvm::isUInt< 16 >(), and llvm_unreachable.
SDValue PPCTargetLowering::LowerOperation (SDValue Op, SelectionDAG & DAG) const [override, virtual]
LowerOperation - Provide custom lowering hooks for some operations.
Reimplemented from llvm::TargetLowering.
Definition at line 7742 of file PPCISelLowering.cpp.
References llvm::ISD::ADJUST_TRAMPOLINE, llvm::ISD::BlockAddress, llvm::ISD::BUILD_VECTOR, llvm::ISD::ConstantPool, llvm::ISD::DYNAMIC_STACKALLOC, llvm::ISD::EH_SJLJ_LONGJMP, llvm::ISD::EH_SJLJ_SETJMP, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FLT_ROUNDS_, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FRAMEADDR, llvm::SDValue::getOpcode(), llvm::ISD::GlobalAddress, llvm::ISD::GlobalTLSAddress, llvm::ISD::INIT_TRAMPOLINE, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::ISD::JumpTable, llvm_unreachable, llvm::ISD::LOAD, llvm::ISD::MUL, llvm::ISD::RETURNADDR, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::ISD::SHL_PARTS, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SINT_TO_FP, llvm::ISD::SRA_PARTS, llvm::ISD::SRL_PARTS, llvm::ISD::STACKRESTORE, llvm::ISD::STORE, llvm::ISD::TRUNCATE, llvm::ISD::UINT_TO_FP, llvm::ISD::VAARG, llvm::ISD::VACOPY, llvm::ISD::VASTART, and llvm::ISD::VECTOR_SHUFFLE.
SDValue PPCTargetLowering::PerformDAGCombine (SDNode * N, DAGCombinerInfo & DCI) const [override, virtual]
This method will be invoked for all target nodes and for any target-independent nodes that the target has registered with invoke it for.
The semantics are as follows: Return Value: SDValue.Val == 0 - No change was made SDValue.Val == N - N was replaced, is dead, and is already handled. otherwise - N should be replaced by the returned Operand.
In addition, methods provided by DAGCombinerInfo may be used to perform more complex transformations.
Reimplemented from llvm::TargetLowering.
Definition at line 9937 of file PPCISelLowering.cpp.
References llvm::ISD::ADD, ADD, llvm::TargetLowering::DAGCombinerInfo::AddToWorklist(), llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::PPCISD::BDNZ, llvm::PPCISD::BDZ, llvm::ISD::BITCAST, llvm::ISD::BR, llvm::ISD::BR_CC, llvm::ISD::BRCOND, llvm::ISD::BSWAP, BuildIntrinsicOp(), llvm::TargetLowering::DAGCombinerInfo::CombineTo(), llvm::PPCISD::COND_BRANCH, llvm::TargetLowering::DAGCombinerInfo::DAG, expandVSXLoadForLE(), expandVSXStoreForLE(), llvm::MVT::f32, llvm::PPCISD::FCTIWZ, findConsecutiveLoad(), llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_SINT, llvm::DataLayout::getABITypeAlignment(), llvm::MemSDNode::getAlignment(), llvm::APInt::getAllOnesValue(), getAltivecCompareInfo(), llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::TargetLoweringBase::getDataLayout(), llvm::SelectionDAG::getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::EVT::getScalarType(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::EVT::getStoreSize(), llvm::SelectionDAG::getTargetConstant(), llvm::EVT::getTypeForEVT(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, llvm::PPCSubtarget::hasAltivec(), llvm::PPCSubtarget::hasLDBRX(), llvm::SDNode::hasNUsesOfValue(), llvm::SDValue::hasOneUse(), llvm::SDNode::hasOneUse(), llvm::PPCSubtarget::hasP8Vector(), llvm::PPCSubtarget::hasQPX(), llvm::PPCSubtarget::hasSTFIWX(), llvm::PPCSubtarget::hasVSX(), llvm::MVT::i16, llvm::MVT::i64, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::PPCSubtarget::isLittleEndian(), llvm::ISD::isNON_EXTLoad(), llvm::PPCSubtarget::isPPC64(), llvm::EVT::isSimple(), llvm::LSBaseSDNode::isUnindexed(), isZero(), llvm::PPCISD::LBRX, llvm::SPII::Load, llvm::ISD::LOAD, llvm::SelectionDAG::MaskedValueIsZero(), llvm::PPCISD::MFOCRF, llvm::MVT::Other, Other, llvm::MVT::ppcf128, llvm::PPC::PRED_EQ, llvm::PPC::PRED_GE, llvm::PPC::PRED_LT, llvm::PPC::PRED_NE, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::ISD::SETEQ, llvm::ISD::SETNE, llvm::PPCISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::ISD::SINT_TO_FP, llvm::PPCISD::SRA, llvm::PPCISD::SRL, llvm::PPCISD::STBRX, llvm::PPCISD::STFIWX, llvm::ISD::STORE, llvm::ISD::TokenFactor, llvm::ISD::TRUNCATE, llvm::ISD::UINT_TO_FP, llvm::SDNode::use_begin(), llvm::SDNode::use_end(), llvm::objcarc::User, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v4i32, llvm::MVT::v8i16, llvm::PPCISD::VCMP, llvm::PPCISD::VCMPo, VI, llvm::ISD::ZERO_EXTEND, and llvm::APInt::zext().
void PPCTargetLowering::ReplaceNodeResults (SDNode * N, SmallVectorImpl< SDValue > & Results, SelectionDAG & DAG) const [override, virtual]
ReplaceNodeResults - Replace the results of node with an illegal result type with new values built out of custom code.
Reimplemented from llvm::TargetLowering.
Definition at line 7803 of file PPCISelLowering.cpp.
References llvm::ISD::BUILD_PAIR, llvm::ISD::EXTRACT_ELEMENT, llvm::PPCISD::FADDRTZ, llvm::ISD::FP_ROUND_INREG, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), getSetCCResultType(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::i1, llvm::MVT::i64, llvm::ISD::INTRINSIC_W_CHAIN, llvm::PPCSubtarget::isPPC64(), llvm::PPCSubtarget::isSVR4ABI(), llvm_unreachable, llvm::MVT::Other, llvm::MVT::ppcf128, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::PPCISD::READ_TIME_BASE, llvm::ISD::READCYCLECOUNTER, and llvm::ISD::VAARG.
bool PPCTargetLowering::SelectAddressRegImm (SDValue N, SDValue & Disp, SDValue & Base, SelectionDAG & DAG, bool Aligned) const
SelectAddressRegImm - Returns true if the address N can be represented by a base register plus a signed 16-bit displacement [r+imm], and if it is not better represented as reg+reg.
Returns true if the address N can be represented by a base register plus a signed 16-bit displacement [r+imm], and if it is not better represented as reg+reg.
If Aligned is true, only accept displacements suitable for STD and friends, i.e. multiples of 4.
Definition at line 1618 of file PPCISelLowering.cpp.
References ADD, llvm::SelectionDAG::computeKnownBits(), fixupFuncForFI(), llvm::SelectionDAG::getMachineNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetFrameIndex(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::APInt::getZExtValue(), llvm::MVT::i32, isIntS16Immediate(), llvm::PPCSubtarget::isPPC64(), llvm::MipsISD::Lo, OR, SelectAddressRegReg(), llvm::ISD::TargetConstantPool, llvm::ISD::TargetGlobalAddress, llvm::ISD::TargetGlobalTLSAddress, and llvm::ISD::TargetJumpTable.
Referenced by getPreIndexedAddressParts().
bool PPCTargetLowering::SelectAddressRegReg (SDValue N, SDValue & Base, SDValue & Index, SelectionDAG & DAG) const
SelectAddressRegReg - Given the specified addressed, check to see if it can be represented as an indexed [r+r] operation.
Returns false if it can be more efficiently represented with [r+imm].
Definition at line 1533 of file PPCISelLowering.cpp.
References ADD, llvm::SelectionDAG::computeKnownBits(), llvm::APInt::getBoolValue(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), isIntS16Immediate(), llvm::MipsISD::Lo, and OR.
Referenced by getPreIndexedAddressParts(), SelectAddressRegImm(), and SelectAddressRegRegOnly().
bool PPCTargetLowering::SelectAddressRegRegOnly (SDValue N, SDValue & Base, SDValue & Index, SelectionDAG & DAG) const
SelectAddressRegRegOnly - Given the specified addressed, force it to be represented as an indexed [r+r] operation.
Definition at line 1717 of file PPCISelLowering.cpp.
References ADD, llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getRegister(), llvm::SDValue::getValueType(), llvm::PPCSubtarget::isPPC64(), and SelectAddressRegReg().
Referenced by getPreIndexedAddressParts().
bool PPCTargetLowering::shouldConvertConstantLoadToIntImm (const APInt & Imm, Type * Ty) const [override, virtual]
Returns true if it is beneficial to convert a load of a constant to just the constant itself.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 11193 of file PPCISelLowering.cpp.
References llvm::Type::getPrimitiveSizeInBits(), and llvm::Type::isIntegerTy().
bool PPCTargetLowering::shouldExpandBuildVectorWithShuffles (EVT VT, unsigned DefinedValues) const [override, virtual]
Reimplemented from llvm::TargetLoweringBase.
Definition at line 11318 of file PPCISelLowering.cpp.
References llvm::PPCSubtarget::hasQPX(), llvm::MVT::v2i64, llvm::MVT::v4f32, and llvm::MVT::v4i1.
The documentation for this class was generated from the following files:
PPCISelLowering.h
PPCISelLowering.cpp