LLVM: llvm::MDTuple Class Reference
llvm::MDTuple Class Reference
Tuple of metadata.
#include <Metadata.h>
Public Member Functions
unsigned getHash () const
Get the hash, if any.
TempMDTuple clone () const
Return a (temporary) clone of this.
Static Public Member Functions
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata * > MDs)
Return a distinct node.
static TempMDTuple getTemporary (LLVMContext &Context, ArrayRef< Metadata * > MDs)
Return a temporary node.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
Friends
class LLVMContextImpl
class MDNode
Detailed Description
Tuple of metadata.
This is the simple MDNode arbitrary tuple. Nodes are uniqued by default based on their operands.
Definition at line 960 of file Metadata.h.
Member Function Documentation
static bool llvm::MDTuple::classof (const Metadata * MD) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::MDNode.
Definition at line 1013 of file Metadata.h.
References llvm::Metadata::getMetadataID(), and llvm::Metadata::MDTupleKind.
TempMDTuple llvm::MDTuple::clone () const [inline]
Return a (temporary) clone of this.
Reimplemented from llvm::MDNode.
Definition at line 1011 of file Metadata.h.
static MDTuple* llvm::MDTuple::get (LLVMContext & Context, ArrayRef< Metadata * > MDs) [inline, static]
Reimplemented from llvm::MDNode.
Definition at line 986 of file Metadata.h.
References llvm::MDNode::Context, and llvm::Metadata::Uniqued.
Referenced by AddOperand(), llvm::DIBuilder::finalize(), and llvm::DIBuilder::getOrCreateArray().
static MDTuple* llvm::MDTuple::getDistinct (LLVMContext & Context, ArrayRef< Metadata * > MDs) [inline, static]
Return a distinct node.
Return a distinct node -- i.e., a node that is not uniqued.
Reimplemented from llvm::MDNode.
Definition at line 996 of file Metadata.h.
References llvm::Metadata::Distinct.
unsigned llvm::MDTuple::getHash () const [inline]
Get the hash, if any.
Definition at line 984 of file Metadata.h.
References llvm::Metadata::SubclassData32.
static MDTuple* llvm::MDTuple::getIfExists (LLVMContext & Context, ArrayRef< Metadata * > MDs) [inline, static]
Reimplemented from llvm::MDNode.
Definition at line 989 of file Metadata.h.
References llvm::Metadata::Uniqued.
static TempMDTuple llvm::MDTuple::getTemporary (LLVMContext & Context, ArrayRef< Metadata * > MDs) [inline, static]
Return a temporary node.
For use in constructing cyclic MDNode structures. A temporary MDNode is not uniqued, may be RAUW'd, and must be manually deleted with deleteTemporary.
Reimplemented from llvm::MDNode.
Definition at line 1005 of file Metadata.h.
References llvm::Metadata::Temporary.
Referenced by CloneAliasScopeMetadata(), llvm::DIBuilder::createCompileUnit(), and llvm::DIBuilder::createFunction().
Friends And Related Function Documentation
friend class LLVMContextImpl [friend]
Reimplemented from llvm::MDNode.
Definition at line 961 of file Metadata.h.
friend class MDNode [friend]
Definition at line 962 of file Metadata.h.
The documentation for this class was generated from the following files:
Metadata.h
Metadata.cpp