LLVM: llvm::RuntimeDyldCheckerImpl Class Reference
llvm::RuntimeDyldCheckerImpl Class Reference
#include <RuntimeDyldCheckerImpl.h>
Classes
struct SectionAddressInfo
Public Member Functions
RuntimeDyldCheckerImpl (RuntimeDyld &RTDyld, MCDisassembler *Disassembler, MCInstPrinter *InstPrinter, llvm::raw_ostream &ErrStream)
bool check (StringRef CheckExpr) const
bool checkAllRulesInBuffer (StringRef RulePrefix, MemoryBuffer *MemBuf) const
Friends
class RuntimeDyldChecker
class RuntimeDyldImpl
class RuntimeDyldCheckerExprEval
class RuntimeDyldELF
Detailed Description
Definition at line 18 of file RuntimeDyldCheckerImpl.h.
Constructor & Destructor Documentation
RuntimeDyldCheckerImpl::RuntimeDyldCheckerImpl (RuntimeDyld & RTDyld, MCDisassembler * Disassembler, MCInstPrinter * InstPrinter, llvm::raw_ostream & ErrStream)
Definition at line 678 of file RuntimeDyldChecker.cpp.
Member Function Documentation
bool RuntimeDyldCheckerImpl::check (StringRef CheckExpr) const
Definition at line 687 of file RuntimeDyldChecker.cpp.
References llvm::dbgs(), DEBUG, llvm::RuntimeDyldCheckerExprEval::evaluate(), P, and llvm::StringRef::trim().
Referenced by checkAllRulesInBuffer().
bool RuntimeDyldCheckerImpl::checkAllRulesInBuffer (StringRef RulePrefix, MemoryBuffer * MemBuf) const
Definition at line 698 of file RuntimeDyldChecker.cpp.
References check(), llvm::MemoryBuffer::getBufferEnd(), llvm::MemoryBuffer::getBufferStart(), llvm::StringRef::size(), llvm::StringRef::startswith(), and llvm::StringRef::substr().
Friends And Related Function Documentation
friend class RuntimeDyldChecker [friend]
Definition at line 19 of file RuntimeDyldCheckerImpl.h.
friend class RuntimeDyldCheckerExprEval [friend]
Definition at line 21 of file RuntimeDyldCheckerImpl.h.
friend class RuntimeDyldELF [friend]
Definition at line 22 of file RuntimeDyldCheckerImpl.h.
friend class RuntimeDyldImpl [friend]
Definition at line 20 of file RuntimeDyldCheckerImpl.h.
The documentation for this class was generated from the following files:
RuntimeDyldCheckerImpl.h
RuntimeDyldChecker.cpp