LLVM: llvm::DILexicalBlockFile Class Reference
llvm::DILexicalBlockFile Class Reference
#include <DebugInfoMetadata.h>
Public Member Functions
DEFINE_MDNODE_GET (DILexicalBlockFile,(DILocalScope *Scope, DIFile *File, unsigned Discriminator),(Scope, File, Discriminator)) DEFINE_MDNODE_GET(DILexicalBlockFile
Metadata Metadata unsigned
Discriminator
TempDILexicalBlockFile clone () const
Create a (temporary) clone of this.
unsigned getLine () const
Forwarding accessors to LexicalBlock.
unsigned getColumn () const
unsigned getDiscriminator () const
Static Public Member Functions
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
Public Attributes
Metadata * Scope
Metadata Metadata * File
Metadata Metadata unsigned Discriminator
Metadata Metadata unsigned Scope
Metadata Metadata unsigned File
Friends
class LLVMContextImpl
class MDNode
Detailed Description
Definition at line 1518 of file DebugInfoMetadata.h.
Member Function Documentation
static bool llvm::DILexicalBlockFile::classof (const Metadata * MD) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::DILexicalBlockBase.
Definition at line 1565 of file DebugInfoMetadata.h.
References llvm::Metadata::DILexicalBlockFileKind, and llvm::Metadata::getMetadataID().
Metadata Metadata unsigned Discriminator TempDILexicalBlockFile llvm::DILexicalBlockFile::clone () const [inline]
Create a (temporary) clone of this.
Reimplemented from llvm::MDNode.
Definition at line 1557 of file DebugInfoMetadata.h.
llvm::DILexicalBlockFile::DEFINE_MDNODE_GET (DILexicalBlockFile , (DILocalScope *Scope, DIFile *File,unsigned Discriminator) , (Scope, File, Discriminator))
unsigned llvm::DILexicalBlockFile::getColumn () const
Reimplemented from llvm::DILexicalBlockBase.
unsigned llvm::DILexicalBlockFile::getDiscriminator () const [inline]
Definition at line 1563 of file DebugInfoMetadata.h.
Referenced by llvm::MDNodeKeyImpl< DILexicalBlockFile >::isKeyOf(), and WriteDILexicalBlockFile().
unsigned llvm::DILexicalBlockFile::getLine () const
Forwarding accessors to LexicalBlock.
TODO: Remove these and update code to use DILexicalBlock directly.
Reimplemented from llvm::DILexicalBlockBase.
Friends And Related Function Documentation
friend class LLVMContextImpl [friend]
Reimplemented from llvm::DINode.
Definition at line 1519 of file DebugInfoMetadata.h.
friend class MDNode [friend]
Reimplemented from llvm::DINode.
Definition at line 1520 of file DebugInfoMetadata.h.
Member Data Documentation
Metadata Metadata unsigned llvm::DILexicalBlockFile::Discriminator
Definition at line 1554 of file DebugInfoMetadata.h.
Metadata Metadata* llvm::DILexicalBlockFile::File
Definition at line 1554 of file DebugInfoMetadata.h.
Metadata Metadata unsigned llvm::DILexicalBlockFile::File
Definition at line 1554 of file DebugInfoMetadata.h.
Metadata* llvm::DILexicalBlockFile::Scope
Definition at line 1554 of file DebugInfoMetadata.h.
Metadata Metadata unsigned llvm::DILexicalBlockFile::Scope
Definition at line 1554 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
DebugInfoMetadata.h
DebugInfoMetadata.cpp