LLVM: llvm::IPDBSession Class Reference
llvm::IPDBSession Class Reference
IPDBSession defines an interface used to provide a context for querying debug information from a debug data source (for example, a PDB).
#include <IPDBSession.h>
Public Member Functions
virtual ~IPDBSession ()
virtual uint64_t getLoadAddress () const =0
virtual void setLoadAddress (uint64_t Address)=0
virtual std::unique_ptr
< PDBSymbolExe > getGlobalScope () const =0
virtual std::unique_ptr
< PDBSymbol > getSymbolById (uint32_t SymbolId) const =0
template<typename T >
std::unique_ptr< T > getConcreteSymbolById (uint32_t SymbolId) const
virtual std::unique_ptr
< PDBSymbol > findSymbolByAddress (uint64_t Address, PDB_SymType Type) const =0
virtual std::unique_ptr
< IPDBEnumLineNumbers > findLineNumbersByAddress (uint64_t Address, uint32_t Length) const =0
virtual std::unique_ptr
< IPDBEnumSourceFiles > getAllSourceFiles () const =0
virtual std::unique_ptr
< IPDBEnumSourceFiles > getSourceFilesForCompiland (const PDBSymbolCompiland &Compiland) const =0
virtual std::unique_ptr
< IPDBSourceFile > getSourceFileById (uint32_t FileId) const =0
virtual std::unique_ptr
< IPDBEnumDataStreams > getDebugStreams () const =0
Detailed Description
IPDBSession defines an interface used to provide a context for querying debug information from a debug data source (for example, a PDB).
Definition at line 24 of file IPDBSession.h.
Constructor & Destructor Documentation
IPDBSession::~IPDBSession () [virtual]
Definition at line 22 of file PDBInterfaceAnchors.cpp.
Member Function Documentation
virtual std::unique_ptr<IPDBEnumLineNumbers> llvm::IPDBSession::findLineNumbersByAddress (uint64_t Address, uint32_t Length) const [pure virtual]
Implemented in llvm::DIASession.
virtual std::unique_ptr<PDBSymbol> llvm::IPDBSession::findSymbolByAddress (uint64_t Address, PDB_SymType Type) const [pure virtual]
Implemented in llvm::DIASession.
virtual std::unique_ptr<IPDBEnumSourceFiles> llvm::IPDBSession::getAllSourceFiles () const [pure virtual]
Implemented in llvm::DIASession.
template<typename T > std::unique_ptr<T> llvm::IPDBSession::getConcreteSymbolById (uint32_t SymbolId) const [inline]
Definition at line 34 of file IPDBSession.h.
References llvm::dyn_cast(), getSymbolById(), and llvm::ARMBuildAttrs::Symbol.
Referenced by llvm::PDBSymbolFunc::getClassParent(), llvm::PDBSymbolTypeEnum::getClassParent(), llvm::PDBSymbolFunc::getSignature(), and llvm::PDBSymbolTypeEnum::getUnderlyingType().
virtual std::unique_ptr<IPDBEnumDataStreams> llvm::IPDBSession::getDebugStreams () const [pure virtual]
Implemented in llvm::DIASession.
virtual std::unique_ptr<PDBSymbolExe> llvm::IPDBSession::getGlobalScope () const [pure virtual]
Implemented in llvm::DIASession.
virtual uint64_t llvm::IPDBSession::getLoadAddress () const [pure virtual]
Implemented in llvm::DIASession.
virtual std::unique_ptr<IPDBSourceFile> llvm::IPDBSession::getSourceFileById (uint32_t FileId) const [pure virtual]
Implemented in llvm::DIASession.
virtual std::unique_ptr<IPDBEnumSourceFiles> llvm::IPDBSession::getSourceFilesForCompiland (const PDBSymbolCompiland & Compiland) const [pure virtual]
Implemented in llvm::DIASession.
virtual std::unique_ptr<PDBSymbol> llvm::IPDBSession::getSymbolById (uint32_t SymbolId) const [pure virtual]
Implemented in llvm::DIASession.
Referenced by llvm::PDBSymbolTypeFunctionSig::getClassParent(), getConcreteSymbolById(), llvm::PDBSymbolTypeArray::getElementType(), llvm::PDBSymbolTypePointer::getPointeeType(), llvm::PDBSymbolTypeFunctionSig::getReturnType(), and llvm::PDBSymbolData::getType().
virtual void llvm::IPDBSession::setLoadAddress (uint64_t Address) [pure virtual]
Implemented in llvm::DIASession.
The documentation for this class was generated from the following files:
IPDBSession.h
PDBInterfaceAnchors.cpp