LLVM: llvm::AssumptionPrinterPass Class Reference
llvm::AssumptionPrinterPass Class Reference
Printer pass for the AssumptionAnalysis results.
#include <AssumptionCache.h>
Public Member Functions
AssumptionPrinterPass (raw_ostream &OS)
PreservedAnalyses run (Function &F, AnalysisManager< Function > *AM)
Static Public Member Functions
static StringRef name ()
Detailed Description
Printer pass for the AssumptionAnalysis results.
Definition at line 122 of file AssumptionCache.h.
Constructor & Destructor Documentation
llvm::AssumptionPrinterPass::AssumptionPrinterPass (raw_ostream & OS) [inline, explicit]
Definition at line 126 of file AssumptionCache.h.
Member Function Documentation
static StringRef llvm::AssumptionPrinterPass::name () [inline, static]
Definition at line 129 of file AssumptionCache.h.
PreservedAnalyses AssumptionPrinterPass::run (Function & F, AnalysisManager< Function > * AM)
Definition at line 79 of file AssumptionCache.cpp.
References llvm::PreservedAnalyses::all(), llvm::AssumptionCache::assumptions(), F(), llvm::Value::getName(), and llvm::detail::AnalysisManagerBase< AnalysisManager< IRUnitT >, IRUnitT >::getResult().
The documentation for this class was generated from the following files:
AssumptionCache.h
AssumptionCache.cpp