LLVM: llvm::IndirectBrInst Class Reference
llvm::IndirectBrInst Class Reference
IndirectBrInst - Indirect Branch Instruction.
#include <Instructions.h>
Public Member Functions
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Provide fast operand accessors.
Value * getAddress ()
const Value * getAddress () const
void setAddress (Value *V)
unsigned getNumDestinations () const
getNumDestinations - return the number of possible destinations in this indirectbr instruction.
BasicBlock * getDestination (unsigned i)
getDestination - Return the specified destination.
const BasicBlock * getDestination (unsigned i) const
void addDestination (BasicBlock *Dest)
addDestination - Add a destination.
void removeDestination (unsigned i)
removeDestination - This method removes the specified successor from the indirectbr instruction.
unsigned getNumSuccessors () const
Return the number of successors that this terminator has.
BasicBlock * getSuccessor (unsigned i) const
Return the specified successor.
void setSuccessor (unsigned i, BasicBlock *NewSucc)
Update the specified successor to point at the provided block.
Static Public Member Functions
static IndirectBrInst * Create (Value *Address, unsigned NumDests, Instruction *InsertBefore=nullptr)
static IndirectBrInst * Create (Value *Address, unsigned NumDests, BasicBlock *InsertAtEnd)
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
IndirectBrInst * clone_impl () const override
Detailed Description
IndirectBrInst - Indirect Branch Instruction.
Definition at line 2999 of file Instructions.h.
Member Function Documentation
void IndirectBrInst::addDestination (BasicBlock * Dest)
addDestination - Add a destination.
Definition at line 3414 of file Instructions.cpp.
References llvm::User::getNumOperands(), llvm::User::getOperandList(), and llvm::User::setNumHungOffUseOperands().
static bool llvm::IndirectBrInst::classof (const Instruction * I) [inline, static]
Reimplemented from llvm::TerminatorInst.
Definition at line 3070 of file Instructions.h.
References llvm::Instruction::getOpcode().
static bool llvm::IndirectBrInst::classof (const Value * V) [inline, static]
Methods for support type inquiry through isa, cast, and dyn_cast:
Reimplemented from llvm::TerminatorInst.
Definition at line 3073 of file Instructions.h.
IndirectBrInst * IndirectBrInst::clone_impl () const [override, protected, virtual]
Implements llvm::Instruction.
Definition at line 3617 of file Instructions.cpp.
static IndirectBrInst* llvm::IndirectBrInst::Create (Value * Address, unsigned NumDests, Instruction * InsertBefore = nullptr) [inline, static]
Definition at line 3027 of file Instructions.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateIndirectBr().
static IndirectBrInst* llvm::IndirectBrInst::Create (Value * Address, unsigned NumDests, BasicBlock * InsertAtEnd) [inline, static]
Definition at line 3031 of file Instructions.h.
llvm::IndirectBrInst::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Provide fast operand accessors.
Value* llvm::IndirectBrInst::getAddress () [inline]
Definition at line 3040 of file Instructions.h.
Referenced by llvm::Interpreter::visitIndirectBrInst().
const Value* llvm::IndirectBrInst::getAddress () const [inline]
Definition at line 3041 of file Instructions.h.
BasicBlock* llvm::IndirectBrInst::getDestination (unsigned i) [inline]
getDestination - Return the specified destination.
Definition at line 3050 of file Instructions.h.
const BasicBlock* llvm::IndirectBrInst::getDestination (unsigned i) const [inline]
Definition at line 3051 of file Instructions.h.
unsigned llvm::IndirectBrInst::getNumDestinations () const [inline]
getNumDestinations - return the number of possible destinations in this indirectbr instruction.
Definition at line 3047 of file Instructions.h.
unsigned llvm::IndirectBrInst::getNumSuccessors () const [inline]
Return the number of successors that this terminator has.
Reimplemented from llvm::TerminatorInst.
Definition at line 3061 of file Instructions.h.
BasicBlock* llvm::IndirectBrInst::getSuccessor (unsigned idx) const [inline]
Return the specified successor.
Reimplemented from llvm::TerminatorInst.
Definition at line 3062 of file Instructions.h.
void IndirectBrInst::removeDestination (unsigned idx)
removeDestination - This method removes the specified successor from the indirectbr instruction.
Definition at line 3426 of file Instructions.cpp.
References llvm::User::getNumOperands(), llvm::User::getOperandList(), llvm::Use::set(), and llvm::User::setNumHungOffUseOperands().
void llvm::IndirectBrInst::setAddress (Value * V) [inline]
Definition at line 3042 of file Instructions.h.
void llvm::IndirectBrInst::setSuccessor (unsigned idx, BasicBlock * B) [inline]
Update the specified successor to point at the provided block.
Reimplemented from llvm::TerminatorInst.
Definition at line 3065 of file Instructions.h.
The documentation for this class was generated from the following files:
Instructions.h
Instructions.cpp