LLVM: llvm::orc::CtorDtorIterator Class Reference
llvm::orc::CtorDtorIterator Class Reference
This iterator provides a convenient way to iterate over the elements of an llvm.global_ctors/llvm.global_dtors instance.
#include <ExecutionUtils.h>
Classes
struct Element
Accessor for an element of the global_ctors/global_dtors array.
Public Member Functions
CtorDtorIterator (const GlobalVariable *GV, bool End)
Construct an iterator instance.
bool operator== (const CtorDtorIterator &Other) const
Test iterators for equality.
bool operator!= (const CtorDtorIterator &Other) const
Test iterators for inequality.
CtorDtorIterator & operator++ ()
Pre-increment iterator.
CtorDtorIterator operator++ (int)
Post-increment iterator.
Element operator* () const
Dereference iterator.
Detailed Description
This iterator provides a convenient way to iterate over the elements of an llvm.global_ctors/llvm.global_dtors instance.
The easiest way to get hold of instances of this class is to use the getConstructors/getDestructors functions.
Definition at line 38 of file ExecutionUtils.h.
Constructor & Destructor Documentation
llvm::orc::CtorDtorIterator::CtorDtorIterator (const GlobalVariable * GV, bool End)
Construct an iterator instance.
If End is true then this iterator acts as the end of the range, otherwise it is the beginning.
Definition at line 20 of file ExecutionUtils.cpp.
Member Function Documentation
bool llvm::orc::CtorDtorIterator::operator!= (const CtorDtorIterator & Other) const
Test iterators for inequality.
Definition at line 31 of file ExecutionUtils.cpp.
References Other.
CtorDtorIterator::Element llvm::orc::CtorDtorIterator::operator* () const
Dereference iterator.
The resulting value provides a read-only view of this element of the global_ctors/global_dtors list.
Definition at line 46 of file ExecutionUtils.cpp.
References llvm::WinEH::CE, llvm::CS, llvm::Data, llvm::dyn_cast(), F(), llvm::User::getOperand(), and llvm::ConstantInt::getZExtValue().
CtorDtorIterator & llvm::orc::CtorDtorIterator::operator++ ()
Pre-increment iterator.
Definition at line 35 of file ExecutionUtils.cpp.
CtorDtorIterator llvm::orc::CtorDtorIterator::operator++ (int)
Post-increment iterator.
Definition at line 40 of file ExecutionUtils.cpp.
bool llvm::orc::CtorDtorIterator::operator== (const CtorDtorIterator & Other) const
Test iterators for equality.
Definition at line 26 of file ExecutionUtils.cpp.
The documentation for this class was generated from the following files:
ExecutionUtils.h
ExecutionUtils.cpp