LLVM: llvm::ARMTargetParser Class Reference
llvm::ARMTargetParser Class Reference
#include <TargetParser.h>
Static Public Member Functions
static StringRef getCanonicalArchName (StringRef Arch)
static const char * getFPUName (unsigned FPUKind)
static unsigned getFPUVersion (unsigned FPUKind)
static unsigned getFPUNeonSupportLevel (unsigned FPUKind)
static unsigned getFPURestriction (unsigned FPUKind)
static bool getFPUFeatures (unsigned FPUKind, std::vector< const char * > &Features)
static const char * getArchName (unsigned ArchKind)
static unsigned getArchAttr (unsigned ArchKind)
static const char * getCPUAttr (unsigned ArchKind)
static const char * getSubArch (unsigned ArchKind)
static const char * getArchExtName (unsigned ArchExtKind)
static const char * getDefaultCPU (StringRef Arch)
static unsigned parseFPU (StringRef FPU)
static unsigned parseArch (StringRef Arch)
static unsigned parseArchExt (StringRef ArchExt)
static unsigned parseCPUArch (StringRef CPU)
static unsigned parseArchISA (StringRef Arch)
static unsigned parseArchEndian (StringRef Arch)
static unsigned parseArchProfile (StringRef Arch)
static unsigned parseArchVersion (StringRef Arch)
Detailed Description
Definition at line 154 of file TargetParser.h.
Member Function Documentation
unsigned ARMTargetParser::getArchAttr (unsigned ArchKind) [static]
Definition at line 347 of file TargetParser.cpp.
References llvm::ARM::AK_LAST, and llvm::ARMBuildAttrs::Pre_v4.
const char * ARMTargetParser::getArchExtName (unsigned ArchExtKind) [static]
Definition at line 353 of file TargetParser.cpp.
References llvm::ARM::AEK_LAST.
const char * ARMTargetParser::getArchName (unsigned ArchKind) [static]
Definition at line 329 of file TargetParser.cpp.
References llvm::ARM::AK_LAST.
StringRef ARMTargetParser::getCanonicalArchName (StringRef Arch) [static]
Definition at line 410 of file TargetParser.cpp.
References llvm::ARM_PROC::A, llvm::StringRef::empty(), llvm::StringRef::endswith(), llvm::lltok::Error, llvm::StringRef::find(), llvm::StringRef::npos, llvm::StringRef::size(), llvm::StringRef::startswith(), and llvm::StringRef::substr().
Referenced by llvm::Triple::getARMCPUForArch(), parseArch(), parseArchProfile(), parseArchVersion(), parseARMArch(), and parseSubArch().
const char * ARMTargetParser::getCPUAttr (unsigned ArchKind) [static]
Definition at line 335 of file TargetParser.cpp.
References llvm::ARM::AK_LAST.
const char * ARMTargetParser::getDefaultCPU (StringRef Arch) [static]
Definition at line 359 of file TargetParser.cpp.
References llvm::ARM::AK_INVALID, and parseArch().
Referenced by llvm::Triple::getARMCPUForArch().
bool ARMTargetParser::getFPUFeatures (unsigned FPUKind, std::vector< const char * > & Features) [static]
Definition at line 254 of file TargetParser.cpp.
References llvm::ARM::FK_INVALID, llvm::ARM::FK_LAST, llvm::ARM::FR_D16, llvm::ARM::FR_None, llvm::ARM::FR_SP_D16, llvm::ARM::NS_Crypto, llvm::ARM::NS_Neon, and llvm::ARM::NS_None.
const char * ARMTargetParser::getFPUName (unsigned FPUKind) [static]
Definition at line 230 of file TargetParser.cpp.
References llvm::ARM::FK_LAST.
unsigned ARMTargetParser::getFPUNeonSupportLevel (unsigned FPUKind) [static]
Definition at line 242 of file TargetParser.cpp.
References llvm::ARM::FK_LAST.
unsigned ARMTargetParser::getFPURestriction (unsigned FPUKind) [static]
Definition at line 248 of file TargetParser.cpp.
References llvm::ARM::FK_LAST.
unsigned ARMTargetParser::getFPUVersion (unsigned FPUKind) [static]
Definition at line 236 of file TargetParser.cpp.
References llvm::ARM::FK_LAST.
const char * ARMTargetParser::getSubArch (unsigned ArchKind) [static]
Definition at line 341 of file TargetParser.cpp.
References llvm::ARM::AK_LAST.
unsigned ARMTargetParser::parseArch (StringRef Arch) [static]
Definition at line 469 of file TargetParser.cpp.
References llvm::ARM_PROC::A, llvm::ARM::AK_INVALID, llvm::StringRef::endswith(), and getCanonicalArchName().
Referenced by getDefaultCPU(), parseArchProfile(), parseArchVersion(), and parseSubArch().
unsigned ARMTargetParser::parseArchEndian (StringRef Arch) [static]
Definition at line 506 of file TargetParser.cpp.
References llvm::ARM::EK_BIG, llvm::ARM::EK_INVALID, llvm::ARM::EK_LITTLE, llvm::StringRef::endswith(), and llvm::StringRef::startswith().
Referenced by parseARMArch().
unsigned ARMTargetParser::parseArchExt (StringRef ArchExt) [static]
Definition at line 479 of file TargetParser.cpp.
References llvm::ARM_PROC::A, and llvm::ARM::AEK_INVALID.
unsigned ARMTargetParser::parseArchISA (StringRef Arch) [static]
Definition at line 496 of file TargetParser.cpp.
References llvm::StringSwitch< T, R >::Default(), llvm::ARM::EK_INVALID, llvm::ARM::IK_AARCH64, llvm::ARM::IK_ARM, llvm::ARM::IK_THUMB, and llvm::StringSwitch< T, R >::StartsWith().
Referenced by parseARMArch().
unsigned ARMTargetParser::parseArchProfile (StringRef Arch) [static]
Definition at line 526 of file TargetParser.cpp.
References llvm::ARM::AK_ARMV6M, llvm::ARM::AK_ARMV6SM, llvm::ARM::AK_ARMV7, llvm::ARM::AK_ARMV7A, llvm::ARM::AK_ARMV7EM, llvm::ARM::AK_ARMV7M, llvm::ARM::AK_ARMV7R, llvm::ARM::AK_ARMV8_1A, llvm::ARM::AK_ARMV8A, getCanonicalArchName(), parseArch(), llvm::ARM::PK_A, llvm::ARM::PK_INVALID, llvm::ARM::PK_M, and llvm::ARM::PK_R.
Referenced by parseARMArch().
unsigned ARMTargetParser::parseArchVersion (StringRef Arch) [static]
Definition at line 546 of file TargetParser.cpp.
References llvm::ARM::AK_ARMV2, llvm::ARM::AK_ARMV2A, llvm::ARM::AK_ARMV3, llvm::ARM::AK_ARMV3M, llvm::ARM::AK_ARMV4, llvm::ARM::AK_ARMV4T, llvm::ARM::AK_ARMV5, llvm::ARM::AK_ARMV5E, llvm::ARM::AK_ARMV5T, llvm::ARM::AK_ARMV5TE, llvm::ARM::AK_ARMV5TEJ, llvm::ARM::AK_ARMV6, llvm::ARM::AK_ARMV6HL, llvm::ARM::AK_ARMV6J, llvm::ARM::AK_ARMV6K, llvm::ARM::AK_ARMV6M, llvm::ARM::AK_ARMV6SM, llvm::ARM::AK_ARMV6T2, llvm::ARM::AK_ARMV6Z, llvm::ARM::AK_ARMV6ZK, llvm::ARM::AK_ARMV7, llvm::ARM::AK_ARMV7A, llvm::ARM::AK_ARMV7EM, llvm::ARM::AK_ARMV7HL, llvm::ARM::AK_ARMV7L, llvm::ARM::AK_ARMV7M, llvm::ARM::AK_ARMV7R, llvm::ARM::AK_ARMV7S, llvm::ARM::AK_ARMV8_1A, llvm::ARM::AK_ARMV8A, llvm::ARM::AK_IWMMXT, llvm::ARM::AK_IWMMXT2, llvm::ARM::AK_XSCALE, getCanonicalArchName(), and parseArch().
Referenced by parseARMArch().
unsigned ARMTargetParser::parseCPUArch (StringRef CPU) [static]
Definition at line 487 of file TargetParser.cpp.
References llvm::ARM::AK_INVALID, and llvm::C.
unsigned ARMTargetParser::parseFPU (StringRef FPU) [static]
Definition at line 459 of file TargetParser.cpp.
References F(), and llvm::ARM::FK_INVALID.
The documentation for this class was generated from the following files:
TargetParser.h
TargetParser.cpp