LLVM: llvm::coverage::BinaryCoverageReader Class Reference
llvm::coverage::BinaryCoverageReader Class Reference
Reader for the coverage mapping data that is emitted by the frontend and stored in an object file.
#include <CoverageMappingReader.h>
Classes
struct ProfileMappingRecord
Public Member Functions
std::error_code readNextRecord (CoverageMappingRecord &Record) override
Static Public Member Functions
static ErrorOr
< std::unique_ptr
< BinaryCoverageReader > > create (std::unique_ptr< MemoryBuffer > &ObjectBuffer, StringRef Arch)
Detailed Description
Reader for the coverage mapping data that is emitted by the frontend and stored in an object file.
Definition at line 140 of file CoverageMappingReader.h.
Member Function Documentation
ErrorOr< std::unique_ptr< BinaryCoverageReader > > BinaryCoverageReader::create (std::unique_ptr< MemoryBuffer > & ObjectBuffer, StringRef Arch) [static]
Definition at line 497 of file CoverageMappingReader.cpp.
References llvm::support::big, llvm::support::little, loadBinaryFormat(), loadTestingFormat(), and llvm::malformed.
Referenced by llvm::coverage::CoverageMapping::load().
std::error_code BinaryCoverageReader::readNextRecord (CoverageMappingRecord & Record) [override, virtual]
Implements llvm::coverage::CoverageMappingReader.
Definition at line 536 of file CoverageMappingReader.cpp.
References llvm::eof, llvm::coverage::CoverageMappingRecord::Expressions, llvm::coverage::CoverageMappingRecord::Filenames, llvm::coverage::CoverageMappingRecord::FunctionHash, llvm::coverage::CoverageMappingRecord::FunctionName, llvm::makeArrayRef(), llvm::coverage::CoverageMappingRecord::MappingRegions, and llvm::coverage::RawCoverageMappingReader::read().
The documentation for this class was generated from the following files:
CoverageMappingReader.h
CoverageMappingReader.cpp