LLVM: llvm::MCUnaryExpr Class Reference
llvm::MCUnaryExpr Class Reference
Unary assembler expressions.
#include <MCExpr.h>
Public Types
enum Opcode { LNot, Minus, Not, Plus }
Public Member Functions
Opcode getOpcode () const
Get the kind of this unary expression.
const MCExpr * getSubExpr () const
Get the child of this unary expression.
Static Public Member Functions
static bool classof (const MCExpr *E)
Construction
static const MCUnaryExpr * create (Opcode Op, const MCExpr *Expr, MCContext &Ctx)
static const MCUnaryExpr * createLNot (const MCExpr *Expr, MCContext &Ctx)
static const MCUnaryExpr * createMinus (const MCExpr *Expr, MCContext &Ctx)
static const MCUnaryExpr * createNot (const MCExpr *Expr, MCContext &Ctx)
static const MCUnaryExpr * createPlus (const MCExpr *Expr, MCContext &Ctx)
Detailed Description
Unary assembler expressions.
Definition at line 352 of file MCExpr.h.
Member Enumeration Documentation
enum llvm::MCUnaryExpr::Opcode
Enumerator:
LNot
Logical negation.
Minus
Unary minus.
Not
Bitwise negation.
Plus
Unary plus.
Definition at line 354 of file MCExpr.h.
Member Function Documentation
static bool llvm::MCUnaryExpr::classof (const MCExpr * E) [inline, static]
Definition at line 397 of file MCExpr.h.
References llvm::MCExpr::getKind(), and llvm::MCExpr::Unary.
const MCUnaryExpr * MCUnaryExpr::create (Opcode Op, const MCExpr * Expr, MCContext & Ctx) [static]
Definition at line 145 of file MCExpr.cpp.
Referenced by createLNot(), createMinus(), createNot(), and createPlus().
static const MCUnaryExpr* llvm::MCUnaryExpr::createLNot (const MCExpr * Expr, MCContext & Ctx) [inline, static]
Definition at line 374 of file MCExpr.h.
References create(), and LNot.
static const MCUnaryExpr* llvm::MCUnaryExpr::createMinus (const MCExpr * Expr, MCContext & Ctx) [inline, static]
Definition at line 377 of file MCExpr.h.
References create(), and Minus.
Referenced by addNegOperand(), llvm::AArch64ExternalSymbolizer::tryAddingSymbolicOperand(), and llvm::MCExternalSymbolizer::tryAddingSymbolicOperand().
static const MCUnaryExpr* llvm::MCUnaryExpr::createNot (const MCExpr * Expr, MCContext & Ctx) [inline, static]
Definition at line 380 of file MCExpr.h.
References create(), and Not.
static const MCUnaryExpr* llvm::MCUnaryExpr::createPlus (const MCExpr * Expr, MCContext & Ctx) [inline, static]
Definition at line 383 of file MCExpr.h.
References create(), and Plus.
Opcode llvm::MCUnaryExpr::getOpcode () const [inline]
Get the kind of this unary expression.
Definition at line 390 of file MCExpr.h.
Referenced by llvm::MCExpr::evaluateAsRelocatableImpl(), and llvm::MCExpr::print().
const MCExpr* llvm::MCUnaryExpr::getSubExpr () const [inline]
Get the child of this unary expression.
Definition at line 393 of file MCExpr.h.
Referenced by llvm::MCExpr::evaluateAsRelocatableImpl(), and llvm::MCExpr::print().
The documentation for this class was generated from the following files:
MCExpr.h
MCExpr.cpp