LLVM: Bit Reader
Bit Reader
LLVM-C: C interface to LLVM
Functions
LLVMBool LLVMParseBitcode (LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutModule, char **OutMessage)
LLVMBool LLVMParseBitcodeInContext (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutModule, char **OutMessage)
LLVMBool LLVMGetBitcodeModuleInContext (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutM, char **OutMessage)
Reads a module from the specified path, returning via the OutMP parameter a module provider which performs lazy deserialization.
LLVMBool LLVMGetBitcodeModule (LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutM, char **OutMessage)
LLVMBool LLVMGetBitcodeModuleProviderInContext (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleProviderRef *OutMP, char **OutMessage)
Deprecated: Use LLVMGetBitcodeModuleInContext instead.
LLVMBool LLVMGetBitcodeModuleProvider (LLVMMemoryBufferRef MemBuf, LLVMModuleProviderRef *OutMP, char **OutMessage)
Deprecated: Use LLVMGetBitcodeModule instead.
Function Documentation
LLVMBool LLVMGetBitcodeModule (LLVMMemoryBufferRef MemBuf, LLVMModuleRef * OutM, char ** OutMessage)
Definition at line 84 of file BitReader.cpp.
References LLVMGetBitcodeModuleInContext(), and LLVMGetGlobalContext().
LLVMBool LLVMGetBitcodeModuleInContext (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef * OutM, char ** OutMessage)
Reads a module from the specified path, returning via the OutMP parameter a module provider which performs lazy deserialization.
Returns 0 on success. Optionally returns a human-readable error message via OutMessage.
Definition at line 60 of file BitReader.cpp.
References llvm::ErrorOr< T >::get(), llvm::ErrorOr< T >::getError(), llvm::getLazyBitcodeModule(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMGetBitcodeModule(), and LLVMGetBitcodeModuleProviderInContext().
LLVMBool LLVMGetBitcodeModuleProvider (LLVMMemoryBufferRef MemBuf, LLVMModuleProviderRef * OutMP, char ** OutMessage)
Deprecated: Use LLVMGetBitcodeModule instead.
Definition at line 101 of file BitReader.cpp.
References LLVMGetBitcodeModuleProviderInContext(), and LLVMGetGlobalContext().
LLVMBool LLVMGetBitcodeModuleProviderInContext (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleProviderRef * OutMP, char ** OutMessage)
Deprecated: Use LLVMGetBitcodeModuleInContext instead.
Definition at line 91 of file BitReader.cpp.
References LLVMGetBitcodeModuleInContext().
Referenced by LLVMGetBitcodeModuleProvider().
LLVMBool LLVMParseBitcode (LLVMMemoryBufferRef MemBuf, LLVMModuleRef * OutModule, char ** OutMessage)
Definition at line 25 of file BitReader.cpp.
References llvm::getGlobalContext(), LLVMParseBitcodeInContext(), and llvm::wrap().
LLVMBool LLVMParseBitcodeInContext (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef * OutModule, char ** OutMessage)
Definition at line 31 of file BitReader.cpp.
References llvm::DI, llvm::raw_ostream::flush(), llvm::ErrorOr< T >::get(), llvm::ErrorOr< T >::getError(), llvm::parseBitcodeFile(), llvm::DiagnosticInfo::print(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMParseBitcode().