LLVM: Call Sites and Invocations
Call Sites and Invocations
Instructions
Functions in this group apply to instructions that refer to call sites and invocations.
Functions
void LLVMSetInstructionCallConv (LLVMValueRef Instr, unsigned CC)
Set the calling convention for a call instruction.
unsigned LLVMGetInstructionCallConv (LLVMValueRef Instr)
Obtain the calling convention for a call instruction.
void LLVMAddInstrAttribute (LLVMValueRef Instr, unsigned index, LLVMAttribute)
void LLVMRemoveInstrAttribute (LLVMValueRef Instr, unsigned index, LLVMAttribute)
void LLVMSetInstrParamAlignment (LLVMValueRef Instr, unsigned index, unsigned align)
LLVMBool LLVMIsTailCall (LLVMValueRef CallInst)
Obtain whether a call instruction is a tail call.
void LLVMSetTailCall (LLVMValueRef CallInst, LLVMBool IsTailCall)
Set whether a call instruction is a tail call.
Detailed Description
Functions in this group apply to instructions that refer to call sites and invocations.
These correspond to C++ types in the llvm::CallInst class tree.
Function Documentation
void LLVMAddInstrAttribute (LLVMValueRef Instr, unsigned index, LLVMAttribute)
Definition at line 2044 of file Core.cpp.
References llvm::AttributeSet::addAttributes(), llvm::Call, llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getAttributes(), and llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setAttributes().
unsigned LLVMGetInstructionCallConv (LLVMValueRef Instr)
Obtain the calling convention for a call instruction.
This is the opposite of LLVMSetInstructionCallConv(). Reads its usage.
See also:
LLVMSetInstructionCallConv()
Definition at line 2026 of file Core.cpp.
References llvm_unreachable, and llvm::unwrap().
LLVMBool LLVMIsTailCall (LLVMValueRef CallInst)
Obtain whether a call instruction is a tail call.
This only works on llvm::CallInst instructions.
See also:
llvm::CallInst::isTailCall()
Definition at line 2077 of file Core.cpp.
References llvm::Call.
void LLVMRemoveInstrAttribute (LLVMValueRef Instr, unsigned index, LLVMAttribute)
Definition at line 2054 of file Core.cpp.
References llvm::Call, llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getAttributes(), llvm::AttributeSet::removeAttributes(), and llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setAttributes().
void LLVMSetInstrParamAlignment (LLVMValueRef Instr, unsigned index, unsigned align)
Definition at line 2064 of file Core.cpp.
References llvm::AttrBuilder::addAlignmentAttr(), llvm::AttributeSet::addAttributes(), llvm::Call, llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getAttributes(), and llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setAttributes().
void LLVMSetInstructionCallConv (LLVMValueRef Instr, unsigned CC)
Set the calling convention for a call instruction.
This expects an LLVMValueRef that corresponds to a llvm::CallInst or llvm::InvokeInst.
See also:
llvm::CallInst::setCallingConv()
llvm::InvokeInst::setCallingConv()
Definition at line 2035 of file Core.cpp.
References llvm_unreachable, and llvm::unwrap().
void LLVMSetTailCall (LLVMValueRef CallInst, LLVMBool IsTailCall)
Set whether a call instruction is a tail call.
This only works on llvm::CallInst instructions.
See also:
llvm::CallInst::setTailCall()
Definition at line 2081 of file Core.cpp.
References llvm::Call.