LLVM: Metadata
Metadata
Core
Functions
LLVMValueRef LLVMMDStringInContext (LLVMContextRef C, const char *Str, unsigned SLen)
Obtain a MDString value from a context.
LLVMValueRef LLVMMDString (const char *Str, unsigned SLen)
Obtain a MDString value from the global context.
LLVMValueRef LLVMMDNodeInContext (LLVMContextRef C, LLVMValueRef *Vals, unsigned Count)
Obtain a MDNode value from a context.
LLVMValueRef LLVMMDNode (LLVMValueRef *Vals, unsigned Count)
Obtain a MDNode value from the global context.
const char * LLVMGetMDString (LLVMValueRef V, unsigned *Len)
Obtain the underlying string from a MDString value.
unsigned LLVMGetMDNodeNumOperands (LLVMValueRef V)
Obtain the number of operands from an MDNode value.
void LLVMGetMDNodeOperands (LLVMValueRef V, LLVMValueRef *Dest)
Obtain the given MDNode's operands.
Function Documentation
unsigned LLVMGetMDNodeNumOperands (LLVMValueRef V)
Obtain the number of operands from an MDNode value.
Parameters:
V MDNode to get number of operands from.
Returns:
Number of operands of the MDNode.
Definition at line 775 of file Core.cpp.
References llvm::unwrap().
Referenced by LLVMGetNumOperands().
void LLVMGetMDNodeOperands (LLVMValueRef V, LLVMValueRef * Dest)
Obtain the given MDNode's operands.
The passed LLVMValueRef pointer should point to enough memory to hold all of the operands of the given MDNode (see LLVMGetMDNodeNumOperands) as LLVMValueRefs. This memory will be populated with the LLVMValueRefs of the MDNode's operands.
Parameters:
V MDNode to get the operands from.
Dest Destination array for operands.
Definition at line 783 of file Core.cpp.
References getMDNodeOperandImpl(), N, llvm::unwrap(), and llvm::wrap().
const char* LLVMGetMDString (LLVMValueRef V, unsigned * Len)
Obtain the underlying string from a MDString value.
Parameters:
V Instance to obtain string from.
Len Memory address which will hold length of returned string.
Returns:
String data in MDString.
Definition at line 765 of file Core.cpp.
References llvm::unwrap().
LLVMValueRef LLVMMDNode (LLVMValueRef * Vals, unsigned Count)
Obtain a MDNode value from the global context.
Definition at line 761 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMMDNodeInContext().
LLVMValueRef LLVMMDNodeInContext (LLVMContextRef C, LLVMValueRef * Vals, unsigned Count)
Obtain a MDNode value from a context.
The returned value corresponds to the llvm::MDNode class.
Definition at line 734 of file Core.cpp.
References llvm::MetadataAsValue::get(), llvm::ConstantAsMetadata::get(), llvm::LocalAsMetadata::get(), llvm::MDNode::get(), llvm::makeArrayRef(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMMDNode().
LLVMValueRef LLVMMDString (const char * Str, unsigned SLen)
Obtain a MDString value from the global context.
Definition at line 730 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMMDStringInContext().
LLVMValueRef LLVMMDStringInContext (LLVMContextRef C, const char * Str, unsigned SLen)
Obtain a MDString value from a context.
The returned instance corresponds to the llvm::MDString class.
The instance is specified by string data of a specified length. The string content is copied, so the backing memory can be freed after this function returns.
Definition at line 723 of file Core.cpp.
References llvm::MetadataAsValue::get(), llvm::MDString::get(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMMDString().