LLVM: llvm::HexagonMCInstrInfo Namespace Reference
llvm::HexagonMCInstrInfo Namespace Reference
Functions
iterator_range
< MCInst::const_iterator > bundleInstructions (MCInst const &MCI)
size_t bundleSize (MCInst const &MCI)
void clampExtended (MCInstrInfo const &MCII, MCInst &MCI)
MCInst * deriveDuplex (MCContext &Context, unsigned iClass, MCInst const &inst0, MCInst const &inst1)
MCInst deriveSubInst (MCInst const &Inst)
MCInst const * extenderForIndex (MCInst const &MCB, size_t Index)
HexagonII::MemAccessSize getAccessSize (MCInstrInfo const &MCII, MCInst const &MCI)
unsigned getBitCount (MCInstrInfo const &MCII, MCInst const &MCI)
unsigned short getCExtOpNum (MCInstrInfo const &MCII, MCInst const &MCI)
MCInstrDesc const & getDesc (MCInstrInfo const &MCII, MCInst const &MCI)
unsigned getDuplexCandidateGroup (MCInst const &MI)
SmallVector< DuplexCandidate, 8 > getDuplexPossibilties (MCInstrInfo const &MCII, MCInst const &MCB)
unsigned short getExtendableOp (MCInstrInfo const &MCII, MCInst const &MCI)
MCOperand const & getExtendableOperand (MCInstrInfo const &MCII, MCInst const &MCI)
unsigned getExtentAlignment (MCInstrInfo const &MCII, MCInst const &MCI)
unsigned getExtentBits (MCInstrInfo const &MCII, MCInst const &MCI)
int getMaxValue (MCInstrInfo const &MCII, MCInst const &MCI)
int getMinValue (MCInstrInfo const &MCII, MCInst const &MCI)
char const * getName (MCInstrInfo const &MCII, MCInst const &MCI)
unsigned short getNewValueOp (MCInstrInfo const &MCII, MCInst const &MCI)
MCOperand const & getNewValueOperand (MCInstrInfo const &MCII, MCInst const &MCI)
int getSubTarget (MCInstrInfo const &MCII, MCInst const &MCI)
unsigned getType (MCInstrInfo const &MCII, MCInst const &MCI)
unsigned getUnits (MCInstrInfo const &MCII, MCSubtargetInfo const &STI, MCInst const &MCI)
Return the slots used by the insn.
bool hasExtenderForIndex (MCInst const &MCB, size_t Index)
bool hasImmExt (MCInst const &MCI)
bool hasNewValue (MCInstrInfo const &MCII, MCInst const &MCI)
MCInst const & instruction (MCInst const &MCB, size_t Index)
bool isBundle (MCInst const &MCI)
bool isCanon (MCInstrInfo const &MCII, MCInst const &MCI)
unsigned iClassOfDuplexPair (unsigned Ga, unsigned Gb)
bool isConstExtended (MCInstrInfo const &MCII, MCInst const &MCI)
bool isDblRegForSubInst (unsigned Reg)
bool isDuplex (MCInstrInfo const &MCII, MCInst const &MCI)
bool isDuplexPair (MCInst const &MIa, MCInst const &MIb)
Symmetrical. See if these two instructions are fit for duplex pair.
bool isDuplexPairMatch (unsigned Ga, unsigned Gb)
bool isExtendable (MCInstrInfo const &MCII, MCInst const &MCI)
bool isExtended (MCInstrInfo const &MCII, MCInst const &MCI)
bool isFloat (MCInstrInfo const &MCII, MCInst const &MCI)
Return whether it is a floating-point insn.
bool isImmext (MCInst const &MCI)
bool isInnerLoop (MCInst const &MCI)
bool isIntReg (unsigned Reg)
bool isIntRegForSubInst (unsigned Reg)
bool isNewValue (MCInstrInfo const &MCII, MCInst const &MCI)
bool isOperandExtended (MCInstrInfo const &MCII, MCInst const &MCI, unsigned short OperandNum)
bool isOrderedDuplexPair (MCInstrInfo const &MCII, MCInst const &MIa, bool ExtendedA, MCInst const &MIb, bool ExtendedB, bool bisReversable)
non-Symmetrical. See if these two instructions are fit for duplex pair.
bool isOuterLoop (MCInst const &MCI)
bool isPredicated (MCInstrInfo const &MCII, MCInst const &MCI)
bool isPredicatedTrue (MCInstrInfo const &MCII, MCInst const &MCI)
bool isPredReg (unsigned Reg)
bool isPrefix (MCInstrInfo const &MCII, MCInst const &MCI)
bool isSolo (MCInstrInfo const &MCII, MCInst const &MCI)
bool isSoloAX (MCInstrInfo const &MCII, MCInst const &MCI)
Return whether the insn can be packaged only with A and X-type insns.
bool isSoloAin1 (MCInstrInfo const &MCII, MCInst const &MCI)
Return whether the insn can be packaged only with an A-type insn in slot #1.
void padEndloop (MCInst &MCI)
bool prefersSlot3 (MCInstrInfo const &MCII, MCInst const &MCI)
void replaceDuplex (MCContext &Context, MCInst &MCB, DuplexCandidate Candidate)
void setInnerLoop (MCInst &MCI)
void setOuterLoop (MCInst &MCI)
bool subInstWouldBeExtended (MCInst const &potentialDuplex)
void tryCompound (MCInstrInfo const &MCII, MCContext &Context, MCInst &MCI)
tryCompound - Given a bundle check for compound insns when one is found update the contents fo the bundle with the compound insn.
Variables
size_t const innerLoopOffset = 0
int64_t const innerLoopMask = 1 << innerLoopOffset
size_t const outerLoopOffset = 1
int64_t const outerLoopMask = 1 << outerLoopOffset
size_t const bundleInstructionsOffset = 1
Function Documentation
iterator_range< MCInst::const_iterator > llvm::HexagonMCInstrInfo::bundleInstructions (MCInst const & MCI)
Definition at line 25 of file HexagonMCInstrInfo.cpp.
References llvm::MCInst::begin(), bundleInstructionsOffset, llvm::MCInst::end(), and isBundle().
Referenced by llvm::HexagonMCELFStreamer::EmitInstruction(), llvm::HexagonMCCodeEmitter::encodeInstruction(), llvm::HexagonMCCodeEmitter::EncodeSingleInstruction(), hasImmExt(), and llvm::HexagonInstPrinter::printInst().
size_t llvm::HexagonMCInstrInfo::bundleSize (MCInst const & MCI)
Definition at line 31 of file HexagonMCInstrInfo.cpp.
References bundleInstructionsOffset, isBundle(), and llvm::MCInst::size().
Referenced by llvm::HexagonMCELFStreamer::EmitInstruction(), llvm::HexagonMCCodeEmitter::encodeInstruction(), extenderForIndex(), llvm::HexagonMCShuffle(), padEndloop(), llvm::HexagonAsmInstPrinter::printInst(), and llvm::HexagonInstPrinter::printInst().
void llvm::HexagonMCInstrInfo::clampExtended (MCInstrInfo const & MCII, MCInst & MCI)
Definition at line 38 of file HexagonMCInstrInfo.cpp.
References llvm::tgtok::Bits, getExtendableOp(), getExtentAlignment(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), isExtendable(), isExtended(), llvm::MCOperand::isImm(), and llvm::MCOperand::setImm().
Referenced by llvm::HexagonMCELFStreamer::EmitInstruction().
MCInst * llvm::HexagonMCInstrInfo::deriveDuplex (MCContext & Context, unsigned iClass, MCInst const & inst0, MCInst const & inst1)
Definition at line 53 of file HexagonMCInstrInfo.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createInst(), deriveSubInst(), and llvm::MCInst::setOpcode().
Referenced by replaceDuplex().
MCInst llvm::HexagonMCInstrInfo::deriveSubInst (MCInst const & Inst)
Definition at line 713 of file HexagonMCDuplexInfo.cpp.
References addOps(), llvm::MCOperand::getImm(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isImm(), llvm_unreachable, and llvm::MCInst::setOpcode().
Referenced by deriveDuplex(), and isOrderedDuplexPair().
MCInst const * llvm::HexagonMCInstrInfo::extenderForIndex (MCInst const & MCB, size_t Index)
Definition at line 67 of file HexagonMCInstrInfo.cpp.
References bundleInstructionsOffset, bundleSize(), llvm::MCOperand::getInst(), llvm::MCInst::getOperand(), and isImmext().
Referenced by hasExtenderForIndex().
HexagonII::MemAccessSize llvm::HexagonMCInstrInfo::getAccessSize (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 80 of file HexagonMCInstrInfo.cpp.
References F(), getDesc(), llvm::HexagonII::MemAccesSizeMask, llvm::HexagonII::MemAccessSizePos, and llvm::MCInstrDesc::TSFlags.
Referenced by llvm::SystemZInstrInfo::foldMemoryOperandImpl(), and getFixupNoBits().
unsigned llvm::HexagonMCInstrInfo::getBitCount (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 87 of file HexagonMCInstrInfo.cpp.
References llvm::HexagonII::ExtentBitsMask, llvm::HexagonII::ExtentBitsPos, F(), getDesc(), and llvm::MCInstrDesc::TSFlags.
unsigned short llvm::HexagonMCInstrInfo::getCExtOpNum (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 94 of file HexagonMCInstrInfo.cpp.
References llvm::HexagonII::ExtendableOpMask, llvm::HexagonII::ExtendableOpPos, F(), getDesc(), and llvm::MCInstrDesc::TSFlags.
Referenced by isConstExtended().
MCInstrDesc const & llvm::HexagonMCInstrInfo::getDesc (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 100 of file HexagonMCInstrInfo.cpp.
References llvm::MCInstrInfo::get(), and llvm::MCInst::getOpcode().
Referenced by llvm::ARMBaseInstrInfo::breakPartialRegDependency(), llvm::HexagonShuffler::check(), llvm::HexagonMCCodeEmitter::EncodeSingleInstruction(), llvm::MachineInstr::findFirstPredOperandIdx(), getAccessSize(), getBitCount(), getCExtOpNum(), getExtendableOp(), getExtentAlignment(), getExtentBits(), getFixupNoBits(), getMaxValue(), getMinValue(), getNewValueOp(), getNewValueOperand(), llvm::MachineInstr::getRegClassConstraint(), getSubTarget(), getType(), getUnits(), hasNewValue(), isCanon(), isExtendable(), isExtended(), isFloat(), isNewValue(), isOperandExtended(), isPredicated(), isPredicatedTrue(), isSolo(), isSoloAin1(), isSoloAX(), prefersSlot3(), llvm::MachineInstr::print(), and llvm::HexagonShuffler::shuffle().
unsigned llvm::HexagonMCInstrInfo::getDuplexCandidateGroup (MCInst const & MI)
Definition at line 181 of file HexagonMCDuplexInfo.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::HexagonII::HSIG_A, llvm::HexagonII::HSIG_L1, llvm::HexagonII::HSIG_L2, llvm::HexagonII::HSIG_None, llvm::HexagonII::HSIG_S1, llvm::HexagonII::HSIG_S2, isDblRegForSubInst(), llvm::MCOperand::isImm(), isIntReg(), isIntRegForSubInst(), and isPredReg().
Referenced by getDuplexPossibilties(), isDuplexPair(), and isOrderedDuplexPair().
SmallVector< DuplexCandidate, 8 > llvm::HexagonMCInstrInfo::getDuplexPossibilties (MCInstrInfo const & MCII, MCInst const & MCB)
Definition at line 1027 of file HexagonMCDuplexInfo.cpp.
References bundleInstructionsOffset, llvm::dbgs(), DEBUG, getDuplexCandidateGroup(), llvm::MCOperand::getInst(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), hasExtenderForIndex(), iClassOfDuplexPair(), isBundle(), isOrderedDuplexPair(), isStoreInst(), and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Referenced by llvm::HexagonAsmPrinter::EmitInstruction().
unsigned short llvm::HexagonMCInstrInfo::getExtendableOp (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 105 of file HexagonMCInstrInfo.cpp.
References llvm::HexagonII::ExtendableOpMask, llvm::HexagonII::ExtendableOpPos, F(), getDesc(), and llvm::MCInstrDesc::TSFlags.
Referenced by clampExtended(), and getExtendableOperand().
MCOperand const & llvm::HexagonMCInstrInfo::getExtendableOperand (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 112 of file HexagonMCInstrInfo.cpp.
References getExtendableOp(), llvm::MCInst::getOperand(), llvm::MCOperand::isExpr(), isExtendable(), isExtended(), and llvm::MCOperand::isImm().
unsigned llvm::HexagonMCInstrInfo::getExtentAlignment (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 123 of file HexagonMCInstrInfo.cpp.
References llvm::HexagonII::ExtentAlignMask, llvm::HexagonII::ExtentAlignPos, F(), getDesc(), and llvm::MCInstrDesc::TSFlags.
Referenced by clampExtended().
unsigned llvm::HexagonMCInstrInfo::getExtentBits (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 129 of file HexagonMCInstrInfo.cpp.
References llvm::HexagonII::ExtentBitsMask, llvm::HexagonII::ExtentBitsPos, F(), getDesc(), and llvm::MCInstrDesc::TSFlags.
int llvm::HexagonMCInstrInfo::getMaxValue (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 137 of file HexagonMCInstrInfo.cpp.
References llvm::HexagonII::ExtentBitsMask, llvm::HexagonII::ExtentBitsPos, llvm::HexagonII::ExtentSignedMask, llvm::HexagonII::ExtentSignedPos, F(), getDesc(), and llvm::MCInstrDesc::TSFlags.
Referenced by isConstExtended().
int llvm::HexagonMCInstrInfo::getMinValue (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 152 of file HexagonMCInstrInfo.cpp.
References llvm::HexagonII::ExtentBitsMask, llvm::HexagonII::ExtentBitsPos, llvm::HexagonII::ExtentSignedMask, llvm::HexagonII::ExtentSignedPos, F(), getDesc(), and llvm::MCInstrDesc::TSFlags.
Referenced by isConstExtended().
char const * llvm::HexagonMCInstrInfo::getName (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 165 of file HexagonMCInstrInfo.cpp.
References llvm::MCInstrInfo::getName(), and llvm::MCInst::getOpcode().
Referenced by llvm::HexagonMCCodeEmitter::EncodeSingleInstruction().
unsigned short llvm::HexagonMCInstrInfo::getNewValueOp (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 170 of file HexagonMCInstrInfo.cpp.
References F(), getDesc(), llvm::HexagonII::NewValueOpMask, llvm::HexagonII::NewValueOpPos, and llvm::MCInstrDesc::TSFlags.
Referenced by llvm::HexagonMCCodeEmitter::EncodeSingleInstruction().
MCOperand const & llvm::HexagonMCInstrInfo::getNewValueOperand (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 176 of file HexagonMCInstrInfo.cpp.
References F(), getDesc(), llvm::MCInst::getOperand(), hasNewValue(), isNewValue(), llvm::MCOperand::isReg(), llvm::HexagonII::NewValueOpMask, llvm::HexagonII::NewValueOpPos, and llvm::MCInstrDesc::TSFlags.
Referenced by llvm::HexagonMCCodeEmitter::EncodeSingleInstruction().
int llvm::HexagonMCInstrInfo::getSubTarget (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 189 of file HexagonMCInstrInfo.cpp.
References F(), getDesc(), llvm::HexagonII::HasV5SubT, llvm::MCInstrDesc::TSFlags, llvm::HexagonII::validSubTargetMask, and llvm::HexagonII::validSubTargetPos.
unsigned llvm::HexagonMCInstrInfo::getType (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 205 of file HexagonMCInstrInfo.cpp.
References F(), getDesc(), llvm::MCInstrDesc::TSFlags, llvm::HexagonII::TypeMask, and llvm::HexagonII::TypePos.
Referenced by llvm::HexagonShuffler::check(), isCanon(), isDuplex(), isPrefix(), and prefersSlot3().
unsigned llvm::HexagonMCInstrInfo::getUnits (MCInstrInfo const & MCII, MCSubtargetInfo const & STI, MCInst const & MCI)
Return the slots used by the insn.
Definition at line 212 of file HexagonMCInstrInfo.cpp.
References getDesc(), llvm::MCInstrDesc::getSchedClass(), llvm::MCSubtargetInfo::getSchedModel(), llvm::HexagonStages, and llvm::MCSchedModel::InstrItineraries.
bool llvm::HexagonMCInstrInfo::hasExtenderForIndex (MCInst const & MCB, size_t Index)
Definition at line 234 of file HexagonMCInstrInfo.cpp.
References extenderForIndex().
Referenced by getDuplexPossibilties().
bool llvm::HexagonMCInstrInfo::hasImmExt (MCInst const & MCI)
Definition at line 221 of file HexagonMCInstrInfo.cpp.
References bundleInstructions(), I, isBundle(), isImmext(), and llvm::AArch64CC::MI.
bool llvm::HexagonMCInstrInfo::hasNewValue (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 239 of file HexagonMCInstrInfo.cpp.
References F(), getDesc(), llvm::HexagonII::hasNewValueMask, llvm::HexagonII::hasNewValuePos, and llvm::MCInstrDesc::TSFlags.
Referenced by llvm::HexagonMCCodeEmitter::EncodeSingleInstruction(), and getNewValueOperand().
unsigned llvm::HexagonMCInstrInfo::iClassOfDuplexPair (unsigned Ga, unsigned Gb)
Definition at line 112 of file HexagonMCDuplexInfo.cpp.
References llvm::HexagonII::HSIG_A, llvm::HexagonII::HSIG_Compound, llvm::HexagonII::HSIG_L1, llvm::HexagonII::HSIG_L2, llvm::HexagonII::HSIG_None, llvm::HexagonII::HSIG_S1, and llvm::HexagonII::HSIG_S2.
Referenced by getDuplexPossibilties().
MCInst const & llvm::HexagonMCInstrInfo::instruction (MCInst const & MCB, size_t Index)
Definition at line 245 of file HexagonMCInstrInfo.cpp.
References bundleInstructionsOffset, llvm::MCOperand::getInst(), llvm::MCInst::getOperand(), HEXAGON_PACKET_SIZE, and isBundle().
bool llvm::HexagonMCInstrInfo::isBundle (MCInst const & MCI)
Definition at line 251 of file HexagonMCInstrInfo.cpp.
References llvm::TargetOpcode::BUNDLE, llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::isImm(), and llvm::MCInst::size().
Referenced by bundleInstructions(), bundleSize(), llvm::HexagonMCCodeEmitter::encodeInstruction(), llvm::HexagonMCCodeEmitter::EncodeSingleInstruction(), getDuplexPossibilties(), hasImmExt(), llvm::HexagonMCShuffle(), instruction(), llvm::MachineInstr::isIdenticalTo(), isInnerLoop(), isOuterLoop(), padEndloop(), llvm::HexagonAsmInstPrinter::printInst(), llvm::HexagonInstPrinter::printInst(), replaceDuplex(), setInnerLoop(), and setOuterLoop().
bool llvm::HexagonMCInstrInfo::isCanon (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 258 of file HexagonMCInstrInfo.cpp.
References getDesc(), getType(), isPrefix(), and llvm::HexagonII::TypeENDLOOP.
bool llvm::HexagonMCInstrInfo::isConstExtended (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 281 of file HexagonMCInstrInfo.cpp.
References getCExtOpNum(), llvm::MCOperand::getImm(), getMaxValue(), getMinValue(), llvm::MCInst::getOperand(), llvm::MCOperand::isExpr(), isExtendable(), isExtended(), and llvm::MCOperand::isImm().
bool llvm::HexagonMCInstrInfo::isDblRegForSubInst (unsigned Reg)
Definition at line 264 of file HexagonMCInstrInfo.cpp.
Referenced by getDuplexCandidateGroup().
bool llvm::HexagonMCInstrInfo::isDuplex (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 269 of file HexagonMCInstrInfo.cpp.
References getType(), and llvm::HexagonII::TypeDUPLEX.
Referenced by llvm::HexagonMCELFStreamer::EmitInstruction(), llvm::HexagonMCCodeEmitter::parseBits(), and llvm::HexagonInstPrinter::printInst().
bool llvm::HexagonMCInstrInfo::isDuplexPair (MCInst const & MIa, MCInst const & MIb)
Symmetrical. See if these two instructions are fit for duplex pair.
Definition at line 669 of file HexagonMCDuplexInfo.cpp.
References getDuplexCandidateGroup(), and isDuplexPairMatch().
bool llvm::HexagonMCInstrInfo::isDuplexPairMatch (unsigned Ga, unsigned Gb)
Definition at line 87 of file HexagonMCDuplexInfo.cpp.
References llvm::HexagonII::HSIG_A, llvm::HexagonII::HSIG_Compound, llvm::HexagonII::HSIG_L1, llvm::HexagonII::HSIG_L2, llvm::HexagonII::HSIG_None, llvm::HexagonII::HSIG_S1, and llvm::HexagonII::HSIG_S2.
Referenced by isDuplexPair(), and isOrderedDuplexPair().
bool llvm::HexagonMCInstrInfo::isExtendable (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 311 of file HexagonMCInstrInfo.cpp.
References llvm::HexagonII::ExtendableMask, llvm::HexagonII::ExtendablePos, F(), getDesc(), and llvm::MCInstrDesc::TSFlags.
Referenced by clampExtended(), getExtendableOperand(), and isConstExtended().
bool llvm::HexagonMCInstrInfo::isExtended (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 317 of file HexagonMCInstrInfo.cpp.
References llvm::HexagonII::ExtendedMask, llvm::HexagonII::ExtendedPos, F(), getDesc(), and llvm::MCInstrDesc::TSFlags.
Referenced by clampExtended(), getExtendableOperand(), and isConstExtended().
bool llvm::HexagonMCInstrInfo::isFloat (MCInstrInfo const & MCII, MCInst const & MCI)
Return whether it is a floating-point insn.
Definition at line 323 of file HexagonMCInstrInfo.cpp.
References F(), llvm::HexagonII::FPMask, llvm::HexagonII::FPPos, getDesc(), and llvm::MCInstrDesc::TSFlags.
Referenced by llvm::HexagonShuffler::check().
bool llvm::HexagonMCInstrInfo::isImmext (MCInst const & MCI)
Definition at line 328 of file HexagonMCInstrInfo.cpp.
References llvm::MCInst::getOpcode().
Referenced by llvm::HexagonMCELFStreamer::EmitInstruction(), llvm::HexagonMCCodeEmitter::encodeInstruction(), llvm::HexagonMCCodeEmitter::EncodeSingleInstruction(), extenderForIndex(), and hasImmExt().
bool llvm::HexagonMCInstrInfo::isInnerLoop (MCInst const & MCI)
Definition at line 334 of file HexagonMCInstrInfo.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), innerLoopMask, and isBundle().
Referenced by padEndloop(), llvm::HexagonMCCodeEmitter::parseBits(), and llvm::HexagonInstPrinter::printInst().
bool llvm::HexagonMCInstrInfo::isIntReg (unsigned Reg)
Definition at line 340 of file HexagonMCInstrInfo.cpp.
Referenced by getDuplexCandidateGroup().
bool llvm::HexagonMCInstrInfo::isIntRegForSubInst (unsigned Reg)
Definition at line 344 of file HexagonMCInstrInfo.cpp.
Referenced by getDuplexCandidateGroup(), and subInstWouldBeExtended().
bool llvm::HexagonMCInstrInfo::isNewValue (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 350 of file HexagonMCInstrInfo.cpp.
References F(), getDesc(), llvm::HexagonII::NewValueMask, llvm::HexagonII::NewValuePos, and llvm::MCInstrDesc::TSFlags.
Referenced by llvm::HexagonMCCodeEmitter::EncodeSingleInstruction(), and getNewValueOperand().
bool llvm::HexagonMCInstrInfo::isOperandExtended (MCInstrInfo const & MCII, MCInst const & MCI, unsigned short OperandNum)
Definition at line 357 of file HexagonMCInstrInfo.cpp.
References llvm::HexagonII::ExtendableOpMask, llvm::HexagonII::ExtendableOpPos, F(), getDesc(), and llvm::MCInstrDesc::TSFlags.
bool llvm::HexagonMCInstrInfo::isOrderedDuplexPair (MCInstrInfo const & MCII, MCInst const & MIa, bool ExtendedA, MCInst const & MIb, bool ExtendedB, bool bisReversable)
non-Symmetrical. See if these two instructions are fit for duplex pair.
Definition at line 598 of file HexagonMCDuplexInfo.cpp.
References deriveSubInst(), getDuplexCandidateGroup(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::HexagonII::HSIG_L2, llvm::HexagonII::HSIG_None, llvm::HexagonII::HSIG_S1, llvm::HexagonII::HSIG_S2, isDuplexPairMatch(), llvm::MCOperand::isReg(), subinstOpcodeMap(), and subInstWouldBeExtended().
Referenced by getDuplexPossibilties().
bool llvm::HexagonMCInstrInfo::isOuterLoop (MCInst const & MCI)
Definition at line 365 of file HexagonMCInstrInfo.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), isBundle(), and outerLoopMask.
Referenced by padEndloop(), llvm::HexagonMCCodeEmitter::parseBits(), and llvm::HexagonInstPrinter::printInst().
bool llvm::HexagonMCInstrInfo::isPredicated (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 371 of file HexagonMCInstrInfo.cpp.
References F(), getDesc(), llvm::HexagonII::PredicatedMask, llvm::HexagonII::PredicatedPos, and llvm::MCInstrDesc::TSFlags.
Referenced by llvm::HexagonMCCodeEmitter::EncodeSingleInstruction(), and llvm::MSP430InstrInfo::isUnpredicatedTerminator().
bool llvm::HexagonMCInstrInfo::isPredicatedTrue (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 377 of file HexagonMCInstrInfo.cpp.
References F(), getDesc(), llvm::HexagonII::PredicatedFalseMask, llvm::HexagonII::PredicatedFalsePos, and llvm::MCInstrDesc::TSFlags.
Referenced by llvm::HexagonMCCodeEmitter::EncodeSingleInstruction().
bool llvm::HexagonMCInstrInfo::isPredReg (unsigned Reg)
Definition at line 384 of file HexagonMCInstrInfo.cpp.
Referenced by getDuplexCandidateGroup().
bool llvm::HexagonMCInstrInfo::isPrefix (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 388 of file HexagonMCInstrInfo.cpp.
References getType(), and llvm::HexagonII::TypePREFIX.
Referenced by isCanon(), and readPrefixes().
bool llvm::HexagonMCInstrInfo::isSolo (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 392 of file HexagonMCInstrInfo.cpp.
References F(), getDesc(), llvm::HexagonII::SoloMask, llvm::HexagonII::SoloPos, and llvm::MCInstrDesc::TSFlags.
Referenced by llvm::HexagonShuffler::check().
bool llvm::HexagonMCInstrInfo::isSoloAin1 (MCInstrInfo const & MCII, MCInst const & MCI)
Return whether the insn can be packaged only with an A-type insn in slot #1.
Definition at line 402 of file HexagonMCInstrInfo.cpp.
References F(), getDesc(), llvm::HexagonII::SoloAin1Mask, llvm::HexagonII::SoloAin1Pos, and llvm::MCInstrDesc::TSFlags.
Referenced by llvm::HexagonShuffler::check().
bool llvm::HexagonMCInstrInfo::isSoloAX (MCInstrInfo const & MCII, MCInst const & MCI)
Return whether the insn can be packaged only with A and X-type insns.
Definition at line 397 of file HexagonMCInstrInfo.cpp.
References F(), getDesc(), llvm::HexagonII::SoloAXMask, llvm::HexagonII::SoloAXPos, and llvm::MCInstrDesc::TSFlags.
Referenced by llvm::HexagonShuffler::check().
void llvm::HexagonMCInstrInfo::padEndloop (MCInst & MCI)
Definition at line 408 of file HexagonMCInstrInfo.cpp.
References llvm::MCInst::addOperand(), bundleSize(), llvm::MCOperand::createInst(), HEXAGON_PACKET_INNER_SIZE, HEXAGON_PACKET_OUTER_SIZE, isBundle(), isInnerLoop(), isOuterLoop(), and llvm::MCInst::setOpcode().
Referenced by llvm::HexagonMCELFStreamer::EmitInstruction(), and llvm::HexagonAsmPrinter::EmitInstruction().
bool llvm::HexagonMCInstrInfo::prefersSlot3 (MCInstrInfo const & MCII, MCInst const & MCI)
Definition at line 419 of file HexagonMCInstrInfo.cpp.
References getDesc(), llvm::MCInstrDesc::getSchedClass(), getType(), and llvm::HexagonII::TypeCR.
Referenced by llvm::HexagonShuffler::check().
void llvm::HexagonMCInstrInfo::replaceDuplex (MCContext & Context, MCInst & MCB, DuplexCandidate Candidate)
Definition at line 439 of file HexagonMCInstrInfo.cpp.
References llvm::MCInst::begin(), deriveDuplex(), llvm::MCInst::erase(), llvm::MCOperand::getInst(), llvm::MCInst::getOperand(), llvm::DuplexCandidate::iClass, isBundle(), llvm::DuplexCandidate::packetIndexI, llvm::DuplexCandidate::packetIndexJ, llvm::MCOperand::setInst(), and llvm::MCInst::size().
Referenced by llvm::HexagonMCShuffle().
void llvm::HexagonMCInstrInfo::setInnerLoop (MCInst & MCI)
Definition at line 453 of file HexagonMCInstrInfo.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), innerLoopMask, isBundle(), and llvm::MCOperand::setImm().
Referenced by llvm::HexagonLowerToMC().
void llvm::HexagonMCInstrInfo::setOuterLoop (MCInst & MCI)
Definition at line 459 of file HexagonMCInstrInfo.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), isBundle(), outerLoopMask, and llvm::MCOperand::setImm().
Referenced by llvm::HexagonLowerToMC().
bool llvm::HexagonMCInstrInfo::subInstWouldBeExtended (MCInst const & potentialDuplex)
Definition at line 558 of file HexagonMCDuplexInfo.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), and isIntRegForSubInst().
Referenced by isOrderedDuplexPair().
void llvm::HexagonMCInstrInfo::tryCompound (MCInstrInfo const & MCII, MCContext & Context, MCInst & MCI)
tryCompound - Given a bundle check for compound insns when one is found update the contents fo the bundle with the compound insn.
If a compound instruction is found then the bundle will have one additional slot.
Definition at line 405 of file HexagonMCCompound.cpp.
References llvm::TargetOpcode::BUNDLE, llvm::MCInst::getOpcode(), and llvm::MCInst::size().
Referenced by llvm::HexagonAsmPrinter::EmitInstruction().
Variable Documentation
size_t const llvm::HexagonMCInstrInfo::bundleInstructionsOffset = 1
Definition at line 42 of file HexagonMCInstrInfo.h.
Referenced by bundleInstructions(), bundleSize(), extenderForIndex(), getDuplexPossibilties(), and instruction().
int64_t const llvm::HexagonMCInstrInfo::innerLoopMask = 1 << innerLoopOffset
Definition at line 37 of file HexagonMCInstrInfo.h.
Referenced by isInnerLoop(), and setInnerLoop().
size_t const llvm::HexagonMCInstrInfo::innerLoopOffset = 0
Definition at line 36 of file HexagonMCInstrInfo.h.
int64_t const llvm::HexagonMCInstrInfo::outerLoopMask = 1 << outerLoopOffset
Definition at line 40 of file HexagonMCInstrInfo.h.
Referenced by isOuterLoop(), and setOuterLoop().
size_t const llvm::HexagonMCInstrInfo::outerLoopOffset = 1
Definition at line 39 of file HexagonMCInstrInfo.h.