LLVM: llvm::dwarf Namespace Reference
llvm::dwarf Namespace Reference
Namespaces
namespace syntax
Classes
struct PubIndexEntryDescriptor
Decsribes an entry of the various gnu_pub* debug sections.
Enumerations
enum LLVMConstants {
DW_TAG_invalid = ~0U, DW_VIRTUALITY_invalid = ~0U, DWARF_VERSION = 4, DW_PUBTYPES_VERSION = 2,
DW_PUBNAMES_VERSION = 2, DW_ARANGES_VERSION = 2
}
enum Tag
enum Attribute {
DW_AT_sibling = 0x01, DW_AT_location = 0x02, DW_AT_name = 0x03, DW_AT_ordering = 0x09,
DW_AT_byte_size = 0x0b, DW_AT_bit_offset = 0x0c, DW_AT_bit_size = 0x0d, DW_AT_stmt_list = 0x10,
DW_AT_low_pc = 0x11, DW_AT_high_pc = 0x12, DW_AT_language = 0x13, DW_AT_discr = 0x15,
DW_AT_discr_value = 0x16, DW_AT_visibility = 0x17, DW_AT_import = 0x18, DW_AT_string_length = 0x19,
DW_AT_common_reference = 0x1a, DW_AT_comp_dir = 0x1b, DW_AT_const_value = 0x1c, DW_AT_containing_type = 0x1d,
DW_AT_default_value = 0x1e, DW_AT_inline = 0x20, DW_AT_is_optional = 0x21, DW_AT_lower_bound = 0x22,
DW_AT_producer = 0x25, DW_AT_prototyped = 0x27, DW_AT_return_addr = 0x2a, DW_AT_start_scope = 0x2c,
DW_AT_bit_stride = 0x2e, DW_AT_upper_bound = 0x2f, DW_AT_abstract_origin = 0x31, DW_AT_accessibility = 0x32,
DW_AT_address_class = 0x33, DW_AT_artificial = 0x34, DW_AT_base_types = 0x35, DW_AT_calling_convention = 0x36,
DW_AT_count = 0x37, DW_AT_data_member_location = 0x38, DW_AT_decl_column = 0x39, DW_AT_decl_file = 0x3a,
DW_AT_decl_line = 0x3b, DW_AT_declaration = 0x3c, DW_AT_discr_list = 0x3d, DW_AT_encoding = 0x3e,
DW_AT_external = 0x3f, DW_AT_frame_base = 0x40, DW_AT_friend = 0x41, DW_AT_identifier_case = 0x42,
DW_AT_macro_info = 0x43, DW_AT_namelist_item = 0x44, DW_AT_priority = 0x45, DW_AT_segment = 0x46,
DW_AT_specification = 0x47, DW_AT_static_link = 0x48, DW_AT_type = 0x49, DW_AT_use_location = 0x4a,
DW_AT_variable_parameter = 0x4b, DW_AT_virtuality = 0x4c, DW_AT_vtable_elem_location = 0x4d, DW_AT_allocated = 0x4e,
DW_AT_associated = 0x4f, DW_AT_data_location = 0x50, DW_AT_byte_stride = 0x51, DW_AT_entry_pc = 0x52,
DW_AT_use_UTF8 = 0x53, DW_AT_extension = 0x54, DW_AT_ranges = 0x55, DW_AT_trampoline = 0x56,
DW_AT_call_column = 0x57, DW_AT_call_file = 0x58, DW_AT_call_line = 0x59, DW_AT_description = 0x5a,
DW_AT_binary_scale = 0x5b, DW_AT_decimal_scale = 0x5c, DW_AT_small = 0x5d, DW_AT_decimal_sign = 0x5e,
DW_AT_digit_count = 0x5f, DW_AT_picture_string = 0x60, DW_AT_mutable = 0x61, DW_AT_threads_scaled = 0x62,
DW_AT_explicit = 0x63, DW_AT_object_pointer = 0x64, DW_AT_endianity = 0x65, DW_AT_elemental = 0x66,
DW_AT_pure = 0x67, DW_AT_recursive = 0x68, DW_AT_signature = 0x69, DW_AT_main_subprogram = 0x6a,
DW_AT_data_bit_offset = 0x6b, DW_AT_const_expr = 0x6c, DW_AT_enum_class = 0x6d, DW_AT_linkage_name = 0x6e,
DW_AT_string_length_bit_size = 0x6f, DW_AT_string_length_byte_size = 0x70, DW_AT_rank = 0x71, DW_AT_str_offsets_base = 0x72,
DW_AT_addr_base = 0x73, DW_AT_ranges_base = 0x74, DW_AT_dwo_id = 0x75, DW_AT_dwo_name = 0x76,
DW_AT_reference = 0x77, DW_AT_rvalue_reference = 0x78, DW_AT_lo_user = 0x2000, DW_AT_hi_user = 0x3fff,
DW_AT_MIPS_loop_begin = 0x2002, DW_AT_MIPS_tail_loop_begin = 0x2003, DW_AT_MIPS_epilog_begin = 0x2004, DW_AT_MIPS_loop_unroll_factor = 0x2005,
DW_AT_MIPS_software_pipeline_depth = 0x2006, DW_AT_MIPS_linkage_name = 0x2007, DW_AT_MIPS_stride = 0x2008, DW_AT_MIPS_abstract_name = 0x2009,
DW_AT_MIPS_clone_origin = 0x200a, DW_AT_MIPS_has_inlines = 0x200b, DW_AT_MIPS_stride_byte = 0x200c, DW_AT_MIPS_stride_elem = 0x200d,
DW_AT_MIPS_ptr_dopetype = 0x200e, DW_AT_MIPS_allocatable_dopetype = 0x200f, DW_AT_MIPS_assumed_shape_dopetype = 0x2010, DW_AT_MIPS_assumed_size = 0x2011,
DW_AT_sf_names = 0x2101, DW_AT_src_info = 0x2102, DW_AT_mac_info = 0x2103, DW_AT_src_coords = 0x2104,
DW_AT_body_begin = 0x2105, DW_AT_body_end = 0x2106, DW_AT_GNU_vector = 0x2107, DW_AT_GNU_template_name = 0x2110,
DW_AT_GNU_odr_signature = 0x210f, DW_AT_GNU_dwo_name = 0x2130, DW_AT_GNU_dwo_id = 0x2131, DW_AT_GNU_ranges_base = 0x2132,
DW_AT_GNU_addr_base = 0x2133, DW_AT_GNU_pubnames = 0x2134, DW_AT_GNU_pubtypes = 0x2135, DW_AT_APPLE_optimized = 0x3fe1,
DW_AT_APPLE_flags = 0x3fe2, DW_AT_APPLE_isa = 0x3fe3, DW_AT_APPLE_block = 0x3fe4, DW_AT_APPLE_major_runtime_vers = 0x3fe5,
DW_AT_APPLE_runtime_class = 0x3fe6, DW_AT_APPLE_omit_frame_ptr = 0x3fe7, DW_AT_APPLE_property_name = 0x3fe8, DW_AT_APPLE_property_getter = 0x3fe9,
DW_AT_APPLE_property_setter = 0x3fea, DW_AT_APPLE_property_attribute = 0x3feb, DW_AT_APPLE_objc_complete_type = 0x3fec, DW_AT_APPLE_property = 0x3fed
}
enum Form {
DW_FORM_addr = 0x01, DW_FORM_block2 = 0x03, DW_FORM_block4 = 0x04, DW_FORM_data2 = 0x05,
DW_FORM_data4 = 0x06, DW_FORM_data8 = 0x07, DW_FORM_string = 0x08, DW_FORM_block = 0x09,
DW_FORM_block1 = 0x0a, DW_FORM_data1 = 0x0b, DW_FORM_flag = 0x0c, DW_FORM_sdata = 0x0d,
DW_FORM_strp = 0x0e, DW_FORM_udata = 0x0f, DW_FORM_ref_addr = 0x10, DW_FORM_ref1 = 0x11,
DW_FORM_ref2 = 0x12, DW_FORM_ref4 = 0x13, DW_FORM_ref8 = 0x14, DW_FORM_ref_udata = 0x15,
DW_FORM_indirect = 0x16, DW_FORM_sec_offset = 0x17, DW_FORM_exprloc = 0x18, DW_FORM_flag_present = 0x19,
DW_FORM_ref_sig8 = 0x20, DW_FORM_GNU_addr_index = 0x1f01, DW_FORM_GNU_str_index = 0x1f02, DW_FORM_GNU_ref_alt = 0x1f20,
DW_FORM_GNU_strp_alt = 0x1f21
}
enum LocationAtom
enum TypeKind
enum DecimalSignEncoding {
DW_DS_unsigned = 0x01, DW_DS_leading_overpunch = 0x02, DW_DS_trailing_overpunch = 0x03, DW_DS_leading_separate = 0x04,
DW_DS_trailing_separate = 0x05
}
enum EndianityEncoding {
DW_END_default = 0x00, DW_END_big = 0x01, DW_END_little = 0x02, DW_END_lo_user = 0x40,
DW_END_hi_user = 0xff
}
enum AccessAttribute { DW_ACCESS_public = 0x01, DW_ACCESS_protected = 0x02, DW_ACCESS_private = 0x03 }
enum VisibilityAttribute { DW_VIS_local = 0x01, DW_VIS_exported = 0x02, DW_VIS_qualified = 0x03 }
enum VirtualityAttribute
enum SourceLanguage
enum CaseSensitivity { DW_ID_case_sensitive = 0x00, DW_ID_up_case = 0x01, DW_ID_down_case = 0x02, DW_ID_case_insensitive = 0x03 }
enum CallingConvention {
DW_CC_normal = 0x01, DW_CC_program = 0x02, DW_CC_nocall = 0x03, DW_CC_lo_user = 0x40,
DW_CC_hi_user = 0xff
}
enum InlineAttribute { DW_INL_not_inlined = 0x00, DW_INL_inlined = 0x01, DW_INL_declared_not_inlined = 0x02, DW_INL_declared_inlined = 0x03 }
enum ArrayDimensionOrdering { DW_ORD_row_major = 0x00, DW_ORD_col_major = 0x01 }
enum DiscriminantList { DW_DSC_label = 0x00, DW_DSC_range = 0x01 }
enum LineNumberOps {
DW_LNS_extended_op = 0x00, DW_LNS_copy = 0x01, DW_LNS_advance_pc = 0x02, DW_LNS_advance_line = 0x03,
DW_LNS_set_file = 0x04, DW_LNS_set_column = 0x05, DW_LNS_negate_stmt = 0x06, DW_LNS_set_basic_block = 0x07,
DW_LNS_const_add_pc = 0x08, DW_LNS_fixed_advance_pc = 0x09, DW_LNS_set_prologue_end = 0x0a, DW_LNS_set_epilogue_begin = 0x0b,
DW_LNS_set_isa = 0x0c
}
enum LineNumberExtendedOps {
DW_LNE_end_sequence = 0x01, DW_LNE_set_address = 0x02, DW_LNE_define_file = 0x03, DW_LNE_set_discriminator = 0x04,
DW_LNE_lo_user = 0x80, DW_LNE_hi_user = 0xff
}
enum MacinfoRecordType {
DW_MACINFO_define = 0x01, DW_MACINFO_undef = 0x02, DW_MACINFO_start_file = 0x03, DW_MACINFO_end_file = 0x04,
DW_MACINFO_vendor_ext = 0xff
}
enum CallFrameInfo {
DW_CFA_extended = 0x00, DW_CFA_nop = 0x00, DW_CFA_advance_loc = 0x40, DW_CFA_offset = 0x80,
DW_CFA_restore = 0xc0, DW_CFA_set_loc = 0x01, DW_CFA_advance_loc1 = 0x02, DW_CFA_advance_loc2 = 0x03,
DW_CFA_advance_loc4 = 0x04, DW_CFA_offset_extended = 0x05, DW_CFA_restore_extended = 0x06, DW_CFA_undefined = 0x07,
DW_CFA_same_value = 0x08, DW_CFA_register = 0x09, DW_CFA_remember_state = 0x0a, DW_CFA_restore_state = 0x0b,
DW_CFA_def_cfa = 0x0c, DW_CFA_def_cfa_register = 0x0d, DW_CFA_def_cfa_offset = 0x0e, DW_CFA_def_cfa_expression = 0x0f,
DW_CFA_expression = 0x10, DW_CFA_offset_extended_sf = 0x11, DW_CFA_def_cfa_sf = 0x12, DW_CFA_def_cfa_offset_sf = 0x13,
DW_CFA_val_offset = 0x14, DW_CFA_val_offset_sf = 0x15, DW_CFA_val_expression = 0x16, DW_CFA_MIPS_advance_loc8 = 0x1d,
DW_CFA_GNU_window_save = 0x2d, DW_CFA_GNU_args_size = 0x2e, DW_CFA_lo_user = 0x1c, DW_CFA_hi_user = 0x3f
}
enum Constants {
DW_CHILDREN_no = 0x00, DW_CHILDREN_yes = 0x01, DW_EH_PE_absptr = 0x00, DW_EH_PE_omit = 0xff,
DW_EH_PE_uleb128 = 0x01, DW_EH_PE_udata2 = 0x02, DW_EH_PE_udata4 = 0x03, DW_EH_PE_udata8 = 0x04,
DW_EH_PE_sleb128 = 0x09, DW_EH_PE_sdata2 = 0x0A, DW_EH_PE_sdata4 = 0x0B, DW_EH_PE_sdata8 = 0x0C,
DW_EH_PE_signed = 0x08, DW_EH_PE_pcrel = 0x10, DW_EH_PE_textrel = 0x20, DW_EH_PE_datarel = 0x30,
DW_EH_PE_funcrel = 0x40, DW_EH_PE_aligned = 0x50, DW_EH_PE_indirect = 0x80
}
enum LocationListEntry {
DW_LLE_end_of_list_entry, DW_LLE_base_address_selection_entry, DW_LLE_start_end_entry, DW_LLE_start_length_entry,
DW_LLE_offset_pair_entry
}
enum ApplePropertyAttributes {
DW_APPLE_PROPERTY_readonly = 0x01, DW_APPLE_PROPERTY_getter = 0x02, DW_APPLE_PROPERTY_assign = 0x04, DW_APPLE_PROPERTY_readwrite = 0x08,
DW_APPLE_PROPERTY_retain = 0x10, DW_APPLE_PROPERTY_copy = 0x20, DW_APPLE_PROPERTY_nonatomic = 0x40, DW_APPLE_PROPERTY_setter = 0x80,
DW_APPLE_PROPERTY_atomic = 0x100, DW_APPLE_PROPERTY_weak = 0x200, DW_APPLE_PROPERTY_strong = 0x400, DW_APPLE_PROPERTY_unsafe_unretained = 0x800
}
Contstants for the DW_APPLE_PROPERTY_attributes attribute.
enum AcceleratorTable {
DW_ATOM_null = 0u, DW_ATOM_die_offset = 1u, DW_ATOM_cu_offset = 2u, DW_ATOM_die_tag = 3u,
DW_ATOM_type_flags = 4u, DW_FLAG_type_implementation = 2u, DW_hash_function_djb = 0u
}
enum GDBIndexEntryKind {
GIEK_NONE, GIEK_TYPE, GIEK_VARIABLE, GIEK_FUNCTION,
GIEK_OTHER, GIEK_UNUSED5, GIEK_UNUSED6, GIEK_UNUSED7
}
enum GDBIndexEntryLinkage { GIEL_EXTERNAL, GIEL_STATIC }
Functions
bool isType (Tag T)
const char * TagString (unsigned Tag)
const char * ChildrenString (unsigned Children)
const char * AttributeString (unsigned Attribute)
const char * FormEncodingString (unsigned Encoding)
const char * OperationEncodingString (unsigned Encoding)
const char * AttributeEncodingString (unsigned Encoding)
const char * DecimalSignString (unsigned Sign)
const char * EndianityString (unsigned Endian)
const char * AccessibilityString (unsigned Access)
const char * VisibilityString (unsigned Visibility)
const char * VirtualityString (unsigned Virtuality)
const char * LanguageString (unsigned Language)
const char * CaseString (unsigned Case)
const char * ConventionString (unsigned Convention)
const char * InlineCodeString (unsigned Code)
const char * ArrayOrderString (unsigned Order)
const char * DiscriminantString (unsigned Discriminant)
const char * LNStandardString (unsigned Standard)
const char * LNExtendedString (unsigned Encoding)
const char * MacinfoString (unsigned Encoding)
const char * CallFrameString (unsigned Encoding)
const char * ApplePropertyString (unsigned)
const char * AtomTypeString (unsigned Atom)
const char * GDBIndexEntryKindString (GDBIndexEntryKind Kind)
const char * GDBIndexEntryLinkageString (GDBIndexEntryLinkage Linkage)
unsigned getTag (StringRef TagString)
unsigned getOperationEncoding (StringRef OperationEncodingString)
unsigned getVirtuality (StringRef VirtualityString)
unsigned getLanguage (StringRef LanguageString)
unsigned getAttributeEncoding (StringRef EncodingString)
const char * AttributeValueString (uint16_t Attr, unsigned Val)
Returns the symbolic string representing Val when used as a value for attribute Attr.
Variables
const uint32_t DW_CIE_ID = UINT32_MAX
const uint64_t DW64_CIE_ID = UINT64_MAX
Enumeration Type Documentation
enum llvm::dwarf::AcceleratorTable
Enumerator:
DW_ATOM_null
DW_ATOM_die_offset
DW_ATOM_cu_offset
DW_ATOM_die_tag
DW_ATOM_type_flags
DW_FLAG_type_implementation
DW_hash_function_djb
Definition at line 515 of file Dwarf.h.
enum llvm::dwarf::AccessAttribute
Enumerator:
DW_ACCESS_public
DW_ACCESS_protected
DW_ACCESS_private
Definition at line 327 of file Dwarf.h.
enum llvm::dwarf::ApplePropertyAttributes
Contstants for the DW_APPLE_PROPERTY_attributes attribute.
Keep this list in sync with clang's DeclSpec.h ObjCPropertyAttributeKind.
Enumerator:
DW_APPLE_PROPERTY_readonly
DW_APPLE_PROPERTY_getter
DW_APPLE_PROPERTY_assign
DW_APPLE_PROPERTY_readwrite
DW_APPLE_PROPERTY_retain
DW_APPLE_PROPERTY_copy
DW_APPLE_PROPERTY_nonatomic
DW_APPLE_PROPERTY_setter
DW_APPLE_PROPERTY_atomic
DW_APPLE_PROPERTY_weak
DW_APPLE_PROPERTY_strong
DW_APPLE_PROPERTY_unsafe_unretained
Definition at line 498 of file Dwarf.h.
enum llvm::dwarf::ArrayDimensionOrdering
Enumerator:
DW_ORD_row_major
DW_ORD_col_major
Definition at line 379 of file Dwarf.h.
enum llvm::dwarf::Attribute
Enumerator:
DW_AT_sibling
DW_AT_location
DW_AT_name
DW_AT_ordering
DW_AT_byte_size
DW_AT_bit_offset
DW_AT_bit_size
DW_AT_stmt_list
DW_AT_low_pc
DW_AT_high_pc
DW_AT_language
DW_AT_discr
DW_AT_discr_value
DW_AT_visibility
DW_AT_import
DW_AT_string_length
DW_AT_common_reference
DW_AT_comp_dir
DW_AT_const_value
DW_AT_containing_type
DW_AT_default_value
DW_AT_inline
DW_AT_is_optional
DW_AT_lower_bound
DW_AT_producer
DW_AT_prototyped
DW_AT_return_addr
DW_AT_start_scope
DW_AT_bit_stride
DW_AT_upper_bound
DW_AT_abstract_origin
DW_AT_accessibility
DW_AT_address_class
DW_AT_artificial
DW_AT_base_types
DW_AT_calling_convention
DW_AT_count
DW_AT_data_member_location
DW_AT_decl_column
DW_AT_decl_file
DW_AT_decl_line
DW_AT_declaration
DW_AT_discr_list
DW_AT_encoding
DW_AT_external
DW_AT_frame_base
DW_AT_friend
DW_AT_identifier_case
DW_AT_macro_info
DW_AT_namelist_item
DW_AT_priority
DW_AT_segment
DW_AT_specification
DW_AT_static_link
DW_AT_type
DW_AT_use_location
DW_AT_variable_parameter
DW_AT_virtuality
DW_AT_vtable_elem_location
DW_AT_allocated
DW_AT_associated
DW_AT_data_location
DW_AT_byte_stride
DW_AT_entry_pc
DW_AT_use_UTF8
DW_AT_extension
DW_AT_ranges
DW_AT_trampoline
DW_AT_call_column
DW_AT_call_file
DW_AT_call_line
DW_AT_description
DW_AT_binary_scale
DW_AT_decimal_scale
DW_AT_small
DW_AT_decimal_sign
DW_AT_digit_count
DW_AT_picture_string
DW_AT_mutable
DW_AT_threads_scaled
DW_AT_explicit
DW_AT_object_pointer
DW_AT_endianity
DW_AT_elemental
DW_AT_pure
DW_AT_recursive
DW_AT_signature
DW_AT_main_subprogram
DW_AT_data_bit_offset
DW_AT_const_expr
DW_AT_enum_class
DW_AT_linkage_name
DW_AT_string_length_bit_size
DW_AT_string_length_byte_size
DW_AT_rank
DW_AT_str_offsets_base
DW_AT_addr_base
DW_AT_ranges_base
DW_AT_dwo_id
DW_AT_dwo_name
DW_AT_reference
DW_AT_rvalue_reference
DW_AT_lo_user
DW_AT_hi_user
DW_AT_MIPS_loop_begin
DW_AT_MIPS_tail_loop_begin
DW_AT_MIPS_epilog_begin
DW_AT_MIPS_loop_unroll_factor
DW_AT_MIPS_software_pipeline_depth
DW_AT_MIPS_linkage_name
DW_AT_MIPS_stride
DW_AT_MIPS_abstract_name
DW_AT_MIPS_clone_origin
DW_AT_MIPS_has_inlines
DW_AT_MIPS_stride_byte
DW_AT_MIPS_stride_elem
DW_AT_MIPS_ptr_dopetype
DW_AT_MIPS_allocatable_dopetype
DW_AT_MIPS_assumed_shape_dopetype
DW_AT_MIPS_assumed_size
DW_AT_sf_names
DW_AT_src_info
DW_AT_mac_info
DW_AT_src_coords
DW_AT_body_begin
DW_AT_body_end
DW_AT_GNU_vector
DW_AT_GNU_template_name
DW_AT_GNU_odr_signature
DW_AT_GNU_dwo_name
DW_AT_GNU_dwo_id
DW_AT_GNU_ranges_base
DW_AT_GNU_addr_base
DW_AT_GNU_pubnames
DW_AT_GNU_pubtypes
DW_AT_APPLE_optimized
DW_AT_APPLE_flags
DW_AT_APPLE_isa
DW_AT_APPLE_block
DW_AT_APPLE_major_runtime_vers
DW_AT_APPLE_runtime_class
DW_AT_APPLE_omit_frame_ptr
DW_AT_APPLE_property_name
DW_AT_APPLE_property_getter
DW_AT_APPLE_property_setter
DW_AT_APPLE_property_attribute
DW_AT_APPLE_objc_complete_type
DW_AT_APPLE_property
Definition at line 92 of file Dwarf.h.
enum llvm::dwarf::CallFrameInfo
Enumerator:
DW_CFA_extended
DW_CFA_nop
DW_CFA_advance_loc
DW_CFA_offset
DW_CFA_restore
DW_CFA_set_loc
DW_CFA_advance_loc1
DW_CFA_advance_loc2
DW_CFA_advance_loc4
DW_CFA_offset_extended
DW_CFA_restore_extended
DW_CFA_undefined
DW_CFA_same_value
DW_CFA_register
DW_CFA_remember_state
DW_CFA_restore_state
DW_CFA_def_cfa
DW_CFA_def_cfa_register
DW_CFA_def_cfa_offset
DW_CFA_def_cfa_expression
DW_CFA_expression
DW_CFA_offset_extended_sf
DW_CFA_def_cfa_sf
DW_CFA_def_cfa_offset_sf
DW_CFA_val_offset
DW_CFA_val_offset_sf
DW_CFA_val_expression
DW_CFA_MIPS_advance_loc8
DW_CFA_GNU_window_save
DW_CFA_GNU_args_size
DW_CFA_lo_user
DW_CFA_hi_user
Definition at line 427 of file Dwarf.h.
enum llvm::dwarf::CallingConvention
Enumerator:
DW_CC_normal
DW_CC_program
DW_CC_nocall
DW_CC_lo_user
DW_CC_hi_user
Definition at line 362 of file Dwarf.h.
enum llvm::dwarf::CaseSensitivity
Enumerator:
DW_ID_case_sensitive
DW_ID_up_case
DW_ID_down_case
DW_ID_case_insensitive
Definition at line 354 of file Dwarf.h.
enum llvm::dwarf::Constants
Enumerator:
DW_CHILDREN_no
DW_CHILDREN_yes
DW_EH_PE_absptr
DW_EH_PE_omit
DW_EH_PE_uleb128
DW_EH_PE_udata2
DW_EH_PE_udata4
DW_EH_PE_udata8
DW_EH_PE_sleb128
DW_EH_PE_sdata2
DW_EH_PE_sdata4
DW_EH_PE_sdata8
DW_EH_PE_signed
DW_EH_PE_pcrel
DW_EH_PE_textrel
DW_EH_PE_datarel
DW_EH_PE_funcrel
DW_EH_PE_aligned
DW_EH_PE_indirect
Definition at line 463 of file Dwarf.h.
enum llvm::dwarf::DecimalSignEncoding
Enumerator:
DW_DS_unsigned
DW_DS_leading_overpunch
DW_DS_trailing_overpunch
DW_DS_leading_separate
DW_DS_trailing_separate
Definition at line 309 of file Dwarf.h.
enum llvm::dwarf::DiscriminantList
Enumerator:
DW_DSC_label
DW_DSC_range
Definition at line 385 of file Dwarf.h.
enum llvm::dwarf::EndianityEncoding
Enumerator:
DW_END_default
DW_END_big
DW_END_little
DW_END_lo_user
DW_END_hi_user
Definition at line 318 of file Dwarf.h.
enum llvm::dwarf::Form
Enumerator:
DW_FORM_addr
DW_FORM_block2
DW_FORM_block4
DW_FORM_data2
DW_FORM_data4
DW_FORM_data8
DW_FORM_string
DW_FORM_block
DW_FORM_block1
DW_FORM_data1
DW_FORM_flag
DW_FORM_sdata
DW_FORM_strp
DW_FORM_udata
DW_FORM_ref_addr
DW_FORM_ref1
DW_FORM_ref2
DW_FORM_ref4
DW_FORM_ref8
DW_FORM_ref_udata
DW_FORM_indirect
DW_FORM_sec_offset
DW_FORM_exprloc
DW_FORM_flag_present
DW_FORM_ref_sig8
DW_FORM_GNU_addr_index
DW_FORM_GNU_str_index
DW_FORM_GNU_ref_alt
DW_FORM_GNU_strp_alt
Definition at line 258 of file Dwarf.h.
enum llvm::dwarf::GDBIndexEntryKind
Enumerator:
GIEK_NONE
GIEK_TYPE
GIEK_VARIABLE
GIEK_FUNCTION
GIEK_OTHER
GIEK_UNUSED5
GIEK_UNUSED6
GIEK_UNUSED7
Definition at line 537 of file Dwarf.h.
enum llvm::dwarf::GDBIndexEntryLinkage
Enumerator:
GIEL_EXTERNAL
GIEL_STATIC
Definition at line 548 of file Dwarf.h.
enum llvm::dwarf::InlineAttribute
Enumerator:
DW_INL_not_inlined
DW_INL_inlined
DW_INL_declared_not_inlined
DW_INL_declared_inlined
Definition at line 371 of file Dwarf.h.
enum llvm::dwarf::LineNumberExtendedOps
Enumerator:
DW_LNE_end_sequence
DW_LNE_set_address
DW_LNE_define_file
DW_LNE_set_discriminator
DW_LNE_lo_user
DW_LNE_hi_user
Definition at line 408 of file Dwarf.h.
enum llvm::dwarf::LineNumberOps
Enumerator:
DW_LNS_extended_op
DW_LNS_copy
DW_LNS_advance_pc
DW_LNS_advance_line
DW_LNS_set_file
DW_LNS_set_column
DW_LNS_negate_stmt
DW_LNS_set_basic_block
DW_LNS_const_add_pc
DW_LNS_fixed_advance_pc
DW_LNS_set_prologue_end
DW_LNS_set_epilogue_begin
DW_LNS_set_isa
Definition at line 391 of file Dwarf.h.
enum llvm::dwarf::LLVMConstants
Enumerator:
DW_TAG_invalid
DW_VIRTUALITY_invalid
DWARF_VERSION
DW_PUBTYPES_VERSION
DW_PUBNAMES_VERSION
DW_ARANGES_VERSION
Definition at line 39 of file Dwarf.h.
enum llvm::dwarf::LocationAtom
Definition at line 295 of file Dwarf.h.
enum llvm::dwarf::LocationListEntry
Enumerator:
DW_LLE_end_of_list_entry
DW_LLE_base_address_selection_entry
DW_LLE_start_end_entry
DW_LLE_start_length_entry
DW_LLE_offset_pair_entry
Definition at line 488 of file Dwarf.h.
enum llvm::dwarf::MacinfoRecordType
Enumerator:
DW_MACINFO_define
DW_MACINFO_undef
DW_MACINFO_start_file
DW_MACINFO_end_file
DW_MACINFO_vendor_ext
Definition at line 418 of file Dwarf.h.
enum llvm::dwarf::SourceLanguage
Definition at line 347 of file Dwarf.h.
enum llvm::dwarf::Tag
Definition at line 56 of file Dwarf.h.
enum llvm::dwarf::TypeKind
Definition at line 302 of file Dwarf.h.
enum llvm::dwarf::VirtualityAttribute
Definition at line 341 of file Dwarf.h.
enum llvm::dwarf::VisibilityAttribute
Enumerator:
DW_VIS_local
DW_VIS_exported
DW_VIS_qualified
Definition at line 334 of file Dwarf.h.
Function Documentation
const char * llvm::dwarf::AttributeValueString (uint16_t Attr, unsigned Val)
Returns the symbolic string representing Val when used as a value for attribute Attr.
Definition at line 561 of file Dwarf.cpp.
References AccessibilityString(), ArrayOrderString(), AttributeEncodingString(), CaseString(), ConventionString(), DecimalSignString(), DiscriminantString(), DW_AT_accessibility, DW_AT_calling_convention, DW_AT_decimal_sign, DW_AT_discr_value, DW_AT_encoding, DW_AT_endianity, DW_AT_identifier_case, DW_AT_inline, DW_AT_language, DW_AT_ordering, DW_AT_virtuality, DW_AT_visibility, EndianityString(), InlineCodeString(), LanguageString(), VirtualityString(), and VisibilityString().
Referenced by llvm::DWARFDebugInfoEntryMinimal::dumpAttribute().
bool llvm::dwarf::isType (Tag T) [inline]
Definition at line 64 of file Dwarf.h.
Referenced by llvm::DwarfUnit::getOrCreateStaticMemberDIE().
Variable Documentation
const uint64_t llvm::dwarf::DW64_CIE_ID = UINT64_MAX
Definition at line 54 of file Dwarf.h.
Referenced by llvm::DWARFDebugFrame::parse().
const uint32_t llvm::dwarf::DW_CIE_ID = UINT32_MAX
Definition at line 53 of file Dwarf.h.
Referenced by llvm::DWARFDebugFrame::parse().