LLVM: llvm::X86_MC Namespace Reference
llvm::X86_MC Namespace Reference
Functions
std::string ParseX86Triple (const Triple &TT)
unsigned getDwarfRegFlavour (const Triple &TT, bool isEH)
void InitLLVM2SEHRegisterMapping (MCRegisterInfo *MRI)
MCSubtargetInfo * createX86MCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
Create a X86 MCSubtargetInfo instance.
Function Documentation
MCSubtargetInfo * llvm::X86_MC::createX86MCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS)
Create a X86 MCSubtargetInfo instance.
This is exposed so Asm parser, etc. do not need to go through TargetRegistry.
Definition at line 77 of file X86MCTargetDesc.cpp.
References llvm::StringRef::empty(), llvm::FS, ParseX86Triple(), and X.
Referenced by LLVMInitializeX86TargetMC().
unsigned llvm::X86_MC::getDwarfRegFlavour (const Triple & TT, bool isEH)
Definition at line 57 of file X86MCTargetDesc.cpp.
References llvm::Triple::getArch(), llvm::Triple::isOSCygMing(), llvm::Triple::isOSDarwin(), llvm::DWARFFlavour::X86_32_DarwinEH, llvm::DWARFFlavour::X86_32_Generic, llvm::DWARFFlavour::X86_64, and llvm::Triple::x86_64.
Referenced by createX86MCRegisterInfo().
void llvm::X86_MC::InitLLVM2SEHRegisterMapping (MCRegisterInfo * MRI)
Definition at line 69 of file X86MCTargetDesc.cpp.
References llvm::MCRegisterInfo::getEncodingValue(), and llvm::MCRegisterInfo::mapLLVMRegToSEHReg().
Referenced by createX86MCRegisterInfo().
std::string llvm::X86_MC::ParseX86Triple (const Triple & TT)
Definition at line 45 of file X86MCTargetDesc.cpp.
References llvm::Triple::CODE16, llvm::FS, llvm::Triple::getArch(), llvm::Triple::getEnvironment(), and llvm::Triple::x86_64.
Referenced by createX86MCSubtargetInfo().