LLVM: llvm::AttributeFuncs Namespace Reference
llvm::AttributeFuncs Namespace Reference
Functions
AttrBuilder typeIncompatible (const Type *Ty)
Which attributes cannot be applied to a type.
Function Documentation
AttrBuilder llvm::AttributeFuncs::typeIncompatible (const Type * Ty)
Which attributes cannot be applied to a type.
Definition at line 1379 of file Attributes.cpp.
References llvm::AttrBuilder::addAttribute(), llvm::AttrBuilder::addDereferenceableAttr(), llvm::AttrBuilder::addDereferenceableOrNullAttr(), llvm::Attribute::ByVal, llvm::Attribute::InAlloca, llvm::Type::isIntegerTy(), llvm::Type::isPointerTy(), llvm::Attribute::Nest, llvm::Attribute::NoAlias, llvm::Attribute::NoCapture, llvm::Attribute::NonNull, llvm::Attribute::ReadNone, llvm::Attribute::ReadOnly, llvm::Attribute::SExt, llvm::Attribute::StructRet, and llvm::Attribute::ZExt.