LLVM: llvm::ARM_AM Namespace Reference
llvm::ARM_AM Namespace Reference
ARM_AM - ARM Addressing Mode Stuff.
Enumerations
enum ShiftOpc {
no_shift = 0, asr, lsl, lsr,
ror, rrx
}
enum AddrOpc { sub = 0, add }
enum AMSubMode {
bad_am_submode = 0, ia, ib, da,
db
}
Functions
static ShiftOpc getShiftOpcForNode (unsigned Opcode)
static const char * getAddrOpcStr (AddrOpc Op)
static const char * getShiftOpcStr (ShiftOpc Op)
static unsigned getShiftOpcEncoding (ShiftOpc Op)
static const char * getAMSubModeStr (AMSubMode Mode)
static unsigned rotr32 (unsigned Val, unsigned Amt)
rotr32 - Rotate a 32-bit unsigned value right by a specified # bits.
static unsigned rotl32 (unsigned Val, unsigned Amt)
rotl32 - Rotate a 32-bit unsigned value left by a specified # bits.
static unsigned getSORegOpc (ShiftOpc ShOp, unsigned Imm)
static unsigned getSORegOffset (unsigned Op)
static ShiftOpc getSORegShOp (unsigned Op)
static unsigned getSOImmValImm (unsigned Imm)
getSOImmValImm - Given an encoded imm field for the reg/imm form, return the 8-bit imm value.
static unsigned getSOImmValRot (unsigned Imm)
getSOImmValRot - Given an encoded imm field for the reg/imm form, return the rotate amount.
static unsigned getSOImmValRotate (unsigned Imm)
getSOImmValRotate - Try to handle Imm with an immediate shifter operand, computing the rotate amount to use.
static int getSOImmVal (unsigned Arg)
getSOImmVal - Given a 32-bit immediate, if it is something that can fit into an shifter_operand immediate operand, return the 12-bit encoding for it.
static bool isSOImmTwoPartVal (unsigned V)
isSOImmTwoPartVal - Return true if the specified value can be obtained by or'ing together two SOImmVal's.
static unsigned getSOImmTwoPartFirst (unsigned V)
getSOImmTwoPartFirst - If V is a value that satisfies isSOImmTwoPartVal, return the first chunk of it.
static unsigned getSOImmTwoPartSecond (unsigned V)
getSOImmTwoPartSecond - If V is a value that satisfies isSOImmTwoPartVal, return the second chunk of it.
static unsigned getThumbImmValShift (unsigned Imm)
getThumbImmValShift - Try to handle Imm with a 8-bit immediate followed by a left shift.
static bool isThumbImmShiftedVal (unsigned V)
isThumbImmShiftedVal - Return true if the specified value can be obtained by left shifting a 8-bit immediate.
static unsigned getThumbImm16ValShift (unsigned Imm)
getThumbImm16ValShift - Try to handle Imm with a 16-bit immediate followed by a left shift.
static bool isThumbImm16ShiftedVal (unsigned V)
isThumbImm16ShiftedVal - Return true if the specified value can be obtained by left shifting a 16-bit immediate.
static unsigned getThumbImmNonShiftedVal (unsigned V)
getThumbImmNonShiftedVal - If V is a value that satisfies isThumbImmShiftedVal, return the non-shiftd value.
static int getT2SOImmValSplatVal (unsigned V)
getT2SOImmValSplat - Return the 12-bit encoded representation if the specified value can be obtained by splatting the low 8 bits into every other byte or every byte of a 32-bit value.
static int getT2SOImmValRotateVal (unsigned V)
getT2SOImmValRotateVal - Return the 12-bit encoded representation if the specified value is a rotated 8-bit value.
static int getT2SOImmVal (unsigned Arg)
getT2SOImmVal - Given a 32-bit immediate, if it is something that can fit into a Thumb-2 shifter_operand immediate operand, return the 12-bit encoding for it.
static unsigned getT2SOImmValRotate (unsigned V)
static bool isT2SOImmTwoPartVal (unsigned Imm)
static unsigned getT2SOImmTwoPartFirst (unsigned Imm)
static unsigned getT2SOImmTwoPartSecond (unsigned Imm)
static unsigned getAM2Opc (AddrOpc Opc, unsigned Imm12, ShiftOpc SO, unsigned IdxMode=0)
static unsigned getAM2Offset (unsigned AM2Opc)
static AddrOpc getAM2Op (unsigned AM2Opc)
static ShiftOpc getAM2ShiftOpc (unsigned AM2Opc)
static unsigned getAM2IdxMode (unsigned AM2Opc)
static unsigned getAM3Opc (AddrOpc Opc, unsigned char Offset, unsigned IdxMode=0)
getAM3Opc - This function encodes the addrmode3 opc field.
static unsigned char getAM3Offset (unsigned AM3Opc)
static AddrOpc getAM3Op (unsigned AM3Opc)
static unsigned getAM3IdxMode (unsigned AM3Opc)
static AMSubMode getAM4SubMode (unsigned Mode)
static unsigned getAM4ModeImm (AMSubMode SubMode)
static unsigned getAM5Opc (AddrOpc Opc, unsigned char Offset)
getAM5Opc - This function encodes the addrmode5 opc field.
static unsigned char getAM5Offset (unsigned AM5Opc)
static AddrOpc getAM5Op (unsigned AM5Opc)
static unsigned createNEONModImm (unsigned OpCmode, unsigned Val)
static unsigned getNEONModImmOpCmode (unsigned ModImm)
static unsigned getNEONModImmVal (unsigned ModImm)
static uint64_t decodeNEONModImm (unsigned ModImm, unsigned &EltBits)
decodeNEONModImm - Decode a NEON modified immediate value into the element value and the element size in bits.
static bool isNEONBytesplat (unsigned Value, unsigned Size)
static bool isNEONi16splat (unsigned Value)
Checks if Value is a correct immediate for instructions like VBIC/VORR.
static unsigned encodeNEONi16splat (unsigned Value)
static bool isNEONi32splat (unsigned Value)
Checks if Value is a correct immediate for instructions like VBIC/VORR.
static unsigned encodeNEONi32splat (unsigned Value)
Encode NEON 32 bits Splat immediate for instructions like VBIC/VORR.
static float getFPImmFloat (unsigned Imm)
static int getFP32Imm (const APInt &Imm)
getFP32Imm - Return an 8-bit floating-point version of the 32-bit floating-point value.
static int getFP32Imm (const APFloat &FPImm)
static int getFP64Imm (const APInt &Imm)
getFP64Imm - Return an 8-bit floating-point version of the 64-bit floating-point value.
static int getFP64Imm (const APFloat &FPImm)
Detailed Description
ARM_AM - ARM Addressing Mode Stuff.
Enumeration Type Documentation
enum llvm::ARM_AM::AddrOpc
Enumerator:
sub
add
Definition at line 36 of file ARMAddressingModes.h.
enum llvm::ARM_AM::AMSubMode
Enumerator:
bad_am_submode
ia
ib
da
db
Definition at line 66 of file ARMAddressingModes.h.
enum llvm::ARM_AM::ShiftOpc
Enumerator:
no_shift
asr
lsl
lsr
ror
rrx
Definition at line 27 of file ARMAddressingModes.h.
Function Documentation
static unsigned llvm::ARM_AM::createNEONModImm (unsigned OpCmode, unsigned Val) [inline, static]
Definition at line 528 of file ARMAddressingModes.h.
Referenced by isNEONModifiedImm().
static uint64_t llvm::ARM_AM::decodeNEONModImm (unsigned ModImm, unsigned & EltBits) [inline, static]
decodeNEONModImm - Decode a NEON modified immediate value into the element value and the element size in bits.
(If the element size is smaller than the vector, it is splatted into all the elements.)
Definition at line 541 of file ARMAddressingModes.h.
References getNEONModImmOpCmode(), getNEONModImmVal(), llvm::X86II::Imm8, and llvm_unreachable.
Referenced by PerformVDUPLANECombine(), and llvm::ARMInstPrinter::printNEONModImmOperand().
static unsigned llvm::ARM_AM::encodeNEONi16splat (unsigned Value) [inline, static]
Definition at line 598 of file ARMAddressingModes.h.
References isNEONi16splat().
static unsigned llvm::ARM_AM::encodeNEONi32splat (unsigned Value) [inline, static]
Encode NEON 32 bits Splat immediate for instructions like VBIC/VORR.
Definition at line 614 of file ARMAddressingModes.h.
References isNEONi32splat().
static const char* llvm::ARM_AM::getAddrOpcStr (AddrOpc Op) [inline, static]
Definition at line 41 of file ARMAddressingModes.h.
References sub.
Referenced by llvm::ARMInstPrinter::printAddrMode2OffsetOperand(), llvm::ARMInstPrinter::printAddrMode3OffsetOperand(), llvm::ARMInstPrinter::printAddrMode5Operand(), llvm::ARMInstPrinter::printAM2PreOrOffsetIndexOp(), and llvm::ARMInstPrinter::printAM3PreOrOffsetIndexOp().
static unsigned llvm::ARM_AM::getAM2IdxMode (unsigned AM2Opc) [inline, static]
Definition at line 422 of file ARMAddressingModes.h.
Referenced by llvm::ARMInstPrinter::printAddrMode2Operand().
static unsigned llvm::ARM_AM::getAM2Offset (unsigned AM2Opc) [inline, static]
Definition at line 413 of file ARMAddressingModes.h.
Referenced by adjustDefLatency(), llvm::ARMBaseInstrInfo::convertToThreeAddress(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::ARMBaseRegisterInfo::getFrameIndexInstrOffset(), getNumMicroOpsSwiftLdSt(), llvm::ARMBaseInstrInfo::getOperandLatency(), llvm::ARMInstPrinter::printAddrMode2OffsetOperand(), llvm::ARMInstPrinter::printAM2PreOrOffsetIndexOp(), and llvm::rewriteARMFrameIndex().
static AddrOpc llvm::ARM_AM::getAM2Op (unsigned AM2Opc) [inline, static]
Definition at line 416 of file ARMAddressingModes.h.
References add, and sub.
Referenced by adjustDefLatency(), llvm::ARMBaseInstrInfo::convertToThreeAddress(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::ARMBaseRegisterInfo::getFrameIndexInstrOffset(), getNumMicroOpsSwiftLdSt(), llvm::ARMInstPrinter::printAddrMode2OffsetOperand(), llvm::ARMInstPrinter::printAM2PreOrOffsetIndexOp(), and llvm::rewriteARMFrameIndex().
static unsigned llvm::ARM_AM::getAM2Opc (AddrOpc Opc, unsigned Imm12, ShiftOpc SO, unsigned IdxMode = 0) [inline, static]
Definition at line 407 of file ARMAddressingModes.h.
References sub.
Referenced by DecodeAddrMode2IdxInstruction(), and DecodeSORegMemOperand().
static ShiftOpc llvm::ARM_AM::getAM2ShiftOpc (unsigned AM2Opc) [inline, static]
Definition at line 419 of file ARMAddressingModes.h.
Referenced by adjustDefLatency(), llvm::ARMBaseInstrInfo::convertToThreeAddress(), getNumMicroOpsSwiftLdSt(), llvm::ARMBaseInstrInfo::getOperandLatency(), llvm::ARMInstPrinter::printAddrMode2OffsetOperand(), and llvm::ARMInstPrinter::printAM2PreOrOffsetIndexOp().
static unsigned llvm::ARM_AM::getAM3IdxMode (unsigned AM3Opc) [inline, static]
Definition at line 453 of file ARMAddressingModes.h.
Referenced by llvm::ARMInstPrinter::printAddrMode3Operand().
static unsigned char llvm::ARM_AM::getAM3Offset (unsigned AM3Opc) [inline, static]
Definition at line 447 of file ARMAddressingModes.h.
Referenced by llvm::ARMBaseInstrInfo::convertToThreeAddress(), llvm::ARMBaseRegisterInfo::getFrameIndexInstrOffset(), getMemoryOpOffset(), llvm::ARMInstPrinter::printAddrMode3OffsetOperand(), llvm::ARMInstPrinter::printAM3PreOrOffsetIndexOp(), and llvm::rewriteARMFrameIndex().
static AddrOpc llvm::ARM_AM::getAM3Op (unsigned AM3Opc) [inline, static]
Definition at line 450 of file ARMAddressingModes.h.
References add, and sub.
Referenced by llvm::ARMBaseInstrInfo::convertToThreeAddress(), llvm::ARMBaseRegisterInfo::getFrameIndexInstrOffset(), getMemoryOpOffset(), getNumMicroOpsSwiftLdSt(), llvm::ARMInstPrinter::printAddrMode3OffsetOperand(), llvm::ARMInstPrinter::printAM3PreOrOffsetIndexOp(), and llvm::rewriteARMFrameIndex().
static unsigned llvm::ARM_AM::getAM3Opc (AddrOpc Opc, unsigned char Offset, unsigned IdxMode = 0) [inline, static]
getAM3Opc - This function encodes the addrmode3 opc field.
Definition at line 442 of file ARMAddressingModes.h.
References sub.
static unsigned llvm::ARM_AM::getAM4ModeImm (AMSubMode SubMode) [inline, static]
Definition at line 476 of file ARMAddressingModes.h.
static AMSubMode llvm::ARM_AM::getAM4SubMode (unsigned Mode) [inline, static]
Definition at line 472 of file ARMAddressingModes.h.
Referenced by llvm::ARMInstPrinter::printLdStmModeOperand().
static unsigned char llvm::ARM_AM::getAM5Offset (unsigned AM5Opc) [inline, static]
Definition at line 496 of file ARMAddressingModes.h.
Referenced by llvm::ARMBaseRegisterInfo::getFrameIndexInstrOffset(), getMemoryOpOffset(), llvm::ARMInstPrinter::printAddrMode5Operand(), llvm::rewriteARMFrameIndex(), and llvm::rewriteT2FrameIndex().
static AddrOpc llvm::ARM_AM::getAM5Op (unsigned AM5Opc) [inline, static]
Definition at line 499 of file ARMAddressingModes.h.
References add, and sub.
Referenced by llvm::ARMBaseRegisterInfo::getFrameIndexInstrOffset(), getMemoryOpOffset(), llvm::ARMInstPrinter::printAddrMode5Operand(), llvm::rewriteARMFrameIndex(), and llvm::rewriteT2FrameIndex().
static unsigned llvm::ARM_AM::getAM5Opc (AddrOpc Opc, unsigned char Offset) [inline, static]
getAM5Opc - This function encodes the addrmode5 opc field.
Definition at line 492 of file ARMAddressingModes.h.
References sub.
Referenced by DecodeAddrMode5Operand(), and DecodeCopMemInstruction().
static const char* llvm::ARM_AM::getAMSubModeStr (AMSubMode Mode) [inline, static]
Definition at line 74 of file ARMAddressingModes.h.
References da, db, ia, ib, and llvm_unreachable.
Referenced by llvm::ARMInstPrinter::printLdStmModeOperand().
static int llvm::ARM_AM::getFP32Imm (const APInt & Imm) [inline, static]
getFP32Imm - Return an 8-bit floating-point version of the 32-bit floating-point value.
If the value cannot be represented as an 8-bit floating-point value, then return -1.
Definition at line 656 of file ARMAddressingModes.h.
References llvm::APInt::getSExtValue(), llvm::APInt::getZExtValue(), and llvm::APInt::lshr().
Referenced by getFP32Imm().
static int llvm::ARM_AM::getFP32Imm (const APFloat & FPImm) [inline, static]
Definition at line 677 of file ARMAddressingModes.h.
References llvm::APFloat::bitcastToAPInt(), and getFP32Imm().
static int llvm::ARM_AM::getFP64Imm (const APInt & Imm) [inline, static]
getFP64Imm - Return an 8-bit floating-point version of the 64-bit floating-point value.
If the value cannot be represented as an 8-bit floating-point value, then return -1.
Definition at line 684 of file ARMAddressingModes.h.
References llvm::APInt::getSExtValue(), llvm::APInt::getZExtValue(), and llvm::APInt::lshr().
Referenced by getFP64Imm().
static int llvm::ARM_AM::getFP64Imm (const APFloat & FPImm) [inline, static]
Definition at line 705 of file ARMAddressingModes.h.
References llvm::APFloat::bitcastToAPInt(), and getFP64Imm().
static float llvm::ARM_AM::getFPImmFloat (unsigned Imm) [inline, static]
Definition at line 628 of file ARMAddressingModes.h.
References F(), and I.
static unsigned llvm::ARM_AM::getNEONModImmOpCmode (unsigned ModImm) [inline, static]
Definition at line 531 of file ARMAddressingModes.h.
Referenced by decodeNEONModImm().
static unsigned llvm::ARM_AM::getNEONModImmVal (unsigned ModImm) [inline, static]
Definition at line 534 of file ARMAddressingModes.h.
Referenced by decodeNEONModImm().
static unsigned llvm::ARM_AM::getShiftOpcEncoding (ShiftOpc Op) [inline, static]
Definition at line 56 of file ARMAddressingModes.h.
References asr, llvm_unreachable, lsl, lsr, and ror.
static ShiftOpc llvm::ARM_AM::getShiftOpcForNode (unsigned Opcode) [inline, static]
Definition at line 23 of file ARMSelectionDAGInfo.h.
References asr, lsl, lsr, no_shift, ror, llvm::ISD::ROTR, llvm::ISD::SHL, llvm::ISD::SRA, and llvm::ISD::SRL.
Referenced by getARMIndexedAddressParts().
static const char* llvm::ARM_AM::getShiftOpcStr (ShiftOpc Op) [inline, static]
Definition at line 45 of file ARMAddressingModes.h.
References asr, llvm_unreachable, lsl, lsr, ror, and rrx.
Referenced by llvm::ARMInstPrinter::printInst(), printRegImmShift(), and llvm::ARMInstPrinter::printSORegRegOperand().
static unsigned llvm::ARM_AM::getSOImmTwoPartFirst (unsigned V) [inline, static]
getSOImmTwoPartFirst - If V is a value that satisfies isSOImmTwoPartVal, return the first chunk of it.
Definition at line 201 of file ARMAddressingModes.h.
References getSOImmValRotate(), and rotr32().
Referenced by llvm::ARMBaseInstrInfo::FoldImmediate().
static unsigned llvm::ARM_AM::getSOImmTwoPartSecond (unsigned V) [inline, static]
getSOImmTwoPartSecond - If V is a value that satisfies isSOImmTwoPartVal, return the second chunk of it.
Definition at line 207 of file ARMAddressingModes.h.
References getSOImmValRotate(), and rotr32().
Referenced by llvm::ARMBaseInstrInfo::FoldImmediate().
static int llvm::ARM_AM::getSOImmVal (unsigned Arg) [inline, static]
getSOImmVal - Given a 32-bit immediate, if it is something that can fit into an shifter_operand immediate operand, return the 12-bit encoding for it.
If not, return -1.
Definition at line 171 of file ARMAddressingModes.h.
References getSOImmValRotate(), rotl32(), and rotr32().
Referenced by adjustFixupValue(), llvm::ARMBaseInstrInfo::convertToThreeAddress(), llvm::ARMTTIImpl::getIntImmCost(), llvm::ARMTargetLowering::isLegalAddImmediate(), llvm::ARMTargetLowering::isLegalICmpImmediate(), IsSingleInstrConstant(), llvm::LowerARMMachineInstrToMCInst(), llvm::ARMTargetLowering::LowerAsmOperandForConstraint(), llvm::ARMInstPrinter::printModImmOperand(), and llvm::rewriteARMFrameIndex().
static unsigned llvm::ARM_AM::getSOImmValImm (unsigned Imm) [inline, static]
getSOImmValImm - Given an encoded imm field for the reg/imm form, return the 8-bit imm value.
Definition at line 124 of file ARMAddressingModes.h.
static unsigned llvm::ARM_AM::getSOImmValRot (unsigned Imm) [inline, static]
getSOImmValRot - Given an encoded imm field for the reg/imm form, return the rotate amount.
Definition at line 129 of file ARMAddressingModes.h.
static unsigned llvm::ARM_AM::getSOImmValRotate (unsigned Imm) [inline, static]
getSOImmValRotate - Try to handle Imm with an immediate shifter operand, computing the rotate amount to use.
If this immediate value cannot be handled with a single shifter-op, determine a good rotate amount that will take a maximal chunk of bits out of the immediate.
Definition at line 137 of file ARMAddressingModes.h.
References llvm::countTrailingZeros(), and rotr32().
Referenced by getSOImmTwoPartFirst(), getSOImmTwoPartSecond(), getSOImmVal(), isSOImmTwoPartVal(), and llvm::rewriteARMFrameIndex().
static unsigned llvm::ARM_AM::getSORegOffset (unsigned Op) [inline, static]
Definition at line 115 of file ARMAddressingModes.h.
Referenced by llvm::ARMBaseInstrInfo::isSwiftFastImmShift(), llvm::ARMInstPrinter::printInst(), llvm::ARMInstPrinter::printSORegImmOperand(), llvm::ARMInstPrinter::printSORegRegOperand(), and llvm::ARMInstPrinter::printT2SOOperand().
static unsigned llvm::ARM_AM::getSORegOpc (ShiftOpc ShOp, unsigned Imm) [inline, static]
Definition at line 112 of file ARMAddressingModes.h.
Referenced by llvm::ARMBaseInstrInfo::convertToThreeAddress(), and emitAligningInstructions().
static ShiftOpc llvm::ARM_AM::getSORegShOp (unsigned Op) [inline, static]
Definition at line 118 of file ARMAddressingModes.h.
Referenced by llvm::ARMBaseInstrInfo::isSwiftFastImmShift(), llvm::ARMInstPrinter::printInst(), llvm::ARMInstPrinter::printSORegImmOperand(), llvm::ARMInstPrinter::printSORegRegOperand(), and llvm::ARMInstPrinter::printT2SOOperand().
static unsigned llvm::ARM_AM::getT2SOImmTwoPartFirst (unsigned Imm) [inline, static]
Definition at line 362 of file ARMAddressingModes.h.
References getT2SOImmVal(), getT2SOImmValRotate(), getT2SOImmValSplatVal(), isT2SOImmTwoPartVal(), and rotr32().
Referenced by llvm::ARMBaseInstrInfo::FoldImmediate(), and getT2SOImmTwoPartSecond().
static unsigned llvm::ARM_AM::getT2SOImmTwoPartSecond (unsigned Imm) [inline, static]
Definition at line 379 of file ARMAddressingModes.h.
References getT2SOImmTwoPartFirst(), and getT2SOImmVal().
Referenced by llvm::ARMBaseInstrInfo::FoldImmediate().
static int llvm::ARM_AM::getT2SOImmVal (unsigned Arg) [inline, static]
getT2SOImmVal - Given a 32-bit immediate, if it is something that can fit into a Thumb-2 shifter_operand immediate operand, return the 12-bit encoding for it.
If not, return -1. See ARM Reference Manual A6.3.2.
Definition at line 314 of file ARMAddressingModes.h.
References getT2SOImmValRotateVal(), and getT2SOImmValSplatVal().
Referenced by llvm::ARMTTIImpl::getIntImmCost(), getT2SOImmTwoPartFirst(), getT2SOImmTwoPartSecond(), llvm::ARMTargetLowering::isLegalAddImmediate(), llvm::ARMTargetLowering::isLegalICmpImmediate(), isT2SOImmTwoPartVal(), llvm::ARMTargetLowering::LowerAsmOperandForConstraint(), and llvm::rewriteT2FrameIndex().
static unsigned llvm::ARM_AM::getT2SOImmValRotate (unsigned V) [inline, static]
Definition at line 328 of file ARMAddressingModes.h.
References llvm::countTrailingZeros().
Referenced by getT2SOImmTwoPartFirst(), and isT2SOImmTwoPartVal().
static int llvm::ARM_AM::getT2SOImmValRotateVal (unsigned V) [inline, static]
getT2SOImmValRotateVal - Return the 12-bit encoded representation if the specified value is a rotated 8-bit value.
Return -1 if no rotation encoding is possible. See ARM Reference Manual A6.3.2.
Definition at line 298 of file ARMAddressingModes.h.
References llvm::countLeadingZeros(), and rotr32().
Referenced by getT2SOImmVal().
static int llvm::ARM_AM::getT2SOImmValSplatVal (unsigned V) [inline, static]
getT2SOImmValSplat - Return the 12-bit encoded representation if the specified value can be obtained by splatting the low 8 bits into every other byte or every byte of a 32-bit value.
i.e., 00000000 00000000 00000000 abcdefgh control = 0 00000000 abcdefgh 00000000 abcdefgh control = 1 abcdefgh 00000000 abcdefgh 00000000 control = 2 abcdefgh abcdefgh abcdefgh abcdefgh control = 3 Return -1 if none of the above apply. See ARM Reference Manual A6.3.2.
Definition at line 270 of file ARMAddressingModes.h.
Referenced by getT2SOImmTwoPartFirst(), getT2SOImmVal(), and isT2SOImmTwoPartVal().
static unsigned llvm::ARM_AM::getThumbImm16ValShift (unsigned Imm) [inline, static]
getThumbImm16ValShift - Try to handle Imm with a 16-bit immediate followed by a left shift.
Returns the shift amount to use.
Definition at line 237 of file ARMAddressingModes.h.
References llvm::countTrailingZeros().
Referenced by isThumbImm16ShiftedVal().
static unsigned llvm::ARM_AM::getThumbImmNonShiftedVal (unsigned V) [inline, static]
getThumbImmNonShiftedVal - If V is a value that satisfies isThumbImmShiftedVal, return the non-shiftd value.
Definition at line 256 of file ARMAddressingModes.h.
References getThumbImmValShift().
static unsigned llvm::ARM_AM::getThumbImmValShift (unsigned Imm) [inline, static]
getThumbImmValShift - Try to handle Imm with a 8-bit immediate followed by a left shift.
Returns the shift amount to use.
Definition at line 218 of file ARMAddressingModes.h.
References llvm::countTrailingZeros().
Referenced by getThumbImmNonShiftedVal(), and isThumbImmShiftedVal().
static bool llvm::ARM_AM::isNEONBytesplat (unsigned Value, unsigned Size) [inline, static]
Definition at line 579 of file ARMAddressingModes.h.
Referenced by isNEONi16splat(), and isNEONi32splat().
static bool llvm::ARM_AM::isNEONi16splat (unsigned Value) [inline, static]
Checks if Value is a correct immediate for instructions like VBIC/VORR.
Definition at line 590 of file ARMAddressingModes.h.
References isNEONBytesplat().
Referenced by encodeNEONi16splat().
static bool llvm::ARM_AM::isNEONi32splat (unsigned Value) [inline, static]
Checks if Value is a correct immediate for instructions like VBIC/VORR.
Definition at line 608 of file ARMAddressingModes.h.
References isNEONBytesplat().
Referenced by encodeNEONi32splat().
static bool llvm::ARM_AM::isSOImmTwoPartVal (unsigned V) [inline, static]
isSOImmTwoPartVal - Return true if the specified value can be obtained by or'ing together two SOImmVal's.
Definition at line 188 of file ARMAddressingModes.h.
References getSOImmValRotate(), and rotr32().
Referenced by llvm::ARMBaseInstrInfo::FoldImmediate().
static bool llvm::ARM_AM::isT2SOImmTwoPartVal (unsigned Imm) [inline, static]
Definition at line 335 of file ARMAddressingModes.h.
References getT2SOImmVal(), getT2SOImmValRotate(), getT2SOImmValSplatVal(), and rotr32().
Referenced by llvm::ARMBaseInstrInfo::FoldImmediate(), and getT2SOImmTwoPartFirst().
static bool llvm::ARM_AM::isThumbImm16ShiftedVal (unsigned V) [inline, static]
isThumbImm16ShiftedVal - Return true if the specified value can be obtained by left shifting a 16-bit immediate.
Definition at line 248 of file ARMAddressingModes.h.
References getThumbImm16ValShift().
static bool llvm::ARM_AM::isThumbImmShiftedVal (unsigned V) [inline, static]
isThumbImmShiftedVal - Return true if the specified value can be obtained by left shifting a 8-bit immediate.
Definition at line 229 of file ARMAddressingModes.h.
References getThumbImmValShift().
Referenced by llvm::ARMTTIImpl::getIntImmCost(), and llvm::ARMTargetLowering::LowerAsmOperandForConstraint().
static unsigned llvm::ARM_AM::rotl32 (unsigned Val, unsigned Amt) [inline, static]
rotl32 - Rotate a 32-bit unsigned value left by a specified # bits.
Definition at line 93 of file ARMAddressingModes.h.
Referenced by getSOImmVal().
static unsigned llvm::ARM_AM::rotr32 (unsigned Val, unsigned Amt) [inline, static]
rotr32 - Rotate a 32-bit unsigned value right by a specified # bits.
Definition at line 86 of file ARMAddressingModes.h.
Referenced by getSOImmTwoPartFirst(), getSOImmTwoPartSecond(), getSOImmVal(), getSOImmValRotate(), getT2SOImmTwoPartFirst(), getT2SOImmValRotateVal(), isSOImmTwoPartVal(), isT2SOImmTwoPartVal(), llvm::ARMInstPrinter::printModImmOperand(), llvm::rewriteARMFrameIndex(), and llvm::rewriteT2FrameIndex().