LLVM: llvm::ARM Namespace Reference
llvm::ARM Namespace Reference
Define some predicates that are used for node matching.
Namespaces
namespace EHABI
namespace WinEH
Enumerations
enum FPUKind {
FK_INVALID = 0, FK_NONE, FK_VFP, FK_VFPV2,
FK_VFPV3, FK_VFPV3_D16, FK_VFPV4, FK_VFPV4_D16,
FK_FPV4_SP_D16, FK_FPV5_D16, FK_FPV5_SP_D16, FK_FP_ARMV8,
FK_NEON, FK_NEON_VFPV4, FK_NEON_FP_ARMV8, FK_CRYPTO_NEON_FP_ARMV8,
FK_SOFTVFP, FK_LAST
}
enum NeonSupportLevel { NS_None = 0, NS_Neon, NS_Crypto }
enum FPURestriction { FR_None = 0, FR_D16, FR_SP_D16 }
enum ArchKind {
AK_INVALID = 0, AK_ARMV2, AK_ARMV2A, AK_ARMV3,
AK_ARMV3M, AK_ARMV4, AK_ARMV4T, AK_ARMV5T,
AK_ARMV5TE, AK_ARMV5TEJ, AK_ARMV6, AK_ARMV6K,
AK_ARMV6T2, AK_ARMV6Z, AK_ARMV6ZK, AK_ARMV6M,
AK_ARMV6SM, AK_ARMV7A, AK_ARMV7R, AK_ARMV7M,
AK_ARMV7EM, AK_ARMV8A, AK_ARMV8_1A, AK_IWMMXT,
AK_IWMMXT2, AK_XSCALE, AK_ARMV5, AK_ARMV5E,
AK_ARMV6J, AK_ARMV6HL, AK_ARMV7, AK_ARMV7L,
AK_ARMV7HL, AK_ARMV7S, AK_LAST
}
enum ArchExtKind {
AEK_INVALID = 0, AEK_CRC, AEK_CRYPTO, AEK_FP,
AEK_HWDIV, AEK_MP, AEK_SIMD, AEK_SEC,
AEK_VIRT, AEK_OS, AEK_IWMMXT, AEK_IWMMXT2,
AEK_MAVERICK, AEK_XSCALE, AEK_LAST
}
enum ISAKind { IK_INVALID = 0, IK_ARM, IK_THUMB, IK_AARCH64 }
enum EndianKind { EK_INVALID = 0, EK_LITTLE, EK_BIG }
enum ProfileKind { PK_INVALID = 0, PK_A, PK_R, PK_M }
enum DW_ISA { DW_ISA_ARM_thumb = 1, DW_ISA_ARM_arm = 2 }
enum Fixups {
fixup_arm_ldst_pcrel_12 = FirstTargetFixupKind, fixup_t2_ldst_pcrel_12, fixup_arm_pcrel_10_unscaled, fixup_arm_pcrel_10,
fixup_t2_pcrel_10, fixup_thumb_adr_pcrel_10, fixup_arm_adr_pcrel_12, fixup_t2_adr_pcrel_12,
fixup_arm_condbranch, fixup_arm_uncondbranch, fixup_t2_condbranch, fixup_t2_uncondbranch,
fixup_arm_thumb_br, fixup_arm_uncondbl, fixup_arm_condbl, fixup_arm_blx,
fixup_arm_thumb_bl, fixup_arm_thumb_blx, fixup_arm_thumb_cb, fixup_arm_thumb_cp,
fixup_arm_thumb_bcc, fixup_arm_movt_hi16, fixup_arm_movw_lo16, fixup_t2_movt_hi16,
fixup_t2_movw_lo16, LastTargetFixupKind, NumTargetFixupKinds = LastTargetFixupKind - FirstTargetFixupKind
}
Functions
bool isBitFieldInvertedMask (unsigned v)
FastISel * createFastISel (FunctionLoweringInfo &funcInfo, const TargetLibraryInfo *libInfo)
Detailed Description
Define some predicates that are used for node matching.
Enumeration Type Documentation
enum llvm::ARM::ArchExtKind
Enumerator:
AEK_INVALID
AEK_CRC
AEK_CRYPTO
AEK_FP
AEK_HWDIV
AEK_MP
AEK_SIMD
AEK_SEC
AEK_VIRT
AEK_OS
AEK_IWMMXT
AEK_IWMMXT2
AEK_MAVERICK
AEK_XSCALE
AEK_LAST
Definition at line 109 of file TargetParser.h.
enum llvm::ARM::ArchKind
Enumerator:
AK_INVALID
AK_ARMV2
AK_ARMV2A
AK_ARMV3
AK_ARMV3M
AK_ARMV4
AK_ARMV4T
AK_ARMV5T
AK_ARMV5TE
AK_ARMV5TEJ
AK_ARMV6
AK_ARMV6K
AK_ARMV6T2
AK_ARMV6Z
AK_ARMV6ZK
AK_ARMV6M
AK_ARMV6SM
AK_ARMV7A
AK_ARMV7R
AK_ARMV7M
AK_ARMV7EM
AK_ARMV8A
AK_ARMV8_1A
AK_IWMMXT
AK_IWMMXT2
AK_XSCALE
AK_ARMV5
AK_ARMV5E
AK_ARMV6J
AK_ARMV6HL
AK_ARMV7
AK_ARMV7L
AK_ARMV7HL
AK_ARMV7S
AK_LAST
Definition at line 69 of file TargetParser.h.
enum llvm::ARM::DW_ISA
Enumerator:
DW_ISA_ARM_thumb
DW_ISA_ARM_arm
Definition at line 26 of file ARMAsmPrinter.h.
enum llvm::ARM::EndianKind
Enumerator:
EK_INVALID
EK_LITTLE
EK_BIG
Definition at line 138 of file TargetParser.h.
enum llvm::ARM::Fixups
Enumerator:
fixup_arm_ldst_pcrel_12
fixup_t2_ldst_pcrel_12
fixup_arm_pcrel_10_unscaled
fixup_arm_pcrel_10
fixup_t2_pcrel_10
fixup_thumb_adr_pcrel_10
fixup_arm_adr_pcrel_12
fixup_t2_adr_pcrel_12
fixup_arm_condbranch
fixup_arm_uncondbranch
fixup_t2_condbranch
fixup_t2_uncondbranch
fixup_arm_thumb_br
fixup_arm_uncondbl
fixup_arm_condbl
fixup_arm_blx
fixup_arm_thumb_bl
fixup_arm_thumb_blx
fixup_arm_thumb_cb
fixup_arm_thumb_cp
fixup_arm_thumb_bcc
fixup_arm_movt_hi16
fixup_arm_movw_lo16
fixup_t2_movt_hi16
fixup_t2_movw_lo16
LastTargetFixupKind
NumTargetFixupKinds
Definition at line 17 of file ARMFixupKinds.h.
enum llvm::ARM::FPUKind
Enumerator:
FK_INVALID
FK_NONE
FK_VFP
FK_VFPV2
FK_VFPV3
FK_VFPV3_D16
FK_VFPV4
FK_VFPV4_D16
FK_FPV4_SP_D16
FK_FPV5_D16
FK_FPV5_SP_D16
FK_FP_ARMV8
FK_NEON
FK_NEON_VFPV4
FK_NEON_FP_ARMV8
FK_CRYPTO_NEON_FP_ARMV8
FK_SOFTVFP
FK_LAST
Definition at line 33 of file TargetParser.h.
enum llvm::ARM::FPURestriction
Enumerator:
FR_None
No restriction.
FR_D16
Only 16 D registers.
FR_SP_D16
Only single-precision instructions, with 16 D registers.
Definition at line 62 of file TargetParser.h.
enum llvm::ARM::ISAKind
Enumerator:
IK_INVALID
IK_ARM
IK_THUMB
IK_AARCH64
Definition at line 129 of file TargetParser.h.
enum llvm::ARM::NeonSupportLevel
Enumerator:
NS_None
No Neon.
NS_Neon
Neon.
NS_Crypto
Neon with Crypto.
Definition at line 55 of file TargetParser.h.
enum llvm::ARM::ProfileKind
Enumerator:
PK_INVALID
PK_A
PK_R
PK_M
Definition at line 145 of file TargetParser.h.
Function Documentation
FastISel * llvm::ARM::createFastISel (FunctionLoweringInfo & funcInfo, const TargetLibraryInfo * libInfo)
Definition at line 3066 of file ARMFastISel.cpp.
References llvm::MachineFunction::getSubtarget(), llvm::FunctionLoweringInfo::MF, and llvm::ARMSubtarget::useFastISel().
bool llvm::ARM::isBitFieldInvertedMask (unsigned v)
Definition at line 11048 of file ARMISelLowering.cpp.
References llvm::isShiftedMask_32().
Referenced by PerformORCombine().