LLVM: llvm::objcarc Namespace Reference
llvm::objcarc Namespace Reference
Classes
class ARCRuntimeEntryPoints
Declarations for ObjC runtime functions and constants.
class ARCMDKindCache
A cache of MDKinds used by various ARC optimizations.
class ObjCARCAliasAnalysis
This is a simple alias analysis implementation that uses knowledge of ARC constructs to answer queries.
class ProvenanceAnalysis
This is similar to BasicAliasAnalysis, and it uses many of the same techniques, except it uses special ObjC-specific reasoning about pointer relationships.
struct RRInfo
Unidirectional information about either a retain-decrement-use-release sequence or release-use-decrement-retain reverse sequence.
class PtrState
This class summarizes several per-pointer runtime properties which are propogated through the flow graph.
struct BottomUpPtrState
struct TopDownPtrState
Enumerations
enum ARCInstKind {
Retain, RetainRV, RetainBlock, Release,
Autorelease, AutoreleaseRV, AutoreleasepoolPush, AutoreleasepoolPop,
NoopCast, FusedRetainAutorelease, FusedRetainAutoreleaseRV, LoadWeakRetained,
StoreWeak, InitWeak, LoadWeak, MoveWeak,
CopyWeak, DestroyWeak, StoreStrong, IntrinsicUser,
CallOrUser, Call, User, None
}
Equivalence classes of instructions in the ARC Model.
enum ARCRuntimeEntryPointKind {
AutoreleaseRV, Release, Retain, RetainBlock,
Autorelease, StoreStrong, RetainRV, RetainAutorelease,
RetainAutoreleaseRV
}
enum DependenceKind {
NeedsPositiveRetainCount, AutoreleasePoolBoundary, CanChangeRetainCount, RetainAutoreleaseDep,
RetainAutoreleaseRVDep, RetainRVDep
}
Defines different dependence kinds among various ARC constructs.
enum ARCMDKindID { ImpreciseRelease, CopyOnEscape, NoObjCARCExceptions }
enum Sequence {
S_None, S_Retain, S_CanRelease, S_Use,
S_Stop, S_Release, S_MovableRelease
}
A sequence of states that a pointer may go through in which an objc_retain and objc_release are actually needed.
Functions
raw_ostream & operator<< (raw_ostream &OS, const ARCInstKind Class)
bool IsUser (ARCInstKind Class)
Test if the given class is a kind of user.
bool IsRetain (ARCInstKind Class)
Test if the given class is objc_retain or equivalent.
bool IsAutorelease (ARCInstKind Class)
Test if the given class is objc_autorelease or equivalent.
bool IsForwarding (ARCInstKind Class)
Test if the given class represents instructions which return their argument verbatim.
bool IsNoopOnNull (ARCInstKind Class)
Test if the given class represents instructions which do nothing if passed a null pointer.
bool IsAlwaysTail (ARCInstKind Class)
Test if the given class represents instructions which are always safe to mark with the "tail" keyword.
bool IsNeverTail (ARCInstKind Class)
Test if the given class represents instructions which are never safe to mark with the "tail" keyword.
bool IsNoThrow (ARCInstKind Class)
Test if the given class represents instructions which are always safe to mark with the nounwind attribute.
bool CanInterruptRV (ARCInstKind Class)
Test whether the given instruction can autorelease any pointer or cause an autoreleasepool pop.
ARCInstKind GetFunctionClass (const Function *F)
Determine if F is one of the special known Functions.
static ARCInstKind GetBasicARCInstKind (const Value *V)
Determine which objc runtime call instruction class V belongs to.
ARCInstKind GetARCInstKind (const Value *V)
Map V to its ARCInstKind equivalence class.
bool CanDecrementRefCount (ARCInstKind Kind)
Returns false if conservatively we can prove that any instruction mapped to this kind can not decrement ref counts.
void FindDependencies (DependenceKind Flavor, const Value *Arg, BasicBlock *StartBB, Instruction *StartInst, SmallPtrSetImpl< Instruction * > &DependingInstructions, SmallPtrSetImpl< const BasicBlock * > &Visited, ProvenanceAnalysis &PA)
Walk up the CFG from StartPos (which is in StartBB) and find local and non-local dependencies on Arg.
bool Depends (DependenceKind Flavor, Instruction *Inst, const Value *Arg, ProvenanceAnalysis &PA)
Test if there can be dependencies on Inst through Arg.
bool CanUse (const Instruction *Inst, const Value *Ptr, ProvenanceAnalysis &PA, ARCInstKind Class)
Test whether the given instruction can "use" the given pointer's object in a way that requires the reference count to be positive.
bool CanAlterRefCount (const Instruction *Inst, const Value *Ptr, ProvenanceAnalysis &PA, ARCInstKind Class)
Test whether the given instruction can result in a reference count modification (positive or negative) for the pointer's object.
bool CanDecrementRefCount (const Instruction *Inst, const Value *Ptr, ProvenanceAnalysis &PA, ARCInstKind Class)
Returns true if we can not conservatively prove that Inst can not decrement the reference count of Ptr.
static bool CanDecrementRefCount (const Instruction *Inst, const Value *Ptr, ProvenanceAnalysis &PA)
static bool ModuleHasARC (const Module &M)
Test if the given module looks interesting to run ARC optimization on.
static const Value * GetUnderlyingObjCPtr (const Value *V, const DataLayout &DL)
This is a wrapper around getUnderlyingObject which also knows how to look through objc_retain and objc_autorelease calls, which we know to return their argument verbatim.
static const Value * GetRCIdentityRoot (const Value *V)
The RCIdentity root of a value V is a dominating value U for which retaining or releasing U is equivalent to retaining or releasing V.
static Value * GetRCIdentityRoot (Value *V)
Helper which calls const Value *GetRCIdentityRoot(const Value *V) and just casts away the const of the result.
static Value * GetArgRCIdentityRoot (Value *Inst)
Assuming the given instruction is one of the special calls such as objc_retain or objc_release, return the RCIdentity root of the argument of the call.
static bool IsNullOrUndef (const Value *V)
static bool IsNoopInstruction (const Instruction *I)
static void EraseInstruction (Instruction *CI)
Erase the given instruction.
static bool IsPotentialRetainableObjPtr (const Value *Op)
Test whether the given value is possible a retainable object pointer.
static bool IsPotentialRetainableObjPtr (const Value *Op, AliasAnalysis &AA)
static ARCInstKind GetCallSiteClass (ImmutableCallSite CS)
Helper for GetARCInstKind.
static bool IsObjCIdentifiedObject (const Value *V)
Return true if this value refers to a distinct and identifiable object.
raw_ostream & operator<< (raw_ostream &OS, const Sequence S) LLVM_ATTRIBUTE_UNUSED
Variables
bool EnableARCOpts
A handy option to enable/disable all ARC Optimizations.
Enumeration Type Documentation
enum llvm::objcarc::ARCInstKind
Equivalence classes of instructions in the ARC Model.
Since we do not have "instructions" to represent ARC concepts in LLVM IR, we instead operate on equivalence classes of instructions.
TODO: This should be split into two enums: a runtime entry point enum (possibly united with the ARCRuntimeEntrypoint class) and an enum that deals with effects of instructions in the ARC model (which would handle the notion of a User or CallOrUser).
Enumerator:
Retain
objc_retain
RetainRV
objc_retainAutoreleasedReturnValue
RetainBlock
objc_retainBlock
Release
objc_release
Autorelease
objc_autorelease
AutoreleaseRV
objc_autoreleaseReturnValue
AutoreleasepoolPush
objc_autoreleasePoolPush
AutoreleasepoolPop
objc_autoreleasePoolPop
NoopCast
objc_retainedObject, etc.
FusedRetainAutorelease
objc_retainAutorelease
FusedRetainAutoreleaseRV
objc_retainAutoreleaseReturnValue
LoadWeakRetained
objc_loadWeakRetained (primitive)
StoreWeak
objc_storeWeak (primitive)
InitWeak
objc_initWeak (derived)
LoadWeak
objc_loadWeak (derived)
MoveWeak
objc_moveWeak (derived)
CopyWeak
objc_copyWeak (derived)
DestroyWeak
objc_destroyWeak (derived)
StoreStrong
objc_storeStrong (derived)
IntrinsicUser
clang.arc.use
CallOrUser
could call objc_release and/or "use" pointers
Call
could call objc_release
User
could "use" a pointer
None
anything that is inert from an ARC perspective.
Definition at line 30 of file ARCInstKind.h.
enum llvm::objcarc::ARCMDKindID
Enumerator:
ImpreciseRelease
CopyOnEscape
NoObjCARCExceptions
Definition at line 262 of file lib/Transforms/ObjCARC/ObjCARC.h.
enum llvm::objcarc::ARCRuntimeEntryPointKind
Enumerator:
AutoreleaseRV
objc_autoreleaseReturnValue
Release
objc_release
Retain
objc_retain
RetainBlock
objc_retainBlock
Autorelease
objc_autorelease
StoreStrong
objc_storeStrong (derived)
RetainRV
objc_retainAutoreleasedReturnValue
RetainAutorelease
RetainAutoreleaseRV
Definition at line 30 of file ARCRuntimeEntryPoints.h.
enum llvm::objcarc::DependenceKind
Defines different dependence kinds among various ARC constructs.
There are several kinds of dependence-like concepts in use here.
Enumerator:
NeedsPositiveRetainCount
AutoreleasePoolBoundary
CanChangeRetainCount
RetainAutoreleaseDep
Blocks objc_retainAutorelease.
RetainAutoreleaseRVDep
Blocks objc_retainAutoreleaseReturnValue.
RetainRVDep
Blocks objc_retainAutoreleasedReturnValue.
Definition at line 44 of file DependencyAnalysis.h.
enum llvm::objcarc::Sequence
A sequence of states that a pointer may go through in which an objc_retain and objc_release are actually needed.
Enumerator:
S_None
S_Retain
objc_retain(x).
S_CanRelease
foo(x) -- x could possibly see a ref count decrement.
S_Use
any use of x.
S_Stop
like S_Release, but code motion is stopped.
S_Release
objc_release(x).
S_MovableRelease
objc_release(x), !clang.imprecise_release.
Definition at line 37 of file PtrState.h.
Function Documentation
bool llvm::objcarc::CanAlterRefCount (const Instruction * Inst, const Value * Ptr, ProvenanceAnalysis & PA, ARCInstKind Class)
Test whether the given instruction can result in a reference count modification (positive or negative) for the pointer's object.
Definition at line 35 of file DependencyAnalysis.cpp.
References llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_begin(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_end(), Autorelease, AutoreleaseRV, llvm::CS, llvm::DL, llvm::objcarc::ProvenanceAnalysis::getAA(), llvm::Module::getDataLayout(), llvm::AliasAnalysis::getModRefBehavior(), llvm::Instruction::getModule(), I, IntrinsicUser, IsPotentialRetainableObjPtr(), llvm::AliasAnalysis::onlyAccessesArgPointees(), llvm::AliasAnalysis::onlyReadsMemory(), llvm::objcarc::ProvenanceAnalysis::related(), and User.
Referenced by CanDecrementRefCount(), Depends(), llvm::objcarc::BottomUpPtrState::HandlePotentialAlterRefCount(), and llvm::objcarc::TopDownPtrState::HandlePotentialAlterRefCount().
bool llvm::objcarc::CanDecrementRefCount (const Instruction * Inst, const Value * Ptr, ProvenanceAnalysis & PA, ARCInstKind Class)
Returns true if we can not conservatively prove that Inst can not decrement the reference count of Ptr.
Returns false if we can.
Definition at line 71 of file DependencyAnalysis.cpp.
References CanAlterRefCount(), and CanDecrementRefCount().
static bool llvm::objcarc::CanDecrementRefCount (const Instruction * Inst, const Value * Ptr, ProvenanceAnalysis & PA) [inline, static]
Definition at line 79 of file DependencyAnalysis.h.
References CanDecrementRefCount(), and GetARCInstKind().
bool llvm::objcarc::CanDecrementRefCount (ARCInstKind Kind)
Returns false if conservatively we can prove that any instruction mapped to this kind can not decrement ref counts.
Returns true otherwise.
Definition at line 637 of file ARCInstKind.cpp.
References Autorelease, AutoreleasepoolPop, AutoreleasepoolPush, AutoreleaseRV, llvm::Call, CallOrUser, CopyWeak, DestroyWeak, FusedRetainAutorelease, FusedRetainAutoreleaseRV, InitWeak, IntrinsicUser, llvm_unreachable, LoadWeak, LoadWeakRetained, MoveWeak, llvm::None, NoopCast, llvm::Release, Retain, RetainBlock, RetainRV, StoreStrong, StoreWeak, and User.
Referenced by CanDecrementRefCount(), and findRetainForStoreStrongContraction().
bool llvm::objcarc::CanInterruptRV (ARCInstKind Class)
Test whether the given instruction can autorelease any pointer or cause an autoreleasepool pop.
This means that it *could* interrupt the RV optimization.
Definition at line 605 of file ARCInstKind.cpp.
References Autorelease, AutoreleasepoolPop, AutoreleasepoolPush, AutoreleaseRV, llvm::Call, CallOrUser, CopyWeak, DestroyWeak, FusedRetainAutorelease, FusedRetainAutoreleaseRV, InitWeak, IntrinsicUser, llvm_unreachable, LoadWeak, LoadWeakRetained, MoveWeak, llvm::None, NoopCast, llvm::Release, Retain, RetainBlock, RetainRV, StoreStrong, StoreWeak, and User.
Referenced by Depends().
bool llvm::objcarc::CanUse (const Instruction * Inst, const Value * Ptr, ProvenanceAnalysis & PA, ARCInstKind Class)
Test whether the given instruction can "use" the given pointer's object in a way that requires the reference count to be positive.
Definition at line 85 of file DependencyAnalysis.cpp.
References llvm::Call, llvm::CS, llvm::DL, llvm::objcarc::ProvenanceAnalysis::getAA(), llvm::Module::getDataLayout(), llvm::Instruction::getModule(), GetUnderlyingObjCPtr(), IsPotentialRetainableObjPtr(), llvm::User::op_begin(), llvm::User::op_end(), llvm::objcarc::ProvenanceAnalysis::related(), and llvm::SI.
Referenced by Depends(), findSafeStoreForStoreStrongContraction(), llvm::objcarc::BottomUpPtrState::HandlePotentialUse(), and llvm::objcarc::TopDownPtrState::HandlePotentialUse().
bool llvm::objcarc::Depends (DependenceKind Flavor, Instruction * Inst, const Value * Arg, ProvenanceAnalysis & PA)
Test if there can be dependencies on Inst through Arg.
This function only tests dependencies relevant for removing pairs of calls.
Definition at line 135 of file DependencyAnalysis.cpp.
References AutoreleasePoolBoundary, AutoreleasepoolPop, AutoreleasepoolPush, CanAlterRefCount(), CanChangeRetainCount, CanInterruptRV(), CanUse(), llvm::Class, GetARCInstKind(), GetArgRCIdentityRoot(), GetBasicARCInstKind(), llvm_unreachable, NeedsPositiveRetainCount, llvm::None, Retain, RetainAutoreleaseDep, RetainAutoreleaseRVDep, RetainRV, and RetainRVDep.
Referenced by FindDependencies().
static void llvm::objcarc::EraseInstruction (Instruction * CI) [inline, static]
Erase the given instruction.
Many ObjC calls return their argument verbatim, so if it's such a call and the return value has users, replace them with the argument value.
Definition at line 145 of file lib/Transforms/ObjCARC/ObjCARC.h.
References llvm::Instruction::eraseFromParent(), GetBasicARCInstKind(), IsForwarding(), IsNoopOnNull(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), llvm::Value::replaceAllUsesWith(), and llvm::Value::use_empty().
void llvm::objcarc::FindDependencies (DependenceKind Flavor, const Value * Arg, BasicBlock * StartBB, Instruction * StartInst, SmallPtrSetImpl< Instruction * > & DependingInsts, SmallPtrSetImpl< const BasicBlock * > & Visited, ProvenanceAnalysis & PA)
Walk up the CFG from StartPos (which is in StartBB) and find local and non-local dependencies on Arg.
TODO: Cache results?
Definition at line 223 of file DependencyAnalysis.cpp.
References llvm::BasicBlock::begin(), Depends(), llvm::SmallVectorBase::empty(), llvm::BasicBlock::end(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), and llvm::SI.
Referenced by FindPredecessorAutoreleaseWithSafePath(), FindPredecessorRetainWithSafePath(), and HasSafePathToPredecessorCall().
ARCInstKind llvm::objcarc::GetARCInstKind (const Value * V)
Map V to its ARCInstKind equivalence class.
Determine what kind of construct V is.
Definition at line 226 of file ARCInstKind.cpp.
References llvm::Alloca, llvm::APIntOps::And(), llvm::Call, CallOrUser, llvm::Class, ExtractElement(), llvm::ExtractValue, F(), llvm::FCmp, llvm::FPExt, llvm::FPToSI, llvm::CallInst::getCalledFunction(), GetCallSiteClass(), GetFunctionClass(), I, llvm::InsertElement, llvm::IntToPtr, isInertIntrinsic(), IsPotentialRetainableObjPtr(), isUseOnlyIntrinsic(), llvm::LShr, llvm::None, llvm::APIntOps::Or(), llvm::TargetOpcode::PHI, llvm::MipsISD::Ret, llvm::MCID::Select, llvm::SExt, llvm::SIToFP, llvm::Trunc, User, llvm::VAArg, and llvm::APIntOps::Xor().
Referenced by CanDecrementRefCount(), and Depends().
static Value* llvm::objcarc::GetArgRCIdentityRoot (Value * Inst) [inline, static]
Assuming the given instruction is one of the special calls such as objc_retain or objc_release, return the RCIdentity root of the argument of the call.
Definition at line 124 of file lib/Transforms/ObjCARC/ObjCARC.h.
References GetRCIdentityRoot().
Referenced by Depends(), FindPredecessorAutoreleaseWithSafePath(), FindPredecessorRetainWithSafePath(), and findRetainForStoreStrongContraction().
static ARCInstKind llvm::objcarc::GetBasicARCInstKind (const Value * V) [inline, static]
Determine which objc runtime call instruction class V belongs to.
This is similar to GetARCInstKind except that it only detects objc runtime calls. This allows it to be faster.
Definition at line 101 of file ARCInstKind.h.
References CallOrUser, F(), GetFunctionClass(), and User.
Referenced by Depends(), EraseInstruction(), FindPredecessorAutoreleaseWithSafePath(), FindPredecessorRetainWithSafePath(), findRetainForStoreStrongContraction(), findSafeStoreForStoreStrongContraction(), FindSingleUseIdentifiedObject(), GetRCIdentityRoot(), GetUnderlyingObjCPtr(), and HasSafePathToPredecessorCall().
static ARCInstKind llvm::objcarc::GetCallSiteClass (ImmutableCallSite CS) [inline, static]
Helper for GetARCInstKind.
Determines what kind of construct CS is.
Definition at line 212 of file lib/Transforms/ObjCARC/ObjCARC.h.
References llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_begin(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_end(), Call, CallOrUser, I, IsPotentialRetainableObjPtr(), llvm::None, llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::onlyReadsMemory(), and User.
Referenced by GetARCInstKind().
ARCInstKind llvm::objcarc::GetFunctionClass (const Function * F)
Determine if F is one of the special known Functions.
If it isn't, return ARCInstKind::CallOrUser.
Definition at line 83 of file ARCInstKind.cpp.
References llvm::Function::arg_begin(), llvm::Function::arg_end(), Autorelease, AutoreleasepoolPop, AutoreleasepoolPush, AutoreleaseRV, CallOrUser, llvm::StringSwitch< T, R >::Case(), CopyWeak, llvm::StringSwitch< T, R >::Default(), DestroyWeak, FusedRetainAutorelease, FusedRetainAutoreleaseRV, llvm::Value::getName(), llvm::Value::getType(), InitWeak, IntrinsicUser, llvm::Type::isIntegerTy(), LoadWeak, LoadWeakRetained, MoveWeak, llvm::None, NoopCast, llvm::Release, Retain, RetainBlock, RetainRV, StoreStrong, StoreWeak, and User.
Referenced by GetARCInstKind(), and GetBasicARCInstKind().
static const Value* llvm::objcarc::GetRCIdentityRoot (const Value * V) [inline, static]
The RCIdentity root of a value V is a dominating value U for which retaining or releasing U is equivalent to retaining or releasing V.
In other words, ARC operations on V are equivalent to ARC operations on U.
We use this in the ARC optimizer to make it easier to match up ARC operations by always mapping ARC operations to RCIdentityRoots instead of pointers themselves.
The two ways that we see RCIdentical values in ObjC are via:
1. PointerCasts 2. Forwarding Calls that return their argument verbatim.
Thus this function strips off pointer casts and forwarding calls. *NOTE* This implies that two RCIdentical values must alias.
Definition at line 103 of file lib/Transforms/ObjCARC/ObjCARC.h.
References GetBasicARCInstKind(), IsForwarding(), and llvm::Value::stripPointerCasts().
Referenced by FindSingleUseIdentifiedObject(), GetArgRCIdentityRoot(), GetRCIdentityRoot(), and IsObjCIdentifiedObject().
static Value* llvm::objcarc::GetRCIdentityRoot (Value * V) [inline, static]
Helper which calls const Value *GetRCIdentityRoot(const Value *V) and just casts away the const of the result.
For documentation about what an RCIdentityRoot (and by extension GetRCIdentityRoot is) look at that function.
Definition at line 117 of file lib/Transforms/ObjCARC/ObjCARC.h.
References GetRCIdentityRoot().
static const Value* llvm::objcarc::GetUnderlyingObjCPtr (const Value * V, const DataLayout & DL) [inline, static]
This is a wrapper around getUnderlyingObject which also knows how to look through objc_retain and objc_autorelease calls, which we know to return their argument verbatim.
Definition at line 76 of file lib/Transforms/ObjCARC/ObjCARC.h.
References GetBasicARCInstKind(), llvm::GetUnderlyingObject(), and IsForwarding().
Referenced by AreAnyUnderlyingObjectsAnAlloca(), and CanUse().
bool llvm::objcarc::IsAlwaysTail (ARCInstKind Class)
Test if the given class represents instructions which are always safe to mark with the "tail" keyword.
Definition at line 494 of file ARCInstKind.cpp.
References Autorelease, AutoreleasepoolPop, AutoreleasepoolPush, AutoreleaseRV, llvm::Call, CallOrUser, CopyWeak, DestroyWeak, FusedRetainAutorelease, FusedRetainAutoreleaseRV, InitWeak, IntrinsicUser, llvm_unreachable, LoadWeak, LoadWeakRetained, MoveWeak, llvm::None, NoopCast, llvm::Release, Retain, RetainBlock, RetainRV, StoreStrong, StoreWeak, and User.
bool llvm::objcarc::IsAutorelease (ARCInstKind Class)
Test if the given class is objc_autorelease or equivalent.
Definition at line 392 of file ARCInstKind.cpp.
References Autorelease, AutoreleasepoolPop, AutoreleasepoolPush, AutoreleaseRV, llvm::Call, CallOrUser, CopyWeak, DestroyWeak, FusedRetainAutorelease, FusedRetainAutoreleaseRV, InitWeak, IntrinsicUser, llvm_unreachable, LoadWeak, LoadWeakRetained, MoveWeak, llvm::None, NoopCast, llvm::Release, Retain, RetainBlock, RetainRV, StoreStrong, StoreWeak, and User.
Referenced by FindPredecessorAutoreleaseWithSafePath().
bool llvm::objcarc::IsForwarding (ARCInstKind Class)
Test if the given class represents instructions which return their argument verbatim.
Definition at line 426 of file ARCInstKind.cpp.
References Autorelease, AutoreleasepoolPop, AutoreleasepoolPush, AutoreleaseRV, llvm::Call, CallOrUser, CopyWeak, DestroyWeak, FusedRetainAutorelease, FusedRetainAutoreleaseRV, InitWeak, IntrinsicUser, llvm_unreachable, LoadWeak, LoadWeakRetained, MoveWeak, llvm::None, NoopCast, llvm::Release, Retain, RetainBlock, RetainRV, StoreStrong, StoreWeak, and User.
Referenced by EraseInstruction(), FindSingleUseIdentifiedObject(), GetRCIdentityRoot(), and GetUnderlyingObjCPtr().
bool llvm::objcarc::IsNeverTail (ARCInstKind Class)
Test if the given class represents instructions which are never safe to mark with the "tail" keyword.
It is never safe to tail call objc_autorelease since by tail calling objc_autorelease: fast autoreleasing causing our object to be potentially reclaimed from the autorelease pool which violates the semantics of __autoreleasing types in ARC.
Definition at line 529 of file ARCInstKind.cpp.
References Autorelease, AutoreleasepoolPop, AutoreleasepoolPush, AutoreleaseRV, llvm::Call, CallOrUser, CopyWeak, DestroyWeak, FusedRetainAutorelease, FusedRetainAutoreleaseRV, InitWeak, IntrinsicUser, llvm_unreachable, LoadWeak, LoadWeakRetained, MoveWeak, llvm::None, NoopCast, llvm::Release, Retain, RetainBlock, RetainRV, StoreStrong, StoreWeak, and User.
static bool llvm::objcarc::IsNoopInstruction (const Instruction * I) [inline, static]
Definition at line 132 of file lib/Transforms/ObjCARC/ObjCARC.h.
References I.
bool llvm::objcarc::IsNoopOnNull (ARCInstKind Class)
Test if the given class represents instructions which do nothing if passed a null pointer.
Definition at line 460 of file ARCInstKind.cpp.
References Autorelease, AutoreleasepoolPop, AutoreleasepoolPush, AutoreleaseRV, llvm::Call, CallOrUser, CopyWeak, DestroyWeak, FusedRetainAutorelease, FusedRetainAutoreleaseRV, InitWeak, IntrinsicUser, llvm_unreachable, LoadWeak, LoadWeakRetained, MoveWeak, llvm::None, NoopCast, llvm::Release, Retain, RetainBlock, RetainRV, StoreStrong, StoreWeak, and User.
Referenced by EraseInstruction().
bool llvm::objcarc::IsNoThrow (ARCInstKind Class)
Test if the given class represents instructions which are always safe to mark with the nounwind attribute.
Definition at line 567 of file ARCInstKind.cpp.
References Autorelease, AutoreleasepoolPop, AutoreleasepoolPush, AutoreleaseRV, llvm::Call, CallOrUser, CopyWeak, DestroyWeak, FusedRetainAutorelease, FusedRetainAutoreleaseRV, InitWeak, IntrinsicUser, llvm_unreachable, LoadWeak, LoadWeakRetained, MoveWeak, llvm::None, NoopCast, llvm::Release, Retain, RetainBlock, RetainRV, StoreStrong, StoreWeak, and User.
static bool llvm::objcarc::IsNullOrUndef (const Value * V) [inline, static]
Definition at line 128 of file lib/Transforms/ObjCARC/ObjCARC.h.
static bool llvm::objcarc::IsObjCIdentifiedObject (const Value * V) [inline, static]
Return true if this value refers to a distinct and identifiable object.
This is similar to AliasAnalysis's isIdentifiedObject, except that it uses special knowledge of ObjC conventions.
Definition at line 226 of file lib/Transforms/ObjCARC/ObjCARC.h.
References llvm::StringRef::find(), GetRCIdentityRoot(), llvm::StringRef::npos, llvm::ARMBuildAttrs::Section, and llvm::StringRef::startswith().
Referenced by FindSingleUseIdentifiedObject().
static bool llvm::objcarc::IsPotentialRetainableObjPtr (const Value * Op) [inline, static]
Test whether the given value is possible a retainable object pointer.
Definition at line 166 of file lib/Transforms/ObjCARC/ObjCARC.h.
References llvm::dyn_cast(), and llvm::Value::getType().
Referenced by CanAlterRefCount(), CanUse(), GetARCInstKind(), GetCallSiteClass(), and IsPotentialRetainableObjPtr().
static bool llvm::objcarc::IsPotentialRetainableObjPtr (const Value * Op, AliasAnalysis & AA) [inline, static]
Definition at line 191 of file lib/Transforms/ObjCARC/ObjCARC.h.
References IsPotentialRetainableObjPtr(), and llvm::AliasAnalysis::pointsToConstantMemory().
bool llvm::objcarc::IsRetain (ARCInstKind Class)
Test if the given class is objc_retain or equivalent.
Definition at line 357 of file ARCInstKind.cpp.
References Autorelease, AutoreleasepoolPop, AutoreleasepoolPush, AutoreleaseRV, llvm::Call, CallOrUser, CopyWeak, DestroyWeak, FusedRetainAutorelease, FusedRetainAutoreleaseRV, InitWeak, IntrinsicUser, llvm_unreachable, LoadWeak, LoadWeakRetained, MoveWeak, llvm::None, NoopCast, llvm::Release, Retain, RetainBlock, RetainRV, StoreStrong, StoreWeak, and User.
Referenced by FindPredecessorRetainWithSafePath(), and findSafeStoreForStoreStrongContraction().
bool llvm::objcarc::IsUser (ARCInstKind Class)
Test if the given class is a kind of user.
Definition at line 324 of file ARCInstKind.cpp.
References Autorelease, AutoreleasepoolPop, AutoreleasepoolPush, AutoreleaseRV, llvm::Call, CallOrUser, CopyWeak, DestroyWeak, FusedRetainAutorelease, FusedRetainAutoreleaseRV, InitWeak, IntrinsicUser, llvm_unreachable, LoadWeak, LoadWeakRetained, MoveWeak, llvm::None, NoopCast, llvm::Release, Retain, RetainBlock, RetainRV, StoreStrong, StoreWeak, and User.
Referenced by llvm::objcarc::BottomUpPtrState::HandlePotentialUse().
static bool llvm::objcarc::ModuleHasARC (const Module & M) [inline, static]
Test if the given module looks interesting to run ARC optimization on.
Definition at line 51 of file lib/Transforms/ObjCARC/ObjCARC.h.
References llvm::Module::getNamedValue().
raw_ostream & llvm::objcarc::operator<< (raw_ostream & OS, const Sequence S)
Definition at line 25 of file PtrState.cpp.
References llvm_unreachable, S_CanRelease, S_MovableRelease, S_None, S_Release, S_Retain, S_Stop, and S_Use.
raw_ostream & llvm::objcarc::operator<< (raw_ostream & OS, const ARCInstKind Class)
Definition at line 28 of file ARCInstKind.cpp.
References Autorelease, AutoreleasepoolPop, AutoreleasepoolPush, AutoreleaseRV, llvm::Call, CallOrUser, CopyWeak, DestroyWeak, FusedRetainAutorelease, FusedRetainAutoreleaseRV, InitWeak, IntrinsicUser, llvm_unreachable, LoadWeak, LoadWeakRetained, MoveWeak, llvm::None, NoopCast, llvm::Release, Retain, RetainBlock, RetainRV, StoreStrong, StoreWeak, and User.
Variable Documentation
bool llvm::objcarc::EnableARCOpts
A handy option to enable/disable all ARC Optimizations.
Definition at line 30 of file ObjCARC.cpp.