LLVM: llvm::ARM_MC Namespace Reference
llvm::ARM_MC Namespace Reference
Functions
std::string ParseARMTriple (const Triple &TT, StringRef CPU)
MCSubtargetInfo * createARMMCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
Create a ARM MCSubtargetInfo instance.
Function Documentation
MCSubtargetInfo * llvm::ARM_MC::createARMMCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS)
Create a ARM MCSubtargetInfo instance.
This is exposed so Asm parser, etc. do not need to go through TargetRegistry.
Definition at line 250 of file ARMMCTargetDesc.cpp.
References llvm::StringRef::empty(), llvm::FS, ParseARMTriple(), and X.
Referenced by LLVMInitializeARMTargetMC().
std::string llvm::ARM_MC::ParseARMTriple (const Triple & TT, StringRef CPU)
Definition at line 133 of file ARMMCTargetDesc.cpp.
References llvm::Triple::ARMSubArch_v4t, llvm::Triple::ARMSubArch_v5, llvm::Triple::ARMSubArch_v5te, llvm::Triple::ARMSubArch_v6, llvm::Triple::ARMSubArch_v6k, llvm::Triple::ARMSubArch_v6m, llvm::Triple::ARMSubArch_v6t2, llvm::Triple::ARMSubArch_v7, llvm::Triple::ARMSubArch_v7em, llvm::Triple::ARMSubArch_v7m, llvm::Triple::ARMSubArch_v7s, llvm::Triple::ARMSubArch_v8, llvm::Triple::ARMSubArch_v8_1a, llvm::StringRef::empty(), llvm::Triple::getArch(), llvm::Triple::getSubArch(), llvm::Triple::isOSNaCl(), isThumb(), llvm_unreachable, llvm::Triple::NoSubArch, llvm::Triple::thumb, and llvm::Triple::thumbeb.
Referenced by createARMMCSubtargetInfo().