LLVM: llvm::object::ArchiveMemberHeader Struct Reference
llvm::object::ArchiveMemberHeader Struct Reference
#include <Archive.h>
Public Member Functions
llvm::StringRef getName () const
Get the name without looking up long names.
uint32_t getSize () const
Members are not larger than 4GB.
sys::fs::perms getAccessMode () const
sys::TimeValue getLastModified () const
llvm::StringRef getRawLastModified () const
unsigned getUID () const
unsigned getGID () const
Public Attributes
char Name [16]
char LastModified [12]
char UID [6]
char GID [6]
char AccessMode [8]
char Size [10]
Size of data, not including header or padding.
char Terminator [2]
Detailed Description
Definition at line 27 of file Archive.h.
Member Function Documentation
sys::fs::perms ArchiveMemberHeader::getAccessMode () const
Definition at line 52 of file Archive.cpp.
References llvm_unreachable, and llvm::MipsISD::Ret.
Referenced by llvm::object::Archive::Child::getAccessMode().
unsigned ArchiveMemberHeader::getGID () const
Definition at line 77 of file Archive.cpp.
References llvm_unreachable, and llvm::MipsISD::Ret.
Referenced by llvm::object::Archive::Child::getGID().
sys::TimeValue ArchiveMemberHeader::getLastModified () const
Definition at line 59 of file Archive.cpp.
References llvm::sys::TimeValue::fromEpochTime(), llvm_unreachable, and llvm::MipsISD::Ret.
Referenced by llvm::object::Archive::Child::getLastModified().
StringRef ArchiveMemberHeader::getName () const
Get the name without looking up long names.
Definition at line 30 of file Archive.cpp.
References llvm::sys::path::end(), llvm::StringRef::find(), and llvm::StringRef::npos.
Referenced by llvm::object::Archive::Child::Child(), and llvm::object::Archive::Child::getRawName().
llvm::StringRef llvm::object::ArchiveMemberHeader::getRawLastModified () const [inline]
Definition at line 44 of file Archive.h.
References LastModified, and llvm::StringRef::rtrim().
Referenced by llvm::object::Archive::Child::getRawLastModified().
uint32_t ArchiveMemberHeader::getSize () const
Members are not larger than 4GB.
Definition at line 45 of file Archive.cpp.
References llvm_unreachable, and llvm::MipsISD::Ret.
Referenced by llvm::object::Archive::Child::Child().
unsigned ArchiveMemberHeader::getUID () const
Definition at line 70 of file Archive.cpp.
References llvm_unreachable, and llvm::MipsISD::Ret.
Referenced by llvm::object::Archive::Child::getUID().
Member Data Documentation
char llvm::object::ArchiveMemberHeader::AccessMode[8]
Definition at line 32 of file Archive.h.
char llvm::object::ArchiveMemberHeader::GID[6]
Definition at line 31 of file Archive.h.
char llvm::object::ArchiveMemberHeader::LastModified[12]
Definition at line 29 of file Archive.h.
Referenced by getRawLastModified().
char llvm::object::ArchiveMemberHeader::Name[16]
Definition at line 28 of file Archive.h.
char llvm::object::ArchiveMemberHeader::Size[10]
Size of data, not including header or padding.
Definition at line 33 of file Archive.h.
char llvm::object::ArchiveMemberHeader::Terminator[2]
Definition at line 34 of file Archive.h.
char llvm::object::ArchiveMemberHeader::UID[6]
Definition at line 30 of file Archive.h.
The documentation for this struct was generated from the following files:
Archive.h
Archive.cpp