LLVM: llvm::MDNodeKeyImpl< DILexicalBlock > Struct Template Reference
llvm::MDNodeKeyImpl< DILexicalBlock > Struct Template Reference
#include <LLVMContextImpl.h>
Public Member Functions
MDNodeKeyImpl (Metadata *Scope, Metadata *File, unsigned Line, unsigned Column)
MDNodeKeyImpl (const DILexicalBlock *N)
bool isKeyOf (const DILexicalBlock *RHS) const
unsigned getHashValue () const
Public Attributes
Metadata * Scope
Metadata * File
unsigned Line
unsigned Column
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DILexicalBlock >
Definition at line 592 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
llvm::MDNodeKeyImpl< DILexicalBlock >::MDNodeKeyImpl (Metadata * Scope, Metadata * File, unsigned Line, unsigned Column) [inline]
Definition at line 598 of file LLVMContextImpl.h.
llvm::MDNodeKeyImpl< DILexicalBlock >::MDNodeKeyImpl (const DILexicalBlock * N) [inline]
Definition at line 600 of file LLVMContextImpl.h.
Member Function Documentation
unsigned llvm::MDNodeKeyImpl< DILexicalBlock >::getHashValue () const [inline]
Definition at line 608 of file LLVMContextImpl.h.
References llvm::ARMBuildAttrs::File, and llvm::hash_combine().
bool llvm::MDNodeKeyImpl< DILexicalBlock >::isKeyOf (const DILexicalBlock * RHS) const [inline]
Definition at line 604 of file LLVMContextImpl.h.
References llvm::ARMBuildAttrs::File, llvm::DILexicalBlock::getColumn(), llvm::DILexicalBlock::getLine(), llvm::DIScope::getRawFile(), and llvm::DILexicalBlockBase::getRawScope().
Member Data Documentation
unsigned llvm::MDNodeKeyImpl< DILexicalBlock >::Column
Definition at line 596 of file LLVMContextImpl.h.
Metadata* llvm::MDNodeKeyImpl< DILexicalBlock >::File
Definition at line 594 of file LLVMContextImpl.h.
unsigned llvm::MDNodeKeyImpl< DILexicalBlock >::Line
Definition at line 595 of file LLVMContextImpl.h.
Metadata* llvm::MDNodeKeyImpl< DILexicalBlock >::Scope
Definition at line 593 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
LLVMContextImpl.h