LLVM: llvm::MDNodeKeyImpl< DINamespace > Struct Template Reference
llvm::MDNodeKeyImpl< DINamespace > Struct Template Reference
#include <LLVMContextImpl.h>
Public Member Functions
MDNodeKeyImpl (Metadata *Scope, Metadata *File, StringRef Name, unsigned Line)
MDNodeKeyImpl (const DINamespace *N)
bool isKeyOf (const DINamespace *RHS) const
unsigned getHashValue () const
Public Attributes
Metadata * Scope
Metadata * File
StringRef Name
unsigned Line
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DINamespace >
Definition at line 633 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
llvm::MDNodeKeyImpl< DINamespace >::MDNodeKeyImpl (Metadata * Scope, Metadata * File, StringRef Name, unsigned Line) [inline]
Definition at line 639 of file LLVMContextImpl.h.
llvm::MDNodeKeyImpl< DINamespace >::MDNodeKeyImpl (const DINamespace * N) [inline]
Definition at line 641 of file LLVMContextImpl.h.
Member Function Documentation
unsigned llvm::MDNodeKeyImpl< DINamespace >::getHashValue () const [inline]
Definition at line 649 of file LLVMContextImpl.h.
References llvm::ARMBuildAttrs::File, and llvm::hash_combine().
bool llvm::MDNodeKeyImpl< DINamespace >::isKeyOf (const DINamespace * RHS) const [inline]
Definition at line 645 of file LLVMContextImpl.h.
References llvm::ARMBuildAttrs::File, llvm::DINamespace::getLine(), llvm::DINamespace::getName(), llvm::DIScope::getRawFile(), and llvm::DINamespace::getRawScope().
Member Data Documentation
Metadata* llvm::MDNodeKeyImpl< DINamespace >::File
Definition at line 635 of file LLVMContextImpl.h.
unsigned llvm::MDNodeKeyImpl< DINamespace >::Line
Definition at line 637 of file LLVMContextImpl.h.
StringRef llvm::MDNodeKeyImpl< DINamespace >::Name
Definition at line 636 of file LLVMContextImpl.h.
Metadata* llvm::MDNodeKeyImpl< DINamespace >::Scope
Definition at line 634 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
LLVMContextImpl.h