LLVM: llvm::MDNodeKeyImpl< DIFile > Struct Template Reference
llvm::MDNodeKeyImpl< DIFile > Struct Template Reference
#include <LLVMContextImpl.h>
Public Member Functions
MDNodeKeyImpl (StringRef Filename, StringRef Directory)
MDNodeKeyImpl (const DIFile *N)
bool isKeyOf (const DIFile *RHS) const
unsigned getHashValue () const
Public Attributes
StringRef Filename
StringRef Directory
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DIFile >
Definition at line 446 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
llvm::MDNodeKeyImpl< DIFile >::MDNodeKeyImpl (StringRef Filename, StringRef Directory) [inline]
Definition at line 450 of file LLVMContextImpl.h.
llvm::MDNodeKeyImpl< DIFile >::MDNodeKeyImpl (const DIFile * N) [inline]
Definition at line 452 of file LLVMContextImpl.h.
Member Function Documentation
unsigned llvm::MDNodeKeyImpl< DIFile >::getHashValue () const [inline]
Definition at line 458 of file LLVMContextImpl.h.
References llvm::hash_combine().
bool llvm::MDNodeKeyImpl< DIFile >::isKeyOf (const DIFile * RHS) const [inline]
Definition at line 455 of file LLVMContextImpl.h.
References llvm::DIFile::getDirectory(), and llvm::DIFile::getFilename().
Member Data Documentation
StringRef llvm::MDNodeKeyImpl< DIFile >::Directory
Definition at line 448 of file LLVMContextImpl.h.
StringRef llvm::MDNodeKeyImpl< DIFile >::Filename
Definition at line 447 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
LLVMContextImpl.h