LLVM: llvm::ILPValue Struct Reference
llvm::ILPValue Struct Reference
Represent the ILP of the subDAG rooted at a DAG node.
#include <ScheduleDFS.h>
Public Member Functions
ILPValue (unsigned count, unsigned length)
bool operator< (ILPValue RHS) const
bool operator> (ILPValue RHS) const
bool operator<= (ILPValue RHS) const
bool operator>= (ILPValue RHS) const
void print (raw_ostream &OS) const
void dump () const
Public Attributes
unsigned InstrCount
unsigned Length
Length may either correspond to depth or height, depending on direction, and cycles or nodes depending on context.
Detailed Description
Represent the ILP of the subDAG rooted at a DAG node.
ILPValues summarize the DAG subtree rooted at each node. ILPValues are valid for all nodes regardless of their subtree membership.
When computed using bottom-up DFS, this metric assumes that the DAG is a forest of trees with roots at the bottom of the schedule branching upward.
Definition at line 35 of file ScheduleDFS.h.
Constructor & Destructor Documentation
llvm::ILPValue::ILPValue (unsigned count, unsigned length) [inline]
Definition at line 41 of file ScheduleDFS.h.
Member Function Documentation
LLVM_DUMP_METHOD void ILPValue::dump () const
Definition at line 1593 of file ScheduleDAGInstrs.cpp.
References llvm::dbgs().
bool llvm::ILPValue::operator< (ILPValue RHS) const [inline]
Definition at line 45 of file ScheduleDFS.h.
References InstrCount, and Length.
bool llvm::ILPValue::operator<= (ILPValue RHS) const [inline]
Definition at line 52 of file ScheduleDFS.h.
References InstrCount, and Length.
bool llvm::ILPValue::operator> (ILPValue RHS) const [inline]
Definition at line 49 of file ScheduleDFS.h.
bool llvm::ILPValue::operator>= (ILPValue RHS) const [inline]
Definition at line 56 of file ScheduleDFS.h.
LLVM_DUMP_METHOD void ILPValue::print (raw_ostream & OS) const
Definition at line 1584 of file ScheduleDAGInstrs.cpp.
References llvm::format(), InstrCount, and Length.
Referenced by llvm::operator<<().
Member Data Documentation
unsigned llvm::ILPValue::InstrCount
Definition at line 36 of file ScheduleDFS.h.
Referenced by operator<(), operator<=(), and print().
unsigned llvm::ILPValue::Length
Length may either correspond to depth or height, depending on direction, and cycles or nodes depending on context.
Definition at line 39 of file ScheduleDFS.h.
Referenced by operator<(), operator<=(), and print().
The documentation for this struct was generated from the following files:
ScheduleDFS.h
ScheduleDAGInstrs.cpp