LLVM: llvm::SCEVVisitor< SC, RetVal > Struct Template Reference
llvm::SCEVVisitor< SC, RetVal > Struct Template Reference
SCEVVisitor - This class defines a simple visitor class that may be used for various SCEV analysis purposes.
#include <ScalarEvolutionExpressions.h>
Public Member Functions
RetVal visit (const SCEV *S)
RetVal visitCouldNotCompute (const SCEVCouldNotCompute *S)
Detailed Description
template<typename SC, typename RetVal = void>
struct llvm::SCEVVisitor< SC, RetVal >
SCEVVisitor - This class defines a simple visitor class that may be used for various SCEV analysis purposes.
Definition at line 529 of file ScalarEvolutionExpressions.h.
Member Function Documentation
template<typename SC, typename RetVal = void> RetVal llvm::SCEVVisitor< SC, RetVal >::visit (const SCEV * S) [inline]
Definition at line 530 of file ScalarEvolutionExpressions.h.
Referenced by llvm::SCEVParameterRewriter::rewrite(), and llvm::SCEVApplyRewriter::rewrite().
template<typename SC, typename RetVal = void> RetVal llvm::SCEVVisitor< SC, RetVal >::visitCouldNotCompute (const SCEVCouldNotCompute * S) [inline]
Reimplemented in llvm::SCEVApplyRewriter, and llvm::SCEVParameterRewriter.
Definition at line 561 of file ScalarEvolutionExpressions.h.
Referenced by llvm::SCEVVisitor< SCEVExpander, Value * >::visit().
The documentation for this struct was generated from the following file:
ScalarEvolutionExpressions.h