LLVM: llvm::AArch64MCAsmInfoDarwin Struct Reference
llvm::AArch64MCAsmInfoDarwin Struct Reference
#include <AArch64MCAsmInfo.h>
Public Member Functions
AArch64MCAsmInfoDarwin ()
const MCExpr * getExprForPersonalitySymbol (const MCSymbol *Sym, unsigned Encoding, MCStreamer &Streamer) const override
Detailed Description
Definition at line 25 of file AArch64MCAsmInfo.h.
Constructor & Destructor Documentation
AArch64MCAsmInfoDarwin::AArch64MCAsmInfoDarwin () [explicit]
Definition at line 35 of file AArch64MCAsmInfo.cpp.
References llvm::MCAsmInfo::AlignmentIsInBytes, AsmWriterVariant, llvm::MCAsmInfo::AssemblerDialect, llvm::MCAsmInfo::CalleeSaveStackSlotSize, llvm::MCAsmInfo::CommentString, Default, llvm::DwarfCFI, llvm::MCAsmInfo::ExceptionsType, llvm::MCAsmInfo::PointerSize, llvm::MCAsmInfo::PrivateGlobalPrefix, llvm::MCAsmInfo::PrivateLabelPrefix, llvm::MCAsmInfo::SeparatorString, llvm::MCAsmInfo::SupportsDebugInformation, llvm::MCAsmInfo::UseDataRegionDirectives, llvm::MCAsmInfo::UseLogicalShr, and llvm::MCAsmInfo::UsesELFSectionDirectiveForBSS.
Member Function Documentation
const MCExpr * AArch64MCAsmInfoDarwin::getExprForPersonalitySymbol (const MCSymbol * Sym, unsigned Encoding, MCStreamer & Streamer) const [override, virtual]
Reimplemented from llvm::MCAsmInfo.
Definition at line 57 of file AArch64MCAsmInfo.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), llvm::MCContext::createTempSymbol(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::getContext(), and llvm::MCSymbolRefExpr::VK_GOT.
The documentation for this struct was generated from the following files:
AArch64MCAsmInfo.h
AArch64MCAsmInfo.cpp