LLVM: llvm::Linker::IdentifiedStructTypeSet Struct Reference
llvm::Linker::IdentifiedStructTypeSet Struct Reference
#include <Linker.h>
Public Member Functions
void addNonOpaque (StructType *Ty)
void switchToNonOpaque (StructType *Ty)
void addOpaque (StructType *Ty)
StructType * findNonOpaque (ArrayRef< Type * > ETypes, bool IsPacked)
bool hasType (StructType *Ty)
Public Attributes
OpaqueStructTypeSet OpaqueStructTypes
NonOpaqueStructTypeSet NonOpaqueStructTypes
Detailed Description
Definition at line 49 of file Linker/Linker.h.
Member Function Documentation
void Linker::IdentifiedStructTypeSet::addNonOpaque (StructType * Ty)
Definition at line 1693 of file LinkModules.cpp.
References llvm::StructType::isOpaque().
void Linker::IdentifiedStructTypeSet::addOpaque (StructType * Ty)
Definition at line 1706 of file LinkModules.cpp.
References llvm::StructType::isOpaque().
StructType * Linker::IdentifiedStructTypeSet::findNonOpaque (ArrayRef< Type * > ETypes, bool IsPacked)
Definition at line 1712 of file LinkModules.cpp.
References I.
bool Linker::IdentifiedStructTypeSet::hasType (StructType * Ty)
Definition at line 1721 of file LinkModules.cpp.
References I, and llvm::StructType::isOpaque().
void Linker::IdentifiedStructTypeSet::switchToNonOpaque (StructType * Ty)
Definition at line 1698 of file LinkModules.cpp.
References llvm::StructType::isOpaque().
Member Data Documentation
NonOpaqueStructTypeSet llvm::Linker::IdentifiedStructTypeSet::NonOpaqueStructTypes
Definition at line 54 of file Linker/Linker.h.
OpaqueStructTypeSet llvm::Linker::IdentifiedStructTypeSet::OpaqueStructTypes
Definition at line 51 of file Linker/Linker.h.
The documentation for this struct was generated from the following files:
Linker/Linker.h
LinkModules.cpp