LLVM: llvm::ThumbRegisterInfo Struct Reference
llvm::ThumbRegisterInfo Struct Reference
#include <ThumbRegisterInfo.h>
Public Member Functions
ThumbRegisterInfo ()
const TargetRegisterClass * getLargestLegalSuperClass (const TargetRegisterClass *RC, const MachineFunction &MF) const override
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind=0) const override
void emitLoadConstPool (MachineBasicBlock &MBB, MachineBasicBlock::iterator &MBBI, DebugLoc dl, unsigned DestReg, unsigned SubIdx, int Val, ARMCC::CondCodes Pred=ARMCC::AL, unsigned PredReg=0, unsigned MIFlags=MachineInstr::NoFlags) const override
emitLoadConstPool - Emits a load from constpool to materialize the specified immediate.
bool rewriteFrameIndex (MachineBasicBlock::iterator II, unsigned FrameRegIdx, unsigned FrameReg, int &Offset, const ARMBaseInstrInfo &TII) const
void resolveFrameIndex (MachineInstr &MI, unsigned BaseReg, int64_t Offset) const override
bool saveScavengerRegister (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, MachineBasicBlock::iterator &UseMI, const TargetRegisterClass *RC, unsigned Reg) const override
saveScavengerRegister - Spill the register so it can be used by the register scavenger.
void eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
Detailed Description
Definition at line 26 of file ThumbRegisterInfo.h.
Constructor & Destructor Documentation
ThumbRegisterInfo::ThumbRegisterInfo ()
Definition at line 41 of file ThumbRegisterInfo.cpp.
Member Function Documentation
void ThumbRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const [override]
Reimplemented from llvm::ARMBaseRegisterInfo.
Definition at line 497 of file ThumbRegisterInfo.cpp.
References llvm::AddDefaultPred(), llvm::ARMBaseRegisterInfo::BasePtr, llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), emitLoadConstPool(), llvm::emitThumbRegPlusImmediate(), emitThumbRegPlusImmInReg(), llvm::MachineInstr::findFirstPredOperandIdx(), llvm::ISD::FrameIndex, llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFrameInfo(), llvm::ARMSubtarget::getFrameLowering(), llvm::ARMFunctionInfo::getFramePtrSpillOffset(), llvm::ARMBaseRegisterInfo::getFrameRegister(), llvm::MachineOperand::getIndex(), llvm::MachineFunction::getInfo(), llvm::ARMSubtarget::getInstrInfo(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::ARMBaseRegisterInfo::hasBasePointer(), llvm::ARMFrameLowering::hasFP(), llvm::ARMFrameLowering::hasReservedCallFrame(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::MachineInstr::isDebugValue(), llvm::MachineInstr::isPredicable(), llvm::RegScavenger::isScavengingFrameIndex(), llvm::ARMSubtarget::isThumb1Only(), llvm::ARMFunctionInfo::isThumbFunction(), llvm_unreachable, llvm::MachineInstr::mayLoad(), llvm::MachineInstr::mayStore(), llvm::AArch64CC::MI, removeOperands(), rewriteFrameIndex(), llvm::MachineInstr::setDesc(), and llvm::SP.
void ThumbRegisterInfo::emitLoadConstPool (MachineBasicBlock & MBB, MachineBasicBlock::iterator & MBBI, DebugLoc dl, unsigned DestReg, unsigned SubIdx, int Val, ARMCC::CondCodes Pred = ARMCC::AL, unsigned PredReg = 0, unsigned MIFlags = MachineInstr::NoFlags) const [override, virtual]
emitLoadConstPool - Emits a load from constpool to materialize the specified immediate.
Reimplemented from llvm::ARMBaseRegisterInfo.
Definition at line 103 of file ThumbRegisterInfo.cpp.
References emitThumb1LoadConstPool(), emitThumb2LoadConstPool(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getSubtarget(), llvm::isARMLowRegister(), and llvm::ARMSubtarget::isThumb1Only().
Referenced by eliminateFrameIndex().
const TargetRegisterClass * ThumbRegisterInfo::getLargestLegalSuperClass (const TargetRegisterClass * RC, const MachineFunction & MF) const [override]
Reimplemented from llvm::ARMBaseRegisterInfo.
Definition at line 44 of file ThumbRegisterInfo.cpp.
References llvm::ARMBaseRegisterInfo::getLargestLegalSuperClass(), llvm::MachineFunction::getSubtarget(), and llvm::ARMSubtarget::isThumb1Only().
const TargetRegisterClass * ThumbRegisterInfo::getPointerRegClass (const MachineFunction & MF, unsigned Kind = 0) const [override]
Reimplemented from llvm::ARMBaseRegisterInfo.
Definition at line 55 of file ThumbRegisterInfo.cpp.
References llvm::ARMBaseRegisterInfo::getPointerRegClass(), llvm::MachineFunction::getSubtarget(), and llvm::ARMSubtarget::isThumb1Only().
void ThumbRegisterInfo::resolveFrameIndex (MachineInstr & MI, unsigned BaseReg, int64_t Offset) const [override]
Reimplemented from llvm::ARMBaseRegisterInfo.
Definition at line 423 of file ThumbRegisterInfo.cpp.
References llvm::ARMSubtarget::getInstrInfo(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getSubtarget(), llvm::MachineOperand::isFI(), llvm::ARMSubtarget::isThumb1Only(), llvm::ARMBaseRegisterInfo::resolveFrameIndex(), and rewriteFrameIndex().
bool ThumbRegisterInfo::rewriteFrameIndex (MachineBasicBlock::iterator II, unsigned FrameRegIdx, unsigned FrameReg, int & Offset, const ARMBaseInstrInfo & TII) const
Definition at line 352 of file ThumbRegisterInfo.cpp.
References llvm::ARMII::AddrModeMask, llvm::ARMII::AddrModeT1_s, llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), convertToNonSPOpcode(), llvm::emitThumbRegPlusImmediate(), llvm::MachineBasicBlock::erase(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getSubtarget(), llvm_unreachable, llvm::AArch64CC::MI, llvm::MachineInstr::setDesc(), llvm::SP, and llvm::MCInstrDesc::TSFlags.
Referenced by eliminateFrameIndex(), and resolveFrameIndex().
bool ThumbRegisterInfo::saveScavengerRegister (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, MachineBasicBlock::iterator & UseMI, const TargetRegisterClass * RC, unsigned Reg) const [override]
saveScavengerRegister - Spill the register so it can be used by the register scavenger.
Return true.
Definition at line 445 of file ThumbRegisterInfo.cpp.
References llvm::AddDefaultPred(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineOperand::clobbersPhysReg(), llvm::RegState::Define, llvm::DL, llvm::MCInstrInfo::get(), llvm::ARMSubtarget::getInstrInfo(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getSubtarget(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isRegMask(), llvm::ARMSubtarget::isThumb1Only(), llvm::MachineOperand::isUndef(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::RegState::Kill, and llvm::R12.
The documentation for this struct was generated from the following files:
ThumbRegisterInfo.h
ThumbRegisterInfo.cpp