LLVM: llvm::LessRecordRegister::RecordParts Struct Reference
llvm::LessRecordRegister::RecordParts Struct Reference
#include <Record.h>
Public Member Functions
RecordParts (StringRef Rec)
size_t size ()
std::pair< bool, StringRef > getPart (size_t i)
Public Attributes
SmallVector< std::pair< bool,
StringRef >, 4 > Parts
Detailed Description
Definition at line 1504 of file Record.h.
Constructor & Destructor Documentation
llvm::LessRecordRegister::RecordParts::RecordParts (StringRef Rec) [inline]
Definition at line 1507 of file Record.h.
References llvm::LessRecordRegister::ascii_isdigit(), llvm::StringRef::data(), llvm::StringRef::empty(), I, Parts, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::StringRef::size().
Member Function Documentation
std::pair<bool, StringRef> llvm::LessRecordRegister::RecordParts::getPart (size_t i) [inline]
Definition at line 1530 of file Record.h.
References Parts, and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::LessRecordRegister::operator()().
size_t llvm::LessRecordRegister::RecordParts::size () [inline]
Definition at line 1528 of file Record.h.
References Parts, and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::LessRecordRegister::operator()().
Member Data Documentation
SmallVector<std::pair< bool, StringRef>, 4> llvm::LessRecordRegister::RecordParts::Parts
Definition at line 1505 of file Record.h.
Referenced by getPart(), RecordParts(), and size().
The documentation for this struct was generated from the following file:
Record.h