LLVM: llvm::MCSchedClassDesc Struct Reference
llvm::MCSchedClassDesc Struct Reference
Summarize the scheduling resources required for an instruction of a particular scheduling class.
#include <MCSchedule.h>
Public Member Functions
bool isValid () const
bool isVariant () const
Public Attributes
const char * Name
unsigned short NumMicroOps
bool BeginGroup
bool EndGroup
unsigned WriteProcResIdx
unsigned NumWriteProcResEntries
unsigned WriteLatencyIdx
unsigned NumWriteLatencyEntries
unsigned ReadAdvanceIdx
unsigned NumReadAdvanceEntries
Static Public Attributes
static const unsigned short InvalidNumMicroOps = UINT16_MAX
static const unsigned short VariantNumMicroOps = UINT16_MAX - 1
Detailed Description
Summarize the scheduling resources required for an instruction of a particular scheduling class.
Defined as an aggregate struct for creating tables with initializer lists.
Definition at line 101 of file MCSchedule.h.
Member Function Documentation
bool llvm::MCSchedClassDesc::isValid () const [inline]
Definition at line 118 of file MCSchedule.h.
References InvalidNumMicroOps, and NumMicroOps.
Referenced by llvm::TargetSchedModel::computeInstrLatency(), llvm::TargetSchedModel::computeOperandLatency(), llvm::TargetSchedModel::computeOutputLatency(), getLatency(), llvm::TargetSchedModel::getNumMicroOps(), llvm::MachineTraceMetrics::Trace::getResourceLength(), llvm::MachineTraceMetrics::getResources(), and llvm::TargetSchedModel::resolveSchedClass().
bool llvm::MCSchedClassDesc::isVariant () const [inline]
Definition at line 121 of file MCSchedule.h.
References NumMicroOps, and VariantNumMicroOps.
Referenced by llvm::TargetSchedModel::computeInstrLatency(), getLatency(), and llvm::TargetSchedModel::resolveSchedClass().
Member Data Documentation
bool llvm::MCSchedClassDesc::BeginGroup
Definition at line 109 of file MCSchedule.h.
bool llvm::MCSchedClassDesc::EndGroup
Definition at line 110 of file MCSchedule.h.
const unsigned short llvm::MCSchedClassDesc::InvalidNumMicroOps = UINT16_MAX [static]
Definition at line 102 of file MCSchedule.h.
Referenced by isValid().
const char* llvm::MCSchedClassDesc::Name
Definition at line 106 of file MCSchedule.h.
unsigned short llvm::MCSchedClassDesc::NumMicroOps
Definition at line 108 of file MCSchedule.h.
Referenced by llvm::TargetSchedModel::getNumMicroOps(), isValid(), and isVariant().
unsigned llvm::MCSchedClassDesc::NumReadAdvanceEntries
Definition at line 116 of file MCSchedule.h.
Referenced by llvm::TargetSchedModel::computeOperandLatency(), and llvm::MCSubtargetInfo::getReadAdvanceCycles().
unsigned llvm::MCSchedClassDesc::NumWriteLatencyEntries
Definition at line 114 of file MCSchedule.h.
Referenced by getLatency().
unsigned llvm::MCSchedClassDesc::NumWriteProcResEntries
Definition at line 112 of file MCSchedule.h.
Referenced by llvm::MCSubtargetInfo::getWriteProcResEnd().
unsigned llvm::MCSchedClassDesc::ReadAdvanceIdx
Definition at line 115 of file MCSchedule.h.
Referenced by llvm::MCSubtargetInfo::getReadAdvanceCycles().
const unsigned short llvm::MCSchedClassDesc::VariantNumMicroOps = UINT16_MAX - 1 [static]
Definition at line 103 of file MCSchedule.h.
Referenced by isVariant().
unsigned llvm::MCSchedClassDesc::WriteLatencyIdx
Definition at line 113 of file MCSchedule.h.
Referenced by llvm::MCSubtargetInfo::getWriteLatencyEntry().
unsigned llvm::MCSchedClassDesc::WriteProcResIdx
Definition at line 111 of file MCSchedule.h.
Referenced by llvm::MCSubtargetInfo::getWriteProcResBegin().
The documentation for this struct was generated from the following file:
MCSchedule.h