LLVM: llvm::ConstantAggrKeyType< ConstantClass > Struct Template Reference
llvm::ConstantAggrKeyType< ConstantClass > Struct Template Reference
#include <ConstantsContext.h>
Public Types
typedef ConstantInfo
< ConstantClass >::TypeClass TypeClass
Public Member Functions
ConstantAggrKeyType (ArrayRef< Constant * > Operands)
ConstantAggrKeyType (ArrayRef< Constant * > Operands, const ConstantClass *)
ConstantAggrKeyType (const ConstantClass *C, SmallVectorImpl< Constant * > &Storage)
bool operator== (const ConstantAggrKeyType &X) const
bool operator== (const ConstantClass *C) const
unsigned getHash () const
ConstantClass * create (TypeClass *Ty) const
Public Attributes
ArrayRef< Constant * > Operands
Detailed Description
template<class ConstantClass>
struct llvm::ConstantAggrKeyType< ConstantClass >
Definition at line 339 of file ConstantsContext.h.
Member Typedef Documentation
template<class ConstantClass > typedef ConstantInfo<ConstantClass>::TypeClass llvm::ConstantAggrKeyType< ConstantClass >::TypeClass
Definition at line 367 of file ConstantsContext.h.
Constructor & Destructor Documentation
template<class ConstantClass > llvm::ConstantAggrKeyType< ConstantClass >::ConstantAggrKeyType (ArrayRef< Constant * > Operands) [inline]
Definition at line 341 of file ConstantsContext.h.
template<class ConstantClass > llvm::ConstantAggrKeyType< ConstantClass >::ConstantAggrKeyType (ArrayRef< Constant * > Operands, const ConstantClass *) [inline]
Definition at line 342 of file ConstantsContext.h.
template<class ConstantClass > llvm::ConstantAggrKeyType< ConstantClass >::ConstantAggrKeyType (const ConstantClass * C, SmallVectorImpl< Constant * > & Storage) [inline]
Definition at line 344 of file ConstantsContext.h.
References llvm::SmallVectorBase::empty(), I, llvm::ConstantAggrKeyType< ConstantClass >::Operands, and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Member Function Documentation
template<class ConstantClass > ConstantClass* llvm::ConstantAggrKeyType< ConstantClass >::create (TypeClass * Ty) const [inline]
Definition at line 368 of file ConstantsContext.h.
References llvm::ConstantAggrKeyType< ConstantClass >::Operands, and llvm::ArrayRef< T >::size().
template<class ConstantClass > unsigned llvm::ConstantAggrKeyType< ConstantClass >::getHash () const [inline]
Definition at line 363 of file ConstantsContext.h.
References llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), llvm::hash_combine_range(), and llvm::ConstantAggrKeyType< ConstantClass >::Operands.
template<class ConstantClass > bool llvm::ConstantAggrKeyType< ConstantClass >::operator== (const ConstantAggrKeyType< ConstantClass > & X) const [inline]
Definition at line 352 of file ConstantsContext.h.
References llvm::ConstantAggrKeyType< ConstantClass >::Operands.
template<class ConstantClass > bool llvm::ConstantAggrKeyType< ConstantClass >::operator== (const ConstantClass * C) const [inline]
Definition at line 355 of file ConstantsContext.h.
References I, llvm::ConstantAggrKeyType< ConstantClass >::Operands, and llvm::ArrayRef< T >::size().
Member Data Documentation
template<class ConstantClass > ArrayRef<Constant *> llvm::ConstantAggrKeyType< ConstantClass >::Operands
Definition at line 340 of file ConstantsContext.h.
Referenced by llvm::ConstantAggrKeyType< ConstantClass >::ConstantAggrKeyType(), llvm::ConstantAggrKeyType< ConstantClass >::create(), llvm::ConstantAggrKeyType< ConstantClass >::getHash(), and llvm::ConstantAggrKeyType< ConstantClass >::operator==().
The documentation for this struct was generated from the following file:
ConstantsContext.h