LLVM: llvm::MDNodeKeyImpl< DIObjCProperty > Struct Template Reference
llvm::MDNodeKeyImpl< DIObjCProperty > Struct Template Reference
#include <LLVMContextImpl.h>
Public Member Functions
MDNodeKeyImpl (StringRef Name, Metadata *File, unsigned Line, StringRef GetterName, StringRef SetterName, unsigned Attributes, Metadata *Type)
MDNodeKeyImpl (const DIObjCProperty *N)
bool isKeyOf (const DIObjCProperty *RHS) const
unsigned getHashValue () const
Public Attributes
StringRef Name
Metadata * File
unsigned Line
StringRef GetterName
StringRef SetterName
unsigned Attributes
Metadata * Type
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DIObjCProperty >
Definition at line 776 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
llvm::MDNodeKeyImpl< DIObjCProperty >::MDNodeKeyImpl (StringRef Name, Metadata * File, unsigned Line, StringRef GetterName, StringRef SetterName, unsigned Attributes, Metadata * Type) [inline]
Definition at line 785 of file LLVMContextImpl.h.
llvm::MDNodeKeyImpl< DIObjCProperty >::MDNodeKeyImpl (const DIObjCProperty * N) [inline]
Definition at line 790 of file LLVMContextImpl.h.
Member Function Documentation
unsigned llvm::MDNodeKeyImpl< DIObjCProperty >::getHashValue () const [inline]
Definition at line 801 of file LLVMContextImpl.h.
References llvm::ARMBuildAttrs::File, and llvm::hash_combine().
bool llvm::MDNodeKeyImpl< DIObjCProperty >::isKeyOf (const DIObjCProperty * RHS) const [inline]
Definition at line 795 of file LLVMContextImpl.h.
References llvm::ARMBuildAttrs::File, llvm::DIObjCProperty::getAttributes(), llvm::DIObjCProperty::getGetterName(), llvm::DIObjCProperty::getLine(), llvm::DIObjCProperty::getName(), llvm::DIObjCProperty::getRawFile(), llvm::DIObjCProperty::getRawType(), and llvm::DIObjCProperty::getSetterName().
Member Data Documentation
unsigned llvm::MDNodeKeyImpl< DIObjCProperty >::Attributes
Definition at line 782 of file LLVMContextImpl.h.
Metadata* llvm::MDNodeKeyImpl< DIObjCProperty >::File
Definition at line 778 of file LLVMContextImpl.h.
StringRef llvm::MDNodeKeyImpl< DIObjCProperty >::GetterName
Definition at line 780 of file LLVMContextImpl.h.
unsigned llvm::MDNodeKeyImpl< DIObjCProperty >::Line
Definition at line 779 of file LLVMContextImpl.h.
StringRef llvm::MDNodeKeyImpl< DIObjCProperty >::Name
Definition at line 777 of file LLVMContextImpl.h.
StringRef llvm::MDNodeKeyImpl< DIObjCProperty >::SetterName
Definition at line 781 of file LLVMContextImpl.h.
Metadata* llvm::MDNodeKeyImpl< DIObjCProperty >::Type
Definition at line 783 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
LLVMContextImpl.h