LLVM: llvm::XCoreRegisterInfo Struct Reference
llvm::XCoreRegisterInfo Struct Reference
#include <XCoreRegisterInfo.h>
Public Member Functions
XCoreRegisterInfo ()
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
Code Generation virtual methods...
BitVector getReservedRegs (const MachineFunction &MF) const override
bool requiresRegisterScavenging (const MachineFunction &MF) const override
bool trackLivenessAfterRegAlloc (const MachineFunction &MF) const override
bool useFPForScavengingIndex (const MachineFunction &MF) const override
void eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
unsigned getFrameRegister (const MachineFunction &MF) const override
Static Public Member Functions
static bool needsFrameMoves (const MachineFunction &MF)
Return whether to emit frame moves.
Detailed Description
Definition at line 26 of file XCoreRegisterInfo.h.
Constructor & Destructor Documentation
XCoreRegisterInfo::XCoreRegisterInfo ()
Definition at line 44 of file XCoreRegisterInfo.cpp.
Member Function Documentation
void XCoreRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const [override]
Definition at line 261 of file XCoreRegisterInfo.cpp.
References llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), contains(), DEBUG, llvm::MachineBasicBlock::erase(), llvm::errs(), llvm::ISD::FrameIndex, llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getFrameLowering(), getFrameRegister(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFunction::getName(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::TargetFrameLowering::hasFP(), InsertFPConstInst(), InsertFPImmInst(), InsertSPConstInst(), InsertSPImmInst(), llvm::MachineInstr::isDebugValue(), isImmU16(), isImmUs(), llvm::AArch64CC::MI, llvm::MachineInstr::print(), and TII.
const MCPhysReg * XCoreRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const [override]
Code Generation virtual methods...
Definition at line 212 of file XCoreRegisterInfo.cpp.
References llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFunction::getSubtarget(), llvm::TargetFrameLowering::hasFP(), llvm::R10, llvm::R8, and llvm::R9.
unsigned XCoreRegisterInfo::getFrameRegister (const MachineFunction & MF) const [override]
Definition at line 326 of file XCoreRegisterInfo.cpp.
References llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFunction::getSubtarget(), llvm::TargetFrameLowering::hasFP(), llvm::R10, and llvm::SP.
Referenced by eliminateFrameIndex().
BitVector XCoreRegisterInfo::getReservedRegs (const MachineFunction & MF) const [override]
Definition at line 231 of file XCoreRegisterInfo.cpp.
References llvm::HexagonISD::CP, llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFunction::getSubtarget(), llvm::TargetFrameLowering::hasFP(), llvm::R10, llvm::Reserved, llvm::BitVector::set(), and llvm::SP.
bool XCoreRegisterInfo::needsFrameMoves (const MachineFunction & MF) [static]
Return whether to emit frame moves.
Definition at line 206 of file XCoreRegisterInfo.cpp.
References llvm::MachineFunction::getFunction(), llvm::MachineFunction::getMMI(), llvm::MachineModuleInfo::hasDebugInfo(), and llvm::Function::needsUnwindTableEntry().
Referenced by llvm::XCoreFrameLowering::emitPrologue(), and llvm::XCoreFrameLowering::spillCalleeSavedRegisters().
bool XCoreRegisterInfo::requiresRegisterScavenging (const MachineFunction & MF) const [override]
Definition at line 246 of file XCoreRegisterInfo.cpp.
bool XCoreRegisterInfo::trackLivenessAfterRegAlloc (const MachineFunction & MF) const [override]
Definition at line 251 of file XCoreRegisterInfo.cpp.
bool XCoreRegisterInfo::useFPForScavengingIndex (const MachineFunction & MF) const [override]
Definition at line 256 of file XCoreRegisterInfo.cpp.
The documentation for this struct was generated from the following files:
XCoreRegisterInfo.h
XCoreRegisterInfo.cpp