LLVM: llvm::BitSetInfo Struct Reference
llvm::BitSetInfo Struct Reference
#include <LowerBitSets.h>
Public Member Functions
bool isSingleOffset () const
bool isAllOnes () const
bool containsGlobalOffset (uint64_t Offset) const
bool containsValue (const DataLayout &DL, const DenseMap< GlobalVariable *, uint64_t > &GlobalLayout, Value *V, uint64_t COffset=0) const
Public Attributes
std::set< uint64_t > Bits
uint64_t ByteOffset
uint64_t BitSize
unsigned AlignLog2
Detailed Description
Definition at line 32 of file LowerBitSets.h.
Member Function Documentation
bool BitSetInfo::containsGlobalOffset (uint64_t Offset) const
Definition at line 46 of file LowerBitSets.cpp.
References AlignLog2, Bits, BitSize, and ByteOffset.
Referenced by containsValue().
bool BitSetInfo::containsValue (const DataLayout & DL, const DenseMap< GlobalVariable *, uint64_t > & GlobalLayout, Value * V, uint64_t COffset = 0) const
Definition at line 60 of file LowerBitSets.cpp.
References containsGlobalOffset(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::DataLayout::getPointerSizeInBits(), llvm::APInt::getZExtValue(), I, and llvm::MCID::Select.
bool llvm::BitSetInfo::isAllOnes () const [inline]
Definition at line 51 of file LowerBitSets.h.
References Bits, and BitSize.
bool llvm::BitSetInfo::isSingleOffset () const [inline]
Definition at line 47 of file LowerBitSets.h.
References Bits.
Member Data Documentation
unsigned llvm::BitSetInfo::AlignLog2
Definition at line 45 of file LowerBitSets.h.
Referenced by llvm::BitSetBuilder::build(), and containsGlobalOffset().
std::set<uint64_t> llvm::BitSetInfo::Bits
Definition at line 34 of file LowerBitSets.h.
Referenced by llvm::BitSetBuilder::build(), containsGlobalOffset(), isAllOnes(), and isSingleOffset().
uint64_t llvm::BitSetInfo::BitSize
Definition at line 40 of file LowerBitSets.h.
Referenced by llvm::BitSetBuilder::build(), containsGlobalOffset(), and isAllOnes().
uint64_t llvm::BitSetInfo::ByteOffset
Definition at line 37 of file LowerBitSets.h.
Referenced by llvm::BitSetBuilder::build(), and containsGlobalOffset().
The documentation for this struct was generated from the following files:
LowerBitSets.h
LowerBitSets.cpp