LLVM: llvm::objcarc::TopDownPtrState Struct Reference
llvm::objcarc::TopDownPtrState Struct Reference
#include <PtrState.h>
Public Member Functions
TopDownPtrState ()
bool InitTopDown (ARCInstKind Kind, Instruction *I)
(Re-)Initialize this bottom up pointer returning true if we detected a pointer with nested releases.
bool MatchWithRelease (ARCMDKindCache &Cache, Instruction *Release)
Return true if this set of retains can be paired with the given release.
void HandlePotentialUse (Instruction *Inst, const Value *Ptr, ProvenanceAnalysis &PA, ARCInstKind Class)
bool HandlePotentialAlterRefCount (Instruction *Inst, const Value *Ptr, ProvenanceAnalysis &PA, ARCInstKind Class)
Detailed Description
Definition at line 188 of file PtrState.h.
Constructor & Destructor Documentation
llvm::objcarc::TopDownPtrState::TopDownPtrState () [inline]
Definition at line 189 of file PtrState.h.
Member Function Documentation
bool TopDownPtrState::HandlePotentialAlterRefCount (Instruction * Inst, const Value * Ptr, ProvenanceAnalysis & PA, ARCInstKind Class)
Definition at line 350 of file PtrState.cpp.
References llvm::objcarc::CanAlterRefCount(), llvm::dbgs(), DEBUG, llvm_unreachable, llvm::objcarc::S_CanRelease, llvm::objcarc::S_MovableRelease, llvm::objcarc::S_None, llvm::objcarc::S_Release, llvm::objcarc::S_Retain, llvm::objcarc::S_Stop, and llvm::objcarc::S_Use.
void TopDownPtrState::HandlePotentialUse (Instruction * Inst, const Value * Ptr, ProvenanceAnalysis & PA, ARCInstKind Class)
Definition at line 383 of file PtrState.cpp.
References llvm::objcarc::CanUse(), llvm::dbgs(), DEBUG, llvm_unreachable, llvm::objcarc::S_CanRelease, llvm::objcarc::S_MovableRelease, llvm::objcarc::S_None, llvm::objcarc::S_Release, llvm::objcarc::S_Retain, llvm::objcarc::S_Stop, and llvm::objcarc::S_Use.
bool TopDownPtrState::InitTopDown (ARCInstKind Kind, Instruction * I)
(Re-)Initialize this bottom up pointer returning true if we detected a pointer with nested releases.
Definition at line 296 of file PtrState.cpp.
References llvm::objcarc::RetainRV, and llvm::objcarc::S_Retain.
bool TopDownPtrState::MatchWithRelease (ARCMDKindCache & Cache, Instruction * Release)
Return true if this set of retains can be paired with the given release.
Modifies state appropriately to reflect that the matching occured.
Definition at line 321 of file PtrState.cpp.
References llvm::objcarc::ARCMDKindCache::get(), llvm::Instruction::getMetadata(), llvm::objcarc::ImpreciseRelease, llvm_unreachable, llvm::objcarc::S_CanRelease, llvm::objcarc::S_MovableRelease, llvm::objcarc::S_None, llvm::objcarc::S_Release, llvm::objcarc::S_Retain, llvm::objcarc::S_Stop, and llvm::objcarc::S_Use.
The documentation for this struct was generated from the following files:
PtrState.h
PtrState.cpp