LLVM: llvm::DwarfStringPoolEntryRef Struct Reference
llvm::DwarfStringPoolEntryRef Struct Reference
String pool entry reference.
#include <DwarfStringPoolEntry.h>
Public Member Functions
DwarfStringPoolEntryRef ()
DwarfStringPoolEntryRef (const StringMapEntry< DwarfStringPoolEntry > &I)
operator bool () const
MCSymbol * getSymbol () const
unsigned getOffset () const
unsigned getIndex () const
StringRef getString () const
bool operator== (const DwarfStringPoolEntryRef &X) const
bool operator!= (const DwarfStringPoolEntryRef &X) const
Public Attributes
const StringMapEntry
< DwarfStringPoolEntry > * I = nullptr
Detailed Description
String pool entry reference.
Definition at line 27 of file DwarfStringPoolEntry.h.
Constructor & Destructor Documentation
llvm::DwarfStringPoolEntryRef::DwarfStringPoolEntryRef ()
llvm::DwarfStringPoolEntryRef::DwarfStringPoolEntryRef (const StringMapEntry< DwarfStringPoolEntry > & I) [inline, explicit]
Definition at line 32 of file DwarfStringPoolEntry.h.
Member Function Documentation
unsigned llvm::DwarfStringPoolEntryRef::getIndex () const [inline]
Definition at line 42 of file DwarfStringPoolEntry.h.
References I, llvm::DwarfStringPoolEntry::Index, and llvm::StringMapEntry< ValueTy >::second.
Referenced by llvm::DIEString::EmitValue(), and llvm::DIEString::SizeOf().
unsigned llvm::DwarfStringPoolEntryRef::getOffset () const [inline]
Definition at line 41 of file DwarfStringPoolEntry.h.
References I, llvm::DwarfStringPoolEntry::Offset, and llvm::StringMapEntry< ValueTy >::second.
Referenced by llvm::AsmPrinter::emitDwarfStringOffset(), llvm::DIEString::EmitValue(), and llvm::DIEString::SizeOf().
StringRef llvm::DwarfStringPoolEntryRef::getString () const [inline]
Definition at line 43 of file DwarfStringPoolEntry.h.
References llvm::StringMapEntry< ValueTy >::first(), and I.
Referenced by llvm::DwarfAccelTable::AddName(), llvm::DIEString::getString(), and llvm::DIEString::print().
MCSymbol* llvm::DwarfStringPoolEntryRef::getSymbol () const [inline]
Definition at line 37 of file DwarfStringPoolEntry.h.
References I, llvm::StringMapEntry< ValueTy >::second, and llvm::DwarfStringPoolEntry::Symbol.
Referenced by llvm::AsmPrinter::emitDwarfStringOffset(), llvm::DIEString::EmitValue(), and llvm::DIEString::SizeOf().
llvm::DwarfStringPoolEntryRef::operator bool () const [inline, explicit]
Definition at line 36 of file DwarfStringPoolEntry.h.
References I.
bool llvm::DwarfStringPoolEntryRef::operator!= (const DwarfStringPoolEntryRef & X) const [inline]
Definition at line 46 of file DwarfStringPoolEntry.h.
References I.
bool llvm::DwarfStringPoolEntryRef::operator== (const DwarfStringPoolEntryRef & X) const [inline]
Definition at line 45 of file DwarfStringPoolEntry.h.
References I.
Member Data Documentation
const StringMapEntry<DwarfStringPoolEntry>* llvm::DwarfStringPoolEntryRef::I = nullptr
Definition at line 28 of file DwarfStringPoolEntry.h.
Referenced by getIndex(), getOffset(), getString(), getSymbol(), operator bool(), operator!=(), and operator==().
The documentation for this struct was generated from the following file:
DwarfStringPoolEntry.h