LLVM: llvm::MDNodeKeyImpl< DICompileUnit > Struct Template Reference
llvm::MDNodeKeyImpl< DICompileUnit > Struct Template Reference
#include <LLVMContextImpl.h>
Public Member Functions
MDNodeKeyImpl (unsigned SourceLanguage, Metadata *File, StringRef Producer, bool IsOptimized, StringRef Flags, unsigned RuntimeVersion, StringRef SplitDebugFilename, unsigned EmissionKind, Metadata *EnumTypes, Metadata *RetainedTypes, Metadata *Subprograms, Metadata *GlobalVariables, Metadata *ImportedEntities, uint64_t DWOId)
MDNodeKeyImpl (const DICompileUnit *N)
bool isKeyOf (const DICompileUnit *RHS) const
unsigned getHashValue () const
Public Attributes
unsigned SourceLanguage
Metadata * File
StringRef Producer
bool IsOptimized
StringRef Flags
unsigned RuntimeVersion
StringRef SplitDebugFilename
unsigned EmissionKind
Metadata * EnumTypes
Metadata * RetainedTypes
Metadata * Subprograms
Metadata * GlobalVariables
Metadata * ImportedEntities
uint64_t DWOId
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DICompileUnit >
Definition at line 461 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
llvm::MDNodeKeyImpl< DICompileUnit >::MDNodeKeyImpl (unsigned SourceLanguage, Metadata * File, StringRef Producer, bool IsOptimized, StringRef Flags, unsigned RuntimeVersion, StringRef SplitDebugFilename, unsigned EmissionKind, Metadata * EnumTypes, Metadata * RetainedTypes, Metadata * Subprograms, Metadata * GlobalVariables, Metadata * ImportedEntities, uint64_t DWOId) [inline]
Definition at line 477 of file LLVMContextImpl.h.
llvm::MDNodeKeyImpl< DICompileUnit >::MDNodeKeyImpl (const DICompileUnit * N) [inline]
Definition at line 489 of file LLVMContextImpl.h.
Member Function Documentation
unsigned llvm::MDNodeKeyImpl< DICompileUnit >::getHashValue () const [inline]
Definition at line 514 of file LLVMContextImpl.h.
References llvm::ARMBuildAttrs::File, and llvm::hash_combine().
bool llvm::MDNodeKeyImpl< DICompileUnit >::isKeyOf (const DICompileUnit * RHS) const [inline]
Definition at line 500 of file LLVMContextImpl.h.
References llvm::ARMBuildAttrs::File, llvm::DICompileUnit::getDWOId(), llvm::DICompileUnit::getEmissionKind(), llvm::DICompileUnit::getFlags(), llvm::DICompileUnit::getProducer(), llvm::DICompileUnit::getRawEnumTypes(), llvm::DIScope::getRawFile(), llvm::DICompileUnit::getRawGlobalVariables(), llvm::DICompileUnit::getRawImportedEntities(), llvm::DICompileUnit::getRawRetainedTypes(), llvm::DICompileUnit::getRawSubprograms(), llvm::DICompileUnit::getRuntimeVersion(), llvm::DICompileUnit::getSourceLanguage(), llvm::DICompileUnit::getSplitDebugFilename(), and llvm::DICompileUnit::isOptimized().
Member Data Documentation
uint64_t llvm::MDNodeKeyImpl< DICompileUnit >::DWOId
Definition at line 475 of file LLVMContextImpl.h.
unsigned llvm::MDNodeKeyImpl< DICompileUnit >::EmissionKind
Definition at line 469 of file LLVMContextImpl.h.
Metadata* llvm::MDNodeKeyImpl< DICompileUnit >::EnumTypes
Definition at line 470 of file LLVMContextImpl.h.
Metadata* llvm::MDNodeKeyImpl< DICompileUnit >::File
Definition at line 463 of file LLVMContextImpl.h.
StringRef llvm::MDNodeKeyImpl< DICompileUnit >::Flags
Definition at line 466 of file LLVMContextImpl.h.
Metadata* llvm::MDNodeKeyImpl< DICompileUnit >::GlobalVariables
Definition at line 473 of file LLVMContextImpl.h.
Metadata* llvm::MDNodeKeyImpl< DICompileUnit >::ImportedEntities
Definition at line 474 of file LLVMContextImpl.h.
bool llvm::MDNodeKeyImpl< DICompileUnit >::IsOptimized
Definition at line 465 of file LLVMContextImpl.h.
StringRef llvm::MDNodeKeyImpl< DICompileUnit >::Producer
Definition at line 464 of file LLVMContextImpl.h.
Metadata* llvm::MDNodeKeyImpl< DICompileUnit >::RetainedTypes
Definition at line 471 of file LLVMContextImpl.h.
unsigned llvm::MDNodeKeyImpl< DICompileUnit >::RuntimeVersion
Definition at line 467 of file LLVMContextImpl.h.
unsigned llvm::MDNodeKeyImpl< DICompileUnit >::SourceLanguage
Definition at line 462 of file LLVMContextImpl.h.
StringRef llvm::MDNodeKeyImpl< DICompileUnit >::SplitDebugFilename
Definition at line 468 of file LLVMContextImpl.h.
Metadata* llvm::MDNodeKeyImpl< DICompileUnit >::Subprograms
Definition at line 472 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
LLVMContextImpl.h