LLVM: llvm::MDNodeKeyImpl< DIImportedEntity > Struct Template Reference
llvm::MDNodeKeyImpl< DIImportedEntity > Struct Template Reference
#include <LLVMContextImpl.h>
Public Member Functions
MDNodeKeyImpl (unsigned Tag, Metadata *Scope, Metadata *Entity, unsigned Line, StringRef Name)
MDNodeKeyImpl (const DIImportedEntity *N)
bool isKeyOf (const DIImportedEntity *RHS) const
unsigned getHashValue () const
Public Attributes
unsigned Tag
Metadata * Scope
Metadata * Entity
unsigned Line
StringRef Name
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DIImportedEntity >
Definition at line 807 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
llvm::MDNodeKeyImpl< DIImportedEntity >::MDNodeKeyImpl (unsigned Tag, Metadata * Scope, Metadata * Entity, unsigned Line, StringRef Name) [inline]
Definition at line 814 of file LLVMContextImpl.h.
llvm::MDNodeKeyImpl< DIImportedEntity >::MDNodeKeyImpl (const DIImportedEntity * N) [inline]
Definition at line 817 of file LLVMContextImpl.h.
Member Function Documentation
unsigned llvm::MDNodeKeyImpl< DIImportedEntity >::getHashValue () const [inline]
Definition at line 826 of file LLVMContextImpl.h.
References llvm::hash_combine().
bool llvm::MDNodeKeyImpl< DIImportedEntity >::isKeyOf (const DIImportedEntity * RHS) const [inline]
Definition at line 821 of file LLVMContextImpl.h.
References llvm::DIImportedEntity::getLine(), llvm::DIImportedEntity::getName(), llvm::DIImportedEntity::getRawEntity(), llvm::DIImportedEntity::getRawScope(), and llvm::DINode::getTag().
Member Data Documentation
Metadata* llvm::MDNodeKeyImpl< DIImportedEntity >::Entity
Definition at line 810 of file LLVMContextImpl.h.
unsigned llvm::MDNodeKeyImpl< DIImportedEntity >::Line
Definition at line 811 of file LLVMContextImpl.h.
StringRef llvm::MDNodeKeyImpl< DIImportedEntity >::Name
Definition at line 812 of file LLVMContextImpl.h.
Metadata* llvm::MDNodeKeyImpl< DIImportedEntity >::Scope
Definition at line 809 of file LLVMContextImpl.h.
unsigned llvm::MDNodeKeyImpl< DIImportedEntity >::Tag
Definition at line 808 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
LLVMContextImpl.h