LLVM: llvm::MCDwarfLineTableHeader Struct Reference
llvm::MCDwarfLineTableHeader Struct Reference
#include <MCDwarf.h>
Public Member Functions
MCDwarfLineTableHeader ()
unsigned getFile (StringRef &Directory, StringRef &FileName, unsigned FileNumber=0)
std::pair< MCSymbol *, MCSymbol * > Emit (MCStreamer *MCOS) const
std::pair< MCSymbol *, MCSymbol * > Emit (MCStreamer *MCOS, ArrayRef< char > SpecialOpcodeLengths) const
Public Attributes
MCSymbol * Label
SmallVector< std::string, 3 > MCDwarfDirs
SmallVector< MCDwarfFile, 3 > MCDwarfFiles
StringMap< unsigned > SourceIdMap
StringRef CompilationDir
Detailed Description
Definition at line 176 of file MCDwarf.h.
Constructor & Destructor Documentation
llvm::MCDwarfLineTableHeader::MCDwarfLineTableHeader () [inline]
Definition at line 183 of file MCDwarf.h.
Member Function Documentation
std::pair< MCSymbol *, MCSymbol * > MCDwarfLineTableHeader::Emit (MCStreamer * MCOS) const
Definition at line 222 of file MCDwarf.cpp.
References llvm::array_lengthof(), and DWARF2_LINE_OPCODE_BASE.
Referenced by llvm::MCDwarfDwoLineTable::Emit(), and llvm::MCDwarfLineTable::EmitCU().
std::pair< MCSymbol *, MCSymbol * > MCDwarfLineTableHeader::Emit (MCStreamer * MCOS, ArrayRef< char > SpecialOpcodeLengths) const
Definition at line 259 of file MCDwarf.cpp.
References llvm::MCContext::createTempSymbol(), DWARF2_LINE_BASE, DWARF2_LINE_DEFAULT_IS_STMT, DWARF2_LINE_RANGE, emitAbsValue(), llvm::MCStreamer::EmitBytes(), llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitULEB128IntValue(), llvm::MCContext::getAsmInfo(), llvm::MCStreamer::getContext(), llvm::MCAsmInfo::getMinInstAlignment(), Label, MakeStartMinusEndExpr(), MCDwarfDirs, MCDwarfFiles, llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::ArrayRef< T >::size().
unsigned MCDwarfLineTableHeader::getFile (StringRef & Directory, StringRef & FileName, unsigned FileNumber = 0)
Definition at line 349 of file MCDwarf.cpp.
References CompilationDir, llvm::MCDwarfFile::DirIndex, llvm::SmallVectorBase::empty(), llvm::StringRef::empty(), llvm::ARMBuildAttrs::File, llvm::sys::path::filename(), llvm::StringMap< ValueTy, AllocatorTy >::insert(), MCDwarfDirs, MCDwarfFiles, llvm::MCDwarfFile::Name, llvm::sys::path::parent_path(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorImpl< T >::resize(), llvm::StringMapImpl::size(), llvm::SmallVectorTemplateCommon< T, typename >::size(), SourceIdMap, and llvm::toStringRef().
Referenced by llvm::MCDwarfDwoLineTable::getFile(), and llvm::MCDwarfLineTable::getFile().
Member Data Documentation
StringRef llvm::MCDwarfLineTableHeader::CompilationDir
Definition at line 181 of file MCDwarf.h.
Referenced by getFile(), llvm::MCDwarfDwoLineTable::setCompilationDir(), and llvm::MCDwarfLineTable::setCompilationDir().
MCSymbol* llvm::MCDwarfLineTableHeader::Label
Definition at line 177 of file MCDwarf.h.
Referenced by Emit(), llvm::MCDwarfLineTable::getLabel(), and llvm::MCDwarfLineTable::setLabel().
SmallVector<std::string, 3> llvm::MCDwarfLineTableHeader::MCDwarfDirs
Definition at line 178 of file MCDwarf.h.
Referenced by Emit(), getFile(), and llvm::MCDwarfLineTable::getMCDwarfDirs().
SmallVector<MCDwarfFile, 3> llvm::MCDwarfLineTableHeader::MCDwarfFiles
Definition at line 179 of file MCDwarf.h.
Referenced by Emit(), getFile(), and llvm::MCDwarfLineTable::getMCDwarfFiles().
StringMap<unsigned> llvm::MCDwarfLineTableHeader::SourceIdMap
Definition at line 180 of file MCDwarf.h.
Referenced by getFile().
The documentation for this struct was generated from the following files:
MCDwarf.h
MCDwarf.cpp