LLVM: llvm::EVT Struct Reference
llvm::EVT Struct Reference
EVT - Extended Value Type.
#include <ValueTypes.h>
Classes
struct compareRawBits
compareRawBits - A meaningless but well-behaved order, useful for constructing containers.
Public Member Functions
LLVM_CONSTEXPR EVT ()
LLVM_CONSTEXPR EVT (MVT::SimpleValueType SVT)
LLVM_CONSTEXPR EVT (MVT S)
bool operator== (EVT VT) const
bool operator!= (EVT VT) const
EVT changeVectorElementTypeToInteger () const
changeVectorElementTypeToInteger - Return a vector with the same number of elements as this vector, but with the element type converted to an integer type with the same bitwidth.
bool isSimple () const
isSimple - Test if the given EVT is simple (as opposed to being extended).
bool isExtended () const
isExtended - Test if the given EVT is extended (as opposed to being simple).
bool isFloatingPoint () const
isFloatingPoint - Return true if this is a FP, or a vector FP type.
bool isInteger () const
isInteger - Return true if this is an integer, or a vector integer type.
bool isVector () const
isVector - Return true if this is a vector value type.
bool is16BitVector () const
is16BitVector - Return true if this is a 16-bit vector type.
bool is32BitVector () const
is32BitVector - Return true if this is a 32-bit vector type.
bool is64BitVector () const
is64BitVector - Return true if this is a 64-bit vector type.
bool is128BitVector () const
is128BitVector - Return true if this is a 128-bit vector type.
bool is256BitVector () const
is256BitVector - Return true if this is a 256-bit vector type.
bool is512BitVector () const
is512BitVector - Return true if this is a 512-bit vector type.
bool is1024BitVector () const
is1024BitVector - Return true if this is a 1024-bit vector type.
bool isOverloaded () const
isOverloaded - Return true if this is an overloaded type for TableGen.
bool isByteSized () const
isByteSized - Return true if the bit size is a multiple of 8.
bool isRound () const
isRound - Return true if the size is a power-of-two number of bytes.
bool bitsEq (EVT VT) const
bitsEq - Return true if this has the same number of bits as VT.
bool bitsGT (EVT VT) const
bitsGT - Return true if this has more bits than VT.
bool bitsGE (EVT VT) const
bitsGE - Return true if this has no less bits than VT.
bool bitsLT (EVT VT) const
bitsLT - Return true if this has less bits than VT.
bool bitsLE (EVT VT) const
bitsLE - Return true if this has no more bits than VT.
MVT getSimpleVT () const
getSimpleVT - Return the SimpleValueType held in the specified simple EVT.
EVT getScalarType () const
getScalarType - If this is a vector type, return the element type, otherwise return this.
EVT getVectorElementType () const
getVectorElementType - Given a vector type, return the type of each element.
unsigned getVectorNumElements () const
getVectorNumElements - Given a vector type, return the number of elements it contains.
unsigned getSizeInBits () const
getSizeInBits - Return the size of the specified value type in bits.
unsigned getScalarSizeInBits () const
unsigned getStoreSize () const
getStoreSize - Return the number of bytes overwritten by a store of the specified value type.
unsigned getStoreSizeInBits () const
getStoreSizeInBits - Return the number of bits overwritten by a store of the specified value type.
EVT getRoundIntegerType (LLVMContext &Context) const
getRoundIntegerType - Rounds the bit-width of the given integer EVT up to the nearest power of two (and at least to eight), and returns the integer EVT with that number of bits.
EVT getHalfSizedIntegerVT (LLVMContext &Context) const
getHalfSizedIntegerVT - Finds the smallest simple value type that is greater than or equal to half the width of this EVT.
EVT widenIntegerVectorElementType (LLVMContext &Context) const
Return a VT for an integer vector type with the size of the elements doubled.
bool isPow2VectorType () const
isPow2VectorType - Returns true if the given vector is a power of 2.
EVT getPow2VectorType (LLVMContext &Context) const
getPow2VectorType - Widens the length of the given vector EVT up to the nearest power of 2 and returns that type.
std::string getEVTString () const
getEVTString - This function returns value type as a string, e.g.
Type * getTypeForEVT (LLVMContext &Context) const
getTypeForEVT - This method returns an LLVM type corresponding to the specified EVT.
intptr_t getRawBits () const
Static Public Member Functions
static EVT getFloatingPointVT (unsigned BitWidth)
getFloatingPointVT - Returns the EVT that represents a floating point type with the given number of bits.
static EVT getIntegerVT (LLVMContext &Context, unsigned BitWidth)
getIntegerVT - Returns the EVT that represents an integer with the given number of bits.
static EVT getVectorVT (LLVMContext &Context, EVT VT, unsigned NumElements)
getVectorVT - Returns the EVT that represents a vector NumElements in length, where each element is of type VT.
static EVT getEVT (Type *Ty, bool HandleUnknown=false)
getEVT - Return the value type corresponding to the specified type.
Detailed Description
EVT - Extended Value Type.
Capable of holding value types which are not native for any processor (such as the i12345 type), as well as the types a MVT can represent.
Definition at line 31 of file ValueTypes.h.
Constructor & Destructor Documentation
LLVM_CONSTEXPR llvm::EVT::EVT () [inline]
Definition at line 37 of file ValueTypes.h.
Referenced by getHalfSizedIntegerVT(), and getRoundIntegerType().
LLVM_CONSTEXPR llvm::EVT::EVT (MVT::SimpleValueType SVT) [inline]
Definition at line 38 of file ValueTypes.h.
LLVM_CONSTEXPR llvm::EVT::EVT (MVT S) [inline]
Definition at line 39 of file ValueTypes.h.
Member Function Documentation
bool llvm::EVT::bitsEq (EVT VT) const [inline]
bitsEq - Return true if this has the same number of bits as VT.
Definition at line 171 of file ValueTypes.h.
References getSizeInBits().
bool llvm::EVT::bitsGE (EVT VT) const [inline]
bitsGE - Return true if this has no less bits than VT.
Definition at line 183 of file ValueTypes.h.
References getSizeInBits().
Referenced by getCopyToPartsVector(), getMemcpyLoadsAndStores(), and llvm::AMDGPUTargetLowering::LowerLOAD().
bool llvm::EVT::bitsGT (EVT VT) const [inline]
bitsGT - Return true if this has more bits than VT.
Definition at line 177 of file ValueTypes.h.
References getSizeInBits().
Referenced by AddCombineToVPADDL(), llvm::SITargetLowering::allowsMisalignedMemoryAccesses(), llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), FindOptimalMemOpLowering(), llvm::SelectionDAG::getAnyExtOrTrunc(), llvm::SelectionDAG::getNode(), llvm::FastISel::getRegForGEPIndex(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::SelectionDAG::getShiftAmountOperand(), llvm::SelectionDAG::getZExtOrTrunc(), LowerScalarVariableShift(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::FastISel::selectOperator(), and llvm::TargetLowering::SimplifySetCC().
bool llvm::EVT::bitsLE (EVT VT) const [inline]
bitsLE - Return true if this has no more bits than VT.
Definition at line 195 of file ValueTypes.h.
References getSizeInBits().
Referenced by llvm::SelectionDAG::getBoolExtOrTrunc(), getCopyFromPartsVector(), getCopyToPartsVector(), llvm::SelectionDAG::getNode(), llvm::SITargetLowering::getPreferredVectorAction(), LowerScalarVariableShift(), and llvm::TargetLowering::SimplifySetCC().
bool llvm::EVT::bitsLT (EVT VT) const [inline]
bitsLT - Return true if this has less bits than VT.
Definition at line 189 of file ValueTypes.h.
References getSizeInBits().
Referenced by llvm::SITargetLowering::allowsMisalignedMemoryAccesses(), llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), getCopyFromParts(), llvm::SelectionDAG::getLoad(), getMemsetStores(), llvm::SelectionDAG::getNode(), llvm::FastISel::getRegForGEPIndex(), llvm::GetReturnInfo(), llvm::SelectionDAG::getTruncStore(), llvm::TargetLowering::getTypeForExtArgOrReturn(), llvm::AMDGPUTargetLowering::isTruncateFree(), LowerScalarVariableShift(), llvm::AMDGPUTargetLowering::LowerSTORE(), OptimizeNoopCopyExpression(), llvm::AArch64TargetLowering::ReconstructShuffle(), llvm::FastISel::selectOperator(), and llvm::TargetLowering::SimplifySetCC().
EVT llvm::EVT::changeVectorElementTypeToInteger () const [inline]
changeVectorElementTypeToInteger - Return a vector with the same number of elements as this vector, but with the element type converted to an integer type with the same bitwidth.
Definition at line 80 of file ValueTypes.h.
References getIntegerVT(), getSimpleVT(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorElementType(), getVectorNumElements(), getVectorVT(), isSimple(), and llvm::MVT::SimpleTy.
Referenced by llvm::R600TargetLowering::getSetCCResultType(), llvm::SparcTargetLowering::getSetCCResultType(), llvm::MipsTargetLowering::getSetCCResultType(), llvm::ARMTargetLowering::getSetCCResultType(), llvm::AArch64TargetLowering::getSetCCResultType(), llvm::SystemZTargetLowering::getSetCCResultType(), llvm::PPCTargetLowering::getSetCCResultType(), lowerVECTOR_SHUFFLE_VSHF(), LowerVectorFP_TO_INT(), LowerVectorINT_TO_FP(), LowerVSETCC(), llvm::SystemZTargetLowering::PerformDAGCombine(), performSelectCombine(), performVSelectCombine(), and toIntegerVT().
EVT EVT::getEVT (Type * Ty, bool HandleUnknown = false) [static]
getEVT - Return the value type corresponding to the specified type.
This returns all pointers as iPTR. If HandleUnknown is true, unknown types are returned as Other, otherwise they are invalid.
This returns all pointers as MVT::iPTR. If HandleUnknown is true, unknown types are returned as Other, otherwise they are invalid.
Definition at line 277 of file ValueTypes.cpp.
References getBitWidth(), llvm::Type::getContext(), llvm::SequentialType::getElementType(), getIntegerVT(), llvm::VectorType::getNumElements(), llvm::Type::getTypeID(), getVectorVT(), llvm::MVT::getVT(), llvm::Type::IntegerTyID, and llvm::Type::VectorTyID.
Referenced by llvm::ARMTargetLowering::allowTruncateForTailCall(), getMangledTypeStr(), llvm::FastISel::getRegForGEPIndex(), llvm::TargetLoweringBase::getValueType(), INITIALIZE_PASS(), llvm::TargetLoweringBase::isExtFree(), isNoopBitcast(), llvm::HexagonTargetLowering::isTruncateFree(), and llvm::FastISel::selectBinaryOp().
std::string EVT::getEVTString () const
getEVTString - This function returns value type as a string, e.g.
getEVTString - This function returns value type as a string, e.g. "i32".
"i32".
Definition at line 106 of file ValueTypes.cpp.
References llvm::MVT::f128, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, getEVTString(), getSizeInBits(), getVectorElementType(), getVectorNumElements(), llvm::MVT::Glue, llvm::MVT::i1, llvm::MVT::i128, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, isInteger(), isVector(), llvm::MVT::isVoid, llvm_unreachable, llvm::MVT::Metadata, llvm::MVT::Other, llvm::MVT::ppcf128, llvm::MVT::SimpleTy, llvm::MVT::Untyped, llvm::utostr(), llvm::MVT::v16f32, llvm::MVT::v16i1, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i64, llvm::MVT::v16i8, llvm::MVT::v1f32, llvm::MVT::v1f64, llvm::MVT::v1i128, llvm::MVT::v1i16, llvm::MVT::v1i32, llvm::MVT::v1i64, llvm::MVT::v1i8, llvm::MVT::v2f16, llvm::MVT::v2f32, llvm::MVT::v2f64, llvm::MVT::v2i1, llvm::MVT::v2i16, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v2i8, llvm::MVT::v32i1, llvm::MVT::v32i16, llvm::MVT::v32i8, llvm::MVT::v4f16, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i1, llvm::MVT::v4i16, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v4i8, llvm::MVT::v64i1, llvm::MVT::v64i8, llvm::MVT::v8f16, llvm::MVT::v8f32, llvm::MVT::v8f64, llvm::MVT::v8i1, llvm::MVT::v8i16, llvm::MVT::v8i32, llvm::MVT::v8i64, llvm::MVT::v8i8, and llvm::MVT::x86mmx.
Referenced by llvm::CCState::AnalyzeCallOperands(), llvm::CCState::AnalyzeCallResult(), llvm::CCState::AnalyzeFormalArguments(), llvm::CCState::AnalyzeReturn(), getEVTString(), getMangledTypeStr(), llvm::CCState::getRemainingRegParmsForType(), and llvm::SDNode::print_types().
static EVT llvm::EVT::getFloatingPointVT (unsigned BitWidth) [inline, static]
getFloatingPointVT - Returns the EVT that represents a floating point type with the given number of bits.
There are two floating point types with 128 bits - this returns f128 rather than ppcf128.
Definition at line 55 of file ValueTypes.h.
Referenced by combineConcatVectorOfScalars(), lowerFP_TO_SINT_STORE(), and LowerVECTOR_SHUFFLE().
EVT llvm::EVT::getHalfSizedIntegerVT (LLVMContext & Context) const [inline]
getHalfSizedIntegerVT - Finds the smallest simple value type that is greater than or equal to half the width of this EVT.
If no simple value type can be found, an extended integer value type of half the size (rounded up) is returned.
Definition at line 270 of file ValueTypes.h.
References EVT(), llvm::MVT::FIRST_INTEGER_VALUETYPE, getIntegerVT(), getSizeInBits(), isInteger(), isVector(), and llvm::MVT::LAST_INTEGER_VALUETYPE.
Referenced by ExpandUnalignedStore(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), and llvm::AMDGPUTargetLowering::LowerUDIVREM64().
static EVT llvm::EVT::getIntegerVT (LLVMContext & Context, unsigned BitWidth) [inline, static]
getIntegerVT - Returns the EVT that represents an integer with the given number of bits.
Definition at line 61 of file ValueTypes.h.
References llvm::MVT::SimpleTy.
Referenced by changeVectorElementTypeToInteger(), combineConcatVectorOfScalars(), llvm::TargetLowering::expandFP_TO_SINT(), ExpandUnalignedLoad(), ExpandUnalignedStore(), getCopyFromParts(), getCopyToParts(), llvm::AMDGPUTargetLowering::getEquivalentLoadRegType(), llvm::AMDGPUTargetLowering::getEquivalentMemType(), getEVT(), getHalfSizedIntegerVT(), getMemsetValue(), getRoundIntegerType(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::FastISel::selectFNeg(), llvm::TargetLowering::TargetLoweringOpt::ShrinkDemandedOp(), llvm::TargetLowering::SimplifySetCC(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), and widenIntegerVectorElementType().
EVT llvm::EVT::getPow2VectorType (LLVMContext & Context) const [inline]
getPow2VectorType - Widens the length of the given vector EVT up to the nearest power of 2 and returns that type.
Definition at line 298 of file ValueTypes.h.
References getVectorElementType(), getVectorNumElements(), getVectorVT(), isPow2VectorType(), and llvm::Log2_32_Ceil().
intptr_t llvm::EVT::getRawBits () const [inline]
Definition at line 323 of file ValueTypes.h.
References isSimple(), and llvm::MVT::SimpleTy.
Referenced by AddNodeIDCustom(), llvm::SelectionDAG::getAtomic(), llvm::SelectionDAG::getIndexedStore(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMaskedGather(), llvm::SelectionDAG::getMaskedLoad(), llvm::SelectionDAG::getMaskedScatter(), llvm::SelectionDAG::getTruncStore(), and llvm::SelectionDAG::getVTList().
EVT llvm::EVT::getRoundIntegerType (LLVMContext & Context) const [inline]
getRoundIntegerType - Rounds the bit-width of the given integer EVT up to the nearest power of two (and at least to eight), and returns the integer EVT with that number of bits.
Definition at line 258 of file ValueTypes.h.
References EVT(), getIntegerVT(), getSizeInBits(), llvm::MVT::i8, isInteger(), isVector(), and llvm::Log2_32_Ceil().
unsigned llvm::EVT::getScalarSizeInBits () const [inline]
Definition at line 239 of file ValueTypes.h.
References getScalarType(), and getSizeInBits().
Referenced by llvm::TargetLowering::BuildSDIV(), CombineBaseUpdate(), FoldIntToFPToInt(), llvm::SelectionDAG::getNode(), llvm::R600TargetLowering::LowerFormalArguments(), LowerINTRINSIC_W_CHAIN(), LowerVectorFP_TO_INT(), LowerVectorINT_TO_FP(), performConcatVectorsCombine(), performPostLD1Combine(), PerformSExtCombine(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), and VectorZextCombine().
EVT llvm::EVT::getScalarType () const [inline]
getScalarType - If this is a vector type, return the element type, otherwise return this.
Definition at line 210 of file ValueTypes.h.
References getVectorElementType(), and isVector().
Referenced by llvm::SelectionDAG::computeKnownBits(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::SelectionDAG::EVTToAPFloatSemantics(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), getCopyFromPartsVector(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getLogicalNOT(), getMemsetValue(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNOT(), llvm::SITargetLowering::getPreferredVectorAction(), llvm::NVPTXTargetLowering::getPreferredVectorAction(), getScalarSizeInBits(), llvm::SDValue::getScalarValueSizeInBits(), llvm::SelectionDAG::getTruncStore(), getUniformBase(), getUsefulBits(), llvm::SelectionDAG::getZeroExtendInReg(), getZeroVector(), Insert128BitVector(), isConstOrConstSplat(), llvm::SITargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::AArch64TargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::SystemZTargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::PPCTargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::AMDGPUTargetLowering::isFPImmLegal(), llvm::AMDGPUTargetLowering::isLoadBitCastBeneficial(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), LowerExtendedLoad(), LowerIntVSETCC_AVX512(), llvm::AMDGPUTargetLowering::LowerLOAD(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformFMACombine(), PerformISDSETCCCombine(), PerformLOADCombine(), PerformMLOADCombine(), PerformMSTORECombine(), PerformSELECTCombine(), PerformSExtCombine(), PerformSTORECombine(), llvm::AMDGPUTargetLowering::ShouldShrinkFPConstant(), llvm::SelectionDAG::SignBitIsZero(), llvm::TargetLowering::SimplifyDemandedBits(), tryToFoldExtendOfConstant(), ValueHasExactlyOneBitSet(), and WidenMaskArithmetic().
MVT llvm::EVT::getSimpleVT () const [inline]
getSimpleVT - Return the SimpleValueType held in the specified simple EVT.
Definition at line 203 of file ValueTypes.h.
References isSimple().
Referenced by AddCombineToVPADDL(), llvm::MipsSETargetLowering::allowsMisalignedMemoryAccesses(), llvm::ARMTargetLowering::allowsMisalignedMemoryAccesses(), llvm::PPCTargetLowering::allowsMisalignedMemoryAccesses(), changeVectorElementTypeToInteger(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), createSplat(), llvm::SelectionDAG::EVTToAPFloatSemantics(), llvm::PPCTargetLowering::expandVSXLoadForLE(), llvm::PPCTargetLowering::expandVSXStoreForLE(), FindOptimalMemOpLowering(), llvm::SelectionDAG::FoldSetCC(), llvm::X86TTIImpl::getCastInstrCost(), llvm::ARMTTIImpl::getCastInstrCost(), llvm::AArch64TTIImpl::getCastInstrCost(), llvm::ARMTTIImpl::getCmpSelInstrCost(), llvm::AArch64TTIImpl::getCmpSelInstrCost(), getExtensionTo64Bits(), llvm::TargetLoweringBase::getLoadExtAction(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getMemoryOpCost(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getNumRegisters(), llvm::TargetLoweringBase::getOperationAction(), llvm::AArch64TargetLowering::getPreferredVectorAction(), llvm::FastISel::getRegForGEPIndex(), llvm::FastISel::getRegForValue(), llvm::TargetLoweringBase::getRegisterType(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::TargetLoweringBase::getSimpleValueType(), llvm::TargetLoweringBase::getTruncStoreAction(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::SelectionDAG::getValueType(), llvm::TargetLoweringBase::getVectorTypeBreakdown(), llvm::ISD::InputArg::InputArg(), Insert128BitVector(), is32Bit(), llvm::SITargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::AArch64TargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::SystemZTargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::PPCTargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::TargetLoweringBase::isIndexedLoadLegal(), llvm::TargetLoweringBase::isIndexedStoreLegal(), isLegalAddressImmediate(), llvm::ARMTargetLowering::isLegalAddressingMode(), isLegalT1AddressImmediate(), isLegalT2AddressImmediate(), llvm::ARMTargetLowering::isLegalT2ScaledAddressingMode(), llvm::HexagonTargetLowering::isTruncateFree(), llvm::TargetLoweringBase::isTruncStoreLegal(), llvm::TargetLoweringBase::isTypeLegal(), isValidIndexedLoad(), llvm::XCoreTargetLowering::isZExtFree(), llvm::ARMTargetLowering::isZExtFree(), llvm::HexagonTargetLowering::LowerBUILD_VECTOR(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), llvm::HexagonTargetLowering::LowerEXTRACT_VECTOR(), llvm::SystemZTargetLowering::LowerFormalArguments(), LowerVECTOR_SHIFT(), matchIntegerMINMAX(), NarrowVector(), llvm::ISD::OutputArg::OutputArg(), performBitcastCombine(), performConcatVectorsCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::FastISel::selectBinaryOp(), llvm::FastISel::selectBitCast(), llvm::FastISel::selectCast(), llvm::FastISel::selectExtractValue(), llvm::FastISel::selectFNeg(), llvm::TargetLowering::SimplifySetCC(), llvm::SelectionDAGBuilder::visitBitTestHeader(), WidenVector(), X86ChooseCmpImmediateOpcode(), X86ChooseCmpOpcode(), and XFormVExtractWithShuffleIntoLoad().
unsigned llvm::EVT::getSizeInBits () const [inline]
getSizeInBits - Return the size of the specified value type in bits.
Definition at line 233 of file ValueTypes.h.
References llvm::MVT::getSizeInBits(), and isSimple().
Referenced by addRequiredExtensionForVectorMULL(), AddRequiredExtensionForVMULL(), bitsEq(), bitsGE(), bitsGT(), bitsLE(), bitsLT(), BuildVectorFromScalar(), CalculateTailCallArgDest(), canTreatAsByteVector(), CombineBaseUpdate(), combineConcatVectorOfScalars(), llvm::SelectionDAG::computeKnownBits(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), ConvertI1VectorToInterger(), EltsFromConsecutiveLoads(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), EmitVectorComparison(), llvm::TargetLowering::expandFP_TO_SINT(), llvm::TargetLowering::expandMUL(), ExpandUnalignedLoad(), ExpandUnalignedStore(), ExtractSubVector(), FindMemType(), FindOptimalMemOpLowering(), genConstMult(), GeneratePerfectShuffle(), GenerateTBL(), llvm::SelectionDAG::getAnyExtendVectorInReg(), llvm::SelectionDAG::getConstant(), getCopyFromParts(), getCopyFromPartsVector(), getCopyToParts(), getCopyToPartsVector(), getEVTString(), getExtensionTo64Bits(), getExtFactor(), getHalfSizedIntegerVT(), getLeftShift(), llvm::SelectionDAG::getLogicalNOT(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), getMemsetStringVal(), getMemsetValue(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNOT(), llvm::TargetLoweringBase::getNumRegisters(), llvm::HexagonTargetLowering::getPostIndexedAddressParts(), llvm::SystemZTargetLowering::getPreferredVectorAction(), getRoundIntegerType(), getScalarSizeInBits(), llvm::SDValue::getScalarValueSizeInBits(), llvm::SelectionDAG::getSignExtendVectorInReg(), getStoreSize(), getTargetShuffleMask(), getUsefulBits(), llvm::SDValue::getValueSizeInBits(), llvm::SDNode::getValueSizeInBits(), getVectorMaskingNode(), llvm::TargetLoweringBase::getVectorTypeBreakdown(), llvm::SelectionDAG::getZeroExtendInReg(), llvm::SelectionDAG::getZeroExtendVectorInReg(), llvm::AArch64TargetLowering::hasPairedLoad(), InsertSubVector(), isBitfieldDstMask(), isBitfieldExtractOpFromShr(), isBitfieldPositioningOp(), llvm::ISD::isBuildVectorAllOnes(), llvm::ISD::isBuildVectorAllZeros(), isByteSized(), isConcatMask(), isConditionalZeroOrAllOnes(), llvm::SelectionDAG::isConsecutiveLoad(), isConsecutiveLSLoc(), llvm::BuildVectorSDNode::isConstantSplat(), isConstantSplatVector(), isExtendedBUILD_VECTOR(), isI24(), llvm::AMDGPUTargetLowering::isLoadBitCastBeneficial(), IsMulWideOperandDemotable(), llvm::AMDGPUTargetLowering::isNarrowingProfitable(), isREVMask(), isRound(), llvm::AArch64TargetLowering::isShuffleMaskLegal(), llvm::ARMTargetLowering::isShuffleMaskLegal(), isSimpleShift(), llvm::MSP430TargetLowering::isTruncateFree(), llvm::AMDGPUTargetLowering::isTruncateFree(), llvm::AArch64TargetLowering::isTruncateFree(), llvm::SystemZTargetLowering::isTruncateFree(), llvm::PPCTargetLowering::isTruncateFree(), isU24(), isVREVMask(), isVShiftLImm(), isVShiftRImm(), isVTRN_v_undef_Mask(), isVTRNMask(), isVUZP_v_undef_Mask(), isVUZPMask(), isVZIP_v_undef_Mask(), isVZIPMask(), llvm::AArch64TargetLowering::isZExtFree(), llvm::HexagonTargetLowering::LowerBUILD_VECTOR(), llvm::NVPTXTargetLowering::LowerCall(), llvm::TargetLowering::LowerCallTo(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), LowerExtendedLoad(), llvm::HexagonTargetLowering::LowerEXTRACT_VECTOR(), LowerEXTRACT_VECTOR_ELT(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerINSERT_VECTOR(), LowerINTRINSIC_WO_CHAIN(), LowerIntVSETCC_AVX512(), llvm::AMDGPUTargetLowering::LowerLOAD(), lowerMSABitClearImm(), llvm::NVPTXTargetLowering::LowerReturn(), LowerShift(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), LowerVAARG(), LowerVECTOR_SHUFFLE(), LowerVectorBroadcast(), LowerVectorFP_TO_INT(), LowerVectorINT_TO_FP(), LowerVSETCC(), MatchingStackOffset(), NormalizeBuildVector(), performANDCombine(), PerformAndCombine(), PerformARMBUILD_VECTORCombine(), performConcatVectorsCombine(), llvm::SystemZTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performDSPShiftCombine(), performExtendCombine(), PerformEXTRACT_VECTOR_ELTCombine(), performIntegerAbsCombine(), PerformINTRINSIC_WO_CHAINCombine(), performIntToFpCombine(), PerformLOADCombine(), PerformMLOADCombine(), PerformMSTORECombine(), performNEONPostLDSTCombine(), performORCombine(), PerformOrCombine(), performSelectCombine(), PerformSELECTCombine(), PerformSExtCombine(), performShiftToAllZeros(), PerformSIGN_EXTEND_INREGCombine(), performSRACombine(), performSTORECombine(), PerformSTORECombine(), PerformVDUPLANECombine(), performVectorCompareAndMaskUnaryOpCombine(), performVSelectCombine(), PerformVZEXT_MOVLCombine(), llvm::AArch64TargetLowering::ReconstructShuffle(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), resolveBuildVector(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::FastISel::selectFNeg(), llvm::HexagonTargetLowering::shouldExpandBuildVectorWithShuffles(), llvm::SelectionDAG::SignBitIsZero(), llvm::TargetLowering::SimplifyDemandedBits(), simplifyI24(), llvm::TargetLowering::SimplifySetCC(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), toIntegerVT(), tryCombineFixedPointConvert(), tryCombineToBSL(), tryCombineToEXTR(), tryFormConcatFromShuffle(), tryLowerToSLI(), TryMULWIDECombine(), tryToFoldExtendOfConstant(), UnpackFromArgumentSlot(), ValueHasExactlyOneBitSet(), VerifySDNode(), llvm::SelectionDAGBuilder::visitBitTestHeader(), widenIntegerVectorElementType(), and WidenMaskArithmetic().
unsigned llvm::EVT::getStoreSize () const [inline]
getStoreSize - Return the number of bytes overwritten by a store of the specified value type.
Definition at line 245 of file ValueTypes.h.
References getSizeInBits().
Referenced by CalculateStackSlotAlignment(), CalculateStackSlotSize(), ComputePTXValueVTs(), llvm::SelectionDAG::CreateStackTemporary(), findConsecutiveLoad(), llvm::SelectionDAG::getAtomic(), llvm::SelectionDAG::getAtomicCmpSwap(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SelectionDAG::getStore(), getStoreSizeInBits(), llvm::PPCTargetLowering::getTgtMemIntrinsic(), llvm::SelectionDAG::getTruncStore(), getVPermMask(), llvm::SITargetLowering::LowerFormalArguments(), llvm::MemSDNode::MemSDNode(), llvm::SystemZTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::AMDGPUTargetLowering::ScalarizeVectorLoad(), ShrinkLoadReplaceStoreWithStore(), llvm::AMDGPUTargetLowering::SplitVectorStore(), and tryBuildVectorByteMask().
unsigned llvm::EVT::getStoreSizeInBits () const [inline]
getStoreSizeInBits - Return the number of bits overwritten by a store of the specified value type.
Definition at line 251 of file ValueTypes.h.
References getStoreSize().
Referenced by llvm::SelectionDAG::CreateStackTemporary(), llvm::AMDGPUTargetLowering::getEquivalentLoadRegType(), llvm::AMDGPUTargetLowering::getEquivalentMemType(), llvm::NVPTXTargetLowering::LowerCall(), and llvm::AMDGPUTargetLowering::shouldReduceLoadWidth().
Type * EVT::getTypeForEVT (LLVMContext & Context) const
getTypeForEVT - This method returns an LLVM type corresponding to the specified EVT.
For integer types, this returns an unsigned type. Note that this will abort for types that cannot be represented.
Definition at line 181 of file ValueTypes.cpp.
References llvm::MVT::f128, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, llvm::IntegerType::get(), llvm::VectorType::get(), llvm::Type::getDoubleTy(), llvm::Type::getFloatTy(), llvm::Type::getFP128Ty(), llvm::Type::getHalfTy(), llvm::Type::getInt128Ty(), llvm::Type::getInt16Ty(), llvm::Type::getInt1Ty(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::Type::getInt8Ty(), llvm::Type::getMetadataTy(), llvm::Type::getPPC_FP128Ty(), llvm::Type::getVoidTy(), llvm::Type::getX86_FP80Ty(), llvm::Type::getX86_MMXTy(), llvm::MVT::i1, llvm::MVT::i128, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, isExtended(), llvm::MVT::isVoid, llvm::MVT::Metadata, llvm::MVT::ppcf128, llvm::MVT::SimpleTy, llvm::MVT::v16f32, llvm::MVT::v16i1, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i64, llvm::MVT::v16i8, llvm::MVT::v1f32, llvm::MVT::v1f64, llvm::MVT::v1i128, llvm::MVT::v1i16, llvm::MVT::v1i32, llvm::MVT::v1i64, llvm::MVT::v1i8, llvm::MVT::v2f16, llvm::MVT::v2f32, llvm::MVT::v2f64, llvm::MVT::v2i1, llvm::MVT::v2i16, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v2i8, llvm::MVT::v32i1, llvm::MVT::v32i16, llvm::MVT::v32i8, llvm::MVT::v4f16, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i1, llvm::MVT::v4i16, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v4i8, llvm::MVT::v64i1, llvm::MVT::v64i8, llvm::MVT::v8f16, llvm::MVT::v8f32, llvm::MVT::v8f64, llvm::MVT::v8i1, llvm::MVT::v8i16, llvm::MVT::v8i32, llvm::MVT::v8i64, llvm::MVT::v8i8, and llvm::MVT::x86mmx.
Referenced by allowableAlignment(), canFoldInAddressingMode(), llvm::SelectionDAG::CreateStackTemporary(), llvm::SelectionDAG::getEVTAlignment(), llvm::SelectionDAG::getMemset(), getMemsetStringVal(), llvm::TargetLoweringBase::getValueType(), llvm::NVPTXTargetLowering::LowerCall(), llvm::TargetLowering::LowerCallTo(), llvm::SparcTargetLowering::LowerF128_LibCallArg(), llvm::SparcTargetLowering::LowerF128Op(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), LowerFSINCOS(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::TargetLowering::makeLibCall(), llvm::PPCTargetLowering::PerformDAGCombine(), ReplaceLoadVector(), and XFormVExtractWithShuffleIntoLoad().
EVT llvm::EVT::getVectorElementType () const [inline]
getVectorElementType - Given a vector type, return the type of each element.
Definition at line 216 of file ValueTypes.h.
References llvm::MVT::getVectorElementType(), isSimple(), and isVector().
Referenced by AddCombineToVPADDL(), canTreatAsByteVector(), ComputePTXValueVTs(), EltsFromConsecutiveLoads(), EmitVectorComparison(), ExtractSubVector(), llvm::SelectionDAG::ExtractVectorElements(), FindMemType(), GeneratePerfectShuffle(), GenerateTBL(), getCopyFromPartsVector(), getCopyToPartsVector(), getEVTString(), getExtFactor(), getMemsetStringVal(), getMemsetValue(), llvm::SelectionDAG::getNode(), getPow2VectorType(), llvm::SystemZTargetLowering::getPreferredVectorAction(), getScalarType(), getShuffleScalarElt(), llvm::SelectionDAG::GetSplitDestVTs(), getTargetShuffleMask(), llvm::TargetLoweringBase::getVectorTypeBreakdown(), getVPermMask(), InsertSubVector(), llvm::ISD::isBuildVectorAllOnes(), llvm::ISD::isBuildVectorAllZeros(), llvm::BuildVectorSDNode::isConstantSplat(), isConstantSplatVector(), isExtendedBUILD_VECTOR(), isREVMask(), llvm::ARMTargetLowering::isShuffleMaskLegal(), isVREVMask(), isVShiftLImm(), isVShiftRImm(), isVTRN_v_undef_Mask(), isVTRNMask(), isVUZP_v_undef_Mask(), isVUZPMask(), isVZIP_v_undef_Mask(), isVZIPMask(), LowerBoolVSETCC_AVX512(), llvm::HexagonTargetLowering::LowerBUILD_VECTOR(), llvm::NVPTXTargetLowering::LowerCall(), LowerCTPOP(), LowerExtendedLoad(), llvm::HexagonTargetLowering::LowerEXTRACT_VECTOR(), LowerEXTRACT_VECTOR_ELT(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerINSERT_VECTOR(), LowerIntVSETCC_AVX512(), lowerMSABitClearImm(), lowerMSACopyIntr(), llvm::NVPTXTargetLowering::LowerReturn(), LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE_VSHF(), LowerVectorFP_TO_INT(), LowerVectorINT_TO_FP(), LowerVSETCC(), NarrowVector(), NormalizeBuildVector(), PerformARMBUILD_VECTORCombine(), PerformBUILD_VECTORCombine(), performConcatVectorsCombine(), llvm::SystemZTargetLowering::PerformDAGCombine(), performDSPShiftCombine(), performExtendCombine(), PerformEXTRACT_VECTOR_ELTCombine(), PerformInsertEltCombine(), PerformINTRINSIC_WO_CHAINCombine(), PerformMLOADCombine(), PerformMSTORECombine(), PerformOrCombine(), performPostLD1Combine(), PerformSELECTCombine(), performShiftToAllZeros(), PerformShuffleCombine(), performSTORECombine(), PerformSTORECombine(), PerformVDUPLANECombine(), performVSelectCombine(), PerformVZEXT_MOVLCombine(), llvm::AArch64TargetLowering::ReconstructShuffle(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::AMDGPUTargetLowering::ScalarizeVectorLoad(), llvm::AMDGPUTargetLowering::ScalarizeVectorStore(), llvm::HexagonTargetLowering::shouldExpandBuildVectorWithShuffles(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), tryBuildVectorByteMask(), tryBuildVectorShuffle(), tryCombineToBSL(), tryFormConcatFromShuffle(), tryLowerToSLI(), llvm::SelectionDAG::UnrollVectorOp(), VerifySDNode(), widenIntegerVectorElementType(), and WidenVector().
unsigned llvm::EVT::getVectorNumElements () const [inline]
getVectorNumElements - Given a vector type, return the number of elements it contains.
Definition at line 225 of file ValueTypes.h.
References llvm::MVT::getVectorNumElements(), isSimple(), and isVector().
Referenced by AddCombineToVPADDL(), AddNodeIDCustom(), buildScalarToVector(), BuildSplatI(), changeVectorElementTypeToInteger(), CombineBaseUpdate(), ComputePTXValueVTs(), ConvertSelectToConcatVector(), ExpandBITCAST(), ExpandHorizontalBinOp(), ExtractSubVector(), llvm::SelectionDAG::ExtractVectorElements(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::SelectionDAG::getAnyExtendVectorInReg(), getBuildVectorSplat(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), getCopyFromPartsVector(), getCopyToPartsVector(), getEVTString(), llvm::SelectionDAG::getLoad(), llvm::ShuffleVectorSDNode::getMask(), getMemsetStringVal(), getMemsetValue(), getMOVL(), llvm::SelectionDAG::getNode(), getPow2VectorType(), llvm::SITargetLowering::getPreferredVectorAction(), llvm::TargetLoweringBase::getPreferredVectorAction(), llvm::NVPTXTargetLowering::getPreferredVectorAction(), llvm::SITargetLowering::getSetCCResultType(), llvm::HexagonTargetLowering::getSetCCResultType(), llvm::PPCTargetLowering::getSetCCResultType(), llvm::NVPTXTargetLowering::getSetCCResultType(), getShuffleScalarElt(), llvm::SelectionDAG::getSignExtendVectorInReg(), llvm::ShuffleVectorSDNode::getSplatIndex(), llvm::SelectionDAG::GetSplitDestVTs(), llvm::SelectionDAG::getTruncStore(), getVectorMaskingNode(), llvm::SelectionDAG::getVectorShuffle(), llvm::TargetLoweringBase::getVectorTypeBreakdown(), getVPermMask(), llvm::SelectionDAG::getZeroExtendVectorInReg(), getZeroVector(), hasNormalLoadOperand(), isAllConstantBuildVector(), isConcatMask(), isConstVecPow2(), isEXTMask(), isHorizontalBinOp(), isPow2VectorType(), isReverseMask(), isREVMask(), isShuffleHigh128VectorInsertLow(), isShuffleLow128VectorInsertHigh(), llvm::AArch64TargetLowering::isShuffleMaskLegal(), llvm::ARMTargetLowering::isShuffleMaskLegal(), isSingletonEXTMask(), isSingletonVEXTMask(), llvm::ShuffleVectorSDNode::isSplatMask(), isTRN_v_undef_Mask(), isTRNMask(), isUZP_v_undef_Mask(), isUZPMask(), isVEXTMask(), isVREVMask(), isVTRN_v_undef_Mask(), isVTRNMask(), isVUZP_v_undef_Mask(), isVUZPMask(), isVZIP_v_undef_Mask(), isVZIPMask(), isZIP_v_undef_Mask(), isZIPMask(), llvm::NVPTXTargetLowering::LowerCall(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::HexagonTargetLowering::LowerEXTRACT_VECTOR(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerINSERT_VECTOR(), LowerINTRINSIC_WO_CHAIN(), lowerMSASplatZExt(), llvm::NVPTXTargetLowering::LowerReturn(), LowerScalarVariableShift(), LowerToAddSub(), LowerToHorizontalOp(), lowerUINT_TO_FP_vXi32(), LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE_VSHF(), LowerVectorAllZeroTest(), LowerVectorFP_TO_INT(), LowerVectorINT_TO_FP(), NarrowVector(), NormalizeBuildVector(), partitionShuffleOfConcats(), PerformARMBUILD_VECTORCombine(), performBitcastCombine(), PerformBUILD_VECTORCombine(), performConcatVectorsCombine(), llvm::R600TargetLowering::PerformDAGCombine(), performExtendCombine(), PerformInsertEltCombine(), PerformMLOADCombine(), PerformMSTORECombine(), performNEONPostLDSTCombine(), PerformSELECTCombine(), PerformShuffleCombine(), PerformShuffleCombine256(), PerformSINT_TO_FPCombine(), performSTORECombine(), PerformSTORECombine(), PerformVCVTCombine(), PerformVDIVCombine(), PerformVECTOR_SHUFFLECombine(), performVSelectCombine(), llvm::AArch64TargetLowering::ReconstructShuffle(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), replaceSplatVectorStore(), llvm::AMDGPUTargetLowering::ScalarizeVectorLoad(), llvm::AMDGPUTargetLowering::ScalarizeVectorStore(), simplifyShuffleOperandRecursively(), simplifyShuffleOperands(), llvm::SelectionDAG::SplitVector(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), llvm::AMDGPUTargetLowering::SplitVectorStore(), tryBuildVectorShuffle(), tryCombineToBSL(), tryFormConcatFromShuffle(), tryToFoldExtendOfConstant(), VerifySDNode(), widenIntegerVectorElementType(), WidenMaskArithmetic(), WidenVector(), and XFormVExtractWithShuffleIntoLoad().
static EVT llvm::EVT::getVectorVT (LLVMContext & Context, EVT VT, unsigned NumElements) [inline, static]
getVectorVT - Returns the EVT that represents a vector NumElements in length, where each element is of type VT.
Definition at line 70 of file ValueTypes.h.
References llvm::MVT::SimpleTy.
Referenced by BuildVectorFromScalar(), changeVectorElementTypeToInteger(), combineConcatVectorOfScalars(), llvm::SelectionDAG::getConstant(), llvm::AMDGPUTargetLowering::getEquivalentLoadRegType(), llvm::AMDGPUTargetLowering::getEquivalentMemType(), getEVT(), getMemsetStringVal(), getPow2VectorType(), llvm::SITargetLowering::getSetCCResultType(), llvm::HexagonTargetLowering::getSetCCResultType(), llvm::PPCTargetLowering::getSetCCResultType(), llvm::NVPTXTargetLowering::getSetCCResultType(), llvm::SelectionDAG::GetSplitDestVTs(), llvm::AArch64TargetLowering::getTgtMemIntrinsic(), llvm::ARMTargetLowering::getTgtMemIntrinsic(), llvm::TargetLoweringBase::getValueType(), llvm::TargetLoweringBase::getVectorTypeBreakdown(), llvm::NVPTXTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerReturn(), LowerVECTOR_SHUFFLE(), PerformARMBUILD_VECTORCombine(), PerformBUILD_VECTORCombine(), performExtendCombine(), PerformInsertEltCombine(), performSelectCombine(), performSTORECombine(), PerformSTORECombine(), llvm::AArch64TargetLowering::ReconstructShuffle(), tryFormConcatFromShuffle(), llvm::SelectionDAG::UnrollVectorOp(), and widenIntegerVectorElementType().
bool llvm::EVT::is1024BitVector () const [inline]
is1024BitVector - Return true if this is a 1024-bit vector type.
Definition at line 150 of file ValueTypes.h.
References llvm::MVT::is1024BitVector(), and isSimple().
bool llvm::EVT::is128BitVector () const [inline]
is128BitVector - Return true if this is a 128-bit vector type.
Definition at line 135 of file ValueTypes.h.
References llvm::MVT::is128BitVector(), and isSimple().
Referenced by addRequiredExtensionForVectorMULL(), AddRequiredExtensionForVMULL(), getVShift(), getZeroVector(), Insert128BitVector(), llvm::AArch64TargetLowering::isShuffleMaskLegal(), llvm::ARMTargetLowering::isShuffleMaskLegal(), LowerCONCAT_VECTORS(), LowerMUL(), LowerVectorAllZeroTest(), PerformANDCombine(), PerformMULCombine(), performORCombine(), PerformORCombine(), PerformSELECTCombine(), performVSELECTCombine(), performXORCombine(), and WidenMaskArithmetic().
bool llvm::EVT::is16BitVector () const [inline]
is16BitVector - Return true if this is a 16-bit vector type.
Definition at line 120 of file ValueTypes.h.
References llvm::MVT::is16BitVector(), and isSimple().
bool llvm::EVT::is256BitVector () const [inline]
is256BitVector - Return true if this is a 256-bit vector type.
Definition at line 140 of file ValueTypes.h.
References llvm::MVT::is256BitVector(), and isSimple().
Referenced by CanFoldXORWithAllOnes(), ExpandHorizontalBinOp(), Extract128BitVector(), getZeroVector(), Insert128BitVector(), Insert256BitVector(), LowerVectorAllZeroTest(), PerformSELECTCombine(), PerformShuffleCombine(), PerformZExtCombine(), and WidenMaskArithmetic().
bool llvm::EVT::is32BitVector () const [inline]
is32BitVector - Return true if this is a 32-bit vector type.
Definition at line 125 of file ValueTypes.h.
References llvm::MVT::is32BitVector(), and isSimple().
bool llvm::EVT::is512BitVector () const [inline]
is512BitVector - Return true if this is a 512-bit vector type.
Definition at line 145 of file ValueTypes.h.
References llvm::MVT::is512BitVector(), and isSimple().
Referenced by Extract128BitVector(), Extract256BitVector(), getZeroVector(), LowerMGATHER(), LowerMSCATTER(), LowerVSETCC(), and PerformSELECTCombine().
bool llvm::EVT::is64BitVector () const [inline]
is64BitVector - Return true if this is a 64-bit vector type.
Definition at line 130 of file ValueTypes.h.
References llvm::MVT::is64BitVector(), and isSimple().
Referenced by CombineVLDDUP(), getCTPOP16BitCounts(), llvm::AArch64TargetLowering::isShuffleMaskLegal(), llvm::ARMTargetLowering::isShuffleMaskLegal(), isVUZP_v_undef_Mask(), isVUZPMask(), isVZIP_v_undef_Mask(), isVZIPMask(), lowerCTPOP16BitElements(), lowerCTPOP32BitElements(), LowerMUL(), PerformMULCombine(), and tryCombineLongOpWithDup().
bool llvm::EVT::isByteSized () const [inline]
isByteSized - Return true if the bit size is a multiple of 8.
Definition at line 160 of file ValueTypes.h.
References getSizeInBits().
bool llvm::EVT::isExtended () const [inline]
isExtended - Test if the given EVT is extended (as opposed to being simple).
Definition at line 100 of file ValueTypes.h.
References isSimple().
Referenced by llvm::TargetLoweringBase::getLoadExtAction(), llvm::TargetLoweringBase::getOperationAction(), llvm::TargetLoweringBase::getTruncStoreAction(), getTypeForEVT(), and llvm::SelectionDAG::getValueType().
bool llvm::EVT::isFloatingPoint () const [inline]
isFloatingPoint - Return true if this is a FP, or a vector FP type.
Definition at line 105 of file ValueTypes.h.
References llvm::MVT::isFloatingPoint(), and isSimple().
Referenced by combineConcatVectorOfScalars(), createFPCmp(), EmitCMP(), emitComparison(), EmitVectorComparison(), llvm::PPCTargetLowering::enableAggressiveFMAFusion(), ExpandUnalignedLoad(), ExpandUnalignedStore(), FindOptimalMemOpLowering(), llvm::TargetLoweringBase::getBooleanContents(), llvm::ARMTTIImpl::getCastInstrCost(), llvm::SelectionDAG::getConstantFP(), getCopyFromParts(), getCopyToParts(), llvm::SelectionDAG::getNode(), llvm::ARMTargetLowering::getSchedulingPreference(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::AArch64TargetLowering::hasPairedLoad(), llvm::AMDGPUTargetLowering::isFAbsFree(), llvm::TargetLoweringBase::isFAbsFree(), llvm::AMDGPUTargetLowering::isFNegFree(), llvm::TargetLoweringBase::isFNegFree(), llvm::PPCTargetLowering::isFPExtFree(), llvm::TargetLoweringBase::isFPExtFree(), llvm::ConstantFPSDNode::isValueValidForType(), lowerVectorSETCC(), LowerVSETCC(), llvm::TargetLowering::LowerXConstraint(), NormalizeBuildVector(), PerformARMBUILD_VECTORCombine(), PerformSELECTCombine(), replaceSplatVectorStore(), llvm::TargetLowering::SimplifyDemandedBits(), and VerifySDNode().
bool llvm::EVT::isInteger () const [inline]
isInteger - Return true if this is an integer, or a vector integer type.
Definition at line 110 of file ValueTypes.h.
References llvm::MVT::isInteger(), and isSimple().
Referenced by AddCombineToVPADDL(), combineConcatVectorOfScalars(), llvm::SelectionDAG::ComputeNumSignBits(), ExpandUnalignedLoad(), ExpandUnalignedStore(), llvm::SelectionDAG::FoldSetCC(), llvm::ARMTTIImpl::getCastInstrCost(), llvm::SelectionDAG::getConstant(), getCopyFromParts(), getCopyToParts(), getEVTString(), getHalfSizedIntegerVT(), llvm::SelectionDAG::getLoad(), getMemcpyLoadsAndStores(), getMemsetStringVal(), getMemsetValue(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getNumRegisters(), llvm::TargetLoweringBase::getRegisterType(), llvm::GetReturnInfo(), getRoundIntegerType(), llvm::TargetLoweringBase::getShiftAmountTy(), getTargetShuffleMask(), llvm::SelectionDAG::getTruncStore(), llvm::AArch64TargetLowering::hasPairedLoad(), llvm::MSP430TargetLowering::isTruncateFree(), llvm::AArch64TargetLowering::isTruncateFree(), llvm::SystemZTargetLowering::isTruncateFree(), llvm::PPCTargetLowering::isTruncateFree(), llvm::XCoreTargetLowering::isZExtFree(), llvm::ARMTargetLowering::isZExtFree(), llvm::AArch64TargetLowering::isZExtFree(), LowerBR_CC(), llvm::NVPTXTargetLowering::LowerCall(), LowerMUL(), LowerSELECT_CC(), LowerVectorBroadcast(), llvm::TargetLowering::LowerXConstraint(), OptimizeConditionalInDecrement(), OptimizeNoopCopyExpression(), PerformADDCombineWithOperands(), llvm::R600TargetLowering::PerformDAGCombine(), performIntegerAbsCombine(), performSELECTCombine(), PerformSELECTCombine(), performVSELECTCombine(), performXORCombine(), llvm::TargetLowering::SimplifySetCC(), and VerifySDNode().
bool llvm::EVT::isOverloaded () const [inline]
isOverloaded - Return true if this is an overloaded type for TableGen.
Definition at line 155 of file ValueTypes.h.
References llvm::MVT::fAny, llvm::MVT::iAny, llvm::MVT::iPTRAny, and llvm::MVT::vAny.
bool llvm::EVT::isPow2VectorType () const [inline]
isPow2VectorType - Returns true if the given vector is a power of 2.
Definition at line 291 of file ValueTypes.h.
References getVectorNumElements().
Referenced by getPow2VectorType().
bool llvm::EVT::isRound () const [inline]
isRound - Return true if the size is a power-of-two number of bytes.
Definition at line 165 of file ValueTypes.h.
References getSizeInBits().
Referenced by llvm::TargetLowering::SimplifySetCC().
bool llvm::EVT::isSimple () const [inline]
isSimple - Test if the given EVT is simple (as opposed to being extended).
Definition at line 94 of file ValueTypes.h.
References llvm::MVT::SimpleTy.
Referenced by llvm::SITargetLowering::allowsMisalignedMemoryAccesses(), llvm::PPCTargetLowering::allowsMisalignedMemoryAccesses(), changeVectorElementTypeToInteger(), llvm::X86TTIImpl::getCastInstrCost(), llvm::ARMTTIImpl::getCastInstrCost(), llvm::AArch64TTIImpl::getCastInstrCost(), llvm::ARMTTIImpl::getCmpSelInstrCost(), llvm::AArch64TTIImpl::getCmpSelInstrCost(), getExtensionTo64Bits(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getMemoryOpCost(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getNumRegisters(), getRawBits(), llvm::FastISel::getRegForValue(), llvm::TargetLoweringBase::getRegisterType(), getSimpleVT(), getSizeInBits(), llvm::SelectionDAG::getValueType(), getVectorElementType(), getVectorMaskingNode(), getVectorNumElements(), llvm::AArch64TargetLowering::hasPairedLoad(), is1024BitVector(), is128BitVector(), is16BitVector(), is256BitVector(), is32BitVector(), is512BitVector(), is64BitVector(), isExtended(), isFloatingPoint(), llvm::SITargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::AArch64TargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::SystemZTargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::PPCTargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::TargetLoweringBase::isIndexedLoadLegal(), llvm::TargetLoweringBase::isIndexedStoreLegal(), isInteger(), isLegalAddressImmediate(), llvm::ARMTargetLowering::isLegalAddressingMode(), llvm::TargetLoweringBase::isLoadExtLegal(), llvm::TargetLoweringBase::isLoadExtLegalOrCustom(), llvm::HexagonTargetLowering::isTruncateFree(), llvm::TargetLoweringBase::isTruncStoreLegal(), llvm::TargetLoweringBase::isTypeLegal(), isVector(), llvm::XCoreTargetLowering::isZExtFree(), llvm::ARMTargetLowering::isZExtFree(), llvm::AArch64TargetLowering::isZExtFree(), llvm::PPCTargetLowering::PerformDAGCombine(), performExtendCombine(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::FastISel::selectBinaryOp(), llvm::FastISel::selectCast(), llvm::FastISel::selectExtractValue(), and llvm::TargetLowering::SimplifyDemandedBits().
bool llvm::EVT::isVector () const [inline]
isVector - Return true if this is a vector value type.
Definition at line 115 of file ValueTypes.h.
References isSimple(), and llvm::MVT::isVector().
Referenced by canTreatAsByteVector(), combineConcatVectorOfScalars(), llvm::SelectionDAG::computeKnownBits(), llvm::SelectionDAG::ComputeNumSignBits(), ComputePTXValueVTs(), ExpandBITCAST(), ExpandUnalignedLoad(), ExpandUnalignedStore(), FindOptimalMemOpLowering(), llvm::SelectionDAG::FoldConstantArithmetic(), FoldOperand(), llvm::SelectionDAG::getAnyExtendVectorInReg(), llvm::TargetLoweringBase::getBooleanContents(), llvm::ARMTTIImpl::getCastInstrCost(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), getCopyFromParts(), getCopyFromPartsVector(), getCopyToParts(), getCopyToPartsVector(), getEVTString(), getHalfSizedIntegerVT(), llvm::SelectionDAG::getLoad(), getMemcpyLoadsAndStores(), getMemsetStores(), getMemsetStringVal(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getNumRegisters(), llvm::AMDGPUTargetLowering::getOriginalFunctionArgs(), llvm::PPCTargetLowering::getPreIndexedAddressParts(), llvm::TargetLoweringBase::getRegisterType(), getRoundIntegerType(), getScalarType(), llvm::ARMTargetLowering::getSchedulingPreference(), llvm::SelectionDAG::getSelect(), llvm::SelectionDAG::getSetCC(), llvm::R600TargetLowering::getSetCCResultType(), llvm::SparcTargetLowering::getSetCCResultType(), llvm::SITargetLowering::getSetCCResultType(), llvm::HexagonTargetLowering::getSetCCResultType(), llvm::MipsTargetLowering::getSetCCResultType(), llvm::ARMTargetLowering::getSetCCResultType(), llvm::AArch64TargetLowering::getSetCCResultType(), llvm::TargetLoweringBase::getSetCCResultType(), llvm::SystemZTargetLowering::getSetCCResultType(), llvm::PPCTargetLowering::getSetCCResultType(), llvm::NVPTXTargetLowering::getSetCCResultType(), llvm::SelectionDAG::getShiftAmountOperand(), llvm::TargetLoweringBase::getShiftAmountTy(), getShuffleScalarElt(), llvm::SelectionDAG::getSignExtendVectorInReg(), llvm::SelectionDAG::GetSplitDestVTs(), getTargetShuffleMask(), llvm::SelectionDAG::getTruncStore(), llvm::TargetLoweringBase::getTypeToExpandTo(), getVectorElementType(), getVectorNumElements(), llvm::SelectionDAG::getZeroExtendInReg(), llvm::SelectionDAG::getZeroExtendVectorInReg(), getZeroVector(), llvm::BuildVectorSDNode::isConstantSplat(), isHorizontalBinOp(), llvm::AArch64TargetLowering::isTruncateFree(), isVShiftLImm(), isVShiftRImm(), llvm::AArch64TargetLowering::isZExtFree(), llvm::TargetLowering::LowerCallTo(), LowerCTPOP(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), LowerExtendedLoad(), llvm::HexagonTargetLowering::LowerEXTRACT_VECTOR(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerINSERT_VECTOR(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::HexagonTargetLowering::LowerSETCC(), LowerShift(), llvm::AMDGPUTargetLowering::LowerSTORE(), LowerVectorBroadcast(), matchIntegerMINMAX(), PerformADDCombineWithOperands(), performBitcastCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), performExtendCombine(), PerformINTRINSIC_WO_CHAINCombine(), PerformLOADCombine(), performMULCombine(), PerformORCombine(), performSelectCombine(), PerformSELECTCombine(), PerformSHLCombine(), PerformShuffleCombine(), PerformSIGN_EXTEND_INREGCombine(), PerformSINT_TO_FPCombine(), performSTORECombine(), PerformSTORECombine(), PerformVCVTCombine(), PerformVDIVCombine(), performVectorCompareAndMaskUnaryOpCombine(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::TargetLowering::TargetLoweringOpt::ShrinkDemandedOp(), llvm::SelectionDAG::SignBitIsZero(), llvm::TargetLowering::SimplifyDemandedBits(), toIntegerVT(), tryCombineToBSL(), tryFoldToZero(), tryLowerToSLI(), tryToFoldExtendOfConstant(), llvm::SelectionDAG::UnrollVectorOp(), VerifySDNode(), VerifyVectorType(), and XFormVExtractWithShuffleIntoLoad().
bool llvm::EVT::operator!= (EVT VT) const [inline]
Definition at line 44 of file ValueTypes.h.
References llvm::MVT::SimpleTy.
bool llvm::EVT::operator== (EVT VT) const [inline]
Definition at line 41 of file ValueTypes.h.
EVT llvm::EVT::widenIntegerVectorElementType (LLVMContext & Context) const [inline]
Return a VT for an integer vector type with the size of the elements doubled.
The typed returned may be an extended type.
Definition at line 284 of file ValueTypes.h.
References getIntegerVT(), getSizeInBits(), getVectorElementType(), getVectorNumElements(), and getVectorVT().
The documentation for this struct was generated from the following files:
ValueTypes.h
ValueTypes.cpp