LLVM: llvm::MDNodeKeyImpl< DITemplateTypeParameter > Struct Template Reference
llvm::MDNodeKeyImpl< DITemplateTypeParameter > Struct Template Reference
#include <LLVMContextImpl.h>
Public Member Functions
MDNodeKeyImpl (StringRef Name, Metadata *Type)
MDNodeKeyImpl (const DITemplateTypeParameter *N)
bool isKeyOf (const DITemplateTypeParameter *RHS) const
unsigned getHashValue () const
Public Attributes
StringRef Name
Metadata * Type
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DITemplateTypeParameter >
Definition at line 654 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
llvm::MDNodeKeyImpl< DITemplateTypeParameter >::MDNodeKeyImpl (StringRef Name, Metadata * Type) [inline]
Definition at line 658 of file LLVMContextImpl.h.
llvm::MDNodeKeyImpl< DITemplateTypeParameter >::MDNodeKeyImpl (const DITemplateTypeParameter * N) [inline]
Definition at line 659 of file LLVMContextImpl.h.
Member Function Documentation
unsigned llvm::MDNodeKeyImpl< DITemplateTypeParameter >::getHashValue () const [inline]
Definition at line 665 of file LLVMContextImpl.h.
References llvm::hash_combine().
bool llvm::MDNodeKeyImpl< DITemplateTypeParameter >::isKeyOf (const DITemplateTypeParameter * RHS) const [inline]
Definition at line 662 of file LLVMContextImpl.h.
References llvm::DITemplateParameter::getName(), and llvm::DITemplateParameter::getRawType().
Member Data Documentation
StringRef llvm::MDNodeKeyImpl< DITemplateTypeParameter >::Name
Definition at line 655 of file LLVMContextImpl.h.
Metadata* llvm::MDNodeKeyImpl< DITemplateTypeParameter >::Type
Definition at line 656 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
LLVMContextImpl.h