LLVM: llvm::AArch64RegisterInfo Struct Reference
llvm::AArch64RegisterInfo Struct Reference
#include <AArch64RegisterInfo.h>
Public Member Functions
AArch64RegisterInfo (const Triple &TT)
bool isReservedReg (const MachineFunction &MF, unsigned Reg) const
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
Code Generation virtual methods...
const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID) const override
unsigned getCSRFirstUseCost () const override
const uint32_t * getTLSCallPreservedMask () const
const uint32_t * getThisReturnPreservedMask (const MachineFunction &MF, CallingConv::ID) const
getThisReturnPreservedMask - Returns a call preserved mask specific to the case that 'returned' is on an i64 first argument if the calling convention is one that can (partially) model this attribute with a preserved mask (i.e.
BitVector getReservedRegs (const MachineFunction &MF) const override
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind=0) const override
const TargetRegisterClass * getCrossCopyRegClass (const TargetRegisterClass *RC) const override
bool requiresRegisterScavenging (const MachineFunction &MF) const override
bool useFPForScavengingIndex (const MachineFunction &MF) const override
bool requiresFrameIndexScavenging (const MachineFunction &MF) const override
bool needsFrameBaseReg (MachineInstr *MI, int64_t Offset) const override
needsFrameBaseReg - Returns true if the instruction's frame index reference would be better served by a base register other than FP or SP.
bool isFrameOffsetLegal (const MachineInstr *MI, unsigned BaseReg, int64_t Offset) const override
void materializeFrameBaseRegister (MachineBasicBlock *MBB, unsigned BaseReg, int FrameIdx, int64_t Offset) const override
Insert defining instruction(s) for BaseReg to be a pointer to FrameIdx at the beginning of the basic block.
void resolveFrameIndex (MachineInstr &MI, unsigned BaseReg, int64_t Offset) const override
void eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
bool cannotEliminateFrame (const MachineFunction &MF) const
bool requiresVirtualBaseRegisters (const MachineFunction &MF) const override
bool hasBasePointer (const MachineFunction &MF) const
unsigned getBaseRegister () const
unsigned getFrameRegister (const MachineFunction &MF) const override
unsigned getRegPressureLimit (const TargetRegisterClass *RC, MachineFunction &MF) const override
bool canRealignStack (const MachineFunction &MF) const
bool needsStackRealignment (const MachineFunction &MF) const override
Detailed Description
Definition at line 27 of file AArch64RegisterInfo.h.
Constructor & Destructor Documentation
AArch64RegisterInfo::AArch64RegisterInfo (const Triple & TT)
Definition at line 41 of file AArch64RegisterInfo.cpp.
Member Function Documentation
bool AArch64RegisterInfo::cannotEliminateFrame (const MachineFunction & MF) const
Definition at line 246 of file AArch64RegisterInfo.cpp.
References llvm::MachineFrameInfo::adjustsStack(), llvm::TargetOptions::DisableFramePointerElim(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getTarget(), llvm::MachineFrameInfo::hasCalls(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::MachineFrameInfo::isFrameAddressTaken(), and llvm::TargetMachine::Options.
Referenced by llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan().
bool AArch64RegisterInfo::canRealignStack (const MachineFunction & MF) const
Definition at line 189 of file AArch64RegisterInfo.cpp.
References llvm::MachineFunction::getFunction(), and llvm::Function::hasFnAttribute().
Referenced by needsStackRealignment().
void AArch64RegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const [override]
Definition at line 369 of file AArch64RegisterInfo.cpp.
References llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::emitFrameOffset(), llvm::ISD::FrameIndex, llvm::MachineInstr::getDebugLoc(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineInstr::isDebugValue(), llvm::RegScavenger::isScavengingFrameIndex(), llvm::AArch64CC::MI, llvm::TargetOpcode::PATCHPOINT, llvm::AArch64FrameLowering::resolveFrameIndexReference(), llvm::rewriteAArch64FrameIndex(), llvm::TargetOpcode::STACKMAP, and TII.
unsigned AArch64RegisterInfo::getBaseRegister () const
Definition at line 159 of file AArch64RegisterInfo.cpp.
Referenced by llvm::AArch64FrameLowering::emitPrologue(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), and llvm::AArch64FrameLowering::resolveFrameIndexReference().
const MCPhysReg * AArch64RegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const [override]
Code Generation virtual methods...
Definition at line 45 of file AArch64RegisterInfo.cpp.
References llvm::CallingConv::AnyReg, llvm::Function::getCallingConv(), llvm::MachineFunction::getFunction(), and llvm::CallingConv::GHC.
Referenced by llvm::AArch64FrameLowering::emitEpilogue(), and llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan().
const uint32_t * AArch64RegisterInfo::getCallPreservedMask (const MachineFunction & MF, CallingConv::ID CC) const [override]
Definition at line 58 of file AArch64RegisterInfo.cpp.
References llvm::CallingConv::AnyReg, and llvm::CallingConv::GHC.
const TargetRegisterClass * AArch64RegisterInfo::getCrossCopyRegClass (const TargetRegisterClass * RC) const [override]
Definition at line 153 of file AArch64RegisterInfo.cpp.
unsigned llvm::AArch64RegisterInfo::getCSRFirstUseCost () const [inline, override]
Definition at line 41 of file AArch64RegisterInfo.h.
unsigned AArch64RegisterInfo::getFrameRegister (const MachineFunction & MF) const [override]
Definition at line 215 of file AArch64RegisterInfo.cpp.
References llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFunction::getSubtarget(), llvm::TargetFrameLowering::hasFP(), and llvm::SP.
Referenced by llvm::AArch64FrameLowering::emitPrologue(), and llvm::AArch64FrameLowering::resolveFrameIndexReference().
const TargetRegisterClass * AArch64RegisterInfo::getPointerRegClass (const MachineFunction & MF, unsigned Kind = 0) const [override]
Definition at line 147 of file AArch64RegisterInfo.cpp.
unsigned llvm::AArch64RegisterInfo::getRegPressureLimit (const TargetRegisterClass * RC, MachineFunction & MF) const [override]
Definition at line 416 of file AArch64RegisterInfo.cpp.
References llvm::TargetSubtargetInfo::getFrameLowering(), llvm::TargetRegisterClass::getID(), llvm::MachineFunction::getSubtarget(), llvm::TargetFrameLowering::hasFP(), and ReserveX18.
BitVector AArch64RegisterInfo::getReservedRegs (const MachineFunction & MF) const [override]
Definition at line 92 of file AArch64RegisterInfo.cpp.
References llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFunction::getSubtarget(), hasBasePointer(), llvm::TargetFrameLowering::hasFP(), llvm::Triple::isOSDarwin(), llvm::Reserved, ReserveX18, llvm::BitVector::set(), and llvm::SP.
const uint32_t * AArch64RegisterInfo::getThisReturnPreservedMask (const MachineFunction & MF, CallingConv::ID CC) const
getThisReturnPreservedMask - Returns a call preserved mask specific to the case that 'returned' is on an i64 first argument if the calling convention is one that can (partially) model this attribute with a preserved mask (i.e.
it is a calling convention that uses the same register for the first i64 argument and an i64 return value)
Should return NULL in the case that the calling convention does not have this property
Definition at line 78 of file AArch64RegisterInfo.cpp.
References llvm::CallingConv::GHC.
const uint32_t * AArch64RegisterInfo::getTLSCallPreservedMask () const
Definition at line 69 of file AArch64RegisterInfo.cpp.
References llvm::Triple::isOSBinFormatELF(), and llvm::Triple::isOSDarwin().
bool AArch64RegisterInfo::hasBasePointer (const MachineFunction & MF) const
Definition at line 161 of file AArch64RegisterInfo.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getLocalFrameSize(), llvm::MachineFrameInfo::hasVarSizedObjects(), and needsStackRealignment().
Referenced by llvm::AArch64FrameLowering::emitPrologue(), getReservedRegs(), isReservedReg(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::AArch64FrameLowering::resolveFrameIndexReference(), and useFPForScavengingIndex().
bool AArch64RegisterInfo::isFrameOffsetLegal (const MachineInstr * MI, unsigned BaseReg, int64_t Offset) const [override]
Definition at line 319 of file AArch64RegisterInfo.cpp.
References llvm::AArch64FrameOffsetIsLegal, and llvm::isAArch64FrameOffsetLegal().
Referenced by needsFrameBaseReg().
bool AArch64RegisterInfo::isReservedReg (const MachineFunction & MF, unsigned Reg) const
Definition at line 120 of file AArch64RegisterInfo.cpp.
References llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFunction::getSubtarget(), hasBasePointer(), llvm::TargetFrameLowering::hasFP(), llvm::Triple::isOSDarwin(), ReserveX18, and llvm::SP.
Referenced by llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan().
void AArch64RegisterInfo::materializeFrameBaseRegister (MachineBasicBlock * MBB, unsigned BaseReg, int FrameIdx, int64_t Offset) const [override]
Insert defining instruction(s) for BaseReg to be a pointer to FrameIdx at the beginning of the basic block.
Definition at line 330 of file AArch64RegisterInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineRegisterInfo::constrainRegClass(), llvm::DL, llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::AArch64_AM::getShifterImm(), llvm::MachineFunction::getSubtarget(), llvm::MipsISD::Ins, llvm::AArch64_AM::LSL, and TII.
bool AArch64RegisterInfo::needsFrameBaseReg (MachineInstr * MI, int64_t Offset) const [override]
needsFrameBaseReg - Returns true if the instruction's frame index reference would be better served by a base register other than FP or SP.
Used by LocalStackFrameAllocation to determine which frame index references it should create new base registers for.
Definition at line 259 of file AArch64RegisterInfo.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFrameInfo::getLocalFrameSize(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getSubtarget(), llvm::TargetFrameLowering::hasFP(), llvm::MachineOperand::isFI(), isFrameOffsetLegal(), llvm::MachineInstr::mayLoad(), llvm::MachineInstr::mayStore(), and llvm::SP.
bool AArch64RegisterInfo::needsStackRealignment (const MachineFunction & MF) const [override]
Definition at line 199 of file AArch64RegisterInfo.cpp.
References canRealignStack(), F(), llvm::AttributeSet::FunctionIndex, llvm::Function::getAttributes(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFrameInfo::getMaxAlignment(), llvm::TargetMachine::getSubtargetImpl(), llvm::MachineFunction::getTarget(), llvm::AttributeSet::hasAttribute(), and llvm::Attribute::StackAlignment.
Referenced by hasBasePointer(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), and llvm::AArch64FrameLowering::resolveFrameIndexReference().
bool AArch64RegisterInfo::requiresFrameIndexScavenging (const MachineFunction & MF) const [override]
Definition at line 240 of file AArch64RegisterInfo.cpp.
bool AArch64RegisterInfo::requiresRegisterScavenging (const MachineFunction & MF) const [override]
Definition at line 221 of file AArch64RegisterInfo.cpp.
bool AArch64RegisterInfo::requiresVirtualBaseRegisters (const MachineFunction & MF) const [override]
Definition at line 226 of file AArch64RegisterInfo.cpp.
void AArch64RegisterInfo::resolveFrameIndex (MachineInstr & MI, unsigned BaseReg, int64_t Offset) const [override]
Definition at line 352 of file AArch64RegisterInfo.cpp.
References llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getSubtarget(), llvm::MachineOperand::isFI(), llvm::rewriteAArch64FrameIndex(), and TII.
bool AArch64RegisterInfo::useFPForScavengingIndex (const MachineFunction & MF) const [override]
Definition at line 232 of file AArch64RegisterInfo.cpp.
References llvm::MachineFunction::getFrameInfo(), hasBasePointer(), and llvm::MachineFrameInfo::hasVarSizedObjects().
The documentation for this struct was generated from the following files:
AArch64RegisterInfo.h
AArch64RegisterInfo.cpp