LLVM: llvm::MDNodeKeyImpl< DILexicalBlockFile > Struct Template Reference
llvm::MDNodeKeyImpl< DILexicalBlockFile > Struct Template Reference
#include <LLVMContextImpl.h>
Public Member Functions
MDNodeKeyImpl (Metadata *Scope, Metadata *File, unsigned Discriminator)
MDNodeKeyImpl (const DILexicalBlockFile *N)
bool isKeyOf (const DILexicalBlockFile *RHS) const
unsigned getHashValue () const
Public Attributes
Metadata * Scope
Metadata * File
unsigned Discriminator
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DILexicalBlockFile >
Definition at line 613 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
llvm::MDNodeKeyImpl< DILexicalBlockFile >::MDNodeKeyImpl (Metadata * Scope, Metadata * File, unsigned Discriminator) [inline]
Definition at line 618 of file LLVMContextImpl.h.
llvm::MDNodeKeyImpl< DILexicalBlockFile >::MDNodeKeyImpl (const DILexicalBlockFile * N) [inline]
Definition at line 620 of file LLVMContextImpl.h.
Member Function Documentation
unsigned llvm::MDNodeKeyImpl< DILexicalBlockFile >::getHashValue () const [inline]
Definition at line 628 of file LLVMContextImpl.h.
References llvm::ARMBuildAttrs::File, and llvm::hash_combine().
bool llvm::MDNodeKeyImpl< DILexicalBlockFile >::isKeyOf (const DILexicalBlockFile * RHS) const [inline]
Definition at line 624 of file LLVMContextImpl.h.
References llvm::ARMBuildAttrs::File, llvm::DILexicalBlockFile::getDiscriminator(), llvm::DIScope::getRawFile(), and llvm::DILexicalBlockBase::getRawScope().
Member Data Documentation
unsigned llvm::MDNodeKeyImpl< DILexicalBlockFile >::Discriminator
Definition at line 616 of file LLVMContextImpl.h.
Metadata* llvm::MDNodeKeyImpl< DILexicalBlockFile >::File
Definition at line 615 of file LLVMContextImpl.h.
Metadata* llvm::MDNodeKeyImpl< DILexicalBlockFile >::Scope
Definition at line 614 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
LLVMContextImpl.h