LLVM: llvm::MDNodeKeyImpl< DIBasicType > Struct Template Reference
llvm::MDNodeKeyImpl< DIBasicType > Struct Template Reference
#include <LLVMContextImpl.h>
Public Member Functions
MDNodeKeyImpl (unsigned Tag, StringRef Name, uint64_t SizeInBits, uint64_t AlignInBits, unsigned Encoding)
MDNodeKeyImpl (const DIBasicType *N)
bool isKeyOf (const DIBasicType *RHS) const
unsigned getHashValue () const
Public Attributes
unsigned Tag
StringRef Name
uint64_t SizeInBits
uint64_t AlignInBits
unsigned Encoding
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DIBasicType >
Definition at line 305 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
llvm::MDNodeKeyImpl< DIBasicType >::MDNodeKeyImpl (unsigned Tag, StringRef Name, uint64_t SizeInBits, uint64_t AlignInBits, unsigned Encoding) [inline]
Definition at line 312 of file LLVMContextImpl.h.
llvm::MDNodeKeyImpl< DIBasicType >::MDNodeKeyImpl (const DIBasicType * N) [inline]
Definition at line 316 of file LLVMContextImpl.h.
Member Function Documentation
unsigned llvm::MDNodeKeyImpl< DIBasicType >::getHashValue () const [inline]
Definition at line 326 of file LLVMContextImpl.h.
References llvm::hash_combine().
bool llvm::MDNodeKeyImpl< DIBasicType >::isKeyOf (const DIBasicType * RHS) const [inline]
Definition at line 320 of file LLVMContextImpl.h.
References llvm::DIType::getAlignInBits(), llvm::DIBasicType::getEncoding(), llvm::DIType::getName(), llvm::DIType::getSizeInBits(), and llvm::DINode::getTag().
Member Data Documentation
uint64_t llvm::MDNodeKeyImpl< DIBasicType >::AlignInBits
Definition at line 309 of file LLVMContextImpl.h.
unsigned llvm::MDNodeKeyImpl< DIBasicType >::Encoding
Definition at line 310 of file LLVMContextImpl.h.
StringRef llvm::MDNodeKeyImpl< DIBasicType >::Name
Definition at line 307 of file LLVMContextImpl.h.
uint64_t llvm::MDNodeKeyImpl< DIBasicType >::SizeInBits
Definition at line 308 of file LLVMContextImpl.h.
unsigned llvm::MDNodeKeyImpl< DIBasicType >::Tag
Definition at line 306 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
LLVMContextImpl.h