LLVM: llvm::DOTGraphTraits< BlockFrequencyInfo * > Struct Template Reference
llvm::DOTGraphTraits< BlockFrequencyInfo * > Struct Template Reference
Public Member Functions
DOTGraphTraits (bool isSimple=false)
std::string getNodeLabel (const BasicBlock *Node, const BlockFrequencyInfo *Graph)
Static Public Member Functions
static std::string getGraphName (const BlockFrequencyInfo *G)
Detailed Description
template<>
struct llvm::DOTGraphTraits< BlockFrequencyInfo * >
Definition at line 75 of file BlockFrequencyInfo.cpp.
Constructor & Destructor Documentation
llvm::DOTGraphTraits< BlockFrequencyInfo * >::DOTGraphTraits (bool isSimple = false) [inline, explicit]
Definition at line 76 of file BlockFrequencyInfo.cpp.
Member Function Documentation
static std::string llvm::DOTGraphTraits< BlockFrequencyInfo * >::getGraphName (const BlockFrequencyInfo * G) [inline, static]
Definition at line 79 of file BlockFrequencyInfo.cpp.
References llvm::BlockFrequencyInfo::getFunction(), and llvm::Value::getName().
std::string llvm::DOTGraphTraits< BlockFrequencyInfo * >::getNodeLabel (const BasicBlock * Node, const BlockFrequencyInfo * Graph) [inline]
Definition at line 83 of file BlockFrequencyInfo.cpp.
References llvm::BlockFrequencyInfo::getBlockFreq(), llvm::BlockFrequency::getFrequency(), llvm::Value::getName(), GVDT_Fraction, GVDT_Integer, GVDT_None, llvm_unreachable, llvm::BlockFrequencyInfo::printBlockFreq(), and ViewBlockFreqPropagationDAG.
The documentation for this struct was generated from the following file:
BlockFrequencyInfo.cpp