LLVM: llvm::BitstreamEntry Struct Reference
llvm::BitstreamEntry Struct Reference
When advancing through a bitstream cursor, each advance can discover a few different kinds of entries:
#include <BitstreamReader.h>
Public Types
enum { Error, EndBlock, SubBlock, Record }
Static Public Member Functions
static BitstreamEntry getError ()
static BitstreamEntry getEndBlock ()
static BitstreamEntry getSubBlock (unsigned ID)
static BitstreamEntry getRecord (unsigned AbbrevID)
Public Attributes
enum llvm::BitstreamEntry:: { ... } Kind
unsigned ID
Detailed Description
When advancing through a bitstream cursor, each advance can discover a few different kinds of entries:
Definition at line 133 of file BitstreamReader.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
Error
EndBlock
SubBlock
Record
Definition at line 134 of file BitstreamReader.h.
Member Function Documentation
static BitstreamEntry llvm::BitstreamEntry::getEndBlock () [inline, static]
Definition at line 147 of file BitstreamReader.h.
References EndBlock, and Kind.
Referenced by llvm::BitstreamCursor::advance().
static BitstreamEntry llvm::BitstreamEntry::getError () [inline, static]
Definition at line 144 of file BitstreamReader.h.
References Error, and Kind.
Referenced by llvm::BitstreamCursor::advance(), and llvm::BitstreamCursor::advanceSkippingSubblocks().
static BitstreamEntry llvm::BitstreamEntry::getRecord (unsigned AbbrevID) [inline, static]
Definition at line 153 of file BitstreamReader.h.
References ID, Kind, and Record.
Referenced by llvm::BitstreamCursor::advance().
static BitstreamEntry llvm::BitstreamEntry::getSubBlock (unsigned ID) [inline, static]
Definition at line 150 of file BitstreamReader.h.
References ID, Kind, and SubBlock.
Referenced by llvm::BitstreamCursor::advance().
Member Data Documentation
unsigned llvm::BitstreamEntry::ID
Definition at line 142 of file BitstreamReader.h.
Referenced by getRecord(), getSubBlock(), and llvm::BitstreamCursor::ReadBlockInfoBlock().
enum { ... } llvm::BitstreamEntry::Kind
Referenced by llvm::BitstreamCursor::advanceSkippingSubblocks(), getEndBlock(), getError(), getRecord(), getSubBlock(), and llvm::BitstreamCursor::ReadBlockInfoBlock().
The documentation for this struct was generated from the following file:
BitstreamReader.h