LLVM: llvm::support::endian::Writer< endian > Struct Template Reference
llvm::support::endian::Writer< endian > Struct Template Reference
Adapter to write values to a stream in a particular byte order.
#include <EndianStream.h>
Public Member Functions
Writer (raw_ostream &OS)
template<typename value_type >
void write (value_type Val)
template<>
void write (float Val)
template<>
void write (double Val)
template<>
void write (float Val)
template<>
void write (double Val)
Public Attributes
raw_ostream & OS
Detailed Description
template<endianness endian>
struct llvm::support::endian::Writer< endian >
Adapter to write values to a stream in a particular byte order.
Definition at line 26 of file EndianStream.h.
Constructor & Destructor Documentation
template<endianness endian> llvm::support::endian::Writer< endian >::Writer (raw_ostream & OS) [inline]
Definition at line 28 of file EndianStream.h.
Member Function Documentation
template<endianness endian> template<typename value_type > void llvm::support::endian::Writer< endian >::write (value_type Val) [inline]
Definition at line 29 of file EndianStream.h.
References llvm::support::endian::Writer< endian >::OS, and llvm::raw_ostream::write().
Referenced by llvm::OnDiskChainedHashTableGenerator< Info >::Emit(), and llvm::MCDwarfFrameEmitter::EncodeAdvanceLoc().
template<> void llvm::support::endian::Writer< little >::write< float > (float Val) [inline]
Definition at line 37 of file EndianStream.h.
References llvm::FloatToBits(), and llvm::support::endian::write().
template<> void llvm::support::endian::Writer< little >::write< double > (double Val) [inline]
Definition at line 43 of file EndianStream.h.
References llvm::DoubleToBits(), and llvm::support::endian::write().
template<> void llvm::support::endian::Writer< big >::write< float > (float Val) [inline]
Definition at line 49 of file EndianStream.h.
References llvm::FloatToBits(), and llvm::support::endian::write().
template<> void llvm::support::endian::Writer< big >::write< double > (double Val) [inline]
Definition at line 55 of file EndianStream.h.
References llvm::DoubleToBits(), and llvm::support::endian::write().
Member Data Documentation
template<endianness endian> raw_ostream& llvm::support::endian::Writer< endian >::OS
Definition at line 27 of file EndianStream.h.
Referenced by llvm::support::endian::Writer< endian >::write().
The documentation for this struct was generated from the following file:
EndianStream.h