LLVM: llvm::MDNodeKeyImpl< DIDerivedType > Struct Template Reference
llvm::MDNodeKeyImpl< DIDerivedType > Struct Template Reference
#include <LLVMContextImpl.h>
Public Member Functions
MDNodeKeyImpl (unsigned Tag, StringRef Name, Metadata *File, unsigned Line, Metadata *Scope, Metadata *BaseType, uint64_t SizeInBits, uint64_t AlignInBits, uint64_t OffsetInBits, unsigned Flags, Metadata *ExtraData)
MDNodeKeyImpl (const DIDerivedType *N)
bool isKeyOf (const DIDerivedType *RHS) const
unsigned getHashValue () const
Public Attributes
unsigned Tag
StringRef Name
Metadata * File
unsigned Line
Metadata * Scope
Metadata * BaseType
uint64_t SizeInBits
uint64_t AlignInBits
uint64_t OffsetInBits
unsigned Flags
Metadata * ExtraData
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DIDerivedType >
Definition at line 331 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
llvm::MDNodeKeyImpl< DIDerivedType >::MDNodeKeyImpl (unsigned Tag, StringRef Name, Metadata * File, unsigned Line, Metadata * Scope, Metadata * BaseType, uint64_t SizeInBits, uint64_t AlignInBits, uint64_t OffsetInBits, unsigned Flags, Metadata * ExtraData) [inline]
Definition at line 344 of file LLVMContextImpl.h.
llvm::MDNodeKeyImpl< DIDerivedType >::MDNodeKeyImpl (const DIDerivedType * N) [inline]
Definition at line 351 of file LLVMContextImpl.h.
Member Function Documentation
unsigned llvm::MDNodeKeyImpl< DIDerivedType >::getHashValue () const [inline]
Definition at line 367 of file LLVMContextImpl.h.
References llvm::ARMBuildAttrs::File, and llvm::hash_combine().
bool llvm::MDNodeKeyImpl< DIDerivedType >::isKeyOf (const DIDerivedType * RHS) const [inline]
Definition at line 358 of file LLVMContextImpl.h.
References llvm::ARMBuildAttrs::File, llvm::DIType::getAlignInBits(), llvm::DIType::getFlags(), llvm::DIType::getLine(), llvm::DIType::getName(), llvm::DIType::getOffsetInBits(), llvm::DIDerivedTypeBase::getRawBaseType(), llvm::DIScope::getRawFile(), llvm::DIType::getRawScope(), llvm::DIType::getSizeInBits(), and llvm::DINode::getTag().
Member Data Documentation
uint64_t llvm::MDNodeKeyImpl< DIDerivedType >::AlignInBits
Definition at line 339 of file LLVMContextImpl.h.
Metadata* llvm::MDNodeKeyImpl< DIDerivedType >::BaseType
Definition at line 337 of file LLVMContextImpl.h.
Metadata* llvm::MDNodeKeyImpl< DIDerivedType >::ExtraData
Definition at line 342 of file LLVMContextImpl.h.
Metadata* llvm::MDNodeKeyImpl< DIDerivedType >::File
Definition at line 334 of file LLVMContextImpl.h.
unsigned llvm::MDNodeKeyImpl< DIDerivedType >::Flags
Definition at line 341 of file LLVMContextImpl.h.
unsigned llvm::MDNodeKeyImpl< DIDerivedType >::Line
Definition at line 335 of file LLVMContextImpl.h.
StringRef llvm::MDNodeKeyImpl< DIDerivedType >::Name
Definition at line 333 of file LLVMContextImpl.h.
uint64_t llvm::MDNodeKeyImpl< DIDerivedType >::OffsetInBits
Definition at line 340 of file LLVMContextImpl.h.
Metadata* llvm::MDNodeKeyImpl< DIDerivedType >::Scope
Definition at line 336 of file LLVMContextImpl.h.
uint64_t llvm::MDNodeKeyImpl< DIDerivedType >::SizeInBits
Definition at line 338 of file LLVMContextImpl.h.
unsigned llvm::MDNodeKeyImpl< DIDerivedType >::Tag
Definition at line 332 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
LLVMContextImpl.h