LLVM: llvm::MSP430RegisterInfo Struct Reference
llvm::MSP430RegisterInfo Struct Reference
#include <MSP430RegisterInfo.h>
Public Member Functions
MSP430RegisterInfo ()
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
Code Generation virtual methods...
BitVector getReservedRegs (const MachineFunction &MF) const override
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind=0) const override
void eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
unsigned getFrameRegister (const MachineFunction &MF) const override
Detailed Description
Definition at line 24 of file MSP430RegisterInfo.h.
Constructor & Destructor Documentation
MSP430RegisterInfo::MSP430RegisterInfo ()
Definition at line 35 of file MSP430RegisterInfo.cpp.
Member Function Documentation
void MSP430RegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const [override]
Definition at line 104 of file MSP430RegisterInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::BuildMI(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), llvm::ISD::FrameIndex, llvm::MCInstrInfo::get(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::TargetFrameLowering::hasFP(), llvm::AArch64CC::MI, llvm::MachineInstr::setDesc(), llvm::SP, and TII.
const MCPhysReg * MSP430RegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const [override]
Code Generation virtual methods...
Definition at line 39 of file MSP430RegisterInfo.cpp.
References F(), llvm::Function::getCallingConv(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getSubtarget(), llvm::TargetFrameLowering::hasFP(), llvm::CallingConv::MSP430_INTR, llvm::R10, llvm::R11, llvm::R12, llvm::R13, llvm::R14, llvm::R15, llvm::R8, and llvm::R9.
unsigned MSP430RegisterInfo::getFrameRegister (const MachineFunction & MF) const [override]
Definition at line 158 of file MSP430RegisterInfo.cpp.
References llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFunction::getSubtarget(), llvm::TargetFrameLowering::hasFP(), and llvm::SP.
const TargetRegisterClass * MSP430RegisterInfo::getPointerRegClass (const MachineFunction & MF, unsigned Kind = 0) const [override]
Definition at line 98 of file MSP430RegisterInfo.cpp.
BitVector MSP430RegisterInfo::getReservedRegs (const MachineFunction & MF) const [override]
Definition at line 74 of file MSP430RegisterInfo.cpp.
References llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFunction::getSubtarget(), llvm::TargetFrameLowering::hasFP(), llvm::Reserved, llvm::BitVector::set(), and llvm::SP.
The documentation for this struct was generated from the following files:
MSP430RegisterInfo.h
MSP430RegisterInfo.cpp