LLVM: llvm::TargetLowering::CallLoweringInfo Struct Reference
llvm::TargetLowering::CallLoweringInfo Struct Reference
This structure contains all information that is necessary for lowering calls.
#include <TargetLowering.h>
Public Member Functions
CallLoweringInfo (SelectionDAG &DAG)
CallLoweringInfo & setDebugLoc (SDLoc dl)
CallLoweringInfo & setChain (SDValue InChain)
CallLoweringInfo & setCallee (CallingConv::ID CC, Type *ResultType, SDValue Target, ArgListTy &&ArgsList, unsigned FixedArgs=-1)
CallLoweringInfo & setCallee (Type *ResultType, FunctionType *FTy, SDValue Target, ArgListTy &&ArgsList, ImmutableCallSite &Call)
CallLoweringInfo & setInRegister (bool Value=true)
CallLoweringInfo & setNoReturn (bool Value=true)
CallLoweringInfo & setVarArg (bool Value=true)
CallLoweringInfo & setTailCall (bool Value=true)
CallLoweringInfo & setDiscardResult (bool Value=true)
CallLoweringInfo & setSExtResult (bool Value=true)
CallLoweringInfo & setZExtResult (bool Value=true)
CallLoweringInfo & setIsPatchPoint (bool Value=true)
ArgListTy & getArgs ()
Public Attributes
SDValue Chain
Type * RetTy
bool RetSExt: 1
bool RetZExt: 1
bool IsVarArg: 1
bool IsInReg: 1
bool DoesNotReturn: 1
bool IsReturnValueUsed: 1
bool IsTailCall
unsigned NumFixedArgs
CallingConv::ID CallConv
SDValue Callee
ArgListTy Args
SelectionDAG & DAG
SDLoc DL
ImmutableCallSite * CS
bool IsPatchPoint
SmallVector< ISD::OutputArg, 32 > Outs
SmallVector< SDValue, 32 > OutVals
SmallVector< ISD::InputArg, 32 > Ins
Detailed Description
This structure contains all information that is necessary for lowering calls.
It is passed to TLI::LowerCallTo when the SelectionDAG builder needs to lower a call, and targets will see this struct in their LowerCall implementation.
Definition at line 2269 of file TargetLowering.h.
Constructor & Destructor Documentation
llvm::TargetLowering::CallLoweringInfo::CallLoweringInfo (SelectionDAG & DAG) [inline]
Definition at line 2295 of file TargetLowering.h.
Member Function Documentation
ArgListTy& llvm::TargetLowering::CallLoweringInfo::getArgs () [inline]
Definition at line 2386 of file TargetLowering.h.
References Args.
Referenced by llvm::NVPTXTargetLowering::LowerCall(), and llvm::TargetLowering::LowerCallTo().
CallLoweringInfo& llvm::TargetLowering::CallLoweringInfo::setCallee (CallingConv::ID CC, Type * ResultType, SDValue Target, ArgListTy && ArgsList, unsigned FixedArgs = -1) [inline]
Definition at line 2311 of file TargetLowering.h.
References Args, CallConv, Callee, NumFixedArgs, and RetTy.
Referenced by llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemmove(), llvm::SelectionDAG::getMemset(), llvm::SelectionDAGBuilder::lowerCallOperands(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::SparcTargetLowering::LowerF128Compare(), and llvm::SparcTargetLowering::LowerF128Op().
CallLoweringInfo& llvm::TargetLowering::CallLoweringInfo::setCallee (Type * ResultType, FunctionType * FTy, SDValue Target, ArgListTy && ArgsList, ImmutableCallSite & Call) [inline]
Definition at line 2323 of file TargetLowering.h.
References Args, llvm::Call, CallConv, Callee, CS, llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::doesNotReturn(), DoesNotReturn, llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCallingConv(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getInstruction(), llvm::FunctionType::getNumParams(), llvm::Attribute::InReg, IsInReg, IsReturnValueUsed, llvm::FunctionType::isVarArg(), IsVarArg, NumFixedArgs, llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::paramHasAttr(), RetSExt, RetTy, RetZExt, llvm::Attribute::SExt, llvm::Value::use_empty(), and llvm::Attribute::ZExt.
CallLoweringInfo& llvm::TargetLowering::CallLoweringInfo::setChain (SDValue InChain) [inline]
Definition at line 2306 of file TargetLowering.h.
References Chain.
Referenced by llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemmove(), llvm::SelectionDAG::getMemset(), llvm::SelectionDAGBuilder::lowerCallOperands(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SparcTargetLowering::LowerF128Op(), LowerFSINCOS(), and llvm::TargetLowering::makeLibCall().
CallLoweringInfo& llvm::TargetLowering::CallLoweringInfo::setDebugLoc (SDLoc dl) [inline]
Definition at line 2301 of file TargetLowering.h.
References DL.
Referenced by llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemmove(), llvm::SelectionDAG::getMemset(), llvm::SelectionDAGBuilder::lowerCallOperands(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SparcTargetLowering::LowerF128Op(), LowerFSINCOS(), and llvm::TargetLowering::makeLibCall().
CallLoweringInfo& llvm::TargetLowering::CallLoweringInfo::setDiscardResult (bool Value = true) [inline]
Definition at line 2366 of file TargetLowering.h.
References IsReturnValueUsed.
Referenced by llvm::TargetLowering::makeLibCall().
CallLoweringInfo& llvm::TargetLowering::CallLoweringInfo::setInRegister (bool Value = true) [inline]
Definition at line 2346 of file TargetLowering.h.
References IsInReg.
CallLoweringInfo& llvm::TargetLowering::CallLoweringInfo::setIsPatchPoint (bool Value = true) [inline]
Definition at line 2381 of file TargetLowering.h.
References IsPatchPoint.
CallLoweringInfo& llvm::TargetLowering::CallLoweringInfo::setNoReturn (bool Value = true) [inline]
Definition at line 2351 of file TargetLowering.h.
References DoesNotReturn.
CallLoweringInfo& llvm::TargetLowering::CallLoweringInfo::setSExtResult (bool Value = true) [inline]
Definition at line 2371 of file TargetLowering.h.
References RetSExt.
Referenced by llvm::TargetLowering::makeLibCall().
CallLoweringInfo& llvm::TargetLowering::CallLoweringInfo::setTailCall (bool Value = true) [inline]
Definition at line 2361 of file TargetLowering.h.
References IsTailCall.
Referenced by llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemmove(), llvm::SelectionDAG::getMemset(), and llvm::SelectionDAGBuilder::LowerCallTo().
CallLoweringInfo& llvm::TargetLowering::CallLoweringInfo::setVarArg (bool Value = true) [inline]
Definition at line 2356 of file TargetLowering.h.
References IsVarArg.
CallLoweringInfo& llvm::TargetLowering::CallLoweringInfo::setZExtResult (bool Value = true) [inline]
Definition at line 2376 of file TargetLowering.h.
References RetZExt.
Referenced by llvm::TargetLowering::makeLibCall().
Member Data Documentation
ArgListTy llvm::TargetLowering::CallLoweringInfo::Args
Definition at line 2286 of file TargetLowering.h.
Referenced by getArgs(), and setCallee().
CallingConv::ID llvm::TargetLowering::CallLoweringInfo::CallConv
Definition at line 2284 of file TargetLowering.h.
Referenced by llvm::MipsTargetLowering::getOpndList(), llvm::HexagonTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), and setCallee().
SDValue llvm::TargetLowering::CallLoweringInfo::Callee
Definition at line 2285 of file TargetLowering.h.
Referenced by llvm::MipsTargetLowering::getOpndList(), llvm::HexagonTargetLowering::LowerCall(), llvm::AMDGPUTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), and setCallee().
SDValue llvm::TargetLowering::CallLoweringInfo::Chain
Definition at line 2270 of file TargetLowering.h.
Referenced by llvm::HexagonTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), and setChain().
ImmutableCallSite* llvm::TargetLowering::CallLoweringInfo::CS
Definition at line 2289 of file TargetLowering.h.
Referenced by llvm::NVPTXTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), and setCallee().
SelectionDAG& llvm::TargetLowering::CallLoweringInfo::DAG
Definition at line 2287 of file TargetLowering.h.
Referenced by llvm::MipsTargetLowering::getOpndList(), llvm::HexagonTargetLowering::LowerCall(), llvm::AMDGPUTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), and llvm::TargetLowering::LowerCallTo().
SDLoc llvm::TargetLowering::CallLoweringInfo::DL
Definition at line 2288 of file TargetLowering.h.
Referenced by llvm::MipsTargetLowering::getOpndList(), llvm::HexagonTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), and setDebugLoc().
bool llvm::TargetLowering::CallLoweringInfo::DoesNotReturn
Definition at line 2276 of file TargetLowering.h.
Referenced by llvm::HexagonTargetLowering::LowerCall(), setCallee(), and setNoReturn().
SmallVector<ISD::InputArg, 32> llvm::TargetLowering::CallLoweringInfo::Ins
Definition at line 2293 of file TargetLowering.h.
Referenced by llvm::HexagonTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), and llvm::TargetLowering::LowerCallTo().
bool llvm::TargetLowering::CallLoweringInfo::IsInReg
Definition at line 2275 of file TargetLowering.h.
Referenced by getReturnAttrs(), llvm::TargetLowering::LowerCallTo(), setCallee(), and setInRegister().
bool llvm::TargetLowering::CallLoweringInfo::IsPatchPoint
Definition at line 2290 of file TargetLowering.h.
Referenced by setIsPatchPoint().
bool llvm::TargetLowering::CallLoweringInfo::IsReturnValueUsed
Definition at line 2277 of file TargetLowering.h.
Referenced by llvm::TargetLowering::LowerCallTo(), setCallee(), and setDiscardResult().
bool llvm::TargetLowering::CallLoweringInfo::IsTailCall
Definition at line 2281 of file TargetLowering.h.
Referenced by llvm::HexagonTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), and setTailCall().
bool llvm::TargetLowering::CallLoweringInfo::IsVarArg
Definition at line 2274 of file TargetLowering.h.
Referenced by llvm::HexagonTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), setCallee(), and setVarArg().
unsigned llvm::TargetLowering::CallLoweringInfo::NumFixedArgs
Definition at line 2283 of file TargetLowering.h.
Referenced by llvm::TargetLowering::LowerCallTo(), and setCallee().
SmallVector<ISD::OutputArg, 32> llvm::TargetLowering::CallLoweringInfo::Outs
Definition at line 2291 of file TargetLowering.h.
Referenced by llvm::HexagonTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), and llvm::TargetLowering::LowerCallTo().
SmallVector<SDValue, 32> llvm::TargetLowering::CallLoweringInfo::OutVals
Definition at line 2292 of file TargetLowering.h.
Referenced by llvm::HexagonTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), and llvm::TargetLowering::LowerCallTo().
bool llvm::TargetLowering::CallLoweringInfo::RetSExt
Definition at line 2272 of file TargetLowering.h.
Referenced by getReturnAttrs(), llvm::TargetLowering::LowerCallTo(), setCallee(), and setSExtResult().
Type* llvm::TargetLowering::CallLoweringInfo::RetTy
Definition at line 2271 of file TargetLowering.h.
Referenced by getReturnAttrs(), llvm::NVPTXTargetLowering::LowerCall(), llvm::TargetLowering::LowerCallTo(), and setCallee().
bool llvm::TargetLowering::CallLoweringInfo::RetZExt
Definition at line 2273 of file TargetLowering.h.
Referenced by getReturnAttrs(), llvm::TargetLowering::LowerCallTo(), setCallee(), and setZExtResult().
The documentation for this struct was generated from the following file:
TargetLowering.h