LLVM: llvm::MDNodeKeyImpl< DILocalVariable > Struct Template Reference
llvm::MDNodeKeyImpl< DILocalVariable > Struct Template Reference
#include <LLVMContextImpl.h>
Public Member Functions
MDNodeKeyImpl (unsigned Tag, Metadata *Scope, StringRef Name, Metadata *File, unsigned Line, Metadata *Type, unsigned Arg, unsigned Flags)
MDNodeKeyImpl (const DILocalVariable *N)
bool isKeyOf (const DILocalVariable *RHS) const
unsigned getHashValue () const
Public Attributes
unsigned Tag
Metadata * Scope
StringRef Name
Metadata * File
unsigned Line
Metadata * Type
unsigned Arg
unsigned Flags
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DILocalVariable >
Definition at line 732 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
llvm::MDNodeKeyImpl< DILocalVariable >::MDNodeKeyImpl (unsigned Tag, Metadata * Scope, StringRef Name, Metadata * File, unsigned Line, Metadata * Type, unsigned Arg, unsigned Flags) [inline]
Definition at line 742 of file LLVMContextImpl.h.
llvm::MDNodeKeyImpl< DILocalVariable >::MDNodeKeyImpl (const DILocalVariable * N) [inline]
Definition at line 746 of file LLVMContextImpl.h.
Member Function Documentation
unsigned llvm::MDNodeKeyImpl< DILocalVariable >::getHashValue () const [inline]
Definition at line 757 of file LLVMContextImpl.h.
References llvm::ARMBuildAttrs::File, and llvm::hash_combine().
bool llvm::MDNodeKeyImpl< DILocalVariable >::isKeyOf (const DILocalVariable * RHS) const [inline]
Definition at line 751 of file LLVMContextImpl.h.
References llvm::ARMBuildAttrs::File, llvm::DILocalVariable::getArg(), llvm::DILocalVariable::getFlags(), llvm::DIVariable::getLine(), llvm::DIVariable::getName(), llvm::DIVariable::getRawFile(), llvm::DIVariable::getRawScope(), llvm::DIVariable::getRawType(), and llvm::DINode::getTag().
Member Data Documentation
unsigned llvm::MDNodeKeyImpl< DILocalVariable >::Arg
Definition at line 739 of file LLVMContextImpl.h.
Metadata* llvm::MDNodeKeyImpl< DILocalVariable >::File
Definition at line 736 of file LLVMContextImpl.h.
unsigned llvm::MDNodeKeyImpl< DILocalVariable >::Flags
Definition at line 740 of file LLVMContextImpl.h.
unsigned llvm::MDNodeKeyImpl< DILocalVariable >::Line
Definition at line 737 of file LLVMContextImpl.h.
StringRef llvm::MDNodeKeyImpl< DILocalVariable >::Name
Definition at line 735 of file LLVMContextImpl.h.
Metadata* llvm::MDNodeKeyImpl< DILocalVariable >::Scope
Definition at line 734 of file LLVMContextImpl.h.
unsigned llvm::MDNodeKeyImpl< DILocalVariable >::Tag
Definition at line 733 of file LLVMContextImpl.h.
Metadata* llvm::MDNodeKeyImpl< DILocalVariable >::Type
Definition at line 738 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
LLVMContextImpl.h