LLVM: llvm::AArch64SysReg::SysRegMapper Struct Reference
llvm::AArch64SysReg::SysRegMapper Struct Reference
#include <AArch64BaseInfo.h>
Public Member Functions
SysRegMapper ()
uint32_t fromString (StringRef Name, const FeatureBitset &FeatureBits, bool &Valid) const
std::string toString (uint32_t Bits, const FeatureBitset &FeatureBits) const
Public Attributes
const
AArch64NamedImmMapper::Mapping * InstMappings
size_t NumInstMappings
Static Public Attributes
static const
AArch64NamedImmMapper::Mapping SysRegMappings []
Detailed Description
Definition at line 1201 of file AArch64BaseInfo.h.
Constructor & Destructor Documentation
llvm::AArch64SysReg::SysRegMapper::SysRegMapper () [inline]
Definition at line 1207 of file AArch64BaseInfo.h.
Member Function Documentation
uint32_t AArch64SysReg::SysRegMapper::fromString (StringRef Name, const FeatureBitset & FeatureBits, bool & Valid) const
Definition at line 810 of file AArch64BaseInfo.cpp.
References llvm::array_lengthof(), llvm::tgtok::Bits, llvm::StringRef::lower(), and llvm::Regex::match().
std::string AArch64SysReg::SysRegMapper::toString (uint32_t Bits, const FeatureBitset & FeatureBits) const
Definition at line 854 of file AArch64BaseInfo.cpp.
References llvm::array_lengthof(), and llvm::utostr().
Member Data Documentation
const AArch64NamedImmMapper::Mapping* llvm::AArch64SysReg::SysRegMapper::InstMappings
Definition at line 1204 of file AArch64BaseInfo.h.
size_t llvm::AArch64SysReg::SysRegMapper::NumInstMappings
Definition at line 1205 of file AArch64BaseInfo.h.
const AArch64NamedImmMapper::Mapping AArch64SysReg::SysRegMapper::SysRegMappings [static]
Definition at line 1202 of file AArch64BaseInfo.h.
The documentation for this struct was generated from the following files:
AArch64BaseInfo.h
AArch64BaseInfo.cpp