LLVM: llvm::MDNodeKeyImpl< DIGlobalVariable > Struct Template Reference
llvm::MDNodeKeyImpl< DIGlobalVariable > Struct Template Reference
#include <LLVMContextImpl.h>
Public Member Functions
MDNodeKeyImpl (Metadata *Scope, StringRef Name, StringRef LinkageName, Metadata *File, unsigned Line, Metadata *Type, bool IsLocalToUnit, bool IsDefinition, Metadata *Variable, Metadata *StaticDataMemberDeclaration)
MDNodeKeyImpl (const DIGlobalVariable *N)
bool isKeyOf (const DIGlobalVariable *RHS) const
unsigned getHashValue () const
Public Attributes
Metadata * Scope
StringRef Name
StringRef LinkageName
Metadata * File
unsigned Line
Metadata * Type
bool IsLocalToUnit
bool IsDefinition
Metadata * Variable
Metadata * StaticDataMemberDeclaration
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DIGlobalVariable >
Definition at line 687 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
llvm::MDNodeKeyImpl< DIGlobalVariable >::MDNodeKeyImpl (Metadata * Scope, StringRef Name, StringRef LinkageName, Metadata * File, unsigned Line, Metadata * Type, bool IsLocalToUnit, bool IsDefinition, Metadata * Variable, Metadata * StaticDataMemberDeclaration) [inline]
Definition at line 699 of file LLVMContextImpl.h.
llvm::MDNodeKeyImpl< DIGlobalVariable >::MDNodeKeyImpl (const DIGlobalVariable * N) [inline]
Definition at line 707 of file LLVMContextImpl.h.
Member Function Documentation
unsigned llvm::MDNodeKeyImpl< DIGlobalVariable >::getHashValue () const [inline]
Definition at line 725 of file LLVMContextImpl.h.
References llvm::ARMBuildAttrs::File, llvm::hash_combine(), and llvm::LinkageName.
bool llvm::MDNodeKeyImpl< DIGlobalVariable >::isKeyOf (const DIGlobalVariable * RHS) const [inline]
Definition at line 715 of file LLVMContextImpl.h.
References llvm::ARMBuildAttrs::File, llvm::DIVariable::getLine(), llvm::DIGlobalVariable::getLinkageName(), llvm::DIVariable::getName(), llvm::DIVariable::getRawFile(), llvm::DIVariable::getRawScope(), llvm::DIGlobalVariable::getRawStaticDataMemberDeclaration(), llvm::DIVariable::getRawType(), llvm::DIGlobalVariable::getRawVariable(), llvm::DIGlobalVariable::isDefinition(), llvm::DIGlobalVariable::isLocalToUnit(), and llvm::LinkageName.
Member Data Documentation
Metadata* llvm::MDNodeKeyImpl< DIGlobalVariable >::File
Definition at line 691 of file LLVMContextImpl.h.
bool llvm::MDNodeKeyImpl< DIGlobalVariable >::IsDefinition
Definition at line 695 of file LLVMContextImpl.h.
bool llvm::MDNodeKeyImpl< DIGlobalVariable >::IsLocalToUnit
Definition at line 694 of file LLVMContextImpl.h.
unsigned llvm::MDNodeKeyImpl< DIGlobalVariable >::Line
Definition at line 692 of file LLVMContextImpl.h.
StringRef llvm::MDNodeKeyImpl< DIGlobalVariable >::LinkageName
Definition at line 690 of file LLVMContextImpl.h.
StringRef llvm::MDNodeKeyImpl< DIGlobalVariable >::Name
Definition at line 689 of file LLVMContextImpl.h.
Metadata* llvm::MDNodeKeyImpl< DIGlobalVariable >::Scope
Definition at line 688 of file LLVMContextImpl.h.
Metadata* llvm::MDNodeKeyImpl< DIGlobalVariable >::StaticDataMemberDeclaration
Definition at line 697 of file LLVMContextImpl.h.
Metadata* llvm::MDNodeKeyImpl< DIGlobalVariable >::Type
Definition at line 693 of file LLVMContextImpl.h.
Metadata* llvm::MDNodeKeyImpl< DIGlobalVariable >::Variable
Definition at line 696 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
LLVMContextImpl.h