LLVM: llvm::ConstantExprKeyType Struct Reference
llvm::ConstantExprKeyType Struct Reference
#include <ConstantsContext.h>
Public Types
typedef ConstantInfo
< ConstantExpr >::TypeClass TypeClass
Public Member Functions
ConstantExprKeyType (unsigned Opcode, ArrayRef< Constant * > Ops, unsigned short SubclassData=0, unsigned short SubclassOptionalData=0, ArrayRef< unsigned > Indexes=None, Type *ExplicitTy=nullptr)
ConstantExprKeyType (ArrayRef< Constant * > Operands, const ConstantExpr *CE)
ConstantExprKeyType (const ConstantExpr *CE, SmallVectorImpl< Constant * > &Storage)
bool operator== (const ConstantExprKeyType &X) const
bool operator== (const ConstantExpr *CE) const
unsigned getHash () const
ConstantExpr * create (TypeClass *Ty) const
Public Attributes
uint8_t Opcode
uint8_t SubclassOptionalData
uint16_t SubclassData
ArrayRef< Constant * > Ops
ArrayRef< unsigned > Indexes
Type * ExplicitTy
Detailed Description
Definition at line 415 of file ConstantsContext.h.
Member Typedef Documentation
typedef ConstantInfo<ConstantExpr>::TypeClass llvm::ConstantExprKeyType::TypeClass
Definition at line 477 of file ConstantsContext.h.
Constructor & Destructor Documentation
llvm::ConstantExprKeyType::ConstantExprKeyType (unsigned Opcode, ArrayRef< Constant * > Ops, unsigned short SubclassData = 0, unsigned short SubclassOptionalData = 0, ArrayRef< unsigned > Indexes = None, Type * ExplicitTy = nullptr) [inline]
Definition at line 423 of file ConstantsContext.h.
llvm::ConstantExprKeyType::ConstantExprKeyType (ArrayRef< Constant * > Operands, const ConstantExpr * CE) [inline]
Definition at line 431 of file ConstantsContext.h.
llvm::ConstantExprKeyType::ConstantExprKeyType (const ConstantExpr * CE, SmallVectorImpl< Constant * > & Storage) [inline]
Definition at line 436 of file ConstantsContext.h.
References llvm::SmallVectorBase::empty(), llvm::User::getNumOperands(), llvm::User::getOperand(), I, Ops, and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Member Function Documentation
ConstantExpr* llvm::ConstantExprKeyType::create (TypeClass * Ty) const [inline]
Definition at line 478 of file ConstantsContext.h.
References llvm::GetElementPtrConstantExpr::Create(), ExplicitTy, ExtractElement(), llvm::ExtractValue, llvm::FCmp, llvm::Intrinsic::getType(), Indexes, llvm::InsertElement, llvm::Instruction::isCast(), llvm_unreachable, Opcode, Ops, llvm::MCID::Select, llvm::ArrayRef< T >::slice(), SubclassData, and SubclassOptionalData.
unsigned llvm::ConstantExprKeyType::getHash () const [inline]
Definition at line 471 of file ConstantsContext.h.
References llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), llvm::hash_combine(), llvm::hash_combine_range(), Indexes, Opcode, Ops, SubclassData, and SubclassOptionalData.
bool llvm::ConstantExprKeyType::operator== (const ConstantExprKeyType & X) const [inline]
Definition at line 448 of file ConstantsContext.h.
References Indexes, Opcode, Ops, SubclassData, and SubclassOptionalData.
bool llvm::ConstantExprKeyType::operator== (const ConstantExpr * CE) const [inline]
Definition at line 454 of file ConstantsContext.h.
References llvm::ConstantExpr::getIndices(), llvm::User::getNumOperands(), llvm::ConstantExpr::getOpcode(), llvm::User::getOperand(), llvm::ConstantExpr::getPredicate(), llvm::Value::getRawSubclassOptionalData(), llvm::ConstantExpr::hasIndices(), I, Indexes, llvm::ConstantExpr::isCompare(), Opcode, Ops, llvm::ArrayRef< T >::size(), SubclassData, and SubclassOptionalData.
Member Data Documentation
Type* llvm::ConstantExprKeyType::ExplicitTy
Definition at line 421 of file ConstantsContext.h.
Referenced by create().
ArrayRef<unsigned> llvm::ConstantExprKeyType::Indexes
Definition at line 420 of file ConstantsContext.h.
Referenced by create(), getHash(), and operator==().
uint8_t llvm::ConstantExprKeyType::Opcode
Definition at line 416 of file ConstantsContext.h.
Referenced by create(), getHash(), and operator==().
ArrayRef<Constant *> llvm::ConstantExprKeyType::Ops
Definition at line 419 of file ConstantsContext.h.
Referenced by ConstantExprKeyType(), create(), getHash(), and operator==().
uint16_t llvm::ConstantExprKeyType::SubclassData
Definition at line 418 of file ConstantsContext.h.
Referenced by create(), getHash(), and operator==().
uint8_t llvm::ConstantExprKeyType::SubclassOptionalData
Definition at line 417 of file ConstantsContext.h.
Referenced by create(), getHash(), and operator==().
The documentation for this struct was generated from the following file:
ConstantsContext.h