LLVM: llvm::MDNodeKeyImpl< DISubrange > Struct Template Reference
llvm::MDNodeKeyImpl< DISubrange > Struct Template Reference
#include <LLVMContextImpl.h>
Public Member Functions
MDNodeKeyImpl (int64_t Count, int64_t LowerBound)
MDNodeKeyImpl (const DISubrange *N)
bool isKeyOf (const DISubrange *RHS) const
unsigned getHashValue () const
Public Attributes
int64_t Count
int64_t LowerBound
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DISubrange >
Definition at line 276 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
llvm::MDNodeKeyImpl< DISubrange >::MDNodeKeyImpl (int64_t Count, int64_t LowerBound) [inline]
Definition at line 280 of file LLVMContextImpl.h.
llvm::MDNodeKeyImpl< DISubrange >::MDNodeKeyImpl (const DISubrange * N) [inline]
Definition at line 282 of file LLVMContextImpl.h.
Member Function Documentation
unsigned llvm::MDNodeKeyImpl< DISubrange >::getHashValue () const [inline]
Definition at line 288 of file LLVMContextImpl.h.
References llvm::hash_combine().
bool llvm::MDNodeKeyImpl< DISubrange >::isKeyOf (const DISubrange * RHS) const [inline]
Definition at line 285 of file LLVMContextImpl.h.
References llvm::DISubrange::getCount(), and llvm::DISubrange::getLowerBound().
Member Data Documentation
int64_t llvm::MDNodeKeyImpl< DISubrange >::Count
Definition at line 277 of file LLVMContextImpl.h.
int64_t llvm::MDNodeKeyImpl< DISubrange >::LowerBound
Definition at line 278 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
LLVMContextImpl.h