LLVM: llvm::LoopAccessInfo::RuntimePointerCheck Struct Reference
llvm::LoopAccessInfo::RuntimePointerCheck Struct Reference
This struct holds information about the memory runtime legality check that a group of pointers do not overlap.
#include <LoopAccessAnalysis.h>
Public Member Functions
RuntimePointerCheck ()
void reset ()
Reset the state of the pointer runtime information.
void insert (ScalarEvolution *SE, Loop *Lp, Value *Ptr, bool WritePtr, unsigned DepSetId, unsigned ASId, const ValueToValueMap &Strides)
Insert a pointer and calculate the start and end SCEVs.
bool empty () const
No run-time memory checking is necessary.
bool needsChecking (unsigned I, unsigned J, const SmallVectorImpl< int > *PtrPartition) const
Decide whether we need to issue a run-time check for pointer at index I and J to prove their independence.
bool needsAnyChecking (const SmallVectorImpl< int > *PtrPartition) const
Return true if any pointer requires run-time checking according to needsChecking.
unsigned getNumberOfChecks (const SmallVectorImpl< int > *PtrPartition) const
Returns the number of run-time checks required according to needsChecking.
void print (raw_ostream &OS, unsigned Depth=0, const SmallVectorImpl< int > *PtrPartition=nullptr) const
Print the list run-time memory checks necessary.
Public Attributes
bool Need
This flag indicates if we need to add the runtime check.
SmallVector< TrackingVH< Value >, 2 > Pointers
Holds the pointers that we need to check.
SmallVector< const SCEV *, 2 > Starts
Holds the pointer value at the beginning of the loop.
SmallVector< const SCEV *, 2 > Ends
Holds the pointer value at the end of the loop.
SmallVector< bool, 2 > IsWritePtr
Holds the information if this pointer is used for writing to memory.
SmallVector< unsigned, 2 > DependencySetId
Holds the id of the set of pointers that could be dependent because of a shared underlying object.
SmallVector< unsigned, 2 > AliasSetId
Holds the id of the disjoint alias set to which this pointer belongs.
Detailed Description
This struct holds information about the memory runtime legality check that a group of pointers do not overlap.
Definition at line 313 of file LoopAccessAnalysis.h.
Constructor & Destructor Documentation
llvm::LoopAccessInfo::RuntimePointerCheck::RuntimePointerCheck () [inline]
Definition at line 314 of file LoopAccessAnalysis.h.
Member Function Documentation
bool llvm::LoopAccessInfo::RuntimePointerCheck::empty () const [inline]
No run-time memory checking is necessary.
Definition at line 333 of file LoopAccessAnalysis.h.
References llvm::SmallVectorBase::empty(), and Pointers.
unsigned LoopAccessInfo::RuntimePointerCheck::getNumberOfChecks (const SmallVectorImpl< int > * PtrPartition) const
Returns the number of run-time checks required according to needsChecking.
Definition at line 180 of file LoopAccessAnalysis.cpp.
References I.
Referenced by llvm::LoopAccessInfo::getNumRuntimePointerChecks().
void LoopAccessInfo::RuntimePointerCheck::insert (ScalarEvolution * SE, Loop * Lp, Value * Ptr, bool WritePtr, unsigned DepSetId, unsigned ASId, const ValueToValueMap & Strides)
Insert a pointer and calculate the start and end SCEVs.
Definition at line 115 of file LoopAccessAnalysis.cpp.
References AliasSetId, DependencySetId, llvm::dyn_cast(), Ends, llvm::SCEVAddRecExpr::evaluateAtIteration(), llvm::ScalarEvolution::getBackedgeTakenCount(), llvm::SCEVAddRecExpr::getStart(), IsWritePtr, Pointers, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::replaceSymbolicStrideSCEV(), and Starts.
bool LoopAccessInfo::RuntimePointerCheck::needsAnyChecking (const SmallVectorImpl< int > * PtrPartition) const
Return true if any pointer requires run-time checking according to needsChecking.
Definition at line 192 of file LoopAccessAnalysis.cpp.
bool LoopAccessInfo::RuntimePointerCheck::needsChecking (unsigned I, unsigned J, const SmallVectorImpl< int > * PtrPartition) const
Decide whether we need to issue a run-time check for pointer at index I and J to prove their independence.
If PtrPartition is set, it contains the partition number for pointers (-1 if the pointer belongs to multiple partitions). In this case omit checks between pointers belonging to the same partition.
Definition at line 132 of file LoopAccessAnalysis.cpp.
Referenced by llvm::LoopAccessInfo::addRuntimeCheck().
void LoopAccessInfo::RuntimePointerCheck::print (raw_ostream & OS, unsigned Depth = 0, const SmallVectorImpl< int > * PtrPartition = nullptr) const
Print the list run-time memory checks necessary.
If PtrPartition is set, it contains the partition number for pointers (-1 if the pointer belongs to multiple partitions). In this case omit checks between pointers belonging to the same partition.
Definition at line 156 of file LoopAccessAnalysis.cpp.
References I, llvm::raw_ostream::indent(), and N.
Referenced by llvm::LoopAccessInfo::print().
void llvm::LoopAccessInfo::RuntimePointerCheck::reset () [inline]
Reset the state of the pointer runtime information.
Definition at line 317 of file LoopAccessAnalysis.h.
References AliasSetId, llvm::SmallVectorImpl< T >::clear(), DependencySetId, Ends, IsWritePtr, Need, Pointers, and Starts.
Member Data Documentation
SmallVector<unsigned, 2> llvm::LoopAccessInfo::RuntimePointerCheck::AliasSetId
Holds the id of the disjoint alias set to which this pointer belongs.
Definition at line 374 of file LoopAccessAnalysis.h.
Referenced by insert(), and reset().
SmallVector<unsigned, 2> llvm::LoopAccessInfo::RuntimePointerCheck::DependencySetId
Holds the id of the set of pointers that could be dependent because of a shared underlying object.
Definition at line 372 of file LoopAccessAnalysis.h.
Referenced by insert(), and reset().
SmallVector<const SCEV*, 2> llvm::LoopAccessInfo::RuntimePointerCheck::Ends
Holds the pointer value at the end of the loop.
Definition at line 367 of file LoopAccessAnalysis.h.
Referenced by llvm::LoopAccessInfo::addRuntimeCheck(), insert(), and reset().
SmallVector<bool, 2> llvm::LoopAccessInfo::RuntimePointerCheck::IsWritePtr
Holds the information if this pointer is used for writing to memory.
Definition at line 369 of file LoopAccessAnalysis.h.
Referenced by insert(), and reset().
bool llvm::LoopAccessInfo::RuntimePointerCheck::Need
This flag indicates if we need to add the runtime check.
Definition at line 361 of file LoopAccessAnalysis.h.
Referenced by llvm::LoopAccessInfo::addRuntimeCheck(), llvm::LoopAccessInfo::print(), and reset().
SmallVector<TrackingVH<Value>, 2> llvm::LoopAccessInfo::RuntimePointerCheck::Pointers
Holds the pointers that we need to check.
Definition at line 363 of file LoopAccessAnalysis.h.
Referenced by llvm::LoopAccessInfo::addRuntimeCheck(), empty(), insert(), and reset().
SmallVector<const SCEV*, 2> llvm::LoopAccessInfo::RuntimePointerCheck::Starts
Holds the pointer value at the beginning of the loop.
Definition at line 365 of file LoopAccessAnalysis.h.
Referenced by llvm::LoopAccessInfo::addRuntimeCheck(), insert(), and reset().
The documentation for this struct was generated from the following files:
LoopAccessAnalysis.h
LoopAccessAnalysis.cpp